### ISSUE TITLE
Source Plaid: does not work for Capital One Items

### ISSUE THREAD

**Issue by hbd** [airbytehq/airbyte#10257]
## Environment
- **Airbyte version**: 0.35.0-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker 
- **Source Connector and version**: Plaid v3.0
- **Severity**: Medium
- **Step where error happened**: Sync job

## Current Behavior
The Plaid source does not correctly handle a specific scenario when syncing Balance data.

A specific field must be supplied for Capital One accounts _only_.

Summarized error:
```
airbyte-worker      | HTTP response body: {
airbyte-worker      |   "display_message": null,
airbyte-worker      |   "documentation_url": "https://plaid.com/docs/?ref=error#invalid-request-errors",
airbyte-worker      |   "error_code": "INVALID_FIELD",
airbyte-worker      |   "error_message": "min_last_updated_datetime parameter required for balance on ins_128026",
airbyte-worker      |   "error_type": "INVALID_REQUEST",
airbyte-worker      |   "request_id": "...",
airbyte-worker      |   "suggested_action": null
airbyte-worker      | }
```

> [min_last_updated_datetime](https://plaid.com/docs/api/products/#accounts-balance-get-request-options-min-last-updated-datetime)
> This field is only used when the institution is ins_128026 (Capital One), in which case a value must be provided or an INVALID_REQUEST error with the code of INVALID_FIELD will be returned. For all other institutions, this field is ignored.

## Expected Behavior
Source should appropriately handle syncing the balance stream when the institution is Capital One.

## Logs

<details>
<summary>LOG</summary> 

```

airbyte-worker      |     return self.callable(self, *args, **kwargs)
airbyte-worker      |   File "/usr/local/lib/python3.7/site-packages/plaid/api/plaid_api.py", line 302, in __accounts_balance_get
airbyte-worker      |     return self.call_with_http_info(**kwargs)
airbyte-worker      |   File "/usr/local/lib/python3.7/site-packages/plaid/api_client.py", line 847, in call_with_http_info
airbyte-worker      |     collection_formats=params['collection_format'])
airbyte-worker      |   File "/usr/local/lib/python3.7/site-packages/plaid/api_client.py", line 412, in call_api
airbyte-worker      |     _check_type)
airbyte-worker      |   File "/usr/local/lib/python3.7/site-packages/plaid/api_client.py", line 200, in __call_api
airbyte-worker      |     raise e
airbyte-worker      |   File "/usr/local/lib/python3.7/site-packages/plaid/api_client.py", line 197, in __call_api
airbyte-worker      |     _request_timeout=_request_timeout)
airbyte-worker      |   File "/usr/local/lib/python3.7/site-packages/plaid/api_client.py", line 458, in request
airbyte-worker      |     body=body)
airbyte-worker      |   File "/usr/local/lib/python3.7/site-packages/plaid/rest.py", line 270, in POST
airbyte-worker      |     body=body)
airbyte-worker      |   File "/usr/local/lib/python3.7/site-packages/plaid/rest.py", line 223, in request
airbyte-worker      |     raise ApiException(http_resp=r)
airbyte-worker      | plaid.exceptions.ApiException: (400)
airbyte-worker      | Reason: Bad Request
airbyte-worker      | HTTP response headers: HTTPHeaderDict({'Server': 'nginx', 'Date': 'Tue, 08 Feb 2022 22:01:25 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '336', 'Connection': 'keep-alive', 'plaid-versio
n': '2020-09-14'})
airbyte-worker      | HTTP response body: {
airbyte-worker      |   "display_message": null,
airbyte-worker      |   "documentation_url": "https://plaid.com/docs/?ref=error#invalid-request-errors",
airbyte-worker      |   "error_code": "INVALID_FIELD",
airbyte-worker      |   "error_message": "min_last_updated_datetime parameter required for balance on ins_128026",
airbyte-worker      |   "error_type": "INVALID_REQUEST",
airbyte-worker      |   "request_id": "...",
airbyte-worker      |   "suggested_action": null
airbyte-worker      | }
airbyte-worker      |
airbyte-worker      | 2022-02-08 22:01:25 source > Finished syncing SourcePlaid
airbyte-worker      | 2022-02-08 22:01:25 source > SourcePlaid runtimes:
airbyte-worker      |
airbyte-worker      | 2022-02-08 22:01:25 source > (400)
airbyte-worker      | Reason: Bad Request
airbyte-worker      | HTTP response headers: HTTPHeaderDict({'Server': 'nginx', 'Date': 'Tue, 08 Feb 2022 22:01:25 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '336', 'Connection': 'keep-alive', 'plaid-versio
n': '2020-09-14'})
airbyte-worker      | HTTP response body: {
airbyte-worker      |   "display_message": null,
airbyte-worker      |   "documentation_url": "https://plaid.com/docs/?ref=error#invalid-request-errors",
airbyte-worker      |   "error_code": "INVALID_FIELD",
airbyte-worker      |   "error_message": "min_last_updated_datetime parameter required for balance on ins_128026",
airbyte-worker      |   "error_type": "INVALID_REQUEST",
airbyte-worker      |   "request_id": "9KAzZ88fejWmcrR",
airbyte-worker      |   "suggested_action": null
airbyte-worker      | }
airbyte-worker      | Traceback (most recent call last):
airbyte-worker      |   File "/airbyte/integration_code/main.py", line 13, in <module>
airbyte-worker      |     launch(source, sys.argv[1:])
airbyte-worker      |   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 116, in launch
airbyte-worker      |     for message in source_entrypoint.run(parsed_args):
airbyte-worker      |   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 107, in run
airbyte-worker      |     for message in generator:
airbyte-worker      |   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 112, in read
airbyte-worker      |     raise e
airbyte-worker      |   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 108, in read
airbyte-worker      |     internal_config=internal_config,
airbyte-worker      |   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 141, in _read_stream
airbyte-worker      |     for record in record_iterator:
airbyte-worker      |   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 213, in _read_full_refresh
airbyte-worker      |     for record in records:
airbyte-worker      |   File "/airbyte/integration_code/source_plaid/source.py", line 51, in read_records
airbyte-worker      |     balance_response = self.client.accounts_balance_get(AccountsBalanceGetRequest(access_token=self.access_token))
airbyte-worker      |   File "/usr/local/lib/python3.7/site-packages/plaid/api_client.py", line 769, in __call__
airbyte-worker      |     return self.callable(self, *args, **kwargs)
airbyte-worker      |   File "/usr/local/lib/python3.7/site-packages/plaid/api/plaid_api.py", line 302, in __accounts_balance_get
airbyte-worker      |     return self.call_with_http_info(**kwargs)
airbyte-worker      |   File "/usr/local/lib/python3.7/site-packages/plaid/api_client.py", line 847, in call_with_http_info
airbyte-worker      |     collection_formats=params['collection_format'])
airbyte-worker      |   File "/usr/local/lib/python3.7/site-packages/plaid/api_client.py", line 412, in call_api
airbyte-worker      |     _check_type)
airbyte-worker      |   File "/usr/local/lib/python3.7/site-packages/plaid/api_client.py", line 200, in __call_api
airbyte-worker      |     raise e
airbyte-worker      |   File "/usr/local/lib/python3.7/site-packages/plaid/api_client.py", line 197, in __call_api
airbyte-worker      |     _request_timeout=_request_timeout)
airbyte-worker      |   File "/usr/local/lib/python3.7/site-packages/plaid/api_client.py", line 458, in request
airbyte-worker      |     body=body)
airbyte-worker      |   File "/usr/local/lib/python3.7/site-packages/plaid/rest.py", line 270, in POST
airbyte-worker      |     body=body)
airbyte-worker      |   File "/usr/local/lib/python3.7/site-packages/plaid/rest.py", line 223, in request
airbyte-worker      |     raise ApiException(http_resp=r)
airbyte-worker      | plaid.exceptions.ApiException: (400)
airbyte-worker      | Reason: Bad Request
airbyte-worker      | HTTP response headers: HTTPHeaderDict({'Server': 'nginx', 'Date': 'Tue, 08 Feb 2022 22:01:25 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '336', 'Connection': 'keep-alive', 'plaid-versio
n': '2020-09-14'})
airbyte-worker      | HTTP response body: {
airbyte-worker      |   "display_message": null,
airbyte-worker      |   "documentation_url": "https://plaid.com/docs/?ref=error#invalid-request-errors",
airbyte-worker      |   "error_code": "INVALID_FIELD",
airbyte-worker      |   "error_message": "min_last_updated_datetime parameter required for balance on ins_128026",
airbyte-worker      |   "error_type": "INVALID_REQUEST",
airbyte-worker      |   "request_id": "...",
airbyte-worker      |   "suggested_action": null
airbyte-worker      | }

...

airbyte-worker      | 2022-02-08 22:01:27 ERROR i.a.w.DefaultReplicationWorker(run):158 - Sync worker failed.
airbyte-worker      | java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Source process exited with non-zero exit code 1
airbyte-worker      |   at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
airbyte-worker      |   at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
airbyte-worker      |   at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:151) ~[io.airbyte-airbyte-workers-0.35.15-alpha.jar:?]
airbyte-worker      |   at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:56) ~[io.airbyte-airbyte-workers-0.35.15-alpha.jar:?]
airbyte-worker      |   at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:171) ~[io.airbyte-airbyte-workers-0.35.15-alpha.jar:?]
airbyte-worker      |   at java.lang.Thread.run(Thread.java:833) [?:?]
airbyte-worker      |   Suppressed: io.airbyte.workers.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
airbyte-worker      |           at io.airbyte.workers.protocols.airbyte.DefaultAirbyteSource.close(DefaultAirbyteSource.java:136) ~[io.airbyte-airbyte-workers-0.35.15-alpha.jar:?]
airbyte-worker      |           at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:125) ~[io.airbyte-airbyte-workers-0.35.15-alpha.jar:?]
airbyte-worker      |           at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:56) ~[io.airbyte-airbyte-workers-0.35.15-alpha.jar:?]
airbyte-worker      |           at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:171) ~[io.airbyte-airbyte-workers-0.35.15-alpha.jar:?]
airbyte-worker      |           at java.lang.Thread.run(Thread.java:833) [?:?]
airbyte-worker      | Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Source process exited with non-zero exit code 1
airbyte-worker      |   at io.airbyte.workers.DefaultReplicationWorker.lambda$getReplicationRunnable$5(DefaultReplicationWorker.java:295) ~[io.airbyte-airbyte-workers-0.35.15-alpha.jar:?]

...

airbyte-worker      |   at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
airbyte-worker      |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
airbyte-worker      |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
airbyte-worker      |   ... 1 more
airbyte-worker      | Caused by: java.lang.RuntimeException: Source process exited with non-zero exit code 1
airbyte-worker      |   at io.airbyte.workers.DefaultReplicationWorker.lambda$getReplicationRunnable$5(DefaultReplicationWorker.java:287) ~[io.airbyte-airbyte-workers-0.35.15-alpha.jar:?]
airbyte-worker      |   at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
airbyte-worker      |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
airbyte-worker      |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
airbyte-worker      |   ... 1 more
airbyte-worker      | 2022-02-08 22:01:27 INFO i.a.w.DefaultReplicationWorker(run):217 - sync summary: io.airbyte.config.ReplicationAttemptSummary@2ea2fc5e[status=failed,recordsSynced=0,bytesSynced=0,startTime=1644357682758,endTime=164435
7687644,totalStats=io.airbyte.config.SyncStats@48f6bb3f[recordsEmitted=0,bytesEmitted=0,stateMessagesEmitted=0,recordsCommitted=0],streamStats=[]]
airbyte-worker      | 2022-02-08 22:01:27 INFO i.a.w.DefaultReplicationWorker(run):239 - Source did not output any state messages
airbyte-worker      | 2022-02-08 22:01:27 WARN i.a.w.DefaultReplicationWorker(run):250 - State capture: No state retained.
airbyte-worker      | 2022-02-08 22:01:27 INFO i.a.w.t.TemporalAttemptExecution(get):141 - Stopping cancellation check scheduling...
airbyte-worker      | 2022-02-08 22:01:27 INFO i.a.w.t.s.ReplicationActivityImpl(lambda$replicate$1):149 - sync summary: io.airbyte.config.StandardSyncOutput@10eec311[standardSyncSummary=io.airbyte.config.StandardSyncSummary@6a4636ac[stat
us=failed,recordsSynced=0,bytesSynced=0,startTime=1644357682758,endTime=1644357687644,totalStats=io.airbyte.config.SyncStats@48f6bb3f[recordsEmitted=0,bytesEmitted=0,stateMessagesEmitted=0,recordsCommitted=0],streamStats=[]],state=<null>,
outputCatalog=io.airbyte.protocol.models.ConfiguredAirbyteCatalog@277acb83[streams=[io.airbyte.protocol.models.ConfiguredAirbyteStream@5b2ac2c4[stream=io.airbyte.protocol.models.AirbyteStream@3d3a74fb[name=plaid_balance,jsonSchema={"type"
:"object","$schema":"http://json-schema.org/draft-07/schema#","required":["account_id","current"],"properties":{"limit":{"type":["number","null"]},"current":{"type":"number"},"available":{"type":["number","null"]},"account_id":{"type":"st
ring"},"iso_currency_code":{"type":["string","null"]},"unofficial_currency_code":{"type":["string","null"]}}},supportedSyncModes=[full_refresh],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[[account_id]],namesp
ace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=overwrite,primaryKey=[[account_id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@6612c6a6[stream=io.airbyte.proto
col.models.AirbyteStream@17453f34[name=plaid_transaction,jsonSchema={"type":"object","$schema":"http://json-schema.org/draft-07/schema#","required":["account_id","amount","iso_currency_code","name","transaction_id","category","date","tran
saction_type"],"properties":{"date":{"type":"string"},"name":{"type":"string"},"amount":{"type":"number"},"pending":{"type":["boolean","null"]},"category":{"type":"array","items":{"type":"string"}},"datetime":{"type":["string","null"]},"l
ocation":{"type":["object","null"],"properties":{"lat":{"type":["string","null"]},"lon":{"type":["string","null"]},"city":{"type":["string","null"]},"region":{"type":["string","null"]},"address":{"type":["string","null"]},"country":{"type
":["string","null"]},"postal_code":{"type":["string","null"]},"store_number":{"type":["string","null"]}}},"account_id":{"type":"string"},"category_id":{"type":["string","null"]},"check_number":{"type":["string","null"]},"payment_meta":{"t
ype":["object","null"],"properties":{"payee":{"type":["string","null"]},"payer":{"type":["string","null"]},"ppd_id":{"type":["string","null"]},"reason":{"type":["string","null"]},"by_order_of":{"type":["string","null"]},"payment_method":{
"type":["string","null"]},"reference_number":{"type":["string","null"]},"payment_processor":{"type":["string","null"]}}},"account_owner":{"type":["string","null"]},"merchant_name":{"type":["string","null"]},"transaction_id":{"type":"strin
g"},"authorized_date":{"type":["string","null"]},"payment_channel":{"type":["string","null"]},"transaction_code":{"type":["string","null"]},"transaction_type":{"type":"string"},"iso_currency_code":{"type":"string"},"authorized_datetime":{
"type":["string","null"]},"pending_transaction_id":{"type":["string","null"]},"unofficial_currency_code":{"type":["string","null"]},"personal_finance_category":{"type":["string","null"]}}},supportedSyncModes=[full_refresh, incremental],so
urceDefinedCursor=<null>,defaultCursorField=[date],sourceDefinedPrimaryKey=[[transaction_id]],namespace=<null>,additionalProperties={}],syncMode=incremental,cursorField=[date],destinationSyncMode=append_dedup,primaryKey=[[transaction_id]]
,additionalProperties={}]],additionalProperties={}],failures=[io.airbyte.config.FailureReason@1a74e3fa[failureOrigin=source,failureType=<null>,internalMessage=java.lang.RuntimeException: java.lang.RuntimeException: Source process exited w
ith non-zero exit code 1,externalMessage=Something went wrong within the source connector,metadata=io.airbyte.config.Metadata@7487d1e3[additionalProperties={attemptNumber=1, jobId=6587}],stacktrace=java.util.concurrent.CompletionException
: java.lang.RuntimeException: java.lang.RuntimeException: Source process exited with non-zero exit code 1
airbyte-worker      |   at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
airbyte-worker      |   at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
airbyte-worker      |   at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
airbyte-worker      |   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
airbyte-worker      |   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
airbyte-worker      |   at java.base/java.lang.Thread.run(Thread.java:833)
airbyte-worker      | Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Source process exited with non-zero exit code 1
airbyte-worker      |   at io.airbyte.workers.DefaultReplicationWorker.lambda$getReplicationRunnable$5(DefaultReplicationWorker.java:295)
airbyte-worker      |   at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
airbyte-worker      |   ... 3 more
airbyte-worker      | Caused by: java.lang.RuntimeException: Source process exited with non-zero exit code 1
airbyte-worker      |   at io.airbyte.workers.DefaultReplicationWorker.lambda$getReplicationRunnable$5(DefaultReplicationWorker.java:287)
airbyte-worker      |   ... 4 more
airbyte-worker      | ,timestamp=1644357685761]]]
```

</details>

## Steps to Reproduce
1. Create connection with a Plaid source using an access token from a Capital One Item
2. Attempt to sync the balance stream

## Are you willing to submit a PR?

Yes

**Comment by ahmed-buksh** [comment]
As mentioned [here](https://plaid.com/docs/sandbox/institutions/), CapitalOne is not supported at the sandbox. In order to reproduce this issue, it looks like to have a plaid account with CapitalOne institution enabled.

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
