### ISSUE TITLE
Server log storage on S3 should use DefaultAWSCredentialsProviderChain

### ISSUE THREAD

**Issue by adamschmidt** [airbytehq/airbyte#10570]
## Environment
- **Airbyte version**:  0.35.32-alpha
- **OS Version / Instance**: AWS EKS
- **Deployment**: Kubernetes
- **Source Connector and version**: n/a
- **Destination Connector and version**: n/a
- **Severity**: High
- **Step where error happened**: Server start

## Current Behavior
Starting the server does not use DefaultAWSCredentialsProviderChain when building the S3 client for server log storage - it assumes that `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` are set when running on AWS. These env vars don't apply when running on EKS and using IRSA.

## Expected Behavior
When running the server using a service account correctly configured with IRSA, the server should start and be able to read/write to the S3 log bucket.

## Logs

```
2022-02-23 06:57:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):788 - Using default value for environment variable AWS_ACCESS_KEY_ID: ''
2022-02-23 06:57:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):788 - Using default value for environment variable AWS_SECRET_ACCESS_KEY: ''
2022-02-23 06:57:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):788 - Using default value for environment variable JOB_MAIN_CONTAINER_CPU_REQUEST: 'null'
2022-02-23 06:57:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):788 - Using default value for environment variable JOB_MAIN_CONTAINER_CPU_LIMIT: 'null'
2022-02-23 06:57:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):788 - Using default value for environment variable JOB_MAIN_CONTAINER_MEMORY_REQUEST: 'null'
2022-02-23 06:57:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):788 - Using default value for environment variable JOB_MAIN_CONTAINER_MEMORY_LIMIT: 'null'
2022-02-23 06:57:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):788 - Using default value for environment variable JOB_KUBE_TOLERATIONS: ''
2022-02-23 06:57:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):788 - Using default value for environment variable JOB_KUBE_NODE_SELECTORS: ''
2022-02-23 06:57:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):788 - Using default value for environment variable JOB_KUBE_MAIN_CONTAINER_IMAGE_PULL_SECRET: ''
2022-02-23 06:57:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):788 - Using default value for environment variable JOB_KUBE_MAIN_CONTAINER_IMAGE_PULL_POLICY: 'IfNotPresent'
2022-02-23 06:57:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):788 - Using default value for environment variable JOB_KUBE_SOCAT_IMAGE: 'alpine/socat:1.7.4.1-r1'
2022-02-23 06:57:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):788 - Using default value for environment variable JOB_KUBE_BUSYBOX_IMAGE: 'busybox:1.28'
2022-02-23 06:57:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):788 - Using default value for environment variable JOB_KUBE_CURL_IMAGE: 'curlimages/curl:7.77.0'
2022-02-23 06:57:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):788 - Using default value for environment variable DEFAULT_WORKER_STATUS_CHECK_INTERVAL: 'PT30S'
2022-02-23 06:57:23 ERROR i.a.s.ServerApp(main):238 - Server failed
java.lang.IllegalArgumentException: null
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:131) ~[guava-31.0.1-jre.jar:?]
    at io.airbyte.config.storage.DefaultS3ClientFactory.validateBase(DefaultS3ClientFactory.java:36) ~[io.airbyte.airbyte-config-models-0.35.32-alpha.jar:?]
    at io.airbyte.config.storage.DefaultS3ClientFactory.validate(DefaultS3ClientFactory.java:31) ~[io.airbyte.airbyte-config-models-0.35.32-alpha.jar:?]
    at io.airbyte.config.storage.DefaultS3ClientFactory.<init>(DefaultS3ClientFactory.java:24) ~[io.airbyte.airbyte-config-models-0.35.32-alpha.jar:?]
    at io.airbyte.config.helpers.CloudLogs.createCloudLogClient(CloudLogs.java:44) ~[io.airbyte.airbyte-config-models-0.35.32-alpha.jar:?]
    at io.airbyte.config.helpers.LogClientSingleton.createCloudClientIfNull(LogClientSingleton.java:162) ~[io.airbyte.airbyte-config-models-0.35.32-alpha.jar:?]
    at io.airbyte.config.helpers.LogClientSingleton.setWorkspaceMdc(LogClientSingleton.java:149) ~[io.airbyte.airbyte-config-models-0.35.32-alpha.jar:?]
    at io.airbyte.server.ServerApp.getServer(ServerApp.java:146) ~[io.airbyte-airbyte-server-0.35.32-alpha.jar:?]
    at io.airbyte.server.ServerApp.main(ServerApp.java:236) [io.airbyte-airbyte-server-0.35.32-alpha.jar:?]
```

## Steps to Reproduce
1. Deploy server to EKS
2. Run under service account with IRSA

## Are you willing to submit a PR?
Yes

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 365 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.
