### ISSUE TITLE
ServiceForm doesn't work because of cyclic dependencies

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#10685]
We currently have a lot of cyclic dependencies in the code. They'll break e.g. the Storybook ServiceForm story (as documented [here](https://github.com/airbytehq/airbyte/blob/master/airbyte-webapp/docs/HowTo-ConnectionSpecification.md)).

This story will no longer be visible and you'll notice the following error on the console:

```
index.js:56 Unexpected error while loading ./views/Connector/ServiceForm/index.stories.tsx: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization
 ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization
    at Object.default (http://localhost:9009/main.iframe.bundle.js:56541:42)
    at Object../src/views/Connector/ServiceForm/index.tsx (http://localhost:9009/main.iframe.bundle.js:60805:107)
    at Object.options.factory (http://localhost:9009/runtime~main.iframe.bundle.js:637:31)
    at __webpack_require__ (http://localhost:9009/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:9009/runtime~main.iframe.bundle.js:308:21)
    at Object../src/views/Connector/ConnectorCard/ConnectorCard.tsx (http://localhost:9009/main.iframe.bundle.js:55564:70)
    at Object.options.factory (http://localhost:9009/runtime~main.iframe.bundle.js:637:31)
    at __webpack_require__ (http://localhost:9009/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:9009/runtime~main.iframe.bundle.js:308:21)
    at Object../src/views/Connector/ConnectorCard/index.tsx (http://localhost:9009/main.iframe.bundle.js:55667:72)
```

This is because of cyclic dependencies will (in specific situations) break webpack compilation. We should try to get rid of the cyclic dependencies that are breaking this story (and in general try to reduce the amount of cycle dependencies, since they always have a high chance of causing trouble at some point in some tool).

It seems the cycle dependency breaking this story is:

```
src/views/Connector/ServiceForm/ServiceForm.tsx
-> src/views/Connector/ServiceForm/FormRoot.tsx
-> src/views/Connector/ServiceForm/components/Sections/FormSection.tsx
-> src/views/Connector/ServiceForm/components/Sections/auth/AuthSection.tsx
-> src/views/Connector/ServiceForm/components/Sections/auth/AuthButton.tsx
-> src/views/Connector/ServiceForm/components/Sections/auth/useOauthFlowAdapter.tsx
-> src/hooks/services/useConnectorAuth.tsx
-> src/hooks/services/useWorkspace.tsx
-> src/hooks/services/Analytics/index.tsx
-> src/hooks/services/Analytics/TrackPageAnalytics.tsx
-> src/hooks/services/Analytics/pageNameUtils.tsx
-> src/pages/routes.tsx
-> src/pages/SourcesPage/index.tsx
-> src/pages/SourcesPage/SourcesPage.tsx
-> src/pages/SourcesPage/pages/CreateSourcePage/index.tsx
-> src/pages/SourcesPage/pages/CreateSourcePage/CreateSourcePage.tsx
-> src/pages/SourcesPage/pages/CreateSourcePage/components/SourceForm.tsx
-> src/views/Connector/ConnectorCard/index.tsx
-> src/views/Connector/ConnectorCard/ConnectorCard.tsx
-> src/views/Connector/ServiceForm/index.tsx
-> src/views/Connector/ServiceForm/ServiceForm.tsx
```

The [circular-dependency-plugin](https://github.com/aackerman/circular-dependency-plugin) can be used to find those circular dependencies.

## Workaround

To quickly get that story running, you can comment out the `export default` line here: https://github.com/timroes/airbyte/blob/master/airbyte-webapp/src/views/Connector/ServiceForm/index.tsx#L3

This will cause the app to no longer work, but the story will be working if you need it for debugging/previewing specifications.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
