### ISSUE TITLE
All connection jobs hang, requiring manual restart

### ISSUE THREAD

**Issue by lgomezm** [airbytehq/airbyte#10748]
## Environment
- **Airbyte version**:  0.35.12-alpha
- **OS Version / Instance**: GCP n2-standard-4.
- **Deployment**: Kubernetes engine on GCP.
- **Severity**: Medium
- **Step where error happened**: Sync job

## Current Behavior
We have a set of connections set up to run periodically at different intervals. A couple times it has happened, jobs start to hang and we have to manually cancel them, so that they automatically restart. If we don't do this manual work, Airbyte will cause zombie job cancellation after some time, but it usually takes longer. As our job connection base grows and we add more sources, this process will become more time-consuming and harder to complete.

The following image is a grafana screenshot of some metrics we setup to monitor the health of our Airbyte jobs. While we were restarting them, I can confirm Airbyte components like scheduler or temporal were up running:
<img width="1761" alt="Screen Shot 2022-02-28 at 11 19 47 AM" src="https://user-images.githubusercontent.com/781929/156101402-caa34805-1cc5-4259-9e7e-7177148ba072.png">

## Expected Behavior
Ideally, jobs won't hang and they will keep running as per their schedule. If, for any reason, jobs start to hang, Airbyte should trigger a process that cancels and re-runs stuck jobs earlier.

## Logs
_We haven't collected logs for this, but will do next time it happens. Promise!_

## Steps to Reproduce
1. Currently, we have the following setup (all connections share the same destination: Google Pub/Sub):
* 30 connections -> source: BigQuery - Setup to run every hour
* 105 connections -> source: Hubspot - Setup to run every 15 minutes
* 4 connections -> source: Outreach - Setup to run every 15 minutes
* 4 connections -> source: Salesloft - Setup to run every 15 minutes
2. It could happen that jobs hang, requiring manual intervention to start again.

**Comment by marcosmarxm** [comment]
Are all those connections running this in a GCP n2-standard-4 machine?

**Comment by marcosmarxm** [comment]
Maybe the jobs are not stuck and just pending status, did you check it?

**Comment by lgomezm** [comment]
I don't know if this is related to this issue, but we've seen some jobs exhausting their 3 attempts and failing with logs like this:
```
2022-03-16 10:16:41 [32mINFO[m i.a.w.w.WorkerRun(call):49 - Executing worker wrapper. Airbyte version: 0.35.12-alpha
2022-03-16 11:28:35 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):117 - Cloud storage job log path: /workspace/295259/2/logs.log
2022-03-16 11:28:35 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):120 - Executing worker wrapper. Airbyte version: 0.35.12-alpha
2022-03-16 11:28:35 [33mWARN[m i.a.d.Databases(createPostgresDatabaseWithRetryTimeout):65 - Waiting for database to become available...
2022-03-16 11:28:35 [32mINFO[m i.a.d.i.j.JobsDatabaseInstance(lambda$static$2):25 - Testing if jobs database is ready...
2022-03-16 11:28:35 [32mINFO[m i.a.d.Databases(createPostgresDatabaseWithRetryTimeout):90 - Database available!
2022-03-16 11:28:35 [32mINFO[m i.a.d.Databases(createPostgresDatabaseWithRetry):48 - Database available!
2022-03-16 11:28:35 [32mINFO[m i.a.w.DefaultReplicationWorker(run):103 - start sync worker. job id: 295259 attempt id: 2
2022-03-16 11:28:35 [32mINFO[m i.a.w.DefaultReplicationWorker(run):115 - configured sync modes: {null.sequence_states=incremental - append, null.sequences=incremental - append, null.prospects=incremental - append}
2022-03-16 11:28:35 [32mINFO[m i.a.w.p.a.DefaultAirbyteDestination(start):69 - Running destination...
2022-03-16 11:28:35 [32mINFO[m i.a.w.p.KubeProcessFactory(create):112 - Attempting to start pod = destination-pubsub-sync-295259-2-oimkx
2022-03-16 11:38:35 [1;31mERROR[m i.a.w.DefaultReplicationWorker(run):158 - Sync worker failed.
io.airbyte.workers.WorkerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "io.airbyte.workers.process.KubePortManagerSingleton.take()" is null
	at io.airbyte.workers.process.KubeProcessFactory.create(KubeProcessFactory.java:149) ~[io.airbyte-airbyte-workers-0.35.12-alpha.jar:?]
	at io.airbyte.workers.process.AirbyteIntegrationLauncher.write(AirbyteIntegrationLauncher.java:143) ~[io.airbyte-airbyte-workers-0.35.12-alpha.jar:?]
	at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.start(DefaultAirbyteDestination.java:70) ~[io.airbyte-airbyte-workers-0.35.12-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:126) ~[io.airbyte-airbyte-workers-0.35.12-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:56) ~[io.airbyte-airbyte-workers-0.35.12-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:171) ~[io.airbyte-airbyte-workers-0.35.12-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "io.airbyte.workers.process.KubePortManagerSingleton.take()" is null
	at io.airbyte.workers.process.KubeProcessFactory.create(KubeProcessFactory.java:114) ~[io.airbyte-airbyte-workers-0.35.12-alpha.jar:?]
	... 6 more
2022-03-16 11:38:35 [32mINFO[m i.a.w.DefaultReplicationWorker(run):217 - sync summary: io.airbyte.config.ReplicationAttemptSummary@116fdae5[status=failed,recordsSynced=0,bytesSynced=0,startTime=1647430115127,endTime=1647430715129,totalStats=io.airbyte.config.SyncStats@76293df9[recordsEmitted=0,bytesEmitted=0,stateMessagesEmitted=0,recordsCommitted=0],streamStats=[]]
2022-03-16 11:38:35 [32mINFO[m i.a.w.DefaultReplicationWorker(run):239 - Source did not output any state messages
2022-03-16 11:38:35 [33mWARN[m i.a.w.DefaultReplicationWorker(run):247 - State capture: No new state, falling back on input state: io.airbyte.config.State@74b25204[state={"prospects":{"updatedAt":"2021-11-10T20:11:37.000Z"},"sequences":{"updatedAt":"2021-11-10T20:12:16.000Z"},"sequence_states":{"updatedAt":"2021-11-10T20:11:37.000Z"}}]
2022-03-16 11:38:35 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):141 - Stopping cancellation check scheduling...
2022-03-16 11:38:35 [32mINFO[m i.a.w.t.s.ReplicationActivityImpl(lambda$replicate$1):149 - sync summary: io.airbyte.config.StandardSyncOutput@29eec459[standardSyncSummary=io.airbyte.config.StandardSyncSummary@6cdc7a69[status=failed,recordsSynced=0,bytesSynced=0,startTime=1647430115127,endTime=1647430715129,totalStats=io.airbyte.config.SyncStats@76293df9[recordsEmitted=0,bytesEmitted=0,stateMessagesEmitted=0,recordsCommitted=0],streamStats=[]],state=io.airbyte.config.State@74b25204[state={"prospects":{"updatedAt":"2021-11-10T20:11:37.000Z"},"sequences":{"updatedAt":"2021-11-10T20:12:16.000Z"},"sequence_states":{"updatedAt":"2021-11-10T20:11:37.000Z"}}],outputCatalog=io.airbyte.protocol.models.ConfiguredAirbyteCatalog@fcc87ee[streams=[io.airbyte.protocol.models.ConfiguredAirbyteStream@45518c7c[stream=io.airbyte.protocol.models.AirbyteStream@1ac25483[name=prospects,jsonSchema={"type":"object","$schema":"http://json-schema.org/draft-07/schema#","properties":{"id":{"type":["null","integer"]},"type":{"type":["null","string"]},"attributes":{"type":["null","object"],"properties":{"name":{"type":["null","string"]},"tags":{"type":["null","array"],"items":{"type":["null","string"]}},"score":{"type":["null","number"]},"title":{"type":["null","string"]},"degree":{"type":["null","string"]},"emails":{"type":["null","array"],"items":{"type":"string"}},"gender":{"type":["null","string"]},"region":{"type":["null","string"]},"school":{"type":["null","string"]},"source":{"type":["null","string"]},"addedAt":{"type":["null","string"],"format":"date-time"},"company":{"type":["null","string"]},"custom1":{"type":["null","string"]},"custom2":{"type":["null","string"]},"custom3":{"type":["null","string"]},"custom4":{"type":["null","string"]},"custom6":{"type":["null","string"]},"custom7":{"type":["null","string"]},"custom8":{"type":["null","string"]},"custom9":{"type":["null","string"]},"custom10":{"type":["null","string"]},"custom11":{"type":["null","string"]},"custom12":{"type":["null","string"]},"custom13":{"type":["null","string"]},"custom14":{"type":["null","string"]},"custom15":{"type":["null","string"]},"custom16":{"type":["null","string"]},"custom17":{"type":["null","string"]},"custom18":{"type":["null","string"]},"custom19":{"type":["null","string"]},"custom20":{"type":["null","string"]},"custom21":{"type":["null","string"]},"custom22":{"type":["null","string"]},"custom23":{"type":["null","string"]},"custom24":{"type":["null","string"]},"custom25":{"type":["null","string"]},"custom26":{"type":["null","string"]},"custom27":{"type":["null","string"]},"custom28":{"type":["null","string"]},"custom29":{"type":["null","string"]},"custom30":{"type":["null","string"]},"custom31":{"type":["null","string"]},"custom32":{"type":["null","string"]},"custom33":{"type":["null","string"]},"custom34":{"type":["null","string"]},"custom35":{"type":["null","string"]},"custom36":{"type":["null","string"]},"custom37":{"type":["null","string"]},"custom38":{"type":["null","string"]},"custom39":{"type":["null","string"]},"custom40":{"type":["null","string"]},"custom41":{"type":["null","string"]},"custom42":{"type":["null","string"]},"custom43":{"type":["null","string"]},"custom44":{"type":["null","string"]},"custom45":{"type":["null","string"]},"custom46":{"type":["null","string"]},"custom47":{"type":["null","string"]},"custom48":{"type":["null","string"]},"custom49":{"type":["null","string"]},"custom50":{"type":["null","string"]},"custom51":{"type":["null","string"]},"custom52":{"type":["null","string"]},"custom53":{"type":["null","string"]},"custom54":{"type":["null","string"]},"custom55":{"type":["null","string"]},"custom56":{"type":["null","string"]},"custom57":{"type":["null","string"]},"custom58":{"type":["null","string"]},"custom59":{"type":["null","string"]},"custom60":{"type":["null","string"]},"custom61":{"type":["null","string"]},"custom62":{"type":["null","string"]},"custom63":{"type":["null","string"]},"custom64":{"type":["null","string"]},"custom65":{"type":["null","string"]},"custom66":{"type":["null","string"]},"custom67":{"type":["null","string"]},"custom68":{"type":["null","string"]},"custom69":{"type":["null","string"]},"custom70":{"type":["null","string"]},"custom71":{"type":["null","string"]},"custom72":{"type":["null","string"]},"custom73":{"type":["null","string"]},"custom74":{"type":["null","string"]},"custom75":{"type":["null","string"]},"custom76":{"type":["null","string"]},"custom77":{"type":["null","string"]},"custom78":{"type":["null","string"]},"custom79":{"type":["null","string"]},"custom80":{"type":["null","string"]},"custom81":{"type":["null","string"]},"custom82":{"type":["null","string"]},"custom83":{"type":["null","string"]},"custom84":{"type":["null","string"]},"custom85":{"type":["null","string"]},"custom86":{"type":["null","string"]},"custom87":{"type":["null","string"]},"custom88":{"type":["null","string"]},"custom89":{"type":["null","string"]},"custom90":{"type":["null","string"]},"custom91":{"type":["null","string"]},"custom92":{"type":["null","string"]},"custom93":{"type":["null","string"]},"custom94":{"type":["null","string"]},"custom95":{"type":["null","string"]},"custom96":{"type":["null","string"]},"custom97":{"type":["null","string"]},"custom98":{"type":["null","string"]},"custom99":{"type":["null","string"]},"lastName":{"type":["null","string"]},"nickname":{"type":["null","string"]},"optedOut":{"type":["null","boolean"]},"quoraUrl":{"type":["null","string"]},"timeZone":{"type":["null","string"]},"createdAt":{"type":["null","string"],"format":"date-time"},"custom100":{"type":["null","string"]},"custom101":{"type":["null","string"]},"custom102":{"type":["null","string"]},"custom103":{"type":["null","string"]},"custom104":{"type":["null","string"]},"custom105":{"type":["null","string"]},"custom106":{"type":["null","string"]},"custom107":{"type":["null","string"]},"custom108":{"type":["null","string"]},"custom109":{"type":["null","string"]},"custom110":{"type":["null","string"]},"custom111":{"type":["null","string"]},"custom112":{"type":["null","string"]},"custom113":{"type":["null","string"]},"custom114":{"type":["null","string"]},"custom115":{"type":["null","string"]},"custom116":{"type":["null","string"]},"custom117":{"type":["null","string"]},"custom118":{"type":["null","string"]},"custom119":{"type":["null","string"]},"custom120":{"type":["null","string"]},"custom121":{"type":["null","string"]},"custom122":{"type":["null","string"]},"custom123":{"type":["null","string"]},"custom124":{"type":["null","string"]},"custom125":{"type":["null","string"]},"custom126":{"type":["null","string"]},"custom127":{"type":["null","string"]},"custom128":{"type":["null","string"]},"custom129":{"type":["null","string"]},"custom130":{"type":["null","string"]},"custom131":{"type":["null","string"]},"custom132":{"type":["null","string"]},"custom133":{"type":["null","string"]},"custom134":{"type":["null","string"]},"custom135":{"type":["null","string"]},"custom136":{"type":["null","string"]},"custom137":{"type":["null","string"]},"custom138":{"type":["null","string"]},"custom139":{"type":["null","string"]},"custom140":{"type":["null","string"]},"custom141":{"type":["null","string"]},"custom142":{"type":["null","string"]},"custom143":{"type":["null","string"]},"custom144":{"type":["null","string"]},"custom145":{"type":["null","string"]},"custom146":{"type":["null","string"]},"custom147":{"type":["null","string"]},"custom148":{"type":["null","string"]},"custom149":{"type":["null","string"]},"custom150":{"type":["null","string"]},"engagedAt":{"type":["null","string"],"format":"date-time"},"eventName":{"type":["null","string"]},"firstName":{"type":["null","string"]},"githubUrl":{"type":["null","string"]},"openCount":{"type":["null","integer"]},"touchedAt":{"type":["null","string"],"format":"date-time"},"trashedAt":{"type":["null","string"],"format":"date-time"},"updatedAt":{"type":["null","string"],"format":"date-time"},"addressZip":{"type":["null","string"]},"clickCount":{"type":["null","integer"]},"externalId":{"type":["null","string"]},"homePhones":{"type":["null","array"],"items":{"type":"string"}},"linkedInId":{"type":["null","string"]},"middleName":{"type":["null","string"]},"occupation":{"type":["null","string"]},"optedOutAt":{"type":["null","string"],"format":"date-time"},"replyCount":{"type":["null","integer"]},"twitterUrl":{"type":["null","string"]},"voipPhones":{"type":["null","array"],"items":{"type":"string"}},"workPhones":{"type":["null","array"],"items":{"type":"string"}},"addressCity":{"type":["null","string"]},"availableAt":{"type":["null","string"],"format":"date-time"},"dateOfBirth":{"type":["null","string"],"format":"date-time"},"facebookUrl":{"type":["null","string"]},"linkedInUrl":{"type":["null","string"]},"otherPhones":{"type":["null","array"],"items":{"type":"string"}},"specialties":{"type":["null","string"]},"websiteUrl1":{"type":["null","string"]},"websiteUrl2":{"type":["null","string"]},"websiteUrl3":{"type":["null","string"]},"addressState":{"type":["null","string"]},"angelListUrl":{"type":["null","string"]},"callOptedOut":{"type":["null","boolean"]},"callsOptedAt":{"type":["null","string"],"format":"date-time"},"campaignName":{"type":["null","string"]},"engagedScore":{"type":["null","number"]},"jobStartDate":{"type":["null","string"],"format":"date-time"},"linkedInSlug":{"type":["null","string"]},"mobilePhones":{"type":["null","array"],"items":{"type":"string"}},"timeZoneIana":{"type":["null","string"]},"addressStreet":{"type":["null","string"]},"emailOptedOut":{"type":["null","boolean"]},"emailsOptedAt":{"type":["null","string"],"format":"date-time"},"externalOwner":{"type":["null","string"]},"googlePlusUrl":{"type":["null","string"]},"personalNote1":{"type":["null","string"]},"personalNote2":{"type":["null","string"]},"sharingTeamId":{"type":["null","string"]},"addressCountry":{"type":["null","string"]},"addressStreet2":{"type":["null","string"]},"callsOptStatus":{"type":["null","string"]},"externalSource":{"type":["null","string"]},"githubUsername":{"type":["null","string"]},"graduationDate":{"type":["null","string"],"format":"date-time"},"emailsOptStatus":{"type":["null","string"]},"stackOverflowId":{"type":["null","string"]},"twitterUsername":{"type":["null","string"]},"contactHistogram":{"type":["null","array"],"items":{"type":"array","items":{"type":"integer"}}},"preferredContact":{"type":["null","string"]},"stackOverflowUrl":{"type":["null","string"]},"timeZoneInferred":{"type":["null","string"]},"linkedInConnections":{"type":["null","integer"]}},"additionalProperties":true}},"additionalProperties":true},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[attributes/properties/updatedAt],sourceDefinedPrimaryKey=[[id]],namespace=or_74b9d70a.16.ii_56fe0665,additionalProperties={}],syncMode=incremental,cursorField=[attributes/properties/updatedAt],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@15c27a80[stream=io.airbyte.protocol.models.AirbyteStream@7eda6c21[name=sequence_states,jsonSchema={"type":"object","$schema":"http://json-schema.org/draft-07/schema#","properties":{"id":{"type":["null","integer"]},"type":{"type":["null","string"]},"attributes":{"type":["null","object"],"properties":{"state":{"type":["null","string"]},"activeAt":{"type":["null","string"],"format":"date-time"},"createdAt":{"type":["null","string"],"format":"date-time"},"openCount":{"type":["null","integer"]},"repliedAt":{"type":["null","string"],"format":"date-time"},"updatedAt":{"type":["null","string"],"format":"date-time"},"clickCount":{"type":["null","integer"]},"replyCount":{"type":["null","integer"]},"bounceCount":{"type":["null","integer"]},"errorReason":{"type":["null","string"]},"optOutCount":{"type":["null","integer"]},"pauseReason":{"type":["null","string"]},"deliverCount":{"type":["null","integer"]},"failureCount":{"type":["null","integer"]},"scheduleCount":{"type":["null","integer"]},"stateChangedAt":{"type":["null","string"],"format":"date-time"},"callCompletedAt":{"type":["null","string"],"format":"date-time"},"neutralReplyCount":{"type":["null","integer"]},"negativeReplyCount":{"type":["null","integer"]},"positiveReplyCount":{"type":["null","integer"]}},"additionalProperties":true}},"additionalProperties":true},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[attributes/properties/updatedAt],sourceDefinedPrimaryKey=[[id]],namespace=or_74b9d70a.16.ii_56fe0665,additionalProperties={}],syncMode=incremental,cursorField=[attributes/properties/updatedAt],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@37a13dea[stream=io.airbyte.protocol.models.AirbyteStream@3f4f11d1[name=sequences,jsonSchema={"type":"object","$schema":"http://json-schema.org/draft-07/schema#","properties":{"id":{"type":["null","integer"]},"type":{"type":["null","string"]},"attributes":{"type":["null","object"],"properties":{"name":{"type":["null","string"]},"tags":{"type":["null","array"],"items":{"type":["null","string"]}},"locked":{"type":["null","boolean"]},"enabled":{"type":["null","boolean"]},"lockedAt":{"type":["null","string"],"format":"date-time"},"createdAt":{"type":["null","string"],"format":"date-time"},"enabledAt":{"type":["null","string"],"format":"date-time"},"openCount":{"type":["null","integer"]},"shareType":{"type":["null","string"]},"updatedAt":{"type":["null","string"],"format":"date-time"},"clickCount":{"type":["null","integer"]},"lastUsedAt":{"type":["null","string"],"format":"date-time"},"replyCount":{"type":["null","integer"]},"bounceCount":{"type":["null","integer"]},"description":{"type":["null","string"]},"optOutCount":{"type":["null","integer"]},"deliverCount":{"type":["null","integer"]},"failureCount":{"type":["null","integer"]},"sequenceType":{"type":["null","string"]},"finishOnReply":{"type":["null","boolean"]},"scheduleCount":{"type":["null","integer"]},"transactional":{"type":["null","boolean"]},"durationInDays":{"type":["null","integer"]},"maxActivations":{"type":["null","integer"]},"throttlePaused":{"type":["null","boolean"]},"throttleCapacity":{"type":["null","integer"]},"throttlePausedAt":{"type":["null","string"],"format":"date-time"},"neutralReplyCount":{"type":["null","integer"]},"sequenceStepCount":{"type":["null","integer"]},"negativeReplyCount":{"type":["null","integer"]},"positiveReplyCount":{"type":["null","integer"]},"primaryReplyAction":{"type":["null","string"]},"numRepliedProspects":{"type":["null","integer"]},"automationPercentage":{"type":["null","number"]},"scheduleIntervalType":{"type":["null","string"]},"secondaryReplyAction":{"type":["null","string"]},"numContactedProspects":{"type":["null","integer"]},"throttleMaxAddsPerDay":{"type":["null","integer"]},"primaryReplyPauseDuration":{"type":["null","integer"]},"secondaryReplyPauseDuration":{"type":["null","integer"]}},"additionalProperties":true}},"additionalProperties":true},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[attributes/properties/updatedAt],sourceDefinedPrimaryKey=[[id]],namespace=or_74b9d70a.16.ii_56fe0665,additionalProperties={}],syncMode=incremental,cursorField=[attributes/properties/updatedAt],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}]],additionalProperties={}],failures=[]]
2022-03-16 11:38:35 [32mINFO[m i.a.w.t.TemporalUtils(withBackgroundHeartbeat):176 - Stopping temporal heartbeating...
2022-03-16 11:38:35 [32mINFO[m i.a.c.p.ConfigRepository(updateConnectionState):545 - Updating connection cafbf25d-ec2f-46c0-b781-73b00e3f63f6 state: io.airbyte.config.State@10b3125d[state={"cdc":false,"streams":[{"cursor":"2022-03-16T06:55:11Z","stream_name":"main_team_members_main_teams_main_org","cursor_field":["updated_at"],"stream_namespace":"derived"}]}]
```

**Comment by hokam** [comment]
Hi @lgomezm, did you find any solution for this issue ? I am also facing the similar issue.

**Comment by prasrvenkat** [comment]
Just another update on how slow it is in certain jobs. I had to trigger a reset for a connection. Please note the difference in time from when I triggered reset (PST) and when it actually started (UTC), **it was 17mins**. I have no idea yet on where to dig to get more information on what the delay is. Would appreciate any pointers on where to look.

![image](https://user-images.githubusercontent.com/47996246/159988789-ed79216e-b376-4a38-bdd4-34fc51ab3a27.png)

**Comment by marcosmarxm** [comment]
@prasrvenkat are the jobs staying in Pending state? I saw some instances with a lot of connections getting stuck in this state. The solution was increasing the parallel job sync env var.

**Comment by prasrvenkat** [comment]
> @prasrvenkat are the jobs staying in Pending state? I saw some instances with a lot of connections getting stuck in this state. The solution was increasing the parallel job sync env var.

Are you talking about `SUBMITTER_NUM_THREADS` (already set to 500) or some other variable? More details on current configuration updated [here](https://github.com/airbytehq/airbyte/issues/10748#issuecomment-1064228370)

**Comment by marcosmarxm** [comment]
```
### APPLICATIONS ###
# Scheduler #
# Relevant to scaling.
SUBMITTER_NUM_THREADS=10

# Worker #
# Relevant to scaling.
MAX_SYNC_WORKERS=5
MAX_SPEC_WORKERS=5
MAX_CHECK_WORKERS=5
MAX_DISCOVER_WORKERS=5
```

**Comment by prasrvenkat** [comment]
> ```
> ### APPLICATIONS ###
> # Scheduler #
> # Relevant to scaling.
> SUBMITTER_NUM_THREADS=10
> 
> # Worker #
> # Relevant to scaling.
> MAX_SYNC_WORKERS=5
> MAX_SPEC_WORKERS=5
> MAX_CHECK_WORKERS=5
> MAX_DISCOVER_WORKERS=5
> ```
> 
> You can increase the SUBMITTER_NUM_THREADS and MAX_SYNC_WORKERS.

Yeah, increased no effect. Same. Check my other comment on current values for these

**Comment by octavia-squidington-iii** [comment]
Marcos Marx commented: > ```
> ### APPLICATIONS ###
> # Scheduler #
> # Relevant to scaling.
> SUBMITTER_NUM_THREADS=10
> 
> # Worker #
> # Relevant to scaling.
> MAX_SYNC_WORKERS=5
> MAX_SPEC_WORKERS=5
> MAX_CHECK_WORKERS=5
> MAX_DISCOVER_WORKERS=5
> ```
> 
> You can increase the SUBMITTER_NUM_THREADS and MAX_SYNC_WORKERS.

Yeah, increased no effect. Same. Check my other comment on current values for these

**Comment by radostyle** [comment]
Not sure if it the same issue, but I have an issue on an Amazon EKS Kubernetes deployed setup with 0.35.30-alpha version where all the scheduled jobs stop. If we kill the worker node so that it regenerates itself, then all the jobs start firing again.

**Comment by marcosmarxm** [comment]
@radostyle can you upgrade Airbyte to latest? now Airbyte uses temporal to schedule all jobs.

**Comment by marcosmarxm** [comment]
@lgomezm can you test latest Airbyte version?

**Comment by lgomezm** [comment]
@marcosmarxm We haven't seen this issue with the latest version. cc @prasrvenkat

**Comment by marcosmarxm** [comment]
I'll close for now and let me know if you need reopen

**Comment by seanglynn-thrive** [comment]
Hi @marcosmarxm ,
We're currently experiencing this issue with version `0.40` + `0.41`
I've posed in the Airbyte slack here: https://airbytehq.slack.com/archives/C021JANJ6TY/p1677680873304649

Let me know if you want me to open a fresh issue or if there is somewhere else I can write this up.

**Comment by sivankumar86** [comment]
I would  like enable autoscale on worker pods in k8s as I have most of the jobs runs on night time and airbyte is multi tanent so, want to scale out during peak and scale in when there is no/less jobs.  any pointer would be helpful ?  I have tried CPU and memory however, it is not graceful scale in and scale out is not happending as expected although , all workers ports are busy. I want to scale using following formula and gracefull shutdown of worker pods

  number of jobs/5 = number of workers.
