### ISSUE TITLE
MongoDB -> Redshift fails when doing a reset.

### ISSUE THREAD

**Issue by nthbooth-feedr** [airbytehq/airbyte#10822]
## Environment
- **Airbyte version**: 0.35.45-alpha
- **OS Version / Instance**:AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: MongoDB: 0.1.13 
- **Destination Connector and version**: Redshift: 0.3.27
- **Severity**:  High 
- **Step where error happened**:  Update connector 

## Current Behavior
Reset and sync of data fails over and over again. happens on this but also on the hubspot connector as well. 

## Expected Behavior
reset should work!

## Logs

2022-03-03 08:45:33 [32mINFO[m i.a.w.w.WorkerRun(call):49 - Executing worker wrapper. Airbyte version: 0.35.45-alpha
2022-03-03 08:45:33 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):105 - Docker volume job log path: /tmp/workspace/4571/0/logs.log
2022-03-03 08:45:33 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):110 - Executing worker wrapper. Airbyte version: 0.35.45-alpha
2022-03-03 08:45:34 [32mINFO[m i.a.w.DefaultReplicationWorker(run):103 - start sync worker. job id: 4571 attempt id: 0
2022-03-03 08:45:34 [32mINFO[m i.a.w.DefaultReplicationWorker(run):115 - configured sync modes: {prod-blue.promotions=full_refresh - overwrite, prod-blue.availabilities=full_refresh - overwrite, prod-blue.schedulednotifications=full_refresh - overwrite, prod-blue.drafts=full_refresh - overwrite, prod-blue.statustimelines=full_refresh - overwrite, prod-blue.baskets=full_refresh - overwrite, prod-blue.lives_copy=full_refresh - overwrite, prod-blue.lives=full_refresh - overwrite}
2022-03-03 08:45:34 [32mINFO[m i.a.w.p.a.DefaultAirbyteDestination(start):69 - Running destination...
2022-03-03 08:45:34 [32mINFO[m i.a.c.i.LineGobbler(voidCall):82 - Checking if airbyte/destination-redshift:0.3.27 exists...
2022-03-03 08:45:34 [32mINFO[m i.a.c.i.LineGobbler(voidCall):82 - airbyte/destination-redshift:0.3.27 was found locally.
2022-03-03 08:45:34 [32mINFO[m i.a.w.p.DockerProcessFactory(create):104 - Creating docker job ID: 4571
2022-03-03 08:45:34 [32mINFO[m i.a.w.p.DockerProcessFactory(create):155 - Preparing command: docker run --rm --init -i -w /data/4571/0 --log-driver none --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local airbyte/destination-redshift:0.3.27 write --config destination_config.json --catalog destination_catalog.json
2022-03-03 08:45:34 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getDestinationOutputRunnable$6):338 - Destination output thread started.
2022-03-03 08:45:34 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):278 - Replication thread started.
2022-03-03 08:45:34 [32mINFO[m i.a.w.DefaultReplicationWorker(run):157 - Waiting for source and destination threads to complete.
2022-03-03 08:45:34 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):304 - Total records read: 1
2022-03-03 08:45:34 [32mINFO[m i.a.w.DefaultReplicationWorker(run):162 - One of source or destination thread complete. Waiting on the other.
2022-03-03 08:45:35 [43mdestination[0m > SLF4J: Class path contains multiple SLF4J bindings.
2022-03-03 08:45:35 [43mdestination[0m > SLF4J: Found binding in [jar:file:/airbyte/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2022-03-03 08:45:35 [43mdestination[0m > SLF4J: Found binding in [jar:file:/airbyte/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2022-03-03 08:45:35 [43mdestination[0m > SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
2022-03-03 08:45:35 [43mdestination[0m > SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
2022-03-03 08:45:36 [43mdestination[0m > 2022-03-03 08:45:36 [32mINFO[m i.a.i.d.r.RedshiftDestination(main):77 - starting destination: class io.airbyte.integrations.destination.redshift.RedshiftDestination
2022-03-03 08:45:37 [43mdestination[0m > 2022-03-03 08:45:37 [32mINFO[m i.a.i.b.IntegrationCliParser(parseOptions):118 - integration args: {catalog=destination_catalog.json, write=null, config=destination_config.json}
2022-03-03 08:45:37 [43mdestination[0m > 2022-03-03 08:45:37 [32mINFO[m i.a.i.b.IntegrationRunner(run):88 - Sentry transaction event: 2991d583ce0540dc9b7c1fa112aee354
2022-03-03 08:45:37 [43mdestination[0m > 2022-03-03 08:45:37 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):106 - Running integration: io.airbyte.integrations.destination.redshift.RedshiftDestination
2022-03-03 08:45:37 [43mdestination[0m > 2022-03-03 08:45:37 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):107 - Command: WRITE
2022-03-03 08:45:37 [43mdestination[0m > 2022-03-03 08:45:37 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):108 - Integration config: IntegrationConfig{command=WRITE, configPath='destination_config.json', catalogPath='destination_catalog.json', statePath='null'}
2022-03-03 08:45:37 [43mdestination[0m > 2022-03-03 08:45:37 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword examples - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2022-03-03 08:45:37 [43mdestination[0m > 2022-03-03 08:45:37 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2022-03-03 08:45:37 [43mdestination[0m > 2022-03-03 08:45:37 [32mINFO[m i.a.i.d.j.c.SwitchingDestination(getConsumer):65 - Using destination type: COPY_S3
2022-03-03 08:45:38 [43mdestination[0m > 2022-03-03 08:45:38 [32mINFO[m i.a.i.d.b.BufferedStreamConsumer(startTracked):141 - class io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer started.
2022-03-03 08:45:38 [43mdestination[0m > 2022-03-03 08:45:38 [32mINFO[m i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):65 - Airbyte message consumer: succeeded.
2022-03-03 08:45:38 [43mdestination[0m > 2022-03-03 08:45:38 [32mINFO[m i.a.i.d.b.BufferedStreamConsumer(close):217 - executing on success close procedure.
2022-03-03 08:45:38 [43mdestination[0m > 2022-03-03 08:45:38 [32mINFO[m i.a.i.d.b.BufferedStreamConsumer(flushQueueToDestination):181 - Flushing buffer: 0 bytes
2022-03-03 08:45:38 [43mdestination[0m > 2022-03-03 08:45:38 [32mINFO[m i.a.i.d.j.c.s.S3StreamCopier(createDestinationSchema):152 - Creating schema in destination if it doesn't exist: null
2022-03-03 08:45:39 [43mdestination[0m > 2022-03-03 08:45:39 [1;31mERROR[m i.a.i.d.j.c.CopyConsumerFactory(closeAsOneTransaction):149 - Failed to finalize copy to temp table due to: java.sql.SQLException: [Amazon](500310) Invalid operation: syntax error at or near "null" 
2022-03-03 08:45:39 [43mdestination[0m > Position: 29;
2022-03-03 08:45:39 [43mdestination[0m > 2022-03-03 08:45:39 [32mINFO[m i.a.i.d.j.c.s.S3StreamCopier(removeFileAndDropTmpTable):202 - Begin cleaning _airbyte_tmp_gfm_drafts tmp table in destination.
2022-03-03 08:45:39 [43mdestination[0m > 2022-03-03 08:45:39 [1;31mERROR[m i.a.i.d.b.BufferedStreamConsumer(close):237 - Close failed.
2022-03-03 08:45:39 [43mdestination[0m > java.sql.SQLException: [Amazon](500310) Invalid operation: syntax error at or near "null" 
2022-03-03 08:45:39 [43mdestination[0m > Position: 22;
2022-03-03 08:45:39 [43mdestination[0m > 	at com.amazon.redshift.client.messages.inbound.ErrorResponse.toErrorException(Unknown Source) ~[redshift-jdbc42-no-awssdk-1.2.51.1078.jar:RedshiftJDBC_1.2.51.1078]
2022-03-03 08:45:39 [43mdestination[0m > 	at com.amazon.redshift.client.PGMessagingContext.handleErrorResponse(Unknown Source) ~[redshift-jdbc42-no-awssdk-1.2.51.1078.jar:RedshiftJDBC_1.2.51.1078]
2022-03-03 08:45:39 [43mdestination[0m > 	at com.amazon.redshift.client.PGMessagingContext.handleMessage(Unknown Source) ~[redshift-jdbc42-no-awssdk-1.2.51.1078.jar:RedshiftJDBC_1.2.51.1078]
2022-03-03 08:45:39 [43mdestination[0m > 	at com.amazon.jdbc.communications.InboundMessagesPipeline.getNextMessageOfClass(Unknown Source) ~[redshift-jdbc42-no-awssdk-1.2.51.1078.jar:RedshiftJDBC_1.2.51.1078]
2022-03-03 08:45:39 [43mdestination[0m > 	at com.amazon.redshift.client.PGMessagingContext.doMoveToNextClass(Unknown Source) ~[redshift-jdbc42-no-awssdk-1.2.51.1078.jar:RedshiftJDBC_1.2.51.1078]
2022-03-03 08:45:39 [43mdestination[0m > 	at com.amazon.redshift.client.PGMessagingContext.moveThroughMetadata(Unknown Source) ~[redshift-jdbc42-no-awssdk-1.2.51.1078.jar:RedshiftJDBC_1.2.51.1078]
2022-03-03 08:45:39 [43mdestination[0m > 	at com.amazon.redshift.client.PGMessagingContext.getNoData(Unknown Source) ~[redshift-jdbc42-no-awssdk-1.2.51.1078.jar:RedshiftJDBC_1.2.51.1078]
2022-03-03 08:45:39 [43mdestination[0m > 	at com.amazon.redshift.client.PGClient.directExecuteExtraMetadataWithMessage(Unknown Source) ~[redshift-jdbc42-no-awssdk-1.2.51.1078.jar:RedshiftJDBC_1.2.51.1078]
2022-03-03 08:45:39 [43mdestination[0m > 	at com.amazon.redshift.dataengine.PGQueryExecutor$CallableExecuteTask.call(Unknown Source) ~[redshift-jdbc42-no-awssdk-1.2.51.1078.jar:RedshiftJDBC_1.2.51.1078]
2022-03-03 08:45:39 [43mdestination[0m > 	at com.amazon.redshift.dataengine.PGQueryExecutor$CallableExecuteTask.call(Unknown Source) ~[redshift-jdbc42-no-awssdk-1.2.51.1078.jar:RedshiftJDBC_1.2.51.1078]
2022-03-03 08:45:39 [43mdestination[0m > 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
2022-03-03 08:45:39 [43mdestination[0m > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
2022-03-03 08:45:39 [43mdestination[0m > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
2022-03-03 08:45:39 [43mdestination[0m > Caused by: com.amazon.support.exceptions.ErrorException: [Amazon](500310) Invalid operation: syntax error at or near "null" 
2022-03-03 08:45:39 [43mdestination[0m > Position: 22;
2022-03-03 08:45:39 [43mdestination[0m > 	... 13 more
2022-03-03 08:45:40 [1;31mERROR[m i.a.w.DefaultReplicationWorker(run):168 - Sync worker failed.
java.util.concurrent.ExecutionException: io.airbyte.workers.DefaultReplicationWorker$DestinationException: Destination process exited with non-zero exit code 1
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:163) ~[io.airbyte-airbyte-workers-0.35.45-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:56) ~[io.airbyte-airbyte-workers-0.35.45-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:155) ~[io.airbyte-airbyte-workers-0.35.45-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
	Suppressed: io.airbyte.workers.WorkerException: Destination process exit with code 1. This warning is normal if the job was cancelled.
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.close(DefaultAirbyteDestination.java:119) ~[io.airbyte-airbyte-workers-0.35.45-alpha.jar:?]
		at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:125) ~[io.airbyte-airbyte-workers-0.35.45-alpha.jar:?]
		at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:56) ~[io.airbyte-airbyte-workers-0.35.45-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:155) ~[io.airbyte-airbyte-workers-0.35.45-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: io.airbyte.workers.DefaultReplicationWorker$DestinationException: Destination process exited with non-zero exit code 1
	at io.airbyte.workers.DefaultReplicationWorker.lambda$getDestinationOutputRunnable$6(DefaultReplicationWorker.java:353) ~[io.airbyte-airbyte-workers-0.35.45-alpha.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
2022-03-03 08:45:40 [32mINFO[m i.a.w.DefaultReplicationWorker(run):227 - sync summary: io.airbyte.config.ReplicationAttemptSummary@25a9f1[status=failed,recordsSynced=0,bytesSynced=0,startTime=1646297134053,endTime=1646297140566,totalStats=io.airbyte.config.SyncStats@7bfa799a[recordsEmitted=0,bytesEmitted=0,stateMessagesEmitted=1,recordsCommitted=0],streamStats=[]]
2022-03-03 08:45:40 [32mINFO[m i.a.w.DefaultReplicationWorker(run):247 - Source output at least one state message
2022-03-03 08:45:40 [33mWARN[m i.a.w.DefaultReplicationWorker(run):260 - State capture: No state retained.
2022-03-03 08:45:40 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):131 - Stopping cancellation check scheduling...
2022-03-03 08:45:40 [32mINFO[m i.a.w.t.s.ReplicationActivityImpl(lambda$replicate$1):147 - sync summary: io.airbyte.config.StandardSyncOutput@2da25672[standardSyncSummary=io.airbyte.config.StandardSyncSummary@5b89a14[status=failed,recordsSynced=0,bytesSynced=0,startTime=1646297134053,endTime=1646297140566,totalStats=io.airbyte.config.SyncStats@7bfa799a[recordsEmitted=0,bytesEmitted=0,stateMessagesEmitted=1,recordsCommitted=0],streamStats=[]],state=<null>,outputCatalog=io.airbyte.protocol.models.ConfiguredAirbyteCatalog@2daa6e64[streams=[io.airbyte.protocol.models.ConfiguredAirbyteStream@16c2ca15[stream=io.airbyte.protocol.models.AirbyteStream@29ec0f79[name=availabilities,jsonSchema={"type":"object","properties":{"_id":{"type":"string"},"submenus":{"type":"array"},"accountId":{"type":"string"},"serviceType":{"type":"string"},"availabilityVendorId":{"type":"number"}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[],namespace=null,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=overwrite,primaryKey=[[_id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@6845486a[stream=io.airbyte.protocol.models.AirbyteStream@16e2d248[name=baskets,jsonSchema={"type":"object","properties":{"__v":{"type":"number"},"_id":{"type":"string"},"items":{"type":"array"},"status":{"type":"string"},"userId":{"type":"number"},"options":{"type":"string"},"settings":{"type":"string"},"logistics":{"type":"string"},"serviceType":{"type":"string"},"availabilityId":{"type":"string"}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[],namespace=null,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=overwrite,primaryKey=[],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@16f020e3[stream=io.airbyte.protocol.models.AirbyteStream@5fae6283[name=drafts,jsonSchema={"type":"object","properties":{"_id":{"type":"string"},"name":{"type":"string"},"image":{"type":"string"},"isHot":{"type":"boolean"},"isVAT":{"type":"boolean"},"locked":{"type":"boolean"},"deleted":{"type":"boolean"},"mealTag":{"type":"string"},"options":{"type":"array"},"activeTo":{"type":"string"},"inReview":{"type":"boolean"},"isActive":{"type":"boolean"},"isOption":{"type":"boolean"},"legacyId":{"type":"number"},"alacalcId":{"type":"number"},"createdAt":{"type":"string"},"updatedAt":{"type":"string"},"vatBandId":{"type":"number"},"activeFrom":{"type":"string"},"cuisineTag":{"type":"string"},"isMenuItem":{"type":"boolean"},"migratedAt":{"type":"string"},"supplierId":{"type":"number"},"variations":{"type":"array"},"description":{"type":"string"},"ingredients":{"type":"string"},"protein_beef":{"type":"boolean"},"protein_fish":{"type":"boolean"},"protein_lamb":{"type":"boolean"},"protein_pork":{"type":"boolean"},"allergen_eggs":{"type":"boolean"},"allergen_fish":{"type":"boolean"},"allergen_milk":{"type":"boolean"},"allergen_none":{"type":"boolean"},"allergen_nuts":{"type":"boolean"},"dietary_halal":{"type":"boolean"},"dietary_vegan":{"type":"boolean"},"allergen_lupin":{"type":"boolean"},"dietary_kosher":{"type":"boolean"},"kitchenStation":{"type":"string"},"allergen_celery":{"type":"boolean"},"allergen_sesame":{"type":"boolean"},"dietary_lowcarb":{"type":"boolean"},"lockedTimestamp":{"type":"string"},"protein_poultry":{"type":"boolean"},"requestToDelete":{"type":"boolean"},"alacalcFetchedAt":{"type":"string"},"allergen_cereals":{"type":"boolean"},"allergen_mustard":{"type":"boolean"},"allergen_peanuts":{"type":"boolean"},"allergen_sulphur":{"type":"boolean"},"shortDescription":{"type":"string"},"allergen_molluscs":{"type":"boolean"},"allergen_soybeans":{"type":"boolean"},"protein_shellfish":{"type":"boolean"},"sub_allergen_nuts":{"type":"string"},"unlockedTimestamp":{"type":"string"},"dietary_powerplant":{"type":"boolean"},"dietary_vegetarian":{"type":"boolean"},"protein_plantbased":{"type":"boolean"},"publishedTimestamp":{"type":"string"},"dietary_highprotein":{"type":"boolean"},"allergen_crustaceans":{"type":"boolean"},"sub_allergen_cereals":{"type":"string"},"dietary_refined_sugar":{"type":"boolean"},"isFoodGoalsCalculated":{"type":"boolean"},"price_aibyte_transform":{"type":"string"},"requestDeleteTimestamp":{"type":"string"},"sentForApprovalTimestamp":{"type":"string"},"deletedAt_aibyte_transform":{"type":"string"},"macros_kj_aibyte_transform":{"type":"string"},"macros_fat_aibyte_transform":{"type":"string"},"macros_kcal_aibyte_transform":{"type":"string"},"macros_salt_aibyte_transform":{"type":"string"},"macros_carbs_aibyte_transform":{"type":"string"},"macros_fibre_aibyte_transform":{"type":"string"},"macros_sugar_aibyte_transform":{"type":"string"},"macros_protein_aibyte_transform":{"type":"string"},"macros_saturates_aibyte_transform":{"type":"string"},"macros_monounsaturates_aibyte_transform":{"type":"string"},"macros_polyunsaturates_aibyte_transform":{"type":"string"}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[],namespace=null,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=overwrite,primaryKey=[],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@1dea7704[stream=io.airbyte.protocol.models.AirbyteStream@1d9a9663[name=lives,jsonSchema={"type":"object","properties":{"_id":{"type":"string"},"name":{"type":"string"},"image":{"type":"string"},"isHot":{"type":"boolean"},"isVAT":{"type":"boolean"},"deleted":{"type":"boolean"},"mealTag":{"type":"string"},"options":{"type":"array"},"activeTo":{"type":"string"},"isActive":{"type":"boolean"},"isOption":{"type":"boolean"},"legacyId":{"type":"number"},"alacalcId":{"type":"number"},"createdAt":{"type":"string"},"updatedAt":{"type":"string"},"vatBandId":{"type":"number"},"activeFrom":{"type":"string"},"cuisineTag":{"type":"string"},"isMenuItem":{"type":"boolean"},"migratedAt":{"type":"string"},"supplierId":{"type":"number"},"variations":{"type":"array"},"description":{"type":"string"},"ingredients":{"type":"string"},"protein_beef":{"type":"boolean"},"protein_fish":{"type":"boolean"},"protein_lamb":{"type":"boolean"},"protein_pork":{"type":"boolean"},"allergen_eggs":{"type":"boolean"},"allergen_fish":{"type":"boolean"},"allergen_milk":{"type":"boolean"},"allergen_none":{"type":"boolean"},"allergen_nuts":{"type":"boolean"},"dietary_halal":{"type":"boolean"},"dietary_vegan":{"type":"boolean"},"allergen_lupin":{"type":"boolean"},"dietary_kosher":{"type":"boolean"},"kitchenStation":{"type":"string"},"allergen_celery":{"type":"boolean"},"allergen_sesame":{"type":"boolean"},"dietary_lowcarb":{"type":"boolean"},"protein_poultry":{"type":"boolean"},"requestToDelete":{"type":"boolean"},"alacalcFetchedAt":{"type":"string"},"allergen_cereals":{"type":"boolean"},"allergen_mustard":{"type":"boolean"},"allergen_peanuts":{"type":"boolean"},"allergen_sulphur":{"type":"boolean"},"shortDescription":{"type":"string"},"allergen_molluscs":{"type":"boolean"},"allergen_soybeans":{"type":"boolean"},"protein_shellfish":{"type":"boolean"},"sub_allergen_nuts":{"type":"string"},"dietary_powerplant":{"type":"boolean"},"dietary_vegetarian":{"type":"boolean"},"protein_plantbased":{"type":"boolean"},"dietary_highprotein":{"type":"boolean"},"allergen_crustaceans":{"type":"boolean"},"sub_allergen_cereals":{"type":"string"},"dietary_refined_sugar":{"type":"boolean"},"price_aibyte_transform":{"type":"string"},"requestDeleteTimestamp":{"type":"string"},"deletedAt_aibyte_transform":{"type":"string"},"macros_kj_aibyte_transform":{"type":"string"},"macros_fat_aibyte_transform":{"type":"string"},"macros_kcal_aibyte_transform":{"type":"string"},"macros_salt_aibyte_transform":{"type":"string"},"macros_carbs_aibyte_transform":{"type":"string"},"macros_fibre_aibyte_transform":{"type":"string"},"macros_sugar_aibyte_transform":{"type":"string"},"macros_protein_aibyte_transform":{"type":"string"},"macros_saturates_aibyte_transform":{"type":"string"},"macros_monounsaturates_aibyte_transform":{"type":"string"},"macros_polyunsaturates_aibyte_transform":{"type":"string"}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[],namespace=null,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=overwrite,primaryKey=[],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@a7a5a0b[stream=io.airbyte.protocol.models.AirbyteStream@26ec9bbd[name=lives_copy,jsonSchema={"type":"object","properties":{"_id":{"type":"string"},"name":{"type":"string"},"image":{"type":"string"},"isHot":{"type":"boolean"},"isVAT":{"type":"boolean"},"deleted":{"type":"boolean"},"mealTag":{"type":"string"},"options":{"type":"array"},"activeTo":{"type":"string"},"isActive":{"type":"boolean"},"isOption":{"type":"boolean"},"legacyId":{"type":"number"},"alacalcId":{"type":"number"},"createdAt":{"type":"string"},"updatedAt":{"type":"string"},"activeFrom":{"type":"string"},"cuisineTag":{"type":"string"},"isMenuItem":{"type":"boolean"},"migratedAt":{"type":"string"},"supplierId":{"type":"number"},"variations":{"type":"array"},"description":{"type":"string"},"ingredients":{"type":"string"},"protein_beef":{"type":"boolean"},"protein_fish":{"type":"boolean"},"protein_lamb":{"type":"boolean"},"protein_pork":{"type":"boolean"},"allergen_eggs":{"type":"boolean"},"allergen_fish":{"type":"boolean"},"allergen_milk":{"type":"boolean"},"allergen_none":{"type":"boolean"},"allergen_nuts":{"type":"boolean"},"dietary_halal":{"type":"boolean"},"dietary_vegan":{"type":"boolean"},"allergen_lupin":{"type":"boolean"},"dietary_kosher":{"type":"boolean"},"allergen_celery":{"type":"boolean"},"allergen_sesame":{"type":"boolean"},"dietary_lowcarb":{"type":"boolean"},"protein_poultry":{"type":"boolean"},"requestToDelete":{"type":"boolean"},"alacalcFetchedAt":{"type":"string"},"allergen_cereals":{"type":"boolean"},"allergen_mustard":{"type":"boolean"},"allergen_peanuts":{"type":"boolean"},"allergen_sulphur":{"type":"boolean"},"shortDescription":{"type":"string"},"allergen_molluscs":{"type":"boolean"},"allergen_soybeans":{"type":"boolean"},"protein_shellfish":{"type":"boolean"},"dietary_powerplant":{"type":"boolean"},"dietary_vegetarian":{"type":"boolean"},"protein_plantbased":{"type":"boolean"},"dietary_highprotein":{"type":"boolean"},"allergen_crustaceans":{"type":"boolean"},"price_aibyte_transform":{"type":"string"},"requestDeleteTimestamp":{"type":"string"},"deletedAt_aibyte_transform":{"type":"string"},"macros_kj_aibyte_transform":{"type":"string"},"macros_fat_aibyte_transform":{"type":"string"},"macros_kcal_aibyte_transform":{"type":"string"},"macros_salt_aibyte_transform":{"type":"string"},"macros_carbs_aibyte_transform":{"type":"string"},"macros_fibre_aibyte_transform":{"type":"string"},"macros_sugar_aibyte_transform":{"type":"string"},"macros_protein_aibyte_transform":{"type":"string"},"macros_saturates_aibyte_transform":{"type":"string"},"macros_monounsaturates_aibyte_transform":{"type":"string"},"macros_polyunsaturates_aibyte_transform":{"type":"string"}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[],namespace=null,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=overwrite,primaryKey=[],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@68f09a33[stream=io.airbyte.protocol.models.AirbyteStream@211030c0[name=promotions,jsonSchema={"type":"object","properties":{"__v":{"type":"number"},"_id":{"type":"string"},"name":{"type":"string"},"rules":{"type":"array"},"status":{"type":"string"},"createdAt":{"type":"string"},"updatedAt":{"type":"string"},"rewardType":{"type":"string"},"description":{"type":"string"},"communication":{"type":"array"},"termsAndConditions":{"type":"string"},"endDate_aibyte_transform":{"type":"string"},"startDate_aibyte_transform":{"type":"string"}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[],namespace=null,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=overwrite,primaryKey=[],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@79628ceb[stream=io.airbyte.protocol.models.AirbyteStream@3b11c109[name=schedulednotifications,jsonSchema={"type":"object","properties":{"__t":{"type":"string"},"__v":{"type":"number"},"_id":{"type":"string"},"date":{"type":"string"},"meal":{"type":"string"},"type":{"type":"string"},"sendTime":{"type":"string"},"accountId":{"type":"number"},"cutOffTime":{"type":"string"},"vendorName":{"type":"string"},"vendorImageUrl":{"type":"string"},"notificationStatus":{"type":"string"},"accountLocationIdArray":{"type":"array"},"ccSupplierOrderIdArray":{"type":"array"},"vendorShortDescription":{"type":"string"}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[],namespace=null,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=overwrite,primaryKey=[],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@57dce55a[stream=io.airbyte.protocol.models.AirbyteStream@776a5951[name=statustimelines,jsonSchema={"type":"object","properties":{"__v":{"type":"number"},"_id":{"type":"string"},"timeline":{"type":"array"},"promotionId":{"type":"string"}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[],namespace=null,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=overwrite,primaryKey=[],additionalProperties={}]],additionalProperties={}],failures=[io.airbyte.config.FailureReason@1a029683[failureOrigin=destination,failureType=<null>,internalMessage=io.airbyte.workers.DefaultReplicationWorker$DestinationException: Destination process exited with non-zero exit code 1,externalMessage=Something went wrong within the destination connector,metadata=io.airbyte.config.Metadata@2fae1543[additionalProperties={attemptNumber=0, jobId=4571}],stacktrace=java.util.concurrent.CompletionException: io.airbyte.workers.DefaultReplicationWorker$DestinationException: Destination process exited with non-zero exit code 1
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.airbyte.workers.DefaultReplicationWorker$DestinationException: Destination process exited with non-zero exit code 1
	at io.airbyte.workers.DefaultReplicationWorker.lambda$getDestinationOutputRunnable$6(DefaultReplicationWorker.java:353)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	... 3 more
,retryable=<null>,timestamp=1646297140565]]]
2022-03-03 08:45:40 [32mINFO[m i.a.w.t.TemporalUtils(withBackgroundHeartbeat):235 - Stopping temporal heartbeating...
```

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?
<!--- 
We accept contributions! 
Don't feel pressured, but if you want to contribute we can help you by giving some tips, 
highlighting the necessary code change or explaining any relevant point your feature will impact.
You can also send questions on #dev Slack channel.

We understand if you can't submit a PR and we're tremendously grateful
that you've already contributed by suggesting a new feature.
-->
Remove this with your answer.

**Comment by nthbooth-feedr** [comment]
Closing the schema name updated its self to null as part of the schema refresh fixing this fixed the issue
