### ISSUE TITLE
Disable custom connectors version check in bootloader

### ISSUE THREAD

**Issue by SebastienN15** [airbytehq/airbyte#10951]
## Tell us about the problem you're trying to solve
In my org, we use an AWS ECR to store custom connector images, but we don't follow semantic versioning : we use `airbyte:source-name:1.2.3` instead of `source-name:1.2.3`. The problem is, when we then try to deploy, the bootloader fails with
```
2022-03-04 14:25:15 INFO i.a.c.p.DatabaseConfigPersistence(updateConfigsFromSeed):1724 - Updating connector definitions from the seed if necessary...
2022-03-04 14:25:15 INFO i.a.c.p.DatabaseConfigPersistence(updateConfigsFromSeed):1728 - Connectors in use: [464622532012.dkr.ecr.us-east-1.amazonaws.com/dd-airbyte]
Exception in thread "main" java.lang.IllegalArgumentException: Invalid version string: destination-snowflake-0.4.1
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at io.airbyte.commons.version.AirbyteVersion.<init>(AirbyteVersion.java:33)
        ...
```

## Describe the solution you’d like
I would like to be able to **not** check custom connector version in the bootloader when deploying Airbyte. I guess a good solution would be a env variable like `CHECK_CUSTOM_CONNECTOR_VERSION` (or any better naming) that we pass to the bootloader container

## Describe the alternative you’ve considered or used
Follow semantic versioning for connectors is an option, but it's a little bit of pain for us, since we need to create a new repo in the ECR for each connector we use, and that's a lot of terraforming 

## Additional context
I don't think it really matters, but we're deploying Airbyte on k8s.

## Are you willing to submit a PR?
I don't know much about Java, and I would really appreciate if someone else could take care of this

**Comment by SebastienN15** [comment]
Seems pretty much related to this issue https://github.com/airbytehq/airbyte/issues/9921
I'll come up with a PR since it seems like a very small code change (hopefully)

**Comment by SebastienN15** [comment]
Here is the [PR](https://github.com/airbytehq/airbyte/pull/12136) !

**Comment by marcosmarxm** [comment]
Thanks @SebastienN15 I think it's a good way to handle this.

**Comment by marcosmarxm** [comment]
This is already fixed.
