### ISSUE TITLE
Migration fails due to out of inodes

### ISSUE THREAD

**Issue by codeaken** [airbytehq/airbyte#10963]
## Environment
- **Airbyte version**:  0.19.0-alpha
- **OS Version / Instance**: Debian
- **Deployment**: Docker
- **Step where error happened**: Automatic database migration

## Current Behavior
We are upgrading an old 0.19.0-alpha version to 0.32.0-alpha-patch-1. 

The migration started out fine (but very slow). After step 26->27 we got an out of disk space error. We found this strange since there is plenty of disk space left on the device. But after some research we discovered that this error could also occur if the filesystem is out of inodes. 

After running `df -ih` we saw that the filesystem that hosts the docker volumes was at 100% inode usage. We started to try and narrow down what directory was using all of the inodes by running `du --inodes -d 3 /var/lib/docker/overlay2 | sort -n | tail`. We found one volume that contained over 1 million directores named schemas<number> (like this schemas1237468246916522418).

We dont know why Airbyte creates all of these files, but it prevents us from doing the migration.

## Expected Behavior
Successful migration to 0.32.0-alpha-patch-1

## Logs
```
2022-03-09 01:40:11 INFO i.a.m.Migrate(run):92 - {workspace_app_root=/tmp/workspace/server/logs} - Migrating from version: 0.26.0-alpha to version 0.27.0-alpha.


schema = 
JOBS
STANDARD_SYNC
DESTINATION_CONNECTION
STANDARD_WORKSPACE
AIRBYTE_METADATA
STANDARD_SOURCE_DEFINITION
SOURCE_CONNECTION
STANDARD_SYNC_OPERATION
STANDARD_DESTINATION_DEFINITION
ATTEMPTS


records = 
JOBS
STANDARD_SYNC
DESTINATION_CONNECTION
STANDARD_WORKSPACE
AIRBYTE_METADATA
STANDARD_SOURCE_DEFINITION
SOURCE_CONNECTION
STANDARD_SYNC_OPERATION
STANDARD_DESTINATION_DEFINITION
ATTEMPTS
2022-03-09 01:41:21 INFO i.a.s.RunMigration(close):73 - {workspace_app_root=/tmp/workspace/server/logs} - Deleting airbyte_config_dump14796239333317549700.tar.gz
2022-03-09 01:41:21 INFO i.a.s.RunMigration(close):73 - {workspace_app_root=/tmp/workspace/server/logs} - Deleting airbyte_archive_output15736332393931269330.tar.gz
2022-03-09 01:41:21 INFO i.a.s.RunMigration(close):73 - {workspace_app_root=/tmp/workspace/server/logs} - Deleting airbyte_archive_output8624128105730958936
2022-03-09 01:41:21 ERROR i.a.s.ServerApp(runAutomaticMigration):368 - {workspace_app_root=/tmp/workspace/server/logs} - Automatic Migration failed 
java.lang.RuntimeException: java.nio.file.FileSystemException: /tmp/schemas10485864463966767386: No space left on device
	at io.airbyte.commons.json.JsonSchemas.prepareSchemas(JsonSchemas.java:58) ~[io.airbyte-airbyte-commons-0.32.0-alpha-patch-1.jar:?]
	at io.airbyte.migrate.MigrationUtils.getNameToSchemasFromResourcePath(MigrationUtils.java:49) ~[io.airbyte-airbyte-migration-0.32.0-alpha-patch-1.jar:?]
	at io.airbyte.migrate.MigrationUtils.getSchemaFromResourcePath(MigrationUtils.java:65) ~[io.airbyte-airbyte-migration-0.32.0-alpha-patch-1.jar:?]
	at io.airbyte.migrate.migrations.MigrationV0_18_0.getInputSchema(MigrationV0_18_0.java:63) ~[io.airbyte-airbyte-migration-0.32.0-alpha-patch-1.jar:?]
	at io.airbyte.migrate.migrations.MigrationV0_18_0.getOutputSchema(MigrationV0_18_0.java:69) ~[io.airbyte-airbyte-migration-0.32.0-alpha-patch-1.jar:?]
	at io.airbyte.migrate.migrations.NoOpMigration.getOutputSchema(NoOpMigration.java:36) ~[io.airbyte-airbyte-migration-0.32.0-alpha-patch-1.jar:?]
	at io.airbyte.migrate.migrations.MigrationV0_20_0.getInputSchema(MigrationV0_20_0.java:49) ~[io.airbyte-airbyte-migration-0.32.0-alpha-patch-1.jar:?]
	at io.airbyte.migrate.migrations.MigrationV0_20_0.getOutputSchema(MigrationV0_20_0.java:67) ~[io.airbyte-airbyte-migration-0.32.0-alpha-patch-1.jar:?]
	at io.airbyte.migrate.migrations.NoOpMigration.getOutputSchema(NoOpMigration.java:36) ~[io.airbyte-airbyte-migration-0.32.0-alpha-patch-1.jar:?]
	at io.airbyte.migrate.migrations.NoOpMigration.getOutputSchema(NoOpMigration.java:36) ~[io.airbyte-airbyte-migration-0.32.0-alpha-patch-1.jar:?]
	at io.airbyte.migrate.migrations.MigrationV0_23_0.getOutputSchema(MigrationV0_23_0.java:56) ~[io.airbyte-airbyte-migration-0.32.0-alpha-patch-1.jar:?]
	at io.airbyte.migrate.migrations.MigrationV0_24_0.getOutputSchema(MigrationV0_24_0.java:53) ~[io.airbyte-airbyte-migration-0.32.0-alpha-patch-1.jar:?]
	at io.airbyte.migrate.migrations.MigrationV0_25_0.getOutputSchema(MigrationV0_25_0.java:46) ~[io.airbyte-airbyte-migration-0.32.0-alpha-patch-1.jar:?]
	at io.airbyte.migrate.migrations.MigrationV0_26_0.getOutputSchema(MigrationV0_26_0.java:58) ~[io.airbyte-airbyte-migration-0.32.0-alpha-patch-1.jar:?]
	at io.airbyte.migrate.migrations.BaseMigration.getInputSchema(BaseMigration.java:26) ~[io.airbyte-airbyte-migration-0.32.0-alpha-patch-1.jar:?]
	at io.airbyte.migrate.Migrate.lambda$runMigration$1(Migrate.java:117) ~[io.airbyte-airbyte-migration-0.32.0-alpha-patch-1.jar:?]
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:441) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
	at io.airbyte.migrate.migrations.MigrationV0_27_0.migrate(MigrationV0_27_0.java:55) ~[io.airbyte-airbyte-migration-0.32.0-alpha-patch-1.jar:?]
	at io.airbyte.migrate.MigrateWithMetadata.migrate(MigrateWithMetadata.java:32) ~[io.airbyte-airbyte-migration-0.32.0-alpha-patch-1.jar:?]
	at io.airbyte.migrate.Migrate.runMigration(Migrate.java:130) ~[io.airbyte-airbyte-migration-0.32.0-alpha-patch-1.jar:?]
	at io.airbyte.migrate.Migrate.run(Migrate.java:93) ~[io.airbyte-airbyte-migration-0.32.0-alpha-patch-1.jar:?]
	at io.airbyte.migrate.MigrationRunner.run(MigrationRunner.java:57) ~[io.airbyte-airbyte-migration-0.32.0-alpha-patch-1.jar:?]
	at io.airbyte.server.RunMigration.run(RunMigration.java:60) ~[io.airbyte-airbyte-server-0.32.0-alpha-patch-1.jar:?]
	at io.airbyte.server.ServerApp.runAutomaticMigration(ServerApp.java:366) [io.airbyte-airbyte-server-0.32.0-alpha-patch-1.jar:?]
	at io.airbyte.server.ServerApp.runFileMigration(ServerApp.java:334) [io.airbyte-airbyte-server-0.32.0-alpha-patch-1.jar:?]
	at io.airbyte.server.ServerApp.getServer(ServerApp.java:228) [io.airbyte-airbyte-server-0.32.0-alpha-patch-1.jar:?]
	at io.airbyte.server.ServerApp.main(ServerApp.java:346) [io.airbyte-airbyte-server-0.32.0-alpha-patch-1.jar:?]
Caused by: java.nio.file.FileSystemException: /tmp/schemas10485864463966767386: No space left on device
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:100) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) ~[?:?]
	at java.nio.file.Files.createDirectory(Files.java:694) ~[?:?]
	at java.nio.file.TempFileHelper.create(TempFileHelper.java:135) ~[?:?]
	at java.nio.file.TempFileHelper.createTempDirectory(TempFileHelper.java:172) ~[?:?]
	at java.nio.file.Files.createTempDirectory(Files.java:1011) ~[?:?]
	at io.airbyte.commons.json.JsonSchemas.prepareSchemas(JsonSchemas.java:48) ~[io.airbyte-airbyte-commons-0.32.0-alpha-patch-1.jar:?]
	... 34 more
2022-03-09 01:41:21 INFO i.a.s.ServerApp(getServer):289 - {workspace_app_root=/tmp/workspace/server/logs} - Start serving version mismatch errors. Automatic migration either failed or didn't run
2022-03-09 01:41:21 ERROR i.a.s.v.VersionMismatchServer(getServer):50 - {workspace_app_root=/tmp/workspace/server/logs} - Version mismatch between 0.32.0-alpha-patch-1 and 0.19.0-alpha.
```

## Docker compose snippet
```
  init:
    image: airbyte/init:${VERSION}
    container_name: init
    command: /bin/sh -c "./scripts/create_mount_directories.sh /local_parent ${HACK_LOCAL_ROOT_PARENT} ${LOCAL_ROOT}"
    environment:
      - LOCAL_ROOT=${LOCAL_ROOT}
      - HACK_LOCAL_ROOT_PARENT=${HACK_LOCAL_ROOT_PARENT}
    volumes:
      - ${HACK_LOCAL_ROOT_PARENT}:/local_parent
  db:
    image: airbyte/db:${VERSION}
    container_name: airbyte-db
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      - CONFIG_DATABASE_USER=${CONFIG_DATABASE_USER:-}
      - CONFIG_DATABASE_PASSWORD=${CONFIG_DATABASE_PASSWORD:-}
      - CONFIG_DATABASE_URL=${CONFIG_DATABASE_URL:-}
    volumes:
      - db:/var/lib/postgresql/data
  scheduler:
    image: airbyte/scheduler:${VERSION}
    container_name: airbyte-scheduler
    environment:
      - WEBAPP_URL=${WEBAPP_URL}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      - CONFIG_DATABASE_USER=${CONFIG_DATABASE_USER:-}
      - CONFIG_DATABASE_PASSWORD=${CONFIG_DATABASE_PASSWORD:-}
      - CONFIG_DATABASE_URL=${CONFIG_DATABASE_URL:-}
      - RUN_DATABASE_MIGRATION_ON_STARTUP=${RUN_DATABASE_MIGRATION_ON_STARTUP}
      - WORKSPACE_ROOT=${WORKSPACE_ROOT}
      - WORKSPACE_DOCKER_MOUNT=${WORKSPACE_DOCKER_MOUNT}
      - LOCAL_ROOT=${LOCAL_ROOT}
      - LOCAL_DOCKER_MOUNT=${LOCAL_DOCKER_MOUNT}
      - CONFIG_ROOT=${CONFIG_ROOT}
      - TRACKING_STRATEGY=${TRACKING_STRATEGY}
      - AIRBYTE_VERSION=${VERSION}
      - AIRBYTE_ROLE=${AIRBYTE_ROLE:-}
      - TEMPORAL_HOST=${TEMPORAL_HOST}
      - WORKER_ENVIRONMENT=${WORKER_ENVIRONMENT}
      - S3_LOG_BUCKET=${S3_LOG_BUCKET}
      - S3_LOG_BUCKET_REGION=${S3_LOG_BUCKET_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - GCP_STORAGE_BUCKET=${GCP_STORAGE_BUCKET}
      - LOG_LEVEL=${LOG_LEVEL}
      - SUBMITTER_NUM_THREADS=${SUBMITTER_NUM_THREADS}
      - RESOURCE_CPU_REQUEST=${RESOURCE_CPU_REQUEST}
      - RESOURCE_CPU_LIMIT=${RESOURCE_CPU_LIMIT}
      - RESOURCE_MEMORY_REQUEST=${RESOURCE_MEMORY_REQUEST}
      - RESOURCE_MEMORY_LIMIT=${RESOURCE_MEMORY_LIMIT}
      - MAX_SYNC_JOB_ATTEMPTS=${MAX_SYNC_JOB_ATTEMPTS}
      - MAX_SYNC_TIMEOUT_DAYS=${MAX_SYNC_TIMEOUT_DAYS}
      - INTERNAL_API_HOST=${INTERNAL_API_HOST}
      - SECRET_PERSISTENCE=${SECRET_PERSISTENCE}
    volumes:
      - workspace:${WORKSPACE_ROOT}
      - ${LOCAL_ROOT}:${LOCAL_ROOT}
      - data:${CONFIG_ROOT}
  worker:
    image: airbyte/worker:${VERSION}
    container_name: airbyte-worker
    environment:
      - WEBAPP_URL=${WEBAPP_URL}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      - CONFIG_DATABASE_USER=${CONFIG_DATABASE_USER:-}
      - CONFIG_DATABASE_PASSWORD=${CONFIG_DATABASE_PASSWORD:-}
      - CONFIG_DATABASE_URL=${CONFIG_DATABASE_URL:-}
      - RUN_DATABASE_MIGRATION_ON_STARTUP=${RUN_DATABASE_MIGRATION_ON_STARTUP}
      - WORKSPACE_ROOT=${WORKSPACE_ROOT}
      - WORKSPACE_DOCKER_MOUNT=${WORKSPACE_DOCKER_MOUNT}
      - LOCAL_ROOT=${LOCAL_ROOT}
      - LOCAL_DOCKER_MOUNT=${LOCAL_DOCKER_MOUNT}
      - CONFIG_ROOT=${CONFIG_ROOT}
      - TRACKING_STRATEGY=${TRACKING_STRATEGY}
      - AIRBYTE_VERSION=${VERSION}
      - AIRBYTE_ROLE=${AIRBYTE_ROLE:-}
      - TEMPORAL_HOST=${TEMPORAL_HOST}
      - WORKER_ENVIRONMENT=${WORKER_ENVIRONMENT}
      - S3_LOG_BUCKET=${S3_LOG_BUCKET}
      - S3_LOG_BUCKET_REGION=${S3_LOG_BUCKET_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - GCP_STORAGE_BUCKET=${GCP_STORAGE_BUCKET}
      - LOG_LEVEL=${LOG_LEVEL}
      - SUBMITTER_NUM_THREADS=${SUBMITTER_NUM_THREADS}
      - RESOURCE_CPU_REQUEST=${RESOURCE_CPU_REQUEST}
      - RESOURCE_CPU_LIMIT=${RESOURCE_CPU_LIMIT}
      - RESOURCE_MEMORY_REQUEST=${RESOURCE_MEMORY_REQUEST}
      - RESOURCE_MEMORY_LIMIT=${RESOURCE_MEMORY_LIMIT}
      - MAX_SYNC_JOB_ATTEMPTS=${MAX_SYNC_JOB_ATTEMPTS}
      - MAX_SYNC_TIMEOUT_DAYS=${MAX_SYNC_TIMEOUT_DAYS}
      - INTERNAL_API_HOST=${INTERNAL_API_HOST}
      - SECRET_PERSISTENCE=${SECRET_PERSISTENCE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - workspace:${WORKSPACE_ROOT}
      - ${LOCAL_ROOT}:${LOCAL_ROOT}
  server:
    image: airbyte/server:${VERSION}
    container_name: airbyte-server
    environment:
      - WEBAPP_URL=${WEBAPP_URL}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      - CONFIG_DATABASE_USER=${CONFIG_DATABASE_USER:-}
      - CONFIG_DATABASE_PASSWORD=${CONFIG_DATABASE_PASSWORD:-}
      - CONFIG_DATABASE_URL=${CONFIG_DATABASE_URL:-}
      - RUN_DATABASE_MIGRATION_ON_STARTUP=${RUN_DATABASE_MIGRATION_ON_STARTUP}
      - WORKSPACE_ROOT=${WORKSPACE_ROOT}
      - CONFIG_ROOT=${CONFIG_ROOT}
      - TRACKING_STRATEGY=${TRACKING_STRATEGY}
      - AIRBYTE_VERSION=${VERSION}
      - AIRBYTE_ROLE=${AIRBYTE_ROLE:-}
      - TEMPORAL_HOST=${TEMPORAL_HOST}
      - WORKER_ENVIRONMENT=${WORKER_ENVIRONMENT}
      - S3_LOG_BUCKET=${S3_LOG_BUCKET}
      - S3_LOG_BUCKET_REGION=${S3_LOG_BUCKET_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - GCP_STORAGE_BUCKET=${GCP_STORAGE_BUCKET}
      - LOG_LEVEL=${LOG_LEVEL}
      - RESOURCE_CPU_REQUEST=${RESOURCE_CPU_REQUEST}
      - RESOURCE_CPU_LIMIT=${RESOURCE_CPU_LIMIT}
      - RESOURCE_MEMORY_REQUEST=${RESOURCE_MEMORY_REQUEST}
      - RESOURCE_MEMORY_LIMIT=${RESOURCE_MEMORY_LIMIT}
      - SECRET_PERSISTENCE=${SECRET_PERSISTENCE}
      - VERSION_0_32_0_FORCE_UPGRADE=${VERSION_0_32_0_FORCE_UPGRADE}
    volumes:
      - workspace:${WORKSPACE_ROOT}
      - data:${CONFIG_ROOT}
      - ${LOCAL_ROOT}:${LOCAL_ROOT}
  airbyte-temporal:
    image: airbyte/temporal:${VERSION}
    container_name: airbyte-temporal
    ports:
      - 7233:7233
    environment:
      - DB=postgresql
      - DB_PORT=${DATABASE_PORT}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PWD=${DATABASE_PASSWORD}
      - POSTGRES_SEEDS=${DATABASE_HOST}
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./temporal/dynamicconfig:/etc/temporal/config/dynamicconfig
```

## Steps to Reproduce
1. Install Airbyte 0.19
2. Attempt to upgrade to Airbyte 0.32.0-alpha-patch-1

**Comment by marcosmarxm** [comment]
This should be solved in latest version where migration is done in batches. I'll close this issue and let me know if it happens again to reopen it.
