### ISSUE TITLE
Scheduler gives up on temporal service silently

### ISSUE THREAD

**Issue by TSkrebe** [airbytehq/airbyte#10966]
## Environment
- **Airbyte version**:  0.35.12
- **OS Version / Instance**: linux
- **Deployment**: k8s
- **Severity**: Medium 
- **Step where error happened**:  pods restarted

## Current Behavior
Often time servers are restarted, kubernetes pods moved from one node to another. If Temporal and Scheculer services are restarted at a similar time, Scheduler seems to quickly give up on Temporal service. In turn, sync connections are not executed.

## Expected Behavior
Scheduler should try to connect to temporal indefinitely. It would also make sense to show such information through UI because we not need to look into logs to understand why syncs are not happening.

## Logs
scheduler logs:
```
2022-03-09 05:06:39 INFO i.a.s.a.SchedulerApp(main):224 - workspaceRoot = /workspace
Publish operation is approaching monitor period. Increase period or risk compromising fixed rate.
2022-03-09 05:07:03 INFO i.a.s.a.SchedulerApp(main):227 - temporalHost = airbyte-temporal-svc:7233
2022-03-09 05:07:21 INFO i.a.s.a.SchedulerApp(main):232 - Creating Job DB connection pool...
2022-03-09 05:07:23 WARN i.a.d.Databases(createPostgresDatabaseWithRetryTimeout):65 - Waiting for database to become available...
2022-03-09 05:07:25 INFO i.a.d.i.j.JobsDatabaseInstance(lambda$static$2):25 - Testing if jobs database is ready...
2022-03-09 05:07:50 INFO i.a.d.Databases(createPostgresDatabaseWithRetryTimeout):90 - Database available!
2022-03-09 05:07:50 INFO i.a.d.Databases(createPostgresDatabaseWithRetry):48 - Database available!
2022-03-09 05:07:50 INFO i.a.c.EnvConfigs(getEnvOrDefault):596 - Using default value for environment variable CONFIG_DATABASE_USER: 'airbyte'
2022-03-09 05:07:51 INFO i.a.c.EnvConfigs(getEnvOrDefault):596 - Using default value for environment variable CONFIG_DATABASE_PASSWORD: '*****'
2022-03-09 05:07:51 INFO i.a.c.EnvConfigs(getEnvOrDefault):596 - Using default value for environment variable CONFIG_DATABASE_URL: 'jdbc:postgresql://pgbouncer:5432/airbyte?prepareThreshold=0'
2022-03-09 05:07:51 WARN i.a.d.Databases(createPostgresDatabaseWithRetryTimeout):65 - Waiting for database to become available...
2022-03-09 05:07:51 INFO i.a.d.i.c.ConfigsDatabaseInstance(lambda$static$3):27 - Testing if airbyte_configs has been created and seeded...
2022-03-09 05:07:51 INFO i.a.d.Databases(createPostgresDatabaseWithRetryTimeout):90 - Database available!
2022-03-09 05:07:51 INFO i.a.d.Databases(createPostgresDatabaseWithRetry):48 - Database available!
2022-03-09 05:07:53 INFO i.a.c.EnvConfigs(getEnvOrDefault):596 - Using default value for environment variable SECRET_PERSISTENCE: 'NONE'
2022-03-09 05:07:53 INFO i.a.c.EnvConfigs(getEnvOrDefault):596 - Using default value for environment variable SECRET_PERSISTENCE: 'NONE'
2022-03-09 05:07:53 INFO i.a.c.EnvConfigs(getEnvOrDefault):596 - Using default value for environment variable SECRET_PERSISTENCE: 'NONE'
2022-03-09 05:07:53 INFO i.a.c.EnvConfigs(getEnvOrDefault):596 - Using default value for environment variable MINIMUM_WORKSPACE_RETENTION_DAYS: '1'
2022-03-09 05:07:53 INFO i.a.c.EnvConfigs(getEnvOrDefault):596 - Using default value for environment variable MAXIMUM_WORKSPACE_RETENTION_DAYS: '60'
2022-03-09 05:07:53 INFO i.a.c.EnvConfigs(getEnvOrDefault):596 - Using default value for environment variable MAXIMUM_WORKSPACE_SIZE_MB: '5000'
2022-03-09 05:07:54 INFO i.a.c.EnvConfigs(getEnvOrDefault):596 - Using default value for environment variable DEPLOYMENT_MODE: 'OSS'
2022-03-09 05:08:13 WARN i.t.i.r.GrpcSyncRetryer(retry):56 - Retrying after failure
io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 2.399817901s. [closed=[], open=[[buffered_nanos=2401851804, waiting_for_connection]]]
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262) ~[grpc-stub-1.42.1.jar:1.42.1]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243) ~[grpc-stub-1.42.1.jar:1.42.1]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156) ~[grpc-stub-1.42.1.jar:1.42.1]
	at io.grpc.health.v1.HealthGrpc$HealthBlockingStub.check(HealthGrpc.java:252) ~[grpc-services-1.42.1.jar:1.42.1]
	at io.temporal.serviceclient.WorkflowServiceStubsImpl.lambda$checkHealth$2(WorkflowServiceStubsImpl.java:282) ~[temporal-serviceclient-1.6.0.jar:?]
	at io.temporal.internal.retryer.GrpcSyncRetryer.retry(GrpcSyncRetryer.java:61) [temporal-serviceclient-1.6.0.jar:?]
	at io.temporal.internal.retryer.GrpcRetryer.retryWithResult(GrpcRetryer.java:51) [temporal-serviceclient-1.6.0.jar:?]
	at io.temporal.serviceclient.WorkflowServiceStubsImpl.checkHealth(WorkflowServiceStubsImpl.java:275) [temporal-serviceclient-1.6.0.jar:?]
	at io.temporal.serviceclient.WorkflowServiceStubsImpl.<init>(WorkflowServiceStubsImpl.java:182) [temporal-serviceclient-1.6.0.jar:?]
	at io.temporal.serviceclient.WorkflowServiceStubs.newInstance(WorkflowServiceStubs.java:51) [temporal-serviceclient-1.6.0.jar:?]
	at io.temporal.serviceclient.WorkflowServiceStubs.newInstance(WorkflowServiceStubs.java:41) [temporal-serviceclient-1.6.0.jar:?]
	at io.airbyte.workers.temporal.TemporalUtils.createTemporalService(TemporalUtils.java:50) [io.airbyte-airbyte-workers-0.35.12-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalClient.production(TemporalClient.java:69) [io.airbyte-airbyte-workers-0.35.12-alpha.jar:?]
	at io.airbyte.scheduler.app.SchedulerApp.main(SchedulerApp.java:270) [io.airbyte.airbyte-scheduler-app-0.35.12-alpha.jar:?]
Exception in thread "main" io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 4.949551595s. [closed=[], open=[[buffered_nanos=4801315757, remote_addr=airbyte-temporal-svc/10.64.2.32:7233]]]
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at io.grpc.health.v1.HealthGrpc$HealthBlockingStub.check(HealthGrpc.java:252)
	at io.temporal.serviceclient.WorkflowServiceStubsImpl.lambda$checkHealth$2(WorkflowServiceStubsImpl.java:282)
	at io.temporal.internal.retryer.GrpcSyncRetryer.retry(GrpcSyncRetryer.java:61)
	at io.temporal.internal.retryer.GrpcRetryer.retryWithResult(GrpcRetryer.java:51)
	at io.temporal.serviceclient.WorkflowServiceStubsImpl.checkHealth(WorkflowServiceStubsImpl.java:275)
	at io.temporal.serviceclient.WorkflowServiceStubsImpl.<init>(WorkflowServiceStubsImpl.java:182)
	at io.temporal.serviceclient.WorkflowServiceStubs.newInstance(WorkflowServiceStubs.java:51)
	at io.temporal.serviceclient.WorkflowServiceStubs.newInstance(WorkflowServiceStubs.java:41)
	at io.airbyte.workers.temporal.TemporalUtils.createTemporalService(TemporalUtils.java:50)
	at io.airbyte.workers.temporal.TemporalClient.production(TemporalClient.java:69)
	at io.airbyte.scheduler.app.SchedulerApp.main(SchedulerApp.java:270)
```

## Steps to Reproduce
1. restart scheduler/temporal services at the same time

**Comment by marcosmarxm** [comment]
Please upgrade to latest
