### ISSUE TITLE
Sync jobs stop when Scheduler crashes

### ISSUE THREAD

**Issue by jedwards-gc** [airbytehq/airbyte#11079]
## Environment
- **Airbyte version**:  0.35.12-alpha
- **OS Version / Instance**: AWS EC2/Amazon Linux 2
- **Deployment**: Docker
- **Source Connector and version**: n/a
- **Destination Connector and version**: n/a
- **Severity**: Medium
- **Step where error happened**: Sync job

## Current Behavior
First, I am *not* using the "bundled" config database (e.g. the `db` Docker service), I am using an external database for the Airbyte config. When the database hosting the Airbyte config is unavailable the `scheduler` service crashes and sync jobs stop running.

I noticed the docker-compose.yaml contains
```
  scheduler:
    image: airbyte/scheduler:${VERSION}
    logging: *default-logging
    container_name: airbyte-scheduler
    restart: unless-stopped
```
However it doesn't seem to be restarting for me. It seems like even though it has crashed, Docker thinks it's still up (but it's actually crashed):
```
[ec2-user@ip-172-x-x-x airbyte]$ docker-compose ps scheduler
      Name                     Command               State   Ports
------------------------------------------------------------------
airbyte-scheduler   /bin/bash -c ${APPLICATION ...   Up
[ec2-user@ip-172-x-x-x airbyte]$ docker-compose logs --tail 40 scheduler
Attaching to airbyte-scheduler
airbyte-scheduler   | 	at java.lang.Thread.run(Thread.java:833) [?:?]
airbyte-scheduler   | Caused by: org.postgresql.util.PSQLException: Connection to example.us-west-2.rds.amazonaws.com:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
airbyte-scheduler   | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:301) ~[postgresql-42.3.1.jar:42.3.1]
airbyte-scheduler   | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51) ~[postgresql-42.3.1.jar:42.3.1]
airbyte-scheduler   | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:225) ~[postgresql-42.3.1.jar:42.3.1]
airbyte-scheduler   | 	at org.postgresql.Driver.makeConnection(Driver.java:466) ~[postgresql-42.3.1.jar:42.3.1]
airbyte-scheduler   | 	at org.postgresql.Driver.connect(Driver.java:265) ~[postgresql-42.3.1.jar:42.3.1]
airbyte-scheduler   | 	at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:55) ~[commons-dbcp2-2.7.0.jar:2.7.0]
airbyte-scheduler   | 	at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:355) ~[commons-dbcp2-2.7.0.jar:2.7.0]
airbyte-scheduler   | 	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:889) ~[commons-pool2-2.7.0.jar:2.7.0]
airbyte-scheduler   | 	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:424) ~[commons-pool2-2.7.0.jar:2.7.0]
airbyte-scheduler   | 	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:349) ~[commons-pool2-2.7.0.jar:2.7.0]
airbyte-scheduler   | 	at org.apache.commons.dbcp2.PoolingDataSource.getConnection(PoolingDataSource.java:134) ~[commons-dbcp2-2.7.0.jar:2.7.0]
airbyte-scheduler   | 	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:753) ~[commons-dbcp2-2.7.0.jar:2.7.0]
airbyte-scheduler   | 	at org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:83) ~[jooq-3.13.4.jar:?]
airbyte-scheduler   | 	... 16 more
airbyte-scheduler   | Caused by: java.net.ConnectException: Connection refused
airbyte-scheduler   | 	at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
airbyte-scheduler   | 	at sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[?:?]
airbyte-scheduler   | 	at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549) ~[?:?]
airbyte-scheduler   | 	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[?:?]
airbyte-scheduler   | 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
airbyte-scheduler   | 	at java.net.Socket.connect(Socket.java:633) ~[?:?]
airbyte-scheduler   | 	at org.postgresql.core.PGStream.createSocket(PGStream.java:238) ~[postgresql-42.3.1.jar:42.3.1]
airbyte-scheduler   | 	at org.postgresql.core.PGStream.<init>(PGStream.java:98) ~[postgresql-42.3.1.jar:42.3.1]
airbyte-scheduler   | 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:100) ~[postgresql-42.3.1.jar:42.3.1]
airbyte-scheduler   | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:215) ~[postgresql-42.3.1.jar:42.3.1]
airbyte-scheduler   | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51) ~[postgresql-42.3.1.jar:42.3.1]
airbyte-scheduler   | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:225) ~[postgresql-42.3.1.jar:42.3.1]
airbyte-scheduler   | 	at org.postgresql.Driver.makeConnection(Driver.java:466) ~[postgresql-42.3.1.jar:42.3.1]
airbyte-scheduler   | 	at org.postgresql.Driver.connect(Driver.java:265) ~[postgresql-42.3.1.jar:42.3.1]
airbyte-scheduler   | 	at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:55) ~[commons-dbcp2-2.7.0.jar:2.7.0]
airbyte-scheduler   | 	at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:355) ~[commons-dbcp2-2.7.0.jar:2.7.0]
airbyte-scheduler   | 	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:889) ~[commons-pool2-2.7.0.jar:2.7.0]
airbyte-scheduler   | 	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:424) ~[commons-pool2-2.7.0.jar:2.7.0]
airbyte-scheduler   | 	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:349) ~[commons-pool2-2.7.0.jar:2.7.0]
airbyte-scheduler   | 	at org.apache.commons.dbcp2.PoolingDataSource.getConnection(PoolingDataSource.java:134) ~[commons-dbcp2-2.7.0.jar:2.7.0]
airbyte-scheduler   | 	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:753) ~[commons-dbcp2-2.7.0.jar:2.7.0]
airbyte-scheduler   | 	at org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:83) ~[jooq-3.13.4.jar:?]
airbyte-scheduler   | 	... 16 more
```

## Expected Behavior
The `scheduler` should recover when the database becomes available again, and resume syncing.

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```
airbyte-scheduler  | 2022-03-10 23:08:01 INFO i.a.w.w.WorkerRun(call):49 - Executing worker wrapper. Airbyte version: 0.35.12-alpha
airbyte-scheduler  | 2022-03-10 23:12:08 ERROR i.a.s.a.JobSubmitter(run):81 - Job Submitter Error
airbyte-scheduler  | org.jooq.exception.DataAccessException: Error getting connection from data source org.apache.commons.dbcp2.BasicDataSource@24638cac
airbyte-scheduler  | 	at org.jooq_3.13.4.POSTGRES.debug(Unknown Source) ~[?:?]
airbyte-scheduler  | 	at org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:86) ~[jooq-3.13.4.jar:?]
airbyte-scheduler  | 	at org.jooq.impl.DefaultExecuteContext.connection(DefaultExecuteContext.java:647) ~[jooq-3.13.4.jar:?]
airbyte-scheduler  | 	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:334) ~[jooq-3.13.4.jar:?]
airbyte-scheduler  | 	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:354) ~[jooq-3.13.4.jar:?]
airbyte-scheduler  | 	at org.jooq.impl.DefaultDSLContext.fetch(DefaultDSLContext.java:892) ~[jooq-3.13.4.jar:?]
airbyte-scheduler  | 	at io.airbyte.scheduler.persistence.DefaultJobPersistence.lambda$getNextJob$21(DefaultJobPersistence.java:410) ~[io.airbyte.airbyte-scheduler-persistence-0.35.12-alpha.jar:?]
airbyte-scheduler  | 	at io.airbyte.db.Database.query(Database.java:27) ~[io.airbyte.airbyte-db-lib-0.35.12-alpha.jar:?]
airbyte-scheduler  | 	at io.airbyte.db.ExceptionWrappingDatabase.query(ExceptionWrappingDatabase.java:23) ~[io.airbyte.airbyte-db-lib-0.35.12-alpha.jar:?]
airbyte-scheduler  | 	at io.airbyte.scheduler.persistence.DefaultJobPersistence.getNextJob(DefaultJobPersistence.java:409) ~[io.airbyte.airbyte-scheduler-persistence-0.35.12-alpha.jar:?]
airbyte-scheduler  | 	at io.airbyte.scheduler.app.JobSubmitter.run(JobSubmitter.java:74) ~[io.airbyte.airbyte-scheduler-app-0.35.12-alpha.jar:?]
airbyte-scheduler  | 	at io.airbyte.scheduler.app.SchedulerApp.lambda$start$1(SchedulerApp.java:157) ~[io.airbyte.airbyte-scheduler-app-0.35.12-alpha.jar:?]
airbyte-scheduler  | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
airbyte-scheduler  | 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
airbyte-scheduler  | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
airbyte-scheduler  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
airbyte-scheduler  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
airbyte-scheduler  | 	at java.lang.Thread.run(Thread.java:833) [?:?]
airbyte-scheduler  | Caused by: org.postgresql.util.PSQLException: FATAL: the database system is in recovery mode
airbyte-scheduler  | 	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:623) ~[postgresql-42.3.1.jar:42.3.1]
airbyte-scheduler  | 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:163) ~[postgresql-42.3.1.jar:42.3.1]
airbyte-scheduler  | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:215) ~[postgresql-42.3.1.jar:42.3.1]
airbyte-scheduler  | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51) ~[postgresql-42.3.1.jar:42.3.1]
airbyte-scheduler  | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:225) ~[postgresql-42.3.1.jar:42.3.1]
airbyte-scheduler  | 	at org.postgresql.Driver.makeConnection(Driver.java:466) ~[postgresql-42.3.1.jar:42.3.1]
airbyte-scheduler  | 	at org.postgresql.Driver.connect(Driver.java:265) ~[postgresql-42.3.1.jar:42.3.1]
airbyte-scheduler  | 	at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:55) ~[commons-dbcp2-2.7.0.jar:2.7.0]
airbyte-scheduler  | 	at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:355) ~[commons-dbcp2-2.7.0.jar:2.7.0]
airbyte-scheduler  | 	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:889) ~[commons-pool2-2.7.0.jar:2.7.0]
airbyte-scheduler  | 	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:424) ~[commons-pool2-2.7.0.jar:2.7.0]
airbyte-scheduler  | 	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:349) ~[commons-pool2-2.7.0.jar:2.7.0]
airbyte-scheduler  | 	at org.apache.commons.dbcp2.PoolingDataSource.getConnection(PoolingDataSource.java:134) ~[commons-dbcp2-2.7.0.jar:2.7.0]
airbyte-scheduler  | 	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:753) ~[commons-dbcp2-2.7.0.jar:2.7.0]
airbyte-scheduler  | 	at org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:83) ~[jooq-3.13.4.jar:?]
airbyte-scheduler  | 	... 16 more
airbyte-scheduler  | 2022-03-10 23:12:13 ERROR i.a.s.a.JobSubmitter(run):81 - Job Submitter Error
airbyte-scheduler  | org.jooq.exception.DataAccessException: Error getting connection from data source org.apache.commons.dbcp2.BasicDataSource@24638cac
airbyte-scheduler  | 	at org.jooq_3.13.4.POSTGRES.debug(Unknown Source) ~[?:?]
airbyte-scheduler  | 	at org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:86) ~[jooq-3.13.4.jar:?]
airbyte-scheduler  | 	at org.jooq.impl.DefaultExecuteContext.connection(DefaultExecuteContext.java:647) ~[jooq-3.13.4.jar:?]
airbyte-scheduler  | 	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:334) ~[jooq-3.13.4.jar:?]
airbyte-scheduler  | 	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:354) ~[jooq-3.13.4.jar:?]
airbyte-scheduler  | 	at org.jooq.impl.DefaultDSLContext.fetch(DefaultDSLContext.java:892) ~[jooq-3.13.4.jar:?]
airbyte-scheduler  | 	at io.airbyte.scheduler.persistence.DefaultJobPersistence.lambda$getNextJob$21(DefaultJobPersistence.java:410) ~[io.airbyte.airbyte-scheduler-persistence-0.35.12-alpha.jar:?]
airbyte-scheduler  | 	at io.airbyte.db.Database.query(Database.java:27) ~[io.airbyte.airbyte-db-lib-0.35.12-alpha.jar:?]
airbyte-scheduler  | 	at io.airbyte.db.ExceptionWrappingDatabase.query(ExceptionWrappingDatabase.java:23) ~[io.airbyte.airbyte-db-lib-0.35.12-alpha.jar:?]
airbyte-scheduler  | 	at io.airbyte.scheduler.persistence.DefaultJobPersistence.getNextJob(DefaultJobPersistence.java:409) ~[io.airbyte.airbyte-scheduler-persistence-0.35.12-alpha.jar:?]
airbyte-scheduler  | 	at io.airbyte.scheduler.app.JobSubmitter.run(JobSubmitter.java:74) ~[io.airbyte.airbyte-scheduler-app-0.35.12-alpha.jar:?]
airbyte-scheduler  | 	at io.airbyte.scheduler.app.SchedulerApp.lambda$start$1(SchedulerApp.java:157) ~[io.airbyte.airbyte-scheduler-app-0.35.12-alpha.jar:?]
airbyte-scheduler  | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
airbyte-scheduler  | 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
airbyte-scheduler  | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
airbyte-scheduler  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
airbyte-scheduler  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
airbyte-scheduler  | 	at java.lang.Thread.run(Thread.java:833) [?:?]
airbyte-scheduler  | Caused by: org.postgresql.util.PSQLException: FATAL: the database system is in recovery mode
airbyte-scheduler  | 	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:623) ~[postgresql-42.3.1.jar:42.3.1]
airbyte-scheduler  | 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:163) ~[postgresql-42.3.1.jar:42.3.1]
airbyte-scheduler  | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:215) ~[postgresql-42.3.1.jar:42.3.1]
airbyte-scheduler  | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51) ~[postgresql-42.3.1.jar:42.3.1]
airbyte-scheduler  | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:225) ~[postgresql-42.3.1.jar:42.3.1]
airbyte-scheduler  | 	at org.postgresql.Driver.makeConnection(Driver.java:466) ~[postgresql-42.3.1.jar:42.3.1]
airbyte-scheduler  | 	at org.postgresql.Driver.connect(Driver.java:265) ~[postgresql-42.3.1.jar:42.3.1]
airbyte-scheduler  | 	at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:55) ~[commons-dbcp2-2.7.0.jar:2.7.0]
airbyte-scheduler  | 	at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:355) ~[commons-dbcp2-2.7.0.jar:2.7.0]
airbyte-scheduler  | 	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:889) ~[commons-pool2-2.7.0.jar:2.7.0]
airbyte-scheduler  | 	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:424) ~[commons-pool2-2.7.0.jar:2.7.0]
airbyte-scheduler  | 	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:349) ~[commons-pool2-2.7.0.jar:2.7.0]
airbyte-scheduler  | 	at org.apache.commons.dbcp2.PoolingDataSource.getConnection(PoolingDataSource.java:134) ~[commons-dbcp2-2.7.0.jar:2.7.0]
airbyte-scheduler  | 	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:753) ~[commons-dbcp2-2.7.0.jar:2.7.0]
airbyte-scheduler  | 	at org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:83) ~[jooq-3.13.4.jar:?]
airbyte-scheduler  | 	... 16 more
```

</details>

## Steps to Reproduce
1. Start Airbyte scheduler
2. Do something to cause it to crash (i.e. shut down the config database)
3. Airbyte scheduler crashes
4. Sync jobs no longer run

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by georgekaz** [comment]
We recently experienced the same on 0.35.45-alpha. Postgresql was unavailable temporarily and the scheduler didn't run any jobs again until after it was restarted.

**Comment by shmf** [comment]
Working with georgekaz - we were able to start jobs manually, which were competing successfully, but none of them was starting when they were due. Frontend was showing no issues and even in the pods showed no errors.
All jobs started all together after scheduler pod was restarted.

**Comment by evantahler** [comment]
Closing as current versions of Airbyte do not use the scheduler - we use Temporal now job orchestration.
