### ISSUE TITLE
Oracle - Discover schema fails when database have hundreds of tables or views

### ISSUE THREAD

**Issue by luisvilla1000** [airbytehq/airbyte#11113]
## Environment
- **Airbyte version**:  0.35.53-alpha
- **OS Version / Instance**:  AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Oracle 0.3.14
- **Destination Connector and version**: S3 0.1.10
- **Severity**: High
- **Step where error happened**: Setup new connection

## Current Behavior

I have an Oracle database with a schema with hundreds of tables and views.

When I try to configure a new connection, the process aborts without any log error or message (only message showed is: "Failed to fetch schema. Please try again").  The only error shown in the logs is below.

I can't find another log or message that can give more information about the error.

Note: the error is always displayed about 70 seconds after the process has started.  I suspect it may be a connection timeout.

## Expected Behavior
Fetch the schema or on error show a descriptive error

## Logs
Logs are not displayed in the graphical interface.  I got them from the docker-compose log.

<details>
<summary>LOG</summary> 

```

airbyte-worker      | 2022-03-14 16:06:57 WARN c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword existingJavaType - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
airbyte-worker      | 2022-03-14 16:06:57 INFO i.a.w.t.TemporalAttemptExecution(get):131 - Stopping cancellation check scheduling...
airbyte-server      | 2022-03-14 16:07:13 INFO i.a.s.RequestLogger(filter):95 - REQ 172.20.0.8 POST 200 /api/v1/web_backend/connections/get - {"connectionId":"8fac660e-8618-42bc-83e4-a7b284675f01","withRefreshedCatalog":true}
airbyte-server      | Mar 14, 2022 4:10:23 PM org.glassfish.jersey.server.ServerRuntime$Responder writeResponse
airbyte-server      | SEVERE: An I/O error has occurred while writing a response message entity to the container output stream.
airbyte-server      | org.glassfish.jersey.server.internal.process.MappableException: org.eclipse.jetty.io.EofException
airbyte-server      |   at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:67)
airbyte-server      |   at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
airbyte-server      |   at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1116)
airbyte-server      |   at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:638)
airbyte-server      |   at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:371)
airbyte-server      |   at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:361)
airbyte-server      |   at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:256)

```

</details>

## Steps to Reproduce
1. Configure a Oracle source with hundreds of tables
2. Configure a any destination (I tried with S3, Redshift and MySQL)
3. Setup a Connection Oracle with a destination

## Are you willing to submit a PR?
No

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 365 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.
