### ISSUE TITLE
Docker setup broken

### ISSUE THREAD

**Issue by tino** [airbytehq/airbyte#11277]
## Environment
- **Airbyte version**:  VERSION=0.35.58-alpha
- **OS Version / Instance**: Ubuntu 20.04.3 LTS
- **Deployment**: Docker (compose)
- **Severity**: Very Low / Low / Medium / High / **Critical**
- **Step where error happened**: **Deploy** / Sync job / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
Server fails to start. Frontend shows: "Cannot reach server. The server may still be starting up."

## Expected Behavior
It should start normally I'd hoped :)

## Logs
<details>
<summary>Server Logs</summary> 

```
...
airbyte-server | 2022-03-20 17:08:08 INFO o.f.c.i.l.s.Slf4jLog(info):49 - Flyway Community Edition 7.14.0 by Redgate
airbyte-server | 2022-03-20 17:08:08 INFO o.f.c.i.l.s.Slf4jLog(info):49 - Database: jdbc:postgresql://db:5432/airbyte (PostgreSQL 13.6)
airbyte-server | 2022-03-20 17:08:08 INFO i.a.d.i.MinimumFlywayMigrationVersionCheck(assertMigrations):76 - Current database migration version 0.35.56.001
airbyte-server | 2022-03-20 17:08:08 INFO i.a.d.i.MinimumFlywayMigrationVersionCheck(assertMigrations):77 - Minimum Flyway version required 0.35.15.001
airbyte-server | 2022-03-20 17:08:08 INFO i.a.s.ServerApp(assertDatabasesReady):137 - Checking jobs database flyway migration version..
airbyte-server | 2022-03-20 17:08:08 INFO i.a.d.i.MinimumFlywayMigrationVersionCheck(assertDatabase):42 - Waiting for database...
airbyte-server | 2022-03-20 17:08:08 WARN i.a.d.Databases(createPostgresDatabaseWithRetryTimeout):74 - Waiting for database to become available...
airbyte-server | 2022-03-20 17:08:08 INFO i.a.d.i.BaseDatabaseInstance(lambda$isDatabaseConnected$5):127 - Testing airbyte jobs database connection...
airbyte-server | 2022-03-20 17:08:08 INFO i.a.d.Databases(createPostgresDatabaseWithRetryTimeout):99 - Database available!
airbyte-server | 2022-03-20 17:08:08 WARN i.a.d.Databases(createPostgresDatabaseWithRetryTimeout):74 - Waiting for database to become available...
airbyte-server | 2022-03-20 17:08:08 INFO i.a.d.i.j.JobsDatabaseInstance(lambda$static$2):25 - Testing if jobs database is ready...
airbyte-server | 2022-03-20 17:08:08 INFO i.a.d.Databases(createPostgresDatabaseWithRetryTimeout):99 - Database available!
airbyte-server | 2022-03-20 17:08:08 INFO i.a.d.Databases(createPostgresDatabaseWithRetry):57 - Database available!
airbyte-server | 2022-03-20 17:08:08 INFO i.a.c.EnvConfigs(getEnvOrDefault):871 - Using default value for environment variable JOBS_DATABASE_INITIALIZATION_TIMEOUT_MS: '60000'
airbyte-server | 2022-03-20 17:08:08 INFO o.f.c.i.l.s.Slf4jLog(info):49 - Flyway Community Edition 7.14.0 by Redgate
airbyte-server | 2022-03-20 17:08:08 INFO o.f.c.i.l.s.Slf4jLog(info):49 - Database: jdbc:postgresql://db:5432/airbyte (PostgreSQL 13.6)
airbyte-server | 2022-03-20 17:08:08 INFO i.a.d.i.MinimumFlywayMigrationVersionCheck(assertMigrations):76 - Current database migration version 0.35.40.001
airbyte-server | 2022-03-20 17:08:08 INFO i.a.d.i.MinimumFlywayMigrationVersionCheck(assertMigrations):77 - Minimum Flyway version required 0.29.15.001
airbyte-server | 2022-03-20 17:08:08 INFO i.a.s.ServerApp(getServer):161 - Creating Staged Resource folder...
airbyte-server | 2022-03-20 17:08:08 INFO i.a.s.ServerApp(getServer):164 - Creating config repository...
airbyte-server | 2022-03-20 17:08:08 WARN i.a.d.Databases(createPostgresDatabaseWithRetryTimeout):74 - Waiting for database to become available...
airbyte-server | 2022-03-20 17:08:08 INFO i.a.d.i.c.ConfigsDatabaseInstance(lambda$static$3):28 - Testing if airbyte_configs has been created and seeded...
airbyte-server | 2022-03-20 17:08:08 INFO i.a.d.Databases(createPostgresDatabaseWithRetryTimeout):99 - Database available!
airbyte-server | 2022-03-20 17:08:08 INFO i.a.d.Databases(createPostgresDatabaseWithRetry):57 - Database available!
airbyte-server | 2022-03-20 17:08:08 INFO i.a.c.EnvConfigs(getEnvOrDefault):871 - Using default value for environment variable SECRET_PERSISTENCE: 'NONE'
airbyte-server | 2022-03-20 17:08:08 INFO i.a.c.EnvConfigs(getEnvOrDefault):871 - Using default value for environment variable SECRET_PERSISTENCE: 'NONE'
airbyte-server | 2022-03-20 17:08:08 INFO i.a.c.EnvConfigs(getEnvOrDefault):871 - Using default value for environment variable SECRET_PERSISTENCE: 'NONE'
airbyte-server | 2022-03-20 17:08:08 INFO i.a.s.ServerApp(getServer):175 - Creating jobs persistence...
airbyte-server | 2022-03-20 17:08:08 WARN i.a.d.Databases(createPostgresDatabaseWithRetryTimeout):74 - Waiting for database to become available...
airbyte-server | 2022-03-20 17:08:08 INFO i.a.d.i.j.JobsDatabaseInstance(lambda$static$2):25 - Testing if jobs database is ready...
airbyte-server | 2022-03-20 17:08:08 INFO i.a.d.Databases(createPostgresDatabaseWithRetryTimeout):99 - Database available!
airbyte-server | 2022-03-20 17:08:08 INFO i.a.d.Databases(createPostgresDatabaseWithRetry):57 - Database available!
airbyte-server | 2022-03-20 17:08:08 INFO i.a.c.EnvConfigs(getEnvOrDefault):871 - Using default value for environment variable DEPLOYMENT_MODE: 'OSS'
airbyte-server | 2022-03-20 17:08:08 INFO i.a.c.EnvConfigs(getEnvOrDefault):871 - Using default value for environment variable WORKER_ENVIRONMENT: 'DOCKER'
airbyte-server | 2022-03-20 17:08:09 INFO i.a.c.EnvConfigs(getEnvOrDefault):871 - Using default value for environment variable ACTIVITY_MAX_ATTEMPT: '10'
airbyte-server | 2022-03-20 17:08:09 INFO i.a.c.EnvConfigs(getEnvOrDefault):871 - Using default value for environment variable ACTIVITY_MAX_TIMEOUT_SECOND: '30'
airbyte-server | 2022-03-20 17:08:09 INFO i.a.c.EnvConfigs(getEnvOrDefault):871 - Using default value for environment variable TEMPORAL_HISTORY_RETENTION_IN_DAYS: '30'
airbyte-server | 2022-03-20 17:08:09 INFO i.a.w.t.TemporalUtils(getTemporalClientWhenConnected):174 - Waiting for temporal server...
airbyte-server | 2022-03-20 17:08:09 WARN i.a.w.t.TemporalUtils(getTemporalClientWhenConnected):185 - Waiting for default namespace to be initialized in temporal...
airbyte-server | 2022-03-20 17:08:17 WARN i.t.i.r.GrpcSyncRetryer(retry):56 - Retrying after failure
airbyte-server | io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: Deadline exceeded after 4.978502629s. 
airbyte-server |        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262) ~[grpc-stub-1.44.1.jar:1.44.1]
airbyte-server |        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243) ~[grpc-stub-1.44.1.jar:1.44.1]
airbyte-server |        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156) ~[grpc-stub-1.44.1.jar:1.44.1]
airbyte-server |        at io.grpc.health.v1.HealthGrpc$HealthBlockingStub.check(HealthGrpc.java:252) ~[grpc-services-1.44.1.jar:1.44.1]
airbyte-server |        at io.temporal.serviceclient.WorkflowServiceStubsImpl.lambda$checkHealth$2(WorkflowServiceStubsImpl.java:286) ~[temporal-serviceclient-1.8.1.jar:?]
airbyte-server |        at io.temporal.internal.retryer.GrpcSyncRetryer.retry(GrpcSyncRetryer.java:61) ~[temporal-serviceclient-1.8.1.jar:?]
airbyte-server |        at io.temporal.internal.retryer.GrpcRetryer.retryWithResult(GrpcRetryer.java:51) ~[temporal-serviceclient-1.8.1.jar:?]
airbyte-server |        at io.temporal.serviceclient.WorkflowServiceStubsImpl.checkHealth(WorkflowServiceStubsImpl.java:279) ~[temporal-serviceclient-1.8.1.jar:?]
airbyte-server |        at io.temporal.serviceclient.WorkflowServiceStubsImpl.<init>(WorkflowServiceStubsImpl.java:186) ~[temporal-serviceclient-1.8.1.jar:?]
airbyte-server |        at io.temporal.serviceclient.WorkflowServiceStubs.newInstance(WorkflowServiceStubs.java:51) ~[temporal-serviceclient-1.8.1.jar:?]
airbyte-server |        at io.temporal.serviceclient.WorkflowServiceStubs.newInstance(WorkflowServiceStubs.java:41) ~[temporal-serviceclient-1.8.1.jar:?]
airbyte-server |        at io.airbyte.workers.temporal.TemporalUtils.lambda$createTemporalService$0(TemporalUtils.java:61) ~[io.airbyte-airbyte-workers-0.35.58-alpha.jar:?]
airbyte-server |        at io.airbyte.workers.temporal.TemporalUtils.getTemporalClientWhenConnected(TemporalUtils.java:190) [io.airbyte-airbyte-workers-0.35.58-alpha.jar:?]
airbyte-server |        at io.airbyte.workers.temporal.TemporalUtils.createTemporalService(TemporalUtils.java:57) [io.airbyte-airbyte-workers-0.35.58-alpha.jar:?]
airbyte-server |        at io.airbyte.server.ServerApp.getServer(ServerApp.java:189) [io.airbyte-airbyte-server-0.35.58-alpha.jar:?]
airbyte-server |        at io.airbyte.server.ServerApp.main(ServerApp.java:242) [io.airbyte-airbyte-server-0.35.58-alpha.jar:?]
airbyte-server | 2022-03-20 17:08:22 WARN i.a.w.t.TemporalUtils(getTemporalClientWhenConnected):194 - Ignoring exception while trying to request Temporal namespaces:
airbyte-server | io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: Deadline exceeded after 4.998910674s. 
airbyte-server |        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262) ~[grpc-stub-1.44.1.jar:1.44.1]
airbyte-server |        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243) ~[grpc-stub-1.44.1.jar:1.44.1]
airbyte-server |        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156) ~[grpc-stub-1.44.1.jar:1.44.1]
airbyte-server |        at io.grpc.health.v1.HealthGrpc$HealthBlockingStub.check(HealthGrpc.java:252) ~[grpc-services-1.44.1.jar:1.44.1]
airbyte-server |        at io.temporal.serviceclient.WorkflowServiceStubsImpl.lambda$checkHealth$2(WorkflowServiceStubsImpl.java:286) ~[temporal-serviceclient-1.8.1.jar:?]
airbyte-server |        at io.temporal.internal.retryer.GrpcSyncRetryer.retry(GrpcSyncRetryer.java:61) ~[temporal-serviceclient-1.8.1.jar:?]
airbyte-server |        at io.temporal.internal.retryer.GrpcRetryer.retryWithResult(GrpcRetryer.java:51) ~[temporal-serviceclient-1.8.1.jar:?]
airbyte-server |        at io.temporal.serviceclient.WorkflowServiceStubsImpl.checkHealth(WorkflowServiceStubsImpl.java:279) ~[temporal-serviceclient-1.8.1.jar:?]
airbyte-server |        at io.temporal.serviceclient.WorkflowServiceStubsImpl.<init>(WorkflowServiceStubsImpl.java:186) ~[temporal-serviceclient-1.8.1.jar:?]
airbyte-server |        at io.temporal.serviceclient.WorkflowServiceStubs.newInstance(WorkflowServiceStubs.java:51) ~[temporal-serviceclient-1.8.1.jar:?]
airbyte-server |        at io.temporal.serviceclient.WorkflowServiceStubs.newInstance(WorkflowServiceStubs.java:41) ~[temporal-serviceclient-1.8.1.jar:?]
airbyte-server |        at io.airbyte.workers.temporal.TemporalUtils.lambda$createTemporalService$0(TemporalUtils.java:61) ~[io.airbyte-airbyte-workers-0.35.58-alpha.jar:?]
airbyte-server |        at io.airbyte.workers.temporal.TemporalUtils.getTemporalClientWhenConnected(TemporalUtils.java:190) [io.airbyte-airbyte-workers-0.35.58-alpha.jar:?]
airbyte-server |        at io.airbyte.workers.temporal.TemporalUtils.createTemporalService(TemporalUtils.java:57) [io.airbyte-airbyte-workers-0.35.58-alpha.jar:?]
airbyte-server |        at io.airbyte.server.ServerApp.getServer(ServerApp.java:189) [io.airbyte-airbyte-server-0.35.58-alpha.jar:?]
airbyte-server |        at io.airbyte.server.ServerApp.main(ServerApp.java:242) [io.airbyte-airbyte-server-0.35.58-alpha.jar:?]
airbyte-server | 2022-03-20 17:08:22 WARN i.a.w.t.TemporalUtils(getTemporalClientWhenConnected):185 - Waiting for default namespace to be initialized in temporal...
airbyte-server | 2022-03-20 17:08:29 WARN i.t.i.r.GrpcSyncRetryer(retry):56 - Retrying after failure
airbyte-server | io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: Deadline exceeded after 4.998560104s.

# ^ this last kees going on every 5s.
```
</details>

<details>
<summary>Temporal Logs</summary> 

```
...
airbyte-temporal | Storage mappings:
airbyte-temporal | +-------------+-------------+
airbyte-temporal | | COLUMN NAME | COLUMN TYPE |
airbyte-temporal | +-------------+-------------+
airbyte-temporal | +-------------+-------------+
airbyte-temporal | Workflow info:
airbyte-temporal | {
airbyte-temporal |   "execution": {
airbyte-temporal |     "workflowId": "temporal-sys-add-search-attributes-workflow",
airbyte-temporal |     "runId": "93002179-71b6-4240-bde8-115f4e775059"
airbyte-temporal |   },
airbyte-temporal |   "startTime": "2022-03-20T17:07:58.050393245Z",
airbyte-temporal |   "closeTime": "2022-03-20T17:07:59.442705625Z",
airbyte-temporal |   "status": "Completed"
airbyte-temporal | }
airbyte-temporal | Search attributes have been added successfully.
airbyte-temporal | {"level":"info","ts":"2022-03-20T17:08:00.126Z","msg":"temporal-sys-tq-scanner-workflow workflow successfully started","service":"worker","logging-call-at":"scanner.go:194"}
airbyte-temporal | {"level":"info","ts":"2022-03-20T17:08:55.593Z","msg":"Get dynamic config","name":"history.transferProcessorCompleteTransferFailureRetryCount","value":10,"default-value":10,"logging-call-at":"config.go:79"}
airbyte-temporal | {"level":"info","ts":"2022-03-20T17:08:55.595Z","msg":"Get dynamic config","name":"history.timerProcessorCompleteTimerFailureRetryCount","value":10,"default-value":10,"logging-call-at":"config.go:79"}
airbyte-temporal | {"level":"info","ts":"2022-03-20T17:08:55.606Z","msg":"Get dynamic config","name":"history.visibilityProcessorCompleteTaskFailureRetryCount","value":10,"default-value":10,"logging-call-at":"config.go:79"}
airbyte-temporal | {"level":"info","ts":"2022-03-20T17:08:56.613Z","msg":"none","service":"matching","component":"matching-engine","wf-task-queue-name":"/_sys/temporal-archival-tq/3","wf-task-queue-type":"Workflow","lifecycle":"Starting","logging-call-at":"taskQueueManager.go:238"}
airbyte-temporal | {"level":"info","ts":"2022-03-20T17:08:56.613Z","msg":"none","service":"matching","component":"matching-engine","wf-task-queue-name":"/_sys/temporal-archival-tq/3","wf-task-queue-type":"Workflow","lifecycle":"Started","logging-call-at":"taskQueueManager.go:242"}
airbyte-temporal | {"level":"info","ts":"2022-03-20T17:08:57.083Z","msg":"none","service":"matching","component":"matching-engine","wf-task-queue-name":"/_sys/temporal-sys-processor-parent-close-policy/2","wf-task-queue-type":"Activity","lifecycle":"Starting","logging-call-at":"taskQueueManager.go:238"}
airbyte-temporal | {"level":"info","ts":"2022-03-20T17:08:57.083Z","msg":"none","service":"matching","component":"matching-engine","wf-task-queue-name":"/_sys/temporal-sys-processor-parent-close-policy/2","wf-task-queue-type":"Activity","lifecycle":"Started","logging-call-at":"taskQueueManager.go:242"}
airbyte-temporal | {"level":"info","ts":"2022-03-20T17:08:57.392Z","msg":"none","service":"matching","component":"matching-engine","wf-task-queue-name":"/_sys/temporal-sys-tq-scanner-taskqueue-0/3","wf-task-queue-type":"Workflow","lifecycle":"Starting","logging-call-at":"taskQueueManager.go:238"}
airbyte-temporal | {"level":"info","ts":"2022-03-20T17:08:57.392Z","msg":"none","service":"matching","component":"matching-engine","wf-task-queue-name":"/_sys/temporal-sys-tq-scanner-taskqueue-0/3","wf-task-queue-type":"Workflow","lifecycle":"Started","logging-call-at":"taskQueueManager.go:242"}
airbyte-temporal | {"level":"info","ts":"2022-03-20T17:09:55.805Z","msg":"none","service":"matching","component":"matching-engine","wf-task-queue-name":"/_sys/temporal-archival-tq/2","wf-task-queue-type":"Activity","lifecycle":"Starting","logging-call-at":"taskQueueManager.go:238"}
airbyte-temporal | {"level":"info","ts":"2022-03-20T17:09:55.806Z","msg":"none","service":"matching","component":"matching-engine","wf-task-queue-name":"/_sys/temporal-archival-tq/2","wf-task-queue-type":"Activity","lifecycle":"Started","logging-call-at":"taskQueueManager.go:242"}
airbyte-temporal | {"level":"info","ts":"2022-03-20T17:09:55.882Z","msg":"none","service":"matching","component":"matching-engine","wf-task-queue-name":"/_sys/temporal-sys-batcher-taskqueue/3","wf-task-queue-type":"Workflow","lifecycle":"Starting","logging-call-at":"taskQueueManager.go:238"}
airbyte-temporal | {"level":"info","ts":"2022-03-20T17:09:55.883Z","msg":"none","service":"matching","component":"matching-engine","wf-task-queue-name":"/_sys/temporal-sys-batcher-taskqueue/3","wf-task-queue-type":"Workflow","lifecycle":"Started","logging-call-at":"taskQueueManager.go:242"}
airbyte-temporal | {"level":"info","ts":"2022-03-20T17:09:56.938Z","msg":"none","service":"matching","component":"matching-engine","wf-task-queue-name":"/_sys/temporal-sys-batcher-taskqueue/1","wf-task-queue-type":"Activity","lifecycle":"Starting","logging-call-at":"taskQueueManager.go:238"}
airbyte-temporal | {"level":"info","ts":"2022-03-20T17:09:56.938Z","msg":"none","service":"matching","component":"matching-engine","wf-task-queue-name":"/_sys/temporal-sys-batcher-taskqueue/1","wf-task-queue-type":"Activity","lifecycle":"Started","logging-call-at":"taskQueueManager.go:242"}
airbyte-temporal | {"level":"info","ts":"2022-03-20T17:11:54.091Z","msg":"none","service":"matching","component":"matching-engine","wf-task-queue-name":"/_sys/temporal-sys-processor-parent-close-policy/2","wf-task-queue-type":"Workflow","lifecycle":"Starting","logging-call-at":"taskQueueManager.go:238"}
airbyte-temporal | {"level":"info","ts":"2022-03-20T17:11:54.091Z","msg":"none","service":"matching","component":"matching-engine","wf-task-queue-name":"/_sys/temporal-sys-processor-parent-close-policy/2","wf-task-queue-type":"Workflow","lifecycle":"Started","logging-call-at":"taskQueueManager.go:242"}
airbyte-temporal | {"level":"info","ts":"2022-03-20T17:11:55.884Z","msg":"none","service":"matching","component":"matching-engine","wf-task-queue-name":"/_sys/temporal-sys-batcher-taskqueue/1","wf-task-queue-type":"Workflow","lifecycle":"Starting","logging-call-at":"taskQueueManager.go:238"}
airbyte-temporal | {"level":"info","ts":"2022-03-20T17:11:55.884Z","msg":"none","service":"matching","component":"matching-engine","wf-task-queue-name":"/_sys/temporal-sys-batcher-taskqueue/1","wf-task-queue-type":"Workflow","lifecycle":"Started","logging-call-at":"taskQueueManager.go:242"}
```

</details>

## Steps to Reproduce
1. Follow the tutorial: https://docs.airbyte.com/deploying-airbyte/on-gcp-compute-engine
2. (I waited quite a while, restarted the server, did down & up everything, all to no avail)

**Comment by tino** [comment]
Is it just me trying out the docker compose setup?

**Comment by sebastianreloaded** [comment]
@tino did you try to set RUN_DATABASE_MIGRATION_ON_STARTUP to true?
I added "RUN_DATABASE_MIGRATION_ON_STARTUP=true" to .env and it worked for me.

**Comment by marcosmarxm** [comment]
@tino this was a new instance of Airbyte or did you try to upgrade from a previous one?

**Comment by tino** [comment]
@sebastianreloaded I did set that at some point and recreated all containers yes. I don't have the env anymore atm.

@marcosmarxm it was a new instance.

To be honest, I quit trying this out and got up and running with Meltano. Guess I can close this.
