### ISSUE TITLE
Source Github: `get_updated_state` problem on `reviews` stream

### ISSUE THREAD

**Issue by grubberr** [airbytehq/airbyte#11566]
## Environment
- **Airbyte version**:  0.35.50-alpha
- **OS Version / Instance**: Linux EC2 m5.4xlarge
- **Deployment**: Docker
- **Source Connector and version**: GitHub (0.2.23)
- **Destination Connector and version**: Snowflake (0.4.24)
- **Severity**: Very Low / Low / Medium / High / Critical
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
The only stream connected is an incremental stream for `reviews` which produces the following error:

```
File "/airbyte/integration_code/source_github/streams.py", line 213, in get_updated_state
    state_value = max(latest_cursor_value, current_stream_state[current_repository][self.cursor_field])
TypeError: '>' not supported between instances of 'str' and 'NoneType'
```

## Expected Behavior
*Tell us what should happen.*

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

[logs-14323.txt](https://github.com/airbytehq/airbyte/files/8378415/logs-14323.txt)

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by grubberr** [comment]
After subsequent testing on client side problem still exists

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 119, in read
    internal_config=internal_config,
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 159, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 217, in _read_incremental
    stream_state = stream_instance.get_updated_state(stream_state, record_data)
  File "/airbyte/integration_code/source_github/streams.py", line 210, in get_updated_state
    updated_state = latest_record[self.cursor_field]
KeyError: 'submitted_at'
```

https://docs.github.com/en/rest/reference/pulls#create-a-review-for-a-pull-request

Pull request reviews created in the `PENDING` state do not include the `submitted_at` property in the response.
