### ISSUE TITLE
Posgresql to MySQL normalization error

### ISSUE THREAD

**Issue by webtekindo** [airbytehq/airbyte#11619]
## Environment
- **Airbyte version**:  0.35.63-alpha
- **OS Version / Instance**: Debian Stretch
- **Deployment**: Docker
- **Source Connector and version**: Postgresql 0.4.9
- **Destination Connector and version**: MySQL connector 0.1.18 (10.3.28-MariaDB)
- **Severity**: Critical
- **Step where error happened**: Sync job Normalization

## Current Behavior
Error during normalization. 

With the same source and destination, on WSL Ubuntu 18.04.5 LTS with Docker it works but for some reason we get that error while on GCP Debian Stretch with Docker.

## Expected Behavior
No error

## Logs

```

2022-03-31 10:11:48 [32mINFO[m i.a.w.DefaultReplicationWorker(run):165 - Source and destination threads complete.
2022-03-31 10:11:48 [32mINFO[m i.a.w.DefaultReplicationWorker(run):228 - sync summary: io.airbyte.config.ReplicationAttemptSummary@31a711db[status=completed,recordsSynced=1000,bytesSynced=56769,startTime=1648721493752,endTime=1648721508846,totalStats=io.airbyte.config.SyncStats@43093332[recordsEmitted=1000,bytesEmitted=56769,stateMessagesEmitted=0,recordsCommitted=1000],streamStats=[io.airbyte.config.StreamSyncStats@6c102558[streamName=sync_odoo_product_external_test,stats=io.airbyte.config.SyncStats@faa3491[recordsEmitted=1000,bytesEmitted=56769,stateMessagesEmitted=<null>,recordsCommitted=1000]]]]
2022-03-31 10:11:48 [32mINFO[m i.a.w.DefaultReplicationWorker(run):250 - Source did not output any state messages
2022-03-31 10:11:48 [33mWARN[m i.a.w.DefaultReplicationWorker(run):258 - State capture: No new state, falling back on input state: io.airbyte.config.State@60ad576[state={}]
2022-03-31 10:11:48 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):131 - Stopping cancellation check scheduling...
2022-03-31 10:11:48 [32mINFO[m i.a.w.t.s.ReplicationActivityImpl(lambda$replicate$1):147 - sync summary: io.airbyte.config.StandardSyncOutput@7e0cb656[standardSyncSummary=io.airbyte.config.StandardSyncSummary@182c37ed[status=completed,recordsSynced=1000,bytesSynced=56769,startTime=1648721493752,endTime=1648721508846,totalStats=io.airbyte.config.SyncStats@43093332[recordsEmitted=1000,bytesEmitted=56769,stateMessagesEmitted=0,recordsCommitted=1000],streamStats=[io.airbyte.config.StreamSyncStats@6c102558[streamName=sync_odoo_product_external_test,stats=io.airbyte.config.SyncStats@faa3491[recordsEmitted=1000,bytesEmitted=56769,stateMessagesEmitted=<null>,recordsCommitted=1000]]]],state=io.airbyte.config.State@60ad576[state={}],outputCatalog=io.airbyte.protocol.models.ConfiguredAirbyteCatalog@39f8d542[streams=[io.airbyte.protocol.models.ConfiguredAirbyteStream@7e2dacf6[stream=io.airbyte.protocol.models.AirbyteStream@65081b63[name=sync_odoo_product_external_test,jsonSchema={"type":"object","properties":{"id":{"type":"number"},"source":{"type":"string"},"product_id":{"type":"string"}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=overwrite,primaryKey=[],additionalProperties={}]],additionalProperties={}],failures=[]]
2022-03-31 10:11:48 [32mINFO[m i.a.w.t.TemporalUtils(withBackgroundHeartbeat):235 - Stopping temporal heartbeating...
2022-03-31 10:11:48 [32mINFO[m i.a.c.p.ConfigRepository(updateConnectionState):731 - Updating connection 2e761e16-0508-4a8f-b3a0-039d5ee6bb63 state: io.airbyte.config.State@709615e8[state={}]
2022-03-31 10:11:48 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):105 - Docker volume job log path: /tmp/workspace/17/1/logs.log
2022-03-31 10:11:48 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):110 - Executing worker wrapper. Airbyte version: 0.35.62-alpha
2022-03-31 10:11:48 [32mINFO[m i.a.w.DefaultNormalizationWorker(run):46 - Running normalization.
2022-03-31 10:11:48 [32mINFO[m i.a.w.n.DefaultNormalizationRunner(runProcess):122 - Running with normalization version: airbyte/normalization-mysql:0.1.74
2022-03-31 10:11:49 [32mINFO[m i.a.c.i.LineGobbler(voidCall):82 - Checking if airbyte/normalization-mysql:0.1.74 exists...
2022-03-31 10:11:49 [32mINFO[m i.a.c.i.LineGobbler(voidCall):82 - airbyte/normalization-mysql:0.1.74 was found locally.
2022-03-31 10:11:49 [32mINFO[m i.a.w.p.DockerProcessFactory(create):106 - Creating docker job ID: 17
2022-03-31 10:11:49 [32mINFO[m i.a.w.p.DockerProcessFactory(create):158 - Preparing command: docker run --rm --init -i -w /data/17/1/normalize --log-driver none --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e AIRBYTE_ROLE= -e WORKER_ENVIRONMENT=DOCKER -e AIRBYTE_VERSION=0.35.62-alpha airbyte/normalization-mysql:0.1.74 run --integration-type mysql --config destination_config.json --catalog destination_catalog.json
2022-03-31 10:11:49 [42mnormalization[0m > Running: transform-config --config destination_config.json --integration-type mysql --out /data/17/1/normalize
2022-03-31 10:11:50 [42mnormalization[0m > Namespace(config='destination_config.json', integration_type=<DestinationType.mysql: 'mysql'>, out='/data/17/1/normalize')
2022-03-31 10:11:50 [42mnormalization[0m > transform_mysql
2022-03-31 10:11:50 [42mnormalization[0m > Running: transform-catalog --integration-type mysql --profile-config-dir /data/17/1/normalize --catalog destination_catalog.json --out /data/17/1/normalize/models/generated/ --json-column _airbyte_data
2022-03-31 10:11:50 [42mnormalization[0m > Processing destination_catalog.json...
2022-03-31 10:11:50 [42mnormalization[0m >   Generating airbyte_ctes/a56d1152_nr1_staging/sync_odoo_product_external_test_ab1.sql from sync_odoo_product_external_test
2022-03-31 10:11:50 [42mnormalization[0m >   Generating airbyte_ctes/a56d1152_nr1_staging/sync_odoo_product_external_test_ab2.sql from sync_odoo_product_external_test
2022-03-31 10:11:50 [42mnormalization[0m > Truncating _airbyte_sync_odoo_product_external_test_hashid (#47) to _airbyte_sync_odoo_pr__external_test_hashid (#44)
2022-03-31 10:11:50 [42mnormalization[0m >   Generating airbyte_ctes/a56d1152_nr1_staging/sync_odoo_product_external_test_ab3.sql from sync_odoo_product_external_test
2022-03-31 10:11:50 [42mnormalization[0m > Truncating _airbyte_sync_odoo_product_external_test_hashid (#47) to _airbyte_sync_odoo_pr__external_test_hashid (#44)
2022-03-31 10:11:50 [42mnormalization[0m >   Generating airbyte_tables/a56d1152_nr1_staging/sync_odoo_product_external_test.sql from sync_odoo_product_external_test
2022-03-31 10:11:50 [42mnormalization[0m > detected no config file for ssh, assuming ssh is off.
2022-03-31 10:11:53 [32mINFO[m i.a.w.t.TemporalAttemptExecution(lambda$getWorkerThread$2):158 - Completing future exceptionally...
io.airbyte.workers.WorkerException: Normalization Failed.
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:60) ~[io.airbyte-airbyte-workers-0.35.62-alpha.jar:?]
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:18) ~[io.airbyte-airbyte-workers-0.35.62-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:155) ~[io.airbyte-airbyte-workers-0.35.62-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: io.airbyte.workers.WorkerException: Normalization Failed.
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:57) ~[io.airbyte-airbyte-workers-0.35.62-alpha.jar:?]
	... 3 more
	Suppressed: io.airbyte.workers.WorkerException: Normalization process wasn't successful
		at io.airbyte.workers.normalization.DefaultNormalizationRunner.close(DefaultNormalizationRunner.java:160) ~[io.airbyte-airbyte-workers-0.35.62-alpha.jar:?]
		at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:45) ~[io.airbyte-airbyte-workers-0.35.62-alpha.jar:?]
		at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:18) ~[io.airbyte-airbyte-workers-0.35.62-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:155) ~[io.airbyte-airbyte-workers-0.35.62-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:833) [?:?]
2022-03-31 10:11:53 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):131 - Stopping cancellation check scheduling...
2022-03-31 10:11:53 [32mINFO[m i.a.w.t.TemporalUtils(withBackgroundHeartbeat):235 - Stopping temporal heartbeating...
2022-03-31 10:11:53 [33mWARN[m i.t.i.a.POJOActivityTaskHandler(activityFailureToResult):307 - Activity failure. ActivityId=4d160306-dac6-3d28-98b8-923b8ab4dc6e, activityType=Normalize, attempt=1
java.lang.RuntimeException: io.temporal.serviceclient.CheckedExceptionWrapper: java.util.concurrent.ExecutionException: io.airbyte.workers.WorkerException: Normalization Failed.
	at io.airbyte.workers.temporal.TemporalUtils.withBackgroundHeartbeat(TemporalUtils.java:233) ~[io.airbyte-airbyte-workers-0.35.62-alpha.jar:?]
	at io.airbyte.workers.temporal.sync.NormalizationActivityImpl.normalize(NormalizationActivityImpl.java:71) ~[io.airbyte-airbyte-workers-0.35.62-alpha.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at io.temporal.internal.activity.POJOActivityTaskHandler$POJOActivityInboundCallsInterceptor.execute(POJOActivityTaskHandler.java:214) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.activity.POJOActivityTaskHandler$POJOActivityImplementation.execute(POJOActivityTaskHandler.java:180) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.activity.POJOActivityTaskHandler.handle(POJOActivityTaskHandler.java:120) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:204) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:164) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93) ~[temporal-sdk-1.8.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: io.temporal.serviceclient.CheckedExceptionWrapper: java.util.concurrent.ExecutionException: io.airbyte.workers.WorkerException: Normalization Failed.
	at io.temporal.serviceclient.CheckedExceptionWrapper.wrap(CheckedExceptionWrapper.java:56) ~[temporal-serviceclient-1.8.1.jar:?]
	at io.temporal.internal.sync.WorkflowInternal.wrap(WorkflowInternal.java:448) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.activity.Activity.wrap(Activity.java:51) ~[temporal-sdk-1.8.1.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:135) ~[io.airbyte-airbyte-workers-0.35.62-alpha.jar:?]
	at io.airbyte.workers.temporal.sync.NormalizationActivityImpl.lambda$normalize$1(NormalizationActivityImpl.java:97) ~[io.airbyte-airbyte-workers-0.35.62-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalUtils.withBackgroundHeartbeat(TemporalUtils.java:228) ~[io.airbyte-airbyte-workers-0.35.62-alpha.jar:?]
	... 14 more
Caused by: java.util.concurrent.ExecutionException: io.airbyte.workers.WorkerException: Normalization Failed.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:129) ~[io.airbyte-airbyte-workers-0.35.62-alpha.jar:?]
	at io.airbyte.workers.temporal.sync.NormalizationActivityImpl.lambda$normalize$1(NormalizationActivityImpl.java:97) ~[io.airbyte-airbyte-workers-0.35.62-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalUtils.withBackgroundHeartbeat(TemporalUtils.java:228) ~[io.airbyte-airbyte-workers-0.35.62-alpha.jar:?]
	... 14 more
Caused by: io.airbyte.workers.WorkerException: Normalization Failed.
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:60) ~[io.airbyte-airbyte-workers-0.35.62-alpha.jar:?]
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:18) ~[io.airbyte-airbyte-workers-0.35.62-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:155) ~[io.airbyte-airbyte-workers-0.35.62-alpha.jar:?]
	... 1 more
Caused by: io.airbyte.workers.WorkerException: Normalization Failed.
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:57) ~[io.airbyte-airbyte-workers-0.35.62-alpha.jar:?]
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:18) ~[io.airbyte-airbyte-workers-0.35.62-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:155) ~[io.airbyte-airbyte-workers-0.35.62-alpha.jar:?]
	... 1 more
	Suppressed: io.airbyte.workers.WorkerException: Normalization process wasn't successful
		at io.airbyte.workers.normalization.DefaultNormalizationRunner.close(DefaultNormalizationRunner.java:160) ~[io.airbyte-airbyte-workers-0.35.62-alpha.jar:?]
		at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:45) ~[io.airbyte-airbyte-workers-0.35.62-alpha.jar:?]
		at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:18) ~[io.airbyte-airbyte-workers-0.35.62-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:155) ~[io.airbyte-airbyte-workers-0.35.62-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:833) [?:?]
```

</details>

## Steps to Reproduce
1. Run sync with normalization

## Are you willing to submit a PR?
No

**Comment by webtekindo** [comment]
When I try docker run --rm -i -v airbyte_workspace:/data -w /data/$NORMALIZE_WORKSPACE/normalize --network host --entrypoint /usr/local/bin/dbt airbyte/normalization debug --profiles-dir=. --project-dir=.

I get error **Error importing adapter: No module named 'dbt.adapters.mysql'**


```
docker run --rm -i -v airbyte_workspace:/data -w /data/$NORMALIZE_WORKSPACE/normalize --network host --entrypoint /usr/local/bin/dbt airbyte/normalization debug --profiles-dir=. --project-dir=.
11:49:29  Running with dbt=1.0.0
dbt version: 1.0.0
python version: 3.9.9
python path: /usr/local/bin/python
os info: Linux-4.9.0-5-amd64-x86_64-with-glibc2.31
Using profiles.yml file at /data/21/0/normalize/profiles.yml
Using dbt_project.yml file at /data/21/0/normalize/dbt_project.yml

11:49:29  Error importing adapter: No module named 'dbt.adapters.mysql'
11:49:29  [WARNING]: Deprecated functionality
The `source-paths` config has been renamed to `model-paths`. Please update your `dbt_project.yml` configuration to
reflect this change.
11:49:29  [WARNING]: Deprecated functionality
The `data-paths` config has been renamed to `seed-paths`. Please update your `dbt_project.yml` configuration to reflect
this change.
Configuration:
  profiles.yml file [ERROR invalid]
  dbt_project.yml file [ERROR invalid]

Required dependencies:
 - git [OK found]

2 checks failed:
Project loading failed for the following reason:
Runtime Error
  at path []: Additional properties are not allowed ('modules-path' was unexpected)

Error encountered in /data/21/0/normalize/dbt_project.yml


Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "normalize", target "prod" invalid: Runtime Error
    Could not find adapter type mysql!
```

**Comment by webtekindo** [comment]
I reinstall airbyte from git with tag **v0.35.60-alpha** and it works perfect. I tried again with latest **v0.35.63-alpha** but same error as before.

**Comment by marcosmarxm** [comment]
@webtekindo I'm closing due inactivity. Please open a new issue if the problem persits.
