### ISSUE TITLE
GitHub source : Personal Access Token authentication method fails since version 0.2.23

### ISSUE THREAD

**Issue by AnatolePledg** [airbytehq/airbyte#11651]
## Environment
- **Airbyte version**:  example is 0.35.4-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: 0.2.23
- **Severity**: High
- **Step where error happened**: Sync job

## Behavior
In version 0.2.22 of the connector it was possible to use Personal Access Token to authenticate into Github, now it is no longer possible.

## Logs

<details>
<summary>LOG</summary> 

```

2022-04-01 07:40:55 [44msource[0m > Config validation error: 'OAuth Credentials' was expected
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 127, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 98, in run
    check_config_against_spec_or_exit(config, source_spec)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 161, in check_config_against_spec_or_exit
    raise Exception("Config validation error: " + validation_error.message) from None
Exception: Config validation error: 'OAuth Credentials' was expected
```

</details>

## Steps to Reproduce
1. Use version 0.2.22 to configure a Personal Access Token
2. Launch a sync --> it works
3. Upgrade to 0.2.23
4. Launch a sync --> it fails

v0.2.2 :
<img width="1006" alt="Capture d’écran 2022-04-01 à 09 56 47" src="https://user-images.githubusercontent.com/90203392/161220798-583dddfa-8ea9-49c7-80a1-8b5bb2aad34e.png">

**Comment by sherifnada** [comment]
@AnatolePledg thanks for the report, will take a look
