### ISSUE TITLE
PostgreSQL source connector fails with large tables

### ISSUE THREAD

**Issue by leoalmeidasant** [airbytehq/airbyte#11661]
## Environment
- **Airbyte version**:  example is 0.35.59-alpha
- **OS Version / Instance**: AWs Eks
- **Deployment**: kubernetes
- **Source Connector and version**: 0.4.4 (cause next versions are broken in fetchSchema)
- **Destination Connector and version**: s3 destination 0.2.13
- **Severity**: High
- **Step where error happened**: Sync job

## Current Behavior
The sync between postgres <> s3 works fine with small tables, but when we run a sync job that are getting data from tables with 500GB (almost 600.000.000 rows) the sync fails and no logs are showing that make we understand the error. And the sync run again from de start. This takes 18 hours to get the error.

## Expected Behavior
Finish the first sync and execute incremental append on next syncs.

## Logs
<details>
<summary>LOG</summary> 

```
2022-04-01 09:09:26 [44msource[0m > 2022-04-01 09:09:25 [32mINFO[m i.a.i.s.r.AbstractDbSource(lambda$createReadIterator$7):249 - Reading stream billing_entry. Records read: 524120000
2022-04-01 09:09:28 [44msource[0m > 2022-04-01 09:09:27 [1;31mERROR[m i.a.c.u.CompositeIterator(close):93 - exception while closing
2022-04-01 09:09:28 [44msource[0m > java.lang.RuntimeException: org.postgresql.util.PSQLException: This connection has been closed.
2022-04-01 09:09:28 [44msource[0m > 	at io.airbyte.db.jdbc.StreamingJdbcDatabase.lambda$query$0(StreamingJdbcDatabase.java:101) ~[io.airbyte.airbyte-db-lib-0.35.12-alpha.jar:?]
2022-04-01 09:09:28 [44msource[0m > 	at java.util.stream.AbstractPipeline.close(AbstractPipeline.java:323) ~[?:?]
2022-04-01 09:09:28 [44msource[0m > 	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15) ~[io.airbyte-airbyte-commons-0.35.12-alpha.jar:?]
2022-04-01 09:09:28 [44msource[0m > 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:49) ~[io.airbyte-airbyte-commons-0.35.12-alpha.jar:?]
2022-04-01 09:09:28 [44msource[0m > 	at io.airbyte.commons.util.LazyAutoCloseableIterator.close(LazyAutoCloseableIterator.java:52) ~[io.airbyte-airbyte-commons-0.35.12-alpha.jar:?]
2022-04-01 09:09:28 [44msource[0m > 	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15) ~[io.airbyte-airbyte-commons-0.35.12-alpha.jar:?]
2022-04-01 09:09:28 [44msource[0m > 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:49) ~[io.airbyte-airbyte-commons-0.35.12-alpha.jar:?]
2022-04-01 09:09:28 [44msource[0m > 	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15) ~[io.airbyte-airbyte-commons-0.35.12-alpha.jar:?]
2022-04-01 09:09:28 [44msource[0m > 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:49) ~[io.airbyte-airbyte-commons-0.35.12-alpha.jar:?]
2022-04-01 09:09:28 [44msource[0m > 	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15) ~[io.airbyte-airbyte-commons-0.35.12-alpha.jar:?]
2022-04-01 09:09:28 [44msource[0m > 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:49) ~[io.airbyte-airbyte-commons-0.35.12-alpha.jar:?]
2022-04-01 09:09:28 [44msource[0m > 	at io.airbyte.commons.util.CompositeIterator.close(CompositeIterator.java:91) ~[io.airbyte-airbyte-commons-0.35.12-alpha.jar:?]
2022-04-01 09:09:28 [44msource[0m > 	at io.airbyte.commons.util.AutoCloseableIterators.lambda$appendOnClose$0(AutoCloseableIterators.java:88) ~[io.airbyte-airbyte-commons-0.35.12-alpha.jar:?]
2022-04-01 09:09:28 [44msource[0m > 	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15) ~[io.airbyte-airbyte-commons-0.35.12-alpha.jar:?]
2022-04-01 09:09:28 [44msource[0m > 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:49) ~[io.airbyte-airbyte-commons-0.35.12-alpha.jar:?]
2022-04-01 09:09:28 [44msource[0m > 	at io.airbyte.commons.util.AutoCloseableIterators.lambda$appendOnClose$0(AutoCloseableIterators.java:88) ~[io.airbyte-airbyte-commons-0.35.12-alpha.jar:?]
2022-04-01 09:09:28 [44msource[0m > 	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15) [io.airbyte-airbyte-commons-0.35.12-alpha.jar:?]
2022-04-01 09:09:28 [44msource[0m > 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:49) [io.airbyte-airbyte-commons-0.35.12-alpha.jar:?]
2022-04-01 09:09:28 [44msource[0m > 	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:143) [io.airbyte.airbyte-integrations.bases-base-java-0.35.12-alpha.jar:?]
2022-04-01 09:09:28 [44msource[0m > 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:88) [io.airbyte.airbyte-integrations.bases-base-java-0.35.12-alpha.jar:?]
2022-04-01 09:09:28 [44msource[0m > 	at io.airbyte.integrations.source.postgres.PostgresSource.main(PostgresSource.java:357) [io.airbyte.airbyte-integrations.connectors-source-postgres-0.35.12-alpha.jar:?]
2022-04-01 09:09:28 [44msource[0m > Caused by: org.postgresql.util.PSQLException: This connection has been closed.
2022-04-01 09:09:28 [44msource[0m > 	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:885) ~[postgresql-42.2.18.jar:42.2.18]
2022-04-01 09:09:28 [44msource[0m > 	at org.postgresql.jdbc.PgConnection.setAutoCommit(PgConnection.java:814) ~[postgresql-42.2.18.jar:42.2.18]
2022-04-01 09:09:28 [44msource[0m > 	at org.apache.commons.dbcp2.DelegatingConnection.setAutoCommit(DelegatingConnection.java:537) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2022-04-01 09:09:28 [44msource[0m > 	at org.apache.commons.dbcp2.DelegatingConnection.setAutoCommit(DelegatingConnection.java:537) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2022-04-01 09:09:28 [44msource[0m > 	at io.airbyte.db.jdbc.StreamingJdbcDatabase.lambda$query$0(StreamingJdbcDatabase.java:98) ~[io.airbyte.airbyte-db-lib-0.35.12-alpha.jar:?]
2022-04-01 09:09:28 [44msource[0m > 	... 20 more
2022-04-01 09:10:28 [32mINFO[m i.a.v.j.JsonSchemaValidator(test):56 - JSON schema validation failed. 
errors: $.compression_codec: is missing but it is required, $.format_type: does not have a value in the enumeration [Avro]
2022-04-01 09:09:58 [32mINFO[m i.a.w.p.KubePodProcess(getReturnCode):743 - (pod: airbyte-namespace / source-postgres-sync-262-0-bwzha) - Exit code for pod is 1
2022-04-01 09:09:58 [32mINFO[m i.a.w.p.KubePodProcess(exitValue):758 - (pod: airbyte-namespace / source-postgres-sync-262-0-bwzha) - Closed all resources for pod
2022-04-01 09:09:58 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):305 - Total records read: 524128000 (230 GB)
2022-04-01 09:09:58 [32mINFO[m i.a.w.p.KubePodProcess(exitValue):758 - (pod: airbyte-namespace / source-postgres-sync-262-0-bwzha) - Closed all resources for pod
2022-04-01 09:09:58 [32mINFO[m i.a.w.p.KubePodProcess(exitValue):758 - (pod: airbyte-namespace / source-postgres-sync-262-0-bwzha) - Closed all resources for pod
2022-04-01 09:09:58 [32mINFO[m i.a.w.p.KubePodProcess(exitValue):758 - (pod: airbyte-namespace / source-postgres-sync-262-0-bwzha) - Closed all resources for pod
2022-04-01 09:09:58 [32mINFO[m i.a.w.p.KubePodProcess(exitValue):758 - (pod: airbyte-namespace / source-postgres-sync-262-0-bwzha) - Closed all resources for pod
2022-04-01 09:09:58 [32mINFO[m i.a.w.p.KubePodProcess(exitValue):758 - (pod: airbyte-namespace / source-postgres-sync-262-0-bwzha) - Closed all resources for pod
2022-04-01 09:09:58 [32mINFO[m i.a.w.p.KubePodProcess(exitValue):758 - (pod: airbyte-namespace / source-postgres-sync-262-0-bwzha) - Closed all resources for pod
2022-04-01 09:09:58 [32mINFO[m i.a.w.p.KubePodProcess(exitValue):758 - (pod: airbyte-namespace / source-postgres-sync-262-0-bwzha) - Closed all resources for pod
2022-04-01 09:09:58 [32mINFO[m i.a.w.p.KubePodProcess(exitValue):758 - (pod: airbyte-namespace / source-postgres-sync-262-0-bwzha) - Closed all resources for pod
2022-04-01 09:09:58 [32mINFO[m i.a.w.p.KubePodProcess(exitValue):758 - (pod: airbyte-namespace / source-postgres-sync-262-0-bwzha) - Closed all resources for pod
2022-04-01 09:10:28 [1;31mERROR[m i.a.w.DefaultReplicationWorker(run):169 - Sync worker failed.
java.util.concurrent.ExecutionException: io.airbyte.workers.DefaultReplicationWorker$SourceException: Source process exited with non-zero exit code 1
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:162) ~[io.airbyte-airbyte-workers-0.35.59-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:57) ~[io.airbyte-airbyte-workers-0.35.59-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:155) ~[io.airbyte-airbyte-workers-0.35.59-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
	Suppressed: io.airbyte.workers.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteSource.close(DefaultAirbyteSource.java:136) ~[io.airbyte-airbyte-workers-0.35.59-alpha.jar:?]
		at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:126) ~[io.airbyte-airbyte-workers-0.35.59-alpha.jar:?]
		at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:57) ~[io.airbyte-airbyte-workers-0.35.59-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:155) ~[io.airbyte-airbyte-workers-0.35.59-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:833) [?:?]
	Suppressed: java.lang.RuntimeException: (pod: airbyte-namespace / destination-s3-sync-262-0-mqrwj) - Cannot find pod %s : %s while trying to retrieve exit code. This probably means the pod was not correctly created.
		at io.airbyte.workers.process.KubePodProcess.getReturnCode(KubePodProcess.java:723) ~[io.airbyte-airbyte-workers-0.35.59-alpha.jar:?]
		at io.airbyte.workers.process.KubePodProcess.exitValue(KubePodProcess.java:751) ~[io.airbyte-airbyte-workers-0.35.59-alpha.jar:?]
		at java.lang.Process.hasExited(Process.java:584) ~[?:?]
		at java.lang.Process.waitFor(Process.java:469) ~[?:?]
		at io.airbyte.workers.process.KubePodProcess.waitFor(KubePodProcess.java:612) ~[io.airbyte-airbyte-workers-0.35.59-alpha.jar:?]
		at io.airbyte.workers.WorkerUtils.gentleClose(WorkerUtils.java:37) ~[io.airbyte-airbyte-workers-0.35.59-alpha.jar:?]
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.close(DefaultAirbyteDestination.java:115) ~[io.airbyte-airbyte-workers-0.35.59-alpha.jar:?]
		at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:126) ~[io.airbyte-airbyte-workers-0.35.59-alpha.jar:?]
		at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:57) ~[io.airbyte-airbyte-workers-0.35.59-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:155) ~[io.airbyte-airbyte-workers-0.35.59-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: io.airbyte.workers.DefaultReplicationWorker$SourceException: Source process exited with non-zero exit code 1
	at io.airbyte.workers.DefaultReplicationWorker.lambda$getReplicationRunnable$5(DefaultReplicationWorker.java:312) ~[io.airbyte-airbyte-workers-0.35.59-alpha.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
2022-04-01 09:10:28 [32mINFO[m i.a.w.DefaultReplicationWorker(run):228 - sync summary: io.airbyte.config.ReplicationAttemptSummary@b8b3612[status=failed,recordsSynced=524128000,bytesSynced=247143020552,startTime=1648751452513,endTime=1648804228774,totalStats=io.airbyte.config.SyncStats@7731ce9[recordsEmitted=524128000,bytesEmitted=247143020552,stateMessagesEmitted=0,recordsCommitted=0],streamStats=[io.airbyte.config.StreamSyncStats@25cdf625[streamName=billing_entry,stats=io.airbyte.config.SyncStats@7ff48e27[recordsEmitted=524128000,bytesEmitted=247143020552,stateMessagesEmitted=<null>,recordsCommitted=<null>]]]]
2022-04-01 09:10:28 [32mINFO[m i.a.w.DefaultReplicationWorker(run):250 - Source did not output any state messages
2022-04-01 09:10:28 [33mWARN[m i.a.w.DefaultReplicationWorker(run):258 - State capture: No new state, falling back on input state: io.airbyte.config.State@66c5df29[state={}]
2022-04-01 09:10:28 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):131 - Stopping cancellation check scheduling...
2022-04-01 09:10:28 [32mINFO[m i.a.w.t.s.ReplicationActivityImpl(lambda$replicate$1):147 - sync summary: io.airbyte.config.StandardSyncOutput@2627aff1[standardSyncSummary=io.airbyte.config.StandardSyncSummary@1c17a17[status=failed,recordsSynced=524128000,bytesSynced=247143020552,startTime=1648751452513,endTime=1648804228774,totalStats=io.airbyte.config.SyncStats@7731ce9[recordsEmitted=524128000,bytesEmitted=247143020552,stateMessagesEmitted=0,recordsCommitted=0],streamStats=[io.airbyte.config.StreamSyncStats@25cdf625[streamName=billing_entry,stats=io.airbyte.config.SyncStats@7ff48e27[recordsEmitted=524128000,bytesEmitted=247143020552,stateMessagesEmitted=<null>,recordsCommitted=<null>]]]],state=io.airbyte.config.State@66c5df29[state={}],outputCatalog=io.airbyte.protocol.models.ConfiguredAirbyteCatalog@1467ab67[streams=[io.airbyte.protocol.models.ConfiguredAirbyteStream@294ff3d[stream=io.airbyte.protocol.models.AirbyteStream@195780b9[name=billing_entry,jsonSchema={"type":"object","properties":{"id":{"type":"number"},"uuid":{"type":"string"},"amount":{"type":"number"},"version":{"type":"number"},"metadata":{"type":"string"},"driver_id":{"type":"number"},"payout_id":{"type":"number"},"promotion":{"type":"boolean"},"finance_key":{"type":"string"},"source_name":{"type":"string"},"source_uuid":{"type":"string"},"billing_type":{"type":"string"},"created_date":{"type":"string"},"billing_cause":{"type":"string"},"payout_instant":{"type":"string"},"source_platform":{"type":"string"},"billing_account_id":{"type":"number"},"last_modified_date":{"type":"string"},"transaction_instant":{"type":"string"}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[[id]],namespace=driver_income/,additionalProperties={}],syncMode=incremental,cursorField=[last_modified_date],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}]],additionalProperties={}],failures=[io.airbyte.config.FailureReason@13cc4046[failureOrigin=source,failureType=<null>,internalMessage=io.airbyte.workers.DefaultReplicationWorker$SourceException: Source process exited with non-zero exit code 1,externalMessage=Something went wrong within the source connector,metadata=io.airbyte.config.Metadata@3a59edcb[additionalProperties={attemptNumber=0, jobId=262}],stacktrace=java.util.concurrent.CompletionException: io.airbyte.workers.DefaultReplicationWorker$SourceException: Source process exited with non-zero exit code 1
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.airbyte.workers.DefaultReplicationWorker$SourceException: Source process exited with non-zero exit code 1
	at io.airbyte.workers.DefaultReplicationWorker.lambda$getReplicationRunnable$5(DefaultReplicationWorker.java:312)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	... 3 more
,retryable=<null>,timestamp=1648804198684], io.airbyte.config.FailureReason@1f9180aa[failureOrigin=replication,failureType=<null>,internalMessage=java.lang.RuntimeException: java.lang.RuntimeException: (pod: airbyte-namespace / destination-s3-sync-262-0-mqrwj) - Cannot find pod %s : %s while trying to retrieve exit code. This probably means the pod was not correctly created.,externalMessage=Something went wrong during replication,metadata=io.airbyte.config.Metadata@3ae699a9[additionalProperties={attemptNumber=0, jobId=262}],stacktrace=java.util.concurrent.CompletionException: java.lang.RuntimeException: java.lang.RuntimeException: (pod: airbyte-namespace / destination-s3-sync-262-0-mqrwj) - Cannot find pod %s : %s while trying to retrieve exit code. This probably means the pod was not correctly created.
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: (pod: airbyte-namespace / destination-s3-sync-262-0-mqrwj) - Cannot find pod %s : %s while trying to retrieve exit code. This probably means the pod was not correctly created.
	at io.airbyte.workers.DefaultReplicationWorker.lambda$getDestinationOutputRunnable$6(DefaultReplicationWorker.java:367)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	... 3 more
Caused by: java.lang.RuntimeException: (pod: airbyte-namespace / destination-s3-sync-262-0-mqrwj) - Cannot find pod %s : %s while trying to retrieve exit code. This probably means the pod was not correctly created.
	at io.airbyte.workers.process.KubePodProcess.getReturnCode(KubePodProcess.java:723)
	at io.airbyte.workers.process.KubePodProcess.exitValue(KubePodProcess.java:751)
	at java.base/java.lang.Process.hasExited(Process.java:584)
	at java.base/java.lang.Process.isAlive(Process.java:574)
	at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.isFinished(DefaultAirbyteDestination.java:146)
	at io.airbyte.workers.DefaultReplicationWorker.lambda$getDestinationOutputRunnable$6(DefaultReplicationWorker.java:341)
	... 4 more
,retryable=<null>,timestamp=1648804228694]]]
2022-04-01 09:10:28 [32mINFO[m i.a.w.t.TemporalUtils(withBackgroundHeartbeat):235 - Stopping temporal heartbeating...
2022-04-01 09:10:28 [32mINFO[m i.a.c.p.ConfigRepository(updateConnectionState):543 - Updating connection fe2888f5-3275-4c8b-be1c-53216d4673da state: io.airbyte.config.State@3ecb6e51[state={}]
2022-04-01 09:09:59 [43mdestination[0m > 2022-04-01 09:09:59 [32mINFO[m i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):65 - Airbyte message consumer: succeeded.
2022-04-01 09:09:59 [43mdestination[0m > 2022-04-01 09:09:59 [32mINFO[m i.a.i.d.b.BufferedStreamConsumer(close):170 - executing on success close procedure.
2022-04-01 09:09:59 [43mdestination[0m > 2022-04-01 09:09:59 [32mINFO[m i.a.i.d.r.SerializedBufferingStrategy(flushAll):92 - Flushing all 1 current buffers (115 MB in total)
2022-04-01 09:09:59 [43mdestination[0m > 2022-04-01 09:09:59 [32mINFO[m i.a.i.d.r.SerializedBufferingStrategy(lambda$flushAll$2):95 - Flushing buffer of stream billing_entry (115 MB)
2022-04-01 09:09:59 [43mdestination[0m > 2022-04-01 09:09:59 [32mINFO[m i.a.i.d.s.S3ConsumerFactory(lambda$flushBufferFunction$3):129 - Flushing buffer for stream billing_entry (115 MB) to storage
2022-04-01 09:09:59 [43mdestination[0m > 2022-04-01 09:09:59 [32mINFO[m i.a.i.d.r.BaseSerializedBuffer(flush):131 - Wrapping up compression and write GZIP trailer data.
2022-04-01 09:09:59 [43mdestination[0m > 2022-04-01 09:09:59 [32mINFO[m i.a.i.d.r.BaseSerializedBuffer(flush):138 - Finished writing data to 53a8771e-8f2b-474a-828d-3e3194cde4ec3102560680272769070.jsonl.gz (115 MB)
2022-04-01 09:09:59 [43mdestination[0m > 2022-04-01 09:09:59 [32mINFO[m i.a.i.d.s.u.StreamTransferManagerHelper(getDefault):55 - PartSize arg is set to 256 MB
2022-04-01 09:09:59 [43mdestination[0m > 2022-04-01 09:09:59 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - Initiated multipart upload to s3_path/dt=2022-03-31/53a8771e-8f2b-474a-828d-3e3194cde4ec3102560680272769070.jsonl.gz with full ID YcAuBuqWe5Hq.M6mSlLlOp.Z9rPwfkUS9QS3qZSqXclKva5BAutpIlsSRyQxD_5gW7GMyoEjSe96R399QOwzlVi1fpflk5bbVaAfhrMToOZeLQ5eR4sDeXSoglynAYBMMAcYatnEK5Rx83HfKmMXng--
2022-04-01 09:09:59 [43mdestination[0m > 2022-04-01 09:09:59 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - Called close() on [MultipartOutputStream for parts 1 - 10000]
2022-04-01 09:10:00 [43mdestination[0m > 2022-04-01 09:10:00 [32mINFO[m a.m.s.StreamTransferManager(uploadStreamPart):558 - [Manager uploading to s3_path/dt=2022-03-31/53a8771e-8f2b-474a-828d-3e3194cde4ec3102560680272769070.jsonl.gz with id YcAuBuqWe...fKmMXng--]: Finished uploading [Part number 1 containing 115.44 MB]
2022-04-01 09:10:01 [43mdestination[0m > 2022-04-01 09:10:01 [32mINFO[m a.m.s.StreamTransferManager(complete):395 - [Manager uploading to s3_path/dt=2022-03-31/53a8771e-8f2b-474a-828d-3e3194cde4ec3102560680272769070.jsonl.gz with id YcAuBuqWe...fKmMXng--]: Completed
2022-04-01 09:10:01 [43mdestination[0m > 2022-04-01 09:10:01 [32mINFO[m i.a.i.d.r.FileBuffer(deleteFile):81 - Deleting tempFile data 53a8771e-8f2b-474a-828d-3e3194cde4ec3102560680272769070.jsonl.gz
2022-04-01 09:10:01 [43mdestination[0m > 2022-04-01 09:10:01 [32mINFO[m i.a.i.d.r.SerializedBufferingStrategy(close):119 - Closing buffer for stream billing_entry
2022-04-01 09:10:01 [43mdestination[0m > 2022-04-01 09:10:01 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):169 - Completed integration: io.airbyte.integrations.destination.s3.S3Destination
2022-04-01 09:10:28 [32mINFO[m i.a.v.j.JsonSchemaValidator(test):56 - JSON schema validation failed. 
errors: $.flattening: is missing but it is required, $.format_type: does not have a value in the enumeration [CSV]
```

</details>

## Steps to Reproduce
1. Create postgresql source connector
2. Create s3 destination connector
3. Create connection using the connectors
4. start sync

This error keep happening even upgrading version of connectors. I can't upgrade postgres connector because there's a bug with next versions and my CI/CD flow using the fetchSchemas endpoint in API. I hope you guys could help me with this cause it's a high priority here in my team.

**Comment by leoalmeidasant** [comment]
Always when sync fails, the next attempt starts without state, there's the log:

```
2022-04-01 09:11:44 source > 2022-04-01 09:11:44 INFO i.a.i.s.r.StateManager(createCursorInfoForStream):118 - No cursor field set in catalog but not present in state. Stream: AirbyteStreamNameNamespacePair{name='billing_entry', namespace='ifood_fleet_driver_income'}, New Cursor Field: last_modified_date. Resetting cursor value
```

**Comment by sherifnada** [comment]
cc @grishick

**Comment by grishick** [comment]
Currently PG source is expected to handle 50GB

Exit criteria: 
 - identify the root cause of the failure
 - file an issue for the solution (even if it is just a recommendation for adjusting container resources)

Size estimate: L (one sprint)

**Comment by tuliren** [comment]
@leoalmeidasant, would you mind sharing the schemas of the tables of the Postgres database in the failed connection? We are particularly interested in if there is any large columns (like text or json blob). This would help us reproduce and debug this issue. Thanks.

**Comment by tuliren** [comment]
Cannot reproduce without more information such as the database schema. Also the reported Postgres source version `0.4.4` did not include the latest optimization to adjust the fetch size. So it is known that if any table has large rows, it can fail due to OOME.

The recommendations are:
1. Upgrade to the latest Postgres source (`0.4.12`).
2. Use the default S3 part size.
  - Leave the part size parameter empty. According to the log, it looks like currently it is set to 256 MB.

Will close for now.
