### ISSUE TITLE
Postgres Destination regularly experiences OOM errors when syncing from Github

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#11721]
On Airbyte Cloud, consider the following [sync](https://cloud.airbyte.io/workspaces/8b2fefd8-6bc6-4a58-9dd2-1764d1dfb8b4/connections/b8baf2f2-f9e0-49fb-b0e9-54756ded1988/status) - [log](https://cloud.airbyte.io/workspaces/8b2fefd8-6bc6-4a58-9dd2-1764d1dfb8b4/connections/b8baf2f2-f9e0-49fb-b0e9-54756ded1988/status#109048::2) from `Github` to `Postgres`.  The sync fails with the following error:

```
2022-04-04 19:26:46 destination > 2022-04-04 19:26:46 ERROR i.a.i.b.IntegrationRunner(consumeWriteStream):149 - Received invalid message: {"type":"RECORD","record":{"stream":"github_issue_events","data":{"id":3827581254,"node_id":"MDE5OkhlYWRSZWZEZWxldGVkRXZlbnQzODI3NTgxMjU0","url":"https://api.github.com/repos/actionhero/example-with-custom-env/issues/events/3827581254","actor":{"login":"evantahler","id":303226,"node_id":"MDQ6VXNlcjMwMzIyNg==","avatar_url":"https://avatars.githubusercontent.com/u/303226?v=4","gravatar_id":"","url":"https://api.github.com/users/evantahler","html_url":"https://github.com/evantahler","followers_url":"https://api.github.com/users/evantahler/followers","following_url":"https://api.github.com/users/evantahler/following{/other_user}","gists_url":"https://api.github.com/users/evantahler/gists{/gist_id}","starred_url":"https://api.github.com/users/evantahler/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/evantahler/subscriptions","organizations_url":"https://api.github.com/users/evantahler/orgs","repos_url":"https://api.github.com/users/evantahler/repos","events_url":"https://api.github.com/users/evantahler/events{/privacy}","received_events_url":"https://api.github.com/users/evantahler/received_events","type":"User","site_admin":false},"event":"head_ref_deleted","commit_id":null,"commit_url":null,"created_at":"2020-10-01T05:35:07Z","issue":{"url":"https://api.github.com/repos/actionhero/example-with-custom-env/issues/36","repository_url":"https://api.github.com/repos/actionhero/example-with-custom-env","labels_url":"https://api.github.com/repos/actionhero/example-with-custom-env/issues/36/labels{/name}","comments_url":"https://api.github.com/repos/actionhero/example-with-custom-env/issues/36/comments","events_url":"https://api.github.com/repos/actionhero/example-with-custom-env/issues/36/events","html_url":"https://github.com/actionhero/example-with-custom-env/pull/36","id":712492650,"node_id":"MDExOlB1bGxSZXF1ZXN0NDk1OTYyOTgx","number":36,"title":"Bump prettier from 2.1.1 to 2.1.2","user":{"login":"dependabot[bot]","id":49699333,"node_id":"MDM6Qm90NDk2OTkzMzM=","avatar_url":"https://avatars.githubusercontent.com/in/29110?v=4","gravatar_id":"","url":"https://api.github.com/users/dependabot%5Bbot%5D","html_url":"https://github.com/apps/dependabot","followers_url":"https://api.github.com/users/dependabot%5Bbot%5D/followers","following_url":"https://api.github.com/users/dependabot%5Bbot%5D/following{/other_user}","gists_url":"https://api.github.com/users/dependabot%5Bbot%5D/gists{/gist_id}","starred_url":"https://api.github.com/users/dependabot%5Bbot%5D/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/dependabot%5Bbot%5D/subscriptions","organizations_url":"https://api.github.com/users/dependabot%5Bbot%5D/orgs","repos_url":"https://api.github.com/users/dependabot%5Bbot%5D/repos","events_url":"https://api.github.com/users/dependabot%5Bbot%5D/events{/privacy}","received_events_url":"https://api.github.com/users/dependabot%5Bbot%5D/received_events","type":"Bot","site_admin":false},"labels":[{"id":2217744916,"node_id":"MDU6TGFiZWwyMjE3NzQ0OTE2","url":"https://api.github.com/repos/actionhero/example-with-custom-env/labels/dependencies","name":"dependencies","color":"0366d6","default":false,"description":"Pull requests that update a dependency file"}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2020-10-01T05:18:41Z","updated_at":"2020-10-01T05:35:07Z","closed_at":"2020-10-01T05:35:06Z","author_association":"CONTRIBUTOR","active_lock_reason":null,"draft":false,"pull_request":{"url":"https://api.github.com/repos/actionhero/example-with-custom-env/pulls/36","html_url":"https://github.com/actionhero/example-with-custom-env/pull/36","diff_url":"https://github.com/actionhero/example-with-custom-env/pull/36.diff","patch_url":"https://github.com/actionhero/example-with-custom-env/pull/36.patch","merged_at":"2020-10-01T05:35:06Z"},"body":"Bumps [prettier](https://github.com/prettier/prettier) from 2.1.1 to 2.1.2.\n<details>\n<summary>Release notes</summary>\n<p><em>Sourced from <a href=\"https://github.com/prettier/prettier/releases\">prettier's releases</a>.</em></p>\n<blockquote>\n<h2>2.1.2</h2>\n<p><a href=\"https://github.com/prettier/prettier/blob/master/CHANGELOG.md#212\">🔗Changelog</a></p>\n</blockquote>\n</details>\n<details>\n<summary>Changelog</summary>\n<p><em>Sourced from <a href=\"https://github.com/prettier/prettier/blob/master/CHANGELOG.md\">prettier's changelog</a>.</em></p>\n<blockquote>\n<h1>2.1.2</h1>\n<p><a href=\"https://github.com/prettier/prettier/compare/2.1.1...2.1.2\">diff</a></p>\n<h4>Fix formatting for directives in fields (<a href=\"https://github-redirect.dependabot.com/prettier/prettier/pull/9116\">#9116</a> by <a href=\"https://github.com/sosukesuzuki\">@sosukesuzuki</a>)</h4>\n<!-- raw HTML omitted -->\n<pre lang=\"graphql\"><code># Input\ntype Query {\n  someQuery(id: ID!, someOtherData: String!): String! @deprecated @isAuthenticated\n  versions: Versions!\n}\n<h1>Prettier stable</h1>\n<p>type Query {\nsomeQuery(id: ID!, someOtherData: String!): String!\n<a href=\"https://github.com/deprecated\">@deprecated</a>\n<a href=\"https://github.com/isAuthenticated\">@isAuthenticated</a>\nversions: Versions!\n}</p>\n<h1>Prettier master</h1>\n<p>type Query {\nsomeQuery(id: ID!, someOtherData: String!): String!\n<a href=\"https://github.com/deprecated\">@deprecated</a>\n<a href=\"https://github.com/isAuthenticated\">@isAuthenticated</a>\nversions: Versions!\n}</p>\n<p></code></pre></p>\n<h4>Fix line breaks for CSS in JS (<a href=\"https://github-redirect.dependabot.com/prettier/prettier/pull/9136\">#9136</a> by <a href=\"https://github.com/sosukesuzuki\">@sosukesuzuki</a>)</h4>\n<!-- raw HTML omitted -->\n<pre lang=\"js\"><code>// Input\nstyled.div`\n  // prettier-ignore\n  @media (aaaaaaaaaaaaa) {\n\tz-index: ${(props) =&gt; (props.isComplete ? '1' : '0')};\n  }\n`;\nstyled.div`\n  ${props =&gt; getSize(props.$size.xs)}\n  ${props =&gt; getSize(props.$size.sm, 'sm')}\n  ${props =&gt; getSize(props.$size.md, 'md')}\n`;\n<p>&lt;/tr&gt;&lt;/table&gt;\n</code></pre></p>\n</blockquote>\n<p>... (truncated)</p>\n</details>\n<details>\n<summary>Commits</summary>\n<ul>\n<li><a href=\"https://github.com/prettier/prettier/commit/8eb8f9ed2dc5eb1c3e6f787e5a5e6fe68af2b8d1\"><code>8eb8f9e</code></a> Release 2.1.2</li>\n<li><a href=\"https://github.com/prettier/prettier/commit/f75844a453beb6cb16791c14e5ff738c02d0b4df\"><code>f75844a</code></a> Fix changelog</li>\n<li><a href=\"https://github.com/prettier/prettier/commit/9153bf20ac2dfcd525b5dd3f3b37d9b6005d20bc\"><code>9153bf2</code></a> Build(deps): Bump yaml-unist-parser from 1.3.0 to 1.3.1 (<a href=\"https://github-redirect.dependabot.com/prettier/prettier/issues/9169\">#9169</a>)</li>\n<li><a href=\"https://github.com/prettier/prettier/commit/ec1b4193079a625633dd0dc86f9a9217a3ad9d7e\"><code>ec1b419</code></a> YAML: Fix printing doubles a blank line before a comment (<a href=\"https://github-redirect.dependabot.com/prettier/prettier/issues/9143\">#9143</a>)</li>\n<li><a href=\"https://github.com/prettier/prettier/commit/ab9474eacc9c883e588ef2500c6230057328ade5\"><code>ab9474e</code></a> Fix line breaks for CSS in JS (<a href=\"https://github-redirect.dependabot.com/prettier/prettier/issues/9136\">#9136</a>)</li>\n<li><a href=\"https://github.com/prettier/prettier/commit/d5da779cb195443c935fd7171f5e81141e2f62e5\"><code>d5da779</code></a> GraphQL: Fix formatting for directives in fields (<a href=\"https://github-redirect.dependabot.com/prettier/prettier/issues/9116\">#9116</a>)</li>\n<li><a href=\"https://github.com/prettier/prettier/commit/a8363197118e530d948978da6e5c414a765ba9c0\"><code>a836319</code></a> Bump Prettier dependency to 2.1.1</li>\n<li>See full diff in <a href=\"https://github.com/prettier/prettier/compare/2.1.1...2.1.2\">compare view</a></li>\n</ul>\n</details>\n<br />\n\n\n[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=prettier&package-manager=npm_and_yarn&previous-version=2.1.1&new-version=2.1.2)](https://docs.github.com/en/github/managing-security-vulnerabilities/configuring-github-dependabot-security-updates)\n\nDependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.\n\n[//]: # (dependabot-automerge-start)\n[//]: # (dependabot-automerge-end)\n\n---\n\n<details>\n<summary>Dependabot commands and options</summary>\n<br />\n\nYou can trigger Dependabot actions by commenting on this PR:\n- `@dependabot rebase` will rebase this PR\n- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it\n- `@dependabot merge` will merge this PR after your CI passes on it\n- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it\n- `@dependabot cancel merge` will cancel a previously requested merge and block automerging\n- `@dependabot reopen` will reopen this PR if it is closed\n- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually\n- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)\n- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)\n- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)\n\n\n</details>","reactions":{"url":"https://api.github.com/repos/actionhero/example-with-custom-env/issues/36/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/actionhero/example-with-custom-env/issues/36/timeline","performed_via_github_app":null},"performed_via_github_app":null,"repository":"actionhero/example-with-custom-env"},"emitted_at":1649100389591}}
2022-04-04 19:26:50 replication-orchestrator > Records read: 20000 (162 MB)
2022-04-04 19:26:57 destination > 2022-04-04 19:26:57 INFO i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):60 - Airbyte message consumer: succeeded.
2022-04-04 19:26:58 destination > 2022-04-04 19:26:58 INFO i.a.i.d.b.BufferedStreamConsumer(close):201 - executing on success close procedure.
2022-04-04 19:27:18 destination > Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
2022-04-04 19:27:18 destination > 	at java.base/java.lang.StringUTF16.compress(StringUTF16.java:161)
2022-04-04 19:27:18 destination > 	at java.base/java.lang.String.<init>(String.java:4496)
2022-04-04 19:27:18 destination > 	at java.base/java.lang.String.<init>(String.java:300)
2022-04-04 19:27:18 destination > 	at com.fasterxml.jackson.core.util.TextBuffer.contentsAsString(TextBuffer.java:453)
2022-04-04 19:27:18 destination > 	at com.fasterxml.jackson.core.io.SegmentedStringWriter.getAndClear(SegmentedStringWriter.java:85)
2022-04-04 19:27:18 destination > 	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3828)
2022-04-04 19:27:18 destination > 	at io.airbyte.commons.json.Jsons.serialize(Jsons.java:38)
2022-04-04 19:27:18 destination > 	at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.acceptTracked(BufferedStreamConsumer.java:149)
2022-04-04 19:27:18 destination > 	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.accept(FailureTrackingAirbyteMessageConsumer.java:46)
```

We (+ @sherifnada) then updated the memory limit on the container manually to `1Gi` and [synced](https://cloud.airbyte.io/workspaces/7eadb73a-1992-4a00-808a-90e2bf236e3e/connections/fdb750a5-ad7c-43ca-b688-487cac918a6f/status) the same data again, and it worked!  /Maybe/ the solution is to globally increase the memory on all Postgres pods, but there might also be an underlying memory leak to check out. 

## Environment

```
Airbyte Version: 0.35.64-alpha-cloud
Source: GitHub (0.2.25)
Destination: Postgres (0.1.3)
```

**Comment by etsybaev** [comment]
Hi @evantahler.
Could you please provide a full set of logs? How much memory it was when it failed?  I tried to run such migration and here is how it was me from the resource-consuming perspective. I see you provided a link of the send sync. but it's not available for me for some reason, getting such error:
"Oops! Something went wrong…You don’t have permission to access this page." 
Thanks

![Selection_293.png](https://images.zenhubusercontent.com/627269f99b780c901a3d24e2/a6b12a9b-d32c-4a79-a96f-0caa89a09873I)

**Comment by evantahler** [comment]
I'll close this issue - we've since made progress on both the source and destination.  The original failure happened with a pod of 500Mb of memory, and succeeded with 1Gb

I've attached the full logs for posterity [logs-109048.txt](https://github.com/airbytehq/airbyte/files/8904182/logs-109048.txt)
