### ISSUE TITLE
Snowflake Normalization failed: KeyError: 'password'

### ISSUE THREAD

**Issue by autronix** [airbytehq/airbyte#11814]
## Environment
* **Airbyte version**:  0.29.15-alpha
* **OS Version / Instance**: AWS EC2
* **Deployment**:  Docker
* **Source Connector and version**: Mysql 0.5.6
* **Destination Connector and version**: Snowflake 0.4.24
* **Severity**: Critical
* **Step where error happened**:  Sync job

## Current Behavior
Start sync, when it reaches normalizations, it triggers an error and fails. 
With the same setup (Mysql => Snowflake) for a different database, this is working fine; same settings on the new connector is showing the error shown below.

## Expected Behavior
Sync normalization should complete.

## Logs
<details>
<summary>LOG</summary> 

```
2022-04-06 20:46:00 INFO () DefaultNormalizationWorker(run):63 - Running normalization.
2022-04-06 20:46:00 INFO () LineGobbler(voidCall):85 - Checking if airbyte/normalization:0.1.42 exists...
2022-04-06 20:46:00 INFO () LineGobbler(voidCall):85 - airbyte/normalization:0.1.42 was found locally.
2022-04-06 20:46:00 INFO () DockerProcessFactory(create):146 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/4838/0/normalize --network host --log-driver none airbyte/normalization:0.1.42 run --integration-type snowflake --config destination_config.json --catalog destination_catalog.json
2022-04-06 20:46:00 INFO () LineGobbler(voidCall):85 - Running: transform-config --config destination_config.json --integration-type snowflake --out /data/4838/0/normalize
2022-04-06 20:46:01 INFO () LineGobbler(voidCall):85 - Namespace(config='destination_config.json', integration_type=<DestinationType.snowflake: 'snowflake'>, out='/data/4838/0/normalize')
2022-04-06 20:46:01 INFO () LineGobbler(voidCall):85 - transform_snowflake
2022-04-06 20:46:01 ERROR () LineGobbler(voidCall):85 - Traceback (most recent call last):
2022-04-06 20:46:01 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/bin/transform-config", line 8, in <module>
2022-04-06 20:46:01 ERROR () LineGobbler(voidCall):85 -     sys.exit(main())
2022-04-06 20:46:01 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.8/site-packages/normalization/transform_config/transform.py", line 196, in main
2022-04-06 20:46:01 ERROR () LineGobbler(voidCall):85 -     TransformConfig().run(args)
2022-04-06 20:46:01 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.8/site-packages/normalization/transform_config/transform.py", line 49, in run
2022-04-06 20:46:01 ERROR () LineGobbler(voidCall):85 -     transformed_config = self.transform(integration_type, original_config)
2022-04-06 20:46:01 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.8/site-packages/normalization/transform_config/transform.py", line 76, in transform
2022-04-06 20:46:01 ERROR () LineGobbler(voidCall):85 -     transformed_integration_config = {
2022-04-06 20:46:01 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.8/site-packages/normalization/transform_config/transform.py", line 152, in transform_snowflake
2022-04-06 20:46:01 ERROR () LineGobbler(voidCall):85 -     "password": config["password"],
2022-04-06 20:46:01 ERROR () LineGobbler(voidCall):85 - KeyError: 'password'
2022-04-06 20:46:01 INFO () TemporalAttemptExecution(lambda$getWorkerThread$2):155 - Completing future exceptionally...
io.airbyte.workers.WorkerException: Normalization Failed.
```

</details>

## Steps to Reproduce
1. Create Mysql source, properly configured
1. Create Snowflake destination, properly configured
1. Connect the two
1. Hit sync.

┆Issue is synchronized with this [Monday item](https://airbyte-bunch.monday.com/boards/2536787439/pulses/2537089700) by [Unito](https://www.unito.io)

**Comment by autronix** [comment]
Reverting to snowflake v 0.4.22, setting the SF user password again and saving seems to have solved the issue.

**Comment by marcosmarxm** [comment]
@autronix please upgrade Airbyte to latest version, latest vrsion of Snowflake depends of Airbyte 0.35.60+ version

**Comment by marcosmarxm** [comment]
Closed after adding the info in Snowflake changelog alerting users about the version dependency of Snowflake and Airbyte.
