### ISSUE TITLE
Airbyte Scheduler does not recover after unexpected database restart

### ISSUE THREAD

**Issue by cjwooo** [airbytehq/airbyte#11812]
## Environment
* **Airbyte version**:  example is 0.33.8-alpha
* **OS Version / Instance**: AWS EC2 Linux
* **Deployment**: Docker
* **Source Connector and version**: (if applicable example Salesforce 0.2.3) 
* **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
* **Severity**: High
* **Step where error happened**: Normal operations

## Current Behavior
Our Airbyte instance runs on EC2 and uses a Postgres RDS. The RDS was restarted automatically for a minor Postgres version upgrade. The Airbyte Scheduler did not reestablish its database connection afterwards, and so scheduled connector syncs were not executed. Other airbyte operations, including manual syncs, worked fine.

## Expected Behavior
The Scheduler should recover gracefully and reconnect to its database.

## Logs
2022-04-04 00:08:39 ERROR () JobSubmitter(run):81 - Job Submitter Error
org.jooq.exception.DataAccessException: Error getting connection from data source org.apache.commons.dbcp2.BasicDataSource199fcfe1
	at org.jooq_3.13.4.POSTGRES.debug(Unknown Source) ~[?:?]
	at org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:86) ~[jooq-3.13.4.jar:?]
	at org.jooq.impl.DefaultExecuteContext.connection(DefaultExecuteContext.java:647) ~[jooq-3.13.4.jar:?]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:334) ~[jooq-3.13.4.jar:?]
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:354) ~[jooq-3.13.4.jar:?]
	at org.jooq.impl.DefaultDSLContext.fetch(DefaultDSLContext.java:892) ~[jooq-3.13.4.jar:?]
	at io.airbyte.scheduler.persistence.DefaultJobPersistence.lambda$getNextJob$20(DefaultJobPersistence.java:396) ~[io.airbyte.airbyte-scheduler-persistence-0.33.8-alpha.jar:?]
	at io.airbyte.db.Database.query(Database.java:27) ~[io.airbyte.airbyte-db-lib-0.33.8-alpha.jar:?]
	at io.airbyte.db.ExceptionWrappingDatabase.query(ExceptionWrappingDatabase.java:23) ~[io.airbyte.airbyte-db-lib-0.33.8-alpha.jar:?]
	at io.airbyte.scheduler.persistence.DefaultJobPersistence.getNextJob(DefaultJobPersistence.java:395) ~[io.airbyte.airbyte-scheduler-persistence-0.33.8-alpha.jar:?]
	at io.airbyte.scheduler.app.JobSubmitter.run(JobSubmitter.java:74) ~[io.airbyte.airbyte-scheduler-app-0.33.8-alpha.jar:?]
	at io.airbyte.scheduler.app.SchedulerApp.lambda$start$1(SchedulerApp.java:148) ~[io.airbyte.airbyte-scheduler-app-0.33.8-alpha.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]

## Steps to Reproduce
1. Deploy Airbyte conected to external database.
1. Restart database.
1. Scheduled syncs no longer run.

## Are you willing to submit a PR?
Maybe, but not familiar with internals.

┆Issue is synchronized with this [Monday item](https://airbyte-bunch.monday.com/boards/2536787439/pulses/2537090377) by [Unito](https://www.unito.io)

**Comment by jvstein** [comment]
We just noticed something similar in our Airbyte deployment as well. The RDS maintenance window was right around the same time.

**Comment by cjwooo** [comment]
@cgardens What is the timeline for "scheduler going away"?

**Comment by marcosmarxm** [comment]
@cgardens should we close this issue now Airbyte doesn't have the `airbyte-scheduler` anymore and use only temporal?
