### ISSUE TITLE
Import configuration fails

### ISSUE THREAD

**Issue by yzislin** [airbytehq/airbyte#12012]
## Environment
- **Airbyte version**:  0.35.67-alpha
- **OS Version / Instance**: Ubuntu 20.04
- **Deployment**: Docker
- **Severity**:  High
- **Step where error happened**: Configuration import

## Current Behavior
Error on importing freshly exported config from different instance (the same version of airbyte).

## Expected Behavior
Successful import

## Logs

<details>
<summary>LOG</summary> 
2022-04-14 12:23:40 ERROR i.a.s.h.ArchiveHandler(importInternal):140 - Import failed
java.lang.RuntimeException: io.airbyte.validation.json.JsonValidationException: json schema validation failed when comparing the data to the json schema.
Errors: $.catalog: null found, object expected
Schema:
{
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "$id" : "https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/AttemptFailureSummary.yaml",
  "title" : "ActorCatalog",
  "description" : "Catalog of an actor.",
  "type" : "object",
  "additionalProperties" : false,
  "required" : [ "id", "catalog", "catalogHash" ],
  "properties" : {
    "id" : {
      "type" : "string",
      "format" : "uuid"
    },
    "catalog" : {
      "type" : "object",
      "existingJavaType" : "com.fasterxml.jackson.databind.JsonNode"
    },
    "catalogHash" : {
      "type" : "string"
    }
  }
}
        at io.airbyte.server.ConfigDumpImporter.lambda$readConfigsFromArchive$2(ConfigDumpImporter.java:208) ~[io.airbyte-airbyte-server-0.35.67-alpha.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:1003) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at io.airbyte.config.persistence.DatabaseConfigPersistence.lambda$replaceAllConfigs$87(DatabaseConfigPersistence.java:1368) ~[io.airbyte.airbyte-config-persistence-.35.67-alpha.jar:?]
        at io.airbyte.db.Database.lambda$transaction$0(Database.java:31) ~[io.airbyte.airbyte-db-lib-0.35.67-alpha.jar:?]
        at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$0(DefaultDSLContext.java:564) ~[jooq-3.13.4.jar:?]
        at org.jooq.impl.Tools$12$1.block(Tools.java:4926) ~[jooq-3.13.4.jar:?]
        at java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463) ~[?:?]
        at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434) ~[?:?]
        at org.jooq.impl.Tools$12.get(Tools.java:4923) ~[jooq-3.13.4.jar:?]
        at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:616) ~[jooq-3.13.4.jar:?]
        at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:533) ~[jooq-3.13.4.jar:?]
        at io.airbyte.db.Database.transaction(Database.java:31) ~[io.airbyte.airbyte-db-lib-0.35.67-alpha.jar:?]
        at io.airbyte.db.ExceptionWrappingDatabase.transaction(ExceptionWrappingDatabase.java:31) ~[io.airbyte.airbyte-db-lib-0.35.67-alpha.jar:?]
        at io.airbyte.config.persistence.DatabaseConfigPersistence.replaceAllConfigs(DatabaseConfigPersistence.java:1276) ~[io.airbyte.airbyte-config-persistence-0.35.67-alha.jar:?]
        at io.airbyte.config.persistence.ValidatingConfigPersistence.replaceAllConfigs(ValidatingConfigPersistence.java:114) ~[io.airbyte.airbyte-config-persistence-0.35.67alpha.jar:?]
        at io.airbyte.config.persistence.ConfigRepository.replaceAllConfigsNoSecrets(ConfigRepository.java:984) ~[io.airbyte.airbyte-config-persistence-0.35.67-alpha.jar:?]
        at io.airbyte.config.persistence.SecretsRepositoryWriter.replaceAllConfigs(SecretsRepositoryWriter.java:263) ~[io.airbyte.airbyte-config-persistence-0.35.67-alpha.jr:?]
        at io.airbyte.server.ConfigDumpImporter.importConfigsFromArchive(ConfigDumpImporter.java:190) ~[io.airbyte-airbyte-server-0.35.67-alpha.jar:?]
        at io.airbyte.server.ConfigDumpImporter.importDataWithSeed(ConfigDumpImporter.java:135) ~[io.airbyte-airbyte-server-0.35.67-alpha.jar:?]
        at io.airbyte.server.handlers.ArchiveHandler.lambda$importData$0(ArchiveHandler.java:106) ~[io.airbyte-airbyte-server-0.35.67-alpha.jar:?]
        at io.airbyte.server.handlers.ArchiveHandler.importInternal(ArchiveHandler.java:137) ~[io.airbyte-airbyte-server-0.35.67-alpha.jar:?]
        at io.airbyte.server.handlers.ArchiveHandler.importData(ArchiveHandler.java:106) ~[io.airbyte-airbyte-server-0.35.67-alpha.jar:?]
        at io.airbyte.server.apis.ConfigurationApi.lambda$importArchive$92(ConfigurationApi.java:847) ~[io.airbyte-airbyte-server-0.35.67-alpha.jar:?]
        at io.airbyte.server.apis.ConfigurationApi.execute(ConfigurationApi.java:871) ~[io.airbyte-airbyte-server-0.35.67-alpha.jar:?]
        at io.airbyte.server.apis.ConfigurationApi.importArchive(ConfigurationApi.java:847) ~[io.airbyte-airbyte-server-0.35.67-alpha.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[jersey-server2.31.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) ~[jersey-server-2.31.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) ~[jersey-server-2.31.jar:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) ~[jerseyserver-2.31.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[jersey-server-2.31.jar:?
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469) ~[jersey-server-2.31.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391) ~[jersey-server-2.31.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80) ~[jersey-server-2.31.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253) ~[jersey-server-2.31.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[jersey-common-2.31.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[jersey-common-2.31.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-2.31.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-2.31.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[jersey-common-2.31.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[jersey-common-2.31.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232) ~[jersey-server-2.31.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680) ~[jersey-server-2.31.jar:?]
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394) ~[jersey-container-servlet-core-2.31.jar:?]
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) ~[jersey-container-servlet-core-2.31.jar:?]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366) ~[jersey-container-servlet-core-2.31.jar:?]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319) ~[jersey-container-servlet-core-2.31.jar:?]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) ~[jersey-container-servlet-core-2.31.jar:?]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:569) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1377) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:507) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.server.Server.handle(Server.java:501) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: io.airbyte.validation.json.JsonValidationException: json schema validation failed when comparing the data to the json schema.
Errors: $.catalog: null found, object expected
Schema:
{
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "$id" : "https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/AttemptFailureSummary.yaml",
  "title" : "ActorCatalog",
  "description" : "Catalog of an actor.",
  "type" : "object",
  "additionalProperties" : false,
  "required" : [ "id", "catalog", "catalogHash" ],
  "properties" : {
    "id" : {
      "type" : "string",
      "format" : "uuid"
    },
    "catalog" : {
      "type" : "object",
      "existingJavaType" : "com.fasterxml.jackson.databind.JsonNode"
    },
    "catalogHash" : {
      "type" : "string"
    }
  }
}
        at io.airbyte.validation.json.JsonSchemaValidator.ensure(JsonSchemaValidator.java:68) ~[io.airbyte-airbyte-json-validation-0.35.67-alpha.jar:?]
        at io.airbyte.server.ConfigDumpImporter.validateJson(ConfigDumpImporter.java:220) ~[io.airbyte-airbyte-server-0.35.67-alpha.jar:?]
        at io.airbyte.server.ConfigDumpImporter.lambda$readConfigsFromArchive$2(ConfigDumpImporter.java:205) ~[io.airbyte-airbyte-server-0.35.67-alpha.jar:?]
        ... 84 more

</details>

## Steps to Reproduce
1. Export Config
2. Import Config
3.

**Comment by andresbravog** [comment]
This is happening to us also, the problem resides in new version `0.35.67-alpha` not taking `EXPOSE_SECRETS_IN_EXPORT=true` flag in consideration and exporting the config with `password: "**********"` from in both `SOURCE_CONNECTION.yaml` and `DESTINATION_CONNECTION.yaml`.

**Comment by yzislin** [comment]
Interesting.
Are you getting some kind of unique error message? Mine just complains about catalog object missing or something of that nature.

**Comment by andresbravog** [comment]
@yzislin your issue is probably related to a previous failure on older versions, probably will be related to `ACTOR_CATALOG.yaml ACTOR_CATALOG_FETCH_EVENT.yaml` if you unpack the configuration, remove those files and pack it again, it will probably work.

It would be interesting to see if your exported configuration contains secrets on `SOURCE_CONNECTION.yaml` as mine does not and that information is going to be lost on the export/import process.

**Comment by marcosmarxm** [comment]
I tried to simulate the issue. Version 0.36.6-alpha
Edited first the env variable (`EXPORT_SECRETS_IN_EXPORT`) to true
export and import the file to a new instance.
The server throw and error but I click in continuing using the app and my connections showed in the UI.
```
2022-05-02 23:08:18 ERROR i.a.s.RequestLogger(filter):110 - REQ 172.21.0.3 POST 404 /api/v1/workspaces/get - {"workspaceId":"832d7f00-6d79-4cc8-b323-37e3d8b0d034"}
```

**Comment by marcosmarxm** [comment]
Closed because this feature is deprecated.
