### ISSUE TITLE
Intercom: always fails when syncing conversations

### ISSUE THREAD

**Issue by nauxliu** [airbytehq/airbyte#12094]
<!-- 
Welcome to Airbyte!
## Environment
Airbyte Version: 0.35.63-alpha
Source: Intercom (0.1.16)
Destination: Snowflake (0.4.24)

## Current Behavior
The sync always fails when syncing the conversation stream

## Logs

```
2022-04-16 05:48:44 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 143000 (342 MB)
2022-04-16 05:49:52 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 144000 (344 MB)
2022-04-16 05:51:02 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 145000 (347 MB)
2022-04-16 05:52:17 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 146000 (350 MB)
2022-04-16 05:53:28 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 147000 (353 MB)
2022-04-16 05:54:36 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 148000 (355 MB)
2022-04-16 05:55:42 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 149000 (358 MB)
2022-04-16 05:56:49 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 150000 (360 MB)
2022-04-16 05:57:55 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 151000 (363 MB)
2022-04-16 05:59:03 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 152000 (365 MB)
2022-04-16 06:00:07 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 153000 (367 MB)
2022-04-16 06:01:27 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 154000 (370 MB)
2022-04-16 06:02:37 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 155000 (372 MB)
2022-04-16 06:03:51 [32mINFO[m i.a.v.j.JsonSchemaValidator(test):56 - JSON schema validation failed. 
errors: $.method: does not have a value in the enumeration [Standard]
2022-04-16 06:03:41 [32mINFO[m i.a.w.t.TemporalAttemptExecution(lambda$getCancellationChecker$3):191 - Running sync worker cancellation...
2022-04-16 06:03:41 [32mINFO[m i.a.w.DefaultReplicationWorker(cancel):377 - Cancelling replication worker...
2022-04-16 06:03:48 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 156000 (374 MB)
2022-04-16 06:03:51 [32mINFO[m i.a.w.DefaultReplicationWorker(cancel):385 - Cancelling destination...
2022-04-16 06:03:51 [32mINFO[m i.a.w.p.a.DefaultAirbyteDestination(cancel):125 - Attempting to cancel destination process...
2022-04-16 06:03:51 [32mINFO[m i.a.w.p.a.DefaultAirbyteDestination(cancel):130 - Destination process exists, cancelling...
2022-04-16 06:03:51 [32mINFO[m i.a.w.p.KubePodProcess(destroy):640 - (pod: airbyte / destination-snowflake-sync-1686-2-emahc) - Destroying Kube process.
2022-04-16 06:03:51 [32mINFO[m i.a.w.DefaultReplicationWorker(run):163 - One of source or destination thread complete. Waiting on the other.
2022-04-16 06:03:51 [33mWARN[m i.a.c.i.LineGobbler(voidCall):86 - airbyte-destination gobbler IOException: Socket closed. Typically happens when cancelling a job.
2022-04-16 06:03:51 [32mINFO[m i.a.w.p.KubePodProcess(close):695 - (pod: airbyte / destination-snowflake-sync-1686-2-emahc) - Closed all resources for pod
2022-04-16 06:03:51 [32mINFO[m i.a.w.p.KubePodProcess(destroy):646 - (pod: airbyte / destination-snowflake-sync-1686-2-emahc) - Destroyed Kube process.
2022-04-16 06:03:51 [32mINFO[m i.a.w.p.a.DefaultAirbyteDestination(cancel):132 - Cancelled destination process!
2022-04-16 06:03:51 [32mINFO[m i.a.w.DefaultReplicationWorker(cancel):392 - Cancelling source...
2022-04-16 06:03:51 [32mINFO[m i.a.w.p.a.DefaultAirbyteSource(cancel):142 - Attempting to cancel source process...
2022-04-16 06:03:51 [32mINFO[m i.a.w.p.a.DefaultAirbyteSource(cancel):147 - Source process exists, cancelling...
2022-04-16 06:03:51 [32mINFO[m i.a.w.p.KubePodProcess(destroy):640 - (pod: airbyte / source-intercom-sync-1686-2-nmjub) - Destroying Kube process.
2022-04-16 06:03:51 [33mWARN[m i.a.c.i.LineGobbler(voidCall):86 - airbyte-source gobbler IOException: Socket closed. Typically happens when cancelling a job.
2022-04-16 06:03:51 [32mINFO[m i.a.w.DefaultReplicationWorker(run):165 - Source and destination threads complete.
2022-04-16 06:03:51 [32mINFO[m i.a.w.p.KubePodProcess(close):695 - (pod: airbyte / source-intercom-sync-1686-2-nmjub) - Closed all resources for pod
2022-04-16 06:03:51 [32mINFO[m i.a.w.p.KubePodProcess(destroy):646 - (pod: airbyte / source-intercom-sync-1686-2-nmjub) - Destroyed Kube process.
2022-04-16 06:03:51 [32mINFO[m i.a.w.p.a.DefaultAirbyteSource(cancel):149 - Cancelled source process!
2022-04-16 06:03:51 [32mINFO[m i.a.w.t.TemporalAttemptExecution(lambda$getCancellationChecker$3):195 - Interrupting worker thread...
2022-04-16 06:03:51 [32mINFO[m i.a.w.t.TemporalAttemptExecution(lambda$getCancellationChecker$3):198 - Cancelling completable future...
2022-04-16 06:03:51 [33mWARN[m i.a.w.t.CancellationHandler$TemporalCancellationHandler(checkAndHandleCancellation):54 - Job either timed out or was cancelled.
2022-04-16 06:03:51 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):131 - Stopping cancellation check scheduling...
2022-04-16 06:03:51 [1;31mERROR[m i.a.w.DefaultReplicationWorker(run):169 - Sync worker failed.
io.airbyte.workers.WorkerException: Source process exit with code 143. This warning is normal if the job was cancelled.
	at io.airbyte.workers.protocols.airbyte.DefaultAirbyteSource.close(DefaultAirbyteSource.java:136) ~[io.airbyte-airbyte-workers-0.35.63-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:167) ~[io.airbyte-airbyte-workers-0.35.63-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:57) ~[io.airbyte-airbyte-workers-0.35.63-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:155) ~[io.airbyte-airbyte-workers-0.35.63-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
	Suppressed: java.net.SocketException: Socket closed
		at sun.nio.ch.NioSocketImpl.ensureOpenAndConnected(NioSocketImpl.java:165) ~[?:?]
		at sun.nio.ch.NioSocketImpl.beginWrite(NioSocketImpl.java:366) ~[?:?]
		at sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:411) ~[?:?]
		at sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440) ~[?:?]
		at sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826) ~[?:?]
		at java.net.Socket$SocketOutputStream.write(Socket.java:1035) ~[?:?]
		at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234) ~[?:?]
		at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:304) ~[?:?]
		at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282) ~[?:?]
		at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:132) ~[?:?]
		at java.io.OutputStreamWriter.write(OutputStreamWriter.java:205) ~[?:?]
		at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:120) ~[?:?]
		at java.io.BufferedWriter.flush(BufferedWriter.java:256) ~[?:?]
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.notifyEndOfStream(DefaultAirbyteDestination.java:98) ~[io.airbyte-airbyte-workers-0.35.63-alpha.jar:?]
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.close(DefaultAirbyteDestination.java:111) ~[io.airbyte-airbyte-workers-0.35.63-alpha.jar:?]
		at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:126) ~[io.airbyte-airbyte-workers-0.35.63-alpha.jar:?]
		at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:57) ~[io.airbyte-airbyte-workers-0.35.63-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:155) ~[io.airbyte-airbyte-workers-0.35.63-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:833) [?:?]
2022-04-16 06:03:51 [33mWARN[m i.a.w.t.CancellationHandler$TemporalCancellationHandler(checkAndHandleCancellation):54 - Job either timed out or was cancelled.
2022-04-16 06:03:51 [32mINFO[m i.a.w.DefaultReplicationWorker(run):228 - sync summary: io.airbyte.config.ReplicationAttemptSummary@271c8b0e[status=cancelled,recordsSynced=156041,bytesSynced=392738858,startTime=1650079771654,endTime=1650089031776,totalStats=io.airbyte.config.SyncStats@62fa04a5[recordsEmitted=156041,bytesEmitted=392738858,stateMessagesEmitted=4,recordsCommitted=0],streamStats=[io.airbyte.config.StreamSyncStats@13db5a19[streamName=companies,stats=io.airbyte.config.SyncStats@782ee5d4[recordsEmitted=2,bytesEmitted=729,stateMessagesEmitted=<null>,recordsCommitted=<null>]], io.airbyte.config.StreamSyncStats@3b294524[streamName=conversations,stats=io.airbyte.config.SyncStats@9c4a1c8[recordsEmitted=122856,bytesEmitted=328029191,stateMessagesEmitted=<null>,recordsCommitted=<null>]], io.airbyte.config.StreamSyncStats@4086297b[streamName=admins,stats=io.airbyte.config.SyncStats@4f0974fa[recordsEmitted=37,bytesEmitted=7424,stateMessagesEmitted=<null>,recordsCommitted=<null>]], io.airbyte.config.StreamSyncStats@3ef8185a[streamName=contacts,stats=io.airbyte.config.SyncStats@129e24ac[recordsEmitted=33146,bytesEmitted=64701514,stateMessagesEmitted=<null>,recordsCommitted=<null>]]]]
2022-04-16 06:03:51 [32mINFO[m i.a.w.DefaultReplicationWorker(run):248 - Source output at least one state message
2022-04-16 06:03:51 [33mWARN[m i.a.w.DefaultReplicationWorker(run):258 - State capture: No new state, falling back on input state: io.airbyte.config.State@996c268[state={}]
2022-04-16 06:03:51 [32mINFO[m i.a.w.t.TemporalUtils(withBackgroundHeartbeat):235 - Stopping temporal heartbeating...
2022-04-16 06:03:51 [33mWARN[m i.t.i.a.POJOActivityTaskHandler(activityFailureToResult):307 - Activity failure. ActivityId=834efa39-fbae-3c3b-a654-9e43ff43e9ab, activityType=Replicate, attempt=1
java.lang.RuntimeException: java.util.concurrent.CancellationException
	at io.airbyte.workers.temporal.TemporalUtils.withBackgroundHeartbeat(TemporalUtils.java:233) ~[io.airbyte-airbyte-workers-0.35.63-alpha.jar:?]
	at io.airbyte.workers.temporal.sync.ReplicationActivityImpl.replicate(ReplicationActivityImpl.java:106) ~[io.airbyte-airbyte-workers-0.35.63-alpha.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor453.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at io.temporal.internal.activity.POJOActivityTaskHandler$POJOActivityInboundCallsInterceptor.execute(POJOActivityTaskHandler.java:214) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.activity.POJOActivityTaskHandler$POJOActivityImplementation.execute(POJOActivityTaskHandler.java:180) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.activity.POJOActivityTaskHandler.handle(POJOActivityTaskHandler.java:120) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:204) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:164) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93) ~[temporal-sdk-1.8.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.util.concurrent.CancellationException
	at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2478) ~[?:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getCancellationChecker$3(TemporalAttemptExecution.java:201) ~[io.airbyte-airbyte-workers-0.35.63-alpha.jar:?]
	at io.airbyte.workers.temporal.CancellationHandler$TemporalCancellationHandler.checkAndHandleCancellation(CancellationHandler.java:53) ~[io.airbyte-airbyte-workers-0.35.63-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getCancellationChecker$4(TemporalAttemptExecution.java:204) ~[io.airbyte-airbyte-workers-0.35.63-alpha.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	... 3 more
```

**Comment by dudidayan1** [comment]
Happened to me also with Google Search Console -> Clickhouse

**Comment by GJMcClintock** [comment]
Experiencing the same issue with both Jira and GitHub to Snowflake - I haven't tried other sources yet because I'm 0/2 with the same error. All normalization passes but then it dumps with this JSON error.

**Comment by marcosmarxm** [comment]
This is just a warning labelled incorrectly. @nauxliu I'm closing because the log you shared it's not the complete log where we can find the root cause of failure. Feel free to post here the complete log and I'll reopen the issue.
