### ISSUE TITLE
Deleting an already-deleted connection fails with WorkflowNotFoundException

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#12160]
## Current Behavior
When calling `https://cloud.airbyte.io/api/v1/connections/delete` on an already-deleted connection, an Internal Server Error is produced, resulting from a `WorkflowNotFoundException` error coming from the server.

A fix was already attempted for this issue: [this logic](https://github.com/airbytehq/airbyte/blob/f065d361b1c1b2da91d64b6e4c07cf4fc313dc53/airbyte-workers/src/main/java/io/airbyte/workers/temporal/TemporalClient.java#L255-L281) is supposed to check if the workflow exists when deleting the connection, and start it first if it doesn't.

However, it doesn't appear that this logic works, as there have been several OC tickets showing that deleting an already-deleted connection fails: 
https://github.com/airbytehq/oncall/issues/190
https://github.com/airbytehq/oncall/issues/202

Note: this issue is currently exacerbated by the fact that when a connection is _first_ deleted, that delete request is actually successful, but the UI does not change at all to show that the delete was successful. This is what prompts users to try to perform a second delete request on the same connection. [This frontend issue](https://github.com/airbytehq/oncall/issues/195) captures that UI problem, and once solved should greatly reduce occurrences of this problem.

**The main goal of this ticket is to determine why our approach for checking if there is an active temporal workflow for the connection is not working, and fix that if possible.**

## Expected Behavior
Deleting an already-deleted connection should effectively be a no-op.

## Logs
https://console.cloud.google.com/logs/query;cursorTimestamp=2022-04-05T15:46:24.624547883Z;query=resource.labels.pod_name%3D%22airbyte-server-bfc448969-k6qfx%22%0Atimestamp%3D%222022-04-05T15:46:24.624547883Z%22%0AinsertId%3D%221xg6kk4raioz4lb1%22;timeRange=2022-04-05T15:46:24.624Z%2F2022-04-05T15:46:24.624Z--PT1H?project=prod-ab-cloud-proj

```
io.temporal.client.WorkflowNotFoundException: workflowId='connection_manager_59b17dae-ca1b-45c7-8d7b-93bae20b8478', runId='', workflowType='ConnectionManagerWorkflow'}
	at io.temporal.internal.sync.WorkflowStubImpl.signal(WorkflowStubImpl.java:98) ~[temporal-sdk-1.6.0.jar:?]
	at io.temporal.internal.sync.WorkflowInvocationHandler$SyncWorkflowInvocationHandler.signalWorkflow(WorkflowInvocationHandler.java:297) ~[temporal-sdk-1.6.0.jar:?]
	at io.temporal.internal.sync.WorkflowInvocationHandler$SyncWorkflowInvocationHandler.invoke(WorkflowInvocationHandler.java:274) ~[temporal-sdk-1.6.0.jar:?]
	at io.temporal.internal.sync.WorkflowInvocationHandler.invoke(WorkflowInvocationHandler.java:178) ~[temporal-sdk-1.6.0.jar:?]
	at jdk.proxy3.$Proxy134.deleteConnection(Unknown Source) ~[?:?]
	at io.airbyte.workers.temporal.TemporalClient.deleteConnection(TemporalClient.java:257) ~[airbyte-server-0.35.64-alpha.jar:?]
	at io.airbyte.scheduler.client.TemporalEventRunner.deleteConnection(TemporalEventRunner.java:39) ~[airbyte-server-0.35.64-alpha.jar:?]
	at io.airbyte.server.handlers.ConnectionsHandler.deleteConnection(ConnectionsHandler.java:328) ~[airbyte-server-0.35.64-alpha.jar:?]
	at io.airbyte.server.wrapped.ConfigurationApiWrapped.lambda$deleteConnection$73(ConfigurationApiWrapped.java:834) ~[io.airbyte-cloud-airbyte-server-wrapped-0.35.64-alpha.jar:?]
	at io.airbyte.cloud.auth.AuthHelper.lambda$execute$1(AuthHelper.java:181) ~[io.airbyte-cloud-cloud-auth-0.35.64-alpha.jar:?]
	at io.airbyte.cloud.auth.AuthHelper.execute(AuthHelper.java:189) ~[io.airbyte-cloud-cloud-auth-0.35.64-alpha.jar:?]
	at io.airbyte.cloud.auth.AuthHelper.execute(AuthHelper.java:180) ~[io.airbyte-cloud-cloud-auth-0.35.64-alpha.jar:?]
	at io.airbyte.cloud.auth.AuthHelper.runForWorkspace(AuthHelper.java:173) ~[io.airbyte-cloud-cloud-auth-0.35.64-alpha.jar:?]
	at io.airbyte.server.wrapped.ConfigurationApiWrapped.deleteConnection(ConfigurationApiWrapped.java:829) ~[io.airbyte-cloud-airbyte-server-wrapped-0.35.64-alpha.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:159) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:569) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1377) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:507) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.server.Server.handle(Server.java:501) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556) [airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) [airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273) [airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375) [airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [airbyte-server-0.35.64-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

## Steps to Reproduce
1. Delete a connection
2. Try deleting it again

**Comment by benmoriceau** [comment]
Maybe ask temporal about how to check if a workflow is running
