### ISSUE TITLE
All Syncs with redshift destination 0.3.32  fail rollback to version 0.3.28  resolves the issue

### ISSUE THREAD

**Issue by nthbooth-feedr** [airbytehq/airbyte#12265]
## Environment
- Is this your first time deploying Airbyte?: No
- OS Version / Instance: Amazon Linux
- Memory / Disk: you can use something like 8Gb / 60 Tb
- Deployment:  Docker
- Airbyte Version: 0.36.2-alpha
- Source name/version:  
Google sheets: 0.2.12
Hubspot: 0.1.53	
Stripe: 0.1.31 etc..... 
- **Severity**: Critical
- **Step where error happened**: Sync job 

## Current Behavior
syncs all fail with version 0.3.32 of the redshift destination connector going back to version 0.3.28 solves the issue. 
## Expected Behavior
Sync should work
## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```
example from sheets:
2022-04-22 06:38:17 [43mdestination[0m > 2022-04-22 06:38:17 [32mINFO[m a.m.s.StreamTransferManager(complete):367 - [Manager uploading to feedr-airbyte-prod-eu-west-2//Google_Sheets_Import/Tracker/2022_04_22_1650609493302_d1405323-22e6-4e58-bd39-60a3cf95c6c1.csv with id 0G4kNjyAV...msdos6H88]: Uploading leftover stream [Part number 1 containing 0.71 MB]
2022-04-22 06:38:17 [43mdestination[0m > 2022-04-22 06:38:17 [32mINFO[m a.m.s.StreamTransferManager(uploadStreamPart):558 - [Manager uploading to feedr-airbyte-prod-eu-west-2//Google_Sheets_Import/Tracker/2022_04_22_1650609493302_d1405323-22e6-4e58-bd39-60a3cf95c6c1.csv with id 0G4kNjyAV...msdos6H88]: Finished uploading [Part number 1 containing 0.71 MB]
2022-04-22 06:38:17 [43mdestination[0m > 2022-04-22 06:38:17 [32mINFO[m a.m.s.StreamTransferManager(complete):395 - [Manager uploading to feedr-airbyte-prod-eu-west-2//Google_Sheets_Import/Tracker/2022_04_22_1650609493302_d1405323-22e6-4e58-bd39-60a3cf95c6c1.csv with id 0G4kNjyAV...msdos6H88]: Completed
2022-04-22 06:38:17 [43mdestination[0m > 2022-04-22 06:38:17 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):115 - Upload completed for stream 'Tracker'.
2022-04-22 06:38:17 [43mdestination[0m > 2022-04-22 06:38:17 [32mINFO[m i.a.i.d.j.c.s.S3StreamCopier(createDestinationSchema):155 - Creating schema in destination if it doesn't exist: google_sheets_import
2022-04-22 06:38:18 [43mdestination[0m > 2022-04-22 06:38:18 [32mINFO[m i.a.i.d.j.c.s.S3StreamCopier(createTemporaryTable):161 - Preparing tmp table in destination for stream: Tracker, schema: google_sheets_import, tmp table name: _airbyte_tmp_rsd_tracker.
2022-04-22 06:38:18 [43mdestination[0m > 2022-04-22 06:38:18 [32mINFO[m i.a.i.d.r.RedshiftStreamCopier(copyStagingFileToTemporaryTable):86 - Starting copy to tmp table: _airbyte_tmp_rsd_tracker in destination for stream: Tracker, schema: google_sheets_import, .
2022-04-22 06:38:19 [43mdestination[0m > 2022-04-22 06:38:19 [32mINFO[m i.a.i.d.r.RedshiftStreamCopier(copyStagingFileToTemporaryTable):90 - Copy to tmp table _airbyte_tmp_rsd_tracker in destination for stream Tracker complete.
2022-04-22 06:38:19 [43mdestination[0m > 2022-04-22 06:38:19 [32mINFO[m i.a.i.d.j.c.s.S3StreamCopier(createDestinationTable):177 - Preparing table _airbyte_raw_tracker in destination.
2022-04-22 06:38:19 [43mdestination[0m > 2022-04-22 06:38:19 [32mINFO[m i.a.i.d.j.c.s.S3StreamCopier(createDestinationTable):179 - Table _airbyte_tmp_rsd_tracker in destination prepared.
2022-04-22 06:38:19 [43mdestination[0m > 2022-04-22 06:38:19 [32mINFO[m i.a.i.d.j.c.s.S3StreamCopier(generateMergeStatement):186 - Preparing to merge tmp table _airbyte_tmp_rsd_tracker to dest table: _airbyte_raw_tracker, schema: google_sheets_import, in destination.
2022-04-22 06:38:19 [43mdestination[0m > 2022-04-22 06:38:19 [32mINFO[m i.a.i.d.j.c.s.S3StreamCopier(generateMergeStatement):190 - Destination OVERWRITE mode detected. Dest table: _airbyte_raw_tracker, schema: google_sheets_import, truncated.
2022-04-22 06:38:19 [43mdestination[0m > 2022-04-22 06:38:19 [32mINFO[m i.a.i.d.r.RedshiftSqlOperations(onDestinationCloseOperations):110 - Executing operations for Redshift Destination DB engine...
2022-04-22 06:38:19 [43mdestination[0m > 2022-04-22 06:38:19 [32mINFO[m i.a.i.d.r.RedshiftSqlOperations(discoverNotSuperTables):129 - Discovering NOT SUPER table types...
2022-04-22 06:38:19 [43mdestination[0m > 2022-04-22 06:38:19 [32mINFO[m i.a.i.d.r.RedshiftSqlOperations(onDestinationCloseOperations):118 - Executing operations for Redshift Destination DB engine completed.
2022-04-22 06:38:19 [43mdestination[0m > 2022-04-22 06:38:19 [32mINFO[m i.a.i.d.j.c.s.S3StreamCopier(removeFileAndDropTmpTable):201 - S3 staging file /Google_Sheets_Import/Tracker/2022_04_22_1650609493302_d1405323-22e6-4e58-bd39-60a3cf95c6c1.csv cleaned.
2022-04-22 06:38:19 [43mdestination[0m > 2022-04-22 06:38:19 [32mINFO[m i.a.i.d.j.c.s.S3StreamCopier(removeFileAndDropTmpTable):205 - Begin cleaning _airbyte_tmp_rsd_tracker tmp table in destination.
2022-04-22 06:38:19 [43mdestination[0m > Exception in thread "main" java.sql.SQLException: [Amazon](500310) Invalid operation: current transaction is aborted, commands ignored until end of transaction block;
2022-04-22 06:38:19 [43mdestination[0m > 	at com.amazon.redshift.client.messages.inbound.ErrorResponse.toErrorException(Unknown Source)
2022-04-22 06:38:19 [43mdestination[0m > 	at com.amazon.redshift.client.PGMessagingContext.handleErrorResponse(Unknown Source)
2022-04-22 06:38:19 [43mdestination[0m > 	at com.amazon.redshift.client.PGMessagingContext.handleMessage(Unknown Source)
2022-04-22 06:38:19 [43mdestination[0m > 	at com.amazon.jdbc.communications.InboundMessagesPipeline.getNextMessageOfClass(Unknown Source)
2022-04-22 06:38:19 [43mdestination[0m > 	at com.amazon.redshift.client.PGMessagingContext.doMoveToNextClass(Unknown Source)
2022-04-22 06:38:19 [43mdestination[0m > 	at com.amazon.redshift.client.PGMessagingContext.moveThroughMetadata(Unknown Source)
2022-04-22 06:38:19 [43mdestination[0m > 	at com.amazon.redshift.client.PGMessagingContext.getNoData(Unknown Source)
2022-04-22 06:38:19 [43mdestination[0m > 	at com.amazon.redshift.client.PGClient.directExecuteExtraMetadataWithMessage(Unknown Source)
2022-04-22 06:38:19 [43mdestination[0m > 2022-04-22 06:38:19 [1;31mERROR[m i.a.i.d.b.BufferedStreamConsumer(close):191 - Close failed.
2022-04-22 06:38:19 [43mdestination[0m > 	at com.amazon.redshift.dataengine.PGQueryExecutor$CallableExecuteTask.call(Unknown Source)
2022-04-22 06:38:19 [43mdestination[0m > 	at com.amazon.redshift.dataengine.PGQueryExecutor$CallableExecuteTask.call(Unknown Source)
2022-04-22 06:38:19 [43mdestination[0m > 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-04-22 06:38:19 [43mdestination[0m > 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2022-04-22 06:38:19 [43mdestination[0m > 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2022-04-22 06:38:19 [43mdestination[0m > Caused by: com.amazon.support.exceptions.ErrorException: [Amazon](500310) Invalid operation: current transaction is aborted, commands ignored until end of transaction block;
2022-04-22 06:38:19 [43mdestination[0m > 	... 13 more
2022-04-22 06:38:19 [43mdestination[0m > java.sql.SQLException: [Amazon](500310) Invalid operation: current transaction is aborted, commands ignored until end of transaction block;
2022-04-22 06:38:19 [43mdestination[0m > 	at com.amazon.redshift.client.messages.inbound.ErrorResponse.toErrorException(Unknown Source) ~[redshift-jdbc42-no-awssdk-1.2.51.1078.jar:RedshiftJDBC_1.2.51.1078]
2022-04-22 06:38:19 [43mdestination[0m > 	at com.amazon.redshift.client.PGMessagingContext.handleErrorResponse(Unknown Source) ~[redshift-jdbc42-no-awssdk-1.2.51.1078.jar:RedshiftJDBC_1.2.51.1078]
2022-04-22 06:38:19 [43mdestination[0m > 	at com.amazon.redshift.client.PGMessagingContext.handleMessage(Unknown Source) ~[redshift-jdbc42-no-awssdk-1.2.51.1078.jar:RedshiftJDBC_1.2.51.1078]
2022-04-22 06:38:19 [43mdestination[0m > 	at com.amazon.jdbc.communications.InboundMessagesPipeline.getNextMessageOfClass(Unknown Source) ~[redshift-jdbc42-no-awssdk-1.2.51.1078.jar:RedshiftJDBC_1.2.51.1078]
2022-04-22 06:38:19 [43mdestination[0m > 	at com.amazon.redshift.client.PGMessagingContext.doMoveToNextClass(Unknown Source) ~[redshift-jdbc42-no-awssdk-1.2.51.1078.jar:RedshiftJDBC_1.2.51.1078]
2022-04-22 06:38:19 [43mdestination[0m > 	at com.amazon.redshift.client.PGMessagingContext.moveThroughMetadata(Unknown Source) ~[redshift-jdbc42-no-awssdk-1.2.51.1078.jar:RedshiftJDBC_1.2.51.1078]
2022-04-22 06:38:19 [43mdestination[0m > 	at com.amazon.redshift.client.PGMessagingContext.getNoData(Unknown Source) ~[redshift-jdbc42-no-awssdk-1.2.51.1078.jar:RedshiftJDBC_1.2.51.1078]
2022-04-22 06:38:19 [43mdestination[0m > 	at com.amazon.redshift.client.PGClient.directExecuteExtraMetadataWithMessage(Unknown Source) ~[redshift-jdbc42-no-awssdk-1.2.51.1078.jar:RedshiftJDBC_1.2.51.1078]
2022-04-22 06:38:19 [43mdestination[0m > 	at com.amazon.redshift.dataengine.PGQueryExecutor$CallableExecuteTask.call(Unknown Source) ~[redshift-jdbc42-no-awssdk-1.2.51.1078.jar:RedshiftJDBC_1.2.51.1078]
2022-04-22 06:38:19 [43mdestination[0m > 	at com.amazon.redshift.dataengine.PGQueryExecutor$CallableExecuteTask.call(Unknown Source) ~[redshift-jdbc42-no-awssdk-1.2.51.1078.jar:RedshiftJDBC_1.2.51.1078]
2022-04-22 06:38:19 [43mdestination[0m > 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
2022-04-22 06:38:19 [43mdestination[0m > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
2022-04-22 06:38:19 [43mdestination[0m > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
2022-04-22 06:38:19 [43mdestination[0m > Caused by: com.amazon.support.exceptions.ErrorException: [Amazon](500310) Invalid operation: current transaction is aborted, commands ignored until end of transaction block;
2022-04-22 06:38:19 [43mdestination[0m > 	... 13 more
2022-04-22 06:38:19 [1;31mERROR[m i.a.w.DefaultReplicationWorker(run):169 - Sync worker failed.
java.util.concurrent.ExecutionException: io.airbyte.workers.DefaultReplicationWorker$DestinationException: Destination process exited with non-zero exit code 1
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:164) ~[io.airbyte-airbyte-workers-0.36.2-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:57) ~[io.airbyte-airbyte-workers-0.36.2-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:155) ~[io.airbyte-airbyte-workers-0.36.2-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
	Suppressed: io.airbyte.workers.WorkerException: Destination process exit with code 1. This warning is normal if the job was cancelled.
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.close(DefaultAirbyteDestination.java:119) ~[io.airbyte-airbyte-workers-0.36.2-alpha.jar:?]
		at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:126) ~[io.airbyte-airbyte-workers-0.36.2-alpha.jar:?]
		at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:57) ~[io.airbyte-airbyte-workers-0.36.2-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:155) ~[io.airbyte-airbyte-workers-0.36.2-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: io.airbyte.workers.DefaultReplicationWorker$DestinationException: Destination process exited with non-zero exit code 1
	at io.airbyte.workers.DefaultReplicationWorker.lambda$getDestinationOutputRunnable$6(DefaultReplicationWorker.java:354) ~[io.airbyte-airbyte-workers-0.36.2-alpha.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
2022-04-22 06:38:19 [32mINFO[m i.a.w.DefaultReplicationWorker(run):228 - sync summary: io.airbyte.config.ReplicationAttemptSummary@7e000863[status=failed,recordsSynced=1968,bytesSynced=556599,startTime=1650609487582,endTime=1650609499928,totalStats=io.airbyte.config.SyncStats@1d01a85f[recordsEmitted=1968,bytesEmitted=556599,stateMessagesEmitted=0,recordsCommitted=0],streamStats=[io.airbyte.config.StreamSyncStats@7fcb5e82[streamName=Tracker,stats=io.airbyte.config.SyncStats@680d96eb[recordsEmitted=1968,bytesEmitted=556599,stateMessagesEmitted=<null>,recordsCommitted=<null>]]]]
2022-04-22 06:38:19 [32mINFO[m i.a.w.DefaultReplicationWorker(run):250 - Source did not output any state messages
2022-04-22 06:38:19 [33mWARN[m i.a.w.DefaultReplicationWorker(run):258 - State capture: No new state, falling back on input state: io.airbyte.config.State@16b0c899[state={}]
2022-04-22 06:38:19 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):131 - Stopping cancellation check scheduling...


example from mail chimp:
2022-04-20 17:46:30 destination > 2022-04-20 17:46:30 INFO a.m.s.MultiPartOutputStream(close):158 - Called close() on [MultipartOutputStream for parts 1 - 10000]
2022-04-20 17:46:30 destination > 2022-04-20 17:46:30 WARN a.m.s.MultiPartOutputStream(close):160 - [MultipartOutputStream for parts 1 - 10000] is already closed
2022-04-20 17:46:31 destination > 2022-04-20 17:46:31 INFO a.m.s.StreamTransferManager(uploadStreamPart):558 - [Manager uploading to feedr-airbyte-prod-eu-west-2//mailchimp/email_activity/2022_04_20_1650474601884_123c2740-22da-43f7-81c5-c22aac1a7719.csv with id 5HLzePKXZ...bGXe7yNdi]: Finished uploading [Part number 3 containing 5.68 MB]
2022-04-20 17:46:31 destination > 2022-04-20 17:46:31 INFO a.m.s.StreamTransferManager(complete):395 - [Manager uploading to feedr-airbyte-prod-eu-west-2//mailchimp/email_activity/2022_04_20_1650474601884_123c2740-22da-43f7-81c5-c22aac1a7719.csv with id 5HLzePKXZ...bGXe7yNdi]: Completed
2022-04-20 17:46:31 destination > 2022-04-20 17:46:31 INFO i.a.i.d.s.w.BaseS3Writer(close):115 - Upload completed for stream 'email_activity'.
2022-04-20 17:46:31 destination > 2022-04-20 17:46:31 INFO i.a.i.d.j.c.s.S3StreamCopier(createDestinationSchema):155 - Creating schema in destination if it doesn't exist: mailchimp
2022-04-20 17:46:31 destination > 2022-04-20 17:46:31 INFO i.a.i.d.j.c.s.S3StreamCopier(createTemporaryTable):161 - Preparing tmp table in destination for stream: email_activity, schema: mailchimp, tmp table name: _airbyte_tmp_jpk_email_activity.
2022-04-20 17:46:32 destination > 2022-04-20 17:46:32 INFO i.a.i.d.r.RedshiftStreamCopier(copyStagingFileToTemporaryTable):86 - Starting copy to tmp table: _airbyte_tmp_jpk_email_activity in destination for stream: email_activity, schema: mailchimp, .
2022-04-20 17:46:54 destination > 2022-04-20 17:46:54 INFO i.a.i.d.r.RedshiftStreamCopier(copyStagingFileToTemporaryTable):90 - Copy to tmp table _airbyte_tmp_jpk_email_activity in destination for stream email_activity complete.
2022-04-20 17:46:54 destination > 2022-04-20 17:46:54 INFO i.a.i.d.j.c.s.S3StreamCopier(createDestinationTable):177 - Preparing table _airbyte_raw_email_activity in destination.
2022-04-20 17:46:54 destination > 2022-04-20 17:46:54 INFO i.a.i.d.j.c.s.S3StreamCopier(createDestinationTable):179 - Table _airbyte_tmp_jpk_email_activity in destination prepared.
2022-04-20 17:46:54 destination > 2022-04-20 17:46:54 INFO i.a.i.d.j.c.s.S3StreamCopier(generateMergeStatement):186 - Preparing to merge tmp table _airbyte_tmp_jpk_email_activity to dest table: _airbyte_raw_email_activity, schema: mailchimp, in destination.
2022-04-20 17:46:54 destination > 2022-04-20 17:46:54 INFO i.a.i.d.j.c.s.S3StreamCopier(generateMergeStatement):190 - Destination OVERWRITE mode detected. Dest table: _airbyte_raw_email_activity, schema: mailchimp, truncated.
2022-04-20 17:46:54 destination > 2022-04-20 17:46:54 INFO i.a.i.d.j.c.s.S3StreamCopier(removeFileAndDropTmpTable):201 - S3 staging file /mailchimp/lists/2022_04_20_1650474601889_60e21a7f-b060-4cb1-8a8a-0776d8dec37d.csv cleaned.
2022-04-20 17:46:54 destination > 2022-04-20 17:46:54 INFO i.a.i.d.j.c.s.S3StreamCopier(removeFileAndDropTmpTable):205 - Begin cleaning _airbyte_tmp_kff_lists tmp table in destination.
2022-04-20 17:46:54 destination > Exception in thread "main" java.sql.SQLException: [Amazon](500310) Invalid operation: current transaction is aborted, commands ignored until end of transaction block;
2022-04-20 17:46:54 destination > 2022-04-20 17:46:54 ERROR i.a.i.d.b.BufferedStreamConsumer(close):191 - Close failed.

```

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by krishagel** [comment]
I can confirm that I had the same problem. Rolling back resolved the issue for now.

**Comment by nthbooth-feedr** [comment]
airbyte cloud uses version: 0.3.28 of the redshift adapter which is why I choose to use it as the fall back as an FYI

**Comment by marcosmarxm** [comment]
@nthbooth-feedr can you share the complete log of the failed sync. The Redshift had a change you need Airbyte minimum version 0.36.2-alpha

**Comment by marieamelie94** [comment]
Hi, also encountering this issue (with airbyte 0.36.4-alpha), rolling back from Redshift destination connector 0.3.32 to version 0.3.28 helps with certain sources ( like google ads 0.1.36 ) but not all of them ( like postgres 0.4.12 ) so we are forced to switch redshift versions to make all our syncs work.

**Comment by alexandertsukanov** [comment]
@marieamelie94 could you share your logs, please?
I was able to make successful sync between Redshift destination connector 0.3.32 and Postgres [14.2](https://hub.docker.com/layers/postgres/library/postgres/14.2/images/sha256-625df66e2b092d2a5be485d52f80d6edf41cb02f7315a29c980a877519d14e4e?context=explore)

**Comment by marieamelie94** [comment]
Hello, our issue is that google ads 0.1.36 source does not work with redshift 0.3.32 destination (but fine with redshift 0.3.28), but our postgres source 0.4.12 does not work with redshift 0.3.28 (but fine with redshift 0.3.32) so we have to switch between redshift versions now to make both work.
Here are the logs 
[logs-gads-redshift.txt](https://github.com/airbytehq/airbyte/files/8629638/logs-gads-redshift.txt)
[logs-postgres-redshift.txt](https://github.com/airbytehq/airbyte/files/8629639/logs-postgres-redshift.txt)

**Comment by alexandertsukanov** [comment]
It will be fixed in the scope of https://github.com/airbytehq/airbyte/pull/12601. Thanks.

**Comment by alafanechere** [comment]
@alexandertsukanov do you think this [error](https://discuss.airbyte.io/t/postgres-source-redshift-destination-connection-error/982) in `discoverNotSuperTables` will be fixed by #12601 ?

**Comment by alexandertsukanov** [comment]
@alafanechere Yep, I think it should be the fix.

**Comment by alexandertsukanov** [comment]
[marieamelie94](https://github.com/marieamelie94) please, update to the last version of the Redshift connector and check whether the issue exists. 
CC: @alafanechere , @nthbooth-feedr

**Comment by alexandertsukanov** [comment]
Also, make sure you have the following versions of Airbyte and Connector:
```
destination-redshift  0.3.31+
base-normalization    0.1.77+ (airbyte platform v0.36.2-alpha+)
```

**Comment by anduresu** [comment]
Uploading logs as requested in https://discuss.airbyte.io/t/downgrading-redshift-destination-connector-not-working/1072/12
[data.zip](https://github.com/airbytehq/airbyte/files/8702133/data.zip)

**Comment by marieamelie94** [comment]
> [marieamelie94](https://github.com/marieamelie94) please, update to the last version of the Redshift connector and check whether the issue exists. CC: @alafanechere , @nthbooth-feedr
Hi, so far looks good with this set up
Airbyte version: 0.36.4-alpha
destination-redshift:0.3.34
normalization-redshift:0.1.77
thanks

**Comment by alexandertsukanov** [comment]
@alafanechere can we close the issue as there is no response from the customer?

**Comment by alexandertsukanov** [comment]
I see successful cases from @marieamelie94 and in slack from Damian Crisafulli

<img width="548" alt="image" src="https://user-images.githubusercontent.com/17796771/170664550-8fff6c57-94b8-4d69-ac4b-b7d14b631b3e.png">

**Comment by alafanechere** [comment]
Closing because @alexandertsukanov can't reproduce and got proof from a user that the bug was fixed.
