### ISSUE TITLE
unsupported startup parameter: search_path

### ISSUE THREAD

**Issue by sadornounnoba** [airbytehq/airbyte#12277]
## Environment

Airbyte version: 0.35.65-alpha
OS Version / Instance: Debian 10 buster
Deployment: Docker compose
Source Connector and version: Postgres 0.4.10
Destination Connector and version: N/A
Severity: High
Step where error happened: Setting up source

## Current Behavior

If I set up a Postgres source without specifying a schema everything works fine, however
when a schema is specified in the “schema” field, the creation of the source connector doesn’t work. It is really necessary to specify a schema because I have too many tables and schemas in the database and selecting one by one after the source is setted up is non-viable.

## Expected Behavior

Allow to filter by schema in the Source creation.

## Logs

<details>
<summary>LOG</summary> 

```

2022-04-22 15:31:19 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):105 - Docker volume job log path: /tmp/workspace/9d3cdd1f-966e-432b-bb32-d3ca7e9c5e5c/0/logs.log
2022-04-22 15:31:19 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):110 - Executing worker wrapper. Airbyte version: 0.35.65-alpha
2022-04-22 15:31:19 [32mINFO[m i.a.c.i.LineGobbler(voidCall):82 - Checking if airbyte/source-postgres:0.4.10 exists...
2022-04-22 15:31:19 [32mINFO[m i.a.c.i.LineGobbler(voidCall):82 - airbyte/source-postgres:0.4.10 was found locally.
2022-04-22 15:31:19 [32mINFO[m i.a.w.p.DockerProcessFactory(create):106 - Creating docker job ID: 9d3cdd1f-966e-432b-bb32-d3ca7e9c5e5c
2022-04-22 15:31:19 [32mINFO[m i.a.w.p.DockerProcessFactory(create):158 - Preparing command: docker run --rm --init -i -w /data/9d3cdd1f-966e-432b-bb32-d3ca7e9c5e5c/0 --log-driver none --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e WORKER_CONNECTOR_IMAGE=airbyte/source-postgres:0.4.10 -e WORKER_JOB_ATTEMPT=0 -e WORKER_ENVIRONMENT=DOCKER -e AIRBYTE_ROLE= -e AIRBYTE_VERSION=0.35.65-alpha -e WORKER_JOB_ID=9d3cdd1f-966e-432b-bb32-d3ca7e9c5e5c airbyte/source-postgres:0.4.10 check --config source_config.json
2022-04-22 15:31:19 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):82 - SLF4J: Class path contains multiple SLF4J bindings.
2022-04-22 15:31:19 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):82 - SLF4J: Found binding in [jar:file:/airbyte/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2022-04-22 15:31:19 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):82 - SLF4J: Found binding in [jar:file:/airbyte/lib/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2022-04-22 15:31:19 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):82 - SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
2022-04-22 15:31:19 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):82 - SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
2022-04-22 15:31:21 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-22 15:31:21 [32mINFO[m i.a.i.s.p.PostgresSource(main):364 - starting source: class io.airbyte.integrations.source.postgres.PostgresSource
2022-04-22 15:31:21 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-22 15:31:21 [32mINFO[m i.a.i.b.IntegrationCliParser(parseOptions):118 - integration args: {check=null, config=source_config.json}
2022-04-22 15:31:21 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-22 15:31:21 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):121 - Running integration: io.airbyte.integrations.base.ssh.SshWrappedSource
2022-04-22 15:31:21 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-22 15:31:21 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):122 - Command: CHECK
2022-04-22 15:31:21 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-22 15:31:21 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):123 - Integration config: IntegrationConfig{command=CHECK, configPath='source_config.json', catalogPath='null', statePath='null'}
2022-04-22 15:31:21 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-22 15:31:21 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2022-04-22 15:31:21 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-22 15:31:21 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword examples - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2022-04-22 15:31:21 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-22 15:31:21 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2022-04-22 15:31:21 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-22 15:31:21 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword multiline - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2022-04-22 15:31:21 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-22 15:31:21 [32mINFO[m i.a.i.b.s.SshTunnel(getInstance):170 - Starting connection with method: NO_TUNNEL
2022-04-22 15:31:22 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-22 15:31:22 [32mINFO[m i.a.i.s.r.AbstractDbSource(check):73 - Exception while checking connection: 
2022-04-22 15:31:22 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - java.sql.SQLException: Cannot create PoolableConnectionFactory (ERROR: unsupported startup parameter: search_path)
2022-04-22 15:31:22 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:669) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2022-04-22 15:31:22 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:544) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2022-04-22 15:31:22 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:753) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2022-04-22 15:31:22 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.db.jdbc.DefaultJdbcDatabase.getMetaData(DefaultJdbcDatabase.java:77) ~[io.airbyte.airbyte-db-lib-0.35.65-alpha.jar:?]
2022-04-22 15:31:22 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.source.jdbc.AbstractJdbcSource.createDatabase(AbstractJdbcSource.java:300) ~[io.airbyte.airbyte-integrations.connectors-source-jdbc-0.35.65-alpha.jar:?]
2022-04-22 15:31:22 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.source.jdbc.AbstractJdbcSource.createDatabase(AbstractJdbcSource.java:63) ~[io.airbyte.airbyte-integrations.connectors-source-jdbc-0.35.65-alpha.jar:?]
2022-04-22 15:31:22 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.source.relationaldb.AbstractDbSource.createDatabaseInternal(AbstractDbSource.java:491) ~[io.airbyte.airbyte-integrations.connectors-source-relational-db-0.35.65-alpha.jar:?]
2022-04-22 15:31:22 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.source.relationaldb.AbstractDbSource.check(AbstractDbSource.java:66) ~[io.airbyte.airbyte-integrations.connectors-source-relational-db-0.35.65-alpha.jar:?]
2022-04-22 15:31:22 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.base.ssh.SshTunnel.sshWrap(SshTunnel.java:205) [io.airbyte.airbyte-integrations.bases-base-java-0.35.65-alpha.jar:?]
2022-04-22 15:31:22 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.base.ssh.SshWrappedSource.check(SshWrappedSource.java:40) [io.airbyte.airbyte-integrations.bases-base-java-0.35.65-alpha.jar:?]
2022-04-22 15:31:22 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:138) [io.airbyte.airbyte-integrations.bases-base-java-0.35.65-alpha.jar:?]
2022-04-22 15:31:22 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:105) [io.airbyte.airbyte-integrations.bases-base-java-0.35.65-alpha.jar:?]
2022-04-22 15:31:22 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.source.postgres.PostgresSource.main(PostgresSource.java:365) [io.airbyte.airbyte-integrations.connectors-source-postgres-0.35.65-alpha.jar:?]
2022-04-22 15:31:22 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - Caused by: org.postgresql.util.PSQLException: ERROR: unsupported startup parameter: search_path
2022-04-22 15:31:22 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:613) ~[postgresql-42.2.18.jar:42.2.18]
2022-04-22 15:31:22 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:161) ~[postgresql-42.2.18.jar:42.2.18]
2022-04-22 15:31:22 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:213) ~[postgresql-42.2.18.jar:42.2.18]
2022-04-22 15:31:22 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51) ~[postgresql-42.2.18.jar:42.2.18]
2022-04-22 15:31:22 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:225) ~[postgresql-42.2.18.jar:42.2.18]
2022-04-22 15:31:22 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at org.postgresql.Driver.makeConnection(Driver.java:465) ~[postgresql-42.2.18.jar:42.2.18]
2022-04-22 15:31:22 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at org.postgresql.Driver.connect(Driver.java:264) ~[postgresql-42.2.18.jar:42.2.18]
2022-04-22 15:31:22 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:55) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2022-04-22 15:31:22 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:355) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2022-04-22 15:31:22 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:115) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2022-04-22 15:31:22 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:665) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2022-04-22 15:31:22 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	... 12 more
2022-04-22 15:31:22 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):131 - Stopping cancellation check scheduling...

```

</details>

## Steps to Reproduce
1. setup Postgres Source
2. Complete all fields, include schema filter.
3. Connect ussing ssl: NO
   Replication method: Standard
   SSH Tunnel method: No Tunnel
4. Press the button

**Comment by sadornounnoba** [comment]
Any help?

**Comment by alafanechere** [comment]
Hi @sadornounnoba , I'm not able to reproduce this problem. 
I did the following:
* created a schema in my database + table that I filled with test data
* set up a source with the schema filter set to my new schema
* Run a sync
I have no error and my data is properly replicated.

Which Postgres version are you running? I tested with 14.2

**Comment by sadornounnoba** [comment]
> 

I am running postgresql 12.2

I already set search_path=public

`psqluser=> show search_path;
   search_path   
-----------------
 "$user", public
`

**Comment by sadornounnoba** [comment]
Any help?

**Comment by grishick** [comment]
@sadornounnoba you may be running into schema size limitation. Currently, Airbyte cannot read schemas that are larger than 4MB. Can you add a screenshot of the error that you are seeing?

**Comment by grishick** [comment]
I ran into this issue today. Some Postgres flavors (e.g. AlloyDB) do not support `?currentSchema=` parameter.

**Comment by bleonard** [comment]
Maybe some configurations of postgres don't support `search_path` ? so look into better error message: "Error in connecting with the specified schema. Enable search_path in your Postgres configuration."
This is happening when run through pg_bouncer. Maybe have to mention that.

https://stackoverflow.com/questions/71798409/postgressql-org-postgresql-util-psqlexception-error-unsupported-startup-param

**Comment by bleonard** [comment]
manuaully test with pg_pbounder but we can mock the same error for our test suire

**Comment by huynguyn2000** [comment]
@bleonard Why this issue is frozen ? I meet this problem so far and I don't know how to solve it :(

**Comment by lideke** [comment]
any update on this issue ?
