### ISSUE TITLE
normalization failed

### ISSUE THREAD

**Issue by nshigit** [airbytehq/airbyte#12295]
## Environment
- **Airbyte version**:  0.35.65-alpha
- **OS Version / Instance**: CentOS7
- **Deployment**: Docker
- **Source Connector and version**:  airbyte/source-mysql          0.5.6
- **Destination Connector and version**: airbyte/destination-mysql     0.1.18
                                                                 airbyte/normalization-mysql   0.1.74
- **Severity**: Critical
- **Step where error happened**: Sync job

## Current Behavior
Sync Failed in normalization.

## Expected Behavior
normalization success.

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```
2022-04-23 07:57:30 ERROR i.t.i.s.WorkflowExecuteRunnable(logWorkflowExecutionException):125 - Workflow execution failure WorkflowId=28c611eb-4df6-4d07-b2e7-bb2f13ecbb25, RunId=0388d50f-cfda-489d-bb15-0ea0a58b0372, WorkflowType=SyncWorkflow                                                                                                                                             
io.temporal.failure.ActivityFailure: scheduledEventId=18, startedEventId=19, activityType='Normalize', activityId='02326f1b-ad85-36d6-a123-f0eb69b23744', identity='1@9bf7ff68428c', retryState=RETRY_STATE_MAXIMUM_ATTEMPTS_REACHED                                                                                                                                                
        at java.lang.Thread.getStackTrace(Thread.java:1610) ~[?:?]                                                                          
        at io.temporal.internal.sync.ActivityStubBase.execute(ActivityStubBase.java:48) ~[temporal-sdk-1.8.1.jar:?]              
        at io.temporal.internal.sync.ActivityInvocationHandler.lambda$getActivityFunc$0(ActivityInvocationHandler.java:77) ~[temporal-sdk-1.8.1.jar:?]                    
        at io.temporal.internal.sync.ActivityInvocationHandlerBase.invoke(ActivityInvocationHandlerBase.java:70) ~[temporal-sdk-1.8.1.jar:?]                              
        at jdk.proxy2.$Proxy32.normalize(Unknown Source) ~[?:?]                                                                                                                                                            at io.airbyte.workers.temporal.sync.SyncWorkflowImpl.run(SyncWorkflowImpl.java:61) ~[io.airbyte-airbyte-workers-0.35.65-alpha.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor170.invoke(Unknown Source) ~[?:?]                                                                                         
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]                                 
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]                                                                                
        at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation$RootWorkflowInboundCallsInterceptor.execute(POJOWorkflowImplementationFactory.java:317) ~[temporal-sdk-1.8.1.jar:?]                                                                                                                                                                           
        at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation.execute(POJOWorkflowImplementationFactory.java:292) ~[temporal-sdk-1.8.1.jar:?]
        at io.temporal.internal.sync.WorkflowExecuteRunnable.run(WorkflowExecuteRunnable.java:72) ~[temporal-sdk-1.8.1.jar:?]                         
        at io.temporal.internal.sync.SyncWorkflow.lambda$start$0(SyncWorkflow.java:137) ~[temporal-sdk-1.8.1.jar:?]                               
        at io.temporal.internal.sync.CancellationScopeImpl.run(CancellationScopeImpl.java:101) [temporal-sdk-1.8.1.jar:?]                         
        at io.temporal.internal.sync.WorkflowThreadImpl$RunnableWrapper.run(WorkflowThreadImpl.java:111) [temporal-sdk-1.8.1.jar:?]                                          
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]                                                                                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]                                                                               
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]                                                                             
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]                                                                    
        at java.lang.Thread.run(Thread.java:833) [?:?]                                      
Caused by: io.temporal.failure.ApplicationFailure: message='io.temporal.serviceclient.CheckedExceptionWrapper: java.util.concurrent.ExecutionException: io.airbyte.workers.WorkerException: Normalization [0/45562] type='java.lang.RuntimeException', nonRetryable=false                                                                                                  
        at io.airbyte.workers.temporal.TemporalUtils.withBackgroundHeartbeat(TemporalUtils.java:233) ~[io.airbyte-airbyte-workers-0.35.65-alpha.jar:?]
        at io.airbyte.workers.temporal.sync.NormalizationActivityImpl.normalize(NormalizationActivityImpl.java:71) ~[io.airbyte-airbyte-workers-0.35.65-alpha.jar:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method:0) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at io.temporal.internal.activity.POJOActivityTaskHandler$POJOActivityInboundCallsInterceptor.execute(POJOActivityTaskHandler.java:214) ~[temporal-sdk-1.8.1.jar:?]
        at io.temporal.internal.activity.POJOActivityTaskHandler$POJOActivityImplementation.execute(POJOActivityTaskHandler.java:180) ~[temporal-sdk-1.8.1.jar:?]
        at io.temporal.internal.activity.POJOActivityTaskHandler.handle(POJOActivityTaskHandler.java:120) ~[temporal-sdk-1.8.1.jar:?]
        at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:204) ~[temporal-sdk-1.8.1.jar:?]
        at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:164) ~[temporal-sdk-1.8.1.jar:?]
        at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93) ~[temporal-sdk-1.8.1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: io.temporal.failure.ApplicationFailure: message='io.airbyte.workers.WorkerException: Normalization Failed.', type='java.util.concurrent.ExecutionException', nonRetryable=false
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
        at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:129) ~[io.airbyte-airbyte-workers-0.35.65-alpha.jar:?]
        at io.airbyte.workers.temporal.sync.NormalizationActivityImpl.lambda$normalize$1(NormalizationActivityImpl.java:97) ~[io.airbyte-airbyte-workers-0.35.65-alpha.jar:?]
        at io.airbyte.workers.temporal.TemporalUtils.withBackgroundHeartbeat(TemporalUtils.java:228) ~[io.airbyte-airbyte-workers-0.35.65-alpha.jar:?]
        at io.airbyte.workers.temporal.sync.NormalizationActivityImpl.normalize(NormalizationActivityImpl.java:71) ~[io.airbyte-airbyte-workers-0.35.65-alpha.jar:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method:0) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at io.temporal.internal.activity.POJOActivityTaskHandler$POJOActivityInboundCallsInterceptor.execute(POJOActivityTaskHandler.java:214) ~[temporal-sdk-1.8.1.jar:?]
        at io.temporal.internal.activity.POJOActivityTaskHandler$POJOActivityImplementation.execute(POJOActivityTaskHandler.java:180) ~[temporal-sdk-1.8.1.jar:?]
        at io.temporal.internal.activity.POJOActivityTaskHandler.handle(POJOActivityTaskHandler.java:120) ~[temporal-sdk-1.8.1.jar:?]
        at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:204) ~[temporal-sdk-1.8.1.jar:?]
        at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:164) ~[temporal-sdk-1.8.1.jar:?]
        at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93) ~[temporal-sdk-1.8.1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: io.temporal.failure.ApplicationFailure: message='Normalization Failed.', type='io.airbyte.workers.WorkerException', nonRetryable=false
        at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:60) ~[io.airbyte-airbyte-workers-0.35.65-alpha.jar:?]
        at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:18) ~[io.airbyte-airbyte-workers-0.35.65-alpha.jar:?]
        at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:155) ~[io.airbyte-airbyte-workers-0.35.65-alpha.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: io.temporal.failure.ApplicationFailure: message='Normalization Failed.', type='io.airbyte.workers.WorkerException', nonRetryable=false
        at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:57) ~[io.airbyte-airbyte-workers-0.35.65-alpha.jar:?]
        at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:18) ~[io.airbyte-airbyte-workers-0.35.65-alpha.jar:?]
        at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:155) ~[io.airbyte-airbyte-workers-0.35.65-alpha.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[?:?]
```

</details>

## Steps to Reproduce
1. Create a MySQL source
2. Create a MySQL Destination
3. Create connection based on upper source and destination

**Comment by nshigit** [comment]
2022-04-23 09:11:23 ^[[32mINFO^[[m i.a.w.DefaultNormalizationWorker(run):46 - Running normalization.
2022-04-23 09:11:23 ^[[32mINFO^[[m i.a.w.n.DefaultNormalizationRunner(runProcess):122 - Running with normalization version: airbyte/normalization-mysql:0.1.74
2022-04-23 09:11:23 ^[[32mINFO^[[m i.a.c.i.LineGobbler(voidCall):82 - Checking if airbyte/normalization-mysql:0.1.74 exists...
2022-04-23 09:11:23 ^[[32mINFO^[[m i.a.c.i.LineGobbler(voidCall):82 - airbyte/normalization-mysql:0.1.74 was found locally.
2022-04-23 09:11:23 ^[[32mINFO^[[m i.a.w.p.DockerProcessFactory(create):106 - Creating docker job ID: 11
2022-04-23 09:11:23 ^[[32mINFO^[[m i.a.w.p.DockerProcessFactory(create):158 - Preparing command: docker run --rm --init -i -w /data/11/2/normalize --log-driver none --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e WORKER_ENVIRONMENT=DOCKER -e AIRBYTE_ROLE= -e AIRBYTE_VERSION=0.35.65-alpha airbyte/normalization-mysql:0.1.74 run --integration-type mysql --config destination_config.json --catalog destination_catalog.json
2022-04-23 09:11:23 ^[[42mnormalization^[[0m > Running: transform-config --config destination_config.json --integration-type mysql --out /data/11/2/normalize
2022-04-23 09:11:23 ^[[42mnormalization^[[0m > Namespace(config='destination_config.json', integration_type=<DestinationType.mysql: 'mysql'>, out='/data/11/2/normalize')
2022-04-23 09:11:23 ^[[42mnormalization^[[0m > transform_mysql
2022-04-23 09:11:23 ^[[42mnormalization^[[0m > Running: transform-catalog --integration-type mysql --profile-config-dir /data/11/2/normalize --catalog destination_catalog.json --out /data/11/2/normalize/models/generated/ --json-column _airbyte_data
2022-04-23 09:11:23 ^[[42mnormalization^[[0m > Processing destination_catalog.json...
2022-04-23 09:11:23 ^[[42mnormalization^[[0m >   Generating airbyte_ctes/ama5_mysql/view_payment_after_20220401_ab1.sql from view_payment_after_20220401
2022-04-23 09:11:23 ^[[42mnormalization^[[0m >   Generating airbyte_ctes/ama5_mysql/view_payment_after_20220401_ab2.sql from view_payment_after_20220401
2022-04-23 09:11:23 ^[[42mnormalization^[[0m >   Generating airbyte_ctes/ama5_mysql/view_payment_after_20220401_ab3.sql from view_payment_after_20220401
2022-04-23 09:11:23 ^[[42mnormalization^[[0m >   Generating airbyte_incremental/ama5_mysql/view_payment_after_20220401.sql from view_payment_after_20220401
2022-04-23 09:11:23 ^[[42mnormalization^[[0m > detected no config file for ssh, assuming ssh is off.

**Comment by nshigit** [comment]
docker run --rm --init -i -w /data/11/2/normalize --log-driver none --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e WORKER_ENVIRONMENT=DOCKER -e AIRBYTE_ROLE= -e AIRBYTE_VERSION=0.35.65-alpha airbyte/normalization-mysql:0.1.74 run --integration-type mysql --config destination_config.json --catalog destination_catalog.json
Running: transform-config --config destination_config.json --integration-type mysql --out /data/11/2/normalize
Namespace(config='destination_config.json', integration_type=<DestinationType.mysql: 'mysql'>, out='/data/11/2/normalize')
transform_mysql
Running: transform-catalog --integration-type mysql --profile-config-dir /data/11/2/normalize --catalog destination_catalog.json --out /data/11/2/normalize/models/generated/ --json-column _airbyte_data
Processing destination_catalog.json...
  Generating airbyte_ctes/ama5_mysql/view_payment_after_20220401_ab1.sql from view_payment_after_20220401
  Generating airbyte_ctes/ama5_mysql/view_payment_after_20220401_ab2.sql from view_payment_after_20220401
  Generating airbyte_ctes/ama5_mysql/view_payment_after_20220401_ab3.sql from view_payment_after_20220401
  Generating airbyte_incremental/ama5_mysql/view_payment_after_20220401.sql from view_payment_after_20220401
detected no config file for ssh, assuming ssh is off.
[root@ama_develop 0]# echo $?
1

**Comment by nshigit** [comment]
worker process can't access destination database with 127.0.0.1 as host address.

**Comment by natalyjazzviolin** [comment]
@nshigit, were you able to resolve this issue?
