### ISSUE TITLE
Error fetching schema from MongoDB Atlas

### ISSUE THREAD

**Issue by sergiomanueljimenez** [airbytehq/airbyte#12463]
## Environment
- **Airbyte version**:  0.34.0-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker 
- **Source Connector and version**: airbyte/source-mongodb-v2:0.1.13
- **Destination Connector and version**: airbyte/destination-redshift:0.3.28
- **Severity**: High 
- **Step where error happened**: Setup new connection 

## Current Behavior
Our MongoDB has 50GB generated with a total of 158 collections. We have tested with 400MB of weight in other databases in the same cluster and with that capacity the collections are returned from mongo through Airbyte.

A source (MongoDB) and a destination (AWS Redshift) are generated, once created, the connection from Airbyte to MongoDB is tested and is successful.
When we are going to generate the connection it runs for a few minutes and then we get the error.
<img width="256" alt="image" src="https://user-images.githubusercontent.com/85502041/165894255-e6d2046f-ec23-4815-916c-27a2577fdf8e.png">
So we can't see inside Airbyte the list of collections from MongoDB.

## Expected Behavior
Get the data schema from MongoDB and be able to select the collections to import into Redshift.

## Logs
Our cluster data has been masked inside the log.
[logs-7796e2c1-021b-4d5a-8059-ae5eae8b2cd2-.txt](https://github.com/airbytehq/airbyte/files/8588602/logs-7796e2c1-021b-4d5a-8059-ae5eae8b2cd2-.txt)

<details>
<summary>LOG</summary> 

```

2022-04-28 10:48:56 INFO () TemporalAttemptExecution(get):116 - Executing worker wrapper. Airbyte version: 0.34.0-alpha
2022-04-28 10:48:56 INFO () LineGobbler(voidCall):82 - Checking if airbyte/source-mongodb-v2:0.1.13 exists...
2022-04-28 10:48:56 INFO () DockerProcessFactory(create):127 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/ddfc6c63-713c-4b10-8919-fd1417c96943/0 --network host --log-driver none airbyte/source-mongodb-v2:0.1.13 discover --config source_config.json
2022-04-28 10:48:56 INFO () LineGobbler(voidCall):82 - airbyte/source-mongodb-v2:0.1.13 was found locally.
2022-04-28 10:48:57 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-28 10:48:57 [32mINFO[m i.a.i.s.m.MongoDbSource(main):64 - starting source: class io.airbyte.integrations.source.mongodb.MongoDbSource
2022-04-28 10:48:57 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-28 10:48:57 [32mINFO[m i.a.i.b.IntegrationCliParser(parseOptions):118 - integration args: {discover=null, config=source_config.json}
2022-04-28 10:48:58 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-28 10:48:58 [32mINFO[m i.a.i.b.IntegrationRunner(run):88 - Sentry transaction event: 837cd7e9bc2649ac81a3bebf52d2e58d
2022-04-28 10:48:58 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-28 10:48:58 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):106 - Running integration: io.airbyte.integrations.source.mongodb.MongoDbSource
2022-04-28 10:48:58 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-28 10:48:58 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):107 - Command: DISCOVER
2022-04-28 10:48:58 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-28 10:48:58 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):108 - Integration config: IntegrationConfig{command=DISCOVER, configPath='source_config.json', catalogPath='null', statePath='null'}
2022-04-28 10:48:58 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-28 10:48:58 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2022-04-28 10:48:58 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-28 10:48:58 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword examples - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2022-04-28 10:48:58 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-28 10:48:58 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2022-04-28 10:48:58 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-28 10:48:58 [32mINFO[m c.m.d.l.SLF4JLogger(info):71 - Cluster created with settings {hosts=[127.0.0.1:27017], srvHost=production.HOST.mongodb.net, mode=MULTIPLE, requiredClusterType=REPLICA_SET, serverSelectionTimeout='30000 ms', requiredReplicaSetName='production-shard-0'}
2022-04-28 10:48:58 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-28 10:48:58 [32mINFO[m c.m.d.l.SLF4JLogger(info):71 - Adding discovered server SECOND_SHARD_MONGO to client view of cluster
2022-04-28 10:48:58 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-28 10:48:58 [32mINFO[m c.m.d.l.SLF4JLogger(info):71 - Cluster description not yet available. Waiting for 30000 ms before timing out
2022-04-28 10:48:58 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-28 10:48:58 [32mINFO[m c.m.d.l.SLF4JLogger(info):71 - Adding discovered server THIRD_SHARD_MONGO to client view of cluster
2022-04-28 10:48:58 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-28 10:48:58 [32mINFO[m c.m.d.l.SLF4JLogger(info):71 - Adding discovered server FIRST_SHARD_MONGO to client view of cluster
2022-04-28 10:48:58 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-28 10:48:58 [32mINFO[m c.m.d.l.SLF4JLogger(info):71 - No server chosen by com.mongodb.client.internal.MongoClientDelegate$1@70807224 from cluster description ClusterDescription{type=REPLICA_SET, connectionMode=MULTIPLE, serverDescriptions=[ServerDescription{address= SECOND_SHARD_MONGO, type=UNKNOWN, state=CONNECTING}, ServerDescription{address= THIRD_SHARD_MONGO, type=UNKNOWN, state=CONNECTING}, ServerDescription{address=FIRST_SHARD_MONGO, type=UNKNOWN, state=CONNECTING}]}. Waiting for 30000 ms before timing out
2022-04-28 10:48:59 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-28 10:48:59 [32mINFO[m c.m.d.l.SLF4JLogger(info):71 - Opened connection [connectionId{localValue:4, serverValue:291963}] to THIRD_SHARD_MONGO
2022-04-28 10:48:59 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-28 10:48:59 [32mINFO[m c.m.d.l.SLF4JLogger(info):71 - Opened connection [connectionId{localValue:2, serverValue:291964}] to THIRD_SHARD_MONGO
2022-04-28 10:48:59 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-28 10:48:59 [32mINFO[m c.m.d.l.SLF4JLogger(info):71 - Opened connection [connectionId{localValue:3, serverValue:259583}] to SECOND_SHARD_MONGO
2022-04-28 10:48:59 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-28 10:48:59 [32mINFO[m c.m.d.l.SLF4JLogger(info):71 - Opened connection [connectionId{localValue:6, serverValue:258027}] to FIRST_SHARD_MONGO
2022-04-28 10:48:59 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-28 10:48:59 [32mINFO[m c.m.d.l.SLF4JLogger(info):71 - Opened connection [connectionId{localValue:1, serverValue:259584}] to SECOND_SHARD_MONGO
2022-04-28 10:48:59 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-28 10:48:59 [32mINFO[m c.m.d.l.SLF4JLogger(info):71 - Opened connection [connectionId{localValue:5, serverValue:258026}] to FIRST_SHARD_MONGO
2022-04-28 10:48:59 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-28 10:48:59 [32mINFO[m c.m.d.l.SLF4JLogger(info):71 - Monitor thread successfully connected to server with description ServerDescription{address= FIRST_SHARD_MONGO, type=REPLICA_SET_SECONDARY, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=404458363, setName='production-shard-0', canonicalAddress= SECOND_SHARD_MONGO, hosts=[SECOND_SHARD_MONGO, THIRD_SHARD_MONGO, FIRST_SHARD_MONGO], passives=[], arbiters=[], primary='THIRD_SHARD_MONGO', tagSet=TagSet{[Tag{name='nodeType', value='ELECTABLE'}, Tag{name='provider', value='AWS'}, Tag{name='region', value='US_EAST_1'}, Tag{name='workloadType', value='OPERATIONAL'}]}, electionId=null, setVersion=5, topologyVersion=null, lastWriteDate=Thu Apr 28 10:48:58 UTC 2022, lastUpdateTimeNanos=4997681353685269}
2022-04-28 10:48:59 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-28 10:48:59 [32mINFO[m c.m.d.l.SLF4JLogger(info):71 - Monitor thread successfully connected to server with description ServerDescription{address= THIRD_SHARD_MONGO, type=REPLICA_SET_PRIMARY, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=403649290, setName='production-shard-0', canonicalAddress=THIRD_SHARD_MONGO, hosts=[SECOND_SHARD_MONGO, THIRD_SHARD_MONGO, FIRST_SHARD_MONGO], passives=[], arbiters=[], primary='THIRD_SHARD_MONGO', tagSet=TagSet{[Tag{name='nodeType', value='ELECTABLE'}, Tag{name='provider', value='AWS'}, Tag{name='region', value='US_EAST_1'}, Tag{name='workloadType', value='OPERATIONAL'}]}, electionId=7fffffff0000000000000046, setVersion=5, topologyVersion=null, lastWriteDate=Thu Apr 28 10:48:58 UTC 2022, lastUpdateTimeNanos=4997681352905743}
2022-04-28 10:48:59 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-28 10:48:59 [32mINFO[m c.m.d.l.SLF4JLogger(info):71 - Monitor thread successfully connected to server with description ServerDescription{address= FIRST_SHARD_MONGO, type=REPLICA_SET_SECONDARY, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=403695755, setName='production-shard-0', canonicalAddress= FIRST_SHARD_MONGO, hosts=[SECOND_SHARD_MONGO, THIRD_SHARD_MONGO, FIRST_SHARD_MONGO], passives=[], arbiters=[], primary='THIRD_SHARD_MONGO', tagSet=TagSet{[Tag{name='nodeType', value='ELECTABLE'}, Tag{name='provider', value='AWS'}, Tag{name='region', value='US_EAST_1'}, Tag{name='workloadType', value='OPERATIONAL'}]}, electionId=null, setVersion=5, topologyVersion=null, lastWriteDate=Thu Apr 28 10:48:58 UTC 2022, lastUpdateTimeNanos=4997681353697972}
2022-04-28 10:48:59 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-28 10:48:59 [32mINFO[m c.m.d.l.SLF4JLogger(info):71 - Setting max election id to 7fffffff0000000000000046 from replica set primary THIRD_SHARD_MONGO
2022-04-28 10:48:59 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-28 10:48:59 [32mINFO[m c.m.d.l.SLF4JLogger(info):71 - Setting max set version to 5 from replica set primary THIRD_SHARD_MONGO
2022-04-28 10:48:59 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-28 10:48:59 [32mINFO[m c.m.d.l.SLF4JLogger(info):71 - Discovered replica set primary THIRD_SHARD_MONGO
2022-04-28 10:48:59 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-04-28 10:48:59 [32mINFO[m c.m.d.l.SLF4JLogger(info):71 - Opened connection [connectionId{localValue:7, serverValue:291965}] to THIRD_SHARD_MONGO
2022-04-28 10:49:24 INFO () TemporalAttemptExecution(lambda$getWorkerThread$2):170 - Completing future exceptionally...
io.airbyte.workers.WorkerException: Discover job subprocess finished with exit code 1
	at io.airbyte.workers.DefaultDiscoverCatalogWorker.run(DefaultDiscoverCatalogWorker.java:70) ~[io.airbyte-airbyte-workers-0.34.0-alpha.jar:?]
	at io.airbyte.workers.DefaultDiscoverCatalogWorker.run(DefaultDiscoverCatalogWorker.java:24) ~[io.airbyte-airbyte-workers-0.34.0-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:167) ~[io.airbyte-airbyte-workers-0.34.0-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
2022-04-28 10:49:24 INFO () TemporalAttemptExecution(get):137 - Stopping cancellation check scheduling...
2022-04-28 10:49:24 WARN () POJOActivityTaskHandler(activityFailureToResult):363 - Activity failure. ActivityId=0ff51dd8-d2ec-318a-b597-b6957893142b, activityType=Run, attempt=1
java.util.concurrent.ExecutionException: io.airbyte.workers.WorkerException: Discover job subprocess finished with exit code 1
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:135) ~[io.airbyte-airbyte-workers-0.34.0-alpha.jar:?]
	at io.airbyte.workers.temporal.discover.catalog.DiscoverCatalogActivityImpl.run(DiscoverCatalogActivityImpl.java:82) ~[io.airbyte-airbyte-workers-0.34.0-alpha.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor165.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityInboundCallsInterceptor.execute(POJOActivityTaskHandler.java:286) ~[temporal-sdk-1.6.0.jar:?]
	at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityImplementation.execute(POJOActivityTaskHandler.java:252) ~[temporal-sdk-1.6.0.jar:?]
	at io.temporal.internal.sync.POJOActivityTaskHandler.handle(POJOActivityTaskHandler.java:209) ~[temporal-sdk-1.6.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:193) ~[temporal-sdk-1.6.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:151) ~[temporal-sdk-1.6.0.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73) ~[temporal-sdk-1.6.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: io.airbyte.workers.WorkerException: Discover job subprocess finished with exit code 1
	at io.airbyte.workers.DefaultDiscoverCatalogWorker.run(DefaultDiscoverCatalogWorker.java:70) ~[io.airbyte-airbyte-workers-0.34.0-alpha.jar:?]
	at io.airbyte.workers.DefaultDiscoverCatalogWorker.run(DefaultDiscoverCatalogWorker.java:24) ~[io.airbyte-airbyte-workers-0.34.0-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:167) ~[io.airbyte-airbyte-workers-0.34.0-alpha.jar:?]
	... 1 more

```

</details>

## Steps to Reproduce
1. Create source and destination
2. Check connection to source and destination
3. Setup new connection

**Comment by willycerezo** [comment]
Hi Airbyte team, do you know if you have an ETA for this bug?? thanks in advance and regards

**Comment by misteryeo** [comment]
Hi @willycerezo, [MongoDB](https://docs.airbyte.com/integrations/) is currently [in Alpha](https://docs.airbyte.com/project-overview/product-release-stages/) so we don't have an ETA here. We welcome the community to contribute to fix the bug!

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [Source MongoDB: Fetching schema successfully](https://app.harvestr.io/components/0/list/cCu5jVQWB)

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 365 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.
