### ISSUE TITLE
source shopify: possible rate limit issue

### ISSUE THREAD

**Issue by dsnam** [airbytehq/airbyte#12549]
## Environment
- **Airbyte version**:  0.35.11-alpha
- **OS Version / Instance**: aws ec2 ubuntu 20.04
- **Deployment**: docker
- **Source Connector and version**: seen on shopify 1.26 and 1.36
- **Destination Connector and version**: redshift 3.23
- **Severity**: High
- **Step where error happened**: sync

## Current Behavior
source connector outputs the error from [this situation described in the docs](https://docs.airbyte.com/integrations/sources/shopify/#performance-considerations) but it is failing after waiting 6 times, which seems to be the default backoff limit. For subsequent attempts at running the sync the `orders` stream restarts from where it initially failed and immediately shows the same error, even though in theory subsequent syncs should have consumed far less of the rate limit by the time it gets to `orders`.

We are using airbyte to get data for several shops and only see this issue with one. This shop has massive order objects with a lot of line items so I could see it causing problems for the destination (a few records I've inspected manually are dangerously close to redshift's varchar max), but the error in the logs comes from the source connector which is surprising. Is it possible that some other error is happening and getting caught in a weird way to make it appear that it was a repeat 429 in the logs? It may be relevant that curl `time_total` for an orders request for this shop with the shopify connector's parameters (max of 250 records) is about 11 seconds. Is there some internal timeout that might be exceeding?

## Expected Behavior
sync should continue even if slowly

## Logs

<details>
<summary>Log from initial sync where you can see we've pulled a lot of records before reaching the failure</summary> 

```
2022-04-29 21:33:44 source > Setting state of orders stream to {'updated_at': '2021-07-31T07:06:27-05:00'}
2022-04-29 21:34:03 source > Setting state of orders stream to {'updated_at': '2021-08-10T05:38:40-05:00'}
2022-04-29 21:34:30 source > Setting state of orders stream to {'updated_at': '2021-08-10T07:18:16-05:00'}
2022-04-29 21:34:47 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):281 - Records read: 67000
2022-04-29 21:34:48 source > Setting state of orders stream to {'updated_at': '2021-08-10T10:08:50-05:00'}
2022-04-29 21:35:31 source > Setting state of orders stream to {'updated_at': '2021-08-10T14:00:13-05:00'}
2022-04-29 21:36:52 source > Backing off _send(...) for 5.0s (airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException)
2022-04-29 21:38:19 source > Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2022-04-29 21:38:19 source > Backing off _send(...) for 10.0s (airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException)
2022-04-29 21:39:50 source > Caught retryable error '' after 2 tries. Waiting 10 seconds then retrying...
2022-04-29 21:39:50 source > Backing off _send(...) for 20.0s (airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException)
2022-04-29 21:41:33 source > Caught retryable error '' after 3 tries. Waiting 20 seconds then retrying...
2022-04-29 21:41:33 source > Backing off _send(...) for 40.0s (airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException)
2022-04-29 21:43:34 source > Caught retryable error '' after 4 tries. Waiting 40 seconds then retrying...
2022-04-29 21:43:34 source > Backing off _send(...) for 80.0s (airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException)
2022-04-29 21:46:15 source > Caught retryable error '' after 5 tries. Waiting 80 seconds then retrying...
2022-04-29 21:46:15 source > Giving up _send(...) after 6 tries (airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException)
2022-04-29 21:46:15 source > Encountered an exception while reading stream SourceShopify
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 108, in read
    internal_config=internal_config,
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 141, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 185, in _read_incremental
    for record_counter, record_data in enumerate(records, start=1):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 352, in read_records
    response = self._send_request(request, request_kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 319, in _send_request
    return backoff_handler(user_backoff_handler)(request, request_kwargs)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 282, in _send
    raise DefaultBackoffException(request=request, response=response)
airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException
2022-04-29 23:02:01 source > Finished syncing SourceShopify
2022-04-29 23:02:01 source > SourceShopify runtimes:
2022-04-29 23:02:01 source > 
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 116, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 107, in run
    for message in generator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 112, in read
    raise e
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 108, in read
    internal_config=internal_config,
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 141, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 185, in _read_incremental
    for record_counter, record_data in enumerate(records, start=1):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 352, in read_records
    response = self._send_request(request, request_kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 319, in _send_request
    return backoff_handler(user_backoff_handler)(request, request_kwargs)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 282, in _send
    raise DefaultBackoffException(request=request, response=response)
airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException
```

</details>

<details>
<summary>Log from a subsequent sync that fails immediately at the same point</summary> 

```
2022-04-30 09:59:22 [44msource[0m > Syncing stream: customers 
2022-04-30 09:59:22 [44msource[0m > Setting state of customers stream to {'updated_at': '2022-04-29T17:49:50-05:00'}
2022-04-30 09:59:23 [44msource[0m > Setting state of customers stream to {'updated_at': '2022-04-30T04:59:19-05:00'}
2022-04-30 09:59:23 [44msource[0m > Read 78 records from customers stream
2022-04-30 09:59:23 [44msource[0m > Finished syncing SourceShopify
2022-04-30 09:59:23 [44msource[0m > SourceShopify runtimes:

2022-04-30 09:59:23 [44msource[0m > Syncing stream: orders 
2022-04-30 09:59:23 [44msource[0m > Setting state of orders stream to {'updated_at': '2021-08-10T14:00:13-05:00'}
2022-04-30 10:00:45 [44msource[0m > Backing off _send(...) for 5.0s (airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException)
2022-04-30 10:02:13 [44msource[0m > Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2022-04-30 10:02:13 [44msource[0m > Backing off _send(...) for 10.0s (airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException)
2022-04-30 10:03:45 [44msource[0m > Caught retryable error '' after 2 tries. Waiting 10 seconds then retrying...
2022-04-30 10:03:45 [44msource[0m > Backing off _send(...) for 20.0s (airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException)
2022-04-30 10:05:27 [44msource[0m > Caught retryable error '' after 3 tries. Waiting 20 seconds then retrying...
2022-04-30 10:05:27 [44msource[0m > Backing off _send(...) for 40.0s (airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException)
2022-04-30 10:07:28 [44msource[0m > Caught retryable error '' after 4 tries. Waiting 40 seconds then retrying...
2022-04-30 10:07:28 [44msource[0m > Backing off _send(...) for 80.0s (airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException)
2022-04-30 10:10:09 [44msource[0m > Caught retryable error '' after 5 tries. Waiting 80 seconds then retrying...
2022-04-30 10:10:09 [44msource[0m > Giving up _send(...) after 6 tries (airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException)
2022-04-30 10:10:09 [44msource[0m > Encountered an exception while reading stream SourceShopify
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 108, in read
    internal_config=internal_config,
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 141, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 185, in _read_incremental
    for record_counter, record_data in enumerate(records, start=1):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 352, in read_records
    response = self._send_request(request, request_kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 319, in _send_request
    return backoff_handler(user_backoff_handler)(request, request_kwargs)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 282, in _send
    raise DefaultBackoffException(request=request, response=response)
airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException
2022-04-30 10:10:09 [44msource[0m > Finished syncing SourceShopify
2022-04-30 10:10:09 [44msource[0m > SourceShopify runtimes:

2022-04-30 10:10:09 [44msource[0m > 
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 116, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 107, in run
    for message in generator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 112, in read
    raise e
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 108, in read
    internal_config=internal_config,
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 141, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 185, in _read_incremental
    for record_counter, record_data in enumerate(records, start=1):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 352, in read_records
    response = self._send_request(request, request_kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 319, in _send_request
    return backoff_handler(user_backoff_handler)(request, request_kwargs)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 282, in _send
    raise DefaultBackoffException(request=request, response=response)
airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException
2022-04-30 10:10:09 [43mdestination[0m > 2022-04-30 10:10:09 [32mINFO[m i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):60 - {} - Airbyte message consumer: succeeded.
```

</details>

## Steps to Reproduce
I suspect this is unique to the shop we are seeing the issue with as I can't reproduce it with any other connection. Happy to share whatever will help diagnose, but may need to be over slack DM rather than posted here.

## Are you willing to submit a PR?
If the shopify connector is what needs a change I could take a stab at it, otherwise not familiar enough with anything else.

**Comment by bazarnov** [comment]
@dsnam Looks like the issue was on the Shopify side. Closing this now, once this occurs again, please re-open this issue and attach the complete logs from the failed sync, thank you.
