### ISSUE TITLE
Source Facebook Pages: field `nativeoffers` has been removed from the page endpoint

### ISSUE THREAD

**Issue by TeOdodin** [airbytehq/airbyte#12563]
## Environment
- **Source Connector and version**: 0.1.5 but still present in 0.1.6 ([metrics.py](https://github.com/airbytehq/airbyte/blob/a4e533e25e84ad0effa8010f65ab38e46fcfb480/airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/metrics.py#L253)) 
- **Destination Connector and version**: Postgres 0.3.13 
- **Severity**: Low (because easy to fix in local), High (because prevent sync from Facebook Graph API for Facebook-Pages)
- **Step where error happened**: Sync job (coming from [PAGE_FIELDS](https://github.com/airbytehq/airbyte/blob/a4e533e25e84ad0effa8010f65ab38e46fcfb480/airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/metrics.py#L103) used in [Page](https://github.com/airbytehq/airbyte/blob/a4e533e25e84ad0effa8010f65ab38e46fcfb480/airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/streams.py#L66) stream)

## Current Behavior
Sync does not succeed. Error during api call to Facebook Pages API.

**Error during Sync Job :**
```bash
source - 2022-05-04 08:08:30 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Starting syncing SourceFacebookPages
source - 2022-05-04 08:08:30 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Syncing stream: page 
source - 2022-05-04 08:08:30 ERROR () DefaultAirbyteStreamFactory(internalLog):95 - Encountered an exception while reading stream page
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 119, in read
    internal_config=internal_config,
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 159, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 248, in _read_full_refresh
    for record in records:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 373, in read_records
    response = self._send_request(request, request_kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 337, in _send_request
    return backoff_handler(user_backoff_handler)(request, request_kwargs)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 110, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 110, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 299, in _send
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://graph.facebook.com/v12.0/100647179127461?access_token=****&limit=100&fields=id%2Cabout%2Cad_campaign%2Caffiliation%2Capp_id%2Cartists_we_like%2Cattire%2Cawards%2Cband_interests%2Cband_members%2Cbio%2Cbirthday%2Cbooking_agent%2Cbuilt%2Ccan_checkin%2Ccan_post%2Ccategory%2Ccategory_list%2Ccheckins%2Ccompany_overview%2Cconnected_page_backed_instagram_account%2Ccontact_address%2Ccountry_page_likes%2Ccover%2Cculinary_team%2Ccurrent_location%2Cdelivery_and_pickup_option_info%2Cdescription%2Cdescription_html%2Cdifferently_open_offerings%2Cdirected_by%2Cdisplay_subtext%2Cdisplayed_message_response_time%2Cemails%2Cengagement%2Cfan_count%2Cfeatured_video%2Cfeatures%2Cfollowers_count%2Cfood_styles%2Cfounded%2Cgeneral_info%2Cgeneral_manager%2Cgenre%2Cglobal_brand_page_name%2Cglobal_brand_root_id%2Chas_added_app%2Chas_transitioned_to_new_page_experience%2Chas_whatsapp_business_number%2Chas_whatsapp_number%2Chometown%2Chours%2Cimpressum%2Cinfluences%2Cis_always_open%2Cis_chain%2Cis_community_page%2Cis_eligible_for_branded_content%2Cis_messenger_bot_get_started_enabled%2Cis_messenger_platform_bot%2Cis_owned%2Cis_permanently_closed%2Cis_published%2Cis_unclaimed%2Cis_webhooks_subscribed%2Cleadgen_tos_acceptance_time%2Cleadgen_tos_accepted%2Cleadgen_tos_accepting_user%2Clink%2Clocation%2Cmembers%2Cmerchant_review_status%2Cmessenger_ads_default_icebreakers%2Cmessenger_ads_default_page_welcome_message%2Cmessenger_ads_default_quick_replies%2Cmessenger_ads_quick_replies_type%2Cmission%2Cmpg%2Cname%2Cname_with_location_descriptor%2Cnetwork%2Cnew_like_count%2Coffer_eligible%2Coverall_star_rating%2Cpage_token%2Cparking%2Cpayment_options%2Cpersonal_info%2Cpersonal_interests%2Cpharma_safety_info%2Cphone%2Cpickup_options%2Cplace_type%2Cplot_outline%2Cpreferred_audience%2Cpress_contact%2Cprice_range%2Cprivacy_info_url%2Cproduced_by%2Cproducts%2Cpromotion_eligible%2Cpromotion_ineligible_reason%2Cpublic_transit%2Crating_count%2Crecord_label%2Crelease_date%2Crestaurant_services%2Crestaurant_specialties%2Cschedule%2Cscreenplay_by%2Cseason%2Csingle_line_address%2Cstarring%2Cstart_info%2Cstore_code%2Cstore_location_descriptor%2Cstore_number%2Cstudio%2Csupports_donate_button_in_live_video%2Ctalking_about_count%2Ctemporary_status%2Cunread_message_count%2Cunread_notif_count%2Cunseen_message_count%2Cusername%2Cverification_status%2Cvoip_info%2Cwebsite%2Cwere_here_count%2Cwhatsapp_number%2Cwritten_by%2Calbums%2Cblocked%2Ccall_to_actions%2Ccanvas_elements%2Ccommerce_merchant_settings%2Cevents%2Cfeed%2Cglobal_brand_children%2Cgroups%2Cimage_copyrights%2Cindexed_videos%2Cinstagram_accounts%2Clikes%2Clive_videos%2Clocations%2Cpage_backed_instagram_accounts%2Cphotos%2Cposts%2Cproduct_catalogs%2Cpublished_posts%2Cratings%2Croles%2Crtb_dynamic_posts%2Cscheduled_posts%2Csettings%2Ctabs%2Ctagged%2Cvideo_lists%2Cvideos%2Cvisitor_posts
```

**Error from Facebook Graph API Explorer :**
```json
{
  "error": {
    "message": "(#100) Tried accessing nonexisting field (nativeoffers) on node type (Page)",
    "type": "OAuthException",
    "code": 100,
    "fbtrace_id": "AXcqDcDg0UcLJ9jdnFsa0ka"
  }
}
```

## Expected Behavior
Call to `/page?fields=...` endpoints works fine and the Sync succeeds.

## Steps to Reproduce
1. Create a connection with the facebook pages connector
2. Try to sync.

**Comment by artem1205** [comment]
Fixed in https://github.com/airbytehq/airbyte/pull/19788
