### ISSUE TITLE
HTTP-Source: Sync error

### ISSUE THREAD

**Issue by awoehrl** [airbytehq/airbyte#1258]
I tried to connect an API with BigQuery, but it failed with the following error message. The first step seemed to be successful, but then the data model? failed?
```

2020-12-09 08:42:54 INFO (/tmp/workspace/29/0) WorkerRun(call):58 - Executing worker wrapper...
2020-12-09 08:42:54 INFO (/tmp/workspace/29/0) DefaultSyncWorker(run):75 - configured sync modes: {data=full_refresh}
2020-12-09 08:42:54 INFO (/tmp/workspace/29/0) DefaultAirbyteDestination(start):67 - Running target...
2020-12-09 08:42:54 DEBUG (/tmp/workspace/29/0) DockerProcessBuilderFactory(create):103 - Preparing command: docker run --rm -i -v workspace:/data -v /tmp/airbyte_local:/local -w /data/29/0 --network host airbyte/destination-bigquery:0.1.10 write --config target_config.json --catalog catalog.json
2020-12-09 08:42:54 DEBUG (/tmp/workspace/29/0) DockerProcessBuilderFactory(create):103 - Preparing command: docker run --rm -i -v workspace:/data -v /tmp/airbyte_local:/local -w /data/29/0 --network host airbyte/source-http-request:0.1.0 read --config tap_config.json --catalog catalog.json
2020-12-09 08:42:56 INFO (/tmp/workspace/29/0) DefaultSyncWorker(run):99 - Running normalization.
2020-12-09 08:42:56 DEBUG (/tmp/workspace/29/0) DockerProcessBuilderFactory(create):103 - Preparing command: docker run --rm -i -v workspace:/data -v /tmp/airbyte_local:/local -w /data/29/0/normalize --network host airbyte/normalization:0.1.2 run --integration-type bigquery --config target_config.json --catalog catalog.json
2020-12-09 08:42:57 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 - 2020-12-09 08:42:57 [32mINFO[m i.a.i.d.b.BigQueryDestination(main):391 - {} - starting destination: class io.airbyte.integrations.destination.bigquery.BigQueryDestination
2020-12-09 08:42:57 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 - 2020-12-09 08:42:57 [32mINFO[m i.a.i.b.IntegrationRunner(run):79 - {} - Running integration: io.airbyte.integrations.destination.bigquery.BigQueryDestination
2020-12-09 08:42:57 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 - 2020-12-09 08:42:57 [32mINFO[m i.a.i.b.IntegrationCliParser(parseOptions):135 - {} - integration args: {catalog=catalog.json, write=null, config=target_config.json}
2020-12-09 08:42:57 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 - 2020-12-09 08:42:57 [32mINFO[m i.a.i.b.IntegrationRunner(run):83 - {} - Command: WRITE
2020-12-09 08:42:57 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 - 2020-12-09 08:42:57 [32mINFO[m i.a.i.b.IntegrationRunner(run):84 - {} - Integration config: IntegrationConfig{command=WRITE, configPath='target_config.json', catalogPath='catalog.json', statePath='null'}
2020-12-09 08:42:58 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 - Namespace(config='target_config.json', integration_type=<DestinationType.bigquery: 'bigquery'>, out='/data/29/0/normalize')
2020-12-09 08:42:58 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 - transform_bigquery
2020-12-09 08:42:58 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 - Processing catalog.json...
2020-12-09 08:42:58 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 - Generating data.sql in /data/29/0/normalize/models/generated/
2020-12-09 08:43:00 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 - 2020-12-09 08:43:00 [32mINFO[m i.a.i.d.b.BigQueryDestination(createTable):270 - {} - Table created successfully
2020-12-09 08:43:01 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 - 2020-12-09 08:43:01 [32mINFO[m i.a.i.b.FailureTrackingConsumer(close):50 - {} - hasFailed: false.
2020-12-09 08:43:04 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 - Running with dbt=0.18.1
2020-12-09 08:43:04 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 - 2020-12-09 08:43:04 [1;31mERROR[m i.a.i.d.b.BigQueryDestination$RecordConsumer(close):345 - {} - executing on success close procedure.
2020-12-09 08:43:06 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 - 2020-12-09 08:43:06 [32mINFO[m i.a.i.b.IntegrationRunner(run):120 - {} - Completed integration: io.airbyte.integrations.destination.bigquery.BigQueryDestination
2020-12-09 08:43:06 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 - 2020-12-09 08:43:06 [32mINFO[m i.a.i.d.b.BigQueryDestination(main):393 - {} - completed destination: class io.airbyte.integrations.destination.bigquery.BigQueryDestination
2020-12-09 08:43:12 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 - Installing https://github.com/fishtown-analytics/dbt-utils.git@0.6.2
2020-12-09 08:43:13 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 - Installed from revision 0.6.2
2020-12-09 08:43:13 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 -
2020-12-09 08:43:15 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 - Running with dbt=0.18.1
2020-12-09 08:43:19 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 - Found 1 model, 0 tests, 0 snapshots, 0 analyses, 319 macros, 0 operations, 0 seed files, 1 source
2020-12-09 08:43:19 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 -
2020-12-09 08:43:20 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 - 08:43:20 | Concurrency: 32 threads (target='prod')
2020-12-09 08:43:20 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 - 08:43:20 |
2020-12-09 08:43:20 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 - 08:43:20 | 1 of 1 START table model articles.data....................................................................... [RUN]
2020-12-09 08:43:23 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 - 08:43:23 | 1 of 1 ERROR creating table model articles.data.............................................................. [[31mERROR[0m in 2.52s]
2020-12-09 08:43:23 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 - 08:43:23 |
2020-12-09 08:43:23 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 - 08:43:23 | Finished running 1 table model in 3.77s.
2020-12-09 08:43:23 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 -
2020-12-09 08:43:23 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 - [31mCompleted with 1 error and 0 warnings:[0m
2020-12-09 08:43:23 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 -
2020-12-09 08:43:23 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 - [33mDatabase Error in model data (models/generated/data.sql)[0m
2020-12-09 08:43:23 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 - No matching signature for function CONCAT with no arguments. Supported signatures: CONCAT(STRING, [STRING, ...]); CONCAT(BYTES, [BYTES, ...]) at [24:21]
2020-12-09 08:43:23 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 - compiled SQL at ../build/run/airbyte_utils/models/generated/data.sql
2020-12-09 08:43:23 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 -
2020-12-09 08:43:23 INFO (/tmp/workspace/29/0) LineGobbler(voidCall):69 - Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
2020-12-09 08:43:23 DEBUG (/tmp/workspace/29/0) DefaultNormalizationRunner(close):97 - Closing tap process
2020-12-09 08:43:23 DEBUG (/tmp/workspace/29/0) DefaultAirbyteSource(close):109 - Closing tap process
2020-12-09 08:43:23 DEBUG (/tmp/workspace/29/0) DefaultAirbyteDestination(close):102 - Closing target process
2020-12-09 08:43:23 ERROR (/tmp/workspace/29/0) DefaultSyncWorker(run):107 - Sync worker failed.
io.airbyte.workers.WorkerException: Normalization Failed.
at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:103) [io.airbyte-airbyte-workers-0.7.0-alpha.jar:?]
at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:48) [io.airbyte-airbyte-workers-0.7.0-alpha.jar:?]
at io.airbyte.workers.wrappers.OutputConvertingWorker.run(OutputConvertingWorker.java:44) [io.airbyte-airbyte-workers-0.7.0-alpha.jar:?]
at io.airbyte.workers.wrappers.JobOutputSyncWorker.run(JobOutputSyncWorker.java:32) [io.airbyte-airbyte-workers-0.7.0-alpha.jar:?]
at io.airbyte.scheduler.WorkerRun.lambda$new$0(WorkerRun.java:53) [io.airbyte-airbyte-scheduler-0.7.0-alpha.jar:?]
at io.airbyte.scheduler.WorkerRun.call(WorkerRun.java:61) [io.airbyte-airbyte-scheduler-0.7.0-alpha.jar:?]
at io.airbyte.scheduler.WorkerRun.call(WorkerRun.java:42) [io.airbyte-airbyte-scheduler-0.7.0-alpha.jar:?]
at io.airbyte.commons.concurrency.LifecycledCallable.execute(LifecycledCallable.java:114) [io.airbyte-airbyte-commons-0.7.0-alpha.jar:?]
at io.airbyte.commons.concurrency.LifecycledCallable.call(LifecycledCallable.java:98) [io.airbyte-airbyte-commons-0.7.0-alpha.jar:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
at java.lang.Thread.run(Thread.java:832) [?:?]
Suppressed: io.airbyte.workers.WorkerException: Tap process wasn't successful
at io.airbyte.workers.normalization.DefaultNormalizationRunner.close(DefaultNormalizationRunner.java:100) ~[io.airbyte-airbyte-workers-0.7.0-alpha.jar:?]
at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:98) [io.airbyte-airbyte-workers-0.7.0-alpha.jar:?]
at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:48) [io.airbyte-airbyte-workers-0.7.0-alpha.jar:?]
at io.airbyte.workers.wrappers.OutputConvertingWorker.run(OutputConvertingWorker.java:44) [io.airbyte-airbyte-workers-0.7.0-alpha.jar:?]
at io.airbyte.workers.wrappers.JobOutputSyncWorker.run(JobOutputSyncWorker.java:32) [io.airbyte-airbyte-workers-0.7.0-alpha.jar:?]
at io.airbyte.scheduler.WorkerRun.lambda$new$0(WorkerRun.java:53) [io.airbyte-airbyte-scheduler-0.7.0-alpha.jar:?]
at io.airbyte.scheduler.WorkerRun.call(WorkerRun.java:61) [io.airbyte-airbyte-scheduler-0.7.0-alpha.jar:?]
at io.airbyte.scheduler.WorkerRun.call(WorkerRun.java:42) [io.airbyte-airbyte-scheduler-0.7.0-alpha.jar:?]
at io.airbyte.commons.concurrency.LifecycledCallable.execute(LifecycledCallable.java:114) [io.airbyte-airbyte-commons-0.7.0-alpha.jar:?]
at io.airbyte.commons.concurrency.LifecycledCallable.call(LifecycledCallable.java:98) [io.airbyte-airbyte-commons-0.7.0-alpha.jar:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
at java.lang.Thread.run(Thread.java:832) [?:?]



```

**Comment by cgardens** [comment]
@awoehrl - thanks for reporting! we'll take a look.

@ChristopheDuong - would you be willing to take a look at this. looks like something is happening in normalization.

**Comment by ChristopheDuong** [comment]
Source and Destination docker images are started at 08:42:54:
```
2020-12-09 08:42:54 DEBUG (/tmp/workspace/29/0) DockerProcessBuilderFactory(create):103 - Preparing command: docker run --rm -i -v workspace:/data -v /tmp/airbyte_local:/local -w /data/29/0 --network host airbyte/destination-bigquery:0.1.10 write --config target_config.json --catalog catalog.json
2020-12-09 08:42:54 DEBUG (/tmp/workspace/29/0) DockerProcessBuilderFactory(create):103 - Preparing command: docker run --rm -i -v workspace:/data -v /tmp/airbyte_local:/local -w /data/29/0 --network host airbyte/source-http-request:0.1.0 read --config tap_config.json --catalog catalog.json
``` 

Only 2 seconds later, Normalization is also started right after:
```
2020-12-09 08:42:56 INFO (/tmp/workspace/29/0) DefaultSyncWorker(run):99 - Running normalization.
2020-12-09 08:42:56 DEBUG (/tmp/workspace/29/0) DockerProcessBuilderFactory(create):103 - Preparing command: docker run --rm -i -v workspace:/data -v /tmp/airbyte_local:/local -w /data/29/0/normalize --network host airbyte/normalization:0.1.2 run --integration-type bigquery --config target_config.json --catalog catalog.json
```

Shouldn't the tap/target images finish first before we invoke normalization? (so that the _raw table is fully ready?)

```
2020-12-09 08:43:23 DEBUG (/tmp/workspace/29/0) DefaultNormalizationRunner(close):97 - Closing tap process
2020-12-09 08:43:23 DEBUG (/tmp/workspace/29/0) DefaultAirbyteSource(close):109 - Closing tap process
2020-12-09 08:43:23 DEBUG (/tmp/workspace/29/0) DefaultAirbyteDestination(close):102 - Closing target process
```

**Comment by michel-tricot** [comment]
Glancing through the code I can see what the issue could be:
`io/airbyte/workers/DefaultSyncWorker.java:82`

the Normalization happens in the try resource. I believe it should happen after.

**Comment by cgardens** [comment]
yeah. i realized the same thing. just put up a fix.
