### ISSUE TITLE
Facebook Marketing JSON to AVRO conversion fails for field video_play_actions

### ISSUE THREAD

**Issue by hbd** [airbytehq/airbyte#12597]
## Environment
- **Airbyte version**:  example is 0.36.2-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker Compose, single instance
- **Source Connector and version**: Facebook Marketing @ 0.2.45
- **Destination Connector and version**: S3 @ 0.3.4
- **Severity**: High
- **Step where error happened**: Sync job

## Current Behavior
Facebook Marketing sync jobs are resulting in an error (see logs) and therefore failing.

## Expected Behavior
I expect the sync job to complete successfully.

## Logs

<details>
<summary>LOG</summary> 

```

2022-05-05 06:25:35 [43mdestination[0m > 2022-05-05 06:25:35 [1;31mERROR[m i.a.i.b.FailureTrackingAirbyteMessageConsumer(accept):52 - Exception while accepting message
2022-05-05 06:25:35 [43mdestination[0m > tech.allegro.schema.json2avro.converter.AvroConversionException: Failed to convert JSON to Avro: Could not evaluate union, field video_play_actions is expected to be one of these: NULL, ARRAY. If this is a complex type, check if offending field (path: video_play_actions.value) adheres to schema: [{action_type=video_view, value=659.0, 1d_view=655.0, 7d_view=655.0, 28d_view=655.0, 1d_click=4.0, 7d_click=4.0, 28d_click=4.0}]
2022-05-05 06:25:35 [43mdestination[0m > 	at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.read(JsonGenericRecordReader.java:129) ~[converter-1.0.1.jar:?]
2022-05-05 06:25:35 [43mdestination[0m > 	at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.read(JsonGenericRecordReader.java:118) ~[converter-1.0.1.jar:?]
2022-05-05 06:25:35 [43mdestination[0m > 	at tech.allegro.schema.json2avro.converter.JsonAvroConverter.convertToGenericDataRecord(JsonAvroConverter.java:95) ~[converter-1.0.1.jar:?]
2022-05-05 06:25:35 [43mdestination[0m > 	at io.airbyte.integrations.destination.s3.avro.AvroRecordFactory.getAvroRecord(AvroRecordFactory.java:39) ~[io.airbyte.airbyte-integrations.connectors-destination-s3-0.36.8-alpha.jar:?]
2022-05-05 06:25:35 [43mdestination[0m > 	at io.airbyte.integrations.destination.s3.parquet.ParquetSerializedBuffer.accept(ParquetSerializedBuffer.java:93) ~[io.airbyte.airbyte-integrations.connectors-destination-s3-0.36.8-alpha.jar:?]
2022-05-05 06:25:35 [43mdestination[0m > 	at io.airbyte.integrations.destination.record_buffer.SerializedBufferingStrategy.addRecord(SerializedBufferingStrategy.java:69) ~[io.airbyte.airbyte-integrations.bases-base-java-0.36.8-alpha.jar:?]
2022-05-05 06:25:35 [43mdestination[0m > 	at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.acceptTracked(BufferedStreamConsumer.java:137) ~[io.airbyte.airbyte-integrations.bases-base-java-0.36.8-alpha.jar:?]
2022-05-05 06:25:35 [43mdestination[0m > 	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.accept(FailureTrackingAirbyteMessageConsumer.java:50) ~[io.airbyte.airbyte-integrations.bases-base-java-0.36.8-alpha.jar:?]
2022-05-05 06:25:35 [43mdestination[0m > 	at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:192) ~[io.airbyte.airbyte-integrations.bases-base-java-0.36.8-alpha.jar:?]
2022-05-05 06:25:35 [43mdestination[0m > 	at io.airbyte.integrations.base.IntegrationRunner.lambda$runConsumer$4(IntegrationRunner.java:201) ~[io.airbyte.airbyte-integrations.bases-base-java-0.36.8-alpha.jar:?]
2022-05-05 06:25:35 [43mdestination[0m > 	at io.airbyte.integrations.base.IntegrationRunner.watchForOrphanThreads(IntegrationRunner.java:230) ~[io.airbyte.airbyte-integrations.bases-base-java-0.36.8-alpha.jar:?]
2022-05-05 06:25:35 [43mdestination[0m > 	at io.airbyte.integrations.base.IntegrationRunner.runConsumer(IntegrationRunner.java:200) ~[io.airbyte.airbyte-integrations.bases-base-java-0.36.8-alpha.jar:?]
2022-05-05 06:25:35 [43mdestination[0m > 	at io.airbyte.integrations.base.IntegrationRunner.lambda$runInternal$1(IntegrationRunner.java:163) ~[io.airbyte.airbyte-integrations.bases-base-java-0.36.8-alpha.jar:?]
2022-05-05 06:25:35 [43mdestination[0m > 	at io.airbyte.integrations.base.sentry.AirbyteSentry.executeWithTracing(AirbyteSentry.java:54) [io.airbyte.airbyte-integrations.bases-base-java-0.36.8-alpha.jar:?]
2022-05-05 06:25:35 [43mdestination[0m > 	at io.airbyte.integrations.base.sentry.AirbyteSentry.executeWithTracing(AirbyteSentry.java:38) [io.airbyte.airbyte-integrations.bases-base-java-0.36.8-alpha.jar:?]
2022-05-05 06:25:35 [43mdestination[0m > 	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:163) [io.airbyte.airbyte-integrations.bases-base-java-0.36.8-alpha.jar:?]
2022-05-05 06:25:35 [43mdestination[0m > 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:105) [io.airbyte.airbyte-integrations.bases-base-java-0.36.8-alpha.jar:?]
2022-05-05 06:25:35 [43mdestination[0m > 	at io.airbyte.integrations.destination.s3.S3Destination.main(S3Destination.java:51) [io.airbyte.airbyte-integrations.connectors-destination-s3-0.36.8-alpha.jar:?]

```

</details>

## Steps to Reproduce
1. Create Facebook Marketing connection to an S3 destination
2. Run sync job

## Are you willing to submit a PR?

Yes, if this is a schema change

**Comment by hbd** [comment]
I don't see any changes to [the field](https://developers.facebook.com/docs/marketing-api/reference/ads-insights/) in the API docs. Could this be related to a [potential bug](https://github.com/allegro/json-avro-converter/issues/59) with Allegro?

**Comment by marcosmarxm** [comment]
@hbd I'm closing due inactivity, could you try to use latest version of FB Marketing connector? If the problem continue please open a new issue.
