### ISSUE TITLE
octavia-cli: `--help` on subcommands raises `Attribute error`

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#12653]
## Environment
- **Airbyte version**: 0.36.6
- **Severity**: Medium

## Current Behavior
When running help on subcommand the following error is raised:
```bash
octavia apply --help
```
```
Traceback (most recent call last):
  File "/usr/local/bin/octavia", line 8, in <module>
    sys.exit(octavia())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/base_commands.py", line 31, in make_context
    telemetry_client.send_command_telemetry(parent, error=e, extra_info_name=info_name)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/telemetry.py", line 87, in send_command_telemetry
    command_name = self._create_command_name(ctx, extra_info_name)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/telemetry.py", line 61, in _create_command_name
    command_names.insert(0, ctx.info_name)
AttributeError: 'str' object has no attribute 'insert'
```

## Expected Behavior
No error should be raised.

**This problem is related to the command name parsing used in the telemetry**

**Comment by Imbruced** [comment]
Also I saw that exception. 

And found the root cause

That is the code how it should looks like

```python 
command_name = self._create_command_name(ctx, extra_info_name=extra_info_name)
```

and that is on main branch

```python
command_name = self._create_command_name(ctx, extra_info_name)

```

And based on signature 

```python
def _create_command_name(self, ctx: click.Context, command_names: Optional[list] = None, extra_info_name: Optional[str] = None) -> str:
```

and bcs of that extra_info_name is passed to argument command_names

If you dont mind I can create pull request for that.

**Comment by Imbruced** [comment]
Created small pr for that, let me know if I am missing anything. https://github.com/airbytehq/airbyte/pull/12691
