### ISSUE TITLE
UI "Unknown error occured" after upgrade because "jsonSchemaNode" is null

### ISSUE THREAD

**Issue by grkhr** [airbytehq/airbyte#13015]
Hi!

I've upgraded from 0.36.2 to 0.38.4 and now can't access the UI. 
<img width="449" alt="image" src="https://user-images.githubusercontent.com/40689054/169276865-f65fcace-40b0-4906-85cf-111c58690135.png">

`Error: Internal Server Error: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.isObject()" because "jsonSchemaNode" is null`

<img width="872" alt="image" src="https://user-images.githubusercontent.com/40689054/169277120-d7a5fc17-f342-433a-b24f-9e8d50a42598.png">

## Environment
- **Airbyte version**:  0.38.4-alpha
- **OS Version / Instance**: Ubuntu 20.04.4 on GCP (2cpu 16gb)
- **Deployment**: Docker compose & .env (airbyte database instance is in Google Cloud SQL)
- **Severity**: Critical

## Steps to Reproduce
1. Run 0.36.2 on GCP
2. Upgrade via docker-compose to 0.38.4
3. Try to access the UI

## Logs
```
2022-05-19 10:54:39 ERROR i.a.s.e.UncaughtExceptionMapper(toResponse):22 - Uncaught exception
java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.isObject()" because "jsonSchemaNode" is null
	at io.airbyte.commons.json.JsonSchemas.traverseJsonSchemaInternal(JsonSchemas.java:152) ~[io.airbyte-airbyte-commons-0.38.1-alpha.jar:?]
	at io.airbyte.commons.json.JsonSchemas.traverseJsonSchemaInternal(JsonSchemas.java:168) ~[io.airbyte-airbyte-commons-0.38.1-alpha.jar:?]
	at io.airbyte.commons.json.JsonSchemas.traverseJsonSchemaInternal(JsonSchemas.java:177) ~[io.airbyte-airbyte-commons-0.38.1-alpha.jar:?]
	at io.airbyte.commons.json.JsonSchemas.traverseJsonSchema(JsonSchemas.java:99) ~[io.airbyte-airbyte-commons-0.38.1-alpha.jar:?]
	at io.airbyte.commons.json.JsonSchemas.traverseJsonSchemaWithCollector(JsonSchemas.java:116) ~[io.airbyte-airbyte-commons-0.38.1-alpha.jar:?]
	at io.airbyte.commons.json.JsonSchemas.collectJsonPathsThatMeetCondition(JsonSchemas.java:129) ~[io.airbyte-airbyte-commons-0.38.1-alpha.jar:?]
	at io.airbyte.config.persistence.split_secrets.JsonSecretsProcessor.maskAllSecrets(JsonSecretsProcessor.java:75) ~[io.airbyte.airbyte-config-persistence-0.38.1-alpha.jar:?]
	at io.airbyte.config.persistence.split_secrets.JsonSecretsProcessor.prepareSecretsForOutput(JsonSecretsProcessor.java:60) ~[io.airbyte.airbyte-config-persistence-0.38.1-alpha.jar:?]
	at io.airbyte.server.handlers.SourceHandler.buildSourceRead(SourceHandler.java:256) ~[io.airbyte-airbyte-server-0.38.1-alpha.jar:?]
	at io.airbyte.server.handlers.SourceHandler.buildSourceRead(SourceHandler.java:247) ~[io.airbyte-airbyte-server-0.38.1-alpha.jar:?]
	at io.airbyte.server.handlers.SourceHandler.getSource(SourceHandler.java:130) ~[io.airbyte-airbyte-server-0.38.1-alpha.jar:?]
	at io.airbyte.server.handlers.WebBackendConnectionsHandler.getSourceRead(WebBackendConnectionsHandler.java:130) ~[io.airbyte-airbyte-server-0.38.1-alpha.jar:?]
	at io.airbyte.server.handlers.WebBackendConnectionsHandler.buildWebBackendConnectionRead(WebBackendConnectionsHandler.java:115) ~[io.airbyte-airbyte-server-0.38.1-alpha.jar:?]
	at io.airbyte.server.handlers.WebBackendConnectionsHandler.webBackendListConnectionsForWorkspace(WebBackendConnectionsHandler.java:98) ~[io.airbyte-airbyte-server-0.38.1-alpha.jar:?]
	at io.airbyte.server.apis.ConfigurationApi.lambda$webBackendListConnectionsForWorkspace$85(ConfigurationApi.java:808) ~[io.airbyte-airbyte-server-0.38.1-alpha.jar:?]
	at io.airbyte.server.apis.ConfigurationApi.execute(ConfigurationApi.java:874) ~[io.airbyte-airbyte-server-0.38.1-alpha.jar:?]
	at io.airbyte.server.apis.ConfigurationApi.webBackendListConnectionsForWorkspace(ConfigurationApi.java:808) ~[io.airbyte-airbyte-server-0.38.1-alpha.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394) ~[jersey-container-servlet-core-2.31.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) ~[jersey-container-servlet-core-2.31.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366) ~[jersey-container-servlet-core-2.31.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319) ~[jersey-container-servlet-core-2.31.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) ~[jersey-container-servlet-core-2.31.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:569) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1377) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:507) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.Server.handle(Server.java:501) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at java.lang.Thread.run(Thread.java:833) [?:?]
2022-05-19 10:54:39 ERROR i.a.s.RequestLogger(filter):110 - REQ 172.24.0.3 POST 500 /api/v1/web_backend/connections/list - {"workspaceId":"67fe71a4-0f4a-49c9-a8f0-a99eb033291a"}
```

**Comment by grkhr** [comment]
Ah, yes, I have some custom builded sources

**Comment by grkhr** [comment]
Bump :(

**Comment by marcosmarxm** [comment]
should not be a problem the custom connector. sorry the delay @grkhr and thanks for the info. I'll try to reproduce here with the same env as yours.

**Comment by Grayfados** [comment]
Hi there. I've faced the same problem here in my environment and I found that the problem is between the 0.36.4-alpha and 0.36.5-aplha release. I´ve made a bisect but I couldn't find the exact commit yet. I will try to find the exact commit that is generating this error and report here.

**Comment by marcosmarxm** [comment]
@Grayfados can you still have the problem with latest version of Airbyte?

**Comment by grkhr** [comment]
Still happening with 0.39.18-alpha.

**Comment by Tamir-Spector** [comment]
Hey , I have the same issue -
After updating a source (Salesforce) it failed to update, and when refreshing I got the same message as yours 
someone?

**Comment by mp-pinheiro** [comment]
Same issue here! Upgraded from `0.34.2` to `0.39.24` and now all connections show "Unknown Error". 

```
{"message":"Internal Server Error: Cannot invoke \"io.airbyte.config.ResetSourceConfiguration.getStreamsToReset()\" because the return value of \"io.airbyte.config.JobResetConnectionConfig.getResetSourceConfiguration()\" is null","exceptionClassName":"java.lang.NullPointerException","exceptionStack":["java.lang.NullPointerException: Cannot invoke \"io.airbyte.config.ResetSourceConfiguration.getStreamsToReset()\" because the return value of \"io.airbyte.config.JobResetConnectionConfig.getResetSourceConfiguration()\" is null","\tat io.airbyte.server.converters.JobConverter.extractResetConfigIfReset(JobConverter.java:105)","\tat io.airbyte.server.converters.JobConverter.getJobWithAttemptsRead(JobConverter.java:88)","\tat io.airbyte.server.handlers.JobHistoryHandler.lambda$listJobsFor$1(JobHistoryHandler.java:89)","\tat java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)","\tat java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)","\tat java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)","\tat java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)","\tat java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)","\tat java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)","\tat java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)","\tat io.airbyte.server.handlers.JobHistoryHandler.listJobsFor(JobHistoryHandler.java:90)","\tat io.airbyte.server.apis.ConfigurationApi.lambda$listJobsFor$81(ConfigurationApi.java:761)","\tat io.airbyte.server.apis.ConfigurationApi.execute(ConfigurationApi.java:860)","\tat io.airbyte.server.apis.ConfigurationApi.listJobsFor(ConfigurationApi.java:761)","\tat jdk.internal.reflect.GeneratedMethodAccessor406.invoke(Unknown Source)","\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)","\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)","\tat org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)","\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)","\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)","\tat org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)","\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)","\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)","\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)","\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)","\tat org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)","\tat org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)","\tat org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)","\tat org.glassfish.jersey.internal.Errors.process(Errors.java:292)","\tat org.glassfish.jersey.internal.Errors.process(Errors.java:274)","\tat org.glassfish.jersey.internal.Errors.process(Errors.java:244)","\tat org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)","\tat org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)","\tat org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)","\tat org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)","\tat org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)","\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)","\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)","\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)","\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)","\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:569)","\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)","\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1377)","\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)","\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:507)","\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)","\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292)","\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)","\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)","\tat org.eclipse.jetty.server.Server.handle(Server.java:501)","\tat org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)","\tat org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)","\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)","\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)","\tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)","\tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)","\tat org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)","\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)","\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)","\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)","\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)","\tat org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)","\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)","\tat org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)","\tat java.base/java.lang.Thread.run(Thread.java:833)"],"rootCauseExceptionStack":[]}
```

**Comment by marcosmarxm** [comment]
Also would be possible to upgrade to 0.39.25+? https://github.com/airbytehq/airbyte/pull/14018 proposal is to solve the issue.

**Comment by marcosmarxm** [comment]
I'm closing this due inactivity. Please open a new one if the problem repeats.
