### ISSUE TITLE
Connect to meilisearch(Version: 0.27) failed, error log: Check connection failed: The Authorization header is missing. It must use the bearer authorization method.

### ISSUE THREAD

**Issue by vzer** [airbytehq/airbyte#13076]
- airbyte version: 0.39.1-alpha
- meilisearch version : 0.27
- error log
```
2022-05-22 06:42:03 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):108 - Docker volume job log path: /tmp/workspace/2888d5f2-fb0b-4244-9f35-c71db235a43b/0/logs.log
2022-05-22 06:42:03 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):113 - Executing worker wrapper. Airbyte version: 0.39.1-alpha
2022-05-22 06:42:03 [32mINFO[m i.a.c.i.LineGobbler(voidCall):82 - Checking if airbyte/destination-meilisearch:0.2.12 exists...
2022-05-22 06:42:03 [32mINFO[m i.a.c.i.LineGobbler(voidCall):82 - airbyte/destination-meilisearch:0.2.12 was found locally.
2022-05-22 06:42:03 [32mINFO[m i.a.w.p.DockerProcessFactory(create):108 - Creating docker job ID: 2888d5f2-fb0b-4244-9f35-c71db235a43b
2022-05-22 06:42:03 [32mINFO[m i.a.w.p.DockerProcessFactory(create):163 - Preparing command: docker run --rm --init -i -w /data/2888d5f2-fb0b-4244-9f35-c71db235a43b/0 --log-driver none --name destination-meilisearch-check-2888d5f2-fb0b-4244-9f35-c71db235a43b-0-suyzo --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e WORKER_CONNECTOR_IMAGE=airbyte/destination-meilisearch:0.2.12 -e WORKER_JOB_ATTEMPT=0 -e WORKER_ENVIRONMENT=DOCKER -e AIRBYTE_ROLE= -e AIRBYTE_VERSION=0.39.1-alpha -e WORKER_JOB_ID=2888d5f2-fb0b-4244-9f35-c71db235a43b airbyte/destination-meilisearch:0.2.12 check --config source_config.json
2022-05-22 06:42:06 [32mINFO[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-05-22 06:42:06 [32mINFO[m i.a.i.d.m.MeiliSearchDestination(main):181 - starting destination: class io.airbyte.integrations.destination.meilisearch.MeiliSearchDestination
2022-05-22 06:42:06 [32mINFO[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-05-22 06:42:06 [32mINFO[m i.a.i.b.IntegrationCliParser(parseOptions):118 - integration args: {check=null, config=source_config.json}
2022-05-22 06:42:06 [32mINFO[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-05-22 06:42:06 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):105 - Running integration: io.airbyte.integrations.destination.meilisearch.MeiliSearchDestination
2022-05-22 06:42:06 [32mINFO[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-05-22 06:42:06 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):106 - Command: CHECK
2022-05-22 06:42:06 [32mINFO[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-05-22 06:42:06 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):107 - Integration config: IntegrationConfig{command=CHECK, configPath='source_config.json', catalogPath='null', statePath='null'}
2022-05-22 06:42:07 [32mINFO[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-05-22 06:42:07 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2022-05-22 06:42:07 [32mINFO[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-05-22 06:42:07 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2022-05-22 06:42:07 [32mINFO[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-05-22 06:42:07 [32mINFO[m i.a.i.d.m.MeiliSearchDestination(check):76 - config in check {"host":"http://10.0.70.110:7700","api_key":"*******"}
2022-05-22 06:42:07 [32mINFO[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-05-22 06:42:07 [1;31mERROR[m i.a.i.d.m.MeiliSearchDestination(check):85 - Check connection failed.
2022-05-22 06:42:07 [32mINFO[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - com.meilisearch.sdk.exceptions.MeiliSearchApiException: The Authorization header is missing. It must use the bearer authorization method.
2022-05-22 06:42:07 [32mINFO[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at com.meilisearch.sdk.MeiliSearchHttpRequest.post(MeiliSearchHttpRequest.java:90) ~[meilisearch-java-0.6.0.jar:?]
2022-05-22 06:42:07 [32mINFO[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at com.meilisearch.sdk.Documents.addDocuments(Documents.java:112) ~[meilisearch-java-0.6.0.jar:?]
2022-05-22 06:42:07 [32mINFO[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at com.meilisearch.sdk.Index.addDocuments(Index.java:114) ~[meilisearch-java-0.6.0.jar:?]
2022-05-22 06:42:07 [32mINFO[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.destination.meilisearch.MeiliSearchDestination.check(MeiliSearchDestination.java:80) [io.airbyte.airbyte-integrations.connectors-destination-meilisearch-0.35.27-alpha.jar:?]
2022-05-22 06:42:07 [32mINFO[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:122) [io.airbyte.airbyte-integrations.bases-base-java-0.35.27-alpha.jar:?]
2022-05-22 06:42:07 [32mINFO[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:89) [io.airbyte.airbyte-integrations.bases-base-java-0.35.27-alpha.jar:?]
2022-05-22 06:42:07 [32mINFO[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.destination.meilisearch.MeiliSearchDestination.main(MeiliSearchDestination.java:182) [io.airbyte.airbyte-integrations.connectors-destination-meilisearch-0.35.27-alpha.jar:?]
2022-05-22 06:42:08 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):134 - Stopping cancellation check scheduling...
```

**Comment by cope** [comment]
Same here

**Comment by thiagola92** [comment]
Same here.
![image](https://user-images.githubusercontent.com/9352894/173031382-8219b5d5-6be9-48ca-a525-01e627c991f2.png)

It doesn't seen to be sending the API key in the request. How the request should be doing:  
```
curl -X POST 'http://127.0.0.1:7700/indexes/example/search' -H 'Authorization: Bearer API_KEY' -H 'Content-Type: application/json' -d '{"q": ""}'
```

If you miss the `-H 'Authorization: Bearer API_KEY'` you will get the response:  
```json
{
  "message":"The Authorization header is missing. It must use the bearer authorization method.",
  "code":"missing_authorization_header",
  "type":"auth",
  "link":"https://docs.meilisearch.com/errors#missing_authorization_header"
}
```

**Comment by thiagola92** [comment]
Meilisearch changed the authentication header in version [0.25.0](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.25.0)  
> The `X-MEILI-API-KEY` header is replaced by the `Authorization: Bearer <apiKey>` header.  

Meilisearch-java fixed this in version [0.7.0](https://github.com/meilisearch/meilisearch-java/releases/tag/v0.7.0)  
> MeiliSearch v0.25.0 use `Authorization` header instead of `X-Meili-API-Key`  

Airbyte is using Meilisearch-java [0.6.0](https://github.com/airbytehq/airbyte/blob/20bd923c63405e6754c822dccbee57da0cef17ed/airbyte-integrations/connectors/destination-meilisearch/build.gradle#L18)

**Comment by tgensol** [comment]
Any update on this one ?

**Comment by longfellowone** [comment]
Also receiving this error when setting up on airbyte cloud

**Comment by CaroFG** [comment]
Hello! I'd like to update the connector to work with the latest Meilisearch version! As specified in the [documentation](https://docs.airbyte.com/contributing-to-airbyte/), I'm going to assign the issue to myself

**Comment by masoud-me** [comment]
I have same issue on :
meilisearch-http 0.28.1

**Comment by cirdes** [comment]
same issue here too! Any updates?

**Comment by CaroFG** [comment]
The meilisearch connector is out of date, it's still using an old [meilisearch-java](https://github.com/meilisearch/meilisearch-java/) version, only compatible with meilisearch v0.24.
I am waiting for the new meilisearch-java version to be released —the current one is just compatible with Meilisearch v0.27.0, which is not [the latest](https://github.com/meilisearch/meilisearch)—  to make a PR to update the connector, but it's taking longer than expected...

**Comment by cirdes** [comment]
@CaroFG, I have open an issue on https://github.com/airbytehq/connector-contest/issues/105 to work on this but feel free to claim it.

Seems that [meilisearch-java](https://github.com/meilisearch/meilisearch-java/releases) it not getting as much update as [Rust](https://github.com/meilisearch/meilisearch-rust/releases) or [Python](https://github.com/meilisearch/meilisearch-python/releases). Maybe change language could be a way too.

**Comment by CaroFG** [comment]
Hey @cirdes! Thank you for taking the time to work on this!

**Comment by marcosmarxm** [comment]
Closing because MeiliSearch now uses Python backend #18036
