### ISSUE TITLE
Kube acceptance tests transiently fail with `java.io.IOException: HTTP/1.1 header parser received no bytes`

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#13156]
## What

Platform kube acceptance tests are repeatedly failing with the following error: ([link to CI logs where this occurred](https://github.com/airbytehq/airbyte/runs/6581214298?check_suite_focus=true#step:11:49882))

```
AcceptanceTests > testBackpressure() > io.airbyte.test.acceptance.AcceptanceTests.testBackpressure()[1] FAILED
    io.airbyte.api.client.invoker.ApiException: java.io.IOException: HTTP/1.1 header parser received no bytes
        at app//io.airbyte.api.client.DestinationApi.deleteDestinationWithHttpInfo(DestinationApi.java:414)
        at app//io.airbyte.api.client.DestinationApi.deleteDestination(DestinationApi.java:386)
        at app//io.airbyte.test.acceptance.AcceptanceTests.deleteDestination(AcceptanceTests.java:1760)
        at app//io.airbyte.test.acceptance.AcceptanceTests.tearDown(AcceptanceTests.java:327)

        Caused by:
        java.io.IOException: HTTP/1.1 header parser received no bytes
            at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:586)
            at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)
            at io.airbyte.api.client.DestinationApi.deleteDestinationWithHttpInfo(DestinationApi.java:399)
            ... 3 more

            Caused by:
            java.io.IOException: HTTP/1.1 header parser received no bytes
                at java.net.http/jdk.internal.net.http.common.Utils.wrapWithExtraDetail(Utils.java:348)
                at java.net.http/jdk.internal.net.http.Http1Response$HeadersReader.onReadError(Http1Response.java:675)
                at java.net.http/jdk.internal.net.http.Http1AsyncReceiver.checkForErrors(Http1AsyncReceiver.java:302)
                at java.net.http/jdk.internal.net.http.Http1AsyncReceiver.flush(Http1AsyncReceiver.java:268)
                at java.net.http/jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:205)
                at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
                at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:230)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
                at java.base/java.lang.Thread.run(Thread.java:833)

                Caused by:
                java.io.EOFException: EOF reached while reading
                    at java.net.http/jdk.internal.net.http.Http1AsyncReceiver$Http1TubeSubscriber.onComplete(Http1AsyncReceiver.java:596)
                    at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadSubscription.signalCompletion(SocketTube.java:640)
                    at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(SocketTube.java:845)
                    at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowTask.run(SocketTube.java:181)
                    at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:230)
                    at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:303)
                    at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:256)
                    at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.signalReadable(SocketTube.java:774)
                    at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent.signalEvent(SocketTube.java:957)
                    at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowEvent.handle(SocketTube.java:253)
                    at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(HttpClientImpl.java:979)
                    at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(HttpClientImpl.java:934)
                    at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
                    at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:934)
```

This issue is "transient" since there are still occasionally successful builds, but this error seems to happen in almost half of all platform CI builds.

## How
The fix for this is unclear. 

I found a [StackOverflow post](https://stackoverflow.com/questions/64353620/caused-by-java-io-ioexception-http-1-1-header-parser-received-no-bytes) that seemed related, and I tried implementing the suggested fix in [this PR](https://github.com/airbytehq/airbyte/pull/13064/files), but the exception still happened.

**Comment by cpdeethree** [comment]
We don't use kube acceptance tests anymore, so I'm closing this
