### ISSUE TITLE
After updating airbyte - connections list not returned by backend

### ISSUE THREAD

**Issue by knugusbayevps** [airbytehq/airbyte#13406]
## Environment
- **Airbyte version**:  0.38.3-alpha
- **Deployment**: Docker
- **Step where error happened**: Upgrade Airbyte

## Current Behavior
*Tell us what happens.*
I updated version of airbyte from 0.35.68-alpha --> 0.38.3-alpha, after connections page not rendered

## Expected Behavior
*Tell us what should happen.*
All connections list returned to WEB successfully.

## Logs - airbyte-server logs
```

2022-06-02 05:57:10 ERROR i.a.s.e.UncaughtExceptionMapper(toResponse):22 - Uncaught exception
java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.isObject()" because "jsonSchemaNode" is null
	at io.airbyte.commons.json.JsonSchemas.traverseJsonSchemaInternal(JsonSchemas.java:152) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
	at io.airbyte.commons.json.JsonSchemas.traverseJsonSchemaInternal(JsonSchemas.java:168) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
	at io.airbyte.commons.json.JsonSchemas.traverseJsonSchemaInternal(JsonSchemas.java:177) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
	at io.airbyte.commons.json.JsonSchemas.traverseJsonSchema(JsonSchemas.java:99) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
	at io.airbyte.commons.json.JsonSchemas.traverseJsonSchemaWithCollector(JsonSchemas.java:116) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
	at io.airbyte.commons.json.JsonSchemas.collectJsonPathsThatMeetCondition(JsonSchemas.java:129) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
	at io.airbyte.config.persistence.split_secrets.JsonSecretsProcessor.maskAllSecrets(JsonSecretsProcessor.java:75) ~[io.airbyte.airbyte-config-persistence-0.38.3-alpha.jar:?]
	at io.airbyte.config.persistence.split_secrets.JsonSecretsProcessor.prepareSecretsForOutput(JsonSecretsProcessor.java:60) ~[io.airbyte.airbyte-config-persistence-0.38.3-alpha.jar:?]
	at io.airbyte.server.handlers.SourceHandler.buildSourceRead(SourceHandler.java:256) ~[io.airbyte-airbyte-server-0.38.3-alpha.jar:?]
	at io.airbyte.server.handlers.SourceHandler.buildSourceRead(SourceHandler.java:247) ~[io.airbyte-airbyte-server-0.38.3-alpha.jar:?]
	at io.airbyte.server.handlers.SourceHandler.getSource(SourceHandler.java:130) ~[io.airbyte-airbyte-server-0.38.3-alpha.jar:?]
	at io.airbyte.server.handlers.WebBackendConnectionsHandler.getSourceRead(WebBackendConnectionsHandler.java:130) ~[io.airbyte-airbyte-server-0.38.3-alpha.jar:?]
	at io.airbyte.server.handlers.WebBackendConnectionsHandler.buildWebBackendConnectionRead(WebBackendConnectionsHandler.java:115) ~[io.airbyte-airbyte-server-0.38.3-alpha.jar:?]
	at io.airbyte.server.handlers.WebBackendConnectionsHandler.webBackendListConnectionsForWorkspace(WebBackendConnectionsHandler.java:98) ~[io.airbyte-airbyte-server-0.38.3-alpha.jar:?]
	at io.airbyte.server.apis.ConfigurationApi.lambda$webBackendListConnectionsForWorkspace$85(ConfigurationApi.java:808) ~[io.airbyte-airbyte-server-0.38.3-alpha.jar:?]
	at io.airbyte.server.apis.ConfigurationApi.execute(ConfigurationApi.java:874) ~[io.airbyte-airbyte-server-0.38.3-alpha.jar:?]
	at io.airbyte.server.apis.ConfigurationApi.webBackendListConnectionsForWorkspace(ConfigurationApi.java:808) ~[io.airbyte-airbyte-server-0.38.3-alpha.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394) ~[jersey-container-servlet-core-2.31.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) ~[jersey-container-servlet-core-2.31.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366) ~[jersey-container-servlet-core-2.31.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319) ~[jersey-container-servlet-core-2.31.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) ~[jersey-container-servlet-core-2.31.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:569) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1377) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:507) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.Server.handle(Server.java:501) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at java.lang.Thread.run(Thread.java:833) [?:?]
2022-06-02 05:57:10 ERROR i.a.s.RequestLogger(filter):110 - REQ 172.19.0.4 POST 500 /api/v1/web_backend/connections/list - {"workspaceId":"XXXXXXXXXXXXXXXXX"}

```
## Steps to Reproduce
1. Start 0.35.68-alpha version of airbyte
2. Create 1 connection
3. Update airbyte's version to 0.38.3-alpha
4. Open airbyte - connections page

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by alafanechere** [comment]
Hey @knugusbayevps , please upgrade Airbyte to its latest version. If the error is still happening, feel free to reach our community support team on our [forum](https://discuss.airbyte.io/).
