### ISSUE TITLE
Blocking error on documentation not found on custom connectors

### ISSUE THREAD

**Issue by AM-I-Human** [airbytehq/airbyte#13487]
## Environment
- **Airbyte version**: 0.39.7-alpha
- **OS Version / Instance**: Windows 11, and a Unix Server
- **Deployment**: Docker
- **Source Connector and version**: custom
- **Destination Connector and version**: custom
- **Step where error happened**: I already added time ago the connector. Now when I add a  custom source or destination, I have no 
-  explicit error, but cant procede. I press the button and nothing happen
## Current Behaviour

When Adding a source or destination that does not have a documentation on web I can't procede.
I  see this exception on the browser dev tools:
```
GET https://gitlab.lunalabs.it/data/airbyte_connectors.md net::ERR_FAILED 302
TypeError: Failed to fetch
    at Documentation.ts:2:26
    at c (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at r (asyncToGenerator.js:3:20)
    at u (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21:12
    at Documentation.ts:1:32
```
Because the link bring to the repo page and not to a markdown file.

## Expected Behaviour
Get the hidden exception, but I can still continue and add the source connector

## Logs
```
GET https://gitlab.lunalabs.it/data/airbyte_connectors.md net::ERR_FAILED 302
TypeError: Failed to fetch
    at Documentation.ts:2:26
    at c (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at r (asyncToGenerator.js:3:20)
    at u (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21:12
    at Documentation.ts:1:32

```

## Steps to Reproduce
1.add a custom connector with an url that points to any web page 
2.set up the connector
3. You can't continue

## Are you willing to submit a PR?
No, this repository is too complex for me.

**Comment by AM-I-Human** [comment]
Probable that was an error because a  required field with a default value require that the default value needs to be edited. 
The error was not shown on UI because there was no description on the field.

I close this issue because it is not easy to reproduce and can be caused by the error above
