### ISSUE TITLE
Not able to upgrade Flyway version from the default one

### ISSUE THREAD

**Issue by taragurung** [airbytehq/airbyte#13848]
## Environment
- **Airbyte version**:  example is 0.31.11-alpha
- **OS Version / Instance**: Ubuntu 18.04,
- **Deployment**: Kubernetes deploy 
- **Step where error happened**: Deploy / Upgrade Airbyte

## Current Behavior
*I am trying to upgrade the Airbyte from 0.31.11-alpha to 0.39.0-alpha and the airbyte-server stops because of  database to fulfill minimum flyway migration version*

## Expected Behavior
*Airbyte server running succesfully and the airbyte upgraded as well*

## Logs

it says the current database migration version is bellow the desire version
`2022-06-16 14:38:20 INFO i.a.d.i.MinimumFlywayMigrationVersionCheck(assertMigrations):76 - Current database migration version 0.30.22.001
2022-06-16 14:38:20 INFO i.a.d.i.MinimumFlywayMigrationVersionCheck(assertMigrations):77 - Minimum Flyway version required 0.35.15.001`

**Error logs**
`2022-06-16 14:31:26 ERROR i.a.s.ServerApp(main):314 - Server failed
java.lang.RuntimeException: Timeout while waiting for database to fulfill minimum flyway migration version..
	at io.airbyte.db.instance.MinimumFlywayMigrationVersionCheck.assertMigrations(MinimumFlywayMigrationVersionCheck.java:81) ~[io.airbyte.airbyte-db-lib-0.39.0-alpha.jar:?]
	at io.airbyte.server.ServerApp.assertDatabasesReady(ServerApp.java:150) ~[io.airbyte-airbyte-server-0.39.0-alpha.jar:?]
	at io.airbyte.server.ServerApp.getServer(ServerApp.java:183) ~[io.airbyte-airbyte-server-0.39.0-alpha.jar:?]
	at io.airbyte.server.ServerApp.main(ServerApp.java:310) [io.airbyte-airbyte-server-0.39.0-alpha.jar:?]`

## Actions taken
I added the following two env variables to the Config map the Airbyte-Server uses. but still the pod seem to use the default version, even after setting this up and restarting the pods
`  CONFIGS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION: 0.35.15.001`
&
` JOBS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION: 0.35.15.001`

**Comment by sajarin** [comment]
Hey @taragurung thanks for the issue. If you want to upgrade from 0.31.11-alpha to 0.39.0-alpha, you actually have to upgrade to version v0.32.0-alpha-patch-1 and then upgrade to 0.39.0-alpha.

You can view the reason and steps behind how to do this in our docs: https://docs.airbyte.com/operator-guides/upgrading-airbyte#mandatory-intermediate-upgrade

If you still run into issues after following these steps, let us know!
