### ISSUE TITLE
JDBC sources: Improve error message when an invalid cursor column is selected

### ISSUE THREAD

**Issue by bleonard** [airbytehq/airbyte#13912]
When a non-sortable column is used as a cursor, we currently produce an error message that isn't super useful (`<column type> can't be used as a cursor`). Ideally, this message should include the table and column names, to assist users in tracking down which stream is causing the problem.

---

```
"java.lang.IllegalArgumentException: OTHER is not supported.
 io.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source process exited with non-zero exit code 1"
```

Something interesting on this cloud account.
More details: https://docs.google.com/spreadsheets/d/1ja8deCtFHtFVP3QrWELsMpVCMfPB1kz0QfLG1szns1I/edit#gid=408762974

**Comment by grishick** [comment]
It appears that the user was able to set up an incremental sync with an unsupported field type.

**Comment by edgao** [comment]
after https://github.com/airbytehq/airbyte/pull/14714 this will be reported with a slightly more informative error message (`OTHER cannot be used as a cursor`).

Hopefully sentry is able to recognize that as the same stacktrace, but leaving a breadcrumb comment in case it doesn't.

**Comment by bleonard** [comment]
> after #14714 this will be reported with a slightly more informative error message (`OTHER cannot be used as a cursor`).
> 
> Hopefully sentry is able to recognize that as the same stacktrace, but leaving a breadcrumb comment in case it doesn't.

It would be slightly nicer if `OTHER` was better explained. Is it possible to do "first_name column can not be used as a cursor. Please use integers or timestamps" or something that effect?

**Comment by edgao** [comment]
yeah, that's fair. I updated the issue title and description.

It requires a bit of refactoring to get the table+column name down to where the exception is thrown (or maybe to catch the exception where the those names are known?) so going to leave this be for now.

**Comment by bleonard** [comment]
> yeah, that's fair. I updated the issue title and description.
> 
> It requires a bit of refactoring to get the table+column name down to where the exception is thrown (or maybe to catch the exception where the those names are known?) so going to leave this be for now.

Agreed, just noting a future ideal. Thanks.

**Comment by grishick** [comment]
This started happening again two days ago for another customer

**Comment by grishick** [comment]
```
2022-08-03 08:33:00 source > 	at io.airbyte.integrations.base.IntegrationRunner.lambda$produceMessages$0(IntegrationRunner.java:157) ~[io.airbyte.airbyte-integrations.bases-base-java-0.39.41-alpha.jar:?]
2022-08-03 08:33:00 source > 	at io.airbyte.integrations.base.IntegrationRunner.watchForOrphanThreads(IntegrationRunner.java:207) ~[io.airbyte.airbyte-integrations.bases-base-java-0.39.41-alpha.jar:?]
2022-08-03 08:33:00 source > 	at io.airbyte.integrations.base.IntegrationRunner.produceMessages(IntegrationRunner.java:156) ~[io.airbyte.airbyte-integrations.bases-base-java-0.39.41-alpha.jar:?]
2022-08-03 08:33:00 source > 	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:137) ~[io.airbyte.airbyte-integrations.bases-base-java-0.39.41-alpha.jar:?]
2022-08-03 08:33:00 source > 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:97) ~[io.airbyte.airbyte-integrations.bases-base-java-0.39.41-alpha.jar:?]
2022-08-03 08:33:00 source > 	at io.airbyte.integrations.source.postgres.PostgresSourceStrictEncrypt.main(PostgresSourceStrictEncrypt.java:45) ~[io.airbyte.airbyte-integrations.connectors-source-postgres-strict-encrypt-0.39.41-alpha.jar:?]
```

**Comment by grishick** [comment]
Related alpha-beta issue: https://github.com/airbytehq/alpha-beta-issues/issues/164

**Comment by tuliren** [comment]
There are already two PRs related to this issue:
https://github.com/airbytehq/airbyte/pull/14356
https://github.com/airbytehq/airbyte/pull/15317

**Comment by subodh1810** [comment]
My PR has been approved but the build is failing, the remaining thing is to fix the build and get it merged

**Comment by grishick** [comment]
@subodh1810 builds should be OK now
