### ISSUE TITLE
destination-bigquery: GCS Staging `AmazonS3Exception: Forbidden`

### ISSUE THREAD

**Issue by sankaranvignesh** [airbytehq/airbyte#14135]
## Environment
- **Airbyte version**:  0.39.7-alpha
- **OS Version / Instance**: Debian GNU/Linux 10 (buster), GCP n2-standard
- **Deployment**: example are Docker container in a VM
- **Source Connector and version**: Zendesk Support connector BETA
- **Destination Connector and version**: Bigquery
- **Step where error happened**: Connection read from Zendesk and write into GCS

## Current Behavior
Connection fails throwing AmazonS3Exception for GCS staging. I am trying to load data from Zendesk support into Bigquery using GCS staging.

## Expected Behavior
I should be able to load data from Zendesk support into Bigquery using GCS staging successfully.

## Logs
```
2022-06-25 17:15:31 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):108 - Docker volume job log path: /tmp/workspace/79/0/logs.log
2022-06-25 17:15:31 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):113 - Executing worker wrapper. Airbyte version: 0.39.7-alpha
2022-06-25 17:15:31 [32mINFO[m i.a.c.i.LineGobbler(voidCall):82 - Checking if airbyte/destination-bigquery:1.1.6 exists...
2022-06-25 17:15:31 [32mINFO[m i.a.c.i.LineGobbler(voidCall):82 - airbyte/destination-bigquery:1.1.6 was found locally.
2022-06-25 17:15:31 [32mINFO[m i.a.w.p.DockerProcessFactory(create):108 - Creating docker job ID: 79
2022-06-25 17:15:31 [32mINFO[m i.a.w.p.DockerProcessFactory(create):163 - Preparing command: docker run --rm --init -i -w /data/79/0 --log-driver none --name destination-bigquery-check-79-0-mazhv --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e WORKER_JOB_ATTEMPT=0 -e WORKER_CONNECTOR_IMAGE=airbyte/destination-bigquery:1.1.6 -e AIRBYTE_ROLE= -e WORKER_ENVIRONMENT=DOCKER -e AIRBYTE_VERSION=0.39.7-alpha -e WORKER_JOB_ID=79 airbyte/destination-bigquery:1.1.6 check --config source_config.json
2022-06-25 17:15:31 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):82 - SLF4J: Class path contains multiple SLF4J bindings.
2022-06-25 17:15:31 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):82 - SLF4J: Found binding in [jar:file:/airbyte/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2022-06-25 17:15:31 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):82 - SLF4J: Found binding in [jar:file:/airbyte/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2022-06-25 17:15:31 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):82 - SLF4J: Found binding in [jar:file:/airbyte/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2022-06-25 17:15:31 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):82 - SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
2022-06-25 17:15:31 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):82 - SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
2022-06-25 17:15:32 [32mINFO[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-06-25 17:15:32 [32mINFO[m i.a.i.b.IntegrationCliParser(parseOptions):118 - integration args: {check=null, config=source_config.json}
2022-06-25 17:15:32 [32mINFO[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-06-25 17:15:32 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):123 - Running integration: io.airbyte.integrations.destination.bigquery.BigQueryDestination
2022-06-25 17:15:32 [32mINFO[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-06-25 17:15:32 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):124 - Command: CHECK
2022-06-25 17:15:32 [32mINFO[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-06-25 17:15:32 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):125 - Integration config: IntegrationConfig{command=CHECK, configPath='source_config.json', catalogPath='null', statePath='null'}
2022-06-25 17:15:32 [32mINFO[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-06-25 17:15:32 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword examples - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2022-06-25 17:15:32 [32mINFO[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-06-25 17:15:32 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2022-06-25 17:15:32 [32mINFO[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-06-25 17:15:32 [32mINFO[m i.a.i.d.b.BigQueryUtils(getLoadingMethod):303 - Selected loading method is set to: GCS
2022-06-25 17:15:35 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):134 - Stopping cancellation check scheduling...
2022-06-25 17:15:35 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):108 - Docker volume job log path: /tmp/workspace/79/0/logs.log
2022-06-25 17:15:35 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):113 - Executing worker wrapper. Airbyte version: 0.39.7-alpha
2022-06-25 17:15:35 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):115 - start sync worker. job id: 79 attempt id: 0
2022-06-25 17:15:35 [1;31mERROR[m i.a.w.i.NamespacingMapper(lambda$mapCatalog$0):50 - Namespace Format cannot be blank for Stream brands. Falling back to default namespace from destination settings
2022-06-25 17:15:35 [1;31mERROR[m i.a.w.i.NamespacingMapper(lambda$mapCatalog$0):50 - Namespace Format cannot be blank for Stream custom_roles. Falling back to default namespace from destination settings
2022-06-25 17:15:35 [1;31mERROR[m i.a.w.i.NamespacingMapper(lambda$mapCatalog$0):50 - Namespace Format cannot be blank for Stream group_memberships. Falling back to default namespace from destination settings
2022-06-25 17:15:35 [1;31mERROR[m i.a.w.i.NamespacingMapper(lambda$mapCatalog$0):50 - Namespace Format cannot be blank for Stream groups. Falling back to default namespace from destination settings
2022-06-25 17:15:35 [1;31mERROR[m i.a.w.i.NamespacingMapper(lambda$mapCatalog$0):50 - Namespace Format cannot be blank for Stream macros. Falling back to default namespace from destination settings
2022-06-25 17:15:35 [1;31mERROR[m i.a.w.i.NamespacingMapper(lambda$mapCatalog$0):50 - Namespace Format cannot be blank for Stream organizations. Falling back to default namespace from destination settings
2022-06-25 17:15:35 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):127 - configured sync modes: {null.brands=full_refresh - overwrite, null.groups=full_refresh - overwrite, null.organizations=full_refresh - overwrite, null.custom_roles=full_refresh - overwrite, null.macros=full_refresh - overwrite, null.group_memberships=full_refresh - overwrite}
2022-06-25 17:15:35 [32mINFO[m i.a.w.i.DefaultAirbyteDestination(start):69 - Running destination...
2022-06-25 17:15:35 [32mINFO[m i.a.c.i.LineGobbler(voidCall):82 - Checking if airbyte/destination-bigquery:1.1.6 exists...
2022-06-25 17:15:35 [32mINFO[m i.a.c.i.LineGobbler(voidCall):82 - airbyte/destination-bigquery:1.1.6 was found locally.
2022-06-25 17:15:35 [32mINFO[m i.a.w.p.DockerProcessFactory(create):108 - Creating docker job ID: 79
2022-06-25 17:15:35 [32mINFO[m i.a.w.p.DockerProcessFactory(create):163 - Preparing command: docker run --rm --init -i -w /data/79/0 --log-driver none --name destination-bigquery-write-79-0-lbxwr --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e WORKER_JOB_ATTEMPT=0 -e WORKER_CONNECTOR_IMAGE=airbyte/destination-bigquery:1.1.6 -e AIRBYTE_ROLE= -e WORKER_ENVIRONMENT=DOCKER -e AIRBYTE_VERSION=0.39.7-alpha -e WORKER_JOB_ID=79 airbyte/destination-bigquery:1.1.6 write --config destination_config.json --catalog destination_catalog.json
2022-06-25 17:15:35 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$getDestinationOutputRunnable$7):395 - Destination output thread started.
2022-06-25 17:15:35 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):169 - Waiting for source and destination threads to complete.
2022-06-25 17:15:35 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$getReplicationRunnable$6):298 - Replication thread started.
2022-06-25 17:15:35 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$getReplicationRunnable$6):355 - Total records read: 1 (0 bytes)
2022-06-25 17:15:35 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):174 - One of source or destination thread complete. Waiting on the other.
2022-06-25 17:15:35 [43mdestination[0m > SLF4J: Class path contains multiple SLF4J bindings.
2022-06-25 17:15:35 [43mdestination[0m > SLF4J: Found binding in [jar:file:/airbyte/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2022-06-25 17:15:35 [43mdestination[0m > SLF4J: Found binding in [jar:file:/airbyte/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2022-06-25 17:15:35 [43mdestination[0m > SLF4J: Found binding in [jar:file:/airbyte/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2022-06-25 17:15:35 [43mdestination[0m > SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
2022-06-25 17:15:36 [43mdestination[0m > SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
2022-06-25 17:15:36 [43mdestination[0m > 2022-06-25 17:15:36 [32mINFO[m i.a.i.b.IntegrationCliParser(parseOptions):118 - integration args: {catalog=destination_catalog.json, write=null, config=destination_config.json}
2022-06-25 17:15:36 [43mdestination[0m > 2022-06-25 17:15:36 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):123 - Running integration: io.airbyte.integrations.destination.bigquery.BigQueryDestination
2022-06-25 17:15:36 [43mdestination[0m > 2022-06-25 17:15:36 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):124 - Command: WRITE
2022-06-25 17:15:36 [43mdestination[0m > 2022-06-25 17:15:36 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):125 - Integration config: IntegrationConfig{command=WRITE, configPath='destination_config.json', catalogPath='destination_catalog.json', statePath='null'}
2022-06-25 17:15:36 [43mdestination[0m > 2022-06-25 17:15:36 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword examples - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2022-06-25 17:15:36 [43mdestination[0m > 2022-06-25 17:15:36 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2022-06-25 17:15:36 [43mdestination[0m > 2022-06-25 17:15:36 [32mINFO[m i.a.i.d.b.BigQueryUtils(getLoadingMethod):303 - Selected loading method is set to: GCS
2022-06-25 17:15:37 [43mdestination[0m > 2022-06-25 17:15:37 [32mINFO[m i.a.i.d.s.S3FormatConfigs(getS3FormatConfig):22 - S3 format config: {"format_type":"AVRO","flattening":"No flattening","part_size_mb":"5"}
2022-06-25 17:15:37 [43mdestination[0m > 2022-06-25 17:15:37 [32mINFO[m i.a.i.d.b.BigQueryUtils(isKeepFilesInGcs):319 - All tmp files will be removed from GCS when replication is finished
2022-06-25 17:15:37 [43mdestination[0m > 2022-06-25 17:15:37 [32mINFO[m i.a.i.d.b.BigQueryDestination(getGcsRecordConsumer):286 - Creating BigQuery staging message consumer with staging ID f9eb3238-2d3b-4cef-b33d-c0bdec4ca596 at 2022-06-25T17:15:37.057Z
2022-06-25 17:15:37 [43mdestination[0m > 2022-06-25 17:15:37 [32mINFO[m i.a.i.d.b.BigQueryStagingConsumerFactory(lambda$createWriteConfigs$1):86 - BigQuery write config: BigQueryWriteConfig[streamName=brands, namespace=null, datasetId=zendesk, datasetLocation=australia-southeast1, tmpTableId=GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=zendesk, tableId=_airbyte_tmp_kuy_brands}}, targetTableId=GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=zendesk, tableId=_airbyte_raw_brands}}, tableSchema=Schema{fields=[Field{name=_airbyte_ab_id, type=STRING, mode=null, description=null, policyTags=null}, Field{name=_airbyte_emitted_at, type=TIMESTAMP, mode=null, description=null, policyTags=null}, Field{name=_airbyte_data, type=STRING, mode=null, description=null, policyTags=null}]}, syncMode=overwrite, stagedFiles=[]]
2022-06-25 17:15:37 [43mdestination[0m > 2022-06-25 17:15:37 [32mINFO[m i.a.i.d.b.BigQueryStagingConsumerFactory(lambda$createWriteConfigs$1):86 - BigQuery write config: BigQueryWriteConfig[streamName=custom_roles, namespace=null, datasetId=zendesk, datasetLocation=australia-southeast1, tmpTableId=GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=zendesk, tableId=_airbyte_tmp_zbu_custom_roles}}, targetTableId=GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=zendesk, tableId=_airbyte_raw_custom_roles}}, tableSchema=Schema{fields=[Field{name=_airbyte_ab_id, type=STRING, mode=null, description=null, policyTags=null}, Field{name=_airbyte_emitted_at, type=TIMESTAMP, mode=null, description=null, policyTags=null}, Field{name=_airbyte_data, type=STRING, mode=null, description=null, policyTags=null}]}, syncMode=overwrite, stagedFiles=[]]
2022-06-25 17:15:37 [43mdestination[0m > 2022-06-25 17:15:37 [32mINFO[m i.a.i.d.b.BigQueryStagingConsumerFactory(lambda$createWriteConfigs$1):86 - BigQuery write config: BigQueryWriteConfig[streamName=group_memberships, namespace=null, datasetId=zendesk, datasetLocation=australia-southeast1, tmpTableId=GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=zendesk, tableId=_airbyte_tmp_nqq_group_memberships}}, targetTableId=GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=zendesk, tableId=_airbyte_raw_group_memberships}}, tableSchema=Schema{fields=[Field{name=_airbyte_ab_id, type=STRING, mode=null, description=null, policyTags=null}, Field{name=_airbyte_emitted_at, type=TIMESTAMP, mode=null, description=null, policyTags=null}, Field{name=_airbyte_data, type=STRING, mode=null, description=null, policyTags=null}]}, syncMode=overwrite, stagedFiles=[]]
2022-06-25 17:15:37 [43mdestination[0m > 2022-06-25 17:15:37 [32mINFO[m i.a.i.d.b.BigQueryStagingConsumerFactory(lambda$createWriteConfigs$1):86 - BigQuery write config: BigQueryWriteConfig[streamName=groups, namespace=null, datasetId=zendesk, datasetLocation=australia-southeast1, tmpTableId=GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=zendesk, tableId=_airbyte_tmp_xpe_groups}}, targetTableId=GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=zendesk, tableId=_airbyte_raw_groups}}, tableSchema=Schema{fields=[Field{name=_airbyte_ab_id, type=STRING, mode=null, description=null, policyTags=null}, Field{name=_airbyte_emitted_at, type=TIMESTAMP, mode=null, description=null, policyTags=null}, Field{name=_airbyte_data, type=STRING, mode=null, description=null, policyTags=null}]}, syncMode=overwrite, stagedFiles=[]]
2022-06-25 17:15:37 [43mdestination[0m > 2022-06-25 17:15:37 [32mINFO[m i.a.i.d.b.BigQueryStagingConsumerFactory(lambda$createWriteConfigs$1):86 - BigQuery write config: BigQueryWriteConfig[streamName=macros, namespace=null, datasetId=zendesk, datasetLocation=australia-southeast1, tmpTableId=GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=zendesk, tableId=_airbyte_tmp_bwy_macros}}, targetTableId=GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=zendesk, tableId=_airbyte_raw_macros}}, tableSchema=Schema{fields=[Field{name=_airbyte_ab_id, type=STRING, mode=null, description=null, policyTags=null}, Field{name=_airbyte_emitted_at, type=TIMESTAMP, mode=null, description=null, policyTags=null}, Field{name=_airbyte_data, type=STRING, mode=null, description=null, policyTags=null}]}, syncMode=overwrite, stagedFiles=[]]
2022-06-25 17:15:37 [43mdestination[0m > 2022-06-25 17:15:37 [32mINFO[m i.a.i.d.b.BigQueryStagingConsumerFactory(lambda$createWriteConfigs$1):86 - BigQuery write config: BigQueryWriteConfig[streamName=organizations, namespace=null, datasetId=zendesk, datasetLocation=australia-southeast1, tmpTableId=GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=zendesk, tableId=_airbyte_tmp_fma_organizations}}, targetTableId=GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=zendesk, tableId=_airbyte_raw_organizations}}, tableSchema=Schema{fields=[Field{name=_airbyte_ab_id, type=STRING, mode=null, description=null, policyTags=null}, Field{name=_airbyte_emitted_at, type=TIMESTAMP, mode=null, description=null, policyTags=null}, Field{name=_airbyte_data, type=STRING, mode=null, description=null, policyTags=null}]}, syncMode=overwrite, stagedFiles=[]]
2022-06-25 17:15:37 [43mdestination[0m > 2022-06-25 17:15:37 [32mINFO[m i.a.i.d.b.BufferedStreamConsumer(startTracked):116 - class io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer started.
2022-06-25 17:15:37 [43mdestination[0m > 2022-06-25 17:15:37 [32mINFO[m i.a.i.d.b.BigQueryStagingConsumerFactory(lambda$onStartFunction$3):98 - Preparing tmp tables in destination started for 6 streams
2022-06-25 17:15:37 [43mdestination[0m > 2022-06-25 17:15:37 [32mINFO[m i.a.i.d.b.BigQueryGcsOperations(createSchemaIfNotExists):86 - Creating dataset zendesk
2022-06-25 17:15:38 [43mdestination[0m > 2022-06-25 17:15:38 [32mINFO[m i.a.i.d.b.BigQueryGcsOperations(createTmpTableIfNotExists):94 - Creating tmp table GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=zendesk, tableId=_airbyte_tmp_kuy_brands}}
2022-06-25 17:15:39 [43mdestination[0m > 2022-06-25 17:15:39 [32mINFO[m i.a.i.d.b.BigQueryUtils(createPartitionedTable):131 - Partitioned table created successfully: GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=zendesk, tableId=_airbyte_tmp_kuy_brands}}
2022-06-25 17:15:39 [43mdestination[0m > 2022-06-25 17:15:39 [32mINFO[m i.a.i.d.b.BigQueryGcsOperations(createStageIfNotExists):101 - Creating staging path for stream brands (dataset zendesk): support/zendesk_brands/2022/06/25/17/f9eb3238-2d3b-4cef-b33d-c0bdec4ca596/
2022-06-25 17:15:40 [43mdestination[0m > 2022-06-25 17:15:40 [1;31mERROR[m i.a.i.b.FailureTrackingAirbyteMessageConsumer(start):39 - Exception while starting consumer
2022-06-25 17:15:40 [43mdestination[0m > com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: null; S3 Extended Request ID: null; Proxy: null)
2022-06-25 17:15:40 [43mdestination[0m > 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1819) ~[aws-java-sdk-core-1.12.14.jar:?]
2022-06-25 17:15:40 [43mdestination[0m > 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1403) ~[aws-java-sdk-core-1.12.14.jar:?]
2022-06-25 17:15:40 [43mdestination[0m > 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1372) ~[aws-java-sdk-core-1.12.14.jar:?]
2022-06-25 17:15:40 [43mdestination[0m > 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145) ~[aws-java-sdk-core-1.12.14.jar:?]
2022-06-25 17:15:40 [43mdestination[0m > 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802) ~[aws-java-sdk-core-1.12.14.jar:?]
2022-06-25 17:15:40 [43mdestination[0m > 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770) ~[aws-java-sdk-core-1.12.14.jar:?]
2022-06-25 17:15:40 [43mdestination[0m > 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744) ~[aws-java-sdk-core-1.12.14.jar:?]
2022-06-25 17:15:40 [43mdestination[0m > 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704) ~[aws-java-sdk-core-1.12.14.jar:?]
```

## Steps to Reproduce
1. Create a source with Zendesk support connector 
2. Set up Destination as Bigquery
3. Create a connection to load data from Zendesk support into Bigquery using GCS staging

## Are you willing to submit a PR?
I am looking in to the source code, but need some professional help.

**Comment by alafanechere** [comment]
Hi @sankaranvignesh,
GCS is compatible with S3 API. We are using the same S3 library for both S3 and GCS connectors to reuse the same logic.
Here the error is clearly a permission issue on your GCS service account. Could you make sure your service account has permission to:
* List bucket objects
* Read bucket objects
* Write bucket objects

As this is not a bug on Airbyte side do you mind opening a topic on our [forum](https://discuss.airbyte.io/) if you need further technical assistance from our team?
