### ISSUE TITLE
Failed to run integration tests for source db2 

### ISSUE THREAD

**Issue by suhomud** [airbytehq/airbyte#14144]
```
  2022-06-25 17:22:32 source > java.lang.IllegalStateException: Unexpected state blob
    2022-06-25 17:22:32 source > 	at io.airbyte.config.helpers.StateMessageHelper.getTypedState(StateMessageHelper.java:51) ~[io.airbyte.airbyte-config-config-models-0.39.25-alpha.jar:?]
    2022-06-25 17:22:32 source > 	at io.airbyte.integrations.source.relationaldb.AbstractDbSource.deserializeInitialState(AbstractDbSource.java:525) ~[io.airbyte.airbyte-integrations.connectors-source-relational-db-0.39.25-alpha.jar:?]
    2022-06-25 17:22:32 source > 	at io.airbyte.integrations.source.relationaldb.AbstractDbSource.read(AbstractDbSource.java:113) ~[io.airbyte.airbyte-integrations.connectors-source-relational-db-0.39.25-alpha.jar:?]
    2022-06-25 17:22:32 source > 	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:155) ~[io.airbyte.airbyte-integrations.bases-base-java-0.39.25-alpha.jar:?]
    2022-06-25 17:22:32 source > 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:107) ~[io.airbyte.airbyte-integrations.bases-base-java-0.39.25-alpha.jar:?]
    2022-06-25 17:22:32 source > 	at io.airbyte.integrations.source.db2.Db2Source.main(Db2Source.java:52) ~[io.airbyte.airbyte-integrations.connectors-source-db2-0.39.25-alpha.jar:?]

Db2SourceCertificateAcceptanceTest > testIncrementalSyncWithState() FAILED
    io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
```

**Comment by etsybaev** [comment]
Already fixed
![Selection_416.png](https://images.zenhubusercontent.com/627269f99b780c901a3d24e2/6088c122-b570-4d5b-b655-1e21906067a5)
