### ISSUE TITLE
Allow partial resets for GLOBAL states

### ISSUE THREAD

**Issue by alovew** [airbytehq/airbyte#14319]
Currently global states (CDC) do not support partial resets. Once they do, we should allow partial resets for GLOBAL states, just like we do for STREAM states. 

The change should be made in the `webBackendUpdateConnection` endpoint in the `WebBackendConnectionsHandler`. Right now we are not allowing partial resets for states that are LEGACY, NOT_SET, or GLOBAL. This should be updated to remove GLOBAL.

**Comment by jasonmaddernstudylink** [comment]
I assume that is why I'm seeing this error on the reset of an individual stream

- Airbyte 0.50.0 (latest)
- Running on Docker

Is there any interim fix (even a manual one I can perform) as I'd prefer not to have to reset everything


`2023-06-30 07:22:35 ERROR i.a.w.i.EmptyAirbyteSource(start):101 - The state a legacy one but we are trying to do a partial update, this is not supported.
2023-06-30 07:22:52 ERROR i.a.w.g.DefaultReplicationWorker(replicate):215 - Sync worker failed.
java.lang.RuntimeException: java.lang.IllegalStateException: Try to perform a partial reset on a legacy state
        at io.airbyte.workers.general.ReplicationWorkerHelper.startSource(ReplicationWorkerHelper.java:138) ~[io.airbyte-airbyte-commons-worker-0.50.5.jar:?]
        at io.airbyte.workers.general.DefaultReplicationWorker.replicate(DefaultReplicationWorker.java:165) ~[io.airbyte-airbyte-commons-worker-0.50.5.jar:?]
        at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:147) ~[io.airbyte-airbyte-commons-worker-0.50.5.jar:?]
        at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:62) ~[io.airbyte-airbyte-commons-worker-0.50.5.jar:?]
        at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$5(TemporalAttemptExecution.java:195) ~[io.airbyte-airbyte-workers-0.50.5.jar:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.IllegalStateException: Try to perform a partial reset on a legacy state
        at io.airbyte.workers.internal.EmptyAirbyteSource.start(EmptyAirbyteSource.java:102) ~[io.airbyte-airbyte-commons-worker-0.50.5.jar:?]
        at io.airbyte.workers.general.ReplicationWorkerHelper.startSource(ReplicationWorkerHelper.java:136) ~[io.airbyte-airbyte-commons-worker-0.50.5.jar:?]
        ... 5 more
2023-06-30 07:22:52 INFO i.a.w.g.ReplicationWorkerHelper(getReplicationOutput):288 - sync summary: {
  "status" : "failed",
  "recordsSynced" : 0,
  "bytesSynced" : 0,
  "startTime" : 1688109755568,
  "endTime" : 1688109772779,
  "totalStats" : {
    "bytesCommitted" : 0,
    "bytesEmitted" : 0,
    "destinationStateMessagesEmitted" : 0,
    "destinationWriteEndTime" : 0,
    "destinationWriteStartTime" : 1688109755569,
    "meanSecondsBeforeSourceStateMessageEmitted" : 0,
    "maxSecondsBeforeSourceStateMessageEmitted" : 0,
    "maxSecondsBetweenStateMessageEmittedandCommitted" : 0,
    "meanSecondsBetweenStateMessageEmittedandCommitted" : 0,
    "recordsEmitted" : 0,
    "recordsCommitted" : 0,
    "replicationEndTime" : 0,
    "replicationStartTime" : 1688109755568,
    "sourceReadEndTime" : 0,
    "sourceReadStartTime" : 1688109755606,
    "sourceStateMessagesEmitted" : 0
  },
`

**Comment by evantahler** [comment]
This is done
