### ISSUE TITLE
Airbyte Core - "Reset your data" status Failed

### ISSUE THREAD

**Issue by grubberr** [airbytehq/airbyte#14333]
## Environment
- **Airbyte version**:  0.39.30-alpha
- **OS Version / Instance**: Ubuntu 20.04
- **Deployment**: Docker
- **Source Connector and version**: (if applicable example Salesforce 0.2.3) 
- **Destination Connector and version**: destination-snowflake:0.4.30, destination-redshift:0.3.46
- **Step where error happened**: Sync job

## Current Behavior
Setup connection which sync data from any source to Snowflake or Redshift and make successful sync.
Next press **"Reset your data"** or **"Refresh source schema"**.

It looks like data really removed from database:

snowflake:
```
select count(*) from "INTEGRATION_TEST_DESTINATION"."TEXT_SCHEMA"."_AIRBYTE_RAW_TABLENAME";
0

select count(*) from "INTEGRATION_TEST_DESTINATION"."TEXT_SCHEMA"."TABLENAME";
0
```

redshift:
```
grubberr_test=# select count(*) from _airbyte_raw_tablename;
 count 
-------
     0
```

But in UI you can see 3 failed attempt:
 
<img width="406" alt="Screenshot 2022-07-01 at 09 45 39" src="https://user-images.githubusercontent.com/195743/176839424-48f5b944-3d64-4662-ab3c-bc2e18ed402b.png">

From logs:
```
2022-07-01 08:00:17 ERROR i.a.w.g.DefaultReplicationWorker(run):180 - Sync worker failed.
java.lang.NullPointerException: Cannot invoke "io.airbyte.config.State.getState()" because the return value of "io.airbyte.config.WorkerSourceConfig.getState()" is null
	at io.airbyte.workers.internal.EmptyAirbyteSource.start(EmptyAirbyteSource.java:86) ~[io.airbyte-airbyte-workers-0.39.30-alpha.jar:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:139) ~[io.airbyte-airbyte-workers-0.39.30-alpha.jar:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:65) ~[io.airbyte-airbyte-workers-0.39.30-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:158) ~[io.airbyte-airbyte-workers-0.39.30-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

## Expected Behavior
We have to get successful reset operation in UI

## Logs
[logs-1.txt](https://github.com/airbytehq/airbyte/files/9026625/logs-1.txt) - log of successful sync + normalization
[logs-2.txt](https://github.com/airbytehq/airbyte/files/9026626/logs-2.txt) - log of failed reset + normalization

[logs-5.txt](https://github.com/airbytehq/airbyte/files/9027175/logs-5.txt) - log of successful sync
[logs-6.txt](https://github.com/airbytehq/airbyte/files/9027177/logs-6.txt) - log of failed reset 

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by evantahler** [comment]
It's fixed, so closing!
