### ISSUE TITLE
Failed "Reset Your Data" will not let you sync again

### ISSUE THREAD

**Issue by yzislin** [airbytehq/airbyte#14529]
## Environment
- 0.39.29-alpha
- AWS EC2 - Ubuntu 22.04
- Docker
- Any Source connector (I believe). For example with Gitlab
- Local JSON
- Sync Job

## Current Behavior
First create a source connector, destination connector and a connection. Then kick off the sync.
If the sync fails or it gets cancelled, Reset Your Data causes unusual behavior. It fails with the error (see below in logs), and clicking on Sync Now will ALSO try to reset the data and fail. The solution is to delete connection and create again.

The error message says there is no sync state available when trying to reset.

## Expected Behavior
Reset the sync even if there is no state available.

## Logs

`2022-07-08 11:10:53 ERROR i.a.w.g.DefaultReplicationWorker(run):180 - Sync worker failed.
java.lang.NullPointerException: Cannot invoke "io.airbyte.config.State.getState()" because the return value of "io.airbyte.config.WorkerSourceConfig.getState()" is null
	at io.airbyte.workers.internal.EmptyAirbyteSource.start(EmptyAirbyteSource.java:86) ~[io.airbyte-airbyte-workers-0.39.29-alpha.jar:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:139) ~[io.airbyte-airbyte-workers-0.39.29-alpha.jar:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:65) ~[io.airbyte-airbyte-workers-0.39.29-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:158) ~[io.airbyte-airbyte-workers-0.39.29-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by evantahler** [comment]
@jdpgrailsdev I think we may have fixed this recently?

**Comment by jdpgrailsdev** [comment]
@evantahler This does sound familiar, but I can't recall anything specifically related to this issue.  It might be something that @alovew or @gosusnp addressed recently.

**Comment by yzislin** [comment]
Yes, this issue has been fixed as of 0.39.41.

Thank you
