### ISSUE TITLE
Source-MSSQL : does not support dot (.) character on database 

### ISSUE THREAD

**Issue by sivankumar86** [airbytehq/airbyte#14824]
## Environment
- **Airbyte version**:  0.39.x
- **OS Version / Instance**:  AWS EC2
- **Deployment**: Kubernetes 
- **Source Connector and version**:  0.4.8

## Current Behavior
*Tell us what happens.*
    Connection set up is failed due to dot (.) special character present in database name. 

## Expected Behavior
   It should work without any issue. 

## Logs
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near '.'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:872)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:767)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7375)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3206)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeQuery(SQLServerStatement.java:692)

## Steps to Reproduce
1. Create a database with dot (.) t Example, est.frontend
2. enable cdc and insert some rows in table which is present in above table
3. run airbyte job with above DB 

## Are you willing to submit a PR?
  Sure, if you can review and accept it.

**Comment by sivankumar86** [comment]
@grishick Could you take a look on pull request and merge it if it looks good ? it is minor change
