### ISSUE TITLE
MongoDB Source Connector Error on system table

### ISSUE THREAD

**Issue by osalloum** [airbytehq/airbyte#14987]
## Environment
- **Airbyte version**:  v0.39.38-alpha
- **OS Version / Instance**: aws ec2
- **Deployment**: Kubernetes
- **Source Connector and version**: airbyte/source-mongodb-v2 0.1.15
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
- **Step where error happened**: Setup new connection

## Current Behavior
The source connector fails to discover the schema 

## Expected Behavior
The source connector introspects the schema and shows the collections and destination configuration

## Logs
"Invalid $project :: caused by :: FieldPath field names may not start with '$'

## Steps to Reproduce
1. Enable Profiling on Mongo
2. Set up new mongo source connector 
3. Click on add new destination 

## Workaround 

Stop profiling and drop collection
```
db.setProfilingLevel(0)
db.system.profile.drop()
```

## Possible fix 

Exclude system tables from schema discovery

**Comment by marcosmarxm** [comment]
Zendesk ticket #[1645](https://airbyte7538.zendesk.com/agent/tickets/1645) has been linked to this issue.

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Sajarin Dider on 2022-07-25 at 15:50:*

<blockquote><div class="zd-comment" dir="auto">Hey @fauh45, looks like another user is also reporting the same issue: <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/14987">https://github.com/airbytehq/airbyte/issues/14987</a>. Looks like there is an issue with the parsing of the $ character according to MongoDB docs: <a rel="noopener noreferrer" href="https://www.mongodb.com/docs/manual/reference/operator/aggregation/literal/">https://www.mongodb.com/docs/manual/reference/operator/aggregation/literal/</a><br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-07-26 at 01:59:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Ahhh I see, let me try to use their workaround first</p> 

 [<a href="https://discuss.airbyte.io/t/source-mongodb-failed-to-fetch-mongodb-of-digitalocean-managed-db-schema/1931/8" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-07-26 at 02:27:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Turns out at my current settings the profiling are set to 0 already. I even tried to set the profiling to 1, then do the connection setup, and do the workaround shown in the issues. Still nothing works.</p>
<p dir="auto">Does the mongodb version could cause this error? But don’t <code style="background-color: #f9f9f9; padding: 2px 5px;">$project</code> already exist way long ago? Maybe just the parsing of the command given by the source connector?</p> 

 [<a href="https://discuss.airbyte.io/t/source-mongodb-failed-to-fetch-mongodb-of-digitalocean-managed-db-schema/1931/9" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-07-26 at 06:51:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Did you try to drop the collection the collection of profiling from the mongo database you are targeting?</p>
<p dir="auto"><code style="background-color: #f9f9f9; padding: 2px 5px;">db.system.profile.drop()</code></p>
<p dir="auto">If that does not help, it might be a different collection that is causing the issue on your end<br>
Unfortunately the airbyte logs are not helpful in identifying the culprit</p>
<p dir="auto">There are 2 ways to figure it out:</p>
<p dir="auto"><strong>The hard way:</strong><br>
To figure it out, if you your own custom mongo setup, you can try figure out the log output of mongo ( <a href="https://www.mongodb.com/docs/manual/reference/program/mongod/#std-option-mongod.--logpath" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;">https://www.mongodb.com/docs/manual/reference/program/mongod/#std-option-mongod.--logpath</a> ) and tail that log stream and filter out for $project call</p>
<p dir="auto"><code style="background-color: #f9f9f9; padding: 2px 5px;">tail -f /replace/with/your/path/to/mongo.log | grep '$project'</code></p>
<p dir="auto">if you are using a SaaS like Atlas, you should download the full file and look into: <a href="https://www.mongodb.com/docs/atlas/mongodb-logs/" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;">https://www.mongodb.com/docs/atlas/mongodb-logs/</a></p>
<p dir="auto">Ultimately you will be able to see error log and identify the culprit collection then figure out what can be done about it</p>
<p dir="auto"><strong>The easy way:</strong><br>
Connect to mongodb with same credentials you are giving airbyte and run</p>
<p dir="auto"><code style="background-color: #f9f9f9; padding: 2px 5px;">db.runCommand( { listCollections: 1.0, authorizedCollections: true, filter: {type: 'collection'} } ).cursor.firstBatch</code></p>
<p dir="auto">which is exactly the same call airbyte is doing  airbytehq/airbyte/blob/436de264cbb9402cfb8d7b6b8d0cd996efc4f659/airbyte-integrations/connectors/source-mongodb-v2/src/main/java/io.airbyte.integrations.source.mongodb/MongoDbSource.java  (can’t post link <img src="https://emoji.discourse-cdn.com/twitter/frowning.png?v=12" title=":frowning:" alt=":frowning:" width="20" height="20">  )</p>
<p dir="auto">If you are seeing a bunch of system tables (has “system.” in the name), that points out to your problem, you need to set up a user with lower access rights to the target db, a “read” user or “dbOwner”</p> 

 [<a href="https://discuss.airbyte.io/t/source-mongodb-failed-to-fetch-mongodb-of-digitalocean-managed-db-schema/1931/10" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by ecylmz** [comment]
Hi,

We are also having the same problem. Any progress on this issue?

**Comment by marcosmarxm** [comment]
Not yet @ecylmz please if you can give more information about how reproduce the issue it will help a lot.

**Comment by nseniak** [comment]
Hi @marcosmarxm I have the same problem, unfortunately I can't give you access to the database that causes the problem but I can give the stack trace if that may help:

```
2022-12-23 14:14:49 INFO i.a.w.i.DefaultAirbyteStreamFactory(internalLog):120 - Opened connection [connectionId{localValue:62, serverValue:703934}] to 192.168.240.56:27017
2022-12-23 14:15:11 ERROR i.a.w.i.DefaultAirbyteStreamFactory(internalLog):116 - Something went wrong in the connector. See the logs for more details.
Stack Trace: com.mongodb.MongoCommandException: Command failed with error 16410 (Location16410): 'FieldPath field names may not start with '$'.' on server 192.168.240.56:27017. The full response is {"operationTime": {"$timestamp": {"t": 1671804890, "i": 2781}}, "ok": 0.0, "errmsg": "FieldPath field names may not start with '$'.", "code": 16410, "codeName": "Location16410", "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1671804890, "i": 2827}}, "signature": {"hash": {"$binary": {"base64": "AAAAAAAAAAAAAAAAAAAAAAAAAAA=", "subType": "00"}}, "keyId": 0}}}
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:198)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:418)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:342)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:116)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:647)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:71)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:244)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:227)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:127)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:117)
	at com.mongodb.internal.connection.DefaultServer$OperationCountTrackingConnection.command(DefaultServer.java:348)
	at com.mongodb.internal.operation.CommandOperationHelper.createReadCommandAndExecute(CommandOperationHelper.java:228)
	at com.mongodb.internal.operation.CommandOperationHelper.lambda$executeRetryableRead$4(CommandOperationHelper.java:210)
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$2(OperationHelper.java:564)
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:589)
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$3(OperationHelper.java:563)
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:589)
	at com.mongodb.internal.operation.OperationHelper.withSourceAndConnection(OperationHelper.java:562)
	at com.mongodb.internal.operation.CommandOperationHelper.lambda$executeRetryableRead$5(CommandOperationHelper.java:207)
	at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:65)
	at com.mongodb.internal.operation.CommandOperationHelper.executeRetryableRead(CommandOperationHelper.java:213)
	at com.mongodb.internal.operation.CommandOperationHelper.executeRetryableRead(CommandOperationHelper.java:193)
	at com.mongodb.internal.operation.AggregateOperationImpl.execute(AggregateOperationImpl.java:195)
	at com.mongodb.internal.operation.AggregateOperation.execute(AggregateOperation.java:306)
	at com.mongodb.internal.operation.AggregateOperation.execute(AggregateOperation.java:46)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:191)
	at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:135)
	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:92)
	at com.mongodb.client.internal.MongoIterableImpl.cursor(MongoIterableImpl.java:97)
	at io.airbyte.db.mongodb.MongoUtils.getTypes(MongoUtils.java:269)
	at io.airbyte.db.mongodb.MongoUtils.lambda$setSubFields$1(MongoUtils.java:235)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at io.airbyte.db.mongodb.MongoUtils.setSubFields(MongoUtils.java:234)
	at io.airbyte.db.mongodb.MongoUtils.lambda$setSubFields$1(MongoUtils.java:239)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at io.airbyte.db.mongodb.MongoUtils.setSubFields(MongoUtils.java:234)
	at io.airbyte.db.mongodb.MongoUtils.lambda$setSubFields$1(MongoUtils.java:239)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at io.airbyte.db.mongodb.MongoUtils.setSubFields(MongoUtils.java:234)
	at io.airbyte.db.mongodb.MongoUtils.lambda$getUniqueFields$0(MongoUtils.java:212)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at io.airbyte.db.mongodb.MongoUtils.getUniqueFields(MongoUtils.java:215)
	at io.airbyte.integrations.source.mongodb.MongoDbSource.lambda$discoverInternal$1(MongoDbSource.java:106)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2022-12-23 14:15:12 INFO i.a.w.t.TemporalAttemptExecution(get):163 - Stopping cancellation check scheduling...
```

**Comment by sajarin** [comment]
@nseniak 

The error message FieldPath field names may not start with '$' occurs when a MongoDB query includes a field path (a document field name or an array of field names) that starts with a dollar sign $. This is not allowed in MongoDB because the dollar sign is reserved for use in special field names and operator names.

The error message is being generated by the com.mongodb.MongoCommandException exception, which is thrown when a MongoDB command fails to execute. The exception contains information about the error that occurred, including the error code and the full response from the server.

This error can occur for a few different reasons:

- The query may include a field path that starts with a dollar sign, either intentionally or by mistake. In this case, the error can be fixed by removing the dollar sign or by escaping it with a backslash.

- The query may include a dollar sign as part of a string value, but the string is being interpreted as a field path. In this case, the error can be fixed by enclosing the string in quotes or by escaping the dollar sign with a backslash.

- The query may be attempting to use a dollar sign in a field name that is not allowed by MongoDB. In this case, the error can be fixed by using a different field name.

Hope this helps!

**Comment by nseniak** [comment]
@sajarin thanks for the clarification. However this error occurs while the mongodb source connectors attempts to introspect the database schema, and I have no control over the database field names.

**Comment by sajarin** [comment]
@nseniak thanks for clarifying, seems like the source isn't escaping and parsing the database field names correctly. If someone's willing to push a fix, we'd be happy to review it.

**Comment by myesn** [comment]
Same problem：

`Source` of MongoDB version is:  `4.4.14`
`Destination` of MongoDB version is: `4.4.14`

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 365 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.
