### ISSUE TITLE
 MSSQL Connector json validator failed error

### ISSUE THREAD

**Issue by yash-ghelani-dsw** [airbytehq/airbyte#15284]
Environment
Airbyte version: 0.39.36-alpha
OS Version / Instance: Ubuntu 18.04 (AWS EC2)
Deployment: Docker 
Source Connector and version: mssql (0.4.8)
Destination Connector and version: Postgres (0.3.8)
Step where error happened: Sync job
Tell us what happens.
I am trying to connect to mssql and transfer data to postgres through airbyte. I have enable cdc with DB and table level as well. Have enable snapshot isolation also DB. Still it gives following error:

Expected Behavior
It should work as per the expected behaviour of airbyte

Logs(have attached top small part of error):
2022-08-03 11:30:14 INFO i.a.v.j.JsonSchemaValidator(test):71 - JSON schema validation failed.
errors: .snapshot_isolation: is not defined in the schema and the schema does not allow additional properties, .replication_type: does not have a value in the enumeration [STANDARD]
2022-08-03 11:30:14 INFO i.a.w.t.TemporalAttemptExecution(get):108 - Docker volume job log path: /tmp/workspace/61/0/logs.log
2022-08-03 11:30:14 INFO i.a.w.t.TemporalAttemptExecution(get):113 - Executing worker wrapper. Airbyte version: 0.39.36-alpha
2022-08-03 11:30:14 INFO i.a.c.f.EnvVariableFeatureFlags(getEnvOrDefault):43 - Using default value for environment variable USE_STREAM_CAPABLE_STATE: 'false'
2022-08-03 11:30:14 INFO i.a.c.i.LineGobbler(voidCall):82 - Checking if airbyte/source-mssql:0.4.8 exists...
2022-08-03 11:30:14 INFO i.a.c.i.LineGobbler(voidCall):82 - airbyte/source-mssql:0.4.8 was found locally.
2022-08-03 11:30:14 INFO i.a.w.p.DockerProcessFactory(create):108 - Creating docker job ID: 61
2022-08-03 11:30:14 INFO i.a.w.p.DockerProcessFactory(create):163 - Preparing command: docker run --rm --init -i -w /data/61/0 --log-driver none --name source-mssql-check-61-0-caxnq --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e USE_STREAM_CAPABLE_STATE=false -e AIRBYTE_ROLE= -e WORKER_ENVIRONMENT=DOCKER -e WORKER_CONNECTOR_IMAGE=airbyte/source-mssql:0.4.8 -e WORKER_JOB_ATTEMPT=0 -e AIRBYTE_VERSION=0.39.36-alpha -e WORKER_JOB_ID=61 airbyte/source-mssql:0.4.8 check --config source_config.json
2022-08-03 11:30:14 ERROR i.a.c.i.LineGobbler(voidCall):82 - SLF4J: Class path contains multiple SLF4J bindings.
2022-08-03 11:30:14 ERROR i.a.c.i.LineGobbler(voidCall):82 - SLF4J: Found binding in [jar:file:/airbyte/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2022-08-03 11:30:14 ERROR i.a.c.i.LineGobbler(voidCall):82 - SLF4J: Found binding in [jar:file:/airbyte/lib/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2022-08-03 11:30:14 ERROR i.a.c.i.LineGobbler(voidCall):82 - SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
2022-08-03 11:30:14 ERROR i.a.c.i.LineGobbler(voidCall):82 - SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]

**Comment by marcosmarxm** [comment]
Please share the complete log file.

**Comment by yash-ghelani-dsw** [comment]
> Please share the complete log file.
have attached below:
[logs-71.txt](https://github.com/airbytehq/airbyte/files/9266305/logs-71.txt)

**Comment by marcosmarxm** [comment]
Here is the correct error:
```
2022-08-04 11:42:53 [44msource[0m > java.lang.RuntimeException: SQL returned max LSN as null, this might be because the SQL Server Agent is not running. Please enable the Agent and try again (https://docs.microsoft.com/en-us/sql/ssms/agent/start-stop-or-pause-the-sql-server-agent-service?view=sql-server-ver15)
2022-08-04 11:42:53 [44msource[0m > 	at io.airbyte.integrations.source.mssql.MssqlCdcTargetPosition.getTargetPosition(MssqlCdcTargetPosition.java:78) ~[io.airbyte.airbyte-integrations.connectors-source-mssql-0.39.28-alpha.jar:?]
2022-08-04 11:42:53 [44msource[0m > 	at io.airbyte.integrations.source.mssql.MssqlSource.getIncrementalIterators(MssqlSource.java:371) ~[io.airbyte.airbyte-integrations.connectors-source-mssql-0.39.28-alpha.jar:?]
2022-08-04 11:42:53 [44msource[0m > 	at io.airbyte.integrations.source.mssql.MssqlSource.getIncrementalIterators(MssqlSource.java:54) ~[io.airbyte.airbyte-integrations.connectors-source-mssql-0.39.28-alpha.jar:?]
2022-08-04 11:42:53 [44msource[0m > 	at io.airbyte.integrations.source.relationaldb.AbstractDbSource.read(AbstractDbSource.java:129) ~[io.airbyte.airbyte-integrations.connectors-source-relational-db-0.39.28-alpha.jar:?]
2022-08-04 11:42:53 [44msource[0m > 	at io.airbyte.integrations.base.ssh.SshWrappedSource.read(SshWrappedSource.java:54) [io.airbyte.airbyte-integrations.bases-base-java-0.39.28-alpha.jar:?]
2022-08-04 11:42:53 [44msource[0m > 	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:155) [io.airbyte.airbyte-integrations.bases-base-java-0.39.28-alpha.jar:?]
2022-08-04 11:42:53 [44msource[0m > 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:107) [io.airbyte.airbyte-integrations.bases-base-java-0.39.28-alpha.jar:?]
2022-08-04 11:42:53 [44msource[0m > 	at io.airbyte.integrations.source.mssql.MssqlSource.main(MssqlSource.java:453) [io.airbyte.airbyte-integrations.connectors-source-mssql-0.39.28-alpha.jar:?]
2022-08-04 11:42:53 [44msource[0m > 2022-08-04 11:42:53 [1;31mERROR[m i.a.i.b.AirbyteExceptionHandler(uncaughtException):26 - Something went wrong in the connector. See the logs for more details.
2022-08-04 11:42:53 [44msource[0m > java.lang.RuntimeException: SQL returned max LSN as null, this might be because the SQL Server Agent is not running. Please enable the Agent and try again (https://docs.microsoft.com/en-us/sql/ssms/agent/start-stop-or-pause-the-sql-server-agent-service?view=sql-server-ver15)
```
Please check the message and your database if it's working properly.

**Comment by yash-ghelani-dsw** [comment]
> Here is the correct error:
> 
> ```
> 2022-08-04 11:42:53 �[44msource�[0m > java.lang.RuntimeException: SQL returned max LSN as null, this might be because the SQL Server Agent is not running. Please enable the Agent and try again (https://docs.microsoft.com/en-us/sql/ssms/agent/start-stop-or-pause-the-sql-server-agent-service?view=sql-server-ver15)
> 2022-08-04 11:42:53 �[44msource�[0m > 	at io.airbyte.integrations.source.mssql.MssqlCdcTargetPosition.getTargetPosition(MssqlCdcTargetPosition.java:78) ~[io.airbyte.airbyte-integrations.connectors-source-mssql-0.39.28-alpha.jar:?]
> 2022-08-04 11:42:53 �[44msource�[0m > 	at io.airbyte.integrations.source.mssql.MssqlSource.getIncrementalIterators(MssqlSource.java:371) ~[io.airbyte.airbyte-integrations.connectors-source-mssql-0.39.28-alpha.jar:?]
> 2022-08-04 11:42:53 �[44msource�[0m > 	at io.airbyte.integrations.source.mssql.MssqlSource.getIncrementalIterators(MssqlSource.java:54) ~[io.airbyte.airbyte-integrations.connectors-source-mssql-0.39.28-alpha.jar:?]
> 2022-08-04 11:42:53 �[44msource�[0m > 	at io.airbyte.integrations.source.relationaldb.AbstractDbSource.read(AbstractDbSource.java:129) ~[io.airbyte.airbyte-integrations.connectors-source-relational-db-0.39.28-alpha.jar:?]
> 2022-08-04 11:42:53 �[44msource�[0m > 	at io.airbyte.integrations.base.ssh.SshWrappedSource.read(SshWrappedSource.java:54) [io.airbyte.airbyte-integrations.bases-base-java-0.39.28-alpha.jar:?]
> 2022-08-04 11:42:53 �[44msource�[0m > 	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:155) [io.airbyte.airbyte-integrations.bases-base-java-0.39.28-alpha.jar:?]
> 2022-08-04 11:42:53 �[44msource�[0m > 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:107) [io.airbyte.airbyte-integrations.bases-base-java-0.39.28-alpha.jar:?]
> 2022-08-04 11:42:53 �[44msource�[0m > 	at io.airbyte.integrations.source.mssql.MssqlSource.main(MssqlSource.java:453) [io.airbyte.airbyte-integrations.connectors-source-mssql-0.39.28-alpha.jar:?]
> 2022-08-04 11:42:53 �[44msource�[0m > 2022-08-04 11:42:53 �[1;31mERROR�[m i.a.i.b.AirbyteExceptionHandler(uncaughtException):26 - Something went wrong in the connector. See the logs for more details.
> 2022-08-04 11:42:53 �[44msource�[0m > java.lang.RuntimeException: SQL returned max LSN as null, this might be because the SQL Server Agent is not running. Please enable the Agent and try again (https://docs.microsoft.com/en-us/sql/ssms/agent/start-stop-or-pause-the-sql-server-agent-service?view=sql-server-ver15)
> ```
> 
> Please check the message and your database if it's working properly.

Hi, my Mssql server agent is unable to work properly, So yeah issue was on DB side
