### ISSUE TITLE
Temporal not able to connect to postgres

### ISSUE THREAD

**Issue by PabloPardoGarcia** [airbytehq/airbyte#15315]
## Environment
- **Airbyte version**:  0.39.41-alpha
- **OS Version / Instance**: EKS
- **Deployment**: Kubernetes (helm chart from https://airbytehq.github.io/helm-charts/ version 0.34.0)

## Current Behavior
When deploying Airbyte, the temporal deployment is stuck with this error:

```
Waiting for PostgreSQL to startup.
+ echo 'Waiting for PostgreSQL to startup.'
+ sleep 1
+ nc -z airbyte-postgresql 5432
nc: bad address 'airbyte-postgresql'
```

The worker and server deployments fail as well since they are not able to connect to temporal.

Digging more into the code, I could see that the temporal deployment is using the env variable `POSTRES_SEEDS` as the host and in the variable is set up to `<release.name>-postrgersql` (https://github.com/airbytehq/airbyte/blob/39db316fc86faa69231d7c8894056051721db781/charts/airbyte-temporal/templates/deployment.yaml#L64). 

## Expected Behavior
*Tell us what should happen.*

## Steps to Reproduce
1. 
2. 
3. 

## Are you willing to submit a PR?

Don't mind

**Comment by edlouth** [comment]
I would propose changing this to:

```
 - name: POSTGRES_SEEDS
            value: {{ .Values.global.database.host | default (printf "%s-postgresql" .Release.Name) }}
```

although maybe people would be expecting this to take host from `externalDatabase.host`?

**Comment by ingo-m** [comment]
@edlouth thanks. I already tried this (not sure about the `default` value, yours probably makes more sense):
```
          - name: POSTGRES_SEEDS
            value: {{ .Values.global.database.host | default "postgresql-host" }}
```
I took helm chart version `0.34.0`, applied the above change, in combination with airbyte version `0.39.42-alpha`. This seems to work in the sense that now the PostgreSQL database becomes available to airbyte, but now the `airbyte-server-...` pod goes into a CrashLoopBackOff. I noticed this in the logs of the `airbyte-server-...` pod:

```
2022-08-08 11:03:23 WARN i.a.w.t.TemporalUtils(getTemporalClientWhenConnected):274 - Ignoring exception while trying to request Temporal namespace:
io.grpc.StatusRuntimeException: NOT_FOUND: Namespace default does not exist.
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262) ~[grpc-stub-1.44.1.jar:1.44.1]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243) ~[grpc-stub-1.44.1.jar:1.44.1]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156) ~[grpc-stub-1.44.1.jar:1.44.1]
	at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.describeNamespace(WorkflowServiceGrpc.java:2582) ~[temporal-serviceclient-1.8.1.jar:?]
	at io.airbyte.workers.temporal.TemporalUtils.getNamespaceInfo(TemporalUtils.java:288) ~[io.airbyte-airbyte-workers-0.39.42-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalUtils.getTemporalClientWhenConnected(TemporalUtils.java:270) [io.airbyte-airbyte-workers-0.39.42-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalUtils.createTemporalService(TemporalUtils.java:75) [io.airbyte-airbyte-workers-0.39.42-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalUtils.createTemporalService(TemporalUtils.java:90) [io.airbyte-airbyte-workers-0.39.42-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalUtils.createTemporalService(TemporalUtils.java:94) [io.airbyte-airbyte-workers-0.39.42-alpha.jar:?]
	at io.airbyte.server.ServerApp.getServer(ServerApp.java:214) [io.airbyte-airbyte-server-0.39.42-alpha.jar:?]
	at io.airbyte.server.ServerApp.main(ServerApp.java:303) [io.airbyte-airbyte-server-0.39.42-alpha.jar:?]
2022-08-08 11:03:23 WARN i.a.w.t.TemporalUtils(getTemporalClientWhenConnected):264 - Waiting for namespace default to be initialized in temporal...
```

I don't know what to make of this.

**Comment by ingo-m** [comment]
A similar (the same?) problem was reported with airbyte version 0.30.21 https://github.com/airbytehq/airbyte/issues/7226

**Comment by evantahler** [comment]
Can you pleas check if https://github.com/airbytehq/airbyte/pull/15510 fixed the problem?

**Comment by evantahler** [comment]
Closing as I believe #15510 fixed the issue.  Please re-open this if you are still having trouble!

**Comment by ingo-m** [comment]
Thanks, I will test whether this fixed the problem ASAP.

**Comment by ingo-m** [comment]
I just tried to test whether https://github.com/airbytehq/airbyte/pull/15510 fixed the problem, but I ran into a new issue that has already been reported here: https://github.com/airbytehq/airbyte/issues/16123

Will try again when https://github.com/airbytehq/airbyte/issues/16123 is fixed.
