### ISSUE TITLE
Source Amazon Seller Partner: `shipments` reports cannot be generated

### ISSUE THREAD

**Issue by pavneet9** [airbytehq/airbyte#15415]
Environment
- Airbyte version:  0.40.0-alpha
- OS Version / Instance: AWS EC2
- Deployment: Docker
- Source Connector and version: amazon-seller-partner 0.24.0
- Step where error happened: Sync job

Current Behaviour
GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL, When i am trying to get data for this end point, the source times out before the report is generated. hence I get an error where the report status is either in_progress or in_queue.

And in the next attempt it again tries to get a new report which again times out before it is generated.

Is there a way to change this behaviour maybe extend the timeout period or store the report Id somewhere.

Logs
  File "/airbyte/integration_code/source_amazon_seller_partner/streams.py", line 368, in read_records
    raise Exception(f"Unknown response for stream `{self.name}`. Response body {report_payload}")
Exception: Unknown response for stream `GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL`. Response body {'reportType': 'GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL', 'processingStatus': 'IN_QUEUE', 'marketplaceIds': ['ATVPDKIKX0DER'], 'reportId': '522360019212', 'dataEndTime': '2022-08-08T18:11:57+00:00', 'createdTime': '2022-08-08T18:11:57+00:00', 'dataStartTime': '2022-08-06T18:11:57+00:00'}
,retryable=<null>,timestamp=1659982859045], io.airbyte.config.FailureReason@2e667c57[failureOrigin=source,failureType=<null>,internalMessage=io.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source cannot be stopped!,externalMessage=Something went wrong within the source connector,metadata=io.airbyte.config.Metadata@2b6f1ed9[additionalProperties={attemptNumber=2, jobId=8}],stacktrace=java.util.concurrent.CompletionException: io.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source cannot be stopped!
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: io.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source cannot be stopped!
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$getReplicationRunnable$6(DefaultReplicationWorker.java:332)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	... 3 more
Caused by: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
	at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:136)
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$getReplicationRunnable$6(DefaultReplicationWorker.java:330)
	... 4 more
,retryable=<null>,timestamp=1659982859170]]]
2022-08-08 18:20:59 INFO i.a.w.t.TemporalUtils(withBackgroundHeartbeat):291 - Stopping temporal heartbeating...

**Comment by sajarin** [comment]
@pavneet9 would it be possible to post the full sync logs as a txt file?

**Comment by pavneet9** [comment]
Here are the text logs
[logs-11.txt](https://github.com/airbytehq/airbyte/files/9284961/logs-11.txt)

**Comment by natalyjazzviolin** [comment]
Hey @pavneet9 , timeout periods can be configured using environmental variables, more here:
https://docs.airbyte.com/operator-guides/configuring-airbyte/

I don't think the issue is in the amount of time Airbyte alots to the stream, unfortunately. Looks like there was an issue with this stream being empty - it's unclear whether it's been fixed:
https://github.com/airbytehq/airbyte/issues/7414

**Comment by lazebnyi** [comment]
Duplicate - https://github.com/airbytehq/airbyte/issues/7414
