### ISSUE TITLE
Helm deployment error: "can't get a valid version for repositories" on AWS EKS

### ISSUE THREAD

**Issue by suman9730** [airbytehq/airbyte#15470]
## Environment
- **Airbyte version**:  0.39.41-alpha
- **OS Version / Instance**: Windows 10
- **Deployment**: helm deployment on AWS EKS
- **Source Connector and version**: N/A
- **Destination Connector and version**: N/A
- **Step where error happened**: Deploy

## Current Behavior
I am trying helm deployment of AirByte on AWS EKS cluster using following commands.
$ helm repo add bitnami https://charts.bitnami.com/bitnami
$ helm dep build charts/airbyte
$ helm upgrade --install --namespace "ns-0000-test"  --debug  --wait  --timeout "600s" contra-airbyte ./charts/airbyte

I am using following for version in Chart.yaml
version: 0.39.36 (Tried with 0.39.x as well)

## Expected Behavior
Build should happen

## Logs

$ helm repo add bitnami https://charts.bitnami.com/bitnami
"bitnami" already exists with the same configuration, skipping

$ helm dep build charts/airbyte
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "airbyte-oss" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
Error: can't get a valid version for repositories airbyte-bootloader, temporal, webapp, server, worker, pod-sweeper. Try changing the version constraint in Chart.yaml

## Steps to Reproduce
Run 
$ helm repo add bitnami https://charts.bitnami.com/bitnami
$ helm dep build charts/airbyte

## Are you willing to submit a PR?
No

**Comment by xpuska513** [comment]
Hi, for using new Helm charts, please refer to [this](https://docs.airbyte.com/deploying-airbyte/on-kubernetes-via-helm#adding-helm-repository) doc

**Comment by xpuska513** [comment]
You don't need to clone the oss repo anymore for that, also the reason it didn't found any charts in repo is because we set version values to "placeholder" so it won't interfere with our CI release workflow

**Comment by suman9730** [comment]
Ran following commands for default installation, but no luck:
$ helm repo add airbyte https://airbytehq.github.io/helm-charts
$ helm repo update
$ helm install --namespace "ns-0026-idl"  --debug  --wait  --timeout "600s" test-airbyte airbyte/airbyte
install.go:178: [debug] Original chart version: ""
install.go:195: [debug] CHART PATH: C:\Users\ssss\AppData\Local\Temp\1\helm\repository\airbyte-0.34.2.tgz

client.go:299: [debug] Starting delete for "airbyte-admin" ServiceAccount
client.go:328: [debug] serviceaccounts "airbyte-admin" not found
client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "test-airbyte-airbyte-env" ConfigMap
client.go:328: [debug] configmaps "test-airbyte-airbyte-env" not found
client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "test-airbyte-airbyte-secrets" Secret
client.go:328: [debug] secrets "test-airbyte-airbyte-secrets" not found
client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "test-airbyte-postgresql" Secret
client.go:328: [debug] secrets "test-airbyte-postgresql" not found
client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "test-airbyte-postgresql" Service
client.go:328: [debug] services "test-airbyte-postgresql" not found
client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "test-airbyte-postgresql" StatefulSet
client.go:328: [debug] statefulsets.apps "test-airbyte-postgresql" not found
client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "test-airbyte-postgresql-headless" Service
client.go:328: [debug] services "test-airbyte-postgresql-headless" not found
client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "test-airbyte-airbyte-bootloader" Pod
client.go:328: [debug] pods "test-airbyte-airbyte-bootloader" not found
client.go:128: [debug] creating 1 resource(s)
client.go:529: [debug] Watching for changes to Pod test-airbyte-airbyte-bootloader with timeout of 10m0s
client.go:557: [debug] Add/Modify event for test-airbyte-airbyte-bootloader: ADDED
client.go:616: [debug] Pod test-airbyte-airbyte-bootloader pending
client.go:557: [debug] Add/Modify event for test-airbyte-airbyte-bootloader: MODIFIED
client.go:616: [debug] Pod test-airbyte-airbyte-bootloader pending
client.go:557: [debug] Add/Modify event for test-airbyte-airbyte-bootloader: MODIFIED
client.go:616: [debug] Pod test-airbyte-airbyte-bootloader pending
client.go:557: [debug] Add/Modify event for test-airbyte-airbyte-bootloader: MODIFIED
client.go:616: [debug] Pod test-airbyte-airbyte-bootloader pending
client.go:557: [debug] Add/Modify event for test-airbyte-airbyte-bootloader: MODIFIED
client.go:618: [debug] Pod test-airbyte-airbyte-bootloader running
client.go:557: [debug] Add/Modify event for test-airbyte-airbyte-bootloader: MODIFIED
Error: INSTALLATION FAILED: failed pre-install: pod test-airbyte-airbyte-bootloader failed
helm.go:84: [debug] failed pre-install: pod test-airbyte-airbyte-bootloader failed
INSTALLATION FAILED
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:127
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.3.0/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.3.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.3.0/command.go:902
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:255
runtime.goexit
        runtime/asm_amd64.s:1581


$ kubectl get pods -n ns-0026-idl | grep airbyte
test-airbyte-airbyte-bootloader                       0/1     Error     0          3m48s
test-airbyte-postgresql-0                             0/1     Pending   0          3m50s

**Comment by xpuska513** [comment]
Can you describe the bootloader pod?
And kubectl logs too

**Comment by suman9730** [comment]
**$ kubectl describe pod test-airbyte-airbyte-bootloader -n ns-0026-idl**
Name:                 test-airbyte-airbyte-bootloader
Namespace:            ns-0026-idl
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 fargate-ip-10-2-5-222.ec2.internal/10.2.5.222
Start Time:           Tue, 09 Aug 2022 15:41:49 -0500
Labels:               app.airbyte.io/fullname=test-airbyte-airbyte-bootloader
                      app.kubernetes.io/instance=test-airbyte
                      app.kubernetes.io/managed-by=Helm
                      app.kubernetes.io/name=airbyte-bootloader
                      app.kubernetes.io/version=0.39.42-alpha
                      eks.amazonaws.com/fargate-profile=fp-0026-idl
                      helm.sh/chart=airbyte-bootloader-0.34.2
Annotations:          CapacityProvisioned: 0.25vCPU 0.5GB
                      Logging: LoggingDisabled: LOGGING_CONFIGMAP_NOT_FOUND
                      helm.sh/hook: pre-install,pre-upgrade
                      helm.sh/hook-weight: 0
                      kubernetes.io/psp: eks.privileged
Status:               Failed
IP:                   10.2.5.222
IPs:
  IP:  10.2.5.222
Containers:
  airbyte-bootloader-container:
    Container ID:   containerd://8bdac4f9e0d8911d620ab3262fa303607d759edabc9ab6c8624702be99838af0
    Image:          airbyte/bootloader:0.39.42-alpha
    Image ID:       docker.io/airbyte/bootloader@sha256:cf07f2660e8b3a8e42e024abdd34fbb5f0b5f7f81425e9d5924f529db79bc16d
    Port:           <none>
    Host Port:      <none>
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 09 Aug 2022 15:42:11 -0500
      Finished:     Tue, 09 Aug 2022 15:43:26 -0500
    Ready:          False
    Restart Count:  0
    Environment:
      AIRBYTE_VERSION:    <set to the key 'AIRBYTE_VERSION' of config map 'test-airbyte-airbyte-env'>  Optional: false
      DATABASE_HOST:      <set to the key 'DATABASE_HOST' of config map 'test-airbyte-airbyte-env'>    Optional: false
      DATABASE_PORT:      <set to the key 'DATABASE_PORT' of config map 'test-airbyte-airbyte-env'>    Optional: false
      DATABASE_PASSWORD:  <set to the key 'postgresql-password' in secret 'test-airbyte-postgresql'>   Optional: false
      DATABASE_URL:       <set to the key 'DATABASE_URL' of config map 'test-airbyte-airbyte-env'>     Optional: false
      DATABASE_USER:      <set to the key 'DATABASE_USER' in secret 'test-airbyte-airbyte-secrets'>    Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from airbyte-admin-token-tkcgt (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  airbyte-admin-token-tkcgt:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  airbyte-admin-token-tkcgt
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>

**$ kubectl describe pod test-airbyte-postgresql-0 -n ns-0026-idl**
Name:                 test-airbyte-postgresql-0
Namespace:            ns-0026-idl
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 <none>
Labels:               app.kubernetes.io/component=primary
                      app.kubernetes.io/instance=test-airbyte
                      app.kubernetes.io/managed-by=Helm
                      app.kubernetes.io/name=postgresql
                      controller-revision-hash=test-airbyte-postgresql-d5b8d7d57
                      eks.amazonaws.com/fargate-profile=fp-0026-idl
                      helm.sh/chart=postgresql-10.16.2
                      role=primary
                      statefulset.kubernetes.io/pod-name=test-airbyte-postgresql-0
Annotations:          kubernetes.io/psp: eks.privileged
Status:               Pending
IP:
IPs:                  <none>
Controlled By:        StatefulSet/test-airbyte-postgresql
Containers:
  test-airbyte-postgresql:
    Image:      docker.io/bitnami/postgresql:11.14.0-debian-10-r28
    Port:       5432/TCP
    Host Port:  0/TCP
    Requests:
      cpu:      250m
      memory:   256Mi
    Liveness:   exec [/bin/sh -c exec pg_isready -U "airbyte" -d "dbname=db-airbyte" -h 127.0.0.1 -p 5432] delay=30s timeout=5s period=10s #success=1 #failure=6
    Readiness:  exec [/bin/sh -c -e exec pg_isready -U "airbyte" -d "dbname=db-airbyte" -h 127.0.0.1 -p 5432
[ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
] delay=5s timeout=5s period=10s #success=1 #failure=6
    Environment:
      BITNAMI_DEBUG:                        false
      POSTGRESQL_PORT_NUMBER:               5432
      POSTGRESQL_VOLUME_DIR:                /bitnami/postgresql
      PGDATA:                               /bitnami/postgresql/data
      POSTGRES_POSTGRES_PASSWORD:           <set to the key 'postgresql-postgres-password' in secret 'test-airbyte-postgresql'>  Optional: false
      POSTGRES_USER:                        airbyte
      POSTGRES_PASSWORD:                    <set to the key 'postgresql-password' in secret 'test-airbyte-postgresql'>  Optional: false
      POSTGRES_DB:                          db-airbyte
      POSTGRESQL_ENABLE_LDAP:               no
      POSTGRESQL_ENABLE_TLS:                no
      POSTGRESQL_LOG_HOSTNAME:              false
      POSTGRESQL_LOG_CONNECTIONS:           false
      POSTGRESQL_LOG_DISCONNECTIONS:        false
      POSTGRESQL_PGAUDIT_LOG_CATALOG:       off
      POSTGRESQL_CLIENT_MIN_MESSAGES:       error
      POSTGRESQL_SHARED_PRELOAD_LIBRARIES:  pgaudit
    Mounts:
      /bitnami/postgresql from data (rw)
      /dev/shm from dshm (rw)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-test-airbyte-postgresql-0
    ReadOnly:   false
  dshm:
    Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:      Memory
    SizeLimit:   <unset>
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>

**$ kubectl logs test-airbyte-airbyte-bootloader -n ns-0026-idl**
2022-08-09 20:42:22 INFO i.a.c.EnvConfigs(getEnvOrDefault):977 - Using default value for environment variable CONFIG_DATABASE_USER: 'airbyte'
2022-08-09 20:42:22 INFO i.a.c.EnvConfigs(getEnvOrDefault):977 - Using default value for environment variable CONFIG_DATABASE_PASSWORD: '*****'
2022-08-09 20:42:22 INFO i.a.c.EnvConfigs(getEnvOrDefault):977 - Using default value for environment variable CONFIG_DATABASE_URL: 'jdbc:postgresql://test-airbyte-postgresql:5432/db-airbyte'
2022-08-09 20:42:23 INFO c.z.h.HikariDataSource(<init>):80 - HikariPool-1 - Starting...
2022-08-09 20:42:23 INFO c.z.h.HikariDataSource(<init>):82 - HikariPool-1 - Start completed.
2022-08-09 20:42:23 INFO c.z.h.HikariDataSource(<init>):80 - HikariPool-2 - Starting...
2022-08-09 20:42:23 INFO c.z.h.HikariDataSource(<init>):82 - HikariPool-2 - Start completed.
2022-08-09 20:42:25 INFO i.a.c.EnvConfigs(getEnvOrDefault):977 - Using default value for environment variable SECRET_PERSISTENCE: 'TESTING_CONFIG_DB_TABLE'
Exception in thread "main" org.jooq.exception.DataAccessException: Error getting connection from data source HikariDataSource (HikariPool-1)
        at org.jooq_3.13.4.POSTGRES.debug(Unknown Source)
        at org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:86)
        at org.jooq.impl.DefaultExecuteContext.connection(DefaultExecuteContext.java:647)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:334)
        at org.jooq.impl.DefaultDSLContext.execute(DefaultDSLContext.java:1139)
        at io.airbyte.config.persistence.split_secrets.LocalTestingSecretPersistence.lambda$new$0(LocalTestingSecretPersistence.java:23)
        at io.airbyte.db.Database.query(Database.java:23)
        at io.airbyte.config.persistence.split_secrets.LocalTestingSecretPersistence.lambda$new$1(LocalTestingSecretPersistence.java:22)
        at io.airbyte.commons.lang.Exceptions.castCheckedToRuntime(Exceptions.java:54)
        at io.airbyte.commons.lang.Exceptions.toRuntime(Exceptions.java:41)
        at io.airbyte.config.persistence.split_secrets.LocalTestingSecretPersistence.<init>(LocalTestingSecretPersistence.java:21)
        at io.airbyte.config.persistence.split_secrets.SecretPersistence.getLongLived(SecretPersistence.java:29)
        at io.airbyte.bootloader.BootloaderApp.main(BootloaderApp.java:238)
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 60078ms.
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:181)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
        at org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:83)
        ... 11 more
Caused by: org.postgresql.util.PSQLException: Connection to test-airbyte-postgresql:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:319)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
        at org.postgresql.Driver.makeConnection(Driver.java:402)
        at org.postgresql.Driver.connect(Driver.java:261)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:733)
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:585)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:666)
        at org.postgresql.core.PGStream.createSocket(PGStream.java:241)
        at org.postgresql.core.PGStream.<init>(PGStream.java:98)
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:109)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235)
        ... 14 more

**Comment by xpuska513** [comment]
Here's your problem:
```
  Warning  FailedScheduling  <unknown>  fargate-scheduler  Pod not supported on Fargate: volumes not supported: data not supported because: PVC data-test-airbyte-postgresql-0 not bound

```

To fix that you'll need to create volume using EFS + create PersistentVolume and PersistentVolumeClaim
Here's stackoverflow answer that can guide you through that:
https://stackoverflow.com/a/63821328

Alternatively you can redeploy your EKS cluster and instead of Fargate backend use EC2

**Comment by xpuska513** [comment]
But I belive it'll block you from deploying anyways(since we're defining a volume by default), so probably will need to perform a little hotfix

**Comment by suman9730** [comment]
I had to create a new namespace tied with a ec2 nodegroup and it worked. Thanks so much for your help.
