### ISSUE TITLE
Mysql source connector stops abruptly after reading 2-3 lakh rows

### ISSUE THREAD

**Issue by yash-ghelani-dsw** [airbytehq/airbyte#15476]
Environment
Airbyte version: 0.39.36-alpha
OS Version / Instance: AWS EC2(Ubuntu 18.04)
Deployment: Docker
Source Connector and version: mysql (0.6.0)
Destination Connector and version: Postgres(0.3.21)
Step where error happened: Sync job 
Current Behavior: it shows error in the middle of sync job (after reading 2-3 lakh rows)
I am trying to trans
[logs-36.txt](https://github.com/airbytehq/airbyte/files/9293827/logs-36.txt)
fer data from mysql tp postgres. Have configured CDC on mysql as well .While transfer it shows error abruptly after  reading 3-4 lakh rows. The error file is attached below 

Logs

**Comment by marcosmarxm** [comment]
@yash-ghelani-dsw the log you shared doesn't contain any error. Could you check if you share the correct file?

**Comment by yash-ghelani-dsw** [comment]
> @yash-ghelani-dsw the log you shared doesn't contain any error. Could you check if you share the correct file?

It shows error after 4,82,000 data read:
Schema validation errors found for stream testmain_data. Error messages: [$._ab_cdc_deleted_at is of an incorrect type. Expected it to be string]
2022-08-09 18:14:25 [32mINFO[m

**Comment by marcosmarxm** [comment]
This is only a warning. Please post the complete file for debugging.

**Comment by yash-ghelani-dsw** [comment]
> This is only a warning. Please post the complete file for debugging.
This was the error shown on airbyte: 
Failure origin: Something went wrong during replication

[logs-37.txt](https://github.com/airbytehq/airbyte/files/9297666/logs-37.txt)

**Comment by marcosmarxm** [comment]
@yash-ghelani-dsw this is the reason of failure and it's not super clear. How much memory/disk you have in your EC2 instance?
```
2022-08-10 07:08:51 [1;31mERROR[m i.a.w.g.DefaultReplicationWorker(run):181 - Sync worker failed.
io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
	at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:136) ~[io.airbyte-airbyte-workers-0.39.41-alpha.jar:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:179) ~[io.airbyte-airbyte-workers-0.39.41-alpha.jar:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:65) ~[io.airbyte-airbyte-workers-0.39.41-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:155) ~[io.airbyte-airbyte-workers-0.39.41-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:1589) [?:?]
	Suppressed: java.io.IOException: Stream closed
		at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:445) ~[?:?]
		at java.io.OutputStream.write(OutputStream.java:164) ~[?:?]
		at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:125) ~[?:?]
		at java.io.BufferedOutputStream.implFlush(BufferedOutputStream.java:251) ~[?:?]
		at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:245) ~[?:?]
		at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:416) ~[?:?]
		at sun.nio.cs.StreamEncoder.lockedFlush(StreamEncoder.java:218) ~[?:?]
		at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:205) ~[?:?]
		at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:263) ~[?:?]
		at java.io.BufferedWriter.implFlush(BufferedWriter.java:372) ~[?:?]
		at java.io.BufferedWriter.flush(BufferedWriter.java:359) ~[?:?]
		at io.airbyte.workers.internal.DefaultAirbyteDestination.notifyEndOfInput(DefaultAirbyteDestination.java:98) ~[io.airbyte-airbyte-workers-0.39.41-alpha.jar:?]
		at io.airbyte.workers.internal.DefaultAirbyteDestination.close(DefaultAirbyteDestination.java:111) ~[io.airbyte-airbyte-workers-0.39.41-alpha.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:138) ~[io.airbyte-airbyte-workers-0.39.41-alpha.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:65) ~[io.airbyte-airbyte-workers-0.39.41-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:155) ~[io.airbyte-airbyte-workers-0.39.41-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:1589) [?:?]
```

**Comment by yash-ghelani-dsw** [comment]
> @yash-ghelani-dsw this is the reason of failure and it's not super clear. How much memory/disk you have in your EC2 instance?
> 
> ```
> 2022-08-10 07:08:51 �[1;31mERROR�[m i.a.w.g.DefaultReplicationWorker(run):181 - Sync worker failed.
> io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
> 	at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:136) ~[io.airbyte-airbyte-workers-0.39.41-alpha.jar:?]
> 	at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:179) ~[io.airbyte-airbyte-workers-0.39.41-alpha.jar:?]
> 	at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:65) ~[io.airbyte-airbyte-workers-0.39.41-alpha.jar:?]
> 	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:155) ~[io.airbyte-airbyte-workers-0.39.41-alpha.jar:?]
> 	at java.lang.Thread.run(Thread.java:1589) [?:?]
> 	Suppressed: java.io.IOException: Stream closed
> 		at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:445) ~[?:?]
> 		at java.io.OutputStream.write(OutputStream.java:164) ~[?:?]
> 		at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:125) ~[?:?]
> 		at java.io.BufferedOutputStream.implFlush(BufferedOutputStream.java:251) ~[?:?]
> 		at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:245) ~[?:?]
> 		at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:416) ~[?:?]
> 		at sun.nio.cs.StreamEncoder.lockedFlush(StreamEncoder.java:218) ~[?:?]
> 		at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:205) ~[?:?]
> 		at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:263) ~[?:?]
> 		at java.io.BufferedWriter.implFlush(BufferedWriter.java:372) ~[?:?]
> 		at java.io.BufferedWriter.flush(BufferedWriter.java:359) ~[?:?]
> 		at io.airbyte.workers.internal.DefaultAirbyteDestination.notifyEndOfInput(DefaultAirbyteDestination.java:98) ~[io.airbyte-airbyte-workers-0.39.41-alpha.jar:?]
> 		at io.airbyte.workers.internal.DefaultAirbyteDestination.close(DefaultAirbyteDestination.java:111) ~[io.airbyte-airbyte-workers-0.39.41-alpha.jar:?]
> 		at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:138) ~[io.airbyte-airbyte-workers-0.39.41-alpha.jar:?]
> 		at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:65) ~[io.airbyte-airbyte-workers-0.39.41-alpha.jar:?]
> 		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:155) ~[io.airbyte-airbyte-workers-0.39.41-alpha.jar:?]
> 		at java.lang.Thread.run(Thread.java:1589) [?:?]
> ```

I have 16gb ram and 100+ gb storage... but other databases and systems are also working on it. Do you feel error is due to lack of cpu and memory

**Comment by marcosmarxm** [comment]
It is possible @yash-ghelani-dsw could you check the Source database and see if its resources are Ok and no error is throw when reading it? Also if it's possible to increase the memory to test the sync would be nice.

**Comment by yash-ghelani-dsw** [comment]
> It is possible @yash-ghelani-dsw could you check the Source database and see if its resources are Ok and no error is throw when reading it? Also if it's possible to increase the memory to test the sync would be nice.

Hi, Issue was related to low resource on Mysql. After increasing the resource it is working well. Thanks
