### ISSUE TITLE
Source Braintree: connection fails to sync subscription and transaction streams

### ISSUE THREAD

**Issue by jan-benisek** [airbytehq/airbyte#15547]
## Environment
- **Airbyte version**:  0.39.35-alpha
- **OS Version / Instance**: -
- **Deployment**: EKS
- **Source Connector and version**: Braintree 0.1.3
- **Destination Connector and version**: s3 0.3.13
- **Step where error happened**:Sync job 

## Current Behavior
- Some data are synced: `customer_stream`, `discount_stream`, `dispute_stream`, `merchant_account_stream`, `plan_stream`
- then it fails, when syncing `subscription_stream` and `transaction_stream`

## Expected Behavior
- Sync should work

## Logs

![image](https://user-images.githubusercontent.com/91880749/184131348-07c2c1fd-5864-476f-8a94-78a244cce4bc.png)

- I think these are the relevant logs for `subscription_stream`:
```
2022-08-11 07:33:51 [44msource[0m > Syncing stream: subscription_stream 
2022-08-11 07:33:54 [44msource[0m > Encountered an exception while reading stream SourceBraintree
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 108, in read
    internal_config=internal_config,
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 141, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 185, in _read_incremental
    for record_counter, record_data in enumerate(records, start=1):
  File "/airbyte/integration_code/source_braintree/streams.py", line 123, in read_records
    yield from self._collect_items(stream_slice)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/airbyte/integration_code/source_braintree/streams.py", line 112, in _collect_items
    item = self.model(**item)
  File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 6 validation errors for Subscription
billing_period_start_date
  invalid type; expected datetime, string, bytes, int or float (type=type_error)
first_billing_date
  invalid type; expected datetime, string, bytes, int or float (type=type_error)
next_billing_date
  invalid type; expected datetime, string, bytes, int or float (type=type_error)
paid_through_date
  invalid type; expected datetime, string, bytes, int or float (type=type_error)
transactions -> 0 -> subscription_details -> billing_period_end_date
  invalid type; expected datetime, string, bytes, int or float (type=type_error)
transactions -> 0 -> subscription_details -> billing_period_start_date
  invalid type; expected datetime, string, bytes, int or float (type=type_error)
```

- and just now I saw the same for `transaction_stream` (not in the log attached below)
```
subscription_details -> billing_period_end_date
  invalid type; expected datetime, string, bytes, int or float (type=type_error)
subscription_details -> billing_period_start_date
  invalid type; expected datetime, string, bytes, int or float (type=type_error)
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 116, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 107, in run
    for message in generator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 112, in read
    raise e
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 108, in read
    internal_config=internal_config,
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 141, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 185, in _read_incremental
    for record_counter, record_data in enumerate(records, start=1):
  File "/airbyte/integration_code/source_braintree/streams.py", line 123, in read_records
    yield from self._collect_items(stream_slice)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/airbyte/integration_code/source_braintree/streams.py", line 112, in _collect_items
    item = self.model(**item)
  File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for Transaction
subscription_details -> billing_period_end_date
  invalid type; expected datetime, string, bytes, int or float (type=type_error)
subscription_details -> billing_period_start_date
  invalid type; expected datetime, string, bytes, int or float (type=type_error)
```

[logs-2239.txt](https://github.com/airbytehq/airbyte/files/9308482/logs-2239.txt)

## Steps to Reproduce
1. Set up source -> Braintree
![Screenshot 2022-08-11 at 14 15 25](https://user-images.githubusercontent.com/91880749/184131192-c80be245-5253-45e4-abde-efcb031eb25e.png)

3. Set up destination -> s3
![Screenshot 2022-08-11 at 14 14 07](https://user-images.githubusercontent.com/91880749/184131048-82e08c7c-3432-4b2d-9a9e-2f13beb1d955.png)

4. Create connection
![image](https://user-images.githubusercontent.com/91880749/184131300-f8bfd57a-6412-41fb-a77f-b15f98afb82f.png)

## Are you willing to submit a PR?
- if it is something I can easily fix?

**Comment by jan-benisek** [comment]
Hi, any update on this issue? Thank you 🙏

**Comment by sajarin** [comment]
@jan-benisek sorry for the delay, it's been in my backlog. I'll have an update for you by the end of this week! Thanks for being patient.

**Comment by sajarin** [comment]
Hey @jan-benisek, again sorry for the delay with this. I think we can get this issue resolved near the beginning of November.

**Comment by jan-benisek** [comment]
Hello @sajarin any update on this? The issue is still persists :/ .

**Comment by sajarin** [comment]
Hey @jan-benisek I actually tried replicating this but couldn't reproduce the error. The sync on my end passes with records from both streams emitting correctly. Are you on the latest Airbyte version?

**Comment by jan-benisek** [comment]
@sajarin We are on 0.40.23, Braintree 0.1.13.

**Comment by jan-benisek** [comment]
```bash
```

**Comment by rstml** [comment]
In the latest version 0.2.0, similar problem with the transaction stream still exists:

```
pydantic.error_wrappers.ValidationError: 2 validation errors for Transaction
subscription_details -> billing_period_end_date
  invalid type; expected datetime, string, bytes, int or float (type=type_error)
subscription_details -> billing_period_start_date
  invalid type; expected datetime, string, bytes, int or float (type=type_error)
```

subscription stream works fine though, at least in my sandbox.

Any idea how to fix this?
