### ISSUE TITLE
Source Amazon Ads: `Asins reports not available to Vendors`

### ISSUE THREAD

**Issue by animer3009** [airbytehq/airbyte#15571]
## Environment
- **Airbyte version**:  0.40.0-alpha
- **OS Version / Instance**:  Ubuntu 22.04, GCP
- **Deployment**: Docker 
- **Source Connector and version**: Amazon Ads 0.1.12
- **Destination Connector and version**: BigQuery 1.1.14
- **Step where error happened**: Amazon Ad Source Connector Issues

## Current Behavior
So we are facing two issues on time using Amazon Ad Source Connector.
1) For the different Regions (EU/NA/FE) we are getting exactly the same profiles. Looks like endpoints are the same for all regions.
2) ERROR on time Report Stream processing:
2022-08-11 09:13:20 - Additional Failure Information: Unexpected HTTP status code 400 when registering asins, SponsoredDisplayReportStream for XXXXXXXX profile: {"code":"400","details":"Asins reports not available to Vendors","requestId":"3G6E4X14MVNCZDNRBK5D"}

Looks like amazon does not support a Asins reports for vendors accounts and Airbyte doesn't skip it. So the full process breaks cuz some profileIds.

**Comment by animer3009** [comment]
I guess the first issue I am facing because:
airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/source.py

config["region"] = AmazonAdsRegion.NA

**Comment by animer3009** [comment]
@sajarin Sorry you saw my last message?

**Comment by sajarin** [comment]
Hey @animer3009, just seeing this. I'll try to take a look at this, the second issue looks like it'll take some more time to investigate. Thanks for the issue!

**Comment by animer3009** [comment]
@sajarin Thank you!
Today we got connector upgrade. 
Looks like report_streams.py issue was solved. I am testing it right now.
But region issue is still exists.
Please help solve it ASAP as it is very important for us :)

**Comment by animer3009** [comment]
Nope,
2022-08-16 18:58:53 - Additional Failure Information: Unexpected HTTP status code 400 when registering asins, SponsoredDisplayReportStream for 950741992331827 profile: {"code":"400","details":"Asins reports not available to Vendors","requestId":"KVKXMZ9EGXMFRE9NDFE3"}
Same error :)

**Comment by animer3009** [comment]
@sajarin 
I tried removing vendor profiles using Profile Id filter.
But now it is getting another error for Sponsored Product Report Stream:

Failure Origin: source, Message: Something went wrong in the connector. See the logs for more details.

`	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	... 1 more
Caused by: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
	at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:136) ~[io.airbyte-airbyte-workers-0.40.0-alpha.jar:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$getReplicationRunnable$6(DefaultReplicationWorker.java:334) ~[io.airbyte-airbyte-workers-0.40.0-alpha.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	... 1 more
2022-08-18 19:12:11 INFO i.a.w.g.DefaultReplicationWorker(run):243 - sync summary: io.airbyte.config.ReplicationAttemptSummary@cfce71d[status=failed,recordsSynced=0,bytesSynced=0,startTime=1660849611138,endTime=1660849931128,totalStats=io.airbyte.config.SyncStats@66cd1a9c[recordsEmitted=0,bytesEmitted=0,stateMessagesEmitted=0,recordsCommitted=0],streamStats=[]]
2022-08-18 19:12:11 INFO i.a.w.g.DefaultReplicationWorker(run):272 - Source did not output any state messages`

**Comment by grubberr** [comment]
@animer3009 
We tries to improve quality of this connector
for last month it was greatly improved but still not fully. 

I want to double check with you
all this problems still actual for you?

I am especially curious about this problem **Asins reports not available to Vendors** what stream you synced to receive  this problem?

**Comment by grubberr** [comment]
@animer3009 
it's very strange
that you got that error
because Asins reports not generated for to profile types "vendor"

https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/streams/report_streams/display_report.py#L186

**Comment by grubberr** [comment]
No response from customer
I cannot reproduce all this problems in current version of connector `source-amazon-ads:0.1.20`
I am closing this issue
Can be re-opened in future if customer provide some proofs in the future.

**Comment by animer3009** [comment]
Hi @grubberr ,
Sorry for the late response.
Hard to answer your question, cuz after this ticket we got multiple connector updates.
About 10-15 days ago we were still experiencing this issue.
After I changed data architecture. I made source connectors for "report streams" and excluded vendor profiles using Profile IDs filter.
So with this action I technically avoid this issue. So I am not sure if it still exists. But as I mentioned, a few days ago we were still facing this one.

**Comment by grubberr** [comment]
@animer3009 
For us are important logs with this problem
if you would be able to provide fresh logs with this problem
it would be good :)

**Comment by animer3009** [comment]
@grubberr I just tested and working good for now.
I am going test different stuff and keep you updated.

**Comment by animer3009** [comment]
@grubberr 
I noticed one issue.
We have FE profiles but Amazon ads 0.1.20 is not returning any data (including profiles).
NA and EU looks good.
Can you look at that?
