### ISSUE TITLE
MySQL destination connector not working with MariaDB after bugfix

### ISSUE THREAD

**Issue by persunde** [airbytehq/airbyte#15589]
## Environment
- **Airbyte version**:  0.39.37-alpha
- **OS Version / Instance**: Ubuntu 22.04
- **Deployment**: Docker
- **Destination Connector and version**: MySQL, any version
- **Step where error happened**: Normalize

Bug(?) / Error introduced by this commit
https://github.com/airbytehq/airbyte/commit/ddc065e9ce7dc3c616d67e6e4ea9587f0b934720
For this file:
https://github.com/airbytehq/airbyte/blob/ddc065e9ce7dc3c616d67e6e4ea9587f0b934720/airbyte-integrations/bases/base-normalization/dbt-project-template/macros/cross_db_utils/json_operations.sql

## Current Behavior
I use the MySQL destination connector to send data to a MariaDB.
MariaDB is supposed to be 100% compatible with MySQL, but there are some minor differences.
The function `json_value` does NOT support options in MariaDB, but is optional in MySQL.

In the file `airbyte-integrations/bases/base-normalization/dbt-project-template/macros/cross_db_utils/json_operations.sql`
It uses this function for normalizing data for MySQL:
```
json_value({{ json_column }}, {{ format_json_path(normalized_json_path) }} RETURNING CHAR)
```

It does not work for MariaDB. To make it work with MariaDB, it would have to be reverted to how the code was before
```
json_value({{ json_column }}, {{ format_json_path(normalized_json_path) }})
```

See here for commit that broke compatibility with MariaDB.
https://github.com/airbytehq/airbyte/commit/ddc065e9ce7dc3c616d67e6e4ea9587f0b934720

The official MariaDB and MySQL docs:
https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#function_json-value
```
JSON_VALUE(json_doc, path [RETURNING type] [on_empty] [on_error])
```
https://mariadb.com/kb/en/json_value/
```
JSON_VALUE(json_doc, path)
```

MySQL supports optional arguments in the JSON_VALUE() function, but MariaDB does not.

## Expected Behavior
I expected MySQL connector to be compatible with MariaDB. Instead it fails in the normalization process.

## Logs
```
2022-08-12 05:22:04 [42mnormalization[0m > 05:22:00.197130 [debug] [Thread-1  ]: mysql adapter: MySQL error: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'RETURNING CHAR) as id,
2022-08-12 05:22:04 [42mnormalization[0m >     json_value(_airbyte_data, 
2022-08-12 05:22:04 [42mnormalization[0m >     '$."adid"' RETURNIN...' at line 14
2022-08-12 05:22:04 [42mnormalization[0m > 05:22:00.197312 [debug] [Thread-1  ]: On model.airbyte_utils.ad_prod_cnc: ROLLBACK
2022-08-12 05:22:04 [42mnormalization[0m > 05:22:00.199191 [debug] [Thread-1  ]: finished collecting timing info
2022-08-12 05:22:04 [42mnormalization[0m > 05:22:00.199383 [debug] [Thread-1  ]: On model.airbyte_utils.ad_prod_cnc: Close
2022-08-12 05:22:04 [42mnormalization[0m > 05:22:00.199906 [debug] [Thread-1  ]: Database Error in model ad_prod_cnc (models/generated/airbyte_tables/test01/ad_prod_cnc.sql)
2022-08-12 05:22:04 [42mnormalization[0m >   1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'RETURNING CHAR) as id,
2022-08-12 05:22:04 [42mnormalization[0m >       json_value(_airbyte_data, 
2022-08-12 05:22:04 [42mnormalization[0m >       '$."adid"' RETURNIN...' at line 14
2022-08-12 05:22:04 [42mnormalization[0m >   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/test01/ad_prod_cnc.sql
2022-08-12 05:22:04 [42mnormalization[0m > 05:22:00.200549 [error] [Thread-1  ]: 1 of 1 ERROR creating table model test01.ad_prod_cnc.................................................................... [[31mERROR[0m in 0.11s]
2022-08-12 05:22:04 [42mnormalization[0m > 05:22:00.201165 [debug] [Thread-1  ]: Finished running node model.airbyte_utils.ad_prod_cnc
2022-08-12 05:22:04 [42mnormalization[0m > 05:22:00.202785 [debug] [MainThread]: Acquiring new mysql connection "master"
2022-08-12 05:22:04 [42mnormalization[0m > 05:22:00.202995 [debug] [MainThread]: Using mysql connection "master"
2022-08-12 05:22:04 [42mnormalization[0m > 05:22:00.203151 [debug] [MainThread]: On master: BEGIN
2022-08-12 05:22:04 [42mnormalization[0m > 05:22:00.203320 [debug] [MainThread]: Opening a new connection, currently in state closed
2022-08-12 05:22:04 [42mnormalization[0m > 05:22:00.230991 [debug] [MainThread]: SQL status: SUCCESS 0 in 0.03 seconds
2022-08-12 05:22:04 [42mnormalization[0m > 05:22:00.231281 [debug] [MainThread]: On master: COMMIT
2022-08-12 05:22:04 [42mnormalization[0m > 05:22:00.231442 [debug] [MainThread]: Using mysql connection "master"
2022-08-12 05:22:04 [42mnormalization[0m > 05:22:00.231597 [debug] [MainThread]: On master: COMMIT
2022-08-12 05:22:04 [42mnormalization[0m > 05:22:00.234180 [debug] [MainThread]: SQL status: SUCCESS 0 in 0.0 seconds
2022-08-12 05:22:04 [42mnormalization[0m > 05:22:00.234383 [debug] [MainThread]: On master: Close
2022-08-12 05:22:04 [42mnormalization[0m > 05:22:00.234981 [info ] [MainThread]: 
2022-08-12 05:22:04 [42mnormalization[0m > 05:22:00.235335 [info ] [MainThread]: Finished running 1 table model in 0.48s.
2022-08-12 05:22:04 [42mnormalization[0m > 05:22:00.236011 [debug] [MainThread]: Connection 'master' was properly closed.
2022-08-12 05:22:04 [42mnormalization[0m > 05:22:00.236254 [debug] [MainThread]: Connection 'model.airbyte_utils.ad_prod_cnc' was properly closed.
2022-08-12 05:22:04 [42mnormalization[0m > 05:22:00.251772 [info ] [MainThread]: 
2022-08-12 05:22:04 [42mnormalization[0m > 05:22:00.252205 [info ] [MainThread]: [31mCompleted with 1 error and 0 warnings:[0m
2022-08-12 05:22:04 [42mnormalization[0m > 05:22:00.252756 [info ] [MainThread]: 
2022-08-12 05:22:04 [42mnormalization[0m > 05:22:00.253372 [error] [MainThread]: [33mDatabase Error in model ad_prod_cnc (models/generated/airbyte_tables/test01/ad_prod_cnc.sql)[0m
2022-08-12 05:22:04 [42mnormalization[0m > 05:22:00.254029 [error] [MainThread]:   1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'RETURNING CHAR) as id,
2022-08-12 05:22:04 [42mnormalization[0m > 05:22:00.254483 [error] [MainThread]:       json_value(_airbyte_data, 
2022-08-12 05:22:04 [42mnormalization[0m > 05:22:00.254937 [error] [MainThread]:       '$."adid"' RETURNIN...' at line 14
2022-08-12 05:22:04 [42mnormalization[0m > 05:22:00.255360 [error] [MainThread]:   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/test01/ad_prod_cnc.sql
2022-08-12 05:22:04 [42mnormalization[0m > 05:22:00.255813 [info ] [MainThread]: 
2022-08-12 05:22:04 [42mnormalization[0m > 05:22:00.256250 [info ] [MainThread]: Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
2022-08-12 05:22:04 [32mINFO[m i.a.w.t.TemporalAttemptExecution(lambda$getWorkerThread$2):161 - Completing future exceptionally...
io.airbyte.workers.exception.WorkerException: Normalization Failed.
	at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:63) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
	at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:21) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:158) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: io.airbyte.workers.exception.WorkerException: Normalization Failed.
	at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:60) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
	... 3 more
	Suppressed: io.airbyte.workers.exception.WorkerException: Normalization process wasn't successful
		at io.airbyte.workers.normalization.DefaultNormalizationRunner.close(DefaultNormalizationRunner.java:162) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
		at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:48) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
		at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:21) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:158) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:833) [?:?]
2022-08-12 05:22:04 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):134 - Stopping cancellation check scheduling...
2022-08-12 05:22:04 [32mINFO[m i.a.w.t.TemporalUtils(withBackgroundHeartbeat):291 - Stopping temporal heartbeating...
2022-08-12 05:22:04 [33mWARN[m i.t.i.a.POJOActivityTaskHandler(activityFailureToResult):307 - Activity failure. ActivityId=ab6ecf95-432c-3eb9-a15f-ee4fcf36c2f5, activityType=Normalize, attempt=1
java.lang.RuntimeException: io.temporal.serviceclient.CheckedExceptionWrapper: java.util.concurrent.ExecutionException: io.airbyte.workers.exception.WorkerException: Normalization Failed.
	at io.airbyte.workers.temporal.TemporalUtils.withBackgroundHeartbeat(TemporalUtils.java:289) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
	at io.airbyte.workers.temporal.sync.NormalizationActivityImpl.normalize(NormalizationActivityImpl.java:75) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor422.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at io.temporal.internal.activity.POJOActivityTaskHandler$POJOActivityInboundCallsInterceptor.execute(POJOActivityTaskHandler.java:214) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.activity.POJOActivityTaskHandler$POJOActivityImplementation.execute(POJOActivityTaskHandler.java:180) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.activity.POJOActivityTaskHandler.handle(POJOActivityTaskHandler.java:120) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:204) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:164) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93) ~[temporal-sdk-1.8.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: io.temporal.serviceclient.CheckedExceptionWrapper: java.util.concurrent.ExecutionException: io.airbyte.workers.exception.WorkerException: Normalization Failed.
	at io.temporal.serviceclient.CheckedExceptionWrapper.wrap(CheckedExceptionWrapper.java:56) ~[temporal-serviceclient-1.8.1.jar:?]
	at io.temporal.internal.sync.WorkflowInternal.wrap(WorkflowInternal.java:448) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.activity.Activity.wrap(Activity.java:51) ~[temporal-sdk-1.8.1.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:138) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
	at io.airbyte.workers.temporal.sync.NormalizationActivityImpl.lambda$normalize$3(NormalizationActivityImpl.java:103) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalUtils.withBackgroundHeartbeat(TemporalUtils.java:284) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
	... 13 more
Caused by: java.util.concurrent.ExecutionException: io.airbyte.workers.exception.WorkerException: Normalization Failed.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:132) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
	at io.airbyte.workers.temporal.sync.NormalizationActivityImpl.lambda$normalize$3(NormalizationActivityImpl.java:103) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalUtils.withBackgroundHeartbeat(TemporalUtils.java:284) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
	... 13 more
Caused by: io.airbyte.workers.exception.WorkerException: Normalization Failed.
	at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:63) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
	at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:21) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:158) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
	... 1 more
Caused by: io.airbyte.workers.exception.WorkerException: Normalization Failed.
	at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:60) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
	at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:21) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:158) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
	... 1 more
	Suppressed: io.airbyte.workers.exception.WorkerException: Normalization process wasn't successful
		at io.airbyte.workers.normalization.DefaultNormalizationRunner.close(DefaultNormalizationRunner.java:162) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
		at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:48) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
		at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:21) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:158) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
```

## Steps to Reproduce
0. Create a MariaDB v10.5.X
1. Use Airbyte 0.39.37-alpha
2. Setup a Postgres Source
3. Setup a MySQL Destination, but use a MariaDB database
4. Setup a Connection from (any or Postgres) Source to the MariaDB connection
5. Enable normalization
6. The normalization process will fail

Can you please add a MariaDB destination where some of the minor differences are fixed? Since it seems that the MySQL json_value function was changed to fix some bugs in MySQL, but that caused it to not work with MariaDB.

**Comment by persunde** [comment]
Also, after reverting to the old version where MariaDB worked, it now does not handle 'null' values correctly.
I have a numeric column (float) that has null values, but when it does the normalization, it tries to cast the string "null" to a float/numeric value and fails.

I think the best is to have its own MariaDB Connector that fixes these issues caused by these minor differences between MariaDB and MySQL.

**Comment by sajarin** [comment]
@persunde, are you open to writing this connector for MariaDB? If not we can create a new issue for a MariaDB connector.

**Comment by persunde** [comment]
@sajarin No, I will not write a MariaDB connector.
I can maybe contribute in the future, but not now.

**Comment by cmuc24** [comment]
In the meantime, please consider adding something like  "mariaDB is not yet supported" to the "mysql" Destination
 ....could save hours ....

user(s) will thanks in advance

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 365 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.
