### ISSUE TITLE
Out of Memory when replicating large table from MySQL

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#1582]
## Expected Behavior
A user (Vivek D) trying Airbyte out reported running into Out of Memory error when running a full refresh from MySQL source for an essentially large table with around 40M records to Snowflake destination.

The setup is using a private linux machine with 8G of RAM and seems to be able to replicate at least 10 batches of 500 records before crashing.

## Current Behavior

```
2021-01-07 07:45:45 INFO (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 2021-01-07 07:45:45 [32mINFO[m i.a.i.d.s.SnowflakeDestination$DestinationImpl(insertBufferedRecords):166 - {} - actual size of batch: 500
2021-01-07 07:45:48 INFO (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 2021-01-07 07:45:48 [32mINFO[m i.a.i.d.s.SnowflakeDestination$DestinationImpl(insertBufferedRecords):165 - {} - max size of batch: 500
2021-01-07 07:45:48 INFO (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 2021-01-07 07:45:48 [32mINFO[m i.a.i.d.s.SnowflakeDestination$DestinationImpl(insertBufferedRecords):166 - {} - actual size of batch: 500
2021-01-07 07:45:50 INFO (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 2021-01-07 07:45:50 [32mINFO[m i.a.i.d.s.SnowflakeDestination$DestinationImpl(insertBufferedRecords):165 - {} - max size of batch: 500
2021-01-07 07:45:50 INFO (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 2021-01-07 07:45:50 [32mINFO[m i.a.i.d.s.SnowflakeDestination$DestinationImpl(insertBufferedRecords):166 - {} - actual size of batch: 500
2021-01-07 07:45:53 INFO (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 2021-01-07 07:45:53 [32mINFO[m i.a.i.d.s.SnowflakeDestination$DestinationImpl(insertBufferedRecords):165 - {} - max size of batch: 500
2021-01-07 07:45:53 INFO (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 2021-01-07 07:45:53 [32mINFO[m i.a.i.d.s.SnowflakeDestination$DestinationImpl(insertBufferedRecords):166 - {} - actual size of batch: 500
2021-01-07 07:45:56 INFO (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 2021-01-07 07:45:56 [32mINFO[m i.a.i.d.s.SnowflakeDestination$DestinationImpl(insertBufferedRecords):165 - {} - max size of batch: 500
2021-01-07 07:45:56 INFO (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 2021-01-07 07:45:56 [32mINFO[m i.a.i.d.s.SnowflakeDestination$DestinationImpl(insertBufferedRecords):166 - {} - actual size of batch: 500
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 	at com.mysql.cj.protocol.a.TextRowFactory.createFromMessage(TextRowFactory.java:72)
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 	at com.mysql.cj.protocol.a.TextRowFactory.createFromMessage(TextRowFactory.java:42)
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 	at com.mysql.cj.protocol.a.ResultsetRowReader.read(ResultsetRowReader.java:87)
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 	at com.mysql.cj.protocol.a.ResultsetRowReader.read(ResultsetRowReader.java:42)
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 	at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1583)
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 	at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:87)
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 	at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:48)
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 	at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1596)
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 	at com.mysql.cj.protocol.a.NativeProtocol.readAllResults(NativeProtocol.java:1650)
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 	at com.mysql.cj.protocol.a.NativeProtocol.convertShowWarningsToSQLWarnings(NativeProtocol.java:2104)
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 	at com.mysql.cj.jdbc.StatementImpl.getWarnings(StatementImpl.java:1733)
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 	at org.apache.commons.dbcp2.DelegatingStatement.getWarnings(DelegatingStatement.java:621)
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 	at org.apache.commons.dbcp2.DelegatingStatement.getWarnings(DelegatingStatement.java:621)
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 	at org.jooq.tools.jdbc.DefaultStatement.getWarnings(DefaultStatement.java:201)
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 	at org.jooq.impl.Tools.consumeWarnings(Tools.java:3891)
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 	at org.jooq.impl.Tools.safeClose(Tools.java:2782)
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 	at org.jooq.impl.Tools.safeClose(Tools.java:2769)
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:393)
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:502)
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:471)
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 	at org.jooq.impl.AbstractResultQuery.lambda$fetchStream$1(AbstractResultQuery.java:442)
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 	at org.jooq.impl.AbstractResultQuery$$Lambda$161/0x0000000800e0f840.apply(Unknown Source)
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
2021-01-07 07:46:25 ERROR (/tmp/workspace/6/0) LineGobbler(voidCall):69 - 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
```

## Severity of the bug for you
High

**Comment by cgardens** [comment]
@sherifnada for visibility

**Comment by opumm** [comment]
This issue happens with PostgreSQL as well.

And not only with a full refresh but also happens with incremental load.

**Comment by cgardens** [comment]
@opumm thanks for reporting. we are looking into it.

**Comment by cgardens** [comment]
@opumm is your issue also when writing to snowflake?

**Comment by opumm** [comment]
@cgardens No, RedShift

**Comment by cgardens** [comment]
I will spend some time looking into this issue this afternoon.

**Comment by cgardens** [comment]
I have _not_ been able to reproduce for full refresh. but i _have_ reproduced for incremental. 🤪

**Comment by cgardens** [comment]
Can reliably recreate now using our stress test harness. This is good because it is easy to iterate on this. The stress test previously only tests full refresh assuming it would always be as bad or worse than incremental. It appears that there is something in how the jdbc driver treats these queries however that is causing a problem. Digging in.

**Comment by cgardens** [comment]
I believe the issue is actually a memory leak in the `StateDecoratingIterator` that we use to keep track of the cursor for incremental. I can tell because when there is no state, the initial query that incremental and full refresh make are the same. Have sanity checked this. But what we see is when full refresh runs this query it has no memory issues and when incremental does it fails. Base on initial testing it seems `StateDecoratingIterator` resolves the issue. Investigating what in there is causing the problem.

**Comment by cgardens** [comment]
I have identified the issue as an issue where we convert from stream => iterator => stream. It is not in fact a memory leak in the `StateDecoratingIterator`. Put up a PR: https://github.com/airbytehq/airbyte/pull/1647 with a "fix". 

I'm not going to try to merge it yet because the solution is a pretty awful hack and I don't yet fully understand why this conversion is causing an OOM. Going to spend time tomorrow:
1. better understanding why this conversion isn't work 
2. push a fix that isn't such an awful hack.

**Comment by cgardens** [comment]
I have found a decent solution to the problem and have a PR up for it now. I plan to merge it today. The PR does a pretty in-depth explanation of the problem and solution so I will not repeat it here. Please refer to the PR if you are interested (a kinda goofy nuance of java `flatMap` was involved).

PR: https://github.com/airbytehq/airbyte/pull/1655
