### ISSUE TITLE
Sync worker failed 

### ISSUE THREAD

**Issue by st0302** [airbytehq/airbyte#15941]
## Environment
- **Airbyte version**:  0.40.1
- **OS Version / Instance**: centos7.6
- **Deployment**: Docker 
- **Source Connector and version**: mysql5.7
- **Destination Connector and version**: clickhouse 22.8.2.11
- **Step where error happened**: Sync job 

## Current Behavior
Sync worker failed.

## Expected Behavior
sync finish

## Logs
2022-08-25 02:01:56 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$getReplicationRunnable$6):333 - Records read: 162000 (12 MB)
2022-08-25 02:01:57 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$getReplicationRunnable$6):333 - Records read: 163000 (12 MB)
2022-08-25 02:01:57 [43mdestination[0m > 2022-08-25 02:01:57 [32mINFO[m i.a.i.d.r.InMemoryRecordBufferingStrategy(flushAll):84 - Flushing dept_emp: 80336 records (24 MB)
2022-08-25 02:01:57 [43mdestination[0m > 2022-08-25 02:01:57 [32mINFO[m i.a.i.d.c.ClickhouseSqlOperations(insertRecordsInternal):67 - actual size of batch: 80336
2022-08-25 02:02:03 [32mINFO[m i.a.w.g.DefaultReplicationWorker(cancel):461 - Cancelling destination...
2022-08-25 02:02:03 [32mINFO[m i.a.w.i.DefaultAirbyteDestination(cancel):125 - Attempting to cancel destination process...
2022-08-25 02:02:03 [32mINFO[m i.a.w.i.DefaultAirbyteDestination(cancel):130 - Destination process exists, cancelling...
2022-08-25 02:02:05 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):178 - One of source or destination thread complete. Waiting on the other.
2022-08-25 02:02:05 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):180 - Source and destination threads complete.
2022-08-25 02:02:05 [32mINFO[m i.a.w.i.DefaultAirbyteDestination(cancel):132 - Cancelled destination process!
2022-08-25 02:02:05 [32mINFO[m i.a.w.g.DefaultReplicationWorker(cancel):468 - Cancelling source...
2022-08-25 02:02:05 [32mINFO[m i.a.w.i.DefaultAirbyteSource(cancel):142 - Attempting to cancel source process...
2022-08-25 02:02:05 [32mINFO[m i.a.w.i.DefaultAirbyteSource(cancel):147 - Source process exists, cancelling...
2022-08-25 02:02:05 [33mWARN[m i.a.c.i.LineGobbler(voidCall):88 - airbyte-source gobbler IOException: Stream closed. Typically happens when cancelling a job.
2022-08-25 02:02:05 [32mINFO[m i.a.w.i.DefaultAirbyteSource(cancel):149 - Cancelled source process!
2022-08-25 02:02:05 [32mINFO[m i.a.w.t.TemporalAttemptExecution(lambda$getCancellationChecker$3):195 - Interrupting worker thread...
2022-08-25 02:02:05 [32mINFO[m i.a.w.t.TemporalAttemptExecution(lambda$getCancellationChecker$3):198 - Cancelling completable future...
2022-08-25 02:02:05 [33mWARN[m i.a.w.t.CancellationHandler$TemporalCancellationHandler(checkAndHandleCancellation):53 - Job either timed out or was cancelled.
2022-08-25 02:02:05 [33mWARN[m i.a.w.t.CancellationHandler$TemporalCancellationHandler(checkAndHandleCancellation):53 - Job either timed out or was cancelled.
2022-08-25 02:02:05 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):131 - Stopping cancellation check scheduling...
2022-08-25 02:02:05 [32mINFO[m i.a.w.t.TemporalUtils(withBackgroundHeartbeat):312 - Stopping temporal heartbeating...
2022-08-25 02:02:05 [1;31mERROR[m i.a.w.g.DefaultReplicationWorker(run):184 - Sync worker failed.
io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
	at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:136) ~[io.airbyte-airbyte-workers-0.40.1.jar:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:182) ~[io.airbyte-airbyte-workers-0.40.1.jar:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:65) ~[io.airbyte-airbyte-workers-0.40.1.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:155) ~[io.airbyte-airbyte-workers-0.40.1.jar:?]
	at java.lang.Thread.run(Thread.java:1589) [?:?]
	Suppressed: java.io.IOException: Stream closed
		at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:445) ~[?:?]
		at java.io.OutputStream.write(OutputStream.java:164) ~[?:?]
		at java.io.BufferedOutputStream.implWrite(BufferedOutputStream.java:216) ~[?:?]
		at java.io.BufferedOutputStream.write(BufferedOutputStream.java:205) ~[?:?]
		at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:313) ~[?:?]
		at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:409) ~[?:?]
		at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:414) ~[?:?]
		at sun.nio.cs.StreamEncoder.lockedFlush(StreamEncoder.java:218) ~[?:?]
		at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:205) ~[?:?]
		at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:263) ~[?:?]
		at java.io.BufferedWriter.implFlush(BufferedWriter.java:372) ~[?:?]
		at java.io.BufferedWriter.flush(BufferedWriter.java:359) ~[?:?]
		at io.airbyte.workers.internal.DefaultAirbyteDestination.notifyEndOfInput(DefaultAirbyteDestination.java:98) ~[io.airbyte-airbyte-workers-0.40.1.jar:?]
		at io.airbyte.workers.internal.DefaultAirbyteDestination.close(DefaultAirbyteDestination.java:111) ~[io.airbyte-airbyte-workers-0.40.1.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:141) ~[io.airbyte-airbyte-workers-0.40.1.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:65) ~[io.airbyte-airbyte-workers-0.40.1.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:155) ~[io.airbyte-airbyte-workers-0.40.1.jar:?]
		at java.lang.Thread.run(Thread.java:1589) [?:?]
2022-08-25 02:02:05 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):247 - sync summary: io.airbyte.config.ReplicationAttemptSummary@75c2df87[status=cancelled,recordsSynced=163631,bytesSynced=13318273,startTime=1661392748631,endTime=1661392925725,totalStats=io.airbyte.config.SyncStats@594c30af[recordsEmitted=163631,bytesEmitted=13318273,sourceStateMessagesEmitted=0,destinationStateMessagesEmitted=0,recordsCommitted=0,meanSecondsBeforeSourceStateMessageEmitted=0,maxSecondsBeforeSourceStateMessageEmitted=0,additionalProperties={}],streamStats=[io.airbyte.config.StreamSyncStats@7e18e2e5[streamName=dept_emp,stats=io.airbyte.config.SyncStats@2ec3bb60[recordsEmitted=163631,bytesEmitted=13318273,sourceStateMessagesEmitted=<null>,destinationStateMessagesEmitted=<null>,recordsCommitted=<null>,meanSecondsBeforeSourceStateMessageEmitted=<null>,maxSecondsBeforeSourceStateMessageEmitted=<null>,additionalProperties={}]]]]
2022-08-25 02:02:05 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):276 - Source did not output any state messages
2022-08-25 02:02:05 [33mWARN[m i.a.w.g.DefaultReplicationWorker(run):287 - State capture: No state retained.
2022-08-25 02:02:05 [33mWARN[m i.t.i.a.POJOActivityTaskHandler(activityFailureToResult):307 - Activity failure. ActivityId=5f24e915-4f98-371f-b590-4356ac152089, activityType=Replicate, attempt=1
java.lang.RuntimeException: java.util.concurrent.CancellationException
	at io.airbyte.workers.temporal.TemporalUtils.withBackgroundHeartbeat(TemporalUtils.java:310) ~[io.airbyte-airbyte-workers-0.40.1.jar:?]
	at io.airbyte.workers.temporal.sync.ReplicationActivityImpl.replicate(ReplicationActivityImpl.java:119) ~[io.airbyte-airbyte-workers-0.40.1.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at io.temporal.internal.activity.POJOActivityTaskHandler$POJOActivityInboundCallsInterceptor.execute(POJOActivityTaskHandler.java:214) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.activity.POJOActivityTaskHandler$POJOActivityImplementation.execute(POJOActivityTaskHandler.java:180) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.activity.POJOActivityTaskHandler.handle(POJOActivityTaskHandler.java:120) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:204) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:164) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93) ~[temporal-sdk-1.8.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [?:?]
	at java.lang.Thread.run(Thread.java:1589) [?:?]
Caused by: java.util.concurrent.CancellationException
	at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2510) ~[?:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getCancellationChecker$3(TemporalAttemptExecution.java:201) ~[io.airbyte-airbyte-workers-0.40.1.jar:?]
	at io.airbyte.workers.temporal.CancellationHandler$TemporalCancellationHandler.checkAndHandleCancellation(CancellationHandler.java:52) ~[io.airbyte-airbyte-workers-0.40.1.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getCancellationChecker$4(TemporalAttemptExecution.java:204) ~[io.airbyte-airbyte-workers-0.40.1.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	... 3 more

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by natalyjazzviolin** [comment]
@st0302 let's jump over to the [Troubleshooting section of the forum](https://discuss.airbyte.io/c/issues/11) as a first step to try and figure this out. Could you create a post there and attach the full logs as a file?
