### ISSUE TITLE
Source LinkedIn Pages: isn't able to pass connection tests

### ISSUE THREAD

**Issue by jscottpolevault** [airbytehq/airbyte#15986]
## Environment
- **Airbyte version**:  0.40.2
- **OS Version / Instance**: macOS 12.5.1
- **Deployment**: Docker on AWS EC2
- **Source Connector and version**: LinkedIn Pages 0.1.0 (I helped to build this connector, so I know it worked at one point).
- **Step where error happened**: Setup new connection

## Current Behavior
*The connection test fails due to the error logs saying "*****" is not an integer*

## Logs
```
2022-08-25 18:56:50 INFO i.a.w.t.TemporalAttemptExecution(get):105 - Docker volume job log path: /tmp/workspace/2c2d5de6-c014-4a2b-a113-d11967110fc6/0/logs.log
2022-08-25 18:56:50 INFO i.a.w.t.TemporalAttemptExecution(get):110 - Executing worker wrapper. Airbyte version: 0.40.2
2022-08-25 18:56:50 INFO i.a.c.i.LineGobbler(voidCall):83 - Checking if airbyte/source-linkedin-pages:0.1.0 exists...
2022-08-25 18:56:50 INFO i.a.c.i.LineGobbler(voidCall):83 - airbyte/source-linkedin-pages:0.1.0 was found locally.
2022-08-25 18:56:50 INFO i.a.w.p.DockerProcessFactory(create):108 - Creating docker job ID: 2c2d5de6-c014-4a2b-a113-d11967110fc6
2022-08-25 18:56:50 INFO i.a.w.p.DockerProcessFactory(create):163 - Preparing command: docker run --rm --init -i -w /data/2c2d5de6-c014-4a2b-a113-d11967110fc6/0 --log-driver none --name source-linkedin-pages-check-2c2d5de6-c014-4a2b-a113-d11967110fc6-0-ygcwh --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e USE_STREAM_CAPABLE_STATE=true -e AIRBYTE_ROLE= -e WORKER_ENVIRONMENT=DOCKER -e WORKER_JOB_ATTEMPT=0 -e WORKER_CONNECTOR_IMAGE=airbyte/source-linkedin-pages:0.1.0 -e AIRBYTE_VERSION=0.40.2 -e WORKER_JOB_ID=2c2d5de6-c014-4a2b-a113-d11967110fc6 airbyte/source-linkedin-pages:0.1.0 check --config source_config.json
2022-08-25 18:56:52 ERROR i.a.w.i.DefaultAirbyteStreamFactory(internalLog):95 - Config validation error: '****' is not of type 'integer'
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 123, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 96, in run
    check_config_against_spec_or_exit(connector_config, source_spec)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 160, in check_config_against_spec_or_exit
    raise Exception("Config validation error: " + validation_error.message) from None
Exception: Config validation error: '****' is not of type 'integer'
2022-08-25 18:56:52 ERROR i.a.w.g.DefaultCheckConnectionWorker(run):94 - Error checking connection, status: Optional.empty, exit code: 1
2022-08-25 18:56:52 INFO i.a.w.t.TemporalAttemptExecution(get):131 - Stopping cancellation check scheduling...
```

## Steps to Reproduce
1. Set up a new connection for LinkedIn Pages 0.1.0

## Are you willing to submit a PR?
Yes! I just don't know how to edit the config process without being in a dev environment. This all worked when I ran it locally, so I'm not sure why the actual user input isn't being stored in the connector settings... and sending "****" instead.

Do you think the needs more lines like this?

Comparing LinkedIn Ads Connector (left) to LinkedIn Pages Connector (right)

<img width="1664" alt="Screen Shot 2022-08-25 at 2 27 44 PM" src="https://user-images.githubusercontent.com/101282547/186751848-3ff9c04d-5d8f-4d99-b37d-14bba408a1d0.png">

______________
The error I'm getting at connection setup:

<img width="854" alt="Screen Shot 2022-08-25 at 2 10 09 PM" src="https://user-images.githubusercontent.com/101282547/186750026-ce8ae8dc-2fa8-4bb3-9cae-2a86a1622aa4.png">

**Comment by marcosmarxm** [comment]
@jscottpolevault probably is the `org_id` parameter which is causing the issue

**Comment by marcosmarxm** [comment]
I was able to reproduce the same issue using Integration Account.

**Comment by jscottpolevault** [comment]
> I was able to reproduce the same issue using Integration Account.

Is this something the Airbyte team is planning to fix? Or do I need to get in there?

**Comment by jscottpolevault** [comment]
I do not want to fix this issue, ha. I'm sorry but it would take me too long to figure out how. I don't understand why it's not working.

**Comment by leminhds** [comment]
any news about this issue?

**Comment by firehist** [comment]
Hello everybody,  
I tried it again and still the same error.  
I don't get why we have this error, if it is connector-related or a more global problem.

Does someone have some insights to help me dive in?

**Comment by LuliRib** [comment]
Hi, I have the same issue :(

**Comment by tinomerl** [comment]
This should be closed via #24161 and #18967. @marcosmarxm could you verify?

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by marcosmarxm** [comment]
Linkedin Pages was updated and latest version now is 1.0.2 please try with this version.
