### ISSUE TITLE
Destination BigQuery (denormalized ): Failed to parse column that has value of `{}`

### ISSUE THREAD

**Issue by jhajajaas** [airbytehq/airbyte#16345]
## Environment
- **Airbyte version**:  0.40.4
- **OS Version / Instance**: GKE
- **Deployment**: Kubernetes
- **Source Connector and version**: Stripe 0.1.37
- **Destination Connector and version**: BigQuery (denormalized typed struct) 1.1.16
- **Step where error happened**: Sync Job

## Current Behavior
Failed to parse column that has value of `{}`. 
Got the error `Field metadata has incompatible types. Configured schema: string. Avro file: record`

## Expected Behavior
`{}` should be treated as null

## Logs
[logs-33.txt](https://github.com/airbytehq/airbyte/files/9496135/logs-33.txt)

## Steps to Reproduce
1. Have one of the RECORD field to have value of `{}`
2. Sync to BigQuery (denormalized typed struct) 

## Are you willing to submit a PR?
Not sure if I could find the time.

**Comment by mrrobby** [comment]
My issue seems similar in a different context. Hoping we can get to a solution. I cannot run this sync at all.

## Environment
Airbyte version: 0.42.0 OSS
OS Version / Instance: MacOS local
Deployment: Docker Compose version v2.15.1
Source Connector and version: Stripe 3.0.1
Destination Connector and version: BigQuery (denormalized typed struct) 1.2.16
Step where error happened: Sync Job

## Current Behavior
Attempting to sync on any objects, it fails every time with error:

```bash
Caused by: org.apache.avro.AvroTypeException: Could not evaluate union, field metadata is expected to be one of these: NULL, RECORD. If this is a complex type, check if offending field (path: metadata) adheres to schema: {"organizations.name":"organizations/<UUID>,"organizations.uuid":"<UUID>"}
	at tech.allegro.schema.json2avro.converter.AvroTypeExceptions.unionException(AvroTypeExceptions.java:16)
	at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.readUnion(JsonGenericRecordReader.java:304)
	at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.read(JsonGenericRecordReader.java:198)
	at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.read(JsonGenericRecordReader.java:172)
	at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.lambda$readRecord$0(JsonGenericRecordReader.java:154)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.readRecord(JsonGenericRecordReader.java:143)
	at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.read(JsonGenericRecordReader.java:129)
```

This works okay with other ETL tools. Another important note - on table creation, the `metadata` field, for some reason, is assigned the `STRING` datatype.

**Comment by davydov-d** [comment]
Unfortunately, we have deprecated the BigQuery Denormalized Destination. Hypothetically this error can also occur in Avro destinations, but that's rather a destination issue and a corresponding bug is filed here https://github.com/airbytehq/airbyte/issues/28814
