### ISSUE TITLE
Worker `docker run` command ignores proxy env variables (http_proxy, https_proxy, no_proxy)

### ISSUE THREAD

**Issue by ajboni** [airbytehq/airbyte#16595]
## Environment
- **Airbyte version**:  example is 0.40.4
- **OS Version / Instance**: rhel 6
- **Deployment**:  Docker
- **Source Connector and version**: posthog:0.1.17 

My host is behind a proxy, so every docker container gets these variables injected. This works ok for airbyte containers but when a new container is spawned insede the worker ct , it won't inject those variable failing for services needing external resources:

## Current Behavior
This example is using posthog connector that connects to their API on the internet. 
Inside the worker container: 
```
echo $http_proxy $https_proxy $no_proxy
** Prints right info**
curl internetUrl` works
** works as expected **

root@b4090f453ef6:/app# docker run --rm --init -i -w /data/9480103c-d9d1-458b-9c3f-dc94561d7828/0 --log-driver none --name source-posthog-check-9480103c-d9d1-458b-9c3f-dc94561d7828-0-ufjju --network local -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e USE_STREAM_CAPABLE_STATE=true -e AIRBYTE_ROLE= -e WORKER_ENVIRONMENT=DOCKER -e WORKER_CONNECTOR_IMAGE=airbyte/source-posthog:0.1.7 -e WORKER_JOB_ATTEMPT=0 -e AIRBYTE_VERSION=0.40.4 -e WORKER_JOB_ID=9480103c-d9d1-458b-9c3f-dc94561d7828 airbyte/source-posthog:0.1.7 check --config source_config.json
{"type": "LOG", "log": {"level": "INFO", "message": "Backing off _send(...) for 5.0s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='[app.posthog.com](http://app.posthog.com/)', port=443): Max retries exceeded with url: /api/users/@me (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6d7e7563d0>: Failed to establish a new connection: [Errno -2] Name or service not known')))"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Caught retryable error 'HTTPSConnectionPool(host='[app.posthog.com](http://app.posthog.com/)', port=443): Max retries exceeded with url: /api/users/@me (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6d7e7563d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))' after 1 tries. Waiting 5 seconds then retrying..."}}
{"type": "LOG", "log": {"level": "INFO", "message": "Backing off _send(...) for 10.0s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='[app.posthog.com](http://app.posthog.com/)', port=443): Max retries exceeded with url: /api/users/@me (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6d7e756340>: Failed to establish a new connection: [Errno -2] Name or service not known')))"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Caught retryable error 'HTTPSConnectionPool(host='[app.posthog.com](http://app.posthog.com/)', port=443): Max retries exceeded with url: /api/users/@me (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6d7e756340>: Failed to establish a new connection: [Errno -2] Name or service not known'))' after 2 tries. Waiting 10 seconds then retrying..."}}
{"type": "LOG", "log": {"level": "INFO", "message": "Backing off _send(...) for 20.0s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='[app.posthog.com](http://app.posthog.com/)', port=443): Max retries exceeded with url: /api/users/@me (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6d7e7563a0>: Failed to establish a new connection: [Errno -2] Name or service not known')))"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Caught retryable error 'HTTPSConnectionPool(host='[app.posthog.com](http://app.posthog.com/)', port=443): Max retries exceeded with url: /api/users/@me (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6d7e7563a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))' after 3 tries. Waiting 20 seconds then retrying..."}}
{"type": "LOG", "log": {"level": "INFO", "message": "Backing off _send(...) for 40.0s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='[app.posthog.com](http://app.posthog.com/)', port=443): Max retries exceeded with url: /api/users/@me (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6d7e756430>: Failed to establish a new connection: [Errno -2] Name or service not known')))"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Caught retryable error 'HTTPSConnectionPool(host='[app.posthog.com](http://app.posthog.com/)', port=443): Max retries exceeded with url: /api/users/@me (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6d7e756430>: Failed to establish a new connection: [Errno -2] Name or service not known'))' after 4 tries. Waiting 40 seconds then retrying..."}}
^CTraceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
conn = connection.create_connection(
File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

```

## Workaround. 
Simplest workaround is to override the run command with the proper env vars.
```
docker run -e --rm --init -i -w /data/9480103c-d9d1-458b-9c3f-dc94561d7828/0 --log-driver none --name source-posthog-check-9480103c-d9d1-458b-9c3f-dc94561d7828-0-ufjju --network local -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e USE_STREAM_CAPABLE_STATE=true -e AIRBYTE_ROLE= -e WORKER_ENVIRONMENT=DOCKER -e WORKER_CONNECTOR_IMAGE=airbyte/source-posthog:0.1.7 -e WORKER_JOB_ATTEMPT=0 -e AIRBYTE_VERSION=0.40.4 -e WORKER_JOB_ID=9480103c-d9d1-458b-9c3f-dc94561d7828 -e http_proxy -e https_proxy -e no_proxy airbyte/source-posthog:0.1.7 check --config source_config.json
{"type": "LOG", "log": {"level": "INFO", "message": "Check succeeded"}}
{"type": "CONNECTION_STATUS", "connectionStatus": {"status": "SUCCEEDED"}}
```

## Expected Behavior
Spawned container inside worker should also use proxy variables.
An env config variable would also be acceptable

## Are you willing to submit a PR?
Yes

Thanks

**Comment by sajarin** [comment]
Thanks @ajboni for this issue. If you were to draft a PR, what would your proposed solution look like?

**Comment by ajboni** [comment]
Hey @sajarin I actually found a nice workaround using `JOB_DEFAULT_ENV_` prefix in `docker_compose.yaml`
```
worker:
...
     - JOB_DEFAULT_ENV_http_proxy=${http_proxy}
     - JOB_DEFAULT_ENV_https_proxy=${https_proxy}
     - JOB_DEFAULT_ENV_no_proxy=${no_proxy}
```
these are appended in the docker run command automatically [here](https://github.com/airbytehq/airbyte/blob/master/airbyte-workers/src/main/java/io/airbyte/workers/process/DockerProcessFactory.java#L138)

I think this is undocumented.

**Comment by sajarin** [comment]
@ajboni just made an issue on updating our documentation to reflect this workaround. Feel free to leave your comments there or suggestions on what you'd ideally want to see documented.

**Comment by ajboni** [comment]
IMO the workaround is just a workaround and the expected behavior should be consistent across containers (all should use the ENV vars).

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
