### ISSUE TITLE
🐛 Source GitHub: KeyError: 'pull_request_updated_at'

### ISSUE THREAD

**Issue by ball-hayden** [airbytehq/airbyte#16641]
## Environment
- **Airbyte version**: 0.40.0-alpha
- **OS Version / Instance**: Official Docker Image
- **Deployment**: Kubernetes
- **Source Connector and version**: GitHub (0.2.46)
- **Destination Connector and version**: BigQuery (1.2.0)
- **Step where error happened**: Sync job

## Current Behavior

Normalisation fails:

```
2022-09-13 13:44:10 [42mnormalization[0m > Traceback (most recent call last):
2022-09-13 13:44:10 [42mnormalization[0m >   File "/usr/local/bin/transform-catalog", line 8, in <module>
2022-09-13 13:44:10 [42mnormalization[0m >     sys.exit(main())
2022-09-13 13:44:10 [42mnormalization[0m >   File "/usr/local/lib/python3.9/site-packages/normalization/transform_catalog/transform.py", line 104, in main
2022-09-13 13:44:10 [42mnormalization[0m >     TransformCatalog().run(args)
2022-09-13 13:44:10 [42mnormalization[0m >   File "/usr/local/lib/python3.9/site-packages/normalization/transform_catalog/transform.py", line 36, in run
2022-09-13 13:44:10 [42mnormalization[0m >     self.process_catalog()
2022-09-13 13:44:10 [42mnormalization[0m >   File "/usr/local/lib/python3.9/site-packages/normalization/transform_catalog/transform.py", line 64, in process_catalog
2022-09-13 13:44:10 [42mnormalization[0m >     processor.process(catalog_file=catalog_file, json_column_name=json_col, default_schema=schema)
2022-09-13 13:44:10 [42mnormalization[0m >   File "/usr/local/lib/python3.9/site-packages/normalization/transform_catalog/catalog_processor.py", line 76, in process
2022-09-13 13:44:10 [42mnormalization[0m >     nested_processors = stream_processor.process()
2022-09-13 13:44:10 [46mnormalization-orchestrator[0m > (pod: airbyte / normalization-normalize-715-2-mndog) - Closed all resources for pod
2022-09-13 13:44:10 [42mnormalization[0m >   File "/usr/local/lib/python3.9/site-packages/normalization/transform_catalog/stream_processor.py", line 298, in process
2022-09-13 13:44:10 [42mnormalization[0m >     self.generate_scd_type_2_model(from_table, column_names),
2022-09-13 13:44:10 [42mnormalization[0m >   File "/usr/local/lib/python3.9/site-packages/normalization/transform_catalog/stream_processor.py", line 742, in generate_scd_type_2_model
2022-09-13 13:44:10 [42mnormalization[0m >     cursor_field = self.get_cursor_field(column_names)
2022-09-13 13:44:10 [42mnormalization[0m >   File "/usr/local/lib/python3.9/site-packages/normalization/transform_catalog/stream_processor.py", line 1023, in get_cursor_field
2022-09-13 13:44:10 [42mnormalization[0m >     cursor = column_names[self.cursor_field[0]][0]
2022-09-13 13:44:10 [42mnormalization[0m > KeyError: 'pull_request_updated_at'
```

## Expected Behavior

Sync should complete successfully

## Logs

[logs-715.txt](https://github.com/airbytehq/airbyte/files/9558372/logs-715.txt)

## Steps to Reproduce

Unknown

## Are you willing to submit a PR?

With debug advice, sure.

**Comment by grubberr** [comment]
@lazebnyi 

as for me, it's not actual, I think we can just close it

Stream `reviews` changed cursor_field `pull_request_updated_at` -> `updated_at`
and normalization failed because it used fresh data with old out-dated catalog

https://github.com/airbytehq/airbyte/commit/4072d46a7c9cf4ca46be865f9992df06c415fb1c#diff-07d1d74e0fefb121bc7f0e8a6bc5e01c0f02b1fa91417fc8c94ee3548e45328bL123

on fresh connection setup or reset data - no such problem will appear

**Comment by lazebnyi** [comment]
Fixed in - https://github.com/airbytehq/airbyte/pull/13989
