### ISSUE TITLE
Source cockroachdb throws OOM on a table with 8 million rows

### ISSUE THREAD

**Issue by obraginskaya** [airbytehq/airbyte#16693]
## Environment
- **Airbyte version**:  0.40.4
- **OS Version / Instance**: AWS EC2
- **Deployment**: Kubernetes
- **Source Connector and version**: cockroachdb 0.1.18
- **Destination Connector and version**: s3 0.3.14
- **Step where error happened**: Sync job

## Current Behavior

I am trying to sync data from Cockroachdb to S3. My table in Cockroachdb is around 8 million rows. Other tables which are smaller work fine.

Worker requirements:

    apiVersion: apps/v1
    kind: Deployment
    metadata:
    name: airbyte-worker
    spec:
    template:
        spec:
        containers:
            - name: airbyte-worker-container
            resources:
                limits:
                cpu: 2
                memory: 2Gi

Sync job requirements:
    
    resourceRequirements:
    cpu_request: "50m"
    cpu_limit: "2"
    memory_request: "1Gi"
    memory_limit: "8Gi"

## Expected Behavior

The sync should succeed

## Logs

    2022-09-13 15:17:10 [44msource[0m > 2022-09-13 15:17:10 [32mINFO[m i.a.i.s.r.AbstractRelationalDbSource(queryTableFullRefresh):35 - Queueing query for table: audit_entries
    2022-09-13 15:17:53 [44msource[0m > Terminating due to java.lang.OutOfMemoryError: Java heap space
    2022-09-13 15:17:55 [43mdestination[0m > 2022-09-13 15:17:55 [32mINFO[m i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):62 - Airbyte message consumer: succeeded.
    2022-09-13 15:17:55 [43mdestination[0m > 2022-09-13 15:17:55 [32mINFO[m i.a.i.d.b.BufferedStreamConsumer(close):171 - executing on success close procedure.
    2022-09-13 15:17:55 [43mdestination[0m > 2022-09-13 15:17:55 [32mINFO[m i.a.i.d.r.SerializedBufferingStrategy(flushAll):100 - Flushing all 0 current buffers (0 bytes in total)
    2022-09-13 15:17:55 [43mdestination[0m > 2022-09-13 15:17:55 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):152 - Completed integration: io.airbyte.integrations.destination.s3.S3Destination
    2022-09-13 15:17:54 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$getReplicationRunnable$6):342 - Source has no more messages, closing connection.
    2022-09-13 15:17:55 [32mINFO[m i.a.w.p.KubePodProcess(close):736 - (pod: de / source-cockroachdb-read-26256-0-qnlsl) - Closed all resources for pod
    2022-09-13 15:17:58 [32mINFO[m i.a.w.p.KubePodProcess(close):736 - (pod: de / destination-s3-write-26256-0-orfyr) - Closed all resources for pod
    2022-09-13 15:17:58 [1;31mERROR[m i.a.w.g.DefaultReplicationWorker(run):184 - Sync worker failed.
    java.util.concurrent.ExecutionException: io.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source cannot be stopped!
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
        at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:177) ~[io.airbyte-airbyte-workers-0.40.4.jar:?]
        at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:65) ~[io.airbyte-airbyte-workers-0.40.4.jar:?]
        at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:159) ~[io.airbyte-airbyte-workers-0.40.4.jar:?]
        at java.lang.Thread.run(Thread.java:1589) [?:?]
        Suppressed: io.airbyte.workers.exception.WorkerException: Source process exit with code 3. This warning is normal if the job was cancelled.
            at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:140) ~[io.airbyte-airbyte-workers-0.40.4.jar:?]
            at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:141) ~[io.airbyte-airbyte-workers-0.40.4.jar:?]
            at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:65) ~[io.airbyte-airbyte-workers-0.40.4.jar:?]
            at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:159) ~[io.airbyte-airbyte-workers-0.40.4.jar:?]
            at java.lang.Thread.run(Thread.java:1589) [?:?]
    Caused by: io.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source cannot be stopped!
        at io.airbyte.workers.general.DefaultReplicationWorker.lambda$getReplicationRunnable$6(DefaultReplicationWorker.java:346) ~[io.airbyte-airbyte-workers-0.40.4.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        ... 1 more
    Caused by: io.airbyte.workers.exception.WorkerException: Source process exit with code 3. This warning is normal if the job was cancelled.
        at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:140) ~[io.airbyte-airbyte-workers-0.40.4.jar:?]
        at io.airbyte.workers.general.DefaultReplicationWorker.lambda$getReplicationRunnable$6(DefaultReplicationWorker.java:344) ~[io.airbyte-airbyte-workers-0.40.4.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        ... 1 more
    2022-09-13 15:17:58 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):249 - sync summary: io.airbyte.config.ReplicationAttemptSummary@6c55d1c7[status=failed,recordsSynced=0,bytesSynced=0,startTime=1663082209885,endTime=1663082278177,totalStats=io.airbyte.config.SyncStats@3246294a[recordsEmitted=0,bytesEmitted=0,sourceStateMessagesEmitted=0,destinationStateMessagesEmitted=0,recordsCommitted=0,meanSecondsBeforeSourceStateMessageEmitted=0,maxSecondsBeforeSourceStateMessageEmitted=0,maxSecondsBetweenStateMessageEmittedandCommitted=0,meanSecondsBetweenStateMessageEmittedandCommitted=0,additionalProperties={}],streamStats=[]]
        return callback(**use_params)  # type: ignore
    File "/app/main.py", line 57, in run_job
        return Connection(
    File "/app/api/connection.py", line 189, in run_job
        job = self.wait_job_to_complete(
    File "/app/api/connection.py", line 128, in wait_job_to_complete
        raise ConnectionRunException("Connection execution failed")
    exceptions.ConnectionRunException: Connection execution failed
    2022-09-13 15:17:58 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):278 - Source did not output any state messages
    2022-09-13 15:17:58 [33mWARN[m i.a.w.g.DefaultReplicationWorker(run):289 - State capture: No state retained.
    2022-09-13 15:17:58 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):132 - Stopping cancellation check scheduling...
    2022-09-13 15:17:58 [32mINFO[m i.a.w.t.s.ReplicationActivityImpl(lambda$replicate$3):166 - sync summary: io.airbyte.config.StandardSyncOutput@603b3d17[standardSyncSummary=io.airbyte.config.StandardSyncSummary@372179b3[status=failed,recordsSynced=0,bytesSynced=0,startTime=1663082209885,endTime=1663082278177,totalStats=io.airbyte.config.SyncStats@3246294a[recordsEmitted=0,bytesEmitted=0,sourceStateMessagesEmitted=0,destinationStateMessagesEmitted=0,recordsCommitted=0,meanSecondsBeforeSourceStateMessageEmitted=0,maxSecondsBeforeSourceStateMessageEmitted=0,maxSecondsBetweenStateMessageEmittedandCommitted=0,meanSecondsBetweenStateMessageEmittedandCommitted=0,additionalProperties={}],streamStats=[]],normalizationSummary=<null>,state=<null>,outputCatalog=io.airbyte.protocol.models.ConfiguredAirbyteCatalog@2f7b8d28[streams=[io.airbyte.protocol.models.ConfiguredAirbyteStream@7283d82[stream=io.airbyte.protocol.models.AirbyteStream@3e426bf5[name=cockroachdb_audit_entries,jsonSchema={"type":"object","properties":{"id":{"type":"string"},"event":{"type":"string"},"account_id":{"type":"string"},"create_time":{"type":"string","format":"date-time","airbyte_type":"timestamp_with_timezone"},"create_actor":{"type":"string"},"resource_path":{"type":"string"}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[[account_id], [resource_path], [create_time], [id]],namespace=public,additionalProperties={}],syncMode=incremental,cursorField=[create_time],destinationSyncMode=append,primaryKey=[[account_id], [resource_path], [create_time], [id]],additionalProperties={}]],additionalProperties={}],failures=[io.airbyte.config.FailureReason@212716f[failureOrigin=source,failureType=<null>,internalMessage=io.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source cannot be stopped!,externalMessage=Something went wrong within the source connector,metadata=io.airbyte.config.Metadata@7173aec8[additionalProperties={attemptNumber=0, jobId=26256, connector_command=read}],stacktrace=java.util.concurrent.CompletionException: io.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source cannot be stopped!
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)
    Caused by: io.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source cannot be stopped!
        at io.airbyte.workers.general.DefaultReplicationWorker.lambda$getReplicationRunnable$6(DefaultReplicationWorker.java:346)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        ... 3 more
    Caused by: io.airbyte.workers.exception.WorkerException: Source process exit with code 3. This warning is normal if the job was cancelled.
        at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:140)
        at io.airbyte.workers.general.DefaultReplicationWorker.lambda$getReplicationRunnable$6(DefaultReplicationWorker.java:344)
        ... 4 more
    ,retryable=<null>,timestamp=1663082275170]]]
    2022-09-13 15:17:58 [32mINFO[m i.a.w.t.TemporalUtils(withBackgroundHeartbeat):312 - Stopping temporal heartbeating...
    attempt 1:

## Steps to Reproduce
1.Set up a connection between Cockroachdb and S3

2.Trigger the sync

## Are you willing to submit a PR?
No

**Comment by sajarin** [comment]
@obraginskaya, thanks for the issue. How much memory does roughly one row of your table take up? 

Have you considered doubling the amount of RAM allocated for this sync?

**Comment by obraginskaya** [comment]
@sajarin, so my table is 3.5 Gb. I read this https://docs.airbyte.com/operator-guides/scaling-airbyte#memory 
3.5 Gb / 8.300.000 = 0.4212Kbs in average. 10000 * 0.4212 = 4.212Mbs of RAM if I calculated it correctly. 

JOB_MAIN_CONTAINER_CPU_REQUEST=500m
JOB_MAIN_CONTAINER_CPU_LIMIT=2
JOB_MAIN_CONTAINER_MEMORY_REQUEST=500Mi
JOB_MAIN_CONTAINER_MEMORY_LIMIT=5Gi

This is my env settings. Now I'm confused which setting I should try: this ones from env or from airbyte-worker resources.

**Comment by obraginskaya** [comment]
I found in a log my pod requirements
`KubeProcessFactory(create):100 - Attempting to start pod = source-cockroachdb-check-30268-0-vnrvn for airbyte/source-cockroachdb:0.1.18 with resources io.airbyte.config.ResourceRequirements@122d65a9[cpuRequest=500m,cpuLimit=2,memoryRequest=500Mi,memoryLimit=5Gi]'`

**Comment by obraginskaya** [comment]
I found from log that my real requirements are the connection requirements    
cpu_request: "50m"
 cpu_limit: "2"
 memory_request: "1Gi"
 memory_limit: "8Gi"

**Comment by obraginskaya** [comment]
I tried to increase resources, still Java OOM:
  resourceRequirements:
    cpu_request: "50m"
    cpu_limit: "2"
    memory_request: "8Gi"
    memory_limit: "16Gi"

**Comment by obraginskaya** [comment]
And tried allowed maximum for our instance type c5a.2xlarge - also OOM

cpu_request: 2
    # cpu_limit: "2" # No limit
    memory_request: "14Gi"
    memory_limit: "14Gi"

**Comment by sajarin** [comment]
Thanks for the additional info/tests. Is this an incremental sync or a full refresh? And how many records are synced before it throws OOM?

**Comment by obraginskaya** [comment]
It's a full refresh. I couldn't find how to get amount a rows. It failed before it created a final file

**Comment by obraginskaya** [comment]
We did an additional test and changed instance type to m5a.4xlarge, then run the job with a new requirements:
  resourceRequirements:
    cpu_request: 8
    cpu_limit: "12"
    memory_request: "60Gi"
    memory_limit: "60Gi"

The sync worked successfully with last record in the log: 2022-09-19 16:00:44 INFO i.a.w.g.DefaultReplicationWorker(lambda$getReplicationRunnable$6):339 - Records read: 8397000 (7 GB).

So I guess we need just more resources in this case

**Comment by sajarin** [comment]
Thanks @obraginskaya for the follow-up, happy to hear the sync is working!

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 365 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by vikas-wishlink** [comment]
same issue on 10 million rows table
