### ISSUE TITLE
Timeout fetching salesforce schema

### ISSUE THREAD

**Issue by A-Costa** [airbytehq/airbyte#1669]
## Expected Behavior
I want to set up a connection between Salesforce and Snowflake

## Current Behavior
The process starts correctly but after i put the credentials for both Salesforce and Snowflake the connections are tested and look fine, but after i get this screen:
![Screen Shot 2021-01-15 at 17 07 59](https://user-images.githubusercontent.com/17851789/104750333-3b60c880-5754-11eb-8eea-542f1cfafdc3.png)

This stays for 2 minutes and then i get this:
![Screen Shot 2021-01-15 at 17 08 45](https://user-images.githubusercontent.com/17851789/104750394-55021000-5754-11eb-9136-4fdcf9c85e18.png)

By looking at the sequence of requests happening in the browser, i can see there's a POST request to 
`http://localhost:8001/api/v1/sources/discover_schema`
that responds exactly after 2 minutes with a 
`message: "internal server error"`.

The airbyte-server logs look like this:

```
airbyte-server | 2021-01-13 16:27:41 DEBUG i.a.s.e.UncaughtExceptionMapper(toResponse):42 - {} - Uncaught exception                                                                                                                     
airbyte-server | java.lang.RuntimeException: Check connection job did not complete.
airbyte-server |        at io.airbyte.scheduler.client.DefaultSchedulerJobClient.waitUntilJobIsTerminalOrTimeout(DefaultSchedulerJobClient.java:128) ~[io.airbyte-airbyte-scheduler-0.10.0-alpha.jar:?]
airbyte-server |        at io.airbyte.scheduler.client.DefaultSchedulerJobClient.createDiscoverSchemaJob(DefaultSchedulerJobClient.java:67) ~[io.airbyte-airbyte-scheduler-0.10.0-alpha.jar:?]
airbyte-server |        at io.airbyte.server.handlers.SchedulerHandler.discoverSchemaForSourceFromSourceId(SchedulerHandler.java:138) ~[io.airbyte-airbyte-server-0.10.0-alpha.jar:?]
airbyte-server |        at io.airbyte.server.apis.ConfigurationApi.lambda$discoverSchemaForSource$13(ConfigurationApi.java:216) ~[io.airbyte-airbyte-server-0.10.0-alpha.jar:?]
airbyte-server |        at io.airbyte.server.apis.ConfigurationApi.execute(ConfigurationApi.java:390) ~[io.airbyte-airbyte-server-0.10.0-alpha.jar:?]
airbyte-server |        at io.airbyte.server.apis.ConfigurationApi.discoverSchemaForSource(ConfigurationApi.java:216) ~[io.airbyte-airbyte-server-0.10.0-alpha.jar:?]
airbyte-server |        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
airbyte-server |        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
airbyte-server |        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
airbyte-server |        at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
airbyte-server |        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[jersey-server-2.31.jar:?]
airbyte-server |        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) ~[jersey-server-2.31.jar:?]
airbyte-server |        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) ~[jersey-server-2.31.jar:?]
airbyte-server |        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) ~[jersey-server-2.31.jar:?]
airbyte-server |        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[jersey-server-2.31.jar:?]
airbyte-server |        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469) ~[jersey-server-2.31.jar:?]
airbyte-server |        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391) ~[jersey-server-2.31.jar:?]
airbyte-server |        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80) ~[jersey-server-2.31.jar:?]
airbyte-server |        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253) [jersey-server-2.31.jar:?]
airbyte-server |        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [jersey-common-2.31.jar:?]
airbyte-server |        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [jersey-common-2.31.jar:?]
airbyte-server |        at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [jersey-common-2.31.jar:?]
airbyte-server |        at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [jersey-common-2.31.jar:?]
airbyte-server |        at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [jersey-common-2.31.jar:?]
airbyte-server |        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [jersey-common-2.31.jar:?]
airbyte-server |        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232) [jersey-server-2.31.jar:?]
airbyte-server |        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680) [jersey-server-2.31.jar:?]
airbyte-server |        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394) [jersey-container-servlet-core-2.31.jar:?]
airbyte-server |        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) [jersey-container-servlet-core-2.31.jar:?]
airbyte-server |        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366) [jersey-container-servlet-core-2.31.jar:?]
airbyte-server |        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319) [jersey-container-servlet-core-2.31.jar:?]
airbyte-server |        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) [jersey-container-servlet-core-2.31.jar:?]
airbyte-server |        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763) [jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server |        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:569) [jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server |        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server |        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1377) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server |        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server |        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:507) [jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server |        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server |        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server |        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server |        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server |        at org.eclipse.jetty.server.Server.handle(Server.java:501) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server |        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server |        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server |        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server |        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server |        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server |        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server |        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server |        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server |        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server |        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server |        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server |        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server |        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server |        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server |        at java.lang.Thread.run(Thread.java:832) [?:?]
```

No interesting log appears for the scheduler.

Also important to note is that in the postgres internal database i can see the discover_schema job has status `running` for longer than 2 minutes (for about 5) to then change it to `succeed`. In the relative Attempt entry in the database, i can see the output column which effectively contain the salesforce catalog. So the job is indeed working fine. 

My guess is that the problem is simply related to this function: https://github.com/airbytehq/airbyte/blob/master/airbyte-scheduler/src/main/java/io/airbyte/scheduler/client/DefaultSchedulerJobClient.java#L112
2 minutes is a relatively short timeout for retrive big schemas (like salesforce).

It would be probably better to increase the timeout, improve errors on the browser (i had to dive into the docker logs to figure stuff out), and maybe have the front-end actually showing logs about the running job instead of a spinning wheel.

## Severity of the bug for you
High

## Additional context
Airbyte v0.10.0-alpha

**Comment by sherifnada** [comment]
@A-Costa thanks for the detailed error report. I've submitted #1674 to increase timeouts. I'll release a patch version for you to  use once this the PR has landed.

**Comment by sherifnada** [comment]
@A-Costa this should be fixed with #1674 . Please update your Airbyte instance as follows: 

```
docker-compose down
rm .env docker-compose.yml
wget https://raw.githubusercontent.com/airbytehq/airbyte/master/{.env,docker-compose.yaml} # or curl if wget not available
docker-compose up
```

Can you confirm things look good on your side?

**Comment by A-Costa** [comment]
Hi @sherifnada , thanks a lot for your help so far! 
I tried the fix released with #1674, (v0.11.1-alpha) but it does not solve the issue.

I'm confident however that #1703 has the right fix. 

Unfortunately though after updaiting the Airbyte instance to v0.11.2-alpha the `airbyte-server` instance is failing. 
Here the logs:

```
airbyte-server | --------------------------------------------------------
airbyte-server |  docker-compose-wait 2.7.2
airbyte-server | ---------------------------
airbyte-server | Starting with configuration:
airbyte-server |  - Hosts to be waiting for: [db:5432]
airbyte-server |  - Timeout before failure: 45 seconds
airbyte-server |  - TCP connection timeout before retry: 5 seconds
airbyte-server |  - Sleeping time before checking for hosts availability: 5 seconds
airbyte-server |  - Sleeping time once all hosts are available: 0 seconds
airbyte-server |  - Sleeping time between retries: 1 seconds
airbyte-server | --------------------------------------------------------
airbyte-server | Waiting 5 seconds before checking for hosts availability
airbyte-server | --------------------------------------------------------
airbyte-server | Checking availability of db:5432
airbyte-server | Host db:5432 is now available!
airbyte-server | --------------------------------------------------------
airbyte-server | docker-compose-wait - Everything's fine, the application can now start!
airbyte-server | --------------------------------------------------------
airbyte-server | 2021-01-19 10:29:44 INFO i.a.s.ServerApp(main):179 - {workspace_app_root=/tmp/workspace/server/logs} - configRoot = /data
airbyte-server | 2021-01-19 10:29:44 INFO i.a.s.ServerApp(main):181 - {workspace_app_root=/tmp/workspace/server/logs} - Creating config repository...
airbyte-server | Exception in thread "main" java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "onboardingComplete" (class io.airbyte.config.StandardWorkspace), not ma
rked as ignorable (10 known properties: "workspaceId", "initialSetupComplete", "news", "anonymousDataCollection", "displaySetupWizard", "customerId", "securityUpdates", "name", "email", "slug"])
airbyte-server |  at [Source: (String)"{"workspaceId":"5ae6b09b-fdec-41af-aaf7-7d94cfc33ef6","customerId":"16dc17ed-3219-4457-9bb7-1fcf8acfc5ca","name":"default","slug":"default","initialSetupComplete":true,"onboardingComplete":t
rue,"anonymousDataCollection":false,"news":false,"securityUpdates":false}"; line: 1, column: 194] (through reference chain: io.airbyte.config.StandardWorkspace["onboardingComplete"])
airbyte-server |        at io.airbyte.commons.json.Jsons.deserialize(Jsons.java:63)
airbyte-server |        at io.airbyte.config.persistence.DefaultConfigPersistence.getConfigInternal(DefaultConfigPersistence.java:90)
airbyte-server |        at io.airbyte.config.persistence.DefaultConfigPersistence.getConfig(DefaultConfigPersistence.java:64)
airbyte-server |        at io.airbyte.config.persistence.ConfigRepository.getStandardWorkspace(ConfigRepository.java:49)
airbyte-server |        at io.airbyte.server.ServerApp.setCustomerIdIfNotSet(ServerApp.java:157)
airbyte-server |        at io.airbyte.server.ServerApp.main(ServerApp.java:186)
airbyte-server | Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "onboardingComplete" (class io.airbyte.config.StandardWorkspace), not marked as ignorable (10 known properties: "wor
kspaceId", "initialSetupComplete", "news", "anonymousDataCollection", "displaySetupWizard", "customerId", "securityUpdates", "name", "email", "slug"])
airbyte-server |  at [Source: (String)"{"workspaceId":"5ae6b09b-fdec-41af-aaf7-7d94cfc33ef6","customerId":"16dc17ed-3219-4457-9bb7-1fcf8acfc5ca","name":"default","slug":"default","initialSetupComplete":true,"onboardingComplete":t
rue,"anonymousDataCollection":false,"news":false,"securityUpdates":false}"; line: 1, column: 194] (through reference chain: io.airbyte.config.StandardWorkspace["onboardingComplete"])
airbyte-server |        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
airbyte-server |        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:843)
airbyte-server |        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1206)
airbyte-server |        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1610)
airbyte-server |        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1588)
airbyte-server |        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
airbyte-server |        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
airbyte-server |        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4218)
airbyte-server |        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3214)
airbyte-server |        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3182)
airbyte-server |        at io.airbyte.commons.json.Jsons.deserialize(Jsons.java:61)
airbyte-server |        ... 5 more
```

This might be unrelated and need a new bug report?

**Comment by A-Costa** [comment]
Ah ok, this was caused by #1694 . 

I've solved by opening the json file in `/data/config/STANDARD_WORKSPACE/` and manually removing the onboardingComplete field.

**Comment by A-Costa** [comment]
After solving the issue with the `onboardingComplete` missing field, i've tried to sync again but the source was not validating. This is probably due to the fact that the upgrade contains a backwards incompatible change in the data schema (as @sherifnada told me on slack). 

I've then completely restarted the Airbyte instance from scratch and can confirm that the salesforce catalog is now correctly fetched! 🎉

**Comment by sherifnada** [comment]
amazing. Very happy to hear!! 🎉 Thanks for reporting the issue.
