### ISSUE TITLE
Kubernetes with Helm Server Error

### ISSUE THREAD

**Issue by donald-kortx** [airbytehq/airbyte#16815]
## Environment
- **Airbyte version**:  Chart Version: 0.40.6, App Version: 0.40.6
- **OS Version / Instance**: AWS EKS
- **Deployment**: Kubernetes (EKS) using Helm
- **Step where error happened**: Deploy

## Current Behavior
I followed the directions on https://docs.airbyte.com/deploying-airbyte/on-kubernetes-via-helm/#install-helm

After running `helm install airbyte-helm airbyte/airbyte`

I received a successful response with a status of DEPLOYED.

When I looked closer, I noticed that the server pod was restarting (all other pods seemed ok).

The logs for the server pod contained the following message:
```
2022-09-16 17:50:37 ERROR i.a.w.WorkerApp(main):592 - Worker app failed
java.lang.IllegalArgumentException: 'INTERNAL_API_HOST' environment variable cannot be null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220) ~[guava-31.0.1-jre.jar:?]
	at io.airbyte.config.EnvConfigs.getEnsureEnv(EnvConfigs.java:1107) ~[io.airbyte.airbyte-config-config-models-0.40.6.jar:?]
	at io.airbyte.config.EnvConfigs.getAirbyteApiHost(EnvConfigs.java:490) ~[io.airbyte.airbyte-config-config-models-0.40.6.jar:?]
	at io.airbyte.workers.WorkerApiClientFactoryImpl.<init>(WorkerApiClientFactoryImpl.java:35) ~[io.airbyte-airbyte-workers-0.40.6.jar:?]
	at io.airbyte.workers.WorkerApp.initializeCommonDependencies(WorkerApp.java:442) ~[io.airbyte-airbyte-workers-0.40.6.jar:?]
	at io.airbyte.workers.WorkerApp.main(WorkerApp.java:578) [io.airbyte-airbyte-workers-0.40.6.jar:?]

```

## Expected Behavior
I would like the default configuration to work with the current documentation.

## Steps to Reproduce
1. Follow the steps in Deploying Airbyte -> Default deployment on the Kubernetes using Helm page with an EKS cluster.

**Comment by marcosmarxm** [comment]
Latest version of Helm fixed the issue @donald-kortx please let me know if you faced the issue again.
