### ISSUE TITLE
Airbyte 0.40.7 worker is failing on startup with an exception, while the same environment worked fine for 0.40.3

### ISSUE THREAD

**Issue by jyates-om1** [airbytehq/airbyte#16893]
## Environment
- **Airbyte version**:  0.43.7-alpha
- **OS Version / Instance**: AWS EC2 / amazon linux
- **Deployment**: Docker on static EC2 instance
- **Step where error happened**: Worker start-up, any UI page that uses the worker

## Current Behavior
Worker is stuck in a crash-loop on start-up

## Expected Behavior
Worker behaves normally

## Logs
We can't share full logs due to company policy. Relevant logs from docker-compose:
```
airbyte-worker      |    /   |  (_)____/ /_  __  __/ /____
airbyte-worker      |   / /| | / / ___/ __ \/ / / / __/ _ \
airbyte-worker      |  / ___ |/ / /  / /_/ / /_/ / /_/  __/
airbyte-worker      | /_/  |_/_/_/  /_.___/\__, /\__/\___/
airbyte-worker      |                     /____/
airbyte-worker      |         : airbyte-workers :
airbyte-worker      |
airbyte-worker      |   Micronaut (v3.6.3)
airbyte-worker      |
airbyte-worker      | 2022-09-19 15:26:34 INFO i.m.c.e.DefaultEnvironment(<init>):159 - Established active environments: [ec2, cloud]
airbyte-worker      | 2022-09-19 15:26:34 INFO i.m.l.PropertiesLoggingLevelsConfigurer(configureLogLevelForPrefix):107 - Setting log level 'DEBUG' for logger: 'io.airbyte.bootloader'
airbyte-worker      | 2022-09-19 15:26:35 ERROR i.m.r.Micronaut(handleStartupException):338 - Error starting Micronaut server: Failed to inject value for parameter [dslContext] of method [configDatabase] of class: io.airbyte.db.Database
airbyte-worker      |
airbyte-worker      | Message: No bean of type [org.jooq.DSLContext] exists for the given qualifier: @Named('config'). Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
airbyte-worker      | Path Taken: new ApplicationInitializer() --> ApplicationInitializer.checkConnectionActivities --> List.checkConnectionActivities([CheckConnectionActivity checkConnectionActivity]) --> CheckConnectionActivityImpl.secretsHydrator --> SecretsHydrator.secretsHydrator([SecretPersistence secretPersistence]) --> SecretPersistence.defaultSecretPersistence([Database configDatabase]) --> Database.configDatabase([DSLContext dslContext])
airbyte-worker      | io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [dslContext] of method [configDatabase] of class: io.airbyte.db.Database
airbyte-worker      |
airbyte-worker      | Message: No bean of type [org.jooq.DSLContext] exists for the given qualifier: @Named('config'). Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
airbyte-worker      | Path Taken: new ApplicationInitializer() --> ApplicationInitializer.checkConnectionActivities --> List.checkConnectionActivities([CheckConnectionActivity checkConnectionActivity]) --> CheckConnectionActivityImpl.secretsHydrator --> SecretsHydrator.secretsHydrator([SecretPersistence secretPersistence]) --> SecretPersistence.defaultSecretPersistence([Database configDatabase]) --> Database.configDatabase([DSLContext dslContext])
airbyte-worker      |   at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2087) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.airbyte.workers.config.$DatabaseBeanFactory$ConfigDatabase0$Definition.build(Unknown Source) ~[io.airbyte-airbyte-workers-0.40.7.jar:?]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.airbyte.workers.config.$SecretPersistenceBeanFactory$DefaultSecretPersistence0$Definition.build(Unknown Source) ~[io.airbyte-airbyte-workers-0.40.7.jar:?]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.airbyte.workers.config.$SecretPersistenceBeanFactory$SecretsHydrator4$Definition.build(Unknown Source) ~[io.airbyte-airbyte-workers-0.40.7.jar:?]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForField(AbstractInitializableBeanDefinition.java:1603) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.airbyte.workers.temporal.check.connection.$CheckConnectionActivityImpl$Definition.injectBean(Unknown Source) ~[io.airbyte-airbyte-workers-0.40.7.jar:?]
airbyte-worker      |   at io.airbyte.workers.temporal.check.connection.$CheckConnectionActivityImpl$Definition.build(Unknown Source) ~[io.airbyte-airbyte-workers-0.40.7.jar:?]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.airbyte.workers.config.$ActivityBeanFactory$CheckConnectionActivities0$Definition.build(Unknown Source) ~[io.airbyte-airbyte-workers-0.40.7.jar:?]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1680) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.AbstractBeanResolutionContext.findBean(AbstractBeanResolutionContext.java:84) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.AbstractInitializableBeanDefinition.resolveOptionalBean(AbstractInitializableBeanDefinition.java:2178) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.AbstractInitializableBeanDefinition.findBeanForField(AbstractInitializableBeanDefinition.java:1843) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.airbyte.workers.$ApplicationInitializer$Definition.injectBean(Unknown Source) ~[io.airbyte-airbyte-workers-0.40.7.jar:?]
airbyte-worker      |   at io.airbyte.workers.$ApplicationInitializer$Definition.build(Unknown Source) ~[io.airbyte-airbyte-workers-0.40.7.jar:?]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2853) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:3511) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.resolveBeanRegistrations(DefaultBeanContext.java:3457) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:3427) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:1381) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:903) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:893) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.event.ApplicationEventPublisherFactory$2.lambda$$0(ApplicationEventPublisherFactory.java:217) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.core.util.SupplierUtil$2.initialize(SupplierUtil.java:77) ~[micronaut-core-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.core.util.SupplierUtil$2.get(SupplierUtil.java:72) ~[micronaut-core-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.event.ApplicationEventPublisherFactory$2.publishEvent(ApplicationEventPublisherFactory.java:229) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.http.server.netty.NettyHttpServer.lambda$fireStartupEvents$15(NettyHttpServer.java:574) ~[micronaut-http-server-netty-3.6.3.jar:3.6.3]
airbyte-worker      |   at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
airbyte-worker      |   at io.micronaut.http.server.netty.NettyHttpServer.fireStartupEvents(NettyHttpServer.java:568) ~[micronaut-http-server-netty-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:297) ~[micronaut-http-server-netty-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:104) ~[micronaut-http-server-netty-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.runtime.Micronaut.lambda$start$2(Micronaut.java:81) ~[micronaut-context-3.6.3.jar:3.6.3]
airbyte-worker      |   at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
airbyte-worker      |   at io.micronaut.runtime.Micronaut.start(Micronaut.java:79) ~[micronaut-context-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.runtime.Micronaut.run(Micronaut.java:323) ~[micronaut-context-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.runtime.Micronaut.run(Micronaut.java:309) ~[micronaut-context-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.airbyte.workers.Application.main(Application.java:12) ~[io.airbyte-airbyte-workers-0.40.7.jar:?]
airbyte-worker      | Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [org.jooq.DSLContext] exists for the given qualifier: @Named('config'). Make sure thebean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2805) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.6.3.jar:3.6.3]
airbyte-worker      |   ... 98 more
```

## Steps to Reproduce
1. Install airbyte `0.40.3`. Everything is vanilla except for using an external AWS-hosted database instance. 
2. Upgrade to `0.40.7` by bumping the version in `.env` and pulling the new version of `docker-compose.yaml`
3. Observer failure logs

## Are you willing to submit a PR?
Yes, but java is not my expertise :)

**Comment by jyates-om1** [comment]
Another community member experienced a similar error here: https://discuss.airbyte.io/t/airtbyte-in-a-crashloop-on-fresh-helm-install/2635/5

**Comment by kyle-cheung** [comment]
This happened to me, make sure you update your `docker-compose` and `env` file to match that of the airbyte repo. That fixed it for me

**Comment by jyates-om1** [comment]
My apologies, closing
