### ISSUE TITLE
Airbyte worker failing with multiple possible bean candidates found

### ISSUE THREAD

**Issue by cloorc** [airbytehq/airbyte#16908]
## Environment
- **Airbyte version**:  0.40.7
- **OS Version / Instance**: Kubernetes 1.20.2(image `airbyte/airbyte:0.40.7`)
- **Deployment**: Kubernetes
- **Source Connector and version**: (if applicable example Salesforce 0.2.3)  not available yet
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) not available yet
- **Step where error happened**: Deploy

## Current Behavior
Deployed using Helm 3.9.3 with chart `airbyte/airbyte:0.40.8` from `https://airbytehq.github.io/helm-charts`.
After all pods deployed, `airbyte-worker`  start failed.
The helm values looks like:

```yaml
airbyte-bootloader:
  image:
    repository: airbyte/bootloader
    tag: 0.40.7
  secrets:
    DATABASE_PASSWORD: ...
    DATABASE_USER: ...
externalDatabase:
  database: airbyte
  existingSecret: airbyte-secret
  existingSecretPasswordKey: DATABASE_PASSWORD
  host: ...
  port: 1921
  user: airbyte
global:
  database:
    host: ...
    port: 1921
    secretName: airbyte-secret
    secretValue: DATABASE_PASSWORD
  imagePullSecret: ...
  logs:
    externalMinio:
      enabled: true
      host: minio.develop
    minio:
      enabled: false
minio:
  enabled: false
pod-sweeper:
  image:
    repository: bitnami/kubectl
postgresql:
  enabled: false
server:
  image:
    repository: airbyte/server
    tag: 0.40.7
temporal:
  image:
    repository: temporalio/auto-setup
    tag: 1.7.0
webapp:
  image:
    repository: airbyte/webapp
    tag: 0.40.7
worker:
  image:
    repository: airbyte/worker
    tag: 0.40.7

```

## Expected Behavior

System could be ready for adding new sources and targets.

## Logs

```text

    ___    _      __          __
   /   |  (_)____/ /_  __  __/ /____
  / /| | / / ___/ __ \/ / / / __/ _ \
 / ___ |/ / /  / /_/ / /_/ / /_/  __/
/_/  |_/_/_/  /_.___/\__, /\__/\___/
                    /____/
        : airbyte-workers :

  Micronaut (v3.6.3)

2022-09-20 03:21:43 [32mINFO[m i.m.c.e.DefaultEnvironment(<init>):159 - Established active environments: [k8s, cloud, control]
2022-09-20 03:21:44 [32mINFO[m c.z.h.HikariDataSource(<init>):71 - HikariPool-1 - Starting...
2022-09-20 03:21:44 [32mINFO[m c.z.h.HikariDataSource(<init>):73 - HikariPool-1 - Start completed.
2022-09-20 03:21:44 [32mINFO[m c.z.h.HikariDataSource(<init>):71 - HikariPool-2 - Starting...
2022-09-20 03:21:44 [32mINFO[m c.z.h.HikariDataSource(<init>):73 - HikariPool-2 - Start completed.
2022-09-20 03:21:44 [32mINFO[m i.m.l.PropertiesLoggingLevelsConfigurer(configureLogLevelForPrefix):107 - Setting log level 'DEBUG' for logger: 'io.airbyte.bootloader'
2022-09-20 03:21:45 [32mINFO[m i.a.w.c.DatabaseBeanFactory(configsDatabaseMigrationCheck):139 - Configs database configuration: 0.35.15.001 60000
2022-09-20 03:21:45 [33mWARN[m i.a.a.TrackingClientSingleton(get):30 - Attempting to fetch an initialized track client. Initializing a default one.
2022-09-20 03:21:45 [32mINFO[m i.a.w.t.TemporalUtils(getTemporalClientWhenConnected):220 - Waiting for temporal server...
2022-09-20 03:21:45 [33mWARN[m i.a.w.t.TemporalUtils(getTemporalClientWhenConnected):231 - Waiting for namespace default to be initialized in temporal...
2022-09-20 03:21:48 [32mINFO[m i.t.s.WorkflowServiceStubsImpl(<init>):188 - Created GRPC client for channel: ManagedChannelOrphanWrapper{delegate=ManagedChannelImpl{logId=1, target=airbyte-temporal:7233}}
2022-09-20 03:21:53 [32mINFO[m i.a.w.t.TemporalUtils(getTemporalClientWhenConnected):248 - Temporal namespace default initialized!
2022-09-20 03:21:53 [1;31mERROR[m i.m.r.Micronaut(handleStartupException):338 - Error starting Micronaut server: Failed to inject value for parameter [jobErrorReportingClient] of method [jobErrorReporter] of class: io.airbyte.scheduler.persistence.job_error_reporter.JobErrorReporter

Message: Multiple possible bean candidates found: [io.airbyte.scheduler.persistence.job_error_reporter.JobErrorReportingClient, io.airbyte.scheduler.persistence.job_error_reporter.JobErrorReportingClient]
Path Taken: new ApplicationInitializer() --> ApplicationInitializer.connectionManagerActivities --> List.connectionManagerActivities(GenerateInputActivity generateInputActivity,[JobCreationAndStatusUpdateActivity jobCreationAndStatusUpdateActivity],ConfigFetchActivity configFetchActivity,ConnectionDeletionActivity connectionDeletionActivity,CheckConnectionActivity checkConnectionActivity,AutoDisableConnectionActivity autoDisableConnectionActivity,StreamResetActivity streamResetActivity,RecordMetricActivity recordMetricActivity,WorkflowConfigActivity workflowConfigActivity,RouteToSyncTaskQueueActivity routeToSyncTaskQueueActivity) --> new JobCreationAndStatusUpdateActivityImpl(SyncJobFactory jobFactory,JobPersistence jobPersistence,TemporalWorkerRunFactory temporalWorkerRunFactory,WorkerEnvironment workerEnvironment,LogConfigs logConfigs,JobNotifier jobNotifier,JobTracker jobTracker,ConfigRepository configRepository,JobCreator jobCreator,StreamResetPersistence streamResetPersistence,[JobErrorReporter jobErrorReporter]) --> JobErrorReporter.jobErrorReporter(String airbyteVersion,ConfigRepository configRepository,DeploymentMode deploymentMode,[JobErrorReportingClient jobErrorReportingClient],WebUrlHelper webUrlHelper)
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [jobErrorReportingClient] of method [jobErrorReporter] of class: io.airbyte.scheduler.persistence.job_error_reporter.JobErrorReporter

Message: Multiple possible bean candidates found: [io.airbyte.scheduler.persistence.job_error_reporter.JobErrorReportingClient, io.airbyte.scheduler.persistence.job_error_reporter.JobErrorReportingClient]
Path Taken: new ApplicationInitializer() --> ApplicationInitializer.connectionManagerActivities --> List.connectionManagerActivities(GenerateInputActivity generateInputActivity,[JobCreationAndStatusUpdateActivity jobCreationAndStatusUpdateActivity],ConfigFetchActivity configFetchActivity,ConnectionDeletionActivity connectionDeletionActivity,CheckConnectionActivity checkConnectionActivity,AutoDisableConnectionActivity autoDisableConnectionActivity,StreamResetActivity streamResetActivity,RecordMetricActivity recordMetricActivity,WorkflowConfigActivity workflowConfigActivity,RouteToSyncTaskQueueActivity routeToSyncTaskQueueActivity) --> new JobCreationAndStatusUpdateActivityImpl(SyncJobFactory jobFactory,JobPersistence jobPersistence,TemporalWorkerRunFactory temporalWorkerRunFactory,WorkerEnvironment workerEnvironment,LogConfigs logConfigs,JobNotifier jobNotifier,JobTracker jobTracker,ConfigRepository configRepository,JobCreator jobCreator,StreamResetPersistence streamResetPersistence,[JobErrorReporter jobErrorReporter]) --> JobErrorReporter.jobErrorReporter(String airbyteVersion,ConfigRepository configRepository,DeploymentMode deploymentMode,[JobErrorReportingClient jobErrorReportingClient],WebUrlHelper webUrlHelper)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2087) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.airbyte.workers.config.$JobErrorReportingBeanFactory$JobErrorReporter3$Definition.build(Unknown Source) ~[io.airbyte-airbyte-workers-0.40.7.jar:?]
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.airbyte.workers.temporal.scheduling.activities.$JobCreationAndStatusUpdateActivityImpl$Definition.build(Unknown Source) ~[io.airbyte-airbyte-workers-0.40.7.jar:?]
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.airbyte.workers.config.$ActivityBeanFactory$ConnectionManagerActivities1$Definition.build(Unknown Source) ~[io.airbyte-airbyte-workers-0.40.7.jar:?]
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1680) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.AbstractBeanResolutionContext.findBean(AbstractBeanResolutionContext.java:84) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveOptionalBean(AbstractInitializableBeanDefinition.java:2178) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.AbstractInitializableBeanDefinition.findBeanForField(AbstractInitializableBeanDefinition.java:1843) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.airbyte.workers.$ApplicationInitializer$Definition.injectBean(Unknown Source) ~[io.airbyte-airbyte-workers-0.40.7.jar:?]
	at io.airbyte.workers.$ApplicationInitializer$Definition.build(Unknown Source) ~[io.airbyte-airbyte-workers-0.40.7.jar:?]
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2853) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:3511) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistrations(DefaultBeanContext.java:3457) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:3427) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:1381) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:903) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:893) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.event.ApplicationEventPublisherFactory$2.lambda$$0(ApplicationEventPublisherFactory.java:217) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.core.util.SupplierUtil$2.initialize(SupplierUtil.java:77) ~[micronaut-core-3.6.3.jar:3.6.3]
	at io.micronaut.core.util.SupplierUtil$2.get(SupplierUtil.java:72) ~[micronaut-core-3.6.3.jar:3.6.3]
	at io.micronaut.context.event.ApplicationEventPublisherFactory$2.publishEvent(ApplicationEventPublisherFactory.java:229) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.http.server.netty.NettyHttpServer.lambda$fireStartupEvents$15(NettyHttpServer.java:574) ~[micronaut-http-server-netty-3.6.3.jar:3.6.3]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at io.micronaut.http.server.netty.NettyHttpServer.fireStartupEvents(NettyHttpServer.java:568) ~[micronaut-http-server-netty-3.6.3.jar:3.6.3]
	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:297) ~[micronaut-http-server-netty-3.6.3.jar:3.6.3]
	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:104) ~[micronaut-http-server-netty-3.6.3.jar:3.6.3]
	at io.micronaut.runtime.Micronaut.lambda$start$2(Micronaut.java:81) ~[micronaut-context-3.6.3.jar:3.6.3]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:79) ~[micronaut-context-3.6.3.jar:3.6.3]
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:323) ~[micronaut-context-3.6.3.jar:3.6.3]
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:309) ~[micronaut-context-3.6.3.jar:3.6.3]
	at io.airbyte.workers.Application.main(Application.java:12) ~[io.airbyte-airbyte-workers-0.40.7.jar:?]
Caused by: io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [io.airbyte.scheduler.persistence.job_error_reporter.JobErrorReportingClient, io.airbyte.scheduler.persistence.job_error_reporter.JobErrorReportingClient]
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:2472) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultApplicationContext.findConcreteCandidate(DefaultApplicationContext.java:488) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.lastChanceResolve(DefaultBeanContext.java:3249) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:3127) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:3058) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.findBeanDefinition(DefaultBeanContext.java:788) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2790) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.6.3.jar:3.6.3]
	... 71 more
```

## Steps to Reproduce

1. Update values as previous description;
2. Deploy chart `airbyte/airbyte:0.40.8`(curious why latest image is 0.40.7 but chart version is 0.40.8, not important anyway);
3. Check pod `airbyte-worker/*`;

## Are you willing to submit a PR?

Yes, but I'm new to airbyte. I'm glad to submit any contribution in future.

**Comment by cloorc** [comment]
The issue seems like has already been fixed on master branch.

**Comment by harshithmullapudi** [comment]
Thanks a lot for confirmation. Closing this, but do feel free to open it if you face issue again
