### ISSUE TITLE
airbyte 0.40.7 worker failing with Micronaut error on kubernetes deployment

### ISSUE THREAD

**Issue by andnig** [airbytehq/airbyte#16950]
## Environment
- **Airbyte version**:  0.40.7
- **OS Version / Instance**: GCP container optimized os
- **Deployment**: Kubernetes - deploy kustomize overlay "stable"
- **Source Connector and version**: any
- **Destination Connector and version**: any
- **Step where error happened**: Deploy

## Current Behavior
When deploying airbyte version 0.40.7 (``kubectl apply -k kube/overlays/stable``), the worker constantly crashes with the error message ``ERROR i.m.r.Micronaut(handleStartupException):338 - Error starting Micronaut server: Failed to inject value for parameter [jobErrorReportingClient] of method [jobErrorReporter]``
(Detailed exception log see bottom of this issue)

- This issue is resolved, if running the worker with version 0.40.6. 

- .env as well as kube-resources are the default ones from your repository.

- I use the default kustomize.yaml - but one change: I use ``namespace: airbyte`` instead of ``default``

## Expected Behavior
Workser starts without Exception.

## Logs
```

    ___    _      __          __
   /   |  (_)____/ /_  __  __/ /____
  / /| | / / ___/ __ \/ / / / __/ _ \
 / ___ |/ / /  / /_/ / /_/ / /_/  __/
/_/  |_/_/_/  /_.___/\__, /\__/\___/
                    /____/
        : airbyte-workers :

  Micronaut (v3.6.3)

2022-09-21 09:09:15 INFO i.m.c.e.DefaultEnvironment(<init>):159 - Established active environments: [k8s, cloud, gcp, control]
2022-09-21 09:09:16 INFO c.z.h.HikariDataSource(<init>):71 - HikariPool-1 - Starting...
2022-09-21 09:09:16 INFO c.z.h.HikariDataSource(<init>):73 - HikariPool-1 - Start completed.
2022-09-21 09:09:16 INFO c.z.h.HikariDataSource(<init>):71 - HikariPool-2 - Starting...
2022-09-21 09:09:16 INFO c.z.h.HikariDataSource(<init>):73 - HikariPool-2 - Start completed.
2022-09-21 09:09:16 INFO i.m.l.PropertiesLoggingLevelsConfigurer(configureLogLevelForPrefix):107 - Setting log level 'DEBUG' for logger: 'io.airbyte.bootloader'
2022-09-21 09:09:18 INFO i.a.w.c.DatabaseBeanFactory(configsDatabaseMigrationCheck):139 - Configs database configuration: 0.35.15.001 60000
2022-09-21 09:09:18 WARN i.a.a.TrackingClientSingleton(get):30 - Attempting to fetch an initialized track client. Initializing a default one.
2022-09-21 09:09:18 INFO i.a.w.t.TemporalUtils(getTemporalClientWhenConnected):220 - Waiting for temporal server...
2022-09-21 09:09:18 WARN i.a.w.t.TemporalUtils(getTemporalClientWhenConnected):231 - Waiting for namespace default to be initialized in temporal...
2022-09-21 09:09:21 INFO i.t.s.WorkflowServiceStubsImpl(<init>):188 - Created GRPC client for channel: ManagedChannelOrphanWrapper{delegate=ManagedChannelImpl{logId=1, target=airbyte-temporal-svc:7233}}
2022-09-21 09:09:26 INFO i.a.w.t.TemporalUtils(getTemporalClientWhenConnected):248 - Temporal namespace default initialized!
2022-09-21 09:09:26 ERROR i.m.r.Micronaut(handleStartupException):338 - Error starting Micronaut server: Failed to inject value for parameter [jobErrorReportingClient] of method [jobErrorReporter] of class: io.airbyte.scheduler.persistence.job_error_reporter.JobErrorReporter

Message: Multiple possible bean candidates found: [io.airbyte.scheduler.persistence.job_error_reporter.JobErrorReportingClient, io.airbyte.scheduler.persistence.job_error_reporter.JobErrorReportingClient]
Path Taken: new ApplicationInitializer() --> ApplicationInitializer.connectionManagerActivities --> List.connectionManagerActivities(GenerateInputActivity generateInputActivity,[JobCreationAndStatusUpdateActivity jobCreationAndStatusUpdateActivity],ConfigFetchActivity configFetchActivity,ConnectionDeletionActivity connectionDeletionActivity,CheckConnectionActivity checkConnectionActivity,AutoDisableConnectionActivity autoDisableConnectionActivity,StreamResetActivity streamResetActivity,RecordMetricActivity recordMetricActivity,WorkflowConfigActivity workflowConfigActivity,RouteToSyncTaskQueueActivity routeToSyncTaskQueueActivity) --> new JobCreationAndStatusUpdateActivityImpl(SyncJobFactory jobFactory,JobPersistence jobPersistence,TemporalWorkerRunFactory temporalWorkerRunFactory,WorkerEnvironment workerEnvironment,LogConfigs logConfigs,JobNotifier jobNotifier,JobTracker jobTracker,ConfigRepository configRepository,JobCreator jobCreator,StreamResetPersistence streamResetPersistence,[JobErrorReporter jobErrorReporter]) --> JobErrorReporter.jobErrorReporter(String airbyteVersion,ConfigRepository configRepository,DeploymentMode deploymentMode,[JobErrorReportingClient jobErrorReportingClient],WebUrlHelper webUrlHelper)
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [jobErrorReportingClient] of method [jobErrorReporter] of class: io.airbyte.scheduler.persistence.job_error_reporter.JobErrorReporter

Message: Multiple possible bean candidates found: [io.airbyte.scheduler.persistence.job_error_reporter.JobErrorReportingClient, io.airbyte.scheduler.persistence.job_error_reporter.JobErrorReportingClient]
Path Taken: new ApplicationInitializer() --> ApplicationInitializer.connectionManagerActivities --> List.connectionManagerActivities(GenerateInputActivity generateInputActivity,[JobCreationAndStatusUpdateActivity jobCreationAndStatusUpdateActivity],ConfigFetchActivity configFetchActivity,ConnectionDeletionActivity connectionDeletionActivity,CheckConnectionActivity checkConnectionActivity,AutoDisableConnectionActivity autoDisableConnectionActivity,StreamResetActivity streamResetActivity,RecordMetricActivity recordMetricActivity,WorkflowConfigActivity workflowConfigActivity,RouteToSyncTaskQueueActivity routeToSyncTaskQueueActivity) --> new JobCreationAndStatusUpdateActivityImpl(SyncJobFactory jobFactory,JobPersistence jobPersistence,TemporalWorkerRunFactory temporalWorkerRunFactory,WorkerEnvironment workerEnvironment,LogConfigs logConfigs,JobNotifier jobNotifier,JobTracker jobTracker,ConfigRepository configRepository,JobCreator jobCreator,StreamResetPersistence streamResetPersistence,[JobErrorReporter jobErrorReporter]) --> JobErrorReporter.jobErrorReporter(String airbyteVersion,ConfigRepository configRepository,DeploymentMode deploymentMode,[JobErrorReportingClient jobErrorReportingClient],WebUrlHelper webUrlHelper)
        at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2087) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.airbyte.workers.config.$JobErrorReportingBeanFactory$JobErrorReporter3$Definition.build(Unknown Source) ~[io.airbyte-airbyte-workers-0.40.7.jar:?]
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.airbyte.workers.temporal.scheduling.activities.$JobCreationAndStatusUpdateActivityImpl$Definition.build(Unknown Source) ~[io.airbyte-airbyte-workers-0.40.7.jar:?]
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.airbyte.workers.config.$ActivityBeanFactory$ConnectionManagerActivities1$Definition.build(Unknown Source) ~[io.airbyte-airbyte-workers-0.40.7.jar:?]
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1680) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.AbstractBeanResolutionContext.findBean(AbstractBeanResolutionContext.java:84) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.AbstractInitializableBeanDefinition.resolveOptionalBean(AbstractInitializableBeanDefinition.java:2178) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.AbstractInitializableBeanDefinition.findBeanForField(AbstractInitializableBeanDefinition.java:1843) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.airbyte.workers.$ApplicationInitializer$Definition.injectBean(Unknown Source) ~[io.airbyte-airbyte-workers-0.40.7.jar:?]
        at io.airbyte.workers.$ApplicationInitializer$Definition.build(Unknown Source) ~[io.airbyte-airbyte-workers-0.40.7.jar:?]
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2853) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:3511) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistrations(DefaultBeanContext.java:3457) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:3427) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:1381) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:903) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:893) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.event.ApplicationEventPublisherFactory$2.lambda$$0(ApplicationEventPublisherFactory.java:217) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.core.util.SupplierUtil$2.initialize(SupplierUtil.java:77) ~[micronaut-core-3.6.3.jar:3.6.3]
        at io.micronaut.core.util.SupplierUtil$2.get(SupplierUtil.java:72) ~[micronaut-core-3.6.3.jar:3.6.3]
        at io.micronaut.context.event.ApplicationEventPublisherFactory$2.publishEvent(ApplicationEventPublisherFactory.java:229) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.http.server.netty.NettyHttpServer.lambda$fireStartupEvents$15(NettyHttpServer.java:574) ~[micronaut-http-server-netty-3.6.3.jar:3.6.3]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at io.micronaut.http.server.netty.NettyHttpServer.fireStartupEvents(NettyHttpServer.java:568) ~[micronaut-http-server-netty-3.6.3.jar:3.6.3]
        at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:297) ~[micronaut-http-server-netty-3.6.3.jar:3.6.3]
        at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:104) ~[micronaut-http-server-netty-3.6.3.jar:3.6.3]
        at io.micronaut.runtime.Micronaut.lambda$start$2(Micronaut.java:81) ~[micronaut-context-3.6.3.jar:3.6.3]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:79) ~[micronaut-context-3.6.3.jar:3.6.3]
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:323) ~[micronaut-context-3.6.3.jar:3.6.3]
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:309) ~[micronaut-context-3.6.3.jar:3.6.3]
        at io.airbyte.workers.Application.main(Application.java:12) ~[io.airbyte-airbyte-workers-0.40.7.jar:?]
Caused by: io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [io.airbyte.scheduler.persistence.job_error_reporter.JobErrorReportingClient, io.airbyte.scheduler.persistence.job_error_reporter.JobErrorReportingClient]
        at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:2472) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultApplicationContext.findConcreteCandidate(DefaultApplicationContext.java:488) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.lastChanceResolve(DefaultBeanContext.java:3249) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:3127) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:3058) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.findBeanDefinition(DefaultBeanContext.java:788) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2790) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.6.3.jar:3.6.3]
```

## Steps to Reproduce
1. (Don't know if this is required): Change the namespace in ``kube/overlays/stable/kustomization.yaml`` from ``default`` to ``airbyte``
2. Deploy airbyte using ``kubectl apply -k kube/overlays/stable``
--> The worker pod constantly crashes

## Are you willing to submit a PR?
If you help me finding the issue - yes :-)

**Comment by oliverzgy** [comment]
It happened to docker-compose deployment, too.

**Comment by salima-airbyte** [comment]
The fix has been merged, and hasn't been released yet.

**Comment by OmarSultan85** [comment]
Where u able to fix this?

**Comment by luancaarvalho** [comment]
Hello Guys !
It also happened with helm chart version 0.41.1 deploy and in helm we face another error which is the duplicated minIO resource at the chart !

<img width="631" alt="image" src="https://user-images.githubusercontent.com/34407796/191615383-4ec883a8-cf1b-417f-aec6-91e604b324cf.png">

**Comment by gosusnp** [comment]
The micronaut related issues that prevented the `airbyte-worker` from starting should have been fixed in `0.40.8`.

@luancaarvalho, after testing the helm charts are running into another issue. I suspect it might be related to https://github.com/airbytehq/airbyte/issues/16586 instead.

**Comment by andnig** [comment]
Thank you very much for the fix. Can confirm that the kubernetes issues are fixed. Closing for that matter 👍

**Comment by Nomad-IC** [comment]
I specified `WORKER_LOGS_STORAGE_TYPE=S3` variable in `.env` file. It solved problem for me.
