### ISSUE TITLE
Source ZohoCRM: ValueError Invalid isoformat string

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#17098]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#1890](https://airbyte7538.zendesk.com/agent/tickets/1890)
**Priority:** normal
**Group:** Community Assistance Engineer
**Assignee:** Sajarin

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><ul style="margin: 0 0 0 10px; padding: 0 0 0 20px;" dir="auto">
<li style="padding-bottom: 10px;">Is this your first time deploying Airbyte?: No</li>
<li style="padding-bottom: 10px;">OS Version / Instance: Ubuntu</li>
<li style="padding-bottom: 10px;">Memory / Disk: you can use something like 8 GB</li>
<li style="padding-bottom: 10px;">Deployment:  Docker</li>
<li style="padding-bottom: 10px;">Airbyte Version: 0.40.0 alpha</li>
<li style="padding-bottom: 10px;">Source name/version:  ZohoCRM 0.1.0</li>
<li style="padding-bottom: 10px;">Destination name/version: Snowflake 0.4.34</li>
<li style="padding-bottom: 10px;">Step: Sync</li>
<li style="padding-bottom: 10px;">Description: After passing the connection creation, the sync fails with the following error:</li>
</ul>
<p dir="auto">Failure Origin: source, Message: Something went wrong within the source connector<em>2022-08-10 15:53:14 -</em> Additional Failure Information: io.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source cannot be stopped!</p> 

[<a href="https://discuss.airbyte.io/t/zohocrm-source-fails-to-connect/2203/1" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Sajarin on 2022-08-12 at 19:35:*

<blockquote><div class="zd-comment" dir="auto">Hi @mijbel, thanks for your post! Could you share the full sync logs for the failed sync? The <code>source cannot be stopped</code> is a fairly generic log error so we need more context.&nbsp;<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-08-21 at 08:42:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Hi <a href="/u/sajarin" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">@sajarin</a> … sorry for the delay I missed your reply. I’ve attached the sync logs here.<br>
<a href="https://discuss.airbyte.io/uploads/short-url/6VHm00gQ8wCV1FBv2uerp470G1d.txt" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">logs-175.txt</a> (293.2 KB)</p> 

 [<a href="https://discuss.airbyte.io/t/source-zohocrm-fails-to-connect/2203/3" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Sajarin on 2022-08-24 at 07:59:*

<blockquote><div class="zd-comment" dir="auto">Hi @mljbel, thanks for posting the logs. I will try to see if I can duplicate the issue and report back with any findings. Seems like one of the streams is broken or isn't working but I will try to see if I can replicate it on my end. Thanks for making this post!<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-08-30 at 15:41:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Hi <a href="/u/sajarin" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">@sajarin</a> … any luck duplicating the issue?</p> 

 [<a href="https://discuss.airbyte.io/t/source-zohocrm-fails-to-connect/2203/5" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-23 at 15:50:*

<blockquote><div class="zd-comment" dir="auto">Hello Mijbel I created the issue <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/17098">https://github.com/airbytehq/airbyte/issues/17098</a><br>&nbsp;<br>I found the error when Zoho try to convert a datetime.<br><pre><code>2022-08-21 08:19:19 [44msource[0m &gt; Invalid isoformat string: '2022-07-01T00:00:00Z'<br>Traceback (most recent call last):<br>  File "/airbyte/integration_code/main.py", line 13, in &lt;module&gt;<br>    launch(source, sys.argv[1:])<br>  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 127, in launch<br>    for message in source_entrypoint.run(parsed_args):<br>  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 118, in run<br>    for message in generator:<br>  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 123, in read<br>    raise e<br>  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 119, in read<br>    internal_config=internal_config,<br>  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 159, in _read_stream<br>    for record in record_iterator:<br>  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 248, in _read_full_refresh<br>    for record in records:<br>  File "/airbyte/integration_code/source_zoho_crm/streams.py", line 88, in read_records<br>    for record in super().read_records(*args, **kwargs):<br>  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 353, in read_records<br>    stream_state=stream_state, stream_slice=stream_slice, next_page_token=next_page_token<br>  File "/airbyte/integration_code/source_zoho_crm/streams.py", line 100, in request_headers<br>    last_modified_dt = datetime.datetime.fromisoformat(last_modified)<br>ValueError: Invalid isoformat string: '2022-07-01T00:00:00Z'</code></pre>A workaround for now it is to use only full refresh sync mode.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
Error: 
```
2022-08-21 08:19:19 [44msource[0m > Invalid isoformat string: '2022-07-01T00:00:00Z'
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 127, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 118, in run
    for message in generator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 123, in read
    raise e
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 119, in read
    internal_config=internal_config,
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 159, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 248, in _read_full_refresh
    for record in records:
  File "/airbyte/integration_code/source_zoho_crm/streams.py", line 88, in read_records
    for record in super().read_records(*args, **kwargs):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 353, in read_records
    stream_state=stream_state, stream_slice=stream_slice, next_page_token=next_page_token
  File "/airbyte/integration_code/source_zoho_crm/streams.py", line 100, in request_headers
    last_modified_dt = datetime.datetime.fromisoformat(last_modified)
ValueError: Invalid isoformat string: '2022-07-01T00:00:00Z'
```

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-25 at 13:24:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Thanks Marcos. FYI I’m using full refresh-overwrite when getting the error.</p> 

 [<a href="https://discuss.airbyte.io/t/source-zohocrm-fails-to-connect/2203/7" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by bibimorlet** [comment]
I have the same error. this issue seems to be linked with this one #14523

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by valentiniqidi** [comment]
Same problem
