### ISSUE TITLE
Source Amazon Seller Partner: invalid input for double precision

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#17163]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#2386](https://airbyte7538.zendesk.com/agent/tickets/2386)
**Priority:** normal
**Group:** Community Assistance Engineer
**Assignee:** Marcos Marx

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><ul style="margin: 0 0 0 10px; padding: 0 0 0 20px;" dir="auto">
<li style="padding-bottom: 10px;">Is this your first time deploying Airbyte?: <strong>Yes</strong>
</li>
<li style="padding-bottom: 10px;">OS Version / Instance: <strong>Windows</strong>
</li>
<li style="padding-bottom: 10px;">Memory / Disk:</li>
<li style="padding-bottom: 10px;">Deployment:  <strong>Local Docker Containers</strong>
</li>
<li style="padding-bottom: 10px;">Airbyte Version: <strong>0.40.4</strong>
</li>
<li style="padding-bottom: 10px;">Source name/version:  <strong>Amazon Seller Partner</strong>
</li>
<li style="padding-bottom: 10px;">Destination name/version: <strong>Postgres 15.0 or MYSQL 8.0.30</strong>
</li>
<li style="padding-bottom: 10px;">Step: <strong>The issue is happening during sync</strong>
</li>
<li style="padding-bottom: 10px;">Description: <strong>I tried to normalize the amazon seller partner data in a mysql database first and then moved to postgress for another try. I can fetch the data in raw json with not problem but i need them normalized.</strong>
</li>
</ul>
<p dir="auto">This is the main error in logs:</p>
<pre style="max-width: 694px; word-wrap: break-word;"><code style="background-color: #f9f9f9; display: block; overflow: auto; padding: 2px 5px;">21 of 56 ERROR creating table model public.listfinancialeventgroups_beginningbalance.................................... [ERROR in 0.19s]
22 of 56 ERROR creating table model public.listfinancialeventgroups_convertedtotal...................................... [ERROR in 0.20s]
23 of 56 ERROR creating table model public.listfinancialeventgroups_originaltotal....................................... [ERROR in 0.18s]
Database Error in model get_merchant_listings_all_data (models/generated/airbyte_tables/public/get_merchant_listings_all_data.sql)
invalid input syntax for type double precision: ""
compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/public/get_merchant_listings_all_data.sql
Database Error in model listfinancialeventgroups_beginningbalance (models/generated/airbyte_tables/public/listfinancialeventgroups_beginningbalance.sql)
invalid input syntax for type bigint: "0.0"
compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/public/listfinancialeventgroups_beginningbalance.sql
Database Error in model listfinancialeventgroups_convertedtotal (models/generated/airbyte_tables/public/listfinancialeventgroups_convertedtotal.sql)
invalid input syntax for type bigint: "693.09"
compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/public/listfinancialeventgroups_convertedtotal.sql
Database Error in model listfinancialeventgroups_originaltotal (models/generated/airbyte_tables/public/listfinancialeventgroups_originaltotal.sql)
</code></pre>
<p dir="auto"><a href="https://discuss.airbyte.io/uploads/short-url/v5P0knf0z5KDldfVRLrTEZseuEg.txt" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">logs-142.txt</a> (278.7 KB)</p> 

[<a href="https://discuss.airbyte.io/t/invalid-input-syntax-for-type-normalization-asp-postgres-mysql/2670/1" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-21 at 17:18:*

<blockquote><div class="zd-comment" dir="auto">Can you update the schema of connection in Replication Tab?<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-23 at 15:36:*

<blockquote><div class="zd-comment" dir="auto">Yes.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-26 at 01:14:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Is there anything else i can do or is this a problem within the connector?</p> 

 [<a href="https://discuss.airbyte.io/t/invalid-input-syntax-for-type-normalization-asp-postgres-mysql/2670/4" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-26 at 19:34:*

<blockquote><div class="zd-comment" dir="auto">&nbsp;<br>Sorry the delay here Alexander. Looks for FinancialGroups stream all amount/numeric values are integer:&nbsp;<br><a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/ListFinancialEventGroups.json">https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/ListFinancialEventGroups.json</a><br>&nbsp;<br>It'll need a fix to update the values to numeric. I escalated your issue to Github <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/17163">https://github.com/airbytehq/airbyte/issues/17163</a><br>I'll return to you when the issue is fixed.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-29 at 17:41:*

<blockquote><div class="zd-comment" dir="auto">A fix was released for Amazon Seller Partner version 0.2.26 correcting the types for ListFinancialEventGroup stream.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-06 at 20:22:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">That 403 response seems to be from “GET_SALES_AND_TRAFFIC_REPORT”, which is one of the newly added schemas i forgot to turn off.</p>
<p dir="auto">I tried a sync with only “GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL” and in the<br>
<a href="/uploads/short-url/5poiJp3AVBUEtRr8kuQSju6JmLP.txt" style="color: #006699; font-weight: bold; text-decoration: none" rel="noreferrer">logs</a> (57.3 KB) for that i cant find an error with the 403 statuscode.</p>
<p dir="auto">We used “GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL” before, so permissions should not be an issue. Right before setting up the new connection this table was synced successfully with the old one. I double checked the credentials, there are correct and the same as before.<br>
But i will let the permissions be checked, just to be save.</p> 

 [<a href="https://discuss.airbyte.io/t/invalid-input-syntax-for-type-normalization-asp-postgres-mysql/2670/9" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-07 at 12:23:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">The traceback:</p>
<pre style="max-width: 694px; word-wrap: break-word"><code style="background-color: #f9f9f9; display: block; overflow: auto; padding: 2px 5px">Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 113, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 182, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 285, in _read_full_refresh
    for record in records:
  File "/airbyte/integration_code/source_amazon_seller_partner/streams.py", line 359, in read_records
    raise Exception(f"Unknown response for stream `{self.name}`. Response body {report_payload}")
Exception: Unknown response for stream `GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL`. Response body {'reportType': 'GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL', 'processingStatus': 'IN_PROGRESS', 'marketplaceIds': ['A1PA6795UKMFR9'], 'reportId': '3875174019271', 'dataEndTime': '2022-10-06T19:56:32+00:00', 'createdTime': '2022-10-06T19:56:32+00:00', 'processingStartTime': '2022-10-06T19:56:36+00:00', 'dataStartTime': '2022-09-16T00:00:00+00:00'}
</code></pre>
<p dir="auto">Reading the code looks the timeout exceed before the report was finished. My suggestion is to increase the parameter: <strong>Max wait time for reports (in seconds)</strong></p> 

 [<a href="https://discuss.airbyte.io/t/invalid-input-syntax-for-type-normalization-asp-postgres-mysql/2670/10" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-11 at 10:57:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Unfortunately the table “get_merchant_listings_all_data” still throws an error while normalazing</p>
<pre style="max-width: 694px; word-wrap: break-word"><code style="background-color: #f9f9f9; display: block; overflow: auto; padding: 2px 5px"> 1 of 1 START table model mszweirad.get_merchant_listings_all_data....................................................... [RUN]
2022-10-11 10:48:09 normalization &gt; 1 of 1 ERROR creating table model mszweirad.get_merchant_listings_all_data.............................................. [ERROR in 0.11s]
2022-10-11 10:48:09 normalization &gt; Finished running 1 table model in 0.31s.
2022-10-11 10:48:09 normalization &gt; Completed with 1 error and 0 warnings:
2022-10-11 10:48:09 normalization &gt; Database Error in model get_merchant_listings_all_data (models/generated/airbyte_incremental/mszweirad/get_merchant_listings_all_data.sql)
2022-10-11 10:48:09 normalization &gt;   1292 (22007): Truncated incorrect CHAR(1050) value: 'Der Ständer wird aufgrund seiner standfesten Spreizung besonders für E-Räder, Transporträder, Tandems und Räder mit Kinders'
2022-10-11 10:48:09 normalization &gt;   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_incremental/mszweirad/get_merchant_listings_all_data.sql
2022-10-11 10:48:09 normalization &gt; Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
</code></pre>
<p dir="auto"><a href="https://discuss.airbyte.io/uploads/short-url/mZ2npmkbLQFhwZyhceQ8LHxbVIS.txt" style="color: #006699; font-weight: bold; text-decoration: none" rel="noreferrer">75163712_cfa4_4f06_88be_82fab7cb88db_logs_167_txt.txt</a> (130.6 KB)</p> 

 [<a href="https://discuss.airbyte.io/t/invalid-input-syntax-for-type-normalization-asp-postgres-mysql/2670/12" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-17 at 12:05:*

<blockquote><div class="zd-comment" dir="auto">Sorry the delay here Alexander, this errors is because there is a string being casted to a wrong data type. Could you search and check what field has this value?&nbsp;<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-18 at 17:45:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">No worries, the field containing this value is “item-description”:</p>
<p dir="auto"></p><div><a href="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/7/7067d5c5364080ff48ee010cf1fc873826c96138.png" title="image" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none"><img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/7/7067d5c5364080ff48ee010cf1fc873826c96138.png" alt="image" width="auto" height="auto" style="max-width: 100%"><div style="display: none">
<span>image</span><span>892×25 5.56 KB</span>
</div></a></div><p dir="auto"></p>
<p dir="auto">I also updated to 0.40.15 and get a new error for the field"_airbyte_data":</p>
<pre style="max-width: 694px; word-wrap: break-word"><code style="background-color: #f9f9f9; display: block; overflow: auto; padding: 2px 5px">2022-10-18 17:33:49 normalization &gt; Completed with 1 error and 0 warnings:
2022-10-18 17:33:49 normalization &gt; Database Error in model get_merchant_listings_all_data (models/generated/airbyte_tables/mszweirad/get_merchant_listings_all_data.sql)
2022-10-18 17:33:49 normalization &gt;   1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CHAR) as asin1,
2022-10-18 17:33:49 normalization &gt;       json_value(_airbyte_data, 
2022-10-18 17:33:49 normalization &gt;       '$."asin2"' RETURNING CHAR) a' at line 14
2022-10-18 17:33:49 normalization &gt;   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/mszweirad/get_merchant_listings_all_data.sql
2022-10-18 17:33:49 normalization &gt; Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
</code></pre>
<p dir="auto"><a href="https://discuss.airbyte.io/uploads/short-url/1zweGAIpbcrJeYbOJAdRbvXuJ9U.txt" style="color: #006699; font-weight: bold; text-decoration: none" rel="noreferrer">75163712_cfa4_4f06_88be_82fab7cb88db_logs_174_txt.txt</a> (51.0 KB)</p> 

 [<a href="https://discuss.airbyte.io/t/invalid-input-syntax-for-type-normalization-asp-postgres-mysql/2670/14" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-19 at 17:16:*

<blockquote><div class="zd-comment" dir="auto">Alexander can you try to update the schema of Amazon Seller Partner too and try with Pg destination?<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-19 at 20:11:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Yes refreshing the schema seemed to solve the latest problem (the error in “_airbyte_data”).<br>
But with either source or destination structure the truncated error stays.</p> 

 [<a href="https://discuss.airbyte.io/t/invalid-input-syntax-for-type-normalization-asp-postgres-mysql/2670/16" rel="noreferrer">Discourse post</a>]</div></blockquote>
