### ISSUE TITLE
default_cursor_field: null found, array expected

### ISSUE THREAD

**Issue by amondnet** [airbytehq/airbyte#17373]
## Environment
- **Airbyte version**:  0.40.10
- **OS Version / Instance**: Ubuntu 22.04
- **Deployment**: Docker
- **Source Connector and version**: mixpanel 0.1.26
- **Destination Connector and version**: postgres 0.3.26
- **Step where error happened**: Setup new connection

## Current Behavior
*Tell us what happens.*

default_cursor_field: null found, array expected

```
          {
  "streams": [
    {
      "stream": {
        "name": "funnels",
        "json_schema": {},
        "supported_sync_modes": ["full_refresh", "incremental"],
        "default_cursor_field": ["date"]
      },
      "sync_mode": "incremental",
      "destination_sync_mode": "overwrite"
    },
    {
      "stream": {
        "name": "engage",
        "json_schema": {},
        "supported_sync_modes": ["full_refresh"],
        "default_cursor_field": null
      },
      "sync_mode": "full_refresh",
      "destination_sync_mode": "overwrite"
    },
    {
      "stream": {
        "name": "annotations",
        "json_schema": {},
        "supported_sync_modes": ["full_refresh"]
      },
      "sync_mode": "full_refresh",
      "destination_sync_mode": "overwrite"
    },
    {
      "stream": {
        "name": "export",
        "json_schema": {},
        "supported_sync_modes": ["full_refresh", "incremental"],
        "default_cursor_field": ["time"]
      },
      "sync_mode": "incremental",
      "destination_sync_mode": "append"
    },
    {
      "stream": {
        "name": "cohorts",
        "json_schema": {},
        "supported_sync_modes": ["full_refresh"]
      },
      "sync_mode": "full_refresh",
      "destination_sync_mode": "overwrite"
    },
    {
      "stream": {
        "name": "cohort_members",
        "json_schema": {},
        "supported_sync_modes": ["full_refresh"]
      },
      "sync_mode": "full_refresh",
      "destination_sync_mode": "overwrite"
    },
    {
      "stream": {
        "name": "revenue",
        "json_schema": {},
        "supported_sync_modes": ["full_refresh", "incremental"],
        "default_cursor_field": ["date"]
      },
      "sync_mode": "incremental",
      "destination_sync_mode": "append"
    }
  ]
}
```

https://github.com/airbytehq/airbyte/blob/1c40fe6644f1110eab2f1e9ebadc528bdbd14099/airbyte-protocol/protocol-models/src/main/resources/airbyte_protocol/airbyte_protocol.yaml#L250
Replacing this line solved the problem.

 `type: array` -> `type: [ "array", "null" ]`.

## Expected Behavior
*Tell us what should happen.*

## Logs

[mixpanel.log](https://github.com/airbytehq/airbyte/files/9672660/mixpanel.log)

## Steps to Reproduce
1. Add mixpanel source.
2. Add destination.
3. Create new connection.

## Are you willing to submit a PR?

Yes.

**Comment by harshithmullapudi** [comment]
Hey, removing engage stream and running the sync can you check if that is working? As in the sync running?

**Comment by chanronson** [comment]
> 

It's not possible to uncheck the engage stream during new source set up :(

**Comment by marcosmarxm** [comment]
I was able to reproduce this locally:
```
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:132) ~[io.airbyte-airbyte-workers-0.40.10.jar:?]
	at io.airbyte.workers.temporal.discover.catalog.DiscoverCatalogActivityImpl.run(DiscoverCatalogActivityImpl.java:93) ~[io.airbyte-airbyte-workers-0.40.10.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at io.temporal.internal.activity.POJOActivityTaskHandler$POJOActivityInboundCallsInterceptor.execute(POJOActivityTaskHandler.java:214) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.activity.POJOActivityTaskHandler$POJOActivityImplementation.execute(POJOActivityTaskHandler.java:180) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.activity.POJOActivityTaskHandler.handle(POJOActivityTaskHandler.java:120) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:204) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:164) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93) ~[temporal-sdk-1.8.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: io.airbyte.workers.exception.WorkerException: Integration failed to output a catalog struct.
	at io.airbyte.workers.general.DefaultDiscoverCatalogWorker.run(DefaultDiscoverCatalogWorker.java:82) ~[io.airbyte-airbyte-workers-0.40.10.jar:?]
	at io.airbyte.workers.general.DefaultDiscoverCatalogWorker.run(DefaultDiscoverCatalogWorker.java:32) ~[io.airbyte-airbyte-workers-0.40.10.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:161) ~[io.airbyte-airbyte-workers-0.40.10.jar:?]
	... 1 more
```

**Comment by marcosmarxm** [comment]
I submitted a fix to this issue.

**Comment by evantahler** [comment]
should this be closed by https://github.com/airbytehq/airbyte/pull/17699 ?
