### ISSUE TITLE
Worker: Failed to inject value for parameter [dslContext] of method [configDatabase] of class: io.airbyte.db.Database

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#17413]
## Environment
- **Airbyte version**:  0.40.9
- **OS Version / Instance**: macOS
- **Deployment**: Docker
- **Source Connector and version**: NA
- **Destination Connector and version**: NA
- **Step where error happened**: Deploy

## Current Behavior
Trying to run a new instance of Airbyte. Web App is accessible but no connection to the Airbyte worker.

## Expected Behavior
*Tell us what should happen.*

## Logs
```
2022-09-29 18:38:11 ERROR i.m.r.Micronaut(handleStartupException):338 - Error starting Micronaut server: Failed to inject value for parameter [dslContext] of method [configDatabase] of class: io.airbyte.db.Database

Message: No bean of type [org.jooq.DSLContext] exists for the given qualifier: @Named('config'). Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
Path Taken: new ApplicationInitializer() --> ApplicationInitializer.checkConnectionActivities --> List.checkConnectionActivities([CheckConnectionActivity checkConnectionActivity]) --> CheckConnectionActivityImpl.secretsHydrator --> SecretsHydrator.secretsHydrator([SecretPersistence secretPersistence]) --> SecretPersistence.defaultSecretPersistence([Database configDatabase]) --> Database.configDatabase([DSLContext dslContext])
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [dslContext] of method [configDatabase] of class: io.airbyte.db.Database

Message: No bean of type [org.jooq.DSLContext] exists for the given qualifier: @Named('config'). Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
Path Taken: new ApplicationInitializer() --> ApplicationInitializer.checkConnectionActivities --> List.checkConnectionActivities([CheckConnectionActivity checkConnectionActivity]) --> CheckConnectionActivityImpl.secretsHydrator --> SecretsHydrator.secretsHydrator([SecretPersistence secretPersistence]) --> SecretPersistence.defaultSecretPersistence([Database configDatabase]) --> Database.configDatabase([DSLContext dslContext])
        at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2087) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.airbyte.workers.config.$DatabaseBeanFactory$ConfigDatabase0$Definition.build(Unknown Source) ~[io.airbyte-airbyte-workers-0.40.9.jar:?]
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.6.3.jar:3.6.3]
        at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.6.3.jar:3.6.3]
```

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by marcosmarxm** [comment]
Complete log file: 
[worker.log](https://github.com/airbytehq/airbyte/files/9678238/worker.log)

**Comment by marcosmarxm** [comment]
Zendesk ticket #[2473](https://airbyte7538.zendesk.com/agent/tickets/2473) has been linked to this issue.

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-29 at 18:48:*

<blockquote><div class="zd-comment" dir="auto">Thanks for raising the issue Mateo. I created the issue <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/17413">https://github.com/airbytehq/airbyte/issues/17413</a> team is working on the solution.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-29 at 19:11:*

<blockquote><div class="zd-comment" dir="auto">Please upgrade to version 0.40.10 a fix was released for this issue in this version.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-30 at 14:04:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">just did that… working as expected! thanks</p> 

 [<a href="https://discuss.airbyte.io/t/airbyte-0-40-9-worker-failure-failed-to-inject-value-for-parameter-dslcontext-of-method-configdatabase-of-class-io-airbyte-db-database/2742/5" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by ext-gvillafane** [comment]
Getting a similar error in version 0.40.10 🤔 

```
2022-10-05 10:12:17 ERROR i.m.r.Micronaut(handleStartupException):338 - Error starting Micronaut server: Failed to inject value for parameter [localockerMount[] of method [checkDockerProcessFactory] of class: io.airbyte.workers.process.ProcessFactory
Message: Failed to inject value for parameter [localDockerMount] of method [checkDockerProcessFactory] of class: io.airbyte.workers.process.ProcessFactory                                                                                                                                              Message: Error resolving property value [${airbyte.local.docker-mount}]. Property doesn't exist                                                     Path Taken: new ApplicationInitializer() --> ApplicationInitializer.checkConnectionActivities --> List.checkConnectionActivities([CheckConnectionActvity checkConnectionActivity[]) --> new CheckConnectionActivityImpl(WorkerConfigs workerConfigs,[ProcessFactory processFactory],SecretsHydrator secretsHydrator,Path workspaceRoot,WorkerEnvironment workerEnvironment,LogConfigs logConfigs,AirbyteApiClient airbyteApiClient,String airbyteVersion) --> ProcessFactory.checkDockerProcessFactory(WorkerConfigs workerConfigs,String dockerNetwork,[String localDockerMount],String localRoot,String workspaceDockerMount,String workspaceRoot)                                                                                                                Path Taken: new ApplicationInitializer() --> ApplicationInitializer.checkConnectionActivities --> List.checkConnectionActivities([CheckConnectionActvity checkConnectionActivity[]) --> new CheckConnectionActivityImpl(WorkerConfigs workerConfigs,[ProcessFactory processFactory],SecretsHydrator secretsHydrator,Path workspaceRoot,WorkerEnvironment workerEnvironment,LogConfigs logConfigs,AirbyteApiClient airbyteApiClient,String airbyteVersion) --> ProcessFactory.checkDockerProcessFactory(WorkerConfigs workerConfigs,String dockerNetwork,[String localDockerMount],String localRoot,String workspaceDockerMount,String workspaceRoot)                                                                                                                io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [localDockerMount] of method [checkDockerProcessFctory[] of class: io.airbyte.workers.process.ProcessFactory
Message: Failed to inject value for parameter [localDockerMount] of method [checkDockerProcessFactory] of class: io.airbyte.workers.process.ProcessFactory
Message: Error resolving property value [${airbyte.local.docker-mount}]. Property doesn't exist
Path Taken: new ApplicationInitializer() --> ApplicationInitializer.checkConnectionActivities --> List.checkConnectionActivities([CheckConnectionActvity checkConnectionActivity[]) --> new CheckConnectionActivityImpl(WorkerConfigs workerConfigs,[ProcessFactory processFactory],SecretsHydrator secretsHydrator,Path workspaceRoot,WorkerEnvironment workerEnvironment,LogConfigs logConfigs,AirbyteApiClient airbyteApiClient,String airbyteVersion) --> ProcessFactory.checkDockerProcessFactory(WorkerConfigs workerConfigs,String dockerNetwork,[String localDockerMount],String localRoot,String workspaceDockerMount,String workspaceRoot)
Path Taken: new ApplicationInitializer() --> ApplicationInitializer.checkConnectionActivities --> List.checkConnectionActivities([CheckConnectionActvity checkConnectionActivity[]) --> new CheckConnectionActivityImpl(WorkerConfigs workerConfigs,[ProcessFactory processFactory],SecretsHydrator secretsHydrator,Path workspaceRoot,WorkerEnvironment workerEnvironment,LogConfigs logConfigs,AirbyteApiClient airbyteApiClient,String airbyteVersion) --> ProcessFactory.checkDockerProcessFactory(WorkerConfigs workerConfigs,String dockerNetwork,[String localDockerMount],String localRoot,String workspaceDockerMount,String workspaceRoot) 
```
