### ISSUE TITLE
Source File: `password` field is being used for `port` number

### ISSUE THREAD

**Issue by terekete** [airbytehq/airbyte#17517]
## Environment
- **Airbyte version**:  Version: 0.40.10
- **OS Version / Instance**: Linux Centos 8 Latest
- **Deployment**:  Kubernetes
- **Source Connector and version**:  File Source Connector
- **Destination Connector and version**:  NA
- **Step where error happened**:
Create a SSH file Source, enter the username and password fields reports an error where the password is seen as the port number.

## Expected Behavior
Ssh Connection should utilize the port already set and the password field should not interfere
## Steps to Reproduce
1. Create a File source with SSH
2. Set a username and password, keep port as 22. Password includes a '#'. Example: Password1234#

## Error: 
```
Failed to load scp:///home/t832967/basic.csv: ValueError("Port could not be cast to integer value as 'Password1234'") Traceback (most recent call last): File "/airbyte/integration_code/source_file/source.py", line 87,
 in check with client.reader.open(): File "/airbyte/integration_code/source_file/client.py", line 86,
 in open self._file = self._open() File "/airbyte/integration_code/source_file/client.py", line 122,
 in _open return smart_open.open(uri, transport_params=transport_params, **self.args) File "/usr/local/lib/python3.9/site-packages/smart_open/smart_open_lib.py", line 224,
 in open binary = _open_binary_stream(uri, binary_mode, transport_params) File "/usr/local/lib/python3.9/site-packages/smart_open/smart_open_lib.py", line 400,
 in _open_binary_stream fobj = submodule.open_uri(uri, mode, transport_params) File "/usr/local/lib/python3.9/site-packages/smart_open/ssh.py", line 71,
 in open_uri parsed_uri = parse_uri(uri) File "/usr/local/lib/python3.9/site-packages/smart_open/ssh.py", line 64,
 in parse_uri port=int(split_uri.port or DEFAULT_PORT), File "/usr/local/lib/python3.9/urllib/parse.py", line 178,
 in port raise ValueError(message) from None ValueError: Port could not be cast to integer value as 'Password1234'
```

**Comment by marcosmarxm** [comment]
This error is happening in `urllib` native lib from Python3.
>  in parse_uri port=int(split_uri.port or DEFAULT_PORT), File "/usr/local/lib/python3.9/urllib/parse.py", line 178,

I tried to use smart_open and urllib and both gave the same error.

**Comment by marcosmarxm** [comment]
If you remove the `#` from the end of your password the code works fine, lol.

**Comment by terekete** [comment]
Yeh! I see that , problem is that # is part of the password.

**Comment by marcosmarxm** [comment]
It should work fine, this limitation comes from other libs than the connector itself.

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
