### ISSUE TITLE
Investigate why permission problems are not caught in CHECK method

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#17612]
I found multiple connections that fail during the first run with an error that seems like it should be caught during `CHECK` method. Here is the error stack trace:
```
2022-09-27 17:29:35 [43mdestination[0m > Exception while starting consumer
Stack Trace: net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
Schema 'PUBLIC' already exists, but current role has no privileges on it. If this is unexpected and you cannot resolve this problem, contact your system administrator. ACCOUNTADMIN role may be required to manage the privileges on the object.
	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:127)
	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:67)
	at net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:451)
	at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:354)
	at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:488)
	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:198)
	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:135)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:768)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:678)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeInternal(SnowflakeStatementV1.java:287)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.execute(SnowflakeStatementV1.java:342)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at io.airbyte.db.jdbc.JdbcDatabase.lambda$execute$0(JdbcDatabase.java:47)
	at io.airbyte.db.jdbc.DefaultJdbcDatabase.execute(DefaultJdbcDatabase.java:46)
	at io.airbyte.db.jdbc.JdbcDatabase.execute(JdbcDatabase.java:47)
	at io.airbyte.integrations.destination.jdbc.JdbcSqlOperations.createSchemaIfNotExists(JdbcSqlOperations.java:47)
	at io.airbyte.integrations.destination.staging.StagingConsumerFactory.lambda$onStartFunction$1(StagingConsumerFactory.java:127)
	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15)
	at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.startTracked(BufferedStreamConsumer.java:118)
	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.start(FailureTrackingAirbyteMessageConsumer.java:34)
	at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:170)
	at io.airbyte.integrations.base.IntegrationRunner.lambda$runConsumer$2(IntegrationRunner.java:178)
	at io.airbyte.integrations.base.IntegrationRunner.watchForOrphanThreads(IntegrationRunner.java:207)
	at io.airbyte.integrations.base.IntegrationRunner.runConsumer(IntegrationRunner.java:177)
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:146)
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:97)
	at io.airbyte.integrations.destination.snowflake.SnowflakeDestination.main(SnowflakeDestination.java:30)

```

The stack trace above is from our own test [connection](https://cloud.airbyte.io/workspaces/b219cc07-1480-4e50-acdd-9a7268e47de9/connections/cc4470f2-42b6-429b-9440-caa8e7f2304a/status) , but there are 9 other similar failures.

**Comment by grishick** [comment]
Also similar to #16992

**Comment by grishick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Destinations-6332532d6893ce001c7a56a7/issues/airbytehq/airbyte/17612?planning-poker) with Zenhub @edgao @ryankfu

**Comment by edgao** [comment]
this looks like a dup of #16833 (https://github.com/airbytehq/airbyte/issues/16833#issuecomment-1253902932)
