### ISSUE TITLE
Source Amazon Ads: schema typed incorrectly, "Could not evaluate union" exception

### ISSUE THREAD

**Issue by animer3009** [airbytehq/airbyte#17623]
## Environment
- **Airbyte version**:  0.40.10
- **OS Version / Instance**:  Ubuntu 22.04, GCP
- **Deployment**: Docker 
- **Source Connector and version**: Amazon Ads 0.1.22
- **Destination Connector and version**: BigQuery (denormalized typed struct) 1.2.4
- **Step where error happened**: BigQuery (denormalized typed struct) Destination connector on time sync

## Current Behavior
I am regularly getting errors like this.

```
2022-09-16 23:07:15 destination > Exception while accepting message
Stack Trace: tech.allegro.schema.json2avro.converter.AvroConversionException: Failed to convert JSON to Avro: Could not evaluate union, field portfolioId is expected to be one of these: NULL, STRING. If this is a complex type, check if offending field (path: portfolioId) adheres to schema: 130457359476581
	at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.read(JsonGenericRecordReader.java:129)
	at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.read(JsonGenericRecordReader.java:118)
	at tech.allegro.schema.json2avro.converter.JsonAvroConverter.convertToGenericDataRecord(JsonAvroConverter.java:95)
	at io.airbyte.integrations.destination.s3.avro.AvroRecordFactory.getAvroRecord(AvroRecordFactory.java:44)
	at io.airbyte.integrations.destination.bigquery.BigQueryAvroSerializedBuffer.writeRecord(BigQueryAvroSerializedBuffer.java:46)
	at io.airbyte.integrations.destination.record_buffer.BaseSerializedBuffer.accept(BaseSerializedBuffer.java:92)
	at io.airbyte.integrations.destination.record_buffer.SerializedBufferingStrategy.addRecord(SerializedBufferingStrategy.java:61)
	at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.acceptTracked(BufferedStreamConsumer.java:138)
	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.accept(FailureTrackingAirbyteMessageConsumer.java:47)
	at io.airbyte.integrations.base.IntegrationRunner.consumeMessage(IntegrationRunner.java:259)
	at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:172)
	at io.airbyte.integrations.base.IntegrationRunner.lambda$runConsumer$2(IntegrationRunner.java:178)
	at io.airbyte.integrations.base.IntegrationRunner.watchForOrphanThreads(IntegrationRunner.java:207)
	at io.airbyte.integrations.base.IntegrationRunner.runConsumer(IntegrationRunner.java:177)
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:146)
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:97)
	at io.airbyte.integrations.destination.bigquery.BigQueryDenormalizedDestination.main(BigQueryDenormalizedDestination.java:200)
Caused by: org.apache.avro.AvroTypeException: Could not evaluate union, field portfolioId is expected to be one of these: NULL, STRING. If this is a complex type, check if offending field (path: portfolioId) adheres to schema: 130457359476581
	at tech.allegro.schema.json2avro.converter.AvroTypeExceptions.unionException(AvroTypeExceptions.java:28)
	at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.readUnion(JsonGenericRecordReader.java:294)
	at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.read(JsonGenericRecordReader.java:196)
	at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.read(JsonGenericRecordReader.java:170)
	at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.lambda$readRecord$0(JsonGenericRecordReader.java:152)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.readRecord(JsonGenericRecordReader.java:141)
	at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.read(JsonGenericRecordReader.java:127)
	... 16 more
```

The full log is attached. 
[logs-10.txt](https://github.com/airbytehq/airbyte/files/9590510/logs-10.txt)

**Comment by sh4sh** [comment]
Here is the source of the exception: https://github.com/airbytehq/json-avro-converter/blob/95f40995354f31069c1db4c2504362c8ea8f80c5/converter/src/main/java/tech/allegro/schema/json2avro/converter/AvroTypeExceptions.java#L18

`Stack Trace: tech.allegro.schema.json2avro.converter.AvroConversionException: Failed to convert JSON to Avro: Could not evaluate union, field portfolioId is expected to be one of these: NULL, STRING. If this is a complex type, check if offending field (path: portfolioId) adheres to schema: 130457359476581`

This exception message says that the field `path: portfolioId` with the value `130457359476581` is expected to be either `NULL` or `STRING` according to the Amazon Ads source schema. I am not too familiar with java connectors yet but I think the bug is here: https://github.com/airbytehq/airbyte/blob/b4fd1ea3bdb49308a6a4208dbcc9850d44605032/airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/schemas/sponsored_display.py#L19

I wonder if it should be typed as `Decimal` to match the two other schemas that use `portfolioId`: https://github.com/airbytehq/airbyte/blob/69f53eb56a7f1d5658e84723b33b2d7ccfedca3d/airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/schemas/sponsored_brands.py#L22
https://github.com/airbytehq/airbyte/blob/69f53eb56a7f1d5658e84723b33b2d7ccfedca3d/airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/schemas/sponsored_products.py#L22

**Comment by sh4sh** [comment]
According to Amazon Ads docs, `portfolioId` is consistently `int` so it could be any or all of these endpoints. https://advertising.amazon.com/API/docs/en-us/reporting/v3/metrics#portfolioid

**Comment by animer3009** [comment]
@sh4sh FYI - This issue exists only on time use BigQuery (denormalized typed struct) destination connector.
On case stabile BigQuery destination connector it works fine.

**Comment by alafanechere** [comment]
@bmcgilli @oustynova @sh4sh I think we can't proceed in solving this issue without test data.
Changing the field type is a breaking change and I don't think we can safely introduce it without test data to check the actual type of the field and how setting it to `integer` impact existing syncs and their destination.
Can we launch a campaign on our test account to collect test data?
An other approach would be to ask @animer3009 to test out the change made in #25874 . @roman-yermilov-gl a pre-release should be published to make the connector docker image available. @animer3009 could then upgrade the connector on an existing connection and share how the new version behaves.
