### ISSUE TITLE
GCS logging used even when envs are empty

### ISSUE THREAD

**Issue by leoalmeidasant** [airbytehq/airbyte#17624]
## Environment
- **Airbyte version**:  example is 0.40.0-alpha
- **OS Version / Instance**: AWS EKS
- **Deployment**: Kubernetes
- **Step where error happened**: Update connector

## Current Behavior
Even setting GCS environments with empty value, airbyte keeps trying to store logs on GCS.

## Expected Behavior
Using minIO as s3.

## Logs
```GET https://storage.googleapis.com/storage/v1/b/$%7Benv:GCS_LOG_BUCKET%7D?projection=full
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Invalid bucket name: '${env:GCS_LOG_BUCKET}'",
    "reason" : "invalid"
  } ],
  "message" : "Invalid bucket name: '${env:GCS_LOG_BUCKET}'"
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:428)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1111)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.get(HttpStorageRpc.java:422)
	... 17 more
Cannot end publish with com.van.logging.gcp.CloudStoragePublishHelper@65cb8af6 due to error: Cannot end publishing: Invalid bucket name: '${env:GCS_LOG_BUCKET}'
```

I've copied envs from kube folder of master branch.
```
# S3/Minio Log Configuration
S3_LOG_BUCKET=airbyte-dev-logs
S3_LOG_BUCKET_REGION=
S3_MINIO_ENDPOINT=http://airbyte-minio-svc:9000
S3_PATH_STYLE_ACCESS=true

# GCS Log Configuration
GCS_LOG_BUCKET=

# State Storage Configuration
STATE_STORAGE_MINIO_BUCKET_NAME=airbyte-dev-logs
STATE_STORAGE_MINIO_ENDPOINT=http://airbyte-minio-svc:9000
```

**Comment by sh4sh** [comment]
Maybe related to https://github.com/airbytehq/airbyte/issues/17649, @leoalmeidasant can you check if you have set the below envs to minio? 

```
# Cloud Storage Configuration
WORKER_LOGS_STORAGE_TYPE=MINIO
WORKER_STATE_STORAGE_TYPE=MINIO
```

**Comment by sh4sh** [comment]
Hey @leoalmeidasant have you had any luck with the above config?

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 365 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.
