### ISSUE TITLE
Source Amazon Seller Partner: was aborted due to a fatal error

### ISSUE THREAD

**Issue by animer3009** [airbytehq/airbyte#17658]
## Environment
- **Airbyte version**:  0.40.12
- **OS Version / Instance**:  Ubuntu 22.04, GCP
- **Deployment**: Docker 
- **Source Connector and version**: Amazon Seller Partner 0.2.27
- **Destination Connector and version**: BigQuery (denormalized typed struct) 1.2.4
- **Step where error happened**: On time sync

## Current Behavior
I am regularly getting errors like this  for different reports.

```
2022-10-06 07:28:47 source > Encountered an exception while reading stream GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 113, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 182, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 285, in _read_full_refresh
    for record in records:
  File "/airbyte/integration_code/source_amazon_seller_partner/streams.py", line 355, in read_records
    raise Exception(f"The report for stream '{self.name}' was aborted due to a fatal error")
Exception: The report for stream 'GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL' was aborted due to a fatal error
```

The full log is attached. 
[aa3da8b6_08cd_4400_9354_85ad1f3c8606_logs_107_txt.txt](https://github.com/airbytehq/airbyte/files/9722477/aa3da8b6_08cd_4400_9354_85ad1f3c8606_logs_107_txt.txt)

**Comment by lazebnyi** [comment]
Fixed in 0.2.31
