### ISSUE TITLE
[OSError]: Looking for schema files in wrong location

### ISSUE THREAD

**Issue by subhamX** [airbytehq/airbyte#17772]
## Environment
- **Airbyte version**:  [Commit Id: 39220f4b1ebee7fce23acebcdbed7e1d259229b6](https://github.com/airbytehq/airbyte/commit/39220f4b1ebee7fce23acebcdbed7e1d259229b6)
- **OS Version / Instance**: Windows 10 WSL (Ubuntu 22.04)
- **Deployment**: Docker
- **Step where error happened**: Setup new connection 

## Current Behavior

I'm working on [building connectors using the new low-code CDK](https://github.com/airbytehq/connector-contest/issues/111). Unfortuantely, it fails to fetch schema. Here is the detailed error log:
```
2022-10-09 16:44:22 ERROR i.a.w.i.DefaultAirbyteStreamFactory(internalLog):105 - Cannot find file ./integration_code/schemas/users.json
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 123, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 108, in run
    catalog = self.source.discover(self.logger, config)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 72, in discover
    streams = [stream.as_airbyte_stream() for stream in self.streams(config=config)]
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 72, in <listcomp>
    streams = [stream.as_airbyte_stream() for stream in self.streams(config=config)]
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/core.py", line 113, in as_airbyte_stream
    stream = AirbyteStream(name=self.name, json_schema=dict(self.get_json_schema()), supported_sync_modes=[SyncMode.full_refresh])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py", line 132, in get_json_schema
    return self._schema_loader.get_json_schema()
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/schema/json_schema.py", line 50, in get_json_schema
    raise IOError(f"Cannot find file {json_schema_path}")
OSError: Cannot find file ./integration_code/schemas/users.json
2022-10-09 16:44:23 INFO i.a.w.t.TemporalAttemptExecution(get):134 - Stopping cancellation check scheduling...
```

Please note that I'm getting the exact same error if I try to follow the tutorial given in https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/.

## Expected Behavior
The schema is actually defined inside `./integration_code/source_<name>/schema/users.json` and not in `./integration_code/schemas/users.json`.

Futhermore I think the issue is with [airbyte_cdk/sources/declarative/schema/json_schema.py](https://github.com/airbytehq/airbyte/blob/65be9b74f0fe50d368da5f94c3cb26cb6d4703f3/airbyte-cdk/python/airbyte_cdk/sources/declarative/schema/json_schema.py) file. 

## Steps to Reproduce
1. Follow this tutorial https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/.
2. Add the connector to the airbyte. And try adding a new connection, and destination. It should fail while fetching schema.
3. Or run the acceptance tests.
```
docker build . -t airbyte/source-exchange-rates-tutorial:dev
python -m pytest integration_tests -p integration_tests.acceptance
```

## Are you willing to submit a PR?
Definitely yes! But I'm very new to airbyte, and am unaware of a lot of design decisions in the past. But I'll try to help in best possible way. :)

**Comment by misteryeo** [comment]
@subhamX in future, please post your questions in the [#hacktoberfest-2022](https://join.slack.com/share/enQtNDEzMjUzNTQ5OTg0Ny0xN2I2MDU4NGFkOTNlYzZlN2JmMGIzOTgyMjU1ODk1MDIzZWM5YTAzMThkMDFkNzgzNWNjNzljOGU1MmRhMDIw) Slack channel for a faster response. 

In the meantime, I've asked the team to look at this and they'll come back to you ASAP!

**Comment by girarda** [comment]
@subhamX as a work around, can you add a schema loader to you base_stream definition?
It should look like this for the tutorial.
```
  base_stream:
    schema_loader:
      file_path: "./source_exchange_rates_tutorial/schemas/{{ options['name'] }}.json"
    retriever:
      $ref: "*ref(definitions.retriever)"
```
You can replace the name of the source for your other connectors
`"./source_<connector_name>/schemas/{{ options['name'] }}.json"`

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by marcosmarxm** [comment]
@girarda are you working on this one?

**Comment by girarda** [comment]
Nope I'll close. low-code connectors should now use the [InlineSchemaLoader](https://docs.airbyte.com/connector-development/config-based/understanding-the-yaml-file/reference#/definitions/InlineSchemaLoader).
