### ISSUE TITLE
Helm Chart: External Database not reachable 

### ISSUE THREAD

**Issue by navi86** [airbytehq/airbyte#17841]
## Environment
- **Airbyte version**:  example is 0.40.14
- **OS Version / Instance**: GCP
- **Deployment**: helm
I am using separate postgresql instance(not instance from airbyte helm chart)

## Current Behavior
*Tell us what happens.* airbyte-server pod restarts every 8-10 minutes due to this error:
```
2022-10-11 13:32:38 ERROR i.a.c.p.ConfigRepository(healthCheck):109 - Health check error: 
org.jooq.exception.DataAccessException: Error getting connection from data source HikariDataSource (HikariPool-1)
	at org.jooq_3.13.4.POSTGRES.debug(Unknown Source) ~[?:?]
	at org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:86) ~[jooq-3.13.4.jar:?]
	at org.jooq.impl.DefaultExecuteContext.connection(DefaultExecuteContext.java:647) ~[jooq-3.13.4.jar:?]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:334) ~[jooq-3.13.4.jar:?]
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:354) ~[jooq-3.13.4.jar:?]
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2690) ~[jooq-3.13.4.jar:?]
	at io.airbyte.config.persistence.ConfigRepository.lambda$healthCheck$0(ConfigRepository.java:107) ~[io.airbyte.airbyte-config-config-persistence-0.40.14.jar:?]
	at io.airbyte.db.Database.query(Database.java:23) ~[io.airbyte.airbyte-db-db-lib-0.40.14.jar:?]
	at io.airbyte.db.ExceptionWrappingDatabase.query(ExceptionWrappingDatabase.java:23) ~[io.airbyte.airbyte-db-db-lib-0.40.14.jar:?]
	at io.airbyte.config.persistence.ConfigRepository.healthCheck(ConfigRepository.java:107) ~[io.airbyte.airbyte-config-config-persistence-0.40.14.jar:?]
	at io.airbyte.server.handlers.HealthCheckHandler.health(HealthCheckHandler.java:19) ~[io.airbyte-airbyte-server-0.40.14.jar:?]
	at io.airbyte.server.apis.ConfigurationApi.getHealthCheck(ConfigurationApi.java:789) ~[io.airbyte-airbyte-server-0.40.14.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680) ~[jersey-server-2.31.jar:?]
```
moreover, airbyte-worker restarts about every 10 minutes due to this error:

```
2022-10-11 13:29:12 ERROR i.a.w.i.DefaultAirbyteStreamFactory(validate):77 - Validation failed: null
```

## Expected Behavior
*Tell us what should happen.*
airbyte-server pod doesn't restart every 5-10 minutes due to the error above.

**Comment by marcosmarxm** [comment]
@navi86 looks this is much more a problem with Airbyte reaching the external database. Are you able to ping/telnet the database instance from the Airbyte instance?

**Comment by navi86** [comment]
@marcosmarxm 
yep, otherwise I would not see any connections/destinations in UI

**Comment by marcosmarxm** [comment]
What version of postgres are you using? Did you check the database logs to see if there is anything wrong there?

**Comment by navi86** [comment]
@marcosmarxm 
I am using postgresql 
`docker.io/bitnami/postgresql:11.14.0-debian-10-r28`
I see only one two errors that was yesterday:
```
2022-10-11 11:48:01.162 GMT [109] ERROR:  canceling statement due to user request
2022-10-11 11:48:01.162 GMT [109] STATEMENT:  INSERT INTO
        cluster_membership (membership_partition, host_id, rpc_address, rpc_port, role, session_start, last_heartbeat, record_expiry)
        VALUES($1, $2, $3, $4, $5, $6, $7, $8)
        ON CONFLICT(membership_partition, host_id)
        DO UPDATE SET 
        membership_partition = $1, host_id = $2, rpc_address = $3, rpc_port = $4, role = $5, session_start = $6, last_heartbeat = $7, record_expiry = $8
2022-10-11 11:48:12.929 GMT [152] LOG:  PID 146 in cancel request did not match any process
2022-10-11 11:48:12.933 GMT [155] LOG:  PID 150 in cancel request did not match any process
2022-10-11 11:48:16.511 GMT [162] ERROR:  canceling statement due to user request
2022-10-11 11:48:16.511 GMT [162] STATEMENT:  SELECT task_id, data, data_encoding 
         FROM visibility_tasks WHERE shard_id = $1 AND task_id > $2 AND task_id <= $3 ORDER BY shard_id, task_id
```

**Comment by navi86** [comment]
@marcosmarxm 
moreover, I add two env variable to cm "airbyte-env":
```
STATE_STORAGE_GCS_APPLICATION_CREDENTIALS
STATE_STORAGE_GCS_BUCKET_NAME
```
with values that I have for variables:
```
GCS_LOG_BUCKET
GOOGLE_APPLICATION_CREDENTIALS
```
I don't see any errors last 20 minutes..

**Comment by navi86** [comment]
small update, I see the same message:
`2022-10-12 10:32:14 INFO i.a.c.EnvConfigs(getEnvOrDefault):1091 - Using default value for environment variable STATE_STORAGE_MINIO_ENDPOINT: ''`
but server and worker pod are running without error(restart)

**Comment by marcosmarxm** [comment]
Are the logs being sent to GCS correctly?

**Comment by navi86** [comment]
@marcosmarxm 
yes, I see logs in gcp

**Comment by navi86** [comment]
@marcosmarxm 
honestly, I got the same error after 2-3 hours, I will try to monitor application, but I am so confused, why new version is not stable, because old application once failed with the same error and then it was running without issue. However new release was restarted 50 times for last 10 hours

**Comment by marcosmarxm** [comment]
Helm chart is under heavy development and is unstable for a couple of days. I'll test later if I can reproduce the same issue. @navi86 are you using a Cloud SQL or a k8s database deployment database?

**Comment by navi86** [comment]
@marcosmarxm 
I am using bitnami helm chart, moreover I am using gcp bucket for logs.

**Comment by navi86** [comment]
@marcosmarxm 
looks like my "fix" doesn't work, worker pod is constantly restarted again.

**Comment by marcosmarxm** [comment]
Sorry the delay here @navi86 I'll try to reproduce your issue today and return to you.

**Comment by navi86** [comment]
@marcosmarxm have you had a chance to test ?
I am currently stuck because on version 14 I have this issue but on version 15 I have another issue https://github.com/airbytehq/airbyte/issues/18217

**Comment by marcosmarxm** [comment]
Sorry @navi86 I didn't have time because of hacktoberfest contributions. :(

**Comment by navi86** [comment]
@marcosmarxm 
I don't know, but version is 0.40.14 is working in terms of applications(I mean it's not restarting), but I have another with connections
https://github.com/airbytehq/airbyte/issues/18106

**Comment by navi86** [comment]
how to specify env variable when airbyte is running in k8s ?
I need to specify env "NEED_STATE_VALIDATION", I've tried to add to configmap, add manually inside worker container, but I was still getting message :
```
Using default value for environment variable NEED_STATE_VALIDATION: 'true'
```

**Comment by ShaneGCareCru** [comment]
Had the same error, extending the initial liveness/readiness probes for the server seems to have fixed it

**Comment by marcosmarxm** [comment]
@ShaneGCareCru you're saying editing the server deployment file?

**Comment by marcosmarxm** [comment]
I tested Helm Chart 0.50.13 and it's possible to setup an external database. For newer versions will continue to test and update the documentation as needed.
