### ISSUE TITLE
Facebook Marketing -> BQ sync error: AttributeError: 'Client' object has no attribute 'new_batch'

### ISSUE THREAD

**Issue by cacan** [airbytehq/airbyte#1803]
## Expected Behavior
Facebook marketing Source should be synced to BigQuery destination. 

## Current Behavior
An error is thrown when the sync is started. Source and destination connections are ok, destination dataset available. 

## Steps to Reproduce
1. setup FB Marketing source [all data selected]
![image](https://user-images.githubusercontent.com/406493/105577645-34047500-5d7b-11eb-9a55-6a227be1be18.png)

2. setup BQ destination
3. sync

## Severity of the bug for you
High

## Airbyte Version
VERSION=0.13.0-alpha

## Additional context
>Starting syncing SourceFacebookMarketing
2021-01-23 11:53:24 ERROR (/tmp/workspace/22/1) LineGobbler(voidCall):69 - Traceback (most recent call last):
2021-01-23 11:53:24 ERROR (/tmp/workspace/22/1) LineGobbler(voidCall):69 - File "/usr/local/bin/base-python", line 8, in <module>
2021-01-23 11:53:24 ERROR (/tmp/workspace/22/1) LineGobbler(voidCall):69 - sys.exit(main())
2021-01-23 11:53:24 ERROR (/tmp/workspace/22/1) LineGobbler(voidCall):69 - File "/usr/local/lib/python3.7/site-packages/base_python/entrypoint.py", line 135, in main
2021-01-23 11:53:24 ERROR (/tmp/workspace/22/1) LineGobbler(voidCall):69 - launch(source, sys.argv[1:])
2021-01-23 11:53:24 ERROR (/tmp/workspace/22/1) LineGobbler(voidCall):69 - File "/usr/local/lib/python3.7/site-packages/base_python/entrypoint.py", line 120, in launch
2021-01-23 11:53:24 ERROR (/tmp/workspace/22/1) LineGobbler(voidCall):69 - AirbyteEntrypoint(source).start(args)
2021-01-23 11:53:24 ERROR (/tmp/workspace/22/1) LineGobbler(voidCall):69 - File "/usr/local/lib/python3.7/site-packages/base_python/entrypoint.py", line 111, in start
2021-01-23 11:53:24 ERROR (/tmp/workspace/22/1) LineGobbler(voidCall):69 - for message in generator:
2021-01-23 11:53:24 ERROR (/tmp/workspace/22/1) LineGobbler(voidCall):69 - File "/usr/local/lib/python3.7/site-packages/base_python/source.py", line 69, in read
2021-01-23 11:53:24 ERROR (/tmp/workspace/22/1) LineGobbler(voidCall):69 - for record in client.read_stream(configured_stream.stream):
2021-01-23 11:53:24 ERROR (/tmp/workspace/22/1) LineGobbler(voidCall):69 - File "/usr/local/lib/python3.7/site-packages/base_python/client.py", line 150, in read_stream
2021-01-23 11:53:24 ERROR (/tmp/workspace/22/1) LineGobbler(voidCall):69 - for message in method(fields=fields):
2021-01-23 11:53:24 ERROR (/tmp/workspace/22/1) LineGobbler(voidCall):69 - File "/usr/local/lib/python3.7/site-packages/source_facebook_marketing/client/client.py", line 257, in stream__adcreatives
2021-01-23 11:53:24 ERROR (/tmp/workspace/22/1) LineGobbler(voidCall):69 - yield from AdCreativeAPI(self).list(fields)
2021-01-23 11:53:24 ERROR (/tmp/workspace/22/1) LineGobbler(voidCall):69 - File "/usr/local/lib/python3.7/site-packages/source_facebook_marketing/client/client.py", line 61, in list
2021-01-23 11:53:24 ERROR (/tmp/workspace/22/1) LineGobbler(voidCall):69 - api_batch = self._api.new_batch()
2021-01-23 11:53:24 ERROR (/tmp/workspace/22/1) LineGobbler(voidCall):69 - AttributeError: 'Client' object has no attribute 'new_batch'
2021-01-23 11:53:24 DEBUG (/tmp/workspace/22/1) DefaultAirbyteSource(close):109 - Closing tap process
2021-01-23 11:53:24 DEBUG (/tmp/workspace/22/1) DefaultAirbyteDestination(close):102 - Closing target process

**Comment by sherifnada** [comment]
Hi @cacan , could you try this in the latest Airbyte version? We released a new version of the Facebook connector. 

To get the new version run (please note this will delete your sources, destinations and connections):

docker-compose down -v
rm .env docker-compose.yaml
wget https://raw.githubusercontent.com/airbytehq/airbyte/master/{.env,docker-compose.yaml} # or curl if wget not available
docker-compose up

and let us know if the problem persists?

**Comment by sherifnada** [comment]
@cacan The fix for this is available on the latest release. Can you upgrade Airbyte as follows (**note: this will remove your sources/destinations/connections)**:

```
docker-compose down -v
rm .env docker-compose.yml
wget https://raw.githubusercontent.com/airbytehq/airbyte/master/{.env,docker-compose.yaml} # or curl if wget not available, or just git pull if you have the whole repo downloaded already
docker-compose up
```

**Comment by cacan** [comment]
Hi @sherifnada,

The initial install of `0.13.0-alpha` was done yesterday, thanks for the quick update. 

An update to `0.13.1-alpha` has created a whole new set of issues. 

Steps performed: 
```
rm -rf airbyte 
docker system prune -a
git clone https://github.com/airbytehq/airbyte.git 
cd airbyte 
docker-compose up
```

resulted in:

1. Scheduler ERROR with saved data 
- docker/airbyte would start but blank screens all over the place, console ERROR with airbyte scheduler [I recall that scheduler error log had info from the old source]
- wasn't all sources/destinations/containers supposed to be purged? /tmp/airbyte_local on the host is empty, any other locations I should look for mapped data?

rebooted the machine

2. `docker-compose up` throws an error:
```
root@cacan_lab_01:/home/cacan/airbyte# docker-compose up
ERROR: Invalid interpolation format for "environment" option in service "scheduler": "AIRBYTE_ROLE=${AIRBYTE_ROLE:-}"
```

Have a nice day,

**Comment by sherifnada** [comment]
@cacan could you remove the airbyte volumes by running `docker-compose down -v` from the Airbyte repository root? IIRC `docker system prune -a` won't remove volumes, which could cause such issues when migrating between versions.

**Comment by cacan** [comment]
@sherifnada ,

before:
```
root@cacan_lab_01:/home/cacan/airbyte# docker volume list
DRIVER              VOLUME NAME
root@cacan_lab_01:/home/cacan/airbyte# docker container list
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

command run:
```
root@cacan_lab_01:/home/cacan/airbyte# docker-compose down -v
ERROR: Invalid interpolation format for "environment" option in service "scheduler": "AIRBYTE_ROLE=${AIRBYTE_ROLE:-}"
```

couldn't start - the same error:
```
root@cacan_lab_01:/home/cacan/airbyte# docker-compose up
ERROR: Invalid interpolation format for "environment" option in service "scheduler": "AIRBYTE_ROLE=${AIRBYTE_ROLE:-}"
```


Tried in another VM - works well... 
Hm... where are the leftovers?! ;-)

**Comment by michel-tricot** [comment]
out of curiosity what version of docker-compose (`docker-compose --version`) was on the VM that didn't work?

I just want to make sure docker-compose is the guilty one here

**Comment by cacan** [comment]
Hi @michel-tricot,

```
root@cacan_lab_01:/home/cacan/airbyte# docker-compose --version
docker-compose version 1.17.1, build unknown
```

**Comment by michel-tricot** [comment]
Thanks! Interpolation got supported in version 1.19.0. That explains it.

**Comment by cacan** [comment]
Hi @michel-tricot ,

yep, a manual upgrade of docker-compose has resolved that issue. 

1] FB source got an upgrade `-> airbyte/source-facebook-marketing:0.1.2`, so the initial problem might be solved 
2] min req: docker-compose >1.19.0

Managed to have it on both VMs. 

Source [FB] -> destination configured [BigQuery] and then run into a limit issue [it is a really small account, just a few ads]:

```
2021-01-26 20:49:54 INFO (/tmp/workspace/13/0) DefaultAirbyteStreamFactory(internalLog):110 - Syncing ads stream
2021-01-26 20:51:10 INFO (/tmp/workspace/13/0) DefaultAirbyteStreamFactory(internalLog):110 - Advancing bookmark for Ads stream from None to 2020-02-26T01:20:27+01:00
2021-01-26 20:51:10 INFO (/tmp/workspace/13/0) DefaultAirbyteStreamFactory(internalLog):110 - Syncing adsets stream
2021-01-26 20:51:10 INFO (/tmp/workspace/13/0) DefaultAirbyteStreamFactory(internalLog):110 -
Message: Call was not successful
Method: GET
Path: https://graph.facebook.com/v9.0/act_10152399345541736/adsets
Params: {'limit': 100, 'fields': 'updated_time', 'summary': 'true'}
Status: 400
Response:
{
"error": {
"message": "(#17) User request limit reached",
"type": "OAuthException",
"is_transient": true,
"code": 17,
"error_subcode": 2446079,
"fbtrace_id": "A6QDoa4gwjio5zg5wWuhQNR"
}
}
2021-01-26 20:51:10 INFO (/tmp/workspace/13/0) DefaultAirbyteStreamFactory(internalLog):110 - Caught retryable error after 1 tries. Waiting 5 more seconds then retrying...
2021-01-26 20:51:10 INFO (/tmp/workspace/13/0) DefaultAirbyteStreamFactory(internalLog):110 -
Message: Call was not successful
Method: GET
Path: https://graph.facebook.com/v9.0/act_10152399345541736/adsets
Params: {'limit': 100, 'fields': 'updated_time', 'summary': 'true'}
Status: 400
Response:
{
"error": {
"message": "(#17) User request limit reached",
"type": "OAuthException",
"is_transient": true,
"code": 17,
"error_subcode": 2446079,
"fbtrace_id": "AiuZT64ZmTvYm4L_V87pv9a"
}
}
```

**Comment by sherifnada** [comment]
@cacan 
1. Just a sanity check: is the connector able to produce any records and then it gets throttled, or does it produce no records at all? 
2. What is your FB Ad account type? is it dev or "Business standard"? According to [Facebook's rate limits ](https://developers.facebook.com/docs/marketing-apis/rate-limiting) (see under "Ad account rate limiting", excerpt is below), dev accounts can be heavily throttled. Between some of the pre-checks Airbyte runs and running the connector repeatedly, I can see the rate limit on a dev account getting hit fairly quickly
3. What is the replication schedule for your FB source 

Relevant section from FB docs: 
> ads_management - As of v4.0, for each ad account in a one-hour time period: (100000 if your app is in the Standard tier or 300 if your app is in the Dev tier) + 40 * Num of Active ads.

**Comment by sherifnada** [comment]
@cacan we've updated our docs to clarify that a rate limit increase is needed to sync any reasonable amount of data from Facebook. See the updated docs here: https://docs.airbyte.io/integrations/sources/facebook-marketing#request-rate-limit-increase

Closing this ticket unless there are further action items.
