### ISSUE TITLE
Internal Server Error: Get Spec job failed when trying to update a custom source

### ISSUE THREAD

**Issue by jack-fireworkhq** [airbytehq/airbyte#18043]
## Environment
- **Airbyte version**:  example is 0.39.23-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**:Kubernetes
- **Source Connector and version**: 
- **Destination Connector and version**: 
- **Step where error happened**: Update connector

## Current Behavior
![image](https://user-images.githubusercontent.com/80802145/196121596-432612b1-e215-4458-b6f8-2944920189fa.png)
![image](https://user-images.githubusercontent.com/80802145/196121945-703db76e-f6e9-4b0d-8763-a8dfedc36884.png)
I have this Agora custom source and I was trying to update it from 0.1.9 to 0.2.0, but I met the "Internal Server Error: Get Spec job failed". I don't know what's going wrong here, It's the first time I met the error.

I checked the action and the latest 0.2.0 image was built and pushed to ECR successfully.
Sorry I can't show you the custom source repository, it's a private repo and belongs to the company.

## Expected Behavior
The custom source can be updated successfully.

## Logs

```Java
0: "java.lang.IllegalStateException: Get Spec job failed."
1: "	at com.google.common.base.Preconditions.checkState(Preconditions.java:502)"
2: "	at io.airbyte.server.converters.SpecFetcher.getSpecFromJob(SpecFetcher.java:14)"
3: "	at io.airbyte.server.handlers.SourceDefinitionsHandler.getSpecForImage(SourceDefinitionsHandler.java:283)"
4: "	at io.airbyte.server.handlers.SourceDefinitionsHandler.updateSourceDefinition(SourceDefinitionsHandler.java:218)"
5: "	at io.airbyte.server.apis.ConfigurationApi.lambda$updateSourceDefinition$14(ConfigurationApi.java:348)"
6: "	at io.airbyte.server.apis.ConfigurationApi.execute(ConfigurationApi.java:860)"
7: "	at io.airbyte.server.apis.ConfigurationApi.updateSourceDefinition(ConfigurationApi.java:348)"
8: "	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
9: "	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)"
10: "	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
11: "	at java.base/java.lang.reflect.Method.invoke(Method.java:568)"
12: "	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)"
13: "	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)"
14: "	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)"
15: "	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)"
16: "	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)"
17: "	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)"
18: "	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)"
19: "	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)"
20: "	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)"
21: "	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)"
22: "	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)"
23: "	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)"
24: "	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)"
25: "	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)"
26: "	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)"
27: "	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)"
28: "	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)"
29: "	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)"
30: "	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)"
31: "	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)"
32: "	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)"
33: "	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)"
34: "	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)"
35: "	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:569)"
36: "	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)"
37: "	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1377)"
38: "	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)"
39: "	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:507)"
40: "	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)"
41: "	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292)"
42: "	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)"
43: "	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)"
44: "	at org.eclipse.jetty.server.Server.handle(Server.java:501)"
45: "	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)"
46: "	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)"
47: "	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)"
48: "	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)"
49: "	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)"
50: "	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)"
51: "	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)"
52: "	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)"
53: "	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)"
54: "	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)"
55: "	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)"
56: "	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)"
57: "	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)"
58: "	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)"
59: "	at java.base/java.lang.Thread.run(Thread.java:833)"
```

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

I'm afraid I can't, I'm not familiar with Java.

**Comment by sajarin** [comment]
Hey @jack-fireworkhq, thanks for the issue. Does the 0.2.0 update include any changes to dependencies or additions of libraries? Another user on our forums reported a [similar issue](https://discuss.airbyte.io/t/internal-server-error-get-spec-job-failed/2508) and the fix was to update the `setup.py` file.

You may also want to try the troubleshooting steps my colleague recommended on the post as well. Let me know if this helps!

**Comment by jack-fireworkhq** [comment]
Hi @sajarin , thanks for the reply. I realized I can build the image locally and run it as your colleague mentioned, so I did and found the problem.
![image](https://user-images.githubusercontent.com/80802145/196864238-0422afae-1e9f-42e6-82b6-b1a910a3c557.png)
It appears that I need to update the airbyte_cdk's version in setup.py to make it work.Besides that I need to change `from airbyte_cdk.sources.streams import IncrementalMixin` to `from airbyte_cdk.sources.streams.core import IncrementalMixin
`
