### ISSUE TITLE
Source SFTP: exception in children non-daemon threads

### ISSUE THREAD

**Issue by wallies** [airbytehq/airbyte#18148]
## Environment
- **Airbyte version**:  OSS 0.40.15 
- **OS Version / Instance**: GKE
- **Deployment**: Kubernetes GKE
- **Source Connector and version**: SFTP 0.1.2
- **Step where error happened**: Sync Job

## Current Behavior
*Tell us what happens.*

Get the following error.
```
2022-10-19 00:38:15 source >  Thread stacktrace: java.base@17.0.1/sun.nio.ch.Net.poll(Native Method)
2022-10-19 00:38:15 source >         at java.base@17.0.1/sun.nio.ch.NioSocketImpl.park(NioSocketImpl.java:181)
2022-10-19 00:38:15 source >         at java.base@17.0.1/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:285)
2022-10-19 00:38:15 source >         at java.base@17.0.1/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309)
2022-10-19 00:38:15 source >         at java.base@17.0.1/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
2022-10-19 00:38:15 source >         at java.base@17.0.1/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
2022-10-19 00:38:15 source >         at java.base@17.0.1/java.net.Socket$SocketInputStream.read(Socket.java:966)
2022-10-19 00:38:15 source >         at app//com.jcraft.jsch.IO.getByte(IO.java:82)
2022-10-19 00:38:15 source >         at app//com.jcraft.jsch.Session.read(Session.java:926)
2022-10-19 00:38:15 source >         at app//com.jcraft.jsch.Session.run(Session.java:1403)
2022-10-19 00:38:15 source >         at java.base@17.0.1/java.lang.Thread.run(Thread.java:833)
2022-10-19 00:38:15 source > 2022-10-19 00:38:15 INFO i.a.i.s.s.SftpSource(lambda$read$2):125 - Closing server connection.
2022-10-19 00:38:15 source > 2022-10-19 00:38:15 INFO i.a.i.s.s.SftpClient(disconnect):79 - Disconnecting from the server
2022-10-19 00:38:15 source > 2022-10-19 00:38:15 INFO i.a.i.s.s.SftpClient(disconnect):86 - Disconnected successfully
2022-10-19 00:38:15 source > 2022-10-19 00:38:15 INFO i.a.i.s.s.SftpSource(lambda$read$2):127 - Closed server connection.
2022-10-19 00:38:15 source > 2022-10-19 00:38:15 INFO i.a.i.b.IntegrationRunner(runInternal):171 - Completed integration: io.airbyte.integrations.source.sftp.SftpSource
```

Also the dependency jsch on sourceforge isnt maintained. Should the fork be used instead https://github.com/mwiede/jsch?

## Expected Behavior
*Tell us what should happen.*
Connect to sftp server and get files from all folders

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
