### ISSUE TITLE
migration failed after upgrade

### ISSUE THREAD

**Issue by navi86** [airbytehq/airbyte#18217]
## Environment
- **Airbyte version**:  0.40.26
- **OS Version / Instance**: GCP 
- **Deployment**: helm/Kubernetes

- **Step where error happened**: Upgrade Airbyte

## Current Behavior
airbyte-bootloader failed to finish due to error:
```
SQL [alter type "operator_type" add value 'webhook']; ERROR: ALTER TYPE ... ADD cannot run inside a transaction block
```

## Expected Behavior
airbyte should be upgraded successfully

## Logs
```
2022-10-19 18:16:26 ERROR o.f.c.i.l.s.Slf4jLog(error):57 - Migration of schema "public" to version "0.40.12.001 - AddWebhookOperationColumns" failed! Changes successfully rolled back.
Exception in thread "main" org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: Migration failed !
        at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:378)
        at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:271)
        at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66)
        at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:270)
        at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:243)
        at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:141)
        at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:70)
        at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:99)
        at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:141)
        at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:141)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:101)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:217)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:168)
        at org.flywaydb.core.Flyway.execute(Flyway.java:584)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:168)
        at io.airbyte.db.instance.FlywayDatabaseMigrator.migrate(FlywayDatabaseMigrator.java:36)
        at io.airbyte.bootloader.BootloaderApp.runFlywayMigration(BootloaderApp.java:343)
        at io.airbyte.bootloader.BootloaderApp.load(BootloaderApp.java:173)
        at io.airbyte.bootloader.BootloaderApp.main(BootloaderApp.java:260)
Caused by: org.flywaydb.core.api.FlywayException: Migration failed !
        at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.executeOnce(JavaMigrationExecutor.java:75)
        at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.lambda$execute$0(JavaMigrationExecutor.java:54)
        at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27)
        at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.execute(JavaMigrationExecutor.java:53)
        at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:370)
        ... 18 more
Caused by: org.jooq.exception.DataAccessException: SQL [alter type "operator_type" add value 'webhook']; ERROR: ALTER TYPE ... ADD cannot run inside a transaction block
        at org.jooq_3.13.4.POSTGRES.debug(Unknown Source)
        at org.jooq.impl.Tools.translate(Tools.java:2753)
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:755)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:385)
        at io.airbyte.db.instance.configs.migrations.V0_40_12_001__AddWebhookOperationColumns.addWebhookOperationType(V0_40_12_001__AddWebhookOperationColumns.java:42)
        at io.airbyte.db.instance.configs.migrations.V0_40_12_001__AddWebhookOperationColumns.migrate(V0_40_12_001__AddWebhookOperationColumns.java:29)
        at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.executeOnce(JavaMigrationExecutor.java:61)
        ... 22 more
Caused by: org.postgresql.util.PSQLException: ERROR: ALTER TYPE ... ADD cannot run inside a transaction block
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:167)
        at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:156)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
        at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:453)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:371)
        ... 25 more

```
this new operation type was added recently https://github.com/airbytehq/airbyte/pull/17671

## Steps to Reproduce
1. deploy airbyte version 0.39.37-alpha
2. upgrade to version 0.40.26 with preserving external database

**Comment by navi86** [comment]
@natalyjazzviolin 
yes, the issue is application issue that bootloader is not able to upgrade my old database.

**Comment by albertopinardi** [comment]
Hello there,
I was in the same situation upgrading from AppVersion 0.40.0-alpha (chart version was 0.36.something), so I upgraded to chart version 0.40.14 (that now coincide with the AppVersion). And the migration in the pre-existing database was fine.
I will attempt upgrading to the latest (0.40.26) once I set up an emergency plan for what's in production.

**Comment by navi86** [comment]
@natalyjazzviolin 
is it possible to get any information when this issue might be fixed ?

**Comment by firehist** [comment]
Hello here,

Thanks for the amazing job.

I got the exact same issue while updating my helm installed version from 0.40.18 to 0.40.40.

The full error log: https://gist.github.com/firehist/12f1b6c5be824d97e0281080b915f6d3

**Comment by navi86** [comment]
@firehist 
I could solve this issue if I migrate my db to internal one(that is part of helm chart). It looks like application doesn't work with external db anymore.

**Comment by firehist** [comment]
> @firehist I could solve this issue if I migrate my db to internal one(that is part of helm chart). It looks like application doesn't work with external db anymore.

Thanks for the feedback.
I could solve my problem by applying manually the migrations based on the  [/V0_40_12_001__AddWebhookOperationColumns.java](https://github.com/airbytehq/airbyte/blob/7009bbeb8200246807b09c2af41526347620a436/airbyte-db/db-lib/src/main/java/io/airbyte/db/instance/configs/migrations/V0_40_12_001__AddWebhookOperationColumns.java)
 file and by adding this migration in the flyway schema as OK.

Hope it'll help some other people using this nice tool!

**Comment by sid-habu** [comment]
> > @firehist I could solve this issue if I migrate my db to internal one(that is part of helm chart). It looks like application doesn't work with external db anymore.
> 
> Thanks for the feedback. I could solve my problem by applying manually the migrations based on the [/V0_40_12_001__AddWebhookOperationColumns.java](https://github.com/airbytehq/airbyte/blob/7009bbeb8200246807b09c2af41526347620a436/airbyte-db/db-lib/src/main/java/io/airbyte/db/instance/configs/migrations/V0_40_12_001__AddWebhookOperationColumns.java) file and by adding this migration in the flyway schema as OK.
> 
> Hope it'll help some other people using this nice tool!

```
alter table operation add column operator_webhook jsonb default null;
alter type "operator_type" add value 'webhook'
alter table workspace add column webhook_operation_configs jsonb default null;
```

```
INSERT INTO "public"."airbyte_configs_migrations" ("installed_rank", "version", "description", "type", "script", "checksum", "installed_by", "installed_on", "execution_time", "success") VALUES
(27, '0.40.12.001', 'AddWebhookOperationColumns', 'JDBC', 'io.airbyte.db.instance.configs.migrations.V0_40_12_001__AddWebhookOperationColumns', NULL, 'BootloaderApp', '2023-04-07 23:09:58.69697', 18, 't');
```
