### ISSUE TITLE
Mysql CDC is not working when user option require ssl is enabled

### ISSUE THREAD

**Issue by VitaliiMaltsev** [airbytehq/airbyte#18362]
from https://discuss.airbyte.io/t/mysql-cdc-is-not-working-when-option-user-require-ssl-is-enabled/2958/1

`Caused by: io.debezium.DebeziumException: Unexpected error while connecting to MySQL and looking at BINLOG_FORMAT mode: 
	at io.debezium.connector.mysql.MySqlConnection.isBinlogFormatRow(MySqlConnection.java:385)
	at io.debezium.connector.mysql.MySqlConnectorTask.validateBinlogConfiguration(MySqlConnectorTask.java:240)
	at io.debezium.connector.mysql.MySqlConnectorTask.start(MySqlConnectorTask.java:85)
	at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:133)
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:760)
	at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:192)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.sql.SQLException: Access denied for user 'airbyte'@'airbyte-server-ip.com' (using password: YES)`

**Comment by VitaliiMaltsev** [comment]
closing as duplicate of https://app.zenhub.com/workspaces/db--dw-source-connectors-6333360e0a41155061efbcbd/issues/airbytehq/airbyte/18369
