### ISSUE TITLE
An error occurs randomly in mongodb-v2 connector 

### ISSUE THREAD

**Issue by emilija-omnisend** [airbytehq/airbyte#18469]
## Environment
- **Airbyte version**:  0.40.18
- **Deployment**: Kubernetes GKE
- **Source Connector and version**: MongoDB (airbyte/source-mongodb-v2), version 0.1.14 and up
- **Step where error happened**: Sync job

## Current Behavior
Every few runs a sync fails with an error:
```Exception in thread "main" java.util.NoSuchElementException
2022-10-26 09:22:21 source > 	at com.mongodb.client.internal.MongoBatchCursorAdapter.next(MongoBatchCursorAdapter.java:60)
2022-10-26 09:22:21 source > 	at io.airbyte.db.mongodb.MongoUtils.getFieldsName(MongoUtils.java:251)
2022-10-26 09:22:21 source > 	at io.airbyte.db.mongodb.MongoUtils.setSubFields(MongoUtils.java:229)
2022-10-26 09:22:21 source > 	at io.airbyte.db.mongodb.MongoUtils.lambda$setSubFields$1(MongoUtils.java:235)
2022-10-26 09:22:21 source > 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2022-10-26 09:22:21 source > 	at io.airbyte.db.mongodb.MongoUtils.setSubFields(MongoUtils.java:230)
2022-10-26 09:22:21 source > 	at io.airbyte.db.mongodb.MongoUtils.lambda$setSubFields$1(MongoUtils.java:235)
2022-10-26 09:22:21 source > 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2022-10-26 09:22:21 source > 	at io.airbyte.db.mongodb.MongoUtils.setSubFields(MongoUtils.java:230)
2022-10-26 09:22:21 source > 	at io.airbyte.db.mongodb.MongoUtils.lambda$getUniqueFields$0(MongoUtils.java:210)
2022-10-26 09:22:21 source > 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
2022-10-26 09:22:21 source > 	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
2022-10-26 09:22:21 source > 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
2022-10-26 09:22:21 source > 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
2022-10-26 09:22:21 source > 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
2022-10-26 09:22:21 source > 	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
2022-10-26 09:22:21 source > 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
```
Sometimes retries help, sometimes they don't. Looked at the code a bit, looks like a potential race condition, but I'm no java expert.

Error first started appearing once we upgraded connector to current newest version - 0.1.19 and only for one and the same stream. 

## Expected Behavior
Sync is reliable and succeeds every time.

## Logs
```
022-10-26 08:58:55 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):177 - Waiting for source and destination threads to complete.
2022-10-26 08:58:55 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$getReplicationRunnable$6):322 - Replication thread started.
2022-10-26 08:59:00 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$getReplicationRunnable$6):355 - Source has no more messages, closing connection.
2022-10-26 08:59:01 [32mINFO[m i.a.w.p.KubePodProcess(close):737 - (pod: bi-platform / source-mongodb-v2-read-6318-0-uqtoo) - Closed all resources for pod
2022-10-26 08:59:03 [32mINFO[m i.a.v.j.JsonSchemaValidator(test):71 - JSON schema validation failed. 
errors: $: null found, object expected
2022-10-26 08:59:03 [1;31mERROR[m i.a.w.i.DefaultAirbyteStreamFactory(validate):77 - Validation failed: null
2022-10-26 08:59:04 [32mINFO[m i.a.w.p.KubePodProcess(close):737 - (pod: bi-platform / destination-bigquery-write-6318-0-dwqtj) - Closed all resources for pod
2022-10-26 08:59:04 [1;31mERROR[m i.a.w.g.DefaultReplicationWorker(run):188 - Sync worker failed.
java.util.concurrent.ExecutionException: io.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source cannot be stopped!
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:181) ~[io.airbyte-airbyte-workers-0.40.14.jar:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:68) ~[io.airbyte-airbyte-workers-0.40.14.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:161) ~[io.airbyte-airbyte-workers-0.40.14.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
	Suppressed: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
		at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:135) ~[io.airbyte-airbyte-workers-0.40.14.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:145) ~[io.airbyte-airbyte-workers-0.40.14.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:68) ~[io.airbyte-airbyte-workers-0.40.14.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:161) ~[io.airbyte-airbyte-workers-0.40.14.jar:?]
		at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: io.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source cannot be stopped!
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$getReplicationRunnable$6(DefaultReplicationWorker.java:359) ~[io.airbyte-airbyte-workers-0.40.14.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
Caused by: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
	at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:135) ~[io.airbyte-airbyte-workers-0.40.14.jar:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$getReplicationRunnable$6(DefaultReplicationWorker.java:357) ~[io.airbyte-airbyte-workers-0.40.14.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
2022-10-26 08:59:04 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):281 - Source did not output any state messages
2022-10-26 08:59:04 [33mWARN[m i.a.w.g.DefaultReplicationWorker(run):289 - State capture: No new state, falling back on input state: io.airbyte.config.State@25ec0cd2[state={}]
2022-10-26 08:59:04 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):300 - sync summary: {
  "status" : "failed",
  "recordsSynced" : 0,
  "bytesSynced" : 0,
  "startTime" : 1666774723373,
  "endTime" : 1666774744066,
  "totalStats" : {
    "recordsEmitted" : 0,
    "bytesEmitted" : 0,
    "sourceStateMessagesEmitted" : 0,
    "destinationStateMessagesEmitted" : 0,
    "recordsCommitted" : 0,
    "meanSecondsBeforeSourceStateMessageEmitted" : 0,
    "maxSecondsBeforeSourceStateMessageEmitted" : 0,
    "maxSecondsBetweenStateMessageEmittedandCommitted" : 0,
    "meanSecondsBetweenStateMessageEmittedandCommitted" : 0
  },
  "streamStats" : [ ]
}
2022-10-26 08:59:04 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):301 - failures: [ {
  "failureOrigin" : "source",
  "internalMessage" : "io.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source cannot be stopped!",
  "externalMessage" : "Something went wrong within the source connector",
  "metadata" : {
    "attemptNumber" : 0,
    "jobId" : 6318,
    "connector_command" : "read"
  },
  "stacktrace" : "java.util.concurrent.CompletionException: io.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source cannot be stopped!\n\tat java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)\n\tat java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat java.base/java.lang.Thread.run(Thread.java:833)\nCaused by: io.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source cannot be stopped!\n\tat io.airbyte.workers.general.DefaultReplicationWorker.lambda$getReplicationRunnable$6(DefaultReplicationWorker.java:359)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)\n\t... 3 more\nCaused by: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.\n\tat io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:135)\n\tat io.airbyte.workers.general.DefaultReplicationWorker.lambda$getReplicationRunnable$6(DefaultReplicationWorker.java:357)\n\t... 4 more\n",
  "timestamp" : 1666774741352
} ]
2022-10-26 08:59:04 [32mINFO[m i.a.c.i.LineGobbler(voidCall):114 - 
2022-10-26 08:59:04 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):134 - Stopping cancellation check scheduling...
2022-10-26 08:59:04 [32mINFO[m i.a.c.i.LineGobbler(voidCall):114 - ----- END REPLICATION -----
2022-10-26 08:59:04 [32mINFO[m i.a.c.i.LineGobbler(voidCall):114 - 
2022-10-26 08:59:04 [32mINFO[m i.a.w.t.s.ReplicationActivityImpl(lambda$replicate$3):157 - sync summary: io.airbyte.config.StandardSyncOutput@41aa5be5[standardSyncSummary=io.airbyte.config.StandardSyncSummary@16d47a0b[status=failed,recordsSynced=0,bytesSynced=0,startTime=1666774723373,endTime=1666774744066,totalStats=io.airbyte.config.SyncStats@3d1bea5[recordsEmitted=0,bytesEmitted=0,sourceStateMessagesEmitted=0,destinationStateMessagesEmitted=0,recordsCommitted=0,meanSecondsBeforeSourceStateMessageEmitted=0,maxSecondsBeforeSourceStateMessageEmitted=0,maxSecondsBetweenStateMessageEmittedandCommitted=0,meanSecondsBetweenStateMessageEmittedandCommitted=0,additionalProperties={}],streamStats=[]],normalizationSummary=<null>,state=io.airbyte.config.State@25ec0cd2[state={}],outputCatalog=io.airbyte.protocol.models.ConfiguredAirbyteCatalog@76738a74[streams=[io.airbyte.protocol.models.ConfiguredAirbyteStream@6595922c[stream=io.airbyte.protocol.models.AirbyteStream@5024b8b7[name=mongo_shared_v2_brands,jsonSchema={"type":"object","properties":{"_id":{"type":"string"},"data":{"type":"string"},"name":{"type":"string"},"note":{"type":"string"},"notes":{"type":"array"},"status":{"type":"string"},"currency":{"type":"string"},"industry":{"type":"string"},"metadata":{"type":"string"},"accountID":{"type":"string"},"deletedAt":{"type":"string"},"deletedBy":{"type":"string"},"isDeleted":{"type":"boolean"},"lastLogin":{"type":"string"},"keyAccount":{"type":"boolean"},"featureFlags":{"type":"string"},"industryCustom":{"type":"string"},"deleteExecuteAt":{"type":"string"},"deleteInitiatedAt":{"type":"string"}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=overwrite,primaryKey=[],additionalProperties={}]],additionalProperties={}],failures=[io.airbyte.config.FailureReason@5e8e1080[failureOrigin=source,failureType=<null>,internalMessage=io.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source cannot be stopped!,externalMessage=Something went wrong within the source connector,metadata=io.airbyte.config.Metadata@34c4110f[additionalProperties={attemptNumber=0, jobId=6318, connector_command=read}],stacktrace=java.util.concurrent.CompletionException: io.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source cannot be stopped!
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source cannot be stopped!
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$getReplicationRunnable$6(DefaultReplicationWorker.java:359)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	... 3 more
Caused by: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
	at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:135)
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$getReplicationRunnable$6(DefaultReplicationWorker.java:357)
	... 4 more
,retryable=<null>,timestamp=1666774741352]]]
```
## Steps to Reproduce
Issue occurs randomly. Could be some sort of a edge-case as at least right now, it would happen on the same mongo collection.

## Are you willing to submit a PR?
I would, but I don't have enough java knowledge to debug this.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
