### ISSUE TITLE
airbyte-server StatusRuntimeException: DEADLINE_EXCEEDED on Initial Deployment

### ISSUE THREAD

**Issue by nullmaxwell** [airbytehq/airbyte#18516]
## Environment
- **Airbyte version**: v0.40.17
- **OS Version / Instance**: Ubuntu 20.04.5
	- Additional info:
	```
	OS: Ubuntu 20.04.5 LTS x86_64
	Kernel: 5.4.0-125-generic
	CPU: 11th Gen Intel i9-11900K (16) @ 5.100GHz
	Memory: 26046MiB / 64187MiB
	```
- **Deployment**: Docker version 20.10.18
- **Source Connector and version**: N/A
- **Destination Connector and version**: N/A
- **Step where the error happened**: Deployment

## Current Behavior
`airbyte-server` container hangs on `grpc.StatusRuntimeException: DEADLINE_EXCEEDED` as a result of `i.t.i.r.GrpcSyncRetryer(retry):56 - Retrying after failure` which stalls the UI with the "Cannot reach server" splash page.

## Expected Behavior
`airbyte-server` should create the GRPC client, initialize the temporal namespace default and finish deploying.

## Logs
From `airbyte-server` container:
```
2022-10-26 17:55:43,319 main INFO Loading mask data from '/seed/specs_secrets_mask.yaml
2022-10-26 17:55:43 INFO i.a.c.EnvConfigs(getEnvOrDefault):1079 - Using default value for environment variable CONFIG_DATABASE_USER: 'docker'
2022-10-26 17:55:43 INFO i.a.c.EnvConfigs(getEnvOrDefault):1079 - Using default value for environment variable CONFIG_DATABASE_PASSWORD: '*****'
2022-10-26 17:55:43 INFO i.a.c.EnvConfigs(getEnvOrDefault):1079 - Using default value for environment variable CONFIG_DATABASE_URL: 'jdbc:postgresql://db:5432/airbyte'
2022-10-26 17:55:43 INFO c.z.h.HikariDataSource(<init>):80 - HikariPool-1 - Starting...
2022-10-26 17:55:43 INFO c.z.h.HikariDataSource(<init>):82 - HikariPool-1 - Start completed.
2022-10-26 17:55:43 INFO c.z.h.HikariDataSource(<init>):80 - HikariPool-2 - Starting...
2022-10-26 17:55:43 INFO c.z.h.HikariDataSource(<init>):82 - HikariPool-2 - Start completed.
2022-10-26 17:55:43 INFO i.a.c.EnvConfigs(getEnvOrDefault):1079 - Using default value for environment variable WORKER_ENVIRONMENT: 'DOCKER'
2022-10-26 17:55:43 INFO i.a.s.ServerApp(getServer):179 - Checking databases..
2022-10-26 17:55:43 INFO i.a.s.ServerApp(assertDatabasesReady):156 - Checking configs database flyway migration version..
2022-10-26 17:55:43 INFO i.a.c.EnvConfigs(getEnvOrDefault):1079 - Using default value for environment variable CONFIGS_DATABASE_INITIALIZATION_TIMEOUT_MS: '60000'
2022-10-26 17:55:43 WARN i.a.d.c.DatabaseAvailabilityCheck(check):38 - Waiting for database to become available...
2022-10-26 17:55:43 INFO i.a.d.c.DatabaseAvailabilityCheck(lambda$isDatabaseConnected$1):75 - Testing airbyte configs database connection...
2022-10-26 17:55:44 INFO i.a.d.c.DatabaseAvailabilityCheck(check):57 - Database available.
2022-10-26 17:55:44 INFO o.f.c.i.l.s.Slf4jLog(info):37 - Flyway Community Edition 8.5.13 by Redgate
2022-10-26 17:55:44 INFO o.f.c.i.l.s.Slf4jLog(info):37 - See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.13
2022-10-26 17:55:44 INFO o.f.c.i.l.s.Slf4jLog(info):37 - 
2022-10-26 17:55:44 INFO o.f.c.i.l.s.Slf4jLog(info):37 - Database: jdbc:postgresql://db:5432/airbyte (PostgreSQL 13.8)
2022-10-26 17:55:44 INFO o.f.c.i.l.s.Slf4jLog(info):37 - Flyway Community Edition 8.5.13 by Redgate
2022-10-26 17:55:44 INFO o.f.c.i.l.s.Slf4jLog(info):37 - See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.13
2022-10-26 17:55:44 INFO o.f.c.i.l.s.Slf4jLog(info):37 - 
2022-10-26 17:55:44 INFO i.a.d.c.DatabaseMigrationCheck(check):46 - Current database migration version 0.40.12.001.
2022-10-26 17:55:44 INFO i.a.d.c.DatabaseMigrationCheck(check):47 - Minimum Flyway version required 0.35.15.001.
2022-10-26 17:55:44 INFO i.a.d.c.DatabaseMigrationCheck(check):62 - Verified that database has been migrated to the required minimum version 60000.
2022-10-26 17:55:44 INFO i.a.s.ServerApp(assertDatabasesReady):162 - Checking jobs database flyway migration version..
2022-10-26 17:55:44 INFO i.a.c.EnvConfigs(getEnvOrDefault):1079 - Using default value for environment variable JOBS_DATABASE_INITIALIZATION_TIMEOUT_MS: '60000'
2022-10-26 17:55:44 WARN i.a.d.c.DatabaseAvailabilityCheck(check):38 - Waiting for database to become available...
2022-10-26 17:55:44 INFO i.a.d.c.DatabaseAvailabilityCheck(lambda$isDatabaseConnected$1):75 - Testing airbyte jobs database connection...
2022-10-26 17:55:44 INFO i.a.d.c.DatabaseAvailabilityCheck(check):57 - Database available.
2022-10-26 17:55:44 INFO o.f.c.i.l.s.Slf4jLog(info):37 - Flyway Community Edition 8.5.13 by Redgate
2022-10-26 17:55:44 INFO o.f.c.i.l.s.Slf4jLog(info):37 - See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.13
2022-10-26 17:55:44 INFO o.f.c.i.l.s.Slf4jLog(info):37 - 
2022-10-26 17:55:44 INFO o.f.c.i.l.s.Slf4jLog(info):37 - Database: jdbc:postgresql://db:5432/airbyte (PostgreSQL 13.8)
2022-10-26 17:55:44 INFO o.f.c.i.l.s.Slf4jLog(info):37 - Flyway Community Edition 8.5.13 by Redgate
2022-10-26 17:55:44 INFO o.f.c.i.l.s.Slf4jLog(info):37 - See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.13
2022-10-26 17:55:44 INFO o.f.c.i.l.s.Slf4jLog(info):37 - 
2022-10-26 17:55:44 INFO i.a.d.c.DatabaseMigrationCheck(check):46 - Current database migration version 0.40.14.001.
2022-10-26 17:55:44 INFO i.a.d.c.DatabaseMigrationCheck(check):47 - Minimum Flyway version required 0.29.15.001.
2022-10-26 17:55:44 INFO i.a.d.c.DatabaseMigrationCheck(check):62 - Verified that database has been migrated to the required minimum version 60000.
2022-10-26 17:55:44 INFO i.a.s.ServerApp(getServer):182 - Creating config repository...
2022-10-26 17:55:44 INFO i.a.c.EnvConfigs(getEnvOrDefault):1079 - Using default value for environment variable SECRET_PERSISTENCE: 'TESTING_CONFIG_DB_TABLE'
2022-10-26 17:55:44 INFO i.a.c.EnvConfigs(getEnvOrDefault):1079 - Using default value for environment variable SECRET_PERSISTENCE: 'TESTING_CONFIG_DB_TABLE'
2022-10-26 17:55:44 INFO i.a.c.EnvConfigs(getEnvOrDefault):1079 - Using default value for environment variable SECRET_PERSISTENCE: 'TESTING_CONFIG_DB_TABLE'
2022-10-26 17:55:44 INFO i.a.s.ServerApp(getServer):196 - Creating jobs persistence...
2022-10-26 17:55:44 INFO i.a.c.EnvConfigs(getEnvOrDefault):1079 - Using default value for environment variable DEPLOYMENT_MODE: 'OSS'
2022-10-26 17:55:44 INFO i.a.c.EnvConfigs(getEnvOrDefault):1079 - Using default value for environment variable WORKER_ENVIRONMENT: 'DOCKER'
2022-10-26 17:55:44 INFO i.a.c.EnvConfigs(getEnvOrDefault):1079 - Using default value for environment variable DEPLOYMENT_MODE: 'OSS'
2022-10-26 17:55:44 INFO i.a.c.EnvConfigs(getEnvOrDefault):1079 - Using default value for environment variable TEMPORAL_CLOUD_CLIENT_CERT: ''
2022-10-26 17:55:44 INFO i.a.c.EnvConfigs(getEnvOrDefault):1079 - Using default value for environment variable TEMPORAL_CLOUD_CLIENT_KEY: ''
2022-10-26 17:55:44 INFO i.a.c.EnvConfigs(getEnvOrDefault):1079 - Using default value for environment variable TEMPORAL_CLOUD_ENABLED: 'false'
2022-10-26 17:55:44 INFO i.a.c.EnvConfigs(getEnvOrDefault):1079 - Using default value for environment variable TEMPORAL_CLOUD_HOST: ''
2022-10-26 17:55:44 INFO i.a.c.EnvConfigs(getEnvOrDefault):1079 - Using default value for environment variable TEMPORAL_CLOUD_NAMESPACE: ''
2022-10-26 17:55:44 INFO i.a.c.EnvConfigs(getEnvOrDefault):1079 - Using default value for environment variable TEMPORAL_HISTORY_RETENTION_IN_DAYS: '30'
2022-10-26 17:55:44 INFO i.a.c.t.TemporalUtils(getTemporalClientWhenConnected):224 - Waiting for temporal server...
2022-10-26 17:55:44 WARN i.a.c.t.TemporalUtils(getTemporalClientWhenConnected):235 - Waiting for namespace default to be initialized in temporal...
2022-10-26 17:55:51 WARN i.t.i.r.GrpcSyncRetryer(retry):56 - Retrying after failure
io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: Deadline exceeded after 4.992691438s. 
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271) ~[grpc-stub-1.49.0.jar:1.49.0]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252) ~[grpc-stub-1.49.0.jar:1.49.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165) ~[grpc-stub-1.49.0.jar:1.49.0]
	at io.grpc.health.v1.HealthGrpc$HealthBlockingStub.check(HealthGrpc.java:252) ~[grpc-services-1.49.0.jar:1.49.0]
	at io.temporal.serviceclient.WorkflowServiceStubsImpl.lambda$checkHealth$2(WorkflowServiceStubsImpl.java:286) ~[temporal-serviceclient-1.8.1.jar:?]
	at io.temporal.internal.retryer.GrpcSyncRetryer.retry(GrpcSyncRetryer.java:61) ~[temporal-serviceclient-1.8.1.jar:?]
	at io.temporal.internal.retryer.GrpcRetryer.retryWithResult(GrpcRetryer.java:51) ~[temporal-serviceclient-1.8.1.jar:?]
	at io.temporal.serviceclient.WorkflowServiceStubsImpl.checkHealth(WorkflowServiceStubsImpl.java:279) ~[temporal-serviceclient-1.8.1.jar:?]
	at io.temporal.serviceclient.WorkflowServiceStubsImpl.<init>(WorkflowServiceStubsImpl.java:186) ~[temporal-serviceclient-1.8.1.jar:?]
	at io.temporal.serviceclient.WorkflowServiceStubs.newInstance(WorkflowServiceStubs.java:51) ~[temporal-serviceclient-1.8.1.jar:?]
	at io.temporal.serviceclient.WorkflowServiceStubs.newInstance(WorkflowServiceStubs.java:41) ~[temporal-serviceclient-1.8.1.jar:?]
	at io.airbyte.commons.temporal.TemporalUtils.lambda$createTemporalService$0(TemporalUtils.java:96) ~[io.airbyte-airbyte-commons-temporal-0.40.17.jar:?]
	at io.airbyte.commons.temporal.TemporalUtils.getTemporalClientWhenConnected(TemporalUtils.java:240) ~[io.airbyte-airbyte-commons-temporal-0.40.17.jar:?]
	at io.airbyte.commons.temporal.TemporalUtils.createTemporalService(TemporalUtils.java:92) ~[io.airbyte-airbyte-commons-temporal-0.40.17.jar:?]
	at io.airbyte.commons.temporal.TemporalUtils.createTemporalService(TemporalUtils.java:107) ~[io.airbyte-airbyte-commons-temporal-0.40.17.jar:?]
	at io.airbyte.commons.temporal.TemporalUtils.createTemporalService(TemporalUtils.java:111) ~[io.airbyte-airbyte-commons-temporal-0.40.17.jar:?]
	at io.airbyte.server.ServerApp.getServer(ServerApp.java:232) ~[io.airbyte-airbyte-server-0.40.17.jar:?]
	at io.airbyte.server.ServerApp.main(ServerApp.java:323) ~[io.airbyte-airbyte-server-0.40.17.jar:?]
```

## Steps to Reproduce
1. `git clone https://github.com/airbytehq/airbyte.git`
2. `cd air byte`
3. `docker-compose up -d`

## Are you willing to submit a PR?
Yes

----------------------------------------------------------------

## Additional Notes:

The following issues mention similar behavior as a result of a heartbeat failure (`ActivityExecutionContextImpl(doHeartBeat):153 - Heartbeat failed`) :
- #4975
- #6417
- #10053

Error messages are looking similar to that of those mentioned in the following comment that references issues #4536 and #6417: https://github.com/airbytehq/airbyte/issues/4975#issuecomment-981645888

However, the main issue I am experiencing is unrelated to a heartbeat failure, **suggesting this as not a duplicate of #4975, #6417, or #10053**.

[This discussion thread is also relevant](https://discuss.airbyte.io/t/error-io-grpc-statusruntimeexception-deadline-exceeded-deadline-exceeded-after/254).

Each of these issues were closed with the suggestion of upgrading to the latest version/release or increasing the amount of resources, however, doing either seems to have made no difference in standing up a deployment.

## Troubleshooting Performed
- Deployment on another machine
	I have deployed the equivalent Airbyte version on a smaller machine with less resources using the same environment without any issues.
	
	- **Airbyte version**: v0.40.17
	- **OS Version / Instance**: Ubuntu 20.04.5
		- Additional info:
		```
		OS: Ubuntu 20.04.5 LTS x86_64
		Host: 10M2S0A200 ThinkCentre M715q
		Kernel: 5.4.0-131-generic
		CPU: AMD PRO A10-8770E R7 4C+6G (4) @ 2.800GHz
		Memory: 1833MiB / 6962MiB
		```
	- **Deployment**: Docker version 20.10.18
	- **Source Connector and version**: N/A
	- **Destination Connector and version**: N/A

- Asserting no memory limit on containers
	`$ docker stats --no-stream`
	```
	CONTAINER ID   NAME                                         CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
	97e16f2b5c50   airbyte-proxy                                0.00%     4.547MiB / 62.68GiB   0.01%     8.09kB / 0B       0B / 16.4kB       3
	b4369b8d499c   airbyte-worker                               0.53%     342.6MiB / 62.68GiB   0.53%     19kB / 18.5kB     0B / 393kB        99
	fe09701dced9   airbyte-webapp                               0.00%     15.08MiB / 62.68GiB   0.02%     4.25kB / 0B       0B / 8.19kB       17
	bfced5e6bbf1   airbyte-cron                                 0.75%     313.1MiB / 62.68GiB   0.49%     17.2kB / 16.9kB   0B / 393kB        85
	133a2f8e9af6   airbyte-db                                   0.42%     95.16MiB / 62.68GiB   0.15%     1.08MB / 993kB    0B / 5.05MB       49
	73ff9391bd9a   airbyte-temporal                             1.37%     61.62MiB / 62.68GiB   0.10%     289kB / 403kB     401kB / 16.4kB    21
	db4c2ffabe3f   airbyte-server                               0.66%     282.9MiB / 62.68GiB   0.44%     45.7kB / 37.3kB   0B / 197kB        67
	```

- Ensuring no memory limit set within repository's `.env`
	```
	...
	### JOBS ###
	# Relevant to scaling.
	SYNC_JOB_MAX_ATTEMPTS=3
	SYNC_JOB_MAX_TIMEOUT_DAYS=3
	JOB_MAIN_CONTAINER_CPU_REQUEST=
	JOB_MAIN_CONTAINER_CPU_LIMIT=
	JOB_MAIN_CONTAINER_MEMORY_REQUEST=
	JOB_MAIN_CONTAINER_MEMORY_LIMIT=
	
	NORMALIZATION_JOB_MAIN_CONTAINER_MEMORY_LIMIT=
	NORMALIZATION_JOB_MAIN_CONTAINER_MEMORY_REQUEST=
	NORMALIZATION_JOB_MAIN_CONTAINER_CPU_LIMIT=
	NORMALIZATION_JOB_MAIN_CONTAINER_CPU_REQUEST=
	
	### LOGGING/MONITORING/TRACKING ###
	TRACKING_STRATEGY=segment
	JOB_ERROR_REPORTING_STRATEGY=logging
	# Although not present as an env var, expected by Log4J configuration.
	LOG_LEVEL=INFO
	
	
	### APPLICATIONS ###
	# Worker #
	WORKERS_MICRONAUT_ENVIRONMENTS=control-plane
	# Cron #
	CRON_MICRONAUT_ENVIRONMENTS=control-plane
	# Relevant to scaling.
	MAX_SYNC_WORKERS=5
	MAX_SPEC_WORKERS=5
	MAX_CHECK_WORKERS=5
	MAX_DISCOVER_WORKERS=5
	# Temporal Activity configuration
	ACTIVITY_MAX_ATTEMPT=
	ACTIVITY_INITIAL_DELAY_BETWEEN_ATTEMPTS_SECONDS=
	ACTIVITY_MAX_DELAY_BETWEEN_ATTEMPTS_SECONDS=
	WORKFLOW_FAILURE_RESTART_DELAY_SECONDS=
	...
	```
----------------------------------------------------------------

While is genuinely unclear to me what the problem could be, any help would be greatly appreciated as I would love to experiment with Airbyte more.

**Comment by nullmaxwell** [comment]
To add some context to the timeline, I am adding an excerpt that describes the first instance of the `io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED` exception.

From `airbyte-server` container:
```
...
2022-10-31 15:18:53 WARN i.t.i.r.GrpcSyncRetryer(retry):56 - Retrying after failure
io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: Deadline exceeded after 4.993337405s. 
...
```

**Comment by sh4sh** [comment]
Hmm interesting, this is hard to pin down. As far as I can tell temporal started successfully, after this snippet it appears to successfully talk to the airbyte db:

```
Temporal server started.
Registering default namespace: default.
Error: Operation DescribeNamespace failed.
Error Details: rpc error: code = NotFound desc = Namespace default does not exist.
('export TEMPORAL_CLI_SHOW_STACKS=1' to see stack traces)
Default namespace default not found. Creating...
{"level":"info","ts":"2022-10-31T15:18:41.826Z","msg":"Get dynamic config","name":"system.visibilityArchivalState","value":"enabled","default-value":"enabled","logging-call-at":"config.go:79"}
{"level":"info","ts":"2022-10-31T15:18:41.828Z","msg":"Register namespace succeeded","service":"frontend","wf-namespace":"default","wf-namespace-id":"9838de98-4c2d-4fc0-9c0c-09c574e33276","logging-call-at":"handler.go:296"}
Namespace default successfully registered.
Default namespace default registration complete.
```

So if it's not temporal container failure, or resource limit related, then my guess is that there's something weird going on with communication between the temporal and airbyte-server containers.

Few quick questions:
1. Have you ever gotten Airbyte working on this machine before?
2. Can you confirm that you're using the latest `docker-compose` or if there's a version difference between both machines?
3. Sorry if you've already tried, but can you see if restarting the Docker service would help? Either `systemctl restart docker` or equivalent, or restarting the machine itself.

Also, depending on how you last shut down Airbyte, it might still have some volumes and networks leftover in Docker. To completely remove these resources, you may need to run `docker-compose down -v` https://docs.docker.com/engine/reference/commandline/compose_down/#options

**Comment by nullmaxwell** [comment]
Thanks for taking the time to look into this with me.

To answer your questions:
1. Unfortunately not; I've attempted to make deployments with several different versions/tagged releases to no avail.
	
2. Yes, both machines are using `docker-compose v1.29.2`, there is currently no version difference between the two.
	Machine A (non-working Airbyte deployment):
	```
	> docker-compose -version
		docker-compose version 1.29.2
	```
	
	Machine B (working Airbyte deployment):
	```
	> docker-compose -version
		docker-compose version 1.29.2
	```

3. I've tried manually restarting the service, bare metal reboot, and even purging stale containers with `docker volume prune` when re-composing alongside the command you suggested. 

It's reassuring that you suspect there's no temporal failure here, but on the consideration that it could be a communication issue between containers, do you have any troubleshooting I can perform?

**Comment by sh4sh** [comment]
I am not too sure about troubleshooting that, but if restarting doesn't fix it then I'm not sure if that's the issue to be honest. Something we haven't checked is the worker container, which Temporal appears to communicate with successfully. Can you share logs from that container to see if there is anything there? (At this point, if you can share logs from any/all containers other than the server and temporal that would be very helpful!)

Also, it might be worth trying the latest Airbyte in case there has been relevant changes.

It looks like the same issue here: https://github.com/airbytehq/airbyte/issues/10053

Just to double check, can you confirm you have >= 30GB disk space? Also, if you're able to take a look at the [Scaling Airbyte](https://docs.airbyte.com/operator-guides/scaling-airbyte) document and try some settings that might improve the behaviour.

**Comment by nullmaxwell** [comment]
Sure, I've attached archives of logs from `v0.40.17` and `v0.40.18`. The issue persists in `v0.40.18`. If more logging is necessary just let me know!

I made a reference to #10053 in my original post as well. 
I do not believe it's a similar issue considering the amount of resources available on the host machine in addition to the fact that the `StatusRuntimeException` is not caused as a result of a heartbeat failure. 
Please see my notes and the 'troubleshooting performed' section on my original comment for more detail.

Also, for the sake of being thorough here are the results of `df -h` showing well above 30G available on the host:
```
...
Filesystem      Size  Used Avail Use% Mounted on
/dev/md2p1      883G  247G  592G  30% /
...
```

[airbyte_deployment_logs_v04018.zip](https://github.com/airbytehq/airbyte/files/9965838/airbyte_deployment_logs_v04018.zip)
[airbyte_deployment_logs_v04017.zip](https://github.com/airbytehq/airbyte/files/9965839/airbyte_deployment_logs_v04017.zip)

**Comment by sh4sh** [comment]
I am stuck on this, I've assigned it to the team's backlog in hopes they might know what's going on. 🙏🏽 Feel free to ping me if I can help with anything.

**Comment by andyjih** [comment]
@benmoriceau Can you take a look? I'd timebox the investigation. Thanks!

**Comment by nullmaxwell** [comment]
I'm happy to provide more information if it's needed. Thanks for taking the time to triage

**Comment by seyal84** [comment]
any update on this ?

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 365 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.
