### ISSUE TITLE
Invalid $project :: caused by :: '$' by itself is not a valid FieldPath

### ISSUE THREAD

**Issue by gousta** [airbytehq/airbyte#18510]
## Environment
- **Airbyte version**:  0.30.25-alpha
- **OS Version / Instance**: DigitalOcean marketplace one-click-install (Ubuntu Airbyte 0.30.25 on 20.04)
- **Deployment**: Docker (using Ubuntu Airbyte 0.30.25 on 20.04 DO marketplace one-click-install)
- **Source Connector and version**: airbyte/source-mongodb-v2 / v0.1.19
- **Destination Connector and version**: airbyte/destination-postgres / v0.3.26
- **Step where error happened**: Setup new connection when fetching schema

## Current Behavior
I'm trying to setup a connection from successfully connected MongoDB as source to successfully connected Postgres as destination.
At step "We are fetching the schema of your data source" I get back an error:
`Failed to fetch schema. Please try again`

## Expected Behavior
It should have found and displayed the collections of this database (as it did for my other databases on the same cluster)

## Logs

<details>
<summary>sources.undefined Logs</summary>
2022-10-26 19:55:59 INFO () TemporalAttemptExecution(get):94 - Executing worker wrapper. Airbyte version: 0.30.25-alpha
2022-10-26 19:55:59 INFO () LineGobbler(voidCall):82 - Checking if airbyte/source-mongodb-v2:0.1.19 exists...
2022-10-26 19:55:59 INFO () DockerProcessFactory(create):127 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/a7da5db2-daea-4bbc-a57e-1fbfabdc19e2/0 --network host --log-driver none airbyte/source-mongodb-v2:0.1.19 discover --config source_config.json
2022-10-26 19:56:01 INFO () DefaultAirbyteStreamFactory(internalLog):98 - starting source: class io.airbyte.integrations.source.mongodb.MongoDbSource
2022-10-26 19:56:01 INFO () DefaultAirbyteStreamFactory(internalLog):98 - integration args: {discover=null, config=source_config.json}
2022-10-26 19:56:01 INFO () DefaultAirbyteStreamFactory(internalLog):98 - Running integration: io.airbyte.integrations.source.mongodb.MongoDbSource
2022-10-26 19:56:01 INFO () DefaultAirbyteStreamFactory(internalLog):98 - Command: DISCOVER
2022-10-26 19:56:01 INFO () DefaultAirbyteStreamFactory(internalLog):98 - Integration config: IntegrationConfig{command=DISCOVER, configPath='source_config.json', catalogPath='null', statePath='null'}
2022-10-26 19:56:01 WARN () DefaultAirbyteStreamFactory(internalLog):97 - Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2022-10-26 19:56:01 WARN () DefaultAirbyteStreamFactory(internalLog):97 - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2022-10-26 19:56:02 INFO () DefaultAirbyteStreamFactory(internalLog):98 - Cluster created with settings {hosts=[127.0.0.1:27017], srvHost=deliverback-production.1qat7.mongodb.net, mode=MULTIPLE, requiredClusterType=REPLICA_SET, serverSelectionTimeout='30000 ms', requiredReplicaSetName='atlas-voj603-shard-0'}
2022-10-26 19:56:02 INFO () DefaultAirbyteStreamFactory(internalLog):98 - Cluster description not yet available. Waiting for 30000 ms before timing out
2022-10-26 19:56:02 INFO () DefaultAirbyteStreamFactory(internalLog):98 - Adding discovered server deliverback-production-shard-00-00.1qat7.mongodb.net:27017 to client view of cluster
2022-10-26 19:56:02 INFO () DefaultAirbyteStreamFactory(internalLog):98 - Adding discovered server deliverback-production-shard-00-02.1qat7.mongodb.net:27017 to client view of cluster
2022-10-26 19:56:02 INFO () DefaultAirbyteStreamFactory(internalLog):98 - Adding discovered server deliverback-production-shard-00-01.1qat7.mongodb.net:27017 to client view of cluster
2022-10-26 19:56:02 INFO () DefaultAirbyteStreamFactory(internalLog):98 - No server chosen by com.mongodb.client.internal.MongoClientDelegate$1@a68df9 from cluster description ClusterDescription{type=REPLICA_SET, connectionMode=MULTIPLE, serverDescriptions=[ServerDescription{address=deliverback-production-shard-00-00.1qat7.mongodb.net:27017, type=UNKNOWN, state=CONNECTING}, ServerDescription{address=deliverback-production-shard-00-02.1qat7.mongodb.net:27017, type=UNKNOWN, state=CONNECTING}, ServerDescription{address=deliverback-production-shard-00-01.1qat7.mongodb.net:27017, type=UNKNOWN, state=CONNECTING}]}. Waiting for 30000 ms before timing out
2022-10-26 19:56:02 INFO () DefaultAirbyteStreamFactory(internalLog):98 - Opened connection [connectionId{localValue:2, serverValue:662}] to deliverback-production-shard-00-00.1qat7.mongodb.net:27017
2022-10-26 19:56:02 INFO () DefaultAirbyteStreamFactory(internalLog):98 - Opened connection [connectionId{localValue:5, serverValue:1964}] to deliverback-production-shard-00-01.1qat7.mongodb.net:27017
2022-10-26 19:56:02 INFO () DefaultAirbyteStreamFactory(internalLog):98 - Opened connection [connectionId{localValue:3, serverValue:1401}] to deliverback-production-shard-00-02.1qat7.mongodb.net:27017
2022-10-26 19:56:02 INFO () DefaultAirbyteStreamFactory(internalLog):98 - Opened connection [connectionId{localValue:6, serverValue:1963}] to deliverback-production-shard-00-01.1qat7.mongodb.net:27017
2022-10-26 19:56:02 INFO () DefaultAirbyteStreamFactory(internalLog):98 - Opened connection [connectionId{localValue:4, serverValue:1400}] to deliverback-production-shard-00-02.1qat7.mongodb.net:27017
2022-10-26 19:56:02 INFO () DefaultAirbyteStreamFactory(internalLog):98 - Opened connection [connectionId{localValue:1, serverValue:663}] to deliverback-production-shard-00-00.1qat7.mongodb.net:27017
2022-10-26 19:56:02 INFO () DefaultAirbyteStreamFactory(internalLog):98 - Monitor thread successfully connected to server with description ServerDescription{address=deliverback-production-shard-00-01.1qat7.mongodb.net:27017, type=REPLICA_SET_PRIMARY, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=18, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=411938570, setName='atlas-voj603-shard-0', canonicalAddress=deliverback-production-shard-00-01.1qat7.mongodb.net:27017, hosts=[deliverback-production-shard-00-01.1qat7.mongodb.net:27017, deliverback-production-shard-00-02.1qat7.mongodb.net:27017, deliverback-production-shard-00-00.1qat7.mongodb.net:27017], passives=[], arbiters=[], primary='deliverback-production-shard-00-01.1qat7.mongodb.net:27017', tagSet=TagSet{[Tag{name='nodeType', value='ELECTABLE'}, Tag{name='provider', value='AWS'}, Tag{name='region', value='EU_CENTRAL_1'}, Tag{name='workloadType', value='OPERATIONAL'}]}, electionId=7fffffff0000000000000002, setVersion=1, topologyVersion=TopologyVersion{processId=6359843fe32746bbc61b01dd, counter=8}, lastWriteDate=Wed Oct 26 19:56:00 UTC 2022, lastUpdateTimeNanos=1760130834583164}
2022-10-26 19:56:02 INFO () DefaultAirbyteStreamFactory(internalLog):98 - Monitor thread successfully connected to server with description ServerDescription{address=deliverback-production-shard-00-00.1qat7.mongodb.net:27017, type=REPLICA_SET_SECONDARY, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=18, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=408501363, setName='atlas-voj603-shard-0', canonicalAddress=deliverback-production-shard-00-00.1qat7.mongodb.net:27017, hosts=[deliverback-production-shard-00-01.1qat7.mongodb.net:27017, deliverback-production-shard-00-02.1qat7.mongodb.net:27017, deliverback-production-shard-00-00.1qat7.mongodb.net:27017], passives=[], arbiters=[], primary='deliverback-production-shard-00-01.1qat7.mongodb.net:27017', tagSet=TagSet{[Tag{name='nodeType', value='ELECTABLE'}, Tag{name='provider', value='AWS'}, Tag{name='region', value='EU_CENTRAL_1'}, Tag{name='workloadType', value='OPERATIONAL'}]}, electionId=null, setVersion=1, topologyVersion=TopologyVersion{processId=6359847e6dc68e4da70da559, counter=9}, lastWriteDate=Wed Oct 26 19:56:00 UTC 2022, lastUpdateTimeNanos=1760130833458585}
2022-10-26 19:56:02 INFO () DefaultAirbyteStreamFactory(internalLog):98 - Monitor thread successfully connected to server with description ServerDescription{address=deliverback-production-shard-00-02.1qat7.mongodb.net:27017, type=REPLICA_SET_SECONDARY, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=18, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=416819216, setName='atlas-voj603-shard-0', canonicalAddress=deliverback-production-shard-00-02.1qat7.mongodb.net:27017, hosts=[deliverback-production-shard-00-01.1qat7.mongodb.net:27017, deliverback-production-shard-00-02.1qat7.mongodb.net:27017, deliverback-production-shard-00-00.1qat7.mongodb.net:27017], passives=[], arbiters=[], primary='deliverback-production-shard-00-01.1qat7.mongodb.net:27017', tagSet=TagSet{[Tag{name='nodeType', value='ELECTABLE'}, Tag{name='provider', value='AWS'}, Tag{name='region', value='EU_CENTRAL_1'}, Tag{name='workloadType', value='OPERATIONAL'}]}, electionId=null, setVersion=1, topologyVersion=TopologyVersion{processId=63598449c3fd404325596429, counter=6}, lastWriteDate=Wed Oct 26 19:56:00 UTC 2022, lastUpdateTimeNanos=1760130835128033}
2022-10-26 19:56:03 INFO () DefaultAirbyteStreamFactory(internalLog):98 - Setting max election id to 7fffffff0000000000000002 from replica set primary deliverback-production-shard-00-01.1qat7.mongodb.net:27017
2022-10-26 19:56:03 INFO () DefaultAirbyteStreamFactory(internalLog):98 - Setting max set version to 1 from replica set primary deliverback-production-shard-00-01.1qat7.mongodb.net:27017
2022-10-26 19:56:03 INFO () DefaultAirbyteStreamFactory(internalLog):98 - Discovered replica set primary deliverback-production-shard-00-01.1qat7.mongodb.net:27017
2022-10-26 19:56:03 INFO () DefaultAirbyteStreamFactory(internalLog):98 - Opened connection [connectionId{localValue:7, serverValue:1966}] to deliverback-production-shard-00-01.1qat7.mongodb.net:27017
2022-10-26 19:56:03 INFO () DefaultAirbyteStreamFactory(internalLog):98 - Opened connection [connectionId{localValue:9, serverValue:1968}] to deliverback-production-shard-00-01.1qat7.mongodb.net:27017
2022-10-26 19:56:03 INFO () DefaultAirbyteStreamFactory(internalLog):98 - Opened connection [connectionId{localValue:8, serverValue:1967}] to deliverback-production-shard-00-01.1qat7.mongodb.net:27017
2022-10-26 19:56:03 ERROR () DefaultAirbyteStreamFactory(internalLog):96 - Something went wrong in the connector. See the logs for more details.
2022-10-26 19:56:03 INFO () JsonSchemaValidator(test):56 - JSON schema validation failed. 
errors: $.type: does not have a value in the enumeration [RECORD, STATE, LOG, SPEC, CONNECTION_STATUS, CATALOG]
2022-10-26 19:56:03 ERROR () DefaultAirbyteStreamFactory(lambda$create$1):71 - Validation failed: {"type":"TRACE","trace":{"type":"ERROR","emitted_at":1.666814163617E12,"error":{"message":"Something went wrong in the connector. See the logs for more details.","internal_message":"com.mongodb.MongoCommandException: Command failed with error 16872 (Location16872): 'Invalid $project :: caused by :: '$' by itself is not a valid FieldPath' on server deliverback-production-shard-00-01.1qat7.mongodb.net:27017. The full response is {\"ok\": 0.0, \"errmsg\": \"Invalid $project :: caused by :: '$' by itself is not a valid FieldPath\", \"code\": 16872, \"codeName\": \"Location16872\", \"$clusterTime\": {\"clusterTime\": {\"$timestamp\": {\"t\": 1666814160, \"i\": 1}}, \"signature\": {\"hash\": {\"$binary\": {\"base64\": \"n3WHiWZkbAT+62kq/h3COPIMFXc=\", \"subType\": \"00\"}}, \"keyId\": 7158898819512401922}}, \"operationTime\": {\"$timestamp\": {\"t\": 1666814160, \"i\": 1}}}","stack_trace":"com.mongodb.MongoCommandException: Command failed with error 16872 (Location16872): 'Invalid $project :: caused by :: '$' by itself is not a valid FieldPath' on server deliverback-production-shard-00-01.1qat7.mongodb.net:27017. The full response is {\"ok\": 0.0, \"errmsg\": \"Invalid $project :: caused by :: '$' by itself is not a valid FieldPath\", \"code\": 16872, \"codeName\": \"Location16872\", \"$clusterTime\": {\"clusterTime\": {\"$timestamp\": {\"t\": 1666814160, \"i\": 1}}, \"signature\": {\"hash\": {\"$binary\": {\"base64\": \"n3WHiWZkbAT+62kq/h3COPIMFXc=\", \"subType\": \"00\"}}, \"keyId\": 7158898819512401922}}, \"operationTime\": {\"$timestamp\": {\"t\": 1666814160, \"i\": 1}}}\n\tat com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:198)\n\tat com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:418)\n\tat com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:342)\n\tat com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:116)\n\tat com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:647)\n\tat com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:71)\n\tat com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:244)\n\tat com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:227)\n\tat com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:127)\n\tat com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:117)\n\tat com.mongodb.internal.connection.DefaultServer$OperationCountTrackingConnection.command(DefaultServer.java:348)\n\tat com.mongodb.internal.operation.CommandOperationHelper.createReadCommandAndExecute(CommandOperationHelper.java:228)\n\tat com.mongodb.internal.operation.CommandOperationHelper.lambda$executeRetryableRead$4(CommandOperationHelper.java:210)\n\tat com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$2(OperationHelper.java:564)\n\tat com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:589)\n\tat com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$3(OperationHelper.java:563)\n\tat com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:589)\n\tat com.mongodb.internal.operation.OperationHelper.withSourceAndConnection(OperationHelper.java:562)\n\tat com.mongodb.internal.operation.CommandOperationHelper.lambda$executeRetryableRead$5(CommandOperationHelper.java:207)\n\tat com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:65)\n\tat com.mongodb.internal.operation.CommandOperationHelper.executeRetryableRead(CommandOperationHelper.java:213)\n\tat com.mongodb.internal.operation.CommandOperationHelper.executeRetryableRead(CommandOperationHelper.java:193)\n\tat com.mongodb.internal.operation.AggregateOperationImpl.execute(AggregateOperationImpl.java:195)\n\tat com.mongodb.internal.operation.AggregateOperation.execute(AggregateOperation.java:306)\n\tat com.mongodb.internal.operation.AggregateOperation.execute(AggregateOperation.java:46)\n\tat com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:191)\n\tat com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:135)\n\tat com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:92)\n\tat com.mongodb.client.internal.MongoIterableImpl.cursor(MongoIterableImpl.java:97)\n\tat io.airbyte.db.mongodb.MongoUtils.getTypes(MongoUtils.java:269)\n\tat io.airbyte.db.mongodb.MongoUtils.lambda$getUniqueFields$0(MongoUtils.java:208)\n\tat java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)\n\tat java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)\n\tat java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)\n\tat java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)\n\tat java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)\n\tat java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)\n\tat java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)\n\tat java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)\n\tat java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)\n\tat io.airbyte.db.mongodb.MongoUtils.getUniqueFields(MongoUtils.java:215)\n\tat io.airbyte.integrations.source.mongodb.MongoDbSource.lambda$discoverInternal$1(MongoDbSource.java:106)\n\tat java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)\n\tat java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)\n\tat java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)\n\tat java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)\n\tat java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)\n\tat java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)\n\tat java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)\n\tat java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)\n\tat java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)\n\tat java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)\n","failure_type":"system_error"}}}
2022-10-26 19:56:04 INFO () TemporalAttemptExecution(lambda$getWorkerThread$1):148 - Completing future exceptionally...
io.airbyte.workers.WorkerException: Discover job subprocess finished with exit code 1
	at io.airbyte.workers.DefaultDiscoverCatalogWorker.run(DefaultDiscoverCatalogWorker.java:70) ~[io.airbyte-airbyte-workers-0.30.25-alpha.jar:?]
	at io.airbyte.workers.DefaultDiscoverCatalogWorker.run(DefaultDiscoverCatalogWorker.java:24) ~[io.airbyte-airbyte-workers-0.30.25-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$1(TemporalAttemptExecution.java:145) ~[io.airbyte-airbyte-workers-0.30.25-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
2022-10-26 19:56:04 INFO () TemporalAttemptExecution(get):115 - Stopping cancellation check scheduling...
2022-10-26 19:56:04 WARN () POJOActivityTaskHandler$POJOActivityImplementation(execute):243 - Activity failure. ActivityId=16db7a7d-bafc-3623-ae3a-2fa07a516352, activityType=Run, attempt=1
java.util.concurrent.ExecutionException: io.airbyte.workers.WorkerException: Discover job subprocess finished with exit code 1
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2063) ~[?:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:113) ~[io.airbyte-airbyte-workers-0.30.25-alpha.jar:?]
	at io.airbyte.workers.temporal.discover.catalog.DiscoverCatalogActivityImpl.run(DiscoverCatalogActivityImpl.java:57) ~[io.airbyte-airbyte-workers-0.30.25-alpha.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor75.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityInboundCallsInterceptor.execute(POJOActivityTaskHandler.java:277) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityImplementation.execute(POJOActivityTaskHandler.java:216) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.POJOActivityTaskHandler.handle(POJOActivityTaskHandler.java:181) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:192) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:154) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73) ~[temporal-sdk-1.0.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: io.airbyte.workers.WorkerException: Discover job subprocess finished with exit code 1
	at io.airbyte.workers.DefaultDiscoverCatalogWorker.run(DefaultDiscoverCatalogWorker.java:70) ~[io.airbyte-airbyte-workers-0.30.25-alpha.jar:?]
	at io.airbyte.workers.DefaultDiscoverCatalogWorker.run(DefaultDiscoverCatalogWorker.java:24) ~[io.airbyte-airbyte-workers-0.30.25-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$1(TemporalAttemptExecution.java:145) ~[io.airbyte-airbyte-workers-0.30.25-alpha.jar:?]
	... 1 more
</details>

## Steps to Reproduce
I don't know how to reproduce it. I have successfully connected 5 other mongodb databases from another 3 clusters just fine and this error happens on this one only. Could it be something with the data?

## Are you willing to submit a PR?
Yes I'm willing but I only know PHP and JS/Typescript and a bit of Golang and I have more than 10 years to write Java

<img width="1281" alt="Screenshot 2022-10-26 at 23 18 43" src="https://user-images.githubusercontent.com/632929/198128572-64939d34-d854-4c2f-8d00-566f1a22e39e.png">

**Comment by gousta** [comment]
FOUND IT! I'm using payloadcms.com and it automatically creates a collection called "default" that inside contains:
```
{
    "_id" : ObjectId("6325be9b55cf47b016af5c16"),
    "" : null
}
```

I backed up and deleted it and I reached the final screen!

<img width="1271" alt="Screenshot 2022-10-26 at 23 30 27" src="https://user-images.githubusercontent.com/632929/198131221-04f0b8db-2bcf-40a3-8c46-972ab2d7e000.png">

**Comment by natalyjazzviolin** [comment]
@gousta wonderful to hear that you've solved it! Closing the issue.

**Comment by gousta** [comment]
Actually I fixed the issue but airbyte mongodb connector shouldn't break because of that. Its bad user experience and not everybody may be able to delete such records.

I believe the connector should be more resilient with these things and provide you the opportunity to move to the next screen and skip that problematic collection
