### ISSUE TITLE
helm upgrade deletes and recreates serviceaccount

### ISSUE THREAD

**Issue by rhooper** [airbytehq/airbyte#18731]
Related to - #15701 #10336 #9133

## Environment
- **Airbyte version**:  0.44.17 / 0.44.33
- **OS Version / Instance**: macOS ARM, AWS EKS (Graviton, Intel)
- **Deployment**: helm chart version 0.44.33
- **Source Connector and version**: n/a
- **Destination Connector and version**: n/a
- **Step where error happened**: Deploy /  Upgrade Airbyte

## Current Behavior
The serviceaccount object is deleted and recreated during helm upgrade, making updating values to tweak configuration challenging.

## Expected Behavior
Service account should be untouched.

## Logs

```
$ (main) helm upgrade  -f values.yaml -n airybte airybte-airbyte . --debug 
upgrade.go:142: [debug] preparing upgrade for airybte-airbyte
upgrade.go:150: [debug] performing update for airybte-airbyte
upgrade.go:322: [debug] creating upgraded release for airybte-airbyte
client.go:310: [debug] Starting delete for "airbyte-admin" ServiceAccount
client.go:128: [debug] creating 1 resource(s)
client.go:310: [debug] Starting delete for "airbyte-db" StatefulSet
client.go:128: [debug] creating 1 resource(s)
client.go:310: [debug] Starting delete for "airbyte-db-svc" Service
client.go:128: [debug] creating 1 resource(s)
client.go:310: [debug] Starting delete for "airbyte-minio" StatefulSet
client.go:128: [debug] creating 1 resource(s)
client.go:310: [debug] Starting delete for "airbyte-minio-svc" Service
client.go:128: [debug] creating 1 resource(s)
client.go:310: [debug] Starting delete for "airybte-airbyte-airbyte-env" ConfigMap
client.go:128: [debug] creating 1 resource(s)
client.go:310: [debug] Starting delete for "airybte-airbyte-airbyte-secrets" Secret
client.go:128: [debug] creating 1 resource(s)
client.go:310: [debug] Starting delete for "airybte-airbyte-airbyte-bootloader" Pod
client.go:128: [debug] creating 1 resource(s)
client.go:540: [debug] Watching for changes to Pod airybte-airbyte-airbyte-bootloader with timeout of 5m0s
client.go:568: [debug] Add/Modify event for airybte-airbyte-airbyte-bootloader: ADDED
client.go:627: [debug] Pod airybte-airbyte-airbyte-bootloader pending
client.go:568: [debug] Add/Modify event for airybte-airbyte-airbyte-bootloader: MODIFIED
client.go:629: [debug] Pod airybte-airbyte-airbyte-bootloader running
client.go:568: [debug] Add/Modify event for airybte-airbyte-airbyte-bootloader: MODIFIED
client.go:629: [debug] Pod airybte-airbyte-airbyte-bootloader running
client.go:568: [debug] Add/Modify event for airybte-airbyte-airbyte-bootloader: MODIFIED
client.go:622: [debug] Pod airybte-airbyte-airbyte-bootloader succeeded
client.go:229: [debug] checking 13 resources for changes
client.go:512: [debug] Looks like there are no changes for Secret "airybte-airbyte-gcs-log-creds"
client.go:512: [debug] Looks like there are no changes for ConfigMap "airybte-airbyte-pod-sweeper-sweep-pod-script"
client.go:512: [debug] Looks like there are no changes for ConfigMap "airybte-airbyte-temporal-dynamicconfig"
client.go:512: [debug] Looks like there are no changes for Role "airbyte-admin-role"
client.go:521: [debug] Patch RoleBinding "airbyte-admin-binding" in namespace airybte
client.go:512: [debug] Looks like there are no changes for Service "airybte-airbyte-airbyte-server-svc"
client.go:512: [debug] Looks like there are no changes for Service "airybte-airbyte-temporal"
client.go:512: [debug] Looks like there are no changes for Service "airybte-airbyte-airbyte-webapp-svc"
client.go:521: [debug] Patch Deployment "airybte-airbyte-pod-sweeper-pod-sweeper" in namespace airybte
client.go:521: [debug] Patch Deployment "airybte-airbyte-server" in namespace airybte
client.go:521: [debug] Patch Deployment "airybte-airbyte-temporal" in namespace airybte
client.go:521: [debug] Patch Deployment "airybte-airbyte-webapp" in namespace airybte
client.go:521: [debug] Patch Deployment "airybte-airbyte-worker" in namespace airybte
upgrade.go:157: [debug] updating status for upgraded release for airybte-airbyte
```

worker
```
│ 2022-10-31 18:46:09 ERROR i.t.i.w.Poller$PollerUncaughtExceptionHandler(logPollErrors):289 - Failure in thread Host Local Workflow Poller: 4                         │
│ io.grpc.StatusRuntimeException: UNAVAILABLE: last connection error: connection closed before server preface received                                                 │
│     at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271) ~[grpc-stub-1.49.0.jar:1.49.0]                                                        │
│     at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252) ~[grpc-stub-1.49.0.jar:1.49.0]                                                                    │
│     at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165) ~[grpc-stub-1.49.0.jar:1.49.0]                                                               │
│     at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.pollWorkflowTaskQueue(WorkflowServiceGrpc.java:2656) ~[temporal-servicecli │
│     at io.temporal.internal.worker.WorkflowPollTask.poll(WorkflowPollTask.java:83) ~[temporal-sdk-1.8.1.jar:?]                                                       │
│     at io.temporal.internal.worker.WorkflowPollTask.poll(WorkflowPollTask.java:39) ~[temporal-sdk-1.8.1.jar:?]                                                       │
│     at io.temporal.internal.worker.Poller$PollExecutionTask.run(Poller.java:262) ~[temporal-sdk-1.8.1.jar:?]                                                         │
│     at io.temporal.internal.worker.Poller$PollLoopTask.run(Poller.java:227) ~[temporal-sdk-1.8.1.jar:?]                                                              │
│     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]                                                                        │
│     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]                                                                        │
│     at java.lang.Thread.run(Thread.java:1589) ~[?:?]                                                                                                                 │
```
## Steps to Reproduce
1. Install helm chart w/values.
2. Upgrade helm chart with upgrade.   No need to edit values.
3. Check logs for errors...

If you try to perform any action that needs to spin up pods (eg create source, destination, etc.) there will be errors about being unable to speak to the kubernetes API.

pod-sweeper:
│ error: You must be logged in to the server (Unauthorized)                                                                                                            │

## Are you willing to submit a PR?
Probably

**Comment by jkleinkauff** [comment]
Any updates?

**Comment by sajarin** [comment]
Hey @jkleinkauff sorry. At the moment, I don't have an update for you on this issue.

**Comment by jkleinkauff** [comment]
Found a workaround that is working for us.
Just delete the **workers** and **server** pods and Airbyte should be able to communicate to the API. Not ideal but it works. Thank you.

**Comment by mixecan** [comment]
I think that the reason is the default behaviour of [helm hooks](https://helm.sh/docs/topics/charts_hooks/#hook-deletion-policies)

The ServiceAccount is created with these hooks
```yaml
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
```
And helm documentation states that
> If no hook deletion policy annotation is specified, the before-hook-creation behavior applies by default.

Honestly I'm not sure hooks are the best way to go for this use case. My understanding is that this ServiceAccount is needed in advance by `airbyte-bootloader` so why not creating a dedicated SA in the bootloader chart instead of referencing the SA from the server chart?

In my case, in order to avoid it being deleted, I'm applying a kustomization patch to remove the annotation.

**Comment by mixecan** [comment]
I'm using `kustomize`

`kustomization.yaml`
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: https://airbytehq.github.io/helm-charts
    releaseName: airbyte
    name: airbyte
    version: 0.43.29
    valuesFile: helm/airbyte.yaml

patchesJson6902:
  - path: remove-sa-hooks.yaml
    target:
      version: v1
      kind: ServiceAccount
      name: airbyte-admin
```

`remove-sa-hooks.yaml`
```yaml
- op: remove
  path: "/metadata/annotations/helm.sh~1hook"
- op: remove
  path: "/metadata/annotations/helm.sh~1hook-weight"
```

**Comment by benen** [comment]
Thanks @mixecan, yeah I'm using kustomize too so this is extremely helpful

**Comment by cpdeethree** [comment]
@rhooper we fixed this a couple of months ago in helm (we no longer support kustomize). Can you verify that this issue persists still in the latest helm chart version?

**Comment by mixecan** [comment]
hi @cpdeethree
I tested your helm chart version `0.45.17` without any patch against my live deployment version `0.43.29` and I got this diff

```diff
diff -u -N /var/folders/hx/n90707sd045fgx1cc3_4cnjw0000gn/T/LIVE-1286449609/v1.ServiceAccount.airbyte.airbyte-admin /var/folders/hx/n90707sd045fgx1cc3_4cnjw0000gn/T/MERGED-4056173688/v1.ServiceAccount.airbyte.airbyte-admin
--- /var/folders/hx/n90707sd045fgx1cc3_4cnjw0000gn/T/LIVE-1286449609/v1.ServiceAccount.airbyte.airbyte-admin
+++ /var/folders/hx/n90707sd045fgx1cc3_4cnjw0000gn/T/MERGED-4056173688/v1.ServiceAccount.airbyte.airbyte-admin
@@ -2,6 +2,8 @@
 kind: ServiceAccount
 metadata:
   annotations:
+    helm.sh/hook: pre-install,pre-upgrade
+    helm.sh/hook-weight: "-10"
     kubectl.kubernetes.io/last-applied-configuration: |
       [....]
   creationTimestamp: "2023-02-23T17:35:20Z"
@@ -9,8 +11,8 @@
     app.kubernetes.io/instance: airbyte
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/name: airbyte
```

The hooks are still there so I would expect it to have the same behaviour described by OP.

**Comment by akshaykarle** [comment]
We've also run into the same issue. Disabling the serviceAccount creation or doing something similar to what @mixecan mentioned seems to work for us. But it does mean we are unable to provision everything with helm. We are using the following setup:
Helm chart version: 0.45.40
Deployment type: OSS on kubernetes (GKE with autopilot, version: 1.26.5-gke.1200)

Fixing the serviceAccount to not use helm hooks or some other way to ensure that the serviceAccount isn't recreated every time we run `helm install/upgrade` would be perfect

**Comment by don-code** [comment]
I found similar behavior with Minio in #29613 just last week. Is it understood why these templates are defined as hooks to begin with? I'm preparing to fork the chart internally and remove these annotations that way, but I'm not sure as to their original purpose.

**Comment by glevineLeap** [comment]
FYI @cpdeethree related to https://airbytehq.slack.com/archives/C01AHCD885S/p1689806906461159

**Comment by talha-naeem1** [comment]
Suggesting to remove Service account creation from helm chart of airbyte. it causes issues very often

**Comment by c-p-b** [comment]
FWIW, one way I've gotten around this is by forcing the chart to not manage the service account and manage it externally. You can do so like this:

```yaml
global:
  # -- Service Account name override
  serviceAccountName: "airbyte-admin"


serviceAccount:
  create: false
  name: "airbyte-admin"
```

Where name matches the global name you specify

then create/manage the service account through your alternative methodology of choice e.g. Argo, Kube manifest, etc.
