### ISSUE TITLE
Support custom DB connection parameter 

### ISSUE THREAD

**Issue by jeesim2** [airbytehq/airbyte#1879]
## Tell us about the problem you're trying to solve

* We operate Mysql Server that set timezone as 'KST'
* From mysql-connector-java 5.1.x, server side timezone KST is not recognized
* It is still possible to connect mysql if we set `serverTimezone=Asia/Seoul` at connection url like below.
```
jdbc:mysql://ip:port/TestDB?serverTimezone=Asia/Seoul
```

## Additional context

This is the full fail log from source set.

<details>

```
2021-01-28 09:45:12 INFO (/tmp/workspace/9/0) WorkerRun(call):58 - Executing worker wrapper...
2021-01-28 09:45:12 INFO (/tmp/workspace/9/0) LineGobbler(voidCall):69 - Checking if airbyte/source-mysql:0.1.9 exists...
2021-01-28 09:45:12 INFO (/tmp/workspace/9/0) LineGobbler(voidCall):69 - airbyte/source-mysql:0.1.9 was found locally.
2021-01-28 09:45:12 DEBUG (/tmp/workspace/9/0) DockerProcessBuilderFactory(create):104 - Preparing command: docker run --rm -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/9/0 --network host airbyte/source-mysql:0.1.9 check --config tap_config.json
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-01-28 09:45:14 [32mINFO[m i.a.i.s.m.MySqlSource(main):75 - {} - starting source: class io.airbyte.integrations.source.mysql.MySqlSource
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-01-28 09:45:14 [32mINFO[m i.a.i.b.IntegrationRunner(run):78 - {} - Running integration: io.airbyte.integrations.source.mysql.MySqlSource
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-01-28 09:45:14 [32mINFO[m i.a.i.b.IntegrationCliParser(parseOptions):135 - {} - integration args: {check=null, config=tap_config.json}
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-01-28 09:45:14 [32mINFO[m i.a.i.b.IntegrationRunner(run):82 - {} - Command: CHECK
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-01-28 09:45:14 [32mINFO[m i.a.i.b.IntegrationRunner(run):83 - {} - Integration config: IntegrationConfig{command=CHECK, configPath='tap_config.json', catalogPath='null', statePath='null'}
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-01-28 09:45:14 [36mDEBUG[m i.a.i.s.j.AbstractJdbcSource(check):129 - {} - Exception while checking connection:
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - java.sql.SQLException: Cannot create PoolableConnectionFactory (The server time zone value 'KST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specific time zone value if you want to utilize time zone support.)
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:669) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:544) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:753) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at io.airbyte.db.jdbc.DefaultJdbcDatabase$DataSourceConnectionSupplier.getConnection(DefaultJdbcDatabase.java:135) ~[io.airbyte-airbyte-db-0.13.1-alpha.jar:?]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at io.airbyte.db.jdbc.DefaultJdbcDatabase.bufferedResultSetQuery(DefaultJdbcDatabase.java:65) ~[io.airbyte-airbyte-db-0.13.1-alpha.jar:?]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at io.airbyte.db.jdbc.StreamingJdbcDatabase.bufferedResultSetQuery(StreamingJdbcDatabase.java:63) ~[io.airbyte-airbyte-db-0.13.1-alpha.jar:?]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at io.airbyte.integrations.source.jdbc.AbstractJdbcSource.check(AbstractJdbcSource.java:125) [io.airbyte.airbyte-integrations.connectors-source-jdbc-0.13.1-alpha.jar:?]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:90) [io.airbyte.airbyte-integrations.bases-base-java-0.13.1-alpha.jar:?]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at io.airbyte.integrations.source.mysql.MySqlSource.main(MySqlSource.java:76) [io.airbyte.airbyte-integrations.connectors-source-mysql-0.13.1-alpha.jar:?]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - Caused by: java.sql.SQLException: The server time zone value 'KST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specific time zone value if you want to utilize time zone support.
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:76) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:55) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:355) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:115) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:665) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - ... 8 more
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - Caused by: com.mysql.cj.exceptions.InvalidConnectionAttributeException: The server time zone value 'KST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specific time zone value if you want to utilize time zone support.
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[?:?]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at com.mysql.cj.util.TimeUtil.getCanonicalTimezone(TimeUtil.java:134) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at com.mysql.cj.protocol.a.NativeProtocol.configureTimezone(NativeProtocol.java:2186) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at com.mysql.cj.protocol.a.NativeProtocol.initServerSession(NativeProtocol.java:2209) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at com.mysql.cj.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:1318) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:967) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:55) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:355) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:115) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:665) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2021-01-28 09:45:14 INFO (/tmp/workspace/9/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - ... 8 more
2021-01-28 09:45:14 DEBUG (/tmp/workspace/9/0) DefaultCheckConnectionWorker(run):96 - Check connection job subprocess finished with exit code 0
2021-01-28 09:45:14 DEBUG (/tmp/workspace/9/0) DefaultCheckConnectionWorker(run):97 - Check connection job received output: io.airbyte.config.StandardCheckConnectionOutput@3211223c[status=failed,message=Could not connect with provided configuration.]
```

</details>

**Comment by jrhizor** [comment]
Maybe each of the sql dbs should have a `oneOf` for how they connect, either with the fields spelled out or a jdbc connect string?

**Comment by michel-tricot** [comment]
Yep! I like this idea

**Comment by michel-tricot** [comment]
The only complexity is if one day we need to move away from JDBC for one particular db.

**Comment by michel-tricot** [comment]
Actually it is just a matter of parsing the url

**Comment by jeesim2** [comment]
By mistake, I deleted my idea.
As you understand, one **connection parameter string** field will be enough. : )

**Comment by ChristopheDuong** [comment]
> By mistake, I deleted my idea.
> As you understand, one **connection parameter string** field for Mysql datasource set up will be enough. : )

@jeesim2, do you think you could contribute by submitting a PR with the required change to make this source compatible with your server's settings?

(We can definitely accompany you in making this change, feel free to reach out on slack too!)

Here are the main things to take care of:
1. Add such  optional `connection parameter string field ` in the properties list of source-MySql spec at [airbyte-integrations/connectors/source-mysql/src/main/resources/spec.json](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-mysql/src/main/resources/spec.json)
2. If the user  has specified a value for that parameter field, then we can concatenate it to the jdbc_url at: https://github.com/airbytehq/airbyte/blob/e9769c81599dc79d50840b24a076ce3806e81a9e/airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/MySqlSource.java#L52

To develop locally you would just need to run:
`./gradlew :airbyte-integrations:connectors:source-mysql:build`

Then to test, you could run these commands for example:
https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/connectors/source-jira#locally-running-the-connector-docker-image

Thanks!!

**Comment by jeesim2** [comment]
> @jeesim2, do you think you could contribute by submitting a PR with the required change to make this source compatible with your server's settings?

Sure. I will give it a try : )

**Comment by data-k** [comment]
This would really help us as well, running into a similar issue connecting to an Azure Managed MySql Database.

> The server timezone value 'UTC' is unrecognized or represents more than one timezone

Cheers

**Comment by sherifnada** [comment]
@data-k would you be interested in contributing this to the MySQL connector? It should be fairly straightforward if you're interested.
