### ISSUE TITLE
ConnectionRefusedError: [Errno 61] Connection refused

### ISSUE THREAD

**Issue by wasa4587** [airbytehq/airbyte#1880]
## Expected Behavior
*It works like the getting started docs says.*

## Current Behavior
`Traceback (most recent call last):
  File "site-packages/urllib3/connectionpool.py", line 677, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "site-packages/docker/transport/unixconn.py", line 43, in connect
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/requests/adapters.py", line 449, in send
  File "site-packages/urllib3/connectionpool.py", line 727, in urlopen
  File "site-packages/urllib3/util/retry.py", line 403, in increment
  File "site-packages/urllib3/packages/six.py", line 734, in reraise
  File "site-packages/urllib3/connectionpool.py", line 677, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "site-packages/docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 205, in _retrieve_server_version
  File "site-packages/docker/api/daemon.py", line 181, in version
  File "site-packages/docker/utils/decorators.py", line 46, in inner
  File "site-packages/docker/api/client.py", line 228, in _get
  File "site-packages/requests/sessions.py", line 543, in get
  File "site-packages/requests/sessions.py", line 530, in request
  File "site-packages/requests/sessions.py", line 643, in send
  File "site-packages/requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 123, in perform_command
  File "compose/cli/command.py", line 69, in project_from_options
  File "compose/cli/command.py", line 132, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "site-packages/docker/api/client.py", line 188, in __init__
  File "site-packages/docker/api/client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))
[19608] Failed to execute script docker-compose`

## Steps to Reproduce
1. git clone https://github.com/airbytehq/airbyte.git
2. cd airbyte
3. docker-compose up

## Severity of the bug for you
 High

## Airbyte Version
VERSION=0.14.1-alpha

## Additional context
first there was a message that the API_URL was not found,
I'll add it empty, then I found somewhere this may works `API_URL=/api/v1/`
then i added my local ip 192.168.1.XXX,
maybe this is the issue, but i couldn't find what to add in there or any additional instructions

My OS is macOS Big Sur version 11.1

**Comment by ChristopheDuong** [comment]
What does your ENV look like before invoking `docker-compose up`?

I'm wondering if you are not encountering the same situation as this other issue:
if you already use environment variables from another project/tool as described here: #1848, they may be in conflict with the ones Airbyte uses in its `.env` file...

**Comment by wasa4587** [comment]
Hi this is my .env
`API_URL=/api/v1/
VERSION=0.14.1-alpha
DATABASE_USER=docker
DATABASE_PASSWORD=docker
DATABASE_DB=airbyte
CONFIG_ROOT=/data
WORKSPACE_ROOT=/tmp/workspace
DATA_DOCKER_MOUNT=airbyte_data
DB_DOCKER_MOUNT=airbyte_db
WORKSPACE_DOCKER_MOUNT=airbyte_workspace
# todo (cgardens) - when we are mount raw directories instead of named volumes, *_DOCKER_MOUNT must
# be the same as *_ROOT.
# Issue: https://github.com/airbytehq/airbyte/issues/578
LOCAL_ROOT=/tmp/airbyte_local
LOCAL_DOCKER_MOUNT=/tmp/airbyte_local
TRACKING_STRATEGY=segment
# todo (cgardens) - hack to handle behavior change in docker compose. *_PARENT directories MUST
# already exist on the host filesystem and MUST be parents of *_ROOT.
# Issue: https://github.com/airbytehq/airbyte/issues/577
HACK_LOCAL_ROOT_PARENT=/tmp
`

**Comment by ChristopheDuong** [comment]
Sorry if I wasn't clear, I meant what is your env as what is the output of: `/usr/bin/env`

Is there any environment variable in your shell that is the same as the ones declared by Airbyte in that .env file that you just copy/paste?

**Comment by wasa4587** [comment]
Oh I see,
I don't think so
 
```
it@it-MacBook-Pro airbyte % /usr/bin/env
TERM_PROGRAM=Apple_Terminal
SHELL=/bin/zsh
TERM=xterm-256color
TMPDIR=/var/folders/nx/8t7n51455wq8wmd3lrx9wjtr0000gn/T/
TERM_PROGRAM_VERSION=440
TERM_SESSION_ID=09CBE75E-5BBB-4DC5-910F-69D58570E04E
USER=it
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.M999OdLCc6/Listeners
PATH=/Users/it/.nvm/versions/node/v12.20.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
__CFBundleIdentifier=com.apple.Terminal
PWD=/Users/it/personal/airbyte
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/it
LOGNAME=it
OLDPWD=/Users/it/personal/airbyte
NVM_DIR=/Users/it/.nvm
NVM_CD_FLAGS=-q
NVM_BIN=/Users/it/.nvm/versions/node/v12.20.1/bin
NVM_INC=/Users/it/.nvm/versions/node/v12.20.1/include/node
LANG=en_US.UTF-8
_=/usr/bin/env
```

nevertheless I was able to run it in a linux server, i think i'll try it there, thank you for you reply

**Comment by jrhizor** [comment]
Is your docker daemon running? What is the output when you run `docker ps -q`?

Changing `API_URL` shouldn't have been necessary in your case. Can you remove that change from `.env` and show the error that occurs?

**Comment by wasa4587** [comment]
omg, I'm such a noob, my docker machine was down, I'm so sorry
Thank you very much for your help

**Comment by jrhizor** [comment]
:) np, glad to help. I know I've run into this type of thing a bunch!
