### ISSUE TITLE
Redshift destination fails on illegal unquoted character

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1881]
## Description
A user reported that their sync from Stripe to redshift is failing with the exception following exception: 

```
Illegal unquoted character ((CTRL-CHAR, code 0)): has to be escaped using backslash to be included in name
```

full stack trace: 

<details>

```
Remaining buffered records: 0
2021-01-23 06:20:29 INFO (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 2021-01-23 06:20:29 [32mINFO[m i.a.i.d.r.RedshiftSqlOperations(insertRecords):59 - {} - actual size of batch: 502
2021-01-23 06:20:33 INFO (/tmp/workspace/25/2) DefaultAirbyteStreamFactory(internalLog):110 - METRIC: {"type": "timer", "metric": "http_request_duration", "value": 3.8829355239868164, "tags": {"endpoint": "charges", "status": "succeeded"}}
2021-01-23 06:20:33 INFO (/tmp/workspace/25/2) DefaultAirbyteStreamFactory(internalLog):110 - message='Stripe API response' path=https://api.stripe.com/v1/charges?limit=100&created[gte]=1577836800&created[lt]=1580428800&starting_after=ch_1G6U6RLglQ30FHRSPxrz6ZFG response_code=200
2021-01-23 06:20:37 INFO (/tmp/workspace/25/2) DefaultAirbyteStreamFactory(internalLog):110 - message='Request to Stripe api' method=get path=https://api.stripe.com/v1/charges?limit=100&created[gte]=1577836800&created[lt]=1580428800&starting_after=ch_1G6U1xLglQ30FHRS8jBiQ8y2
2021-01-23 06:20:37 INFO (/tmp/workspace/25/2) DefaultAirbyteStreamFactory(internalLog):110 - METRIC: {"type": "timer", "metric": "http_request_duration", "value": 4.078315258026123, "tags": {"endpoint": "charges", "status": "succeeded"}}
2021-01-23 06:20:37 INFO (/tmp/workspace/25/2) DefaultAirbyteStreamFactory(internalLog):110 - message='Stripe API response' path=https://api.stripe.com/v1/charges?limit=100&created[gte]=1577836800&created[lt]=1580428800&starting_after=ch_1G6U1xLglQ30FHRS8jBiQ8y2 response_code=200
2021-01-23 06:20:37 INFO (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 2021-01-23 06:20:37 [32mINFO[m i.a.i.b.FailureTrackingConsumer(close):64 - {} - hasFailed: false.
2021-01-23 06:20:37 INFO (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 2021-01-23 06:20:37 [32mINFO[m i.a.i.d.b.BufferedStreamConsumer(close):158 - {} - executing on success close procedure.
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - Exception in thread "main" java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 	at java.base/java.lang.StringUTF16.compress(StringUTF16.java:161)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 	at java.base/java.lang.String.<init>(String.java:3651)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 	at java.base/java.lang.String.<init>(String.java:294)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 	at java.base/java.nio.HeapCharBuffer.toString(HeapCharBuffer.java:688)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 	at java.base/java.nio.CharBuffer.toString(CharBuffer.java:1626)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 	at java.base/java.util.regex.Matcher.group(Matcher.java:650)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 	at java.base/java.util.regex.Matcher.group(Matcher.java:604)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 	at java.base/java.util.Scanner.findWithinHorizon(Scanner.java:1793)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 	at java.base/java.util.Scanner.hasNextLine(Scanner.java:1610)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 	at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:124)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:112)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 	at io.airbyte.integrations.destination.redshift.RedshiftDestination.main(RedshiftDestination.java:65)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 	Suppressed: java.lang.RuntimeException: java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Illegal unquoted character ((CTRL-CHAR, code 0)): has to be escaped using backslash to be included in name
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 -  at [Source: (String)"{"stream":"charges","data":{"id":"ch_1G6U0ILglQ30FHRSGwHxlAzm","object":"charge","amount":100,"amount_refunded":0,"application":null,"application_fee":null,"balance_transaction":"txn_1G6U0JLglQ30FHRScmNyTJ2n","captured":true,"created":"2020-01-30T03:47:42.000000Z","currency":"usd","customer":"cus_9pROA4bpcyK5Jj","description":null,"destination":null,"dispute":null,"failure_code":null,"failure_message":null,"fraud_details":{},"invoice":null,"livemode":true,"metadata":{"appointment_id":"162900253""[truncated 1428 chars]; line: 1, column: 1218] (through reference chain: io.airbyte.protocol.models.AirbyteRecordMessage["data"])
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.writeStreamsWithNRecords(BufferedStreamConsumer.java:192)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.close(BufferedStreamConsumer.java:165)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at io.airbyte.integrations.base.FailureTrackingConsumer.close(FailureTrackingConsumer.java:65)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:122)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		... 2 more
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 	Caused by: java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Illegal unquoted character ((CTRL-CHAR, code 0)): has to be escaped using backslash to be included in name
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 -  at [Source: (String)"{"stream":"charges","data":{"id":"ch_1G6U0ILglQ30FHRSGwHxlAzm","object":"charge","amount":100,"amount_refunded":0,"application":null,"application_fee":null,"balance_transaction":"txn_1G6U0JLglQ30FHRScmNyTJ2n","captured":true,"created":"2020-01-30T03:47:42.000000Z","currency":"usd","customer":"cus_9pROA4bpcyK5Jj","description":null,"destination":null,"dispute":null,"failure_code":null,"failure_message":null,"fraud_details":{},"invoice":null,"livemode":true,"metadata":{"appointment_id":"162900253""[truncated 1428 chars]; line: 1, column: 1218] (through reference chain: io.airbyte.protocol.models.AirbyteRecordMessage["data"])
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at io.airbyte.commons.json.Jsons.deserialize(Jsons.java:63)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.lambda$writeStreamsWithNRecords$1(BufferedStreamConsumer.java:185)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at java.base/java.util.stream.SliceOps$1$1.accept(SliceOps.java:199)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at io.airbyte.commons.lang.Queues$1.tryAdvance(Queues.java:52)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.writeStreamsWithNRecords(BufferedStreamConsumer.java:186)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		... 5 more
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 	Caused by: com.fasterxml.jackson.databind.JsonMappingException: Illegal unquoted character ((CTRL-CHAR, code 0)): has to be escaped using backslash to be included in name
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 -  at [Source: (String)"{"stream":"charges","data":{"id":"ch_1G6U0ILglQ30FHRSGwHxlAzm","object":"charge","amount":100,"amount_refunded":0,"application":null,"application_fee":null,"balance_transaction":"txn_1G6U0JLglQ30FHRScmNyTJ2n","captured":true,"created":"2020-01-30T03:47:42.000000Z","currency":"usd","customer":"cus_9pROA4bpcyK5Jj","description":null,"destination":null,"dispute":null,"failure_code":null,"failure_message":null,"fraud_details":{},"invoice":null,"livemode":true,"metadata":{"appointment_id":"162900253""[truncated 1428 chars]; line: 1, column: 1218] (through reference chain: io.airbyte.protocol.models.AirbyteRecordMessage["data"])
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:397)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:356)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1732)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:290)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4218)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3214)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3182)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at io.airbyte.commons.json.Jsons.deserialize(Jsons.java:61)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		... 17 more
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 	Caused by: com.fasterxml.jackson.core.JsonParseException: Illegal unquoted character ((CTRL-CHAR, code 0)): has to be escaped using backslash to be included in name
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 -  at [Source: (String)"{"stream":"charges","data":{"id":"ch_1G6U0ILglQ30FHRSGwHxlAzm","object":"charge","amount":100,"amount_refunded":0,"application":null,"application_fee":null,"balance_transaction":"txn_1G6U0JLglQ30FHRScmNyTJ2n","captured":true,"created":"2020-01-30T03:47:42.000000Z","currency":"usd","customer":"cus_9pROA4bpcyK5Jj","description":null,"destination":null,"dispute":null,"failure_code":null,"failure_message":null,"fraud_details":{},"invoice":null,"livemode":true,"metadata":{"appointment_id":"162900253""[truncated 1428 chars]; line: 1, column: 1218]
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at com.fasterxml.jackson.core.base.ParserBase._throwUnquotedSpace(ParserBase.java:1046)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._parseName2(ReaderBasedJsonParser.java:1743)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._parseName(ReaderBasedJsonParser.java:1710)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:932)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:250)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:68)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
2021-01-23 06:20:37 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):69 - 		... 22 more
2021-01-23 06:20:42 INFO (/tmp/workspace/25/2) DefaultAirbyteStreamFactory(internalLog):110 - message='Request to Stripe api' method=get path=https://api.stripe.com/v1/charges?limit=100&created[gte]=1577836800&created[lt]=1580428800&starting_after=ch_1G6TwrLglQ30FHRSSM4KSiyL
2021-01-23 06:20:42 INFO (/tmp/workspace/25/2) DefaultAirbyteStreamFactory(internalLog):110 - METRIC: {"type": "timer", "metric": "http_request_duration", "value": 4.367048263549805, "tags": {"endpoint": "charges", "status": "succeeded"}}
2021-01-23 06:20:42 INFO (/tmp/workspace/25/2) DefaultAirbyteStreamFactory(internalLog):110 - message='Stripe API response' path=https://api.stripe.com/v1/charges?limit=100&created[gte]=1577836800&created[lt]=1580428800&starting_after=ch_1G6TwrLglQ30FHRSSM4KSiyL response_code=200
2021-01-23 06:20:42 DEBUG (/tmp/workspace/25/2) DefaultAirbyteSource(close):109 - Closing tap process
2021-01-23 06:21:42 WARN (/tmp/workspace/25/2) WorkerUtils(gentleClose):49 - Process is taking too long to finish. Killing it
2021-01-23 06:21:42 ERROR (/tmp/workspace/25/2) LineGobbler(voidCall):72 - Error when reading stream
java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:168) ~[?:?]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:281) ~[?:?]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:343) ~[?:?]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:297) ~[?:?]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339) ~[?:?]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188) ~[?:?]
	at java.io.InputStreamReader.read(InputStreamReader.java:181) ~[?:?]
	at java.io.BufferedReader.fill(BufferedReader.java:161) ~[?:?]
	at java.io.BufferedReader.readLine(BufferedReader.java:326) ~[?:?]
	at java.io.BufferedReader.readLine(BufferedReader.java:392) ~[?:?]
	at io.airbyte.commons.io.LineGobbler.voidCall(LineGobbler.java:68) [io.airbyte-airbyte-commons-0.13.0-alpha.jar:?]
	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:33) [io.airbyte-airbyte-commons-0.13.0-alpha.jar:?]
	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:29) [io.airbyte-airbyte-commons-0.13.0-alpha.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
2021-01-23 06:21:42 ERROR (/tmp/workspace/25/2) DefaultSyncWorker(run):104 - Sync worker failed.
java.io.IOException: Stream closed
	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:442) ~[?:?]
	at java.io.OutputStream.write(OutputStream.java:162) ~[?:?]
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:123) ~[?:?]
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:242) ~[?:?]
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:312) ~[?:?]
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:290) ~[?:?]
	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:131) ~[?:?]
	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:208) ~[?:?]
	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:120) ~[?:?]
	at java.io.BufferedWriter.write(BufferedWriter.java:233) ~[?:?]
	at java.io.Writer.write(Writer.java:249) ~[?:?]
	at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.accept(DefaultAirbyteDestination.java:79) ~[io.airbyte-airbyte-workers-0.13.0-alpha.jar:?]
	at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.accept(DefaultAirbyteDestination.java:46) ~[io.airbyte-airbyte-workers-0.13.0-alpha.jar:?]
	at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:99) [io.airbyte-airbyte-workers-0.13.0-alpha.jar:?]
	at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:48) [io.airbyte-airbyte-workers-0.13.0-alpha.jar:?]
	at io.airbyte.workers.wrappers.OutputConvertingWorker.run(OutputConvertingWorker.java:44) [io.airbyte-airbyte-workers-0.13.0-alpha.jar:?]
	at io.airbyte.workers.wrappers.JobOutputSyncWorker.run(JobOutputSyncWorker.java:32) [io.airbyte-airbyte-workers-0.13.0-alpha.jar:?]
	at io.airbyte.scheduler.WorkerRun.lambda$new$0(WorkerRun.java:53) [io.airbyte-airbyte-scheduler-0.13.0-alpha.jar:?]
	at io.airbyte.scheduler.WorkerRun.call(WorkerRun.java:61) [io.airbyte-airbyte-scheduler-0.13.0-alpha.jar:?]
	at io.airbyte.scheduler.WorkerRun.call(WorkerRun.java:42) [io.airbyte-airbyte-scheduler-0.13.0-alpha.jar:?]
	at io.airbyte.commons.concurrency.LifecycledCallable.execute(LifecycledCallable.java:114) [io.airbyte-airbyte-commons-0.13.0-alpha.jar:?]
	at io.airbyte.commons.concurrency.LifecycledCallable.call(LifecycledCallable.java:98) [io.airbyte-airbyte-commons-0.13.0-alpha.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
	Suppressed: io.airbyte.workers.WorkerException: Tap process wasn't successful
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteSource.close(DefaultAirbyteSource.java:112) ~[io.airbyte-airbyte-workers-0.13.0-alpha.jar:?]
		at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:89) [io.airbyte-airbyte-workers-0.13.0-alpha.jar:?]
		at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:48) [io.airbyte-airbyte-workers-0.13.0-alpha.jar:?]
		at io.airbyte.workers.wrappers.OutputConvertingWorker.run(OutputConvertingWorker.java:44) [io.airbyte-airbyte-workers-0.13.0-alpha.jar:?]
		at io.airbyte.workers.wrappers.JobOutputSyncWorker.run(JobOutputSyncWorker.java:32) [io.airbyte-airbyte-workers-0.13.0-alpha.jar:?]
		at io.airbyte.scheduler.WorkerRun.lambda$new$0(WorkerRun.java:53) [io.airbyte-airbyte-scheduler-0.13.0-alpha.jar:?]
		at io.airbyte.scheduler.WorkerRun.call(WorkerRun.java:61) [io.airbyte-airbyte-scheduler-0.13.0-alpha.jar:?]
		at io.airbyte.scheduler.WorkerRun.call(WorkerRun.java:42) [io.airbyte-airbyte-scheduler-0.13.0-alpha.jar:?]
		at io.airbyte.commons.concurrency.LifecycledCallable.execute(LifecycledCallable.java:114) [io.airbyte-airbyte-commons-0.13.0-alpha.jar:?]
		at io.airbyte.commons.concurrency.LifecycledCallable.call(LifecycledCallable.java:98) [io.airbyte-airbyte-commons-0.13.0-alpha.jar:?]
		at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
		at java.lang.Thread.run(Thread.java:832) [?:?]
	Suppressed: java.io.IOException: Stream closed
		at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:442) ~[?:?]
		at java.io.OutputStream.write(OutputStream.java:162) ~[?:?]
		at java.io.BufferedOutputStream.write(BufferedOutputStream.java:123) ~[?:?]
		at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:242) ~[?:?]
		at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:321) ~[?:?]
		at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:325) ~[?:?]
		at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:159) ~[?:?]
		at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:251) ~[?:?]
		at java.io.BufferedWriter.flush(BufferedWriter.java:257) ~[?:?]
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.notifyEndOfStream(DefaultAirbyteDestination.java:87) ~[io.airbyte-airbyte-workers-0.13.0-alpha.jar:?]
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.close(DefaultAirbyteDestination.java:99) ~[io.airbyte-airbyte-workers-0.13.0-alpha.jar:?]
		at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:89) [io.airbyte-airbyte-workers-0.13.0-alpha.jar:?]
		at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:48) [io.airbyte-airbyte-workers-0.13.0-alpha.jar:?]
		at io.airbyte.workers.wrappers.OutputConvertingWorker.run(OutputConvertingWorker.java:44) [io.airbyte-airbyte-workers-0.13.0-alpha.jar:?]
		at io.airbyte.workers.wrappers.JobOutputSyncWorker.run(JobOutputSyncWorker.java:32) [io.airbyte-airbyte-workers-0.13.0-alpha.jar:?]
		at io.airbyte.scheduler.WorkerRun.lambda$new$0(WorkerRun.java:53) [io.airbyte-airbyte-scheduler-0.13.0-alpha.jar:?]
		at io.airbyte.scheduler.WorkerRun.call(WorkerRun.java:61) [io.airbyte-airbyte-scheduler-0.13.0-alpha.jar:?]
		at io.airbyte.scheduler.WorkerRun.call(WorkerRun.java:42) [io.airbyte-airbyte-scheduler-0.13.0-alpha.jar:?]
		at io.airbyte.commons.concurrency.LifecycledCallable.execute(LifecycledCallable.java:114) [io.airbyte-airbyte-commons-0.13.0-alpha.jar:?]
		at io.airbyte.commons.concurrency.LifecycledCallable.call(LifecycledCallable.java:98) [io.airbyte-airbyte-commons-0.13.0-alpha.jar:?]
		at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
		at java.lang.Thread.run(Thread.java:832) [?:?]
```

</details>

## Steps to Reproduce
Unknown yet

## Severity of the bug for you
Medium

## Airbyte Version
v0.13.0-alpha

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368144833156) by [Unito](https://www.unito.io)

**Comment by jrhizor** [comment]
This may be already fixed. Need to verify.

**Comment by ChristopheDuong** [comment]
I wasn't able to reproduce this behavior so far

**Comment by cgardens** [comment]
It seems like this issue isn't actionable, should we close it? We can reopen it if we happen to reproduce it or if it gets reported again.
