### ISSUE TITLE
Worker process of Airbyte >= v0.40.9 fails to work with K8s

### ISSUE THREAD

**Issue by anhtranbk** [airbytehq/airbyte#18888]
## Environment
- **Airbyte version**:  0.40.9 (upgraded to 0.40.18 and this error still happened)
- **OS Version / Instance**: GCP Compute Engine
- **Deployment**: Self-managed Kubernetes cluster running on GCP
- **Source Connector and version**: any
- **Destination Connector and version**: any
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector

## Current Behavior
*When I do any action on web app like Setup new Connection/Deloy job/Setup connector... an exception will occur on Worker node*

After investigating, I found that Airbyte workers are using [Micronaut](https://micronaut.io/) that depends (indirect) on OkHttp version 4.9.x. But Airbyte workers are also using K8s client by Fabric8, that depends on OkHttp version 3.12.x. And these two versions of OkHttp is not compatible with each other. Is it may the root cause of this issue ?

## Expected Behavior
*No error*

## Logs

Stack trace error when exception occurred
```
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void okhttp3.internal.platform.Platform.log(int, java.lang.String, java.lang.Throwable)'
--
2022-10-31 11:20:29 | at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
2022-10-31 11:20:29 | at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
2022-10-31 11:20:29 | at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:160) ~[io.airbyte-airbyte-workers-0.40.17.jar:?]
2022-10-31 11:20:29 | at io.airbyte.workers.temporal.check.connection.CheckConnectionActivityImpl.runWithJobOutput(CheckConnectionActivityImpl.java:107) ~[io.airbyte-airbyte-workers-0.40.17.jar:?]
2022-10-31 11:20:29 | at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
2022-10-31 11:20:29 | at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
2022-10-31 11:20:29 | at io.temporal.internal.activity.POJOActivityTaskHandler$POJOActivityInboundCallsInterceptor.execute(POJOActivityTaskHandler.java:214) ~[temporal-sdk-1.8.1.jar:?]
2022-10-31 11:20:29 | at io.temporal.internal.activity.POJOActivityTaskHandler$POJOActivityImplementation.execute(POJOActivityTaskHandler.java:180) ~[temporal-sdk-1.8.1.jar:?]
2022-10-31 11:20:29 | at io.temporal.internal.activity.POJOActivityTaskHandler.handle(POJOActivityTaskHandler.java:120) ~[temporal-sdk-1.8.1.jar:?]
2022-10-31 11:20:29 | at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:204) ~[temporal-sdk-1.8.1.jar:?]
2022-10-31 11:20:29 | at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:164) ~[temporal-sdk-1.8.1.jar:?]
2022-10-31 11:20:29 | at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93) ~[temporal-sdk-1.8.1.jar:?]
2022-10-31 11:20:29 | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
2022-10-31 11:20:29 | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
2022-10-31 11:20:29 | at java.lang.Thread.run(Thread.java:1589) ~[?:?]
2022-10-31 11:20:29 | Caused by: java.lang.NoSuchMethodError: 'void okhttp3.internal.platform.Platform.log(int, java.lang.String, java.lang.Throwable)'
2022-10-31 11:20:29 | at okhttp3.logging.HttpLoggingInterceptor$Logger$1.log(HttpLoggingInterceptor.java:114) ~[logging-interceptor-3.12.12.jar:?]
2022-10-31 11:20:29 | at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:173) ~[logging-interceptor-3.12.12.jar:?]
2022-10-31 11:20:29 | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:?]
2022-10-31 11:20:29 | at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34) ~[okhttp-4.10.0.jar:?]
2022-10-31 11:20:29 | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:?]
2022-10-31 11:20:29 | at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[okhttp-4.10.0.jar:?]
2022-10-31 11:20:29 | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:?]
2022-10-31 11:20:29 | at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.10.0.jar:?]
2022-10-31 11:20:29 | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:?]
2022-10-31 11:20:29 | at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.10.0.jar:?]
2022-10-31 11:20:29 | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:?]
2022-10-31 11:20:29 | at io.fabric8.kubernetes.client.okhttp.OkHttpClientBuilderImpl$InteceptorAdapter.intercept(OkHttpClientBuilderImpl.java:62) ~[kubernetes-client-5.12.2.jar:?]
2022-10-31 11:20:29 | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:?]
2022-10-31 11:20:29 | at io.fabric8.kubernetes.client.okhttp.OkHttpClientBuilderImpl$InteceptorAdapter.intercept(OkHttpClientBuilderImpl.java:62) ~[kubernetes-client-5.12.2.jar:?]
2022-10-31 11:20:29 | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:?]
2022-10-31 11:20:29 | at io.fabric8.kubernetes.client.okhttp.OkHttpClientBuilderImpl$InteceptorAdapter.intercept(OkHttpClientBuilderImpl.java:62) ~[kubernetes-client-5.12.2.jar:?]
2022-10-31 11:20:29 | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:?]
2022-10-31 11:20:29 | at io.fabric8.kubernetes.client.okhttp.OkHttpClientBuilderImpl$InteceptorAdapter.intercept(OkHttpClientBuilderImpl.java:62) ~[kubernetes-client-5.12.2.jar:?]
2022-10-31 11:20:29 | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:?]
2022-10-31 11:20:29 | at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[okhttp-4.10.0.jar:?]
2022-10-31 11:20:29 | at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154) ~[okhttp-4.10.0.jar:?]
2022-10-31 11:20:29 | at io.fabric8.kubernetes.client.okhttp.OkHttpClientImpl.send(OkHttpClientImpl.java:138) ~[kubernetes-client-5.12.2.jar:?]
2022-10-31 11:20:29 | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.retryWithExponentialBackoff(OperationSupport.java:574) ~[kubernetes-client-5.12.2.jar:?]
2022-10-31 11:20:29 | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:553) ~[kubernetes-client-5.12.2.jar:?]
2022-10-31 11:20:29 | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:518) ~[kubernetes-client-5.12.2.jar:?]
2022-10-31 11:20:29 | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:305) ~[kubernetes-client-5.12.2.jar:?]
2022-10-31 11:20:29 | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:644) ~[kubernetes-client-5.12.2.jar:?]
2022-10-31 11:20:29 | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:83) ~[kubernetes-client-5.12.2.jar:?]
2022-10-31 11:20:29 | at io.fabric8.kubernetes.client.dsl.base.CreateOnlyResourceOperation.create(CreateOnlyResourceOperation.java:61) ~[kubernetes-client-5.12.2.jar:?]
2022-10-31 11:20:29 | at io.fabric8.kubernetes.client.utils.CreateOrReplaceHelper.createOrReplace(CreateOrReplaceHelper.java:48) ~[kubernetes-client-5.12.2.jar:?]
2022-10-31 11:20:29 | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:318) ~[kubernetes-client-5.12.2.jar:?]
2022-10-31 11:20:29 | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:83) ~[kubernetes-client-5.12.2.jar:?]
2022-10-31 11:20:29 | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:308) ~[kubernetes-client-5.12.2.jar:?]
2022-10-31 11:20:29 | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:83) ~[kubernetes-client-5.12.2.jar:?]
2022-10-31 11:20:29 | at io.airbyte.workers.process.KubePodProcess.<init>(KubePodProcess.java:523) ~[io.airbyte-airbyte-commons-worker-0.40.17.jar:?]
2022-10-31 11:20:29 | at io.airbyte.workers.process.KubeProcessFactory.create(KubeProcessFactory.java:134) ~[io.airbyte-airbyte-commons-worker-0.40.17.jar:?]
2022-10-31 11:20:29 | at io.airbyte.workers.process.AirbyteIntegrationLauncher.check(AirbyteIntegrationLauncher.java:86) ~[io.airbyte-airbyte-commons-worker-0.40.17.jar:?]
2022-10-31 11:20:29 | at io.airbyte.workers.general.DefaultCheckConnectionWorker.run(DefaultCheckConnectionWorker.java:60) ~[io.airbyte-airbyte-commons-worker-0.40.17.jar:?]
2022-10-31 11:20:29 | at io.airbyte.workers.general.DefaultCheckConnectionWorker.run(DefaultCheckConnectionWorker.java:36) ~[io.airbyte-airbyte-commons-worker-0.40.17.jar:?]
2022-10-31 11:20:29 | at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$4(TemporalAttemptExecution.java:190) ~[io.airbyte-airbyte-workers-0.40.17.jar:?]
2022-10-31 11:20:29 | ... 1 more
```

## Steps to Reproduce
1. Deploy Airbyte on Kubernetes
2. Do any actions on web app like create new source/destination, setup new connection ... and check worker's log. No actions can be success.

## Are you willing to submit a PR?

Sure. But now I have no idea on how to solve this issue.

**Comment by davinchia** [comment]
@anhtranbk does this still happen on 0.40.18?

**Comment by anhtranbk** [comment]
@davinchia Yes, it's still happening on 0.40.18

**Comment by davinchia** [comment]
that's strange - we run this in Airbyte Cloud and this is working fine for us. 

@anhtranbk how are you deploying Airbyte? Are you changing any configuration?

**Comment by khanhngobackend** [comment]
Dear @davinchia , I'm from the same team with @anhtranbk, we are deploying on K8s, using the official Helm charts, with the help of Kustomize to generate the final manifests.

**Comment by davinchia** [comment]
@khanhngobackend you mean https://artifacthub.io/packages/helm/airbyte/airbyte?

Those aren't well maintained today. Is it possible to use the `stable` kustomize charts in the airbyte monorepo?

**Comment by khanhngobackend** [comment]
@davinchia , we are using Helm charts from https://airbytehq.github.io/helm-charts . 
We followed the official guide: https://docs.airbyte.com/deploying-airbyte/on-kubernetes-via-helm/#adding-helm-repository
The only difference I'm aware of is that we use Kustomize to first generate all manifests before using kubectl to apply (kind-a like gitops).

**Comment by dangtrivan15** [comment]
Is there any update on this issue? I also encountered this on [v0.40.32](https://github.com/airbytehq/airbyte/releases/tag/v0.40.32). I think this should be considered a severe issue as it blocked an entire segment of users (a huge one) from utilizing this amazing platform.

**Comment by sajarin** [comment]
@dangtrivan15 what's your deployment configuration look like and have you tried the latest release (v41.0)?

**Comment by marcosmarxm** [comment]
Closing as outdated version. Please try with latest version of the platform, if the issue persists open a new issue.
