### ISSUE TITLE
Error screen when trying to create a connection from a source or destination page

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#19142]
## Environment
- **Airbyte version**:  v0.40.18

## Current Behavior
![Screen Shot 2022-11-08 at 16 11 07](https://user-images.githubusercontent.com/168664/200676199-8d006b29-206a-4d02-837d-85631686112d.png)

## Expected Behavior
Should be able to setup a connection

## Logs
Error in console when running locally:

```
ConnectionEditService.tsx:73 Uncaught Error: useConnectionEditService must be used within a ConnectionEditServiceProvider
    at useConnectionEditService (ConnectionEditService.tsx:73:1)
    at StreamConnectionHeader (StreamConnectionHeader.tsx:14:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at mountIndeterminateComponent (react-dom.development.js:17811:1)
    at beginWork (react-dom.development.js:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
```

## Steps to Reproduce
1. Go to sources and select a source
2. On the source page, click on "Add a destination", select any destination
3. Wait a few seconds

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by edmundito** [comment]
Update: This bug only applies when the new streams table #18187 is enabled, so this does not impact customers

**Comment by tealjulia** [comment]
This should be fixed by pulling from the `useConnectionForm` rather than `useConnectionEdit` context.  `useConnectionForm` should house all of the data that is shared between the creation and editing workflow.
