### ISSUE TITLE
Lowcode server: generate proper exception types

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#19324]
## Tell us about the problem you're trying to solve
The FastAPI framework typically [handles errors](https://fastapi.tiangolo.com/tutorial/handling-errors/) by expecting the developer to `raise` them as Exceptions sub-classing `HTTPException`. The Framework then transforms it to the correct HTTP response, and returns it to the API consumer. 

In our [OpenAPI spec](https://github.com/airbytehq/airbyte/blob/master/airbyte-connector-builder-server/src/main/openapi/openapi.yaml) we define some error responses e.g: it  defines that when returning 400s, the `KnownException` type should be used. 

But the generated code is just a "plain old object" -- it does not subclass `HTTPException`. This causes a problem: if an endpoint `raise`s a `KnownException` we get the following error: 

```
  File "/Users/lakemossman/code/airbyte/airbyte-connector-builder-server/./connector_builder/impl/default_api.py", line 63, in list_streams
    raise KnownExceptionInfo(message="failure")
TypeError: exceptions must derive from BaseException
```

## Describe the solution you’d like
I would like the autogenerated exception classes to extend the `HTTPException` class defined by FastAPI.

**Comment by sherifnada** [comment]
@juweins I may have been too optimistic in labeling this as a good first issue -- my guess is that it might be involved as it requires an understanding of the OpenAPI generator. You're welcome to give it a shot, but just wanted to flag that it may be more complicated than I initially anticipated. I've assigned to you, let me know if you want me to unassign

**Comment by juweins** [comment]
@sherifnada You can unassign me, my upcoming proposal has already been implemented with the latest pull today....

**Comment by sherifnada** [comment]
@juweins which pull are you referencing?

**Comment by juweins** [comment]
@sherifnada I was pretty confused by the latest merge to that specific class default_api.py. However, I found some time last weekend to get near a possible solution.
Hopefully I am able to propose my solution around 10 AM GMT-8.

**Comment by juweins** [comment]
I struggle testing my implementation with the provided unit-tests. I am not able to run the test script due to unresolved module imports. How may I enable this?

`/usr/bin/python3 /home/wenzork/airbyte-contribution/airbyte-19324/airbyte-
connector-builder-server/connector_builder/impl/default_api.py
Traceback (most recent call last):
  File "/home/wenzork/airbyte-contribution/airbyte-19324/airbyte-connector-builder-server/connector_builder/impl/default_api.py", line 11, in <module>
    from airbyte_cdk.models import AirbyteLogMessage, AirbyteMessage, Type
ModuleNotFoundError: No module named 'airbyte_cdk'
➜  airbyte-19324 git:(master) ✗ `

**Comment by juweins** [comment]
@sherifnada I committed my proposal to my repo. Can you maybe have a look on my implementation & make suggestions?
Am I on the right track to solve this issue? Thanks!

**Comment by sherifnada** [comment]
@juweins the code is on the right track, but the ticket is saying that the OpenAPI generator we use to generate all the code under the `generated/` directory should be the one generating this code, rather than us writing it by hand if that makes sense. 
See [the README](https://github.com/airbytehq/airbyte/tree/master/airbyte-connector-builder-server#openapi-generation)  for a description of how to invoke the code generator. An example of a type defined in OpenAPI which _should_ generate a class which extends `HTTPException` is the [KnownException](https://github.com/airbytehq/airbyte/blob/master/airbyte-connector-builder-server/src/main/openapi/openapi.yaml#L279) class. We want to define this in the OpenAPI spec yaml in such a way that the generated class extends `HTTPException`. 

Does that help?

**Comment by sherifnada** [comment]
Looking at [this issue](https://github.com/OAI/OpenAPI-Specification/issues/398) in the openAPi generator, it's actually not clear to me if openAPI even natively supports it. My guess is that there might be a code generator flag which tells the generator to use a specific super class when generating python code. But short of something like that, I'm not sure the spec itself can support this.

**Comment by dsinghvi** [comment]
@sherifnada Fern supports this! Here's a link to a [generated exception](https://github.com/fern-api/venus/blob/35ae881f0a0a4d275b8112f2fdc21e1cc9434d36/src/venus/generated/server/resources/registry/errors/organization_not_found_error.py#L3-L8) and the [corresponding definition](https://github.com/fern-api/venus/blob/35ae881f0a0a4d275b8112f2fdc21e1cc9434d36/fern/venus-api/definition/registry.yml#L56-L60).
