### ISSUE TITLE
Prefect call to AirByte Health Returns 401 Error

### ISSUE THREAD

**Issue by stevenwilber-deliveroo** [airbytehq/airbyte#19414]
### Prefect
Version:             2.6.7
API version:         0.8.3
Python version:      3.10.7
Git commit:          9074c158
Built:               Thu, Nov 10, 2022 1:07 PM
OS/Arch:             darwin/arm64
Profile:             local
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.37.0

### Airbyte
- Version: 0.40.18
- Deployment: Docker (local)
- Source: Airtable v0.13 (latest)
- Destination: Snowflake v0.1.24

## OS
macOS v12.6.1

## Current Behavior
Prefect starts in ephemeral mode and attempts to check the health of Airbyte using `http://localhost:8000/api/v1/health/`. This returned a 401 error - `httpx.HTTPStatusError: Client error '401 Unauthorized' for url 'http://localhost:8000/api/v1/health/'`.
If I paste that link into my browser, then I need to log in with the default user and password for Airbyte, but then I receive: `{"available":true}`.
The logging in seems to be the issue, but removing authorisation seems an odd step to have to take.

## Expected Behavior
I would have assumed some token based authorisation that is passed in the request and that the health check comes back fine and the sync is triggered.

### Prefect Logs
```
10:20:03.575 | INFO    | prefect.engine - Created flow run 'amorphous-silkworm' 
for flow 'main-flow'
10:20:03.698 | INFO    | Flow run 'amorphous-silkworm' - Created subflow run 
'fierce-jaybird' for flow 'sync-airtable'
10:20:03.731 | INFO    | Flow run 'fierce-jaybird' - Created task run 
'trigger_sync-6dd98a16-0' for task 'trigger_sync'
10:20:03.732 | INFO    | Flow run 'fierce-jaybird' - Executing 
'trigger_sync-6dd98a16-0' immediately...
10:20:03.752 | INFO    | prefect - Getting Airbyte Connection 
945cfb79-64d5-44a1-b82b-8c05894de860, poll interval 5 seconds, airbyte_base_url 
http://127.0.0.1:8001/api/v1
10:20:03.782 | ERROR   | Task run 'trigger_sync-6dd98a16-0' - Encountered 
exception during execution:
10:20:03.796 | ERROR   | Task run 'trigger_sync-6dd98a16-0' - Finished in state 
Failed('Task run encountered an exception: Traceback (most recent call last):\n 
File 
"/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/
prefect_airbyte/client.py", line 61, in check_health_status\n    
response.raise_for_status()\n  File 
"/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/
httpx/_models.py", line 736, in raise_for_status\n    raise 
HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError:
Client error \'401 Unauthorized\' for url 
\'http://127.0.0.1:8001/api/v1/health/\'\nFor more information check: 
https://httpstatuses.com/401\n\nThe above exception was the direct cause of the 
following 
exception:\n\nprefect_airbyte.exceptions.AirbyteServerNotHealthyException\n')
10:20:03.797 | ERROR   | Flow run 'fierce-jaybird' - Encountered exception 
during execution:
10:20:03.818 | ERROR   | Flow run 'fierce-jaybird' - Finished in state 
Failed('Flow run encountered an exception. Traceback (most recent call last):\n 
File 
"/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/
prefect_airbyte/client.py", line 61, in check_health_status\n    
response.raise_for_status()\n  File 
"/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/
httpx/_models.py", line 736, in raise_for_status\n    raise 
HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError:
Client error \'401 Unauthorized\' for url 
\'http://127.0.0.1:8001/api/v1/health/\'\nFor more information check: 
https://httpstatuses.com/401\n\nThe above exception was the direct cause of the 
following 
exception:\n\nprefect_airbyte.exceptions.AirbyteServerNotHealthyException\n')
10:20:03.818 | ERROR   | Flow run 'amorphous-silkworm' - Encountered exception 
during execution:
10:20:03.831 | ERROR   | Flow run 'amorphous-silkworm' - Finished in state 
Failed('Flow run encountered an exception. Traceback (most recent call last):\n 
File 
"/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/
prefect_airbyte/client.py", line 61, in check_health_status\n    
response.raise_for_status()\n  File 
"/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/
httpx/_models.py", line 736, in raise_for_status\n    raise 
HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError:
Client error \'401 Unauthorized\' for url 
\'http://127.0.0.1:8001/api/v1/health/\'\nFor more information check: 
https://httpstatuses.com/401\n\nThe above exception was the direct cause of the 
following 
exception:\n\nprefect_airbyte.exceptions.AirbyteServerNotHealthyException\n')
Traceback (most recent call last):
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/prefect_airbyte/client.py", line 61, in check_health_status
    response.raise_for_status()
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/httpx/_models.py", line 736, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '401 Unauthorized' for url 'http://127.0.0.1:8001/api/v1/health/'
For more information check: https://httpstatuses.com/401

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/stevenwilber/Documents/edgewing/projects/git/airtable-airbyte-dbt-prefect/prefect/first.py", line 29, in <module>
    print(main_flow())
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/prefect/flows.py", line 442, in __call__
    return enter_flow_run_engine_from_flow_call(
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/prefect/engine.py", line 157, in enter_flow_run_engine_from_flow_call
    return anyio.run(begin_run)
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/Users/stevenwilber/.pyenv/versions/3.10.7/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/stevenwilber/.pyenv/versions/3.10.7/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/prefect/client/utilities.py", line 47, in with_injected_client
    return await fn(*args, **kwargs)
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/prefect/engine.py", line 237, in create_then_begin_flow_run
    return await state.result(fetch=True)
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/prefect/states.py", line 74, in _get_state_result
    raise await get_state_exception(state)
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/prefect/engine.py", line 610, in orchestrate_flow_run
    result = await run_sync(flow_call)
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 68, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/stevenwilber/Documents/edgewing/projects/git/airtable-airbyte-dbt-prefect/prefect/first.py", line 27, in main_flow
    sync_airtable()
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/prefect/flows.py", line 442, in __call__
    return enter_flow_run_engine_from_flow_call(
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/prefect/engine.py", line 161, in enter_flow_run_engine_from_flow_call
    return run_async_from_worker_thread(begin_run)
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 148, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/anyio/from_thread.py", line 49, in run
    return asynclib.run_async_from_thread(func, *args)
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "/Users/stevenwilber/.pyenv/versions/3.10.7/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/Users/stevenwilber/.pyenv/versions/3.10.7/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/prefect/client/utilities.py", line 47, in with_injected_client
    return await fn(*args, **kwargs)
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/prefect/engine.py", line 520, in create_and_begin_subflow_run
    return await terminal_state.result(fetch=True)
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/prefect/states.py", line 74, in _get_state_result
    raise await get_state_exception(state)
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/prefect/engine.py", line 610, in orchestrate_flow_run
    result = await run_sync(flow_call)
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 68, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/stevenwilber/Documents/edgewing/projects/git/airtable-airbyte-dbt-prefect/prefect/first.py", line 11, in sync_airtable
    trigger_sync(
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/prefect/tasks.py", line 360, in __call__
    return enter_task_run_engine(
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/prefect/engine.py", line 733, in enter_task_run_engine
    return run_async_from_worker_thread(begin_run)
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 148, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/anyio/from_thread.py", line 49, in run
    return asynclib.run_async_from_thread(func, *args)
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "/Users/stevenwilber/.pyenv/versions/3.10.7/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/Users/stevenwilber/.pyenv/versions/3.10.7/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/prefect/engine.py", line 874, in get_task_call_return_value
    return await future._result()
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/prefect/futures.py", line 237, in _result
    return await final_state.result(raise_on_failure=raise_on_failure, fetch=True)
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/prefect/states.py", line 74, in _get_state_result
    raise await get_state_exception(state)
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/prefect/engine.py", line 1232, in orchestrate_task_run
    result = await task.fn(*args, **kwargs)
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/prefect_airbyte/connections.py", line 116, in trigger_sync
    connection_status = await airbyte.get_connection_status(connection_id)
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/prefect_airbyte/client.py", line 118, in get_connection_status
    client = await self.create_client()
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/prefect_airbyte/client.py", line 81, in create_client
    client = await self._establish_session()
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/prefect_airbyte/client.py", line 45, in _establish_session
    await self.check_health_status(client)
  File "/Users/stevenwilber/.pyenv/versions/prefect_env_1/lib/python3.10/site-packages/prefect_airbyte/client.py", line 72, in check_health_status
    raise err.AirbyteServerNotHealthyException() from e
prefect_airbyte.exceptions.AirbyteServerNotHealthyException
```

**Comment by stevenwilber-deliveroo** [comment]
Looks like this will be fixed with: https://pypi.org/project/prefect-airbyte/0.1.3/
