### ISSUE TITLE
Pulsar destination connector to support StreamNative Cloud or authenticated Pulsar broker

### ISSUE THREAD

**Issue by jovezhong** [airbytehq/airbyte#19527]
## Tell us about the problem you're trying to solve
I tried the pulsar destination connector. There is no way to set OAuth or Token. Only 'None' authentication is supported.
Be more specific, I have a few topics on StreamNative cloud but cannot use AirByte to send data to it.

## Error message

[2022-11-17T01:36:50.513Z] Destination: java.lang.ClassNotFoundException: org.conscrypt.OpenSSLProvider
[2022-11-17T01:36:50.513Z] Destination: 	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
[2022-11-17T01:36:50.513Z] Destination: 	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
[2022-11-17T01:36:50.513Z] Destination: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
[2022-11-17T01:36:50.513Z] Destination: 	at java.lang.Class.forName0(Native Method) ~[?:?]
[2022-11-17T01:36:50.513Z] Destination: 	at java.lang.Class.forName(Class.java:375) ~[?:?]
[2022-11-17T01:36:50.513Z] Destination: 	at org.apache.pulsar.common.util.SecurityUtility.loadConscryptProvider(SecurityUtility.java:121) ~[pulsar-client-2.8.1.jar:2.8.1]
[2022-11-17T01:36:50.513Z] Destination: 	at org.apache.pulsar.common.util.SecurityUtility.<clinit>(SecurityUtility.java:79) ~[pulsar-client-2.8.1.jar:2.8.1]
[2022-11-17T01:36:50.513Z] Destination: 	at org.apache.pulsar.client.impl.PulsarChannelInitializer.lambda$new$0(PulsarChannelInitializer.java:95) ~[pulsar-client-2.8.1.jar:2.8.1]
[2022-11-17T01:36:50.513Z] Destination: 	at org.apache.pulsar.client.util.ObjectCache.get(ObjectCache.java:48) ~[pulsar-client-2.8.1.jar:2.8.1]
[2022-11-17T01:36:50.513Z] Destination: 	at org.apache.pulsar.client.impl.PulsarChannelInitializer.lambda$initTls$1(PulsarChannelInitializer.java:140) ~[pulsar-client-2.8.1.jar:2.8.1]
[2022-11-17T01:36:50.513Z] Destination: 	at org.apache.pulsar.shade.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [pulsar-client-2.8.1.jar:2.8.1]
[2022-11-17T01:36:50.513Z] Destination: 	at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [pulsar-client-2.8.1.jar:2.8.1]
[2022-11-17T01:36:50.513Z] Destination: 	at org.apache.pulsar.shade.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) [pulsar-client-2.8.1.jar:2.8.1]
[2022-11-17T01:36:50.513Z] Destination: 	at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [pulsar-client-2.8.1.jar:2.8.1]
[2022-11-17T01:36:50.513Z] Destination: 	at org.apache.pulsar.shade.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [pulsar-client-2.8.1.jar:2.8.1]
[2022-11-17T01:36:50.514Z] Destination: 	at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [pulsar-client-2.8.1.jar:2.8.1]

## Describe the solution you’d like
Support more auth method

Take an example of [Timeplus Cloud](https://timeplus.com)
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/5076438/202333677-ffb48d1e-60dc-4392-9d39-b4a25dddc60e.png">
<img width="815" alt="image" src="https://user-images.githubusercontent.com/5076438/202333743-5c1ef20b-e64b-4fde-89a1-36ab43f6a97d.png">
<img width="808" alt="image" src="https://user-images.githubusercontent.com/5076438/202333777-4813ccd1-cb86-4b57-9146-3470dc818f55.png">

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?
No. Maybe invite Pulsar community or StreamNative team to do so

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 365 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.
