### ISSUE TITLE
Pipedrive source is broken

### ISSUE THREAD

**Issue by bmikaili** [airbytehq/airbyte#19584]
Using official docker-compose on M1 Pro Macbook Pro. Get the following error in raw transformation.

```
    latest_benchmark = latest_record[self.cursor_field]
KeyError: 'update_time'
,retryable=<null>,timestamp=1668769647025], io.airbyte.config.FailureReason@1d5c49a5[failureOrigin=source,failureType=<null>,internalMessage=io.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source cannot be stopped!,externalMessage=Something went wrong within the source connector,metadata=io.airbyte.config.Metadata@2f7ff3c1[additionalProperties={attemptNumber=1, jobId=102, connector_command=read}],stacktrace=java.util.concurrent.CompletionException: io.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source cannot be stopped!
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: io.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source cannot be stopped!
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$getReplicationRunnable$6(DefaultReplicationWorker.java:390)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	... 3 more
Caused by: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
	at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:144)
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$getReplicationRunnable$6(DefaultReplicationWorker.java:388)
	... 4 more
,retryable=<null>,timestamp=1668769647275]]]
```

**Comment by natalyjazzviolin** [comment]
Hey @bmikaili , please use our standard issue report template (repasted it for you below), as currently this issue does not have enough information to debug further. I am closing this issue until additional details are provided.

 

## Environment
- **Airbyte version**:  example is 0.22.0-alpha
- **OS Version / Instance**: example macOS, Windows 7/10, Ubuntu 18.04, GCP n2. , AWS EC2
- **Deployment**: example are Docker or Kubernetes deploy env
- **Source Connector and version**: (if applicable example Salesforce 0.2.3) 
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
*Tell us what happens.*

## Expected Behavior
*Tell us what should happen.*

## Logs


## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.
