### ISSUE TITLE
Helm Chart - TEMPORAL_HOST not passed to Cron deployment

### ISSUE THREAD

**Issue by nicoodle** [airbytehq/airbyte#19705]
## Environment
- **Airbyte version**: 0.40.22
- **OS Version / Instance**: AWS EC2/EKS
- **Deployment**: Kubernetes
- **Source Connector and version**: N/A
- **Destination Connector and version**: N/A
- **Step where error happened**: Deploy Airbyte using Helm Chart

## Current Behavior
Deployment of Airbyte using the Helm Chart results in a crashing Cron container. The reason is due to the Cron deployment not using the TEMPORAL_HOST defined within the Airbyte config map and instead trying the default. With named Helm deployments this env var needs to be passed down the chain. 

## Expected Behavior
TEMPORAL_HOST env var is populated within the Cron deployment via the Airbyte config map allowing cron to connect to the correct Kubernetes service. 

## Logs
```
Nov 22, 2022 10:52:06 AM io.grpc.internal.ManagedChannelImpl$NameResolverListener handleErrorInSyncContext
84
WARNING: [Channel<101>: (airbyte-temporal:7233)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Unable to resolve host airbyte-temporal, cause=java.lang.RuntimeException: java.net.UnknownHostException: airbyte-temporal
83
	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223)
82
	at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)
81
	at io.grpc.grpclb.GrpclbNameResolver.doResolve(GrpclbNameResolver.java:63)
80
	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)
79
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
78
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
77
	at java.base/java.lang.Thread.run(Thread.java:1589)
76
Caused by: java.net.UnknownHostException: airbyte-temporal
75
	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:952)
74
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1658)
73
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1524)
72
	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:631)
71
	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
70
	... 6 more
69
}
```

## Steps to Reproduce
1. Deploy Airbyte using Helm
2. Cron is borked

## Are you willing to submit a PR? 
Yes

**Comment by thodquach** [comment]
Hello, I wonder do we have a workaround solution for this problem for now?
I met this problem too.

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.
