### ISSUE TITLE
🐛 Destination BigQuery 1.2.7 with GCS Staging Fails to Reset Data 

### ISSUE THREAD

**Issue by andresbravog** [airbytehq/airbyte#19823]
## Environment
- **Airbyte version**:  example is 0.40.22
- **OS Version / Instance**: GCP n2.
- **Deployment**: Docker
- **Source Connector and version**:  NA
- **Destination Connector and version**: 1.2.7
- **Step where error happened**: Reset job - Setup new connection

## Current Behavior

When setting up a new connector with BigQuery destination using GCS staging, when trying to create the GCS folders uses S3 library for some reason making the process fail:

```log
2022-11-28 12:10:06 destination > Creating staging path for stream brands (dataset my_dataset): level_test/google_external/staging_validation/my_dataset_my_stream/2022/11/28/12/a9d79913-0f2f-4273-86aa-5806e1384893/
2022-11-28 12:10:06 destination > Exception while starting consumer
Stack Trace: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: null; S3 Extended Request ID: null; Proxy: null), S3 Extended Request ID: null
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1819)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1403)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1372)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
```

## Expected Behavior

It should use the GCS lib instead and complete the folder structure creation.

## Logs

[fd23b3e1_0c1a_45f1_8c8b_afbd21da3515_logs_842_txt.txt](https://github.com/airbytehq/airbyte/files/10103627/fd23b3e1_0c1a_45f1_8c8b_afbd21da3515_logs_842_txt.txt)

## Steps to Reproduce

1. Create a Connection with BigQuery `1.2.7` destination and GCS staging load
2. Run a first reset
3. See the failure

## Are you willing to submit a PR?

Yes

**Comment by andresbravog** [comment]
Tested on previous BigQuery Destination versions `1.1.0` and `0.6.1` and keeps failing, it doesn't seem to be related to the destination version.

**Comment by andresbravog** [comment]
OK somehow seems to be related to my credentials being somehow an old HMAC key, closing this ticket but the message is still misleading that refers to S3
