### ISSUE TITLE
MySQL Source fails to take initial snapshot of a large table (15GB+)

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#19833]
Debezium is running into the following error while taking a snapshot of a large table after almost 2 hours of reading records:
```
Finished exporting 54085424 records for table 'customer_table_name_reducted'; total duration '01:47:09.207
2022-11-26 03:33:49 source > Producer failure
Stack Trace: io.debezium.DebeziumException: java.lang.RuntimeException: java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown.
	at io.debezium.pipeline.source.AbstractSnapshotChangeEventSource.execute(AbstractSnapshotChangeEventSource.java:85)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.doSnapshot(ChangeEventSourceCoordinator.java:155)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.executeChangeEventSources(ChangeEventSourceCoordinator.java:137)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:109)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

this could be happening due to a combination of configs on the source database server and Debezium connector settings.

**Comment by rodireich** [comment]
This can be resolved with new PK based snapshot
