### ISSUE TITLE
destination-s3-glue: Error when finalizing empty source tables synced to destination

### ISSUE THREAD

**Issue by blarghmatey** [airbytehq/airbyte#19902]
## Environment
- **Airbyte version**:  example is 0.40.22
- **OS Version / Instance**: AWS EC2 running Debian 11
- **Deployment**: Docker-compose
- **Source Connector and version**: BigQuery 0.2.3
- **Destination Connector and version**: S3-Glue 0.1.0
- **Step where error happened**: Sync job

## Current Behavior
The sync errors when closing some of the streams. It appears to be related to trying to create the table definition in Glue for empty source tables because there is no schema for it to intuit from the data in the stream.

## Expected Behavior
The destination table schema should either be created with the schema identified in the source, or skipped entirely.

## Logs
Relevant snippet of the log (the full file is over 20,000 lines)
```
{"type":"number","airbyte_type":"integer"}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[],namespace=irx/edxorg/bigquery/aggregate_data,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=overwrite,primaryKey=[],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@44ef5a2a[stream=io.airbyte.protocol.models.AirbyteStream@cdebb00[name=raw__irx__edxorg__bigquery__person_course_day,jsonSchema={"type":"object","properties":{"date":{"type":"string"},"username":{"type":"string"},"course_id":{"type":"string"}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[],namespace=irx/edxorg/bigquery/aggregate_data,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=overwrite,primaryKey=[],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@713ac576[stream=io.airbyte.protocol.models.AirbyteStream@4baf567d[name=raw__irx__edxorg__bigquery__user_info_combo,jsonSchema={"type":"object","properties":{"email":{"type":"string"},"user_id":{"type":"number","airbyte_type":"integer"},"username":{"type":"string"},"id_map_hash_id":{"type":"string"}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[],namespace=irx/edxorg/bigquery/aggregate_data,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=overwrite,primaryKey=[],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@752f7b28[stream=io.airbyte.protocol.models.AirbyteStream@cd0c836[name=raw__irx__edxorg__bigquery__user_info_name_country,jsonSchema={"type":"object","properties":{"user_id":{"type":"number","airbyte_type":"integer"},"profile_name":{"type":"string"},"id_map_hash_id":{"type":"string"},"profile_country":{"type":"string"},"profile_mailing_address":{"type":"string"}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[],namespace=irx/edxorg/bigquery/aggregate_data,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=overwrite,primaryKey=[],additionalProperties={}]],additionalProperties={}],failures=[io.airbyte.config.FailureReason@2b66bdaf[failureOrigin=destination,failureType=system_error,internalMessage=java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because "properties" is null,externalMessage=Something went wrong in the connector. See the logs for more details.,metadata=io.airbyte.config.Metadata@1acb1a00[additionalProperties={attemptNumber=0, jobId=807, from_trace_message=true, connector_command=write}],stacktrace=java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because "properties" is null
	at io.airbyte.integrations.destination.s3_glue.GlueOperations.transformSchemaRecursive(GlueOperations.java:151)
	at io.airbyte.integrations.destination.s3_glue.GlueOperations.lambda$transformSchema$0(GlueOperations.java:116)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.airbyte.integrations.destination.s3_glue.GlueOperations.transformSchema(GlueOperations.java:117)
	at io.airbyte.integrations.destination.s3_glue.GlueOperations.upsertTable(GlueOperations.java:64)
	at io.airbyte.integrations.destination.s3_glue.S3GlueConsumerFactory.lambda$onCloseFunction$3(S3GlueConsumerFactory.java:166)
	at io.airbyte.integrations.destination.buffered_stream_consumer.OnCloseFunction.accept(OnCloseFunction.java:9)
	at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.close(BufferedStreamConsumer.java:184)
	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.close(FailureTrackingAirbyteMessageConsumer.java:64)
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:151)
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:100)
	at io.airbyte.integrations.destination.s3_glue.S3GlueDestination.main(S3GlueDestination.java:35)
,retryable=<null>,timestamp=1669758494171],
```

## Steps to Reproduce
1. Sync a source table that is empty

## Are you willing to submit a PR?
Yes

**Comment by blarghmatey** [comment]
@itaseskii I think this is due to trying to create the Glue table when there are no records/schema from the source stream to use for generating the table definition. I can take a look in the morning if you don't get to it first.

**Comment by itaseskii** [comment]
Hey @blarghmatey thanks for the heads up. I'm going through the code and most likely this was caused by an inner object in the schema which has no properties with it https://github.com/airbytehq/airbyte/blob/2c5dabc64a6b3fc3ad6be55becdaa4dfc2a326e1/airbyte-integrations/connectors/destination-s3-glue/src/main/java/io/airbyte/integrations/destination/s3_glue/GlueOperations.java#L150. We already check if the schema has properties at the top level https://github.com/airbytehq/airbyte/blob/2c5dabc64a6b3fc3ad6be55becdaa4dfc2a326e1/airbyte-integrations/connectors/destination-s3-glue/src/main/java/io/airbyte/integrations/destination/s3_glue/GlueOperations.java#L113 which should handle empty schemas. 

Can you please provide me with the schema of the source just to be certain?

I'll fix this first thing in the morning.

**Comment by itaseskii** [comment]
I have linked a PR that should fix this issue. hopefully it is fine to provide a **_struct<>_** glue type with empty parameters when we have blank objects in the schema. Please try it out when you can and tell me how it goes.

**Comment by blarghmatey** [comment]
Thanks for the quick work! I'm doing some digging to see if that is a valid signature as well as investigating what the data actually looks like.

**Comment by blarghmatey** [comment]
So I found a specific table that is causing the errors. A representative entry pulled from the data loaded to S3 is:

**Comment by blarghmatey** [comment]
Here's the sync summary for the failed table creation:
```
2022-11-30 19:06:52 [32mINFO[m i.a.w.t.s.ReplicationActivityImpl(lambda$replicate$3):198 - sync summary: io.airbyte.config.StandardSyncOutput@76fa7520[standardSyncSummary=io.airbyte.config.StandardSyncSummary@27caac1e[status=failed,recordsSynced=1342850,bytesSynced=1039342058,startTime=1669834640161,endTime=1669835212046,totalStats=io.airbyte.config.SyncStats@7e4a1036[recordsEmitted=1342850,bytesEmitted=1039342058,sourceStateMessagesEmitted=0,destinationStateMessagesEmitted=0,recordsCommitted=0,meanSecondsBeforeSourceStateMessageEmitted=0,maxSecondsBeforeSourceStateMessageEmitted=0,maxSecondsBetweenStateMessageEmittedandCommitted=0,meanSecondsBetweenStateMessageEmittedandCommitted=0,replicationStartTime=1669834640161,replicationEndTime=1669835212046,sourceReadStartTime=1669834640206,sourceReadEndTime=1669835207706,destinationWriteStartTime=1669834640280,destinationWriteEndTime=1669835212045,additionalProperties={}],streamStats=[io.airbyte.config.StreamSyncStats@e4fc019[streamName=raw__irx__edxorg__bigquery__mitx_course_axis,streamNamespace=irx/edxorg/bigquery/aggregate_data,stats=io.airbyte.config.SyncStats@2b39f785[recordsEmitted=1342850,bytesEmitted=1039342058,sourceStateMessagesEmitted=<null>,destinationStateMessagesEmitted=<null>,recordsCommitted=<null>,meanSecondsBeforeSourceStateMessageEmitted=<null>,maxSecondsBeforeSourceStateMessageEmitted=<null>,maxSecondsBetweenStateMessageEmittedandCommitted=<null>,meanSecondsBetweenStateMessageEmittedandCommitted=<null>,replicationStartTime=<null>,replicationEndTime=<null>,sourceReadStartTime=<null>,sourceReadEndTime=<null>,destinationWriteStartTime=<null>,destinationWriteEndTime=<null>,additionalProperties={}]]]],normalizationSummary=<null>,webhookOperationSummary=<null>,state=<null>,outputCatalog=io.airbyte.protocol.models.ConfiguredAirbyteCatalog@596114a0[streams=[io.airbyte.protocol.models.ConfiguredAirbyteStream@7704741a[stream=io.airbyte.protocol.models.AirbyteStream@7bb2deb[name=raw__irx__edxorg__bigquery__mitx_course_axis,jsonSchema={"type":"object","properties":{"due":{"type":"string"},"data":{"type":"object"},"name":{"type":"string"},"path":{"type":"string"},"index":{"type":"number","airbyte_type":"integer"},"start":{"type":"string"},"graded":{"type":"boolean"},"parent":{"type":"string"},"gformat":{"type":"string"},"category":{"type":"string"},"is_split":{"type":"boolean"},"url_name":{"type":"string"},"course_id":{"type":"string"},"module_id":{"type":"string"},"chapter_mid":{"type":"string"},"split_url_name":{"type":"string"},"visible_to_staff_only":{"type":"boolean"}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[],namespace=irx/edxorg/bigquery/aggregate_data,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=append,primaryKey=[],additionalProperties={}]],additionalProperties={}],failures=[io.airbyte.config.FailureReason@635a7746[failureOrigin=destination,failureType=system_error,internalMessage=java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because "properties" is null,externalMessage=Something went wrong in the connector. See the logs for more details.,metadata=io.airbyte.config.Metadata@32cfab99[additionalProperties={attemptNumber=1, jobId=822, from_trace_message=true, connector_command=write}],stacktrace=java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because "properties" is null
	at io.airbyte.integrations.destination.s3_glue.GlueOperations.transformSchemaRecursive(GlueOperations.java:151)
	at io.airbyte.integrations.destination.s3_glue.GlueOperations.lambda$transformSchema$0(GlueOperations.java:116)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.airbyte.integrations.destination.s3_glue.GlueOperations.transformSchema(GlueOperations.java:117)
	at io.airbyte.integrations.destination.s3_glue.GlueOperations.upsertTable(GlueOperations.java:64)
	at io.airbyte.integrations.destination.s3_glue.S3GlueConsumerFactory.lambda$onCloseFunction$3(S3GlueConsumerFactory.java:166)
	at io.airbyte.integrations.destination.buffered_stream_consumer.OnCloseFunction.accept(OnCloseFunction.java:9)
	at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.close(BufferedStreamConsumer.java:184)
	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.close(FailureTrackingAirbyteMessageConsumer.java:64)
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:151)
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:100)
	at io.airbyte.integrations.destination.s3_glue.S3GlueDestination.main(S3GlueDestination.java:35)
,retryable=<null>,timestamp=1669835211904], io.airbyte.config.FailureReason@66bfad7e[failureOrigin=destination,failureType=<null>,internalMessage=io.airbyte.workers.general.DefaultReplicationWorker$DestinationException: Destination process exited with non-zero exit code 1,externalMessage=Something went wrong within the destination connector,metadata=io.airbyte.config.Metadata@38b51037[additionalProperties={attemptNumber=1, jobId=822, connector_command=write}],stacktrace=java.util.concurrent.CompletionException: io.airbyte.workers.general.DefaultReplicationWorker$DestinationException: Destination process exited with non-zero exit code 1
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: io.airbyte.workers.general.DefaultReplicationWorker$DestinationException: Destination process exited with non-zero exit code 1
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromDstRunnable$4(DefaultReplicationWorker.java:259)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	... 3 more
,retryable=<null>,timestamp=1669835212045]]]
```

**Comment by blarghmatey** [comment]
In the UI Airbyte shows the source schema having a type of `Object` for the nested field in the BigQuery source.
