### ISSUE TITLE
Job proceeds after failing destination CHECK - connector not signaling failure to the platform 

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#19996]
Looking at this [connection](https://cloud.airbyte.io/workspaces/cd88cbb4-36c8-4738-9138-f1a26d3bee72/connections/c9a7448f-7d2e-4660-a32f-02684cdada6a/status#902405::2) I am seeing the following behavior:

- `CHECK` throws an exception, logs the stack trace, and emits config error
- Job proceeds and fails

```
2022-12-01 03:15:15 [32mINFO[m i.a.c.i.LineGobbler(voidCall):114 - ----- START CHECK -----
2022-12-01 03:15:15 [32mINFO[m i.a.w.p.KubeProcessFactory(create):100 - Attempting to start pod 

...

2022-12-01 03:15:15 [32mINFO[m i.a.w.p.KubePodProcess(waitForInitPodToRun):309 - Waiting for init container to be ready before copying files...
2022-12-01 03:15:15 [32mINFO[m i.a.w.p.KubePodProcess(waitForInitPodToRun):313 - Init container present..
2022-12-01 03:15:17 [32mINFO[m i.a.w.p.KubePodProcess(waitForInitPodToRun):316 - Init container ready..

...

2022-12-01 03:15:19 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(create):97 - Reading messages from protocol version 0.2.0
2022-12-01 03:15:20 [32mINFO[m i.a.w.i.DefaultAirbyteStreamFactory(internalLog):120 - integration args: {check=null, config=source_config.json}
2022-12-01 03:15:20 [32mINFO[m i.a.w.i.DefaultAirbyteStreamFactory(internalLog):120 - Running integration: io.airbyte.integrations.destination.bigquery.BigQueryDestination
2022-12-01 03:15:20 [32mINFO[m i.a.w.i.DefaultAirbyteStreamFactory(internalLog):120 - Command: CHECK

...

2022-12-01 03:15:23 [32mINFO[m i.a.w.i.DefaultAirbyteStreamFactory(internalLog):120 - Started testing if all required credentials assigned to user for single file uploading
2022-12-01 03:15:24 [1;31mERROR[m i.a.w.i.DefaultAirbyteStreamFactory(internalLog):116 - Exception attempting to access the Gcs bucket
Stack Trace: com.amazonaws.services.s3.model.AmazonS3Exception: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: null; S3 Extended Request ID: null; Proxy: null), S3 Extended Request ID: null
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1819)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1403)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1372)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5437)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5384)
	at com.amazonaws.services.s3.AmazonS3Client.deleteObject(AmazonS3Client.java:2294)
	at com.amazonaws.services.s3.AmazonS3Client.deleteObject(AmazonS3Client.java:2278)
	at io.airbyte.integrations.destination.s3.S3BaseChecks.testSingleUpload(S3BaseChecks.java:46)
	at io.airbyte.integrations.destination.gcs.GcsDestination.check(GcsDestination.java:53)
	at io.airbyte.integrations.destination.bigquery.BigQueryDestination.checkGcsPermission(BigQueryDestination.java:145)
	at io.airbyte.integrations.destination.bigquery.BigQueryDestination.check(BigQueryDestination.java:103)
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:125)
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:100)
	at io.airbyte.integrations.destination.bigquery.BigQueryDestination.main(BigQueryDestination.java:327)

2022-12-01 03:15:25 [32mINFO[m i.a.w.i.DefaultAirbyteStreamFactory(internalLog):120 - Completed integration: io.airbyte.integrations.destination.bigquery.BigQueryDestination
2022-12-01 03:15:25 [32mINFO[m i.a.w.p.KubePodProcess(close):737 - (pod: jobs / destination-bigquery-check-902405-1-zxddo) - Closed all resources for pod
2022-12-01 03:15:25 [32mINFO[m i.a.c.i.LineGobbler(voidCall):114 - 
2022-12-01 03:15:25 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):163 - Stopping cancellation check scheduling...
2022-12-01 03:15:25 [32mINFO[m i.a.c.i.LineGobbler(voidCall):114 - ----- END CHECK -----
2022-12-01 03:15:25 [32mINFO[m i.a.c.i.LineGobbler(voidCall):114 - 
2022-12-01 03:16:00 [32mINFO[m i.a.m.l.DogStatsDMetricClient(count):85 - publishing count, name: ATTEMPT_SUCCEEDED_BY_RELEASE_STAGE, value: 1, attributes: [MetricAttribute[key=release_stage, value=generally_available]]
2022-12-01 03:16:00 [32mINFO[m i.a.m.l.DogStatsDMetricClient(count):85 - publishing count, name: ATTEMPT_SUCCEEDED_BY_RELEASE_STAGE, value: 1, attributes: [MetricAttribute[key=release_stage, value=generally_available]]
2022-12-01 03:16:00 [33mWARN[m i.a.p.j.JobNotifier(notifyJob):113 - Failed to successfully notify success: 

...

2022-12-01 03:18:40 replication-orchestrator > start sync worker. job id: 902405 attempt id: 2
2022-12-01 03:18:40 replication-orchestrator > 
2022-12-01 03:18:40 replication-orchestrator > ----- START REPLICATION -----
2022-12-01 03:18:40 replication-orchestrator > 
2022-12-01 03:18:40 replication-orchestrator > configured sync modes: {public.activities=full_refresh - overwrite}
2022-12-01 03:18:40 replication-orchestrator > Running destination...

...

2022-12-01 03:18:54 destination > Exception while starting consumer
Stack Trace: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: null; S3 Extended Request ID: null; Proxy: null), S3 Extended Request ID: null
```

after `CHECK` fails, the job proceeds, attempts to write to destination and predictably fails with the same error. As far as I can see, the destination emits a config error when it runs into this exception ([GcsDestination.java ](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-gcs/src/main/java/io/airbyte/integrations/destination/gcs/GcsDestination.java)):
```
 } catch (final AmazonS3Exception e) {
      LOGGER.error("Exception attempting to access the Gcs bucket", e);
      final String message = getErrorMessage(e.getErrorCode(), 0, e.getMessage(), e);
      AirbyteTraceMessageUtility.emitConfigErrorTrace(e, message);
      return new AirbyteConnectionStatus()
          .withStatus(Status.FAILED)
          .withMessage(message);
    } catch (final Exception e) {
      LOGGER.error("Exception attempting to access the Gcs bucket: {}. Please make sure you account has all of these roles: " + EXPECTED_ROLES, e);
      AirbyteTraceMessageUtility.emitConfigErrorTrace(e, e.getMessage());
      return new AirbyteConnectionStatus()
          .withStatus(AirbyteConnectionStatus.Status.FAILED)
          .withMessage("Could not connect to the Gcs bucket with the provided configuration. \n" + e
              .getMessage());
    }
```

**Comment by evantahler** [comment]
This /might/ be a bug with the check - the source catches and logs the exception (and sends a trace message), but does it `exit(1)`?

**Comment by grishick** [comment]
Is the connector supposed to `exit(1)` from `check` if it catches an exception? cc @benmoriceau

**Comment by grishick** [comment]
> This /might/ be a bug with the check - the connector catches and logs the exception (and sends a trace message), but does it `exit(1)`?
> 
> I think this like tells me the platform things the check was a success:
> 
> ```
> 2022-12-01 03:16:00 �[32mINFO�[m i.a.m.l.DogStatsDMetricClient(count):85 - publishing count, name: ATTEMPT_SUCCEEDED_BY_RELEASE_STAGE, value: 1, attributes: [MetricAttribute[key=release_stage, value=generally_available]]
> ```

I don't think our protocol assumes that the destination::check has to crash and exit(1). It returns a failure message like so:
```
return new AirbyteConnectionStatus()
          .withStatus(Status.FAILED)
          .withMessage(message);
```

which is consumed by the `IntegrationRunner` :
```
outputRecordCollector.accept(new AirbyteMessage().withType(Type.CONNECTION_STATUS).withConnectionStatus(integration.check(config)));
```

but then it seems that the `IntegrationRunner` only handles errors when the connector throws an exception

**Comment by benmoriceau** [comment]
I don't know about the exit code of the connector. I think that the status should be transfer through messages. Looking at the logs of a fail conection, it seems that it is doing that: https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22prod-ab-cloud-proj%22%0Aresource.labels.location%3D%22us-west3%22%0Aresource.labels.cluster_name%3D%22prod-gke-cluster%22%0Aresource.labels.pod_name%3D%22destination-bigquery-check-902886-2-tsfqs%22;timeRange=P30D;cursorTimestamp=2022-12-01T06:18:34.017394081Z?authuser=1&project=prod-ab-cloud-proj

**Comment by evantahler** [comment]
Confirmed with @sherifnada and @cgardens:
* A non-0 exit code means there was an un-caught exception, signalling the check has failed
* If there is caught exception, and a reasonable failure response can be emitted (either with or without an prior TraceErrorMessage), that also signals that the check has failed.

So, since both of the code paths @grishick called out above will `return new AirbyteConnectionStatus().withStatus(Status.FAILED)`, this should be a failing check and the replication should not have started.  I think this might be a logical bug in the worker somewhere.

**Comment by grishick** [comment]
I ran into another strange behavior while trying to reproduce this problem. The bahavior is that `CHECK` is not triggered at all during a reset, even if the previous reset has failed.

**Comment by grishick** [comment]
Another side effect of this problem is that it allows user to set up a Destination that does not work. Checking settings with "Save changes and test" button reports that everything is OK while the staging bucket is not writable by the service account. See this [connection](https://cloud.airbyte.io/workspaces/2cd160a0-0dda-458a-9ecc-b88e0e422416/connections/03675adf-4ad7-45d5-9bf1-a87dc5eb2c6b/status)

**Comment by grishick** [comment]
I confirmed this behavior in this [connection](https://cloud.airbyte.io/workspaces/2cd160a0-0dda-458a-9ecc-b88e0e422416/connections/03675adf-4ad7-45d5-9bf1-a87dc5eb2c6b/status). Full log is attached.
[greg_default_logs_958649_txt (1).txt](https://github.com/airbytehq/airbyte/files/10223739/greg_default_logs_958649_txt.1.txt)

**Comment by grishick** [comment]
Update: after looking at it together with Benoit we found the bug and it is in BigQueryDestination.java on line 103. The destination is swallowing the error here:

```
if (UploadingMethod.GCS.equals(uploadingMethod)) {
        checkGcsPermission(config);
      }
```

`checkGcsPermission` returns `AirbyteConnectionStatus` and when that status is `FAILURE`, we shouldn't continue checking, but should return the message further up the call stack
