### ISSUE TITLE
BigQuery destination runs into 404 error in `STANDARD` mode (reproduce the error)

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#19998]
OnCall issues https://github.com/airbytehq/oncall/issues/1134, https://github.com/airbytehq/oncall/issues/1271

A [connection](https://cloud.airbyte.io/workspaces/cd88cbb4-36c8-4738-9138-f1a26d3bee72/connections/8d01e7d6-44dc-4941-b79a-9ad2e0987c84/status#902272::2) configured to use `STANDARD` loading method passed `CHECK` but failed with an error that indicates that dataset either does not exist or is not located in the specified region:

```
	2022-12-01 02:21:54 [43mdestination[0m > Selected loading method is set to: STANDARD
2022-12-01 02:21:55 [43mdestination[0m > Partitioned table created successfully: GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=public, tableId=_airbyte_tmp_kol_activities}}
2022-12-01 02:21:55 [43mdestination[0m > Selected loading method is set to: STANDARD
2022-12-01 02:21:55 [43mdestination[0m > Something went wrong in the connector. See the logs for more details.
Stack Trace: com.google.cloud.bigquery.BigQueryException: 404 Not Found
POST https://www.googleapis.com/upload/bigquery/v2/projects/redacted-dataset-name/jobs?uploadType=resumable
{
  "error": {
    "code": 404,
    "message": "Not found: Dataset redacted-dataset-name:redacted-schema-name",
    "errors": [
      {
        "message": "Not found: Dataset redacted-dataset-name:redacted-schema-name,
        "domain": "global",
        "reason": "notFound"
      }
    ],
    "status": "NOT_FOUND"
  }
}

	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:115)
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.open(HttpBigQueryRpc.java:655)
	at com.google.cloud.bigquery.TableDataWriteChannel$2.call(TableDataWriteChannel.java:87)
	at com.google.cloud.bigquery.TableDataWriteChannel$2.call(TableDataWriteChannel.java:82)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.bigquery.TableDataWriteChannel.open(TableDataWriteChannel.java:81)
	at com.google.cloud.bigquery.TableDataWriteChannel.<init>(TableDataWriteChannel.java:41)
	at com.google.cloud.bigquery.BigQueryImpl.writer(BigQueryImpl.java:1388)
	at io.airbyte.integrations.destination.bigquery.uploader.BigQueryUploaderFactory.getBigQueryDirectUploader(BigQueryUploaderFactory.java:144)
	at io.airbyte.integrations.destination.bigquery.uploader.BigQueryUploaderFactory.getUploader(BigQueryUploaderFactory.java:66)
	at io.airbyte.integrations.destination.bigquery.BigQueryDestination.putStreamIntoUploaderMap(BigQueryDestination.java:241)
	at io.airbyte.integrations.destination.bigquery.BigQueryDestination.getUploaderMap(BigQueryDestination.java:230)
	at io.airbyte.integrations.destination.bigquery.BigQueryDestination.getStandardRecordConsumer(BigQueryDestination.java:269)
	at io.airbyte.integrations.destination.bigquery.BigQueryDestination.getConsumer(BigQueryDestination.java:201)
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:149)
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:100)
	at io.airbyte.integrations.destination.bigquery.BigQueryDestination.main(BigQueryDestination.java:327)
Caused by: com.google.api.client.http.HttpResponseException: 404 Not Found
```

the other strange behavior that I noticed in this case is that the connector successfully created a table before attempting to load data.  Looking at the destination code, one suspicion I have is that the connector should specify dataset location when creating the table in `STANDARD` mode.

**Comment by grishick** [comment]
Related OC issue: https://github.com/airbytehq/oncall/issues/1134

**Comment by grishick** [comment]
Notes from grooming: it is not yet clear what is causing this. Dataset location could be it, but need to confirm.
Estimate is for coming up with repro scenario.

**Comment by etsybaev** [comment]
I finally managed to reproduce this issue. Basically, it's related to https://github.com/airbytehq/airbyte/issues/20561 and https://github.com/airbytehq/airbyte/issues/21030

In our case, we check the connection against the provided config (i.e. provided schema), but then we set the "Mirror Source Structure". So basically we will try to write data to the schema that we haven't checked.  

So steps to reproduce this particular issue:
1. Create a custom schema in bigquery in some location (ex. EU) manually.
2. Create a destination connector setting another location (ex. US) and some schema name
3. Create source connection to the DB with schema name equals to schema from step 1. 
4. Create c connection pair (source-destination) with the default "Mirror Source Structure".

Actual result:
All connectors will pass the check connection stage but the sync itself will fail


![Selection_187](https://user-images.githubusercontent.com/4688354/210621893-2d497397-d1cb-40de-a3bf-bef27ea4b2c9.png)


![Selection_188](https://user-images.githubusercontent.com/4688354/210621938-921c04be-adea-4413-bbea-0672f60b6316.png)


![Selection_189](https://user-images.githubusercontent.com/4688354/210621965-5baab942-c0d9-408f-a2f6-077636528887.png)

![Workspace 1_185](https://user-images.githubusercontent.com/4688354/210621994-ead145db-0099-4782-9bb4-e31ab361d2a5.png)
