### ISSUE TITLE
Airbyte job can not sync successfully because *Failure processing workflow task*

### ISSUE THREAD

**Issue by thodquach** [airbytehq/airbyte#20014]
## Environment
- **Airbyte version**:  0.40.23
- **OS Version / Instance**: AWS EC2
- **Deployment**: Kubernetes EKS - v1.20.15-eks-fb459a0
- **Source Connector and version**: PostgresSQL 1.0.25
- **Destination Connector and version**: BigQuery 1.2.7
- **Step where error happened**: Sync job

## Current Behavior
After set up Airbyte on K8s, set up source and destination (PSQL -> BigQuery), everythings is OK but
Sync job can not run successfully
I noticed that the sync pods (check job, sync job, normalize job) can not be created in K8s so the job failed, but the node of K8s still have many resource, event a I created new node for only airbyte to test this problem but the job still cannot be created to implement the sync job

## Expected Behavior
Sync job run successfully

## Logs

[0909faaf_37c0_4a94_ba64_6c3328aab973_logs_5_txt.txt](https://github.com/airbytehq/airbyte/files/10138115/0909faaf_37c0_4a94_ba64_6c3328aab973_logs_5_txt.txt)
[0909faaf_37c0_4a94_ba64_6c3328aab973_logs_5_txt (1).txt](https://github.com/airbytehq/airbyte/files/10138118/0909faaf_37c0_4a94_ba64_6c3328aab973_logs_5_txt.1.txt)
And sometimes sync logs is: (there is no action on k8s at all?)
```
No logs available
```
And I notice that in woker pods logs there are many error logs:
```
022-12-02 04:11:45 INFO i.a.w.t.s.ConnectionManagerWorkflowImpl(runMandatoryActivityWithOutput):630 - Waiting PT10M before restarting the workflow for connection null, to prevent spamming temporal with restarts.
2022-12-02 04:11:45 INFO i.a.w.t.s.ConnectionManagerWorkflowImpl(runMandatoryActivityWithOutput):645 - Finished wait for connection null, restarting connection manager workflow
2022-12-02 04:11:45 ERROR i.a.w.t.s.ConnectionManagerWorkflowImpl(run):200 - The connection update workflow has failed, will create a new attempt.
java.lang.NullPointerException: connectionId is marked non-null but is null
	at io.airbyte.commons.temporal.scheduling.ConnectionUpdaterInput$ConnectionUpdaterInputBuilder.connectionId(ConnectionUpdaterInput.java:19) ~[io.airbyte-airbyte-commons-temporal-0.40.22.jar:?]
	at io.airbyte.commons.temporal.TemporalWorkflowUtils.buildStartWorkflowInput(TemporalWorkflowUtils.java:33) ~[io.airbyte-airbyte-commons-temporal-0.40.22.jar:?]
	at io.airbyte.workers.temporal.scheduling.ConnectionManagerWorkflowImpl.runMandatoryActivityWithOutput(ConnectionManagerWorkflowImpl.java:647) ~[io.airbyte-airbyte-workers-0.40.22.jar:?]
	at io.airbyte.workers.temporal.scheduling.ConnectionManagerWorkflowImpl.runMandatoryActivity(ConnectionManagerWorkflowImpl.java:670) ~[io.airbyte-airbyte-workers-0.40.22.jar:?]
	at io.airbyte.workers.temporal.scheduling.ConnectionManagerWorkflowImpl.recordMetric(ConnectionManagerWorkflowImpl.java:720) ~[io.airbyte-airbyte-workers-0.40.22.jar:?]
	at io.airbyte.workers.temporal.scheduling.ConnectionManagerWorkflowImpl.run(ConnectionManagerWorkflowImpl.java:166) ~[io.airbyte-airbyte-workers-0.40.22.jar:?]
	at ConnectionManagerWorkflowImplProxy.run$accessor$aCejtn94(Unknown Source) ~[?:?]
	at ConnectionManagerWorkflowImplProxy$auxiliary$r2WrmhtS.call(Unknown Source) ~[?:?]
	at io.airbyte.workers.temporal.support.TemporalActivityStubInterceptor.execute(TemporalActivityStubInterceptor.java:79) ~[io.airbyte-airbyte-workers-0.40.22.jar:?]
	at ConnectionManagerWorkflowImplProxy.run(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation$RootWorkflowInboundCallsInterceptor.execute(POJOWorkflowImplementationFactory.java:302) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation.execute(POJOWorkflowImplementationFactory.java:277) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.sync.WorkflowExecuteRunnable.run(WorkflowExecuteRunnable.java:71) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.sync.SyncWorkflow.lambda$start$0(SyncWorkflow.java:116) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.sync.CancellationScopeImpl.run(CancellationScopeImpl.java:102) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.sync.WorkflowThreadImpl$RunnableWrapper.run(WorkflowThreadImpl.java:106) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.worker.ActiveThreadReportingExecutor.lambda$submit$0(ActiveThreadReportingExecutor.java:53) ~[temporal-sdk-1.17.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
2022-12-02 04:11:45 ERROR i.a.w.t.s.ConnectionManagerWorkflowImpl(runMandatoryActivityWithOutput):621 - [ACTIVITY-FAILURE] Connection null failed to run an activity.(AttemptNumberFailureInput).  Connection manager workflow will be restarted after a delay of PT10M.
io.temporal.failure.ActivityFailure: scheduledEventId=28, startedEventId=29, activityType='AttemptFailureWithAttemptNumber', activityId='6a0645c9-e6a7-38af-ad05-bf434297f6fd', identity='1@airbyte-worker-7bdb968798-b4298', retryState=RETRY_STATE_MAXIMUM_ATTEMPTS_REACHED
	at java.lang.Thread.getStackTrace(Thread.java:2550) ~[?:?]
	at io.temporal.internal.sync.ActivityStubBase.execute(ActivityStubBase.java:49) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.sync.ActivityInvocationHandler.lambda$getActivityFunc$0(ActivityInvocationHandler.java:78) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.sync.ActivityInvocationHandlerBase.invoke(ActivityInvocationHandlerBase.java:60) ~[temporal-sdk-1.17.0.jar:?]
	at jdk.proxy2.$Proxy86.attemptFailureWithAttemptNumber(Unknown Source) ~[?:?]
	at io.airbyte.workers.temporal.scheduling.ConnectionManagerWorkflowImpl.lambda$runMandatoryActivity$2(ConnectionManagerWorkflowImpl.java:671) ~[io.airbyte-airbyte-workers-0.40.22.jar:?]
	at io.airbyte.workers.temporal.scheduling.ConnectionManagerWorkflowImpl.runMandatoryActivityWithOutput(ConnectionManagerWorkflowImpl.java:619) ~[io.airbyte-airbyte-workers-0.40.22.jar:?]
	at io.airbyte.workers.temporal.scheduling.ConnectionManagerWorkflowImpl.runMandatoryActivity(ConnectionManagerWorkflowImpl.java:670) ~[io.airbyte-airbyte-workers-0.40.22.jar:?]
	at io.airbyte.workers.temporal.scheduling.ConnectionManagerWorkflowImpl.reportFailure(ConnectionManagerWorkflowImpl.java:349) ~[io.airbyte-airbyte-workers-0.40.22.jar:?]
	at io.airbyte.workers.temporal.scheduling.ConnectionManagerWorkflowImpl.reportFailure(ConnectionManagerWorkflowImpl.java:330) ~[io.airbyte-airbyte-workers-0.40.22.jar:?]
	at io.airbyte.workers.temporal.scheduling.ConnectionManagerWorkflowImpl.run(ConnectionManagerWorkflowImpl.java:201) ~[io.airbyte-airbyte-workers-0.40.22.jar:?]
	at ConnectionManagerWorkflowImplProxy.run$accessor$aCejtn94(Unknown Source) ~[?:?]
	at ConnectionManagerWorkflowImplProxy$auxiliary$r2WrmhtS.call(Unknown Source) ~[?:?]
	at io.airbyte.workers.temporal.support.TemporalActivityStubInterceptor.execute(TemporalActivityStubInterceptor.java:79) ~[io.airbyte-airbyte-workers-0.40.22.jar:?]
	at ConnectionManagerWorkflowImplProxy.run(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation$RootWorkflowInboundCallsInterceptor.execute(POJOWorkflowImplementationFactory.java:302) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation.execute(POJOWorkflowImplementationFactory.java:277) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.sync.WorkflowExecuteRunnable.run(WorkflowExecuteRunnable.java:71) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.sync.SyncWorkflow.lambda$start$0(SyncWorkflow.java:116) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.sync.CancellationScopeImpl.run(CancellationScopeImpl.java:102) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.sync.WorkflowThreadImpl$RunnableWrapper.run(WorkflowThreadImpl.java:106) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.worker.ActiveThreadReportingExecutor.lambda$submit$0(ActiveThreadReportingExecutor.java:53) ~[temporal-sdk-1.17.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: io.temporal.failure.ApplicationFailure: type='java.lang.NullPointerException', nonRetryable=false
	at java.base/java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
	at java.base/java.util.ImmutableCollections$MapN.<init>(ImmutableCollections.java:1186) ~[?:?]
	at java.base/java.util.Map.of(Map.java:1393) ~[?:?]
	at io.airbyte.workers.temporal.scheduling.activities.JobCreationAndStatusUpdateActivityImpl.attemptFailureWithAttemptNumber(JobCreationAndStatusUpdateActivityImpl.java:319) ~[io.airbyte-airbyte-workers-0.40.22.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at io.temporal.internal.activity.RootActivityInboundCallsInterceptor$POJOActivityInboundCallsInterceptor.executeActivity(RootActivityInboundCallsInterceptor.java:64) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.activity.RootActivityInboundCallsInterceptor.execute(RootActivityInboundCallsInterceptor.java:43) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.activity.ActivityTaskExecutors$BaseActivityTaskExecutor.execute(ActivityTaskExecutors.java:95) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.activity.ActivityTaskHandlerImpl.handle(ActivityTaskHandlerImpl.java:92) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handleActivity(ActivityWorker.java:241) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:206) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:179) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93) ~[temporal-sdk-1.17.0.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1589) ~[?:?]
2022-12-02 04:11:45 INFO i.a.w.t.s.ConnectionManagerWorkflowImpl(runMandatoryActivityWithOutput):630 - Waiting PT10M before restarting the workflow for connection null, to prevent spamming temporal with restarts.
2022-12-02 04:11:45 INFO i.a.w.t.s.ConnectionManagerWorkflowImpl(runMandatoryActivityWithOutput):645 - Finished wait for connection null, restarting connection manager workflow
2022-12-02 04:11:45 WARN i.t.i.r.ReplayWorkflowTaskHandler(failureToWFTResult):255 - Workflow task processing failure. startedEventId=40, WorkflowId=connection_manager_7b63e308-310f-4ae7-b9db-f8d8b2ce9e00, RunId=c3994f63-f3e7-40a2-8aa2-c0cc661faa3e. If seen continuously the workflow might be stuck.
io.temporal.internal.statemachines.InternalWorkflowTaskException: Failure handling event 40 of type 'EVENT_TYPE_WORKFLOW_TASK_STARTED' during execution. {WorkflowTaskStartedEventId=40, CurrentStartedEventId=40}
	at io.temporal.internal.statemachines.WorkflowStateMachines.createEventProcessingException(WorkflowStateMachines.java:257) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.statemachines.WorkflowStateMachines.handleEventsBatch(WorkflowStateMachines.java:236) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.statemachines.WorkflowStateMachines.handleEvent(WorkflowStateMachines.java:208) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.applyServerHistory(ReplayWorkflowRunTaskHandler.java:208) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.handleWorkflowTaskImpl(ReplayWorkflowRunTaskHandler.java:192) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.handleWorkflowTask(ReplayWorkflowRunTaskHandler.java:147) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.replay.ReplayWorkflowTaskHandler.handleWorkflowTaskWithQuery(ReplayWorkflowTaskHandler.java:132) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.replay.ReplayWorkflowTaskHandler.handleWorkflowTask(ReplayWorkflowTaskHandler.java:97) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handleTask(WorkflowWorker.java:336) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:246) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:188) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93) ~[temporal-sdk-1.17.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.RuntimeException: WorkflowTask: failure executing SCHEDULED->WORKFLOW_TASK_STARTED, transition history is [CREATED->WORKFLOW_TASK_SCHEDULED]
	at io.temporal.internal.statemachines.StateMachine.executeTransition(StateMachine.java:152) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.statemachines.StateMachine.handleHistoryEvent(StateMachine.java:102) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.statemachines.EntityStateMachineBase.handleEvent(EntityStateMachineBase.java:68) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.statemachines.WorkflowStateMachines.handleSingleEvent(WorkflowStateMachines.java:277) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.statemachines.WorkflowStateMachines.handleEventsBatch(WorkflowStateMachines.java:234) ~[temporal-sdk-1.17.0.jar:?]
	... 13 more
Caused by: java.lang.NullPointerException: connectionId is marked non-null but is null
	at io.airbyte.commons.temporal.scheduling.ConnectionUpdaterInput$ConnectionUpdaterInputBuilder.connectionId(ConnectionUpdaterInput.java:19) ~[io.airbyte-airbyte-commons-temporal-0.40.22.jar:?]
	at io.airbyte.commons.temporal.TemporalWorkflowUtils.buildStartWorkflowInput(TemporalWorkflowUtils.java:33) ~[io.airbyte-airbyte-commons-temporal-0.40.22.jar:?]
	at io.airbyte.workers.temporal.scheduling.ConnectionManagerWorkflowImpl.runMandatoryActivityWithOutput(ConnectionManagerWorkflowImpl.java:647) ~[io.airbyte-airbyte-workers-0.40.22.jar:?]
	at io.airbyte.workers.temporal.scheduling.ConnectionManagerWorkflowImpl.runMandatoryActivity(ConnectionManagerWorkflowImpl.java:670) ~[io.airbyte-airbyte-workers-0.40.22.jar:?]
	at io.airbyte.workers.temporal.scheduling.ConnectionManagerWorkflowImpl.reportFailure(ConnectionManagerWorkflowImpl.java:349) ~[io.airbyte-airbyte-workers-0.40.22.jar:?]
	at io.airbyte.workers.temporal.scheduling.ConnectionManagerWorkflowImpl.reportFailure(ConnectionManagerWorkflowImpl.java:330) ~[io.airbyte-airbyte-workers-0.40.22.jar:?]
	at io.airbyte.workers.temporal.scheduling.ConnectionManagerWorkflowImpl.run(ConnectionManagerWorkflowImpl.java:201) ~[io.airbyte-airbyte-workers-0.40.22.jar:?]
	at ConnectionManagerWorkflowImplProxy.run$accessor$aCejtn94(Unknown Source) ~[?:?]
	at ConnectionManagerWorkflowImplProxy$auxiliary$r2WrmhtS.call(Unknown Source) ~[?:?]
	at io.airbyte.workers.temporal.support.TemporalActivityStubInterceptor.execute(TemporalActivityStubInterceptor.java:79) ~[io.airbyte-airbyte-workers-0.40.22.jar:?]
	at ConnectionManagerWorkflowImplProxy.run(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation$RootWorkflowInboundCallsInterceptor.execute(POJOWorkflowImplementationFactory.java:302) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation.execute(POJOWorkflowImplementationFactory.java:277) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.sync.WorkflowExecuteRunnable.run(WorkflowExecuteRunnable.java:71) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.sync.SyncWorkflow.lambda$start$0(SyncWorkflow.java:116) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.sync.CancellationScopeImpl.run(CancellationScopeImpl.java:102) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.sync.WorkflowThreadImpl$RunnableWrapper.run(WorkflowThreadImpl.java:106) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.worker.ActiveThreadReportingExecutor.lambda$submit$0(ActiveThreadReportingExecutor.java:53) ~[temporal-sdk-1.17.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	... 3 more
2022-12-02 04:11:45 ERROR i.t.i.w.PollerOptions$Builder(lambda$build$0):146 - uncaught exception
java.lang.RuntimeException: Failure processing workflow task. WorkflowId=connection_manager_7b63e308-310f-4ae7-b9db-f8d8b2ce9e00, RunId=c3994f63-f3e7-40a2-8aa2-c0cc661faa3e, Attempt=5917
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.wrapFailure(WorkflowWorker.java:327) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.wrapFailure(WorkflowWorker.java:188) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:98) ~[temporal-sdk-1.17.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: io.temporal.internal.statemachines.InternalWorkflowTaskException: Failure handling event 40 of type 'EVENT_TYPE_WORKFLOW_TASK_STARTED' during execution. {WorkflowTaskStartedEventId=40, CurrentStartedEventId=40}
	at io.temporal.internal.statemachines.WorkflowStateMachines.createEventProcessingException(WorkflowStateMachines.java:257) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.statemachines.WorkflowStateMachines.handleEventsBatch(WorkflowStateMachines.java:236) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.statemachines.WorkflowStateMachines.handleEvent(WorkflowStateMachines.java:208) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.applyServerHistory(ReplayWorkflowRunTaskHandler.java:208) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.handleWorkflowTaskImpl(ReplayWorkflowRunTaskHandler.java:192) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.handleWorkflowTask(ReplayWorkflowRunTaskHandler.java:147) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.replay.ReplayWorkflowTaskHandler.handleWorkflowTaskWithQuery(ReplayWorkflowTaskHandler.java:132) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.replay.ReplayWorkflowTaskHandler.handleWorkflowTask(ReplayWorkflowTaskHandler.java:97) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handleTask(WorkflowWorker.java:336) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:246) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:188) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93) ~[temporal-sdk-1.17.0.jar:?]
	... 3 more
Caused by: java.lang.RuntimeException: WorkflowTask: failure executing SCHEDULED->WORKFLOW_TASK_STARTED, transition history is [CREATED->WORKFLOW_TASK_SCHEDULED]
	at io.temporal.internal.statemachines.StateMachine.executeTransition(StateMachine.java:152) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.statemachines.StateMachine.handleHistoryEvent(StateMachine.java:102) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.statemachines.EntityStateMachineBase.handleEvent(EntityStateMachineBase.java:68) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.statemachines.WorkflowStateMachines.handleSingleEvent(WorkflowStateMachines.java:277) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.statemachines.WorkflowStateMachines.handleEventsBatch(WorkflowStateMachines.java:234) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.statemachines.WorkflowStateMachines.handleEvent(WorkflowStateMachines.java:208) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.applyServerHistory(ReplayWorkflowRunTaskHandler.java:208) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.handleWorkflowTaskImpl(ReplayWorkflowRunTaskHandler.java:192) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.handleWorkflowTask(ReplayWorkflowRunTaskHandler.java:147) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.replay.ReplayWorkflowTaskHandler.handleWorkflowTaskWithQuery(ReplayWorkflowTaskHandler.java:132) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.replay.ReplayWorkflowTaskHandler.handleWorkflowTask(ReplayWorkflowTaskHandler.java:97) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handleTask(WorkflowWorker.java:336) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:246) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:188) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93) ~[temporal-sdk-1.17.0.jar:?]
	... 3 more
Caused by: java.lang.NullPointerException: connectionId is marked non-null but is null
	at io.airbyte.commons.temporal.scheduling.ConnectionUpdaterInput$ConnectionUpdaterInputBuilder.connectionId(ConnectionUpdaterInput.java:19) ~[io.airbyte-airbyte-commons-temporal-0.40.22.jar:?]
	at io.airbyte.commons.temporal.TemporalWorkflowUtils.buildStartWorkflowInput(TemporalWorkflowUtils.java:33) ~[io.airbyte-airbyte-commons-temporal-0.40.22.jar:?]
	at io.airbyte.workers.temporal.scheduling.ConnectionManagerWorkflowImpl.runMandatoryActivityWithOutput(ConnectionManagerWorkflowImpl.java:647) ~[io.airbyte-airbyte-workers-0.40.22.jar:?]
	at io.airbyte.workers.temporal.scheduling.ConnectionManagerWorkflowImpl.runMandatoryActivity(ConnectionManagerWorkflowImpl.java:670) ~[io.airbyte-airbyte-workers-0.40.22.jar:?]
	at io.airbyte.workers.temporal.scheduling.ConnectionManagerWorkflowImpl.reportFailure(ConnectionManagerWorkflowImpl.java:349) ~[io.airbyte-airbyte-workers-0.40.22.jar:?]
	at io.airbyte.workers.temporal.scheduling.ConnectionManagerWorkflowImpl.reportFailure(ConnectionManagerWorkflowImpl.java:330) ~[io.airbyte-airbyte-workers-0.40.22.jar:?]
	at io.airbyte.workers.temporal.scheduling.ConnectionManagerWorkflowImpl.run(ConnectionManagerWorkflowImpl.java:201) ~[io.airbyte-airbyte-workers-0.40.22.jar:?]
	at ConnectionManagerWorkflowImplProxy.run$accessor$aCejtn94(Unknown Source) ~[?:?]
	at ConnectionManagerWorkflowImplProxy$auxiliary$r2WrmhtS.call(Unknown Source) ~[?:?]
	at io.airbyte.workers.temporal.support.TemporalActivityStubInterceptor.execute(TemporalActivityStubInterceptor.java:79) ~[io.airbyte-airbyte-workers-0.40.22.jar:?]
	at ConnectionManagerWorkflowImplProxy.run(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation$RootWorkflowInboundCallsInterceptor.execute(POJOWorkflowImplementationFactory.java:302) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation.execute(POJOWorkflowImplementationFactory.java:277) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.sync.WorkflowExecuteRunnable.run(WorkflowExecuteRunnable.java:71) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.sync.SyncWorkflow.lambda$start$0(SyncWorkflow.java:116) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.sync.CancellationScopeImpl.run(CancellationScopeImpl.java:102) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.sync.WorkflowThreadImpl$RunnableWrapper.run(WorkflowThreadImpl.java:106) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.worker.ActiveThreadReportingExecutor.lambda$submit$0(ActiveThreadReportingExecutor.java:53) ~[temporal-sdk-1.17.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	... 3 more

```

## Steps to Reproduce
1. Set up Airbyte using latest helm chart of airbyte in K8s
2. Set up source (PSQL) and destination (BigQuery)
3. Set up connection and click sync button

## Are you willing to submit a PR?

No

If anyone need more information I will supply from our system
Tks and Br

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.

**Comment by capture-namang** [comment]
I am still getting the error
