### ISSUE TITLE
Low-code CDK: error on "python main.py spec" with python3.11

### ISSUE THREAD

**Issue by smitterer** [airbytehq/airbyte#20168]
## Environment
- **Airbyte version**:  0.40.23
- **OS Version / Instance**: Ubuntu 20.04 via WSL2
- **Deployment**: Docker
- **Source Connector and version**:  CDK / Low Code
- **Destination Connector and version**: not applicable
- **Step where error happened**: [Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte](https://airbytehq.github.io/connector-development/config-based/tutorial/install-dependencies)

## Current Behavior
when going through all the steps in the tutorial and running `python main.py spec` I get:
```
Traceback (most recent call last):
  File "/home/myuser/dev/airbyte/airbyte-integrations/connectors/source-pimcore-graphql/main.py", line 8, in <module>
    from airbyte_cdk.entrypoint import launch
  File "/home/myuser/dev/airbyte/airbyte-integrations/connectors/source-pimcore-graphql/.venv/lib/python3.11/site-packages/airbyte_cdk/__init__.py", line 5, in <module>
    from .connector import AirbyteSpec, Connector
  File "/home/myuser/dev/airbyte/airbyte-integrations/connectors/source-pimcore-graphql/.venv/lib/python3.11/site-packages/airbyte_cdk/connector.py", line 14, in <module>
    from airbyte_cdk.models import AirbyteConnectionStatus, ConnectorSpecification
  File "/home/myuser/dev/airbyte/airbyte-integrations/connectors/source-pimcore-graphql/.venv/lib/python3.11/site-packages/airbyte_cdk/models/__init__.py", line 2, in <module>
    from .airbyte_protocol import *
  File "/home/myuser/dev/airbyte/airbyte-integrations/connectors/source-pimcore-graphql/.venv/lib/python3.11/site-packages/airbyte_cdk/models/airbyte_protocol.py", line 346, in <module>
    class AirbyteStateMessage(BaseModel):
  File "/home/myuser/dev/airbyte/airbyte-integrations/connectors/source-pimcore-graphql/.venv/lib/python3.11/site-packages/pydantic/main.py", line 292, in __new__
    cls.__signature__ = ClassAttribute('__signature__', generate_model_signature(cls.__init__, fields, config))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/dev/airbyte/airbyte-integrations/connectors/source-pimcore-graphql/.venv/lib/python3.11/site-packages/pydantic/utils.py", line 258, in generate_model_signature
    merged_params[param_name] = Parameter(
                                ^^^^^^^^^^
  File "/usr/lib/python3.11/inspect.py", line 2715, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: 'global' is not a valid parameter name
```

## Expected Behavior
It should return some json as in the documentation

## Steps to Reproduce
Go through the CDK low code tutorial till you reach the point where you run `python main.py spec`
Might this be related to python3.11?

**Comment by smitterer** [comment]
Hi @juweins 

I just went through the tutorial. The yaml already looked as described in the linked PR (the correct version) without further changes.

**Comment by juweins** [comment]
> Hi @juweins
> 
> I just went through the tutorial. The yaml already looked as described in the linked PR (the correct version) without further changes.

@smitterer I assume restrarting the tutorial fixed your issue?

@marcosmarxm This Issue can be closed.

**Comment by smitterer** [comment]
@juweins I went through the tutorial again and am unfortunately still getting the same error.

**Comment by girarda** [comment]
the only python version we currently support is 3.9
