### ISSUE TITLE
[Custom Connector Stream Reset] Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "io.airbyte.persistence.job.models.IntegrationLauncherConfig.getIsCustomConnector()" is null

### ISSUE THREAD

**Issue by philippeboyd** [airbytehq/airbyte#20265]
## Environment
- **Airbyte version**:  0.40.24
- **OS Version / Instance**: GCP COS
- **Deployment**: Docker
- **Step where error happened**: Reset

## Current Behavior
Reset fails with `Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "io.airbyte.persistence.job.models.IntegrationLauncherConfig.getIsCustomConnector()" is null`

## Expected Behavior
Reset should not fail

## Logs
```
2022-12-08 21:40:28 INFO i.a.w.t.TemporalAttemptExecution(get):136 - Docker volume job log path: /tmp/workspace/9523/1/logs.log
2022-12-08 21:40:28 INFO i.a.w.t.TemporalAttemptExecution(get):141 - Executing worker wrapper. Airbyte version: 0.40.24
2022-12-08 21:40:28 INFO i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to save workflow id for cancellation
2022-12-08 21:40:28 INFO i.a.c.t.TemporalUtils(withBackgroundHeartbeat):283 - Stopping temporal heartbeating...
2022-12-08 21:40:28 WARN i.t.i.a.ActivityTaskExecutors$BaseActivityTaskExecutor(execute):114 - Activity failure. ActivityId=f0815dca-854e-3b15-8f04-a70207c8080d, activityType=Replicate, attempt=1
java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "io.airbyte.persistence.job.models.IntegrationLauncherConfig.getIsCustomConnector()" is null
	at io.airbyte.commons.temporal.TemporalUtils.withBackgroundHeartbeat(TemporalUtils.java:281) ~[io.airbyte-airbyte-commons-temporal-0.40.24.jar:?]
	at io.airbyte.workers.temporal.sync.ReplicationActivityImpl.replicate(ReplicationActivityImpl.java:156) ~[io.airbyte-airbyte-workers-0.40.24.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at io.temporal.internal.activity.RootActivityInboundCallsInterceptor$POJOActivityInboundCallsInterceptor.executeActivity(RootActivityInboundCallsInterceptor.java:64) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.activity.RootActivityInboundCallsInterceptor.execute(RootActivityInboundCallsInterceptor.java:43) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.activity.ActivityTaskExecutors$BaseActivityTaskExecutor.execute(ActivityTaskExecutors.java:95) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.activity.ActivityTaskHandlerImpl.handle(ActivityTaskHandlerImpl.java:92) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handleActivity(ActivityWorker.java:241) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:206) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:179) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93) ~[temporal-sdk-1.17.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "io.airbyte.persistence.job.models.IntegrationLauncherConfig.getIsCustomConnector()" is null
	at io.airbyte.workers.temporal.sync.ReplicationActivityImpl.lambda$getLegacyWorkerFactory$6(ReplicationActivityImpl.java:277) ~[io.airbyte-airbyte-workers-0.40.24.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:147) ~[io.airbyte-airbyte-workers-0.40.24.jar:?]
	at io.airbyte.workers.temporal.sync.ReplicationActivityImpl.lambda$replicate$3(ReplicationActivityImpl.java:201) ~[io.airbyte-airbyte-workers-0.40.24.jar:?]
	at io.airbyte.commons.temporal.TemporalUtils.withBackgroundHeartbeat(TemporalUtils.java:276) ~[io.airbyte-airbyte-commons-temporal-0.40.24.jar:?]
	... 14 more
```

## Steps to Reproduce
1. Reset streams using a custom connector

**Comment by natalyjazzviolin** [comment]
Hey @philippeboyd I want to make sure this isn't particular to your custom connector, but to the platform as a whole. Could you please attach screenshots/screen caps to show how to replicate the problem? Closing for now, will reopen once I get more details.

**Comment by philippeboyd** [comment]
@natalyjazzviolin How can this be an error with my custom connector when we don't have any control on the Reset step?

Also the error clearly comes from Airbyte where `IntegrationLauncherConfig.getIsCustomConnector()` returns null instead of a boolean.

I would like to debug myself but it seems the implementation of `getIsCustomConnector()` is not open source.

Please reopen this issue.

**Comment by philippeboyd** [comment]
Hi @marcosmarxm, sorry to tag you here but as an Airbyte veteran, I thought you might know where I could find the implementation of `IntegrationLauncherConfig.getIsCustomConnector()` as the class `io.airbyte.persistence.job.models.IntegrationLauncherConfig` doesn't seem to be part of the open source version of Airbyte.

I'm trying to figure out why `getIsCustomConnector()` is returning `null` on my custom connector.

Thanks for the help

**Comment by philippeboyd** [comment]
@natalyjazzviolin do you know the implementation of `IntegrationLauncherConfig.getIsCustomConnector()` so that I can figure out why it's returning `null`?

**Comment by vasilisgav** [comment]
@philippeboyd we are having the same issue, were you able to figure this out? thanks!

**Comment by philippeboyd** [comment]
@vasilisgav unfortunately, no. And @natalyjazzviolin is not answering. And we cannot debug this since the implementation of `IntegrationLauncherConfig.getIsCustomConnector()` is closed source.

**Comment by vasilisgav** [comment]
@vasilisgav thank you for answering, Thankfully the error disappeared once we upgraded airbyte to version 0.42.0. Don't know though which version (from 0.40.24 till 0.42.0) fixes the issue.
