### ISSUE TITLE
Connector Builder pod failing to start

### ISSUE THREAD

**Issue by eabrouwer3** [airbytehq/airbyte#20309]
## Environment
- **Airbyte version**: 0.40.24
- **OS Version / Instance**: Amazon EKS
- **Deployment**: Amazon EKS via Helm Chart
- **Step where error happened**: Deploy

## Current Behavior
The connector builder pod ends up in this state:
```
pod/airbyte-core-connector-builder-server-ccc4d6f9f-pq8qv   0/1     CrashLoopBackOff   3 (15s ago)   64s
```

## Expected Behavior
The connector builder pod should look like this:
```
pod/airbyte-core-connector-builder-server-ccc4d6f9f-pq8qv   1/1     Completed   0   64s
```

## Logs
```
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 404, in main
    run(
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/connector-builder-server/./connector_builder/entrypoint.py", line 8, in <module>
    from connector_builder.generated.apis.default_api_interface import initialize_router
  File "/home/connector-builder-server/./connector_builder/generated/apis/default_api_interface.py", line 31, in <module>
    from connector_builder.generated.models.stream_read_request_body import StreamReadRequestBody
  File "/home/connector-builder-server/./connector_builder/generated/models/stream_read_request_body.py", line 10, in <module>
    from connector_builder.generated.models.connector_manifest import ConnectorManifest
  File "/home/connector-builder-server/./connector_builder/generated/models/connector_manifest.py", line 11, in <module>
    from connector_builder.generated.models.declarative_stream import DeclarativeStream
  File "/home/connector-builder-server/./connector_builder/generated/models/declarative_stream.py", line 10, in <module>
    from connector_builder.generated.models.any_of_add_fields_remove_fields import AnyOfAddFieldsRemoveFields
ModuleNotFoundError: No module named 'connector_builder.generated.models.any_of_add_fields_remove_fields'
```

## Steps to Reproduce
1. Deploy Helm chart 0.43.0 to EKS
2. Run `kubectl get pods` and see the pod is failing
3. Run `kubectl logs pod/airbyte-connector-builder-server-...` on the pod to see the logs where it's failing

## Are you willing to submit a PR?
Potentially yes

## Current Workaround
I don't need the connector builder right now, so in my `values.yaml` file I simply add this:
```yaml
connectorBuilderServer:
  enabled: false
```

**Comment by eabrouwer3** [comment]
So, actually I had to set

```yaml
connector-builder-server:
  enabled: false
```

to get it to not create the pod, but then the webapp throws these errors:

```
2022/12/09 20:23:48 [emerg] 1#1: host not found in upstream "airbyte-core-airbyte-connector-builder-server-svc:8003" in /etc/nginx/conf.d/default.conf:6
nginx: [emerg] host not found in upstream "airbyte-core-airbyte-connector-builder-server-svc:8003" in /etc/nginx/conf.d/default.conf:6
```
