### ISSUE TITLE
Source-snowflake showing an error upon finishing up a sync

### ISSUE THREAD

**Issue by rodireich** [airbytehq/airbyte#20467]
## Environment
- **Airbyte version**:  example is 0.22.0-alpha
- **OS Version / Instance**: example macOS, Windows 7/10, Ubuntu 18.04, GCP n2. , AWS EC2
- **Deployment**: example are Docker or Kubernetes deploy env
- **Source Connector and version**: (if applicable example Salesforce 0.2.3) 
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
When source-snowflake completed a sync successfully I see the following error in log which indicates the connection did not shutdown gracefully

## Expected Behavior
Finish up reading from snowflake and shutdown without an error

## Logs
```
22-12-10 02:42:35 [44msource[0m > Table SAT_BASIC_DATASET column TEST_COLUMN_6 (type NUMBER[38], nullable false) -> JsonSchemaType({type=number, airbyte_type=integer})
2022-12-10 02:42:35 [44msource[0m > Table SAT_BASIC_DATASET column TEST_COLUMN_7 (type NUMBER[38], nullable false) -> JsonSchemaType({type=number, airbyte_type=integer})
2022-12-10 02:42:35 [44msource[0m > Table SAT_BASIC_DATASET column TEST_COLUMN_8 (type NUMBER[38], nullable false) -> JsonSchemaType({type=number, airbyte_type=integer})
2022-12-10 02:42:35 [44msource[0m > Table SAT_BASIC_DATASET column TEST_COLUMN_9 (type NUMBER[38], nullable false) -> JsonSchemaType({type=number, airbyte_type=integer})
2022-12-10 02:42:35 [44msource[0m > Queueing query for table: MY_TEST_TABLE
2022-12-10 02:42:35 [44msource[0m > Set initial fetch size: 10 rows
2022-12-10 02:42:36 [44msource[0m > The main thread is exiting while children non-daemon threads from a connector are still active.
Ideally, this situation should not happen...
Please check with maintainers if the connector or library code should safely clean up its threads before quitting instead.
The main thread is: main (RUNNABLE)
 Thread stacktrace: java.base/java.lang.Thread.getStackTrace(Thread.java:1610)
        at io.airbyte.integrations.base.IntegrationRunner.dumpThread(IntegrationRunner.java:334)
        at io.airbyte.integrations.base.IntegrationRunner.watchForOrphanThreads(IntegrationRunner.java:282)
        at io.airbyte.integrations.base.IntegrationRunner.produceMessages(IntegrationRunner.java:219)
        at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:141)
        at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:100)
        at io.airbyte.integrations.base.adaptive.AdaptiveSourceRunner$Runner.run(AdaptiveSourceRunner.java:86)
        at io.airbyte.integrations.source.snowflake.SnowflakeSourceRunner.main(SnowflakeSourceRunner.java:15)
2022-12-10 02:42:36 [44msource[0m > Active non-daemon thread: pool-5-thread-1 (RUNNABLE)
 Thread stacktrace: java.base@17.0.4.1/sun.nio.ch.Net.poll(Native Method)
        at java.base@17.0.4.1/sun.nio.ch.NioSocketImpl.park(NioSocketImpl.java:181)
        at java.base@17.0.4.1/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:285)
        at java.base@17.0.4.1/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309)
        at java.base@17.0.4.1/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
        at java.base@17.0.4.1/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
        at java.base@17.0.4.1/java.net.Socket$SocketInputStream.read(Socket.java:966)
        at java.base@17.0.4.1/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
        at java.base@17.0.4.1/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
        at java.base@17.0.4.1/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
        at java.base@17.0.4.1/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1460)
        at java.base@17.0.4.1/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1064)
        at app//net.snowflake.client.jdbc.internal.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
        at app//net.snowflake.client.jdbc.internal.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
        at app//net.snowflake.client.jdbc.internal.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
        at app//net.snowflake.client.jdbc.internal.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
        at app//net.snowflake.client.jdbc.internal.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
        at app//net.snowflake.client.jdbc.internal.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at app//net.snowflake.client.jdbc.internal.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
        at app//net.snowflake.client.jdbc.internal.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
        at app//net.snowflake.client.jdbc.internal.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
        at app//net.snowflake.client.jdbc.internal.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
        at app//net.snowflake.client.jdbc.internal.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
        at app//net.snowflake.client.jdbc.internal.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at app//net.snowflake.client.jdbc.internal.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at app//net.snowflake.client.jdbc.internal.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at app//net.snowflake.client.jdbc.internal.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at app//net.snowflake.client.jdbc.internal.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at app//net.snowflake.client.jdbc.internal.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at app//net.snowflake.client.jdbc.RestRequest.execute(RestRequest.java:174)
        at app//net.snowflake.client.core.HttpUtil.executeRequestInternal(HttpUtil.java:737)
        at app//net.snowflake.client.core.HttpUtil.executeRequest(HttpUtil.java:672)
        at app//net.snowflake.client.core.HttpUtil.executeGeneralRequest(HttpUtil.java:594)
        at app//net.snowflake.client.jdbc.telemetry.TelemetryClient.sendBatch(TelemetryClient.java:336)
        at app//net.snowflake.client.jdbc.telemetry.TelemetryClient.lambda$sendBatchAsync$0(TelemetryClient.java:267)
        at app//net.snowflake.client.jdbc.telemetry.TelemetryClient$$Lambda$275/0x000000080100d6e0.call(Unknown Source)
        at java.base@17.0.4.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)
2022-12-10 02:42:36 [44msource[0m > Closing database connection pool.
2022-12-10 02:42:36 [44msource[0m > HikariPool-1 - Shutdown initiated...
2022-12-10 02:42:37 [44msource[0m > HikariPool-1 - Shutdown completed.
2022-12-10 02:42:37 [44msource[0m > Closed database connection pool.
2022-12-10 02:42:37 [44msource[0m > Completed integration: io.airbyte.integrations.source.snowflake.SnowflakeSource
2022-12-10 02:42:37 [44msource[0m > Completed source: io.airbyte.integrations.source.snowflake.SnowflakeSource
```

**Comment by bleonard** [comment]
Moving this to backlog if this is every time. That right @rodireich ?

**Comment by rodireich** [comment]
This was happening every time for that connection. I don't think this is generally happen to all source-snowflake.
I also feel like @VitaliiMaltsev may have looked at it at some point(?)

**Comment by rodireich** [comment]
@VitaliiMaltsev is #20888 the same issue?

**Comment by VitaliiMaltsev** [comment]
> @VitaliiMaltsev is #20888 the same issue?

@rodireich I don't think these 2 issues are related.

**Comment by bleonard** [comment]
Maybe some sort of open connection?

**Comment by prateekmukhedkar** [comment]
Does not have an impact on the sync.
