### ISSUE TITLE
Default 2GB memory limit not being observed and JOB_MAIN_CONTAINER_MEMORY_LIMIT= kills containers instead of limiting

### ISSUE THREAD

**Issue by OrangeManLives** [airbytehq/airbyte#20508]
Created From Airbyte Discuss post https://discuss.airbyte.io/t/default-2gb-memory-limit-not-being-observed/3472

## Environment
- **Airbyte version**:  0.40.22
- **OS Version / Instance**: Oracle Linux 8 Ec2 Instance
- **Deployment**: Docker
- **Source Connector and version**: Postgres 1.0.33
- **Destination Connector and version**:  S3 0.3.17
- **Step where error happened**: The issue is happening during sync

## Current Behavior
I’m attempting to inital sync approximately 666 tables for a number of databases.
In this scenario, I’m only doing this for 1 database which results in 2.02GB of initial sync data, 479,832 records.

The documentation states that a container’s memory limit should default to 2GB, however, I’m seeing it use more than this, which will occasionally crash the EC2 instance requiring a restart.
https://docs.airbyte.com/operator-guides/scaling-airbyte/#memory

## Expected Behavior
I’ve attempted to set the max memory usage using `JOB_MAIN_CONTAINER_MEMORY_LIMIT=3g`, however, this just kills the sync when the limit is reached instead of limiting it as expected.

I would expect either the 2GB limit to be observed and setting JOB_MAIN_CONTAINER_MEMORY_LIMIT= be a limit rather than a kill switch.

## Logs

`
...
2022-12-14 11:53:50 source > Terminating due to java.lang.OutOfMemoryError: Java heap space
2022-12-14 11:53:51 ERROR i.a.w.g.DefaultReplicationWorker(replicate):229 - Sync worker failed.
java.util.concurrent.ExecutionException: io.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source cannot be stopped!
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
        at io.airbyte.workers.general.DefaultReplicationWorker.replicate(DefaultReplicationWorker.java:221) ~[io.airbyte-airbyte-commons-worker-0.40.22.jar:?]
        at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:157) ~[io.airbyte-airbyte-commons-worker-0.40.22.jar:?]
        at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:80) ~[io.airbyte-airbyte-commons-worker-0.40.22.jar:?]
        at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$4(TemporalAttemptExecution.java:192) ~[io.airbyte-airbyte-workers-0.40.22.jar:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
        Suppressed: io.airbyte.workers.exception.WorkerException: Source process exit with code 3. This warning is normal if the job was cancelled.
                at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:144) ~[io.airbyte-airbyte-commons-worker-0.40.22.jar:?]
                at io.airbyte.workers.general.DefaultReplicationWorker.replicate(DefaultReplicationWorker.java:178) ~[io.airbyte-airbyte-commons-worker-0.40.22.jar:?]
                at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:157) ~[io.airbyte-airbyte-commons-worker-0.40.22.jar:?]
                at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:80) ~[io.airbyte-airbyte-commons-worker-0.40.22.jar:?]
                at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$4(TemporalAttemptExecution.java:192) ~[io.airbyte-airbyte-workers-0.40.22.jar:?]
                at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: io.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source cannot be stopped!
        at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$6(DefaultReplicationWorker.java:328) ~[io.airbyte-airbyte-commons-worker-0.40.22.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        ... 1 more
Caused by: io.airbyte.workers.exception.WorkerException: Source process exit with code 3. This warning is normal if the job was cancelled.
        at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:144) ~[io.airbyte-airbyte-commons-worker-0.40.22.jar:?]
        at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$6(DefaultReplicationWorker.java:326) ~[io.airbyte-airbyte-commons-worker-0.40.22.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        ... 1 more
`

## Steps to Reproduce
1. Configure a Postgres source connection to a databae which typically syncs more than 2GB and approx 666 tables
2. Configure an S3 destination
3. Refresh source schema
4. Perform an initial sync and watch the memory climb past 2GB, and the container be killed if `JOB_MAIN_CONTAINER_MEMORY_LIMIT= `is exceeded

## Are you willing to submit a PR?
I would love to contribute, but Java is not in my current skill set.

**Comment by olivermeyer** [comment]
Seems to be the same issue as https://github.com/airbytehq/airbyte/issues/17575.

**Comment by davinchia** [comment]
This should be fixed with the latest versions. Please upgrade and let us know.
