### ISSUE TITLE
`Removal of NormalizationRunnerFactory` introduced a bug - "this.normalizationIntegrationType" is null

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#20559]
Releasing https://github.com/airbytehq/airbyte/pull/20245 to Airbyte Cloud caused a number of syncs to fail. The relevant stack trace is:

```
2022-12-16 00:42:30 normalization-orchestrator > Normalization failed for job 967706.
java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "this.normalizationIntegrationType" is null
	at io.airbyte.workers.normalization.DefaultNormalizationRunner.normalize(DefaultNormalizationRunner.java:107) ~[io.airbyte-airbyte-commons-worker-dev-6b86f5024c.jar:?]
	at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:77) ~[io.airbyte-airbyte-commons-worker-dev-6b86f5024c.jar:?]
	at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:34) ~[io.airbyte-airbyte-commons-worker-dev-6b86f5024c.jar:?]
	at io.airbyte.container_orchestrator.orchestrator.NormalizationJobOrchestrator.runJob(NormalizationJobOrchestrator.java:82) ~[io.airbyte-airbyte-container-orchestrator-dev-6b86f5024c.jar:?]
	at io.airbyte.container_orchestrator.Application.run(Application.java:79) ~[io.airbyte-airbyte-container-orchestrator-dev-6b86f5024c.jar:?]
	at io.airbyte.container_orchestrator.Application.main(Application.java:38) ~[io.airbyte-airbyte-container-orchestrator-dev-6b86f5024c.jar:?]
Log4j2Appender says: Normalization executed in 0 seconds for job 967706.
2022-12-16 00:42:30 normalization-orchestrator > Normalization executed in 0 seconds for job 967706.
Log4j2Appender says: Killing orchestrator because of an Exception
2022-12-16 00:42:30 ERROR i.a.c.Application(run):81 - Killing orchestrator because of an Exception
io.airbyte.workers.exception.WorkerException: Normalization Failed.
	at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:103) ~[io.airbyte-airbyte-commons-worker-dev-6b86f5024c.jar:?]
	at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:34) ~[io.airbyte-airbyte-commons-worker-dev-6b86f5024c.jar:?]
	at io.airbyte.container_orchestrator.orchestrator.NormalizationJobOrchestrator.runJob(NormalizationJobOrchestrator.java:82) ~[io.airbyte-airbyte-container-orchestrator-dev-6b86f5024c.jar:?]
	at io.airbyte.container_orchestrator.Application.run(Application.java:79) ~[io.airbyte-airbyte-container-orchestrator-dev-6b86f5024c.jar:?]
	at io.airbyte.container_orchestrator.Application.main(Application.java:38) ~[io.airbyte-airbyte-container-orchestrator-dev-6b86f5024c.jar:?]
```

The working theory is that the migration didn't alter existing configs, so we end up hitting null strings when trying to lookup old configs.  
```
public enum DestinationType {
    BIGQUERY,
    MSSQL,
    MYSQL,
    ORACLE,
    POSTGRES,
    REDSHIFT,
    SNOWFLAKE,
    CLICKHOUSE,
    TIDB
  }
```
This ^ was removed, and it looks like we should use those values to fill in any nulls in the config db.  The fix likely looks like another migration to populate the missing values.  

As https://github.com/airbytehq/airbyte/pull/20245 has already been deployed to Airbyte Cloud, we don't want to roll back that code unless absolutely necessary.

Deploying to Airbyte Cloud is frozen until this issue is resolved.

### Tasks:
1. Reproduce the bug to confirm the hypothesis that a sync which was started before the migration would produce the error above after the migration is applied, as the sync transitions from the replication phase to the normalization phase.  The best reproduction of this is a test.
2. Fix the bug! 
3. Work with @airbytehq/platform-cloud to re-enable Cloud deploys and deploy Airbyte Cloud

**Comment by marcelopio** [comment]
I am having this issue on Airbyte 0.40.26 after upgrading from 0.40.14.

Is it supposed to be fixed on 0.40.26? Do I have to do any manual steps to upgrade?

**Comment by pedroslopez** [comment]
Hi @marcelopio - this issue should have only affected our Cloud environments. Could you share more about what you're seeing? How is your environment configured? When are you seeing the error? Please post a full stack trace of any errors you're encountering to help us verify 😄

**Comment by marcelopio** [comment]
[91f8e58a_84d7_499a_b152_c75d708a4675_logs_78_txt.txt](https://github.com/airbytehq/airbyte/files/10260718/91f8e58a_84d7_499a_b152_c75d708a4675_logs_78_txt.txt)

Full log attached, I am seeing this error trying to run a custom dbt transformation

**Comment by pedroslopez** [comment]
@marcelopio Could you please provide the following?

1. Environment details
- **Deployment Environment**: e.g. docker, kubernetes
- **Source Connector and version**: (example Salesforce 0.2.3)
- **Destination Connector and version**: (example Postgres 0.3.3) 

2. Logs from the airbyte-bootloader on start up. There should be a set of logs relating to connector definition updates.
3. If you have the airbyte code checked out, the contents of `/airbyte-config/init/src/main/resources/seed/destination_definitions.yaml`

**Comment by marcelopio** [comment]
Found the error. We were the original developers for a source, and since it was in a future version, someone added it as a custom connector, but added the docker tag as "latest". The bootloader was trying to upgrade it, since it is from airbyte, but could not parse "latest", and so was not doing the migration. 

Since it is a very edge case I don't think we have a problem, it is all fixed now. Thanks!

Error message on bootloader:
```
airbyte-bootloader  | Exception in thread "main" java.lang.IllegalArgumentException: Invalid version string: latest
airbyte-bootloader  |   at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
airbyte-bootloader  |   at io.airbyte.commons.version.Version.<init>(Version.java:37)
airbyte-bootloader  |   at io.airbyte.commons.version.AirbyteVersion.<init>(AirbyteVersion.java:15)
airbyte-bootloader  |   at io.airbyte.config.persistence.ActorDefinitionMigrator.lambda$getConnectorRepositoryToInfoMap$3(ActorDefinitionMigrator.java:144)
airbyte-bootloader  |   at java.base/java.util.HashMap.merge(HashMap.java:1391)
airbyte-bootloader  |   at java.base/java.util.stream.Collectors.lambda$toMap$68(Collectors.java:1673)
airbyte-bootloader  |   at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
airbyte-bootloader  |   at java.base/java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:1003)
airbyte-bootloader  |   at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1921)
airbyte-bootloader  |   at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
airbyte-bootloader  |   at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
airbyte-bootloader  |   at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
airbyte-bootloader  |   at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
airbyte-bootloader  |   at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
airbyte-bootloader  |   at io.airbyte.config.persistence.ActorDefinitionMigrator.getConnectorRepositoryToInfoMap(ActorDefinitionMigrator.java:110)
airbyte-bootloader  |   at io.airbyte.config.persistence.ActorDefinitionMigrator.updateConfigsFromSeed(ActorDefinitionMigrator.java:77)
airbyte-bootloader  |   at io.airbyte.config.persistence.ActorDefinitionMigrator.lambda$migrate$0(ActorDefinitionMigrator.java:59)
airbyte-bootloader  |   at io.airbyte.db.Database.lambda$transaction$0(Database.java:27)
airbyte-bootloader  |   at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$0(DefaultDSLContext.java:564)
airbyte-bootloader  |   at org.jooq.impl.Tools$12$1.block(Tools.java:4926)
airbyte-bootloader  |   at java.base/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3744)
airbyte-bootloader  |   at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3689)
airbyte-bootloader  |   at org.jooq.impl.Tools$12.get(Tools.java:4923)
airbyte-bootloader  |   at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:616)
airbyte-bootloader  |   at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:533)
airbyte-bootloader  |   at io.airbyte.db.Database.transaction(Database.java:27)
airbyte-bootloader  |   at io.airbyte.db.ExceptionWrappingDatabase.transaction(ExceptionWrappingDatabase.java:31)
airbyte-bootloader  |   at io.airbyte.config.persistence.ActorDefinitionMigrator.migrate(ActorDefinitionMigrator.java:57)
airbyte-bootloader  |   at io.airbyte.config.persistence.ConfigRepository.seedActorDefinitions(ConfigRepository.java:1190)
airbyte-bootloader  |   at io.airbyte.config.init.ApplyDefinitionsHelper.apply(ApplyDefinitionsHelper.java:71)
airbyte-bootloader  |   at io.airbyte.config.init.ApplyDefinitionsHelper.apply(ApplyDefinitionsHelper.java:47)
airbyte-bootloader  |   at io.airbyte.bootloader.BootloaderApp.lambda$new$0(BootloaderApp.java:178)
airbyte-bootloader  |   at io.airbyte.bootloader.BootloaderApp.load(BootloaderApp.java:227)
airbyte-bootloader  |   at io.airbyte.bootloader.BootloaderApp.main(BootloaderApp.java:300)
```
