### ISSUE TITLE
Unable to use cursor fields whose name contains special characters

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2092]
## Expected Behavior
I expect to be able to run an incremental sync from my postgres DB when a column has `$` in its name. 

## Current Behavior
A user is having an issue when a cursor field for incremental refresh from a Postgres source contains a `$` in its name. The following exception is thrown in the sync: 

```
2021-02-17 01:58:51 ERROR (/tmp/workspace/65/0) LineGobbler(voidCall):69 - Exception in thread "main" java.lang.IllegalStateException: Could not find cursor field: id_ in schema for stream: public.users.
2021-02-17 01:58:51 ERROR (/tmp/workspace/65/0) LineGobbler(voidCall):69 - at io.airbyte.integrations.source.jdbc.IncrementalUtils.getCursorType(IncrementalUtils.java:49)
2021-02-17 01:58:51 ERROR (/tmp/workspace/65/0) LineGobbler(voidCall):69 - at io.airbyte.integrations.source.jdbc.AbstractJdbcSource.createReadStream(AbstractJdbcSource.java:214)
2021-02-17 01:58:51 ERROR (/tmp/workspace/65/0) LineGobbler(voidCall):69 - at io.airbyte.integrations.source.jdbc.AbstractJdbcSource.read(AbstractJdbcSource.java:176)
2021-02-17 01:58:51 ERROR (/tmp/workspace/65/0) LineGobbler(voidCall):69 - at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:103)
2021-02-17 01:58:51 ERROR (/tmp/workspace/65/0) LineGobbler(voidCall):69 - at io.airbyte.integrations.source.postgres.PostgresSource.main(PostgresSource.java:72)
```

## Steps to Reproduce
1. Create Postgres to Postgres sync where the source has a table `users(id$ int)`
1. Sync using `id$` as the cursor field
1. 💣 

## Severity of the bug for you
High - blocking the user from using airbyte

## Airbyte Version
0.14.3

**Comment by cgardens** [comment]
I think this has already been solved. See issue: https://github.com/airbytehq/airbyte/issues/2007. I'm looking and there is a test that covers the quoted identifier case [here](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-jdbc/src/testFixtures/java/io/airbyte/integrations/source/jdbc/test/JdbcSourceStandardTest.java#L361-L384). I have locally modified this test to use exactly the inputs described in this issue and the test still passes without failure. Let's reopen this if we run into it again.
