### ISSUE TITLE
Source Close.com - connector fails to synchronize large number of items

### ISSUE THREAD

**Issue by AnatolePledg** [airbytehq/airbyte#20959]
## Environment
- **Airbyte version**:  irrelevant
- **OS Version / Instance**: irrelevant
- **Deployment**: irrelevant
- **Source Connector and version**: [source-close-com](https://docs.airbyte.io/integrations/sources/close-com) 0.2.0
- **Destination Connector and version**: irrelevant
- **Step where error happened**: Initial Sync

## Current Behavior
It is not possible to synchronize the whole history of the Email Activities stream because Airbyte is making use of the `_skip` parameter of the API to paginate the results but it has an upper limit of 25000. So when the total number of items exceeds this number, the sync fails with below error :
````
"message":"Something went wrong in the connector. See the logs for more details.","internal_message":"Request to https://api.close.com/api/v1/activity/email/?_skip=250100&_limit=100&date_created__gt=2021-03-01T00%3A00%3A00Z&date_created__lte=2022-02-28T00%3A00%3A00Z failed with status code 400 and error message **The skip you set is larger than the maximum skip for this resource (max_skip = 250000)**.
Please refine your search query.","stack_trace":"Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 131, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 122, in run
    for message in generator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/manifest_declarative_source.py", line 112, in read
    yield from super().read(logger, config, catalog, state)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 125, in read
    raise e
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 111, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 180, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 243, in _read_incremental
    for message_counter, record_data_or_message in enumerate(records, start=1):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py", line 115, in read_records
    for record in self.retriever.read_records(sync_mode, cursor_field, stream_slice, stream_state):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 374, in read_records
    for record in records_generator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 430, in _read_pages
    yield from records_generator_fn(request, response, stream_state, stream_slice)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 415, in parse_records_and_emit_request_and_responses
    yield from self.parse_response(response, stream_slice=stream_slice, stream_state=stream_state)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 326, in parse_response
    raise ReadException(error_message)
````

## Expected Behavior
To iterate through a long list of results Close.com recommends to update the query so that fewer results are returned, for instance using the `date_created` field. Alternatively the Export API can be used.
It is fully explained here: https://developer.close.com/topics/pagination/#deep-pagination

## Are you willing to submit a PR?
Not at the moment

**Comment by topefolorunso** [comment]
You can assign this to me next @justinbchau

**Comment by anatolec** [comment]
Hey @topefolorunso,
Thanks for the fix.
Though, I am not sure how it works. How is the `date_created` field now used to split a big initial sync into several ones ?
I am asking because I am witnessing an issue where only a very small subset of the email activity stream is synced.
