### ISSUE TITLE
Source Amplitude: Enable events stream `time_interval` selection  

### ISSUE THREAD

**Issue by mariamthiam** [airbytehq/airbyte#21010]
## Tell us about the problem you're trying to solve
Currently event stream `time_interval` is hard coded in Amplitude source and set to 1 days, when we are using this stream we are getting   `MemoryError` with this stack trace :  

```   
 source > Encountered an exception while reading stream events
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 111, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 180, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 243, in _read_incremental
    for message_counter, record_data_or_message in enumerate(records, start=1):
  File "/airbyte/integration_code/source_amplitude/api.py", line 209, in read_records
    yield from records
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 412, in read_records
    yield from self._read_pages(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 428, in _read_pages
    request, response = self._fetch_next_page(stream_slice, stream_state, next_page_token)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 451, in _fetch_next_page
    response = self._send_request(request, request_kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 354, in _send_request
    return backoff_handler(user_backoff_handler)(request, request_kwargs)
  File "/usr/local/lib/python3.9/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 298, in _send
    response: requests.Response = self._session.send(request, **request_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 745, in send
    r.content
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
MemoryError
```
When we reduce the time interval to 5 hours it fix this issue.  
## Describe the solution you’d like
Enable for event stream `time_interval`  selection at source configuration level to be able to reduce or increase this value to each user use cases.  

## Describe the alternative you’ve considered or used
Modify the connector locally, use custom connector with docker image to extract Amplitude data without sharing. Non maintainable and not ideal solution

## Are you willing to submit a PR?
Yes I will open a PR

**Comment by artem1205** [comment]
Fixed in https://github.com/airbytehq/airbyte/pull/22362
