### ISSUE TITLE
Postgres destination fails on illegal newline character

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2108]
## Expected Behavior
A user reported via Slack that their are unable to sync data from Mysql to postgres. The connection fails with the following exception: 

```
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - Exception in thread "main" java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 	at java.base/java.lang.StringUTF16.compress(StringUTF16.java:161)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 	at java.base/java.lang.String.<init>(String.java:3651)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 	at java.base/java.lang.String.<init>(String.java:294)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 	at java.base/java.nio.HeapCharBuffer.toString(HeapCharBuffer.java:688)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 	at java.base/java.nio.CharBuffer.toString(CharBuffer.java:1626)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 	at java.base/java.util.regex.Matcher.toMatchResult(Matcher.java:274)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 	at java.base/java.util.Scanner.match(Scanner.java:1399)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 	at java.base/java.util.Scanner.hasNextLine(Scanner.java:1612)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 	at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:124)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:112)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 	at io.airbyte.integrations.destination.postgres.PostgresDestination.main(PostgresDestination.java:69)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 	Suppressed: java.lang.RuntimeException: java.lang.RuntimeException: com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 0)): only regular white space (\r, \n, \t) is allowed between tokens
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 -  at [Source: (String)"��������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������"[truncated 123 chars]; line: 1, column: 2]
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 		at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.writeStreamsWithNRecords(BufferedStreamConsumer.java:198)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 		at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.close(BufferedStreamConsumer.java:171)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 		at io.airbyte.integrations.base.FailureTrackingConsumer.close(FailureTrackingConsumer.java:65)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 		at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:122)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 		... 2 more
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 	Caused by: java.lang.RuntimeException: com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 0)): only regular white space (\r, \n, \t) is allowed between tokens
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 -  at [Source: (String)"��������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������"[truncated 123 chars]; line: 1, column: 2]
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 		at io.airbyte.commons.json.Jsons.deserialize(Jsons.java:63)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 		at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.lambda$writeStreamsWithNRecords$1(BufferedStreamConsumer.java:191)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 		at java.base/java.util.stream.SliceOps$1$1.accept(SliceOps.java:199)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 		at io.airbyte.commons.lang.Queues$1.tryAdvance(Queues.java:52)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 		at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 		at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 		at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 		at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 		at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.writeStreamsWithNRecords(BufferedStreamConsumer.java:192)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 		... 5 more
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 	Caused by: com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 0)): only regular white space (\r, \n, \t) is allowed between tokens
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 -  at [Source: (String)"��������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������"[truncated 123 chars]; line: 1, column: 2]
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 		at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 		at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 		at com.fasterxml.jackson.core.base.ParserMinimalBase._throwInvalidSpace(ParserMinimalBase.java:690)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 		at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd(ReaderBasedJsonParser.java:2372)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 		at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:671)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 		at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4356)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 		at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4205)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 		at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3214)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 		at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3182)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 		at io.airbyte.commons.json.Jsons.deserialize(Jsons.java:61)
2021-02-11 14:00:53 ERROR (/tmp/workspace/75/0) LineGobbler(voidCall):69 - 		... 17 more
```

[Logs](https://github.com/airbytehq/airbyte/files/5998047/logs-75-0.txt)

## Steps to Reproduce
1. Unkonwn yet

## Severity of the bug for you
High - blocks user from using airbyte

## Context
[slack thread](https://airbytehq.slack.com/archives/C01MFR03D5W/p1613035545186000?thread_ts=1613035489.185500&cid=C01MFR03D5W)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368214064382) by [Unito](https://www.unito.io)

**Comment by ChristopheDuong** [comment]
it seems related to https://github.com/airbytehq/airbyte/issues/1881

**Comment by cgardens** [comment]
It seems like this issue isn't actionable, should we close it? We can reopen it if we happen to reproduce it or if it gets reported again.
