### ISSUE TITLE
Unrecognized field "schema" (class io.airbyte.config.StandardSync), not marked as ignorable

### ISSUE THREAD

**Issue by ezg** [airbytehq/airbyte#2143]
I was playing around with airbyte locally through docker-compose.
Now I can't get it to start anymore, I keep getting the error below. localhost:8000 loads initially with loading animation, but then turns blank after a few seconds. 

Did I corrupt some local state? I see from the docker-compose file that `/tmp/airbyte_local` is used. Would removing that folder lead to a "clean" installation? Or are there other local folders where data is stored?

## Log
```
airbyte-scheduler | 2021-02-22 03:05:53 ERROR i.a.s.JobScheduler(run):86 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Job Scheduler Error
airbyte-scheduler | java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "schema" (class io.airbyte.config.StandardSync), not marked as ignorable (6 known properties: "status", "sourceId", "destinationId", "name", "connectionId", "catalog"])
airbyte-scheduler |  at [Source: (StringReader); line: 1, column: 188] (through reference chain: io.airbyte.config.StandardSync["schema"])
airbyte-scheduler | 	at io.airbyte.commons.json.Jsons.deserialize(Jsons.java:63) ~[io.airbyte-airbyte-commons-0.14.4-alpha.jar:?]
airbyte-scheduler | 	at io.airbyte.config.persistence.DefaultConfigPersistence.getConfigInternal(DefaultConfigPersistence.java:90) ~[io.airbyte.airbyte-config-persistence-0.14.4-alpha.jar:?]
airbyte-scheduler | 	at io.airbyte.config.persistence.DefaultConfigPersistence.getConfig(DefaultConfigPersistence.java:64) ~[io.airbyte.airbyte-config-persistence-0.14.4-alpha.jar:?]
airbyte-scheduler | 	at io.airbyte.config.persistence.DefaultConfigPersistence.listConfigsInternal(DefaultConfigPersistence.java:111) ~[io.airbyte.airbyte-config-persistence-0.14.4-alpha.jar:?]
airbyte-scheduler | 	at io.airbyte.config.persistence.DefaultConfigPersistence.listConfigs(DefaultConfigPersistence.java:71) ~[io.airbyte.airbyte-config-persistence-0.14.4-alpha.jar:?]
airbyte-scheduler | 	at io.airbyte.config.persistence.ConfigRepository.listStandardSyncs(ConfigRepository.java:157) ~[io.airbyte.airbyte-config-persistence-0.14.4-alpha.jar:?]
airbyte-scheduler | 	at io.airbyte.scheduler.JobScheduler.getAllActiveConnections(JobScheduler.java:115) ~[io.airbyte-airbyte-scheduler-0.14.4-alpha.jar:?]
airbyte-scheduler | 	at io.airbyte.scheduler.JobScheduler.scheduleSyncJobs(JobScheduler.java:92) ~[io.airbyte-airbyte-scheduler-0.14.4-alpha.jar:?]
airbyte-scheduler | 	at io.airbyte.scheduler.JobScheduler.run(JobScheduler.java:82) [io.airbyte-airbyte-scheduler-0.14.4-alpha.jar:?]
airbyte-scheduler | 	at io.airbyte.scheduler.SchedulerApp.lambda$start$0(SchedulerApp.java:112) [io.airbyte-airbyte-scheduler-0.14.4-alpha.jar:?]
airbyte-scheduler | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
airbyte-scheduler | 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
airbyte-scheduler | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
airbyte-scheduler | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
airbyte-scheduler | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
airbyte-scheduler | 	at java.lang.Thread.run(Thread.java:832) [?:?]
airbyte-scheduler | Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "schema" (class io.airbyte.config.StandardSync), not marked as ignorable (6 known properties: "status", "sourceId", "destinationId", "name", "connectionId", "catalog"])
```

## Airbyte Version
VERSION=0.14.4-alpha

**Comment by sherifnada** [comment]
@ezg this was probably caused by a backwards-incompatible update to Airbyte. Did you upgrade airbyte from a previous installation? if yes and you are okay losing your airbyte configuration, then you should run `docker-compose down -v` then `docker-compose up`. This will reset airbyte to "factory settings" but should fix this issue.

**Comment by ezg** [comment]
Sorry for the late response, but yes, that worked for me. Thanks!
