### ISSUE TITLE
RecursionError when using recursive JSON-Schema

### ISSUE THREAD

**Issue by mjstel** [airbytehq/airbyte#21452]
## Environment
- **Airbyte version**:  0.43.3
- **OS Version / Instance**: AWS EKS
- **Deployment**: Helm
- **Source Connector and version**: Custom Http Connector
- **Step where error happened**: Setup new connection

## Current Behavior
Hello airbyte community,
I build a custom Http Source to consume and API from another team at my company.
For this API they provide a JSON-Schema that uses `$ref` to reference other schemas.
I have an object called Topic which I put into the `shared/topic.json`, that look like this
#### **`topic.json`**
```json
{
  "type": "object",
  "additionalProperties": false,
  "properties": {
    ...
    "subtopics": {
      "type": "array",
      "items": {
        "$ref": "topic.json"
      }
    },
   ....
  },
  "required": [
   ....
  ]
}
```
As you can see the topic has subtopics which is itself an array of topics.
There is no Info of how deep this recursion goes in reality.

When I want to setup a connection with this source, it fails and in the logs of the Worker I see the following Exception:
`RecursionError: maximum recursion depth exceeded while calling a Python object`
Which most likely relates to the recursion I described.
When I looked up the [JSON-Schema doc](https://json-schema.org/understanding-json-schema/structuring.html#recursion), it says that recursion should be allowed.

## Expected Behavior
The recursion should be resolved properly and no RecursionError should be thrown.

## Logs

```
2023-01-16 09:35:49 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(create):97 - Reading messages from protocol version 0.2.0
Log4j2Appender says: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 131, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 116, in run
    catalog = self.source.discover(self.logger, config)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 70, in discover
    streams = [stream.as_airbyte_stream() for stream in self.streams(config=config)]
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 70, in <listcomp>
    streams = [stream.as_airbyte_stream() for stream in self.streams(config=config)]
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/core.py", line 124, in as_airbyte_stream
    stream = AirbyteStream(name=self.name, json_schema=dict(self.get_json_schema()), supported_sync_modes=[SyncMode.full_refresh])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/core.py", line 121, in get_json_schema
    return ResourceSchemaLoader(package_name_from_class(self.__class__)).get_schema(self.name)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 132, in get_schema
    return self._resolve_schema_references(raw_schema)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 145, in _resolve_schema_references
    resolved = resolve_ref_links(resolved)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 44, in resolve_ref_links
    obj = resolve_ref_links(obj.__subject__)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 50, in resolve_ref_links
    return {k: resolve_ref_links(v) for k, v in obj.items()}
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 50, in <dictcomp>
    return {k: resolve_ref_links(v) for k, v in obj.items()}
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 50, in resolve_ref_links
    return {k: resolve_ref_links(v) for k, v in obj.items()}
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 50, in <dictcomp>
    return {k: resolve_ref_links(v) for k, v in obj.items()}
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 50, in resolve_ref_links
    return {k: resolve_ref_links(v) for k, v in obj.items()}
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 50, in <dictcomp>
    return {k: resolve_ref_links(v) for k, v in obj.items()}
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 44, in resolve_ref_links
  
  <......>
  
 File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 50, in resolve_ref_links
    return {k: resolve_ref_links(v) for k, v in obj.items()}
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 50, in <dictcomp>
    return {k: resolve_ref_links(v) for k, v in obj.items()}
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 50, in resolve_ref_links
    return {k: resolve_ref_links(v) for k, v in obj.items()}
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 50, in <dictcomp>
    return {k: resolve_ref_links(v) for k, v in obj.items()}
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 50, in resolve_ref_links
    return {k: resolve_ref_links(v) for k, v in obj.items()}
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 50, in <dictcomp>
    return {k: resolve_ref_links(v) for k, v in obj.items()}
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 44, in resolve_ref_links
    obj = resolve_ref_links(obj.__subject__)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 50, in resolve_ref_links
    return {k: resolve_ref_links(v) for k, v in obj.items()}
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 50, in <dictcomp>
    return {k: resolve_ref_links(v) for k, v in obj.items()}
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 50, in resolve_ref_links
    return {k: resolve_ref_links(v) for k, v in obj.items()}
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 50, in <dictcomp>
    return {k: resolve_ref_links(v) for k, v in obj.items()}
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 50, in resolve_ref_links
    return {k: resolve_ref_links(v) for k, v in obj.items()}
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 50, in <dictcomp>
    return {k: resolve_ref_links(v) for k, v in obj.items()}
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 50, in resolve_ref_links
    return {k: resolve_ref_links(v) for k, v in obj.items()}
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 50, in <dictcomp>
    return {k: resolve_ref_links(v) for k, v in obj.items()}
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 50, in resolve_ref_links
    return {k: resolve_ref_links(v) for k, v in obj.items()}
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 50, in <dictcomp>
    return {k: resolve_ref_links(v) for k, v in obj.items()}
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 50, in resolve_ref_links
    return {k: resolve_ref_links(v) for k, v in obj.items()}
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 50, in <dictcomp>
    return {k: resolve_ref_links(v) for k, v in obj.items()}
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 44, in resolve_ref_links
    obj = resolve_ref_links(obj.__subject__)
  File "/usr/local/lib/python3.9/site-packages/proxytypes.py", line 164, in __getattribute__
    return _oga(self, attr)
  File "/usr/local/lib/python3.9/site-packages/proxytypes.py", line 119, in wrapper
    notproxied = _oga(self, "__notproxied__")
RecursionError: maximum recursion depth exceeded while calling a Python object
```
## Steps to Reproduce
1. Create an Http Source with a static JSON-Schema
2. In the JSON Schema add an object that has a `$ref` to the same schema.
3. Create a connection with a destination of your choice
4. Error on Schema Introspection.

## Are you willing to submit a PR?
It depends on what to do

**Comment by sherifnada** [comment]
@mjstel I think the CDK is behaving correctly. As in: the schema, as described in the sample you provided, is infinitely recursive, which _shouldn't_ actually work. There needs to be a limit somwhere. Is the API you're replicating from actually supporting infinite sub-topics?
