### ISSUE TITLE
Octavia-cli - DestinationDefinitionSpecificationRead has no attribute 'supports_normalization'

### ISSUE THREAD

**Issue by nzack** [airbytehq/airbyte#21818]
## Environment
- **Airbyte version**:  0.40.29
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Postgres 1.0.39
- **Destination Connector and version**: Snowflake 0.4.44
- **Step where error happened**: octavia import connection <ID>

## Current Behavior

When importing a connection I receive this error: `DestinationDefinitionSpecificationRead has no attribute 'supports_normalization' at ['['received_data']']['supports_normalization']`

This happened on an existing connection, so i created all new sources and destinations to retest, and the error still occurs.  This also happens for any of my existing connections using Snowflake as the destination (it's my only destination).  The get command for this connection does complete successfully.

$ octavia import connection c5b9d831-538b-464b-8410-a326435531f7
🐙 - Octavia is targetting your Airbyte instance running at http://localhost:8000 on workspace 4260f0a5-8400-4c86-b727-b5cb60801fb0.
Traceback (most recent call last):
  File "/usr/local/bin/octavia", line 8, in <module>
    sys.exit(octavia())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/base_commands.py", line 54, in invoke
    raise e
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/base_commands.py", line 51, in invoke
    result = super().invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/check_context.py", line 91, in wrapper
    f(ctx, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/_import/commands.py", line 156, in connection
    click.echo(import_connection(ctx.obj["API_CLIENT"], ctx.obj["WORKSPACE_ID"], resource))
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/_import/commands.py", line 120, in import_connection
    new_configuration_path = connection_renderer.import_configuration(".", remote_configuration)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/generate/renderers.py", line 314, in import_configuration
    rendered = self._render()
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/generate/renderers.py", line 301, in _render
    "supports_normalization": self.destination.definition.supports_normalization,
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 189, in __getattr__
    return self.__getitem__(attr)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 524, in __getitem__
    raise ApiAttributeError(
airbyte_api_client.exceptions.ApiAttributeError: DestinationDefinitionSpecificationRead has no attribute 'supports_normalization' at ['['received_data']']['supports_normalization']

## Expected Behavior
Import completes successfully.

## Steps to Reproduce
1. Create a new Connection using either an existing or new Snowflake configuration as the destination.
2. Run the octavia cli:  `octavia import connection <ID>`

## Are you willing to submit a PR?
Possibly, but this looks beyond my ability to troubleshoot and fix.

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by togidoto** [comment]
I know that Octavia is kinda dead, but i'm facing the same issue here still can't find any fix on github and Airbyte community. And i do think that get/import connection should be the basic functions of Octavia CLI.
