### ISSUE TITLE
Learn what went wrong with `allowedHosts` check on prod

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#21921]
allowedHosts checking caused some problems - https://github.com/airbytehq/oncall/issues/1373.  What happened?  We revered the check added in https://github.com/airbytehq/airbyte/pull/21676 via https://github.com/airbytehq/airbyte/pull/21923 which threw an error if a value that allowedHosts was missing from the connector's configuration.

Errors of this class looked like:
```
2023-01-26 08:22:27 WARN i.t.i.a.ActivityTaskExecutors$BaseActivityTaskExecutor(execute):114 - Activity failure. ActivityId=ba4a1133-acda-370f-aa5f-de5f5a10b908, activityType=GetSyncWorkflowInputWithAttemptNumber, attempt=1
io.airbyte.commons.temporal.exception.RetryableException: java.io.IOException: The allowed host value, '${host}', is expecting an interpolation value from the connector's configuration, but none is present
	at io.airbyte.workers.temporal.scheduling.activities.GenerateInputActivityImpl.getSyncWorkflowInput(GenerateInputActivityImpl.java:153) ~[io.airbyte-airbyte-workers-dev-e7cc086394.jar:?]
	at io.airbyte.workers.temporal.scheduling.activities.GenerateInputActivityImpl.getSyncWorkflowInputWithAttemptNumber(GenerateInputActivityImpl.java:161) ~[io.airbyte-airbyte-workers-dev-e7cc086394.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at io.temporal.internal.activity.RootActivityInboundCallsInterceptor$POJOActivityInboundCallsInterceptor.executeActivity(RootActivityInboundCallsInterceptor.java:64) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.activity.RootActivityInboundCallsInterceptor.execute(RootActivityInboundCallsInterceptor.java:43) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.activity.ActivityTaskExecutors$BaseActivityTaskExecutor.execute(ActivityTaskExecutors.java:95) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.activity.ActivityTaskHandlerImpl.handle(ActivityTaskHandlerImpl.java:92) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handleActivity(ActivityWorker.java:241) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:206) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:179) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93) ~[temporal-sdk-1.17.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.io.IOException: The allowed host value, '${host}', is expecting an interpolation value from the connector's configuration, but none is present
	at io.airbyte.workers.utils.ConfigReplacer.getAllowedHosts(ConfigReplacer.java:52) ~[io.airbyte-airbyte-workers-dev-e7cc086394.jar:?]
	at io.airbyte.workers.temporal.scheduling.activities.GenerateInputActivityImpl.getSyncWorkflowInput(GenerateInputActivityImpl.java:120) ~[io.airbyte-airbyte-workers-dev-e7cc086394.jar:?]
	... 14 more
```

**Comment by evantahler** [comment]
@benmoriceau I'm stuck on this one.  The workspaces in question in the on-call ticket do all have a value for "host" in the connector's config.  Is this a temporal pre-loading the data problem/

**Comment by evantahler** [comment]
Here's @jnr0790's workspace which reproduces the error https://cloud.airbyte.io/workspaces/1f571f36-8190-4c62-9a39-e7dce69f287b/connections/d3899d6b-0655-4530-b86e-7bddeb2ea5fe/status

**Comment by evantahler** [comment]
Current theory is that something is different between Docker and K8S implementations of a sync.  Docker syncs work OK...

**Comment by evantahler** [comment]
The problem is limited to resets! 
We change the config for reset syncs as we also change the container in use...
