### ISSUE TITLE
 Octavia not able to import the Bigquery destinations config

### ISSUE THREAD

**Issue by ni-jkhanna** [airbytehq/airbyte#21964]
## Environment
- **Airbyte version**:  example is 0.40.26
- **OS Version / Instance**: GCP GCE VM
- **Deployment**: Docker Compose
- **Destination Connector and version**: airbyte/destination-bigquery | 1.2.9
- **Step where error happened**: Importing configuration from Airbyte into Octavia

## Current Behavior
Not able to import the Bigquery destinations config using Octavia

## Expected Behavior
Octavia should be able to import Bigquery destinations.

## Logs
When running Octavia -

```
octavia import destination e3dd2a68-561e-46fc-a5b8-560bed72c0b8                                    
🐙 - Octavia is targetting your Airbyte instance running at http://host.docker.internal:8000 on workspace 0bba9860-2063-4c38-a2d7-4260dbc79a05.
Traceback (most recent call last):
  File "/usr/local/bin/octavia", line 8, in <module>
    sys.exit(octavia())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/base_commands.py", line 54, in invoke
    raise e
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/base_commands.py", line 51, in invoke
    result = super().invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/check_context.py", line 91, in wrapper
    f(ctx, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/_import/commands.py", line 148, in destination
    click.echo(import_source_or_destination(ctx.obj["API_CLIENT"], ctx.obj["WORKSPACE_ID"], UnmanagedDestination, resource))
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/_import/commands.py", line 58, in import_source_or_destination
    definition = definitions.factory(resource_type, api_client, workspace_id, remote_configuration[f"{resource_type}_definition_id"])
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/generate/definitions.py", line 148, in factory
    definition = DestinationDefinition(api_client, definition_id)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/generate/definitions.py", line 64, in __init__
    self._api_data = self._read()
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/generate/definitions.py", line 68, in _read
    return self._get_fn(self.api_instance, **self._get_fn_kwargs, **self.COMMON_GET_FUNCTION_KWARGS)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/api/destination_definition_api.py", line 782, in get_destination_definition
    return self.get_destination_definition_endpoint.call_with_http_info(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/api_client.py", line 849, in call_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/api_client.py", line 410, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/api_client.py", line 225, in __call_api
    return_data = self.deserialize(
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/api_client.py", line 326, in deserialize
    deserialized_data = validate_and_convert_types(
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 1570, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 1454, in attempt_convert_item
    return deserialize_model(input_value, valid_class,
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 1374, in deserialize_model
    return model_class._new_from_openapi_data(**kw_args)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 46, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 370, in _new_from_openapi_data
    return cls._from_openapi_data(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 46, in wrapped_init
    return fn(_self, *args, **kwargs)
TypeError: _from_openapi_data() missing 2 required positional arguments: 'supports_dbt' and 'normalization_config'
```

**Comment by marcosmarxm** [comment]
Thanks for reporting the issue @ni-jkhanna it's added to team backlog.
