### ISSUE TITLE
Source Jira: Issue stream sync failing 

### ISSUE THREAD

**Issue by anamargaridarl** [airbytehq/airbyte#22062]
## Environment
Airbyte version: 0.40.27
OS Version / Instance: AWS EC2
Deployment: Kubernetes
Source Connector and version: Jira 0.3.2
Step where error happened: Sync job

## Current Behavior
Issues stream fails
I think it might be a memory issue but would like an opinion on it

## Expected Behavior
Read data from the Issue stream 

## Logs

```
2023-01-27 17:41:24 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$readFromSrcAndWriteToDstRunnable$6):378 - Records read: 74000 (3 GB)
2023-01-27 17:43:14 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$readFromSrcAndWriteToDstRunnable$6):378 - Records read: 75000 (3 GB)
2023-01-27 17:43:58 [43mdestination[0m > Flushing buffer of stream AIRBYTE_JIRA_TEST__issues (200 MB)
2023-01-27 17:43:58 [43mdestination[0m > Flushing buffer for stream AIRBYTE_JIRA_TEST__issues (200 MB) to staging
2023-01-27 17:43:58 [43mdestination[0m > Wrapping up compression and write GZIP trailer data.
2023-01-27 17:43:58 [43mdestination[0m > Finished writing data to 0d3ca9c1-c09f-4f56-a1d7-4a3f5aa7b39f14561012586015002017.csv.gz (200 MB)
2023-01-27 17:44:04 [43mdestination[0m > closing connection
2023-01-27 17:44:04 [43mdestination[0m > Deleting tempFile data 0d3ca9c1-c09f-4f56-a1d7-4a3f5aa7b39f14561012586015002017.csv.gz
2023-01-27 17:44:04 [43mdestination[0m > Starting a new buffer for stream AIRBYTE_JIRA_TEST__issues (current state: -10802 bytes in 0 buffers)
2023-01-27 17:44:59 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$readFromSrcAndWriteToDstRunnable$6):378 - Records read: 76000 (3 GB)
2023-01-27 17:46:37 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$readFromSrcAndWriteToDstRunnable$6):378 - Records read: 77000 (3 GB)
2023-01-27 17:48:02 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$readFromSrcAndWriteToDstRunnable$6):378 - Records read: 78000 (3 GB)
2023-01-27 17:48:51 [44msource[0m > Killed
2023-01-27 17:48:52 [43mdestination[0m > Airbyte message consumer: succeeded.
2023-01-27 17:48:52 [43mdestination[0m > executing on success close procedure.
2023-01-27 17:48:52 [43mdestination[0m > Flushing all 1 current buffers (19 MB in total)
2023-01-27 17:48:52 [43mdestination[0m > Flushing buffer of stream AIRBYTE_JIRA_TEST__issues (19 MB)
2023-01-27 17:48:52 [43mdestination[0m > Flushing buffer for stream AIRBYTE_JIRA_TEST__issues (19 MB) to staging
2023-01-27 17:48:52 [43mdestination[0m > Wrapping up compression and write GZIP trailer data.
2023-01-27 17:48:52 [43mdestination[0m > Finished writing data to 765de9da-78d0-4811-b208-b6eb1bba9ce15122983249644409027.csv.gz (19 MB)
2023-01-27 17:48:53 [43mdestination[0m > closing connection
2023-01-27 17:48:53 [43mdestination[0m > Deleting tempFile data 765de9da-78d0-4811-b208-b6eb1bba9ce15122983249644409027.csv.gz
2023-01-27 17:48:53 [43mdestination[0m > Closing buffer for stream AIRBYTE_JIRA_TEST__issues
2023-01-27 17:48:53 [43mdestination[0m > Copying into tables in destination started for 1 streams
2023-01-27 17:48:53 [43mdestination[0m > Copying stream AIRBYTE_JIRA_TEST__issues of schema LANDING into tmp table _airbyte_tmp_dnb_AIRBYTE_JIRA_TEST__issues to final table _airbyte_raw_AIRBYTE_JIRA_TEST__issues from stage path 2023/01/27/16/628B3730-29F4-4A57-9AEA-1364885B1D54/ with 3 file(s) [b1b255f4-63cc-43f2-850e-17db190be30312818199422497317429.csv.gz,0d3ca9c1-c09f-4f56-a1d7-4a3f5aa7b39f14561012586015002017.csv.gz,765de9da-78d0-4811-b208-b6eb1bba9ce15122983249644409027.csv.gz]
2023-01-27 17:48:51 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$readFromSrcAndWriteToDstRunnable$6):381 - Source has no more messages, closing connection.
2023-01-27 17:48:52 [32mINFO[m i.a.w.p.KubePodProcess(close):721 - (pod: data / xxxx-5301-0-serki) - Closed all resources for pod
2023-01-27 17:49:52 [32mINFO[m i.a.w.p.KubePodProcess(destroy):653 - (pod: data / destination-snowflake-write-5301-0-crlux) - Destroying Kube process.
2023-01-27 17:49:52 [32mINFO[m i.a.w.p.KubePodProcess(close):721 - (pod: data / destination-snowflake-write-5301-0-crlux) - Closed all resources for pod
2023-01-27 17:49:52 [33mWARN[m i.a.c.i.LineGobbler(voidCall):119 - airbyte-destination gobbler IOException: Socket closed. Typically happens when cancelling a job.
2023-01-27 17:49:52 [32mINFO[m i.a.w.p.KubePodProcess(destroy):659 - (pod: data / destination-snowflake-write-5301-0-crlux) - Destroyed Kube process.
2023-01-27 17:49:52 [1;31mERROR[m i.a.w.g.DefaultReplicationWorker(replicate):255 - Sync worker failed.
java.util.concurrent.ExecutionException: io.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source cannot be stopped!
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.replicate(DefaultReplicationWorker.java:247) ~[io.airbyte-airbyte-commons-worker-0.40.27.jar:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:171) ~[io.airbyte-airbyte-commons-worker-0.40.27.jar:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:87) ~[io.airbyte-airbyte-commons-worker-0.40.27.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$5(TemporalAttemptExecution.java:195) ~[io.airbyte-airbyte-workers-0.40.27.jar:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
	Suppressed: io.airbyte.workers.exception.WorkerException: Source process exit with code 137. This warning is normal if the job was cancelled.
		at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:151) ~[io.airbyte-airbyte-commons-worker-0.40.27.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.replicate(DefaultReplicationWorker.java:192) ~[io.airbyte-airbyte-commons-worker-0.40.27.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:171) ~[io.airbyte-airbyte-commons-worker-0.40.27.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:87) ~[io.airbyte-airbyte-commons-worker-0.40.27.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$5(TemporalAttemptExecution.java:195) ~[io.airbyte-airbyte-workers-0.40.27.jar:?]
		at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: io.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source cannot be stopped!
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$6(DefaultReplicationWorker.java:385) ~[io.airbyte-airbyte-commons-worker-0.40.27.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	... 1 more
Caused by: io.airbyte.workers.exception.WorkerException: Source process exit with code 137. This warning is normal if the job was cancelled.
	at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:151) ~[io.airbyte-airbyte-commons-worker-0.40.27.jar:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$6(DefaultReplicationWorker.java:383) ~[io.airbyte-airbyte-commons-worker-0.40.27.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	... 1 more
2023-01-27 17:49:52 [32mINFO[m i.a.w.g.DefaultReplicationWorker(prepStateForLaterSaving):550 - Source did not output any state messages
2023-01-27 17:49:52 [33mWARN[m i.a.w.g.DefaultReplicationWorker(prepStateForLaterSaving):561 - State capture: No state retained.
2023-01-27 17:49:52 [32mINFO[m i.a.w.g.DefaultReplicationWorker(getReplicationOutput):481 - sync summary: {
```

## Steps to Reproduce
1. Activate Issue stream
2. Sync job
3.

## Are you willing to submit a PR?

Yes

**Comment by marcosmarxm** [comment]
@anamargaridarl can you upload the complete log file?

**Comment by marcosmarxm** [comment]
Maybe one possible solution is try the sync with a Docker deployment to validate the resource limitation.

**Comment by itsarraj** [comment]
Hello sir ,
I am new to open source contribution.
I already know java , my tech stacks & tools includes C, C++ , Python , Java, JavaScript , HTML , CSS , SQL , Bootstrap, ReactJS, ExpressJS, NodeJS & Git . I need a little help from your side to contribute to these amazing projects.

**Comment by anamargaridarl** [comment]
> @anamargaridarl can you upload the complete log file?

Here!
I ran it in our environment and checked that the failure happens when the memory allocation reaches the limit.

[e69fc9c7_639f_4413_aa94_2f4ebfe34871_logs_5326_txt.txt](https://github.com/airbytehq/airbyte/files/10555202/e69fc9c7_639f_4413_aa94_2f4ebfe34871_logs_5326_txt.txt)

**Comment by koconder** [comment]
@marcosmarxm i have some ideas on how we can better handle memory usage in the JIRA connector. I'll push a PR for review shortly. Assigning to myself

**Comment by koconder** [comment]
PR raised https://github.com/airbytehq/airbyte/pull/26816

**Comment by koconder** [comment]
Waiting for test/sandbox credentials so I can finalise PR

**Comment by jrolom** [comment]
@koconder do you have access to creds to finish this?

**Comment by darynaishchenko** [comment]
Created new issue: https://github.com/airbytehq/airbyte/issues/30342
