### ISSUE TITLE
`qa_checks.py` crashing in `/test` commands

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#22127]
From https://github.com/airbytehq/airbyte/actions/runs/4050865951/jobs/6968665380

```
Traceback (most recent call last):
  File "/actions-runner/_work/_tool/Python/3.9.16/x64/bin/run-qa-checks", line 33, in <module>
    sys.exit(load_entry_point('ci-connector-ops==0.1.10', 'console_scripts', 'run-qa-checks')())
  File "/actions-runner/_work/_tool/Python/3.9.16/x64/bin/run-qa-checks", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/actions-runner/_work/_tool/Python/3.9.16/x64/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/actions-runner/_work/_tool/Python/3.9.16/x64/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/actions-runner/_work/_tool/Python/3.9.16/x64/lib/python3.9/site-packages/ci_connector_ops/qa_checks.py", line 8, in <module>
    from ci_connector_ops.utils import Connector
  File "/actions-runner/_work/_tool/Python/3.9.16/x64/lib/python3.9/site-packages/ci_connector_ops/utils.py", line 19, in <module>
    AIRBYTE_REPO = git.Repo(".")
  File "/actions-runner/_work/_tool/Python/3.9.16/x64/lib/python3.9/site-packages/git/repo/base.py", line 282, in __init__
    self.working_dir: Optional[PathLike] = self._working_tree_dir or self.common_dir
  File "/actions-runner/_work/_tool/Python/3.9.16/x64/lib/python3.9/site-packages/git/repo/base.py", line 363, in common_dir
    raise InvalidGitRepositoryError()
git.exc.InvalidGitRepositoryError
```

One idea is that the `/test` command does a shallow clone, and perhaps we need the full git history?  We might not need the git utility here, so we might be able to skip the initialization of the git object entirely.

https://github.com/airbytehq/airbyte/blob/1f2b6d619b8b4a747d1c7239db32de60cc45fbbc/tools/ci_connector_ops/ci_connector_ops/utils.py#L19

**Comment by bechurch** [comment]
@evantahler I was just looking into this.

From what I can tell youre on the right track

Its likely due to the checkout action only taking the latest commit and running

https://github.com/actions/checkout

Putting up a PR right now to disable the QA-engine check

Afterwards we can decide how to tackle.

I imagine if we start pulling in the git history into every runner we might see a large increase in build time. Worth testing

**Comment by flash1293** [comment]
@erohmensing I think https://github.com/airbytehq/airbyte/pull/22131 fixed it for now

**Comment by erohmensing** [comment]
Ah right, okay. Thanks! Ignore me lol

**Comment by bechurch** [comment]
@erohmensing current work is being done here #22184
