### ISSUE TITLE
orchestrator job start failed when set METRIC_CLIENT=otel

### ISSUE THREAD

**Issue by gwny** [airbytehq/airbyte#22401]
## Environment
- **Airbyte version**:  0.40.30
- **OS Version / Instance**: AWS EKS 1.24
- **Deployment**: Kubernetes
- **Source Connector and version**: mysql 1.0.21
- **Destination Connector and version**: S3 0.3.19
- **Step where error happened**: Sync job

## Current Behavior
I have a connection which sync data from mysql to AWS S3, when set METRIC_CLIENT=otel, it sync failed, when set METRIC_CLIENT to empty, it sync successful.

## Expected Behavior
* When using otel to collect metrics, the connection still sync successfully.

## Logs
`
kubectl -n airbyte logs orchestrator-repl-job-26-attempt-0 

2023-02-06 07:06:03 replication-orchestrator > Setting up source...
Log4j2Appender says: Using default value for environment variable OTEL_COLLECTOR_ENDPOINT: ''
2023-02-06 07:06:04 replication-orchestrator > Using default value for environment variable OTEL_COLLECTOR_ENDPOINT: ''
Log4j2Appender says: Killing orchestrator because of an Exception
2023-02-06 07:06:05 ERROR i.a.c.Application(run):81 - Killing orchestrator because of an Exception
java.lang.IllegalArgumentException: Invalid endpoint, must start with http:// or https://: 
        at io.opentelemetry.exporter.internal.ExporterBuilderUtil.validateEndpoint(ExporterBuilderUtil.java:30) ~[opentelemetry-exporter-common-1.18.0.jar:1.18.0]
        at io.opentelemetry.exporter.internal.grpc.GrpcExporterBuilder.setEndpoint(GrpcExporterBuilder.java:96) ~[opentelemetry-exporter-common-1.18.0.jar:1.18.0]
        at io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporterBuilder.setEndpoint(OtlpGrpcSpanExporterBuilder.java:88) ~[opentelemetry-exporter-otlp-1.18.0.jar:1.18.0]
        at io.airbyte.metrics.lib.OpenTelemetryMetricClient.initialize(OpenTelemetryMetricClient.java:73) ~[io.airbyte.airbyte-metrics-metrics-lib-0.40.30.jar:?]
        at io.airbyte.metrics.lib.MetricClientFactory.initializeOpenTelemetryMetricClient(MetricClientFactory.java:135) ~[io.airbyte.airbyte-metrics-metrics-lib-0.40.30.jar:?]
        at io.airbyte.metrics.lib.MetricClientFactory.initialize(MetricClientFactory.java:71) ~[io.airbyte.airbyte-metrics-metrics-lib-0.40.30.jar:?]
        at io.airbyte.container_orchestrator.orchestrator.ReplicationJobOrchestrator.runJob(ReplicationJobOrchestrator.java:149) ~[io.airbyte-airbyte-container-orchestrator-0.40.30.jar:?]
        at io.airbyte.container_orchestrator.Application.run(Application.java:79) ~[io.airbyte-airbyte-container-orchestrator-0.40.30.jar:?]
        at io.airbyte.container_orchestrator.Application.main(Application.java:38) ~[io.airbyte-airbyte-container-orchestrator-0.40.30.jar:?]
Log4j2Appender says: Writing async status FAILED for KubePodInfo[namespace=airbyte, name=orchestrator-repl-job-26-attempt-0, mainContainerInfo=KubeContainerInfo[image=airbyte/container-orchestrator:0.40.30, pullPolicy=]]...
`

## Steps to Reproduce
1. set METRIC_CLIENT=otel and OTEL_COLLECTOR_ENDPOINT=http://otel-collector:4317 in .env.
2. create a connection on airbyte web ui.
3. sync the connection.

## Are you willing to submit a PR?
Yes, if I known the root cause of the problem.

## Extra Information
`
my .env config:
METRIC_CLIENT=otel
OTEL_COLLECTOR_ENDPOINT=http://otel-collector:4317

cmd：kubectl -n airbyte get pods
NAME                                               READY   STATUS    RESTARTS   AGE
airbyte-connector-builder-server-9b864d997-hvqb7   1/1     Running   0          172m
airbyte-cron-c55d6bfb9-wjnqx                       1/1     Running   0          172m
airbyte-metrics-65cf4b894-62kx2                    1/1     Running   0          172m
airbyte-minio-9f7dc754c-q64jg                      1/1     Running   0          172m
airbyte-pod-sweeper-78548959d8-vx55j               1/1     Running   0          172m
airbyte-server-769b798c5b-5j8qr                    1/1     Running   0          171m
airbyte-temporal-7dbc57f687-rng4v                  1/1     Running   0          171m
airbyte-webapp-7cd64ccdbf-kcqnz                    1/1     Running   0          171m
airbyte-worker-76d9c96668-lts4l                    1/1     Running   0          171m
orchestrator-repl-job-26-attempt-0                 0/1     Error     0          168m
orchestrator-repl-job-26-attempt-1                 0/1     Error     0          167m
orchestrator-repl-job-26-attempt-2                 0/1     Error     0          166m
otel-collector-6cc584496b-szkvk                    1/1     Running   0          170m

cmd: kubectl -n airbyte describe pod orchestrator-repl-job-26-attempt-0
Environment:
      PUBLISH_METRICS:                              false
      DD_AGENT_HOST:                                
      DD_DOGSTATSD_PORT:                            
      AIRBYTE_API_AUTH_HEADER_NAME:                 
      JAVA_OPTS:                                    
      AUTO_DETECT_SCHEMA:                           true
      MICRONAUT_ENVIRONMENTS:                       control-plane
      DATA_PLANE_SERVICE_ACCOUNT_CREDENTIALS_PATH:  
      AIRBYTE_API_AUTH_HEADER_VALUE:                
      USE_STREAM_CAPABLE_STATE:                     true
      FIELD_SELECTION_WORKSPACES:                   
      APPLY_FIELD_SELECTION:                        false
      DD_SERVICE:                                   airbyte-container-orchestrator
      METRIC_CLIENT:                                otel
      DATA_PLANE_SERVICE_ACCOUNT_EMAIL:             
      INTERNAL_API_HOST:                            airbyte-server-svc:8001
      CONTROL_PLANE_AUTH_ENDPOINT:                  
    Mounts:
      /config from airbyte-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-7tzhp (ro)
`
It looks like the orchestrator job pod lacks enviroment variables: OTEL_COLLECTOR_ENDPOINT
possibly related code: https://github.com/airbytehq/airbyte/blob/v0.40.30/airbyte-workers/src/main/java/io/airbyte/workers/config/ContainerOrchestratorConfigBeanFactory.java

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
