### ISSUE TITLE
Problem to generate yaml destination connectors

### ISSUE THREAD

**Issue by devscheffer** [airbytehq/airbyte#22478]
## Environment
- **Airbyte version**:  0.40.32
- **OS Version / Instance**: Ubuntu 22.04.1 LTS
- **Deployment**: Docker 
- **Source Connector and version**: OpenWeather 0.1.6
- **Destination Connector and version**: Postgres 0.3.26
- **Step where error happened**: Generate YAML

## Current Behavior
I'm trying to generate a destination file and I'm getting this error. However source generation is working fine.

## Expected Behavior
Generate the YAML for the postgre connection

## Logs
```shell
octavia --airbyte-url  http://localhost:8085 generate destination 471e5cab-8ed1-49f3-ba11-79c687784737 weather

🐙 - Octavia is targetting your Airbyte instance running at http://localhost:8085 on workspace 674819ad-bf1e-448c-905d-8ad9b0f3cc0c.
Traceback (most recent call last):
  File "/usr/local/bin/octavia", line 8, in <module>
    sys.exit(octavia())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/base_commands.py", line 54, in invoke
    raise e
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/base_commands.py", line 51, in invoke
    result = super().invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/generate/commands.py", line 42, in destination
    generate_source_or_destination("destination", ctx.obj["API_CLIENT"], ctx.obj["WORKSPACE_ID"], definition_id, resource_name)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/generate/commands.py", line 22, in generate_source_or_destination
    definition = definitions.factory(definition_type, api_client, workspace_id, definition_id)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/generate/definitions.py", line 148, in factory
    definition = DestinationDefinition(api_client, definition_id)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/generate/definitions.py", line 64, in __init__
    self._api_data = self._read()
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/generate/definitions.py", line 68, in _read
    return self._get_fn(self.api_instance, **self._get_fn_kwargs, **self.COMMON_GET_FUNCTION_KWARGS)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/api/destination_definition_api.py", line 782, in get_destination_definition
    return self.get_destination_definition_endpoint.call_with_http_info(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/api_client.py", line 849, in call_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/api_client.py", line 410, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/api_client.py", line 225, in __call_api
    return_data = self.deserialize(
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/api_client.py", line 326, in deserialize
    deserialized_data = validate_and_convert_types(
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 1570, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 1454, in attempt_convert_item
    return deserialize_model(input_value, valid_class,
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 1374, in deserialize_model
    return model_class._new_from_openapi_data(**kw_args)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 46, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 370, in _new_from_openapi_data
    return cls._from_openapi_data(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 46, in wrapped_init
    return fn(_self, *args, **kwargs)
TypeError: _from_openapi_data() missing 2 required positional arguments: 'supports_dbt' and 'normalization_config'
```

## Steps to Reproduce
1. octavia --airbyte-url  http://localhost:8085 generate destination 471e5cab-8ed1-49f3-ba11-79c687784737 weather

**Comment by tinomerl** [comment]
Running into the same issue. Sources can be generated just fine. Doesn't seem to be Postgres exclusive as i get the same error when trying with an E2E Testing destination. Running Octavia 0.40.32.

**Comment by mattppal** [comment]
Same issue here— present across all destinations (s3, redshift)

**Comment by lemantas** [comment]
Same issue here. Airbyte 0.40.7, Octavia 0.41.0, PostgreSQL destination adapter 0.3.26.
