### ISSUE TITLE
File source does not build in OSX

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#2267]
## Expected Behavior
It should build.

## Current Behavior
It does not. 

```
> Task :airbyte-integrations:connectors:source-file:installLocalReqs
[python] .venv/bin/python -m pip install -r requirements.txt
         Obtaining file:///Users/charles/code/airbyte/airbyte-integrations/bases/airbyte-protocol (from -r requirements.txt (line 1))
         Obtaining file:///Users/charles/code/airbyte/airbyte-integrations/bases/base-python (from -r requirements.txt (line 2))
         Obtaining file:///Users/charles/code/airbyte/airbyte-integrations/bases/base-python-test (from -r requirements.txt (line 3))
         Obtaining file:///Users/charles/code/airbyte/airbyte-integrations/connectors/source-file (from -r requirements.txt (line 4))
         Requirement already satisfied: pytest in ./.venv/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (6.1.2)
         Collecting boto3
           Using cached boto3-1.17.19-py2.py3-none-any.whl (130 kB)
         Processing /Users/charles/Library/Caches/pip/wheels/5e/03/1e/e1e954795d6f35dfc7b637fe2277bff021303bd9570ecea653/PyYAML-5.3.1-cp37-cp37m-macosx_11_0_x86_64.whl
         Collecting pydantic==1.6.1
           Using cached pydantic-1.6.1-py36.py37.py38-none-any.whl (99 kB)
         Collecting jsonschema==2.6.0
           Using cached jsonschema-2.6.0-py2.py3-none-any.whl (39 kB)
         Collecting gcsfs==0.7.1
           Using cached gcsfs-0.7.1-py2.py3-none-any.whl (20 kB)
         Processing /Users/charles/Library/Caches/pip/wheels/2e/34/be/0194d05d18bc4695b5c4969178790d535bdd23eabdb9d3b1e3/genson-1.2.2-py2.py3-none-any.whl
         Collecting google-cloud-storage==1.35.0
           Using cached google_cloud_storage-1.35.0-py2.py3-none-any.whl (96 kB)
         Collecting pandas==1.2.0
           Using cached pandas-1.2.0.tar.gz (5.4 MB)
           Installing build dependencies: started
           Installing build dependencies: finished with status 'done'
           Getting requirements to build wheel: started
           Getting requirements to build wheel: finished with status 'error'
           ERROR: Command errored out with exit status 1:
            command: /Users/charles/code/airbyte/airbyte-integrations/connectors/source-file/.venv/bin/python /Users/charles/code/airbyte/airbyte-integrations/connectors/source-file/.venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/t4/qppzg2nj6kl4z36pvz_czvr40000gn/T/tmp5bpr3_on
                cwd: /private/var/folders/t4/qppzg2nj6kl4z36pvz_czvr40000gn/T/pip-install-wkweo42j/pandas
           Complete output (22 lines):
           Traceback (most recent call last):
             File "/Users/charles/code/airbyte/airbyte-integrations/connectors/source-file/.venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
               main()
             File "/Users/charles/code/airbyte/airbyte-integrations/connectors/source-file/.venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
               json_out['return_val'] = hook(**hook_input['kwargs'])
             File "/Users/charles/code/airbyte/airbyte-integrations/connectors/source-file/.venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
               return hook(config_settings)
             File "/private/var/folders/t4/qppzg2nj6kl4z36pvz_czvr40000gn/T/pip-build-env-huohx0hq/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 150, in get_requires_for_build_wheel
               config_settings, requirements=['wheel'])
             File "/private/var/folders/t4/qppzg2nj6kl4z36pvz_czvr40000gn/T/pip-build-env-huohx0hq/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 130, in _get_build_requires
               self.run_setup()
             File "/private/var/folders/t4/qppzg2nj6kl4z36pvz_czvr40000gn/T/pip-build-env-huohx0hq/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 254, in run_setup
               self).run_setup(setup_script=setup_script)
             File "/private/var/folders/t4/qppzg2nj6kl4z36pvz_czvr40000gn/T/pip-build-env-huohx0hq/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 145, in run_setup
               exec(compile(code, __file__, 'exec'), locals())
             File "setup.py", line 438, in <module>
               LooseVersion(python_target) < "10.9"
             File "/usr/local/Cellar/python@3.7/3.7.9_3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/version.py", line 304, in __init__
               self.parse(vstring)
             File "/usr/local/Cellar/python@3.7/3.7.9_3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/version.py", line 312, in parse
               components = [x for x in self.component_re.split(vstring)
           TypeError: expected string or bytes-like object
           ----------------------------------------
         ERROR: Command errored out with exit status 1: /Users/charles/code/airbyte/airbyte-integrations/connectors/source-file/.venv/bin/python /Users/charles/code/airbyte/airbyte-integrations/connectors/source-file/.venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/t4/qppzg2nj6kl4z36pvz_czvr40000gn/T/tmp5bpr3_on Check the logs for full command output.
         WARNING: You are using pip version 20.2; however, version 21.0.1 is available.
         You should consider upgrading via the '/Users/charles/code/airbyte/airbyte-integrations/connectors/source-file/.venv/bin/python -m pip install --upgrade pip' command.
```

## Steps to Reproduce
1. ./gradlew :airbyte-integrations:connectors:source-file:clean
1. rm -rf airbyte-integrations/connectors/source-file/.venv/
1. rm -rf airbyte-integrations/connectors/source-file/.eggs
1. rm -rf airbyte-integrations/connectors/source-file/.pytest_cache
1. ./gradlew :airbyte-integrations:connectors:source-file:build

## Mac Version
11.2 (big sur)

## Airbyte Version
v0.15.0

## Connector Version (if applicable)
v0.1.10

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368092909062) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
Same failure when i just try to pip install manually

```
➜  airbyte git:(cgardens/worker_run_assembly) ✗ pip install pandas==1.2.0
Collecting pandas==1.2.0
  Using cached pandas-1.2.0.tar.gz (5.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.7/bin/python3.7 /Users/charles/Library/Python/3.7/lib/python/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/t4/qppzg2nj6kl4z36pvz_czvr40000gn/T/tmpsufn14cp
       cwd: /private/var/folders/t4/qppzg2nj6kl4z36pvz_czvr40000gn/T/pip-install-x8u4n8ai/pandas
  Complete output (22 lines):
  Traceback (most recent call last):
    File "/Users/charles/Library/Python/3.7/lib/python/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/Users/charles/Library/Python/3.7/lib/python/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/charles/Library/Python/3.7/lib/python/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/private/var/folders/t4/qppzg2nj6kl4z36pvz_czvr40000gn/T/pip-build-env-vuu58o3b/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 150, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/private/var/folders/t4/qppzg2nj6kl4z36pvz_czvr40000gn/T/pip-build-env-vuu58o3b/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "/private/var/folders/t4/qppzg2nj6kl4z36pvz_czvr40000gn/T/pip-build-env-vuu58o3b/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 254, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/private/var/folders/t4/qppzg2nj6kl4z36pvz_czvr40000gn/T/pip-build-env-vuu58o3b/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 438, in <module>
      LooseVersion(python_target) < "10.9"
    File "/usr/local/Cellar/python@3.7/3.7.9_3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/version.py", line 304, in __init__
      self.parse(vstring)
    File "/usr/local/Cellar/python@3.7/3.7.9_3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/version.py", line 312, in parse
      components = [x for x in self.component_re.split(vstring)
  TypeError: expected string or bytes-like object
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python@3.7/bin/python3.7 /Users/charles/Library/Python/3.7/lib/python/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/t4/qppzg2nj6kl4z36pvz_czvr40000gn/T/tmpsufn14cp Check the logs for full command output.
WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
You should consider upgrading via the '/usr/local/opt/python@3.7/bin/python3.7 -m pip install --upgrade pip' command.
```

**Comment by davinchia** [comment]
File Source is also erroring out for me on Big Sur, but with a different error:
```

           creating build/bdist.macosx-11.2-x86_64
           creating build/bdist.macosx-11.2-x86_64/wheel
           creating build/bdist.macosx-11.2-x86_64/wheel/pyarrow
           copying build/lib.macosx-11.2-x86_64-3.7/pyarrow/public-api.pxi -> build/bdist.macosx-11.2-x86_64/wheel/pyarrow
           copying build/lib.macosx-11.2-x86_64-3.7/pyarrow/io.pxi -> build/bdist.macosx-11.2-x86_64/wheel/pyarrow
           copying build/lib.macosx-11.2-x86_64-3.7/pyarrow/serialization.pxi -> build/bdist.macosx-11.2-x86_64/wheel/pyarrow
           copying build/lib.macosx-11.2-x86_64-3.7/pyarrow/orc.py -> build/bdist.macosx-11.2-x86_64/wheel/pyarrow
           copying build/lib.macosx-11.2-x86_64-3.7/pyarrow/_compute.pyx -> build/bdist.macosx-11.2-x86_64/wheel/pyarrow
           copying build/lib.macosx-11.2-x86_64-3.7/pyarrow/_orc.pxd -> build/bdist.macosx-11.2-x86_64/wheel/pyarrow
           copying build/lib.macosx-11.2-x86_64-3.7/pyarrow/builder.pxi -> build/bdist.macosx-11.2-x86_64/wheel/pyarrow
           copying build/lib.macosx-11.2-x86_64-3.7/pyarrow/array.pxi -> build/bdist.macosx-11.2-x86_64/wheel/pyarrow
           copying build/lib.macosx-11.2-x86_64-3.7/pyarrow/_generated_version.py -> build/bdist.macosx-11.2-x86_64/wheel/pyarrow
           copying build/lib.macosx-11.2-x86_64-3.7/pyarrow/compat.py -> build/bdist.macosx-11.2-x86_64/wheel/pyarrow
           copying build/lib.macosx-11.2-x86_64-3.7/pyarrow/_cuda.pyx -> build/bdist.macosx-11.2-x86_64/wheel/pyarrow
           copying build/lib.macosx-11.2-x86_64-3.7/pyarrow/_csv.cpython-37m-darwin.so -> build/bdist.macosx-11.2-x86_64/wheel/pyarrow
           copying build/lib.macosx-11.2-x86_64-3.7/pyarrow/benchmark.py -> build/bdist.macosx-11.2-x86_64/wheel/pyarrow
           copying build/lib.macosx-11.2-x86_64-3.7/pyarrow/parquet.py -> build/bdist.macosx-11.2-x86_64/wheel/pyarrow
           copying build/lib.macosx-11.2-x86_64-3.7/pyarrow/_fs.cpython-37m-darwin.so -> build/bdist.macosx-11.2-x86_64/wheel/pyarrow
           copying build/lib.macosx-11.2-x86_64-3.7/pyarrow/_csv.pyx -> build/bdist.macosx-11.2-x86_64/wheel/pyarrow
           copying build/lib.macosx-11.2-x86_64-3.7/pyarrow/config.pxi -> build/bdist.macosx-11.2-x86_64/wheel/pyarrow
           copying build/lib.macosx-11.2-x86_64-3.7/pyarrow/_dataset.pyx -> build/bdist.macosx-11.2-x86_64/wheel/pyarrow
           copying build/lib.macosx-11.2-x86_64-3.7/pyarrow/_flight.pyx -> build/bdist.macosx-11.2-x86_64/wheel/pyarrow
           copying build/lib.macosx-11.2-x86_64-3.7/pyarrow/ipc.py -> build/bdist.macosx-11.2-x86_64/wheel/pyarrow
           copying build/lib.macosx-11.2-x86_64-3.7/pyarrow/util.py -> build/bdist.macosx-11.2-x86_64/wheel/pyarrow
           copying build/lib.macosx-11.2-x86_64-3.7/pyarrow/flight.py -> build/bdist.macosx-11.2-x86_64/wheel/pyarrow
           copying build/lib.macosx-11.2-x86_64-3.7/pyarrow/tensor.pxi -> build/bdist.macosx-11.2-x86_64/wheel/pyarrow
           copying build/lib.macosx-11.2-x86_64-3.7/pyarrow/__init__.pxd -> build/bdist.macosx-11.2-x86_64/wheel/pyarrow
           copying build/lib.macosx-11.2-x86_64-3.7/pyarrow/lib.cpython-37m-darwin.so -> build/bdist.macosx-11.2-x86_64/wheel/pyarrow
           copying build/lib.macosx-11.2-x86_64-3.7/pyarrow/cffi.py -> build/bdist.macosx-11.2-x86_64/wheel/pyarrow
           creating build/bdist.macosx-11.2-x86_64/wheel/pyarrow/include
           error: can't copy 'build/lib.macosx-11.2-x86_64-3.7/pyarrow/include/arrow': doesn't exist or not a regular file
           ----------------------------------------
           ERROR: Failed building wheel for pyarrow
         ERROR: Could not build wheels for pyarrow which use PEP 517 and cannot be installed directly
         WARNING: You are using pip version 20.2; however, version 21.0.1 is available.
         You should consider upgrading via the '/Users/davinchia/code/airbyte/airbyte-integrations/connectors/source-file/.venv/bin/python -m pip install --upgrade pip' command.
```

**Comment by gordalina** [comment]
I have a similar issue: https://gist.github.com/gordalina/39915a946816fb6b4456fe77197d8c8b

**Comment by gordalina** [comment]
From a clean OS 11.2 installation i had to have these run before running build until I hit the error @davinchia mentioned:

```
brew install rust apache-arrow

export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CPPFLAGS="-I/usr/local/opt/openssl/include"
export OPENSSL_ROOT_DIR="/usr/local/opt/openssl"
export OPENSSL_LIBRARIES="/usr/local/opt/openssl/lib"
```
