### ISSUE TITLE
Job pod init container times out on EKS

### ISSUE THREAD

**Issue by olivermeyer** [airbytehq/airbyte#22907]
## Environment
- **Airbyte version**: 0.40.32
- **Deployment**: Kubernetes (EKS)
- **Step where error happened**: Sync job

## Current Behavior
Some of our syncs are failing because the init container in the job pod times out. The logs for the init container just show `Timeout while attempting to copy to init container, exiting with code 1...` which was introduced by [this commit](https://github.com/airbytehq/airbyte/pull/10592/files#diff-9c6752fe44b24cd937f905d5edf2be25ce430dda6be7e91d4c5adcb1abd0f083R28).

From our observations, this doesn't happen when the job pod runs on an existing node. The problem occurs when existing nodes are busy, and a new node is provisioned to run the job pod. A 1-minute timeout doesn't seem to be long enough.

A fairly simple solution could be to expose the `INIT_RETRY_TIMEOUT_MINUTES` in the chart and allow users to increase it if needed.

## Expected Behavior
The init container should not time out.

## Logs
From the UI:
```
2023-02-13 12:26:16 ERROR i.a.w.g.DefaultReplicationWorker(replicate):259 - Sync worker failed.
io.airbyte.workers.exception.WorkerException: java.io.IOException: kubectl cp failed with exit code 1
	at io.airbyte.workers.process.KubeProcessFactory.create(KubeProcessFactory.java:143) ~[io.airbyte-airbyte-commons-worker-0.40.32.jar:?]
	at io.airbyte.workers.process.AirbyteIntegrationLauncher.read(AirbyteIntegrationLauncher.java:170) ~[io.airbyte-airbyte-commons-worker-0.40.32.jar:?]
	at io.airbyte.workers.internal.DefaultAirbyteSource.start(DefaultAirbyteSource.java:93) ~[io.airbyte-airbyte-commons-worker-0.40.32.jar:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.replicate(DefaultReplicationWorker.java:199) ~[io.airbyte-airbyte-commons-worker-0.40.32.jar:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:175) ~[io.airbyte-airbyte-commons-worker-0.40.32.jar:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:91) ~[io.airbyte-airbyte-commons-worker-0.40.32.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$5(TemporalAttemptExecution.java:195) ~[io.airbyte-airbyte-workers-0.40.32.jar:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.RuntimeException: java.io.IOException: kubectl cp failed with exit code 1
	at io.airbyte.workers.process.KubePodProcess.copyFilesToKubeConfigVolume(KubePodProcess.java:289) ~[io.airbyte-airbyte-commons-worker-0.40.32.jar:?]
```
From the init container logs:
```
Timeout while attempting to copy to init container, exiting with code 1...
```

## Are you willing to submit a PR?
No

**Comment by marcosmarxm** [comment]
@olivermeyer are you running Airbyte using Helm? I think the suggestion is valuable. I don't have much context about the change and why the variable isn't exposed.

@pmossman tagging you because maybe has more context and can give some opinion.

**Comment by olivermeyer** [comment]
> @olivermeyer are you running Airbyte using Helm? I think the suggestion is valuable. I don't have much context about the change and why the variable isn't exposed.

That's right, we're using the official Helm chart.

We're still observing this every day, and the pattern is super consistent: the jobs get scheduled on a new node, the first attempt fails with this timeout error, and the second attempt succeeds (on the same node). I'm fairly confident that increasing this timeout would fix it.

**Comment by pmossman** [comment]
@marcosmarxm  I agree that exposing the timeout as a variable would be valuable here. @olivermeyer since the 2nd attempt succeeds consistently, this issue isn't a hard blocker for you, correct? Of course it would be nice to avoid failures in general, but the attempt retry mechanism seems to be doing its job here at least!

**Comment by olivermeyer** [comment]
> @marcosmarxm I agree that exposing the timeout as a variable would be valuable here. @olivermeyer since the 2nd attempt succeeds consistently, this issue isn't a hard blocker for you, correct? Of course it would be nice to avoid failures in general, but the attempt retry mechanism seems to be doing its job here at least!

Yep we can get around it by relying on the retries. Just saw your PR to increase the timeout to 5 minutes, that's good enough for us for now!

**Comment by pmossman** [comment]
@olivermeyer we actually started experiencing the same issue on our own AWS cluster so the naive increase to 5 minutes felt like the path of least resistance for everyone involved 😅 

We will likely work on a more elegant fix in the longer term but hopefully the 5 minute increase works as a short term band-aid for you as well!

**Comment by rootindex** [comment]
+1 

I am stuck with a similar situation where the config takes over 60 seconds to copy, it times out and the orchestrator fails as a result. Because this job gets created by generator I can not control this timeout.

```
Command:
      sh
      -c
      i=0
      until [ $i -gt 60 ]
      do
        echo "$i - waiting for config file transfer to complete..."
        # check if the upload-complete file exists, if so exit without error
        if [ -f "/config/FINISHED_UPLOADING" ]; then
          exit 0
        fi
        i=$((i+1))
        sleep 1
      done
      echo "config files did not transfer in time"
      # no upload-complete file was created in time, exit with error
      exit 1
``` 

```
55 - waiting for config file transfer to complete...
2024-03-14T22:29:25.908236920+01:00 56 - waiting for config file transfer to complete...
57 - waiting for config file transfer to complete...
2024-03-14T22:29:27.910415600+01:00 58 - waiting for config file transfer to complete...
59 - waiting for config file transfer to complete...
2024-03-14T22:29:29.912513097+01:00 60 - waiting for config file transfer to complete...
config files did not transfer in time
```

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
