### ISSUE TITLE
Upgrading Airbyte from version 0.39.10-alpha to new version fails

### ISSUE THREAD

**Issue by vasuenduri** [airbytehq/airbyte#22976]
## Environment
- **Airbyte version**:  0.43.22
- **OS Version / Instance**: AWS EC2
- **Deployment**: Kubernetes deploy env
- **Step where error happened**:  Upgrade Airbyte

## Current Behavior
*After trying to upgrade Aibyte from 0.39.10-alpha to 0.43.22, Airbyte bootloader pod won't start.*

## Expected Behavior
*Airbyte should start with no problems.*

## Logs
Log
*
2023-02-14 07:12:54 WARN i.a.d.c.DatabaseAvailabilityCheck(check):38 - Waiting for database to become available...
2023-02-14 07:12:54 INFO i.a.d.c.DatabaseAvailabilityCheck(lambda$isDatabaseConnected$1):75 - Testing airbyte jobs database connection...
2023-02-14 07:12:54 INFO i.a.d.c.DatabaseAvailabilityCheck(check):57 - Database available.
2023-02-14 07:12:54 INFO i.a.d.i.DatabaseInitializer(initializeSchema):90 - The airbyte jobs database is initialized
2023-02-14 07:12:54 INFO i.a.b.Bootloader(initializeDatabases):201 - Databases initialized.
2023-02-14 07:12:54 INFO i.a.b.Bootloader(load):103 - Checking migration compatibility...
2023-02-14 07:12:54 INFO i.a.b.Bootloader(assertNonBreakingMigration):135 - Checking for illegal upgrade...
2023-02-14 07:12:54 INFO i.a.b.Bootloader(isLegalUpgrade):208 - No previous Airbyte Version set.
2023-02-14 07:12:54 INFO i.a.b.Bootloader(load):106 - Checking protocol version constraints...
2023-02-14 07:12:54 INFO i.a.b.ProtocolVersionChecker(validate):82 - No previous version of Airbyte detected, assuming this is a fresh deploy.
2023-02-14 07:12:54 INFO i.a.b.Bootloader(trackProtocolVersion):241 - AirbyteProtocol version support range: [0.0.0:1.0.0]
2023-02-14 07:12:54 INFO i.a.b.Bootloader(load):109 - Running database migrations...
2023-02-14 07:12:54 INFO i.a.b.Bootloader(runFlywayMigration):222 - Creating baseline for config database...
2023-02-14 07:12:54 INFO o.f.c.i.l.s.Slf4jLog(info):49 - Flyway Community Edition 7.14.0 by Redgate
2023-02-14 07:12:54 INFO o.f.c.i.l.s.Slf4jLog(info):49 - Database: jdbc:postgresql://crm-preprod-airbyte.cfajfvu1ed2i.us-east-1.rds.amazonaws.com:5432/airbyte (PostgreSQL 11.16)
2023-02-14 07:12:54 INFO o.f.c.i.l.s.Slf4jLog(info):49 - Schema history table "public"."airbyte_configs_migrations" already initialized with (0.29.0.001,Baseline from file-based migration v1). Skipping.
2023-02-14 07:12:54 INFO i.a.b.Bootloader(runFlywayMigration):224 - Creating baseline for job database...
2023-02-14 07:12:54 INFO o.f.c.i.l.s.Slf4jLog(info):49 - Flyway Community Edition 7.14.0 by Redgate
2023-02-14 07:12:54 INFO o.f.c.i.l.s.Slf4jLog(info):49 - Database: jdbc:postgresql://crm-preprod-airbyte.cfajfvu1ed2i.us-east-1.rds.amazonaws.com:5432/airbyte (PostgreSQL 11.16)
2023-02-14 07:12:54 INFO o.f.c.i.l.s.Slf4jLog(info):49 - Schema history table "public"."airbyte_jobs_migrations" already initialized with (0.29.0.001,Baseline from file-based migration v1). Skipping.
2023-02-14 07:12:54 INFO i.a.b.Bootloader(runFlywayMigration):228 - Migrating configs database...
2023-02-14 07:12:54 INFO o.f.c.i.l.s.Slf4jLog(info):49 - Flyway Community Edition 7.14.0 by Redgate
2023-02-14 07:12:54 INFO o.f.c.i.l.s.Slf4jLog(info):49 - Successfully validated 35 migrations (execution time 00:00.021s)
2023-02-14 07:12:54 INFO o.f.c.i.l.s.Slf4jLog(info):49 - Current version of schema "public": 0.40.11.002
2023-02-14 07:12:54 INFO o.f.c.i.l.s.Slf4jLog(info):49 - Migrating schema "public" to version "0.40.12.001 - AddWebhookOperationColumns"
2023-02-14 07:12:54 INFO i.a.d.i.c.m.V0_40_12_001__AddWebhookOperationColumns(migrate):22 - Running migration: V0_40_12_001__AddWebhookOperationColumns
2023-02-14 07:12:54 ERROR o.f.c.i.l.s.Slf4jLog(error):57 - Migration of schema "public" to version "0.40.12.001 - AddWebhookOperationColumns" failed! Changes successfully rolled back.
2023-02-14 07:12:54 ERROR i.a.b.Application(main):25 - Unable to bootstrap Airbyte environment.
org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: Migration failed !
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:378) ~[flyway-core-7.14.0.jar:?]
	at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:271) ~[flyway-core-7.14.0.jar:?]
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66) ~[flyway-core-7.14.0.jar:?]
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:270) ~[flyway-core-7.14.0.jar:?]
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:243) ~[flyway-core-7.14.0.jar:?]
	at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:141) ~[flyway-core-7.14.0.jar:?]
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:70) ~[flyway-core-7.14.0.jar:?]
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:99) ~[flyway-core-7.14.0.jar:?]
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:141) ~[flyway-core-7.14.0.jar:?]
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:141) ~[flyway-core-7.14.0.jar:?]
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:101) ~[flyway-core-7.14.0.jar:?]
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:217) ~[flyway-core-7.14.0.jar:?]
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:168) ~[flyway-core-7.14.0.jar:?]
	at org.flywaydb.core.Flyway.execute(Flyway.java:584) ~[flyway-core-7.14.0.jar:?]
	at org.flywaydb.core.Flyway.migrate(Flyway.java:168) ~[flyway-core-7.14.0.jar:?]
	at io.airbyte.db.instance.FlywayDatabaseMigrator.migrate(FlywayDatabaseMigrator.java:36) ~[io.airbyte.airbyte-db-db-lib-0.40.32.jar:?]
	at io.airbyte.bootloader.Bootloader.runFlywayMigration(Bootloader.java:229) ~[io.airbyte-airbyte-bootloader-0.40.32.jar:?]
	at io.airbyte.bootloader.Bootloader.load(Bootloader.java:110) ~[io.airbyte-airbyte-bootloader-0.40.32.jar:?]
	at io.airbyte.bootloader.Application.main(Application.java:22) ~[io.airbyte-airbyte-bootloader-0.40.32.jar:?]
Caused by: org.flywaydb.core.api.FlywayException: Migration failed !
	at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.executeOnce(JavaMigrationExecutor.java:75) ~[flyway-core-7.14.0.jar:?]
	at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.lambda$execute$0(JavaMigrationExecutor.java:54) ~[flyway-core-7.14.0.jar:?]
	at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27) ~[flyway-core-7.14.0.jar:?]
	at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.execute(JavaMigrationExecutor.java:53) ~[flyway-core-7.14.0.jar:?]
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:370) ~[flyway-core-7.14.0.jar:?]
	... 18 more
Caused by: org.jooq.exception.DataAccessException: SQL [alter type "operator_type" add value 'webhook']; ERROR: ALTER TYPE ... ADD cannot run inside a transaction block
	at org.jooq_3.13.4.POSTGRES.debug(Unknown Source) ~[?:?]
	at org.jooq.impl.Tools.translate(Tools.java:2753) ~[jooq-3.13.4.jar:?]
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:755) ~[jooq-3.13.4.jar:?]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:385) ~[jooq-3.13.4.jar:?]
	at io.airbyte.db.instance.configs.migrations.V0_40_12_001__AddWebhookOperationColumns.addWebhookOperationType(V0_40_12_001__AddWebhookOperationColumns.java:42) ~[io.airbyte.airbyte-db-db-lib-0.40.32.jar:?]
	at io.airbyte.db.instance.configs.migrations.V0_40_12_001__AddWebhookOperationColumns.migrate(V0_40_12_001__AddWebhookOperationColumns.java:29) ~[io.airbyte.airbyte-db-db-lib-0.40.32.jar:?]
	at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.executeOnce(JavaMigrationExecutor.java:61) ~[flyway-core-7.14.0.jar:?]
	at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.lambda$execute$0(JavaMigrationExecutor.java:54) ~[flyway-core-7.14.0.jar:?]
	at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27) ~[flyway-core-7.14.0.jar:?]
	at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.execute(JavaMigrationExecutor.java:53) ~[flyway-core-7.14.0.jar:?]
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:370) ~[flyway-core-7.14.0.jar:?]
	... 18 more
Caused by: org.postgresql.util.PSQLException: ERROR: ALTER TYPE ... ADD cannot run inside a transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676) ~[postgresql-42.5.0.jar:42.5.0]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366) ~[postgresql-42.5.0.jar:42.5.0]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356) ~[postgresql-42.5.0.jar:42.5.0]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496) ~[postgresql-42.5.0.jar:42.5.0]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413) ~[postgresql-42.5.0.jar:42.5.0]
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190) ~[postgresql-42.5.0.jar:42.5.0]
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:177) ~[postgresql-42.5.0.jar:42.5.0]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[HikariCP-5.0.1.jar:?]
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209) ~[jooq-3.13.4.jar:?]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:453) ~[jooq-3.13.4.jar:?]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:371) ~[jooq-3.13.4.jar:?]
	at io.airbyte.db.instance.configs.migrations.V0_40_12_001__AddWebhookOperationColumns.addWebhookOperationType(V0_40_12_001__AddWebhookOperationColumns.java:42) ~[io.airbyte.airbyte-db-db-lib-0.40.32.jar:?]
	at io.airbyte.db.instance.configs.migrations.V0_40_12_001__AddWebhookOperationColumns.migrate(V0_40_12_001__AddWebhookOperationColumns.java:29) ~[io.airbyte.airbyte-db-db-lib-0.40.32.jar:?]
	at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.executeOnce(JavaMigrationExecutor.java:61) ~[flyway-core-7.14.0.jar:?]
	at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.lambda$execute$0(JavaMigrationExecutor.java:54) ~[flyway-core-7.14.0.jar:?]
	at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27) ~[flyway-core-7.14.0.jar:?]
	at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.execute(JavaMigrationExecutor.java:53) ~[flyway-core-7.14.0.jar:?]
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:370) ~[flyway-core-7.14.0.jar:?]
*

## Steps to Reproduce
1.Upgrade Airbyte from 0.39.10-alpha to 0.43.22

**Comment by sajarin** [comment]
@vasuenduri are you still facing this issue? What happens when you upgrade to a new version of Airbyte?

**Comment by voroninman** [comment]
This worked for me https://github.com/airbytehq/airbyte/issues/18217#issuecomment-1500722430

**Comment by nataliekwong** [comment]
Hey there, since it's been a while since the last comment, and it appears there is a resolution, I will go ahead and close this issue.
