### ISSUE TITLE
Hitting the logs api results in an internal server error.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#2303]
## Expected Behavior
Logs should be returned as per https://petstore.swagger.io/?url=https://raw.githubusercontent.com/airbytehq/airbyte/master/airbyte-api/src/main/openapi/config.yaml#/.

## Current Behavior
The Airbyte server returns an internal server error response.

## Steps to Reproduce
After the server is up, 
```
➜  .dockerversions git:(better-api-docs) ✗ curl localhost:8001/api/v1/logs/get
{"message":"internal server error"}%
```

## Severity of the bug for you
Low. Not show stopper. Noticed this while playing around with the Airbyte API. 

## Additional context
All I did was pull from head and run `docker-compose up`.

**Comment by ChristopheDuong** [comment]
The exception in the server logs are:
```
2021-03-04 13:12:46 DEBUG i.a.s.e.UncaughtExceptionMapper(toResponse):42 - {} - Uncaught exception
airbyte-server | javax.ws.rs.NotAllowedException: HTTP 405 Method Not Allowed
airbyte-server |        at org.glassfish.jersey.server.internal.routing.MethodSelectingRouter.getMethodRouter(MethodSelectingRouter.java:400) ~[jersey-server-2.31.jar:?]
airbyte-server |        at org.glassfish.jersey.server.internal.routing.MethodSelectingRouter.access$000(MethodSelectingRouter.java:73) ~[jersey-server-2.31.jar:?]
airbyte-server |        at org.glassfish.jersey.server.internal.routing.MethodSelectingRouter$4.apply(MethodSelectingRouter.java:665) ~[jersey-server-2.31.jar:?]
airbyte-server |        at org.glassfish.jersey.server.internal.routing.MethodSelectingRouter.apply(MethodSelectingRouter.java:305) ~[jersey-server-2.31.jar:?]
airbyte-server |        at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:86) ~[jersey-server-2.31.jar:?]
airbyte-server |        at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:89) ~[jersey-server-2.31.jar:?]
airbyte-server |        at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:89) ~[jersey-server-2.31.jar:?]
airbyte-server |        at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:89) ~[jersey-server-2.31.jar:?]
airbyte-server |        at org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:69) ~[jersey-server-2.31.jar:?]
airbyte-server |        at org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:38) ~[jersey-server-2.31.jar:?]
airbyte-server |        at org.glassfish.jersey.process.internal.Stages.process(Stages.java:173) ~[jersey-common-2.31.jar:?]
```

**Comment by davinchia** [comment]
Turns out I was dumb and did not use the right curl command. Oops.
