### ISSUE TITLE
Source Clickhouse - java.sql.SQLFeatureNotSupportedException: getResultSet not implemented

### ISSUE THREAD

**Issue by realjustinwu** [airbytehq/airbyte#23465]
## Environment
- **Airbyte version**:  v0.40.30
- **OS Version / Instance**: Ubuntu 20.04
- **Deployment**:  Docker
- **Source Connector and version**: clickhouse - 0.2.2
- **Destination Connector and version**: clickhouse - 0.2.2
- **Step where error happened**:  Sync job

## Current Behavior
Synced failed.

## Expected Behavior
Sync success.

## Logs

```log
2023-02-26 04:07:04 [44msource[0m > Something went wrong in the connector. See the logs for more details.
Stack Trace: java.lang.RuntimeException: java.sql.SQLFeatureNotSupportedException: getResultSet not implemented
	at io.airbyte.db.jdbc.StreamingJdbcDatabase$1.tryAdvance(StreamingJdbcDatabase.java:105)
	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at io.airbyte.commons.util.LazyAutoCloseableIterator.computeNext(LazyAutoCloseableIterator.java:42)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:46)
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:46)
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at io.airbyte.commons.util.CompositeIterator.computeNext(CompositeIterator.java:63)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
	at io.airbyte.integrations.base.IntegrationRunner.lambda$produceMessages$0(IntegrationRunner.java:187)
	at io.airbyte.integrations.base.IntegrationRunner.watchForOrphanThreads(IntegrationRunner.java:237)
	at io.airbyte.integrations.base.IntegrationRunner.produceMessages(IntegrationRunner.java:186)
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:139)
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:98)
	at io.airbyte.integrations.source.clickhouse.ClickHouseSource.main(ClickHouseSource.java:134)
Caused by: java.sql.SQLFeatureNotSupportedException: getResultSet not implemented
	at com.clickhouse.jdbc.SqlExceptionUtils.unsupportedError(SqlExceptionUtils.java:138)
	at com.clickhouse.jdbc.ClickHouseArray.getResultSet(ClickHouseArray.java:74)
	at io.airbyte.db.jdbc.AbstractJdbcCompatibleSourceOperations.putArray(AbstractJdbcCompatibleSourceOperations.java:68)
	at io.airbyte.db.jdbc.JdbcSourceOperations.copyToJsonField(JdbcSourceOperations.java:60)
	at io.airbyte.db.jdbc.AbstractJdbcCompatibleSourceOperations.rowToJson(AbstractJdbcCompatibleSourceOperations.java:60)
	at io.airbyte.db.jdbc.AbstractJdbcCompatibleSourceOperations.rowToJson(AbstractJdbcCompatibleSourceOperations.java:37)
	at io.airbyte.db.jdbc.StreamingJdbcDatabase$1.tryAdvance(StreamingJdbcDatabase.java:99)
	... 31 more
```

[5b8a8f5c_da0b_448e_8f04_75f30d02ec84_logs_5_txt.txt](https://github.com/airbytehq/airbyte/files/10833083/5b8a8f5c_da0b_448e_8f04_75f30d02ec84_logs_5_txt.txt)

## Table

```sql
CREATE TABLE my_test_v2 (
    server_timestamp DateTime,
    timestamp DateTime,
    labels Nested(
        key String,
        value String
    ),
    metrics Nested(
        key String,
        value Int
    )
) ENGINE = MergeTree() PARTITION BY toYYYYMM(timestamp)
ORDER BY (timestamp);

```

## Steps to Reproduce
1.
2.
3.

**Comment by realjustinwu** [comment]
Due to clickhouse-jdbc didn't implement the function getResultSet in [ClickHouseArray.java](https://github.com/ClickHouse/clickhouse-java/blob/main/clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/ClickHouseArray.java), just throw an exception.

**Comment by ram-oscilar** [comment]
@realjustinwu hey did you find a workaround for this issue?
