### ISSUE TITLE
Source Github: Check connection fails for a GitHub organization with large number of repositories

### ISSUE THREAD

**Issue by abhishekbiyala** [airbytehq/airbyte#23679]
## Environment
- **Airbyte version**:  0.40.32
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Github 0.4.1
- **Destination Connector and version**: N/A
- **Step where error happened**: Setup new connection

## Current Behavior
Check connection fails when setting up Github source for a very large GitHub organization consisting of over 10k repos (org-name/*).
Connection with single repo works fine. So the problem appears to be in checking connection for a large number of repos.

## Expected Behavior
Check connection behavior should be successful.

## Logs
```
airbyte-worker  | 2023-03-02 17:49:27 INFO i.a.w.i.DefaultAirbyteStreamFactory(internalLog):167 - Caught retryable error 'Request URL: https://api.github.com/orgs/***/repos?per_page=100&page=5&sort=updated&direction=desc, Response Code: 502, Response Text: {
airbyte-worker  |   "message": "Server Error"
airbyte-worker  | }
airbyte-worker  | ' after 1 tries. Waiting 5 seconds then retrying...
airbyte-worker  | 2023-03-02 17:53:53 WARN i.t.i.s.WorkflowExecuteRunnable(throwAndFailWorkflowExecution):134 - Workflow execution failure WorkflowId='e02eb324-a902-47e2-9cd5-3b99e13ddf8b', RunId=3ed23809-fec5-4646-8668-5ca6f7802067, WorkflowType='CheckConnectionWorkflow'
airbyte-worker  | io.temporal.failure.ActivityFailure: scheduledEventId=6, startedEventId=7, activityType='RunWithJobOutput', activityId='1bd7227d-7ae4-3c42-9e16-408c2fffc461', identity='', retryState=RETRY_STATE_NON_RETRYABLE_FAILURE
airbyte-worker  |       at java.lang.Thread.getStackTrace(Thread.java:2550) ~[?:?]
airbyte-worker  |       at io.temporal.internal.sync.ActivityStubBase.execute(ActivityStubBase.java:49) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker  |       at io.temporal.internal.sync.ActivityInvocationHandler.lambda$getActivityFunc$0(ActivityInvocationHandler.java:78) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker  |       at io.temporal.internal.sync.ActivityInvocationHandlerBase.invoke(ActivityInvocationHandlerBase.java:60) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker  |       at jdk.proxy2.$Proxy82.runWithJobOutput(Unknown Source) ~[?:?]
airbyte-worker  |       at io.airbyte.workers.temporal.check.connection.CheckConnectionWorkflowImpl.run(CheckConnectionWorkflowImpl.java:51) ~[io.airbyte-airbyte-workers-0.40.32.jar:?]
airbyte-worker  |       at CheckConnectionWorkflowImplProxy.run$accessor$V85Bqwgn(Unknown Source) ~[?:?]
airbyte-worker  |       at CheckConnectionWorkflowImplProxy$auxiliary$n1QVgHj2.call(Unknown Source) ~[?:?]
airbyte-worker  |       at io.airbyte.workers.temporal.support.TemporalActivityStubInterceptor.execute(TemporalActivityStubInterceptor.java:79) ~[io.airbyte-airbyte-workers-0.40.32.jar:?]
airbyte-worker  |       at CheckConnectionWorkflowImplProxy.run(Unknown Source) ~[?:?]
airbyte-worker  |       at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
airbyte-worker  |       at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
airbyte-worker  |       at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation$RootWorkflowInboundCallsInterceptor.execute(POJOWorkflowImplementationFactory.java:302) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker  |       at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation.execute(POJOWorkflowImplementationFactory.java:277) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker  |       at io.temporal.internal.sync.WorkflowExecuteRunnable.run(WorkflowExecuteRunnable.java:71) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker  |       at io.temporal.internal.sync.SyncWorkflow.lambda$start$0(SyncWorkflow.java:116) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker  |       at io.temporal.internal.sync.CancellationScopeImpl.run(CancellationScopeImpl.java:102) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker  |       at io.temporal.internal.sync.WorkflowThreadImpl$RunnableWrapper.run(WorkflowThreadImpl.java:106) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker  |       at io.temporal.worker.ActiveThreadReportingExecutor.lambda$submit$0(ActiveThreadReportingExecutor.java:53) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker  |       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[?:?]
airbyte-worker  |       at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
airbyte-worker  |       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
airbyte-worker  |       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
airbyte-worker  |       at java.lang.Thread.run(Thread.java:1589) ~[?:?]
airbyte-worker  | Caused by: io.temporal.failure.TimeoutFailure: message='activity timeout', timeoutType=TIMEOUT_TYPE_SCHEDULE_TO_CLOSE
```

## Steps to Reproduce
1. Setup a Github org with large number of repos, lets say 10000
2. Try setting up Github source and check connection

## Are you willing to submit a PR?
Maybe

**Comment by davydov-d** [comment]
hey @abhishekbiyala I have a speculative fix, but yet can not test it as we don't have this large number of repositories in our test account. Could you please consider sharing your config so we could test if my fix really helps?

**Comment by davydov-d** [comment]
Closing this one as we do not have enough inputs to reproduce the issue and test the fix

**Comment by talha-naeem1** [comment]
https://github.com/airbytehq/airbyte/issues/38461
