### ISSUE TITLE
java.lang.IllegalStateException: getTransportChannel() called when needsExecutor() is true when trying to implement tracing in dataproc

### ISSUE THREAD

**Issue by ahmed7927** [airbytehq/airbyte#23714]
Error Trace:
getTransportChannel() called when needsExecutor() is true	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:171)	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:201)	at com.google.cloud.trace.v2.stub.GrpcTraceServiceStub.create(GrpcTraceServiceStub.java:73)	at com.google.cloud.trace.v2.stub.TraceServiceStubSettings.createStub(TraceServiceStubSettings.java:99)	at com.google.cloud.trace.v2.TraceServiceClient.<init>(TraceServiceClient.java:137)	at com.google.cloud.trace.v2.TraceServiceClient.create(TraceServiceClient.java:118)	at io.opencensus.exporter.trace.stackdriver.StackdriverV2ExporterHandler.createWithCredentials(StackdriverV2ExporterHandler.java:187)	at io.opencensus.exporter.trace.stackdriver.StackdriverTraceExporter.createAndRegister(StackdriverTraceExporter.java:86)

Dependencies used with versions:
"io.opencensus" % "opencensus-api" % "0.31.1",
"io.opencensus" % "opencensus-exporter-trace-stackdriver" % "0.31.0",
"com.google.cloud" % "google-cloud-trace" % "2.5.0",
"com.google.api" % "gax-grpc" % "2.6.1"

Function code:(Just trying to register a trace)
import io.opencensus.exporter.trace.stackdriver.StackdriverTraceConfiguration
    import io.opencensus.exporter.trace.stackdriver.StackdriverTraceExporter
    StackdriverTraceExporter.createAndRegister(
      StackdriverTraceConfiguration.builder()
        .setProjectId("project-id")
        .build())

It is a Dataproc job and i want to see trace in google Stackdriver . any help with the permissions needed or any other stuff which is missing for creating a trace in Dataproc how can we manage the transport channel

**Comment by ahmed7927** [comment]
Any permission needed for this to be added ? 
or the versions are incorrect

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 365 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.
