### ISSUE TITLE
Backoff strategy does not work if there are no response

### ISSUE THREAD

**Issue by maxi297** [airbytehq/airbyte#23942]
## Environment
- **Airbyte CDK version**:  0.30.1
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

Assuming an server that can be started with `node app.js`:
```javascript
const http = require('http');

const hostname = '127.0.0.1';
const port = 8002;

const server = http.createServer((req, res) => {
  req.socket.end();
});

server.listen(port, hostname, () => {
  console.log();
});
```

And the following manifest:
```python
STREAM_READ_REQUEST = {
    "manifest": {
        "spec": {
            "type": "Spec",
            "documentation_url": "https://example.org",
            "connection_specification": {
                "type": "object",
                "$schema": "http://json-schema.org/draft-07/schema#",
                "required": [],
                "properties": {},
                "additionalProperties": True
            }
        },
        "type": "DeclarativeSource",
        "check": {
            "type": "CheckStream",
            "stream_names": [
                "test"
            ]
        },
        "streams": [
            {
                "name": "test",
                "type": "DeclarativeStream",
                "retriever": {
                    "type": "SimpleRetriever",
                    "paginator": {
                        "type": "NoPagination"
                    },
                    "requester": {
                        "path": "/",
                        "type": "HttpRequester",
                        "url_base": "http://127.0.0.1:8002",
                        "http_method": "GET",
                        "authenticator": {
                            "type": "NoAuth"
                        },
                        "error_handler": {
                          "type": "DefaultErrorHandler",
                          "backoff_strategies": [
                            {
                              "type": "ConstantBackoff",
                              "backoff_time_in_seconds": 1
                            }
                          ]
                        },
                        "request_headers": {},
                        "request_body_json": {},
                        "request_parameters": {}
                    },
                    "record_selector": {
                        "type": "RecordSelector",
                        "extractor": {
                            "type": "DpathExtractor",
                            "field_path": []
                        }
                    }
                },
                "primary_key": [],
                "schema_loader": {
                    "type": "InlineSchemaLoader",
                    "schema": {}
                }
            }
        ],
        "version": "0.30.1"
    },
    "stream": "test",
    "config": {}
}
```

## Current Behavior
Backoff is exponential as it waits for 5s, 10s, 20s, 40s and 80s before it breaks

## Expected Behavior
If `backoff_strategies` is defined as `ConstantBackoff`, the backoff is constant using the `backoff_time_in_seconds`

## Logs
```
{"type": "LOG", "log": {"level": "INFO", "message": "Starting syncing ManifestDeclarativeSource"}}
{"type": "DEBUG", "message": "declarative source created from manifest", "data": {"source_name": "ManifestDeclarativeSource", "parsed_config": "{\"spec\": {\"type\": \"Spec\", \"documentation_url\": \"https://example.org\", \"connection_specification\": {\"type\": \"object\", \"$schema\": \"http://json-schema.org/draft-07/schema#\", \"required\": [], \"properties\": {}, \"additionalProperties\": true}}, \"type\": \"DeclarativeSource\", \"check\": {\"type\": \"CheckStream\", \"stream_names\": [\"test\"]}, \"streams\": [{\"name\": \"test\", \"type\": \"DeclarativeStream\", \"retriever\": {\"type\": \"SimpleRetriever\", \"paginator\": {\"type\": \"NoPagination\"}, \"requester\": {\"path\": \"/\", \"type\": \"HttpRequester\", \"url_base\": \"http://127.0.0.1:8002\", \"http_method\": \"GET\", \"authenticator\": {\"type\": \"NoAuth\"}, \"request_headers\": {}, \"request_body_json\": {}, \"request_parameters\": {}}, \"record_selector\": {\"type\": \"RecordSelector\", \"extractor\": {\"type\": \"DpathExtractor\", \"field_path\": []}}}, \"primary_key\": [], \"schema_loader\": {\"type\": \"InlineSchemaLoader\", \"schema\": {}}}], \"version\": \"0.30.1\"}"}}
{"type": "DEBUG", "message": "Syncing configured stream: test", "data": {"primary_key": "None", "sync_mode": "SyncMode.full_refresh", "cursor_field": "None"}}
{"type": "DEBUG", "message": "Syncing stream instance: test", "data": {"primary_key": "[]", "cursor_field": "[]"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Syncing stream: test "}}
{"type": "DEBUG", "message": "Processing stream slices for test (sync_mode: full_refresh)", "data": {"stream_slices": "<itertools.islice object at 0x1058b2a40>"}}
{"type": "DEBUG", "message": "Making outbound API request", "data": {"request_body": "None", "headers": "{'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}", "url": "http://127.0.0.1:8002/"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Backing off _send(...) for 5.0s (requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Caught retryable error '('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))' after 1 tries. Waiting 5 seconds then retrying..."}}
{"type": "DEBUG", "message": "Making outbound API request", "data": {"request_body": "None", "headers": "{'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}", "url": "http://127.0.0.1:8002/"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Backing off _send(...) for 10.0s (requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Caught retryable error '('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))' after 2 tries. Waiting 10 seconds then retrying..."}}
{"type": "DEBUG", "message": "Making outbound API request", "data": {"request_body": "None", "headers": "{'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}", "url": "http://127.0.0.1:8002/"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Backing off _send(...) for 20.0s (requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Caught retryable error '('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))' after 3 tries. Waiting 20 seconds then retrying..."}}
{"type": "DEBUG", "message": "Making outbound API request", "data": {"request_body": "None", "headers": "{'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}", "url": "http://127.0.0.1:8002/"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Backing off _send(...) for 40.0s (requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Caught retryable error '('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))' after 4 tries. Waiting 40 seconds then retrying..."}}
{"type": "DEBUG", "message": "Making outbound API request", "data": {"request_body": "None", "headers": "{'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}", "url": "http://127.0.0.1:8002/"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Backing off _send(...) for 80.0s (requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Caught retryable error '('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))' after 5 tries. Waiting 80 seconds then retrying..."}}
{"type": "DEBUG", "message": "Making outbound API request", "data": {"request_body": "None", "headers": "{'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}", "url": "http://127.0.0.1:8002/"}}
{"type": "LOG", "log": {"level": "ERROR", "message": "Giving up _send(...) after 6 tries (requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))"}}
{"type": "LOG", "log": {"level": "ERROR", "message": "Encountered an exception while reading stream test\nTraceback (most recent call last):\n  File \"/Users/maxime/devel/code/airbyte-platform-internal/oss/airbyte-connector-builder-server/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 703, in urlopen\n    httplib_response = self._make_request(\n  File \"/Users/maxime/devel/code/airbyte-platform-internal/oss/airbyte-connector-builder-server/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 449, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/Users/maxime/devel/code/airbyte-platform-internal/oss/airbyte-connector-builder-server/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 444, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/Users/maxime/.pyenv/versions/3.9.11/lib/python3.9/http/client.py\", line 1377, in getresponse\n    response.begin()\n  File \"/Users/maxime/.pyenv/versions/3.9.11/lib/python3.9/http/client.py\", line 320, in begin\n    version, status, reason = self._read_status()\n  File \"/Users/maxime/.pyenv/versions/3.9.11/lib/python3.9/http/client.py\", line 289, in _read_status\n    raise RemoteDisconnected(\"Remote end closed connection without\"\nhttp.client.RemoteDisconnected: Remote end closed connection without response\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/maxime/devel/code/airbyte-platform-internal/oss/airbyte-connector-builder-server/.venv/lib/python3.9/site-packages/requests/adapters.py\", line 489, in send\n    resp = conn.urlopen(\n  File \"/Users/maxime/devel/code/airbyte-platform-internal/oss/airbyte-connector-builder-server/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"/Users/maxime/devel/code/airbyte-platform-internal/oss/airbyte-connector-builder-server/.venv/lib/python3.9/site-packages/urllib3/util/retry.py\", line 550, in increment\n    raise six.reraise(type(error), error, _stacktrace)\n  File \"/Users/maxime/devel/code/airbyte-platform-internal/oss/airbyte-connector-builder-server/.venv/lib/python3.9/site-packages/urllib3/packages/six.py\", line 769, in reraise\n    raise value.with_traceback(tb)\n  File \"/Users/maxime/devel/code/airbyte-platform-internal/oss/airbyte-connector-builder-server/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 703, in urlopen\n    httplib_response = self._make_request(\n  File \"/Users/maxime/devel/code/airbyte-platform-internal/oss/airbyte-connector-builder-server/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 449, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/Users/maxime/devel/code/airbyte-platform-internal/oss/airbyte-connector-builder-server/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 444, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/Users/maxime/.pyenv/versions/3.9.11/lib/python3.9/http/client.py\", line 1377, in getresponse\n    response.begin()\n  File \"/Users/maxime/.pyenv/versions/3.9.11/lib/python3.9/http/client.py\", line 320, in begin\n    version, status, reason = self._read_status()\n  File \"/Users/maxime/.pyenv/versions/3.9.11/lib/python3.9/http/client.py\", line 289, in _read_status\n    raise RemoteDisconnected(\"Remote end closed connection without\"\nurllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/maxime/devel/code/airbyte/airbyte-cdk/python/airbyte_cdk/sources/abstract_source.py\", line 120, in read\n    yield from self._read_stream(\n  File \"/Users/maxime/devel/code/airbyte/airbyte-cdk/python/airbyte_cdk/sources/abstract_source.py\", line 189, in _read_stream\n    for record in record_iterator:\n  File \"/Users/maxime/devel/code/airbyte/airbyte-cdk/python/airbyte_cdk/sources/abstract_source.py\", line 307, in _read_full_refresh\n    for record_data_or_message in record_data_or_messages:\n  File \"/Users/maxime/devel/code/airbyte/airbyte-cdk/python/airbyte_cdk/sources/declarative/declarative_stream.py\", line 100, in read_records\n    for record in self.retriever.read_records(sync_mode, cursor_field, stream_slice, stream_state):\n  File \"/Users/maxime/devel/code/airbyte/airbyte-cdk/python/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py\", line 375, in read_records\n    for record in records_generator:\n  File \"/Users/maxime/devel/code/airbyte/airbyte-cdk/python/airbyte_cdk/sources/streams/http/http.py\", line 435, in _read_pages\n    request, response = self._fetch_next_page(stream_slice, stream_state, next_page_token)\n  File \"/Users/maxime/devel/code/airbyte/airbyte-cdk/python/airbyte_cdk/sources/streams/http/http.py\", line 458, in _fetch_next_page\n    response = self._send_request(request, request_kwargs)\n  File \"/Users/maxime/devel/code/airbyte/airbyte-cdk/python/airbyte_cdk/sources/streams/http/http.py\", line 360, in _send_request\n    return backoff_handler(user_backoff_handler)(request, request_kwargs)\n  File \"/Users/maxime/devel/code/airbyte-platform-internal/oss/airbyte-connector-builder-server/.venv/lib/python3.9/site-packages/backoff/_sync.py\", line 105, in retry\n    ret = target(*args, **kwargs)\n  File \"/Users/maxime/devel/code/airbyte-platform-internal/oss/airbyte-connector-builder-server/.venv/lib/python3.9/site-packages/backoff/_sync.py\", line 105, in retry\n    ret = target(*args, **kwargs)\n  File \"/Users/maxime/devel/code/airbyte/airbyte-cdk/python/airbyte_cdk/sources/streams/http/http.py\", line 304, in _send\n    response: requests.Response = self._session.send(request, **request_kwargs)\n  File \"/Users/maxime/devel/code/airbyte-platform-internal/oss/airbyte-connector-builder-server/.venv/lib/python3.9/site-packages/requests/sessions.py\", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File \"/Users/maxime/devel/code/airbyte-platform-internal/oss/airbyte-connector-builder-server/.venv/lib/python3.9/site-packages/requests/adapters.py\", line 547, in send\n    raise ConnectionError(err, request=request)\nrequests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Finished syncing test"}}
{"type": "LOG", "log": {"level": "INFO", "message": "ManifestDeclarativeSource runtimes:\nSyncing stream test 0:02:35.053835"}}
{"type": "LOG", "log": {"level": "ERROR", "message": "Could not perform read with with error: Every message grouping should have at least one request and response - Traceback (most recent call last):\n  File \"/Users/maxime/devel/code/airbyte-platform-internal/oss/airbyte-connector-builder-server/connector_builder/impl/default_api.py\", line 145, in read_stream\n    for message_group in self._get_message_groups(\n  File \"/Users/maxime/devel/code/airbyte-platform-internal/oss/airbyte-connector-builder-server/connector_builder/impl/default_api.py\", line 243, in _get_message_groups\n    self._close_page(current_page_request, current_page_response, current_slice_pages, current_page_records)\n  File \"/Users/maxime/devel/code/airbyte-platform-internal/oss/airbyte-connector-builder-server/connector_builder/impl/default_api.py\", line 257, in _close_page\n    raise ValueError(\"Every message grouping should have at least one request and response\")\nValueError: Every message grouping should have at least one request and response\n"}}
Traceback (most recent call last):
  File "/Users/maxime/devel/code/airbyte-platform-internal/oss/airbyte-connector-builder-server/connector_builder/impl/default_api.py", line 145, in read_stream
    for message_group in self._get_message_groups(
  File "/Users/maxime/devel/code/airbyte-platform-internal/oss/airbyte-connector-builder-server/connector_builder/impl/default_api.py", line 243, in _get_message_groups
    self._close_page(current_page_request, current_page_response, current_slice_pages, current_page_records)
  File "/Users/maxime/devel/code/airbyte-platform-internal/oss/airbyte-connector-builder-server/connector_builder/impl/default_api.py", line 257, in _close_page
    raise ValueError("Every message grouping should have at least one request and response")
ValueError: Every message grouping should have at least one request and response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/maxime/devel/code/airbyte-platform-internal/oss/airbyte-connector-builder-server/connector_builder/impl/default_api.py", line 382, in <module>
    api.read_stream(StreamReadRequestBody(**STREAM_READ_REQUEST))
  File "/Users/maxime/devel/code/airbyte-platform-internal/oss/airbyte-connector-builder-server/connector_builder/impl/default_api.py", line 157, in read_stream
    raise HTTPException(
fastapi.exceptions.HTTPException

Process finished with exit code 1
```

## Steps to Reproduce
Why the above context, run:
```
configured_catalog = ConfiguredAirbyteCatalog.parse_obj(
    {
        "streams": [
            {
                "stream": {
                    "name": stream,
                    "json_schema": {},
                    "supported_sync_modes": ["full_refresh", "incremental"],
                },
                "sync_mode": "full_refresh",
                "destination_sync_mode": "overwrite",
            }
        ]
    }
)

source = ManifestDeclarativeSource(
            manifest,
            debug=True,
            component_factory=ModelToComponentFactory(limit_page_fetched_per_slice, limit_slices_fetched)
        )
source.read(logger=source.logger, config={}, catalog=configured_catalog)
```

**Comment by maxi297** [comment]
Root cause for this issue: HttpStream has it's own retry/backoff strategy (see https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/streams/http/http.py#L362)

**Comment by flash1293** [comment]
@brianjlai will take a look to gauge the effort required to fix this properly

**Comment by brianjlai** [comment]
Initial investigation into level of effort:

- We cannot scope the fix for this to the declarative framework. In the `airbyte-cdk` runtime in `http.py`, when we do not receive a response back as a result of the `send()` call, we catch an exception triggering a default to an exponential backoff starting at 5 seconds. This happens *before* we invoke the implementations of the connectors `should_retry()` or `backoff_time()`.
- One particular complication is that the current CDK interfaces rely on the assumption that there is a response object. And underlying implementations are also coded to expect and behave that way as well.

I see a few options we can take:

1. [Low LOE] When making the outbound request, we can catch `ConnectionError` which would arise when we couldn't get a valid response back. Proper error responses should not throw this exception. From there we can build our own Response object with a 500 error code which will be handled according to the error handler behavior defined.
2. [High LOE] We can change the `should_retry()` and `backoff_time()` interfaces to make `Response` optional. In the event that `Response` is not present, a connector can define an implementation of what the default behavior should be. We would also need to invoke these methods in `http.py._send_request()` and set values on the default backoff handlers.

**Comment by brianjlai** [comment]
Grooming notes:

- We should opt to change the interface for the should retry and backoff_time methods to support an optional response
- we also need to support the 1 second constant backoff time for faster connector builder requests which we can use a decorator for (but that will be a separate issue)
- brian to write quick summary of what we would change to make this work in the new interface
- and to derisk that this doesn't block the dependent issue
