### ISSUE TITLE
'octavia import connection' fails with invalid type

### ISSUE THREAD

**Issue by eschrock** [airbytehq/airbyte#23953]
## Environment
- **Airbyte version**:  0.41.0
- **OS Version / Instance**:  macOS Ventura 13.2.1
- **Deployment**: Docker
- **Source Connector and version**: Jira 0.3.4
- **Destination Connector and version**: Snowflake 0.4.48
- **Step where error happened**: `octavia import`

## Current Behavior
`octavia import` of a connection fails with "Invalid type for variable 'web_backend_connection_list_request_body'".

## Expected Behavior
`octavia import` should succeed.

## Logs

```
Traceback (most recent call last):
  File "/usr/local/bin/octavia", line 8, in <module>
    sys.exit(octavia())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
🐙 - Octavia is targetting your Airbyte instance running at http://localhost:8000 on workspace 4f91da45-79b2-402d-875e-08aac8ae36fa.
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/base_commands.py", line 54, in invoke
    raise e
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/base_commands.py", line 51, in invoke
    result = super().invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/check_context.py", line 91, in wrapper
    f(ctx, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/_import/commands.py", line 156, in connection
    click.echo(import_connection(ctx.obj["API_CLIENT"], ctx.obj["WORKSPACE_ID"], resource))
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/_import/commands.py", line 87, in import_connection
    remote_configuration = json.loads(get_json_representation(api_client, workspace_id, UnmanagedConnection, resource_to_get))
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/get/commands.py", line 67, in get_json_representation
    return resource.to_json()
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/get/resources.py", line 148, in to_json
    return json.dumps(self.get_remote_resource().to_dict())
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/get/resources.py", line 140, in get_remote_resource
    return self._find_by_resource_name()
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/get/resources.py", line 108, in _find_by_resource_name
    api_response = self._list_for_workspace_fn(self.api_instance, self.list_for_workspace_payload)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/api/web_backend_api.py", line 844, in web_backend_list_connections_for_workspace
    return self.web_backend_list_connections_for_workspace_endpoint.call_with_http_info(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/api_client.py", line 829, in call_with_http_info
    self.__validate_inputs(kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/api_client.py", line 723, in __validate_inputs
    fixed_val = validate_and_convert_types(
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 1570, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 1449, in attempt_convert_item
    raise get_type_error(input_value, path_to_item, valid_classes,
airbyte_api_client.exceptions.ApiTypeError: Invalid type for variable 'web_backend_connection_list_request_body'. Required value type is WebBackendConnectionListRequestBody and passed type was WorkspaceIdRequestBody at ['web_backend_connection_list_request_body']
```

## Steps to Reproduce
1. unzip [airbyte-bug.zip](https://github.com/airbytehq/airbyte/files/10946664/airbyte-bug.zip)
2. `octavia apply`
3. `octavia import connection octavia-bug-demo`

## Are you willing to submit a PR?
I don't sufficiently understand the code in question, but if someone can educate me I can do the gruntwork.

**Comment by marcosmarxm** [comment]
Octavia was removed from the main repo and won't receive updates anymore.
