### ISSUE TITLE
MySQL Source : unexpected EOF in middle of data block during CDC incremental sync

### ISSUE THREAD

**Issue by VitaliiMaltsev** [airbytehq/airbyte#24191]
MySQL СDC syncs started to fail permanently in master branch with the error 

```
Caused by: org.apache.kafka.connect.errors.ConnectException: java.io.StreamCorruptedException: unexpected EOF in middle of data block
	at io.airbyte.integrations.debezium.internals.AirbyteFileOffsetBackingStore.load(AirbyteFileOffsetBackingStore.java:137)
	at io.airbyte.integrations.debezium.internals.AirbyteFileOffsetBackingStore.read(AirbyteFileOffsetBackingStore.java:57)
	at io.airbyte.integrations.debezium.internals.DebeziumStateDecoratingIterator.computeNext(DebeziumStateDecoratingIterator.java:148)
```
Probably the root cause of these failing is [this PR](https://github.com/airbytehq/airbyte/pull/21727/files)

## Steps to Reproduce
0. Create MySQL table and populate it with 1M rows of random test data
`CREATE TABLE test_table(id INTEGER PRIMARY KEY, test_column timestamp);
`
2. Create MySQL connector with CDC replication mode
3. Create any destination
4. Choose mode Incremental | Append
5. Sync

**Comment by VitaliiMaltsev** [comment]
issue is not persists anymore

**Comment by dimoschi** [comment]
I still experience the same issue after having a vast data migration to one of our tables. The source is MySQL (running the latest Airbyte source version) and the destination is Snowflake.

```log
2023-03-19 10:51:56 [44msource[0m > ERROR i.a.i.b.AirbyteExceptionHandler(uncaughtException):26 Something went wrong in the connector. See the logs for more details. java.lang.RuntimeException: org.apache.kafka.connect.errors.ConnectException: java.io.StreamCorruptedException: unexpected EOF in middle of data block
	at io.airbyte.integrations.debezium.internals.DebeziumStateDecoratingIterator.computeNext(DebeziumStateDecoratingIterator.java:163) ~[io.airbyte.airbyte-integrations.bases-debezium-0.42.0.jar:?]
	at io.airbyte.integrations.debezium.internals.DebeziumStateDecoratingIterator.computeNext(DebeziumStateDecoratingIterator.java:27) ~[io.airbyte.airbyte-integrations.bases-debezium-0.42.0.jar:?]
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.1-jre.jar:?]
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38) ~[io.airbyte-airbyte-commons-0.42.0.jar:?]
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.1-jre.jar:?]
	at io.airbyte.commons.util.CompositeIterator.computeNext(CompositeIterator.java:63) ~[io.airbyte-airbyte-commons-0.42.0.jar:?]
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.1-jre.jar:?]
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38) ~[io.airbyte-airbyte-commons-0.42.0.jar:?]
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.1-jre.jar:?]
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38) ~[io.airbyte-airbyte-commons-0.42.0.jar:?]
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.1-jre.jar:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:132) ~[?:?]
	at io.airbyte.integrations.base.IntegrationRunner.lambda$produceMessages$0(IntegrationRunner.java:187) ~[io.airbyte.airbyte-integrations.bases-base-java-0.42.0.jar:?]
	at io.airbyte.integrations.base.IntegrationRunner.watchForOrphanThreads(IntegrationRunner.java:237) ~[io.airbyte.airbyte-integrations.bases-base-java-0.42.0.jar:?]
	at io.airbyte.integrations.base.IntegrationRunner.produceMessages(IntegrationRunner.java:186) ~[io.airbyte.airbyte-integrations.bases-base-java-0.42.0.jar:?]
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:139) ~[io.airbyte.airbyte-integrations.bases-base-java-0.42.0.jar:?]
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:98) ~[io.airbyte.airbyte-integrations.bases-base-java-0.42.0.jar:?]
	at io.airbyte.integrations.source.mysql.MySqlSource.main(MySqlSource.java:400) ~[io.airbyte.airbyte-integrations.connectors-source-mysql-0.42.0.jar:?]
Caused by: org.apache.kafka.connect.errors.ConnectException: java.io.StreamCorruptedException: unexpected EOF in middle of data block
	at io.airbyte.integrations.debezium.internals.AirbyteFileOffsetBackingStore.load(AirbyteFileOffsetBackingStore.java:137) ~[io.airbyte.airbyte-integrations.bases-debezium-0.42.0.jar:?]
	at io.airbyte.integrations.debezium.internals.AirbyteFileOffsetBackingStore.read(AirbyteFileOffsetBackingStore.java:57) ~[io.airbyte.airbyte-integrations.bases-debezium-0.42.0.jar:?]
	at io.airbyte.integrations.debezium.internals.DebeziumStateDecoratingIterator.computeNext(DebeziumStateDecoratingIterator.java:148) ~[io.airbyte.airbyte-integrations.bases-debezium-0.42.0.jar:?]
	... 22 more
Caused by: java.io.StreamCorruptedException: unexpected EOF in middle of data block
	at java.io.ObjectInputStream$BlockDataInputStream.refill(ObjectInputStream.java:3155) ~[?:?]
	at java.io.ObjectInputStream$BlockDataInputStream.read(ObjectInputStream.java:3231) ~[?:?]
	at java.io.DataInputStream.readInt(DataInputStream.java:393) ~[?:?]
	at java.io.ObjectInputStream$BlockDataInputStream.readInt(ObjectInputStream.java:3436) ~[?:?]
	at java.io.ObjectInputStream.readInt(ObjectInputStream.java:1128) ~[?:?]
	at java.util.HashMap.readObject(HashMap.java:1523) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor31.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1100) ~[?:?]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2423) ~[?:?]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2257) ~[?:?]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733) ~[?:?]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:509) ~[?:?]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:467) ~[?:?]
	at io.airbyte.integrations.debezium.internals.AirbyteFileOffsetBackingStore.load(AirbyteFileOffsetBackingStore.java:120) ~[io.airbyte.airbyte-integrations.bases-debezium-0.42.0.jar:?]
	at io.airbyte.integrations.debezium.internals.AirbyteFileOffsetBackingStore.read(AirbyteFileOffsetBackingStore.java:57) ~[io.airbyte.airbyte-integrations.bases-debezium-0.42.0.jar:?]
	at io.airbyte.integrations.debezium.internals.DebeziumStateDecoratingIterator.computeNext(DebeziumStateDecoratingIterator.java:148) ~[io.airbyte.airbyte-integrations.bases-debezium-0.42.0.jar:?]
	... 22 more

Stack Trace: java.lang.RuntimeException: org.apache.kafka.connect.errors.ConnectException: java.io.StreamCorruptedException: unexpected EOF in middle of data block
	at io.airbyte.integrations.debezium.internals.DebeziumStateDecoratingIterator.computeNext(DebeziumStateDecoratingIterator.java:163)
	at io.airbyte.integrations.debezium.internals.DebeziumStateDecoratingIterator.computeNext(DebeziumStateDecoratingIterator.java:27)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at io.airbyte.commons.util.CompositeIterator.computeNext(CompositeIterator.java:63)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
	at io.airbyte.integrations.base.IntegrationRunner.lambda$produceMessages$0(IntegrationRunner.java:187)
	at io.airbyte.integrations.base.IntegrationRunner.watchForOrphanThreads(IntegrationRunner.java:237)
	at io.airbyte.integrations.base.IntegrationRunner.produceMessages(IntegrationRunner.java:186)
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:139)
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:98)
	at io.airbyte.integrations.source.mysql.MySqlSource.main(MySqlSource.java:400)
Caused by: org.apache.kafka.connect.errors.ConnectException: java.io.StreamCorruptedException: unexpected EOF in middle of data block
	at io.airbyte.integrations.debezium.internals.AirbyteFileOffsetBackingStore.load(AirbyteFileOffsetBackingStore.java:137)
	at io.airbyte.integrations.debezium.internals.AirbyteFileOffsetBackingStore.read(AirbyteFileOffsetBackingStore.java:57)
	at io.airbyte.integrations.debezium.internals.DebeziumStateDecoratingIterator.computeNext(DebeziumStateDecoratingIterator.java:148)
	... 22 more
Caused by: java.io.StreamCorruptedException: unexpected EOF in middle of data block
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.refill(ObjectInputStream.java:3155)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.read(ObjectInputStream.java:3231)
	at java.base/java.io.DataInputStream.readInt(DataInputStream.java:393)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.readInt(ObjectInputStream.java:3436)
	at java.base/java.io.ObjectInputStream.readInt(ObjectInputStream.java:1128)
	at java.base/java.util.HashMap.readObject(HashMap.java:1523)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor31.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1100)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2423)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2257)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:509)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:467)
	at io.airbyte.integrations.debezium.internals.AirbyteFileOffsetBackingStore.load(AirbyteFileOffsetBackingStore.java:120)
	... 24 more
```


I'm running the latest Airbyte version (v0.42.0) on a VM with docker.

**Comment by VitaliiMaltsev** [comment]
i confirm that issue persists in 2.0.2 and 2.0.3 versions
