### ISSUE TITLE
Octavia CLI unable to upload configuration due to type mismatch

### ISSUE THREAD

**Issue by alexander-marquardt** [airbytehq/airbyte#24228]
## Environment
- **Airbyte version**:  0.42.0
- **OS Version / Instance**: macOS
- **Deployment**: Docker compose OSS running locally
- **Source Connector and version**:  Sample Data (Faker) -- but applies to others as well
- **Destination Connector and version**: E2E TEsting
- **Step where error happened**: Octavia CLI is unable to do a forced upload of a confguration due to a type mismatch

## Background
As part of the exploration of how to ease migration from OSS, I am evaluating using Octavia CLI for this. Based on https://airbyte.com/tutorials/version-control-airbyte-configurations, this should be possible. 

## Steps to reproduce error

Download the configuration by executing the following steps:

```
octavia init
octavia import all
```

Then try to upload the configuration by executing the following (note that "force" is required since we have not modified the configuration, and it won't try to upload without this option.
```
octavia apply --force
```

## Expected Behavior
Octavia should upload the configuration

## Logs

```
Running update because the force mode is activated.
Traceback (most recent call last):
  File "/usr/local/bin/octavia", line 8, in <module>
    sys.exit(octavia())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/base_commands.py", line 54, in invoke
    raise e
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/base_commands.py", line 51, in invoke
    result = super().invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/check_context.py", line 91, in wrapper
    f(ctx, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/apply/commands.py", line 29, in apply
    apply_single_resource(resource, force)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/apply/commands.py", line 63, in apply_single_resource
    messages = update_resource(resource, force)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/apply/commands.py", line 153, in update_resource
    updated_resource, state = resource.update()
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/apply/resources.py", line 730, in update
    return self._create_or_update(self._update_fn, self.update_payload)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/apply/resources.py", line 724, in update_payload
    return WebBackendConnectionUpdate(connection_id=self.resource_id, **self.configuration)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 46, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model/web_backend_connection_update.py", line 347, in __init__
    setattr(self, var_name, var_value)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 185, in __setattr__
    self[attr] = value
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 510, in __setitem__
    self.set_attribute(name, value)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 157, in set_attribute
    value = validate_and_convert_types(
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 1582, in validate_and_convert_types
    raise get_type_error(input_value, path_to_item, valid_classes,
airbyte_api_client.exceptions.ApiTypeError: Invalid type for variable 'non_breaking_changes_preference'. Required value type is NonBreakingChangesPreference and passed type was str at ['non_breaking_changes_preference']

```

## Are you willing to submit a PR?
I think this would be best addressed by Engineering.

**Comment by alexnikitchuk** [comment]
same issue on our side

**Comment by alexander-marquardt** [comment]
This error first appears in [Octavia-CLI 0.40.18](https://hub.docker.com/layers/airbyte/octavia-cli/0.40.18/images/sha256-3f86636224253d239cb89c7500a724444f5f386c3005ba08d50ea85bdfcd3eb0?context=explore) (Nov 2, 2022), and was working correctly with [Octavia-CLI0.40.17](https://hub.docker.com/layers/airbyte/octavia-cli/0.40.17/images/sha256-9803d757c6e50e7a2cff1df5cdc5602ac9cd35c99c88ed8967624a5729056c5b?context=explore). 

Verified by downloading an older version of Aibyte 0.40.10 (prior to username/password authentication), and aliasing Octavia as follows:

```
alias octavia="docker run -i --rm -v \$(pwd):/home/octavia-project --network host --env-file \${OCTAVIA_ENV_FILE} --user \$(id -u):\$(id -g) airbyte/octavia-cli:0.40.18"
```

```
alias octavia="docker run -i --rm -v \$(pwd):/home/octavia-project --network host --env-file \${OCTAVIA_ENV_FILE} --user \$(id -u):\$(id -g) airbyte/octavia-cli:0.40.17"
```
