### ISSUE TITLE
Source-postgres (V2) read failing with: `java.lang.NumberFormatException: For input string: "419866639440"`

### ISSUE THREAD

**Issue by seanglynn-thrive** [airbytehq/airbyte#24226]
## Environment
- **Airbyte version**:  0.42.0
- **OS Version / Instance**: AKS
- **Deployment**: Kubernetes
- **Source Connector and version**: Source Postgres `v2.0.3`
- **Step where error happened**: Sync job during READ step

## Current Behavior
*Tell us what happens.*

Since upgrading to source-postgres V2 we are noticing some of our connections that use source-postgres with CDC (pgoutput) are failing with the following exception:
`java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "419933727392"`
This seems to occur while the source-postgres connector reads from the postgres WAL and encounters an unexpected value.

Full stack trace:

```log
2023-03-20 09:23:22 [44msource[0m > WARN i.a.i.b.IntegrationRunner(watchForOrphanThreads):245 The main thread is exiting while children non-daemon threads from a connector are still active.
Ideally, this situation should not happen...
Please check with maintainers if the connector or library code should safely clean up its threads before quitting instead.
The main thread is: main (RUNNABLE)
 Thread stacktrace: java.base/java.lang.Thread.getStackTrace(Thread.java:1610)
        at io.airbyte.integrations.base.IntegrationRunner.dumpThread(IntegrationRunner.java:302)
        at io.airbyte.integrations.base.IntegrationRunner.watchForOrphanThreads(IntegrationRunner.java:249)
        at io.airbyte.integrations.base.IntegrationRunner.produceMessages(IntegrationRunner.java:186)
        at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:139)
        at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:98)
        at io.airbyte.integrations.base.adaptive.AdaptiveSourceRunner$Runner.run(AdaptiveSourceRunner.java:86)
        at io.airbyte.integrations.source.postgres.PostgresSourceRunner.main(PostgresSourceRunner.java:15)
2023-03-20 09:23:22 [44msource[0m > WARN i.a.i.b.IntegrationRunner(watchForOrphanThreads):257 Active non-daemon thread: pool-2-thread-1 (RUNNABLE)
 Thread stacktrace: app//com.fasterxml.jackson.core.json.UTF8JsonGenerator._writeStringSegment(UTF8JsonGenerator.java:1456)
        at app//com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeString(UTF8JsonGenerator.java:524)
        at app//com.fasterxml.jackson.databind.node.TextNode.serialize(TextNode.java:151)
        at app//com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:425)
        at app//com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:425)
        at app//com.fasterxml.jackson.databind.ser.std.SerializableSerializer.serialize(SerializableSerializer.java:39)
        at app//com.fasterxml.jackson.databind.ser.std.SerializableSerializer.serialize(SerializableSerializer.java:20)
        at app//com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
        at app//com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
        at app//com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4624)
        at app//com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:3892)
        at app//org.apache.kafka.connect.json.JsonSerializer.serialize(JsonSerializer.java:64)
        at app//org.apache.kafka.connect.json.JsonConverter.fromConnectData(JsonConverter.java:306)
        at app//io.debezium.embedded.ConvertingEngineBuilder.lambda$build$4(ConvertingEngineBuilder.java:175)
        at app//io.debezium.embedded.ConvertingEngineBuilder$$Lambda$446/0x0000000800fab280.apply(Unknown Source)
        at app//io.debezium.embedded.ConvertingEngineBuilder.lambda$notifying$0(ConvertingEngineBuilder.java:75)
        at app//io.debezium.embedded.ConvertingEngineBuilder$$Lambda$441/0x0000000800fae890.accept(Unknown Source)
        at app//io.debezium.embedded.EmbeddedEngine$1.handleBatch(EmbeddedEngine.java:518)
        at app//io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:913)
        at app//io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:195)
        at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)
2023-03-20 09:23:22 [44msource[0m > WARN i.a.i.b.IntegrationRunner(watchForOrphanThreads):257 Active non-daemon thread: FileOffsetBackingStore-1 (WAITING)
 Thread stacktrace: java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
        at java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506)
        at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
        at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
        at java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623)
        at java.base@17.0.4.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
        at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
        at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
        at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)
2023-03-20 09:23:22 [44msource[0m > WARN i.a.i.b.IntegrationRunner(watchForOrphanThreads):257 Active non-daemon thread: debezium-postgresconnector-today-change-event-source-coordinator (RUNNABLE)
 Thread stacktrace: java.base@17.0.4.1/java.math.BigDecimal.toPlainString(BigDecimal.java:3478)
        at java.base@17.0.4.1/java.time.format.DateTimeFormatterBuilder$FractionPrinterParser.format(DateTimeFormatterBuilder.java:3225)
        at java.base@17.0.4.1/java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2402)
        at java.base@17.0.4.1/java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1849)
        at java.base@17.0.4.1/java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1823)
        at java.base@17.0.4.1/java.time.ZonedDateTime.format(ZonedDateTime.java:2157)
        at app//io.airbyte.db.jdbc.DateTimeConverter.convertToTimestampWithTimezone(DateTimeConverter.java:67)
        at app//io.airbyte.integrations.debezium.internals.PostgresConverter.lambda$registerDate$22(PostgresConverter.java:230)
        at app//io.airbyte.integrations.debezium.internals.PostgresConverter$$Lambda$608/0x0000000800ff9a28.convert(Unknown Source)
        at app//io.debezium.relational.CustomConverterRegistry.lambda$getValueConverter$1(CustomConverterRegistry.java:142)
        at app//io.debezium.relational.CustomConverterRegistry$$Lambda$609/0x0000000800ff9c50.convert(Unknown Source)
        at app//io.debezium.relational.TableSchemaBuilder.lambda$createValueGenerator$5(TableSchemaBuilder.java:279)
        at app//io.debezium.relational.TableSchemaBuilder$$Lambda$616/0x00000008010011c0.generateValue(Unknown Source)
        at app//io.debezium.relational.TableSchema.valueFromColumnData(TableSchema.java:141)
        at app//io.debezium.relational.RelationalChangeRecordEmitter.emitReadRecord(RelationalChangeRecordEmitter.java:87)
        at app//io.debezium.relational.RelationalChangeRecordEmitter.emitChangeRecords(RelationalChangeRecordEmitter.java:50)
        at app//io.debezium.pipeline.EventDispatcher.dispatchSnapshotEvent(EventDispatcher.java:170)
        at app//io.debezium.relational.RelationalSnapshotChangeEventSource.createDataEventsForTable(RelationalSnapshotChangeEventSource.java:409)
        at app//io.debezium.relational.RelationalSnapshotChangeEventSource.createDataEvents(RelationalSnapshotChangeEventSource.java:318)
        at app//io.debezium.relational.RelationalSnapshotChangeEventSource.doExecute(RelationalSnapshotChangeEventSource.java:133)
        at app//io.debezium.pipeline.source.AbstractSnapshotChangeEventSource.execute(AbstractSnapshotChangeEventSource.java:76)
        at app//io.debezium.pipeline.ChangeEventSourceCoordinator.doSnapshot(ChangeEventSourceCoordinator.java:155)
        at app//io.debezium.pipeline.ChangeEventSourceCoordinator.executeChangeEventSources(ChangeEventSourceCoordinator.java:137)
        at app//io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:109)
        at app//io.debezium.pipeline.ChangeEventSourceCoordinator$$Lambda$568/0x0000000800ff35c0.run(Unknown Source)
        at java.base@17.0.4.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base@17.0.4.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)

...


2023-03-20 09:23:22 [44msource[0m > ERROR i.a.i.b.AirbyteExceptionHandler(uncaughtException):26 Something went wrong in the connector. See the logs for more details. java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "419866627120"
	at io.airbyte.integrations.debezium.internals.DebeziumStateDecoratingIterator.computeNext(DebeziumStateDecoratingIterator.java:163) ~[io.airbyte.airbyte-integrations.bases-debezium-0.42.0.jar:?]
	at io.airbyte.integrations.debezium.internals.DebeziumStateDecoratingIterator.computeNext(DebeziumStateDecoratingIterator.java:27) ~[io.airbyte.airbyte-integrations.bases-debezium-0.42.0.jar:?]
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.1-jre.jar:?]
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38) ~[io.airbyte-airbyte-commons-0.42.0.jar:?]
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.1-jre.jar:?]
	at io.airbyte.commons.util.CompositeIterator.computeNext(CompositeIterator.java:63) ~[io.airbyte-airbyte-commons-0.42.0.jar:?]
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.1-jre.jar:?]
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38) ~[io.airbyte-airbyte-commons-0.42.0.jar:?]
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.1-jre.jar:?]
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38) ~[io.airbyte-airbyte-commons-0.42.0.jar:?]
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.1-jre.jar:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:132) ~[?:?]
	at io.airbyte.integrations.base.IntegrationRunner.lambda$produceMessages$0(IntegrationRunner.java:187) ~[io.airbyte.airbyte-integrations.bases-base-java-0.42.0.jar:?]
	at io.airbyte.integrations.base.IntegrationRunner.watchForOrphanThreads(IntegrationRunner.java:237) ~[io.airbyte.airbyte-integrations.bases-base-java-0.42.0.jar:?]
	at io.airbyte.integrations.base.IntegrationRunner.produceMessages(IntegrationRunner.java:186) ~[io.airbyte.airbyte-integrations.bases-base-java-0.42.0.jar:?]
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:139) ~[io.airbyte.airbyte-integrations.bases-base-java-0.42.0.jar:?]
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:98) ~[io.airbyte.airbyte-integrations.bases-base-java-0.42.0.jar:?]
	at io.airbyte.integrations.base.adaptive.AdaptiveSourceRunner$Runner.run(AdaptiveSourceRunner.java:86) ~[io.airbyte.airbyte-integrations.bases-base-java-0.42.0.jar:?]
	at io.airbyte.integrations.source.postgres.PostgresSourceRunner.main(PostgresSourceRunner.java:15) ~[io.airbyte.airbyte-integrations.connectors-source-postgres-0.42.0.jar:?]
Caused by: java.lang.NumberFormatException: For input string: "419866627120"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:786) ~[?:?]
	at io.airbyte.integrations.source.postgres.PostgresCdcStateHandler.isRecordBehindOffset(PostgresCdcStateHandler.java:84) ~[io.airbyte.airbyte-integrations.connectors-source-postgres-0.42.0.jar:?]
	at io.airbyte.integrations.debezium.internals.DebeziumStateDecoratingIterator.computeNext(DebeziumStateDecoratingIterator.java:157) ~[io.airbyte.airbyte-integrations.bases-debezium-0.42.0.jar:?]
	... 23 more

Stack Trace: java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "419866627120"
	at io.airbyte.integrations.debezium.internals.DebeziumStateDecoratingIterator.computeNext(DebeziumStateDecoratingIterator.java:163)
	at io.airbyte.integrations.debezium.internals.DebeziumStateDecoratingIterator.computeNext(DebeziumStateDecoratingIterator.java:27)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at io.airbyte.commons.util.CompositeIterator.computeNext(CompositeIterator.java:63)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
	at io.airbyte.integrations.base.IntegrationRunner.lambda$produceMessages$0(IntegrationRunner.java:187)
	at io.airbyte.integrations.base.IntegrationRunner.watchForOrphanThreads(IntegrationRunner.java:237)
	at io.airbyte.integrations.base.IntegrationRunner.produceMessages(IntegrationRunner.java:186)
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:139)
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:98)
	at io.airbyte.integrations.base.adaptive.AdaptiveSourceRunner$Runner.run(AdaptiveSourceRunner.java:86)
	at io.airbyte.integrations.source.postgres.PostgresSourceRunner.main(PostgresSourceRunner.java:15)
Caused by: java.lang.NumberFormatException: For input string: "419866627120"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at io.airbyte.integrations.source.postgres.PostgresCdcStateHandler.isRecordBehindOffset(PostgresCdcStateHandler.java:84)
	at io.airbyte.integrations.debezium.internals.DebeziumStateDecoratingIterator.computeNext(DebeziumStateDecoratingIterator.java:157)
	... 23 more

```

#### Other observations (may be related/unrelated)
Since upgrading to source-postgres V2, we have noticed an issue with the schema change feature:

<img width="642" alt="image" src="https://user-images.githubusercontent.com/93200565/226304497-99ebc869-d2c2-42a8-9f39-06a8ffcda9f5.png">

When we click the **"Review Changes"** button, the screen loads for moment but then returns:
**"No changes were detected in the source schema."**
<img width="489" alt="image" src="https://user-images.githubusercontent.com/93200565/226304562-be5640cf-5ec2-4847-b26d-1f6aa0ca9bac.png">

The **"non-breaking schema changes available"** notification continues to show on the connection but does not show any changes on the source when we click it.
<img width="330" alt="image" src="https://user-images.githubusercontent.com/93200565/226306762-fe504cd8-3ef1-4cf1-abcc-371c6f3e1a98.png">

## Expected Behavior
Source-postgres v2 should behave like v1 and read CDC data without exceptions like: `NumberFormatException`

## Are you willing to submit a PR?

Yes.

**Comment by CamiloAtencio** [comment]
Ive had this issue too and have fixed it. Im willing to share the code changes that fixed this for me.

**Comment by subodh1810** [comment]
I think this is no longer happening in the latest version of Postgres connector (version 2.0.19)! Am going to close the issue.
