### ISSUE TITLE
v.42.0 server still stuck in Micronaut crash loop

### ISSUE THREAD

**Issue by thenaturalist** [airbytehq/airbyte#24279]
## Environment
- **Airbyte version**:  0.42.0
- **OS Version / Instance**: EC2/ AWS Linux
- **Deployment**: Docker
- **Step where error happened**: Deploy 

## Current Behavior
Upon `docker-compose up -d`, the airbyte-server crashes in a loop

## Expected Behavior
The deployment works fine.

## Logs
```
2023-03-21 11:14:41,948 main INFO Loading mask data from '/seed/specs_secrets_mask.yaml

    ___    _      __          __
   /   |  (_)____/ /_  __  __/ /____
  / /| | / / ___/ __ \/ / / / __/ _ \
 / ___ |/ / /  / /_/ / /_/ / /_/  __/
/_/  |_/_/_/  /_.___/\__, /\__/\___/
                    /____/
        : airbyte-server :
--------------------------------------------------
 Will soon be available at http://localhost:8000/
--------------------------------------------------

  Micronaut (v3.8.6)

2023-03-21 11:14:43 INFO i.m.c.e.DefaultEnvironment(<init>):159 - Established active environments: [ec2, cloud, control-plane]
2023-03-21 11:14:44 INFO i.a.c.t.TemporalUtils(getTemporalClientWhenConnected):248 - Waiting for temporal server...
2023-03-21 11:14:44 WARN i.a.c.t.TemporalUtils(getTemporalClientWhenConnected):259 - Waiting for namespace default to be initialized in temporal...
2023-03-21 11:14:46 INFO i.t.s.WorkflowServiceStubsImpl(<init>):86 - Created WorkflowServiceStubs for channel: ManagedChannelOrphanWrapper{delegate=ManagedChannelImpl{logId=1, target=airbyte-temporal:7233}}
2023-03-21 11:14:52 INFO i.a.c.t.TemporalUtils(getTemporalClientWhenConnected):276 - Temporal namespace default initialized!
2023-03-21 11:14:53 ERROR i.m.r.Micronaut(handleStartupException):338 - Error starting Micronaut server: Bean definition [io.airbyte.server.apis.SourceDefinitionApiController] could not be loaded: Error instantiating bean of type  [io.airbyte.commons.temporal.TemporalClient]

Message: Unrecognized field "serve" (class io.airbyte.featureflag.ConfigFileFlag), not marked as ignorable (2 known properties: "enabled", "name"])
 at [Source: (File); line: 4, column: 3] (through reference chain: io.airbyte.featureflag.ConfigFileFlags["flags"]->java.util.ArrayList[0]->io.airbyte.featureflag.ConfigFileFlag["serve"])
Path Taken: new SourceDefinitionApiController(SourceDefinitionsHandler sourceDefinitionsHandler) --> new SourceDefinitionApiController([SourceDefinitionsHandler sourceDefinitionsHandler]) --> new SourceDefinitionsHandler(ConfigRepository configRepository,Supplier uuidSupplier,[SynchronousSchedulerClient schedulerSynchronousClient],AirbyteRemoteOssCatalog remoteOssCatalog,SourceHandler sourceHandler,AirbyteProtocolVersionRange protocolVersionRange) --> SynchronousSchedulerClient.synchronousSchedulerClient([TemporalClient temporalClient],JobTracker jobTracker,JobErrorReporter jobErrorReporter,OAuthConfigSupplier oAuthConfigSupplier,RouterService routerService,ConfigInjector configInjector) --> new TemporalClient(Path workspaceRoot,WorkflowClient client,WorkflowServiceStubs service,StreamResetPersistence streamResetPersistence,ConnectionManagerUtils connectionManagerUtils,NotificationUtils notificationUtils,StreamResetRecordsHelper streamResetRecordsHelper,[FeatureFlagClient featureFlagClient])
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.airbyte.server.apis.SourceDefinitionApiController] could not be loaded: Error instantiating bean of type  [io.airbyte.commons.temporal.TemporalClient]

Message: Unrecognized field "serve" (class io.airbyte.featureflag.ConfigFileFlag), not marked as ignorable (2 known properties: "enabled", "name"])
 at [Source: (File); line: 4, column: 3] (through reference chain: io.airbyte.featureflag.ConfigFileFlags["flags"]->java.util.ArrayList[0]->io.airbyte.featureflag.ConfigFileFlag["serve"])
Path Taken: new SourceDefinitionApiController(SourceDefinitionsHandler sourceDefinitionsHandler) --> new SourceDefinitionApiController([SourceDefinitionsHandler sourceDefinitionsHandler]) --> new SourceDefinitionsHandler(ConfigRepository configRepository,Supplier uuidSupplier,[SynchronousSchedulerClient schedulerSynchronousClient],AirbyteRemoteOssCatalog remoteOssCatalog,SourceHandler sourceHandler,AirbyteProtocolVersionRange protocolVersionRange) --> SynchronousSchedulerClient.synchronousSchedulerClient([TemporalClient temporalClient],JobTracker jobTracker,JobErrorReporter jobErrorReporter,OAuthConfigSupplier oAuthConfigSupplier,RouterService routerService,ConfigInjector configInjector) --> new TemporalClient(Path workspaceRoot,WorkflowClient client,WorkflowServiceStubs service,StreamResetPersistence streamResetPersistence,ConnectionManagerUtils connectionManagerUtils,NotificationUtils notificationUtils,StreamResetRecordsHelper streamResetRecordsHelper,[FeatureFlagClient featureFlagClient])
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1921) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:249) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3326) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3684) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:341) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:194) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:75) ~[micronaut-context-3.8.6.jar:3.8.6]
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:323) ~[micronaut-context-3.8.6.jar:3.8.6]
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:309) ~[micronaut-context-3.8.6.jar:3.8.6]
	at io.airbyte.server.Application.main(Application.java:15) ~[io.airbyte-airbyte-server-0.42.0.jar:?]
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.airbyte.commons.temporal.TemporalClient]

Message: Unrecognized field "serve" (class io.airbyte.featureflag.ConfigFileFlag), not marked as ignorable (2 known properties: "enabled", "name"])
 at [Source: (File); line: 4, column: 3] (through reference chain: io.airbyte.featureflag.ConfigFileFlags["flags"]->java.util.ArrayList[0]->io.airbyte.featureflag.ConfigFileFlag["serve"])
Path Taken: new SourceDefinitionApiController(SourceDefinitionsHandler sourceDefinitionsHandler) --> new SourceDefinitionApiController([SourceDefinitionsHandler sourceDefinitionsHandler]) --> new SourceDefinitionsHandler(ConfigRepository configRepository,Supplier uuidSupplier,[SynchronousSchedulerClient schedulerSynchronousClient],AirbyteRemoteOssCatalog remoteOssCatalog,SourceHandler sourceHandler,AirbyteProtocolVersionRange protocolVersionRange) --> SynchronousSchedulerClient.synchronousSchedulerClient([TemporalClient temporalClient],JobTracker jobTracker,JobErrorReporter jobErrorReporter,OAuthConfigSupplier oAuthConfigSupplier,RouterService routerService,ConfigInjector configInjector) --> new TemporalClient(Path workspaceRoot,WorkflowClient client,WorkflowServiceStubs service,StreamResetPersistence streamResetPersistence,ConnectionManagerUtils connectionManagerUtils,NotificationUtils notificationUtils,StreamResetRecordsHelper streamResetRecordsHelper,[FeatureFlagClient featureFlagClient])
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2367) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.airbyte.commons.temporal.$TemporalClient$Definition.build(Unknown Source) ~[io.airbyte-airbyte-commons-temporal-0.42.0.jar:?]
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.airbyte.server.config.$TemporalBeanFactory$SynchronousSchedulerClient3$Definition.build(Unknown Source) ~[io.airbyte-airbyte-server-0.42.0.jar:?]
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.airbyte.commons.server.handlers.$SourceDefinitionsHandler$Definition.build(Unknown Source) ~[io.airbyte-airbyte-commons-server-0.42.0.jar:?]
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.airbyte.server.apis.$SourceDefinitionApiController$Definition.build(Unknown Source) ~[io.airbyte-airbyte-server-0.42.0.jar:?]
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2746) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1915) ~[micronaut-inject-3.8.6.jar:3.8.6]
	... 9 more
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "serve" (class io.airbyte.featureflag.ConfigFileFlag), not marked as ignorable (2 known properties: "enabled", "name"])
 at [Source: (File); line: 4, column: 3] (through reference chain: io.airbyte.featureflag.ConfigFileFlags["flags"]->java.util.ArrayList[0]->io.airbyte.featureflag.ConfigFileFlag["serve"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61) ~[jackson-databind-2.14.1.jar:2.14.1]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1132) ~[jackson-databind-2.14.1.jar:2.14.1]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2202) ~[jackson-databind-2.14.1.jar:2.14.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1705) ~[jackson-databind-2.14.1.jar:2.14.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1655) ~[jackson-databind-2.14.1.jar:2.14.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:540) ~[jackson-databind-2.14.1.jar:2.14.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405) ~[jackson-databind-2.14.1.jar:2.14.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352) ~[jackson-databind-2.14.1.jar:2.14.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185) ~[jackson-databind-2.14.1.jar:2.14.1]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359) ~[jackson-databind-2.14.1.jar:2.14.1]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244) ~[jackson-databind-2.14.1.jar:2.14.1]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28) ~[jackson-databind-2.14.1.jar:2.14.1]
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542) ~[jackson-databind-2.14.1.jar:2.14.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:564) ~[jackson-databind-2.14.1.jar:2.14.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439) ~[jackson-databind-2.14.1.jar:2.14.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405) ~[jackson-databind-2.14.1.jar:2.14.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352) ~[jackson-databind-2.14.1.jar:2.14.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185) ~[jackson-databind-2.14.1.jar:2.14.1]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[jackson-databind-2.14.1.jar:2.14.1]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730) ~[jackson-databind-2.14.1.jar:2.14.1]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3562) ~[jackson-databind-2.14.1.jar:2.14.1]
	at io.airbyte.featureflag.ClientKt.readConfig(Client.kt:218) ~[io.airbyte-airbyte-featureflag-0.42.0.jar:?]
	at io.airbyte.featureflag.ClientKt.access$readConfig(Client.kt:1) ~[io.airbyte-airbyte-featureflag-0.42.0.jar:?]
	at io.airbyte.featureflag.ConfigFileClient.<init>(Client.kt:75) ~[io.airbyte-airbyte-featureflag-0.42.0.jar:?]
	at io.airbyte.featureflag.$ConfigFileClient$Definition.build(Unknown Source) ~[io.airbyte-airbyte-featureflag-0.42.0.jar:?]
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.airbyte.commons.temporal.$TemporalClient$Definition.build(Unknown Source) ~[io.airbyte-airbyte-commons-temporal-0.42.0.jar:?]
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.airbyte.server.config.$TemporalBeanFactory$SynchronousSchedulerClient3$Definition.build(Unknown Source) ~[io.airbyte-airbyte-server-0.42.0.jar:?]
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.airbyte.commons.server.handlers.$SourceDefinitionsHandler$Definition.build(Unknown Source) ~[io.airbyte-airbyte-commons-server-0.42.0.jar:?]
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.airbyte.server.apis.$SourceDefinitionApiController$Definition.build(Unknown Source) ~[io.airbyte-airbyte-server-0.42.0.jar:?]
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2746) ~[micronaut-inject-3.8.6.jar:3.8.6]
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1915) ~[micronaut-inject-3.8.6.jar:3.8.6]
	... 9 more
```

## Steps to Reproduce
1. Follow EC2 Deployment docs

**Comment by bjgbeelen** [comment]
Getting the same issue following the GCP docs

**Comment by vasilisgav** [comment]
Getting the same error, but it is not consistent, We are having multiple installations, and in some of them it works and in some of them it doesn't. Still searching why...

**Comment by vinaykarode** [comment]
getting same error too

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
