### ISSUE TITLE
Source MySQL: Sync Job fails

### ISSUE THREAD

**Issue by dimoschi** [airbytehq/airbyte#24419]
## Environment
- **Airbyte version**:  0.42.0
- **OS Version / Instance**: Digitalocean
- **Deployment**: Kubernetes
- **Source Connector and version**: MySQL 2.0.0
- **Destination Connector and version**: Snowflake
- **Step where error happened**: Sync job

## Current Behavior
The job has an error, continues to sync and normalize data and ends up with a failure after 3 attempts

## Expected Behavior
Job to succeed.

## Logs
[scheduler-logs.txt](https://github.com/airbytehq/airbyte/files/11054946/scheduler-logs.txt)
[server-logs.txt](https://github.com/airbytehq/airbyte/files/11054948/server-logs.txt)

```log
2023-03-23 14:42:29 [44msource[0m > INFO i.a.i.s.m.MySqlCdcTargetPosition(reachedTargetPosition):82 Signalling close because record's binlog file : mysql-binlog.003646 , position : 73299384 is after target file : mysql-binlog.003646 , target position : 73299026
2023-03-23 14:42:29 [44msource[0m > INFO i.a.i.d.i.DebeziumRecordIterator(computeNext):137 Closing: Change event reached target position
2023-03-23 14:42:29 [44msource[0m > INFO i.d.e.EmbeddedEngine(stop):1147 Stopping the embedded engine
2023-03-23 14:42:29 [44msource[0m > INFO i.d.e.EmbeddedEngine(stop):1155 Waiting for PT5M for connector to stop
2023-03-23 14:42:29 [44msource[0m > INFO i.d.e.EmbeddedEngine(run):945 Stopping the task and engine
2023-03-23 14:42:29 [44msource[0m > INFO i.d.c.c.BaseSourceTask(stop):265 Stopping down connector
2023-03-23 14:42:29 [44msource[0m > INFO i.d.p.ChangeEventSourceCoordinator(streamEvents):175 Finished streaming
2023-03-23 14:42:29 [44msource[0m > INFO i.d.c.m.MySqlStreamingChangeEventSource$ReaderThreadLifecycleListener(lambda$onDisconnect$0):1251 Stopped reading binlog after 0 events, last recorded offset: {transaction_id=null, ts_sec=1679582260, file=mysql-binlog.003648, pos=30825032, server_id=1, event=1}
2023-03-23 14:42:29 [44msource[0m > INFO i.d.j.JdbcConnection(lambda$doClose$4):946 Connection gracefully closed
2023-03-23 14:42:29 [44msource[0m > INFO o.a.k.c.s.FileOffsetBackingStore(stop):66 Stopped FileOffsetBackingStore
2023-03-23 14:42:29 [44msource[0m > INFO i.a.i.d.i.DebeziumRecordPublisher(lambda$start$1):73 Debezium engine shutdown.
2023-03-23 14:42:29 [44msource[0m > INFO i.a.i.d.i.DebeziumRecordPublisher(lambda$start$1):74 Stopping connector after error in the application's handler method: java.lang.InterruptedException
2023-03-23 14:42:29 [44msource[0m > INFO i.a.i.d.i.DebeziumRecordIterator(close):172 Closing: Iterator closing
2023-03-23 14:42:29 [44msource[0m > INFO i.a.i.s.r.AbstractDbSource(lambda$read$2):181 Closing database connection pool.
2023-03-23 14:42:29 [44msource[0m > INFO c.z.h.HikariDataSource(close):350 HikariPool-1 - Shutdown initiated...
2023-03-23 14:42:29 [44msource[0m > INFO c.z.h.HikariDataSource(close):352 HikariPool-1 - Shutdown completed.
2023-03-23 14:42:29 [44msource[0m > INFO i.a.i.s.r.AbstractDbSource(lambda$read$2):183 Closed database connection pool.
2023-03-23 14:42:29 [44msource[0m > ERROR i.a.i.b.AirbyteExceptionHandler(uncaughtException):26 Something went wrong in the connector. See the logs for more details. java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.InterruptedException
	at io.airbyte.integrations.debezium.internals.DebeziumRecordIterator.requestClose(DebeziumRecordIterator.java:196) ~[io.airbyte.airbyte-integrations.bases-debezium-0.41.0.jar:?]
	at io.airbyte.integrations.debezium.internals.DebeziumRecordIterator.computeNext(DebeziumRecordIterator.java:138) ~[io.airbyte.airbyte-integrations.bases-debezium-0.41.0.jar:?]
	at io.airbyte.integrations.debezium.internals.DebeziumRecordIterator.computeNext(DebeziumRecordIterator.java:40) ~[io.airbyte.airbyte-integrations.bases-debezium-0.41.0.jar:?]
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:46) ~[guava-31.1-jre.jar:?]
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38) ~[io.airbyte-airbyte-commons-0.41.0.jar:?]
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.1-jre.jar:?]
	at io.airbyte.commons.util.CompositeIterator.computeNext(CompositeIterator.java:63) ~[io.airbyte-airbyte-commons-0.41.0.jar:?]
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.1-jre.jar:?]
	at io.airbyte.commons.util.CompositeIterator.computeNext(CompositeIterator.java:63) ~[io.airbyte-airbyte-commons-0.41.0.jar:?]
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.1-jre.jar:?]
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38) ~[io.airbyte-airbyte-commons-0.41.0.jar:?]
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.1-jre.jar:?]
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38) ~[io.airbyte-airbyte-commons-0.41.0.jar:?]
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.1-jre.jar:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:132) ~[?:?]
	at io.airbyte.integrations.base.IntegrationRunner.lambda$produceMessages$0(IntegrationRunner.java:187) ~[io.airbyte.airbyte-integrations.bases-base-java-0.41.0.jar:?]
	at io.airbyte.integrations.base.IntegrationRunner.watchForOrphanThreads(IntegrationRunner.java:237) ~[io.airbyte.airbyte-integrations.bases-base-java-0.41.0.jar:?]
	at io.airbyte.integrations.base.IntegrationRunner.produceMessages(IntegrationRunner.java:186) ~[io.airbyte.airbyte-integrations.bases-base-java-0.41.0.jar:?]
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:139) ~[io.airbyte.airbyte-integrations.bases-base-java-0.41.0.jar:?]
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:98) ~[io.airbyte.airbyte-integrations.bases-base-java-0.41.0.jar:?]
	at io.airbyte.integrations.source.mysql.MySqlSource.main(MySqlSource.java:310) ~[io.airbyte.airbyte-integrations.connectors-source-mysql-0.41.0.jar:?]
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.InterruptedException
	at io.airbyte.integrations.debezium.internals.DebeziumRecordPublisher.close(DebeziumRecordPublisher.java:106) ~[io.airbyte.airbyte-integrations.bases-debezium-0.41.0.jar:?]
	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15) ~[io.airbyte-airbyte-commons-0.41.0.jar:?]
	at io.airbyte.integrations.debezium.internals.DebeziumRecordIterator.requestClose(DebeziumRecordIterator.java:194) ~[io.airbyte.airbyte-integrations.bases-debezium-0.41.0.jar:?]
	... 27 more
Caused by: java.lang.RuntimeException: java.lang.InterruptedException
	at io.airbyte.integrations.debezium.internals.DebeziumRecordPublisher.lambda$start$0(DebeziumRecordPublisher.java:68) ~[io.airbyte.airbyte-integrations.bases-debezium-0.41.0.jar:?]
	at io.debezium.embedded.ConvertingEngineBuilder.lambda$notifying$0(ConvertingEngineBuilder.java:75) ~[debezium-embedded-2.1.2.Final.jar:2.1.2.Final]
	at io.debezium.embedded.EmbeddedEngine$1.handleBatch(EmbeddedEngine.java:518) ~[debezium-embedded-2.1.2.Final.jar:2.1.2.Final]
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:913) ~[debezium-embedded-2.1.2.Final.jar:2.1.2.Final]
	at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:195) ~[debezium-embedded-2.1.2.Final.jar:2.1.2.Final]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1638) ~[?:?]
	at java.util.concurrent.LinkedBlockingQueue.put(LinkedBlockingQueue.java:343) ~[?:?]
	at io.airbyte.integrations.debezium.internals.DebeziumRecordPublisher.lambda$start$0(DebeziumRecordPublisher.java:65) ~[io.airbyte.airbyte-integrations.bases-debezium-0.41.0.jar:?]
	at io.debezium.embedded.ConvertingEngineBuilder.lambda$notifying$0(ConvertingEngineBuilder.java:75) ~[debezium-embedded-2.1.2.Final.jar:2.1.2.Final]
	at io.debezium.embedded.EmbeddedEngine$1.handleBatch(EmbeddedEngine.java:518) ~[debezium-embedded-2.1.2.Final.jar:2.1.2.Final]
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:913) ~[debezium-embedded-2.1.2.Final.jar:2.1.2.Final]
	at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:195) ~[debezium-embedded-2.1.2.Final.jar:2.1.2.Final]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

Stack Trace: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.InterruptedException
	at io.airbyte.integrations.debezium.internals.DebeziumRecordIterator.requestClose(DebeziumRecordIterator.java:196)
	at io.airbyte.integrations.debezium.internals.DebeziumRecordIterator.computeNext(DebeziumRecordIterator.java:138)
	at io.airbyte.integrations.debezium.internals.DebeziumRecordIterator.computeNext(DebeziumRecordIterator.java:40)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:46)
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at io.airbyte.commons.util.CompositeIterator.computeNext(CompositeIterator.java:63)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at io.airbyte.commons.util.CompositeIterator.computeNext(CompositeIterator.java:63)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
	at io.airbyte.integrations.base.IntegrationRunner.lambda$produceMessages$0(IntegrationRunner.java:187)
	at io.airbyte.integrations.base.IntegrationRunner.watchForOrphanThreads(IntegrationRunner.java:237)
	at io.airbyte.integrations.base.IntegrationRunner.produceMessages(IntegrationRunner.java:186)
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:139)
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:98)
	at io.airbyte.integrations.source.mysql.MySqlSource.main(MySqlSource.java:310)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.InterruptedException
	at io.airbyte.integrations.debezium.internals.DebeziumRecordPublisher.close(DebeziumRecordPublisher.java:106)
	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15)
	at io.airbyte.integrations.debezium.internals.DebeziumRecordIterator.requestClose(DebeziumRecordIterator.java:194)
	... 27 more
Caused by: java.lang.RuntimeException: java.lang.InterruptedException
	at io.airbyte.integrations.debezium.internals.DebeziumRecordPublisher.lambda$start$0(DebeziumRecordPublisher.java:68)
	at io.debezium.embedded.ConvertingEngineBuilder.lambda$notifying$0(ConvertingEngineBuilder.java:75)
	at io.debezium.embedded.EmbeddedEngine$1.handleBatch(EmbeddedEngine.java:518)
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:913)
	at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:195)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1638)
	at java.base/java.util.concurrent.LinkedBlockingQueue.put(LinkedBlockingQueue.java:343)
	at io.airbyte.integrations.debezium.internals.DebeziumRecordPublisher.lambda$start$0(DebeziumRecordPublisher.java:65)
	... 7 more

2023-03-23 14:42:29 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$readFromSrcAndWriteToDstRunnable$7):442 - Total records read: 41608 (22 MB)
```

## Are you willing to submit a PR?
Yes, but I wasn't able to pinpoint the issue

**Comment by dimoschi** [comment]
Seems very similar if not the same to this issue #17512

**Comment by prateekmukhedkar** [comment]
@dimoschi can you try upgrading the MySQL source connector to 3.x? We have made reliability improvements to CDC replication mode, both when taking initial snapshots and when reading incremental changes. Keep in mind 3.x upgrade is a breaking change from 2.0, we sent out comms in July for actions needed from you, please let me know if you need any help for upgrade.

**Comment by dimoschi** [comment]
@prateekmukhedkar We have upgraded the connector to `3.x` but we see similar issues when trying to sync specific tables that don't have a primary key (intermediate tables for many-to-many relationships). I will try to set up a new connection and check again and post the logs.
