### ISSUE TITLE
Does one have to publish the destination first then add basic normalization to it?

### ISSUE THREAD

**Issue by ChrisZou** [airbytehq/airbyte#24571]
Hi, I'm building a Java based destination connector for your database, and would like it to support basic normalization. I'm following the [guide here](https://docs.airbyte.com/connector-development/?_ga=2.4755315.1329325472.1679627444-130081057.1677825843#adding-normalization-to-a-connector), but run into an error when executing the command `./gradlew :airbyte-config:init:processResources`:

```
> Task :airbyte-config:specs:generateSeedConnectorSpecs FAILED
2023-03-27 16:12:56,026 main INFO Loading mask data from '/seed/specs_secrets_mask.yaml
2023-03-27 16:12:56,030 main ERROR Unable to load mask data from '/seed/specs_secrets_mask.yaml': null.
2023-03-27 08:12:56 INFO i.a.c.EnvConfigs(getEnvOrDefault):1173 - Using default value for environment variable SPEC_CACHE_BUCKET: 'io-airbyte-cloud-spec-cache'
2023-03-27 08:12:56 INFO i.a.c.s.SeedConnectorSpecGenerator(run):78 - Updating seeded SOURCE definition specs if necessary...
2023-03-27 08:12:56 INFO i.a.c.s.SeedConnectorSpecGenerator(run):90 - Finished updating /Users/myname/code/bytedance/airbyte/airbyte-config/init/src/main/resources/seed/source_specs.yaml
2023-03-27 08:12:56 INFO i.a.c.s.SeedConnectorSpecGenerator(run):78 - Updating seeded DESTINATION definition specs if necessary...
2023-03-27 08:12:56 INFO i.a.c.s.SeedConnectorSpecGenerator(fetchSpecFromGCS):119 - Seeded spec not found for docker image airbyte/destination-ourdestinationname:dev - fetching from GCS bucket io-airbyte-cloud-spec-cache...
Exception in thread "main" java.lang.RuntimeException: Failed to fetch valid spec file for docker image airbyte/destination-ourdestinationname:dev from GCS bucket io-airbyte-cloud-spec-cache. This will continue to fail until the connector change has been approved and published. See https://github.com/airbytehq/airbyte/tree/master/docs/connector-development#publishing-a-connector for more details.
        at io.airbyte.config.specs.SeedConnectorSpecGenerator.lambda$fetchSpecFromGCS$4(SeedConnectorSpecGenerator.java:121)
        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
        at io.airbyte.config.specs.SeedConnectorSpecGenerator.fetchSpecFromGCS(SeedConnectorSpecGenerator.java:121)
        at io.airbyte.config.specs.SeedConnectorSpecGenerator.lambda$fetchUpdatedSeedSpecs$3(SeedConnectorSpecGenerator.java:114)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at io.airbyte.config.specs.SeedConnectorSpecGenerator.fetchUpdatedSeedSpecs(SeedConnectorSpecGenerator.java:115)
        at io.airbyte.config.specs.SeedConnectorSpecGenerator.run(SeedConnectorSpecGenerator.java:83)
        at io.airbyte.config.specs.SeedConnectorSpecGenerator.main(SeedConnectorSpecGenerator.java:74)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':airbyte-config:specs:generateSeedConnectorSpecs'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk-19.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
```
I googled and found [this article](https://airbyte.com/tutorials/creating-duckdb-destination-with-python) which said this issues was expected since the destination was not published yet. Does that mean I have to publish our destination first then add basic normalization feature to it?
The connector definition I have is:

```
- name: Ourdestinationname
  destinationDefinitionId: db46a450-6873-4a95-a31e-e597c9242354
  dockerRepository: airbyte/destination-ourdestinationname
  dockerImageTag: dev
  documentationUrl: https://docs.airbyte.com/integrations/destinations/ourdestinationname
  icon: ourdestinationname.svg
  releaseStage: alpha
  normalizationConfig:
    normalizationRepository: airbyte/normalization
    normalizationTag: 0.2.25
    normalizationIntegrationType: ourdestinationname
```

Thank you!

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.
