### ISSUE TITLE
Source Google Ads: 0.2.13 new columns incremental failure

### ISSUE THREAD

**Issue by hanslemm** [airbytehq/airbyte#24631]
## Environment
- **Airbyte version**:  0.40.29
- **OS Version / Instance**: AWS EC2
- **Deployment**: Kubernetes
- **Source Connector and version**: Google Ads 0.2.13
- **Destination Connector and version**: Postgres 0.3.26
- **Step where error happened**: Sync job after Google Ads update

## Current Behavior
After updating the Google Ads Connector to 0.2.13 (#24338), some new columns were added to two streams. The new column names contain some points (`.` symbol), that if not escaped by wrapping the column name with `""` in Postgres queries, they are interpreted as database/schema/table separator. 
My `campaign` stream, which contains one of the new columns, is configured with `incremental + dedup`  sync. When the new column appeared during the sync, dbt tried to add the new column, but it failed, as the column name has invalid syntax (`.` in the name without wrapping the whole name with `""`).

## Logs

```
2023-03-28 00:03:06 [42mnormalization[0m > Found 70 models, 0 tests, 0 snapshots, 0 analyses, 579 macros, 0 operations, 0 seed files, 16 sources, 0 exposures, 0 metrics
2023-03-28 00:03:08 [42mnormalization[0m > Concurrency: 8 threads (target='prod')
2023-03-28 00:03:17 [42mnormalization[0m > 1 of 28 START incremental model _airbyte_raw.google_ads__ad_groups_stg.................................................. [RUN]
2023-03-28 00:03:19 [42mnormalization[0m > 2 of 28 START incremental model _airbyte_raw.google_ads__accounts_stg................................................... [RUN]
2023-03-28 00:03:20 [42mnormalization[0m > 3 of 28 START table model raw.google_ads__ad_group_ad_labels............................................................ [RUN]
2023-03-28 00:03:21 [42mnormalization[0m > 4 of 28 START table model raw.google_ads__ad_group_labels............................................................... [RUN]
2023-03-28 00:03:21 [42mnormalization[0m > 5 of 28 START incremental model _airbyte_raw.google_ads__click_view_stg................................................. [RUN]
2023-03-28 00:03:22 [42mnormalization[0m > 6 of 28 START table model raw.google_ads__campaign_labels............................................................... [RUN]
2023-03-28 00:03:23 [42mnormalization[0m > 7 of 28 START incremental model _airbyte_raw.google_ads__account_performance_report_stg................................. [RUN]
2023-03-28 00:03:24 [42mnormalization[0m > 8 of 28 START incremental model _airbyte_raw.google_ads__user_location_report_stg....................................... [RUN]
2023-03-28 00:03:24 [42mnormalization[0m > 3 of 28 OK created table model raw.google_ads__ad_group_ad_labels....................................................... [[32mSELECT 40[0m in 3.89s]
2023-03-28 00:03:24 [42mnormalization[0m > 4 of 28 OK created table model raw.google_ads__ad_group_labels.......................................................... [[32mSELECT 0[0m in 3.35s]
2023-03-28 00:03:24 [42mnormalization[0m > 9 of 28 START incremental model _airbyte_raw.google_ads__campaigns_stg.................................................. [RUN]
2023-03-28 00:03:24 [42mnormalization[0m > 6 of 28 OK created table model raw.google_ads__campaign_labels.......................................................... [[32mSELECT 64[0m in 2.50s]
2023-03-28 00:03:24 [42mnormalization[0m > 10 of 28 START table model raw.google_ads__geographic_report............................................................ [RUN]
2023-03-28 00:03:26 [42mnormalization[0m > 2 of 28 OK created incremental model _airbyte_raw.google_ads__accounts_stg.............................................. [[32mINSERT 0 15[0m in 7.04s]
2023-03-28 00:03:28 [42mnormalization[0m > 10 of 28 OK created table model raw.google_ads__geographic_report....................................................... [[32mSELECT 40219[0m in 3.38s]
2023-03-28 00:03:28 [42mnormalization[0m > 1 of 28 ERROR creating incremental model _airbyte_raw.google_ads__ad_groups_stg......................................... [[31mERROR[0m in 11.43s]
2023-03-28 00:03:28 [42mnormalization[0m > 11 of 28 START table model raw.google_ads__keyword_report............................................................... [RUN]
2023-03-28 00:03:33 [42mnormalization[0m > 7 of 28 OK created incremental model _airbyte_raw.google_ads__account_performance_report_stg............................ [[32mINSERT 0 73[0m in 9.83s]
2023-03-28 00:03:34 [42mnormalization[0m > 12 of 28 START incremental model raw.google_ads__accounts_scd........................................................... [RUN]
2023-03-28 00:03:35 [42mnormalization[0m > 11 of 28 OK created table model raw.google_ads__keyword_report.......................................................... [[32mSELECT 125670[0m in 6.62s]
2023-03-28 00:03:35 [42mnormalization[0m > 13 of 28 SKIP relation raw.google_ads__ad_groups_scd.................................................................... [[33mSKIP[0m]
2023-03-28 00:03:35 [42mnormalization[0m > 14 of 28 START table model raw.google_ads__shopping_performance_report.................................................. [RUN]
2023-03-28 00:03:36 [42mnormalization[0m > 15 of 28 START incremental model raw.google_ads__account_performance_report_scd......................................... [RUN]
2023-03-28 00:03:38 [42mnormalization[0m > 14 of 28 OK created table model raw.google_ads__shopping_performance_report............................................. [[32mSELECT 0[0m in 2.69s]
2023-03-28 00:03:38 [42mnormalization[0m > 16 of 28 START table model raw.google_ads__display___rd_performance_report.............................................. [RUN]
2023-03-28 00:03:43 [42mnormalization[0m > 8 of 28 OK created incremental model _airbyte_raw.google_ads__user_location_report_stg.................................. [[32mINSERT 0 6535[0m in 18.50s]
2023-03-28 00:03:43 [42mnormalization[0m > 16 of 28 OK created table model raw.google_ads__display___rd_performance_report......................................... [[32mSELECT 0[0m in 4.10s]
2023-03-28 00:03:43 [42mnormalization[0m > 17 of 28 START table model raw.google_ads__display___cs_performance_report.............................................. [RUN]
2023-03-28 00:03:43 [42mnormalization[0m > 18 of 28 SKIP relation raw.google_ads__ad_groups........................................................................ [[33mSKIP[0m]
2023-03-28 00:03:43 [42mnormalization[0m > 12 of 28 OK created incremental model raw.google_ads__accounts_scd...................................................... [[32mINSERT 0 28[0m in 9.08s]
2023-03-28 00:03:43 [42mnormalization[0m > 19 of 28 START incremental model raw.google_ads__user_location_report_scd............................................... [RUN]
2023-03-28 00:03:44 [42mnormalization[0m > 20 of 28 START incremental model raw.google_ads__accounts............................................................... [RUN]
2023-03-28 00:03:44 [42mnormalization[0m > 21 of 28 START table model raw.google_ads__ad_group_ads................................................................. [RUN]
2023-03-28 00:03:44 [42mnormalization[0m > 22 of 28 START table model raw.google_ads__ad_group_ad_report........................................................... [RUN]
2023-03-28 00:03:44 [42mnormalization[0m > 15 of 28 OK created incremental model raw.google_ads__account_performance_report_scd.................................... [[32mINSERT 0 144[0m in 8.59s]
2023-03-28 00:03:44 [42mnormalization[0m > 23 of 28 START incremental model raw.google_ads__account_performance_report............................................. [RUN]
2023-03-28 00:03:45 [42mnormalization[0m > 17 of 28 OK created table model raw.google_ads__display___cs_performance_report......................................... [[32mSELECT 0[0m in 2.13s]
2023-03-28 00:03:45 [42mnormalization[0m > 20 of 28 OK created incremental model raw.google_ads__accounts.......................................................... [[32mINSERT 0 14[0m in 1.88s]
2023-03-28 00:03:46 [42mnormalization[0m > 23 of 28 OK created incremental model raw.google_ads__account_performance_report........................................ [[32mINSERT 0 72[0m in 1.34s]
2023-03-28 00:03:54 [42mnormalization[0m > 5 of 28 OK created incremental model _airbyte_raw.google_ads__click_view_stg............................................ [[32mINSERT 0 48347[0m in 32.68s]
2023-03-28 00:03:54 [42mnormalization[0m > 24 of 28 START incremental model raw.google_ads__click_view_scd......................................................... [RUN]
2023-03-28 00:04:15 [42mnormalization[0m > 19 of 28 OK created incremental model raw.google_ads__user_location_report_scd.......................................... [[32mINSERT 0 13068[0m in 31.57s]
2023-03-28 00:04:15 [42mnormalization[0m > 25 of 28 START incremental model raw.google_ads__user_location_report................................................... [RUN]
2023-03-28 00:04:20 [42mnormalization[0m > 25 of 28 OK created incremental model raw.google_ads__user_location_report.............................................. [[32mINSERT 0 6534[0m in 4.82s]
2023-03-28 00:06:19 [42mnormalization[0m > 24 of 28 OK created incremental model raw.google_ads__click_view_scd.................................................... [[32mINSERT 0 96674[0m in 144.94s]
2023-03-28 00:06:19 [42mnormalization[0m > 26 of 28 START incremental model raw.google_ads__click_view............................................................. [RUN]
2023-03-28 00:06:35 [42mnormalization[0m > 26 of 28 OK created incremental model raw.google_ads__click_view........................................................ [[32mINSERT 0 48346[0m in 15.73s]
2023-03-28 00:08:00 [42mnormalization[0m > 9 of 28 ERROR creating incremental model _airbyte_raw.google_ads__campaigns_stg......................................... [[31mERROR[0m in 276.22s]
2023-03-28 00:08:01 [42mnormalization[0m > 27 of 28 SKIP relation raw.google_ads__campaigns_scd.................................................................... [[33mSKIP[0m]
2023-03-28 00:08:01 [42mnormalization[0m > 28 of 28 SKIP relation raw.google_ads__campaigns........................................................................ [[33mSKIP[0m]
2023-03-28 00:08:21 [42mnormalization[0m > 21 of 28 OK created table model raw.google_ads__ad_group_ads............................................................ [[32mSELECT 26007[0m in 276.59s]
2023-03-28 00:09:25 [32mINFO[m i.a.w.n.NormalizationAirbyteStreamFactory(filterOutAndHandleNonAirbyteMessageLines):104 - 
2023-03-28 00:09:25 [32mINFO[m i.a.w.n.NormalizationAirbyteStreamFactory(filterOutAndHandleNonAirbyteMessageLines):104 - 
2023-03-28 00:09:29 [32mINFO[m i.a.w.n.NormalizationAirbyteStreamFactory(filterOutAndHandleNonAirbyteMessageLines):104 - 
2023-03-28 00:09:29 [32mINFO[m i.a.w.n.NormalizationAirbyteStreamFactory(filterOutAndHandleNonAirbyteMessageLines):104 - 
2023-03-28 00:09:29 [32mINFO[m i.a.w.n.NormalizationAirbyteStreamFactory(filterOutAndHandleNonAirbyteMessageLines):104 - 
2023-03-28 00:09:29 [32mINFO[m i.a.w.n.NormalizationAirbyteStreamFactory(filterOutAndHandleNonAirbyteMessageLines):104 - 
2023-03-28 00:09:30 [32mINFO[m i.a.w.n.NormalizationAirbyteStreamFactory(filterOutAndHandleNonAirbyteMessageLines):104 - 
2023-03-28 00:09:30 [32mINFO[m i.a.w.n.NormalizationAirbyteStreamFactory(filterOutAndHandleNonAirbyteMessageLines):104 - 
2023-03-28 00:09:30 [32mINFO[m i.a.w.p.KubePodProcess(close):721 - (pod: dataplatform-production / normalization-normalize-86-2-bnnoa) - Closed all resources for pod
2023-03-28 00:09:30 [32mINFO[m i.a.w.n.DefaultNormalizationRunner(close):189 - Terminating normalization process...
2023-03-28 00:09:30 [1;31mERROR[m i.a.w.g.DefaultNormalizationWorker(run):83 - Normalization failed for job 86.
io.airbyte.workers.exception.WorkerException: Normalization process did not terminate normally (exit code: 1)
	at io.airbyte.workers.normalization.DefaultNormalizationRunner.close(DefaultNormalizationRunner.java:200) ~[io.airbyte-airbyte-commons-worker-0.40.29.jar:?]
	at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:81) ~[io.airbyte-airbyte-commons-worker-0.40.29.jar:?]
	at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:34) ~[io.airbyte-airbyte-commons-worker-0.40.29.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$5(TemporalAttemptExecution.java:195) ~[io.airbyte-airbyte-workers-0.40.29.jar:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
2023-03-28 00:09:30 [32mINFO[m i.a.w.g.DefaultNormalizationWorker(run):94 - Normalization executed in 7 minutes 25 seconds for job 86.
2023-03-28 00:09:30 [32mINFO[m i.a.w.g.DefaultNormalizationWorker(run):106 - Normalization summary: io.airbyte.config.NormalizationSummary@77b5acea[startTime=1679961725602,endTime=1679962170871,failures=[io.airbyte.config.FailureReason@12885c67[failureOrigin=normalization,failureType=system_error,internalMessage=syntax error at or near "."
LINE 6:                add column ad_group.optimized_targeting_enabl...,externalMessage=Normalization failed during the dbt run. This may indicate a problem with the data itself.,metadata=io.airbyte.config.Metadata@34639261[additionalProperties={attemptNumber=2, jobId=86, from_trace_message=true}],stacktrace=AirbyteDbtError: 
1 of 28 ERROR creating incremental model _airbyte_raw.google_ads__ad_groups_stg......................................... [[31mERROR[0m in 11.43s]
9 of 28 ERROR creating incremental model _airbyte_raw.google_ads__campaigns_stg......................................... [[31mERROR[0m in 276.22s]
[33mDatabase Error in model google_ads__ad_groups_stg (models/generated/airbyte_incremental/raw/google_ads__ad_groups_stg.sql)[0m
  syntax error at or near "."
  LINE 6:                add column ad_group.optimized_targeting_enabl...
                                            ^
[33mDatabase Error in model google_ads__campaigns_stg (models/generated/airbyte_incremental/raw/google_ads__campaigns_stg.sql)[0m
  syntax error at or near "."
  LINE 6:                add column campaign.target_cpm.__quency_goal....
                                            ^
1 of 28 ERROR creating incremental model _airbyte_raw.google_ads__ad_groups_stg......................................... [[31mERROR[0m in 11.43s]
9 of 28 ERROR creating incremental model _airbyte_raw.google_ads__campaigns_stg......................................... [[31mERROR[0m in 276.22s]
[33mDatabase Error in model google_ads__ad_groups_stg (models/generated/airbyte_incremental/raw/google_ads__ad_groups_stg.sql)[0m
  syntax error at or near "."
  LINE 6:                add column ad_group.optimized_targeting_enabl...
                                            ^
[33mDatabase Error in model google_ads__campaigns_stg (models/generated/airbyte_incremental/raw/google_ads__campaigns_stg.sql)[0m
  syntax error at or near "."
  LINE 6:                add column campaign.target_cpm.__quency_goal....
                                            ^,retryable=<null>,timestamp=1679962170353], io.airbyte.config.FailureReason@e0b1701[failureOrigin=normalization,failureType=system_error,internalMessage=syntax error at or near "."
LINE 6:                add column ad_group.optimized_targeting_enabl...,externalMessage=Normalization failed during the dbt run. This may indicate a problem with the data itself.,metadata=io.airbyte.config.Metadata@540338d6[additionalProperties={attemptNumber=2, jobId=86, from_trace_message=true}],stacktrace=AirbyteDbtError: 
1 of 28 ERROR creating incremental model _airbyte_raw.google_ads__ad_groups_stg......................................... [[31mERROR[0m in 11.43s]
9 of 28 ERROR creating incremental model _airbyte_raw.google_ads__campaigns_stg......................................... [[31mERROR[0m in 276.22s]
[33mDatabase Error in model google_ads__ad_groups_stg (models/generated/airbyte_incremental/raw/google_ads__ad_groups_stg.sql)[0m
  syntax error at or near "."
  LINE 6:                add column ad_group.optimized_targeting_enabl...
                                            ^
[33mDatabase Error in model google_ads__campaigns_stg (models/generated/airbyte_incremental/raw/google_ads__campaigns_stg.sql)[0m
  syntax error at or near "."
  LINE 6:                add column campaign.target_cpm.__quency_goal....
                                            ^
1 of 28 ERROR creating incremental model _airbyte_raw.google_ads__ad_groups_stg......................................... [[31mERROR[0m in 11.43s]
9 of 28 ERROR creating incremental model _airbyte_raw.google_ads__campaigns_stg......................................... [[31mERROR[0m in 276.22s]
[33mDatabase Error in model google_ads__ad_groups_stg (models/generated/airbyte_incremental/raw/google_ads__ad_groups_stg.sql)[0m
  syntax error at or near "."
  LINE 6:                add column ad_group.optimized_targeting_enabl...
                                            ^
[33mDatabase Error in model google_ads__campaigns_stg (models/generated/airbyte_incremental/raw/google_ads__campaigns_stg.sql)[0m
  syntax error at or near "."
  LINE 6:                add column campaign.target_cpm.__quency_goal....
                                            ^,retryable=<null>,timestamp=1679962170353]]]
2023-03-28 00:09:30 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):163 - Stopping cancellation check scheduling...
2023-03-28 00:09:30 [32mINFO[m i.a.c.i.LineGobbler(voidCall):114 - 
2023-03-28 00:09:30 [32mINFO[m i.a.c.i.LineGobbler(voidCall):114 - ----- END DEFAULT NORMALIZATION -----
2023-03-28 00:09:30 [32mINFO[m i.a.c.t.TemporalUtils(withBackgroundHeartbeat):283 - Stopping temporal heartbeating...
2023-03-28 00:09:30 [32mINFO[m i.a.c.i.LineGobbler(voidCall):114 - 
2023-03-28 00:09:24 [42mnormalization[0m > 22 of 28 OK created table model raw.google_ads__ad_group_ad_report...................................................... [[32mSELECT 43319[0m in 339.93s]
2023-03-28 00:09:24 [42mnormalization[0m > Finished running 10 table models, 18 incremental models in 378.30s.
2023-03-28 00:09:24 [42mnormalization[0m > [31mCompleted with 2 errors and 0 warnings:[0m
2023-03-28 00:09:24 [42mnormalization[0m > [33mDatabase Error in model google_ads__ad_groups_stg (models/generated/airbyte_incremental/raw/google_ads__ad_groups_stg.sql)[0m
2023-03-28 00:09:24 [42mnormalization[0m >   syntax error at or near "."
2023-03-28 00:09:24 [42mnormalization[0m >   LINE 6:                add column ad_group.optimized_targeting_enabl...
2023-03-28 00:09:24 [42mnormalization[0m >                                             ^
2023-03-28 00:09:24 [42mnormalization[0m > [33mDatabase Error in model google_ads__campaigns_stg (models/generated/airbyte_incremental/raw/google_ads__campaigns_stg.sql)[0m
2023-03-28 00:09:24 [42mnormalization[0m >   syntax error at or near "."
2023-03-28 00:09:24 [42mnormalization[0m >   LINE 6:                add column campaign.target_cpm.__quency_goal....
2023-03-28 00:09:24 [42mnormalization[0m >                                             ^
2023-03-28 00:09:24 [42mnormalization[0m > Done. PASS=22 WARN=0 ERROR=2 SKIP=4 TOTAL=28
2023-03-28 00:09:25 [42mnormalization[0m > Diagnosing dbt debug to check if destination is available for dbt and well configured (1):
2023-03-28 00:09:29 [42mnormalization[0m > 00:09:29  Running with dbt=1.0.0
2023-03-28 00:09:29 [42mnormalization[0m > dbt version: 1.0.0
2023-03-28 00:09:29 [42mnormalization[0m > python version: 3.9.9
2023-03-28 00:09:29 [42mnormalization[0m > python path: /usr/local/bin/python
2023-03-28 00:09:29 [42mnormalization[0m > os info: Linux-5.4.226-129.415.amzn2.x86_64-x86_64-with-glibc2.31
2023-03-28 00:09:29 [42mnormalization[0m > Using profiles.yml file at /config/profiles.yml
2023-03-28 00:09:29 [42mnormalization[0m > Using dbt_project.yml file at /config/dbt_project.yml
2023-03-28 00:09:29 [42mnormalization[0m > Configuration:
2023-03-28 00:09:29 [42mnormalization[0m >   profiles.yml file [OK found and valid]
2023-03-28 00:09:29 [42mnormalization[0m >   dbt_project.yml file [OK found and valid]
2023-03-28 00:09:29 [42mnormalization[0m > Required dependencies:
2023-03-28 00:09:29 [42mnormalization[0m >  - git [OK found]
2023-03-28 00:09:29 [42mnormalization[0m > Connection:
2023-03-28 00:09:29 [42mnormalization[0m >   host: xxxx
2023-03-28 00:09:29 [42mnormalization[0m >   port: 5432
2023-03-28 00:09:29 [42mnormalization[0m >   user: xxxx
2023-03-28 00:09:29 [42mnormalization[0m >   database: xxxx
2023-03-28 00:09:29 [42mnormalization[0m >   schema: raw
2023-03-28 00:09:29 [42mnormalization[0m >   search_path: None
2023-03-28 00:09:29 [42mnormalization[0m >   keepalives_idle: 0
2023-03-28 00:09:29 [42mnormalization[0m >   sslmode: None
2023-03-28 00:09:29 [42mnormalization[0m >   Connection test: [OK connection ok]
2023-03-28 00:09:29 [42mnormalization[0m > All checks passed!
2023-03-28 00:09:30 [42mnormalization[0m > Forward dbt output logs to diagnose/debug errors (0):
2023-03-28 00:09:30 [42mnormalization[0m > Running with dbt=1.0.0
2023-03-28 00:09:30 [42mnormalization[0m > Partial parse save file not found. Starting full parse.
2023-03-28 00:09:30 [42mnormalization[0m > [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.airbyte_utils.generated.airbyte_views

2023-03-28 00:09:30 [42mnormalization[0m > Found 70 models, 0 tests, 0 snapshots, 0 analyses, 579 macros, 0 operations, 0 seed files, 16 sources, 0 exposures, 0 metrics
2023-03-28 00:09:30 [42mnormalization[0m > Concurrency: 8 threads (target='prod')
2023-03-28 00:09:30 [42mnormalization[0m > 1 of 28 START incremental model _airbyte_raw.google_ads__ad_groups_stg.................................................. [RUN]
2023-03-28 00:09:30 [42mnormalization[0m > 2 of 28 START incremental model _airbyte_raw.google_ads__accounts_stg................................................... [RUN]
2023-03-28 00:09:30 [42mnormalization[0m > 3 of 28 START table model raw.google_ads__ad_group_ad_labels............................................................ [RUN]
2023-03-28 00:09:30 [42mnormalization[0m > 4 of 28 START table model raw.google_ads__ad_group_labels............................................................... [RUN]
2023-03-28 00:09:30 [42mnormalization[0m > 5 of 28 START incremental model _airbyte_raw.google_ads__click_view_stg................................................. [RUN]
2023-03-28 00:09:30 [42mnormalization[0m > 6 of 28 START table model raw.google_ads__campaign_labels............................................................... [RUN]
2023-03-28 00:09:30 [42mnormalization[0m > 7 of 28 START incremental model _airbyte_raw.google_ads__account_performance_report_stg................................. [RUN]
2023-03-28 00:09:30 [42mnormalization[0m > 8 of 28 START incremental model _airbyte_raw.google_ads__user_location_report_stg....................................... [RUN]
2023-03-28 00:09:30 [42mnormalization[0m > 3 of 28 OK created table model raw.google_ads__ad_group_ad_labels....................................................... [[32mSELECT 40[0m in 3.89s]
2023-03-28 00:09:30 [42mnormalization[0m > 4 of 28 OK created table model raw.google_ads__ad_group_labels.......................................................... [[32mSELECT 0[0m in 3.35s]
2023-03-28 00:09:30 [42mnormalization[0m > 9 of 28 START incremental model _airbyte_raw.google_ads__campaigns_stg.................................................. [RUN]
2023-03-28 00:09:30 [42mnormalization[0m > 6 of 28 OK created table model raw.google_ads__campaign_labels.......................................................... [[32mSELECT 64[0m in 2.50s]
2023-03-28 00:09:30 [42mnormalization[0m > 10 of 28 START table model raw.google_ads__geographic_report............................................................ [RUN]
2023-03-28 00:09:30 [42mnormalization[0m > 2 of 28 OK created incremental model _airbyte_raw.google_ads__accounts_stg.............................................. [[32mINSERT 0 15[0m in 7.04s]
2023-03-28 00:09:30 [42mnormalization[0m > 10 of 28 OK created table model raw.google_ads__geographic_report....................................................... [[32mSELECT 40219[0m in 3.38s]
2023-03-28 00:09:30 [42mnormalization[0m > 1 of 28 ERROR creating incremental model _airbyte_raw.google_ads__ad_groups_stg......................................... [[31mERROR[0m in 11.43s]
2023-03-28 00:09:30 [42mnormalization[0m > 11 of 28 START table model raw.google_ads__keyword_report............................................................... [RUN]
2023-03-28 00:09:30 [42mnormalization[0m > 7 of 28 OK created incremental model _airbyte_raw.google_ads__account_performance_report_stg............................ [[32mINSERT 0 73[0m in 9.83s]
2023-03-28 00:09:30 [42mnormalization[0m > 12 of 28 START incremental model raw.google_ads__accounts_scd........................................................... [RUN]
2023-03-28 00:09:30 [42mnormalization[0m > 11 of 28 OK created table model raw.google_ads__keyword_report.......................................................... [[32mSELECT 125670[0m in 6.62s]
2023-03-28 00:09:30 [42mnormalization[0m > 13 of 28 SKIP relation raw.google_ads__ad_groups_scd.................................................................... [[33mSKIP[0m]
2023-03-28 00:09:30 [42mnormalization[0m > 14 of 28 START table model raw.google_ads__shopping_performance_report.................................................. [RUN]
2023-03-28 00:09:30 [42mnormalization[0m > 15 of 28 START incremental model raw.google_ads__account_performance_report_scd......................................... [RUN]
2023-03-28 00:09:30 [42mnormalization[0m > 14 of 28 OK created table model raw.google_ads__shopping_performance_report............................................. [[32mSELECT 0[0m in 2.69s]
2023-03-28 00:09:30 [42mnormalization[0m > 16 of 28 START table model raw.google_ads__display___rd_performance_report.............................................. [RUN]
2023-03-28 00:09:30 [42mnormalization[0m > 8 of 28 OK created incremental model _airbyte_raw.google_ads__user_location_report_stg.................................. [[32mINSERT 0 6535[0m in 18.50s]
2023-03-28 00:09:30 [42mnormalization[0m > 16 of 28 OK created table model raw.google_ads__display___rd_performance_report......................................... [[32mSELECT 0[0m in 4.10s]
2023-03-28 00:09:30 [42mnormalization[0m > 17 of 28 START table model raw.google_ads__display___cs_performance_report.............................................. [RUN]
2023-03-28 00:09:30 [42mnormalization[0m > 18 of 28 SKIP relation raw.google_ads__ad_groups........................................................................ [[33mSKIP[0m]
2023-03-28 00:09:30 [42mnormalization[0m > 12 of 28 OK created incremental model raw.google_ads__accounts_scd...................................................... [[32mINSERT 0 28[0m in 9.08s]
2023-03-28 00:09:30 [42mnormalization[0m > 19 of 28 START incremental model raw.google_ads__user_location_report_scd............................................... [RUN]
2023-03-28 00:09:30 [42mnormalization[0m > 20 of 28 START incremental model raw.google_ads__accounts............................................................... [RUN]
2023-03-28 00:09:30 [42mnormalization[0m > 21 of 28 START table model raw.google_ads__ad_group_ads................................................................. [RUN]
2023-03-28 00:09:30 [42mnormalization[0m > 22 of 28 START table model raw.google_ads__ad_group_ad_report........................................................... [RUN]
2023-03-28 00:09:30 [42mnormalization[0m > 15 of 28 OK created incremental model raw.google_ads__account_performance_report_scd.................................... [[32mINSERT 0 144[0m in 8.59s]
2023-03-28 00:09:30 [42mnormalization[0m > 23 of 28 START incremental model raw.google_ads__account_performance_report............................................. [RUN]
2023-03-28 00:09:30 [42mnormalization[0m > 17 of 28 OK created table model raw.google_ads__display___cs_performance_report......................................... [[32mSELECT 0[0m in 2.13s]
2023-03-28 00:09:30 [42mnormalization[0m > 20 of 28 OK created incremental model raw.google_ads__accounts.......................................................... [[32mINSERT 0 14[0m in 1.88s]
2023-03-28 00:09:30 [42mnormalization[0m > 23 of 28 OK created incremental model raw.google_ads__account_performance_report........................................ [[32mINSERT 0 72[0m in 1.34s]
2023-03-28 00:09:30 [42mnormalization[0m > 5 of 28 OK created incremental model _airbyte_raw.google_ads__click_view_stg............................................ [[32mINSERT 0 48347[0m in 32.68s]
2023-03-28 00:09:30 [42mnormalization[0m > 24 of 28 START incremental model raw.google_ads__click_view_scd......................................................... [RUN]
2023-03-28 00:09:30 [42mnormalization[0m > 19 of 28 OK created incremental model raw.google_ads__user_location_report_scd.......................................... [[32mINSERT 0 13068[0m in 31.57s]
2023-03-28 00:09:30 [42mnormalization[0m > 25 of 28 START incremental model raw.google_ads__user_location_report................................................... [RUN]
2023-03-28 00:09:30 [42mnormalization[0m > 25 of 28 OK created incremental model raw.google_ads__user_location_report.............................................. [[32mINSERT 0 6534[0m in 4.82s]
2023-03-28 00:09:30 [42mnormalization[0m > 24 of 28 OK created incremental model raw.google_ads__click_view_scd.................................................... [[32mINSERT 0 96674[0m in 144.94s]
2023-03-28 00:09:30 [42mnormalization[0m > 26 of 28 START incremental model raw.google_ads__click_view............................................................. [RUN]
2023-03-28 00:09:30 [42mnormalization[0m > 26 of 28 OK created incremental model raw.google_ads__click_view........................................................ [[32mINSERT 0 48346[0m in 15.73s]
2023-03-28 00:09:30 [42mnormalization[0m > 9 of 28 ERROR creating incremental model _airbyte_raw.google_ads__campaigns_stg......................................... [[31mERROR[0m in 276.22s]
2023-03-28 00:09:30 [42mnormalization[0m > 27 of 28 SKIP relation raw.google_ads__campaigns_scd.................................................................... [[33mSKIP[0m]
2023-03-28 00:09:30 [42mnormalization[0m > 28 of 28 SKIP relation raw.google_ads__campaigns........................................................................ [[33mSKIP[0m]
2023-03-28 00:09:30 [42mnormalization[0m > 21 of 28 OK created table model raw.google_ads__ad_group_ads............................................................ [[32mSELECT 26007[0m in 276.59s]
2023-03-28 00:09:30 [42mnormalization[0m > 22 of 28 OK created table model raw.google_ads__ad_group_ad_report...................................................... [[32mSELECT 43319[0m in 339.93s]
2023-03-28 00:09:30 [42mnormalization[0m > Finished running 10 table models, 18 incremental models in 378.30s.
2023-03-28 00:09:30 [42mnormalization[0m > [31mCompleted with 2 errors and 0 warnings:[0m
2023-03-28 00:09:30 [42mnormalization[0m > [33mDatabase Error in model google_ads__ad_groups_stg (models/generated/airbyte_incremental/raw/google_ads__ad_groups_stg.sql)[0m
2023-03-28 00:09:30 [42mnormalization[0m >   syntax error at or near "."
2023-03-28 00:09:30 [42mnormalization[0m >   LINE 6:                add column ad_group.optimized_targeting_enabl...
2023-03-28 00:09:30 [42mnormalization[0m >                                             ^
2023-03-28 00:09:30 [42mnormalization[0m > [33mDatabase Error in model google_ads__campaigns_stg (models/generated/airbyte_incremental/raw/google_ads__campaigns_stg.sql)[0m
2023-03-28 00:09:30 [42mnormalization[0m >   syntax error at or near "."
2023-03-28 00:09:30 [42mnormalization[0m >   LINE 6:                add column campaign.target_cpm.__quency_goal....
2023-03-28 00:09:30 [42mnormalization[0m >                                             ^
2023-03-28 00:09:30 [42mnormalization[0m > Done. PASS=22 WARN=0 ERROR=2 SKIP=4 TOTAL=28
```

## Expected Behavior
The incremental sync should wrap all the column names with `""` (if not mistaken, for all SQL flavours) to avoid this kind of error. 
The `add column "campaign.target_cpm.__quency_goal..."` would've solved this problem.

## Steps to Reproduce
1. You must have a `campaign` or `ad_groups` stream in incremental produced by Source Google Ads 0.2.11
2. Update Source Google Ads 0.2.11 to 0.2.13
3. Run the sync job

## Are you willing to submit a PR?
Yes.

**Comment by tolik0** [comment]
A few columns were deleted in version 0.2.13, so changes should be considered breaking, and the source needs full refresh sync after updating to 0.2.13. @hanslemm , please notify me if you have the same issue with the latest versions of Google Ads and Postgres connectors
