### ISSUE TITLE
Source MySQL 2.0.0+ throws ERROR Sync output exceeds the max temporal message size

### ISSUE THREAD

**Issue by ifun248** [airbytehq/airbyte#24650]
## Environment
- **Airbyte version**:  0.40.26/0.40.32/0.41.0
- **OS Version / Instance**: AWS EC2
- **Deployment**: Kubernetes deploy env
- **Source Connector and version**: MySQL 1.0.8/1.0.9/1.0.21/2.0.0/2.0.10 
- **Destination Connector and version**: AWS S3 0.3.18/0.3.20 
- **Step where error happened**: Sync job

## Current Behavior
Syncing data from MySQL Source 2.0.0+ to AWS S3, throw:
1 ERROR: Sync output exceeds the max temporal message size of 2097152, actual is 6297529. 
2 WARN: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: grpc: received message larger than max (6340023 vs. 4194304)

From the behaviors, I find this problem arises after Source MySQL upgrading to 2.0.0 which a change from DB sources cdc : upgrade Debezium version to 2.1.2. Ref https://github.com/airbytehq/airbyte/pull/23112.

## Expected Behavior
As syncing data from MySQL Source 1.0.21- to AWS S3, syncing success without error and warn.

## Logs

1 ERROR i.a.w.t.s.ReplicationActivityImpl(lambda$replicate$3):222 - Sync output exceeds the max temporal message size of 2097152, actual is 6297529. 
![image](https://user-images.githubusercontent.com/28381238/228447911-07eb48ae-06c8-417f-865b-0e428fccf1a1.png)

2 WARN i.t.i.w.ActivityWorker$TaskHandlerImpl(logExceptionDuringResultReporting):365 - Failure during reporting of activity result to the server. ActivityId = 369f7845-058f-363a-b7ca-52f03f30b870, ActivityType = Replicate, WorkflowId=sync_5, WorkflowType=SyncWorkflow, RunId=ddd5d275-a08c-4199-8e20-a2c386d936ec io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: grpc: received message larger than max (6340023 vs. 4194304)
![image](https://user-images.githubusercontent.com/28381238/228448103-21de771c-0309-48ce-bce1-0c9d69cea7c5.png)

Detail logs: [logs.txt](https://github.com/airbytehq/airbyte/files/11118808/logs.txt)

## Are you willing to submit a PR?

No

**Comment by subodh1810** [comment]
@ifun248 can you share the complete log file please, this might be not related to the source connector but platform level issue.

**Comment by prateekmukhedkar** [comment]
We are completing the sync successfully and emit a state. This error seems to be on the platform side. 

`2023-03-28 10:34:04 [44msource[0m > INFO i.a.i.b.IntegrationRunner(runInternal):186 Completed integration: io.airbyte.integrations.base.ssh.SshWrappedSource
2023-03-28 10:34:04 [44msource[0m > INFO i.a.i.s.m.MySqlSource(main):409 completed source: class io.airbyte.integrations.source.mysql.MySqlSource`

**Comment by alexnikitchuk** [comment]
we observe the same error on Airbyte 0.44.0, MySQL source 2.0.28: the first sync completes successfully but the next one just hangs and does not react on the Cancel button. What's interesting is that we have another connection with exactly the same source/destination but created a long time ago and has different set of tables to sync - and it works as expected.
```
2023-05-08 12:35:51 INFO i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to get state
2023-05-08 12:35:51 INFO i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to set attempt sync config
2023-05-08 12:36:52 WARN i.t.i.w.ActivityWorker$TaskHandlerImpl(logExceptionDuringResultReporting):365 - Failure during reporting of activity result to the server. ActivityId = c2e6dbb0-f329-340a-940a-33ddbdae694f, ActivityType = GetSyncWorkflowInputWithAttemptNumber, WorkflowId=connection_manager_29334c51-f5e3-4921-963b-6fb53f50a0cc, WorkflowType=ConnectionManagerWorkflow, RunId=c0457841-602b-46a6-a5ae-3c0da82de303
io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: grpc: received message larger than max (4458601 vs. 4194304)
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271) ~[grpc-stub-1.52.1.jar:1.52.1]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252) ~[grpc-stub-1.52.1.jar:1.52.1]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165) ~[grpc-stub-1.52.1.jar:1.52.1]
	at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.respondActivityTaskCompleted(WorkflowServiceGrpc.java:3840) ~[temporal-serviceclient-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.lambda$sendReply$0(ActivityWorker.java:303) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.retryer.GrpcRetryer.lambda$retry$0(GrpcRetryer.java:52) ~[temporal-serviceclient-1.17.0.jar:?]
	at io.temporal.internal.retryer.GrpcSyncRetryer.retry(GrpcSyncRetryer.java:67) ~[temporal-serviceclient-1.17.0.jar:?]
	at io.temporal.internal.retryer.GrpcRetryer.retryWithResult(GrpcRetryer.java:60) ~[temporal-serviceclient-1.17.0.jar:?]
	at io.temporal.internal.retryer.GrpcRetryer.retry(GrpcRetryer.java:50) ~[temporal-serviceclient-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.sendReply(ActivityWorker.java:298) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handleActivity(ActivityWorker.java:252) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:206) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:179) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93) ~[temporal-sdk-1.17.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

**Comment by alexnikitchuk** [comment]
Tried to debug my error a bit and found that the connection with ID `7bdaf293-1f16-4816-a846-11a20dba9935` simply does not exist.
The connection which fails has a different ID.
[The code ](https://github.com/airbytehq/airbyte-platform/commit/9472f0eacc087c33305a69dc38bd479669fe9bd2) which throws the error was added recently by @octavia-squidington-iii

**Comment by thanhld15** [comment]
A similar problem occurs to me too. The sync summary stacks up after each runs (almost linearly) to the number of records transmitted and quickly exceeds Max Messages setting, cause the ERROR and RESOURCE_EXHAUSTED in log. 
The interesting part is I have another connection with the same type of source/destination set up a while ago and it works fine, the sync summary does stack up but got cleared after around 25 runs so it is stable and doesn't expand linear to the size of transmitted record.

**Comment by alexnikitchuk** [comment]
> Today I've tried to update to the latest release v0.44.5: situation remains the same except I can cancel sync and the only error that appears in the log is RESOURCE_EXHAUSTED. Can anyone help with this?

To workaround RESOURCE_EXHAUSTED error we have granted SELECT privileges to the Airbyte user onto the tables that we are syncing, not all tables in the database therefore less metadata is being stored in Airbyte DB, and it is not breaching the 4MB limit in gRPC

**Comment by alexnikitchuk** [comment]
looks like and old issue https://github.com/airbytehq/airbyte/issues/12514

**Comment by prateekmukhedkar** [comment]
There are 2 changes that are taking place that will help Airbyte handle large schemas:
1. An Airbyte platform level change that enables catalogs to deal with schemas. It bypasses storing catalog related schema info in Temporal.
2. A MySQL connector change that @subodh1810 is working on that compresses Debezium schema history before we store it in connection state. 
ETA for both these improvements is week of Sep 21.

**Comment by akashkulk** [comment]
Closing this issue out as the 2 changes have been implemented
