### ISSUE TITLE
Connector Builder Sync failure - User should not be able to publish connector without schema

### ISSUE THREAD

**Issue by maxi297** [airbytehq/airbyte#24699]
## Environment
- **Airbyte version**:  0.42.0
- **OS Version / Instance**: any
- **Deployment**: Docker
- **Step where error happened**: Sync job

## Current Behavior
The sync fails because of the Inline schema
```
    schema_loader:
      type: InlineSchemaLoader
      schema: {}
```

## Expected Behavior
It depends on how we want to handle schema generation but the user shouldn't be able to publish a connector that we know will fail.

## Logs
```
2023-03-30 13:55:56 ERROR i.a.w.g.DefaultReplicationWorker(replicate):279 - Sync worker failed.
java.lang.RuntimeException: No properties node in stream schema
	at io.airbyte.workers.general.DefaultReplicationWorker.populateStreamToAllFields(DefaultReplicationWorker.java:692) ~[io.airbyte-airbyte-commons-worker-dev.jar:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$7(DefaultReplicationWorker.java:389) ~[io.airbyte-airbyte-commons-worker-dev.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

## Steps to Reproduce
1. In the browser, go on <url base>/workspaces/<workspace id>/connector-builder/create
2. "Start from scratch"
3. Enter API URL: https://pokeapi.co/api/v2/
4. Add a stream with URL path "pokemon/" (not mandatory, add Record Selector "results"
5. Publish
6. Create connection: "Connection -> New Connection -> Set up the source -> <newly created source from connector builder> -> Set up source -> <set up any destination> -> Set up destination -> Set up connection"
7. At that point, the sync should be running so wait for it to complete and fail

**Comment by flash1293** [comment]
Agreed that we should catch this in the builder - the easiest way seems to set a better default than the current one.

**Comment by lmossman** [comment]
Grooming notes:
- We will set the default schema value to an valid schema containing empty properties
- We will allow users to publish their connector if it has this default schema
