### ISSUE TITLE
Octavia imported Postgres Bigquery has Invalid Variable types

### ISSUE THREAD

**Issue by Maannniii** [airbytehq/airbyte#24896]
## Environment
- **Airbyte version**:  0.41.0
- **Octavia cli image version**: airbyte/octavia-cli:0.42.1
- **Deployment**: Kubernetes
- **Source Connector and version**: Postgres - 2.0.15
- **Destination Connector and version**: Bigquery - 1.2.14
- **Step where error happened**: Used `octavia import all` to import the existing sources, destinations and connections. Updated secrets and used `octavia apply` to update configurations.

## Current Behavior
Throws following errors with exception for Variable types **non_breaking_changes_preference** and **geography** in configuration.yaml
### non_breaking_changes_preference
`airbyte_api_client.exceptions.ApiTypeError: Invalid type for variable 'non_breaking_changes_preference'. Required value type is NonBreakingChangesPreference and passed type was str at ['non_breaking_changes_preference']`
### geography
`airbyte_api_client.exceptions.ApiTypeError: Invalid type for variable 'geography'. Required value type is Geography and passed type was str at ['geography']`

## Expected Behavior
Should accept the values without throwing exception as the configuration.yaml was generated by `octavia import`

### non_breaking_changes_preference
```
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/check_context.py", line 91, in wrapper
    f(ctx, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/apply/commands.py", line 29, in apply
    apply_single_resource(resource, force)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/apply/commands.py", line 66, in apply_single_resource
    messages = create_resource(resource)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/apply/commands.py", line 127, in create_resource
    created_resource, state = resource.create()
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/apply/resources.py", line 727, in create
    return self._create_or_update(self._create_fn, self.create_payload)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/apply/resources.py", line 701, in create_payload
    return WebBackendConnectionCreate(
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 46, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model/web_backend_connection_create.py", line 351, in __init__
    setattr(self, var_name, var_value)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 185, in __setattr__
    self[attr] = value
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 510, in __setitem__
    self.set_attribute(name, value)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 157, in set_attribute
    value = validate_and_convert_types(
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 1582, in validate_and_convert_types
    raise get_type_error(input_value, path_to_item, valid_classes,
airbyte_api_client.exceptions.ApiTypeError: Invalid type for variable 'non_breaking_changes_preference'. Required value type is NonBreakingChangesPreference and passed type was str at ['non_breaking_changes_preference']
```

### geography
```
Traceback (most recent call last):
  File "/usr/local/bin/octavia", line 8, in <module>
    sys.exit(octavia())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/base_commands.py", line 54, in invoke
    raise e
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/base_commands.py", line 51, in invoke
    result = super().invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/check_context.py", line 91, in wrapper
    f(ctx, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/apply/commands.py", line 29, in apply
    apply_single_resource(resource, force)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/apply/commands.py", line 66, in apply_single_resource
    messages = create_resource(resource)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/apply/commands.py", line 127, in create_resource
    created_resource, state = resource.create()
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/apply/resources.py", line 727, in create
    return self._create_or_update(self._create_fn, self.create_payload)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/apply/resources.py", line 701, in create_payload
    return WebBackendConnectionCreate(
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 46, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model/web_backend_connection_create.py", line 351, in __init__
    setattr(self, var_name, var_value)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 185, in __setattr__
    self[attr] = value
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 510, in __setitem__
    self.set_attribute(name, value)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 157, in set_attribute
    value = validate_and_convert_types(
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 1582, in validate_and_convert_types
    raise get_type_error(input_value, path_to_item, valid_classes,
airbyte_api_client.exceptions.ApiTypeError: Invalid type for variable 'geography'. Required value type is Geography and passed type was str at ['geography']
```

## Steps to Reproduce
1. Create Postgres source
2. create Bigquery destination
3. Create a connection with Postgres source and Bigquery destination.
4. Use `octavia import all` to save the configs
5. Reomve the statefile in connections/postggres_bigquery.
6. try applying using `octavia apply`

## Workaround:
- change `non_breaking_changes_preference` to `NonBreakingChangesPreference` in configuration.yaml.
- change `geography` to `Geography` in configuration.yaml.

## Are you willing to submit a PR?
yes. I believe this is a unnoticed bug. Updating  respective python script to refer to `non_breaking_changes_preference` and `geography` should fix the issue.

**Comment by waltermo** [comment]
I'm getting the same error when trying to apply a conf for an Oracle to Snowflake connection.

**Comment by marcosmarxm** [comment]
Octavia was removed from the main repo and won't receive updates anymore.
