### ISSUE TITLE
Migration runs out of memory

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#2492]
## Expected Behavior
Shouldn't run out of memory, no matter how old it has been running

## Current Behavior
It takes an long time and crashes at the end

## Logs
```
2021-03-16 19:58:46 INFO i.a.m.Migrate(run):87 - {} - Starting migrations. Current version: 0.14.1-alpha, Target version: 0.17.0-alpha
2021-03-16 19:58:46 INFO i.a.m.Migrate(run):105 - {} - Migrating from version: 0.14.0-alpha to version 0.14.3-alpha.

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.yaml.snakeyaml.reader.StreamReader.getMark(StreamReader.java:98)
	at org.yaml.snakeyaml.scanner.ScannerImpl.savePossibleSimpleKey(ScannerImpl.java:501)
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchPlain(ScannerImpl.java:1036)
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:399)
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:168)
	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:355)
	at com.fasterxml.jackson.core.JsonParser.nextFieldName(JsonParser.java:861)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:250)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:437)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:261)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:437)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:70)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4270)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2720)
	at io.airbyte.commons.yaml.Yamls.deserialize(Yamls.java:60)
	at io.airbyte.migrate.Migrate.createInputStreamsForResourceType(Migrate.java:164)
	at io.airbyte.migrate.Migrate.createInputStreams(Migrate.java:143)
	at io.airbyte.migrate.Migrate.runMigration(Migrate.java:123)
	at io.airbyte.migrate.Migrate.run(Migrate.java:106)
	at io.airbyte.migrate.MigrationRunner.run(MigrationRunner.java:70)
	at io.airbyte.migrate.MigrationRunner.main(MigrationRunner.java:108)
```
## Steps to Reproduce
1. ran 
```
docker run --rm -v /tmp:/config airbyte/migration:0.17.1-alpha -- --input /config/save.tar.gz --output /config/new.tar.gz --target-version 0.17.0-alpha
```

## Severity of the bug for you
Medium

## Airbyte Version
Old version was 0.14.1

**Comment by michel-tricot** [comment]
```
$ du -h
88K	./airbyte_config
171M	./airbyte_db
177M	.
```
