### ISSUE TITLE
Scheduler can't run new jobs after it crashes

### ISSUE THREAD

**Issue by gordalina** [airbytehq/airbyte#2495]
## Expected Behavior

Scheduler should run new jobs (e.g: discover schema)

## Current Behavior
It can run new jobs until a SYNC job crashes.

## Logs
```
airbyte-scheduler   | 2021-03-17 02:03:40 INFO i.a.c.i.LineGobbler(voidCall):69 - {ActivityId=43e53145-bc8d-3136-8abf-e81896e417aa, ActivityType=Run, Namespace=default, RunId=1167c082-f000-485b-b8c6-006d514f9335, TaskQueue=SYNC, WorkflowId=1ff3624d-c7b0-43f4-a174-cdb49d4cbe8b, job_id=11, job_log_filename=logs.log, job_root=/tmp/workspace/11/0} - 2021-03-17 02:03:40 INFO i.a.i.b.FailureTrackingConsumer(close):64 - {} - hasFailed: true.
airbyte-scheduler   | 2021-03-17 02:03:40 INFO i.a.c.i.LineGobbler(voidCall):69 - {ActivityId=43e53145-bc8d-3136-8abf-e81896e417aa, ActivityType=Run, Namespace=default, RunId=1167c082-f000-485b-b8c6-006d514f9335, TaskQueue=SYNC, WorkflowId=1ff3624d-c7b0-43f4-a174-cdb49d4cbe8b, job_id=11, job_log_filename=logs.log, job_root=/tmp/workspace/11/0} - 2021-03-17 02:03:40 ERROR i.a.i.d.b.BufferedStreamConsumer(close):158 - {} - executing on failed close procedure.
airbyte-scheduler   | 2021-03-17 02:03:40 INFO i.a.c.i.LineGobbler(voidCall):69 - {ActivityId=43e53145-bc8d-3136-8abf-e81896e417aa, ActivityType=Run, Namespace=default, RunId=1167c082-f000-485b-b8c6-006d514f9335, TaskQueue=SYNC, WorkflowId=1ff3624d-c7b0-43f4-a174-cdb49d4cbe8b, job_id=11, job_log_filename=logs.log, job_root=/tmp/workspace/11/0} - 2021-03-17 02:03:40 INFO i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):153 - {} - Cleaning tmp tables in destination started for 0 streams
airbyte-scheduler   | 2021-03-17 02:03:40 INFO i.a.c.i.LineGobbler(voidCall):69 - {ActivityId=43e53145-bc8d-3136-8abf-e81896e417aa, ActivityType=Run, Namespace=default, RunId=1167c082-f000-485b-b8c6-006d514f9335, TaskQueue=SYNC, WorkflowId=1ff3624d-c7b0-43f4-a174-cdb49d4cbe8b, job_id=11, job_log_filename=logs.log, job_root=/tmp/workspace/11/0} - 2021-03-17 02:03:40 INFO i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):162 - {} - Cleaning tmp tables in destination completed.
airbyte-scheduler   | 2021-03-17 02:03:40 ERROR i.a.c.i.LineGobbler(voidCall):69 - {ActivityId=43e53145-bc8d-3136-8abf-e81896e417aa, ActivityType=Run, Namespace=default, RunId=1167c082-f000-485b-b8c6-006d514f9335, TaskQueue=SYNC, WorkflowId=1ff3624d-c7b0-43f4-a174-cdb49d4cbe8b, job_id=11, job_log_filename=logs.log, job_root=/tmp/workspace/11/0} - Exception in thread "main" java.lang.IllegalArgumentException: Message contained record from a stream that was not in the catalog.
airbyte-scheduler   | 2021-03-17 02:03:40 ERROR i.a.c.i.LineGobbler(voidCall):69 - {ActivityId=43e53145-bc8d-3136-8abf-e81896e417aa, ActivityType=Run, Namespace=default, RunId=1167c082-f000-485b-b8c6-006d514f9335, TaskQueue=SYNC, WorkflowId=1ff3624d-c7b0-43f4-a174-cdb49d4cbe8b, job_id=11, job_log_filename=logs.log, job_root=/tmp/workspace/11/0} - catalog: {"streams":[]} ,
airbyte-scheduler   | 2021-03-17 02:03:40 ERROR i.a.c.i.LineGobbler(voidCall):69 - {ActivityId=43e53145-bc8d-3136-8abf-e81896e417aa, ActivityType=Run, Namespace=default, RunId=1167c082-f000-485b-b8c6-006d514f9335, TaskQueue=SYNC, WorkflowId=1ff3624d-c7b0-43f4-a174-cdb49d4cbe8b, job_id=11, job_log_filename=logs.log, job_root=/tmp/workspace/11/0} - message: {"type":"RECORD","record":{"stream":"sf733bec714344f80971f113d4a3063c5exchange_rate","data":{"CAD":1.299830251,"HKD":7.790851425,"ISK":122.3085857232,"PHP":50.7683373537,"DKK":6.6755114804,"HUF":294.8092557849,"CZK":22.7025819709,"GBP":0.7578665237,"RON":4.2730277852,"SEK":9.356562137,"IDR":13884.4992405968,"INR":71.3897078531,"BRL":4.0087554722,"RUB":61.8147949611,"HRK":6.6510318949,"JPY":108.7733404807,"THB":30.1447333155,"CHF":0.9706959707,"EUR":0.8934155276,"MYR":4.0886268203,"BGN":1.7473420888,"TRY":5.9589922273,"CNY":6.9638166711,"NOK":8.7919235236,"NZD":1.493612079,"ZAR":14.0709371929,"USD":1.0,"MXN":18.8852854463,"SGD":1.3476279818,"AUD":1.4300008934,"ILS":3.4566246761,"KRW":1159.8677745019,"PLN":3.8009470205,"date":"2020-01-02T00:00:00Z"},"emitted_at":1615946618000}}
airbyte-scheduler   | 2021-03-17 02:03:40 ERROR i.a.c.i.LineGobbler(voidCall):69 - {ActivityId=43e53145-bc8d-3136-8abf-e81896e417aa, ActivityType=Run, Namespace=default, RunId=1167c082-f000-485b-b8c6-006d514f9335, TaskQueue=SYNC, WorkflowId=1ff3624d-c7b0-43f4-a174-cdb49d4cbe8b, job_id=11, job_log_filename=logs.log, job_root=/tmp/workspace/11/0} - 	at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.acceptTracked(BufferedStreamConsumer.java:147)
airbyte-scheduler   | 2021-03-17 02:03:40 ERROR i.a.c.i.LineGobbler(voidCall):69 - {ActivityId=43e53145-bc8d-3136-8abf-e81896e417aa, ActivityType=Run, Namespace=default, RunId=1167c082-f000-485b-b8c6-006d514f9335, TaskQueue=SYNC, WorkflowId=1ff3624d-c7b0-43f4-a174-cdb49d4cbe8b, job_id=11, job_log_filename=logs.log, job_root=/tmp/workspace/11/0} - 	at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.acceptTracked(BufferedStreamConsumer.java:75)
airbyte-scheduler   | 2021-03-17 02:03:40 ERROR i.a.c.i.LineGobbler(voidCall):69 - {ActivityId=43e53145-bc8d-3136-8abf-e81896e417aa, ActivityType=Run, Namespace=default, RunId=1167c082-f000-485b-b8c6-006d514f9335, TaskQueue=SYNC, WorkflowId=1ff3624d-c7b0-43f4-a174-cdb49d4cbe8b, job_id=11, job_log_filename=logs.log, job_root=/tmp/workspace/11/0} - 	at io.airbyte.integrations.base.FailureTrackingConsumer.accept(FailureTrackingConsumer.java:53)
airbyte-scheduler   | 2021-03-17 02:03:40 ERROR i.a.c.i.LineGobbler(voidCall):69 - {ActivityId=43e53145-bc8d-3136-8abf-e81896e417aa, ActivityType=Run, Namespace=default, RunId=1167c082-f000-485b-b8c6-006d514f9335, TaskQueue=SYNC, WorkflowId=1ff3624d-c7b0-43f4-a174-cdb49d4cbe8b, job_id=11, job_log_filename=logs.log, job_root=/tmp/workspace/11/0} - 	at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:131)
airbyte-scheduler   | 2021-03-17 02:03:40 ERROR i.a.c.i.LineGobbler(voidCall):69 - {ActivityId=43e53145-bc8d-3136-8abf-e81896e417aa, ActivityType=Run, Namespace=default, RunId=1167c082-f000-485b-b8c6-006d514f9335, TaskQueue=SYNC, WorkflowId=1ff3624d-c7b0-43f4-a174-cdb49d4cbe8b, job_id=11, job_log_filename=logs.log, job_root=/tmp/workspace/11/0} - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:115)
airbyte-scheduler   | 2021-03-17 02:03:40 ERROR i.a.c.i.LineGobbler(voidCall):69 - {ActivityId=43e53145-bc8d-3136-8abf-e81896e417aa, ActivityType=Run, Namespace=default, RunId=1167c082-f000-485b-b8c6-006d514f9335, TaskQueue=SYNC, WorkflowId=1ff3624d-c7b0-43f4-a174-cdb49d4cbe8b, job_id=11, job_log_filename=logs.log, job_root=/tmp/workspace/11/0} - 	at io.airbyte.integrations.destination.postgres.PostgresDestination.main(PostgresDestination.java:69)
```

## Steps to Reproduce
1. Create a connection with an empty syncCatalog
1. Run a discover schema command and see it return ok
1. Wait until the scheduler crashes when running a SYNC for the connection
2. Run discover schema command and see it fail

## Severity of the bug for you
Pretty High

## Airbyte Version
0.17.1-alpha

## Connector Version (if applicable)
I'm using exchange rates API (the version is the one bundled with 0.17.1)

## Additional context
Debian 10.8 using Linux 4.19 on x64

**Comment by cgardens** [comment]
Thanks! We will take a look at this first thing in the morning.

**Comment by cgardens** [comment]
@gordalina  i think i got to the bottom of this. I will be merging a [fix](https://github.com/airbytehq/airbyte/pull/2502) shortly and will make sure we do a patch release to get it in the stable version.

**Comment by gordalina** [comment]
Awesome! I'll be sure to test it out!

**Comment by gordalina** [comment]
Seems to be working perfectly in `0.17.2-alpha`, thank you @cgardens!
