### ISSUE TITLE
Increase `BUFFER_READ_AHEAD_LIMIT`

### ISSUE THREAD

**Issue by ypc-faros** [airbytehq/airbyte#25015]
## Tell us about the problem you're trying to solve
I have a connector with a very large spec (+50kb and growing). After upgrading from Airbyte 39 to 43, I cannot add the connector from the Airbyte UI settings page.

I tracked down the issue to a limit [here](https://github.com/airbytehq/airbyte-platform/blob/f0a6652dcb1eed0131905fdad0f4409f80897c0a/airbyte-commons-worker/src/main/java/io/airbyte/workers/internal/VersionedAirbyteStreamFactory.java#L69).

```
airbyte-worker                    | 2023-04-10 13:21:26 INFO i.a.w.p.DockerProcessFactory(create):184 - Preparing command: docker run --rm --init -i -w /data/ccdbeab7-e877-47e4-b035-a7dc1b811bd5/0 --log-driver none --name airbyte-faros-feeds-source-spec-ccdbeab7-e877-47e4-b035-a7dc1b811bd5-0-ufyke --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=farosai/airbyte-faros-feeds-source:latest -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e USE_STREAM_CAPABLE_STATE=true -e FIELD_SELECTION_WORKSPACES= -e WORKER_ENVIRONMENT=DOCKER -e AIRBYTE_ROLE= -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=0 -e FEATURE_FLAG_CLIENT= -e AIRBYTE_VERSION=0.43.1 -e WORKER_JOB_ID=ccdbeab7-e877-47e4-b035-a7dc1b811bd5 farosai/airbyte-faros-feeds-source:latest spec
airbyte-worker                    | 2023-04-10 13:21:27 ERROR i.a.c.i.LineGobbler(voidCall):149 - WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
airbyte-worker                    | 2023-04-10 13:21:29 WARN i.a.w.i.VersionedAirbyteStreamFactory(detectVersion):185 - Protocol version detection failed, it is likely than the connector sent more than 32000B without an complete SPEC message. A SPEC message that is too long could be the root cause here.
airbyte-worker                    | 2023-04-10 13:21:29 INFO i.a.w.t.TemporalAttemptExecution(lambda$getWorkerThread$6):205 - Completing future exceptionally...
airbyte-worker                    | io.airbyte.workers.exception.WorkerException: Error while getting spec from image farosai/airbyte-faros-feeds-source:latest
airbyte-worker                    | 	at io.airbyte.workers.general.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:83) ~[io.airbyte-airbyte-commons-worker-0.43.1.jar:?]
airbyte-worker                    | 	at io.airbyte.workers.general.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:36) ~[io.airbyte-airbyte-commons-worker-0.43.1.jar:?]
airbyte-worker                    | 	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$6(TemporalAttemptExecution.java:202) ~[io.airbyte-airbyte-workers-0.43.1.jar:?]
airbyte-worker                    | 	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
airbyte-worker                    | Caused by: java.lang.RuntimeException: java.io.IOException: Mark invalid
airbyte-worker                    | 	at io.airbyte.workers.internal.VersionedAirbyteStreamFactory.create(VersionedAirbyteStreamFactory.java:132) ~[io.airbyte-airbyte-commons-worker-0.43.1.jar:?]
airbyte-worker                    | 	at io.airbyte.workers.WorkerUtils.getMessagesByType(WorkerUtils.java:203) ~[io.airbyte-airbyte-commons-worker-0.43.1.jar:?]
airbyte-worker                    | 	at io.airbyte.workers.general.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:60) ~[io.airbyte-airbyte-commons-worker-0.43.1.jar:?]
airbyte-worker                    | 	... 3 more
airbyte-worker                    | Caused by: java.io.IOException: Mark invalid
airbyte-worker                    | 	at java.io.BufferedReader.implReset(BufferedReader.java:612) ~[?:?]
airbyte-worker                    | 	at java.io.BufferedReader.reset(BufferedReader.java:596) ~[?:?]
airbyte-worker                    | 	at io.airbyte.workers.internal.VersionedAirbyteStreamFactory.detectVersion(VersionedAirbyteStreamFactory.java:177) ~[io.airbyte-airbyte-commons-worker-0.43.1.jar:?]
airbyte-worker                    | 	at io.airbyte.workers.internal.VersionedAirbyteStreamFactory.create(VersionedAirbyteStreamFactory.java:130) ~[io.airbyte-airbyte-commons-worker-0.43.1.jar:?]
airbyte-worker                    | 	at io.airbyte.workers.WorkerUtils.getMessagesByType(WorkerUtils.java:203) ~[io.airbyte-airbyte-commons-worker-0.43.1.jar:?]
airbyte-worker                    | 	at io.airbyte.workers.general.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:60) ~[io.airbyte-airbyte-commons-worker-0.43.1.jar:?]
airbyte-worker                    | 	... 3 more
```

## Describe the solution you’d like
~~I'd like to be able to configure this value.~~
I'd like this value increased to a more reasonable limit (e.g., 2MB)

**Comment by ypc-faros** [comment]
Actually, I'm okay with just increasing this limit to a reasonable number. I opened https://github.com/airbytehq/airbyte-platform/pull/287 that increases it to 2MB
