### ISSUE TITLE
Race condition in schema validation executor 

### ISSUE THREAD

**Issue by erohmensing** [airbytehq/airbyte#25301]
We currently spin up the schema validation thread in the background and let it run while we sync data. When we get to the part where we report validation errors, we don't block and wait for the executor thread to finish, nor do we shut down the executor thread. We just continue on in the original thread while the validator thread continues to modify our concurrent objects. 

This results in, in the extreme case that we validate a LOT of data and all that data fails validation, the validation thread running longer than the replication thread. By the time we want to report the validation errors, we can run into an error like the one this workspace ran into. Essentially the WorkerMetricReporter is trying to iterate over the `uncountedValidationErrors` at the same time that the executor thread is still updating that map. 

To resolve this we should either 1. shut down the executor early when we're ready to report validation errors, or 2. block and wait for the thread to be done before reporting validation errors. 

I vote for option 1. as I don't want validation to inflate the sync time. Over time, we should be reducing these validation errors so that there is less likely of a chance that we miss validation errors due to this. In the meantime the effect of us having too many errors only affects our reporting, and not the end user.

**Comment by erohmensing** [comment]
@davinchia and I [thought about this before](https://docs.google.com/document/d/14czPkFUiV4pmBMI-eH5QYkPxXWQ0OCN8fOC5ZCFnicc/edit?disco=AAAAu5Su2v4) and assumed it was the case that we were just reporting what we had whenever we got there, which further supports option 1. We (at least I) didn't realize that this could read to issues re: synchronous read/write operations on the map.

**Comment by erohmensing** [comment]
Traceback: 
```
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:489)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.airbyte.workers.WorkerMetricReporter.trackSchemaValidationErrors(WorkerMetricReporter.java:38)
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$5(DefaultReplicationWorker.java:453)
	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:451)
	... 4 more
```

**Comment by erohmensing** [comment]
I thought that the ConcurrentHashMap would not run into this based on the comment: 


But looks like we might have run into this: 
> Retrieval operations (including get) generally do not block, so may overlap with update operations (including put and remove). Retrievals reflect the results of the most recently completed update operations holding upon their onset. (More formally, an update operation for a given key bears a happens-before relation with any (non-null) retrieval for that key reporting the updated value.) For aggregate operations such as putAll and clear, concurrent retrievals may reflect insertion or removal of only some entries. Similarly, Iterators, Spliterators and Enumerations return elements reflecting the state of the hash table at some point at or since the creation of the iterator/enumeration. They do not throw ConcurrentModificationException. However, iterators are designed to be used by only one thread at a time. Bear in mind that the results of aggregate status methods including size, isEmpty, and containsValue are typically useful only when a map is not undergoing concurrent updates in other threads. Otherwise the results of these methods reflect transient states that may be adequate for monitoring or estimation purposes, but not for program control.

I.e. iterating over the whole map is not threadsafe - we'd need to acquire a lock before performing this. This is option 3, i guess - but for the sake of the output we get, is functionally the same as option 1.

**Comment by davinchia** [comment]
@erohmensing either one works to me. I don't think option 2 would result in significantly more time. In any case, both options are risk-comparable 2-way doors, so I'd pick the option that lets you implement this the fastest.
