### ISSUE TITLE
Destination Postgres: Failed to Transform data using DBT 

### ISSUE THREAD

**Issue by KILLYOUGUTSXXX** [airbytehq/airbyte#25380]
hello everyone, am new in airbyte, and i had some trouble when i tried to create flow transform using DBT Custom, i put the logs below with seperate some of part :

`
**============= The Repository of Github wa successfully to access =============**
2023-04-21 02:22:41 [42mnormalization[0m > Running: git clone --depth 5 -b main --single-branch  $GIT_REPO git_repo
2023-04-21 02:22:42 [42mnormalization[0m > Last 5 commits in git_repo:
2023-04-21 02:22:42 [42mnormalization[0m > 77a9b06 new models
2023-04-21 02:22:42 [42mnormalization[0m > c9d25d6 initial
2023-04-21 02:22:42 [42mnormalization[0m > /data/21/0/transform
2023-04-21 02:22:42 [42mnormalization[0m > Running: transform-config --config destination_config.json --integration-type postgres --out /data/21/0/transform
2023-04-21 02:22:43 [42mnormalization[0m > Namespace(config='destination_config.json', integration_type=<DestinationType.POSTGRES: 'postgres'>, out='/data/21/0/transform')
2023-04-21 02:22:43 [42mnormalization[0m > transform_postgres
2023-04-21 02:22:43 [42mnormalization[0m > Cloning into 'git_repo'...

**============= Check and run the DBT from docker images of  _fishtownanalytics/dbt:1.0.0_ =============**
2023-04-21 02:22:43 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - Checking if fishtownanalytics/dbt:1.0.0 exists...
2023-04-21 02:22:43 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - fishtownanalytics/dbt:1.0.0 was found locally.
2023-04-21 02:22:43 [32mINFO[m i.a.w.p.DockerProcessFactory(create):133 - Creating docker container = dbt-custom-21-0-ubjvd with resources io.airbyte.config.ResourceRequirements@455fa029[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts null
2023-04-21 02:22:43 [32mINFO[m i.a.w.p.DockerProcessFactory(create):184 - Preparing command: docker run --rm --init -i -w /data/21/0/transform --log-driver none --name dbt-custom-21-0-ubjvd --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e AIRBYTE_ROLE= -e WORKER_ENVIRONMENT=DOCKER -e AIRBYTE_VERSION=0.44.0 --entrypoint /bin/bash fishtownanalytics/dbt:1.0.0 entrypoint.sh run

**============= I think the problem start from here, but idk what the solutons for this =============**
2023-04-21 02:22:43 [45mdbt[0m > Running from /data/21/0/transform/git_repo
2023-04-21 02:22:43 [45mdbt[0m > detected no config file for ssh, assuming ssh is off.
2023-04-21 02:22:43 [45mdbt[0m > Running: dbt run --profiles-dir=/data/21/0/transform --project-dir=/data/21/0/transform/git_repo
2023-04-21 02:22:46 [45mdbt[0m > 02:22:46  Running with dbt=1.0.0
2023-04-21 02:22:46 [45mdbt[0m > 02:22:46  Encountered an error:
2023-04-21 02:22:46 [45mdbt[0m > Compilation Error
2023-04-21 02:22:46 [45mdbt[0m >   dbt found 1 package(s) specified in packages.yml, but only 0 package(s) installed in /dbt. Run "dbt deps" to install package dependencies.
2023-04-21 02:22:47 [32mINFO[m i.a.w.n.DefaultNormalizationRunner(close):194 - Terminating normalization process...
2023-04-21 02:22:47 [32mINFO[m i.a.w.n.DefaultNormalizationRunner(close):207 - Normalization process successfully terminated.
2023-04-21 02:22:47 [32mINFO[m i.a.w.t.TemporalAttemptExecution(lambda$getWorkerThread$5):198 - Completing future exceptionally...

io.airbyte.workers.exception.WorkerException: Dbt Transformation Failed.
	at io.airbyte.workers.general.DbtTransformationWorker.run(DbtTransformationWorker.java:75) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
	at io.airbyte.workers.general.DbtTransformationWorker.run(DbtTransformationWorker.java:29) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$5(TemporalAttemptExecution.java:195) ~[io.airbyte-airbyte-workers-0.44.0.jar:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: io.airbyte.workers.exception.WorkerException: DBT Transformation Failed.
	at io.airbyte.workers.general.DbtTransformationWorker.run(DbtTransformationWorker.java:71) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
	... 3 more
	Suppressed: io.airbyte.workers.exception.WorkerException: Dbt transformation process wasn't successful
		at io.airbyte.workers.general.DbtTransformationRunner.close(DbtTransformationRunner.java:156) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
		at io.airbyte.workers.general.DbtTransformationWorker.run(DbtTransformationWorker.java:60) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
		at io.airbyte.workers.general.DbtTransformationWorker.run(DbtTransformationWorker.java:29) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$5(TemporalAttemptExecution.java:195) ~[io.airbyte-airbyte-workers-0.44.0.jar:?]
		at java.lang.Thread.run(Thread.java:1589) ~[?:?]
2023-04-21 02:22:47 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):163 - Stopping cancellation check scheduling...
2023-04-21 02:22:47 [32mINFO[m i.a.c.t.TemporalUtils(withBackgroundHeartbeat):307 - Stopping temporal heartbeating...
2023-04-21 02:22:47 [33mWARN[m i.t.i.a.ActivityTaskExecutors$BaseActivityTaskExecutor(execute):114 - Activity failure. ActivityId=ebee41c5-34b5-3f46-96d5-7a3d96c2881a, activityType=Run, attempt=1
java.lang.RuntimeException: io.temporal.serviceclient.CheckedExceptionWrapper: java.util.concurrent.ExecutionException: io.airbyte.workers.exception.WorkerException: Dbt Transformation Failed.
	at io.airbyte.commons.temporal.TemporalUtils.withBackgroundHeartbeat(TemporalUtils.java:305) ~[io.airbyte-airbyte-commons-temporal-0.44.0.jar:?]
	at io.airbyte.workers.temporal.sync.DbtTransformationActivityImpl.run(DbtTransformationActivityImpl.java:103) ~[io.airbyte-airbyte-workers-0.44.0.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at io.temporal.internal.activity.RootActivityInboundCallsInterceptor$POJOActivityInboundCallsInterceptor.executeActivity(RootActivityInboundCallsInterceptor.java:64) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.activity.RootActivityInboundCallsInterceptor.execute(RootActivityInboundCallsInterceptor.java:43) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.activity.ActivityTaskExecutors$BaseActivityTaskExecutor.execute(ActivityTaskExecutors.java:95) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.activity.ActivityTaskHandlerImpl.handle(ActivityTaskHandlerImpl.java:92) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handleActivity(ActivityWorker.java:241) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:206) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:179) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93) ~[temporal-sdk-1.17.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: io.temporal.serviceclient.CheckedExceptionWrapper: java.util.concurrent.ExecutionException: io.airbyte.workers.exception.WorkerException: Dbt Transformation Failed.
	at io.temporal.serviceclient.CheckedExceptionWrapper.wrap(CheckedExceptionWrapper.java:57) ~[temporal-serviceclient-1.17.0.jar:?]
	at io.temporal.internal.sync.WorkflowInternal.wrap(WorkflowInternal.java:461) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.activity.Activity.wrap(Activity.java:52) ~[temporal-sdk-1.17.0.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:167) ~[io.airbyte-airbyte-workers-0.44.0.jar:?]
	at io.airbyte.workers.temporal.sync.DbtTransformationActivityImpl.lambda$run$3(DbtTransformationActivityImpl.java:134) ~[io.airbyte-airbyte-workers-0.44.0.jar:?]
	at io.airbyte.commons.temporal.TemporalUtils.withBackgroundHeartbeat(TemporalUtils.java:300) ~[io.airbyte-airbyte-commons-temporal-0.44.0.jar:?]
	... 14 more
Caused by: java.util.concurrent.ExecutionException: io.airbyte.workers.exception.WorkerException: Dbt Transformation Failed.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:161) ~[io.airbyte-airbyte-workers-0.44.0.jar:?]
	at io.airbyte.workers.temporal.sync.DbtTransformationActivityImpl.lambda$run$3(DbtTransformationActivityImpl.java:134) ~[io.airbyte-airbyte-workers-0.44.0.jar:?]
	at io.airbyte.commons.temporal.TemporalUtils.withBackgroundHeartbeat(TemporalUtils.java:300) ~[io.airbyte-airbyte-commons-temporal-0.44.0.jar:?]
	... 14 more
Caused by: io.airbyte.workers.exception.WorkerException: Dbt Transformation Failed.
	at io.airbyte.workers.general.DbtTransformationWorker.run(DbtTransformationWorker.java:75) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
	at io.airbyte.workers.general.DbtTransformationWorker.run(DbtTransformationWorker.java:29) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$5(TemporalAttemptExecution.java:195) ~[io.airbyte-airbyte-workers-0.44.0.jar:?]
	... 1 more
Caused by: io.airbyte.workers.exception.WorkerException: DBT Transformation Failed.
	at io.airbyte.workers.general.DbtTransformationWorker.run(DbtTransformationWorker.java:71) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
	at io.airbyte.workers.general.DbtTransformationWorker.run(DbtTransformationWorker.java:29) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$5(TemporalAttemptExecution.java:195) ~[io.airbyte-airbyte-workers-0.44.0.jar:?]
	... 1 more
	Suppressed: io.airbyte.workers.exception.WorkerException: Dbt transformation process wasn't successful
		at io.airbyte.workers.general.DbtTransformationRunner.close(DbtTransformationRunner.java:156) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
		at io.airbyte.workers.general.DbtTransformationWorker.run(DbtTransformationWorker.java:60) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
		at io.airbyte.workers.general.DbtTransformationWorker.run(DbtTransformationWorker.java:29) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$5(TemporalAttemptExecution.java:195) ~[io.airbyte-airbyte-workers-0.44.0.jar:?]
		at java.lang.Thread.run(Thread.java:1589) ~[?:?]
`

Huge thank's for helping me.

**Comment by evantahler** [comment]
Closing this issue because normalization as we know it is going away shortly - learn more @ https://github.com/airbytehq/airbyte/issues/26028
