### ISSUE TITLE
Platform Issue: Redshift source connector

### ISSUE THREAD

**Issue by herbertstos** [airbytehq/airbyte#25513]
### Platform Version

0.44.2

### What step the error happened?

During the Sync

### Revelant information

The source of redshift is not working as it should, I'm trying to use it as cdc, whenever I use version 0.3.16 it shows a null point error, when I use version 0.3.11, it works normally.

### Relevant log output

```shell
at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:91) ~[io.airbyte-airbyte-commons-worker-0.44.2.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$5(TemporalAttemptExecution.java:195) ~[io.airbyte-airbyte-workers-0.44.2.jar:?]
		at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
	at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:150) ~[io.airbyte-airbyte-commons-worker-0.44.2.jar:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:440) ~[io.airbyte-airbyte-commons-worker-0.44.2.jar:?]
	... 4 more
```

**Comment by herbertstos** [comment]
![image](https://user-images.githubusercontent.com/31415553/234410698-6d407e35-5392-4041-931d-86f84067974d.png)

**Comment by marcosmarxm** [comment]
@herbertstos please share the complete logfile here.

**Comment by herbertstos** [comment]
@marcosmarxm good morning.
this bug happens whenever I try to create the connection, when creating the source it does not show an error

This is the complete logfile, when I try to create the connection

[discover_schema-failure-68b4c278-a7fa-4561-904d-f6ca9f61ca31.txt](https://github.com/airbytehq/airbyte/files/11333051/discover_schema-failure-68b4c278-a7fa-4561-904d-f6ca9f61ca31.txt)

**Comment by davinchia** [comment]
I'm going to close this. Can you please try this using the latest version, thanks!
