### ISSUE TITLE
Connector Issue: MySQL connector raises SELECT command denied error in version 2.0.18/2.0.19 but not in 2.0.17

### ISSUE THREAD

**Issue by pholterman** [airbytehq/airbyte#25660]
### Connector Name

airbyte/source-mysql

### Connector Version

2.0.18 and 2.0.19

### What step the error happened?

During the sync

### Revelant information

After upgrading the mysql connector version from 2.0.17 to 2.0.18, we encountered a `SELECT command denied` error. Upgrading to the latest version (2.0.19) did nothing, but when I downgrade the connector to version 2.0.17 it worked again. 

### Relevant log output

```shell
java.sql.SQLSyntaxErrorException: SELECT command denied to user 'USERNAME'@'IPADDRESS' for table 'TABLENAME'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1200)
	at com.mysql.cj.jdbc.DatabaseMetaData$6.forEach(DatabaseMetaData.java:2745)
	at com.mysql.cj.jdbc.DatabaseMetaData$6.forEach(DatabaseMetaData.java:2732)
	at com.mysql.cj.jdbc.IterateBlock.doForAll(IterateBlock.java:56)
	at com.mysql.cj.jdbc.DatabaseMetaData.getIndexInfo(DatabaseMetaData.java:2802)
	at com.zaxxer.hikari.pool.ProxyDatabaseMetaData.getIndexInfo(ProxyDatabaseMetaData.java:207)
	at com.zaxxer.hikari.pool.HikariProxyDatabaseMetaData.getIndexInfo(HikariProxyDatabaseMetaData.java)
	at io.airbyte.integrations.source.jdbc.AbstractJdbcSource.logPreSyncDebugData(AbstractJdbcSource.java:451)
	at io.airbyte.integrations.source.jdbc.AbstractJdbcSource.logPreSyncDebugData(AbstractJdbcSource.java:86)
	at io.airbyte.integrations.source.relationaldb.AbstractDbSource.read(AbstractDbSource.java:147)
	at io.airbyte.integrations.base.ssh.SshWrappedSource.read(SshWrappedSource.java:74)
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:141)
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:101)
	at io.airbyte.integrations.source.mysql.MySqlSource.main(MySqlSource.java:388)
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by akashkulk** [comment]
Couple of things that could help me debug : 
1. Are you comfortable including logs from the failed version (2.0.18+) and the successfully version (2.0.17)?
2. This can occur if there is a drift between the tables that have been configured to sync vs what exist in the DB. Can you confirm that the table for which the error still exists/hasn't been renamed?
3. If point 2 does not apply - this could also indicate a permissions issue, that the given user does not have `SELECT` access to the given table. Can you verify that you have the correct access to the given table?
