### ISSUE TITLE
Migration from 0.15.0-alpha appears not to work

### ISSUE THREAD

**Issue by cooperfrench95** [airbytehq/airbyte#2578]
## Expected Behavior
According to the documentation found [here](https://docs.airbyte.io/tutorials/upgrading-airbyte) I should be able to follow the instructions and perform a migration using the provided docker image. But it doesn't work. I am attempting to upgrade from 0.15.0-alpha to 0.17.2-alpha

## Current Behavior
I did the following as instructed by the docs:
```bash
docker-compose down
docker-compose up -d db server webapp
```
Then step 3: _Navigate to the Admin page in the UI. Then go to the Configuration Tab. Click Export. This will download a gzipped tarball of all of your Airbyte configuration data and sync history._ 

Did that and received a gzipped file which ends in .gz rather than .tar.gz, but I figured it's still fine probably...

Step 4 is where it goes wrong.
The instructions state that this command should achieve the migration (example given places the downloaded file in /tmp:

```bash
docker run --rm -v /tmp:/config airbyte/migration:0.17.2-alpha --\
  --input /config/airbyte_archive.tar.gz\
  --output /config/airbyte_archive_migrated.tar.gz\
  --target-version 0.17.2-alpha
```

When I attempt this I get one of two errors. If I run it with the filename `/config/airbyte_archive.tar.gz` as stated in the example I get NoSuchFileException:

```bash
cooper@airbyte:~$ ls
airbyte_archive.gz
cooper@airbyte:~$ docker run --rm -v /home/cooper:/config airbyte/migration:0.17.2-alpha -- --input /config/airbyte_archive.tar.gz --output ./airbyte_migrated.tar.gz --target-version 0.17.2-alpha
2021-03-23 14:35:00 INFO i.a.m.MigrationRunner(parse):78 - {} - args: [--input, /config/airbyte_archive.tar.gz, --output, ./airbyte_migrated.tar.gz, --target-version, 0.17.2-alpha]
2021-03-23 14:35:00 INFO i.a.m.MigrationRunner(run):50 - {} - Unpacking tarball
Exception in thread "main" java.nio.file.NoSuchFileException: /config/airbyte_archive.tar.gz
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:375)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:426)
        at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
        at java.base/java.nio.file.Files.newInputStream(Files.java:160)
        at io.airbyte.commons.io.Archives.extractArchive(Archives.java:75)
        at io.airbyte.migrate.MigrationRunner.run(MigrationRunner.java:52)
        at io.airbyte.migrate.MigrationRunner.main(MigrationRunner.java:108)
cooper@airbyte:~$ 
```

If I run it using the filename I actually have, I get "No migration exists":

```bash
cooper@airbyte:~$ docker run --rm -v /home/cooper:/config airbyte/migration:0.17.2-alpha -- --input /config/airbyte_archive.gz --output ./airbyte_migrated.tar.gz --target-version 0.17.2-alpha
2021-03-23 14:36:42 INFO i.a.m.MigrationRunner(parse):78 - {} - args: [--input, /config/airbyte_archive.gz, --output, ./airbyte_migrated.tar.gz, --target-version, 0.17.2-alpha]
2021-03-23 14:36:42 INFO i.a.m.MigrationRunner(run):50 - {} - Unpacking tarball
2021-03-23 14:36:42 INFO i.a.m.MigrationRunner(run):67 - {} - Running migrations...
2021-03-23 14:36:42 INFO i.a.m.MigrationRunner(run):68 - {} - MigrateConfig{inputPath=/tmp/airbyte_migrate13626990095279544631/uncompressed, outputPath=/tmp/airbyte_migrate13626990095279544631/output, targetVersion='0.17.2-alpha'}
2021-03-23 14:36:42 INFO i.a.m.Migrate(run):87 - {} - Starting migrations. Current version: 0.15.0-alpha, Target version: 0.17.2-alpha
Exception in thread "main" java.lang.IllegalArgumentException: No migration found for target version: 0.17.2-alpha
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
        at io.airbyte.migrate.Migrate.run(Migrate.java:94)
        at io.airbyte.migrate.MigrationRunner.run(MigrationRunner.java:70)
        at io.airbyte.migrate.MigrationRunner.main(MigrationRunner.java:108)
cooper@airbyte:~$ 
```

## Severity of the bug for you
Medium

## Airbyte Version
0.15.0-alpha

**Comment by cooperfrench95** [comment]
@ChristopheDuong I did this and it appeared to work, but now when I try to upload the migrated configuration file through the airbyte interface, nothing happens. I can't click submit or anything.

**Comment by cooperfrench95** [comment]
Referring to this screen 
![image](https://user-images.githubusercontent.com/44951144/112180316-6a088d00-8c36-11eb-8e53-2f7bc7a73fa7.png)

**Comment by ChristopheDuong** [comment]
Did you drag and drop or click to select a file?

Otherwise you can also use the API with command-line tool such as curl to do the import:
https://docs.airbyte.io/tutorials/upgrading-airbyte#api-instruction

**Comment by cooperfrench95** [comment]
> Did you drag and drop or click to select a file?

Tried both and also tried renaming the file to .tar, .gz, .tar.gz etc. (the migrated zip generated had no file extension originally, but ubuntu recognized it as a gzip). Also tried in firefox and chrome

I will give the API method a shot.

**Comment by ChristopheDuong** [comment]
Looking closer to the migration command that you ran, I see that we omitted the `/config/` there, the command should be:

> docker run --rm -v /home/cooper:/config airbyte/migration:0.17.2-alpha -- --input /config/airbyte_archive.gz --output /config/airbyte_migrated.tar.gz --target-version 0.17.0-alpha

**Comment by ChristopheDuong** [comment]
Make sure to clean the `airbyte_migrated.tar.gz` from `home/cooper` before migrating so you actually produce a new migrated tarball

**Comment by cooperfrench95** [comment]
> Make sure to clean the `airbyte_migrated.tar.gz` from `home/cooper` before migrating so you actually produce a new migrated tarball

This actually never got created, because of the missing `/config` part, before I was trying to upload the old non-migrated zip file thinking it had been modified as there was an archive within it called `airbyte_migrated` but it was just the non-migrated data.

I added the config dir to the command and generated the migration file successfully, but was still unable to upload it through the interface. So I used the API which returned a success code. The issue now however is when I go into the airbyte interface at `localhost:8000` the sources and destinations don't load. In the admin panel they have an infinite loading spinner and in the sources and destinations tabs outside of admin they are just empty. I looked at my browser devtools and all I can see is a 500 from something called papercups.io, and that the request to this endpoint: `http://localhost:8001/api/v1/web_backend/connections/list` pends indefinitely.

I also checked the logs for the server, db and webapp, the server never logs a request to the `/connections/list` endpoint, it only receives the preflight request.

Here are the related logs:

```bash
2021-03-23 18:16:04 INFO i.a.s.RequestLogger(filter):107 - {workspace_app_root=/tmp/workspace/server/logs} - REQ 172.23.0.1 OPTIONS 200 /api/v1/web_backend/connections/list
2021-03-23 18:16:05 DEBUG i.a.s.c.SpecCachingSchedulerJobClient(createGetSpecJob):61 - {workspace_app_root=/tmp/workspace/server/logs} - cache miss: airbyte/source-hubspot-singer:0.2.0
2021-03-23 18:16:05 INFO i.a.s.p.DefaultJobPersistence(enqueueJob):131 - {workspace_app_root=/tmp/workspace/server/logs} - enqueuing pending job for scope: airbyte/source-hubspot-singer:0.2.0
2021-03-23 18:16:05 INFO i.a.s.c.DefaultSchedulerJobClient(waitUntilJobIsTerminalOrTimeout):117 - {workspace_app_root=/tmp/workspace/server/logs} - Waiting for job id: 29
```

after this nothing appears to happen. The request doesn't seem to time out either in Chrome or curl. It just pends forever

**Comment by ChristopheDuong** [comment]
Are you sure this is spinning forever without any results? if you wait a minute or two? (you should see activity in server logs though)

We have this trouble with caching where it takes a long time to refresh the pages (right after import too):
https://github.com/airbytehq/airbyte/issues/2034

**Comment by cooperfrench95** [comment]
19 hours later it's still spinning for me

**Comment by ChristopheDuong** [comment]
> 19 hours later it's still spinning for me

Ok definitely way too long...

**Comment by cooperfrench95** [comment]
Anything that can be done to remedy this issue from this point?

**Comment by ChristopheDuong** [comment]
> Anything that can be done to remedy this issue from this point?

it's tough to debug through discussion on github, would you be able to jump in slack to discuss this further?

**Comment by cooperfrench95** [comment]
> it's tough to debug through discussion on github, would you be able to jump in slack to discuss this further?

Sure is there a link somewhere?

**Comment by ChristopheDuong** [comment]
https://slack.airbyte.io/

**Comment by cgardens** [comment]
convo in progress here https://airbytehq.slack.com/archives/C01MFR03D5W/p1617020474169400

**Comment by cooperfrench95** [comment]
Resolved, the problem was that for some reason we weren't using the correct `docker-compose.yaml` file, which meant that `airbyte-temporal` container didn't exist. Copy pasting the yaml file from this repo and restarting airbyte fixed the issue. Thanks for your help guys.
