### ISSUE TITLE
Connector Issue: source-redshift NPE for view with no schema binding

### ISSUE THREAD

**Issue by hellmund** [airbytehq/airbyte#25825]
### Connector Name

airbyte/source-redshift

### Connector Version

0.3.16

### What step the error happened?

Configuring a new connector

### Revelant information

When the schema contains at least one view "with no schema binding", then the precondition scan fails with a NPE. This also happens when tables/views from a schema were synched successfully with airbyte, and that view is newly added to the schema, effectively breaking that connection during next pre-scan.

One work-around is to only use Airbyte on schemas which don't contain any views with no schema binding.

Steps to reproduce:
- create a no schema binding view on any of the existing tables in your schema, e.g. `CREATE VIEW test_view AS SELECT * from test_table WITH NO SCHEMA BINDING;`
- tap "review changes" of an existing connection to review schema updates, or try creating a new source to that Redshift schema

### Relevant log output

```shell
Stack Trace: java.lang.NullPointerException: null value in entry: isNullable=null
	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:33)
	at com.google.common.collect.ImmutableMapEntry.<init>(ImmutableMapEntry.java:54)
	at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:339)
	at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:449)
	at io.airbyte.integrations.source.jdbc.AbstractJdbcSource.getColumnMetadata(AbstractJdbcSource.java:268)
	at io.airbyte.db.jdbc.JdbcDatabase$1.tryAdvance(JdbcDatabase.java:81)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.airbyte.db.jdbc.DefaultJdbcDatabase.bufferedResultSetQuery(DefaultJdbcDatabase.java:56)
	at io.airbyte.integrations.source.jdbc.AbstractJdbcSource.discoverInternal(AbstractJdbcSource.java:191)
	at io.airbyte.integrations.source.redshift.RedshiftSource.discoverInternal(RedshiftSource.java:90)
	at io.airbyte.integrations.source.redshift.RedshiftSource.discoverInternal(RedshiftSource.java:30)
	at io.airbyte.integrations.source.relationaldb.AbstractDbSource.discoverWithoutSystemTables(AbstractDbSource.java:255)
	at io.airbyte.integrations.source.relationaldb.AbstractDbSource.read(AbstractDbSource.java:156)
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:138)
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:98)
	at io.airbyte.integrations.source.redshift.RedshiftSource.main(RedshiftSource.java:136)
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by utkarsh2811** [comment]
same error exists in version 0.4.0

**Comment by JakeCowton** [comment]
Adding that this error still exists in 0.8.0.

**Comment by evantahler** [comment]
This is a great area for community contribution!  A check can be added to test views for schema bindings, or we could prevent this source from syncing views.

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 365 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.
