### ISSUE TITLE
Can't set GCP for log + storageas alternative to AWS or MINIO

### ISSUE THREAD

**Issue by sho34215** [airbytehq/airbyte#25906]
### Platform Version or Helm Chart Version

44.3

### What step the error happened?

On deploy

### Revelant information

When set we want to use GCP as storage for airbyte:

values.yaml: 

- global.state.storage.type: GCP
- global.logs.storage.type: GCP
- global.logs.minio.enabled: false
- global.logs.externalMinio.enabled: false

Error is that system expects MINIO + AWS

### Relevant log output

```shell
at org.apache.logging.log4j.core.config.LoggerConfig.logParent(LoggerConfig.java:674)
99
at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:643)
98
at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:624)
97
at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:560)
96
at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
95
at org.apache.logging.log4j.core.Logger.log(Logger.java:162)
94
at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
93
at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
92
at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
91
at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2034)
90
at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1899)
89
at org.apache.logging.slf4j.Log4jLogger.info(Log4jLogger.java:185)
88
at io.temporal.internal.worker.Poller.start(Poller.java:91)
87
at io.temporal.internal.worker.LocalActivityWorker.start(LocalActivityWorker.java:98)
86
at io.temporal.internal.worker.SyncWorkflowWorker.start(SyncWorkflowWorker.java:162)
85
at io.temporal.worker.Worker.start(Worker.java:372)
84
at io.temporal.worker.WorkerFactory.start(WorkerFactory.java:213)
83
at io.airbyte.workers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:169)
82
at io.airbyte.workers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:62)
81
at io.micronaut.context.event.ApplicationEventPublisherFactory.notifyEventListeners(ApplicationEventPublisherFactory.java:262)
80
at io.micronaut.context.event.ApplicationEventPublisherFactory.access$200(ApplicationEventPublisherFactory.java:60)
79
at io.micronaut.context.event.ApplicationEventPublisherFactory$2.publishEvent(ApplicationEventPublisherFactory.java:229)
78
at io.micronaut.http.server.netty.NettyHttpServer.lambda$fireStartupEvents$15(NettyHttpServer.java:587)
77
at java.base/java.util.Optional.ifPresent(Optional.java:178)
76
at io.micronaut.http.server.netty.NettyHttpServer.fireStartupEvents(NettyHttpServer.java:581)
75
at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:298)
74
at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:104)
73
at io.micronaut.runtime.Micronaut.lambda$start$2(Micronaut.java:81)
72
at java.base/java.util.Optional.ifPresent(Optional.java:178)
71
at io.micronaut.runtime.Micronaut.start(Micronaut.java:79)
70
at io.micronaut.runtime.Micronaut.run(Micronaut.java:323)
69
at io.micronaut.runtime.Micronaut.run(Micronaut.java:309)
68
at io.airbyte.workers.Application.main(Application.java:15)
67
Caused by: com.amazonaws.SdkClientException: Unable to find a region via the region provider chain. Must provide an explicit region in the builder or setup environment to supply a region.
66
at com.amazonaws.client.builder.AwsClientBuilder.setRegion(AwsClientBuilder.java:462)
65
at com.amazonaws.client.builder.AwsClientBuilder.configureMutableProperties(AwsClientBuilder.java:424)
64
at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
63
at com.van.logging.aws.AwsClientHelpers.buildClient(AwsClientHelpers.java:88)
62
at com.van.logging.aws.S3PublishHelper.<init>(S3PublishHelper.java:53)
61
at com.van.logging.log4j2.Log4j2AppenderBuilder.lambda$createCachePublisher$0(Log4j2AppenderBuilder.java:271)
60
at java.base/java.util.Optional.ifPresent(Optional.java:178)
59
at com.van.logging.log4j2.Log4j2AppenderBuilder.createCachePublisher(Log4j2AppenderBuilder.java:266)
58
at com.van.logging.log4j2.Log4j2AppenderBuilder.build(Log4j2AppenderBuilder.java:137)
57
... 52 more
56
55
2023-05-09 08:07:52,698 main ERROR Unable to invoke factory method in class com.van.logging.log4j2.Log4j2Appender for element Log4j2Appender: java.lang.IllegalStateException: No factory method found for class com.van.logging.log4j2.Log4j2Appender java.lang.IllegalStateException: No factory method found for class com.van.logging.log4j2.Log4j2Appender
54
at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.findFactoryMethod(PluginBuilder.java:260)
53
at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:136)
52
at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1138)
51
at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1063)
50
at org.apache.logging.log4j.core.appender.routing.RoutingAppender.createAppender(RoutingAppender.java:310)
49
at org.apache.logging.log4j.core.appender.routing.RoutingAppender.getControl(RoutingAppender.java:282)
48
at org.apache.logging.log4j.core.appender.routing.RoutingAppender.append(RoutingAppender.java:240)
47
at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
46
at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
45
at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
44
at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
43
at org.apache.logging.log4j.core.appender.rewrite.RewriteAppender.append(RewriteAppender.java:84)
42
at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
41
at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
40
at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
39
at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
38
at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:683)
37
at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:641)
36
at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:624)
35
at org.apache.logging.log4j.core.config.LoggerConfig.logParent(LoggerConfig.java:674)
34
at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:643)
33
at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:624)
32
at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:560)
31
at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
30
at org.apache.logging.log4j.core.Logger.log(Logger.java:162)
29
at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
28
at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
27
at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
26
at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2034)
25
at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1899)
24
at org.apache.logging.slf4j.Log4jLogger.info(Log4jLogger.java:185)
23
at io.temporal.internal.worker.Poller.start(Poller.java:91)
22
at io.temporal.internal.worker.LocalActivityWorker.start(LocalActivityWorker.java:98)
21
at io.temporal.internal.worker.SyncWorkflowWorker.start(SyncWorkflowWorker.java:162)
20
at io.temporal.worker.Worker.start(Worker.java:372)
19
at io.temporal.worker.WorkerFactory.start(WorkerFactory.java:213)
18
at io.airbyte.workers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:169)
17
at io.airbyte.workers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:62)
16
at io.micronaut.context.event.ApplicationEventPublisherFactory.notifyEventListeners(ApplicationEventPublisherFactory.java:262)
15
at io.micronaut.context.event.ApplicationEventPublisherFactory.access$200(ApplicationEventPublisherFactory.java:60)
14
at io.micronaut.context.event.ApplicationEventPublisherFactory$2.publishEvent(ApplicationEventPublisherFactory.java:229)
13
at io.micronaut.http.server.netty.NettyHttpServer.lambda$fireStartupEvents$15(NettyHttpServer.java:587)
12
at java.base/java.util.Optional.ifPresent(Optional.java:178)
11
at io.micronaut.http.server.netty.NettyHttpServer.fireStartupEvents(NettyHttpServer.java:581)
10
at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:298)
9
at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:104)
8
at io.micronaut.runtime.Micronaut.lambda$start$2(Micronaut.java:81)
7
at java.base/java.util.Optional.ifPresent(Optional.java:178)
6
at io.micronaut.runtime.Micronaut.start(Micronaut.java:79)
5
at io.micronaut.runtime.Micronaut.run(Micronaut.java:323)
4
at io.micronaut.runtime.Micronaut.run(Micronaut.java:309)
3
at io.airbyte.workers.Application.main(Application.java:15)
2
1
2023-05-09 08:07:52 INFO i.t.i.w.Poller(start):91 - start: Poller{name=Activity Poller taskQueue="DISCOVER_SCHEMA", namespace="default", identity=1@dev-itx5-airbyte-dev-worker-86b4b86cc7-x6q2p}
```

**Comment by kYann** [comment]
Same here !

**Comment by sho34215** [comment]
I managed to log into GCP, here is what I have done:

  ```
state:
    ## state.storage.type Determines which state storage will be utilized.  One of "MINIO", "S3" or "GCS"
    storage:
      type: "GCS"
  logs:
    ##  logs.accessKey.password Logs Access Key
    ##  logs.accessKey.existingSecret
    ##  logs.accessKey.existingSecretKey
    accessKey:
      password: ""
      existingSecret: ""
      existingSecretKey: ""
    ##  logs.secretKey.password Logs Secret Key
    ##  logs.secretKey.existingSecret
    ##  logs.secretKey.existingSecretKey
    secretKey:
      password: ""
      existingSecret: ""
      existingSecretKey: ""

    ## logs.storage.type Determines which log storage  will be utilized.  One of "MINIO", "S3" or "GCS"
    ##                   Used in conjunction with logs.minio.*, logs.s3.* or logs.gcs.*
    storage:
      type: "GCS"

    ##  logs.minio.enabled Switch to enable or disable the Minio helm chart
    minio:
      enabled: false

    ##  logs.externalMinio.enabled Switch to enable or disable an external Minio instance
    ##  logs.externalMinio.host External Minio Host
    ##  logs.externalMinio.port External Minio Port
    ##  logs.externalMinio.endpoint Fully qualified hostname for s3-compatible storage
    externalMinio:
      enabled: false
      host: ""
      port: ""
      endpoint: ""

    ##  logs.s3.enabled Switch to enable or disable custom S3 Log location
    ##  logs.s3.bucket Bucket name where logs should be stored
    ##  logs.s3.bucketRegion Region of the bucket (must be empty if using minio)
    s3:
      enabled: false
      bucket: ""
      bucketRegion: ""

    ## Google Cloud Storage (GCS) Log Location Configuration
    ##  logs.gcs.bucket GCS bucket name
    ##  logs.gcs.credentials The path the GCS creds are written to
    ##  logs.gcs.credentialsJson Base64 encoded json GCP credentials file contents
    gcs:
      bucket: "my-bucket"
      # If you are mounting an existing secret to extraVolumes on scheduler, server and worker
      # deployments, then set credentials to the path of the mounted JSON file
      credentials: "/etc/vault-configmap/sql-replication-dev-643d8a2fa8d2.json"
      credentialsJson: ""

minio:
  enabled: false

```

On each components, I use a extract volume which mount sql-replication-dev-643d8a2fa8d2.json from secret

```
` ##  extraVolumeMounts [array] Additional volumeMounts for worker container(s).
  ## Examples (when using `worker.containerSecurityContext.readOnlyRootFilesystem=true`):
  ## extraVolumeMounts:
  ##   - name: tmpdir
  ##     mountPath: /tmp
  ##
  extraVolumeMounts:
    - name: vault-configmap
      mountPath: /etc/vault-configmap
  ##  extraVolumes [array] Additional volumes for worker pod(s).
  ## Examples (when using `worker.containerSecurityContext.readOnlyRootFilesystem=true`):
  ## extraVolumes:
  ##   - name: tmpdir
  ##     emptyDir: {}
  ##
  extraVolumes:
    - name: vault-configmap
      secret:
        secretName: db-credentials
```
Be aware that there are bugs on the chart version I use: 0.45.17

cron, metrics and otel-collector do not have extraVolumes and extraVolumeMounts on their respective chart defined.

**Comment by chargui-yassine** [comment]
+1

**Comment by anaselmhamdi** [comment]
Same here, the issue is solved when setting `logs.s3.bucket` to an empty string

**Comment by leonardo-lages-hyperflow** [comment]
> Same here, the issue is solved when setting `logs.s3.bucket` to an empty string

This not work for me, i got this erro putting an empty string:

Caused by: java.lang.IllegalArgumentException: Cannot create enum from ${env:S3_LOG_BUCKET_REGION} value!
	at com.amazonaws.regions.Regions.fromName(Regions.java:105)
	at com.van.logging.aws.S3Configuration.resolveRegion(S3Configuration.java:204)

**Comment by gingeard** [comment]
> > Same here, the issue is solved when setting `logs.s3.bucket` to an empty string
> 
> This not work for me, i got this erro putting an empty string:
> 
> Caused by: java.lang.IllegalArgumentException: Cannot create enum from ${env:S3_LOG_BUCKET_REGION} value! at com.amazonaws.regions.Regions.fromName(Regions.java:105) at com.van.logging.aws.S3Configuration.resolveRegion(S3Configuration.java:204)

It seems specifically 0.50.44 issue: https://github.com/airbytehq/airbyte/issues/34512

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
