### ISSUE TITLE
try to replicate empty sync file bug

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#2596]
Someone ran into an issue where:
> I probably should have mentioned sooner, but I remember now that originally I had tried to select more tables on a connector, so i clicked “update schema” and it never loaded, so I tried to reload the UI and it never did

And then empty files were present, causing:

```
2021-03-23 18:10:22 INFO  REQ 192.168.100.69 POST 200 /api/v1/sources/list - {"workspaceId":"5ae6b09b-fdec-41af-aaf7-7d94cfc33ef6"}
2021-03-23 18:10:22 INFO  REQ 192.168.100.69 OPTIONS 200 /api/v1/web_backend/connections/list
2021-03-23 18:10:22 DEBUG Uncaught exception
java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
	at io.airbyte.commons.json.Jsons.deserialize(Jsons.java:63) ~[io.airbyte-airbyte-commons-0.16.1-alpha.jar:?]
	at io.airbyte.config.persistence.DefaultConfigPersistence.getConfigInternal(DefaultConfigPersistence.java:90) ~[io.airbyte.airbyte-config-persistence-0.16.1-alpha.jar:?]
	at io.airbyte.config.persistence.DefaultConfigPersistence.getConfig(DefaultConfigPersistence.java:64) ~[io.airbyte.airbyte-config-persistence-0.16.1-alpha.jar:?]
	at io.airbyte.config.persistence.DefaultConfigPersistence.listConfigsInternal(DefaultConfigPersistence.java:111) ~[io.airbyte.airbyte-config-persistence-0.16.1-alpha.jar:?]
	at io.airbyte.config.persistence.DefaultConfigPersistence.listConfigs(DefaultConfigPersistence.java:71) ~[io.airbyte.airbyte-config-persistence-0.16.1-alpha.jar:?]
	at io.airbyte.config.persistence.ConfigRepository.listStandardSyncs(ConfigRepository.java:157) ~[io.airbyte.airbyte-config-persistence-0.16.1-alpha.jar:?]
```

We should probably audit our file handling for blocking server requests and make sure we aren't leaving bad files behind somehow.

What I'm proposing here is to make a schema change / cancel partway through a schema update, and restart Airbyte to see what happens.

If that doesn't induce the failure, I'm not sure what we would try to do it...

Probably the best thing is to log files as seen in https://github.com/airbytehq/airbyte/pull/2378 (after responding to the requests for changes). Then if there is a bad config file we can see exactly when it was written and hopefully get information that allows us to reproduce the issue.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368097493137) by [Unito](https://www.unito.io)

**Comment by jrhizor** [comment]
Relevant Slack thread (near the end): https://airbytehq.slack.com/archives/C01MFR03D5W/p1616513448065200

**Comment by cgardens** [comment]
i think this has since been solved.
