### ISSUE TITLE
Discovery fails when catalog is too big

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2619]
## Expected Behavior
discovery should display a catalog in the UI

## Current Behavior
There are two issues: 

1. Discovery fails but doesn't show logs properly. The attached logs are what is displayed for the job's logs: 
[logs_airbyte_problem.txt](https://github.com/airbytehq/airbyte/files/6208430/logs_airbyte_problem.txt)
2. After digging with the user on a screenshare, we found the following logs in the scheduler logs: 
```
2021-03-25 23:12:44 INFO i.a.w.t.TemporalAttemptExecution(get):124 - {ActivityId=c43b9bb2-7e25-31e3-93a3-568b2f78244c, ActivityType=Run, Namespace=default, RunId=1c7beb3e-7a20-4f8a-a341-6f05845f44ad, TaskQueue=DISCOVER_SCHEMA, WorkflowId=361a99ab-20c4-4413-84db-14139778991d, job_id=ee9adef3-7b2e-4136-a24b-a4ebf8616342, job_log_filename=logs.log, job_root=/tmp/workspace/ee9adef3-7b2e-4136-a24b-a4ebf8616342/0} - Stopping cancellation check scheduling...
2021-03-25 23:12:44 ERROR i.t.i.s.POJOWorkflowImplementationFactory$POJOWorkflowImplementation$RootWorkflowInboundCallsInterceptor(logWorkflowExecutionException):323 - {Namespace=default, RunId=1c7beb3e-7a20-4f8a-a341-6f05845f44ad, TaskQueue=DISCOVER_SCHEMA, WorkflowId=361a99ab-20c4-4413-84db-14139778991d, WorkflowType=DiscoverCatalogWorkflow} - Workflow execution failure WorkflowId=361a99ab-20c4-4413-84db-14139778991d, RunId=1c7beb3e-7a20-4f8a-a341-6f05845f44ad, WorkflowType=DiscoverCatalogWorkflow
io.temporal.failure.ActivityFailure: scheduledEventId=5, startedEventId=6, activityType='Run', activityId='c43b9bb2-7e25-31e3-93a3-568b2f78244c', identity='1@75c62b9be67b', retryState=RETRY_STATE_NON_RETRYABLE_FAILURE
	at java.lang.Thread.getStackTrace(Thread.java:1598) ~[?:?]
	at io.temporal.internal.sync.ActivityStubBase.execute(ActivityStubBase.java:48) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.ActivityInvocationHandler.lambda$getActivityFunc$0(ActivityInvocationHandler.java:59) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.ActivityInvocationHandlerBase.invoke(ActivityInvocationHandlerBase.java:65) ~[temporal-sdk-1.0.4.jar:?]
	at com.sun.proxy.$Proxy46.run(Unknown Source) ~[?:?]
	at io.airbyte.workers.temporal.DiscoverCatalogWorkflow$WorkflowImpl.run(DiscoverCatalogWorkflow.java:69) ~[io.airbyte-airbyte-workers-0.17.3-alpha.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation$RootWorkflowInboundCallsInterceptor.execute(POJOWorkflowImplementationFactory.java:289) [temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation.execute(POJOWorkflowImplementationFactory.java:253) [temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.WorkflowExecuteRunnable.run(WorkflowExecuteRunnable.java:52) [temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.SyncWorkflow.lambda$start$0(SyncWorkflow.java:126) [temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.CancellationScopeImpl.run(CancellationScopeImpl.java:101) [temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.WorkflowThreadImpl$RunnableWrapper.run(WorkflowThreadImpl.java:107) [temporal-sdk-1.0.4.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: io.temporal.failure.ServerFailure: Complete result exceeds size limit.
	at io.temporal.failure.FailureConverter.failureToExceptionImpl(FailureConverter.java:136) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.failure.FailureConverter.failureToException(FailureConverter.java:73) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.failure.FailureConverter.failureToExceptionImpl(FailureConverter.java:87) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.failure.FailureConverter.failureToException(FailureConverter.java:73) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.SyncWorkflowContext$ActivityCallback.lambda$invoke$0(SyncWorkflowContext.java:207) ~[temporal-sdk-1.0.4.jar:?]
	... 7 more
```
It looks like the exception happens because the resulting catalog's size is too large. The user reported that they have ~3500 tables in the source database. 

They are syncing from MSSQL to BQ on the latest versions. 

## Steps to Reproduce
Not sure exactly yet, but seems like it would be
1.  Create MSSQL instance with thousands of tables
1. run discovery via the API
1. 💣 

## Severity of the bug for you
high -- blocking user from creating a connection to this database

## Airbyte Version
0.17.3-alpha

## Connector Version (if applicable)
source mssql 0.2.0 
destination bigquery 0.2.0

**Comment by jrhizor** [comment]
Looks like we could bump the value: https://community.temporal.io/t/find-cause-of-complete-result-exceeds-size-limit-error/457/4

However, if we're getting large-ish files maybe the better approach is to store them outside of postgres.
