### ISSUE TITLE
Airbyte is not starting due to connectivity of PostgreSQL

### ISSUE THREAD

**Issue by parthprydotinfotech** [airbytehq/airbyte#26334]
### What method are you using to run Airbyte?

Docker

### Platform Version or Helm Chart Version

0.44.5

### What step the error happened?

On deploy

### Revelant information

Getting error while deploying the airbyte in local ubuntu environment.
Tried with older version and latest version as well but getting the same problem. Also, I have checked with different system and windows as well but due to Postgresql start up airbyte service is not starting.

### Relevant log output

```shell
airbyte-temporal                  | Waiting for PostgreSQL to startup.
airbyte-temporal                  | Waiting for PostgreSQL to startup.
airbyte-temporal                  | Waiting for PostgreSQL to startup.
airbyte-bootloader                | 2023-05-22 05:21:16 ERROR i.a.d.c.DatabaseAvailabilityCheck(lambda$isDatabaseConnected$1):78 - Failed to verify database connection.
airbyte-bootloader                | org.jooq.exception.DataAccessException: Error getting connection from data source HikariDataSource (HikariPool-2)
airbyte-bootloader                | 	at org.jooq_3.17.8.POSTGRES.debug(Unknown Source) ~[?:?]
airbyte-bootloader                | 	at org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:90) ~[jooq-3.17.8.jar:?]
airbyte-bootloader                | 	at org.jooq.impl.DefaultExecuteContext.connection(DefaultExecuteContext.java:560) ~[jooq-3.17.8.jar:?]
airbyte-bootloader                | 	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:296) ~[jooq-3.17.8.jar:?]
airbyte-bootloader                | 	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:301) ~[jooq-3.17.8.jar:?]
airbyte-bootloader                | 	at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:322) ~[jooq-3.17.8.jar:?]
airbyte-bootloader                | 	at org.jooq.impl.SelectImpl.fetchLazyNonAutoClosing(SelectImpl.java:2861) ~[jooq-3.17.8.jar:?]
airbyte-bootloader                | 	at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:509) ~[jooq-3.17.8.jar:?]
airbyte-bootloader                | 	at org.jooq.impl.Tools.attach(Tools.java:1526) ~[jooq-3.17.8.jar:?]
airbyte-bootloader                | 	at org.jooq.impl.DefaultDSLContext.fetchOne(DefaultDSLContext.java:4662) ~[jooq-3.17.8.jar:?]
airbyte-bootloader                | 	at org.jooq.impl.DefaultDSLContext.lambda$fetchValue$49(DefaultDSLContext.java:4682) ~[jooq-3.17.8.jar:?]
airbyte-bootloader                | 	at org.jooq.impl.Tools.attach(Tools.java:1526) ~[jooq-3.17.8.jar:?]
airbyte-bootloader                | 	at org.jooq.impl.DefaultDSLContext.fetchValue(DefaultDSLContext.java:4682) ~[jooq-3.17.8.jar:?]
airbyte-bootloader                | 	at org.jooq.impl.DefaultDSLContext.fetchValue(DefaultDSLContext.java:4696) ~[jooq-3.17.8.jar:?]
airbyte-bootloader                | 	at org.jooq.impl.DefaultDSLContext.fetchExists(DefaultDSLContext.java:4778) ~[jooq-3.17.8.jar:?]
airbyte-bootloader                | 	at io.airbyte.db.check.DatabaseAvailabilityCheck.lambda$isDatabaseConnected$0(DatabaseAvailabilityCheck.java:76) ~[io.airbyte.airbyte-db-db-lib-0.44.5.jar:?]
airbyte-bootloader                | 	at io.airbyte.db.Database.query(Database.java:23) ~[io.airbyte.airbyte-db-db-lib-0.44.5.jar:?]
airbyte-bootloader                | 	at io.airbyte.db.check.DatabaseAvailabilityCheck.lambda$isDatabaseConnected$1(DatabaseAvailabilityCheck.java:76) ~[io.airbyte.airbyte-db-db-lib-0.44.5.jar:?]
airbyte-bootloader                | 	at io.airbyte.db.check.DatabaseAvailabilityCheck.check(DatabaseAvailabilityCheck.java:47) ~[io.airbyte.airbyte-db-db-lib-0.44.5.jar:?]
airbyte-bootloader                | 	at io.airbyte.db.init.DatabaseInitializer.initialize(DatabaseInitializer.java:45) ~[io.airbyte.airbyte-db-db-lib-0.44.5.jar:?]
airbyte-bootloader                | 	at io.airbyte.bootloader.Bootloader.initializeDatabases(Bootloader.java:200) ~[io.airbyte-airbyte-bootloader-0.44.5.jar:?]
airbyte-bootloader                | 	at io.airbyte.bootloader.Bootloader.load(Bootloader.java:101) ~[io.airbyte-airbyte-bootloader-0.44.5.jar:?]
airbyte-bootloader                | 	at io.airbyte.bootloader.Application.main(Application.java:22) ~[io.airbyte-airbyte-bootloader-0.44.5.jar:?]
airbyte-bootloader                | Caused by: java.sql.SQLTransientConnectionException: HikariPool-2 - Connection is not available, request timed out after 30000ms.
airbyte-bootloader                | 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696) ~[HikariCP-5.0.1.jar:?]
airbyte-bootloader                | 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:181) ~[HikariCP-5.0.1.jar:?]
airbyte-bootloader                | 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146) ~[HikariCP-5.0.1.jar:?]
airbyte-bootloader                | 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[HikariCP-5.0.1.jar:?]
airbyte-bootloader                | 	at org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:87) ~[jooq-3.17.8.jar:?]
airbyte-bootloader                | 	... 21 more
airbyte-bootloader                | Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
airbyte-bootloader                | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:354) ~[postgresql-42.5.4.jar:42.5.4]
airbyte-bootloader                | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54) ~[postgresql-42.5.4.jar:42.5.4]
airbyte-bootloader                | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:253) ~[postgresql-42.5.4.jar:42.5.4]
airbyte-bootloader                | 	at org.postgresql.Driver.makeConnection(Driver.java:434) ~[postgresql-42.5.4.jar:42.5.4]
airbyte-bootloader                | 	at org.postgresql.Driver.connect(Driver.java:291) ~[postgresql-42.5.4.jar:42.5.4]
airbyte-bootloader                | 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-5.0.1.jar:?]
airbyte-bootloader                | 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[HikariCP-5.0.1.jar:?]
airbyte-bootloader                | 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-5.0.1.jar:?]
airbyte-bootloader                | 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[HikariCP-5.0.1.jar:?]
airbyte-bootloader                | 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:733) ~[HikariCP-5.0.1.jar:?]
airbyte-bootloader                | 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712) ~[HikariCP-5.0.1.jar:?]
airbyte-bootloader                | 	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
airbyte-bootloader                | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
airbyte-bootloader                | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
airbyte-bootloader                | 	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
airbyte-bootloader                | Caused by: java.net.NoRouteToHostException: No route to host
airbyte-bootloader                | 	at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
airbyte-bootloader                | 	at sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[?:?]
airbyte-bootloader                | 	at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542) ~[?:?]
airbyte-bootloader                | 	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:585) ~[?:?]
airbyte-bootloader                | 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
airbyte-bootloader                | 	at java.net.Socket.connect(Socket.java:666) ~[?:?]
airbyte-bootloader                | 	at org.postgresql.core.PGStream.createSocket(PGStream.java:243) ~[postgresql-42.5.4.jar:42.5.4]
airbyte-bootloader                | 	at org.postgresql.core.PGStream.<init>(PGStream.java:98) ~[postgresql-42.5.4.jar:42.5.4]
airbyte-bootloader                | 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132) ~[postgresql-42.5.4.jar:42.5.4]
airbyte-bootloader                | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258) ~[postgresql-42.5.4.jar:42.5.4]
airbyte-bootloader                | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54) ~[postgresql-42.5.4.jar:42.5.4]
airbyte-bootloader                | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:253) ~[postgresql-42.5.4.jar:42.5.4]
airbyte-bootloader                | 	at org.postgresql.Driver.makeConnection(Driver.java:434) ~[postgresql-42.5.4.jar:42.5.4]
airbyte-bootloader                | 	at org.postgresql.Driver.connect(Driver.java:291) ~[postgresql-42.5.4.jar:42.5.4]
airbyte-bootloader                | 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-5.0.1.jar:?]
airbyte-bootloader                | 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[HikariCP-5.0.1.jar:?]
airbyte-bootloader                | 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-5.0.1.jar:?]
airbyte-bootloader                | 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[HikariCP-5.0.1.jar:?]
airbyte-bootloader                | 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:733) ~[HikariCP-5.0.1.jar:?]
airbyte-bootloader                | 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712) ~[HikariCP-5.0.1.jar:?]
airbyte-bootloader                | 	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
airbyte-bootloader                | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
airbyte-bootloader                | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
airbyte-bootloader                | 	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
airbyte-bootloader                | 2023-05-22 05:21:16 INFO i.a.d.c.DatabaseAvailabilityCheck(check):49 - Database is not ready yet. Please wait a moment, it might still be initializing...
airbyte-temporal                  | Waiting for PostgreSQL to startup.
```

**Comment by parthprydotinfotech** [comment]
Destroy the docker all images.
Delete docker-compose.yml and docker-compose.yaml files from the airbyte directory.
This is worked for me.
Not getting any support from airbyte team.
