### ISSUE TITLE
UI doesn't render if spec fetching fails 

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#2670]
Ran into a case when using the demo instance where spec fetching failed during listing connections for the web backend:

```
2021-03-30 16:48:54 DEBUG i.a.s.e.UncaughtExceptionMapper(toResponse):42 - {workspace_app_root=/tmp/workspace/server/logs} - Uncaught exception
java.lang.IllegalArgumentException: no spec output found
	at io.airbyte.server.converters.SpecFetcher.lambda$getSpecFromJob$0(SpecFetcher.java:51) ~[io.airbyte-airbyte-server-0.17.1-alpha.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:401) ~[?:?]
	at io.airbyte.server.converters.SpecFetcher.getSpecFromJob(SpecFetcher.java:51) ~[io.airbyte-airbyte-server-0.17.1-alpha.jar:?]
	at io.airbyte.server.converters.SpecFetcher.execute(SpecFetcher.java:43) ~[io.airbyte-airbyte-server-0.17.1-alpha.jar:?]
	at io.airbyte.server.handlers.DestinationHandler.getSpec(DestinationHandler.java:208) ~[io.airbyte-airbyte-server-0.17.1-alpha.jar:?]
	at io.airbyte.server.handlers.DestinationHandler.buildDestinationRead(DestinationHandler.java:230) ~[io.airbyte-airbyte-server-0.17.1-alpha.jar:?]
	at io.airbyte.server.handlers.DestinationHandler.getDestination(DestinationHandler.java:178) ~[io.airbyte-airbyte-server-0.17.1-alpha.jar:?]
	at io.airbyte.server.handlers.WebBackendConnectionsHandler.buildWbConnectionRead(WebBackendConnectionsHandler.java:104) ~[io.airbyte-airbyte-server-0.17.1-alpha.jar:?]
	at io.airbyte.server.handlers.WebBackendConnectionsHandler.webBackendListConnectionsForWorkspace(WebBackendConnectionsHandler.java:93) ~[io.airbyte-airbyte-server-0.17.1-alpha.jar:?]
	at io.airbyte.server.apis.ConfigurationApi.lambda$webBackendListConnectionsForWorkspace$41(ConfigurationApi.java:426) ~[io.airbyte-airbyte-server-0.17.1-alpha.jar:?]
	at io.airbyte.server.apis.ConfigurationApi.execute(ConfigurationApi.java:464) ~[io.airbyte-airbyte-server-0.17.1-alpha.jar:?]
	at io.airbyte.server.apis.ConfigurationApi.webBackendListConnectionsForWorkspace(ConfigurationApi.java:426) ~[io.airbyte-airbyte-server-0.17.1-alpha.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
```

And the UI is completely blank, with `api/v1/sources/list` errors in the devtools console.

It's possible this might be demo instance-specific, but it's probably worth trying to reproduce. If it is reproducible, this is probably a high priority issue to fix.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368098337421) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
There were no logs?

**Comment by jrhizor** [comment]
These were the only exceptions in the logs.

**Comment by eliziario** [comment]
Just found out that if a docker image for a connector can't be found for some reason, the connections screen can't be displayed because  /api/v1/web_backend/connections/list fails apparently because io.airbyte.server.converters.SpecFetcher.getSpecFromJob fails (due to not being able to fetch the docker image), thus breaking io.airbyte.server.apis.ConfigurationApi.webBackendListConnectionsForWorkspace.

A simple way of trigering this is building a dev version of a connector, install it, then create a connection that uses it. delete this dev image and then restart docker-compose. 

/api/v1/web_backend/connections/list will 500 with the following stack trace (redacted to eliminate redundant retries)

```airbyte-worker      | 2021-10-06 13:17:32 ERROR i.t.i.s.POJOWorkflowImplementationFactory$POJOWorkflowImplementation$RootWorkflowInboundCallsInterceptor(logWorkflowExecutionException):323 - {Namespace=default, RunId=d4a0df87-b28d-4b6f-a44e-f684f704a30a, TaskQueue=GET_SPEC, WorkflowId=74c6a9e2-d9cb-4bd8-9f59-4b518e6c65c0, WorkflowType=SpecWorkflow} - Workflow execution failure WorkflowId=74c6a9e2-d9cb-4bd8-9f59-4b518e6c65c0, RunId=d4a0df87-b28d-4b6f-a44e-f684f704a30a, WorkflowType=SpecWorkflow
airbyte-worker      | io.temporal.failure.ActivityFailure: scheduledEventId=5, startedEventId=6, activityType='Run', activityId='299a60d4-4457-3a28-aed7-2e5903ba2ca4', identity='1@f9cb6328044a', retryState=RETRY_STATE_MAXIMUM_ATTEMPTS_REACHED
airbyte-worker      |   at java.lang.Thread.getStackTrace(Thread.java:1598) ~[?:?]
airbyte-worker      |   at io.temporal.internal.sync.ActivityStubBase.execute(ActivityStubBase.java:48) ~[temporal-sdk-1.0.4.jar:?]
airbyte-worker      |   at io.temporal.internal.sync.ActivityInvocationHandler.lambda$getActivityFunc$0(ActivityInvocationHandler.java:59) ~[temporal-sdk-1.0.4.jar:?]
airbyte-worker      |   at io.temporal.internal.sync.ActivityInvocationHandlerBase.invoke(ActivityInvocationHandlerBase.java:65) ~[temporal-sdk-1.0.4.jar:?]
airbyte-worker      |   at com.sun.proxy.$Proxy26.run(Unknown Source) ~[?:?]
airbyte-worker      |   at io.airbyte.workers.temporal.SpecWorkflow$WorkflowImpl.run(SpecWorkflow.java:44) ~[io.airbyte-airbyte-workers-0.30.11-alpha.jar:?]
airbyte-worker      |   at jdk.internal.reflect.GeneratedMethodAccessor20.invoke(Unknown Source) ~[?:?]
airbyte-worker      |   at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
airbyte-worker      |   at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
airbyte-worker      |   at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation$RootWorkflowInboundCallsInterceptor.execute(POJOWorkflowImplementationFactory.java:289) ~[temporal-sdk-1.0.4.jar:?]
airbyte-worker      |   at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation.execute(POJOWorkflowImplementationFactory.java:253) ~[temporal-sdk-1.0.4.jar:?]
airbyte-worker      |   at io.temporal.internal.sync.WorkflowExecuteRunnable.run(WorkflowExecuteRunnable.java:52) ~[temporal-sdk-1.0.4.jar:?]
airbyte-worker      |   at io.temporal.internal.sync.SyncWorkflow.lambda$start$0(SyncWorkflow.java:126) ~[temporal-sdk-1.0.4.jar:?]
airbyte-worker      |   at io.temporal.internal.sync.CancellationScopeImpl.run(CancellationScopeImpl.java:101) [temporal-sdk-1.0.4.jar:?]
airbyte-worker      |   at io.temporal.internal.sync.WorkflowThreadImpl$RunnableWrapper.run(WorkflowThreadImpl.java:107) [temporal-sdk-1.0.4.jar:?]
airbyte-worker      |   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
airbyte-worker      |   at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
airbyte-worker      |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
airbyte-worker      |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
airbyte-worker      |   at java.lang.Thread.run(Thread.java:832) [?:?]
airbyte-worker      | Caused by: io.temporal.failure.ApplicationFailure: message='io.airbyte.workers.WorkerException: Error while getting spec from image airbyte/source-jira:dev', type='java.util.concurrent.ExecutionException', nonRetryable=false
airbyte-worker      |   at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[?:?]
airbyte-worker      |   at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2063) ~[?:?]
airbyte-worker      |   at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:113) ~[io.airbyte-airbyte-workers-0.30.11-alpha.jar:?]
airbyte-worker      |   at io.airbyte.workers.temporal.SpecWorkflow$SpecActivityImpl.run(SpecWorkflow.java:77) ~[io.airbyte-airbyte-workers-0.30.11-alpha.jar:?]
airbyte-worker      |   at jdk.internal.reflect.GeneratedMethodAccessor26.invoke(Unknown Source:0) ~[?:?]
airbyte-worker      |   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
airbyte-worker      |   at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
airbyte-worker      |   at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityInboundCallsInterceptor.execute(POJOActivityTaskHandler.java:277) ~[temporal-sdk-1.0.4.jar:?]
airbyte-worker      |   at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityImplementation.execute(POJOActivityTaskHandler.java:216) ~[temporal-sdk-1.0.4.jar:?]
airbyte-worker      |   at io.temporal.internal.sync.POJOActivityTaskHandler.handle(POJOActivityTaskHandler.java:181) ~[temporal-sdk-1.0.4.jar:?]
airbyte-worker      |   at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:192) ~[temporal-sdk-1.0.4.jar:?]
airbyte-worker      |   at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:154) ~[temporal-sdk-1.0.4.jar:?]
airbyte-worker      |   at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73) ~[temporal-sdk-1.0.4.jar:?]
airbyte-worker      |   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
airbyte-worker      |   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
airbyte-worker      |   at java.base/java.lang.Thread.run(Thread.java:832) ~[?:?]
airbyte-worker      | Caused by: io.temporal.failure.ApplicationFailure: message='Error while getting spec from image airbyte/source-jira:dev', type='io.airbyte.workers.WorkerException', nonRetryable=false
airbyte-worker      |   at io.airbyte.workers.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:74) ~[io.airbyte-airbyte-workers-0.30.11-alpha.jar:?]
airbyte-worker      |   at io.airbyte.workers.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:23) ~[io.airbyte-airbyte-workers-0.30.11-alpha.jar:?]
airbyte-worker      |   at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$1(TemporalAttemptExecution.java:145) ~[io.airbyte-airbyte-workers-0.30.11-alpha.jar:?]
airbyte-worker      |   at java.base/java.lang.Thread.run(Thread.java:832) ~[?:?]
airbyte-worker      | Caused by: io.temporal.failure.ApplicationFailure: message='Could not find image: airbyte/source-jira:dev', type='io.airbyte.workers.WorkerException', nonRetryable=false
airbyte-worker      |   at io.airbyte.workers.process.DockerProcessFactory.create(DockerProcessFactory.java:77) ~[io.airbyte-airbyte-workers-0.30.11-alpha.jar:?]
airbyte-worker      |   at io.airbyte.workers.process.AirbyteIntegrationLauncher.spec(AirbyteIntegrationLauncher.java:52) ~[io.airbyte-airbyte-workers-0.30.11-alpha.jar:?]
airbyte-worker      |   at io.airbyte.workers.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:44) ~[io.airbyte-airbyte-workers-0.30.11-alpha.jar:?]
airbyte-worker      |   at io.airbyte.workers.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:23) ~[io.airbyte-airbyte-workers-0.30.11-alpha.jar:?]
airbyte-worker      |   at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$1(TemporalAttemptExecution.java:145) ~[io.airbyte-airbyte-workers-0.30.11-alpha.jar:?]
airbyte-worker      |   at java.base/java.lang.Thread.run(Thread.java:832) ~[?:?]
airbyte-server      | 2021-10-06 13:17:32 ERROR i.a.s.e.UncaughtExceptionMapper(toResponse):22 - {workspace_app_root=/tmp/workspace/server/logs} - Uncaught exception
airbyte-server      | java.lang.IllegalStateException: Get Spec job failed.
airbyte-server      |   at com.google.common.base.Preconditions.checkState(Preconditions.java:510) ~[guava-30.1.1-jre.jar:?]
airbyte-server      |   at io.airbyte.server.converters.SpecFetcher.getSpecFromJob(SpecFetcher.java:26) ~[io.airbyte-airbyte-server-0.30.11-alpha.jar:?]
airbyte-server      |   at io.airbyte.server.converters.SpecFetcher.execute(SpecFetcher.java:22) ~[io.airbyte-airbyte-server-0.30.11-alpha.jar:?]
airbyte-server      |   at io.airbyte.server.handlers.SourceHandler.buildSourceRead(SourceHandler.java:194) ~[io.airbyte-airbyte-server-0.30.11-alpha.jar:?]
airbyte-server      |   at io.airbyte.server.handlers.SourceHandler.getSource(SourceHandler.java:127) ~[io.airbyte-airbyte-server-0.30.11-alpha.jar:?]
airbyte-server      |   at io.airbyte.server.handlers.WebBackendConnectionsHandler.getSourceRead(WebBackendConnectionsHandler.java:111) ~[io.airbyte-airbyte-server-0.30.11-alpha.jar:?]
airbyte-server      |   at io.airbyte.server.handlers.WebBackendConnectionsHandler.buildWebBackendConnectionRead(WebBackendConnectionsHandler.java:97) ~[io.airbyte-airbyte-server-0.30.11-alpha.jar:?]
airbyte-server      |   at io.airbyte.server.handlers.WebBackendConnectionsHandler.webBackendListConnectionsForWorkspace(WebBackendConnectionsHandler.java:90) ~[io.airbyte-airbyte-server-0.30.11-alpha.jar:?]
airbyte-server      |   at io.airbyte.server.apis.ConfigurationApi.lambda$webBackendListConnectionsForWorkspace$58(ConfigurationApi.java:576) ~[io.airbyte-airbyte-server-0.30.11-alpha.jar:?]
airbyte-server      |   at io.airbyte.server.apis.ConfigurationApi.execute(ConfigurationApi.java:638) ~[io.airbyte-airbyte-server-0.30.11-alpha.jar:?]
airbyte-server      |   at io.airbyte.server.apis.ConfigurationApi.webBackendListConnectionsForWorkspace(ConfigurationApi.java:576) ~[io.airbyte-airbyte-server-0.30.11-alpha.jar:?]
airbyte-server      |   at jdk.internal.reflect.GeneratedMethodAccessor176.invoke(Unknown Source) ~[?:?]
airbyte-server      |   at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
airbyte-server      |   at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
airbyte-server      |   at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[jersey-server-2.31.jar:?]
airbyte-server      |   at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) ~[jersey-server-2.31.jar:?]
airbyte-server      |   at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) ~[jersey-server-2.31.jar:?]
airbyte-server      |   at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) ~[jersey-server-2.31.jar:?]
airbyte-server      |   at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[jersey-server-2.31.jar:?]
airbyte-server      |   at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469) ~[jersey-server-2.31.jar:?]
airbyte-server      |   at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391) ~[jersey-server-2.31.jar:?]
airbyte-server      |   at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80) ~[jersey-server-2.31.jar:?]
airbyte-server      |   at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253) ~[jersey-server-2.31.jar:?]
airbyte-server      |   at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[jersey-common-2.31.jar:?]
airbyte-server      |   at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[jersey-common-2.31.jar:?]
airbyte-server      |   at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-2.31.jar:?]
airbyte-server      |   at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-2.31.jar:?]
airbyte-server      |   at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[jersey-common-2.31.jar:?]
airbyte-server      |   at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[jersey-common-2.31.jar:?]
airbyte-server      |   at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232) ~[jersey-server-2.31.jar:?]
airbyte-server      |   at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680) ~[jersey-server-2.31.jar:?]
airbyte-server      |   at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394) ~[jersey-container-servlet-core-2.31.jar:?]
airbyte-server      |   at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) ~[jersey-container-servlet-core-2.31.jar:?]
airbyte-server      |   at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366) ~[jersey-container-servlet-core-2.31.jar:?]
airbyte-server      |   at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319) ~[jersey-container-servlet-core-2.31.jar:?]
airbyte-server      |   at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) ~[jersey-container-servlet-core-2.31.jar:?]
airbyte-server      |   at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server      |   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:569) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server      |   at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server      |   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1377) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server      |   at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server      |   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:507) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server      |   at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server      |   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server      |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server      |   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server      |   at org.eclipse.jetty.server.Server.handle(Server.java:501) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server      |   at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server      |   at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server      |   at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server      |   at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server      |   at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server      |   at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server      |   at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server      |   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server      |   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server      |   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server      |   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server      |   at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server      |   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server      |   at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server      |   at java.lang.Thread.run(Thread.java:832) [?:?]
airbyte-server      | 2021-10-06 13:17:32 ERROR i.a.s.RequestLogger(filter):87 - {workspace_app_root=/tmp/workspace/server/logs} - REQ 172.21.0.5 POST 500 /api/v1/web_backend/connections/lis```

**Comment by cgardens** [comment]
not relevant anymore. spec is stored in the db so there is no fetching to do.
