### ISSUE TITLE
connectors-ci: `fatal error: concurrent map iteration and map write` errors

### ISSUE THREAD

**Issue by kpenfound** [airbytehq/airbyte#26863]
The following category of errors have been observed in Nightly pipelines:

```
fatal error: concurrent map iteration and map write
2023-05-31T18:02:15.7435113Z 
2023-05-31T18:02:15.7435514Z goroutine 1724813 [running]:
2023-05-31T18:02:15.7436065Z reflect.mapiternext(0x4a610f?)
2023-05-31T18:02:15.7436630Z 	/usr/local/go/src/runtime/map.go:1380 +0x19
2023-05-31T18:02:15.7437099Z reflect.(*MapIter).Next(0xc0109ff3d0?)
2023-05-31T18:02:15.7437548Z 	/usr/local/go/src/reflect/value.go:1924 +0x7e
2023-05-31T18:02:15.7438188Z encoding/json.mapEncoder.encode(***0xc0109ff490?***, 0xc008c1a000, ***0x1296400?, 0xc001410780?, 0xc0115235f0?***, ***0x9?, 0x0?***)
2023-05-31T18:02:15.7438742Z 	/usr/local/go/src/encoding/json/encode.go:797 +0x33e
2023-05-31T18:02:15.7439377Z encoding/json.structEncoder.encode(***0xc00086f200?, 0x533365?, 0x7f2315bb34b8?***, 0xc0002b1e60?***, 0xc008c1a000, ***0x141e3a0?, 0xc001410708?, 0x6?***, ***0x0, 0x1***)
2023-05-31T18:02:15.7440235Z 	/usr/local/go/src/encoding/json/encode.go:759 +0x1f4
2023-05-31T18:02:15.7440864Z encoding/json.structEncoder.encode(***0xc00086e900?, 0x0?, 0xc00ea4c240?***, 0xc0009ca360?***, 0xc008c1a000, ***0x143b360?, 0xc001410700?, 0xc012877398?***, ***0x0, 0x1***)
2023-05-31T18:02:15.7441436Z 	/usr/local/go/src/encoding/json/encode.go:759 +0x1f4
2023-05-31T18:02:15.7442058Z encoding/json.ptrEncoder.encode(***0x0?***, 0xc008c1a000, ***0x1469160?, 0xc001410700?, 0x1469160?***, ***0x80?, 0x41?***)
2023-05-31T18:02:15.7442589Z 	/usr/local/go/src/encoding/json/encode.go:943 +0x21c
2023-05-31T18:02:15.7443153Z encoding/json.(*encodeState).reflectValue(0xc0109ff850?, ***0x1469160?, 0xc001410700?, 0xc001bf3560?***, ***0x40?, 0x31?***)
2023-05-31T18:02:15.7443696Z 	/usr/local/go/src/encoding/json/encode.go:358 +0x78
2023-05-31T18:02:15.7444519Z encoding/json.(*encodeState).marshal(0xc011523650?, ***0x1469160?, 0xc001410700?***, ***0x1?, 0x0?***)
2023-05-31T18:02:15.7445174Z 	/usr/local/go/src/encoding/json/encode.go:330 +0xfa
2023-05-31T18:02:15.7445786Z encoding/json.Marshal(***0x1469160, 0xc001410700***)
2023-05-31T18:02:15.7446367Z 	/usr/local/go/src/encoding/json/encode.go:161 +0xe5
2023-05-31T18:02:15.7446885Z github.com/dagger/dagger/core.encodeID[...](***0x1469160?, 0xc001410700?***)
```

Originally reported in https://github.com/airbytehq/airbyte/issues/25877

Example failure: https://github.com/airbytehq/airbyte/actions/runs/5134719754/jobs/9239119521

**Comment by vito** [comment]
Might have a lead on this. The "read" part is obvious since it's in the backtrace, but the "write" is a bit harder to find, since the backtrace doesn't specify which field led to the panic.

My guess is the "write" is in [`overrideProgress`](https://github.com/dagger/dagger/blob/2dd8717ee0c09230dbc2d9bee5d3f6343e8ccd36/core/progress.go#L19), which gets called when starting a service. In every other place I found we're careful to clone maps before modification (in `Container.Clone`).

**Comment by kpenfound** [comment]
@vito here's an extended stack if that helps:

```
2023-05-31T18:02:15.7403493Z fatal error: concurrent map iteration and map write
2023-05-31T18:02:15.7435113Z 
2023-05-31T18:02:15.7435514Z goroutine 1724813 [running]:
2023-05-31T18:02:15.7436065Z reflect.mapiternext(0x4a610f?)
2023-05-31T18:02:15.7436630Z 	/usr/local/go/src/runtime/map.go:1380 +0x19
2023-05-31T18:02:15.7437099Z reflect.(*MapIter).Next(0xc0109ff3d0?)
2023-05-31T18:02:15.7437548Z 	/usr/local/go/src/reflect/value.go:1924 +0x7e
2023-05-31T18:02:15.7438188Z encoding/json.mapEncoder.encode(***0xc0109ff490?***, 0xc008c1a000, ***0x1296400?, 0xc001410780?, 0xc0115235f0?***, ***0x9?, 0x0?***)
2023-05-31T18:02:15.7438742Z 	/usr/local/go/src/encoding/json/encode.go:797 +0x33e
2023-05-31T18:02:15.7439377Z encoding/json.structEncoder.encode(***0xc00086f200?, 0x533365?, 0x7f2315bb34b8?***, 0xc0002b1e60?***, 0xc008c1a000, ***0x141e3a0?, 0xc001410708?, 0x6?***, ***0x0, 0x1***)
2023-05-31T18:02:15.7440235Z 	/usr/local/go/src/encoding/json/encode.go:759 +0x1f4
2023-05-31T18:02:15.7440864Z encoding/json.structEncoder.encode(***0xc00086e900?, 0x0?, 0xc00ea4c240?***, 0xc0009ca360?***, 0xc008c1a000, ***0x143b360?, 0xc001410700?, 0xc012877398?***, ***0x0, 0x1***)
2023-05-31T18:02:15.7441436Z 	/usr/local/go/src/encoding/json/encode.go:759 +0x1f4
2023-05-31T18:02:15.7442058Z encoding/json.ptrEncoder.encode(***0x0?***, 0xc008c1a000, ***0x1469160?, 0xc001410700?, 0x1469160?***, ***0x80?, 0x41?***)
2023-05-31T18:02:15.7442589Z 	/usr/local/go/src/encoding/json/encode.go:943 +0x21c
2023-05-31T18:02:15.7443153Z encoding/json.(*encodeState).reflectValue(0xc0109ff850?, ***0x1469160?, 0xc001410700?, 0xc001bf3560?***, ***0x40?, 0x31?***)
2023-05-31T18:02:15.7443696Z 	/usr/local/go/src/encoding/json/encode.go:358 +0x78
2023-05-31T18:02:15.7444519Z encoding/json.(*encodeState).marshal(0xc011523650?, ***0x1469160?, 0xc001410700?***, ***0x1?, 0x0?***)
2023-05-31T18:02:15.7445174Z 	/usr/local/go/src/encoding/json/encode.go:330 +0xfa
2023-05-31T18:02:15.7445786Z encoding/json.Marshal(***0x1469160, 0xc001410700***)
2023-05-31T18:02:15.7446367Z 	/usr/local/go/src/encoding/json/encode.go:161 +0xe5
2023-05-31T18:02:15.7446885Z github.com/dagger/dagger/core.encodeID[...](***0x1469160?, 0xc001410700?***)
2023-05-31T18:02:15.7447333Z 	/app/core/util.go:24 +0x30
2023-05-31T18:02:15.7447776Z github.com/dagger/dagger/core.(*Container).ID(...)
2023-05-31T18:02:15.7448195Z 	/app/core/container.go:137
2023-05-31T18:02:15.7448639Z github.com/dagger/dagger/core.(*Container).Digest(0x1469160?)
2023-05-31T18:02:15.7449093Z 	/app/core/container.go:153 +0x2a
2023-05-31T18:02:15.7449530Z github.com/dagger/dagger/router.ToResolver[...].func1()
2023-05-31T18:02:15.7449968Z 	/app/router/schema.go:151 +0x4e6
2023-05-31T18:02:15.7451234Z github.com/dagger/graphql.resolveField(0xc00dea2540, 0xc0006d6630, ***0x1469160, 0xc001410540***, ***0xc000c4d1d0, 0x1, 0x1***, 0xc005edbc80)
2023-05-31T18:02:15.7452484Z 	/go/pkg/mod/github.com/dagger/graphql@v0.0.0-20221102000338-24d5e47d3b72/executor.go:649 +0x675
2023-05-31T18:02:15.7453219Z github.com/dagger/graphql.executeSubFields(***0xc00dea2540, 0xc0006d6630, ***0x1469160, 0xc001410540***, 0xc011f1f170, 0xc005edb338***)
2023-05-31T18:02:15.7453941Z 	/go/pkg/mod/github.com/dagger/graphql@v0.0.0-20221102000338-24d5e47d3b72/executor.go:300 +0x212
2023-05-31T18:02:15.7454706Z github.com/dagger/graphql.completeObjectValue(0xc00dea2540, 0xc0006d6630, ***_, _, _***, ***0xc012f51760, 0x9***, ***0xc000c4d178, 0x1, 0x1***, ...***, ...)
```

**Comment by alafanechere** [comment]
[Another occurrence of this error on this nightly build, happened earlier.](https://github.com/airbytehq/airbyte/actions/runs/5141498040/jobs/9254058832)

**Comment by alafanechere** [comment]
It looks like @vito found the root cause 👍 https://github.com/dagger/dagger/pull/5233#issuecomment-1572402863

**Comment by alafanechere** [comment]
@vito @kpenfound do you have an engine image with your code change we could try to deploy?

**Comment by vito** [comment]
@alafanechere `registry.dagger.io/engine:main@sha256:22d78c356e05445d2d43b3fe69a3aa986f80e712a5bbcd7164202dc7c8cd7310`

**Comment by alafanechere** [comment]
@vito I deployed the new engine image but still face the same error: https://github.com/airbytehq/airbyte/actions/runs/5149147508/jobs/9271923565

**Comment by vito** [comment]
@alafanechere Ah sorry, since the panic is actually in the `dagger session` binary that the SDK spawns, you'll need a new SDK/CLI rather than a new engine image. We're in the process of shipping a new release, so unless you have a process for bumping ahead to unreleased SDK CLIs it will be easier to wait a moment. :pray:

**Comment by alafanechere** [comment]
I confirm the upgrade to engine + CLI 0.6.1 fixed the problem and nightly build now fully ran! Thank you!!!
