### ISSUE TITLE
[destination-snowflake] Loading silently Drops rows due to Internal Stage config on_error='skip_file'

### ISSUE THREAD

**Issue by kevin868** [airbytehq/airbyte#27124]
### Connector Name

destination-snowflake

### Connector Version

0.4.63

### What step the error happened?

During the sync

### Revelant information

When performing an Airbyte sync of a table that happens to have large nested input.. the loads are **marked successful**, but rows are *silently dropped*. This is due to the config, InternalStage of Snowflake is set up using:

```
"CREATE STAGE IF NOT EXISTS %s encryption = (type = 'SNOWFLAKE_SSE') copy_options = (on_error='skip_file');";
```
With the problem being `on_error='skip_file'` means rows (entire files) are silently dropped. The error we would encounter is actually (which is the reason for the file skip):
`net.snowflake.client.jdbc.SnowflakeSQLException: Max LOB size (16777216) exceeded, actual size of parsed column is 17917227`

If we are unlucky enough, the Source connector reads 1 million rows. The problematic rows might appear in EVERY file, resulting in a successful Airbyte sync, where 0 rows actually get inserted at the Destination. If we get 'lucky' and some files have no errors, then maybe ~1000 of those 1 million rows get successfully inserted. This behavior is very dangerous, with Airbyte not highlighting any problem.

Suggestion: change the [copy_options](https://docs.snowflake.com/en/sql-reference/sql/create-stage#label-create-stage-copyoptions) to `ABORT_STATEMENT` for safest production behavior. `CONTINUE` seems better than SKIP_FILE, but the latter just seems lazy: In order to 'successfully' sync the connection, we end up dropping 1 (or all) files.

I don't believe the expected contract of Airbyte should be to silently let some rows be lost, between the Source and the Destination.  Either way, we should document the loading behavior after choosing one.

https://github.com/airbytehq/airbyte/blob/9711bee6ad3982e5008ee388e8e557dce5c0ca57/airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeInternalStagingSqlOperations.java#LL27C1-L28C1

To recap:
1. Source connector works correctly, 1 million rows read, JSON-ified and stashed into csv.gz files
2. Destination connector silently loads all these files, `on_error='skip_file'` means some files are never loaded. 
3. Normalization from the Airbyte raw table may have anywhere from 0 rows to 1 million rows to process. (drastically reduced row count compared what the Source and Airbyte workers stashed into the CSV.gz files)

## Proposed fix
Change the skip_file behavior to: `ABORT_STATEMENT`  -> safest
- or maybe `CONTINUE` -> this lets more data through, but can still hide problems

### Relevant log output

```shell
*NOTE*: the below logs happen when I *manually change the Internal Stage* to remove the SKIP_FILE config. The regular Airbyte behavior results in *no error logs* - just the destination rows loaded will be MUCH lower or 0, compared to the Source rows read.

This just shows the step WHERE the Load error occurs, so we can discuss how to handle it.


io.airbyte.integrations.destination.snowflake.SnowflakeInternalStagingSqlOperations.copyIntoTmpTableFromStage(SnowflakeInternalStagingSqlOperations.java:142) ~[io.airbyte.airbyte-integrations.connectors-destination-snowflake-0.39.37-alpha.jar:?]
2023-05-23 20:56:13 [43mdestination[0m > 	at io.airbyte.integrations.destination.staging.StagingConsumerFactory.lambda$onCloseFunction$3(StagingConsumerFactory.java:195) ~[io.airbyte.airbyte-integrations.connectors-destination-jdbc-0.39.37-alpha.jar:?]
2023-05-23 20:56:13 [43mdestination[0m > 	... 6 more
2023-05-23 20:56:13 [43mdestination[0m > 2023-05-23 20:56:13 [1;31mERROR[m i.a.i.b.AirbyteExceptionHandler(uncaughtException):26 - Something went wrong in the connector. See the logs for more details.
2023-05-23 20:56:13 [43mdestination[0m > java.lang.RuntimeException: Failed to upload data from stage 2023/05/23/20/3FF617F4-1583-4BF2-80B3-B6E89B87B55F/
2023-05-23 20:56:13 [43mdestination[0m > 	at io.airbyte.integrations.destination.staging.StagingConsumerFactory.lambda$onCloseFunction$3(StagingConsumerFactory.java:199) ~[io.airbyte.airbyte-integrations.connectors-destination-jdbc-0.39.37-alpha.jar:?]
2023-05-23 20:56:13 [43mdestination[0m > 	at io.airbyte.integrations.destination.buffered_stream_consumer.OnCloseFunction.accept(OnCloseFunction.java:9) ~[io.airbyte.airbyte-integrations.bases-base-java-0.39.37-alpha.jar:?]
2023-05-23 20:56:13 [43mdestination[0m > 	at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.close(BufferedStreamConsumer.java:191) ~[io.airbyte.airbyte-integrations.bases-base-java-0.39.37-alpha.jar:?]
2023-05-23 20:56:13 [43mdestination[0m > 	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.close(FailureTrackingAirbyteMessageConsumer.java:64) ~[io.airbyte.airbyte-integrations.bases-base-java-0.39.37-alpha.jar:?]
2023-05-23 20:56:13 [43mdestination[0m > 	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:147) ~[io.airbyte.airbyte-integrations.bases-base-java-0.39.37-alpha.jar:?]
2023-05-23 20:56:13 [43mdestination[0m > 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:97) ~[io.airbyte.airbyte-integrations.bases-base-java-0.39.37-alpha.jar:?]
2023-05-23 20:56:13 [43mdestination[0m > 	at io.airbyte.integrations.destination.snowflake.SnowflakeDestination.main(SnowflakeDestination.java:30) ~[io.airbyte.airbyte-integrations.connectors-destination-snowflake-0.39.37-alpha.jar:?]
2023-05-23 20:56:13 [43mdestination[0m > Caused by: net.snowflake.client.jdbc.SnowflakeSQLException: Max LOB size (16777216) exceeded, actual size of parsed column is 17917227
2023-05-23 20:56:13 [43mdestination[0m >   File '2023/05/23/20/3FF617F4-1583-4BF2-80B3-B6E89B87B55F/ced0d4ef-19e5-4897-adb7-015a19f4f1c11323605938297866175.csv.gz', line 6315, character 19010206
2023-05-23 20:56:13 [43mdestination[0m >   Row 6315, column "_AIRBYTE_TMP_KMP_AB_TABLE_NAME_STRIPPED"["_AIRBYTE_DATA":2]
2023-05-23 20:56:13 [43mdestination[0m >   If you would like to continue loading when an error is encountered, use other values such as 'SKIP_FILE' or 'CONTINUE' for the ON_ERROR option. For more information on loading options, please run 'info loading_data' in a SQL client.
2023-05-23 20:56:13 [43mdestination[0m > 	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:127) ~[snowflake-jdbc-3.13.9.jar:3.13.9]
2023-05-23 20:56:13 [43mdestination[0m > 	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:67) ~[snowflake-jdbc-3.13.9.jar:3.13.9]
2023-05-23 20:56:13 [43mdestination[0m > 	at net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:442) ~[snowflake-jdbc-3.13.9.jar:3.13.9]
2023-05-23 20:56:13 [43mdestination[0m > 	at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:345) ~[snowflake-jdbc-3.13.9.jar:3.13.9]
2023-05-23 20:56:13 [43mdestination[0m > 	at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:487) ~[snowflake-jdbc-3.13.9.jar:3.13.9]
2023-05-23 20:56:13 [43mdestination[0m > 	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:198) ~[snowflake-jdbc-3.13.9.jar:3.13.9]
2023-05-23 20:56:13 [43mdestination[0m > 	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:135) ~[snowflake-jdbc-3.13.9.jar:3.13.9]
2023-05-23 20:56:13 [43mdestination[0m > 	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:781) ~[snowflake-jdbc-3.13.9.jar:3.13.9]
2023-05-23 20:56:13 [43mdestination[0m > 	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:677) ~[snowflake-jdbc-3.13.9.jar:3.13.9]
2023-05-23 20:56:13 [43mdestination[0m > 	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeInternal(SnowflakeStatementV1.java:287) ~[snowflake-jdbc-3.13.9.jar:3.13.9]
2023-05-23 20:56:13 [43mdestination[0m > 	at net.snowflake.client.jdbc.SnowflakeStatementV1.execute(SnowflakeStatementV1.java:342) ~[snowflake-jdbc-3.13.9.jar:3.13.9]
2023-05-23 20:56:13 [43mdestination[0m > 	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94) ~[HikariCP-5.0.1.jar:?]
2023-05-23 20:56:13 [43mdestination[0m > 	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-5.0.1.jar:?]
2023-05-23 20:56:13 [43mdestination[0m > 	at io.airbyte.db.jdbc.JdbcDatabase.lambda$execute$0(JdbcDatabase.java:47) ~[io.airbyte.airbyte-db-db-lib-0.39.37-alpha.jar:?]
2023-05-23 20:56:13 [43mdestination[0m > 	at io.airbyte.db.jdbc.DefaultJdbcDatabase.execute(DefaultJdbcDatabase.java:44) ~[io.airbyte.airbyte-db-db-lib-0.39.37-alpha.jar:?]
2023-05-23 20:56:13 [43mdestination[0m > 	at io.airbyte.db.jdbc.JdbcDatabase.execute(JdbcDatabase.java:47) ~[io.airbyte.airbyte-db-db-lib-0.39.37-alpha.jar:?]
2023-05-23 20:56:13 [43mdestination[0m > 	at io.airbyte.integrations.destination.snowflake.SnowflakeInternalStagingSqlOperations.copyIntoTmpTableFromStage(SnowflakeInternalStagingSqlOperations.java:142) ~[io.airbyte.airbyte-integrations.connectors-destination-snowflake-0.39.37-alpha.jar:?]
2023-05-23 20:56:13 [43mdestination[0m > 	at io.airbyte.integrations.destination.staging.StagingConsumerFactory.lambda$onCloseFunction$3(StagingConsumerFactory.java:195) ~[io.airbyte.airbyte-integrations.connectors-destination-jdbc-0.39.37-alpha.jar:?]
2023-05-23 20:56:13 [43mdestination[0m > 	... 6 more
2023-05-23 20:56:13 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$getDestinationOutputRunnable$7):415 - State in DefaultReplicationWorker from destination: io.airbyte.protocol.models.AirbyteMessage@d30b303[type=TRACE,log=<null>,spec=<null>,connectionStatus=<null>,catalog=<null>,record=<null>,state=<null>,trace=io.airbyte.protocol.models.AirbyteTraceMessage@3f75cd5[type=ERROR,emittedAt=1.684875373257E12,error=io.airbyte.protocol.models.AirbyteErrorTraceMessage@7c8d873[message=Something went wrong in the connector. See the logs for more details.,internalMessage=java.lang.RuntimeException: Failed to upload data from stage 2023/05/23/20/3FF617F4-1583-4BF2-80B3-B6E89B87B55F/,stackTrace=java.lang.RuntimeException: Failed to upload data from stage 2023/05/23/20/3FF617F4-1583-4BF2-80B3-B6E89B87B55F/
	at io.airbyte.integrations.destination.staging.StagingConsumerFactory.lambda$onCloseFunction$3(StagingConsumerFactory.java:199)
	at io.airbyte.integrations.destination.buffered_stream_consumer.OnCloseFunction.accept(OnCloseFunction.java:9)
	at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.close(BufferedStreamConsumer.java:191)
	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.close(FailureTrackingAirbyteMessageConsumer.java:64)
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:147)
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:97)
	at io.airbyte.integrations.destination.snowflake.SnowflakeDestination.main(SnowflakeDestination.java:30)
Caused by: net.snowflake.client.jdbc.SnowflakeSQLException: Max LOB size (16777216) exceeded, actual size of parsed column is 17917227
  File '2023/05/23/20/3FF617F4-1583-4BF2-80B3-B6E89B87B55F/ced0d4ef-19e5-4897-adb7-015a19f4f1c11323605938297866175.csv.gz', line 6315, character 19010206
  Row 6315, column "_AIRBYTE_TMP_KMP_AB_TABLE_NAME_STRIPPED"["_AIRBYTE_DATA":2]
  If you would like to continue loading when an error is encountered, use other values such as 'SKIP_FILE' or 'CONTINUE' for the ON_ERROR option. For more information on loading options, please run 'info loading_data' in a SQL client.
	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:127)
	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:67)
	at net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:442)
	at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:345)
	at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:487)
	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:198)
	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:135)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:781)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:677)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeInternal(SnowflakeStatementV1.java:287)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.execute(SnowflakeStatementV1.java:342)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at io.airbyte.db.jdbc.JdbcDatabase.lambda$execute$0(JdbcDatabase.java:47)
	at io.airbyte.db.jdbc.DefaultJdbcDatabase.execute(DefaultJdbcDatabase.java:44)
	at io.airbyte.db.jdbc.JdbcDatabase.execute(JdbcDatabase.java:47)
	at io.airbyte.integrations.destination.snowflake.SnowflakeInternalStagingSqlOperations.copyIntoTmpTableFromStage(SnowflakeInternalStagingSqlOperations.java:142)
	at io.airbyte.integrations.destination.staging.StagingConsumerFactory.lambda$onCloseFunction$3(StagingConsumerFactory.java:195)
	... 6 more
,failureType=system_error,additionalProperties={}],additionalProperties={}],additionalProperties={}]
2023-05-23 20:56:13 [1;31mERROR[m i.a.w.g.DefaultReplicationWorker(run):180 - Sync worker failed.
java.util.concurrent.ExecutionException: io.airbyte.workers.general.DefaultReplicationWorker$DestinationException: Destination process exited with non-zero exit code 1
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:175) ~[io.airbyte-airbyte-workers-0.39.34-alpha.jar:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:65) ~[io.airbyte-airbyte-workers-0.39.34-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:158) ~[io.airbyte-airbyte-workers-0.39.34-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
	Suppressed: io.airbyte.workers.exception.WorkerException: Destination process exit with code 1. This warning is normal if the job was cancelled.
		at io.airbyte.workers.internal.DefaultAirbyteDestination.close(DefaultAirbyteDestination.java:119) ~[io.airbyte-airbyte-workers-0.39.34-alpha.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:137) ~[io.airbyte-airbyte-workers-0.39.34-alpha.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:65) ~[io.airbyte-airbyte-workers-0.39.34-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:158) ~[io.airbyte-airbyte-workers-0.39.34-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: io.airbyte.workers.general.DefaultReplicationWorker$DestinationException: Destination process exited with non-zero exit code 1
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$getDestinationOutputRunnable$7(DefaultReplicationWorker.java:420) ~[io.airbyte-airbyte-workers-0.39.34-alpha.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
2023-05-23 20:56:13 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):239 - sync summary: 
```
```


### Contribute

- [ ] Yes, I want to contribute

**Comment by kevin868** [comment]
@subodh1810 can we get a triage on this? There's a second report of this problem, and the problem still exists on destination-snowflake `1.0.5`

**Comment by anchitagarwal** [comment]
We are potentially facing a similar issue with our Iceberg and Databricks destinations. Here's the scenario:

1. The destination is in the process of copying data from staging/temp tables to final tables.
2. An error occurs during this process, causing the connection to fail.
3. Despite the failure, the state is committed for the source, and the source cursor advances.
4. The next time a sync runs, the new read query includes a WHERE clause like `WHERE xmin::text::bigint >= 1091685220`.
5. As a result, we observe data loss because the source cursor has moved forward, and the data that failed to be copied during the previous sync is not included in the new read query.

This issue seems to occur when a failure happens during the data copying process. Any insights or suggestions would be greatly appreciated.

**Comment by marcosmarxm** [comment]
@anchitagarwal please open a new issue.

I'm closing this issue as it reports a problem to an outdated version of Snowflake (2023-04-27). Current version of Snowflake connector is 3.6.1. If you faced the issue using latest version please open a new issue reporting the problem.
