### ISSUE TITLE
Bug: Unexpected record type when pointing to array value

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#27293]
## Context

In a build-a-connector session, the user ran into the following error when testing the `Cases per district` stream of [this builder YAML](https://drive.google.com/file/d/1aeUWdxPfDDGBrIwXyDJ0R3aqKmW7DveR/view?usp=sharing)

```
Unexpected record type. Expected typing.Union[typing.Mapping[str, typing.Any], airbyte_protocol.models.airbyte_protocol.AirbyteMessage]. Got <class 'list'>. This is probably due to a bug in the CDK. - Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/connector_builder/message_grouper.py", line 182, in _read_stream
    yield from AirbyteEntrypoint(source).read(source.spec(self.logger), config, configured_catalog, {})
  File "/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 132, in read
    yield from self.source.read(self.logger, config, catalog, state)
  File "/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/manifest_declarative_source.py", line 130, in read
    yield from super().read(logger, config, catalog, state)
  File "/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 139, in read
    raise e
  File "/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 120, in read
    yield from self._read_stream(
  File "/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 194, in _read_stream
    for record in record_iterator:
  File "/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 324, in _read_full_refresh
    for record_data_or_message in record_data_or_messages:
  File "/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py", line 101, in read_records
    yield self._apply_transformations(record, self.config, stream_slice)
  File "/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py", line 121, in _apply_transformations
    raise ValueError(
ValueError: Unexpected record type. Expected typing.Union[typing.Mapping[str, typing.Any], airbyte_protocol.models.airbyte_protocol.AirbyteMessage]. Got <class 'list'>. This is probably due to a bug in the CDK.
```

This bug happened when `history` was added to the Record Selector of that stream.

Adding a `*` after `history` seems to fix the issue, so this is error seems to come from pointing the record selector at a field which has an array value.

## Acceptance Criteria
Users don't need to add a `*` when pointing the record selector at an array value to avoid the above error

**Comment by lmossman** [comment]
Grooming notes:
- This shouldn't be happening; there is a check for pointing to an array in the code, so this seems like a bug for this particular YAML
