### ISSUE TITLE
Export configuration issue

### ISSUE THREAD

**Issue by FUT** [airbytehq/airbyte#2733]
## Expected Behavior
Export configuration button should let me download the archive with full configurations.

## Current Behavior
I'm getting the error

## Logs
```
2021-04-05 13:04:42 DEBUG i.a.s.e.UncaughtExceptionMapper(toResponse):42 - {workspace_app_root=/tmp/workspace/server/logs} - Uncaught exception
java.lang.RuntimeException: java.nio.file.NoSuchFileException: /tmp/airbyte_archive16791194529863967286.tar.gz
        at io.airbyte.commons.io.FileTtlManager.lambda$reportCacheStatus$1(FileTtlManager.java:94) ~[io.airbyte-airbyte-commons-0.18.2-alpha.jar:?]
        at java.util.concurrent.ConcurrentMap.forEach(ConcurrentMap.java:122) ~[?:?]
        at io.airbyte.commons.io.FileTtlManager.reportCacheStatus(FileTtlManager.java:86) ~[io.airbyte-airbyte-commons-0.18.2-alpha.jar:?]
        at io.airbyte.commons.io.FileTtlManager.register(FileTtlManager.java:79) ~[io.airbyte-airbyte-commons-0.18.2-alpha.jar:?]
        at io.airbyte.server.handlers.ArchiveHandler.exportData(ArchiveHandler.java:83) ~[io.airbyte-airbyte-server-0.18.2-alpha.jar:?]
        at io.airbyte.server.apis.ConfigurationApi.execute(ConfigurationApi.java:475) ~[io.airbyte-airbyte-server-0.18.2-alpha.jar:?]
        at io.airbyte.server.apis.ConfigurationApi.exportArchive(ConfigurationApi.java:465) ~[io.airbyte-airbyte-server-0.18.2-alpha.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[jersey-server-2.31.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) ~[jersey-server-2.31.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) ~[jersey-server-2.31.jar:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) ~[jersey-server-2.31.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[jersey-server-2.31.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469) ~[jersey-server-2.31.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391) ~[jersey-server-2.31.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80) ~[jersey-server-2.31.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253) [jersey-server-2.31.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [jersey-common-2.31.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [jersey-common-2.31.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [jersey-common-2.31.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [jersey-common-2.31.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [jersey-common-2.31.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [jersey-common-2.31.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232) [jersey-server-2.31.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680) [jersey-server-2.31.jar:?]
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394) [jersey-container-servlet-core-2.31.jar:?]
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) [jersey-container-servlet-core-2.31.jar:?]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366) [jersey-container-servlet-core-2.31.jar:?]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319) [jersey-container-servlet-core-2.31.jar:?]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) [jersey-container-servlet-core-2.31.jar:?]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763) [jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:569) [jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1377) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:507) [jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.server.Server.handle(Server.java:501) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.nio.file.NoSuchFileException: /tmp/airbyte_archive16791194529863967286.tar.gz
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
        at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149) ~[?:?]
        at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99) ~[?:?]
        at java.nio.file.Files.readAttributes(Files.java:1843) ~[?:?]
        at java.nio.file.Files.size(Files.java:2460) ~[?:?]
        at io.airbyte.commons.io.FileTtlManager.lambda$reportCacheStatus$1(FileTtlManager.java:92) ~[io.airbyte-airbyte-commons-0.18.2-alpha.jar:?]
        ... 58 more
2021-04-05 13:04:42 ERROR i.a.s.RequestLogger(filter):105 - {workspace_app_root=/tmp/workspace/server/logs} - REQ 172.20.0.1 POST 500 /api/v1/deployment/export - {}

```

## Steps to Reproduce
1. Setup fresh Airbyte using docker-compose file
1. Go to Admin -> Configuration
1. Press Export configuration button
1. Nothing happens (error in the logs)

## Severity of the bug for you
High

## Airbyte Version
0.18.2-alpha (same on 0.14.1-alpha)

## Additional context
Ubuntu 20.04. Docker 19 and 20

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368157879551) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
@FUT thanks for creating this issue. We'll investigate soon.

next steps: 
1. reproduce this issue and verify whether it is a problem for all Airbyte instances. If so, then the priority is critical. 
2. fix the issue

**Comment by jrhizor** [comment]
I wasn't able to reproduce this with a fresh Airbyte instance on Mac.

@FUT between steps 1) and 2) did you configure any sources or destinations? If so, which ones?

Also, is there any other context on the environment you're running? Is it on Ubuntu on a VM/laptop/EC2/etc?

**Comment by ifokeev** [comment]
We have some internal airbyte setup, export works fine on master branch, but not in our environment. I suppose it's because of some ENV variables or hardcoded solutions inside airbyte.

For instance, It catches all exceptions https://github.com/airbytehq/airbyte/blob/73044ac29047ab87cc9fb08682eafa0ad203b37a/airbyte-server/src/main/java/io/airbyte/server/handlers/ArchiveHandler.java#L89 and I can't understand the problem really. After export just getting 
<img width="1407" alt="Screen Shot 2021-04-19 at 18 30 42" src="https://user-images.githubusercontent.com/2017148/115262584-5b31cf00-a13d-11eb-94f9-80e6ce755c4a.png">

how to catch the error?

**Comment by davinchia** [comment]
@FUT are you still seeing this?

**Comment by cgardens** [comment]
it does now.
