### ISSUE TITLE
Snowflake Destination Acceptance Tests failing on Master

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#27509]

**Comment by evantahler** [comment]
From today's nightly builds (https://github.com/airbytehq/airbyte/actions/runs/5317126142/jobs/9627322098)

SNOWFLAKE:

```
2023-06-20T03:35:17.7724200Z #504 1081.5 SnowflakeInternalStagingDestinationAcceptanceTest > testSyncWriteSameTableNameDifferentNamespace() FAILED
2023-06-20T03:35:17.7731394Z #504 1081.5     org.opentest4j.AssertionFailedError: expected: <10> but was: <0>
2023-06-20T03:35:17.7737090Z #504 1081.5         at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
2023-06-20T03:35:17.7743022Z #504 1081.5         at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
2023-06-20T03:35:17.7750461Z #504 1081.5         at app//org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
2023-06-20T03:35:17.7758455Z #504 1081.5         at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
2023-06-20T03:35:17.7767011Z #504 1081.5         at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
2023-06-20T03:35:17.7775169Z #504 1081.5         at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:528)
2023-06-20T03:35:17.7784422Z #504 1081.5         at app//io.***.integrations.standardtest.destination.comparator.AdvancedTestDataComparator.assertSameData(AdvancedTestDataComparator.java:50)
2023-06-20T03:35:17.7795009Z #504 1081.5         at app//io.***.integrations.standardtest.destination.DestinationAcceptanceTest.assertSameMessages(DestinationAcceptanceTest.java:1422)
2023-06-20T03:35:17.7805944Z #504 1081.5         at app//io.***.integrations.standardtest.destination.DestinationAcceptanceTest.retrieveRawRecordsAndAssertSameMessages(DestinationAcceptanceTest.java:1402)
2023-06-20T03:35:17.7815509Z #504 1081.5         at app//io.***.integrations.standardtest.destination.DestinationAcceptanceTest.testSyncWriteSameTableNameDifferentNamespace(DestinationAcceptanceTest.java:1115)
```

```
2023-06-20T03:35:17.8597309Z #504 1081.5 SnowflakeGcsCopyDestinationAcceptanceTest > testSyncWriteSameTableNameDifferentNamespace() FAILED
2023-06-20T03:35:17.8604869Z #504 1081.5     org.opentest4j.AssertionFailedError: expected: <10> but was: <0>
2023-06-20T03:35:17.8612387Z #504 1081.5         at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
2023-06-20T03:35:17.8620503Z #504 1081.5         at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
2023-06-20T03:35:17.8627217Z #504 1081.5         at app//org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
2023-06-20T03:35:17.8633825Z #504 1081.5         at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
2023-06-20T03:35:17.8640417Z #504 1081.5         at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
2023-06-20T03:35:17.8648802Z #504 1081.5         at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:528)
2023-06-20T03:35:17.8657819Z #504 1081.5         at app//io.***.integrations.standardtest.destination.comparator.AdvancedTestDataComparator.assertSameData(AdvancedTestDataComparator.java:50)
2023-06-20T03:35:17.8665147Z #504 1081.5         at app//io.***.integrations.standardtest.destination.DestinationAcceptanceTest.assertSameMessages(DestinationAcceptanceTest.java:1422)
2023-06-20T03:35:17.8675883Z #504 1081.5         at app//io.***.integrations.standardtest.destination.DestinationAcceptanceTest.retrieveRawRecordsAndAssertSameMessages(DestinationAcceptanceTest.java:1402)
2023-06-20T03:35:17.8684483Z #504 1081.5         at 
```

BIGQUERY

```
2023-06-20T04:07:54.8191984Z #511 327.7 BigQueryDestinationTest > testWriteSuccess(String) > io.***.integrations.destination.bigquery.BigQueryDestinationTest.testWriteSuccess(String)[3] FAILED
2023-06-20T04:07:54.8204715Z #511 327.7     com.amazonaws.services.s3.model.AmazonS3Exception: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: null; S3 Extended Request ID: null; Proxy: null), S3 Extended Request ID: null
2023-06-20T04:07:54.8213863Z #511 327.7         at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879)
2023-06-20T04:07:54.8221878Z #511 327.7         at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418)
2023-06-20T04:07:54.8230330Z #511 327.7         at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387)
2023-06-20T04:07:54.8237865Z #511 327.7         at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
```

```
```

**Comment by evantahler** [comment]
Grooming:
* The tests ARE passing locally.  
* Removing silly tests is also OK
* Goal is to be able to trust master branch

**Comment by ryankfu** [comment]
@jbfbell I split the ticket into a BigQuery specific ticket and added you as the assignee. I'll continue taking a look into Snowflake

**Comment by edgao** [comment]
whatever this was is no longer happening... snowflake tests are running successfully right now. Anything else we want to do here?

**Comment by evantahler** [comment]
closed!  
I'll bet this was that we had too many schemas
