### ISSUE TITLE
YouTube Analytics Source refresh_token error

### ISSUE THREAD

**Issue by jasonpedely** [airbytehq/airbyte#27672]
### Connector Name

source-YouTube Analytics

### Connector Version

	0.1.4

### What step the error happened?

Configuring a new connector

### Revelant information

Internal message: 400 Client Error: Bad Request for url: https://oauth2.googleapis.com/token
Failure origin: source
Failure type: system_error

### Relevant log output

```shell
2023-06-23 16:03:50 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):136 - Docker volume job log path: /tmp/workspace/9192ed04-4032-40fe-b6e3-d87d4988cc84/0/logs.log
2023-06-23 16:03:50 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):141 - Executing worker wrapper. Airbyte version: 0.44.12
2023-06-23 16:03:50 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitterThrows):229 - Attempt 0 to save workflow id for cancellation
2023-06-23 16:03:50 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-06-23 16:03:50 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - ----- START CHECK -----
2023-06-23 16:03:50 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-06-23 16:03:50 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2023-06-23 16:03:50 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2023-06-23 16:03:50 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2023-06-23 16:03:50 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2023-06-23 16:03:50 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable LAUNCHDARKLY_KEY: ''
2023-06-23 16:03:50 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - Checking if airbyte/source-youtube-analytics:0.1.4 exists...
2023-06-23 16:03:50 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - airbyte/source-youtube-analytics:0.1.4 was found locally.
2023-06-23 16:03:50 [32mINFO[m i.a.w.p.DockerProcessFactory(create):139 - Creating docker container = source-youtube-analytics-check-9192ed04-4032-40fe-b6e3-d87d4988cc84-0-twaub with resources io.airbyte.config.ResourceRequirements@22f80c4b[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts null
2023-06-23 16:03:50 [32mINFO[m i.a.w.p.DockerProcessFactory(create):192 - Preparing command: docker run --rm --init -i -w /data/9192ed04-4032-40fe-b6e3-d87d4988cc84/0 --log-driver none --name source-youtube-analytics-check-9192ed04-4032-40fe-b6e3-d87d4988cc84-0-twaub --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/source-youtube-analytics:0.1.4 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e USE_STREAM_CAPABLE_STATE=true -e FIELD_SELECTION_WORKSPACES= -e WORKER_ENVIRONMENT=DOCKER -e AIRBYTE_ROLE= -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=0 -e OTEL_COLLECTOR_ENDPOINT=http://host.docker.internal:4317 -e FEATURE_FLAG_CLIENT=config -e AIRBYTE_VERSION=0.44.12 -e WORKER_JOB_ID=9192ed04-4032-40fe-b6e3-d87d4988cc84 airbyte/source-youtube-analytics:0.1.4 check --config source_config.json
2023-06-23 16:03:50 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(create):177 - Reading messages from protocol version 0.2.0
2023-06-23 16:03:51 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):308 - 400 Client Error: Bad Request for url: https://oauth2.googleapis.com/token
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 156, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 91, in run
    yield from map(AirbyteEntrypoint.airbyte_message_to_string, self.check(source_spec, config))
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 112, in check
    check_result = self.source.check(self.logger, config)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 84, in check
    check_succeeded, error = self.check_connection(logger, config)
  File "/airbyte/integration_code/source_youtube_analytics/source.py", line 266, in check_connection
    result = jobs_resource.list()
  File "/airbyte/integration_code/source_youtube_analytics/source.py", line 144, in list
    results = list(self.read_records(sync_mode=None))
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 423, in read_records
    yield from self._read_pages(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 439, in _read_pages
    request, response = self._fetch_next_page(stream_slice, stream_state, next_page_token)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 453, in _fetch_next_page
    request = self._create_prepared_request(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 280, in _create_prepared_request
    return self._session.prepare_request(requests.Request(**args))
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 372, in prepare
    self.prepare_auth(auth, url)
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 603, in prepare_auth
    r = auth(self)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py", line 28, in __call__
    request.headers.update(self.get_auth_header())
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py", line 33, in get_auth_header
    return {"Authorization": f"Bearer {self.get_access_token()}"}
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py", line 38, in get_access_token
    token, expires_in = self.refresh_access_token()
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py", line 98, in refresh_access_token
    response_json = self._get_refresh_access_token_response()
  File "/usr/local/lib/python3.9/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py", line 83, in _get_refresh_access_token_response
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://oauth2.googleapis.com/token
2023-06-23 16:03:51 [33mWARN[m i.a.w.g.DefaultCheckConnectionWorker(run):108 - Check connection job subprocess finished with exit code 1
2023-06-23 16:03:51 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):163 - Stopping cancellation check scheduling...
2023-06-23 16:03:51 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-06-23 16:03:51 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - ----- END CHECK -----
2023-06-23 16:03:51 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 -
```

### Contribute

- [X] Yes, I want to contribute

**Comment by efimmatytsin** [comment]
we have the same problem

**Comment by Arjunhg** [comment]
Hi @jasonpedely 

I want to work on this issue. Can you please assign it to me?

**Comment by jasonpedely** [comment]
@Arjunhg Please follow: https://docs.airbyte.com/contributing-to-airbyte

**Comment by Arjunhg** [comment]
> @Arjunhg Please follow: https://docs.airbyte.com/contributing-to-airbyte

I looked into it. Thanks for the guidance, I will do as it says.

**Comment by justinbchau** [comment]
all yours @Arjunhg

**Comment by jovezhong** [comment]
I tried YouTube source connector on both Airbyte Cloud and self-hosted one. Both failed.

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 180 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
