### ISSUE TITLE
source-mssql : thread clean up warning 

### ISSUE THREAD

**Issue by sivankumar86** [airbytehq/airbyte#27740]
### Connector Name

source-mssql

### Connector Version

1.0.19

### What step the error happened?

During the sync

### Revelant information

Sync works however, there is a warning message on thread cleanup. Airbyte version is 0.50.4

### Relevant log output

```shell
2023-06-27 03:19:21 INFO i.a.w.p.KubePodProcess(copyFilesToKubeConfigVolume):334 - kubectl cp complete, closing process
2023-06-27 03:19:21 INFO i.a.w.p.KubePodProcess(copyFilesToKubeConfigVolume):309 - Uploading file: FINISHED_UPLOADING
2023-06-27 03:19:21 INFO i.a.w.p.KubePodProcess(copyFilesToKubeConfigVolume):317 - kubectl cp /tmp/a2f9f4da-f3aa-4f22-a596-20e7da5dcd94/FINISHED_UPLOADING product-analytics/source-mssql-read-19644-0-ewgus:/config/FINISHED_UPLOADING -c init
2023-06-27 03:19:21 INFO i.a.w.p.KubePodProcess(copyFilesToKubeConfigVolume):320 - Waiting for kubectl cp to complete
2023-06-27 03:19:21 INFO i.a.w.p.KubePodProcess(copyFilesToKubeConfigVolume):334 - kubectl cp complete, closing process
2023-06-27 03:19:21 INFO i.a.w.p.KubePodProcess(<init>):616 - Waiting until pod is ready...
2023-06-27 03:19:22 INFO i.a.w.p.KubePodProcess(lambda$setupStdOutAndStdErrListeners$11):665 - Setting stdout...
2023-06-27 03:19:22 INFO i.a.w.p.KubePodProcess(lambda$setupStdOutAndStdErrListeners$12):677 - Setting stderr...
2023-06-27 03:19:23 INFO i.a.w.p.KubePodProcess(<init>):632 - Reading pod IP...
2023-06-27 03:19:23 INFO i.a.w.p.KubePodProcess(<init>):634 - Pod IP: 10.52.96.188
2023-06-27 03:19:23 INFO i.a.w.p.KubePodProcess(<init>):641 - Using null stdin output stream...
2023-06-27 03:19:23 INFO i.a.w.i.VersionedAirbyteStreamFactory(create):177 - Reading messages from protocol version 0.2.0
2023-06-27 03:19:23 INFO i.a.w.g.DefaultReplicationWorker(lambda$readFromDstRunnable$4):228 - Destination output thread started.
2023-06-27 03:19:23 INFO i.a.w.i.HeartbeatTimeoutChaperone(runWithHeartbeatThread):94 - Starting source heartbeat check. Will check every 1 minutes.
2023-06-27 03:19:23 INFO i.a.w.g.DefaultReplicationWorker(lambda$readFromSrcAndWriteToDstRunnable$5):272 - Replication thread started.
2023-06-27 03:19:31 INFO i.a.w.g.DefaultReplicationWorker(lambda$readFromSrcAndWriteToDstRunnable$5):299 - Source has no more messages, closing connection.
2023-06-27 03:19:32 INFO i.a.w.p.KubePodProcess(close):797 - (pod: product-analytics / source-mssql-read-19644-0-ewgus) - Closed all resources for pod
2023-06-27 03:19:32 INFO i.a.w.g.ReplicationWorkerHelper(endOfSource):157 - Total records read: 4 (0 bytes)
2023-06-27 03:19:32 INFO i.a.w.i.FieldSelector(reportMetrics):122 - Schema validation was performed to a max of 10 records with errors per stream.
2023-06-27 03:19:32 INFO i.a.w.i.HeartbeatTimeoutChaperone(runWithHeartbeatThread):111 - thread status... heartbeat thread: false , replication thread: true
2023-06-27 03:19:32 INFO i.a.w.g.DefaultReplicationWorker(replicate):201 - Waiting for source and destination threads to complete.
2023-06-27 03:19:32 INFO i.a.w.g.DefaultReplicationWorker(replicate):206 - One of source or destination thread complete. Waiting on the other.
2023-06-27 03:19:32 INFO i.a.w.g.ReplicationWorkerHelper(processMessageFromDestination):234 - State in DefaultReplicationWorker from destination: io.airbyte.protocol.models.AirbyteMessage@24c1362b[type=STATE,log=<null>,spec=<null>,connectionStatus=<null>,catalog=<null>,record=<null>,state=io.airbyte.protocol.models.AirbyteStateMessage@2ef85e7[type=LEGACY,stream=<null>,global=<null>,data={"cdc":false,"streams":[{"stream_name":"GatewayTokens","stream_namespace":"dbo","cursor_field":["CreatedTimestamp"],"cursor":"2023-06-27T00:56:57.697000Z","cursor_record_count":1}]},additionalProperties={}],trace=<null>,control=<null>,additionalProperties={}]
2023-06-27 03:19:32 INFO i.a.w.h.AirbyteMessageDataExtractor(getStreamFromMessage):42 - Extracting stream from state message: null
2023-06-27 03:19:32 INFO i.a.w.i.s.SyncPersistenceImpl(startBackgroundFlushStateTask):180 - starting state flush thread for connectionId 9adaaa75-5c35-4fbe-b6de-1ef388ebb5c1
2023-06-27 03:19:35 INFO i.a.w.p.KubePodProcess(close):797 - (pod: product-analytics / destination-snowflake-write-19644-0-saxjp) - Closed all resources for pod
2023-06-27 03:19:35 INFO i.a.w.g.DefaultReplicationWorker(replicate):208 - Source and destination threads complete.
2023-06-27 03:19:35 INFO i.a.w.t.TemporalAttemptExecution(get):163 - Stopping cancellation check scheduling...
2023-06-27 03:19:35 INFO i.a.w.t.s.ReplicationActivityImpl(lambda$replicate$3):158 - sync summary: io.airbyte.config.StandardSyncOutput@1ae0f8b8[standardSyncSummary=io.airbyte.config.StandardSyncSummary@514bb4fe[status=completed,recordsSynced=0,bytesSynced=0,startTime=1687835919246,endTime=1687835975424,totalStats=io.airbyte.config.SyncStats@5829686e[bytesCommitted=0,bytesEmitted=0,destinationStateMessagesEmitted=1,destinationWriteEndTime=1687835975420,destinationWriteStartTime=1687835919246,estimatedBytes=<null>,estimatedRecords=<null>,meanSecondsBeforeSourceStateMessageEmitted=0,maxSecondsBeforeSourceStateMessageEmitted=0,maxSecondsBetweenStateMessageEmittedandCommitted=6,meanSecondsBetweenStateMessageEmittedandCommitted=6,recordsEmitted=0,recordsCommitted=0,replicationEndTime=1687835975424,replicationStartTime=1687835919246,sourceReadEndTime=1687835972437,sourceReadStartTime=1687835958383,sourceStateMessagesEmitted=1,additionalProperties={}],streamStats=[],additionalProperties={}],normalizationSummary=<null>,webhookOperationSummary=<null>,state=<null>,outputCatalog=io.airbyte.protocol.models.ConfiguredAirbyteCatalog@4d2a812f[streams=[io.airbyte.protocol.models.ConfiguredAirbyteStream@5092850a[stream=io.airbyte.protocol.models.AirbyteStream@5cf227a2[name=payments_GatewayTokens,jsonSchema={"type":"object","properties":{"TokenizedCard":{"type":"string"},"CreatedByUserId":{"type":"string"},"CreatedTimestamp":{"type":"string"},"PaymentMethodId":{"type":"string"},"Gateway":{"airbyte_type":"integer","type":"number"},"Id":{"type":"string"}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[[Id]],namespace=<null>,additionalProperties={}],syncMode=incremental,cursorField=[CreatedTimestamp],destinationSyncMode=append,primaryKey=[[Id]],additionalProperties={}]],additionalProperties={}],failures=[],commitStateAsap=true,additionalProperties={}]
2023-06-27 03:19:35 INFO i.a.w.t.s.ReplicationActivityImpl(lambda$replicate$3):163 - Sync summary length: 1838
2023-06-27 03:19:35 INFO i.a.c.t.TemporalUtils(withBackgroundHeartbeat):307 - Stopping temporal heartbeating...
2023-06-27 03:19:23 destination > INFO i.a.i.b.a.AdaptiveDestinationRunner$Runner(run):86 Starting destination: io.airbyte.integrations.destination.snowflake.SnowflakeDestination
2023-06-27 03:19:23 destination > INFO i.a.i.b.IntegrationCliParser(parseOptions):126 integration args: {catalog=destination_catalog.json, write=null, config=destination_config.json}
2023-06-27 03:19:23 destination > INFO i.a.i.b.IntegrationRunner(runInternal):106 Running integration: io.airbyte.integrations.destination.snowflake.SnowflakeDestination
2023-06-27 03:19:23 destination > INFO i.a.i.b.IntegrationRunner(runInternal):107 Command: WRITE
2023-06-27 03:19:23 destination > INFO i.a.i.b.IntegrationRunner(runInternal):108 Integration config: IntegrationConfig{command=WRITE, configPath='destination_config.json', catalogPath='destination_catalog.json', statePath='null'}
2023-06-27 03:19:23 destination > WARN c.n.s.JsonMetaSchema(newValidator):278 Unknown keyword pattern_descriptor - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-06-27 03:19:23 destination > WARN c.n.s.JsonMetaSchema(newValidator):278 Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-06-27 03:19:23 destination > WARN c.n.s.JsonMetaSchema(newValidator):278 Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-06-27 03:19:23 destination > INFO i.a.i.d.s.SnowflakeDestination(getSerializedMessageConsumer):40 destination class: class io.airbyte.integrations.destination.snowflake.SnowflakeDestination
2023-06-27 03:19:23 destination > INFO i.a.i.d.s.SnowflakeDestination(getSerializedMessageConsumer):47 using async snowflake: false
2023-06-27 03:19:23 destination > INFO i.a.i.d.j.c.SwitchingDestination(getConsumer):65 Using destination type: INTERNAL_STAGING
2023-06-27 03:19:23 destination > INFO i.a.i.d.s.StagingConsumerFactory(lambda$toWriteConfig$2):164 Write config: WriteConfig{streamName=payments_GatewayTokens, namespace=null, outputSchemaName=AIRBYTE, tmpTableName=_airbyte_tmp_csu_payments_GatewayTokens, outputTableName=_airbyte_raw_payments_GatewayTokens, syncMode=append}
2023-06-27 03:19:23 destination > INFO i.a.i.d.b.BufferedStreamConsumer(startTracked):144 class io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer started.
2023-06-27 03:19:23 destination > INFO i.a.i.d.s.GeneralStagingFunctions(lambda$onStartFunction$0):25 Preparing raw tables in destination started for 1 streams
2023-06-27 03:19:23 destination > INFO i.a.i.d.s.GeneralStagingFunctions(lambda$onStartFunction$0):35 Preparing staging area in destination started for schema AIRBYTE stream payments_GatewayTokens: target table: _airbyte_raw_payments_GatewayTokens, stage: 2023/06/27/03/79806D10-898A-4E89-B789-A07739620C7E/
2023-06-27 03:19:23 destination > INFO c.z.h.HikariDataSource(getConnection):110 HikariPool-1 - Starting...
2023-06-27 03:19:23 destination > INFO c.z.h.p.HikariPool(checkFailFast):565 HikariPool-1 - Added connection net.snowflake.client.jdbc.SnowflakeConnectionV1@cb39552
2023-06-27 03:19:23 destination > INFO c.z.h.HikariDataSource(getConnection):123 HikariPool-1 - Start completed.
2023-06-27 03:19:23 destination > INFO i.a.d.j.DefaultJdbcDatabase(lambda$unsafeQuery$1):115 closing connection
2023-06-27 03:19:23 destination > INFO i.a.i.d.s.GeneralStagingFunctions(lambda$onStartFunction$0):52 Preparing staging area in destination completed for schema AIRBYTE stream payments_GatewayTokens
2023-06-27 03:19:23 destination > INFO i.a.i.d.s.GeneralStagingFunctions(lambda$onStartFunction$0):54 Executing finalization of tables.
2023-06-27 03:19:23 source > INFO i.a.i.s.m.MssqlSource(main):553 starting source: class io.airbyte.integrations.source.mssql.MssqlSource
2023-06-27 03:19:23 source > INFO i.a.i.b.IntegrationCliParser(parseOptions):126 integration args: {read=null, catalog=source_catalog.json, state=input_state.json, config=source_config.json}
2023-06-27 03:19:23 source > INFO i.a.i.b.IntegrationRunner(runInternal):106 Running integration: io.airbyte.integrations.base.ssh.SshWrappedSource
2023-06-27 03:19:23 source > INFO i.a.i.b.IntegrationRunner(runInternal):107 Command: READ
2023-06-27 03:19:23 source > INFO i.a.i.b.IntegrationRunner(runInternal):108 Integration config: IntegrationConfig{command=READ, configPath='source_config.json', catalogPath='source_catalog.json', statePath='input_state.json'}
2023-06-27 03:19:23 source > WARN c.n.s.JsonMetaSchema(newValidator):278 Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-06-27 03:19:23 source > WARN c.n.s.JsonMetaSchema(newValidator):278 Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-06-27 03:19:24 source > INFO i.a.i.b.s.SshTunnel(getInstance):204 Starting connection with method: NO_TUNNEL
2023-06-27 03:19:24 source > INFO i.a.i.s.r.s.StateManagerFactory(createStateManager):48 Legacy state manager selected to manage state object with type LEGACY.
2023-06-27 03:19:24 source > INFO i.a.i.s.r.s.CursorManager(createCursorInfoForStream):169 Found matching cursor in state. Stream: dbo_GatewayTokens. Cursor Field: CreatedTimestamp Value: 2023-06-27T00:56:57.697000Z Count: 1
2023-06-27 03:19:24 source > INFO i.a.i.s.r.CdcStateManager(<init>):29 Initialized CDC state with: null
2023-06-27 03:19:24 source > INFO c.z.h.HikariDataSource(<init>):80 HikariPool-1 - Starting...
2023-06-27 03:19:24 source > INFO c.z.h.HikariDataSource(<init>):82 HikariPool-1 - Start completed.
2023-06-27 03:19:25 source > INFO i.a.i.s.j.AbstractJdbcSource(logPreSyncDebugData):450 Data source product recognized as Microsoft SQL Server:14.00.3460
2023-06-27 03:19:25 source > INFO i.a.i.s.j.AbstractJdbcSource(discoverInternal):166 Internal schemas to exclude: [spt_fallback_db, spt_monitor, cdc, spt_values, INFORMATION_SCHEMA, spt_fallback_usg, MSreplication_options, sys, spt_fallback_dev]
2023-06-27 03:19:25 source > INFO i.a.i.s.m.MssqlSource(lambda$verifyCursorColumnValues$4):284 MsSQL Table Structure {"TABLE_QUALIFIER":"ZipMoney.Payments","TABLE_OWNER":"dbo","TABLE_NAME":"GatewayTokens","COLUMN_NAME":"Id","DATA_TYPE":-11,"TYPE_NAME":"uniqueidentifier","PRECISION":36,"LENGTH":16,"NULLABLE":0,"SQL_DATA_TYPE":-11,"ORDINAL_POSITION":1,"IS_NULLABLE":"NO","SS_DATA_TYPE":37}, dbo, GatewayTokens
2023-06-27 03:19:25 source > INFO i.a.i.s.m.MssqlSource(lambda$verifyCursorColumnValues$4):284 MsSQL Table Structure {"TABLE_QUALIFIER":"ZipMoney.Payments","TABLE_OWNER":"dbo","TABLE_NAME":"GatewayTokens","COLUMN_NAME":"PaymentMethodId","DATA_TYPE":-11,"TYPE_NAME":"uniqueidentifier","PRECISION":36,"LENGTH":16,"NULLABLE":0,"SQL_DATA_TYPE":-11,"ORDINAL_POSITION":2,"IS_NULLABLE":"NO","SS_DATA_TYPE":37}, dbo, GatewayTokens
2023-06-27 03:19:25 source > INFO i.a.i.s.m.MssqlSource(lambda$verifyCursorColumnValues$4):284 MsSQL Table Structure {"TABLE_QUALIFIER":"ZipMoney.Payments","TABLE_OWNER":"dbo","TABLE_NAME":"GatewayTokens","COLUMN_NAME":"Gateway","DATA_TYPE":4,"TYPE_NAME":"int","PRECISION":10,"LENGTH":4,"SCALE":0,"RADIX":10,"NULLABLE":0,"SQL_DATA_TYPE":4,"ORDINAL_POSITION":3,"IS_NULLABLE":"NO","SS_DATA_TYPE":56}, dbo, GatewayTokens
2023-06-27 03:19:25 source > INFO i.a.i.s.m.MssqlSource(lambda$verifyCursorColumnValues$4):284 MsSQL Table Structure {"TABLE_QUALIFIER":"ZipMoney.Payments","TABLE_OWNER":"dbo","TABLE_NAME":"GatewayTokens","COLUMN_NAME":"TokenizedCard","DATA_TYPE":-9,"TYPE_NAME":"nvarchar","PRECISION":50,"LENGTH":100,"NULLABLE":1,"SQL_DATA_TYPE":-9,"CHAR_OCTET_LENGTH":100,"ORDINAL_POSITION":4,"IS_NULLABLE":"YES","SS_DATA_TYPE":39}, dbo, GatewayTokens
2023-06-27 03:19:25 source > INFO i.a.i.s.m.MssqlSource(lambda$verifyCursorColumnValues$4):284 MsSQL Table Structure {"TABLE_QUALIFIER":"ZipMoney.Payments","TABLE_OWNER":"dbo","TABLE_NAME":"GatewayTokens","COLUMN_NAME":"CreatedTimestamp","DATA_TYPE":11,"TYPE_NAME":"datetime","PRECISION":23,"LENGTH":16,"SCALE":3,"NULLABLE":0,"SQL_DATA_TYPE":9,"SQL_DATETIME_SUB":3,"ORDINAL_POSITION":5,"IS_NULLABLE":"NO","SS_DATA_TYPE":61}, dbo, GatewayTokens
2023-06-27 03:19:25 source > INFO i.a.i.s.m.MssqlSource(getIncrementalIterators):467 using CDC: false
2023-06-27 03:19:25 source > INFO i.a.i.s.j.AbstractJdbcSource(queryTableIncremental):320 Queueing query for table: GatewayTokens
2023-06-27 03:19:25 source > INFO i.a.i.s.j.AbstractJdbcSource(lambda$queryTableIncremental$18):327 Preparing query for table: GatewayTokens
2023-06-27 03:19:25 source > INFO i.a.i.s.j.AbstractJdbcSource(lambda$queryTableIncremental$18):337 Table GatewayTokens cursor count: expected 1, actual 0
2023-06-27 03:19:26 source > INFO i.a.d.j.s.AdaptiveStreamingQueryConfig(initialize):31 Set initial fetch size: 10 rows
2023-06-27 03:19:26 source > INFO i.a.i.s.j.AbstractJdbcSource(lambda$queryTableIncremental$18):358 Executing query for table GatewayTokens: HikariProxyPreparedStatement@1638471954 wrapping SQLServerPreparedStatement:7
2023-06-27 03:19:26 source > INFO i.a.d.j.s.AdaptiveStreamingQueryConfig(initialize):31 Set initial fetch size: 10 rows
2023-06-27 03:19:26 source > INFO i.a.i.s.r.StateDecoratingIterator(createStateMessage):207 State report for stream dbo_GatewayTokens - original: CreatedTimestamp = 2023-06-27T00:56:57.697000Z (count 1) -> latest: CreatedTimestamp = 2023-06-27T00:56:57.697000Z (count 1)
2023-06-27 03:19:26 source > INFO i.a.c.u.CompositeIterator(lambda$emitStartStreamStatus$1):155 STARTING -> dbo_GatewayTokens
2023-06-27 03:19:26 source > INFO i.a.c.u.CompositeIterator(lambda$emitRunningStreamStatus$0):148 RUNNING -> dbo_GatewayTokens
2023-06-27 03:19:26 source > INFO i.a.c.u.CompositeIterator(lambda$emitCompleteStreamStatus$2):162 COMPLETE -> dbo_GatewayTokens
2023-06-27 03:19:26 source > WARN i.a.i.b.IntegrationRunner(watchForOrphanThreads):278 The main thread is exiting while children non-daemon threads from a connector are still active.
Ideally, this situation should not happen...
Please check with maintainers if the connector or library code should safely clean up its threads before quitting instead.
The main thread is: main (RUNNABLE)
 Thread stacktrace: java.base/java.lang.Thread.getStackTrace(Thread.java:1610)
        at io.airbyte.integrations.base.IntegrationRunner.dumpThread(IntegrationRunner.java:309)
        at io.airbyte.integrations.base.IntegrationRunner.watchForOrphanThreads(IntegrationRunner.java:282)
        at io.airbyte.integrations.base.IntegrationRunner.produceMessages(IntegrationRunner.java:199)
        at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:140)
        at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:99)
        at io.airbyte.integrations.source.mssql.MssqlSource.main(MssqlSource.java:554)
2023-06-27 03:19:26 source > WARN i.a.i.b.IntegrationRunner(watchForOrphanThreads):290 Active non-daemon thread: pool-2-thread-1 (TIMED_WAITING)
 Thread stacktrace: java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
        at java.base@17.0.4.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401)
        at java.base@17.0.4.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903)
        at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061)
        at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
        at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)
2023-06-27 03:19:26 source > WARN i.a.i.b.IntegrationRunner(watchForOrphanThreads):290 Active non-daemon thread: pool-2-thread-2 (TIMED_WAITING)
 Thread stacktrace: java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
        at java.base@17.0.4.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401)
        at java.base@17.0.4.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903)
        at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061)
        at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
        at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)
2023-06-27 03:19:26 source > INFO i.a.i.s.r.AbstractDbSource(lambda$read$1):173 Closing database connection pool.
2023-06-27 03:19:26 source > INFO c.z.h.HikariDataSource(close):350 HikariPool-1 - Shutdown initiated...
2023-06-27 03:19:26 source > INFO c.z.h.HikariDataSource(close):352 HikariPool-1 - Shutdown completed.
2023-06-27 03:19:26 source > INFO i.a.i.s.r.AbstractDbSource(lambda$read$1):175 Closed database connection pool.
2023-06-27 03:19:26 source > INFO i.a.i.b.IntegrationRunner(runInternal):195 Completed integration: io.airbyte.integrations.base.ssh.SshWrappedSource
2023-06-27 03:19:26 source > INFO i.a.i.s.m.MssqlSource(main):555 completed source: class io.airbyte.integrations.source.mssql.MssqlSource
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Duplicated of https://github.com/airbytehq/airbyte/issues/27741
