### ISSUE TITLE
Source AppStore: Unable to get historical data

### ISSUE THREAD

**Issue by qimumu9406** [airbytehq/airbyte#27822]
### Connector Name

Appstore

### Connector Version

0.2.6

### What step the error happened?

During the sync

### Revelant information

1、Create Appstore connection, set start date = 2023-02-28T00:00:00Z (or more distant time)
<img width="1219" alt="image" src="https://github.com/airbytehq/airbyte/assets/104196507/57814173-90bd-44fe-a813-2b41343e61a9">
2、Create a destination connect of any type, I use S3 (version=0.3.23) Destinaion connect
3、Connect the above and perform synchronization tasks at the same time

### Relevant log output

```shell
2023-06-29 08:09:01 [44msource[0m > Requesting Appstore data for: sales_report on 2023-06-27
2023-06-29 08:09:02 [44msource[0m > Requesting Appstore data for: sales_report on 2023-06-28
2023-06-29 08:09:04 [44msource[0m > Report is not available yet. Daily reports for the Americas are available by 5 am Pacific Time; Japan, Australia, and New Zealand by 5 am Japan Standard Time; and 5 am Central European Time for all other territories.
2023-06-29 08:09:04 [44msource[0m > Requesting Appstore data for: subscriber_report on 2023-02-28
2023-06-29 08:10:04 [32mINFO[m i.a.w.p.KubePodProcess(destroy):692 - (pod: airbyte / source-appstore-singer-read-3672-0-cwpdm) - Destroying Kube process.
2023-06-29 08:10:04 [32mINFO[m i.a.w.p.KubePodProcess(close):760 - (pod: airbyte / source-appstore-singer-read-3672-0-cwpdm) - Closed all resources for pod
2023-06-29 08:10:04 [32mINFO[m i.a.w.p.KubePodProcess(destroy):698 - (pod: airbyte / source-appstore-singer-read-3672-0-cwpdm) - Destroyed Kube process.
2023-06-29 08:10:04 [33mWARN[m i.a.c.i.LineGobbler(voidCall):154 - airbyte-source gobbler IOException: Socket closed. Typically happens when cancelling a job.
2023-06-29 08:10:05 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$readFromDstRunnable$4):321 - State in DefaultReplicationWorker from destination: io.airbyte.protocol.models.AirbyteMessage@6ffc1c6e[type=STATE,log=<null>,spec=<null>,connectionStatus=<null>,catalog=<null>,record=<null>,state=io.airbyte.protocol.models.AirbyteStateMessage@6058e5eb[type=<null>,stream=<null>,global=<null>,data={"bookmarks":{"sales_report":{"start_date":"2023-06-28T00:00:00Z"}}},additionalProperties={}],trace=<null>,control=<null>,additionalProperties={}]
2023-06-29 08:10:05 [32mINFO[m i.a.w.i.s.SyncPersistenceImpl(startBackgroundFlushStateTask):168 - starting state flush thread for connectionId c061edc4-c2b0-491e-b703-5095d24c3d06
2023-06-29 08:10:06 [32mINFO[m i.a.w.p.KubePodProcess(close):760 - (pod: airbyte / destination-s3-write-3672-0-nejvg) - Closed all resources for pod
2023-06-29 08:10:06 [1;31mERROR[m i.a.w.g.DefaultReplicationWorker(replicate):278 - Sync worker failed.
java.lang.RuntimeException: java.lang.NullPointerException
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:489) ~[io.airbyte-airbyte-commons-worker-0.44.2.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.NullPointerException
2023-06-29 08:10:06 [32mINFO[m i.a.w.g.DefaultReplicationWorker(getReplicationOutput):561 - sync summary: {
  "status" : "failed",
  "recordsSynced" : 210763,
  "bytesSynced" : 159646658,
  "startTime" : 1688025864648,
  "endTime" : 1688026206619,
  "totalStats" : {
    "bytesCommitted" : 159646658,
    "bytesEmitted" : 159646658,
    "destinationStateMessagesEmitted" : 1,
    "destinationWriteEndTime" : 1688026206520,
    "destinationWriteStartTime" : 1688025872571,
    "meanSecondsBeforeSourceStateMessageEmitted" : 0,
    "maxSecondsBeforeSourceStateMessageEmitted" : 13,
    "maxSecondsBetweenStateMessageEmittedandCommitted" : 309,
    "meanSecondsBetweenStateMessageEmittedandCommitted" : 309,
    "recordsEmitted" : 210763,
    "recordsCommitted" : 210763,
    "replicationEndTime" : 1688026206619,
    "replicationStartTime" : 1688025864648,
    "sourceReadEndTime" : 0,
    "sourceReadStartTime" : 1688025868771,
    "sourceStateMessagesEmitted" : 121
  },
  "streamStats" : [ {
    "streamName" : "sales_report",
    "stats" : {
      "bytesCommitted" : 159646658,
      "bytesEmitted" : 159646658,
      "recordsEmitted" : 210763,
      "recordsCommitted" : 210763
    }
  } ]
}
2023-06-29 08:10:06 [32mINFO[m i.a.w.g.DefaultReplicationWorker(getReplicationOutput):562 - failures: [ {
  "failureOrigin" : "replication",
  "internalMessage" : "java.lang.NullPointerException",
  "externalMessage" : "Something went wrong during replication",
  "metadata" : {
    "attemptNumber" : 0,
    "jobId" : 3672
  },
  "stacktrace" : "java.lang.RuntimeException: java.lang.NullPointerException\n\tat io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:489)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1589)\nCaused by: java.lang.NullPointerException\n",
  "timestamp" : 1688026144045
} ]
2023-06-29 08:10:06 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):163 - Stopping cancellation check scheduling...
2023-06-29 08:10:06 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-06-29 08:10:06 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - ----- END REPLICATION -----
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by qimumu9406** [comment]
When AppStore connect Start Date= 2023-02-28T00:00:00Z, connect will keep re-running during synchronization until it exceeds 3 times and the entire synchronization task fails. In fact, the data has been successfully synchronized, but the source connect pods are destroyed due to unknown reasons, and the Airbyte is deployed using EKS helm! ! ! !
When the AppStore connect Start Date= 2023-03-01T00:00:00Z, the synchronization task is in a normal health state

**Comment by qimumu9406** [comment]
Similar questions：

- https://github.com/airbytehq/airbyte/issues/10934
- https://github.com/airbytehq/airbyte/issues/5870
- https://github.com/airbytehq/airbyte/issues/5623

**Comment by qimumu9406** [comment]
@lmossman  hi,lmossman.can you help i solve this problem?

**Comment by lmossman** [comment]
@davydov-d can you look into this as API Sources OC?

**Comment by qimumu9406** [comment]
thanks Imossman and davydov !!!

**Comment by lazebnyi** [comment]
Hi @lmossman 

This is an alpha connector that is not integrated with the cloud. OC is not responsible for handling these connectors as per the standard procedure. If this connector is important to you, please reach out to @bmcgilli and request prioritization.

cc @oustynova @sherifnada

**Comment by sherifnada** [comment]
We'll keep this issue open but as @lazebnyi mentioned we currently aren't actively supporting this connector as it's in alpha

**Comment by qimumu9406** [comment]
Thanks all of you, I believe other small partners in the community have encountered this problem, if I want to solve this problem, how should I start to troubleshoot the cause of the problem?

cc: @sherifnada @lazebnyi  @lmossman

**Comment by marcosmarxm** [comment]
The App Store connector has been [archived](https://docs.airbyte.com/integrations/sources/appstore#deprecation-notice) and won't get updates in the future. We're closing this issue to focus on features and connectors in our roadmap. Thanks for understanding! 🚀
