### ISSUE TITLE
Lacking instructions on how to do a Multi-architecture build docker image

### ISSUE THREAD

**Issue by alberttwong** [airbytehq/airbyte#27888]
### Description

When I tested our the connector I was building, I get the following error.  WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested. Is there a way to build a Multi-architecture build docker image

**Comment by alberttwong** [comment]
https://stackoverflow.com/questions/65612411/forcing-docker-to-use-linux-amd64-platform-by-default-on-macos

**Comment by Towloo** [comment]
Can you provide the folder you're building from and a screenshot of the error you got?

**Comment by alberttwong** [comment]
You get that message when you run the container.  So the answer is to build multiple os images or force to build to the most common server os.

**Comment by alberttwong** [comment]
here is the error message
```
airbyte-worker                    | io.airbyte.workers.exception.WorkerException: Error while getting spec from image starrocks/destination-starrocks:latest
airbyte-worker                    | 	at io.airbyte.workers.general.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:83) ~[io.airbyte-airbyte-commons-worker-0.44.5.jar:?]
airbyte-worker                    | 	at io.airbyte.workers.general.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:36) ~[io.airbyte-airbyte-commons-worker-0.44.5.jar:?]
airbyte-worker                    | 	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$5(TemporalAttemptExecution.java:195) ~[io.airbyte-airbyte-workers-0.44.5.jar:?]
airbyte-worker                    | 	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
airbyte-worker                    | Caused by: io.airbyte.workers.exception.WorkerException: Could not find image: starrocks/destination-starrocks:latest
airbyte-worker                    | 	at io.airbyte.workers.process.DockerProcessFactory.create(DockerProcessFactory.java:117) ~[io.airbyte-airbyte-commons-worker-0.44.5.jar:?]
airbyte-worker                    | 	at io.airbyte.workers.process.AirbyteIntegrationLauncher.spec(AirbyteIntegrationLauncher.java:89) ~[io.airbyte-airbyte-commons-worker-0.44.5.jar:?]
airbyte-worker                    | 	at io.airbyte.workers.general.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:55) ~[io.airbyte-airbyte-commons-worker-0.44.5.jar:?]
airbyte-worker                    | 	... 3 more
```

**Comment by alberttwong** [comment]
I also linked it to the answer.   

Running airbyte on a mac so it expects a arm64 image so therefore the error.   I had to force airbye to download the container.   

```
docker exec -it airbyte-worker `/bin/bash`
docker pull starrocks/destination-starrocks --platform=linux/amd64
```

**Comment by alberttwong** [comment]
so I built two different images... amd64 and arm64 and then used https://dev.to/aws-builders/using-docker-manifest-to-create-multi-arch-images-on-aws-graviton-processors-1320 to generate a single entry.
