### ISSUE TITLE
Fix TIMEOUT in Salesforce service cloud connector

### ISSUE THREAD

**Issue by tdebroc** [airbytehq/airbyte#27969]
### Connector Name

source-salesforce

### Connector Version

2.1.0

### What step the error happened?

During the sync

### Revelant information

During sync initial load with Salesforce Service Cloud, we have a TIMEOUT.
It's because on the connector it fetches the last 30 days. But we have huge amount of data.
We fixed it (thanks to support of Airbyte team and Marcos), by rebuilding a connector changing this line:
https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-salesforce/source_salesforce/streams.py#L582
From 30 to 1 (to fetch day by day, instead of month per month).

But this should be fixed in the connector. Here are some options:
- Make this 30 configurable in the connector / UI
- The connector of Salesforce could calculate itself the right "step", if too much data
- If TIMEOUT, maybe retry by dividing the STEP by 2 or 4
- Also we see an "ORDER BY" in the query to Salesforce which is not recommended at all by Salesforce => https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/queries.htm it increases risk of timeout. Could we remove this ORDER BY ?

Doing the 4 options would be of course the best.

Thanks,

 Best regards

### Relevant log output

```shell
2023-06-30 00:45:24 [44msource[0m > [{"message":"Your query request was running for too long.","errorCode":"QUERY_TIMEOUT"}]
2023-06-30 00:45:24 [44msource[0m > Encountered an exception while reading stream Account
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 121, in read
    yield from self._read_stream(
  File "/airbyte/integration_code/source_salesforce/source.py", line 154, in _read_stream
    raise error
  File "/airbyte/integration_code/source_salesforce/source.py", line 146, in _read_stream
    yield from super()._read_stream(logger, stream_instance, configured_stream, state_manager, internal_config)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 196, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 327, in _read_full_refresh
    for record_data_or_message in record_data_or_messages:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 423, in read_records
    yield from self._read_pages(
  File "/airbyte/integration_code/source_salesforce/streams.py", line 211, in _read_pages
    request, response = self._fetch_next_page_for_chunk(
  File "/airbyte/integration_code/source_salesforce/streams.py", line 278, in _fetch_next_page_for_chunk
    response = self._send_request(request, request_kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 364, in _send_request
    return backoff_handler(user_backoff_handler)(request, request_kwargs)
  File "/usr/local/lib/python3.9/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 331, in _send
    raise exc
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 328, in _send
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://my.salesforce.com/services/data/v57.0/queryAll?q=SELECT+Id%2CIsDeleted%2CMasterRecordId......__pc+FROM+Account+WHERE+SystemModstamp+%3E%3D+2021-12-25T00%3A00%3A00.000%2B00%3A00+AND+SystemModstamp+%3C+2022-01-24T00%3A00%3A00.000%2B00%3A00+ORDER+BY+SystemModstamp+ASC
2023-06-30 00:45:24 [44msource[0m > Marking stream Account as STOPPED
2023-06-30 00:45:24 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitterThrows):229 - Attempt 0 to update stream status incomplete null:Account
2023-06-30 00:45:24 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitterThrows):234 - Attempt 0 to update stream status incomplete null:Account error: io.airbyte.api.client.invoker.generated.ApiException: updateStreamStatus call failed with: 400 - {"message":"Incomplete run cause must be set for runs that stopped in an incomplete
```

### Contribute

- [X] Yes, I want to contribute

**Comment by maxi297** [comment]
@tdebroc, we have implemented the first proposal as part of version 2.3.2. Could you check it this solves your issue?

**Comment by tdebroc** [comment]
Hey @maxi297  yes indeed, it solved the problem, many thanks !
Best regards

**Comment by maxi297** [comment]
Thanks @tdebroc ! I'll close this issue then
