### ISSUE TITLE
Source Github: Incremental stream Sync failing due to KeyError

### ISSUE THREAD

**Issue by vivekin** [airbytehq/airbyte#28006]
### Connector Name

source-github

### Connector Version

0.4.7

### What step the error happened?

During the sync

### Revelant information

There might be some repositories which are deleted/renamed, which might be causing the issue.

Referring the code:
https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-github/source_github/source.py#L172
Instead of :
repo_branches = [default_branches[repo]]

The issue can be avoided by changing it to :
repo_branches = [] if default_branches.get(repo) == None else [default_branches.get(repo)]

### Relevant log output

```shell
2023-07-04 21:33:01 [44msource[0m > 'ORG/sample-repo-name'
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 131, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 122, in run
    for message in generator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 99, in read
    stream_instances = {s.name: s for s in self.streams(config)}
  File "/airbyte/integration_code/source_github/source.py", line 246, in streams
    default_branches, branches_to_pull = self._get_branches_data(config.get("branch", ""), repository_args)
  File "/airbyte/integration_code/source_github/source.py", line 188, in _get_branches_data
    repo_branches = [default_branches[repo]]
KeyError: 'ORG/sample-repo-name'
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by artem1205** [comment]
Hi @vivekin ,
May I ask yo to provide me a config example, as i'm not able to reproduce the issue.

**Comment by artem1205** [comment]
@vivekin , any updates?

**Comment by artem1205** [comment]
any updates?

**Comment by artem1205** [comment]
@vivekin , any updates?

**Comment by artem1205** [comment]
Closing for now as no response received. Will reopen if needed.
