### ISSUE TITLE
AppsFlyer

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/airbyte#28108]
https://docs.airbyte.com/integrations/sources/appsflyer

**Comment by kananindzya** [comment]
Hi @RealChrisSean , I wanna to implement this.
Can you give introduce information to what to do? :)

**Comment by RealChrisSean** [comment]
Hello this has been assigned to you. You can learn more about our low-code/no-code docs here: https://airbyte.com/solutions/connector-development-kit

You can find more information on our landing page: https://airbyte.com/community/connector-hackathon

Good luck!

**Comment by parthiv11** [comment]
Sorry @RealChrisSean , I am not familiar with AppsFlyer and it seems difficult to setup demo account for test creds.

**Comment by anjshrg** [comment]
@RealChrisSean Would like to give this a try.

**Comment by KimuchuJr** [comment]
I would like to give this a try.

**Comment by justinbchau** [comment]
Has been more than 5 days and no commits have come through so I am unassigning. This is now open!

**Comment by abu-hasib** [comment]
@justinbchau I want to work on this.

**Comment by abu-hasib** [comment]
hey @justinbchau, I'm getting this error when i try to run `python3 main.py spec`

```
Traceback (most recent call last):
  File "/Users/thisbo/oss/airbyte/airbyte-integrations/connectors/source-appsflyer/main.py", line 9, in <module>
    from source_appsflyer import SourceAppsflyer
  File "/Users/thisbo/oss/airbyte/airbyte-integrations/connectors/source-appsflyer/source_appsflyer/__init__.py", line 6, in <module>
    from .source import SourceAppsflyer
  File "/Users/thisbo/oss/airbyte/airbyte-integrations/connectors/source-appsflyer/source_appsflyer/source.py", line 5, in <module>
    from airbyte_cdk.sources.declarative.yaml_declarative_source import YamlDeclarativeSource
  File "/Users/thisbo/oss/airbyte/airbyte-integrations/connectors/source-appsflyer/.venv/lib/python3.11/site-packages/airbyte_cdk/sources/declarative/yaml_declarative_source.py", line 8, in <module>
    from airbyte_cdk.sources.declarative.manifest_declarative_source import ManifestDeclarativeSource
  File "/Users/thisbo/oss/airbyte/airbyte-integrations/connectors/source-appsflyer/.venv/lib/python3.11/site-packages/airbyte_cdk/sources/declarative/manifest_declarative_source.py", line 27, in <module>
    from airbyte_cdk.sources.declarative.parsers.model_to_component_factory import ModelToComponentFactory
  File "/Users/thisbo/oss/airbyte/airbyte-integrations/connectors/source-appsflyer/.venv/lib/python3.11/site-packages/airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py", line 16, in <module>
    from airbyte_cdk.sources.declarative.auth.token import (
  File "/Users/thisbo/oss/airbyte/airbyte-integrations/connectors/source-appsflyer/.venv/lib/python3.11/site-packages/airbyte_cdk/sources/declarative/auth/token.py", line 12, in <module>
    from airbyte_cdk.sources.declarative.auth.token_provider import TokenProvider
  File "/Users/thisbo/oss/airbyte/airbyte-integrations/connectors/source-appsflyer/.venv/lib/python3.11/site-packages/airbyte_cdk/sources/declarative/auth/token_provider.py", line 31, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1220, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1210, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'airbyte_cdk.sources.declarative.decoders.json_decoder.JsonDecoder'> for field _decoder is not allowed: use default_factory
```

**Comment by abu-hasib** [comment]
nothing from the searches so far

**Comment by abu-hasib** [comment]
@RealChrisSean

**Comment by jonwihl** [comment]
@abu-hasib I ran into the same issue, did you ever end up resolving it?

**Comment by maver1ck** [comment]
Same problem here.

**Comment by maver1ck** [comment]
@abu-hasib it should be fixed by https://github.com/airbytehq/airbyte/pull/33798

**Comment by anjshrg** [comment]
@maver1ck @abu-hasib issue is because appsflyer API returns a CSV. Can you please help me understand how #33798 will help in this case?
