### ISSUE TITLE
[Async Destinations] -flush worker error: java.lang.NullPointerException

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#28154]
@rodireich  is attempting to sync 1TB to destination snowflake.  We see it crashing eventually around flush operations

https://cloud.airbyte.com/workspaces/23ef6ec3-cbc7-460f-bbfb-2b88a7716c53/connections/951e1359-f56e-4a3e-a161-9b511d0efd20/job-history#3086715::2

```
2023-07-11 01:38:20 destination > ERROR i.a.i.d.FlushWorkers(lambda$flush$1):168 Flush Worker (69f89) -- flush worker error: java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:?]
        at io.airbyte.integrations.destination_async.state.GlobalAsyncStateManager.flushStates(GlobalAsyncStateManager.java:153) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
        at io.airbyte.integrations.destination_async.buffers.MemoryAwareMessageBatch.flushStates(MemoryAwareMessageBatch.java:69) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
        at io.airbyte.integrations.destination_async.FlushWorkers.lambda$flush$1(FlushWorkers.java:161) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by evantahler** [comment]
cc @davinchia should these be on the Move team's radar now?

**Comment by rodireich** [comment]
Example of a falling sync
https://cloud.airbyte.com/workspaces/23ef6ec3-cbc7-460f-bbfb-2b88a7716c53/connections/951e1359-f56e-4a3e-a161-9b511d0efd20/job-history#3086715::2

**Comment by davinchia** [comment]
Fortunately, I think this is a pretty quick fix! @rodireich do you know if this is reproducible?
