### ISSUE TITLE
Empty table causing a failure in cursor based ctid

### ISSUE THREAD

**Issue by rodireich** [airbytehq/airbyte#28262]
A table with 0 rows will fail to sync via ctid in cursor based mode.
The max cursor query returns no values and as a result the sync fails:
```
2023-07-13 06:14:06 source > INFO i.a.i.s.p.PostgresQueryUtils(lambda$getCursorBasedSyncStatusForStreams$4):153 Querying max cursor value for public.tc10_lineitem
2023-07-13 06:14:06 source > ERROR i.a.i.b.s.SshWrappedSource(read):76 Exception occurred while getting the delegate read iterator, closing SSH tunnel java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:361) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at io.airbyte.integrations.source.postgres.PostgresQueryUtils.lambda$getCursorBasedSyncStatusForStreams$4(PostgresQueryUtils.java:163) ~[io.airbyte.airbyte-integrations.connectors-source-postgres-0.50.7.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at io.airbyte.integrations.source.postgres.PostgresQueryUtils.getCursorBasedSyncStatusForStreams(PostgresQueryUtils.java:143) ~[io.airbyte.airbyte-integrations.connectors-source-postgres-0.50.7.jar:?]
	at io.airbyte.integrations.source.postgres.PostgresSource.getIncrementalIterators(PostgresSource.java:590) ~[io.airbyte.airbyte-integrations.connectors-source-postgres-0.50.7.jar:?]
```

**Comment by rodireich** [comment]
For comparison
This is the state saved _pre ctid_ for an empty table:
```
[
  {
    "streamDescriptor": {
      "name": "tc10_lineitem",
      "namespace": "public"
    },
    "streamState": {
      "stream_name": "tc10_lineitem",
      "cursor_field": [
        "column_1"
      ],
      "stream_namespace": "public"
    }
  }
]
```
