### ISSUE TITLE
Source Amazon Ads: none is not an allowed value (type=type_error.none.not_allowed)

### ISSUE THREAD

**Issue by ASchmidtGit** [airbytehq/airbyte#28265]
### Connector Name

Srouce-Amazon Ads

### Connector Version

2.3.0

### What step the error happened?

During the sync

### Revelant information

Started Sync of "sponsored_products_report_stream" from 2023-07-01.

For the report on 2023-07-06 i get the following error:

```
2023-07-12 18:44:55 source > Encountered an exception while reading stream sponsored_products_report_stream
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 122, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 197, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 266, in _read_incremental
    for message_counter, record_data_or_message in enumerate(records, start=1):
  File "/airbyte/integration_code/source_amazon_ads/streams/report_streams/report_streams.py", line 170, in read_records
    yield self._model( File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for MetricsModel
recordId
  none is not an allowed value (type=type_error.none.not_allowed)
```

and the sync stops.

Log file:
[05789bfa_4c52_48ad_9150_09e59474ff51_logs_243_txt.txt](https://github.com/airbytehq/airbyte/files/12037191/05789bfa_4c52_48ad_9150_09e59474ff51_logs_243_txt.txt)

### Relevant log output

```shell
2023-07-12 18:44:55 source > Encountered an exception while reading stream sponsored_products_report_stream
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 122, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 197, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 266, in _read_incremental
    for message_counter, record_data_or_message in enumerate(records, start=1):
  File "/airbyte/integration_code/source_amazon_ads/streams/report_streams/report_streams.py", line 170, in read_records
    yield self._model( File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for MetricsModel
recordId
  none is not an allowed value (type=type_error.none.not_allowed)
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by bazarnov** [comment]
Closing this one, after the Local testing - no issues with `recordID: None` values are faced. Please re-open once faced with such an error using the latest connector version.
