### ISSUE TITLE
run-ab-platform.sh     Cannot invoke "io.airbyte.config.NotificationSettings.getSendOnFailure()" because "notificationSetting" is null

### ISSUE THREAD

**Issue by Touketsu-jie** [airbytehq/airbyte#28261]
### Topic

VERSION=0.50.7， OS=Ubuntu 22.04.2 LTS

### Revelant information

Unable to bootstrap Airbyte environment.
airbyte-bootloader                | org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: Migration failed !
airbyte-bootloader                |     at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:378) ~[flyway-core-7.14.0.jar:?]
airbyte-bootloader                |     at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:271) ~[flyway-core-7.14.0.jar:?]
airbyte-bootloader                |     at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66) ~[flyway-core-7.14.0.jar:?]
airbyte-bootloader                |     at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:270) ~[flyway-core-7.14.0.jar:?]
airbyte-bootloader                |     at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:243) ~[flyway-core-7.14.0.jar:?]
airbyte-bootloader                |     at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:141) ~[flyway-core-7.14.0.jar:?]
airbyte-bootloader                |     at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:70) ~[flyway-core-7.14.0.jar:?]
airbyte-bootloader                |     at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:99) ~[flyway-core-7.14.0.jar:?]
airbyte-bootloader                |     at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:141) ~[flyway-core-7.14.0.jar:?]
airbyte-bootloader                |     at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:141) ~[flyway-core-7.14.0.jar:?]
airbyte-bootloader                |     at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:101) ~[flyway-core-7.14.0.jar:?]
airbyte-bootloader                |     at org.flywaydb.core.Flyway$1.execute(Flyway.java:217) ~[flyway-core-7.14.0.jar:?]
airbyte-bootloader                |     at org.flywaydb.core.Flyway$1.execute(Flyway.java:168) ~[flyway-core-7.14.0.jar:?]
airbyte-bootloader                |     at org.flywaydb.core.Flyway.execute(Flyway.java:584) ~[flyway-core-7.14.0.jar:?]
airbyte-bootloader                |     at org.flywaydb.core.Flyway.migrate(Flyway.java:168) ~[flyway-core-7.14.0.jar:?]
airbyte-bootloader                |     at io.airbyte.db.instance.FlywayDatabaseMigrator.migrate(FlywayDatabaseMigrator.java:45) ~[io.airbyte.airbyte-db-db-lib-0.50.7.jar:?]
airbyte-bootloader                |     at io.airbyte.bootloader.Bootloader.runFlywayMigration(Bootloader.java:240) ~[io.airbyte-airbyte-bootloader-0.50.7.jar:?]
airbyte-bootloader                |     at io.airbyte.bootloader.Bootloader.load(Bootloader.java:112) ~[io.airbyte-airbyte-bootloader-0.50.7.jar:?]
airbyte-bootloader                |     at io.airbyte.bootloader.Application.main(Application.java:22) ~[io.airbyte-airbyte-bootloader-0.50.7.jar:?]
airbyte-bootloader                | Caused by: org.flywaydb.core.api.FlywayException: Migration failed !
airbyte-bootloader                |     at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.executeOnce(JavaMigrationExecutor.java:75) ~[flyway-core-7.14.0.jar:?]
airbyte-bootloader                |     at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.lambda$execute$0(JavaMigrationExecutor.java:54) ~[flyway-core-7.14.0.jar:?]
airbyte-bootloader                |     at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27) ~[flyway-core-7.14.0.jar:?]
airbyte-bootloader                |     at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.execute(JavaMigrationExecutor.java:53) ~[flyway-core-7.14.0.jar:?]
airbyte-bootloader                |     at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:370) ~[flyway-core-7.14.0.jar:?]
airbyte-bootloader                |     ... 18 more
airbyte-bootloader                | Caused by: java.lang.NullPointerException: Cannot invoke "io.airbyte.config.NotificationSettings.getSendOnFailure()" because "notificationSetting" is null
airbyte-bootloader                |     at io.airbyte.db.instance.configs.migrations.V0_50_5_003__NotificationSettingsSendOnFailureBackfill.lambda$backfillNotificationSettings$0(V0_50_5_003__NotificationSettingsSendOnFailureBackfill.java:68) ~[io.airbyte.airbyte-db-db-lib-0.50.7.jar:?]
airbyte-bootloader                |     at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
airbyte-bootloader                |     at io.airbyte.db.instance.configs.migrations.V0_50_5_003__NotificationSettingsSendOnFailureBackfill.backfillNotificationSettings(V0_50_5_003__NotificationSettingsSendOnFailureBackfill.java:53) ~[io.airbyte.airbyte-db-db-lib-0.50.7.jar:?]
airbyte-bootloader                |     at io.airbyte.db.instance.configs.migrations.V0_50_5_003__NotificationSettingsSendOnFailureBackfill.migrate(V0_50_5_003__NotificationSettingsSendOnFailureBackfill.java:44) ~[io.airbyte.airbyte-db-db-lib-0.50.7.jar:?]
airbyte-bootloader                |     at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.executeOnce(JavaMigrationExecutor.java:61) ~[flyway-core-7.14.0.jar:?]
airbyte-bootloader                |     at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.lambda$execute$0(JavaMigrationExecutor.java:54) ~[flyway-core-7.14.0.jar:?]
airbyte-bootloader                |     at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27) ~[flyway-core-7.14.0.jar:?]
airbyte-bootloader                |     at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.execute(JavaMigrationExecutor.java:53) ~[flyway-core-7.14.0.jar:?]
airbyte-bootloader                |     at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:370) ~[flyway-core-7.14.0.jar:?]
airbyte-bootloader                |     ... 18 more
airbyte-bootloader                | 2023-07-13 03:23:34 INFO i.m.r.Micronaut(lambda$start$0):115 - Embedded Application shutting down

**Comment by ViljarVoidula** [comment]
+1 same problem today with deployment and bootloader pod

**Comment by ViljarVoidula** [comment]
@Octopus-tang 
how to fix it - find your configuration db , workspaces table and add to notification_settings column
`{"sendOnFailure": {"notificationType": [], "slackConfiguration": {}, "customerioConfiguration": null}, "sendOnSuccess": {"notificationType": [], "slackConfiguration": {}, "customerioConfiguration": null}, "sendOnSyncDisabled": {"notificationType": [], "slackConfiguration": {}, "customerioConfiguration": null}, "sendOnConnectionUpdate": {"notificationType": [], "slackConfiguration": {}, "customerioConfiguration": null}, "sendOnSyncDisabledWarning": {"notificationType": [], "slackConfiguration": {}, "customerioConfiguration": null}, "sendOnConnectionUpdateActionRequired": {"notificationType": [], "slackConfiguration": {}, "customerioConfiguration": null}}`

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
