### ISSUE TITLE
Postgres emitting scientific notation integers (`7E+3`) in CDC mode

### ISSUE THREAD

**Issue by rodireich** [airbytehq/airbyte#28303]
### Connector Name

source-postgres

### Connector Version

3.0.0

### What step the error happened?

During the sync

### Revelant information

Similarly to the issue seen and fixed in standard sync (#21413).
CDC is emitting integer values in the form of `1E+3`,
Causing normalization to fail with ```Bad int64 value: 1E+3```

It's possible the fix we made for standard needs to be extended to CDC.

### Relevant log output

```shell
2023-07-07 19:59:16 INFO i.a.w.t.s.ReplicationActivityImpl(lambda$replicate$3):160 - sync summary: io.airbyte.config.StandardSyncOutput@29fec12e[standardSyncSummary=io.airbyte.config.StandardSyncSummary@3ee0e9dc[status=failed,recordsSynced=3124,bytesSynced=21165413,startTime=1688759492509,endTime=1688759956245,totalStats=io.airbyte.config.SyncStats@205be055[bytesCommitted=<null>,bytesEmitted=21165413,destinationStateMessagesEmitted=15,destinationWriteEndTime=0,destinationWriteStartTime=1688759492536,estimatedBytes=<null>,estimatedRecords=<null>,meanSecondsBeforeSourceStateMessageEmitted=161,maxSecondsBeforeSourceStateMessageEmitted=308,maxSecondsBetweenStateMessageEmittedandCommitted=<null>,meanSecondsBetweenStateMessageEmittedandCommitted=<null>,recordsEmitted=3124,recordsCommitted=<null>,replicationEndTime=1688759956242,replicationStartTime=1688759492509,sourceReadEndTime=1688759847203,sourceReadStartTime=1688759492518,sourceStateMessagesEmitted=2,additionalProperties={}],streamStats=[io.airbyte.config.StreamSyncStats@7a7ad4ca[streamName=product_in_loan,streamNamespace=src_postgres_loan_db,stats=io.airbyte.config.SyncStats@25d28d1a[bytesCommitted=<null>,bytesEmitted=21165413,destinationStateMessagesEmitted=<null>,destinationWriteEndTime=<null>,destinationWriteStartTime=<null>,estimatedBytes=<null>,estimatedRecords=<null>,meanSecondsBeforeSourceStateMessageEmitted=<null>,maxSecondsBeforeSourceStateMessageEmitted=<null>,maxSecondsBetweenStateMessageEmittedandCommitted=<null>,meanSecondsBetweenStateMessageEmittedandCommitted=<null>,recordsEmitted=3124,recordsCommitted=<null>,replicationEndTime=<null>,replicationStartTime=<null>,sourceReadEndTime=<null>,sourceReadStartTime=<null>,sourceStateMessagesEmitted=<null>,additionalProperties={}],additionalProperties={}]],performanceMetrics=io.airbyte.config.PerformanceMetrics@1cc53e75[additionalProperties={processFromSource={elapsedTimeInNanos=317151896, executionCount=3126, avgExecTimeInNanos=101456.14075495841}, readFromSource={elapsedTimeInNanos=337625362676, executionCount=37348, avgExecTimeInNanos=9039985.077540966}, processFromDest={elapsedTimeInNanos=176378504, executionCount=16, avgExecTimeInNanos=1.10236565E7}, writeToDest={elapsedTimeInNanos=23735799052, executionCount=3126, avgExecTimeInNanos=7593025.92834293}, readFromDest={elapsedTimeInNanos=458202925124, executionCount=537377, avgExecTimeInNanos=852665.6800049128}}],additionalProperties={}],normalizationSummary=<null>,webhookOperationSummary=<null>,state=<null>,outputCatalog=io.airbyte.protocol.models.ConfiguredAirbyteCatalog@63e32cf0[streams=[io.airbyte.protocol.models.ConfiguredAirbyteStream@4f1378c2[stream=io.airbyte.protocol.models.AirbyteStream@7e989667[name=supplier,jsonSchema={"type":"object","properties":{"country":{"type":"string"},"city":{"type":"string"},"postalCode":{"type":"string"},"houseNumber":{"type":"string"},"_ab_cdc_deleted_at":{"type":"string"},"_ab_cdc_lsn":{"type":"number"},"createdAt":{"format":"date-time","airbyte_type":"timestamp_without_timezone","type":"string"},"street":{"type":"string"},"name":{"type":"string"},"_ab_cdc_updated_at":{"type":"string"},"id":{"airbyte_type":"integer","type":"number"},"loanId":{"airbyte_type":"integer","type":"number"},"updatedAt":{"format":"date-time","airbyte_type":"timestamp_without_timezone","type":"string"}},"$schema":"http://json-schema.org/draft-07/schema#"},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[],sourceDefinedPrimaryKey=[[id]],namespace=src_postgres_loan_db,additionalProperties={}],syncMode=incremental,cursorField=[],destinationSyncMode=append_dedup,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@4b9b3957[stream=io.airbyte.protocol.models.AirbyteStream@31651878[name=repayment_request,jsonSchema={"type":"object","properties":{"isCancelled":{"type":"boolean"},"contactId":{"airbyte_type":"integer","type":"number"},"_ab_cdc_deleted_at":{"type":"string"},"_ab_cdc_lsn":{"type":"number"},"repaymentAmountPrincipal":{"type":"number"},"updatedDate":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"reference":{"type":"string"},"isPaid":{"type":"boolean"},"createdDate":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"_ab_cdc_updated_at":{"type":"string"},"paidAt":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"id":{"airbyte_type":"integer","type":"number"},"repaymentAmountTotal":{"type":"number"},"loanId":{"airbyte_type":"integer","type":"number"},"effectiveDate":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"repaymentAmountInterest":{"type":"number"}},"$schema":"http://json-schema.org/draft-07/schema#"},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[],sourceDefinedPrimaryKey=[[id]],namespace=src_postgres_loan_db,additionalProperties={}],syncMode=incremental,cursorField=[],destinationSyncMode=append_dedup,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@6564a3fe[stream=io.airbyte.protocol.models.AirbyteStream@5ff53a9b[name=loan_task,jsonSchema={"type":"object","properties":{"createdAt":{"format":"date-time","airbyte_type":"timestamp_without_timezone","type":"string"},"task":{"type":"string"},"_ab_cdc_updated_at":{"type":"string"},"_ab_cdc_deleted_at":{"type":"string"},"_ab_cdc_lsn":{"type":"number"},"id":{"airbyte_type":"integer","type":"number"},"assignee":{"type":"string"},"isActive":{"type":"boolean"},"board":{"type":"string"},"loanId":{"airbyte_type":"integer","type":"number"},"scheduledAt":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"updatedAt":{"format":"date-time","airbyte_type":"timestamp_without_timezone","type":"string"}},"$schema":"http://json-schema.org/draft-07/schema#"},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[],sourceDefinedPrimaryKey=[[id]],namespace=src_postgres_loan_db,additionalProperties={}],syncMode=incremental,cursorField=[],destinationSyncMode=append_dedup,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@4d36e1b3[stream=io.airbyte.protocol.models.AirbyteStream@548986b5[name=processed_transaction,jsonSchema={"type":"object","properties":{"createdDate":{"format":"date-time","airbyte_type":"timestamp_without_timezone","type":"string"},"_ab_cdc_updated_at":{"type":"string"},"_ab_cdc_deleted_at":{"type":"string"},"_ab_cdc_lsn":{"type":"number"},"id":{"airbyte_type":"integer","type":"number"},"transactionId":{"airbyte_type":"integer","type":"number"}},"$schema":"http://json-schema.org/draft-07/schema#"},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[],sourceDefinedPrimaryKey=[[id]],namespace=src_postgres_loan_db,additionalProperties={}],syncMode=incremental,cursorField=[],destinationSyncMode=append_dedup,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@1432b489[stream=io.airbyte.protocol.models.AirbyteStream@62e57576[name=checkout,jsonSchema={"type":"object","properties":{"completedAt":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"contactId":{"airbyte_type":"integer","type":"number"},"_ab_cdc_deleted_at":{"type":"string"},"_ab_cdc_lsn":{"type":"number"},"repaymentAmountPrincipal":{"type":"number"},"updatedDate":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"reference":{"type":"string"},"createdDate":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"_ab_cdc_updated_at":{"type":"string"},"checkoutId":{"airbyte_type":"integer","type":"number"},"repaymentAmountTotal":{"type":"number"},"repaymentAmountInterest":{"type":"number"},"status":{"type":"string"}},"$schema":"http://json-schema.org/draft-07/schema#"},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[],sourceDefinedPrimaryKey=[[checkoutId]],namespace=src_postgres_loan_db,additionalProperties={}],syncMode=incremental,cursorField=[],destinationSyncMode=append_dedup,primaryKey=[[checkoutId]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@18a42be0[stream=io.airbyte.protocol.models.AirbyteStream@80aa6f[name=product_in_loan,jsonSchema={"type":"object","properties":{"expectedInterest":{"type":"number"},"targetPrincipalAdjustmentFactor":{"type":"number"},"acceptedPrincipal":{"type":"number"},"updatedDate":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"isActive":{"type":"boolean"},"maxInterest":{"type":"number"},"titleOverride":{"type":"string"},"puti":{"type":"string"},"orderVolume":{"airbyte_type":"integer","type":"number"},"userProvidedIdentifier":{"type":"string"},"isBorrowerNotSeller":{"type":"boolean"},"modelSPMOverride":{"type":"number"},"isCurrentlySourced":{"type":"boolean"},"financingPerUnit":{"type":"number"},"scoreBasedLTVAppliedLTVRule":{"type":"number"},"sku":{"type":"string"},"portfolioRiskLTV":{"type":"number"},"productQuotient":{"type":"number"},"collateralSalesDuration":{"airbyte_type":"integer","type":"number"},"productId":{"airbyte_type":"integer","type":"number"},"isLTVRulesAppliedInCalc":{"type":"boolean"},"targetPrincipalAdjustedLTV":{"type":"number"},"expInterestInPercentOfPrincipal":{"type":"number"},"expInterestMargin":{"type":"number"},"expInterestMultiple":{"type":"number"},"overrideLtvAdjustmentRule":{"type":"string"},"expInterestPerProduct":{"type":"number"},"productDbCache":{"type":"string"},"schufaRuleBasedLTV":{"type":"number"},"productInLoanId":{"airbyte_type":"integer","type":"number"},"loanId":{"airbyte_type":"integer","type":"number"},"collateralStoreAt":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"_ab_cdc_deleted_at":{"type":"string"},"approvedPrincipal":{"type":"number"},"salesPerMonthAppliedLTVRule":{"type":"number"},"principal":{"type":"number"},"collateralShare":{"type":"number"},"financingPerRevenues":{"type":"number"},"approvedOrderVolume":{"airbyte_type":"integer","type":"number"},"acceptedOrderVolume":{"airbyte_type":"integer","type":"number"},"higherVolumeFPU":{"type":"number"},"purchasingPrice":{"type":"number"},"purchasePriceSelector":{"type":"string"},"parentVariantPILId":{"airbyte_type":"integer","type":"number"},"ltvOverride":{"type":"number"},"installmentRate":{"type":"number"},"identifiers":{"type":"string"},"_ab_cdc_lsn":{"type":"number"},"platformId":{"airbyte_type":"integer","type":"number"},"isRiskApproved":{"type":"boolean"},"appliedLtvRules":{"type":"array","items":{"type":"string"}},"createdDate":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"totalRevenues":{"type":"number"},"financingPerUnitOfCollateral":{"type":"number"},"_ab_cdc_updated_at":{"type":"string"},"collateralVolume":{"airbyte_type":"integer","type":"number"},"platformCategoryId":{"airbyte_type":"integer","type":"number"},"projectMargin":{"type":"number"}},"$schema":"http://json-schema.org/draft-07/schema#"},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[],sourceDefinedPrimaryKey=[[productInLoanId]],namespace=src_postgres_loan_db,additionalProperties={}],syncMode=incremental,cursorField=[],destinationSyncMode=append_dedup,primaryKey=[[productInLoanId]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@197c00a[stream=io.airbyte.protocol.models.AirbyteStream@48105b8b[name=checkout_product_in_loan,jsonSchema={"type":"object","properties":{"releasedUnits":{"airbyte_type":"integer","type":"number"},"repaymentId":{"type":"string"},"isInitial":{"type":"boolean"},"_ab_cdc_deleted_at":{"type":"string"},"_ab_cdc_lsn":{"type":"number"},"repaymentAmountPrincipal":{"type":"number"},"updatedDate":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"releasedCollis":{"airbyte_type":"integer","type":"number"},"createdDate":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"inventoryOperationId":{"airbyte_type":"integer","type":"number"},"_ab_cdc_updated_at":{"type":"string"},"repaymentStatus":{"type":"string"},"id":{"airbyte_type":"integer","type":"number"},"checkoutId":{"airbyte_type":"integer","type":"number"},"productInLoanId":{"airbyte_type":"integer","type":"number"},"repaymentAmountTotal":{"type":"number"},"loanId":{"airbyte_type":"integer","type":"number"},"repaymentAmountInterest":{"type":"number"}},"$schema":"http://json-schema.org/draft-07/schema#"},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[],sourceDefinedPrimaryKey=[[id]],namespace=src_postgres_loan_db,additionalProperties={}],syncMode=incremental,cursorField=[],destinationSyncMode=append_dedup,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@71528242[stream=io.airbyte.protocol.models.AirbyteStream@74849dd5[name=fpu_change,jsonSchema={"type":"object","properties":{"createdAt":{"format":"date-time","airbyte_type":"timestamp_without_timezone","type":"string"},"higherVolumeFPU":{"type":"number"},"financingPerUnitOfCollateral":{"type":"number"},"_ab_cdc_updated_at":{"type":"string"},"_ab_cdc_deleted_at":{"type":"string"},"_ab_cdc_lsn":{"type":"number"},"financingPerUnit":{"type":"number"},"id":{"airbyte_type":"integer","type":"number"},"isActive":{"type":"boolean"},"productInLoanId":{"airbyte_type":"integer","type":"number"},"updatedAt":{"format":"date-time","airbyte_type":"timestamp_without_timezone","type":"string"}},"$schema":"http://json-schema.org/draft-07/schema#"},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[],sourceDefinedPrimaryKey=[[id]],namespace=src_postgres_loan_db,additionalProperties={}],syncMode=incremental,cursorField=[],destinationSyncMode=append_dedup,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@4b2c84df[stream=io.airbyte.protocol.models.AirbyteStream@12a5232[name=loan_event,jsonSchema={"type":"object","properties":{"createdDate":{"format":"date-time","airbyte_type":"timestamp_without_timezone","type":"string"},"_ab_cdc_updated_at":{"type":"string"},"_ab_cdc_deleted_at":{"type":"string"},"_ab_cdc_lsn":{"type":"number"},"id":{"type":"string"},"loanState":{"type":"string"},"updatedDate":{"format":"date-time","airbyte_type":"timestamp_without_timezone","type":"string"},"loanId":{"airbyte_type":"integer","type":"number"}},"$schema":"http://json-schema.org/draft-07/schema#"},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[],sourceDefinedPrimaryKey=[[id]],namespace=src_postgres_loan_db,additionalProperties={}],syncMode=incremental,cursorField=[],destinationSyncMode=append_dedup,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@640f80c7[stream=io.airbyte.protocol.models.AirbyteStream@34b5d3a6[name=loan,jsonSchema={"type":"object","properties":{"initialPayment":{"type":"number"},"expectedInterest":{"type":"number"},"notionalInclInterests":{"type":"number"},"contractType":{"type":"string"},"payoutValidationComments":{"type":"array","items":{"type":"string"}},"acceptedPrincipal":{"type":"number"},"updatedDate":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"myosAccountId":{"airbyte_type":"integer","type":"number"},"payoutDate":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"bank":{"type":"string"},"collateralizedWebshop":{"type":"boolean"},"inventoryPayment":{"type":"string"},"payoutPreference":{"type":"string"},"modelLTV":{"type":"number"},"offeredLTV":{"type":"number"},"totalInterest":{"type":"number"},"firstMonthFeeReference":{"type":"string"},"payoutBankAccounts":{"type":"string"},"payoutNoticeGeneratedAt":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"currentPrincipalValute":{"type":"number"},"contractUploadedAt":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"expectedPayoutDate":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"supplierAccountId":{"airbyte_type":"integer","type":"number"},"dataSourcingType":{"type":"string"},"payoutDateUpdatedAt":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"collateralSecured":{"type":"boolean"},"directContract":{"type":"boolean"},"warehouseId":{"airbyte_type":"integer","type":"number"},"feeModelMigratedAt":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"paymentReceivedAt":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"projectFee":{"type":"number"},"requirePrice":{"type":"string"},"keyMetrictsApproval":{"type":"string"},"customerPaymentReference":{"type":"string"},"collateralDocumentsState":{"type":"string"},"goodsFullyPaid":{"type":"boolean"},"inDefaultDate":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"expectedPayoutDateStatus":{"type":"string"},"outstandingInvoiceAmountCurrency":{"type":"string"},"payoutTypeUpdatedAt":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"shopAPICredentials":{"type":"string"},"blockThresholdValue":{"type":"number"},"customerProvidedInvoiceCurrency":{"type":"string"},"invoiceCurrency":{"type":"string"},"exemptions":{"type":"string"},"repaymentThresholdValue":{"type":"number"},"expectedArrivalDate":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"inLiquidationDate":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"alibabaOrderNumber":{"type":"string"},"yearlyInterestRate":{"type":"number"},"warehouseCountry":{"type":"string"},"customerInformedPayoutAt":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"isRollingInventory":{"type":"boolean"},"_ab_cdc_lsn":{"type":"number"},"createdDate":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"firstMonthFeeAccountId":{"airbyte_type":"integer","type":"number"},"discountDuration":{"airbyte_type":"integer","type":"number"},"_ab_cdc_updated_at":{"type":"string"},"postPayoutMergeExtendType":{"type":"string"},"contractCreatedAt":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"projectMargin":{"type":"number"},"payoutType":{"type":"string"},"paymentTermsSplitPay":{"type":"string"},"extensionAmount":{"type":"number"},"schufaMaxPrincipalOverride":{"type":"number"},"collateralCallAmount":{"type":"number"},"luti":{"type":"string"},"maxInterest":{"type":"number"},"productCount":{"airbyte_type":"integer","type":"number"},"borrowerStatusMhb":{"type":"string"},"partialPayment":{"type":"number"},"isExtension":{"type":"boolean"},"outstandingInvoiceAmount":{"type":"number"},"interestRatePerMonth":{"type":"number"},"maturityDate":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"contractSigningPersons":{"type":"string"},"expectedInterestMultiple":{"type":"number"},"schufaMaxPrincipal":{"type":"number"},"modelInterestRatePerMonth":{"type":"number"},"shopId":{"type":"string"},"isPayoutAta":{"type":"boolean"},"collateralizedBrand":{"type":"boolean"},"paymentTerms":{"type":"string"},"collateralWhereaboutsAtPayout":{"type":"string"},"pricingModel":{"type":"string"},"projectCurrency":{"type":"string"},"expectedPayoutDateUpdatedAt":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"extraCollateralDocRequirements":{"type":"array","items":{"type":"string"}},"warehouseOwnedBy":{"type":"string"},"defaultedDate":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"payoutExchangeRateValidTill":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"proofType":{"type":"string"},"targetPrincipal":{"type":"number"},"borrowerOverview":{"type":"string"},"isTargetPrincipalAppliedInCalc":{"type":"boolean"},"outstandingPrincipalInclundingInterest":{"type":"number"},"customerAccountId":{"airbyte_type":"integer","type":"number"},"supplierPayment":{"type":"string"},"expectedPayoutDateStatusUpdatedAt":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"loanPDNote":{"type":"string"},"financeType":{"type":"string"},"outstandingInvoice":{"type":"number"},"paymentMethod":{"type":"string"},"fundingSource":{"type":"string"},"supplierPaymentReference":{"type":"string"},"loanId":{"airbyte_type":"integer","type":"number"},"contractMerchantSignedDate":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"dealId":{"airbyte_type":"integer","type":"number"},"splitPayment":{"type":"string"},"fxHedgingCase":{"type":"string"},"collateralStored":{"type":"boolean"},"_ab_cdc_deleted_at":{"type":"string"},"approvedPrincipal":{"type":"number"},"title":{"type":"string"},"duration":{"airbyte_type":"integer","type":"number"},"principal":{"type":"number"},"extensionOf":{"type":"array","items":{"airbyte_type":"integer","type":"number"}},"warehouseProviderUpdatedAt":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"myosPaymentReference":{"type":"string"},"principalInstallmentRate":{"type":"number"},"loanCountry":{"type":"string"},"borrowerStatusDhb":{"type":"string"},"finalPayment":{"type":"number"},"expectedInterestMargin":{"type":"number"},"outstandingInvoiceValute":{"type":"number"},"warehouseDataProvider":{"type":"string"},"warehouseProvider":{"type":"string"},"writeOffDate":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"myosHandlesWithAll":{"type":"string"},"fPSignUploadedAt":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"contractBankSignedDate":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"payoutValidationBy":{"type":"string"},"myosHandles":{"type":"string"},"contractMyosSignedDate":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"contractId":{"type":"string"},"isBundleRepaymentTracker":{"type":"boolean"},"payoutValidationApprovedAt":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"comment":{"type":"string"},"outstandingPrincipal":{"type":"number"},"projectInstallmentRate":{"type":"number"}},"$schema":"http://json-schema.org/draft-07/schema#"},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[],sourceDefinedPrimaryKey=[[loanId]],namespace=src_postgres_loan_db,additionalProperties={}],syncMode=incremental,cursorField=[],destinationSyncMode=append_dedup,primaryKey=[[loanId]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@1b10b393[stream=io.airbyte.protocol.models.AirbyteStream@48f8c901[name=loan_state,jsonSchema={"type":"object","properties":{"owner":{"type":"string"},"isCurrent":{"type":"boolean"},"createdDate":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"_ab_cdc_updated_at":{"type":"string"},"_ab_cdc_deleted_at":{"type":"string"},"_ab_cdc_lsn":{"type":"number"},"id":{"type":"string"},"state":{"type":"string"},"updatedDate":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"loanId":{"airbyte_type":"integer","type":"number"}},"$schema":"http://json-schema.org/draft-07/schema#"},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[],sourceDefinedPrimaryKey=[[id]],namespace=src_postgres_loan_db,additionalProperties={}],syncMode=incremental,cursorField=[],destinationSyncMode=append_dedup,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@50e97161[stream=io.airbyte.protocol.models.AirbyteStream@4adbb039[name=contact_loan_relation,jsonSchema={"type":"object","properties":{"role":{"type":"string"},"createdDate":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"contactId":{"airbyte_type":"integer","type":"number"},"contact":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"_ab_cdc_updated_at":{"type":"string"},"_ab_cdc_deleted_at":{"type":"string"},"_ab_cdc_lsn":{"type":"number"},"id":{"airbyte_type":"integer","type":"number"},"updatedDate":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"loanId":{"airbyte_type":"integer","type":"number"}},"$schema":"http://json-schema.org/draft-07/schema#"},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[],sourceDefinedPrimaryKey=[[id]],namespace=src_postgres_loan_db,additionalProperties={}],syncMode=incremental,cursorField=[],destinationSyncMode=append_dedup,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@54c91eda[stream=io.airbyte.protocol.models.AirbyteStream@5af77583[name=repayment_request_items,jsonSchema={"type":"object","properties":{"checkoutProductInLoanId":{"airbyte_type":"integer","type":"number"},"createdAt":{"format":"date-time","airbyte_type":"timestamp_with_timezone","type":"string"},"_ab_cdc_updated_at":{"type":"string"},"_ab_cdc_deleted_at":{"type":"string"},"repaymentRequestId":{"airbyte_type":"integer","type":"number"},"_ab_cdc_lsn":{"type":"number"},"id":{"airbyte_type":"integer","type":"number"}},"$schema":"http://json-schema.org/draft-07/schema#"},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[],sourceDefinedPrimaryKey=[[id]],namespace=src_postgres_loan_db,additionalProperties={}],syncMode=incremental,cursorField=[],destinationSyncMode=append_dedup,primaryKey=[[id]],additionalProperties={}]],additionalProperties={}],failures=[io.airbyte.config.FailureReason@418e65c5[failureOrigin=destination,failureType=system_error,internalMessage=Bad int64 value: 1E+3,externalMessage=Normalization failed during the dbt run. This may indicate a problem with the data itself.,metadata=io.airbyte.config.Metadata@56434fb5[additionalProperties={attemptNumber=0, jobId=3034615, from_trace_message=true, connector_command=write}],stacktrace=AirbyteDbtError: </null></null></null></null></null></null></null></null></null></null></null></null></null></null></null></null></null></null></null></null></null></null></null></null></null>
1442
23 of 39 ERROR creating incremental model src_postgres_loan_db.product_in_loan_scd...................................... [ERROR in 5.29s]
1443
Database Error in model product_in_loan_scd (models/generated/airbyte_incremental/scd/src_postgres_loan_db/product_in_loan_scd.sql)
1444
  Bad int64 value: 1E+3
1445
  compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_incremental/scd/src_postgres_loan_db/product_in_loan_scd.sql
1446
23 of 39 ERROR creating incremental model src_postgres_loan_db.product_in_loan_scd...................................... [ERROR in 5.29s]
1447
Database Error in model product_in_loan_scd (models/generated/airbyte_incremental/scd/src_postgres_loan_db/product_in_loan_scd.sql)
1448
  Bad int64 value: 1E+3
1449
  compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_incremental/scd/src_postgres_loan_db/product_in_loan_scd.sql,retryable=<null>,timestamp=1688759955078,additionalProperties={}], io.airbyte.config.FailureReason@4ae0a469[failureOrigin=destination,failureType=<null>,internalMessage=Destination process exited with non-zero exit code 1,externalMessage=Something went wrong within the destination connector,metadata=io.airbyte.config.Metadata@2b5a9bdb[additionalProperties={attemptNumber=0, jobId=3034615, connector_command=write}],stacktrace=io.airbyte.workers.internal.exception.DestinationException: Destination process exited with non-zero exit code 1</null></null>
1450
        at io.airbyte.workers.general.BufferedReplicationWorker.readFromDestination(BufferedReplicationWorker.java:418)
1451
        at io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsync$2(BufferedReplicationWorker.java:203)
1452
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
1453
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
1454
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
1455
        at java.base/java.lang.Thread.run(Thread.java:1589)
1456
,retryable=<null>,timestamp=1688759956194,additionalProperties={}]],additionalProperties={}]</null>
1457
2023-07-07 19:59:16 INFO i.a.w.t.s.ReplicationActivityImpl(lambda$replicate$3):165 - Sync summary length: 28299
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by rodireich** [comment]
https://github.com/airbytehq/oncall/issues/2446
[connection](https://cloud.airbyte.com/workspaces/91b3b9aa-df80-4893-80dc-19f4cce867c1/connections/5dd8775b-03a9-4255-ac22-b36a93f480e9/job-history#3034615::1)

**Comment by rodireich** [comment]
This code change seems to be related: https://github.com/airbytehq/airbyte/pull/14534/files#diff-02de9849a77ce73c67f0ab580b96a6170897f6eabcd42ac5516641f8944e9f08

**Comment by nguyenaiden** [comment]
This [PR](https://github.com/airbytehq/airbyte/commit/0537dde7d2d03192d1e3a507c28c34b8ba695942#diff-f01d6784124f99887982ac7ab84be1895a463ae5105dbcef9ceadefcbdb7e1d3) shadow patched the issue when the fasterxml version is bumped to 2.15.2 from 2.14. This upgrade currently breaking some existing tests. Once those are addressed, I'll submit the PR with the appropriate test cases and close out this ticket.

**Comment by nguyenaiden** [comment]
The fix has been merged and released. Will move it to done, but not close it yet to monitor.
