### ISSUE TITLE
After using ssh tunnel, residual thread problem

### ISSUE THREAD

**Issue by g9420** [airbytehq/airbyte#28310]
### What method are you using to run Airbyte?

Docker

### Platform Version or Helm Chart Version

0.44.3

### What step the error happened?

During the Sync

### Revelant information

After using sshWrapper, the warning is as follows
```
The main thread is exiting while children non-daemon threads from a connector are still active.
Ideally, this situation should not happen...
Please check with maintainers if the connector or library code should safely clean up its threads before quitting instead.
```

During the debugging process, it was found that the surviving non-daemon thread is related to ssh, and its shutdown sequence is after the main thread.
I think it should be set as a daemon thread when starting ssh.

### Relevant log output

```shell
io.airbyte.integrations.source.oss_tencent.OssTencentSourceKt --read --config /home/gao/Project/skw-airbyte-connector/airbyte-integrations/connectors/source-oss-tencent/src/main/resources/config.json --catalog /home/gao/Project/skw-airbyte-connector/airbyte-integrations/connectors/source-oss-tencent/src/main/resources/catalog.json
2023-07-14 10:21:17,738 main ERROR Rewrite contains an invalid element or attribute "MaskedDataInterceptor"
2023-07-14 02:21:17 INFO i.a.i.b.IntegrationCliParser(parseOptions):126 - integration args: {read=null, catalog=/home/gao/Project/skw-airbyte-connector/airbyte-integrations/connectors/source-oss-tencent/src/main/resources/catalog.json, config=/home/gao/Project/skw-airbyte-connector/airbyte-integrations/connectors/source-oss-tencent/src/main/resources/config.json}
2023-07-14 02:21:17 INFO i.a.i.b.IntegrationRunner(runInternal):127 - Running integration: io.airbyte.integrations.source.oss_tencent.TencentSshWrappedSource
2023-07-14 02:21:17 INFO i.a.i.b.IntegrationRunner(runInternal):128 - Command: READ
2023-07-14 02:21:17 INFO i.a.i.b.IntegrationRunner(runInternal):129 - Integration config: IntegrationConfig{command=READ, configPath='/home/gao/Project/skw-airbyte-connector/airbyte-integrations/connectors/source-oss-tencent/src/main/resources/config.json', catalogPath='/home/gao/Project/skw-airbyte-connector/airbyte-integrations/connectors/source-oss-tencent/src/main/resources/catalog.json', statePath='null'}
2023-07-14 02:21:18 WARN c.n.s.JsonMetaSchema(newValidator):278 - Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-07-14 02:21:18 WARN c.n.s.JsonMetaSchema(newValidator):278 - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-07-14 02:21:18 INFO i.a.i.b.s.SshTunnel(getInstance):204 - Starting connection with method: SSH_PASSWORD_AUTH
2023-07-14 02:21:18 WARN o.a.s.c.k.StaticServerKeyVerifier(handleAcceptance):59 - Server at /10.11.0.9:22 presented unverified EC key: SHA256:DfoZJEdv2wikYogzkCyFVqd0oF66R7F5C1L9o/Eqi/Y
2023-07-14 02:21:18 INFO i.a.i.b.s.SshTunnel(openTunnel):367 - Established tunneling session to airbyte-oss-test-1258678410.cos.ap-nanjing.myqcloud.com:80. Port forwarding started on /127.0.0.1:40993 
{"type":"RECORD","record":{"stream":"oss_file","data":{"name":"40m文件.txt","time":1688452018000,"data":"#file:./tmp/large-binary11790632438796495381.dat","size":43819776},"emitted_at":1689301282867}}
{"type":"RECORD","record":{"stream":"oss_file","data":{"name":"test/test.txt","time":1688452151000,"data":"data","size":9049},"emitted_at":1689301282977}}
2023-07-14 02:21:22 WARN i.a.i.b.IntegrationRunner(watchForOrphanThreads):268 - The main thread is exiting while children non-daemon threads from a connector are still active.
Ideally, this situation should not happen...
Please check with maintainers if the connector or library code should safely clean up its threads before quitting instead.
The main thread is: main (RUNNABLE)
 Thread stacktrace: java.base/java.lang.Thread.getStackTrace(Thread.java:1610)
        at io.airbyte.integrations.base.IntegrationRunner.dumpThread(IntegrationRunner.java:329)
        at io.airbyte.integrations.base.IntegrationRunner.watchForOrphanThreads(IntegrationRunner.java:272)
        at io.airbyte.integrations.base.IntegrationRunner.produceMessages(IntegrationRunner.java:209)
        at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:161)
        at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:120)
        at io.airbyte.integrations.source.oss_tencent.OssTencentSourceKt.main(OssTencentSource.kt:184)
2023-07-14 02:21:22 WARN i.a.i.b.IntegrationRunner(watchForOrphanThreads):280 - Active non-daemon thread: pool-2-thread-1 (TIMED_WAITING)
 Thread stacktrace: java.base@17.0.7/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@17.0.7/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
        at java.base@17.0.7/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401)
        at java.base@17.0.7/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903)
        at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061)
        at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
        at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
2023-07-14 02:21:22 WARN i.a.i.b.IntegrationRunner(watchForOrphanThreads):280 - Active non-daemon thread: NioSocketAcceptor-2 (RUNNABLE)
 Thread stacktrace: java.base@17.0.7/sun.nio.ch.EPoll.wait(Native Method)
        at java.base@17.0.7/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:118)
        at java.base@17.0.7/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:129)
        at java.base@17.0.7/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:146)
        at app//org.apache.mina.transport.socket.nio.NioSocketAcceptor.select(NioSocketAcceptor.java:299)
        at app//org.apache.mina.core.polling.AbstractPollingIoAcceptor$Acceptor.run(AbstractPollingIoAcceptor.java:466)
        at app//org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
        at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
2023-07-14 02:21:22 INFO i.a.i.b.IntegrationRunner(runInternal):205 - Completed integration: io.airbyte.integrations.source.oss_tencent.TencentSshWrappedSource
```

**Comment by girarda** [comment]
Closing due to inactivity. Feel free to reopen if this is still an issue
