### ISSUE TITLE
Using JsonSchemaPrimitive.v1 in airbyte-db

### ISSUE THREAD

**Issue by mdibaiee** [airbytehq/airbyte#28529]
### Topic

airbyte-db

### Revelant information

Hey folks!

I just noticed that connectors that rely on `airbyte-db` currently do not support `type: "integer"` fields as their cursor, mainly because they use the `v0` of JSONSchemaPrimitive models: [airbyte-db/IncrementalUtils.java](https://github.com/airbytehq/airbyte/blob/a16cbea2ae3f58ed803b1c18e5d2d4a2168dea50/airbyte-db/db-lib/src/main/java/io/airbyte/db/IncrementalUtils.java#L9) and [airbyte-protocol/JsonSchemaPrimitiveUtil.java](https://github.com/airbytehq/airbyte-protocol/blob/69a887bedb05bfd51740f1f5a23565afdfa30321/protocol-models/src/main/java/io/airbyte/protocol/models/JsonSchemaPrimitiveUtil.java#L25-L45)

Are there any plans to update `airbyte-db` and connectors that rely on it to use the newer `v1` types of `JsonSchemaPrimitive` so that `type: "integer"` fields can also be used as cursor?

For reference, this is the error you get if you try to use an integer field as cursor field:

```
{"error": Object {
"failure_type": String("system_error"),
"internal_message": String("java.lang.IllegalArgumentException: No enum constant io.airbyte.protocol.models.JsonSchemaPrimitive.INTEGER"),
"message": String("Something went wrong in the connector. See the logs for more details."),
"stack_trace": String("java.lang.IllegalArgumentException: No enum constant io.airbyte.protocol.models.JsonSchemaPrimitive.INTEGER\
	at java.base/java.lang.Enum.valueOf(Enum.java:273)\
	at io.airbyte.protocol.models.JsonSchemaPrimitive.valueOf(JsonSchemaPrimitive.java:7)\
	at io.airbyte.db.IncrementalUtils.getCursorType(IncrementalUtils.java:49)\
	at io.airbyte.integrations.source.relationaldb.AbstractDbSource.createReadIterator(AbstractDbSource.java:373)\
	at io.airbyte.integrations.source.relationaldb.AbstractDbSource.getSelectedIterators(AbstractDbSource.java:312)\
	at io.airbyte.integrations.source.relationaldb.AbstractDbSource.getIncrementalIterators(AbstractDbSource.java:269)\
	at io.airbyte.integrations.source.relationaldb.AbstractDbSource.read(AbstractDbSource.java:167)\
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:136)\
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:97)\
	at io.airbyte.integrations.source.bigquery.BigQuerySource.main(BigQuerySource.java:195)\
")}, "emitted_at": Number(1689868974354.0)}

```

**Comment by dyaffe** [comment]
@sherifnada is there any way that you could help with this one?  If so, I will buy you a beer.

**Comment by sherifnada** [comment]
@dyaffe just saw this! will get back to you soon

**Comment by evantahler** [comment]
Closing this issue - Airbyte can certainly sync integer types to and from databases:

 
![Screenshot 2024-07-02 at 3 31 29 PM](https://github.com/airbytehq/airbyte/assets/303226/dbcff71c-ac51-4e39-a4b2-12d3f435ed99)
