### ISSUE TITLE
Facing problem in deploying to local machine

### ISSUE THREAD

**Issue by saikumar1182** [airbytehq/airbyte#28603]

**Comment by saikumar1182** [comment]
WARNING: [Channel<51>: (airbyte-temporal:7233)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Unable to resolve host airbyte-temporal, cause=java.lang.RuntimeException: java.net.UnknownHostException: airbyte-temporal
airbyte-cron                      | 	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223)
airbyte-cron                      | 	at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)
airbyte-cron                      | 	at io.grpc.grpclb.GrpclbNameResolver.doResolve(GrpclbNameResolver.java:63)
airbyte-cron                      | 	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)
airbyte-cron                      | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
airbyte-cron                      | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
airbyte-cron                      | 	at java.base/java.lang.Thread.run(Thread.java:1589)
airbyte-cron                      | Caused by: java.net.UnknownHostException: airbyte-temporal
airbyte-cron                      | 	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:952)
airbyte-cron                      | 	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1663)
airbyte-cron                      | 	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1528)
airbyte-cron                      | 	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:632)
airbyte-cron                      | 	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
airbyte-cron                      | 	... 6 more
airbyte-cron                      | }
airbyte-server                    | Jul 24, 2023 6:57:01 AM io.grpc.internal.ManagedChannelImpl$NameResolverListener handleErrorInSyncContext
airbyte-server                    | WARNING: [Channel<41>: (airbyte-temporal:7233)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Unable to resolve host airbyte-temporal, cause=java.lang.RuntimeException: java.net.UnknownHostException: airbyte-temporal: Name or service not known
airbyte-server                    | 	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223)
airbyte-server                    | 	at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)
airbyte-server                    | 	at io.grpc.grpclb.GrpclbNameResolver.doResolve(GrpclbNameResolver.java:63)
airbyte-server                    | 	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)
airbyte-server                    | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
airbyte-server                    | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
airbyte-server                    | 	at java.base/java.lang.Thread.run(Thread.java:1589)
airbyte-server                    | Caused by: java.net.UnknownHostException: airbyte-temporal: Name or service not known
airbyte-server                    | 	at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
airbyte-server                    | 	at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Inet4AddressImpl.java:43)
airbyte-server                    | 	at java.base/java.net.InetAddress$PlatformResolver.lookupByName(InetAddress.java:1059)
airbyte-server                    | 	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1673)
airbyte-server                    | 	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:1003)
airbyte-server                    | 	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1663)
airbyte-server                    | 	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1528)
airbyte-server                    | 	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:632)
airbyte-server                    | 	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
airbyte-server                    | 	... 6 more
airbyte-server                    | }
airbyte-cron                      | Jul 24, 2023 6:57:01 AM io.grpc.internal.ManagedChannelImpl$NameResolverListener handleErrorInSyncContext
airbyte-cron                      | WARNING: [Channel<61>: (airbyte-temporal:7233)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Unable to resolve host airbyte-temporal, cause=java.lang.RuntimeException: java.net.UnknownHostException: airbyte-temporal
airbyte-cron                      | 	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223)
airbyte-cron                      | 	at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)
airbyte-cron                      | 	at io.grpc.grpclb.GrpclbNameResolver.doResolve(GrpclbNameResolver.java:63)
airbyte-cron                      | 	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)
airbyte-cron                      | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
airbyte-cron                      | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
airbyte-cron                      | 	at java.base/java.lang.Thread.run(Thread.java:1589)
airbyte-cron                      | Caused by: java.net.UnknownHostException: airbyte-temporal
airbyte-cron                      | 	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:952)
airbyte-cron                      | 	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1663)
airbyte-cron                      | 	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1528)
airbyte-cron                      | 	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:632)
airbyte-cron                      | 	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
airbyte-cron                      | 	... 6 more
airbyte-cron                      | }

**Comment by saikumar1182** [comment]
Facing the issue with the airbyte-temporal where it is rebooting and its in a loop.Please solve this issue asap !!

**Comment by Hikari** [comment]
I got the same error. Seems like the problem with airbyte-temporal is:
`Unable to create dynamic config client. Error: unable to validate dynamic config: dynamic config: config/dynamicconfig/development.yaml: stat config/dynamicconfig/development.yaml: no such file or directory
`

**Comment by renepetersen1984** [comment]
Same issue here!

**Comment by Hikari** [comment]
There is another thread, with a possible solution: https://github.com/airbytehq/airbyte/issues/28567

**Comment by alice010101** [comment]
I have same issue

**Comment by alice010101** [comment]
I resolved this issue by follow this [https://github.com/airbytehq/airbyte/issues/28469](https://github.com/airbytehq/airbyte/issues/28469)

**Comment by nahdaveiga** [comment]
I resolved this issue by follow this #28469

**Comment by marcosmarxm** [comment]
Should be fixed by https://github.com/airbytehq/airbyte/issues/28629

**Comment by pankajmyt** [comment]
Getting this in latest install done today using abctl
```
2024-10-04 16:20:27 INFO i.t.s.WorkflowServiceStubsImpl(<init>):86 - Created WorkflowServiceStubs for channel: ManagedChannelOrphanWrapper{delegate=ManagedChannelImpl{logId=9, target=airbyte-abctl-temporal:7233}}
Oct 04, 2024 4:20:28 PM io.grpc.internal.ManagedChannelImpl$NameResolverListener handleErrorInSyncContext
WARNING: [Channel<9>: (airbyte-abctl-temporal:7233)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Unable to resolve host airbyte-abctl-temporal, cause=java.lang.RuntimeException: java.net.UnknownHostException: airbyte-abctl-temporal
	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223)
	at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)
	at io.grpc.grpclb.GrpclbNameResolver.doResolve(GrpclbNameResolver.java:63)
	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.net.UnknownHostException: airbyte-abctl-temporal
	at java.base/java.net.InetAddress$CachedLookup.get(InetAddress.java:988)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1818)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1688)
	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:632)
	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
	... 6 more
}
2024-10-04 16:20:28 WARN i.a.c.t.TemporalUtils(getTemporalClientWhenConnected):173 - Ignoring exception while trying to request Temporal namespace:
io.grpc.StatusRuntimeException: UNAVAILABLE: Unable to resolve host airbyte-abctl-temporal
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:268) ~[grpc-stub-1.66.0.jar:1.66.0]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:249) ~[grpc-stub-1.66.0.jar:1.66.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:167) ~[grpc-stub-1.66.0.jar:1.66.0]
	at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.getSystemInfo(WorkflowServiceGrpc.java:4299) ~[temporal-serviceclient-1.22.3.jar:?]
	at io.temporal.serviceclient.SystemInfoInterceptor.getServerCapabilitiesOrThrow(SystemInfoInterceptor.java:95) ~[temporal-serviceclient-1.22.3.jar:?]
	at io.temporal.serviceclient.SystemInfoInterceptor$1.start(SystemInfoInterceptor.java:81) ~[temporal-serviceclient-1.22.3.jar:?]
	at io.grpc.stub.ClientCalls.startCall(ClientCalls.java:335) ~[grpc-stub-1.66.0.jar:1.66.0]
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:311) ~[grpc-stub-1.66.0.jar:1.66.0]
	at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:224) ~[grpc-stub-1.66.0.jar:1.66.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156) ~[grpc-stub-1.66.0.jar:1.66.0]
	at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.describeNamespace(WorkflowServiceGrpc.java:3822) ~[temporal-serviceclient-1.22.3.jar:?]
	at io.airbyte.commons.temporal.TemporalUtils.getNamespaceInfo(TemporalUtils.java:187) ~[io.airbyte-airbyte-commons-temporal-1.1.0.jar:?]
	at io.airbyte.commons.temporal.TemporalUtils.getTemporalClientWhenConnected(TemporalUtils.java:169) ~[io.airbyte-airbyte-commons-temporal-1.1.0.jar:?]
	at io.airbyte.commons.temporal.TemporalUtils.createTemporalService(TemporalUtils.java:78) ~[io.airbyte-airbyte-commons-temporal-1.1.0.jar:?]
	at io.airbyte.commons.temporal.TemporalUtils.createTemporalService(TemporalUtils.java:101) ~[io.airbyte-airbyte-commons-temporal-1.1.0.jar:?]
	at io.airbyte.commons.temporal.config.TemporalBeanFactory.temporalService(TemporalBeanFactory.java:32) ~[io.airbyte-airbyte-commons-temporal-1.1.0.jar:?]
	at io.airbyte.commons.temporal.config.$TemporalBeanFactory$TemporalService0$Definition.instantiate(Unknown Source) ~[io.airbyte-airbyte-commons-temporal-1.1.0.jar:?]
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2330) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2300) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2312) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3123) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3025) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2986) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2752) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1745) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:89) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2188) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForField(AbstractInitializableBeanDefinition.java:1694) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.airbyte.commons.temporal.$TemporalInitializationUtils$Definition.inject(Unknown Source) ~[io.airbyte-airbyte-commons-temporal-1.1.0.jar:?]
	at io.airbyte.commons.temporal.$TemporalInitializationUtils$Definition.instantiate(Unknown Source) ~[io.airbyte-airbyte-commons-temporal-1.1.0.jar:?]
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2330) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2300) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2312) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3123) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3025) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2986) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2752) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1745) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:89) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2188) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForField(AbstractInitializableBeanDefinition.java:1694) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.airbyte.workers.$ApplicationInitializer$Definition.inject(Unknown Source) ~[io.airbyte-airbyte-workers-1.1.0.jar:?]
	at io.airbyte.workers.$ApplicationInitializer$Definition.instantiate(Unknown Source) ~[io.airbyte-airbyte-workers-1.1.0.jar:?]
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2330) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2300) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2312) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3123) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3025) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2986) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2959) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:3577) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistrations(DefaultBeanContext.java:3532) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:3506) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:1446) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:883) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:873) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.event.ApplicationEventPublisherFactory$2.lambda$$1(ApplicationEventPublisherFactory.java:215) ~[micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.core.util.SupplierUtil$1.get(SupplierUtil.java:47) [micronaut-core-4.6.5.jar:4.6.5]
	at io.micronaut.context.event.ApplicationEventPublisherFactory$2.publishEvent(ApplicationEventPublisherFactory.java:226) [micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.http.server.netty.discovery.NettyServiceDiscovery.onStart(NettyServiceDiscovery.java:54) [micronaut-http-server-netty-4.6.5.jar:4.6.5]
	at io.micronaut.http.server.netty.discovery.$NettyServiceDiscovery$Definition$Exec.dispatch(Unknown Source) [micronaut-http-server-netty-4.6.5.jar:4.6.5]
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:456) [micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:3940) [micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.aop.chain.AdapterIntroduction.intercept(AdapterIntroduction.java:87) [micronaut-aop-4.6.5.jar:4.6.5]
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:143) [micronaut-aop-4.6.5.jar:4.6.5]
	at io.micronaut.http.server.netty.discovery.NettyServiceDiscovery$ApplicationEventListener$onStart1$Intercepted.onApplicationEvent(Unknown Source) [micronaut-http-server-netty-4.6.5.jar:4.6.5]
	at io.micronaut.context.event.ApplicationEventPublisherFactory.notifyEventListeners(ApplicationEventPublisherFactory.java:266) [micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.context.event.ApplicationEventPublisherFactory$2.publishEvent(ApplicationEventPublisherFactory.java:226) [micronaut-inject-4.6.5.jar:4.6.5]
	at io.micronaut.http.server.netty.NettyHttpServer.fireStartupEvents(NettyHttpServer.java:692) [micronaut-http-server-netty-4.6.5.jar:4.6.5]
	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:314) [micronaut-http-server-netty-4.6.5.jar:4.6.5]
	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:112) [micronaut-http-server-netty-4.6.5.jar:4.6.5]
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:81) [micronaut-context-4.6.5.jar:4.6.5]
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:334) [micronaut-context-4.6.5.jar:4.6.5]
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:320) [micronaut-context-4.6.5.jar:4.6.5]
	at io.airbyte.workers.Application.main(Application.java:15) [io.airbyte-airbyte-workers-1.1.0.jar:?]
Caused by: java.lang.RuntimeException: java.net.UnknownHostException: airbyte-abctl-temporal
	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223) ~[grpc-core-1.66.0.jar:1.66.0]
	at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282) ~[grpc-core-1.66.0.jar:1.66.0]
	at io.grpc.grpclb.GrpclbNameResolver.doResolve(GrpclbNameResolver.java:63) ~[grpc-grpclb-1.66.0.jar:1.66.0]
	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318) ~[grpc-core-1.66.0.jar:1.66.0]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.net.UnknownHostException: airbyte-abctl-temporal
	at java.base/java.net.InetAddress$CachedLookup.get(InetAddress.java:988) ~[?:?]
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1818) ~[?:?]
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1688) ~[?:?]
	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:632) ~[grpc-core-1.66.0.jar:1.66.0]
	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219) ~[grpc-core-1.66.0.jar:1.66.0]
	at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282) ~[grpc-core-1.66.0.jar:1.66.0]
	at io.grpc.grpclb.GrpclbNameResolver.doResolve(GrpclbNameResolver.java:63) ~[grpc-grpclb-1.66.0.jar:1.66.0]
	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318) ~[grpc-core-1.66.0.jar:1.66.0]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
2024-10-04 16:20:28 WARN i.a.c.t.TemporalUtils(getTemporalClientWhenConnected):163 - Waiting for namespace default to be initialized in temporal...
Oct 04, 2024 4:20:28 PM io.grpc.internal.ManagedChannelImpl$NameResolverListener handleErrorInSyncContext
WARNING: [Channel<1>: (airbyte-abctl-temporal:7233)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Unable to resolve host airbyte-abctl-temporal, cause=java.lang.RuntimeException: java.net.UnknownHostException: airbyte-abctl-temporal
	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223)
	at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)
	at io.grpc.grpclb.GrpclbNameResolver.doResolve(GrpclbNameResolver.java:63)
	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.net.UnknownHostException: airbyte-abctl-temporal
	at java.base/java.net.InetAddress$CachedLookup.get(InetAddress.java:988)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1818)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1688)
	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:632)
	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
	... 6 more
}

```

**Comment by marcosmarxm** [comment]
If someone is facing the issue please report a new ticket.
