### ISSUE TITLE
Flaky destinations tests imply that secrets are sometimes not present 

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#28617]
The [nightly build history](https://connectors.airbyte.com/files/generated_reports/test_summary/destination-snowflake/index.html) for Destination Snowflake is flaky.  

Looking at the failures:

```
SnowflakeDestinationIntegrationTest > testCheckFailsWithInvalidPermissions() FAILED
    java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.asText()" because the return value of "com.fasterxml.jackson.databind.JsonNode.get(String)" is null
        at io.airbyte.integrations.destination.snowflake.SnowflakeDatabase.createDataSource(SnowflakeDatabase.java:63)
        at io.airbyte.integrations.destination.snowflake.SnowflakeInternalStagingDestination.getDataSource(SnowflakeInternalStagingDestination.java:94)
        at io.airbyte.integrations.destination.snowflake.SnowflakeInternalStagingDestination.check(SnowflakeInternalStagingDestination.java:50)
        at io.airbyte.integrations.destination.jdbc.copy.SwitchingDestination.check(SwitchingDestination.java:56)
        at io.airbyte.integrations.destination.snowflake.SnowflakeDestinationIntegrationTest.testCheckFailsWithInvalidPermissions(SnowflakeDestinationIntegrationTest.java:36)
```

This is the short test: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-snowflake/src/test-integration/java/io/airbyte/integrations/destination/snowflake/SnowflakeDestinationIntegrationTest.java#L29-L38

This error implies that reading the config's JSON file is failing... sometimes.  If the secret itself isn't changing, then perhaps downloading the config into the test environment is having problems.

**Comment by alafanechere** [comment]
The nightly build passed today.
Will monitor for two consecutive successes before closing.

**Comment by alafanechere** [comment]
[Four consecutive successes on destination-snowflake](https://github.com/airbytehq/airbyte/issues/28419), closing.
![Screen Shot 2023-07-28 at 12.14.09.png](https://images.zenhubusercontent.com/62a72f6a30e85f5981338b7c/bbf37e07-d995-4915-a6cc-539c258ebc15)
