### ISSUE TITLE
Latest 0.50.11 in Docker results in "Unable to process retrieved latest destination definitions list"

### ISSUE THREAD

**Issue by PaulMatthieu** [airbytehq/airbyte#28779]
### What method are you using to run Airbyte?

Docker

### Platform Version or Helm Chart Version

0.50.11

### What step the error happened?

Upgrading the Platform or Helm Chart

### Revelant information

I upgraded from 0.44 to 0.50.11. Deployment works, and the UI is up.

However:  
Settings > Sources
Settings > Destinations
Clicking on any destination
Clicking on some of the sources (Typeform, Lokalize & Jenkins)
leads to an error page and the attached log output in the airbyte-server container

### Relevant log output

```shell
2023-07-27 12:56:23 ERROR i.a.s.a.ApiHelper(execute):40 - Unexpected Exception
io.airbyte.commons.server.errors.InternalServerKnownException: Unable to process retrieved latest source definitions list
	at io.airbyte.commons.server.handlers.SourceDefinitionsHandler.buildSourceDefinitionRead(SourceDefinitionsHandler.java:131) ~[io.airbyte-airbyte-commons-server-0.50.11.jar:?]
	at io.airbyte.commons.server.handlers.SourceDefinitionsHandler.getSourceDefinition(SourceDefinitionsHandler.java:215) ~[io.airbyte-airbyte-commons-server-0.50.11.jar:?]
	at io.airbyte.commons.server.handlers.SourceDefinitionsHandler.getSourceDefinitionForWorkspace(SourceDefinitionsHandler.java:237) ~[io.airbyte-airbyte-commons-server-0.50.11.jar:?]
	at io.airbyte.server.apis.SourceDefinitionApiController.lambda$getSourceDefinitionForWorkspace$4(SourceDefinitionApiController.java:97) ~[io.airbyte-airbyte-server-0.50.11.jar:?]
	at io.airbyte.server.apis.ApiHelper.execute(ApiHelper.java:26) ~[io.airbyte-airbyte-server-0.50.11.jar:?]
	at io.airbyte.server.apis.SourceDefinitionApiController.getSourceDefinitionForWorkspace(SourceDefinitionApiController.java:97) ~[io.airbyte-airbyte-server-0.50.11.jar:?]
	at io.airbyte.server.apis.$SourceDefinitionApiController$Definition$Exec.dispatch(Unknown Source) ~[io.airbyte-airbyte-server-0.50.11.jar:?]
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371) ~[micronaut-inject-3.9.4.jar:3.9.4]
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594) ~[micronaut-inject-3.9.4.jar:3.9.4]
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303) ~[micronaut-router-3.9.4.jar:3.9.4]
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111) ~[micronaut-router-3.9.4.jar:3.9.4]
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103) ~[micronaut-http-3.9.4.jar:3.9.4]
	at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659) ~[micronaut-http-server-3.9.4.jar:3.9.4]
	at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49) ~[reactor-core-3.5.5.jar:3.5.5]
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62) ~[reactor-core-3.5.5.jar:3.5.5]
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194) ~[reactor-core-3.5.5.jar:3.5.5]
	at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62) ~[micronaut-runtime-3.9.4.jar:3.9.4]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.5.5.jar:3.5.5]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.5.5.jar:3.5.5]
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53) ~[micronaut-context-3.9.4.jar:3.9.4]
	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.length()" because "this.input" is null
	at java.net.URI$Parser.parse(URI.java:3161) ~[?:?]
	at java.net.URI.<init>(URI.java:620) ~[?:?]
	at io.airbyte.commons.server.handlers.SourceDefinitionsHandler.buildSourceDefinitionRead(SourceDefinitionsHandler.java:122) ~[io.airbyte-airbyte-commons-server-0.50.11.jar:?]
	... 23 more
```

**Comment by pedroslopez** [comment]
Hey @PaulMatthieu - could you run the following query against the airbyte configs database and report back the results to help debug the issue?

```
SELECT * FROM actor_definition_version WHERE documentation_url is null;
```

**Comment by Paul-Jouhaud** [comment]
Hey @pedroslopez ,
I'm a coworker of @PaulMatthieu. Here's our list of actor_definition_version with the documentation_url undefined. As you can see, in the specs column, most have documentation_url embedded, so we could probably add one.
[actor_definition_version.csv](https://github.com/airbytehq/airbyte/files/12213033/actor_definition_version.csv)

**Comment by Paul-Jouhaud** [comment]
Ok @pedroslopez , I can confirm that by filling the documentation_url this fixes the issue.
Thanks for the lead!

**Comment by PaulMatthieu** [comment]
thanks a lot for this resolution

**Comment by davidmathers** [comment]
In summary, the solution is:

```sh
docker exec -ti airbyte-db psql -U docker -d airbyte -c "UPDATE actor_definition_version set documentation_url = '' WHERE documentation_url is null;"
```
