### ISSUE TITLE
airbyte-ci doesn't seem to work with python 3.11

### ISSUE THREAD

**Issue by marcosnils** [airbytehq/airbyte#28785]
### Topic

CI

### Revelant information

:wave: following the instructions here https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md and trying to make `airbyte-ci` work with python 3.11.2 and getting the following error: 

```
Traceback (most recent call last):                                                             
  File "/home/marcos/.local/bin/airbyte-ci", line 5, in <module>
    from pipelines.commands.airbyte_ci import airbyte_ci
  File "/home/marcos/.local/pipx/venvs/pipelines/lib/python3.11/site-packages/pipelines/commands/airbyte_ci.py", line 22, in <module>
    from .groups.connectors import connectors
  File "/home/marcos/.local/pipx/venvs/pipelines/lib/python3.11/site-packages/pipelines/commands/groups/connectors.py", line 20, in <module>
    from pipelines.publish import reorder_contexts, run_connector_publish_pipeline
  File "/home/marcos/.local/pipx/venvs/pipelines/lib/python3.11/site-packages/pipelines/publish.py", line 9, in <module>
    from airbyte_protocol.models.airbyte_protocol import ConnectorSpecification
  File "/home/marcos/.local/pipx/venvs/pipelines/lib/python3.11/site-packages/airbyte_protocol/models/__init__.py", line 3, in <module>
    from .airbyte_protocol import *    
  File "/home/marcos/.local/pipx/venvs/pipelines/lib/python3.11/site-packages/airbyte_protocol/models/airbyte_protocol.py", line 374, in <module>
    class AirbyteStateMessage(BaseModel):
  File "/home/marcos/.local/pipx/venvs/pipelines/lib/python3.11/site-packages/pydantic/main.py", line 292, in __new__
    cls.__signature__ = ClassAttribute('__signature__', generate_model_signature(cls.__init__, fields, config))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcos/.local/pipx/venvs/pipelines/lib/python3.11/site-packages/pydantic/utils.py", line 258, in generate_model_signature
    merged_params[param_name] = Parameter(
                                ^^^^^^^^^^
  File "/usr/lib/python3.11/inspect.py", line 2722, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: 'global' is not a valid parameter name
```

Just opening this since the README states that apparently python versions >=3.10 are supported :pray: 

cc @helder

**Comment by samber** [comment]
I'm having the same issue and just successfully ran a connector with python3.10 instead.

**Comment by MaxSPG** [comment]
Same problem here. Even with pipx installed and using the command exactly as stated in the docs here it does not work for me. 

Commands used: 
- `pipx install --editable --force --python=python3.10 airbyte-ci/connectors/pipelines`
- `pipx install --editable --force --python=python3.11 airbyte-ci/connectors/pipelines`

I am getting the following error: 
"_Unable to parse package spec: airbyte-ci/connectors/pipelines_"

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 365 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.
