### ISSUE TITLE
Source S3: Handle pyarrow exception: pyarrow.lib.ArrowInvalid: straddling object straddles two block boundaries (try to increase block size?)

### ISSUE THREAD

**Issue by roman-yermilov-gl** [airbytehq/airbyte#28860]
Affected workspace: [link](https://cloud.airbyte.io/workspaces/0ab05f51-6e83-4df4-9899-7eed7e045f16/connections/dae83cc6-f15e-4789-9a4e-83960a1b0a3d/job-history#3506252::2)

The problem happen while reading from file `data_sync/ad_account/2023_07_25_1690287882276_0.csv.gz`. The file size is 0.0055 Mb which is half the default block size of 10000 bytes

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 121, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 196, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 327, in _read_full_refresh
    for record_data_or_message in record_data_or_messages:
  File "/airbyte/integration_code/source_s3/source_files_abstract/stream.py", line 300, in read_records
    yield from self._read_from_slice(file_reader, stream_slice)
  File "/airbyte/integration_code/source_s3/source_files_abstract/stream.py", line 274, in _read_from_slice
    for record in file_reader.stream_records(f, storage_file.file_info):
  File "/airbyte/integration_code/source_s3/source_files_abstract/formats/csv_parser.py", line 236, in stream_records
    streaming_reader = pa_csv.open_csv(
  File "pyarrow/_csv.pyx", line 1273, in pyarrow._csv.open_csv
  File "pyarrow/_csv.pyx", line 1137, in pyarrow._csv.CSVStreamingReader._open
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: straddling object straddles two block boundaries (try to increase block size?)
```

**Comment by roman-yermilov-gl** [comment]
Closed due to new version using file-based CDK release
