### ISSUE TITLE
syncing to redshift fails if a row is too big

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2889]
from https://airbytehq.slack.com/archives/C01MFR03D5W/p1618295157432200
## Expected Behavior
If a row that is being synced to redshift is too big then it should be dropped and the sync should not fail

## Current Behavior
The sync fails because the row is too large
Logs: [logs-28-0.txt](https://github.com/airbytehq/airbyte/files/6312817/logs-28-0.txt)
The user later communicated the error code they saw in the system table: 
```
err_code: 1204
err_reason: String length exceeds DDL length
```

This is happening while syncing the "Engagements" stream from Hubspot. 

## Severity of the bug for you
Medium

**Comment by michel-tricot** [comment]
If we drop data, we should have a warning in the documentation.

**Comment by erichartono** [comment]
Maybe we should truncate data into max length, and has a flag in airbyte raw table to say it has been truncated.

**Comment by cgardens** [comment]
Note: This failure is happening in normalization.

error:
```
2021-04-13 05:07:00 INFO (/tmp/workspace/13/2) DefaultSyncWorker(run):111 - Running normalization.
2021-04-13 05:07:00 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 - Checking if airbyte/normalization:0.1.18 exists...
2021-04-13 05:07:01 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 - airbyte/normalization:0.1.18 was found locally.
2021-04-13 05:07:02 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 - Namespace(config='destination_config.json', integration_type=<DestinationType.redshift: 'redshift'>, out='/data/13/2/normalize')
2021-04-13 05:07:02 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 - transform_redshift
2021-04-13 05:07:02 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 - Processing destination_catalog.json...
2021-04-13 05:07:02 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 -   Generating airbyte_views/hubspot/contact_lists_ab1.sql from contact_lists
2021-04-13 05:07:02 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 -   Generating airbyte_views/hubspot/contact_lists_ab2.sql from contact_lists
2021-04-13 05:07:02 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 -   Generating airbyte_views/hubspot/contact_lists_ab3.sql from contact_lists
2021-04-13 05:07:02 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 -   Generating airbyte_tables/hubspot/contact_lists.sql from contact_lists
2021-04-13 05:07:02 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 -   Generating airbyte_views/hubspot/contact_lists_a20_filters_ab1.sql from contact_lists/filters
2021-04-13 05:07:02 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 -   Generating airbyte_views/hubspot/contact_lists_a20_filters_ab2.sql from contact_lists/filters
2021-04-13 05:07:02 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 -   Generating airbyte_views/hubspot/contact_lists_a20_filters_ab3.sql from contact_lists/filters
2021-04-13 05:07:02 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 -   Generating airbyte_tables/hubspot/contact_lists_a20_filters.sql from contact_lists/filters
2021-04-13 05:07:02 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 -   Generating airbyte_views/hubspot/contact_lists_4c6_metadata_ab1.sql from contact_lists/metaData
2021-04-13 05:07:02 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 -   Generating airbyte_views/hubspot/contact_lists_4c6_metadata_ab2.sql from contact_lists/metaData
2021-04-13 05:07:02 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 -   Generating airbyte_views/hubspot/contact_lists_4c6_metadata_ab3.sql from contact_lists/metaData
2021-04-13 05:07:02 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 -   Generating airbyte_tables/hubspot/contact_lists_4c6_metadata.sql from contact_lists/metaData
2021-04-13 05:07:03 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 - Running with dbt=0.18.2-rc1
2021-04-13 05:07:05 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 - Found 12 models, 0 tests, 0 snapshots, 0 analyses, 349 macros, 0 operations, 0 seed files, 1 source
2021-04-13 05:07:05 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 - 
2021-04-13 05:07:05 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 - 05:07:05 | Concurrency: 32 threads (target='prod')
2021-04-13 05:07:05 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 - 05:07:05 | 
2021-04-13 05:07:05 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 - 05:07:05 | 1 of 3 START table model hubspot.contact_lists............................................................... [RUN]
2021-04-13 05:07:06 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 - 05:07:06 | 1 of 3 OK created table model hubspot.contact_lists.......................................................... [[32mSELECT[0m in 0.34s]
2021-04-13 05:07:06 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 - 05:07:06 | 2 of 3 START table model hubspot.contact_lists_4c6_metadata.................................................. [RUN]
2021-04-13 05:07:06 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 - 05:07:06 | 3 of 3 START table model hubspot.contact_lists_a20_filters................................................... [RUN]
2021-04-13 05:07:06 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 - 05:07:06 | 2 of 3 OK created table model hubspot.contact_lists_4c6_metadata............................................. [[32mSELECT[0m in 0.43s]
2021-04-13 05:07:06 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 - 05:07:06 | 3 of 3 ERROR creating table model hubspot.contact_lists_a20_filters.......................................... [[31mERROR[0m in 0.35s]
2021-04-13 05:07:06 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 - 05:07:06 | 
2021-04-13 05:07:06 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 - 05:07:06 | Finished running 3 table models in 1.43s.
2021-04-13 05:07:06 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 - 
2021-04-13 05:07:06 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 - [31mCompleted with 1 error and 0 warnings:[0m
2021-04-13 05:07:06 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 - 
2021-04-13 05:07:06 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 - [33mDatabase Error in model contact_lists_a20_filters (models/generated/airbyte_tables/hubspot/contact_lists_a20_filters.sql)[0m
2021-04-13 05:07:06 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 -   JSON parsing error
2021-04-13 05:07:06 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 -   DETAIL:  
2021-04-13 05:07:06 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 -     -----------------------------------------------
2021-04-13 05:07:06 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 -     error:  JSON parsing error
2021-04-13 05:07:06 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 -     code:      8001
2021-04-13 05:07:06 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 -     context:   invalid json object [{"filterFamily":"CompanyPropertyValue","operator":"SET_ANY","propertyObjectType":"COMPANY","withinTimeMode":"PAST","type":"enumeration","property":"business_type","value":"Grower"},{"filterFamily":"CompanyPropertyValue","operator":"SET
2021-04-13 05:07:06 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 -     query:     72527682
2021-04-13 05:07:06 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 -     location:  funcs_json.hpp:128
2021-04-13 05:07:06 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 -     process:   query0_101_72527682 [pid=27692]
2021-04-13 05:07:06 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 -     -----------------------------------------------
2021-04-13 05:07:06 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 -   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/hubspot/contact_lists_a20_filters.sql
2021-04-13 05:07:06 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 - 
2021-04-13 05:07:06 INFO (/tmp/workspace/13/2) LineGobbler(voidCall):69 - Done. PASS=2 WARN=0 ERROR=1 SKIP=0 TOTAL=3
2021-04-13 05:07:07 INFO (/tmp/workspace/13/2) TemporalAttemptExecution(lambda$getWorkerThread$2):140 - Completing future exceptionally...
io.airbyte.workers.WorkerException: Normalization Failed.
	at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:118) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
	at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:48) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:137) [io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: io.airbyte.workers.WorkerException: Normalization Failed.
	at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:115) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
	... 3 more
	Suppressed: io.airbyte.workers.WorkerException: Tap process wasn't successful
		at io.airbyte.workers.normalization.DefaultNormalizationRunner.close(DefaultNormalizationRunner.java:100) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
		at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:110) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
		at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:48) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:137) [io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:832) [?:?]
2021-04-13 05:07:07 INFO (/tmp/workspace/13/2) TemporalAttemptExecution(get):124 - Stopping cancellation check scheduling...
2021-04-13 05:07:07 WARN (/tmp/workspace/13/2) POJOActivityTaskHandler$POJOActivityImplementation(execute):243 - Activity failure. ActivityId=611dd166-e763-3b56-985a-77325139c297, activityType=Run, attempt=1
java.util.concurrent.ExecutionException: io.airbyte.workers.WorkerException: Normalization Failed.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2063) ~[?:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:122) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
	at io.airbyte.workers.temporal.SyncWorkflow$SyncActivityImpl.run(SyncWorkflow.java:124) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityInboundCallsInterceptor.execute(POJOActivityTaskHandler.java:277) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityImplementation.execute(POJOActivityTaskHandler.java:216) [temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.POJOActivityTaskHandler.handle(POJOActivityTaskHandler.java:181) [temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:192) [temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:154) [temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73) [temporal-sdk-1.0.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: io.airbyte.workers.WorkerException: Normalization Failed.
	at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:118) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
	at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:48) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:137) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
	... 1 more
Caused by: io.airbyte.workers.WorkerException: Normalization Failed.
	at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:115) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
	at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:48) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:137) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
	... 1 more
	Suppressed: io.airbyte.workers.WorkerException: Tap process wasn't successful
		at io.airbyte.workers.normalization.DefaultNormalizationRunner.close(DefaultNormalizationRunner.java:100) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
		at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:110) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
		at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:48) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:137) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by erichartono** [comment]
FYI. This also happened on MS SQL to Redshift sync.

**Comment by ChristopheDuong** [comment]
From https://github.com/airbytehq/airbyte/issues/2889#issuecomment-820649760, it looks like a error code returned by Redshift because the `JSON_EXTRACT_PATH_TEXT` function wasn't able to parse the JSON properly.
(is that referring to https://github.com/airbytehq/airbyte/issues/2890?)

See https://docs.aws.amazon.com/redshift/latest/dg/JSON_EXTRACT_PATH_TEXT.html

There is an argument to those functions:

> null_if_invalid
>
>   A Boolean value that specifies whether to return NULL if the input JSON string is invalid instead of returning an error. To return NULL if the JSON is invalid, specify true (t). To return an error if the JSON is invalid, specify false (f). The default is false.

Should we override that default value with `true` instead? which would make this data loss that you are mentioning by skipping this row that would be invalid (too long?) 

In any case, would it work for you to export the normalization DBT models in order to tweak the `JSON_EXTRACT_PATH_TEXT` function call for the moment to your use (or in the short term)?

**Comment by ChristopheDuong** [comment]
The error 
> err_reason: String length exceeds DDL length

Should be thrown when the destination is copying data from s3 to redshift? not during normalization process?

**Comment by erichartono** [comment]
@ChristopheDuong I got that error "String length exceeds DDL length" on stl_load_errors table in redshift. I agree that this error is in RedShift. 

However, with MS SQL to Redshift, I think the issue is when syncing VARCHAR(MAX) on MS SQL to Redshift as VARCHAR(65535). I think redshift doesnt support VARCHAR(MAX).

**Comment by MC1-RicardoLeka** [comment]
I got the same problem.
When airbyte create the destination table he crated all the text coluns with varchar(65535) even the timestamp columns or columns with less than 65535.
Instead off varchar(65535) he can use text type for large columns and create the other with the same type.

**Comment by MC1-RicardoLeka** [comment]
After the Airbyte create the destination tables, I drop the wrong columns and add the columns with text type, and sync again, this work-around look´s fine.

**Comment by ChristopheDuong** [comment]
From AWS docs, the data type `TEXT` seems to be `Converted to VARCHAR(256).`

So, if you create the redshift destination tables with TEXT datatype, wouldn't you run more often into "row is too big" failures than with `VARCHAR(MAX) or VARCHAR(65535)`?
