### ISSUE TITLE
scheduler can fail until restart if temporal isn't ready on startup

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#2893]
## Expected Behavior
The scheduler should attempt to start, wait for temporal to start, and then begin running.

## Current Behavior
In some (presumably rare) cases, the scheduler can fail within `waitForTemporalServerAndLog` with an exception like:
```
[32mairbyte-scheduler   |[0m Exception in thread "main" io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
[32mairbyte-scheduler   |[0m 	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
[32mairbyte-scheduler   |[0m 	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
[32mairbyte-scheduler   |[0m 	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
[32mairbyte-scheduler   |[0m 	at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.listNamespaces(WorkflowServiceGrpc.java:2588)
[32mairbyte-scheduler   |[0m 	at io.airbyte.workers.temporal.TemporalPool.getNamespaces(TemporalPool.java:105)
[32mairbyte-scheduler   |[0m 	at io.airbyte.workers.temporal.TemporalPool.waitForTemporalServerAndLog(TemporalPool.java:84)
[32mairbyte-scheduler   |[0m 	at io.airbyte.workers.temporal.TemporalPool.run(TemporalPool.java:58)
[32mairbyte-scheduler   |[0m 	at io.airbyte.scheduler.app.SchedulerApp.start(SchedulerApp.java:113)
[32mairbyte-scheduler   |[0m 	at io.airbyte.scheduler.app.SchedulerApp.main(SchedulerApp.java:230)
[32mairbyte-scheduler   |[0m Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: airbyte-temporal/172.23.0.6:7233
[32mairbyte-scheduler   |[0m Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
[32mairbyte-scheduler   |[0m 	at io.grpc.netty.shaded.io.netty.channel.unix.Errors.throwConnectException(Errors.java:124)
[32mairbyte-scheduler   |[0m 	at io.grpc.netty.shaded.io.netty.channel.unix.Socket.finishConnect(Socket.java:243)
[32mairbyte-scheduler   |[0m 	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:672)
[32mairbyte-scheduler   |[0m 	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:649)
[32mairbyte-scheduler   |[0m 	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:529)
[32mairbyte-scheduler   |[0m 	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:465)
[32mairbyte-scheduler   |[0m 	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[32mairbyte-scheduler   |[0m 	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[32mairbyte-scheduler   |[0m 	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[32mairbyte-scheduler   |[0m 	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
```

## Severity of the bug for you
Medium

This happened multiple times for this person on restarting from scratch. It probably runs with unfortunate timing on his machine. I'm pretty sure the general solution is to just swallow exceptions during the namespace check (`waitForTemporalServerAndLog`) so the retries can continue until it succeeds. The instance we saw of this issue was "resolved" by running `docker restart airbyte-scheduler`.

Relevant Slack thread: https://airbytehq.slack.com/archives/C01MFR03D5W/p1618420149490500

**Comment by josedemouramachado** [comment]
Hello @jrhizor,

Can I have a go at it?

**Comment by jrhizor** [comment]
Sure! Basically if any call in `TemporalPool.getNamespaces` has an exception, we would want to either handle the exception in a way that lets us continue waiting in `waitForTemporalServerAndLog` or `getNamespaces` could just return an empty `Set`.

Ideally we would also have a test to make sure this behavior happens with a mocked `temporalService`. To test we'll likely need to make a few of these functions `protected` instead of `private`. You can ask questions here, create a PR directly, or reach out out to me on Slack if you have questions!

**Comment by marcosmarxm** [comment]
hey @josedemouramachado I just faced this problem on my Ubuntu machine again. Do you want help to set up the initial steps? You can find me on Slack so I can help you if you want, of course.

**Comment by jrhizor** [comment]
lowering the priority on this since https://github.com/airbytehq/airbyte/pull/3423 will restart the scheduler automatically anyways
