### ISSUE TITLE
[destination-Clickhouse] Cloud check fails because the service doesn't get enough time to load

### ISSUE THREAD

**Issue by apostoltego** [airbytehq/airbyte#29005]
### Connector Name

destination-clickhouse

### Connector Version

0.2.3

### What step the error happened?

During the sync

### Revelant information

When using clickhouse cloud users have the option to allow the service to idle after a defined period of inactivity. When new connections are attempted clickhouse brings up the service and this process can take a few minutes.

Currently, during the connection check process airbyte only wait 60000ms and fails if the connection isn't established within this time. This happens even if jdbc params are specified such as:

`socket_timeout=4000000&connection_timeout=300000`
Error is as follows:
`Stack Trace: io.airbyte.commons.exceptions.ConnectionErrorException: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 60002ms.`
This requires that the sync is reattempted when the service has fully loaded.

### Relevant log output

```shell
2023-08-02 12:24:53 INFO i.a.c.i.LineGobbler(voidCall):149 - ----- START CHECK -----
2023-08-02 12:24:53 INFO i.a.w.p.KubePodProcess(<init>):584 - Creating pod destination-clickhouse-check-102260-0-vndjn...
2023-08-02 12:24:53 INFO i.a.c.i.LineGobbler(voidCall):149 - 
2023-08-02 12:24:54 INFO i.a.w.p.KubePodProcess(waitForInitPodToRun):362 - Waiting for init container to be ready before copying files...
2023-08-02 12:24:54 INFO i.a.w.p.KubePodProcess(waitForInitPodToRun):366 - Init container present..
2023-08-02 12:24:56 INFO i.a.w.p.KubePodProcess(waitForInitPodToRun):369 - Init container ready..
2023-08-02 12:24:56 INFO i.a.w.p.KubePodProcess(<init>):615 - Copying files...
2023-08-02 12:24:56 INFO i.a.w.p.KubePodProcess(copyFilesToKubeConfigVolume):311 - Uploading file: source_config.json
2023-08-02 12:24:56 INFO i.a.w.p.KubePodProcess(copyFilesToKubeConfigVolume):319 - kubectl cp /tmp/86071372-e0c5-4b1b-94ac-66530ce28c67/source_config.json airbyte/destination-clickhouse-check-102260-0-vndjn:/config/source_config.json -c init
2023-08-02 12:24:56 INFO i.a.w.p.KubePodProcess(copyFilesToKubeConfigVolume):322 - Waiting for kubectl cp to complete
2023-08-02 12:24:56 INFO i.a.w.p.KubePodProcess(copyFilesToKubeConfigVolume):336 - kubectl cp complete, closing process
2023-08-02 12:24:56 INFO i.a.w.p.KubePodProcess(copyFilesToKubeConfigVolume):311 - Uploading file: FINISHED_UPLOADING
2023-08-02 12:24:56 INFO i.a.w.p.KubePodProcess(copyFilesToKubeConfigVolume):319 - kubectl cp /tmp/dbbc798f-5b3b-4f8c-8f97-00d8d5156e08/FINISHED_UPLOADING airbyte/destination-clickhouse-check-102260-0-vndjn:/config/FINISHED_UPLOADING -c init
2023-08-02 12:24:56 INFO i.a.w.p.KubePodProcess(copyFilesToKubeConfigVolume):322 - Waiting for kubectl cp to complete
2023-08-02 12:24:56 INFO i.a.w.p.KubePodProcess(copyFilesToKubeConfigVolume):336 - kubectl cp complete, closing process
2023-08-02 12:24:56 INFO i.a.w.p.KubePodProcess(<init>):618 - Waiting until pod is ready...
2023-08-02 12:24:57 INFO i.a.w.p.KubePodProcess(lambda$setupStdOutAndStdErrListeners$11):667 - Setting stdout...
2023-08-02 12:24:57 INFO i.a.w.p.KubePodProcess(lambda$setupStdOutAndStdErrListeners$12):679 - Setting stderr...
2023-08-02 12:24:58 INFO i.a.w.p.KubePodProcess(<init>):634 - Reading pod IP...
2023-08-02 12:24:58 INFO i.a.w.p.KubePodProcess(<init>):636 - Pod IP: 10.0.24.76
2023-08-02 12:24:58 INFO i.a.w.p.KubePodProcess(<init>):643 - Using null stdin output stream...
2023-08-02 12:24:58 INFO i.a.w.i.VersionedAirbyteStreamFactory(create):177 - Reading messages from protocol version 0.2.0
2023-08-02 12:25:00 INFO i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - INFO i.a.i.d.c.ClickhouseDestination(main):113 starting destination: class io.airbyte.integrations.destination.clickhouse.ClickhouseDestination
2023-08-02 12:25:01 INFO i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - INFO i.a.i.b.IntegrationCliParser(parseOptions):126 integration args: {check=null, config=source_config.json}
2023-08-02 12:25:01 INFO i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - INFO i.a.i.b.IntegrationRunner(runInternal):108 Running integration: io.airbyte.integrations.base.ssh.SshWrappedDestination
2023-08-02 12:25:01 INFO i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - INFO i.a.i.b.IntegrationRunner(runInternal):109 Command: CHECK
2023-08-02 12:25:01 INFO i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - INFO i.a.i.b.IntegrationRunner(runInternal):110 Integration config: IntegrationConfig{command=CHECK, configPath='source_config.json', catalogPath='null', statePath='null'}
2023-08-02 12:25:01 WARN i.a.w.i.VersionedAirbyteStreamFactory(internalLog):309 - WARN c.n.s.JsonMetaSchema(newValidator):278 Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-08-02 12:25:01 WARN i.a.w.i.VersionedAirbyteStreamFactory(internalLog):309 - WARN c.n.s.JsonMetaSchema(newValidator):278 Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-08-02 12:25:02 INFO i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - INFO i.a.i.b.s.SshTunnel(getInstance):204 Starting connection with method: NO_TUNNEL
2023-08-02 12:25:02 INFO i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - INFO c.z.h.HikariDataSource(<init>):80 HikariPool-1 - Starting...
2023-08-02 12:25:02 INFO i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - INFO c.z.h.HikariDataSource(<init>):82 HikariPool-1 - Start completed.
2023-08-02 12:26:02 ERROR i.a.w.i.VersionedAirbyteStreamFactory(internalLog):308 - ERROR i.a.i.d.c.ClickhouseDestination(check):93 Exception while checking connection: io.airbyte.commons.exceptions.ConnectionErrorException: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 60002ms.
	at io.airbyte.integrations.destination.jdbc.AbstractJdbcDestination.attemptTableOperations(AbstractJdbcDestination.java:143) ~[io.airbyte.airbyte-integrations.connectors-destination-jdbc-0.42.1.jar:?]
	at io.airbyte.integrations.destination.jdbc.AbstractJdbcDestination.attemptSQLCreateAndDropTableOperations(AbstractJdbcDestination.java:100) ~[io.airbyte.airbyte-integrations.connectors-destination-jdbc-0.42.1.jar:?]
	at io.airbyte.integrations.destination.clickhouse.ClickhouseDestination.check(ClickhouseDestination.java:90) ~[io.airbyte.airbyte-integrations.connectors-destination-clickhouse-0.42.1.jar:?]
	at io.airbyte.integrations.base.ssh.SshTunnel.sshWrap(SshTunnel.java:270) ~[io.airbyte.airbyte-integrations.bases-base-java-0.42.1.jar:?]
	at io.airbyte.integrations.base.ssh.SshWrappedDestination.check(SshWrappedDestination.java:67) ~[io.airbyte.airbyte-integrations.bases-base-java-0.42.1.jar:?]
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:126) ~[io.airbyte.airbyte-integrations.bases-base-java-0.42.1.jar:?]
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:101) ~[io.airbyte.airbyte-integrations.bases-base-java-0.42.1.jar:?]
	at io.airbyte.integrations.destination.clickhouse.ClickhouseDestination.main(ClickhouseDestination.java:114) ~[io.airbyte.airbyte-integrations.connectors-destination-clickhouse-0.42.1.jar:?]
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 60002ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:181) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[HikariCP-5.0.1.jar:?]
	at io.airbyte.db.jdbc.DefaultJdbcDatabase.bufferedResultSetQuery(DefaultJdbcDatabase.java:54) ~[io.airbyte.airbyte-db-db-lib-0.42.1.jar:?]
	at io.airbyte.integrations.destination.jdbc.AbstractJdbcDestination.attemptTableOperations(AbstractJdbcDestination.java:126) ~[io.airbyte.airbyte-integrations.connectors-destination-jdbc-0.42.1.jar:?]
	... 7 more

Stack Trace: io.airbyte.commons.exceptions.ConnectionErrorException: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 60002ms.
	at io.airbyte.integrations.destination.jdbc.AbstractJdbcDestination.attemptTableOperations(AbstractJdbcDestination.java:143)
	at io.airbyte.integrations.destination.jdbc.AbstractJdbcDestination.attemptSQLCreateAndDropTableOperations(AbstractJdbcDestination.java:100)
	at io.airbyte.integrations.destination.clickhouse.ClickhouseDestination.check(ClickhouseDestination.java:90)
	at io.airbyte.integrations.base.ssh.SshTunnel.sshWrap(SshTunnel.java:270)
	at io.airbyte.integrations.base.ssh.SshWrappedDestination.check(SshWrappedDestination.java:67)
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:126)
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:101)
	at io.airbyte.integrations.destination.clickhouse.ClickhouseDestination.main(ClickhouseDestination.java:114)
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 60002ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:181)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
	at io.airbyte.db.jdbc.DefaultJdbcDatabase.bufferedResultSetQuery(DefaultJdbcDatabase.java:54)
	at io.airbyte.integrations.destination.jdbc.AbstractJdbcDestination.attemptTableOperations(AbstractJdbcDestination.java:126)
	... 7 more

2023-08-02 12:26:02 INFO i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - INFO c.z.h.HikariDataSource(close):350 HikariPool-1 - Shutdown initiated...
2023-08-02 12:26:16 INFO i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - INFO c.z.h.HikariDataSource(close):352 HikariPool-1 - Shutdown completed.
2023-08-02 12:26:16 INFO i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - INFO i.a.i.b.IntegrationRunner(runInternal):186 Completed integration: io.airbyte.integrations.base.ssh.SshWrappedDestination
2023-08-02 12:26:16 INFO i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - INFO i.a.i.d.c.ClickhouseDestination(main):115 completed destination: class io.airbyte.integrations.destination.clickhouse.ClickhouseDestination
2023-08-02 12:26:17 INFO i.a.w.p.KubePodProcess(close):799 - (pod: airbyte / destination-clickhouse-check-102260-0-vndjn) - Closed all resources for pod
2023-08-02 12:26:17 INFO i.a.w.g.DefaultCheckConnectionWorker(run):117 - Check connection job received output: io.airbyte.config.StandardCheckConnectionOutput@5cfd8527[status=failed,message=Could not connect with provided configuration. 
java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 60002ms.,additionalProperties={}]
2023-08-02 12:26:17 INFO i.a.w.t.TemporalAttemptExecution(get):163 - Stopping cancellation check scheduling...
2023-08-02 12:26:17 INFO i.a.c.i.LineGobbler(voidCall):149 - 
2023-08-02 12:26:17 INFO i.a.c.i.LineGobbler(voidCall):149 - ----- END CHECK -----
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
