### ISSUE TITLE
BigQuery Destination V2 - Query error: Invalid JSON Path

### ISSUE THREAD

**Issue by haithem-souala** [airbytehq/airbyte#29078]
### Connector Name

destination-bigquery

### Connector Version

1.7.2

### What step the error happened?

During the sync

### Revelant information

Normalization: Raw data (json)
Source: Postgres v3.0.2

### Relevant log output

```shell
at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146) ~[google-api-client-1.31.5.jar:1.31.5]
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118) ~[google-api-client-1.31.5.jar:1.31.5]
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37) ~[google-api-client-1.31.5.jar:1.31.5]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:428) ~[google-api-client-1.31.5.jar:1.31.5]
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1111) ~[google-http-client-1.43.1.jar:1.43.1]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514) ~[google-api-client-1.31.5.jar:1.31.5]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455) ~[google-api-client-1.31.5.jar:1.31.5]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565) ~[google-api-client-1.31.5.jar:1.31.5]
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.getQueryResults(HttpBigQueryRpc.java:692) ~[google-cloud-bigquery-2.27.0.jar:2.27.0]
	at com.google.cloud.bigquery.BigQueryImpl$36.call(BigQueryImpl.java:1437) ~[google-cloud-bigquery-2.27.0.jar:2.27.0]
	at com.google.cloud.bigquery.BigQueryImpl$36.call(BigQueryImpl.java:1432) ~[google-cloud-bigquery-2.27.0.jar:2.27.0]
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103) ~[gax-2.28.1.jar:2.28.1]
	at com.google.cloud.bigquery.BigQueryRetryHelper.run(BigQueryRetryHelper.java:86) ~[google-cloud-bigquery-2.27.0.jar:2.27.0]
	at com.google.cloud.bigquery.BigQueryRetryHelper.runWithRetries(BigQueryRetryHelper.java:49) ~[google-cloud-bigquery-2.27.0.jar:2.27.0]
	at com.google.cloud.bigquery.BigQueryImpl.getQueryResults(BigQueryImpl.java:1431) ~[google-cloud-bigquery-2.27.0.jar:2.27.0]
	at com.google.cloud.bigquery.BigQueryImpl.getQueryResults(BigQueryImpl.java:1415) ~[google-cloud-bigquery-2.27.0.jar:2.27.0]
	at com.google.cloud.bigquery.Job$1.call(Job.java:338) ~[google-cloud-bigquery-2.27.0.jar:2.27.0]
	at com.google.cloud.bigquery.Job$1.call(Job.java:335) ~[google-cloud-bigquery-2.27.0.jar:2.27.0]
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103) ~[gax-2.28.1.jar:2.28.1]
	at com.google.cloud.bigquery.BigQueryRetryHelper.run(BigQueryRetryHelper.java:86) ~[google-cloud-bigquery-2.27.0.jar:2.27.0]
	at com.google.cloud.bigquery.BigQueryRetryHelper.runWithRetries(BigQueryRetryHelper.java:49) ~[google-cloud-bigquery-2.27.0.jar:2.27.0]
	at com.google.cloud.bigquery.Job.waitForQueryResults(Job.java:334) ~[google-cloud-bigquery-2.27.0.jar:2.27.0]
	at com.google.cloud.bigquery.Job.waitFor(Job.java:244) ~[google-cloud-bigquery-2.27.0.jar:2.27.0]
	at io.airbyte.integrations.destination.bigquery.typing_deduping.BigQueryDestinationHandler.execute(BigQueryDestinationHandler.java:63) ~[io.airbyte.airbyte-integrations.connectors-destination-bigquery-24.0.2.jar:?]
	at io.airbyte.integrations.base.destination.typing_deduping.DefaultTyperDeduper.typeAndDedupe(DefaultTyperDeduper.java:100) ~[io.airbyte.airbyte-integrations.bases-base-typing-deduping-24.0.2.jar:?]
	at io.airbyte.integrations.destination.bigquery.BigQueryStagingConsumerFactory.lambda$incrementalTypingAndDedupingStreamConsumer$1(BigQueryStagingConsumerFactory.java:93) ~[io.airbyte.airbyte-integrations.connectors-destination-bigquery-24.0.2.jar:?]
	at io.airbyte.integrations.destination.bigquery.BigQueryStagingConsumerFactory.lambda$flushBufferFunction$5(BigQueryStagingConsumerFactory.java:217) ~[io.airbyte.airbyte-integrations.connectors-destination-bigquery-24.0.2.jar:?]
	... 13 more

Stack Trace: java.lang.RuntimeException: Failed to upload buffer to stage and commit to destination
	at io.airbyte.integrations.destination.bigquery.BigQueryStagingConsumerFactory.lambda$flushBufferFunction$5(BigQueryStagingConsumerFactory.java:220)
	at io.airbyte.integrations.destination.record_buffer.SerializedBufferingStrategy.flushSingleBuffer(SerializedBufferingStrategy.java:125)
	at io.airbyte.integrations.destination.record_buffer.SerializedBufferingStrategy.addRecord(SerializedBufferingStrategy.java:82)
	at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.acceptTracked(BufferedStreamConsumer.java:205)
	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.accept(FailureTrackingAirbyteMessageConsumer.java:65)
	at io.airbyte.integrations.base.Destination$ShimToSerializedAirbyteMessageConsumer.consumeMessage(Destination.java:114)
	at io.airbyte.integrations.base.Destination$ShimToSerializedAirbyteMessageConsumer.accept(Destination.java:90)
	at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:234)
	at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:214)
	at io.airbyte.integrations.base.IntegrationRunner.lambda$runInternal$0(IntegrationRunner.java:153)
	at io.airbyte.integrations.base.IntegrationRunner.watchForOrphanThreads(IntegrationRunner.java:272)
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:157)
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:99)
	at io.airbyte.integrations.destination.bigquery.BigQueryDestination.main(BigQueryDestination.java:455)
Caused by: com.google.cloud.bigquery.BigQueryException: Query error: Invalid JSON Path at [7:1]
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:114)
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.getQueryResults(HttpBigQueryRpc.java:694)
	at com.google.cloud.bigquery.BigQueryImpl$36.call(BigQueryImpl.java:1437)
	at com.google.cloud.bigquery.BigQueryImpl$36.call(BigQueryImpl.java:1432)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103)
	at com.google.cloud.bigquery.BigQueryRetryHelper.run(BigQueryRetryHelper.java:86)
	at com.google.cloud.bigquery.BigQueryRetryHelper.runWithRetries(BigQueryRetryHelper.java:49)
	at com.google.cloud.bigquery.BigQueryImpl.getQueryResults(BigQueryImpl.java:1431)
	at com.google.cloud.bigquery.BigQueryImpl.getQueryResults(BigQueryImpl.java:1415)
	at com.google.cloud.bigquery.Job$1.call(Job.java:338)
	at com.google.cloud.bigquery.Job$1.call(Job.java:335)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103)
	at com.google.cloud.bigquery.BigQueryRetryHelper.run(BigQueryRetryHelper.java:86)
	at com.google.cloud.bigquery.BigQueryRetryHelper.runWithRetries(BigQueryRetryHelper.java:49)
	at com.google.cloud.bigquery.Job.waitForQueryResults(Job.java:334)
	at com.google.cloud.bigquery.Job.waitFor(Job.java:244)
	at io.airbyte.integrations.destination.bigquery.typing_deduping.BigQueryDestinationHandler.execute(BigQueryDestinationHandler.java:63)
	at io.airbyte.integrations.base.destination.typing_deduping.DefaultTyperDeduper.typeAndDedupe(DefaultTyperDeduper.java:100)
	at io.airbyte.integrations.destination.bigquery.BigQueryStagingConsumerFactory.lambda$incrementalTypingAndDedupingStreamConsumer$1(BigQueryStagingConsumerFactory.java:93)
	at io.airbyte.integrations.destination.bigquery.BigQueryStagingConsumerFactory.lambda$flushBufferFunction$5(BigQueryStagingConsumerFactory.java:217)
	... 13 more
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
GET https://www.googleapis.com/bigquery/v2/projects/obfuscated-prod/queries/job_2Lrm0bREkUjJzsaSYhOC8mPD_Mk6?location=EU&maxResults=0&prettyPrint=false
{
  "code": 400,
  "errors": [
    {
      "domain": "global",
      "location": "q",
      "locationType": "parameter",
      "message": "Query error: Invalid JSON Path at [7:1]",
      "reason": "invalidQuery"
    }
  ],
  "message": "Query error: Invalid JSON Path at [7:1]",
  "status": "INVALID_ARGUMENT"
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:428)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1111)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.getQueryResults(HttpBigQueryRpc.java:692)
	... 31 more

2023-08-04 10:12:27 [43mdestination[0m > WARN i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):78 Airbyte message consumer: failed.
2023-08-04 10:12:27 [43mdestination[0m > ERROR i.a.i.d.b.BufferedStreamConsumer(close):286 executing on failed close procedure.
2023-08-04 10:12:27 [43mdestination[0m > INFO i.a.i.d.r.SerializedBufferingStrategy(close):158 Closing buffer for stream mempo_prod_rakam_web
2023-08-04 10:12:27 [43mdestination[0m > INFO i.a.i.d.b.BigQueryStagingConsumerFactory(lambda$onCloseFunction$6):241 Cleaning up destination started for 6 streams
2023-08-04 10:12:27 [43mdestination[0m > INFO i.a.i.b.d.t.DefaultTyperDeduper(typeAndDedupe):96 Attempting typing and deduping for eu_dataset_ds.mempo_prod_rakam_web
2023-08-04 10:12:27 [43mdestination[0m > INFO i.a.i.d.b.t.BigQueryDestinationHandler(execute):56 Executing sql 8e08afa0-b54e-49cc-b2bc-4658d5359e45:
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by haithem-souala** [comment]
Stacktrace:
[52fea15b_0d9a_4fde_80eb_00873cf4136b_logs_121_txt.txt](https://github.com/airbytehq/airbyte/files/12259802/52fea15b_0d9a_4fde_80eb_00873cf4136b_logs_121_txt.txt)

**Comment by haithem-souala** [comment]
It seems like BQ is not able to query a field starting with `$` --> SAFE_CAST(JSON_VALUE(`_airbyte_data`, '$.$server_time') AS DATETIME) AS `_server_time`

**Comment by haithem-souala** [comment]
Workaround: exclude the `$server_time`field.

**Comment by edgao** [comment]
destination-bigquery 1.7.4 is now available - can you give it a try?
