### ISSUE TITLE
BigQuery Destination V2 - Query error: Column metadata is not present in table

### ISSUE THREAD

**Issue by haithem-souala** [airbytehq/airbyte#29091]
### Connector Name

destination-bigquery

### Connector Version

1.7.2

### What step the error happened?

During the sync

### Revelant information

Normalization: raw data (json)
Source: Postgres

### Relevant log output

```shell
at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.start(FailureTrackingAirbyteMessageConsumer.java:43) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
        at io.airbyte.integrations.base.Destination$ShimToSerializedAirbyteMessageConsumer.start(Destination.java:75) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
        at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:223) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
        at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:214) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
        at io.airbyte.integrations.base.IntegrationRunner.lambda$runInternal$0(IntegrationRunner.java:153) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
        at io.airbyte.integrations.base.IntegrationRunner.watchForOrphanThreads(IntegrationRunner.java:272) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
        at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:157) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
        at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:99) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
        at io.airbyte.integrations.destination.bigquery.BigQueryDestination.main(BigQueryDestination.java:455) ~[io.airbyte.airbyte-integrations.connectors-destination-bigquery-24.0.2.jar:?]
        Suppressed: com.google.cloud.bigquery.BigQueryException: Query error: Column metadata is not present in table eu_woop_ds.notification_notification at [11:1]
                at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:114) ~[google-cloud-bigquery-2.27.0.jar:2.27.0]
                at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.getQueryResults(HttpBigQueryRpc.java:694) ~[google-cloud-bigquery-2.27.0.jar:2.27.0]
                at com.google.cloud.bigquery.BigQueryImpl$36.call(BigQueryImpl.java:1437) ~[google-cloud-bigquery-2.27.0.jar:2.27.0]
                at com.google.cloud.bigquery.BigQueryImpl$36.call(BigQueryImpl.java:1432) ~[google-cloud-bigquery-2.27.0.jar:2.27.0]
                at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103) ~[gax-2.28.1.jar:2.28.1]
                at com.google.cloud.bigquery.BigQueryRetryHelper.run(BigQueryRetryHelper.java:86) ~[google-cloud-bigquery-2.27.0.jar:2.27.0]
                at com.google.cloud.bigquery.BigQueryRetryHelper.runWithRetries(BigQueryRetryHelper.java:49) ~[google-cloud-bigquery-2.27.0.jar:2.27.0]
                at com.google.cloud.bigquery.BigQueryImpl.getQueryResults(BigQueryImpl.java:1431) ~[google-cloud-bigquery-2.27.0.jar:2.27.0]
                at com.google.cloud.bigquery.BigQueryImpl.getQueryResults(BigQueryImpl.java:1415) ~[google-cloud-bigquery-2.27.0.jar:2.27.0]
                at com.google.cloud.bigquery.Job$1.call(Job.java:338) ~[google-cloud-bigquery-2.27.0.jar:2.27.0]
                at com.google.cloud.bigquery.Job$1.call(Job.java:335) ~[google-cloud-bigquery-2.27.0.jar:2.27.0]
                at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103) ~[gax-2.28.1.jar:2.28.1]
                at com.google.cloud.bigquery.BigQueryRetryHelper.run(BigQueryRetryHelper.java:86) ~[google-cloud-bigquery-2.27.0.jar:2.27.0]
                at com.google.cloud.bigquery.BigQueryRetryHelper.runWithRetries(BigQueryRetryHelper.java:49) ~[google-cloud-bigquery-2.27.0.jar:2.27.0]
                at com.google.cloud.bigquery.Job.waitForQueryResults(Job.java:334) ~[google-cloud-bigquery-2.27.0.jar:2.27.0]
                at com.google.cloud.bigquery.Job.waitFor(Job.java:244) ~[google-cloud-bigquery-2.27.0.jar:2.27.0]
                at io.airbyte.integrations.destination.bigquery.typing_deduping.BigQueryDestinationHandler.execute(BigQueryDestinationHandler.java:63) ~[io.airbyte.airbyte-integrations.connectors-destination-bigquery-24.0.2.jar:?]
                at io.airbyte.integrations.base.destination.typing_deduping.DefaultTyperDeduper.typeAndDedupe(DefaultTyperDeduper.java:100) ~[io.airbyte.airbyte-integrations.bases-base-typing-deduping-24.0.2.jar:?]
                at io.airbyte.integrations.destination.bigquery.BigQueryStagingConsumerFactory.lambda$onCloseFunction$6(BigQueryStagingConsumerFactory.java:243) ~[io.airbyte.airbyte-integrations.connectors-destination-bigquery-24.0.2.jar:?]
                at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.close(BufferedStreamConsumer.java:306) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
                at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.close(FailureTrackingAirbyteMessageConsumer.java:82) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
                at io.airbyte.integrations.base.Destination$ShimToSerializedAirbyteMessageConsumer.close(Destination.java:95) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
                at io.airbyte.integrations.base.IntegrationRunner.lambda$runInternal$0(IntegrationRunner.java:152) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
                at io.airbyte.integrations.base.IntegrationRunner.watchForOrphanThreads(IntegrationRunner.java:272) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
                at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:157) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
                at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:99) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
                at io.airbyte.integrations.destination.bigquery.BigQueryDestination.main(BigQueryDestination.java:455) ~[io.airbyte.airbyte-integrations.connectors-destination-bigquery-24.0.2.jar:?]
        Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
GET https://www.googleapis.com/bigquery/v2/projects/lastmile-prod/queries/job_bJ8c8MZWWWp1myf2JyMFdIJJLIOt?location=EU&maxResults=0&prettyPrint=false
{
  "code": 400,
  "errors": [
    {
      "domain": "global",
      "location": "q",
      "locationType": "parameter",
      "message": "Query error: Column metadata is not present in table eu_woop_ds.notification_notification at [11:1]",
      "reason": "invalidQuery"
    }
  ],
  "message": "Query error: Column metadata is not present in table eu_woop_ds.notification_notification at [11:1]",
  "status": "INVALID_ARGUMENT"
}
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by haithem-souala** [comment]
Stacktrace:
[52fea15b_0d9a_4fde_80eb_00873cf4136b_logs_136_txt.txt](https://github.com/airbytehq/airbyte/files/12262819/52fea15b_0d9a_4fde_80eb_00873cf4136b_logs_136_txt.txt)

**Comment by haithem-souala** [comment]
When i check the destination table on bigquery: notification_notification, the field `metadata` is not present.

**Comment by evantahler** [comment]
Was `notification_notification` created by destinations v2, or did that table exist beforehand?

**Comment by haithem-souala** [comment]
Okey, that was a false-positive, i forgot to disable the old sync. (not v2), and the two syncs. the legacy and v2 were running in the same time.
