### ISSUE TITLE
HTTP sources fail to sync (HTTP GET Request)

### ISSUE THREAD

**Issue by dannob** [airbytehq/airbyte#2910]
## Expected Behavior

Given open source data like this:

`https://chronicdata.cdc.gov/resource/g4ie-h725.json`

I would like to store this data in Postgres.

## Current Behavior

The source and destination configuration was successful.  I specified the HTTP source as shown above.  the sync was not successful.  The error was 

`Caused by: io.airbyte.workers.WorkerException: Tap process wasn't successful`

## Logs
See attached log

## Steps to Reproduce
1. Configure source and destination as specified
1. Run a manual sync.
1.  Sync fails

## Severity of the bug for you
Medium

## Airbyte Version

VERSION=0.20.0-alpha

## Connector Version (if applicable)
HTTP 0.2.2

## Additional context
Docker image, MacOS 10.14.6
[logs-2-0.txt](https://github.com/airbytehq/airbyte/files/6320821/logs-2-0.txt)

**Comment by cgardens** [comment]
thanks for reporting @dannob ! we'll post here as we prioritize a fix for this

```
2021-04-15 19:51:55 INFO (/tmp/workspace/2/0) DefaultAirbyteDestination(start):66 - Running target...
2021-04-15 19:51:55 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 - Checking if airbyte/destination-postgres:0.2.4 exists...
2021-04-15 19:51:55 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 - airbyte/destination-postgres:0.2.4 was found locally.
2021-04-15 19:51:55 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 - Checking if airbyte/source-http-request:0.2.2 exists...
2021-04-15 19:51:55 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 - airbyte/source-http-request:0.2.2 was found locally.
2021-04-15 19:51:56 ERROR (/tmp/workspace/2/0) LineGobbler(voidCall):69 - Traceback (most recent call last):
2021-04-15 19:51:56 ERROR (/tmp/workspace/2/0) LineGobbler(voidCall):69 -   File "/usr/local/bin/base-python", line 8, in <module>
2021-04-15 19:51:56 ERROR (/tmp/workspace/2/0) LineGobbler(voidCall):69 -     sys.exit(main())
2021-04-15 19:51:56 ERROR (/tmp/workspace/2/0) LineGobbler(voidCall):69 -   File "/usr/local/lib/python3.7/site-packages/base_python/entrypoint.py", line 135, in main
2021-04-15 19:51:56 ERROR (/tmp/workspace/2/0) LineGobbler(voidCall):69 -     launch(source, sys.argv[1:])
2021-04-15 19:51:56 ERROR (/tmp/workspace/2/0) LineGobbler(voidCall):69 -   File "/usr/local/lib/python3.7/site-packages/base_python/entrypoint.py", line 120, in launch
2021-04-15 19:51:56 ERROR (/tmp/workspace/2/0) LineGobbler(voidCall):69 -     AirbyteEntrypoint(source).start(args)
2021-04-15 19:51:56 ERROR (/tmp/workspace/2/0) LineGobbler(voidCall):69 -   File "/usr/local/lib/python3.7/site-packages/base_python/entrypoint.py", line 110, in start
2021-04-15 19:51:56 ERROR (/tmp/workspace/2/0) LineGobbler(voidCall):69 -     generator = self.source.read(logger, config, catalog, state)
2021-04-15 19:51:56 ERROR (/tmp/workspace/2/0) LineGobbler(voidCall):69 -   File "/usr/local/lib/python3.7/site-packages/source_http_request/source.py", line 77, in read
2021-04-15 19:51:56 ERROR (/tmp/workspace/2/0) LineGobbler(voidCall):69 -     stream=SourceHttpRequest.STREAM_NAME, data=r.json(), emitted_at=int(datetime.now().timestamp()) * 1000
2021-04-15 19:51:56 ERROR (/tmp/workspace/2/0) LineGobbler(voidCall):69 -   File "pydantic/main.py", line 346, in pydantic.main.BaseModel.__init__
2021-04-15 19:51:56 ERROR (/tmp/workspace/2/0) LineGobbler(voidCall):69 - pydantic.error_wrappers.ValidationError: 1 validation error for AirbyteRecordMessage
2021-04-15 19:51:56 ERROR (/tmp/workspace/2/0) LineGobbler(voidCall):69 - data
2021-04-15 19:51:56 ERROR (/tmp/workspace/2/0) LineGobbler(voidCall):69 -   value is not a valid dict (type=type_error.dict)
```

**Comment by cgardens** [comment]
fy @sherifnada

**Comment by sherifnada** [comment]
A reasonable fix here would be to see if the return value is an array vs. an object. If the former then return a record per element in the array. otherwise return the object as a single record.

**Comment by Zirochkaa** [comment]
As @sherifnada mentioned [here](https://github.com/airbytehq/airbyte/issues/2910#issuecomment-821941256), we could look at type of `r.json()` (currently line 77 in `/source-http-request/source_http_request/source.py` file). If it's a dict - just yield AirbyteMessage. If it's a list - yield AirbyteMessage for each object in list. Since `SourceHttpRequest.read()` returns generator it won't be a problem.

This should take about 4-5 hours.

**Comment by vovavovavovavova** [comment]
I want to clarify a moment here. The responce.json() output can be any json-serialized object, as well object, as well array, as well array of arrays of objects, as well array of digits. The current validation accepts only objects and that caused an issue.

Proposed `if it's a list - yield AirbyteMessage for each object in list.` WILL fail if we get array containing any integer, float of inner array.

So in additional to yield every element of array I think the validation rule for AirbyteMessage.data should be changed from Object (Dict) to any JSON-type object. 

Otherwise we'll fail on data like below:

[
     {'field1': 'value1'},
     {field2: value2'},
     6,
     [1,2,3]
]
