### ISSUE TITLE
StarRocks destination. o.airbyte.workers.exception.TestHarnessException: Could not find image: airbyte/destination-starrocks:dev

### ISSUE THREAD

**Issue by alberttwong** [airbytehq/airbyte#29340]
### Connector Name

destination-starrocks

### Connector Version

latest

### What step the error happened?

None

### Revelant information

I can't find the image when running.  `./gradlew airbyte-integrations:connectors:destination-starrocks:integrationTest`

### Relevant log output

```shell
StarrocksDestinationAcceptanceTest > testCheckConnection() FAILED
    io.airbyte.workers.exception.TestHarnessException: Unexpected error while getting checking connection.
        at app//io.airbyte.workers.general.DefaultCheckConnectionTestHarness.run(DefaultCheckConnectionTestHarness.java:118)
        at app//io.airbyte.integrations.standardtest.destination.DestinationAcceptanceTest.runCheck(DestinationAcceptanceTest.java:1206)
        at app//io.airbyte.integrations.standardtest.destination.DestinationAcceptanceTest.testCheckConnection(DestinationAcceptanceTest.java:386)
        at java.base@17.0.8/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base@17.0.8/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base@17.0.8/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base@17.0.8/java.lang.reflect.Method.invoke(Method.java:568)
        at app//org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
        at app//org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
        at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
        at app//org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
        at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
        at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
        at app//org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.
11:19 AM
        Caused by:
        io.airbyte.workers.exception.TestHarnessException: Could not find image: airbyte/destination-starrocks:dev
            at app//io.airbyte.workers.process.DockerProcessFactory.create(DockerProcessFactory.java:104)
            at app//io.airbyte.workers.process.AirbyteIntegrationLauncher.check(AirbyteIntegrationLauncher.java:91)
            at app//io.airbyte.workers.general.DefaultCheckConnectionTestHarness.run(DefaultCheckConnectionTestHarness.java:64)
```
```


### Contribute

- [ ] Yes, I want to contribute

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
