### ISSUE TITLE
Unable to Start Airbyte v0.50.16 locally using the ./run-ab-platform.sh script

### ISSUE THREAD

**Issue by AidanHarveyNelson** [airbytehq/airbyte#29501]
### What method are you using to run Airbyte?

Docker

### Platform Version or Helm Chart Version

0.50.16

### What step the error happened?

On deploy

### Revelant information

Followed the instructions here https://docs.airbyte.com/deploying-airbyte/local-deployment/ to download the relevant docker compose information.

Attempted to run the `./run-ab-platform.sh` script to start the Airbyte service.

I can see that both the server and worker containers are stuck in a crash loop. I have provided the exact crash information below.

Unsure what I am doing wrong or what needs to be changed to ensure that the nodes are able to correctly start.

### Relevant log output

```shell
2023-08-17 09:37:59 2023-08-16 23:37:59 ERROR i.m.r.Micronaut(handleStartupException):338 - Error starting Micronaut server: Bean definition [io.airbyte.server.apis.DeclarativeSourceDefinitionsApiController] could not be loaded: Error instantiating bean of type  [io.airbyte.config.persistence.ConfigRepository]
2023-08-17 09:37:59 
2023-08-17 09:37:59 Message: Function not implemented
2023-08-17 09:37:59 Path Taken: new DeclarativeSourceDefinitionsApiController(DeclarativeSourceDefinitionsHandler handler) --> new DeclarativeSourceDefinitionsApiController([DeclarativeSourceDefinitionsHandler handler]) --> new DeclarativeSourceDefinitionsHandler([ConfigRepository configRepository],DeclarativeSourceManifestInjector manifestInjector) --> ConfigRepository.configRepository(Database configDatabase,[FeatureFlagClient featureFlagClient])
2023-08-17 09:37:59 io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.airbyte.server.apis.DeclarativeSourceDefinitionsApiController] could not be loaded: Error instantiating bean of type  [io.airbyte.config.persistence.ConfigRepository]
2023-08-17 09:37:59 
2023-08-17 09:37:59 Message: Function not implemented
2023-08-17 09:37:59 Path Taken: new DeclarativeSourceDefinitionsApiController(DeclarativeSourceDefinitionsHandler handler) --> new DeclarativeSourceDefinitionsApiController([DeclarativeSourceDefinitionsHandler handler]) --> new DeclarativeSourceDefinitionsHandler([ConfigRepository configRepository],DeclarativeSourceManifestInjector manifestInjector) --> ConfigRepository.configRepository(Database configDatabase,[FeatureFlagClient featureFlagClient])
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1921) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:249) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3326) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3684) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:341) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:194) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.runtime.Micronaut.start(Micronaut.java:75) ~[micronaut-context-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.runtime.Micronaut.run(Micronaut.java:323) ~[micronaut-context-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.runtime.Micronaut.run(Micronaut.java:309) ~[micronaut-context-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.airbyte.server.Application.main(Application.java:15) ~[io.airbyte-airbyte-server-0.50.16.jar:?]
2023-08-17 09:37:59 Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.airbyte.config.persistence.ConfigRepository]
2023-08-17 09:37:59 
2023-08-17 09:37:59 Message: Function not implemented
2023-08-17 09:37:59 Path Taken: new DeclarativeSourceDefinitionsApiController(DeclarativeSourceDefinitionsHandler handler) --> new DeclarativeSourceDefinitionsApiController([DeclarativeSourceDefinitionsHandler handler]) --> new DeclarativeSourceDefinitionsHandler([ConfigRepository configRepository],DeclarativeSourceManifestInjector manifestInjector) --> ConfigRepository.configRepository(Database configDatabase,[FeatureFlagClient featureFlagClient])
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2367) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.airbyte.server.config.$DatabaseBeanFactory$ConfigRepository3$Definition.build(Unknown Source) ~[io.airbyte-airbyte-server-0.50.16.jar:?]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.airbyte.commons.server.handlers.$DeclarativeSourceDefinitionsHandler$Definition.build(Unknown Source) ~[io.airbyte-airbyte-commons-server-0.50.16.jar:?]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.airbyte.server.apis.$DeclarativeSourceDefinitionsApiController$Definition.build(Unknown Source) ~[io.airbyte-airbyte-server-0.50.16.jar:?]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2746) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1915) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     ... 9 more
2023-08-17 09:37:59 Caused by: java.io.IOException: Function not implemented
2023-08-17 09:37:59     at sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:62) ~[?:?]
2023-08-17 09:37:59     at sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47) ~[?:?]
2023-08-17 09:37:59     at io.airbyte.featureflag.ClientKt.onChange(Client.kt:237) ~[io.airbyte-airbyte-featureflag-0.50.16.jar:?]
2023-08-17 09:37:59     at io.airbyte.featureflag.ClientKt.access$onChange(Client.kt:1) ~[io.airbyte-airbyte-featureflag-0.50.16.jar:?]
2023-08-17 09:37:59     at io.airbyte.featureflag.ConfigFileClient.<init>(Client.kt:100) ~[io.airbyte-airbyte-featureflag-0.50.16.jar:?]
2023-08-17 09:37:59     at io.airbyte.featureflag.$ConfigFileClient$Definition.build(Unknown Source) ~[io.airbyte-airbyte-featureflag-0.50.16.jar:?]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.airbyte.server.config.$DatabaseBeanFactory$ConfigRepository3$Definition.build(Unknown Source) ~[io.airbyte-airbyte-server-0.50.16.jar:?]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.airbyte.commons.server.handlers.$DeclarativeSourceDefinitionsHandler$Definition.build(Unknown Source) ~[io.airbyte-airbyte-commons-server-0.50.16.jar:?]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.airbyte.server.apis.$DeclarativeSourceDefinitionsApiController$Definition.build(Unknown Source) ~[io.airbyte-airbyte-server-0.50.16.jar:?]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2746) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1915) ~[micronaut-inject-3.10.0.jar:3.10.0]
2023-08-17 09:37:59     ... 9 more
```

**Comment by udit-001** [comment]
Facing the same issue on 0.50.36 and above! Unable to upgrade 😔

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
