### ISSUE TITLE
Airbyte is not stable 

### ISSUE THREAD

**Issue by sivankumar86** [airbytehq/airbyte#29570]
### What method are you using to run Airbyte?

Kubernetes

### Platform Version or Helm Chart Version

0.50.4

### What step the error happened?

During the Sync

### Revelant information

Airbyte is intermittently failing 

[c810ba10_3e93_4c4c_976f_8605746e4520_logs_335632_txt.log](https://github.com/airbytehq/airbyte/files/12374104/c810ba10_3e93_4c4c_976f_8605746e4520_logs_335632_txt.log)
 

### Relevant log output

```shell
2023-08-17 22:28:23 INFO i.a.p.j.DefaultJobPersistence(enqueueJob):172 - enqueuing pending job for scope: 5c5f2e21-cb7a-423d-85f4-1a00faf864af
2023-08-17 22:28:23 INFO i.a.w.t.s.a.JobCreationAndStatusUpdateActivityImpl(createNewJob):218 - New job created, with id: 335646
2023-08-17 22:28:23 INFO i.a.w.t.TemporalAttemptExecution(get):141 - Executing worker wrapper. Airbyte version: 0.50.4
2023-08-17 22:28:23 INFO i.a.a.c.AirbyteApiClient(retryWithJitterThrows):229 - Attempt 0 to save workflow id for cancellation
2023-08-17 22:28:23 INFO i.a.c.i.LineGobbler(voidCall):149 - 
2023-08-17 22:28:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2023-08-17 22:28:23 INFO i.a.c.i.LineGobbler(voidCall):149 - ----- START CHECK -----
2023-08-17 22:28:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2023-08-17 22:28:23 INFO i.a.c.i.LineGobbler(voidCall):149 - 
2023-08-17 22:28:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2023-08-17 22:28:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2023-08-17 22:28:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable LAUNCHDARKLY_KEY: ''
2023-08-17 22:28:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable FEATURE_FLAG_CLIENT: ''
2023-08-17 22:28:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable OTEL_COLLECTOR_ENDPOINT: ''
2023-08-17 22:28:23 INFO i.a.w.p.KubeProcessFactory(create):107 - Attempting to start pod = source-mssql-check-335632-1-knczw for zipau-docker.jfrog.io/source-mssql:1.1.25 with resources io.airbyte.config.ResourceRequirements@2c9bc7c3[cpuRequest=1000m,cpuLimit=2000m,memoryRequest=2048Mi,memoryLimit=4096Mi,additionalProperties={}] and allowedHosts null
2023-08-17 22:31:23 INFO i.a.w.t.TemporalAttemptExecution(get):138 - Cloud storage job log path: /workspace/335632/1/logs.log
2023-08-17 22:30:33 INFO i.a.w.t.TemporalAttemptExecution(lambda$getCancellationChecker$6):231 - Running sync worker cancellation...
2023-08-17 22:30:33 INFO i.a.w.t.TemporalAttemptExecution(lambda$getCancellationChecker$6):235 - Interrupting worker thread...
2023-08-17 22:30:33 INFO i.a.w.t.TemporalAttemptExecution(lambda$getCancellationChecker$6):238 - Cancelling completable future...
2023-08-17 22:30:33 WARN i.a.c.t.CancellationHandler$TemporalCancellationHandler(checkAndHandleCancellation):60 - Job either timed out or was cancelled.
2023-08-17 22:30:33 INFO i.a.w.t.TemporalAttemptExecution(get):163 - Stopping cancellation check scheduling...
2023-08-17 22:30:33 ERROR i.a.w.g.DefaultCheckConnectionWorker(run):125 - Unexpected error while checking connection: 
io.airbyte.workers.exception.WorkerException: null
	at io.airbyte.workers.process.KubeProcessFactory.create(KubeProcessFactory.java:154) ~[io.airbyte-airbyte-commons-worker-0.50.4.jar:?]
	at io.airbyte.workers.process.AirbyteIntegrationLauncher.check(AirbyteIntegrationLauncher.java:113) ~[io.airbyte-airbyte-commons-worker-0.50.4.jar:?]
	at io.airbyte.workers.general.DefaultCheckConnectionWorker.run(DefaultCheckConnectionWorker.java:69) ~[io.airbyte-airbyte-commons-worker-0.50.4.jar:?]
	at io.airbyte.workers.general.DefaultCheckConnectionWorker.run(DefaultCheckConnectionWorker.java:43) ~[io.airbyte-airbyte-commons-worker-0.50.4.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$5(TemporalAttemptExecution.java:195) ~[io.airbyte-airbyte-workers-0.50.4.jar:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1681) ~[?:?]
	at java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:515) ~[?:?]
	at java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:677) ~[?:?]
	at io.airbyte.workers.process.KubePortManagerSingleton.take(KubePortManagerSingleton.java:69) ~[io.airbyte-airbyte-commons-worker-0.50.4.jar:?]
	at io.airbyte.workers.process.KubeProcessFactory.create(KubeProcessFactory.java:110) ~[io.airbyte-airbyte-commons-worker-0.50.4.jar:?]
	... 5 more
2023-08-17 22:30:33 WARN i.t.i.a.ActivityTaskExecutors$BaseActivityTaskExecutor(execute):114 - Activity failure. ActivityId=9eca5684-457b-34cd-adc4-78a2d12cfb53, activityType=RunWithJobOutput, attempt=2
java.util.concurrent.CancellationException: null
	at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2510) ~[?:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getCancellationChecker$6(TemporalAttemptExecution.java:241) ~[io.airbyte-airbyte-workers-0.50.4.jar:?]
	at io.airbyte.commons.temporal.CancellationHandler$TemporalCancellationHandler.checkAndHandleCancellation(CancellationHandler.java:59) ~[io.airbyte-airbyte-commons-temporal-0.50.4.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getCancellationChecker$7(TemporalAttemptExecution.java:244) ~[io.airbyte-airbyte-workers-0.50.4.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
2023-08-17 22:30:33 INFO i.a.w.t.TemporalAttemptExecution(lambda$getWorkerThread$5):198 - Completing future exceptionally...
io.airbyte.workers.exception.WorkerException: Unexpected error while getting checking connection.
	at io.airbyte.workers.general.DefaultCheckConnectionWorker.run(DefaultCheckConnectionWorker.java:127) ~[io.airbyte-airbyte-commons-worker-0.50.4.jar:?]
	at io.airbyte.workers.general.DefaultCheckConnectionWorker.run(DefaultCheckConnectionWorker.java:43) ~[io.airbyte-airbyte-commons-worker-0.50.4.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$5(TemporalAttemptExecution.java:195) ~[io.airbyte-airbyte-workers-0.50.4.jar:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: io.airbyte.workers.exception.WorkerException
	at io.airbyte.workers.process.KubeProcessFactory.create(KubeProcessFactory.java:154) ~[io.airbyte-airbyte-commons-worker-0.50.4.jar:?]
	at io.airbyte.workers.process.AirbyteIntegrationLauncher.check(AirbyteIntegrationLauncher.java:113) ~[io.airbyte-airbyte-commons-worker-0.50.4.jar:?]
	at io.airbyte.workers.general.DefaultCheckConnectionWorker.run(DefaultCheckConnectionWorker.java:69) ~[io.airbyte-airbyte-commons-worker-0.50.4.jar:?]
	... 3 more
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1681) ~[?:?]
	at java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:515) ~[?:?]
	at java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:677) ~[?:?]
	at io.airbyte.workers.process.KubePortManagerSingleton.take(KubePortManagerSingleton.java:69) ~[io.airbyte-airbyte-commons-worker-0.50.4.jar:?]
	at io.airbyte.workers.process.KubeProcessFactory.create(KubeProcessFactory.java:110) ~[io.airbyte-airbyte-commons-worker-0.50.4.jar:?]
	at io.airbyte.workers.process.AirbyteIntegrationLauncher.check(AirbyteIntegrationLauncher.java:113) ~[io.airbyte-airbyte-commons-worker-0.50.4.jar:?]
	at io.airbyte.workers.general.DefaultCheckConnectionWorker.run(DefaultCheckConnectionWorker.java:69) ~[io.airbyte-airbyte-commons-worker-0.50.4.jar:?]
	... 3 more
2023-08-17 22:30:33 INFO i.a.c.i.LineGobbler(voidCall):149 - 
2023-08-17 22:30:33 INFO i.a.c.i.LineGobbler(voidCall):149 - ----- END CHECK -----
2023-08-17 22:30:33 INFO i.a.c.i.LineGobbler(voidCall):149 - 
2023-08-17 22:30:33 WARN i.t.i.w.ActivityWorker$TaskHandlerImpl(logExceptionDuringResultReporting):365 - Failure during reporting of activity result to the server. ActivityId = 9eca5684-457b-34cd-adc4-78a2d12cfb53, ActivityType = RunWithJobOutput, WorkflowId=connection_manager_29cf561d-c50c-4aea-93a9-ed2c28967113, WorkflowType=ConnectionManagerWorkflow, RunId=1c87c5bf-da67-4270-9266-65b673aaa1ca
io.grpc.StatusRuntimeException: NOT_FOUND: invalid activityID or activity already timed out or invoking workflow is completed
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271) ~[grpc-stub-1.54.0.jar:1.54.0]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252) ~[grpc-stub-1.54.0.jar:1.54.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165) ~[grpc-stub-1.54.0.jar:1.54.0]
	at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.respondActivityTaskFailed(WorkflowServiceGrpc.java:3866) ~[temporal-serviceclient-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.lambda$sendReply$1(ActivityWorker.java:320) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.retryer.GrpcRetryer.lambda$retry$0(GrpcRetryer.java:52) ~[temporal-serviceclient-1.17.0.jar:?]
	at io.temporal.internal.retryer.GrpcSyncRetryer.retry(GrpcSyncRetryer.java:67) ~[temporal-serviceclient-1.17.0.jar:?]
	at io.temporal.internal.retryer.GrpcRetryer.retryWithResult(GrpcRetryer.java:60) ~[temporal-serviceclient-1.17.0.jar:?]
	at io.temporal.internal.retryer.GrpcRetryer.retry(GrpcRetryer.java:50) ~[temporal-serviceclient-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.sendReply(ActivityWorker.java:315) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handleActivity(ActivityWorker.java:252) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:206) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:179) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93) ~[temporal-sdk-1.17.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
2023-08-17 22:30:39 INFO i.a.a.LoggingTrackingClient(track):55 - track. version: 0.50.4, userId: d34023de-55ec-4c7e-a758-937681bc1a92, action: Connector Jobs, metadata: {job_type=sync, namespace_definition=destination, number_of_streams=3, connector_source=Microsoft SQL Server (MSSQL) - Local Development, frequency=cron, connector_source_definition_id=afb6cf3f-b26d-4206-92f8-31d56a16eae5, workspace_id=c810ba10-3e93-4c4c-976f-8605746e4520, connector_source_docker_repository=zipau-docker.jfrog.io/source-mssql, attempt_stage=STARTED, connection_id=195d82e9-6531-4434-a1c1-648aa8cfe9d0, job_id=335649, connector_source_version=1.1.25, catalog.destination_sync_mode.append=set, connector_destination_version=1.0.5, attempt_id=2, connector_destination=Snowflake, operation_count=0, catalog.sync_mode.incremental=set, connector_destination_docker_repository=airbyte/destination-snowflake, table_prefix=true, workspace_name=c810ba10-3e93-4c4c-976f-8605746e4520, connector_destination_definition_id=424892c4-daac-4491-b35d-c6688ba547ba}
2023-08-17 22:32:07 INFO i.a.w.t.TemporalAttemptExecution(get):138 - Cloud storage job log path: /workspace/335632/1/logs.log
2023-08-17 22:31:23 INFO i.a.w.t.TemporalAttemptExecution(get):141 - Executing worker wrapper. Airbyte version: 0.50.4
2023-08-17 22:31:23 INFO i.a.a.c.AirbyteApiClient(retryWithJitterThrows):229 - Attempt 0 to save workflow id for cancellation
2023-08-17 22:31:23 INFO i.a.c.i.LineGobbler(voidCall):149 - 
2023-08-17 22:31:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2023-08-17 22:31:23 INFO i.a.c.i.LineGobbler(voidCall):149 - ----- START CHECK -----
2023-08-17 22:31:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2023-08-17 22:31:23 INFO i.a.c.i.LineGobbler(voidCall):149 - 
2023-08-17 22:31:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2023-08-17 22:31:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2023-08-17 22:31:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable LAUNCHDARKLY_KEY: ''
2023-08-17 22:31:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable FEATURE_FLAG_CLIENT: ''
2023-08-17 22:31:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable OTEL_COLLECTOR_ENDPOINT: ''
2023-08-17 22:31:23 INFO i.a.w.p.KubeProcessFactory(create):107 - Attempting to start pod = source-mssql-check-335632-1-uurhm for zipau-docker.jfrog.io/source-mssql:1.1.25 with resources io.airbyte.config.ResourceRequirements@3f74f01e[cpuRequest=1000m,cpuLimit=2000m,memoryRequest=2048Mi,memoryLimit=4096Mi,additionalProperties={}] and allowedHosts null
2023-08-17 22:31:23 INFO i.a.w.p.KubeProcessFactory(create):111 - source-mssql-check-335632-1-uurhm stdoutLocalPort = 9008
```

**Comment by marcosmarxm** [comment]
@sivankumar86 Closing this as it reports an issue from an outdated version of Airbyte. Please upgrade to the latest version. If the problem persists, please open a new issue.
