### ISSUE TITLE
Redshift Copier OOM

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#2957]
## Expected Behavior
*Tell us what should happen.*

## Current Behavior
full log: 
[logs-7-0 (3).txt](https://github.com/airbytehq/airbyte/files/6338920/logs-7-0.3.txt)

relevant log:
```
2021-04-15 00:55:54 INFO (/tmp/workspace/7/0) DefaultAirbyteDestination(cancel):113 - Attempting to cancel destination process...
2021-04-15 00:55:54 INFO (/tmp/workspace/7/0) DefaultAirbyteDestination(cancel):118 - Target process exists, cancelling...
2021-04-15 00:55:54 ERROR (/tmp/workspace/7/0) LineGobbler(voidCall):72 - Error when reading stream
java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:168) ~[?:?]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:281) ~[?:?]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:343) ~[?:?]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:297) ~[?:?]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339) ~[?:?]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188) ~[?:?]
	at java.io.InputStreamReader.read(InputStreamReader.java:181) ~[?:?]
	at java.io.BufferedReader.fill(BufferedReader.java:161) ~[?:?]
	at java.io.BufferedReader.readLine(BufferedReader.java:326) ~[?:?]
	at java.io.BufferedReader.readLine(BufferedReader.java:392) ~[?:?]
	at io.airbyte.commons.io.LineGobbler.voidCall(LineGobbler.java:68) [io.airbyte-airbyte-commons-0.20.0-alpha.jar:?]
	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:35) [io.airbyte-airbyte-commons-0.20.0-alpha.jar:?]
	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:29) [io.airbyte-airbyte-commons-0.20.0-alpha.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
2021-04-15 00:55:55 ERROR (/tmp/workspace/7/0) LineGobbler(voidCall):69 - read unix @->/var/run/docker.sock: read: connection reset by peer
2021-04-15 00:55:55 INFO (/tmp/workspace/7/0) TemporalAttemptExecution(lambda$getWorkerThread$2):140 - Completing future exceptionally...
io.airbyte.workers.WorkerException: Sync worker failed.
	at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:107) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
	at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:48) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:137) [io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.io.IOException: Broken pipe
	at java.io.FileOutputStream.writeBytes(Native Method) ~[?:?]
	at java.io.FileOutputStream.write(FileOutputStream.java:347) ~[?:?]
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:123) ~[?:?]
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:242) ~[?:?]
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:312) ~[?:?]
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:290) ~[?:?]
	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:131) ~[?:?]
	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:208) ~[?:?]
	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:120) ~[?:?]
	at java.io.BufferedWriter.write(BufferedWriter.java:233) ~[?:?]
	at java.io.Writer.write(Writer.java:249) ~[?:?]
	at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.accept(DefaultAirbyteDestination.java:81) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
	at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.accept(DefaultAirbyteDestination.java:46) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
	at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:102) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
	... 3 more
	Suppressed: io.airbyte.workers.WorkerException: Tap process wasn't successful
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteSource.close(DefaultAirbyteSource.java:112) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
		at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:92) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
		at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:48) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:137) [io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:832) [?:?]
	Suppressed: java.io.IOException: Broken pipe
		at java.io.FileOutputStream.writeBytes(Native Method) ~[?:?]
		at java.io.FileOutputStream.write(FileOutputStream.java:347) ~[?:?]
		at java.io.BufferedOutputStream.write(BufferedOutputStream.java:123) ~[?:?]
		at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:242) ~[?:?]
		at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:321) ~[?:?]
		at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:325) ~[?:?]
		at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:159) ~[?:?]
		at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:251) ~[?:?]
		at java.io.BufferedWriter.flush(BufferedWriter.java:257) ~[?:?]
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.notifyEndOfStream(DefaultAirbyteDestination.java:89) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.close(DefaultAirbyteDestination.java:101) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
		at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:92) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
		at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:48) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:137) [io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:832) [?:?]
2021-04-15 00:55:55 INFO (/tmp/workspace/7/0) TemporalAttemptExecution(get):124 - Stopping cancellation check scheduling...
2021-04-15 00:55:55 WARN (/tmp/workspace/7/0) POJOActivityTaskHandler$POJOActivityImplementation(execute):243 - Activity failure. ActivityId=4b02e5cd-82b6-3dc1-9d0b-486a90ddd4c3, activityType=Run, attempt=1
java.util.concurrent.ExecutionException: io.airbyte.workers.WorkerException: Sync worker failed.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2063) ~[?:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:122) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
	at io.airbyte.workers.temporal.SyncWorkflow$SyncActivityImpl.run(SyncWorkflow.java:124) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityInboundCallsInterceptor.execute(POJOActivityTaskHandler.java:277) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityImplementation.execute(POJOActivityTaskHandler.java:216) [temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.POJOActivityTaskHandler.handle(POJOActivityTaskHandler.java:181) [temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:192) [temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:154) [temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73) [temporal-sdk-1.0.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: io.airbyte.workers.WorkerException: Sync worker failed.
	at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:107) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
	at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:48) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:137) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
	... 1 more
Caused by: java.io.IOException: Broken pipe
	at java.io.FileOutputStream.writeBytes(Native Method) ~[?:?]
	at java.io.FileOutputStream.write(FileOutputStream.java:347) ~[?:?]
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:123) ~[?:?]
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:242) ~[?:?]
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:312) ~[?:?]
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:290) ~[?:?]
	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:131) ~[?:?]
	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:208) ~[?:?]
	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:120) ~[?:?]
	at java.io.BufferedWriter.write(BufferedWriter.java:233) ~[?:?]
	at java.io.Writer.write(Writer.java:249) ~[?:?]
	at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.accept(DefaultAirbyteDestination.java:81) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
	at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.accept(DefaultAirbyteDestination.java:46) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
	at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:102) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
	at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:48) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:137) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
	... 1 more
	Suppressed: io.airbyte.workers.WorkerException: Tap process wasn't successful
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteSource.close(DefaultAirbyteSource.java:112) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
		at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:92) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
		at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:48) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:137) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:832) [?:?]
	Suppressed: java.io.IOException: Broken pipe
		at java.io.FileOutputStream.writeBytes(Native Method) ~[?:?]
		at java.io.FileOutputStream.write(FileOutputStream.java:347) ~[?:?]
		at java.io.BufferedOutputStream.write(BufferedOutputStream.java:123) ~[?:?]
		at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:242) ~[?:?]
		at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:321) ~[?:?]
		at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:325) ~[?:?]
		at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:159) ~[?:?]
		at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:251) ~[?:?]
		at java.io.BufferedWriter.flush(BufferedWriter.java:257) ~[?:?]
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.notifyEndOfStream(DefaultAirbyteDestination.java:89) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.close(DefaultAirbyteDestination.java:101) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
		at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:92) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
		at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:48) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:137) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:832) [?:?]
2021-04-15 00:55:55 INFO (/tmp/workspace/7/0) DefaultAirbyteDestination(cancel):120 - Cancelled destination process!
2021-04-15 00:55:55 INFO (/tmp/workspace/7/0) DefaultSyncWorker(cancel):163 - Cancelling normalization runner...
2021-04-15 00:55:55 INFO (/tmp/workspace/7/0) TemporalAttemptExecution(lambda$getCancellationChecker$3):155 - Interrupting worker thread...
2021-04-15 00:55:55 INFO (/tmp/workspace/7/0) TemporalAttemptExecution(lambda$getCancellationChecker$3):158 - Cancelling completable future...
2021-04-15 00:55:55 ERROR (/tmp/workspace/7/0) TemporalAttemptExecution(lambda$getCancellationChecker$4):164 - Cancellation checker exception
io.airbyte.workers.WorkerException: Worker cleaned up after exception
	at io.airbyte.workers.temporal.CancellationHandler$TemporalCancellationHandler.checkAndHandleCancellation(CancellationHandler.java:67) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getCancellationChecker$4(TemporalAttemptExecution.java:162) [io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: io.temporal.client.ActivityCanceledException: WorkflowId=a87bf3b2-f10e-4bc5-9276-c028f881799b, RunId=b40e1dea-9f57-4189-88c6-1f8e98a2eff3, ActivityType=Run, ActivityId=4b02e5cd-82b6-3dc1-9d0b-486a90ddd4c3
	at io.temporal.internal.sync.ActivityExecutionContextImpl.sendHeartbeatRequest(ActivityExecutionContextImpl.java:205) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.ActivityExecutionContextImpl.doHeartBeat(ActivityExecutionContextImpl.java:147) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.ActivityExecutionContextImpl.heartbeat(ActivityExecutionContextImpl.java:108) ~[temporal-sdk-1.0.4.jar:?]
	at io.airbyte.workers.temporal.CancellationHandler$TemporalCancellationHandler.checkAndHandleCancellation(CancellationHandler.java:64) ~[io.airbyte-airbyte-workers-0.20.0-alpha.jar:?]
	... 7 more
```

**Comment by davinchia** [comment]
I wrote up my notes here: 
https://docs.google.com/document/d/1wnrVuvZ0d93fA4Ds4iJVEguFn6QRt6EFDCLFlpoZs3g/edit?usp=sharing

After two days of profiling, I believe there is no memory leak, and this issue arose due to combination of lack of resource limits and bad timing.
