### ISSUE TITLE
Source Braintree:  pydantic.error_wrappers.ValidationError: 1 validation error for Transaction, custom_fields str type expected (type=type_error.str)

### ISSUE THREAD

**Issue by stufan** [airbytehq/airbyte#29692]
### Connector Name

destination-s3

### Connector Version

0.1.15

### What step the error happened?

None

### Revelant information

When sync is enabled an exception is thrown and the replication process is cancelled. Attached is the synchronization job log with the error.
[f460218f_41fb_4f15_8622_56e80d28d668_job_2_attempt_5_txt.txt](https://github.com/airbytehq/airbyte/files/12405655/f460218f_41fb_4f15_8622_56e80d28d668_job_2_attempt_5_txt.txt)

### Relevant log output

```shell
The excerpt from the log indicating the issue is as follow:

2023-08-22 06:23:37 source > 1 validation error for Transaction
custom_fields
  str type expected (type=type_error.str)
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module></module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 156, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 98, in run
    yield from map(AirbyteEntrypoint.airbyte_message_to_string, self.read(source_spec, config, config_catalog, state))
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 132, in read
    yield from self.source.read(self.logger, config, catalog, state)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 139, in read
    raise e
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 120, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 194, in _read_stream
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by topefolorunso** [comment]
Assign this to me @justinbchau
