### ISSUE TITLE
Zendesk Support - tickets stream failing for TypeError: '>' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by leozqin** [airbytehq/airbyte#29836]
### Connector Name

source-zendesk-support

### Connector Version

1.0.0

### What step the error happened?

During the sync

### Revelant information

Shortly after beginning to stream the tickets, the stream encountered an exception - `TypeError: '>' not supported between instances of 'NoneType' and 'int'`.

Previous syncs have succeeded without issue. This issue started around between 9am and 10am pacific time on Aug 24, 2023.

### Relevant log output

```shell
2023-08-25 14:13:03 source > Marking stream tickets as STARTED
2023-08-25 14:13:03 replication-orchestrator > Attempt 0 to stream status started null:tickets
2023-08-25 14:13:04 source > Syncing stream: tickets 
2023-08-25 14:13:04 source > Encountered an exception while reading stream tickets
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 122, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 197, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 266, in _read_incremental
    for message_counter, record_data_or_message in enumerate(records, start=1):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 450, in read_records
    yield from self._read_pages(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 466, in _read_pages
    request, response = self._fetch_next_page(stream_slice, stream_state, next_page_token)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 486, in _fetch_next_page
    params=self.request_params(stream_state=stream_state, stream_slice=stream_slice, next_page_token=next_page_token),
  File "/airbyte/integration_code/source_zendesk_support/streams.py", line 518, in request_params
    params = {"start_time": self.check_start_time_param(parsed_state)}
  File "/airbyte/integration_code/source_zendesk_support/streams.py", line 541, in check_start_time_param
    return super().check_start_time_param(requested_start_time, value=3)
  File "/airbyte/integration_code/source_zendesk_support/streams.py", line 341, in check_start_time_param
    return now if requested_start_time > now else requested_start_time
TypeError: '>' not supported between instances of 'NoneType' and 'int'
2023-08-25 14:13:04 source > Marking stream tickets as STOPPED
2023-08-25 14:13:04 replication-orchestrator > Attempt 0 to update stream status incomplete null:tickets
2023-08-25 14:13:04 source > Finished syncing tickets
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by leozqin** [comment]
This was due to a change in semantics in Zendesk Support - the instructions below are from an email that I guess I missed:

```
What is changing?

With the new version 1.0.0, the `cursor_field` for `Tickets` stream is changed to `generated_timestamp`. The reason is that the API compares the start_time with the ticket's generated_timestamp value, not updated_at value (see Zendesk API docs)

What action is needed from me?

After the release date:

- Navigate to you Zendesk Support connections
- Within your connection, under the Replication tab select the “Refresh your schema” button.
- Save changes.
- A pop-up will appear, keep the "Reset affected streams" selected.
- Select to save the connection - a new sync will be started

```
After doing this, syncs were able to resume.
