### ISSUE TITLE
Source S3: source instance profile 

### ISSUE THREAD

**Issue by asimabbas31** [airbytehq/airbyte#29843]
### Topic

S3 source instance profile 

### Revelant information

On K8s it is possible use the instance profile for bucket source connection ? . I am trying to add the new source connection with aws s3 and my nodes have s3 full access role assigned. On worker and server pods i can access the buckets without keys because of the role. But when i create the new source connection with S3 getting this error 

```
2023-08-25 15:55:07 INFO i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - Iterating S3 bucket 'auth-airbyte-test'
Log4j2Appender says: Traceback (most recent call last):
  File "/airbyte/integration_code/source_s3/stream.py", line 61, in filepath_iterator
    response = client.list_objects_v2(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/airbyte/integration_code/source_s3/source_files_abstract/source.py", line 63, in check_connection
    for file_info in stream.filepath_iterator():
  File "/airbyte/integration_code/source_s3/stream.py", line 65, in filepath_iterator
    raise AirbyteTracedException(message, message, failure_type=FailureType.config_error)
airbyte_cdk.utils.traced_exception.AirbyteTracedException: Access Denied

2023-08-25 15:55:07 ERROR i.a.w.i.VersionedAirbyteStreamFactory(internalLog):308 - Traceback (most recent call last):
  File "/airbyte/integration_code/source_s3/stream.py", line 61, in filepath_iterator
    response = client.list_objects_v2(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/airbyte/integration_code/source_s3/source_files_abstract/source.py", line 63, in check_connection
    for file_info in stream.filepath_iterator():
  File "/airbyte/integration_code/source_s3/stream.py", line 65, in filepath_iterator
    raise AirbyteTracedException(message, message, failure_type=FailureType.config_error)
airbyte_cdk.utils.traced_exception.AirbyteTracedException: Access Denied

Log4j2Appender says: Check failed

Publishing to S3 (bucket=airbyte-dev-logs; key=job-logging/workspace/a75a2833-88b8-48b9-966a-49c905a6bf7c/0/logs.log/20230825155603_airbyte-dl-worker-778494dbd-vf4hj_be57aeab801645b98972b4c21e400e44):
java.lang.RuntimeException: Cannot publish to S3: The Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: 177EAB65B653499F; S3 Extended Request ID: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8; Proxy: null)
        at com.van.logging.aws.S3PublishHelper.publishFile(S3PublishHelper.java:127)
        at com.van.logging.AbstractFilePublishHelper.end(AbstractFilePublishHelper.java:61)
        at com.van.logging.BufferPublisher.endPublish(BufferPublisher.java:66)
        at com.van.logging.LoggingEventCache.publishEventsFromFile(LoggingEventCache.java:201)
        at com.van.logging.LoggingEventCache.lambda$publishCache$0(LoggingEventCache.java:243)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: 177EAB65B653499F; S3 Extended Request ID: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8; Proxy: null), S3 Extended Request ID: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8
```

**Comment by mickutz** [comment]
having the same issue with airbyte running on ec2
the destination connector already has this implemented, source connector doesn't though

**Comment by midavadim** [comment]
Hi @mickutz @asimabbas31 

I have tried to reproduce the conditions you described.
I created EC2 instance, installed Airbyte, added role with access to s3 service.
And I was able to successfully sync from s3 without specifying S3 API key/secret.

Actually, I  don't know what I can suggest in this situation. Maybe there is still lack of permissions from your side.

**Comment by midavadim** [comment]
Closed, since there is no actions
