### ISSUE TITLE
[source-elasticsearch] Cannot map unsupported data type to Airbyte data type: percolator

### ISSUE THREAD

**Issue by fakhavan** [airbytehq/airbyte#29932]
### Connector Name

source-elasticsearch

### Connector Version

0.1.1

### What step the error happened?

Configuring a new connector

### Revelant information

When creating a new connection using Elasticsearch as source, it fails to fetch the schema of data source. 

### Relevant log output

```shell
Try again
Discovering schema failed
Something went wrong in the connector. See the logs for more details.


Learn more

Internal message: java.lang.RuntimeException: io.airbyte.integrations.source.elasticsearch.UnsupportedDatatypeException: Cannot map unsupported data type to Airbyte data type: percolator
Failure type: system_error
```

Stacktrace
```
java.lang.RuntimeException: io.airbyte.integrations.source.elasticsearch.UnsupportedDatatypeException: Cannot map unsupported data type to Airbyte data type: percolator
	at io.airbyte.integrations.source.elasticsearch.typemapper.ElasticsearchTypeMapper.lambda$formatJSONSchema$0(ElasticsearchTypeMapper.java:133)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at io.airbyte.integrations.source.elasticsearch.typemapper.ElasticsearchTypeMapper.formatJSONSchema(ElasticsearchTypeMapper.java:129)
	at io.airbyte.integrations.source.elasticsearch.typemapper.ElasticsearchTypeMapper.lambda$formatJSONSchema$0(ElasticsearchTypeMapper.java:131)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at io.airbyte.integrations.source.elasticsearch.typemapper.ElasticsearchTypeMapper.formatJSONSchema(ElasticsearchTypeMapper.java:129)
	at io.airbyte.integrations.source.elasticsearch.ElasticsearchSource.discover(ElasticsearchSource.java:75)
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:131)
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:100)
	at io.airbyte.integrations.source.elasticsearch.ElasticsearchSource.main(ElasticsearchSource.java:34)
Caused by: io.airbyte.integrations.source.elasticsearch.UnsupportedDatatypeException: Cannot map unsupported data type to Airbyte data type: percolator
	at io.airbyte.integrations.source.elasticsearch.typemapper.ElasticsearchTypeMapper.formatJSONSchema(ElasticsearchTypeMapper.java:127)
	at io.airbyte.integrations.source.elasticsearch.typemapper.ElasticsearchTypeMapper.lambda$formatJSONSchema$0(ElasticsearchTypeMapper.java:131)
	... 9 more
```

Logs
```
2023-08-29 06:12:49 INFO i.a.w.t.TemporalAttemptExecution(get):138 - Cloud storage job log path: /workspace/cf7db568-8ec9-4027-860f-274f89688260/0/logs.log
```
```


### Contribute

- [ ] Yes, I want to contribute

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
