### ISSUE TITLE
Postgres source connector lacking notice about `xmin` incremental being incompatible with views

### ISSUE THREAD

**Issue by gabrielalmeida** [airbytehq/airbyte#29988]
### Page URL

https://docs.airbyte.com/integrations/sources/postgres#xmin

### Description

Postgres source sync was failing with:

Failure reason: Something went wrong in the connector. See the logs for more details.
`java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: column "xmin" does not exist Position: 254`

<details>
<summary>Stack trace</summary>

```
2023-08-30 07:14:21 source > ERROR i.a.i.b.AirbyteExceptionHandler(uncaughtException):26 Something went wrong in the connector. See the logs for more details. java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: column "xmin" does not exist
  Position: 254
        at io.airbyte.db.jdbc.StreamingJdbcDatabase.unsafeQuery(StreamingJdbcDatabase.java:82) ~[io.airbyte.airbyte-db-db-lib-24.0.2.jar:?]
        at io.airbyte.integrations.source.postgres.xmin.PostgresXminHandler.lambda$queryTableXmin$1(PostgresXminHandler.java:120) ~[io.airbyte.airbyte-integrations.connectors-source-postgres-24.0.2.jar:?]
        at io.airbyte.commons.util.LazyAutoCloseableIterator.computeNext(LazyAutoCloseableIterator.java:41) ~[io.airbyte-airbyte-commons-24.0.2.jar:?]
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.1-jre.jar:?]
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.1-jre.jar:?]
        at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:46) ~[guava-31.1-jre.jar:?]
        at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:42) ~[io.airbyte-airbyte-commons-24.0.2.jar:?]
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.1-jre.jar:?]
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.1-jre.jar:?]
        at io.airbyte.integrations.source.postgres.xmin.XminStateIterator.computeNext(XminStateIterator.java:61) ~[io.airbyte.airbyte-integrations.connectors-source-postgres-24.0.2.jar:?]
        at io.airbyte.integrations.source.postgres.xmin.XminStateIterator.computeNext(XminStateIterator.java:16) ~[io.airbyte.airbyte-integrations.connectors-source-postgres-24.0.2.jar:?]
        at autovalue.shaded.com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[auto-value-1.10.1.jar:?]
        at autovalue.shaded.com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[auto-value-1.10.1.jar:?]
        at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:42) ~[io.airbyte-airbyte-commons-24.0.2.jar:?]
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.1-jre.jar:?]
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.1-jre.jar:?]
        at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:46) ~[guava-31.1-jre.jar:?]
        at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:42) ~[io.airbyte-airbyte-commons-24.0.2.jar:?]
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.1-jre.jar:?]
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.1-jre.jar:?]
        at io.airbyte.commons.util.CompositeIterator.computeNext(CompositeIterator.java:72) ~[io.airbyte-airbyte-commons-24.0.2.jar:?]
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.1-jre.jar:?]
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.1-jre.jar:?]
        at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:42) ~[io.airbyte-airbyte-commons-24.0.2.jar:?]
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.1-jre.jar:?]
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.1-jre.jar:?]
        at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:42) ~[io.airbyte-airbyte-commons-24.0.2.jar:?]
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.1-jre.jar:?]
```
</details>

Ref airbytehq/airbyte-internal-issues#2030

The Postgres source connector docs embedded on the Airbyte Open Source has no warnings about `xmin` not being compatible with views: 

![Screen Shot 2023-08-30 at 07 18 28](https://github.com/airbytehq/airbyte/assets/310382/c4d79e18-4c67-4e11-9119-576c2aaa15cf)

OTOH, the [Airbyte website docs](https://docs.airbyte.com/integrations/sources/postgres#xmin) clearly states that views are incompatible with `xmin`.

https://github.com/airbytehq/airbyte/blob/d0bc7ba9364adb1890ed2326baa2e428c5954211/docs/integrations/sources/postgres.md?plain=1#L191

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
