### ISSUE TITLE
Swallowed error at io.airbyte.persistence.job.errorreporter.JobErrorReporter.getFailureReasonMetadata

### ISSUE THREAD

**Issue by arthur-github-user** [airbytehq/airbyte#30095]
### Topic

Application error that prevents debugging

### What method are you using to run Airbyte?
Kubernetes, GKE, v1.24.14-gke.2700

### Platform Version or Helm Chart Version
0.48.4

### What step the error happened?
Adding first source after clean installation.

### Revelant information
Errors appear after trying to add a new Source, and the source can't be added. Running on a clean installation in k8s using Airbyte Helm release `0.48.4`.

### To reproduce:
Set up a new source -> File source (CSV, etc.) -> Add URL to a public csv -> click 'Test source'.
After a few seconds, UI shows `Internal error`. One of the errors from `airbyte-server` component that can be found is
`Cannot invoke "io.airbyte.config.Metadata.getAdditionalProperties()" because the return value of "io.airbyte.config.FailureReason.getMetadata()" is null`
This hides the actual error and prevents further debugging.

### Full traceback:
```
ERROR i.a.c.l.Exceptions(swallow):65 - Swallowed error.
java.lang.NullPointerException: Cannot invoke "io.airbyte.config.Metadata.getAdditionalProperties()" because the return value of "io.airbyte.config.FailureReason.getMetadata()" is null
	at io.airbyte.persistence.job.errorreporter.JobErrorReporter.getFailureReasonMetadata(JobErrorReporter.java:283) ~[io.airbyte.airbyte-persistence-job-persistence-0.50.24.jar:?]
	at io.airbyte.persistence.job.errorreporter.JobErrorReporter.reportJobFailureReason(JobErrorReporter.java:328) ~[io.airbyte.airbyte-persistence-job-persistence-0.50.24.jar:?]
	at io.airbyte.persistence.job.errorreporter.JobErrorReporter.reportSourceCheckJobFailure(JobErrorReporter.java:174) ~[io.airbyte.airbyte-persistence-job-persistence-0.50.24.jar:?]
	at io.airbyte.commons.server.scheduler.DefaultSynchronousSchedulerClient.lambda$reportError$4(DefaultSynchronousSchedulerClient.java:288) ~[io.airbyte-airbyte-commons-server-0.50.24.jar:?]
	at io.airbyte.commons.lang.Exceptions.swallow(Exceptions.java:63) ~[io.airbyte-airbyte-commons-0.50.24.jar:?]
	at io.airbyte.commons.server.scheduler.DefaultSynchronousSchedulerClient.reportError(DefaultSynchronousSchedulerClient.java:286) ~[io.airbyte-airbyte-commons-server-0.50.24.jar:?]
	at io.airbyte.commons.server.scheduler.DefaultSynchronousSchedulerClient.execute(DefaultSynchronousSchedulerClient.java:228) ~[io.airbyte-airbyte-commons-server-0.50.24.jar:?]
	at io.airbyte.commons.server.scheduler.DefaultSynchronousSchedulerClient.createSourceCheckConnectionJob(DefaultSynchronousSchedulerClient.java:106) ~[io.airbyte-airbyte-commons-server-0.50.24.jar:?]
	at io.airbyte.commons.server.handlers.SchedulerHandler.checkSourceConnectionFromSourceCreate(SchedulerHandler.java:282) ~[io.airbyte-airbyte-commons-server-0.50.24.jar:?]
	at io.airbyte.server.apis.SchedulerApiController.lambda$executeSourceCheckConnection$1(SchedulerApiController.java:48) ~[io.airbyte-airbyte-server-0.50.24.jar:?]
	at io.airbyte.server.apis.ApiHelper.execute(ApiHelper.java:26) ~[io.airbyte-airbyte-server-0.50.24.jar:?]
	at io.airbyte.server.apis.SchedulerApiController.executeSourceCheckConnection(SchedulerApiController.java:48) ~[io.airbyte-airbyte-server-0.50.24.jar:?]
	at io.airbyte.server.apis.$SchedulerApiController$Definition$Exec.dispatch(Unknown Source) ~[io.airbyte-airbyte-server-0.50.24.jar:?]
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303) ~[micronaut-router-3.10.1.jar:3.10.1]
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111) ~[micronaut-router-3.10.1.jar:3.10.1]
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103) ~[micronaut-http-3.10.1.jar:3.10.1]
	at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659) ~[micronaut-http-server-3.10.1.jar:3.10.1]
	at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49) ~[reactor-core-3.5.5.jar:3.5.5]
```

### Expected fix
Could you please add handling of this case [here](https://github.com/airbytehq/airbyte-platform/blob/f33758e1a25a17967780615167f3df335707a049/airbyte-persistence/job-persistence/src/main/java/io/airbyte/persistence/job/errorreporter/JobErrorReporter.java#L283) so that the actual error could propagate?

**Comment by ricardosouzamorais** [comment]
I am facing the same issue with Airbyte 0.50.31 running on kubernetes version v1.25.6.
Airbyte is using PostgreSQL 15.

**Comment by ricardosouzamorais** [comment]
@micgeronimo , are you using an external postgresql for config store and etc ?

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
