### ISSUE TITLE
[source-mysql] Error when reading table size causing syncs to fail

### ISSUE THREAD

**Issue by prateekmukhedkar** [airbytehq/airbyte#30363]
### Connector Name

source-mysql

### Connector Version

3.0.4

### What step the error happened?

During the sync

### Revelant information

https://cloud.airbyte.com/workspaces/b226d62a-38b8-4cfb-84d6-b03c654358d9/connections/a6804b51-08aa-4e79-a6c5-dcfd40d787cc/job-history#4583693::4

### Relevant log output

```shell
2023-09-11 14:44:24 source > ERROR i.a.i.b.s.SshWrappedSource(read):77 Exception occurred while getting the delegate read iterator, closing SSH tunnel java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.asLong()" because the return value of "com.fasterxml.jackson.databind.JsonNode.get(String)" is null
        at io.airbyte.integrations.source.mysql.MySqlQueryUtils.lambda$getTableSizeInfoForStreams$5(MySqlQueryUtils.java:119) ~[io.airbyte.airbyte-integrations.connectors-source-mysql-24.0.2.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at io.airbyte.integrations.source.mysql.MySqlQueryUtils.getTableSizeInfoForStreams(MySqlQueryUtils.java:111) ~[io.airbyte.airbyte-integrations.connectors-source-mysql-24.0.2.jar:?]
        at io.airbyte.integrations.source.mysql.initialsync.MySqlInitialReadUtil.getCdcReadIterators(MySqlInitialReadUtil.java:138) ~[io.airbyte.airbyte-integrations.connectors-source-mysql-24.0.2.jar:?]
        at io.airbyte.integrations.source.mysql.MySqlSource.getIncrementalIterators(MySqlSource.java:339) ~[io.airbyte.airbyte-integrations.connectors-source-mysql-24.0.2.jar:?]
        at io.airbyte.integrations.source.mysql.MySqlSource.getIncrementalIterators(MySqlSource.java:77) ~[io.airbyte.airbyte-integrations.connectors-source-mysql-24.0.2.jar:?]
        at io.airbyte.integrations.source.relationaldb.AbstractDbSource.read(AbstractDbSource.java:161) ~[io.airbyte.airbyte-integrations.connectors-source-relational-db-24.0.2.jar:?]
        at io.airbyte.integrations.base.ssh.SshWrappedSource.read(SshWrappedSource.java:75) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
        at io.airbyte.integrations.base.spec_modification.SpecModifyingSource.read(SpecModifyingSource.java:50) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
        at io.airbyte.integrations.base.IntegrationRunner.readSerial(IntegrationRunner.java:271) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
        at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:170) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
        at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:125) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
        at io.airbyte.integrations.source.mysql_strict_encrypt.MySqlStrictEncryptSource.main(MySqlStrictEncryptSource.java:79) ~[io.airbyte.airbyte-integrations.connectors-source-mysql-strict-encrypt-24.0.2.jar:?]
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by rodireich** [comment]
This is failing on a stream called `ExpiredCautionsView`, which by the name I guess is a view and not a table.
I don't think we try to sync views to begin with but maybe the bug is with how we handle this flow.
Trying to recreate with a View
