### ISSUE TITLE
Source MongoDB: Sync to Postgres fails with "Infinity not allowed in JSON"

### ISSUE THREAD

**Issue by gregsharples** [airbytehq/airbyte#3037]
## Expected Behavior
Mongo Source data should be sync'd to Postgres destination with successful handling on Infinity in the source Mongo collection data.  The Infinity values should be graciously handled (potentially with warning messages in the UI).

## Current Behavior
Sync fails with a "Infinity not allowed in JSON" error in the log:

`2021-04-21 07:56:00 ERROR (/tmp/workspace/21/2) LineGobbler(voidCall):69 - /usr/local/lib/ruby/3.0.0/json/common.rb:312:in `to_json': 1005: Infinity not allowed in JSON (JSON::GeneratorError)
2021-04-21 07:56:00 ERROR (/tmp/workspace/21/2) LineGobbler(voidCall):69 - from /usr/local/lib/ruby/3.0.0/json/common.rb:312:in `generate'
2021-04-21 07:56:00 ERROR (/tmp/workspace/21/2) LineGobbler(voidCall):69 - from /usr/local/lib/ruby/3.0.0/json/common.rb:312:in `generate'
2021-04-21 07:56:00 ERROR (/tmp/workspace/21/2) LineGobbler(voidCall):69 - from /airbyte/lib/airbyte_protocol.rb:369:in `to_json'
2021-04-21 07:56:00 ERROR (/tmp/workspace/21/2) LineGobbler(voidCall):69 - from /airbyte/lib/mongodb_reader.rb:57:in `block in read_configured_stream'
2021-04-21 07:56:00 ERROR (/tmp/workspace/21/2) LineGobbler(voidCall):69 - from /usr/local/bundle/gems/mongo-2.14.0/lib/mongo/collection/view/iterable.rb:66:in `block in each'
2021-04-21 07:56:00 ERROR (/tmp/workspace/21/2) LineGobbler(voidCall):69 - from /usr/local/bundle/gems/mongo-2.14.0/lib/mongo/cursor.rb:164:in `block in each'
2021-04-21 07:56:00 ERROR (/tmp/workspace/21/2) LineGobbler(voidCall):69 - from /usr/local/bundle/gems/mongo-2.14.0/lib/mongo/cursor.rb:162:in `loop'
2021-04-21 07:56:00 ERROR (/tmp/workspace/21/2) LineGobbler(voidCall):69 - from /usr/local/bundle/gems/mongo-2.14.0/lib/mongo/cursor.rb:162:in `each'
2021-04-21 07:56:00 ERROR (/tmp/workspace/21/2) LineGobbler(voidCall):69 - from /usr/local/bundle/gems/mongo-2.14.0/lib/mongo/collection/view/iterable.rb:65:in `each'
2021-04-21 07:56:00 ERROR (/tmp/workspace/21/2) LineGobbler(voidCall):69 - from /airbyte/lib/mongodb_reader.rb:41:in `read_configured_stream'
2021-04-21 07:56:00 ERROR (/tmp/workspace/21/2) LineGobbler(voidCall):69 - from /airbyte/lib/mongodb_reader.rb:25:in `block in read'
2021-04-21 07:56:00 ERROR (/tmp/workspace/21/2) LineGobbler(voidCall):69 - from /airbyte/lib/mongodb_reader.rb:19:in `each'
2021-04-21 07:56:00 ERROR (/tmp/workspace/21/2) LineGobbler(voidCall):69 - from /airbyte/lib/mongodb_reader.rb:19:in `read'
2021-04-21 07:56:00 ERROR (/tmp/workspace/21/2) LineGobbler(voidCall):69 - from /airbyte/lib/mongodb_source.rb:61:in `read'
2021-04-21 07:56:00 ERROR (/tmp/workspace/21/2) LineGobbler(voidCall):69 - from /airbyte/source.rb:16:in `public_send'
2021-04-21 07:56:00 ERROR (/tmp/workspace/21/2) LineGobbler(voidCall):69 - from /airbyte/source.rb:16:in `<main>'`

## Logs
[logs-21-2.txt](https://github.com/airbytehq/airbyte/files/6364614/logs-21-2.txt)

## Steps to Reproduce
1. Configure MongoDB source with an Infinity value in a source data connection
1. Configure postgres destination and create connection to source
1. After schema identification, sync the data, and the sync will fail with the above error.

## Severity of the bug for you
High

## Airbyte Version
0.20.0-alpha

## Connector Version (if applicable)
- MongoDB: 0.3.0
- Postgres 0.3.0

## Additional context
- docker-compose version 1.25.5
- Docker version 20.10.5
- Ubuntu 20.04.2 LTS

**Comment by sherifnada** [comment]
@gregsharples thanks for the very thorough report! looking at our backlog i'm currently anticipating a fix in about two weeks. Will update you here as we make progress. You're also welcome to contribute a fix if you'd like it sooner than that!

**Comment by gregsharples** [comment]
> @gregsharples thanks for the very thorough report! looking at our backlog i'm currently anticipating a fix in about two weeks. Will update you here as we make progress. You're also welcome to contribute a fix if you'd like it sooner than that!

Thanks @sherifnada.  I'll take a look but with my Ruby skills it might take me a lot more than a couple of weeks ;)

**Comment by grishick** [comment]
This needs to be re-tested (add integration test) after MongoDB source and Postgres destination are switched to V1 protocol.

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 365 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.
