### ISSUE TITLE
🐛 Cannot add custom connector definitions on airgapped Airbyte instance

### ISSUE THREAD

**Issue by StevenReitsma** [airbytehq/airbyte#30433]
### Description

**Situation**
We are running an airgapped (no internet access) Airbyte instance and want to add/update custom connector definitions. In this case a destination.

**Problem**
When trying to add or update a new connector definition, we encounter the following error:

```
{
    "message": "Internal Server Error: Failed to fetch connector registry entry for redacted/destination-foo:0.4.1",
    "exceptionClassName": "java.lang.RuntimeException",
    "exceptionStack": [
        "java.lang.RuntimeException: Failed to fetch connector registry entry for redacted/destination-foo:0.4.1,
        "\tat io.airbyte.config.specs.RemoteDefinitionsProvider.getConnectorRegistryEntryJson(RemoteDefinitionsProvider.java:188)",
        "\tat io.airbyte.config.specs.RemoteDefinitionsProvider.getDestinationDefinitionByVersion(RemoteDefinitionsProvider.java:122)",
        "\tat io.airbyte.config.persistence.ActorDefinitionVersionResolver.fetchRemoteActorDefinitionVersion(ActorDefinitionVersionResolver.java:84)",
        "\tat io.airbyte.config.persistence.ActorDefinitionVersionResolver.resolveVersionForTag(ActorDefinitionVersionResolver.java:59)",
        "\tat io.airbyte.commons.server.handlers.helpers.ActorDefinitionHandlerHelper.defaultDefinitionVersionFromUpdate(ActorDefinitionHandlerHelper.java:117)",
        "\tat io.airbyte.commons.server.handlers.DestinationDefinitionsHandler.updateDestinationDefinition(DestinationDefinitionsHandler.java:265)",
        "\tat io.airbyte.server.apis.DestinationDefinitionApiController.lambda$updateDestinationDefinition$9(DestinationDefinitionApiController.java:160)",
        "\tat io.airbyte.server.apis.ApiHelper.execute(ApiHelper.java:26)",
        "\tat io.airbyte.server.apis.DestinationDefinitionApiController.updateDestinationDefinition(DestinationDefinitionApiController.java:160)",
        "\tat io.airbyte.server.apis.$DestinationDefinitionApiController$Definition$Exec.dispatch(Unknown Source)",
        "\tat io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371)",
        "\tat io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594)",
        "\tat io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)",
        "\tat io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)",
        "\tat io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)",
        "\tat io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659)",
        "\tat reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)",
        "\tat reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)",
        "\tat reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)",
        "\tat io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62)",
        "\tat reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)",
        "\tat reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)",
        "\tat io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)",
        "\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)",
        "\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)",
        "\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)",
        "\tat java.base/java.lang.Thread.run(Thread.java:1589)",
        "Caused by: java.net.ConnectException",
        "\tat java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:846)",
        "\tat java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)",
        "\tat io.airbyte.config.specs.RemoteDefinitionsProvider.getConnectorRegistryEntryJson(RemoteDefinitionsProvider.java:177)",
        "\t... 26 more",
        "Caused by: java.net.ConnectException",
        "\tat java.net.http/jdk.internal.net.http.common.Utils.toConnectException(Utils.java:1045)",
        "\tat java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:224)",
        "\tat java.net.http/jdk.internal.net.http.AsyncSSLConnection.connectAsync(AsyncSSLConnection.java:56)",
        "\tat java.net.http/jdk.internal.net.http.Http2Connection.createAsync(Http2Connection.java:380)",
        "\tat java.net.http/jdk.internal.net.http.Http2ClientImpl.getConnectionFor(Http2ClientImpl.java:128)",
        "\tat java.net.http/jdk.internal.net.http.ExchangeImpl.get(ExchangeImpl.java:94)",
        "\tat java.net.http/jdk.internal.net.http.Exchange.establishExchange(Exchange.java:368)",
        "\tat java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl0(Exchange.java:500)",
        "\tat java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl(Exchange.java:405)",
        "\tat java.net.http/jdk.internal.net.http.Exchange.responseAsync(Exchange.java:397)",
        "\tat java.net.http/jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:409)",
        "\tat java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:450)",
        "\tat java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)",
        "\tat java.base/java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:950)",
        "\tat java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2372)",
        "\tat java.net.http/jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:440)",
        "\tat java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(MultiExchange.java:342)",
        "\tat java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)",
        "\tat java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)",
        "\tat java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)",
        "\tat java.net.http/jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:172)",
        "\tat java.base/java.util.concurrent.CompletableFuture.completeAsync(CompletableFuture.java:2719)",
        "\tat java.net.http/jdk.internal.net.http.MultiExchange.responseAsync(MultiExchange.java:295)",
        "\tat java.net.http/jdk.internal.net.http.HttpClientImpl.sendAsync(HttpClientImpl.java:931)",
        "\tat java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:825)",
        "\t... 28 more",
        "Caused by: java.nio.channels.UnresolvedAddressException",
        "\tat java.base/sun.nio.ch.Net.checkAddress(Net.java:149)",
        "\tat java.base/sun.nio.ch.Net.checkAddress(Net.java:157)",
        "\tat java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:842)",
        "\tat java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:865)",
        "\tat java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(PlainHttpConnection.java:208)",
        "\tat java.base/java.security.AccessController.doPrivileged(AccessController.java:569)",
        "\tat java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:210)",
        "\t... 51 more"
    ],
    "rootCauseExceptionClassName": "java.lang.Class",
    "rootCauseExceptionStack": [
        "java.net.ConnectException",
        "\tat java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:846)",
        "\tat java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)",
        "\tat io.airbyte.config.specs.RemoteDefinitionsProvider.getConnectorRegistryEntryJson(RemoteDefinitionsProvider.java:177)",
        "\tat io.airbyte.config.specs.RemoteDefinitionsProvider.getDestinationDefinitionByVersion(RemoteDefinitionsProvider.java:122)",
        "\tat io.airbyte.config.persistence.ActorDefinitionVersionResolver.fetchRemoteActorDefinitionVersion(ActorDefinitionVersionResolver.java:84)",
        "\tat io.airbyte.config.persistence.ActorDefinitionVersionResolver.resolveVersionForTag(ActorDefinitionVersionResolver.java:59)",
        "\tat io.airbyte.commons.server.handlers.helpers.ActorDefinitionHandlerHelper.defaultDefinitionVersionFromUpdate(ActorDefinitionHandlerHelper.java:117)",
        "\tat io.airbyte.commons.server.handlers.DestinationDefinitionsHandler.updateDestinationDefinition(DestinationDefinitionsHandler.java:265)",
        "\tat io.airbyte.server.apis.DestinationDefinitionApiController.lambda$updateDestinationDefinition$9(DestinationDefinitionApiController.java:160)",
        "\tat io.airbyte.server.apis.ApiHelper.execute(ApiHelper.java:26)",
        "\tat io.airbyte.server.apis.DestinationDefinitionApiController.updateDestinationDefinition(DestinationDefinitionApiController.java:160)",
        "\tat io.airbyte.server.apis.$DestinationDefinitionApiController$Definition$Exec.dispatch(Unknown Source)",
        "\tat io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371)",
        "\tat io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594)",
        "\tat io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)",
        "\tat io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)",
        "\tat io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)",
        "\tat io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659)",
        "\tat reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)",
        "\tat reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)",
        "\tat reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)",
        "\tat io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62)",
        "\tat reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)",
        "\tat reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)",
        "\tat io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)",
        "\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)",
        "\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)",
        "\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)",
        "\tat java.base/java.lang.Thread.run(Thread.java:1589)",
        "Caused by: java.net.ConnectException",
        "\tat java.net.http/jdk.internal.net.http.common.Utils.toConnectException(Utils.java:1045)",
        "\tat java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:224)",
        "\tat java.net.http/jdk.internal.net.http.AsyncSSLConnection.connectAsync(AsyncSSLConnection.java:56)",
        "\tat java.net.http/jdk.internal.net.http.Http2Connection.createAsync(Http2Connection.java:380)",
        "\tat java.net.http/jdk.internal.net.http.Http2ClientImpl.getConnectionFor(Http2ClientImpl.java:128)",
        "\tat java.net.http/jdk.internal.net.http.ExchangeImpl.get(ExchangeImpl.java:94)",
        "\tat java.net.http/jdk.internal.net.http.Exchange.establishExchange(Exchange.java:368)",
        "\tat java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl0(Exchange.java:500)",
        "\tat java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl(Exchange.java:405)",
        "\tat java.net.http/jdk.internal.net.http.Exchange.responseAsync(Exchange.java:397)",
        "\tat java.net.http/jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:409)",
        "\tat java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:450)",
        "\tat java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)",
        "\tat java.base/java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:950)",
        "\tat java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2372)",
        "\tat java.net.http/jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:440)",
        "\tat java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(MultiExchange.java:342)",
        "\tat java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)",
        "\tat java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)",
        "\tat java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)",
        "\tat java.net.http/jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:172)",
        "\tat java.base/java.util.concurrent.CompletableFuture.completeAsync(CompletableFuture.java:2719)",
        "\tat java.net.http/jdk.internal.net.http.MultiExchange.responseAsync(MultiExchange.java:295)",
        "\tat java.net.http/jdk.internal.net.http.HttpClientImpl.sendAsync(HttpClientImpl.java:931)",
        "\tat java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:825)",
        "\t... 28 more",
        "Caused by: java.nio.channels.UnresolvedAddressException",
        "\tat java.base/sun.nio.ch.Net.checkAddress(Net.java:149)",
        "\tat java.base/sun.nio.ch.Net.checkAddress(Net.java:157)",
        "\tat java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:842)",
        "\tat java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:865)",
        "\tat java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(PlainHttpConnection.java:208)",
        "\tat java.base/java.security.AccessController.doPrivileged(AccessController.java:569)",
        "\tat java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:210)",
        "\t... 51 more"
    ]
}
```

This is caused by following line of code: https://github.com/airbytehq/airbyte-platform/blob/main/airbyte-config/specs/src/main/java/io/airbyte/config/specs/RemoteDefinitionsProvider.java#L194
When no connection can be made to the internet, Airbyte throws an error.

**Solution**
Instead of throwing an error, this function should just return `Optional.empty()` and issue a warning.

**Comment by StevenReitsma** [comment]
@pedroslopez

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.

**Comment by tamilselvan-stratforge** [comment]
Still facing the same issue, when upgrading Airbyte version in an airgapped environment! 

Steps to reproduce: Using an Airbyte older version for eg in my scenario was using V0.58.0 create few connection like source: postgres and destination: clickhouse lets say.

Now I tried to upgrade to V0.63.15, The bootloader existed with code 255, with the below error

1. Failed to fetch remote platform compatibility file.
2. Caused by: java.net.UnknownHostException: connectors.airbyte.com - Trying to connect to airbyte
3. Failed to fetch connector registry entry for airbyte/source-postgres:3.3.29

`2024-08-19 08:10:04 ERROR i.a.c.i.AirbyteCompatibleConnectorVersionsProvider(getCompatibleConnectorsMatrix):60 - **Failed to fetch remote platform compatibility file.**
2024-08-19 13:40:04 dev.failsafe.FailsafeException: java.net.UnknownHostException: connectors.airbyte.com
2024-08-19 13:40:04     at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:196) ~[failsafe-3.3.2.jar:3.3.2]
2024-08-19 13:40:04     at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376) ~[failsafe-3.3.2.jar:3.3.2]
2024-08-19 13:40:04     at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112) ~[failsafe-3.3.2.jar:3.3.2]
2024-08-19 13:40:04     at io.airbyte.config.init.AirbyteCompatibleConnectorVersionsProvider.getCompatibleConnectorsMatrix(AirbyteCompatibleConnectorVersionsProvider.kt:47) ~[io.airbyte.airbyte-config-init-0.63.15.jar:?]
2024-08-19 13:40:04     at io.airbyte.config.init.$AirbyteCompatibleConnectorVersionsProvider$Definition$Intercepted.$$access$$getCompatibleConnectorsMatrix(Unknown Source) ~[io.airbyte.airbyte-config-init-0.63.15.jar:?]
2024-08-19 13:40:04     at io.airbyte.config.init.$AirbyteCompatibleConnectorVersionsProvider$Definition$Exec.dispatch(Unknown Source) ~[io.airbyte.airbyte-config-init-0.63.15.jar:?]
2024-08-19 13:40:04     at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:456) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-19 13:40:04     at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:129) ~[micronaut-aop-4.5.4.jar:4.5.4]
2024-08-19 13:40:04     at io.micronaut.cache.interceptor.CacheInterceptor.doContextProceed(CacheInterceptor.java:753) ~[micronaut-cache-core-4.3.0.jar:4.3.0]
2024-08-19 13:40:04     at io.micronaut.cache.interceptor.CacheInterceptor.doProceed(CacheInterceptor.java:757) ~[micronaut-cache-core-4.3.0.jar:4.3.0]
2024-08-19 13:40:04     at io.micronaut.cache.interceptor.CacheInterceptor.interceptSync(CacheInterceptor.java:435) ~[micronaut-cache-core-4.3.0.jar:4.3.0]
2024-08-19 13:40:04     at io.micronaut.cache.interceptor.CacheInterceptor.intercept(CacheInterceptor.java:161) ~[micronaut-cache-core-4.3.0.jar:4.3.0]
2024-08-19 13:40:04     at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:138) ~[micronaut-aop-4.5.4.jar:4.5.4]
2024-08-19 13:40:04     at io.airbyte.config.init.$AirbyteCompatibleConnectorVersionsProvider$Definition$Intercepted.getCompatibleConnectorsMatrix(Unknown Source) ~[io.airbyte.airbyte-config-init-0.63.15.jar:?]
2024-08-19 13:40:04     at io.airbyte.config.init.RealAirbyteCompatibleConnectorsValidator.validate(AirbyteCompatibleConnectorsValidator.kt:59) ~[io.airbyte.airbyte-config-init-0.63.15.jar:?]
2024-08-19 13:40:04     at io.airbyte.config.init.ApplyDefinitionsHelper$filterOutIncompatibleSourceDefsWithCurrentAirbyteVersion$1.invoke(ApplyDefinitionsHelper.kt:333) ~[io.airbyte.airbyte-config-init-0.63.15.jar:?]
2024-08-19 13:40:04     at io.airbyte.config.init.ApplyDefinitionsHelper$filterOutIncompatibleSourceDefsWithCurrentAirbyteVersion$1.invoke(ApplyDefinitionsHelper.kt:332) ~[io.airbyte.airbyte-config-init-0.63.15.jar:?]
2024-08-19 13:40:04     at io.airbyte.config.init.ApplyDefinitionsHelper.filterOutIncompatibleSourceDefsWithCurrentAirbyteVersion$lambda$4(ApplyDefinitionsHelper.kt:332) ~[io.airbyte.airbyte-config-init-0.63.15.jar:?]
2024-08-19 13:40:04     at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) [?:?]
2024-08-19 13:40:04     at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722) [?:?]
2024-08-19 13:40:04     at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) [?:?]
2024-08-19 13:40:04     at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) [?:?]
2024-08-19 13:40:04     at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) [?:?]
2024-08-19 13:40:04     at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) [?:?]
2024-08-19 13:40:04     at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) [?:?]
2024-08-19 13:40:04     at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) [?:?]
2024-08-19 13:40:04     at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) [?:?]
2024-08-19 13:40:04     at io.airbyte.config.init.ApplyDefinitionsHelper.filterOutIncompatibleSourceDefsWithCurrentAirbyteVersion(ApplyDefinitionsHelper.kt:339) [io.airbyte.airbyte-config-init-0.63.15.jar:?]
2024-08-19 13:40:04     at io.airbyte.config.init.ApplyDefinitionsHelper.apply(ApplyDefinitionsHelper.kt:89) [io.airbyte.airbyte-config-init-0.63.15.jar:?]
2024-08-19 13:40:04     at io.airbyte.bootloader.DefaultPostLoadExecutor.execute(DefaultPostLoadExecutor.java:45) [io.airbyte-airbyte-bootloader-0.63.15.jar:?]
2024-08-19 13:40:04     at io.airbyte.bootloader.Bootloader.load(Bootloader.java:134) [io.airbyte-airbyte-bootloader-0.63.15.jar:?]
2024-08-19 13:40:04     at io.airbyte.bootloader.Application.main(Application.java:22) [io.airbyte-airbyte-bootloader-0.63.15.jar:?]
2024-08-19 13:40:04 Caused by: java.net.UnknownHostException: connectors.airbyte.com
2024-08-19 13:40:04     at java.base/java.net.InetAddress$CachedLookup.get(InetAddress.java:988) ~[?:?]
2024-08-19 13:40:04     at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1818) ~[?:?]
2024-08-19 13:40:04     at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1688) ~[?:?]
2024-08-19 13:40:04     at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:169) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:131) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:73) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at io.airbyte.config.init.AirbyteCompatibleConnectorVersionsProvider$getCompatibleConnectorsMatrix$responseSupplier$1.invoke(AirbyteCompatibleConnectorVersionsProvider.kt:46) ~[io.airbyte.airbyte-config-init-0.63.15.jar:?]
2024-08-19 13:40:04     at io.airbyte.config.init.AirbyteCompatibleConnectorVersionsProvider$getCompatibleConnectorsMatrix$responseSupplier$1.invoke(AirbyteCompatibleConnectorVersionsProvider.kt:46) ~[io.airbyte.airbyte-config-init-0.63.15.jar:?]
2024-08-19 13:40:04     at io.airbyte.config.init.AirbyteCompatibleConnectorVersionsProvider.getCompatibleConnectorsMatrix$lambda$0(AirbyteCompatibleConnectorVersionsProvider.kt:47) ~[io.airbyte.airbyte-config-init-0.63.15.jar:?]
2024-08-19 13:40:04     at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243) ~[failsafe-3.3.2.jar:3.3.2]
2024-08-19 13:40:04     at dev.failsafe.Functions.lambda$get$0(Functions.java:46) ~[failsafe-3.3.2.jar:3.3.2]
2024-08-19 13:40:04     at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74) ~[failsafe-3.3.2.jar:3.3.2]
2024-08-19 13:40:04     at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187) ~[failsafe-3.3.2.jar:3.3.2]
2024-08-19 13:40:04     ... 31 more
2024-08-19 13:40:05 2024-08-19 08:10:05 WARN i.m.s.r.u.Loggers$Slf4JLogger(warn):299 - [8a8a5904, L:/127.0.0.1:38285 - R:localhost/127.0.0.1:8125] An exception has been observed post termination, use DEBUG level to see the full stack: java.net.PortUnreachableException: recvAddress(..) failed: Connection refused
2024-08-19 13:40:05 2024-08-19 08:10:05 WARN i.m.s.r.u.Loggers$Slf4JLogger(warn):299 - [8a8a5904, L:/127.0.0.1:38285 - R:localhost/127.0.0.1:8125] An exception has been observed post termination, use DEBUG level to see the full stack: java.net.PortUnreachableException: recvAddress(..) failed: Connection refused
2024-08-19 13:40:05 2024-08-19 08:10:05 WARN i.m.s.r.u.Loggers$Slf4JLogger(warn):299 - [8a8a5904, L:/127.0.0.1:38285 - R:localhost/127.0.0.1:8125] An exception has been observed post termination, use DEBUG level to see the full stack: java.net.PortUnreachableException: recvAddress(..) failed: Connection refused
2024-08-19 13:40:05 2024-08-19 08:10:05 WARN i.m.s.r.u.Loggers$Slf4JLogger(warn):299 - [8a8a5904, L:/127.0.0.1:38285 - R:localhost/127.0.0.1:8125] An exception has been observed post termination, use DEBUG level to see the full stack: java.net.PortUnreachableException: recvAddress(..) failed: Connection refused
2024-08-19 13:40:05 2024-08-19 08:10:05 WARN i.m.s.r.u.Loggers$Slf4JLogger(warn):299 - [8a8a5904, L:/127.0.0.1:38285 - R:localhost/127.0.0.1:8125] An exception has been observed post termination, use DEBUG level to see the full stack: java.net.PortUnreachableException: recvAddress(..) failed: Connection refused
2024-08-19 13:40:05 2024-08-19 08:10:05 INFO i.a.c.i.ApplyDefinitionsHelper(applySourceDefinition):165 - Refreshing default version metadata for connector airbyte/source-postgres:3.3.29
2024-08-19 13:40:05 2024-08-19 08:10:05 WARN i.m.s.r.u.Loggers$Slf4JLogger(warn):299 - [8a8a5904, L:/127.0.0.1:38285 - R:localhost/127.0.0.1:8125] An exception has been observed post termination, use DEBUG level to see the full stack: java.net.PortUnreachableException: recvAddress(..) failed: Connection refused
2024-08-19 13:40:05 2024-08-19 08:10:05 ERROR i.a.b.Application(main):25 - Unable to bootstrap Airbyte environment.
2024-08-19 13:40:05 java.lang.RuntimeException: **Failed to fetch connector registry entry for airbyte/source-postgres:3.3.29**
2024-08-19 13:40:05     at io.airbyte.config.specs.RemoteDefinitionsProvider.getConnectorRegistryEntryJson(RemoteDefinitionsProvider.java:224) ~[io.airbyte.airbyte-config-specs-0.63.15.jar:?]
2024-08-19 13:40:05     at io.airbyte.config.specs.RemoteDefinitionsProvider.getSourceDefinitionByVersion(RemoteDefinitionsProvider.java:114) ~[io.airbyte.airbyte-config-specs-0.63.15.jar:?]
2024-08-19 13:40:05     at io.airbyte.config.persistence.ActorDefinitionVersionResolver.fetchRemoteActorDefinitionVersion(ActorDefinitionVersionResolver.java:79) ~[io.airbyte.airbyte-config-config-persistence-0.63.15.jar:?]
2024-08-19 13:40:05     at io.airbyte.config.init.ApplyDefinitionsHelper.applySourceDefinition(ApplyDefinitionsHelper.kt:168) ~[io.airbyte.airbyte-config-init-0.63.15.jar:?]
2024-08-19 13:40:05     at io.airbyte.config.init.ApplyDefinitionsHelper.apply(ApplyDefinitionsHelper.kt:99) ~[io.airbyte.airbyte-config-init-0.63.15.jar:?]
2024-08-19 13:40:05     at io.airbyte.bootloader.DefaultPostLoadExecutor.execute(DefaultPostLoadExecutor.java:45) ~[io.airbyte-airbyte-bootloader-0.63.15.jar:?]
2024-08-19 13:40:05     at io.airbyte.bootloader.Bootloader.load(Bootloader.java:134) ~[io.airbyte-airbyte-bootloader-0.63.15.jar:?]
2024-08-19 13:40:05     at io.airbyte.bootloader.Application.main(Application.java:22) [io.airbyte-airbyte-bootloader-0.63.15.jar:?]`

Expected Result: Airbyte should look if the local images exist first, if exist use the same.
