### ISSUE TITLE
[source-MSSQL] Connector exits with error when I try to sync a table with sync mode: intremental + append

### ISSUE THREAD

**Issue by deepak-deepmeta** [airbytehq/airbyte#30470]
### Connector Name

source-mssql

### Connector Version

2.0.1

### What step the error happened?

During the sync

### Revelant information

I am syncing a MSSQL source with a Postgres destination. The table that I want to sync do not have a primay key, though the tables have datetime2 fields which can be used as cursor. When I sync with the sync mode: full-refresh + override, the syncs are happening without any issue, but when I use sync mode: incremental + append, the sync is exiting with the following error message:

`Stack Trace: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near the keyword 'EXISTS'`

The full log of the exception is attached.

### Relevant log output

```shell
Stack Trace: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near the keyword 'EXISTS'.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1676)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:907)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:802)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7730)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3786)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:268)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:242)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeQuery(SQLServerStatement.java:724)
        at com.zaxxer.hikari.pool.ProxyStatement.executeQuery(ProxyStatement.java:110)
        at com.zaxxer.hikari.pool.HikariProxyStatement.executeQuery(HikariProxyStatement.java)
        at io.airbyte.integrations.source.mssql.MssqlSource.lambda$verifyCursorColumnValues$9(MssqlSource.java:301)
        at io.airbyte.db.jdbc.DefaultJdbcDatabase.bufferedResultSetQuery(DefaultJdbcDatabase.java:55)
        at io.airbyte.integrations.source.mssql.MssqlSource.verifyCursorColumnValues(MssqlSource.java:301)
        at io.airbyte.integrations.source.mssql.MssqlSource.verifyCursorColumnValues(MssqlSource.java:70)
        at io.airbyte.integrations.source.relationaldb.AbstractDbSource.validateCursorFieldForIncrementalTables(AbstractDbSource.java:216)
        at io.airbyte.integrations.source.relationaldb.AbstractDbSource.read(AbstractDbSource.java:156)
        at io.airbyte.integrations.base.ssh.SshWrappedSource.read(SshWrappedSource.java:75)
        at io.airbyte.integrations.base.IntegrationRunner.readSerial(IntegrationRunner.java:269)
        at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:168)
        at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:123)
        at io.airbyte.integrations.source.mssql.MssqlSource.main(MssqlSource.java:570)
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by evantahler** [comment]
Since this issue was written, we've dramatically revamped the connector.  Please try your sync again with the latest connectors and platform!
