### ISSUE TITLE
Redshift Source connector unable to load schema

### ISSUE THREAD

**Issue by corbin-Tprime** [airbytehq/airbyte#30497]
### Connector Name

redshift-source

### Connector Version

0.4.0

### What step the error happened?

Other

### Revelant information

Airbyte Version: `0.5.29`

When trying to setup a new connection or refresh the schema of a current connection, a 504 error is propagated. This error occurs when connecting a redshift source to any destination type.  The only fix we found was to revert our upgrade from version `0.5.29 -> 0.5.12` 

### Relevant log output

```shell
2023-09-15 17:53:52 ERROR i.a.a.c.AirbyteApiClient(retryWithJitter):233 - retryWithJitter caught and ignoring exception:
call to write discover schema result: java.io.IOException: HTTP/1.1 header parser received no bytes
io.airbyte.api.client.invoker.generated.ApiException: java.io.IOException: HTTP/1.1 header parser received no bytes
	at io.airbyte.api.client.generated.SourceApi.writeDiscoverCatalogResultWithHttpInfo(SourceApi.java:1315) ~[io.airbyte-airbyte-api-0.50.29.jar:?]
	at io.airbyte.api.client.generated.SourceApi.writeDiscoverCatalogResult(SourceApi.java:1282) ~[io.airbyte-airbyte-api-0.50.29.jar:?]
	at io.airbyte.workers.general.DefaultDiscoverCatalogWorker.lambda$run$0(DefaultDiscoverCatalogWorker.java:111) ~[io.airbyte-airbyte-commons-worker-0.50.29.jar:?]
	at io.airbyte.api.client.AirbyteApiClient.retryWithJitterThrows(AirbyteApiClient.java:291) ~[io.airbyte-airbyte-api-0.50.29.jar:?]
	at io.airbyte.api.client.AirbyteApiClient.retryWithJitter(AirbyteApiClient.java:231) ~[io.airbyte-airbyte-api-0.50.29.jar:?]
	at io.airbyte.api.client.AirbyteApiClient.retryWithJitter(AirbyteApiClient.java:199) ~[io.airbyte-airbyte-api-0.50.29.jar:?]
	at io.airbyte.workers.general.DefaultDiscoverCatalogWorker.run(DefaultDiscoverCatalogWorker.java:110) ~[io.airbyte-airbyte-commons-worker-0.50.29.jar:?]
	at io.airbyte.workers.general.DefaultDiscoverCatalogWorker.run(DefaultDiscoverCatalogWorker.java:48) ~[io.airbyte-airbyte-commons-worker-0.50.29.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:135) ~[io.airbyte-airbyte-workers-0.50.29.jar:?]
	at io.airbyte.workers.temporal.discover.catalog.DiscoverCatalogActivityImpl.lambda$run$1(DiscoverCatalogActivityImpl.java:140) ~[io.airbyte-airbyte-workers-0.50.29.jar:?]
	at io.airbyte.commons.temporal.TemporalUtils.withBackgroundHeartbeat(TemporalUtils.java:314) ~[io.airbyte-airbyte-commons-temporal-0.50.29.jar:?]
	at io.airbyte.workers.temporal.discover.catalog.DiscoverCatalogActivityImpl.run(DiscoverCatalogActivityImpl.java:125) ~[io.airbyte-airbyte-workers-0.50.29.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at io.temporal.internal.activity.RootActivityInboundCallsInterceptor$POJOActivityInboundCallsInterceptor.executeActivity(RootActivityInboundCallsInterceptor.java:64) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.activity.RootActivityInboundCallsInterceptor.execute(RootActivityInboundCallsInterceptor.java:43) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.activity.ActivityTaskExecutors$BaseActivityTaskExecutor.execute(ActivityTaskExecutors.java:95) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.activity.ActivityTaskHandlerImpl.handle(ActivityTaskHandlerImpl.java:92) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handleActivity(ActivityWorker.java:241) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:206) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:179) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93) ~[temporal-sdk-1.17.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.io.IOException: HTTP/1.1 header parser received no bytes
	at jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:857) ~[java.net.http:?]
	at jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123) ~[java.net.http:?]
	at io.airbyte.api.client.generated.SourceApi.writeDiscoverCatalogResultWithHttpInfo(SourceApi.java:1296) ~[io.airbyte-airbyte-api-0.50.29.jar:?]
	... 24 more
Caused by: java.io.IOException: HTTP/1.1 header parser received no bytes
	at jdk.internal.net.http.common.Utils.wrapWithExtraDetail(Utils.java:348) ~[java.net.http:?]
	at jdk.internal.net.http.Http1Response$HeadersReader.onReadError(Http1Response.java:565) ~[java.net.http:?]
	at jdk.internal.net.http.Http1AsyncReceiver.checkForErrors(Http1AsyncReceiver.java:302) ~[java.net.http:?]
	at jdk.internal.net.http.Http1AsyncReceiver.flush(Http1AsyncReceiver.java:268) ~[java.net.http:?]
	at jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:205) ~[java.net.http:?]
	at jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149) ~[java.net.http:?]
	at jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:230) ~[java.net.http:?]
	... 3 more
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method) ~[?:?]
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:66) ~[?:?]
	at sun.nio.ch.IOUtil.write(IOUtil.java:226) ~[?:?]
	at sun.nio.ch.IOUtil.write(IOUtil.java:157) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:574) ~[?:?]
	at java.nio.channels.SocketChannel.write(SocketChannel.java:642) ~[?:?]
	at jdk.internal.net.http.SocketTube.writeAvailable(SocketTube.java:1244) ~[java.net.http:?]
	at jdk.internal.net.http.SocketTube$InternalWriteSubscriber.tryFlushCurrent(SocketTube.java:354) ~[java.net.http:?]
	at jdk.internal.net.http.SocketTube$InternalWriteSubscriber.onNext(SocketTube.java:317) ~[java.net.http:?]
	at jdk.internal.net.http.SocketTube.onNext(SocketTube.java:135) ~[java.net.http:?]
	at jdk.internal.net.http.SocketTube.onNext(SocketTube.java:58) ~[java.net.http:?]
	at jdk.internal.net.http.Http1Exchange$Http1Publisher$WriteTask.run(Http1Exchange.java:817) ~[java.net.http:?]
	at jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:205) ~[java.net.http:?]
	at jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149) ~[java.net.http:?]
	at jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:230) ~[java.net.http:?]
	at jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:172) ~[java.net.http:?]
	at jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:305) ~[java.net.http:?]
	at jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:274) ~[java.net.http:?]
	at jdk.internal.net.http.Http1Exchange$Http1Publisher$Http1WriteSubscription.request(Http1Exchange.java:833) ~[java.net.http:?]
	at jdk.internal.net.http.SocketTube$InternalWriteSubscriber$WriteSubscription.requestMore(SocketTube.java:519) ~[java.net.http:?]
	at jdk.internal.net.http.SocketTube$InternalWriteSubscriber.requestMore(SocketTube.java:404) ~[java.net.http:?]
	... 3 more
```
```


### Contribute

- [ ] Yes, I want to contribute

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 365 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.
