### ISSUE TITLE
java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: Parameters were not supplied for the function

### ISSUE THREAD

**Issue by damiencamilleri** [airbytehq/airbyte#30519]
### Connector Name

source-mssqlserver

### Connector Version

2.0.1

### What step the error happened?

During the sync

### Revelant information

I get this on tables with full load. How do I fix it?

java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: Parameters were not supplied for the function

### Relevant log output

```shell
Stack Trace: java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: Parameters were not supplied for the function 'dbo.INCIDENTMONTHS'.
        at io.airbyte.db.jdbc.StreamingJdbcDatabase.unsafeQuery(StreamingJdbcDatabase.java:82)
        at io.airbyte.db.jdbc.JdbcDatabase.queryMetadata(JdbcDatabase.java:219)
        at io.airbyte.integrations.source.mssql.MssqlSource.getWrappedColumnNames(MssqlSource.java:148)
        at io.airbyte.integrations.source.mssql.MssqlSource.queryTableFullRefresh(MssqlSource.java:120)
        at io.airbyte.integrations.source.mssql.MssqlSource.queryTableFullRefresh(MssqlSource.java:70)
        at io.airbyte.integrations.source.relationaldb.AbstractDbSource.getFullRefreshStream(AbstractDbSource.java:488)
        at io.airbyte.integrations.source.relationaldb.AbstractDbSource.createReadIterator(AbstractDbSource.java:404)
        at io.airbyte.integrations.source.relationaldb.AbstractDbSource.getSelectedIterators(AbstractDbSource.java:326)
        at io.airbyte.integrations.source.relationaldb.AbstractDbSource.getFullRefreshIterators(AbstractDbSource.java:270)
        at io.airbyte.integrations.source.relationaldb.AbstractDbSource.read(AbstractDbSource.java:164)
        at io.airbyte.integrations.base.ssh.SshWrappedSource.read(SshWrappedSource.java:75)
        at io.airbyte.integrations.base.IntegrationRunner.readSerial(IntegrationRunner.java:269)
        at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:168)
        at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:123)
        at io.airbyte.integrations.source.mssql.MssqlSource.main(MssqlSource.java:570)
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by evantahler** [comment]
Since this issue was written, we've dramatically revamped the connector.  Please try your sync again with the latest connectors and platform!
