### ISSUE TITLE
source-mysql: error saving state to airbyte db

### ISSUE THREAD

**Issue by dimoschi** [airbytehq/airbyte#30524]
### Connector Name

source-mysql

### Connector Version

3.0.7

### What step the error happened?

During the sync

### Revelant information

The sync goes through and we have two issues:
1. Not all records are synced to the destination, Snowflake 3.0.3
2. The state cannot be saved to the Airbyte DB

The database I'm trying has more than 300 tables. I've tried to sync them all at once or start with a single table, the outcome is the same. In a previous version of MySQL connector, I didn't experience any issues. The last successful sync was on 2023-09-07.

Initially, I thought the state was too big, so I upgraded from version `3.0.3` to `3.0.7`, but that didn't resolve the issue.

### Relevant log output

```shell
at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15)
        at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:53)
        at io.airbyte.integrations.source.mysql.initialsync.MySqlInitialLoadRecordIterator.computeNext(MySqlInitialLoadRecordIterator.java:93)
        ... 36 more
Caused by: java.sql.SQLException: Buffer length is less than expected payload length.
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
        at com.mysql.cj.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:2042)
        at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:401)
        at com.zaxxer.hikari.pool.HikariProxyConnection.setAutoCommit(HikariProxyConnection.java)
        at io.airbyte.db.jdbc.StreamingJdbcDatabase.lambda$unsafeQuery$0(StreamingJdbcDatabase.java:72)
        ... 40 more
Caused by: com.mysql.cj.exceptions.WrongArgumentException: Buffer length is less than expected payload length.
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
        at com.mysql.cj.protocol.a.NativePacketPayload.readString(NativePacketPayload.java:632)
        at com.mysql.cj.protocol.a.NativePacketPayload.readString(NativePacketPayload.java:606)
        at com.mysql.cj.protocol.a.NativeServerSessionStateController$NativeServerSessionStateChanges.init(NativeServerSessionStateController.java:119)
        at com.mysql.cj.protocol.a.result.OkPacket.parse(OkPacket.java:66)
        at com.mysql.cj.protocol.a.NativeProtocol.readServerStatusForResultSets(NativeProtocol.java:1755)
        at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:116)
        at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:48)
        at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1664)
        at com.mysql.cj.protocol.a.NativeProtocol.readAllResults(NativeProtocol.java:1718)
        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1064)
        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryString(NativeProtocol.java:997)
        at com.mysql.cj.NativeSession.execSQL(NativeSession.java:663)
        at com.mysql.cj.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:2033)
        ... 43 more
2023-09-18 13:44:25 INFO i.a.w.g.BufferedReplicationWorker(readFromSource):346 - readFromSource: source exception
io.airbyte.workers.internal.exception.SourceException: Source process exited with non-zero exit code 1
        at io.airbyte.workers.general.BufferedReplicationWorker.readFromSource(BufferedReplicationWorker.java:343) ~[io.airbyte-airbyte-commons-worker-0.50.27.jar:?]
        at io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsyncWithHeartbeatCheck$3(BufferedReplicationWorker.java:236) ~[io.airbyte-airbyte-commons-worker-0.50.27.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

Full log: [a0117286_6815_4c3a_8575_98b3b5ac8274_job_5617_attempt_1_txt.txt](https://github.com/airbytehq/airbyte/files/12648643/a0117286_6815_4c3a_8575_98b3b5ac8274_job_5617_attempt_1_txt.txt)

### Contribute

- [ ] Yes, I want to contribute

**Comment by evantahler** [comment]
This issue doesn't look like a state issue... and we've made some big improvements to the connectors and platform (e.g. we can now store larger states).  I'm going to close this issue - please try again with the latest platform and connectors!
