### ISSUE TITLE
[destination-snowflake] Not able to sync tables with the same name from different sources in parallel

### ISSUE THREAD

**Issue by rrittsteiger** [airbytehq/airbyte#30531]
### Connector Name

destination-snowflake

### Connector Version

3.1.2

### What step the error happened?

During the sync

### Revelant information

Hi all,

we have a problem regarding the stages inside airbyte_internal for some weeks. The problems started after the destination-snowflake upgrade from 1.3.2 to 3.1.2. But we are not sure if the problem was already existent before. 

We got two source both Postgres with a stream/table with the same naming "companies". When both streams/tables are synced in the same time only one stage is "companies" is created that is used by both data syncs. In the moment one of the destinations finishes the sync the stage "companies" gets deleted and the other sync that is still running got the problem, that it is not able to find its stage anymore.

I have attached some log output. Thank you for your help.

### Relevant log output

```shell
2023-09-18 14:27:23 destination > ERROR i.a.i.b.AirbyteExceptionHandler(uncaughtException):26 Something went wrong in the connector. See the logs for more details. java.lang.IllegalArgumentException: Self-suppression not permitted
        at java.lang.Throwable.addSuppressed(Throwable.java:1072) ~[?:?]
        at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:186) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
        at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:125) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
        at io.airbyte.integrations.base.adaptive.AdaptiveDestinationRunner$Runner.run(AdaptiveDestinationRunner.java:101) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
        at io.airbyte.integrations.destination.snowflake.SnowflakeDestinationRunner.main(SnowflakeDestinationRunner.java:18) ~[io.airbyte.airbyte-integrations.connectors-destination-snowflake-24.0.2.jar:?]
Caused by: java.lang.RuntimeException: Failed to upload buffer to stage and commit to destination
        at io.airbyte.integrations.destination.staging.AsyncFlush.flush(AsyncFlush.java:126) ~[io.airbyte.airbyte-integrations.bases-bases-destination-jdbc-24.0.2.jar:?]
        at io.airbyte.integrations.destination_async.FlushWorkers.lambda$flush$1(FlushWorkers.java:163) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: Exceptions thrown while uploading records into stage: net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
Stage 'AIRBYTE_SYNCS_FULL_REFRESH."airbyte_internal"."companies"' does not exist or not authorized.
net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
Stage 'AIRBYTE_SYNCS_FULL_REFRESH."airbyte_internal"."companies"' does not exist or not authorized.
net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
Stage 'AIRBYTE_SYNCS_FULL_REFRESH."airbyte_internal"."companies"' does not exist or not authorized.
        at io.airbyte.integrations.destination.snowflake.SnowflakeInternalStagingSqlOperations.uploadRecordsToStage(SnowflakeInternalStagingSqlOperations.java:94) ~[io.airbyte.airbyte-integrations.connectors-destination-snowflake-24.0.2.jar:?]
        at io.airbyte.integrations.destination.staging.AsyncFlush.flush(AsyncFlush.java:111) ~[io.airbyte.airbyte-integrations.bases-bases-destination-jdbc-24.0.2.jar:?]
        at io.airbyte.integrations.destination_async.FlushWorkers.lambda$flush$1(FlushWorkers.java:163) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by evantahler** [comment]
We should be better at preventing that in the UI, but this isn't supported.  Change the namespace (schema), or the table when setting up the syncs so they don't collide. A common pattern is `${source_name}_${table_name}`, so you'll end up with `pg1_customers` and `pg2_customers`
