### ISSUE TITLE
[destination-postgres] Unexpected error while checking connection: io.airbyte.workers.exception.WorkerException: Could not find image: airbyte/destination-postgres:0.4.0

### ISSUE THREAD

**Issue by judiennetSC** [airbytehq/airbyte#30575]
### Connector Name

destination-postgres

### Connector Version

0.4.0

### What step the error happened?

Configuring a new connector

### Revelant information

Hi everyone,

Cf. title: "ERROR i.a.w.g.DefaultCheckConnectionWorker(run):133 - Unexpected error while checking connection: 
io.airbyte.workers.exception.WorkerException: Could not find image: airbyte/destination-postgres:0.4.0"
**Airbyte version: 0.50.30**
Deployed on AWS EC2 (working well until now).
Here are the logs:

[check_connection_destination-failure-f1c42395-6c3d-43ec-b468-c5fa385d5a50.txt](https://github.com/airbytehq/airbyte/files/12659860/check_connection_destination-failure-f1c42395-6c3d-43ec-b468-c5fa385d5a50.txt)

Can you help please? 
Thank you!

### Relevant log output

```
Configuration check failed
The check connection failed because of an internal error


Learn more
Internal message: scheduledEventId=6, startedEventId=7, activityType='RunWithJobOutput', activityId='d57c9db4-9baa-3ef3-90cd-0273d083df00', identity='1@caec9bec35dc', retryState=RETRY_STATE_MAXIMUM_ATTEMPTS_REACHED
Failure origin: destination

Stacktrace
io.temporal.failure.ActivityFailure: scheduledEventId=6, startedEventId=7, activityType='RunWithJobOutput', activityId='d57c9db4-9baa-3ef3-90cd-0273d083df00', identity='1@caec9bec35dc', retryState=RETRY_STATE_MAXIMUM_ATTEMPTS_REACHED

Logs

2023-09-19 12:21:35 INFO i.a.w.t.TemporalAttemptExecution(get):124 - Docker volume job log path: /tmp/workspace/f1c42395-6c3d-43ec-b468-c5fa385d5a50/0/logs.log
2023-09-19 12:21:35 INFO i.a.w.t.TemporalAttemptExecution(get):129 - Executing worker wrapper. Airbyte version: 0.50.30
2023-09-19 12:21:35 INFO i.a.a.c.AirbyteApiClient(retryWithJitterThrows):290 - Attempt 0 to save workflow id for cancellation
2023-09-19 12:21:35 INFO i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2023-09-19 12:21:35 INFO i.a.c.i.LineGobbler(voidCall):149 - 
2023-09-19 12:21:35 INFO i.a.c.i.LineGobbler(voidCall):149 - ----- START CHECK -----
2023-09-19 12:21:35 INFO i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2023-09-19 12:21:35 INFO i.a.c.i.LineGobbler(voidCall):149 - 
2023-09-19 12:21:35 INFO i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2023-09-19 12:21:35 INFO i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2023-09-19 12:21:35 INFO i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable LAUNCHDARKLY_KEY: ''
2023-09-19 12:21:35 INFO i.a.c.i.LineGobbler(voidCall):149 - Checking if airbyte/destination-postgres:0.4.0 exists...
2023-09-19 12:21:35 INFO i.a.c.i.LineGobbler(voidCall):149 - airbyte/destination-postgres:0.4.0 not found locally. Attempting to pull the image...
2023-09-19 12:21:51 INFO i.a.c.i.LineGobbler(voidCall):149 - Image does not exist.
2023-09-19 12:21:51 ERROR i.a.w.g.DefaultCheckConnectionWorker(run):133 - Unexpected error while checking connection: 
io.airbyte.workers.exception.WorkerException: Could not find image: airbyte/destination-postgres:0.4.0
	at io.airbyte.workers.process.DockerProcessFactory.create(DockerProcessFactory.java:120) ~[io.airbyte-airbyte-commons-worker-0.50.30.jar:?]
	at io.airbyte.workers.process.AirbyteIntegrationLauncher.check(AirbyteIntegrationLauncher.java:143) ~[io.airbyte-airbyte-commons-worker-0.50.30.jar:?]
	at io.airbyte.workers.general.DefaultCheckConnectionWorker.run(DefaultCheckConnectionWorker.java:71) ~[io.airbyte-airbyte-commons-worker-0.50.30.jar:?]
	at io.airbyte.workers.general.DefaultCheckConnectionWorker.run(DefaultCheckConnectionWorker.java:44) ~[io.airbyte-airbyte-commons-worker-0.50.30.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:135) ~[io.airbyte-airbyte-workers-0.50.30.jar:?]
	at io.airbyte.workers.temporal.check.connection.CheckConnectionActivityImpl.lambda$runWithJobOutput$1(CheckConnectionActivityImpl.java:136) ~[io.airbyte-airbyte-workers-0.50.30.jar:?]
	at io.airbyte.commons.temporal.TemporalUtils.withBackgroundHeartbeat(TemporalUtils.java:314) ~[io.airbyte-airbyte-commons-temporal-0.50.30.jar:?]
	at io.airbyte.workers.temporal.check.connection.CheckConnectionActivityImpl.runWithJobOutput(CheckConnectionActivityImpl.java:121) ~[io.airbyte-airbyte-workers-0.50.30.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at io.temporal.internal.activity.RootActivityInboundCallsInterceptor$POJOActivityInboundCallsInterceptor.executeActivity(RootActivityInboundCallsInterceptor.java:64) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.activity.RootActivityInboundCallsInterceptor.execute(RootActivityInboundCallsInterceptor.java:43) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.activity.ActivityTaskExecutors$BaseActivityTaskExecutor.execute(ActivityTaskExecutors.java:95) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.activity.ActivityTaskHandlerImpl.handle(ActivityTaskHandlerImpl.java:92) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handleActivity(ActivityWorker.java:241) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:206) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:179) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93) ~[temporal-sdk-1.17.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
2023-09-19 12:21:51 INFO i.a.c.i.LineGobbler(voidCall):149 - 
2023-09-19 12:21:51 INFO i.a.c.i.LineGobbler(voidCall):149 - ----- END CHECK -----
2023-09-19 12:21:51 INFO i.a.c.i.LineGobbler(voidCall):149 - 
```

```
### Contribute

- [ ] Yes, I want to contribute

```

**Comment by ibrentlam** [comment]
have same issue running on Ubuntu 22.03.2 LTS

**Comment by evantahler** [comment]
Closing this issue - This is a very old image, and the latest versions of the platform handle image pulling differently.  Please open a new issue if the latest images can't be pulled.
