### ISSUE TITLE
GA connector breaking schema change after 1.4.0 version

### ISSUE THREAD

**Issue by zypox** [airbytehq/airbyte#30582]
### Connector Name

source-google-analytics-data-api

### Connector Version

1.4.0

### What step the error happened?

During the sync

### Revelant information

GA4 API allows to fetch custom dimensions by using `customEvent:parameter_name` structure. With `google-analytics-data-api` connector version `1.4.0` a change was introduced where all column symbols (`:`) are being automatically replaced with an underscore (`_`). Related PR: https://github.com/airbytehq/airbyte/pull/30417

After this change we received a breaking schema change notifications for all our GA4 connectors and it seems like there is no way to resolve this from the UI side. We also tried re-creating the connection, but it fails during the sync process in transformation step with error that seems to be related to column not being found (`KeyError: 'customEvent:user_id_dimension'`) when checking for primary key (added additional log output with the traceback). Any ideas how to resolve this?

### Relevant log output

```shell
2023-09-19 14:10:34 destination > 'customEvent:user_id_dimension'
Traceback (most recent call last):
  File "/usr/local/bin/transform-catalog", line 33, in <module>
    sys.exit(load_entry_point('normalization==0.0.0', 'console_scripts', 'transform-catalog')())
  File "/usr/local/lib/python3.7/site-packages/normalization/transform_catalog/transform.py", line 111, in main
    TransformCatalog().run(args)
  File "/usr/local/lib/python3.7/site-packages/normalization/transform_catalog/transform.py", line 36, in run
    self.process_catalog()
  File "/usr/local/lib/python3.7/site-packages/normalization/transform_catalog/transform.py", line 64, in process_catalog
    processor.process(catalog_file=catalog_file, json_column_name=json_col, default_schema=schema)
  File "/usr/local/lib/python3.7/site-packages/normalization/transform_catalog/catalog_processor.py", line 80, in process
    nested_processors = stream_processor.process()
  File "/usr/local/lib/python3.7/site-packages/normalization/transform_catalog/stream_processor.py", line 298, in process
    self.generate_scd_type_2_model(from_table, column_names),
  File "/usr/local/lib/python3.7/site-packages/normalization/transform_catalog/stream_processor.py", line 854, in generate_scd_type_2_model
    "primary_key_partition": self.get_primary_key_partition(column_names),
  File "/usr/local/lib/python3.7/site-packages/normalization/transform_catalog/stream_processor.py", line 1059, in get_primary_key_partition
    return [self.get_primary_key_from_path(column_names, path) for path in self.primary_key]
  File "/usr/local/lib/python3.7/site-packages/normalization/transform_catalog/stream_processor.py", line 1059, in <listcomp>
    return [self.get_primary_key_from_path(column_names, path) for path in self.primary_key]
  File "/usr/local/lib/python3.7/site-packages/normalization/transform_catalog/stream_processor.py", line 1067, in get_primary_key_from_path
    if "type" in self.properties[field]:
KeyError: 'customEvent:user_id_dimension'
2023-09-19 14:10:34 destination > 
2023-09-19 14:10:34 destination > Showing destination_catalog.json to diagnose/debug errors (1):
2023-09-19 14:10:34 destination > 
2023-09-19 14:10:34 destination > In-connector normalization done (exit code 1)
2023-09-19 14:10:34 replication-orchestrator > (pod: jobs / destination-bigquery-write-4748485-9-fgqkx) - Closed all resources for pod
2023-09-19 14:10:34 replication-orchestrator > Attempt 0 to update stream status incomplete null:events
2023-09-19 14:10:34 replication-orchestrator > Attempt 0 to Flush States from SyncPersistenceImpl
2023-09-19 14:10:35 replication-orchestrator > Attempt 0 to Flush Stats from SyncPersistenceImpl
2023-09-19 14:10:35 replication-orchestrator > Sync worker failed.
java.util.concurrent.ExecutionException: io.airbyte.workers.internal.exception.DestinationException: Destination process exited with non-zero exit code 1
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.replicate(DefaultReplicationWorker.java:214) ~[io.airbyte-airbyte-commons-worker-dev-8669f25941.jar:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:153) ~[io.airbyte-airbyte-commons-worker-dev-8669f25941.jar:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:68) ~[io.airbyte-airbyte-commons-worker-dev-8669f25941.jar:?]
	at io.airbyte.container_orchestrator.orchestrator.ReplicationJobOrchestrator.runJob(ReplicationJobOrchestrator.java:91) ~[io.airbyte-airbyte-container-orchestrator-dev-8669f25941.jar:?]
	at io.airbyte.container_orchestrator.Application.run(Application.java:78) ~[io.airbyte-airbyte-container-orchestrator-dev-8669f25941.jar:?]
	at io.airbyte.container_orchestrator.Application.main(Application.java:38) ~[io.airbyte-airbyte-container-orchestrator-dev-8669f25941.jar:?]
	Suppressed: io.airbyte.workers.exception.WorkerException: Destination process exit with code 1. This warning is normal if the job was cancelled.
		at io.airbyte.workers.internal.DefaultAirbyteDestination.close(DefaultAirbyteDestination.java:138) ~[io.airbyte-airbyte-commons-worker-dev-8669f25941.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.replicate(DefaultReplicationWorker.java:169) ~[io.airbyte-airbyte-commons-worker-dev-8669f25941.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:153) ~[io.airbyte-airbyte-commons-worker-dev-8669f25941.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:68) ~[io.airbyte-airbyte-commons-worker-dev-8669f25941.jar:?]
		at io.airbyte.container_orchestrator.orchestrator.ReplicationJobOrchestrator.runJob(ReplicationJobOrchestrator.java:91) ~[io.airbyte-airbyte-container-orchestrator-dev-8669f25941.jar:?]
		at io.airbyte.container_orchestrator.Application.run(Application.java:78) ~[io.airbyte-airbyte-container-orchestrator-dev-8669f25941.jar:?]
		at io.airbyte.container_orchestrator.Application.main(Application.java:38) ~[io.airbyte-airbyte-container-orchestrator-dev-8669f25941.jar:?]
Caused by: io.airbyte.workers.internal.exception.DestinationException: Destination process exited with non-zero exit code 1
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromDstRunnable$4(DefaultReplicationWorker.java:264) ~[io.airbyte-airbyte-commons-worker-dev-8669f25941.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
2023-09-19 14:10:35 replication-orchestrator > Could not reliably determine committed record counts, committed record stats will be set to null
2023-09-19 14:10:35 replication-orchestrator > sync summary: {
  "status" : "failed",
  "recordsSynced" : 11175,
  "bytesSynced" : 3089685,
  "startTime" : 1695132590176,
  "endTime" : 1695132635173,
  "totalStats" : {
    "bytesCommitted" : 2050915,
    "bytesEmitted" : 3089685,
    "destinationStateMessagesEmitted" : 12,
    "destinationWriteEndTime" : 0,
    "destinationWriteStartTime" : 1695132590183,
    "meanSecondsBeforeSourceStateMessageEmitted" : 1,
    "maxSecondsBeforeSourceStateMessageEmitted" : 6,
    "recordsEmitted" : 11175,
    "recordsCommitted" : 7144,
    "replicationEndTime" : 0,
    "replicationStartTime" : 1695132590176,
    "sourceReadEndTime" : 1695132609252,
    "sourceReadStartTime" : 1695132595883,
    "sourceStateMessagesEmitted" : 9
  },
  "streamStats" : [ {
    "streamName" : "users",
    "stats" : {
      "bytesCommitted" : 349041,
      "bytesEmitted" : 528468,
      "recordsEmitted" : 2285,
      "recordsCommitted" : 1457
    }
  }, {
    "streamName" : "test_report",
    "stats" : {
      "bytesCommitted" : 425981,
      "bytesEmitted" : 636044,
      "recordsEmitted" : 2316,
      "recordsCommitted" : 1488
    }
  }, {
    "streamName" : "events",
    "stats" : {
      "bytesCommitted" : 1275893,
      "bytesEmitted" : 1925173,
      "recordsEmitted" : 6574,
      "recordsCommitted" : 4199
    }
  } ]
}
2023-09-19 14:10:35 replication-orchestrator > failures: [ {
  "failureOrigin" : "destination",
  "internalMessage" : "Destination process exited with non-zero exit code 1",
  "externalMessage" : "Something went wrong within the destination connector",
  "metadata" : {
    "attemptNumber" : 9,
    "jobId" : 4748485,
    "connector_command" : "write"
  },
  "stacktrace" : "io.airbyte.workers.internal.exception.DestinationException: Destination process exited with non-zero exit code 1\n\tat io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromDstRunnable$4(DefaultReplicationWorker.java:264)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1589)\n",
  "timestamp" : 1695132634690
} ]
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by lazebnyi** [comment]
Hi @zypox
What destination you use in your connection?

**Comment by zypox** [comment]
Hey, @lazebnyi , we're using BigQuery.
