### ISSUE TITLE
Destination Lakehouse: Source didn't exit properly

### ISSUE THREAD

**Issue by jacobpascalcoblentz** [airbytehq/airbyte#30676]
### Connector Name

destination-lakehouse

### Connector Version

1.1.0

### What step the error happened?

None

### Revelant information

Seems to sync records to Lakehouse, but fail part way, and I'm not sure why -- the error message is not very helpful here. 

### Relevant log output

```shell
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$5(DefaultReplicationWorker.java:326) ~[io.airbyte-airbyte-commons-worker-dev-6b3172bc57.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
	Suppressed: io.airbyte.workers.exception.WorkerException: Source process exit with code 137. This warning is normal if the job was cancelled.

```

### Contribute

- [ ] Yes, I want to contribute

**Comment by jacobpascalcoblentz** [comment]
Follow up here is that the source is from surveymonkey

**Comment by jacobpascalcoblentz** [comment]
Seems to be a 137 error, that airbyte cloud is running out of memory

**Comment by evantahler** [comment]
Closing - this destination has been updated significantly since this issue was posted.
