### ISSUE TITLE
[destination-bigquery] Read timed out

### ISSUE THREAD

**Issue by liuqian1990** [airbytehq/airbyte#30707]
### Connector Name

Destination bigquery

### Connector Version

2.0.10

### What step the error happened?

During the sync

### Revelant information

- [ ] There is no problem when the test data volume is 40 million. When the data volume reaches 6 billion, the following problems occur.

### Relevant log output

```shell
INFO i.a.w.p.KubePodProcess(close):787 - (pod: devops / destination-bigquery-write-20-0-bcegs) - Closed all resources for pod
2023-09-21 16:27:20 INFO i.a.w.g.BufferedReplicationWorker(readFromDestination):457 - readFromDestination: exception caught
io.airbyte.workers.internal.exception.DestinationException: Destination process exited with non-zero exit code 1
	at io.airbyte.workers.general.BufferedReplicationWorker.readFromDestination(BufferedReplicationWorker.java:451) ~[io.airbyte-airbyte-commons-worker-0.50.25.jar:?]
	at io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsync$2(BufferedReplicationWorker.java:225) ~[io.airbyte-airbyte-commons-worker-0.50.25.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
2023-09-21 16:27:20 INFO i.a.w.g.BufferedReplicationWorker(readFromDestination):460 - readFromDestination: done. (writeToDestFailed:false, dest.isFinished:true)

java.lang.RuntimeException: com.google.cloud.bigquery.BigQueryException: Read timed out
   at io.airbyte.integrations.destination.bigquery.uploader.AbstractBigQueryUploader.close(AbstractBigQueryUploader.java:92)
   at io.airbyte.integrations.destination.bigquery.BigQueryRecordConsumer.lambda$close$1(BigQueryRecordConsumer.java:126)
   at java.base/java.util.HashMap.forEach(HashMap.java:1421)
   at io.airbyte.integrations.destination.bigquery.BigQueryRecordConsumer.close(BigQueryRecordConsumer.java:124)
   at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.close(FailureTrackingAirbyteMessageConsumer.java:82)
   at io.airbyte.integrations.base.Destination$ShimToSerializedAirbyteMessageConsumer.close(Destination.java:96)
   at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:188)
   at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:125)
   at io.airbyte.integrations.destination.bigquery.BigQueryDestination.main(BigQueryDestination.java:441)
Caused by: com.google.cloud.bigquery.BigQueryException: Read timed out
   at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:114)
   at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.write(HttpBigQueryRpc.java:795)
   at com.google.cloud.bigquery.TableDataWriteChannel$1.call(TableDataWriteChannel.java:59)
   at com.google.cloud.bigquery.TableDataWriteChannel$1.call(TableDataWriteChannel.java:54)
   at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103)
   at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
   at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
   at com.google.cloud.bigquery.TableDataWriteChannel.flushBuffer(TableDataWriteChannel.java:53)
   at com.google.cloud.BaseWriteChannel.close(BaseWriteChannel.java:151)
   at io.airbyte.integrations.destination.bigquery.writer.BigQueryTableWriter.close(BigQueryTableWriter.java:44)
   at io.airbyte.integrations.destination.bigquery.uploader.AbstractBigQueryUploader.close(AbstractBigQueryUploader.java:82)
Caused by: java.net.SocketTimeoutException: Read timed out
   at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:288)
   at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:314)
   at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
   at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
   at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
   at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:484)
   at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:478)\n\
   at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
   at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1465)
   at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1069)
   at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
   at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
   at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
   at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:826)
   at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:761)
   at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1688)
   at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
   at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
   at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
   at com.google.api.client.http.javanet.NetHttpResponse.<init>(NetHttpResponse.java:36)
   at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:152)
   at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:84)
   at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1012)
   at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.write(HttpBigQueryRpc.java:778)... 17 more


io.airbyte.workers.internal.exception.DestinationException: Destination process exited with non-zero exit code 1
 at io.airbyte.workers.general.BufferedReplicationWorker.readFromDestination(BufferedReplicationWorker.java:451)
 at io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsync$2(BufferedReplicationWorker.java:225)
 at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
 at java.base/java.lang.Thread.run(Thread.java:1589)
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by evantahler** [comment]
Can you include the full sync log please?

**Comment by evantahler** [comment]
Also, I'm going to close this issue.  I'm sorry for the delay, but since then, we've made a number of improvements in the connector
