### ISSUE TITLE
Airbyte worker fails to spin up sync pods for source connectors

### ISSUE THREAD

**Issue by TalhaNaeem101** [airbytehq/airbyte#30727]
### Problem

While configuring source connectors, the airbyte worker gets stuck in queuing the workflow of source connectors creation. When I try to create a source connector with stripe or mailchimp source, the sync worker pods (source-check, source-read) are not spun up and the flow to setup source connector fails with the following output due to timeout:
![image](https://github.com/airbytehq/airbyte/assets/105629434/f0bc16b1-daf8-47d8-9ed6-ae780248c5c0)

### Error logs

We get the following errors in airbyte worker logs:
```
2023-09-25 07:41:54 WARN i.t.i.a.POJOActivityTaskHandler(activityFailureToResult):307 - Activity failure. ActivityId=114c5799-1eb1-32b4-bb5e-1437a33d7190, activityType=RunWithJobOutput, attempt=4
java.util.concurrent.CancellationException: null
	at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2510) ~[?:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getCancellationChecker$3(TemporalAttemptExecution.java:205) ~[io.airbyte-airbyte-workers-0.40.6.jar:?]
	at io.airbyte.workers.temporal.CancellationHandler$TemporalCancellationHandler.checkAndHandleCancellation(CancellationHandler.java:52) ~[io.airbyte-airbyte-workers-0.40.6.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getCancellationChecker$4(TemporalAttemptExecution.java:208) ~[io.airbyte-airbyte-workers-0.40.6.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [?:?]
	at java.lang.Thread.run(Thread.java:1589) [?:?]
Log4j2Appender says: Activity failure. ActivityId=114c5799-1eb1-32b4-bb5e-1437a33d7190, activityType=RunWithJobOutput, attempt=4
2023-09-25 07:41:54 ERROR i.a.w.g.DefaultCheckConnectionWorker(run):102 - Unexpected error while checking connection: 
io.airbyte.workers.exception.WorkerException: null
	at io.airbyte.workers.process.KubeProcessFactory.create(KubeProcessFactory.java:138) ~[io.airbyte-airbyte-workers-0.40.6.jar:?]
	at io.airbyte.workers.process.AirbyteIntegrationLauncher.check(AirbyteIntegrationLauncher.java:86) ~[io.airbyte-airbyte-workers-0.40.6.jar:?]
	at io.airbyte.workers.general.DefaultCheckConnectionWorker.run(DefaultCheckConnectionWorker.java:64) ~[io.airbyte-airbyte-workers-0.40.6.jar:?]
	at io.airbyte.workers.general.DefaultCheckConnectionWorker.run(DefaultCheckConnectionWorker.java:37) ~[io.airbyte-airbyte-workers-0.40.6.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:159) ~[io.airbyte-airbyte-workers-0.40.6.jar:?]
	at java.lang.Thread.run(Thread.java:1589) [?:?]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1681) ~[?:?]
	at java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:515) ~[?:?]
	at java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:677) ~[?:?]
	at io.airbyte.workers.process.KubePortManagerSingleton.take(KubePortManagerSingleton.java:67) ~[io.airbyte-airbyte-workers-0.40.6.jar:?]
	at io.airbyte.workers.process.KubeProcessFactory.create(KubeProcessFactory.java:102) ~[io.airbyte-airbyte-workers-0.40.6.jar:?]
	... 5 more
```

The following logs are captured exactly when we try to setup the source connector:

```
2023-09-25 07:45:08 INFO i.a.c.i.LineGobbler(voidCall):114 - ----- START CHECK -----
Log4j2Appender says: ----- START CHECK -----
2023-09-25 07:45:08 INFO i.a.c.i.LineGobbler(voidCall):114 - 
Log4j2Appender says: 
2023-09-25 07:45:15 ERROR i.a.w.t.s.ConnectionManagerWorkflowImpl(runMandatoryActivityWithOutput):541 - [ACTIVITY-FAILURE] Connection 6795baa4-1a9d-4cc3-b636-86ec4a797501 failed to run an activity. Connection manager workflow will be restarted after a delay of 600 seconds.
io.temporal.failure.ActivityFailure: scheduledEventId=45, startedEventId=46, activityType='RunWithJobOutput', activityId='7c6543f6-4d29-3d16-9b2b-c9b7b5eb0681', identity='', retryState=RETRY_STATE_MAXIMUM_ATTEMPTS_REACHED
	at java.lang.Thread.getStackTrace(Thread.java:2550) ~[?:?]
	at io.temporal.internal.sync.ActivityStubBase.execute(ActivityStubBase.java:48) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.sync.ActivityInvocationHandler.lambda$getActivityFunc$0(ActivityInvocationHandler.java:77) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.sync.ActivityInvocationHandlerBase.invoke(ActivityInvocationHandlerBase.java:70) ~[temporal-sdk-1.8.1.jar:?]
	at jdk.proxy2.$Proxy53.runWithJobOutput(Unknown Source) ~[?:?]
	at io.airbyte.workers.temporal.scheduling.ConnectionManagerWorkflowImpl.runMandatoryActivityWithOutput(ConnectionManagerWorkflowImpl.java:539) ~[io.airbyte-airbyte-workers-0.40.6.jar:?]
	at io.airbyte.workers.temporal.scheduling.ConnectionManagerWorkflowImpl.getCheckResponse(ConnectionManagerWorkflowImpl.java:363) ~[io.airbyte-airbyte-workers-0.40.6.jar:?]
	at io.airbyte.workers.temporal.scheduling.ConnectionManagerWorkflowImpl.checkConnections(ConnectionManagerWorkflowImpl.java:391) ~[io.airbyte-airbyte-workers-0.40.6.jar:?]
	at io.airbyte.workers.temporal.scheduling.ConnectionManagerWorkflowImpl.lambda$generateSyncWorkflowRunnable$1(ConnectionManagerWorkflowImpl.java:227) ~[io.airbyte-airbyte-workers-0.40.6.jar:?]
	at io.temporal.internal.sync.CancellationScopeImpl.run(CancellationScopeImpl.java:101) ~[temporal-sdk-1.8.1.jar:?]
	at io.airbyte.workers.temporal.scheduling.ConnectionManagerWorkflowImpl.run(ConnectionManagerWorkflowImpl.java:146) ~[io.airbyte-airbyte-workers-0.40.6.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation$RootWorkflowInboundCallsInterceptor.execute(POJOWorkflowImplementationFactory.java:317) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation.execute(POJOWorkflowImplementationFactory.java:292) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.sync.WorkflowExecuteRunnable.run(WorkflowExecuteRunnable.java:72) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.sync.SyncWorkflow.lambda$start$0(SyncWorkflow.java:137) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.sync.CancellationScopeImpl.run(CancellationScopeImpl.java:101) [temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.sync.WorkflowThreadImpl$RunnableWrapper.run(WorkflowThreadImpl.java:111) [temporal-sdk-1.8.1.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:317) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [?:?]
	at java.lang.Thread.run(Thread.java:1589) [?:?]

2023-09-25 07:45:25 ERROR i.a.w.g.DefaultCheckConnectionWorker(run):102 - Unexpected error while checking connection: 
io.airbyte.workers.exception.WorkerException: null
	at io.airbyte.workers.process.KubeProcessFactory.create(KubeProcessFactory.java:138) ~[io.airbyte-airbyte-workers-0.40.6.jar:?]
	at io.airbyte.workers.process.AirbyteIntegrationLauncher.check(AirbyteIntegrationLauncher.java:86) ~[io.airbyte-airbyte-workers-0.40.6.jar:?]
	at io.airbyte.workers.general.DefaultCheckConnectionWorker.run(DefaultCheckConnectionWorker.java:64) ~[io.airbyte-airbyte-workers-0.40.6.jar:?]
	at io.airbyte.workers.general.DefaultCheckConnectionWorker.run(DefaultCheckConnectionWorker.java:37) ~[io.airbyte-airbyte-workers-0.40.6.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:159) ~[io.airbyte-airbyte-workers-0.40.6.jar:?]
	at java.lang.Thread.run(Thread.java:1589) [?:?]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1681) ~[?:?]
	at java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:515) ~[?:?]
	at java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:677) ~[?:?]
	at io.airbyte.workers.process.KubePortManagerSingleton.take(KubePortManagerSingleton.java:67) ~[io.airbyte-airbyte-workers-0.40.6.jar:?]
	at io.airbyte.workers.process.KubeProcessFactory.create(KubeProcessFactory.java:102) ~[io.airbyte-airbyte-workers-0.40.6.jar:?]
	... 5 more
Log4j2Appender says: Activity failure. ActivityId=7c6543f6-4d29-3d16-9b2b-c9b7b5eb0681, activityType=RunWithJobOutput, attempt=5
```

After **restarting airbyte-worker pod**, the **sync worker pods get start spinning up all at once**:
![image](https://github.com/airbytehq/airbyte/assets/105629434/6ef69a0a-ac17-4e30-b707-73b97e322633)

Please help me out in finding out the cause of these errors in airbyte worker logs. :pray: thanks in advance

**Airbyte Version:** 0.40.6
**EKS version:** v1.25

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by shubhamqua** [comment]
I am using Airbyte Version 0.50.31  and i am getting the following error when i am trying to retest the source:

`Internal message: scheduledEventId=6, startedEventId=7, activityType='RunWithJobOutput', activityId='6bbfd5c2-5dad-36e8-94b7-4c31106bde34', identity='1@airbyte-worker-7964c4b767-vhkgh', retryState=RETRY_STATE_MAXIMUM_ATTEMPTS_REACHED`

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 180 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
