### ISSUE TITLE
Bigquery destination -> Invalid value: Field stsc_time1 has type TIME, which is not supported for clustering

### ISSUE THREAD

**Issue by pasglop** [airbytehq/airbyte#30720]
### Connector Name

destination-bigquery

### Connector Version

2.0.16

### What step the error happened?

During the sync

### Revelant information

We consume a mysql source with CDC (binlog) enabled. The DB user is properly configured and connection works.

I notice that there are no data in airbyte_internal.

main error is : Invalid value: Field stsc_time1 has type TIME, which is not supported for clustering

I don't find this field in bigquery.

### Relevant log output

```shell
ERROR i.a.i.b.AirbyteExceptionHandler(uncaughtException):26 Something went wrong in the connector. See the logs for more details. com.google.cloud.bigquery.BigQueryException: Invalid value: Field stsc_time1 has type TIME, which is not supported for clustering. at [4:1]
        at com.google.cloud.bigquery.Job.reload(Job.java:424) ~[google-cloud-bigquery-2.31.1.jar:2.31.1]
        at io.airbyte.integrations.destination.bigquery.typing_deduping.BigQueryDestinationHandler.execute(BigQueryDestinationHandler.java:70) ~[io.airbyte.airbyte-integrations.connectors-destination-bigquery-0.50.30.jar:?]
        at io.airbyte.integrations.base.destination.typing_deduping.DefaultTyperDeduper.lambda$prepareTablesFuture$1(DefaultTyperDeduper.java:144) ~[io.airbyte.airbyte-integrations.bases-base-typing-deduping-0.50.30.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Stack Trace: com.google.cloud.bigquery.BigQueryException: Invalid value: Field stsc_time1 has type TIME, which is not supported for clustering. at [4:1]
        at com.google.cloud.bigquery.Job.reload(Job.java:424)
        at io.airbyte.integrations.destination.bigquery.typing_deduping.BigQueryDestinationHandler.execute(BigQueryDestinationHandler.java:70)
        at io.airbyte.integrations.base.destination.typing_deduping.DefaultTyperDeduper.lambda$prepareTablesFuture$1(DefaultTyperDeduper.java:144)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Contribute

- [X] Yes, I want to contribute

**Comment by pasglop** [comment]
This is related to our own DB. I close this.
