### ISSUE TITLE
🐛 Container orchestrator not working with custom service account

### ISSUE THREAD

**Issue by berosen** [airbytehq/airbyte#30745]
### Revelant information

**Airbyte Version**: `0.50.27`
**Deployment**: AWS EKS 

The helm chart supports [providing a custom service account](https://github.com/airbytehq/airbyte-platform/blob/b7b319c8821d9cd94f3f6ee8d3efa2ca119fbb48/charts/airbyte/values.yaml#L8) which is then set properly on the [worker pod](https://github.com/airbytehq/airbyte-platform/blob/main/charts/airbyte-worker/templates/deployment.yaml#L137), so any K8s client in the worker use the proper service account. 

When running Airbyte with the container orchestrator enabled, the `JOB_KUBE_SERVICEACCOUNT` environment variable appears to [never get passed onto the container orchestrator pod](https://github.com/airbytehq/airbyte-platform/blob/main/airbyte-commons-temporal/src/main/java/io/airbyte/commons/temporal/sync/OrchestratorConstants.java#L27). This then causes the K8s clients in the orchestrator to always fall back to the `airbyte-admin` SA, which is the default configured in the [application](https://github.com/airbytehq/airbyte-platform/blob/main/airbyte-container-orchestrator/src/main/resources/application.yml#L61) configuration. This causes a service account not found exception when the source/destination sync pods are being created. I've run a local build adding `JOB_KUBE_SERVICEACCOUNT` to the orchestrator constants list and the SA exception has gone away, with syncs finishing successfully. Let me know if I've misconfigured anything, and I'm happy to submit a PR for this if it is indeed a bug. Thanks!

```txt
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://172.20.0.1:443/api/v1/namespaces/<my-namespace>/pods. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. │
│  pods "source-file-read-8-0-evqpp" is forbidden: error looking up service account <my-namespace>/airbyte-admin: serviceaccount "airbyte-admin" not found.                                                                                                              │
│     at io.fabric8.kubernetes.client.KubernetesClientException.copyAsCause(KubernetesClientException.java:238)                                                                                                                                                                  │
│     at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:546)                                                                                                                                                                     │
│     at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:566)                                                                                                                                                                    │
│     at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleCreate(OperationSupport.java:350)                                                                                                                                                                      │
│     at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleCreate(BaseOperation.java:707)                                                                                                                                                                            │
│     at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleCreate(BaseOperation.java:93)                                                                                                                                                                             │
│     at io.fabric8.kubernetes.client.dsl.internal.CreateOnlyResourceOperation.create(CreateOnlyResourceOperation.java:42)                                                                                                                                                       │
│     at io.fabric8.kubernetes.client.utils.internal.CreateOrReplaceHelper.createOrReplace(CreateOrReplaceHelper.java:51)                                                                                                                                                        │
│     at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.createOrReplace(BaseOperation.java:310)                                                                                                                                                                         │
│     at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.createOrReplace(BaseOperation.java:93)                                                                                                                                                                          │
│     at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.createOrReplace(BaseOperation.java:1077)                                                                                                                                                                        │
│     at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.createOrReplace(BaseOperation.java:93)                                                                                                                                                                          │
│     at io.airbyte.workers.process.KubePodProcess.<init>(KubePodProcess.java:574)                                                                                                                                                                                               │
│     at io.airbyte.workers.process.KubeProcessFactory.create(KubeProcessFactory.java:170)                                                                                                                                                                                       │
│     ... 9 more                                                    
```

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.

**Comment by cjangrist** [comment]
can reproduce on latest heml chart

another thread suggests setting 

```
  set {
    name  = "global.jobs.kube.serviceAccountName"
    value = google_service_account_key.airbyte.name
  }
```
