### ISSUE TITLE
[source-freshsales] exception for `won_deals` and `lost_deals`

### ISSUE THREAD

**Issue by nsi319** [airbytehq/airbyte#30932]
### Connector Name

source-freshsales

### Connector Version

0.1.4	

### What step the error happened?

During the sync

### Revelant information

I have chosen three steams (open_deals, lost_deals and won_deals). Airbyte is syncing data properly for open_deals. For other two, I'm facing this issue.

### Relevant log output

```shell
2023-09-29 13:59:11 source > Starting syncing SourceFreshsales
2023-09-29 13:59:13 source > generator raised StopIteration
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 439, in _read_pages
    request, response = self._fetch_next_page(stream_slice, stream_state, next_page_token)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 454, in _fetch_next_page
    path=self.path(stream_state=stream_state, stream_slice=stream_slice, next_page_token=next_page_token),
  File "/airbyte/integration_code/source_freshsales/source.py", line 85, in path
    return f"{self.object_name}/view/{self.get_view_id()}"
  File "/airbyte/integration_code/source_freshsales/source.py", line 81, in get_view_id
    return next(_filter["id"] for _filter in filters if _filter["name"] == self.filter_name)
StopIteration
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by yilepoh** [comment]
facing issue with `won_deals` specifically.
able to sync successfully for `open_deals` and `lost_deals`, tested this out by using 3 individual connections for each streams

would like to add, on top of the logs shown above, here's a longer version of it

```
2023-10-18 03:04:17 source > Starting syncing SourceFreshsales
2023-10-18 03:04:18 source > generator raised StopIteration
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 439, in _read_pages
    request, response = self._fetch_next_page(stream_slice, stream_state, next_page_token)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 454, in _fetch_next_page
    path=self.path(stream_state=stream_state, stream_slice=stream_slice, next_page_token=next_page_token),
  File "/airbyte/integration_code/source_freshsales/source.py", line 85, in path
    return f"{self.object_name}/view/{self.get_view_id()}"
  File "/airbyte/integration_code/source_freshsales/source.py", line 81, in get_view_id
    return next(_filter["id"] for _filter in filters if _filter["name"] == self.filter_name)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 131, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 122, in run
    for message in generator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 110, in read
    stream_is_available, error = stream_instance.check_availability(logger, self)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/core.py", line 190, in check_availability
    return self.availability_strategy.check_availability(self, logger, source)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/availability_strategy.py", line 45, in check_availability
    get_first_record_for_slice(stream, stream_slice)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/utils/stream_helper.py", line 38, in get_first_record_for_slice
    return next(records_for_slice)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 423, in read_records
    yield from self._read_pages(
RuntimeError: generator raised StopIteration
2023-10-18 03:04:18 replication-orchestrator > Source has no more messages, closing connection.
2023-10-18 03:04:19 replication-orchestrator > (pod: jobs / source-freshsales-read-5350701-0-rpjva) - Closed all resources for pod
```

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
