### ISSUE TITLE
Issue Using Temporal v1.20.1 in Helm Deployment

### ISSUE THREAD

**Issue by FransDel** [airbytehq/airbyte#30973]
### Topic

temporal, worker, server

### Relevant information

I suspect there might be an issue with the version of temporal used in airbyte's helm chart by default in the recent versions (version 1.21.0). 

After having upgraded from a 40.x version of airbyte (using helm) to a 50.20 then 50.25 then 50.30 we were having issues in airbyte server (problems with temporal) + worker (error bellow) + temporal (a lot of deadline exceeded errors these were spotted on the history service).
This was causing the following behaviours: 
* 504 errors on the UI and API 
* extreme slowness on starting flows 
* impossible to start flows 
* flows starting but not pods. 

After some investigation I have found this error in the worker logs: 

```
io.temporal.internal.statemachines.InternalWorkflowTaskException: Failure handling event 24 of type 'EVENT_TYPE_WORKFLOW_TASK_STARTED' during execution. {WorkflowTaskStartedEventId=24, CurrentStartedEventId=24}
	at io.temporal.internal.statemachines.WorkflowStateMachines.createEventProcessingException(WorkflowStateMachines.java:257) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.statemachines.WorkflowStateMachines.handleEventsBatch(WorkflowStateMachines.java:236) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.statemachines.WorkflowStateMachines.handleEvent(WorkflowStateMachines.java:208) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.applyServerHistory(ReplayWorkflowRunTaskHandler.java:208) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.handleWorkflowTaskImpl(ReplayWorkflowRunTaskHandler.java:192) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.handleWorkflowTask(ReplayWorkflowRunTaskHandler.java:147) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.replay.ReplayWorkflowTaskHandler.handleWorkflowTaskWithQuery(ReplayWorkflowTaskHandler.java:132) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.replay.ReplayWorkflowTaskHandler.handleWorkflowTask(ReplayWorkflowTaskHandler.java:97) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handleTask(WorkflowWorker.java:336) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:246) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:188) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93) ~[temporal-sdk-1.17.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.RuntimeException: WorkflowTask: failure executing SCHEDULED->WORKFLOW_TASK_STARTED, transition history is [CREATED->WORKFLOW_TASK_SCHEDULED]
	at io.temporal.internal.statemachines.StateMachine.executeTransition(StateMachine.java:152) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.statemachines.StateMachine.handleHistoryEvent(StateMachine.java:102) ~[temporal-sdk-… [message truncated due to size]
```

Noticing this and that previously we were in version v1.13 for temporal I downgraded the temporal version to v1.13 and all the problems were resolved. I suspect something does not work between the worker and that version of temporal, it might be just the version of the temporal lib.
Just added this here in case someone had the same issue and maybe to further investigate this weird behaviour.

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
