### ISSUE TITLE
Source Postgres: glibc error CPU does not support x86-64-v2

### ISSUE THREAD

**Issue by damaradiprabowo** [airbytehq/airbyte#31010]
### Connector Name

source-postgres

### Connector Version

3.1.8

### What step the error happened?

Configuring a new connector

### Revelant information

I encountered an error while attempting to set up a new connection or update an existing connection to PostgreSQL on the source-postgres version 3.1.8. This issue is only present in the >= 3.1.8, as it worked flawlessly with previous versions.

I am running Ubuntu Server 22.04 on an x86_64 virtual machine.

### Relevant log output

```shell
2023-10-03 09:03:47 INFO i.a.w.t.TemporalAttemptExecution(get):124 - Docker volume job log path: /tmp/workspace/5912b69d-2815-490f-a8d5-c10676d075b4/0/logs.log
2023-10-03 09:03:47 INFO i.a.w.t.TemporalAttemptExecution(get):129 - Executing worker wrapper. Airbyte version: 0.50.30
2023-10-03 09:03:47 INFO i.a.a.c.AirbyteApiClient(retryWithJitterThrows):290 - Attempt 0 to save workflow id for cancellation
2023-10-03 09:03:47 INFO i.a.c.i.LineGobbler(voidCall):149 - 
2023-10-03 09:03:47 INFO i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2023-10-03 09:03:47 INFO i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2023-10-03 09:03:47 INFO i.a.c.i.LineGobbler(voidCall):149 - ----- START CHECK -----
2023-10-03 09:03:47 INFO i.a.c.i.LineGobbler(voidCall):149 - 
2023-10-03 09:03:47 INFO i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2023-10-03 09:03:47 INFO i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2023-10-03 09:03:47 INFO i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable LAUNCHDARKLY_KEY: ''
2023-10-03 09:03:47 INFO i.a.c.i.LineGobbler(voidCall):149 - Checking if airbyte/source-postgres:3.1.8 exists...
2023-10-03 09:03:47 INFO i.a.c.i.LineGobbler(voidCall):149 - airbyte/source-postgres:3.1.8 was found locally.
2023-10-03 09:03:47 INFO i.a.w.p.DockerProcessFactory(create):143 - Creating docker container = source-postgres-check-5912b69d-2815-490f-a8d5-c10676d075b4-0-azbvx with resources io.airbyte.config.ResourceRequirements@ceaebe9[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts null
2023-10-03 09:03:47 INFO i.a.w.p.DockerProcessFactory(create):196 - Preparing command: docker run --rm --init -i -w /data/5912b69d-2815-490f-a8d5-c10676d075b4/0 --log-driver none --name source-postgres-check-5912b69d-2815-490f-a8d5-c10676d075b4-0-azbvx --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/source-postgres:3.1.8 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e USE_STREAM_CAPABLE_STATE=true -e FIELD_SELECTION_WORKSPACES= -e WORKER_ENVIRONMENT=DOCKER -e AIRBYTE_ROLE= -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=0 -e OTEL_COLLECTOR_ENDPOINT=http://host.docker.internal:4317 -e FEATURE_FLAG_CLIENT=config -e AIRBYTE_VERSION=0.50.30 -e WORKER_JOB_ID=5912b69d-2815-490f-a8d5-c10676d075b4 airbyte/source-postgres:3.1.8 check --config source_config.json
2023-10-03 09:03:47 INFO i.a.w.i.VersionedAirbyteStreamFactory(create):177 - Reading messages from protocol version 0.2.0
2023-10-03 09:03:47 ERROR i.a.c.i.LineGobbler(voidCall):149 - Fatal glibc error: CPU does not support x86-64-v2
2023-10-03 09:03:47 WARN i.a.w.g.DefaultCheckConnectionWorker(run):110 - Check connection job subprocess finished with exit code 127
2023-10-03 09:03:47 ERROR i.a.w.g.DefaultCheckConnectionWorker(run):133 - Unexpected error while checking connection: 
io.airbyte.workers.exception.WorkerException: Error checking connection status: no status nor failure reason were outputted
	at io.airbyte.workers.WorkerUtils.throwWorkerException(WorkerUtils.java:267) ~[io.airbyte-airbyte-commons-worker-0.50.30.jar:?]
	at io.airbyte.workers.general.DefaultCheckConnectionWorker.run(DefaultCheckConnectionWorker.java:120) ~[io.airbyte-airbyte-commons-worker-0.50.30.jar:?]
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by kira-youshikage** [comment]
I use VirtualBox and meet same error. I solve it by executing this command for the virtual machine:
**vboxmanage setextradata "your_machine_name" "VBoxInternal/CPUM/IsaExts/POPCNT" "1"**

**Comment by d3-nico** [comment]
@damaradiprabowo i have the same error on my debian buster machine. You found a solution?

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 365 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.
