### ISSUE TITLE
🐛 Source Paypal Transaction: `RESULTSET_TOO_LARGE` not handled in v2.1.0

### ISSUE THREAD

**Issue by domzae** [airbytehq/airbyte#31124]
### Connector Name

source-paypal-transaction

### Connector Version

2.1.0

### What step the error happened?

During the sync

### Relevant information

It seems like since the migration to low code, the [RESULTSET_TOO_LARGE error](https://github.com/airbytehq/airbyte/pull/29223/files#diff-f246a29b73b766978a1df8073be09e9e6384fd7da42031031159a72890164606L322-L328) ([test](https://github.com/airbytehq/airbyte/pull/29223/files#diff-4eb413a0f4b44cc9d63200e7aed178040db0389890386e2db90d71137e4a7925L283-L318)) is no longer handled. Causing syncs to fail if there are too many results.

### Relevant log output

```shell
2023-10-06 12:15:17 source > Encountered an exception while reading stream transactions
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 119, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 194, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 250, in _read_incremental
    for message_counter, record_data_or_message in enumerate(records, start=1):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py", line 104, in read_records
    yield from self.retriever.read_records(stream_slice)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 304, in read_records
    for stream_data in self._read_pages(self._parse_records, self.state, stream_slice):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 282, in _read_pages
    response = self._fetch_next_page(stream_state, stream_slice, next_page_token)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 256, in _fetch_next_page
    return self.requester.send_request(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 399, in send_request
    return self._validate_response(response)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 496, in _validate_response
    raise ReadException(error_message)
airbyte_cdk.sources.declarative.exceptions.ReadException: Request to https://api-m.paypal.com/v1/reporting/transactions?fields=all&page_size=500&start_date=2023-02-01T01%3A00%3A00Z&end_date=2023-02-16T00%3A59%3A59Z failed with status code 400 and error message Result set size is greater than the maximum limit. Change the filter criteria and try again.
```

### Contribute

- [X] Yes, I want to contribute

**Comment by domzae** [comment]
Most people can probably avoid this error by setting the `Number of days per request` field to low enough (added in #31852).
It's still possible to hit this error using the minimum days (1), and at the very least this limitation and workaround should be mentioned in the docs.

**Comment by murat-cetinkaya** [comment]
This issue is a blocker for us. It's not possible to use this connector since we have some days with more than 10k transactions.

**Comment by Jgerardopine** [comment]
As mentioned by domzaer, you can use the `Number of days per request` to limit to one day. 
If 1 day has more than 10K transactions, what you can do is use a **cron expression** in your replication configuration to ensure the sync runs every X hours/minutes, with the incremental sync, you shouldn't have any problem.

I will keep this open for some weeks and see if there are additional comments.

**Comment by domzae** [comment]
> If 1 day has more than 10K transactions, what you can do is use a **cron expression** in your replication configuration to ensure the sync runs every X hours/minutes, with the incremental sync, you shouldn't have any problem.

Even if a shorter replication interval guarantees less than 10k transactions, you won't be able to "backfill" data like this. Also, any interruption to the connector could then cause the next sync to be larger 10k transactions and fail.
