### ISSUE TITLE
Source Mysql: Failed to synchronize data from MySQL with a binary field.

### ISSUE THREAD

**Issue by felixng1028** [airbytehq/airbyte#31161]
### Connector Name

airbyte/source-mysql

### Connector Version

3.1.1

### What step the error happened?

During the sync

### Relevant information

The exception is occurring in version 3.0.8 but does not occur in 3.0.2. 
I also tested it with version 3.1.1, and the issue still persists.
The field type in MySQL is binary(16), which stores UUID in binary format.

### Relevant log output

```shell
Caused by: java.lang.IllegalArgumentException: contains illegal character for hexBinary: /PMRj4ZHT4yMDlk5WmsyLg==
        at javax.xml.bind.DatatypeConverterImpl.parseHexBinary(DatatypeConverterImpl.java:466)
        at javax.xml.bind.DatatypeConverter.parseHexBinary(DatatypeConverter.java:372)
        at io.airbyte.db.jdbc.AbstractJdbcCompatibleSourceOperations.setBinary(AbstractJdbcCompatibleSourceOperations.java:225)
        at io.airbyte.integrations.source.mysql.MySqlSourceOperations.setCursorField(MySqlSourceOperations.java:157)
        at io.airbyte.integrations.source.mysql.initialsync.MySqlInitialLoadRecordIterator.getPkPreparedStatement(MySqlInitialLoadRecordIterator.java:172)
        at io.airbyte.db.jdbc.StreamingJdbcDatabase.unsafeQuery(StreamingJdbcDatabase.java:66)
        at io.airbyte.integrations.source.mysql.initialsync.MySqlInitialLoadRecordIterator.computeNext(MySqlInitialLoadRecordIterator.java:97)
        ... 36 more
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by mathop** [comment]
I'm experiencing the same problem. Rolling back to 3.0.2 also solved the issue.

**Comment by evantahler** [comment]
Closing as stale - this is a very old version of the connector.  Please re-open a new issue if the issue persists on the latest connector version
