### ISSUE TITLE
Source MongoDB: fails when discovering schema

### ISSUE THREAD

**Issue by johnspackman** [airbytehq/airbyte#31359]
### Connector Name

source-mongodb

### Connector Version

0.2.5

### What step the error happened?

Configuring a new connector

### Relevant information

When creating a connector, it fails saying `Invalid $project :: caused by :: FieldPath must not end with a '.'.'`

I have a MongoDB source and MySQL destination; this is a brand new install.

```
Discovering schema failed
Something went wrong in the connector. See the logs for more details.


Learn more
Internal message: com.mongodb.MongoCommandException: Command failed with error 40353 (Location40353): 'Invalid $project :: caused by :: FieldPath must not end with a '.'.' on server 192.168.86.20:27017. The full response is {"ok": 0.0, "errmsg": "Invalid $project :: caused by :: FieldPath must not end with a '.'.", "code": 40353, "codeName": "Location40353"}
Failure type: system_error
```

### Relevant log output

```shell
2023-10-12 21:19:44 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):124 - Docker volume job log path: /tmp/workspace/0ba4b0ab-afa3-40de-aa4e-6747ffb9d389/0/logs.log
2023-10-12 21:19:44 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):129 - Executing worker wrapper. Airbyte version: 0.50.30
2023-10-12 21:19:44 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitterThrows):290 - Attempt 0 to save workflow id for cancellation
2023-10-12 21:19:44 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2023-10-12 21:19:44 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2023-10-12 21:19:44 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2023-10-12 21:19:44 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2023-10-12 21:19:44 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1228 - Using default value for environment variable LAUNCHDARKLY_KEY: ''
2023-10-12 21:19:44 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - Checking if airbyte/source-mongodb-v2:0.2.5 exists...
2023-10-12 21:19:44 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - airbyte/source-mongodb-v2:0.2.5 was found locally.
2023-10-12 21:19:44 [32mINFO[m i.a.w.p.DockerProcessFactory(create):143 - Creating docker container = source-mongodb-v2-discover-0ba4b0ab-afa3-40de-aa4e-6747ffb9d389-0-etbap with resources io.airbyte.config.ResourceRequirements@e1f0397[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts null
2023-10-12 21:19:44 [32mINFO[m i.a.w.p.DockerProcessFactory(create):196 - Preparing command: docker run --rm --init -i -w /data/0ba4b0ab-afa3-40de-aa4e-6747ffb9d389/0 --log-driver none --name source-mongodb-v2-discover-0ba4b0ab-afa3-40de-aa4e-6747ffb9d389-0-etbap --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/source-mongodb-v2:0.2.5 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e USE_STREAM_CAPABLE_STATE=true -e FIELD_SELECTION_WORKSPACES= -e WORKER_ENVIRONMENT=DOCKER -e AIRBYTE_ROLE= -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=0 -e OTEL_COLLECTOR_ENDPOINT=http://host.docker.internal:4317 -e FEATURE_FLAG_CLIENT=config -e AIRBYTE_VERSION=0.50.30 -e WORKER_JOB_ID=0ba4b0ab-afa3-40de-aa4e-6747ffb9d389 airbyte/source-mongodb-v2:0.2.5 discover --config source_config.json
2023-10-12 21:19:44 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(create):177 - Reading messages from protocol version 0.2.0
2023-10-12 21:19:45 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - INFO i.a.i.s.m.MongoDbSource(main):55 starting source: class io.airbyte.integrations.source.mongodb.MongoDbSource
2023-10-12 21:19:45 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - INFO i.a.i.b.IntegrationCliParser(parseOptions):126 integration args: {discover=null, config=source_config.json}
2023-10-12 21:19:45 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - INFO i.a.i.b.IntegrationRunner(runInternal):106 Running integration: io.airbyte.integrations.source.mongodb.MongoDbSource
2023-10-12 21:19:45 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - INFO i.a.i.b.IntegrationRunner(runInternal):107 Command: DISCOVER
2023-10-12 21:19:45 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - INFO i.a.i.b.IntegrationRunner(runInternal):108 Integration config: IntegrationConfig{command=DISCOVER, configPath='source_config.json', catalogPath='null', statePath='null'}
2023-10-12 21:19:45 [33mWARN[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):309 - WARN c.n.s.JsonMetaSchema(newValidator):278 Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-10-12 21:19:45 [33mWARN[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):309 - WARN c.n.s.JsonMetaSchema(newValidator):278 Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-10-12 21:19:45 [33mWARN[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):309 - WARN c.m.d.l.SLF4JLogger(warn):86 Ignoring unrecognized boolean value 'admin' in the connection string for 'ssl'. Replace with either 'true' or 'false'
2023-10-12 21:19:45 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - INFO c.m.d.l.SLF4JLogger(info):71 Cluster created with settings {hosts=[192.168.86.20:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms'}
2023-10-12 21:19:45 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - INFO c.m.d.l.SLF4JLogger(info):71 Cluster description not yet available. Waiting for 30000 ms before timing out
2023-10-12 21:19:45 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - INFO c.m.d.l.SLF4JLogger(info):71 Opened connection [connectionId{localValue:1, serverValue:985}] to 192.168.86.20:27017
2023-10-12 21:19:45 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - INFO c.m.d.l.SLF4JLogger(info):71 Opened connection [connectionId{localValue:2, serverValue:986}] to 192.168.86.20:27017
2023-10-12 21:19:45 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - INFO c.m.d.l.SLF4JLogger(info):71 Monitor thread successfully connected to server with description ServerDescription{address=192.168.86.20:27017, type=STANDALONE, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=17, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=10119583}
2023-10-12 21:19:45 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - INFO c.m.d.l.SLF4JLogger(info):71 Opened connection [connectionId{localValue:3, serverValue:987}] to 192.168.86.20:27017
2023-10-12 21:19:45 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - INFO c.m.d.l.SLF4JLogger(info):71 Opened connection [connectionId{localValue:4, serverValue:988}] to 192.168.86.20:27017
2023-10-12 21:19:45 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - INFO c.m.d.l.SLF4JLogger(info):71 Opened connection [connectionId{localValue:5, serverValue:989}] to 192.168.86.20:27017
2023-10-12 21:19:45 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - INFO c.m.d.l.SLF4JLogger(info):71 Opened connection [connectionId{localValue:7, serverValue:990}] to 192.168.86.20:27017
2023-10-12 21:19:45 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - INFO c.m.d.l.SLF4JLogger(info):71 Opened connection [connectionId{localValue:8, serverValue:991}] to 192.168.86.20:27017
2023-10-12 21:20:44 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):308 - ERROR i.a.i.b.AirbyteExceptionHandler(uncaughtException):26 Something went wrong in the connector. See the logs for more details. com.mongodb.MongoCommandException: Command failed with error 40353 (Location40353): 'Invalid $project :: caused by :: FieldPath must not end with a '.'.' on server 192.168.86.20:27017. The full response is {"ok": 0.0, "errmsg": "Invalid $project :: caused by :: FieldPath must not end with a '.'.", "code": 40353, "codeName": "Location40353"}
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:198) ~[mongodb-driver-core-4.4.0.jar:?]
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:418) ~[mongodb-driver-core-4.4.0.jar:?]
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:342) ~[mongodb-driver-core-4.4.0.jar:?]
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:116) ~[mongodb-driver-core-4.4.0.jar:?]
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:647) ~[mongodb-driver-core-4.4.0.jar:?]
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:71) ~[mongodb-driver-core-4.4.0.jar:?]
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:244) ~[mongodb-driver-core-4.4.0.jar:?]
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:227) ~[mongodb-driver-core-4.4.0.jar:?]
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:127) ~[mongodb-driver-core-4.4.0.jar:?]
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:117) ~[mongodb-driver-core-4.4.0.jar:?]
	at com.mongodb.internal.connection.DefaultServer$OperationCountTrackingConnection.command(DefaultServer.java:348) ~[mongodb-driver-core-4.4.0.jar:?]
	at com.mongodb.internal.operation.CommandOperationHelper.createReadCommandAndExecute(CommandOperationHelper.java:228) ~[mongodb-driver-core-4.4.0.jar:?]
	at com.mongodb.internal.operation.CommandOperationHelper.lambda$executeRetryableRead$4(CommandOperationHelper.java:210) ~[mongodb-driver-core-4.4.0.jar:?]
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$2(OperationHelper.java:564) ~[mongodb-driver-core-4.4.0.jar:?]
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:589) ~[mongodb-driver-core-4.4.0.jar:?]
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$3(OperationHelper.java:563) ~[mongodb-driver-core-4.4.0.jar:?]
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:589) ~[mongodb-driver-core-4.4.0.jar:?]
	at com.mongodb.internal.operation.OperationHelper.withSourceAndConnection(OperationHelper.java:562) ~[mongodb-driver-core-4.4.0.jar:?]
	at com.mongodb.internal.operation.CommandOperationHelper.lambda$executeRetryableRead$5(CommandOperationHelper.java:207) ~[mongodb-driver-core-4.4.0.jar:?]
	at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:65) ~[mongodb-driver-core-4.4.0.jar:?]
	at com.mongodb.internal.operation.CommandOperationHelper.executeRetryableRead(CommandOperationHelper.java:213) ~[mongodb-driver-core-4.4.0.jar:?]
	at com.mongodb.internal.operation.CommandOperationHelper.executeRetryableRead(CommandOperationHelper.java:193) ~[mongodb-driver-core-4.4.0.jar:?]
	at com.mongodb.internal.operation.AggregateOperationImpl.execute(AggregateOperationImpl.java:195) ~[mongodb-driver-core-4.4.0.jar:?]
	at com.mongodb.internal.operation.AggregateOperation.execute(AggregateOperation.java:306) ~[mongodb-driver-core-4.4.0.jar:?]
	at com.mongodb.internal.operation.AggregateOperation.execute(AggregateOperation.java:46) ~[mongodb-driver-core-4.4.0.jar:?]
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:191) ~[mongodb-driver-sync-4.4.0.jar:?]
	at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:135) ~[mongodb-driver-sync-4.4.0.jar:?]
	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:92) ~[mongodb-driver-sync-4.4.0.jar:?]
	at com.mongodb.client.internal.MongoIterableImpl.cursor(MongoIterableImpl.java:97) ~[mongodb-driver-sync-4.4.0.jar:?]
	at io.airbyte.db.mongodb.MongoUtils.getTypes(MongoUtils.java:315) ~[io.airbyte.airbyte-db-db-lib-24.0.2.jar:?]
	at io.airbyte.db.mongodb.MongoUtils.lambda$setSubFields$1(MongoUtils.java:281) ~[io.airbyte.airbyte-db-db-lib-24.0.2.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at io.airbyte.db.mongodb.MongoUtils.setSubFields(MongoUtils.java:280) ~[io.airbyte.airbyte-db-db-lib-24.0.2.jar:?]
	at io.airbyte.db.mongodb.MongoUtils.lambda$getUniqueFields$0(MongoUtils.java:258) ~[io.airbyte.airbyte-db-db-lib-24.0.2.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at io.airbyte.db.mongodb.MongoUtils.getUniqueFields(MongoUtils.java:261) ~[io.airbyte.airbyte-db-db-lib-24.0.2.jar:?]
	at io.airbyte.integrations.source.mongodb.MongoDbSource.lambda$discoverInternal$1(MongoDbSource.java:113) ~[io.airbyte.airbyte-integrations.connectors-source-mongodb-v2-24.0.2.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[?:?]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

Stack Trace: com.mongodb.MongoCommandException: Command failed with error 40353 (Location40353): 'Invalid $project :: caused by :: FieldPath must not end with a '.'.' on server 192.168.86.20:27017. The full response is {"ok": 0.0, "errmsg": "Invalid $project :: caused by :: FieldPath must not end with a '.'.", "code": 40353, "codeName": "Location40353"}
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:198)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:418)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:342)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:116)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:647)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:71)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:244)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:227)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:127)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:117)
	at com.mongodb.internal.connection.DefaultServer$OperationCountTrackingConnection.command(DefaultServer.java:348)
	at com.mongodb.internal.operation.CommandOperationHelper.createReadCommandAndExecute(CommandOperationHelper.java:228)
	at com.mongodb.internal.operation.CommandOperationHelper.lambda$executeRetryableRead$4(CommandOperationHelper.java:210)
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$2(OperationHelper.java:564)
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:589)
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$3(OperationHelper.java:563)
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:589)
	at com.mongodb.internal.operation.OperationHelper.withSourceAndConnection(OperationHelper.java:562)
	at com.mongodb.internal.operation.CommandOperationHelper.lambda$executeRetryableRead$5(CommandOperationHelper.java:207)
	at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:65)
	at com.mongodb.internal.operation.CommandOperationHelper.executeRetryableRead(CommandOperationHelper.java:213)
	at com.mongodb.internal.operation.CommandOperationHelper.executeRetryableRead(CommandOperationHelper.java:193)
	at com.mongodb.internal.operation.AggregateOperationImpl.execute(AggregateOperationImpl.java:195)
	at com.mongodb.internal.operation.AggregateOperation.execute(AggregateOperation.java:306)
	at com.mongodb.internal.operation.AggregateOperation.execute(AggregateOperation.java:46)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:191)
	at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:135)
	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:92)
	at com.mongodb.client.internal.MongoIterableImpl.cursor(MongoIterableImpl.java:97)
	at io.airbyte.db.mongodb.MongoUtils.getTypes(MongoUtils.java:315)
	at io.airbyte.db.mongodb.MongoUtils.lambda$setSubFields$1(MongoUtils.java:281)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at io.airbyte.db.mongodb.MongoUtils.setSubFields(MongoUtils.java:280)
	at io.airbyte.db.mongodb.MongoUtils.lambda$getUniqueFields$0(MongoUtils.java:258)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at io.airbyte.db.mongodb.MongoUtils.getUniqueFields(MongoUtils.java:261)
	at io.airbyte.integrations.source.mongodb.MongoDbSource.lambda$discoverInternal$1(MongoDbSource.java:113)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

2023-10-12 21:20:45 [33mWARN[m i.a.w.g.DefaultDiscoverCatalogWorker(run):105 - Discover job subprocess finished with exit codee 1
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by evantahler** [comment]
Closing as stale - this is a very old connector version
