### ISSUE TITLE
[destination-aws-datalake] Initial sync hang 

### ISSUE THREAD

**Issue by Seitk** [airbytehq/airbyte#31536]
### Connector Name

aws-datalake

### Connector Version

0.1.3

### What step the error happened?

During the sync

### Relevant information

Create a new connection between MongoDB and AWS Datalake, initial sync takes ages and job history shows 3 attempts
Found duplicated data files in S3 but connection stayed in "syncing"

### Relevant log output

```shell
2023-10-18 02:58:47 INFO i.a.w.i.HeartbeatTimeoutChaperone(runWithHeartbeatThread):115 - thread status... heartbeat thread: false , replication thread: true
2023-10-18 02:58:47 INFO i.a.w.g.BufferedReplicationWorker(writeToDestination):428 - writeToDestination: done. (forDest.isDone:true, isDestRunning:true)
2023-10-18 02:58:47 destination > Received empty state for, resetting all streams including non-incremental streams
2023-10-18 02:58:47 destination > Deleting table cms:products
2023-10-18 02:58:47 destination > Deleting table cms.products
2023-10-18 02:58:48 WARN i.a.w.i.b.DefaultSyncStatsTracker(updateDestinationStateStats):198 - The message tracker encountered an issue that prevents committed record counts from being reliably computed. This only impacts metadata and does not indicate a problem with actual sync data.
io.airbyte.workers.internal.book_keeping.StateDeltaTracker$StateDeltaTrackerException: Delta was not stored for state hash 1727035794
        at io.airbyte.workers.internal.book_keeping.StateDeltaTracker.commitStateHash(StateDeltaTracker.java:128) ~[io.airbyte-airbyte-commons-worker-0.50.30.jar:?]
        at io.airbyte.workers.internal.book_keeping.DefaultSyncStatsTracker.updateDestinationStateStats(DefaultSyncStatsTracker.java:195) ~[io.airbyte-airbyte-commons-worker-0.50.30.jar:?]
        at io.airbyte.workers.internal.sync_persistence.SyncPersistenceImpl.updateDestinationStateStats(SyncPersistenceImpl.java:481) ~[io.airbyte-airbyte-commons-worker-0.50.30.jar:?]
        at io.airbyte.workers.internal.book_keeping.AirbyteMessageTracker.handleDestinationEmittedState(AirbyteMessageTracker.java:116) ~[io.airbyte-airbyte-commons-worker-0.50.30.jar:?]
        at io.airbyte.workers.internal.book_keeping.AirbyteMessageTracker.acceptFromDestination(AirbyteMessageTracker.java:84) ~[io.airbyte-airbyte-commons-worker-0.50.30.jar:?]
        at io.airbyte.workers.general.ReplicationWorkerHelper.internalProcessMessageFromDestination(ReplicationWorkerHelper.java:266) ~[io.airbyte-airbyte-commons-worker-0.50.30.jar:?]
        at io.airbyte.workers.general.ReplicationWorkerHelper.processMessageFromDestination(ReplicationWorkerHelper.java:282) ~[io.airbyte-airbyte-commons-worker-0.50.30.jar:?]
        at io.airbyte.workers.general.BufferedReplicationWorker.readFromDestination(BufferedReplicationWorker.java:450) ~[io.airbyte-airbyte-commons-worker-0.50.30.jar:?]
        at io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsync$2(BufferedReplicationWorker.java:229) ~[io.airbyte-airbyte-commons-worker-0.50.30.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
2023-10-18 02:58:48 WARN i.a.w.i.b.DefaultSyncStatsTracker(updateDestinationStateStats):208 - The state message tracker was unable to match the destination state message to a corresponding source state message.This only impacts metrics and does not indicate a problem with actual sync data.
io.airbyte.workers.internal.book_keeping.StateMetricsTracker$StateMetricsTrackerNoStateMatchException: Destination state message cannot be matched to corresponding Source state message.
        at io.airbyte.workers.internal.book_keeping.StateMetricsTracker.findStartingTimeStampAndRemoveOlderEntries(StateMetricsTracker.java:169) ~[io.airbyte-airbyte-commons-worker-0.50.30.jar:?]
        at io.airbyte.workers.internal.book_keeping.StateMetricsTracker.updateStates(StateMetricsTracker.java:104) ~[io.airbyte-airbyte-commons-worker-0.50.30.jar:?]
        at io.airbyte.workers.internal.book_keeping.DefaultSyncStatsTracker.updateDestinationStateStats(DefaultSyncStatsTracker.java:205) ~[io.airbyte-airbyte-commons-worker-0.50.30.jar:?]
        at io.airbyte.workers.internal.sync_persistence.SyncPersistenceImpl.updateDestinationStateStats(SyncPersistenceImpl.java:481) ~[io.airbyte-airbyte-commons-worker-0.50.30.jar:?]
        at io.airbyte.workers.internal.book_keeping.AirbyteMessageTracker.handleDestinationEmittedState(AirbyteMessageTracker.java:116) ~[io.airbyte-airbyte-commons-worker-0.50.30.jar:?]
        at io.airbyte.workers.internal.book_keeping.AirbyteMessageTracker.acceptFromDestination(AirbyteMessageTracker.java:84) ~[io.airbyte-airbyte-commons-worker-0.50.30.jar:?]
        at io.airbyte.workers.general.ReplicationWorkerHelper.internalProcessMessageFromDestination(ReplicationWorkerHelper.java:266) ~[io.airbyte-airbyte-commons-worker-0.50.30.jar:?]
        at io.airbyte.workers.general.ReplicationWorkerHelper.processMessageFromDestination(ReplicationWorkerHelper.java:282) ~[io.airbyte-airbyte-commons-worker-0.50.30.jar:?]
        at io.airbyte.workers.general.BufferedReplicationWorker.readFromDestination(BufferedReplicationWorker.java:450) ~[io.airbyte-airbyte-commons-worker-0.50.30.jar:?]
        at io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsync$2(BufferedReplicationWorker.java:229) ~[io.airbyte-airbyte-commons-worker-0.50.30.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
2023-10-18 02:58:48 INFO i.a.w.i.s.SyncPersistenceImpl(startBackgroundFlushStateTask):188 - starting state flush thread for connectionId 811857c3-bba9-4f1d-b936-0d066406917f
2023-10-18 02:58:48 destination > Received empty state for, resetting all streams including non-incremental streams
2023-10-18 02:58:48 destination > Deleting table cms:products
2023-10-18 02:58:48 destination > Deleting table cms.products
2023-10-18 02:58:48 destination > Failed to reset table cms:products
2023-10-18 02:58:58 destination > Writing complete.
2023-10-18 02:58:58 INFO i.a.w.g.BufferedReplicationWorker(readFromDestination):464 - readFromDestination: done. (writeToDestFailed:false, dest.isFinished:true)
2023-10-18 02:58:58 INFO i.a.a.c.AirbyteApiClient(retryWithJitterThrows):290 - Attempt 0 to Flush States from SyncPersistenceImpl
2023-10-18 02:58:58 INFO i.a.a.c.AirbyteApiClient(retryWithJitterThrows):295 - Attempt 0 to Flush States from SyncPersistenceImpl error: io.airbyte.api.client.invoker.generated.ApiException: createOrUpdateState call failed with: 500 - {"message":"Internal Server Error: Cannot invoke \"io.airbyte.protocol.models.AirbyteStateMessage.getGlobal()\" because the return value of \"io.airbyte.config.StateWrapper.getGlobal()\" is null","exceptionClassName":"java.lang.NullPointerException","exceptionStack":["java.lang.NullPointerException: Cannot invoke \"io.airbyte.protocol.models.AirbyteStateMessage.getGlobal()\" because the return value of \"io.airbyte.config.StateWrapper.getGlobal()\" is null","\tat io.airbyte.config.persistence.StatePersistence.lambda$updateOrCreateState$1(StatePersistence.java:103)","\tat io.airbyte.db.Database.lambda$transaction$0(Database.java:27)","\tat org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:552)","\tat org.jooq.impl.Tools$3$1.block(Tools.java:5854)","\tat java.base/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3745)","\tat java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3690)","\tat org.jooq.impl.Tools$3.get(Tools.java:5851)","\tat org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:600)","\tat org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:524)","\tat io.airbyte.db.Database.transaction(Database.java:27)","\tat io.airbyte.db.ExceptionWrappingDatabase.transaction(ExceptionWrappingDatabase.java:47)","\tat io.airbyte.config.persistence.StatePersistence.updateOrCreateState(StatePersistence.java:98)","\tat io.airbyte.commons.server.handlers.StateHandler.createOrUpdateState(StateHandler.java:44)","\tat io.airbyte.server.apis.StateApiController.lambda$createOrUpdateState$0(StateApiController.java:40)","\tat io.airbyte.server.apis.ApiHelper.execute(ApiHelper.java:26)","\tat io.airbyte.server.apis.StateApiController.createOrUpdateState(StateApiController.java:40)","\tat io.airbyte.server.apis.$StateApiController$Definition$Exec.dispatch(Unknown Source)","\tat io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371)","\tat io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594)","\tat io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)","\tat io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)","\tat io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)","\tat io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659)","\tat reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)","\tat reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)","\tat reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)","\tat io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62)","\tat reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)","\tat reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)","\tat io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)","\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)","\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)","\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)","\tat java.base/java.lang.Thread.run(Thread.java:1589)"]}
2023-10-18 02:58:59 INFO i.a.a.c.AirbyteApiClient(retryWithJitterThrows):290 - Attempt 1 to Flush States from SyncPersistenceImpl
2023-10-18 02:58:59 INFO i.a.a.c.AirbyteApiClient(retryWithJitterThrows):295 - Attempt 1 to Flush States from SyncPersistenceImpl error: io.airbyte.api.client.invoker.generated.ApiException: createOrUpdateState call failed with: 500 - {"message":"Internal Server Error: Cannot invoke \"io.airbyte.protocol.models.AirbyteStateMessage.getGlobal()\" because the return value of \"io.airbyte.config.StateWrapper.getGlobal()\" is null","exceptionClassName":"java.lang.NullPointerException","exceptionStack":["java.lang.NullPointerException: Cannot invoke \"io.airbyte.protocol.models.AirbyteStateMessage.getGlobal()\" because the return value of \"io.airbyte.config.StateWrapper.getGlobal()\" is null","\tat io.airbyte.config.persistence.StatePersistence.lambda$updateOrCreateState$1(StatePersistence.java:103)","\tat io.airbyte.db.Database.lambda$transaction$0(Database.java:27)","\tat org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:552)","\tat org.jooq.impl.Tools$3$1.block(Tools.java:5854)","\tat java.base/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3745)","\tat java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3690)","\tat org.jooq.impl.Tools$3.get(Tools.java:5851)","\tat org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:600)","\tat org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:524)","\tat io.airbyte.db.Database.transaction(Database.java:27)","\tat io.airbyte.db.ExceptionWrappingDatabase.transaction(ExceptionWrappingDatabase.java:47)","\tat io.airbyte.config.persistence.StatePersistence.updateOrCreateState(StatePersistence.java:98)","\tat io.airbyte.commons.server.handlers.StateHandler.createOrUpdateState(StateHandler.java:44)","\tat io.airbyte.server.apis.StateApiController.lambda$createOrUpdateState$0(StateApiController.java:40)","\tat io.airbyte.server.apis.ApiHelper.execute(ApiHelper.java:26)","\tat io.airbyte.server.apis.StateApiController.createOrUpdateState(StateApiController.java:40)","\tat io.airbyte.server.apis.$StateApiController$Definition$Exec.dispatch(Unknown Source)","\tat io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371)","\tat io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594)","\tat io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)","\tat io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)","\tat io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)","\tat io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659)","\tat reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)","\tat reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)","\tat reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)","\tat io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62)","\tat reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)","\tat reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)","\tat io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)","\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)","\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)","\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)","\tat java.base/java.lang.Thread.run(Thread.java:1589)"]}
2023-10-18 02:59:07 INFO i.a.a.c.AirbyteApiClient(retryWithJitterThrows):290 - Attempt 2 to Flush States from SyncPersistenceImpl
2023-10-18 02:59:07 INFO i.a.a.c.AirbyteApiClient(retryWithJitterThrows):295 - Attempt 2 to Flush States from SyncPersistenceImpl error: io.airbyte.api.client.invoker.generated.ApiException: createOrUpdateState call failed with: 500 - {"message":"Internal Server Error: Cannot invoke \"io.airbyte.protocol.models.AirbyteStateMessage.getGlobal()\" because the return value of \"io.airbyte.config.StateWrapper.getGlobal()\" is null","exceptionClassName":"java.lang.NullPointerException","exceptionStack":["java.lang.NullPointerException: Cannot invoke \"io.airbyte.protocol.models.AirbyteStateMessage.getGlobal()\" because the return value of \"io.airbyte.config.StateWrapper.getGlobal()\" is null","\tat io.airbyte.config.persistence.StatePersistence.lambda$updateOrCreateState$1(StatePersistence.java:103)","\tat io.airbyte.db.Database.lambda$transaction$0(Database.java:27)","\tat org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:552)","\tat org.jooq.impl.Tools$3$1.block(Tools.java:5854)","\tat java.base/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3745)","\tat java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3690)","\tat org.jooq.impl.Tools$3.get(Tools.java:5851)","\tat org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:600)","\tat org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:524)","\tat io.airbyte.db.Database.transaction(Database.java:27)","\tat io.airbyte.db.ExceptionWrappingDatabase.transaction(ExceptionWrappingDatabase.java:47)","\tat io.airbyte.config.persistence.StatePersistence.updateOrCreateState(StatePersistence.java:98)","\tat io.airbyte.commons.server.handlers.StateHandler.createOrUpdateState(StateHandler.java:44)","\tat io.airbyte.server.apis.StateApiController.lambda$createOrUpdateState$0(StateApiController.java:40)","\tat io.airbyte.server.apis.ApiHelper.execute(ApiHelper.java:26)","\tat io.airbyte.server.apis.StateApiController.createOrUpdateState(StateApiController.java:40)","\tat io.airbyte.server.apis.$StateApiController$Definition$Exec.dispatch(Unknown Source)","\tat io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371)","\tat io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594)","\tat io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)","\tat io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)","\tat io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)","\tat io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659)","\tat reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)","\tat reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)","\tat reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)","\tat io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62)","\tat reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)","\tat reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)","\tat io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)","\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)","\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)","\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)","\tat java.base/java.lang.Thread.run(Thread.java:1589)"]}
2023-10-18 03:09:07 INFO i.a.a.c.AirbyteApiClient(retryWithJitterThrows):290 - Attempt 3 to Flush States from SyncPersistenceImpl
2023-10-18 03:09:07 INFO i.a.a.c.AirbyteApiClient(retryWithJitterThrows):295 - Attempt 3 to Flush States from SyncPersistenceImpl error: io.airbyte.api.client.invoker.generated.ApiException: createOrUpdateState call failed with: 500 - {"message":"Internal Server Error: Cannot invoke \"io.airbyte.protocol.models.AirbyteStateMessage.getGlobal()\" because the return value of \"io.airbyte.config.StateWrapper.getGlobal()\" is null","exceptionClassName":"java.lang.NullPointerException","exceptionStack":["java.lang.NullPointerException: Cannot invoke \"io.airbyte.protocol.models.AirbyteStateMessage.getGlobal()\" because the return value of \"io.airbyte.config.StateWrapper.getGlobal()\" is null","\tat io.airbyte.config.persistence.StatePersistence.lambda$updateOrCreateState$1(StatePersistence.java:103)","\tat io.airbyte.db.Database.lambda$transaction$0(Database.java:27)","\tat org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:552)","\tat org.jooq.impl.Tools$3$1.block(Tools.java:5854)","\tat java.base/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3745)","\tat java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3690)","\tat org.jooq.impl.Tools$3.get(Tools.java:5851)","\tat org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:600)","\tat org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:524)","\tat io.airbyte.db.Database.transaction(Database.java:27)","\tat io.airbyte.db.ExceptionWrappingDatabase.transaction(ExceptionWrappingDatabase.java:47)","\tat io.airbyte.config.persistence.StatePersistence.updateOrCreateState(StatePersistence.java:98)","\tat io.airbyte.commons.server.handlers.StateHandler.createOrUpdateState(StateHandler.java:44)","\tat io.airbyte.server.apis.StateApiController.lambda$createOrUpdateState$0(StateApiController.java:40)","\tat io.airbyte.server.apis.ApiHelper.execute(ApiHelper.java:26)","\tat io.airbyte.server.apis.StateApiController.createOrUpdateState(StateApiController.java:40)","\tat io.airbyte.server.apis.$StateApiController$Definition$Exec.dispatch(Unknown Source)","\tat io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371)","\tat io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594)","\tat io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)","\tat io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)","\tat io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)","\tat io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659)","\tat reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)","\tat reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)","\tat reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)","\tat io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62)","\tat reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)","\tat reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)","\tat io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)","\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)","\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)","\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)","\tat java.base/java.lang.Thread.run(Thread.java:1589)"]}
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
