### ISSUE TITLE
Response error being masked by python error in _try_get_error

### ISSUE THREAD

**Issue by tjhiggins** [airbytehq/airbyte#31661]
### What method are you using to run Airbyte?

Docker

### Platform Version or Helm Chart Version

0.50.31

### What step the error happened?

During the Sync

### Revelant information

Developing a connector using the builder for Chorus. Found that a 404 error was getting masked by a python error trying to get the error.

### Relevant log output

```shell
2023-10-19 14:10:18 source > Starting syncing ManifestDeclarativeSource
2023-10-19 14:10:18 source > Marking stream Conversation as STARTED
2023-10-19 14:10:18 source > Syncing stream: Conversation 
2023-10-19 14:10:18 destination > INFO i.a.i.d.p.PostgresDestination(main):98 starting destination: class io.airbyte.integrations.destination.postgres.PostgresDestination
2023-10-19 14:10:18 destination > INFO i.a.i.b.IntegrationCliParser(parseOptions):126 integration args: {catalog=destination_catalog.json, write=null, config=destination_config.json}
2023-10-19 14:10:18 destination > INFO i.a.i.b.IntegrationRunner(runInternal):106 Running integration: io.airbyte.integrations.base.ssh.SshWrappedDestination
2023-10-19 14:10:18 destination > INFO i.a.i.b.IntegrationRunner(runInternal):107 Command: WRITE
2023-10-19 14:10:18 destination > INFO i.a.i.b.IntegrationRunner(runInternal):108 Integration config: IntegrationConfig{command=WRITE, configPath='destination_config.json', catalogPath='destination_catalog.json', statePath='null'}
2023-10-19 14:10:18 destination > WARN c.n.s.JsonMetaSchema(newValidator):278 Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-10-19 14:10:18 destination > WARN c.n.s.JsonMetaSchema(newValidator):278 Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-10-19 14:10:19 destination > INFO i.a.i.b.s.SshTunnel(getInstance):204 Starting connection with method: NO_TUNNEL
2023-10-19 14:10:19 destination > INFO c.z.h.HikariDataSource(<init>):80 HikariPool-1 - Starting...
2023-10-19 14:10:19 destination > INFO c.z.h.HikariDataSource(<init>):82 HikariPool-1 - Start completed.
2023-10-19 14:10:19 destination > INFO i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):103 Write config: WriteConfig{streamName=Conversation, namespace=chorus-test, outputSchemaName=chorus_test, tmpTableName=_airbyte_tmp_ice_Conversation, outputTableName=_airbyte_raw_Conversation, syncMode=append}
2023-10-19 14:10:19 destination > INFO i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):103 Write config: WriteConfig{streamName=Conversations, namespace=chorus-test, outputSchemaName=chorus_test, tmpTableName=_airbyte_tmp_yqz_Conversations, outputTableName=_airbyte_raw_Conversations, syncMode=append_dedup}
2023-10-19 14:10:19 destination > INFO i.a.i.d.b.BufferedStreamConsumer(startTracked):173 class io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer started.
2023-10-19 14:10:19 destination > INFO i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):142 Preparing raw tables in destination started for 2 streams
2023-10-19 14:10:19 destination > INFO i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):147 Preparing raw table in destination started for stream Conversation. schema: chorus_test, table name: _airbyte_raw_Conversation
2023-10-19 14:10:19 destination > INFO i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):147 Preparing raw table in destination started for stream Conversations. schema: chorus_test, table name: _airbyte_raw_Conversations
2023-10-19 14:10:19 destination > INFO i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):160 Preparing raw tables in destination completed.
2023-10-19 14:10:21 source > Marking stream Conversation as RUNNING
2023-10-19 14:10:24 source > Encountered an exception while reading stream Conversation
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 119, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 194, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 304, in _read_full_refresh
    for record_data_or_message in record_data_or_messages:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py", line 104, in read_records
    yield from self.retriever.read_records(stream_slice)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 304, in read_records
    for stream_data in self._read_pages(self._parse_records, self.state, stream_slice):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 282, in _read_pages
    response = self._fetch_next_page(stream_state, stream_slice, next_page_token)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 256, in _fetch_next_page
    return self.requester.send_request(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 399, in send_request
    return self._validate_response(response)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 494, in _validate_response
    or f"Request to {response.request.url} failed with status code {response.status_code} and error message {HttpRequester.parse_response_error_message(response)}"
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 534, in parse_response_error_message
    error = _try_get_error(body)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 529, in _try_get_error
    return _try_get_error(new_value)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 519, in _try_get_error
    return ", ".join(_try_get_error(v) for v in value)
TypeError: sequence item 0: expected str instance, NoneType found
2023-10-19 14:10:24 source > Marking stream Conversation as STOPPED
2023-10-19 14:10:24 source > Finished syncing Conversation
```

**Comment by maxi297** [comment]
[Here](https://airbytehq.sentry.io/issues/4375206970/?project=6527718&query=connector_repository%3Aairbyte%2Fsource-declarative-manifest&referrer=issue-stream&statsPeriod=14d&stream_index=3) is the Sentry alert for more information

**Comment by girarda** [comment]
## Acceptance criteria
- [ ] _try_get_error does not swallow exceptions
