### ISSUE TITLE
[source-pipedrive] TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by pato0301** [airbytehq/airbyte#31907]
### Connector Name

Pipedrive

### Connector Version

2.1.0

### What step the error happened?

During the sync

### Relevant information

I've tried to migrate to the version `2.1.0` of the `Pipedrive` connector but when I did a sync an error related with python made the sync failed. Currently I am at version `1.0.0`

Also, we are using Bigquery GCS with Destination V2 (destination version 2.1.5)

Also, I am syncing the following models:

- activities [ incremental | append + deduped ]
- activity_fields [ Full refresh | overwrite ]
- deal_fields [ Full refresh | overwrite ]
- deals [ incremental | append + deduped ]
- stages [ Full refresh | overwrite ]
- user [ Full refresh | overwrite ]

Also, none of the model have much data, we probably done reach 500MB between all models.

### Relevant log output

```shell
2023-10-24 11:14:35 source > Marking stream stages as STARTED
102
2023-10-24 11:14:35 source > Syncing stream: stages 
103
2023-10-24 11:14:36 source > Encountered an exception while reading stream stages
104
Traceback (most recent call last):
105
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 119, in read
106
    yield from self._read_stream(
107
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 194, in _read_stream
108
    for record in record_iterator:
109
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 304, in _read_full_refresh
110
    for record_data_or_message in record_data_or_messages:
111
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py", line 104, in read_records
112
    yield from self.retriever.read_records(stream_slice)
113
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 305, in read_records
114
    most_recent_record_from_slice = self._get_most_recent_record(most_recent_record_from_slice, stream_data, stream_slice)
115
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 315, in _get_most_recent_record
116
    if self.cursor and (record := self._extract_record(stream_data, stream_slice)):
117
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/types.py", line 38, in __len__
118
    return len(self._data)
119
TypeError: object of type 'NoneType' has no len()
120
2023-10-24 11:14:36 source > Marking stream stages as STOPPED
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
