### ISSUE TITLE
[destination-elasticsearch] MongoDB -> ElasticSearch failed to parse field [_id] of type [_id]

### ISSUE THREAD

**Issue by parkee** [airbytehq/airbyte#31943]
### Connector Name

destination-elasticsearch

### Connector Version

0.1.6

### What step the error happened?

During the sync

### Relevant information

MongoDB -> ElasticSearch sync fails because _id is a reserved name in ElasticSearch, and the MongoDB id field is also _id.
Unfortunately, in our case, the MongoDB "_id" represents a "business" id rather than an auto-generated value, and it needs to be synced.
It would be great if either the destination connector took into account "reserved" field names and used corresponding non-reserved names such as _id -> id, _index -> index, etc., or (better) there would be a way to control the field name mapping manually.

### Relevant log output

```shell
Stack Trace: java.lang.Exception: failed to write bulk records for index: mydb_mycollection 
error type: document_parsing_exception
 reason: [1:8] failed to parse field [_id] of type [_id] in document with id '2bce4d15-f5dd-435d-a3db-aff7f2c79515'. Preview of field's value: '0xffead88'
        at io.airbyte.integrations.destination.elasticsearch.ElasticsearchAirbyteMessageConsumerFactory.lambda$recordWriterFunction$3(ElasticsearchAirbyteMessageConsumerFactory.java:97)
        at io.airbyte.integrations.destination.record_buffer.InMemoryRecordBufferingStrategy.flushAll(InMemoryRecordBufferingStrategy.java:86)
        at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.close(BufferedStreamConsumer.java:172)
        at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.close(FailureTrackingAirbyteMessageConsumer.java:64)
        at io.airbyte.integrations.base.AirbyteMessageConsumer$1.close(AirbyteMessageConsumer.java:59)
        at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:147)
        at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:97)
        at io.airbyte.integrations.destination.elasticsearch.ElasticsearchDestination.main(ElasticsearchDestination.java:31)
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
