### ISSUE TITLE
Complete result exceeds size limit (4442047 of 4194304)

### ISSUE THREAD

**Issue by Amanraj0007** [airbytehq/airbyte#31954]
### What method are you using to run Airbyte?

Docker

### Platform Version or Helm Chart Version

0.50.31

### What step the error happened?

During the Sync

### Revelant information

1> created a connection which syncs data from postgres to snowflake.

- postgres database have multiple schemas and am trying to sync all the schemas.

2> sync failed checked logs of sync connection on airbyte UI
3> source and destination checks are successfully ended.
4> errors after source and destination check 

> 2023-10-29 20:32:23 INFO i.a.w.t.s.a.AppendToAttemptLogActivityImpl(log):56 - Retry State: RetryManager(completeFailureBackoffPolicy=BackoffPolicy(minInterval=PT10S, maxInterval=PT30M, base=3), partialFailureBackoffPolicy=null, successiveCompleteFailureLimit=5, totalCompleteFailureLimit=10, successivePartialFailureLimit=1000, totalPartialFailureLimit=10, successiveCompleteFailures=1, totalCompleteFailures=1, successivePartialFailures=0, totalPartialFailures=0)
 Backoff before next attempt: 10 seconds
 
 5> some more logs in logs page 
 
> Failure reason: Something went wrong within the airbyte platform

> io.temporal.failure.ActivityFailure: scheduledEventId=120, startedEventId=121, activityType='GetSyncWorkflowInputWithAttemptNumber', activityId='bc1c63b7-0e66-3a23-bd28-6c32c57dd67d', identity='1@ip-10-9-16-89.ec2.internal', retryState=RETRY_STATE_MAXIMUM_ATTEMPTS_REACHED

Attaching logs below which i found from worker (STDOUT) containers.

`io.airbyte.commons.temporal.exception.SizeLimitException: Complete result exceeds size limit (4442047 of 4194304)
	at io.airbyte.commons.temporal.utils.PayloadChecker.validatePayloadSize(PayloadChecker.java:33) ~[io.airbyte-airbyte-commons-temporal-0.50.31.jar:?]`

### Relevant log output

```shell
2023-10-29 18:33:44 INFO i.a.a.c.AirbyteApiClient(retryWithJitterThrows):290 - Attempt 0 to Create job input.
2023-10-29 18:33:45 WARN i.t.i.a.ActivityTaskExecutors$BaseActivityTaskExecutor(execute):114 - Activity failure. ActivityId=03c1b556-c86d-3d2c-837f-f6dab78d46d1, activityType=GetSyncWorkflowInputWithAttemptNumber, attempt=1
io.airbyte.commons.temporal.exception.SizeLimitException: Complete result exceeds size limit (4442047 of 4194304)
	at io.airbyte.commons.temporal.utils.PayloadChecker.validatePayloadSize(PayloadChecker.java:33) ~[io.airbyte-airbyte-commons-temporal-0.50.31.jar:?]
	at io.airbyte.workers.temporal.scheduling.activities.GenerateInputActivityImpl.getSyncWorkflowInput(GenerateInputActivityImpl.java:48) ~[io.airbyte-airbyte-workers-0.50.31.jar:?]
	at io.airbyte.workers.temporal.scheduling.activities.GenerateInputActivityImpl.getSyncWorkflowInputWithAttemptNumber(GenerateInputActivityImpl.java:58) ~[io.airbyte-airbyte-workers-0.50.31.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at io.temporal.internal.activity.RootActivityInboundCallsInterceptor$POJOActivityInboundCallsInterceptor.executeActivity(RootActivityInboundCallsInterceptor.java:64) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.activity.RootActivityInboundCallsInterceptor.execute(RootActivityInboundCallsInterceptor.java:43) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.activity.ActivityTaskExecutors$BaseActivityTaskExecutor.execute(ActivityTaskExecutors.java:95) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.activity.ActivityTaskHandlerImpl.handle(ActivityTaskHandlerImpl.java:92) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handleActivity(ActivityWorker.java:241) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:206) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:179) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93) ~[temporal-sdk-1.17.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

**Comment by octavia-squidington-iii** [comment]
Zendesk ticket #[4365](https://airbyte1416.zendesk.com/agent/tickets/4365) has been linked to this issue.

**Comment by rwask** [comment]
This issue is effecting a large Salesforce stream job of only 1 schema with over 50gb of data (there are  over 30 million new rows being introduced.) Other smaller streams are not an issue but each attempt is failing while waiting for the data from Salesforce after the 3 hour heartbeat limit is reached.

**Comment by octavia-squidington-iii** [comment]
Zendesk ticket #[4365](https://airbyte1416.zendesk.com/agent/tickets/4365) has been linked to this issue.

**Comment by davinchia** [comment]
This is no longer relevant after Airbyte 1.0. Please upgrade and try again!
