### ISSUE TITLE
Destination Bigquery (denormalized): Propagate column changes setting not applying non-breaking changes on destination table

### ISSUE THREAD

**Issue by Stu-Selina** [airbytehq/airbyte#31970]
### Connector Name

destination-bigquery-denormalized

### Connector Version

1.5.3

### What step the error happened?

None

### Relevant information

I have a connection to bigquery set up with the 'Propagate column changes only' setting enabled. When a new non-breaking column change was detected, I was prompted to review it and save the changes. 

I did not reset the affected stream when saving the change, because my understanding is that the propagation function should be able to handle this without resetting the table. (I also confirmed this as best I could with the AI bot on slack before doing it!)

However the change was not then applied to the destination table, and the next time the sync ran, an error was thrown on the load job saying that it cannot add the new field. I needed to manually alter the table and add the field in bigquery to get it to work again.

![image](https://github.com/airbytehq/airbyte/assets/105647611/1d6bc84c-a491-4034-b7ae-b2d185dc2748)

### Relevant log output

```shell
        
	at io.airbyte.integrations.destination.bigquery.BigQueryUtils.waitForJobFinish(BigQueryUtils.java:443)
	at io.airbyte.integrations.destination.bigquery.BigQueryGcsOperations.lambda$copyIntoTableFromStage$0(BigQueryGcsOperations.java:151)
	... 27 more
Caused by: com.google.cloud.bigquery.BigQueryException: Provided Schema does not match Table selina-bigquery-prod:source_salesforce_prod.Opportunity. Cannot add fields (field: pcfEligibility__c)
	at com.google.cloud.bigquery.Job.reload(Job.java:419)
	at com.google.cloud.bigquery.Job.waitFor(Job.java:252)
	at io.airbyte.integrations.destination.bigquery.BigQueryUtils.waitForJobFinish(BigQueryUtils.java:438)
	... 28 more
,retryable=<null>,timestamp=1698678584880,additionalProperties={}], io.airbyte.config.FailureReason@3e0d370b[failureOrigin=destination,failureType=<null>,internalMessage=Destination process exited with non-zero exit code 1,externalMessage=Something went wrong within the destination connector,metadata=io.airbyte.config.Metadata@6c62a867[additionalProperties={attemptNumber=1, jobId=311, connector_command=write}],stacktrace=io.airbyte.workers.internal.exception.DestinationException: Destination process exited with non-zero exit code 1
	at io.airbyte.workers.general.BufferedReplicationWorker.readFromDestination(BufferedReplicationWorker.java:424)
	at io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsync$2(BufferedReplicationWorker.java:209)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
,retryable=<null>,timestamp=1698678585815,additionalProperties={}], io.airbyte.config.FailureReason@7f1b6b54[failureOrigin=destination,failureType=<null>,internalMessage=Destination process message delivery failed,externalMessage=Something went wrong within the destination connector,metadata=io.airbyte.config.Metadata@602de5df[additionalProperties={attemptNumber=1, jobId=311, connector_command=write}],stacktrace=io.airbyte.workers.internal.exception.DestinationException: Destination process message delivery failed
	at io.airbyte.workers.general.BufferedReplicationWorker.writeToDestination(BufferedReplicationWorker.java:395)
	at io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsync$2(BufferedReplicationWorker.java:209)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.net.SocketException: Socket closed
	at java.base/sun.nio.ch.NioSocketImpl.ensureOpenAndConnected(NioSocketImpl.java:163)
	at java.base/sun.nio.ch.NioSocketImpl.beginWrite(NioSocketImpl.java:356)
	at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:401)
	at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:433)
	at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:812)
	at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1120)
	at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:313)
	at java.base/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:409)
	at java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:414)
	at java.base/sun.nio.cs.StreamEncoder.lockedFlush(StreamEncoder.java:218)
	at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:205)
	at java.base/java.io.OutputStreamWriter.flush(OutputStreamWriter.java:263)
	at java.base/java.io.BufferedWriter.implFlush(BufferedWriter.java:372)
	at java.base/java.io.BufferedWriter.flush(BufferedWriter.java:359)
	at io.airbyte.workers.internal.DefaultAirbyteMessageBufferedWriter.flush(DefaultAirbyteMessageBufferedWriter.java:31)
	at io.airbyte.workers.internal.DefaultAirbyteDestination.notifyEndOfInput(DefaultAirbyteDestination.java:117)
	at io.airbyte.workers.general.BufferedReplicationWorker.writeToDestination(BufferedReplicationWorker.java:389)
	... 5 more
,retryable=<null>,timestamp=1698678585826,additionalProperties={}], io.airbyte.config.FailureReason@37cf33be[failureOrigin=source,failureType=<null>,internalMessage=Source process read attempt failed,externalMessage=Something went wrong within the source connector,metadata=io.airbyte.config.Metadata@4e9784b0[additionalProperties={attemptNumber=1, jobId=311, connector_command=read}],stacktrace=io.airbyte.workers.internal.exception.SourceException: Source process read attempt failed
	at io.airbyte.workers.general.BufferedReplicationWorker.readFromSource(BufferedReplicationWorker.java:323)
	at io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsyncWithHeartbeatCheck$3(BufferedReplicationWorker.java:216)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.IllegalStateException: Source process is still alive, cannot retrieve exit value.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:502)
	at io.airbyte.workers.internal.DefaultAirbyteSource.getExitValue(DefaultAirbyteSource.java:114)
	at io.airbyte.workers.general.BufferedReplicationWorker.readFromSource(BufferedReplicationWorker.java:309)
	... 5 more
,retryable=<null>,timestamp=1698678593786,additionalProperties={}]],additionalProperties={}]
2023-10-30 15:10:11 INFO i.a.w.t.s.ReplicationActivityImpl(lambda$replicate$3):165 - Sync summary length: 195379
2023-10-30 15:10:11 INFO i.a.c.t.TemporalUtils(withBackgroundHeartbeat):316 - Stopping temporal heartbeating...
2023-10-30 15:10:58 INFO i.a.a.c.AirbyteApiClient(retryWithJitterThrows):258 - Attempt 0 to Get a connection by connection Id
2023-10-30 15:10:58 INFO i.a.a.c.AirbyteApiClient(retryWithJitterThrows):258 - Attempt 0 to get the most recent source actor catalog
2023-10-30 15:10:59 INFO i.a.a.c.AirbyteApiClient(retryWithJitterThrows):258 - Attempt 0 to Retrieve Id of the workspace for the source
2023-10-30 15:10:59 INFO i.a.a.c.AirbyteApiClient(retryWithJitterThrows):258 - Attempt 0 to Get a connection by connection Id
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
This connector is outdated and will not receive further updates. Please use Destination Bigquery Dv2 instead.
