### ISSUE TITLE
Airbyte worker fails to start in Kubernetes (`0.50.33`)

### ISSUE THREAD

**Issue by adamstrawson** [airbytehq/airbyte#32036]
Opening here for visibility, as it feels like an issue since it's an out the box installation. 

### Discussed in https://github.com/airbytehq/airbyte/discussions/31959

<div type='discussions-op-text'>

<sup>Originally posted by **adamstrawson** October 30, 2023</sup>
I'm new to Airbyte, and getting familiar with its setup ahead of our data team using it more widely. 

We've setup Airbyte within Kubernetes (GKE) via the Airbyte helm charts.  Helm values are pretty much the default with the exception of `externalDatabase` and `logs`. 

All pods are running successfully, with the exception of the worker pods, which are failing to start-up. 

```log
2023-10-30 13:51:46 INFO i.m.c.e.DefaultEnvironment(<init>):167 - Established active environments: [k8s, cloud, gcp, control-plane]
2023-10-30 13:51:47 INFO i.m.l.PropertiesLoggingLevelsConfigurer(configureLogLevelForPrefix):111 - Setting log level 'DEBUG' for logger: 'io.airbyte.bootloader'
2023-10-30 13:51:48 INFO i.a.f.ConfigFileClient(<init>):105 - path /flags does not exist, will return default flag values
2023-10-30 13:51:48 INFO i.a.c.EnvConfigs(getEnvOrDefault):1158 - Using default value for environment variable METRIC_CLIENT: ''
2023-10-30 13:51:48 INFO i.a.c.EnvConfigs(getEnvOrDefault):1158 - Using default value for environment variable METRIC_CLIENT: ''
2023-10-30 13:51:49 WARN i.a.m.l.MetricClientFactory(initialize):74 - MetricClient was not recognized or not provided. Accepted values are `datadog` or `otel`. 
2023-10-30 13:51:49 ERROR i.m.r.Micronaut(handleStartupException):338 - Error starting Micronaut server: Error instantiating bean of type  [io.airbyte.workers.orchestrator.KubeOrchestratorHandleFactory]

Path Taken: new ApplicationInitializer() --> ApplicationInitializer.syncActivities --> List.syncActivities([ReplicationActivity replicationActivity],NormalizationActivity normalizationActivity,DbtTransformationActivity dbtTransformationActivity,NormalizationSummaryCheckActivity normalizationSummaryCheckActivity,WebhookOperationActivity webhookOperationActivity,ConfigFetchActivity configFetchActivity,RefreshSchemaActivity refreshSchemaActivity) --> new ReplicationActivityImpl(SecretsHydrator secretsHydrator,Path workspaceRoot,WorkerEnvironment workerEnvironment,LogConfigs logConfigs,String airbyteVersion,AirbyteConfigValidator airbyteConfigValidator,TemporalUtils temporalUtils,AirbyteApiClient airbyteApiClient,[OrchestratorHandleFactory orchestratorHandleFactory],MetricClient metricClient,FeatureFlagClient featureFlagClient) --> new KubeOrchestratorHandleFactory([ContainerOrchestratorConfig containerOrchestratorConfig],WorkerConfigsProvider workerConfigsProvider,FeatureFlagClient featureFlagClient,Integer serverPort,MetricClient metricClient)
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.airbyte.workers.orchestrator.KubeOrchestratorHandleFactory]

Path Taken: new ApplicationInitializer() --> ApplicationInitializer.syncActivities --> List.syncActivities([ReplicationActivity replicationActivity],NormalizationActivity normalizationActivity,DbtTransformationActivity dbtTransformationActivity,NormalizationSummaryCheckActivity normalizationSummaryCheckActivity,WebhookOperationActivity webhookOperationActivity,ConfigFetchActivity configFetchActivity,RefreshSchemaActivity refreshSchemaActivity) --> new ReplicationActivityImpl(SecretsHydrator secretsHydrator,Path workspaceRoot,WorkerEnvironment workerEnvironment,LogConfigs logConfigs,String airbyteVersion,AirbyteConfigValidator airbyteConfigValidator,TemporalUtils temporalUtils,AirbyteApiClient airbyteApiClient,[OrchestratorHandleFactory orchestratorHandleFactory],MetricClient metricClient,FeatureFlagClient featureFlagClient) --> new KubeOrchestratorHandleFactory([ContainerOrchestratorConfig containerOrchestratorConfig],WorkerConfigsProvider workerConfigsProvider,FeatureFlagClient featureFlagClient,Integer serverPort,MetricClient metricClient)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2367) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.airbyte.workers.orchestrator.$KubeOrchestratorHandleFactory$Definition.build(Unknown Source) ~[io.airbyte-airbyte-commons-worker-0.50.33.jar:?]
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.10.1.jar:3.10.1]
<snip>
```

I can't find much information on this error, or any existing issues etc, so I've hit a bit of a wall with troubleshooting. Does anyone have any pointers?</div>

**Comment by adamstrawson** [comment]
Closing as duplicate of https://github.com/airbytehq/airbyte/issues/31988
