### ISSUE TITLE
Config errors not handled correctly on cloud / Kubernetes

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#32133]
### What method are you using to run Airbyte?

Docker

### Platform Version or Helm Chart Version

latest

### What step the error happened?

During the Sync

### Revelant information

When running a sync that emits an error trace message, it's not propagated correctly on cloud, but it works fine when running locally via docker compose:

These two syncs run into the same issue that emits a trace error message, but only when running via docker the error is handled correctly. It looks like on Kubernetes (or just cloud, didn't check that), the trace message is not propagated correctly but wrapped in an "unknown failure".

<img width="1248" alt="Screenshot 2023-11-03 at 11 34 59" src="https://github.com/airbytehq/airbyte/assets/1508364/4fd973b0-a259-4e1e-8125-d0eb161798f8">
<img width="1265" alt="Screenshot 2023-11-03 at 11 34 53" src="https://github.com/airbytehq/airbyte/assets/1508364/11795b9c-1293-4aac-a1b7-f56b1a9fe43d">

### Relevant log output

```shell
On OSS via docker compose:

2023-11-03 10:29:52 destination > No text fields found in record
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 11, in <module></module>
    DestinationWeaviate().run(sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/destinations/destination.py", line 119, in run
    for message in output_messages:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/destinations/destination.py", line 113, in run_cmd
    yield from self._run_write(config=config, configured_catalog_path=parsed_args.catalog, input_stream=wrapped_stdin)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/destinations/destination.py", line 49, in _run_write
    yield from self.write(config=config, configured_catalog=catalog, input_messages=input_messages)
  File "/airbyte/integration_code/destination_weaviate/destination.py", line 38, in write
    yield from writer.write(configured_catalog, input_messages)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/destinations/vector_db_based/writer.py", line 62, in write
    record_documents, record_id_to_delete = self.processor.process(message.record)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/destinations/vector_db_based/document_processor.py", line 109, in process
    raise AirbyteTracedException(
airbyte_cdk.utils.traced_exception.AirbyteTracedException: No text fields found in record
2023-11-03 10:29:52 INFO i.a.w.g.BufferedReplicationWorker(readFromDestination):461 - readFromDestination: exception caught
io.airbyte.workers.internal.exception.DestinationException: Destination process exited with non-zero exit code 1
        at io.airbyte.workers.general.BufferedReplicationWorker.readFromDestination(BufferedReplicationWorker.java:455) ~[io.airbyte-airbyte-commons-worker-dev.jar:?]
        at io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsync$2(BufferedReplicationWorker.java:229) ~[io.airbyte-airbyte-commons-worker-dev.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
2023-11-03 10:29:52 INFO i.a.w.g.BufferedReplicationWorker(readFromDestination):464 - readFromDestination: done. (writeToDestFailed:false, dest.isFinished:true)
```

On cloud:
```
2023-11-01 18:42:17 destination > No text fields found in record
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 11, in <module>
    DestinationWeaviate().run(sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/destinations/destination.py", line 119, in run
    for message in output_messages:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/destinations/destination.py", line 113, in run_cmd
    yield from self._run_write(config=config, configured_catalog_path=parsed_args.catalog, input_stream=wrapped_stdin)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/destinations/destination.py", line 49, in _run_write
    yield from self.write(config=config, configured_catalog=catalog, input_messages=input_messages)
  File "/airbyte/integration_code/destination_weaviate/destination.py", line 38, in write
    yield from writer.write(configured_catalog, input_messages)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/destinations/vector_db_based/writer.py", line 62, in write
    record_documents, record_id_to_delete = self.processor.process(message.record)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/destinations/vector_db_based/document_processor.py", line 109, in process
    raise AirbyteTracedException(
airbyte_cdk.utils.traced_exception.AirbyteTracedException: No text fields found in record
2023-11-01 18:42:18 replication-orchestrator > (pod: jobs / destination-weaviate-write-5677463-0-xjwsk) - Closed all resources for pod
2023-11-01 18:42:18 replication-orchestrator > Sync worker failed.
java.util.concurrent.ExecutionException: io.airbyte.workers.internal.exception.DestinationException: Destination process exited with non-zero exit code 1
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
        at io.airbyte.workers.general.DefaultReplicationWorker.replicate(DefaultReplicationWorker.java:226) ~[io.airbyte-airbyte-commons-worker-dev-e1f296b48d.jar:?]
        at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:160) ~[io.airbyte-airbyte-commons-worker-dev-e1f296b48d.jar:?]
        at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:70) ~[io.airbyte-airbyte-commons-worker-dev-e1f296b48d.jar:?]
        at io.airbyte.container_orchestrator.orchestrator.ReplicationJobOrchestrator.runJob(ReplicationJobOrchestrator.java:91) ~[io.airbyte-airbyte-container-orchestrator-dev-e1f296b48d.jar:?]
        at io.airbyte.container_orchestrator.Application.run(Application.java:78) ~[io.airbyte-airbyte-container-orchestrator-dev-e1f296b48d.jar:?]
        at io.airbyte.container_orchestrator.Application.main(Application.java:38) ~[io.airbyte-airbyte-container-orchestrator-dev-e1f296b48d.jar:?]
Caused by: io.airbyte.workers.internal.exception.DestinationException: Destination process exited with non-zero exit code 1
        at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromDstRunnable$8(DefaultReplicationWorker.java:338) ~[io.airbyte-airbyte-commons-worker-dev-e1f296b48d.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
2023-11-01 18:42:20 INFO i.a.w.t.s.a.AppendToAttemptLogActivityImpl(log):56 - Retry State: RetryManager(completeFailureBackoffPolicy=BackoffPolicy(minInterval=PT10S, maxInterval=PT30M, base=3), partialFailureBackoffPolicy=null, successiveCompleteFailureLimit=5, totalCompleteFailureLimit=5, successivePartialFailureLimit=1000, totalPartialFailureLimit=10, successiveCompleteFailures=1, totalCompleteFailures=1, successivePartialFailures=0, totalPartialFailures=0)
 Backoff before next attempt: 10 seconds
2023-11-01 18:42:19 WARN i.a.w.p.AsyncOrchestratorPodProcess(computeExitValue):152 - State Store reports orchestrator pod orchestrator-repl-job-5677463-attempt-0 failed
```
```

**Comment by pmossman** [comment]
@jpefaur we're looking at this in Compose, and thinking that it makes more sense as a Move issue. Curious if this is related to the investigations into errors that you've been working on?
