### ISSUE TITLE
Docker startup error in version 0.50.34 of airbyte-server

### ISSUE THREAD

**Issue by toidang92** [airbytehq/airbyte#32450]
### What method are you using to run Airbyte?

Docker

### Platform Version or Helm Chart Version

0.50.34

### What step the error happened?

Other

### Revelant information

When I upgraded Airbyte from version 0.50.33 to 0.50.34, I encountered an error as shown in the log below in docker airbyte-server. I attempted to roll back to the previous version, 0.50.33, and everything worked fine.

I changed the VERSION variable `0.50.34` in the .env file and ran the command ./run-ab-platform.sh -b. After that, when I checked the web interface, Airbyte was no longer functioning.

### Relevant log output

```shell
___    _      __          __
   /   |  (_)____/ /_  __  __/ /____
  / /| | / / ___/ __ \/ / / / __/ _ \
 / ___ |/ / /  / /_/ / /_/ / /_/  __/
/_/  |_/_/_/  /_.___/\__, /\__/\___/
                    /____/
        : airbyte-server :
--------------------------------------------------
 Will soon be available at http://localhost:8000/
--------------------------------------------------

  Micronaut (v3.10.1)

2023-11-12 09:25:33 INFO i.m.c.e.DefaultEnvironment(<init>):167 - Established active environments: [control-plane]
2023-11-12 09:25:34 INFO i.a.c.t.TemporalUtils(getTemporalClientWhenConnected):148 - Waiting for temporal server...
2023-11-12 09:25:34 WARN i.a.c.t.TemporalUtils(getTemporalClientWhenConnected):159 - Waiting for namespace default to be initialized in temporal...
2023-11-12 09:25:37 INFO i.t.s.WorkflowServiceStubsImpl(<init>):86 - Created WorkflowServiceStubs for channel: ManagedChannelOrphanWrapper{delegate=ManagedChannelImpl{logId=1, target=airbyte-temporal:7233}}
2023-11-12 09:25:42 INFO i.a.c.t.TemporalUtils(getTemporalClientWhenConnected):176 - Temporal namespace default initialized!
2023-11-12 09:25:42 INFO i.a.c.EnvConfigs(getEnvOrDefault):1158 - Using default value for environment variable METRIC_CLIENT: ''
2023-11-12 09:25:42 INFO i.a.c.EnvConfigs(getEnvOrDefault):1158 - Using default value for environment variable METRIC_CLIENT: ''
2023-11-12 09:25:42 WARN i.a.m.l.MetricClientFactory(initialize):74 - MetricClient was not recognized or not provided. Accepted values are `datadog` or `otel`.
2023-11-12 09:25:42 INFO i.a.c.s.RemoteDefinitionsProvider(<init>):74 - Creating remote definitions provider for URL 'https://connectors.airbyte.com/files/' and registry 'OSS'...
2023-11-12 09:25:43 INFO i.a.c.p.v.DefaultDefinitionVersionOverrideProvider(<init>):52 - Initialized feature flag definition version overrides
2023-11-12 09:25:43 INFO i.a.c.p.ActorDefinitionVersionHelper(<init>):62 - ActorDefinitionVersionHelper initialized with override provider: DefaultDefinitionVersionOverrideProvider
2023-11-12 09:25:43 ERROR i.m.r.Micronaut(handleStartupException):338 - Error starting Micronaut server: Bean definition [io.airbyte.server.apis.SourceDefinitionApiController] could not be loaded: Failed to inject value for parameter [secretsRepositoryWriter] of class: io.airbyte.commons.server.handlers.SourceHandler

Message: No bean of type [io.airbyte.config.secrets.SecretsRepositoryWriter] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
Path Taken: new SourceDefinitionApiController(SourceDefinitionsHandler sourceDefinitionsHandler) --> new SourceDefinitionApiController([SourceDefinitionsHandler sourceDefinitionsHandler]) --> new SourceDefinitionsHandler(ConfigRepository configRepository,Supplier uuidSupplier,ActorDefinitionHandlerHelper actorDefinitionHandlerHelper,RemoteDefinitionsProvider remoteDefinitionsProvider,[SourceHandler sourceHandler],SupportStateUpdater supportStateUpdater,FeatureFlagClient featureFlagClient) --> new SourceHandler(ConfigRepository configRepository,SecretsRepositoryReader secretsRepositoryReader,[SecretsRepositoryWriter secretsRepositoryWriter],JsonSchemaValidator integrationSchemaValidation,ConnectionsHandler connectionsHandler,Supplier uuidGenerator,JsonSecretsProcessor secretsProcessor,ConfigurationUpdate configurationUpdate,OAuthConfigSupplier oAuthConfigSupplier,ActorDefinitionVersionHelper actorDefinitionVersionHelper,FeatureFlagClient featureFlagClient)
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.airbyte.server.apis.SourceDefinitionApiController] could not be loaded: Failed to inject value for parameter [secretsRepositoryWriter] of class: io.airbyte.commons.server.handlers.SourceHandler

Message: No bean of type [io.airbyte.config.secrets.SecretsRepositoryWriter] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
Path Taken: new SourceDefinitionApiController(SourceDefinitionsHandler sourceDefinitionsHandler) --> new SourceDefinitionApiController([SourceDefinitionsHandler sourceDefinitionsHandler]) --> new SourceDefinitionsHandler(ConfigRepository configRepository,Supplier uuidSupplier,ActorDefinitionHandlerHelper actorDefinitionHandlerHelper,RemoteDefinitionsProvider remoteDefinitionsProvider,[SourceHandler sourceHandler],SupportStateUpdater supportStateUpdater,FeatureFlagClient featureFlagClient) --> new SourceHandler(ConfigRepository configRepository,SecretsRepositoryReader secretsRepositoryReader,[SecretsRepositoryWriter secretsRepositoryWriter],JsonSchemaValidator integrationSchemaValidation,ConnectionsHandler connectionsHandler,Supplier uuidGenerator,JsonSecretsProcessor secretsProcessor,ConfigurationUpdate configurationUpdate,OAuthConfigSupplier oAuthConfigSupplier,ActorDefinitionVersionHelper actorDefinitionVersionHelper,FeatureFlagClient featureFlagClient)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1921) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:249) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3326) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3684) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:341) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:194) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:75) ~[micronaut-context-3.10.1.jar:3.10.1]
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:323) ~[micronaut-context-3.10.1.jar:3.10.1]
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:309) ~[micronaut-context-3.10.1.jar:3.10.1]
	at io.airbyte.server.Application.main(Application.java:15) ~[io.airbyte-airbyte-server-0.50.34.jar:?]
Caused by: io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [secretsRepositoryWriter] of class: io.airbyte.commons.server.handlers.SourceHandler

Message: No bean of type [io.airbyte.config.secrets.SecretsRepositoryWriter] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
Path Taken: new SourceDefinitionApiController(SourceDefinitionsHandler sourceDefinitionsHandler) --> new SourceDefinitionApiController([SourceDefinitionsHandler sourceDefinitionsHandler]) --> new SourceDefinitionsHandler(ConfigRepository configRepository,Supplier uuidSupplier,ActorDefinitionHandlerHelper actorDefinitionHandlerHelper,RemoteDefinitionsProvider remoteDefinitionsProvider,[SourceHandler sourceHandler],SupportStateUpdater supportStateUpdater,FeatureFlagClient featureFlagClient) --> new SourceHandler(ConfigRepository configRepository,SecretsRepositoryReader secretsRepositoryReader,[SecretsRepositoryWriter secretsRepositoryWriter],JsonSchemaValidator integrationSchemaValidation,ConnectionsHandler connectionsHandler,Supplier uuidGenerator,JsonSecretsProcessor secretsProcessor,ConfigurationUpdate configurationUpdate,OAuthConfigSupplier oAuthConfigSupplier,ActorDefinitionVersionHelper actorDefinitionVersionHelper,FeatureFlagClient featureFlagClient)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2087) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.airbyte.commons.server.handlers.$SourceHandler$Definition.build(Unknown Source) ~[io.airbyte-airbyte-commons-server-0.50.34.jar:?]
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.airbyte.commons.server.handlers.$SourceDefinitionsHandler$Definition.build(Unknown Source) ~[io.airbyte-airbyte-commons-server-0.50.34.jar:?]
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.airbyte.server.apis.$SourceDefinitionApiController$Definition.build(Unknown Source) ~[io.airbyte-airbyte-server-0.50.34.jar:?]
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2746) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1915) ~[micronaut-inject-3.10.1.jar:3.10.1]
	... 9 more
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.airbyte.config.secrets.SecretsRepositoryWriter] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2805) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.airbyte.commons.server.handlers.$SourceHandler$Definition.build(Unknown Source) ~[io.airbyte-airbyte-commons-server-0.50.34.jar:?]
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.airbyte.commons.server.handlers.$SourceDefinitionsHandler$Definition.build(Unknown Source) ~[io.airbyte-airbyte-commons-server-0.50.34.jar:?]
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.airbyte.server.apis.$SourceDefinitionApiController$Definition.build(Unknown Source) ~[io.airbyte-airbyte-server-0.50.34.jar:?]
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2746) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1915) ~[micronaut-inject-3.10.1.jar:3.10.1]
	... 9 more
```

**Comment by lpadula** [comment]
Same problem here!

**Comment by marcosmarxm** [comment]
@timoa did you use the `run-ab-platform` script or only edited the `.env` file?

**Comment by ysguy** [comment]
Sam problem, though moving back to 0.50.33 doesn't resolve it for me. 
I notice the airbyte/temporal server is restarting every minute or so and the airbyte/server is following along. 

Trying to **sudo docker exec -it <temporal container id> bash** won't let me in. Not sure how to troubleshoot this problem further.

**Comment by Ageds** [comment]
Same for us.

**Comment by marcosmarxm** [comment]
> Same for us.

Can you give more information about what steps are you doing? Because I'm able to run a new instance using Docker.
Are you changing anything in the .env or docker compose file? Are you upgrading from a previous version?
Are you changing only the `.env` version or did you upgrade using the `run-ab-platorm.sh` to get the new version of the file?

**Comment by Ageds** [comment]
> Same

I have upgraded the Airbyte version before. This time I upgraded from 0.50.33 to 0.50.34 and there will be such a prompt. I just tried upgrading to 0.50.40 and it is still the same! The same error occurred after I edited the version number of .env and used the following two methods; docker-compose up -d or ./run-ab-platform.sh -b
tips:

No bean of type [io.airbyte.config.secrets.SecretsRepositoryWriter] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor)

![image](https://github.com/airbytehq/airbyte/assets/15166076/c47c62e6-7160-4eab-bd04-2f637626f107)

**Comment by Ishankoradia** [comment]
For me, adding this `SECRET_PERSISTENCE=TESTING_CONFIG_DB_TABLE` to `.env`  . It is expecting some secret persistence strategy.

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
