### ISSUE TITLE
Destination BigQuery: using application default GCP credentials broken

### ISSUE THREAD

**Issue by rob-pomelo** [airbytehq/airbyte#32477]
### Connector Name

destination-bigquery

### Connector Version

2.3.14	

### What step the error happened?

During the sync

### Relevant information

https://github.com/airbytehq/airbyte/pull/32190/files#diff-71f64097f537f4492650bf539bdc98817ebf73178d7b7054a08b339abdd952f9 broke using application default credentials because it tries to parse the creds when they might be empty.

Broken since 2.3.7

### Relevant log output

```shell
2023-11-13 23:31:24 destination > java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.isTextual()" because "serviceAccountKey" is null
2023-11-13 23:31:24 destination >         at io.airbyte.integrations.destination.bigquery.BigQueryDestination.getSerializedMessageConsumer(BigQueryDestination.java:243) ~[io.airbyte.airbyte-integrations.connectors-destination-bigquery-0.50.33.jar:?]
2023-11-13 23:31:24 destination >         at io.airbyte.cdk.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:186) ~[airbyte-cdk-core-0.4.5.jar:?]
2023-11-13 23:31:24 destination >         at io.airbyte.cdk.integrations.base.IntegrationRunner.run(IntegrationRunner.java:125) ~[airbyte-cdk-core-0.4.5.jar:?]
2023-11-13 23:31:24 destination >         at io.airbyte.integrations.destination.bigquery.BigQueryDestination.main(BigQueryDestination.java:493) ~[io.airbyte.airbyte-integrations.connectors-destination-bigquery-0.50.33.jar:?]
2023-11-13 23:32:27 INFO i.a.w.p.KubePodProcess(cleanup):732 - (pod: airbyte / source-typeform-read-2055-3-piwdq) - Destroying Kube process.
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by stevenmurphy12** [comment]
I'm seeing the same problem with v2.3.25, having upgraded from v2.2.0. I'm using application default credentials.

Connection test works fine, presumably as it hits this section: https://github.com/airbytehq/airbyte/blob/f1099f5b53677102c564d5c5f12ff6da5a939802/airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/BigQueryDestination.java#L193-L197

Whereas I get the same error as rob above in this section: https://github.com/airbytehq/airbyte/blob/f1099f5b53677102c564d5c5f12ff6da5a939802/airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/BigQueryDestination.java#L238-L239

Any thoughts on this @edgao ? (saw your commit on this section )

**Comment by edgao** [comment]
ah, nice catch. For now - are you able to downgrade to an older version of destination-bigquery as a workaround?

**Comment by stevenmurphy12** [comment]
> ah, nice catch. For now - are you able to downgrade to an older version of destination-bigquery as a workaround?

Yeah I can downgrade for now

**Comment by shikanime** [comment]
I'd like to delve into the hypothesis further and initiate a pull request to resolve this matter if no one else has commenced one.

**Comment by evantahler** [comment]
Thanks for taking a look at this @shikanime! Let me know when your PR is ready for review

**Comment by shikanime** [comment]
@evantahler I think the PR should be ok for a review

**Comment by evantahler** [comment]
Thanks! I opened a new PR (https://github.com/airbytehq/airbyte/pull/34073) to address some metadata stuff.  I'll close this PR and merge in https://github.com/airbytehq/airbyte/pull/34073 soon!
