### ISSUE TITLE
Iceberg Destination: Could not connect to the Iceberg catalog with the provided configuration. Table was created concurrently: default.temp_xxx

### ISSUE THREAD

**Issue by deoooo** [airbytehq/airbyte#32482]
### Connector Name

destination-iceberg

### Connector Version

0.1.4

### What step the error happened?

Configuring a new connector

### Relevant information

Set up destination "iceberg" get this error.
I have ensured that the links to iceberg and s3 are correct.
destination-iceberg version: 0.1.4
airbyte version: 0.50.29

### Relevant log output

```shell
Stack Trace:
	at io.airbyte.integrations.destination.iceberg.config.catalog.IcebergCatalogConfig.check(IcebergCatalogConfig.java:50) ~[io.airbyte.airbyte-integrations.connectors-destination-iceberg-24.0.2.jar:?]
	at io.airbyte.integrations.destination.iceberg.IcebergDestination.check(IcebergDestination.java:49) ~[io.airbyte.airbyte-integrations.connectors-destination-iceberg-24.0.2.jar:?]
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:124) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:99) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
	at io.airbyte.integrations.destination.iceberg.IcebergDestination.main(IcebergDestination.java:42) ~[io.airbyte.airbyte-integrations.connectors-destination-iceberg-24.0.2.jar:?]
Stack Trace: org.apache.iceberg.exceptions.AlreadyExistsException: Table was created concurrently: default.temp_1699872848347
	at org.apache.iceberg.BaseMetastoreCatalog$BaseMetastoreCatalogTableBuilder.create(BaseMetastoreCatalog.java:201)
	at org.apache.iceberg.catalog.Catalog.createTable(Catalog.java:75)
	at org.apache.iceberg.catalog.Catalog.createTable(Catalog.java:118)
	at io.airbyte.integrations.destination.iceberg.config.catalog.IcebergCatalogConfig.check(IcebergCatalogConfig.java:50)
	at io.airbyte.integrations.destination.iceberg.IcebergDestination.check(IcebergDestination.java:49)
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:124)
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:99)
	at io.airbyte.integrations.destination.iceberg.IcebergDestination.main(IcebergDestination.java:42)
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 365 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.
