### ISSUE TITLE
JSON on SFTP file source times out

### ISSUE THREAD

**Issue by aleloi** [airbytehq/airbyte#32799]
### Connector Name

source-file

### Connector Version

0.3.15

### What step the error happened?

During the sync

### Relevant information

I'm running Airybte with `run-ab-platform.sh -x` after checking out tag v0.50.34. My sources are JSON files accessed though SFTP. My destination is BigQuery. I've noticed that for files larger than ca 50MB, the sync step mostly fails. For smaller files there are no problems. I'm running Airbyte on a GCP VM.

My source configuration is:

```json
{
  "sourceId": "the source id",
  "name": "the name",
  "sourceType": "file",
  "workspaceId": "844d0e8f-ff0c-4cdc-ad73-c019611df0c0",
  "configuration": {
    "url": "/ftp/the_file_name.json",
    "format": "json",
    "provider": {
      "host": "<host_name>",
      "port": "2025",
      "user": "<user>",
      "storage": "SFTP",
      "password": "**********"
    },
    "dataset_name": "orders_2021"
  }
}
```

My connection configuration is:

```json
    {
      "connectionId": "<the id>",
      "name": "<connection name>",
      "sourceId": "the source id",
      "destinationId": "fe56cf4b-5874-4ad5-a178-a63ae7ded22c",
      "workspaceId": "844d0e8f-ff0c-4cdc-ad73-c019611df0c0",
      "status": "active",
      "schedule": {
        "scheduleType": "manual"
      },
      "dataResidency": "auto",
      "nonBreakingSchemaUpdatesBehavior": "ignore",
      "namespaceDefinition": "destination",
      "namespaceFormat": "${SOURCE_NAMESPACE}",
      "configurations": {
        "streams": [
          {
            "name": "orders_2021",
            "syncMode": "full_refresh_overwrite"
          }
        ]
      }
    },
```

The airbyte-worker docker image stats the source-file container with:

```
airbyte-worker                    | 2023-11-24 13:58:46 INFO i.a.w.p.DockerProcessFactory(create):140 - Creating docker container = source-file-check-81-0-edxgx with resources io.airbyte.config.ResourceRequirements@7209da9c[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts io.airbyte.config.AllowedHosts@1f12c41e[hosts=[*, *.datadoghq.com, *.datadoghq.eu, *.sentry.io],additionalProperties={}]
airbyte-worker                    | 2023-11-24 13:58:46 INFO i.a.w.p.DockerProcessFactory(create):187 - Preparing command: docker run --rm --init -i -w /data/81/0 --log-driver none --name source-file-check-81-0-edxgx --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/source-file:0.3.15 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e FIELD_SELECTION_WORKSPACES= -e USE_STREAM_CAPABLE_STATE=true -e AIRBYTE_ROLE= -e WORKER_ENVIRONMENT=DOCKER -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=0 -e OTEL_COLLECTOR_ENDPOINT=http://host.docker.internal:4317 -e FEATURE_FLAG_CLIENT=config -e AIRBYTE_VERSION=0.50.33 -e WORKER_JOB_ID=81 airbyte/source-file:0.3.15 check --config source_config.json
```

After a while, airbyte-worker prints this and tries again:

```
airbyte-worker                    | 2023-11-24 14:04:05 WARN i.a.c.t.CancellationHandler$TemporalCancellationHandler(checkAndHandleCancellation):79 - The job timeout and was not a sync, we will destroy the pods related to it
airbyte-worker                    | io.temporal.client.ActivityNotExistsException: WorkflowId=check_81_source, RunId=9c1805c3-697f-4bf5-9424-ee820fba40f3, ActivityType=RunWithJobOutput, ActivityId=cc87c434-d165-39fb-a65c-9e1cd46f24be
airbyte-worker                    |     at io.temporal.internal.activity.HeartbeatContextImpl.sendHeartbeatRequest(HeartbeatContextImpl.java:200) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker                    |     at io.temporal.internal.activity.HeartbeatContextImpl.doHeartBeatLocked(HeartbeatContextImpl.java:144) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker                    |     at io.temporal.internal.activity.HeartbeatContextImpl.lambda$scheduleNextHeartbeatLocked$0(HeartbeatContextImpl.java:167) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker                    |     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[?:?]
airbyte-worker                    |     at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
airbyte-worker                    |     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
airbyte-worker                    |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
airbyte-worker                    |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
airbyte-worker                    |     at java.lang.Thread.run(Thread.java:1589) ~[?:?]
airbyte-worker                    | Caused by: io.grpc.StatusRuntimeException: NOT_FOUND: workflow execution already completed
airbyte-worker                    |     at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271) ~[grpc-stub-1.55.1.jar:1.55.1]
airbyte-worker                    |     at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252) ~[grpc-stub-1.55.1.jar:1.55.1]
airbyte-worker                    |     at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165) ~[grpc-stub-1.55.1.jar:1.55.1]
airbyte-worker                    |     at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.recordActivityTaskHeartbeat(WorkflowServiceGrpc.java:3813) ~[temporal-serviceclient-1.17.0.jar:?]
airbyte-worker                    |     at io.temporal.internal.client.ActivityClientHelper.sendHeartbeatRequest(ActivityClientHelper.java:67) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker                    |     at io.temporal.internal.activity.HeartbeatContextImpl.sendHeartbeatRequest(HeartbeatContextImpl.java:185) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker                    |     ... 8 more
airbyte-worker                    | 2023-11-24 14:04:05 WARN i.a.w.g.DefaultCheckConnectionWorker(run):110 - Check connection job subprocess finished with exit code 143
airbyte-worker                    | 2023-11-24 14:04:05 ERROR i.a.w.g.DefaultCheckConnectionWorker(run):128 - Lost connection to the source: 
airbyte-worker                    | java.io.IOException: Stream closed
airbyte-worker                    |     at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:172) ~[?:?]
airbyte-worker                    |     at java.io.BufferedInputStream.implRead(BufferedInputStream.java:373) ~[?:?]
airbyte-worker                    |     at java.io.BufferedInputStream.read(BufferedInputStream.java:367) ~[?:?]
airbyte-worker                    |     at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:333) ~[?:?]
airbyte-worker                    |     at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:376) ~[?:?]
airbyte-worker                    |     at sun.nio.cs.StreamDecoder.lockedRead(StreamDecoder.java:219) ~[?:?]
airbyte-worker                    |     at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:173) ~[?:?]
airbyte-worker                    |     at java.io.InputStreamReader.read(InputStreamReader.java:189) ~[?:?]
airbyte-worker                    |     at java.io.BufferedReader.fill(BufferedReader.java:161) ~[?:?]
airbyte-worker                    |     at java.io.BufferedReader.implReadLine(BufferedReader.java:371) ~[?:?]
airbyte-worker                    |     at java.io.BufferedReader.readLine(BufferedReader.java:348) ~[?:?]
airbyte-worker                    |     at java.io.BufferedReader.readLine(BufferedReader.java:437) ~[?:?]
```

### Relevant log output

```shell
Failure reason: The check connection failed because of an internal error
2023-11-24 13:47:44 INFO i.a.w.t.s.a.AppendToAttemptLogActivityImpl(log):56 - Retry State: RetryManager(completeFailureBackoffPolicy=BackoffPolicy(minInterval=PT10S, maxInterval=PT30M, base=3), partialFailureBackoffPolicy=null, successiveCompleteFailureLimit=5, totalCompleteFailureLimit=10, successivePartialFailureLimit=1000, totalPartialFailureLimit=10, successiveCompleteFailures=1, totalCompleteFailures=1, successivePartialFailures=0, totalPartialFailures=0)
2023-11-24 13:47:44 WARN i.a.w.t.s.a.AppendToAttemptLogActivityImpl(log):55 - Backing off for: 10 seconds.
2023-11-24 13:47:54 INFO i.a.w.t.TemporalAttemptExecution(get):124 - Docker volume job log path: /tmp/workspace/80/1/logs.log
2023-11-24 13:47:54 INFO i.a.w.t.TemporalAttemptExecution(get):129 - Executing worker wrapper. Airbyte version: 0.50.33
2023-11-24 13:47:54 INFO i.a.a.c.AirbyteApiClient(retryWithJitterThrows):290 - Attempt 0 to save workflow id for cancellation
2023-11-24 13:47:54 INFO i.a.c.EnvConfigs(getEnvOrDefault):1158 - Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2023-11-24 13:47:55 INFO i.a.c.EnvConfigs(getEnvOrDefault):1158 - Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2023-11-24 13:47:55 INFO i.a.c.EnvConfigs(getEnvOrDefault):1158 - Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2023-11-24 13:47:55 INFO i.a.c.EnvConfigs(getEnvOrDefault):1158 - Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2023-11-24 13:47:55 INFO i.a.c.EnvConfigs(getEnvOrDefault):1158 - Using default value for environment variable LAUNCHDARKLY_KEY: ''
2023-11-24 13:47:55 INFO i.a.c.i.LineGobbler(voidCall):149 - 
2023-11-24 13:47:55 INFO i.a.c.i.LineGobbler(voidCall):149 - ----- START CHECK -----
2023-11-24 13:47:55 INFO i.a.c.i.LineGobbler(voidCall):149 - 
2023-11-24 13:47:55 INFO i.a.c.i.LineGobbler(voidCall):149 - Checking if airbyte/source-file:0.3.15 exists...
2023-11-24 13:47:55 INFO i.a.c.i.LineGobbler(voidCall):149 - airbyte/source-file:0.3.15 was found locally.
2023-11-24 13:47:55 INFO i.a.w.p.DockerProcessFactory(create):140 - Creating docker container = source-file-check-80-1-xovlp with resources io.airbyte.config.ResourceRequirements@78326127[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts io.airbyte.config.AllowedHosts@3675cd93[hosts=[*, *.datadoghq.com, *.datadoghq.eu, *.sentry.io],additionalProperties={}]
2023-11-24 13:47:55 INFO i.a.w.p.DockerProcessFactory(create):187 - Preparing command: docker run --rm --init -i -w /data/80/1 --log-driver none --name source-file-check-80-1-xovlp --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/source-file:0.3.15 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e FIELD_SELECTION_WORKSPACES= -e USE_STREAM_CAPABLE_STATE=true -e WORKER_ENVIRONMENT=DOCKER -e AIRBYTE_ROLE= -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=1 -e OTEL_COLLECTOR_ENDPOINT=http://host.docker.internal:4317 -e FEATURE_FLAG_CLIENT=config -e AIRBYTE_VERSION=0.50.33 -e WORKER_JOB_ID=80 airbyte/source-file:0.3.15 check --config source_config.json
2023-11-24 13:47:55 INFO i.a.w.i.VersionedAirbyteStreamFactory(create):186 - Reading messages from protocol version 0.2.0
2023-11-24 13:52:55 INFO i.a.w.t.s.a.AppendToAttemptLogActivityImpl(log):56 - Retry State: RetryManager(completeFailureBackoffPolicy=BackoffPolicy(minInterval=PT10S, maxInterval=PT30M, base=3), partialFailureBackoffPolicy=null, successiveCompleteFailureLimit=5, totalCompleteFailureLimit=10, successivePartialFailureLimit=1000, totalPartialFailureLimit=10, successiveCompleteFailures=2, totalCompleteFailures=2, successivePartialFailures=0, totalPartialFailures=0)
 Backoff before next attempt: 30 seconds
2023-11-24 13:53:15 WARN i.a.w.g.DefaultCheckConnectionWorker(run):110 - Check connection job subprocess finished with exit code 143
2023-11-24 13:53:15 ERROR i.a.w.g.DefaultCheckConnectionWorker(run):128 - Lost connection to the source: 
java.io.IOException: Stream closed
        at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:172) ~[?:?]
        at java.io.BufferedInputStream.implRead(BufferedInputStream.java:373) ~[?:?]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:367) ~[?:?]
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:333) ~[?:?]
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:376) ~[?:?]
        at sun.nio.cs.StreamDecoder.lockedRead(StreamDecoder.java:219) ~[?:?]
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:173) ~[?:?]
        at java.io.InputStreamReader.read(InputStreamReader.java:189) ~[?:?]
        at java.io.BufferedReader.fill(BufferedReader.java:161) ~[?:?]
        at java.io.BufferedReader.implReadLine(BufferedReader.java:371) ~[?:?]
        at java.io.BufferedReader.readLine(BufferedReader.java:348) ~[?:?]
        at java.io.BufferedReader.readLine(BufferedReader.java:437) ~[?:?]
        at io.airbyte.workers.WorkerUtils.getStdErrFromErrorStream(WorkerUtils.java:249) ~[io.airbyte-airbyte-commons-worker-0.50.33.jar:?]
        at io.airbyte.workers.WorkerUtils.throwWorkerException(WorkerUtils.java:266) ~[io.airbyte-airbyte-commons-worker-0.50.33.jar:?]
        at io.airbyte.workers.general.DefaultCheckConnectionWorker.run(DefaultCheckConnectionWorker.java:120) ~[io.airbyte-airbyte-commons-worker-0.50.33.jar:?]
        at io.airbyte.workers.general.DefaultCheckConnectionWorker.run(DefaultCheckConnectionWorker.java:44) ~[io.airbyte-airbyte-commons-worker-0.50.33.jar:?]
        at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:135) ~[io.airbyte-airbyte-workers-0.50.33.jar:?]
        at io.airbyte.workers.temporal.check.connection.CheckConnectionActivityImpl.lambda$runWithJobOutput$1(CheckConnectionActivityImpl.java:136) ~[io.airbyte-airbyte-workers-0.50.33.jar:?]
        at io.airbyte.commons.temporal.TemporalUtils.withBackgroundHeartbeat(TemporalUtils.java:314) ~[io.airbyte-airbyte-commons-temporal-0.50.33.jar:?]
        at io.airbyte.workers.temporal.check.connection.CheckConnectionActivityImpl.runWithJobOutput(CheckConnectionActivityImpl.java:121) ~[io.airbyte-airbyte-workers-0.50.33.jar:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
        at io.temporal.internal.activity.RootActivityInboundCallsInterceptor$POJOActivityInboundCallsInterceptor.executeActivity(RootActivityInboundCallsInterceptor.java:64) ~[temporal-sdk-1.17.0.jar:?]
        at io.temporal.internal.activity.RootActivityInboundCallsInterceptor.execute(RootActivityInboundCallsInterceptor.java:43) ~[temporal-sdk-1.17.0.jar:?]
        at io.temporal.internal.activity.ActivityTaskExecutors$BaseActivityTaskExecutor.execute(ActivityTaskExecutors.java:95) ~[temporal-sdk-1.17.0.jar:?]
        at io.temporal.internal.activity.ActivityTaskHandlerImpl.handle(ActivityTaskHandlerImpl.java:92) ~[temporal-sdk-1.17.0.jar:?]
        at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handleActivity(ActivityWorker.java:241) ~[temporal-sdk-1.17.0.jar:?]
        at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:206) ~[temporal-sdk-1.17.0.jar:?]
        at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:179) ~[temporal-sdk-1.17.0.jar:?]
        at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93) ~[temporal-sdk-1.17.0.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
2023-11-24 13:53:15 INFO i.a.c.i.LineGobbler(voidCall):149 - 
2023-11-24 13:53:15 INFO i.a.c.i.LineGobbler(voidCall):149 - ----- END CHECK -----
2023-11-24 13:53:15 INFO i.a.c.i.LineGobbler(voidCall):149 -
```

### Contribute

- [X] Yes, I want to contribute

**Comment by aleloi** [comment]
This was probably due to OOM. Increasing to 8G from 4G and reducing max concurrent workers solved it. What I'd like to see though is an indication in the logs that airbyte-server or airbyte-worker is killed due to OOM.
