### ISSUE TITLE
[connector builder] AttributeError: 'DeclarativeOauth2Authenticator' object has no attribute '_refresh_token_error_status_codes'

### ISSUE THREAD

**Issue by hmcc** [airbytehq/airbyte#32820]
### What method are you using to run Airbyte?

Docker

### Platform Version or Helm Chart Version

0.50.33

### What step the error happened?

Other

## Summary

In order to better understand the Builder capabilities, I tried to build a connector using OAuth with the [Connector Builder UI](https://docs.airbyte.com/connector-development/connector-builder-ui/overview). I was not able to because of an `AttributeError` in `DeclarativeOauth2Authenticator`.

The error can also be reproduced with the [Low Code CDK](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview).

## Steps to reproduce
To reproduce the error you will need an OAuth service to connect to , shown below as https://auth.service.com

1. Start Airbyte with Docker compose
2. Go to http://localhost:8000/
3. In the left menu, click Builder
4. Select Start from scratch
5. Under Authentication, select OAuth
6. Fill in the API Base URL https://auth.service.com and Token Refresh Endpoint https://auth.service.com/token
7. Set the Grant Type to client_credentials and set a test client ID and client secret - I used aaaaaa and bbbbbb
8. Add a stream - I used test/test
9. Click test

## Expected behaviour
The test connection fails because the client ID and secret were not correct

## Actual behaviour
The request fails with `'DeclarativeOauth2Authenticator' object has no attribute '_refresh_token_error_status_codes'`

### Relevant log output

```shell
'DeclarativeOauth2Authenticator' object has no attribute '_refresh_token_error_status_codes' - Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py", line 116, in _get_refresh_access_token_response
    response.raise_for_status()
  File "/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://auth.chimera.anaplan.com/token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/connector_builder/message_grouper.py", line 249, in _read_stream
    yield from AirbyteEntrypoint(source).read(source.spec(self.logger), config, configured_catalog, {})
  File "/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 158, in read
    yield from self.source.read(self.logger, config, catalog, state)
  File "/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/manifest_declarative_source.py", line 138, in read
    yield from super().read(logger, config, catalog, state)
  File "/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 142, in read
    raise e
  File "/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 122, in read
    yield from self._read_stream(
  File "/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 194, in _read_stream
    for record in record_iterator:
  File "/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 292, in _read_full_refresh
    for record_data_or_message in stream_instance.read_full_refresh(configured_stream.cursor_field, logger, self._slice_logger):
  File "/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/streams/core.py", line 120, in read_full_refresh
    yield from self.read_records(
  File "/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py", line 104, in read_records
    yield from self.retriever.read_records(stream_slice)
  File "/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 304, in read_records
    for stream_data in self._read_pages(self._parse_records, self.state, stream_slice):
  File "/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 282, in _read_pages
    response = self._fetch_next_page(stream_state, stream_slice, next_page_token)
  File "/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 395, in _fetch_next_page
    return self.requester.send_request(
  File "/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 392, in send_request
    headers=self._request_headers(stream_state, stream_slice, next_page_token, request_headers),
  File "/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 251, in _request_headers
    headers = self._get_request_options(
  File "/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 235, in _get_request_options
    auth_options_method(),
  File "/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py", line 55, in get_auth_header
    return {"Authorization": f"Bearer {self.get_access_token()}"}
  File "/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py", line 60, in get_access_token
    token, expires_in = self.refresh_access_token()
  File "/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py", line 134, in refresh_access_token
    response_json = self._get_refresh_access_token_response()
  File "/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py", line 121, in _get_refresh_access_token_response
    if self._wrap_refresh_token_exception(e):
  File "/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py", line 100, in _wrap_refresh_token_exception
    exception.response.status_code in self._refresh_token_error_status_codes
AttributeError: 'DeclarativeOauth2Authenticator' object has no attribute '_refresh_token_error_status_codes'
```

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
