### ISSUE TITLE
Fail loudly when tap or target image is not available

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#330]
## Expected Behavior
If, for whatever reason, the worker cannot pull the tap or target image, we should fail with an explicit error that says so.

## Current Behavior
* We fail, with an esoteric error message (at least for targets).
```
airbyte-scheduler | 2020-09-22 00:02:11 ERROR i.a.c.i.LineGobbler(voidCall):60 - {} - Running sync...
airbyte-scheduler | 2020-09-22 00:02:11 ERROR i.a.c.i.LineGobbler(voidCall):60 - {} - docker: Error response from daemon: manifest for airbyte/integration-singer-csv-destination:0.1.1 not found: manifest unknown: manifest unknown.
...
dataline-scheduler | 2020-09-16 22:28:58 DEBUG c.n.s.BaseJsonValidator(debug):136 - {context=worker, job_id=3, job_root=/tmp/workspace/3/4} - validate( {"type":"RECORD","stream":"exchange_rate","record":{"CAD":1.316707389,"HKD":7.7500210633,"ISK":135.3104726599,"PHP":48.359592215,"DKK":6.2680933524,"HUF":302.0810514786,"CZK":22.5174825175,"GBP":0.7702670823,"RON":4.0938579493,"SEK":8.7722638807,"IDR":14834.9987362036,"INR":73.5247282838,"BRL":5.241469374,"RUB":74.8199511332,"HRK":6.3539472576,"JPY":105.080461707,"THB":31.1003454377,"CHF":0.9059735445,"EUR":0.842530963,"MYR":4.1305080462,"BGN":1.6478220575,"TRY":7.4968405089,"CNY":6.7595416632,"NOK":8.9820540905,"NZD":1.4816749516,"ZAR":16.3220153341,"USD":1.0,"MXN":21.0307523801,"SGD":1.3573173814,"AUD":1.3627095796,"ILS":3.4197489258,"KRW":1171.7246608813,"PLN":3.7463981801,"date":"2020-09-16T00:00:00Z"}}, {"type":"RECORD","stream":"exchange_rate","record":{"CAD":1.316707389,"HKD":7.7500210633,"ISK":135.3104726599,"PHP":48.359592215,"DKK":6.2680933524,"HUF":302.0810514786,"CZK":22.5174825175,"GBP":0.7702670823,"RON":4.0938579493,"SEK":8.7722638807,"IDR":14834.9987362036,"INR":73.5247282838,"BRL":5.241469374,"RUB":74.8199511332,"HRK":6.3539472576,"JPY":105.080461707,"THB":31.1003454377,"CHF":0.9059735445,"EUR":0.842530963,"MYR":4.1305080462,"BGN":1.6478220575,"TRY":7.4968405089,"CNY":6.7595416632,"NOK":8.9820540905,"NZD":1.4816749516,"ZAR":16.3220153341,"USD":1.0,"MXN":21.0307523801,"SGD":1.3573173814,"AUD":1.3627095796,"ILS":3.4197489258,"KRW":1171.7246608813,"PLN":3.7463981801,"date":"2020-09-16T00:00:00Z"}}, $)
...
dataline-scheduler | 2020-09-16 22:28:58 DEBUG c.n.s.BaseJsonValidator(debug):136 - {context=worker, job_id=3, job_root=/tmp/workspace/3/4} - validate( {"type":"STATE","value":{"start_date":"2020-09-16"}}, {"type":"STATE","value":{"start_date":"2020-09-16"}}, $)
dataline-scheduler | 2020-09-16 22:28:58 DEBUG c.n.s.BaseJsonValidator(debug):136 - {context=worker, job_id=3, job_root=/tmp/workspace/3/4} - validate( "STATE", {"type":"STATE","value":{"start_date":"2020-09-16"}}, $.type)
dataline-scheduler | 2020-09-16 22:28:58 DEBUG c.n.s.BaseJsonValidator(debug):136 - {context=worker, job_id=3, job_root=/tmp/workspace/3/4} - validate( "STATE", {"type":"STATE","value":{"start_date":"2020-09-16"}}, $.type)
dataline-scheduler | 2020-09-16 22:28:58 DEBUG c.n.s.BaseJsonValidator(debug):136 - {context=worker, job_id=3, job_root=/tmp/workspace/3/4} - validate( {"start_date":"2020-09-16"}, {"type":"STATE","value":{"start_date":"2020-09-16"}}, $.value)
dataline-scheduler | 2020-09-16 22:28:58 DEBUG c.n.s.BaseJsonValidator(debug):136 - {context=worker, job_id=3, job_root=/tmp/workspace/3/4} - validate( {"type":"STATE","value":{"start_date":"2020-09-16"}}, {"type":"STATE","value":{"start_date":"2020-09-16"}}, $)
dataline-scheduler | 2020-09-16 22:28:58 DEBUG i.d.w.p.s.DefaultSingerTap(close):141 - {context=worker, job_id=3, job_root=/tmp/workspace/3/4} - Closing tap process
dataline-scheduler | 2020-09-16 22:28:58 ERROR i.d.w.p.s.SingerSyncWorker(run):89 - {context=worker, job_id=3, job_root=/tmp/workspace/3/4} - Sync worker failed. Tap error log: <null>.
dataline-scheduler |  Target error log: <null>
dataline-scheduler | java.io.IOException: Stream closed
dataline-scheduler | 	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:442) ~[?:?]
dataline-scheduler | 	at java.io.OutputStream.write(OutputStream.java:162) ~[?:?]
dataline-scheduler | 	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:123) ~[?:?]
dataline-scheduler | 	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:242) ~[?:?]
dataline-scheduler | 	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:312) ~[?:?]
dataline-scheduler | 	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:290) ~[?:?]
dataline-scheduler | 	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:131) ~[?:?]
dataline-scheduler | 	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:208) ~[?:?]
dataline-scheduler | 	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:120) ~[?:?]
dataline-scheduler | 	at java.io.BufferedWriter.flush(BufferedWriter.java:256) ~[?:?]
dataline-scheduler | 	at io.dataline.workers.protocols.singer.DefaultSingerTarget.notifyEndOfStream(DefaultSingerTarget.java:91) ~[dataline-workers-0.1.0.jar:?]
dataline-scheduler | 	at io.dataline.workers.protocols.singer.SingerSyncWorker.run(SingerSyncWorker.java:86) [dataline-workers-0.1.0.jar:?]
dataline-scheduler | 	at io.dataline.workers.protocols.singer.SingerSyncWorker.run(SingerSyncWorker.java:47) [dataline-workers-0.1.0.jar:?]
dataline-scheduler | 	at io.dataline.workers.wrappers.OutputConvertingWorker.run(OutputConvertingWorker.java:46) [dataline-workers-0.1.0.jar:?]
dataline-scheduler | 	at io.dataline.workers.wrappers.JobOutputSyncWorker.run(JobOutputSyncWorker.java:32) [dataline-workers-0.1.0.jar:?]
dataline-scheduler | 	at io.dataline.scheduler.WorkerRun.lambda$new$0(WorkerRun.java:53) [dataline-scheduler-0.1.0.jar:?]
dataline-scheduler | 	at io.dataline.scheduler.WorkerRun.call(WorkerRun.java:61) [dataline-scheduler-0.1.0.jar:?]
dataline-scheduler | 	at io.dataline.scheduler.WorkerRun.call(WorkerRun.java:42) [dataline-scheduler-0.1.0.jar:?]
dataline-scheduler | 	at io.dataline.commons.concurrency.LifecycledCallable.execute(LifecycledCallable.java:114) [dataline-commons-0.1.0.jar:?]
dataline-scheduler | 	at io.dataline.commons.concurrency.LifecycledCallable.call(LifecycledCallable.java:98) [dataline-commons-0.1.0.jar:?]
dataline-scheduler | 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
dataline-scheduler | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
dataline-scheduler | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
dataline-scheduler | 	at java.lang.Thread.run(Thread.java:832) [?:?]
dataline-scheduler | 	Suppressed: java.io.IOException: Stream closed
dataline-scheduler | 		at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:442) ~[?:?]
dataline-scheduler | 		at java.io.OutputStream.write(OutputStream.java:162) ~[?:?]
dataline-scheduler | 		at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81) ~[?:?]
dataline-scheduler | 		at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142) ~[?:?]
dataline-scheduler | 		at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:327) ~[?:?]
dataline-scheduler | 		at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:159) ~[?:?]
dataline-scheduler | 		at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:251) ~[?:?]
dataline-scheduler | 		at java.io.BufferedWriter.flush(BufferedWriter.java:257) ~[?:?]
dataline-scheduler | 		at io.dataline.workers.protocols.singer.DefaultSingerTarget.notifyEndOfStream(DefaultSingerTarget.java:91) ~[dataline-workers-0.1.0.jar:?]
dataline-scheduler | 		at io.dataline.workers.protocols.singer.DefaultSingerTarget.close(DefaultSingerTarget.java:103) ~[dataline-workers-0.1.0.jar:?]
dataline-scheduler | 		at io.dataline.workers.protocols.singer.SingerSyncWorker.run(SingerSyncWorker.java:72) [dataline-workers-0.1.0.jar:?]
dataline-scheduler | 		at io.dataline.workers.protocols.singer.SingerSyncWorker.run(SingerSyncWorker.java:47) [dataline-workers-0.1.0.jar:?]
dataline-scheduler | 		at io.dataline.workers.wrappers.OutputConvertingWorker.run(OutputConvertingWorker.java:46) [dataline-workers-0.1.0.jar:?]
dataline-scheduler | 		at io.dataline.workers.wrappers.JobOutputSyncWorker.run(JobOutputSyncWorker.java:32) [dataline-workers-0.1.0.jar:?]
dataline-scheduler | 		at io.dataline.scheduler.WorkerRun.lambda$new$0(WorkerRun.java:53) [dataline-scheduler-0.1.0.jar:?]
dataline-scheduler | 		at io.dataline.scheduler.WorkerRun.call(WorkerRun.java:61) [dataline-scheduler-0.1.0.jar:?]
dataline-scheduler | 		at io.dataline.scheduler.WorkerRun.call(WorkerRun.java:42) [dataline-scheduler-0.1.0.jar:?]
dataline-scheduler | 		at io.dataline.commons.concurrency.LifecycledCallable.execute(LifecycledCallable.java:114) [dataline-commons-0.1.0.jar:?]
dataline-scheduler | 		at io.dataline.commons.concurrency.LifecycledCallable.call(LifecycledCallable.java:98) [dataline-commons-0.1.0.jar:?]
dataline-scheduler | 		at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
dataline-scheduler | 		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
dataline-scheduler | 		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
dataline-scheduler | 		at java.lang.Thread.run(Thread.java:832) [?:?]
dataline-scheduler | 2020-09-16 22:28:58 INFO i.d.s.p.DefaultSchedulerPersistence(updateStatus):195 - {context=worker, job_id=3, job_root=/tmp/workspace/3/4} - Setting job status to FAILED for job 3
```

## Steps to Reproduce
1. run a sync with a target image that does not exist.

**Comment by cgardens** [comment]
closed by https://github.com/airbytehq/airbyte/pull/393 and https://github.com/airbytehq/airbyte/pull/378
