### ISSUE TITLE
MSSQL source doesn't parse date correctly

### ISSUE THREAD

**Issue by goldengrisha** [airbytehq/airbyte#33094]
### Connector Name

source-mssql

### Connector Version

3.1.0

### What step the error happened?

During the sync

### Relevant information

Hello, please help, `Date can't be parsed: '2015-05-16 19:17:07.49 +01:00'`

### Relevant log output

```shell
023-12-04 13:52:38 ERROR i.d.u.Loggings(logErrorAndTraceRecord):58 - Failed to properly convert data value for '_____.dbo.EmailsReport.SentDate' of type datetimeoffset
2023-12-04 13:52:38 source > java.time.format.DateTimeParseException: Text '2015-05-16 19:17:07.49 +01:00' could not be parsed at index 19
2023-12-04 13:52:38 source >         at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2052) ~[?:?]
2023-12-04 13:52:38 source >         at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1954) ~[?:?]
2023-12-04 13:52:38 source >         at java.base/java.time.OffsetDateTime.parse(OffsetDateTime.java:404) ~[?:?]
2023-12-04 13:52:38 source >         at io.airbyte.cdk.integrations.debezium.internals.mssql.MSSQLConverter.lambda$registerDateTimeOffSet$4(MSSQLConverter.java:148) ~[airbyte-cdk-db-sources-0.6.2.jar:?]
2023-12-04 13:52:38 source >         at io.debezium.relational.CustomConverterRegistry.lambda$getValueConverter$1(CustomConverterRegistry.java:147) ~[debezium-core-2.4.0.Final.jar:2.4.0.Final]
2023-12-04 13:52:38 source >         at io.debezium.relational.TableSchemaBuilder.lambda$createValueGenerator$5(TableSchemaBuilder.java:281) ~[debezium-core-2.4.0.Final.jar:2.4.0.Final]
2023-12-04 13:52:38 source >         at io.debezium.relational.TableSchema.valueFromColumnData(TableSchema.java:141) ~[debezium-core-2.4.0.Final.jar:2.4.0.Final]
2023-12-04 13:52:38 source >         at io.debezium.relational.RelationalChangeRecordEmitter.emitReadRecord(RelationalChangeRecordEmitter.java:87) ~[debezium-core-2.4.0.Final.jar:2.4.0.Final]
2023-12-04 13:52:38 source >         at io.debezium.relational.RelationalChangeRecordEmitter.emitChangeRecords(RelationalChangeRecordEmitter.java:50) ~[debezium-core-2.4.0.Final.jar:2.4.0.Final]
2023-12-04 13:52:38 source >         at io.debezium.pipeline.EventDispatcher.dispatchSnapshotEvent(EventDispatcher.java:207) ~[debezium-core-2.4.0.Final.jar:2.4.0.Final]
2023-12-04 13:52:38 source >         at io.debezium.relational.RelationalSnapshotChangeEventSource.doCreateDataEventsForTable(RelationalSnapshotChangeEventSource.java:574) ~[debezium-core-2.4.0.Final.jar:2.4.0.Final]
2023-12-04 13:52:38 source >         at io.debezium.relational.RelationalSnapshotChangeEventSource.lambda$createDataEventsForTableCallable$6(RelationalSnapshotChangeEventSource.java:515) ~[debezium-core-2.4.0.Final.jar:2.4.0.Final]
2023-12-04 13:52:38 source >         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
2023-12-04 13:52:38 source >         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
2023-12-04 13:52:38 source >         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
2023-12-04 13:52:38 source >         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
2023-12-04 13:52:38 source >         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
2023-12-04 13:52:38 source >         at java.base/java.lang.Thread.run(Thread.java:833) [?:?]
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by goldengrisha** [comment]
@marcosmarxm sorry, why do close it?
