### ISSUE TITLE
[source-mysql] sync failures after schema update

### ISSUE THREAD

**Issue by sarunasandr** [airbytehq/airbyte#33215]
### Connector Name

source-mysql

### Connector Version

2.1.1

### What step the error happened?

During the sync

### Relevant information

**Context**
We are using two different Airbyte clusters (version 0.50.12) for **develop** and **production** environments. Currently, we are using these RDS versions:
1) RDS Aurora Serverless (8.0.mysql_aurora.3.05.0 MySQL Engine)
2) RDS MySQL (8.0.28 MySQL Engine)

2023-12-04 08:40 (UTC) We had an RDS schema update in both environments (same changes), which added additional fields to one of the tables:
`ALTER TABLE 'order' ADD cancelled TINYINT(1) DEFAULT 0 NOT NULL, ADD delivered TINYINT(1) DEFAULT 0 NOT NULL, ADD returning TINYINT(1) DEFAULT 0 NOT NULL`.
SQL queries were successful, and new fields were added.

After this RDS schema update, multiple Airbyte syncs on both environments started to fail (added relevant log output). Syncs started to fail for connections, which use  "Incremental | Append" sync mode for the tables. **It is important to mention, that the updated table is not synced by any connection on Airbyte**.

**Resolution**
We tried to reset data and start syncs manually but with no success. We finally solved sync problems by forcing RDS in both environments to create a new binlog file and deleting the older one which was used. After binlog file change, we reset the data and manually started syncs.

**Reproduce the problem**
After the issues were resolved, we tried to reproduce the issue while doing the same RDS schema updates in **develop** environment but couldn't reproduce the issue and break binlog file again.

**Questions**
1. What actually could cause an issue if the updated table is not synced by any Airbyte connection?
2. What steps should be taken to avoid situations like these in the future?
3. What is the best way to resolve problems like this (when binlog file is corrupted)?
4. Is it possible to force Airbyte use a newer binlog file instead of deleting it from RDS?

### Relevant log output

```shell
2023-12-04 08:45:35 source > ERROR i.d.c.m.MySqlStreamingChangeEventSource(logStreamingSourceState):1143 Error during binlog processing. Last offset stored = {transaction_id=null, ts_sec=1701679283, file=mysql-bin-changelog.086509, pos=19208933, server_id=69937904, event=1}, binlog reader near position = mysql-bin-changelog.086509/19208933
2023-12-04 08:45:35 source > ERROR i.d.p.ErrorHandler(setProducerThrowable):57 Producer failure io.debezium.DebeziumException: Error processing binlog event
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleEvent(MySqlStreamingChangeEventSource.java:392) ~[debezium-connector-mysql-2.2.0.Final.jar:2.2.0.Final]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.lambda$execute$27(MySqlStreamingChangeEventSource.java:923) ~[debezium-connector-mysql-2.2.0.Final.jar:2.2.0.Final]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.notifyEventListeners(BinaryLogClient.java:1246) ~[mysql-binlog-connector-java-0.27.2.jar:0.27.2]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:1072) ~[mysql-binlog-connector-java-0.27.2.jar:0.27.2]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:631) ~[mysql-binlog-connector-java-0.27.2.jar:0.27.2]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:932) ~[mysql-binlog-connector-java-0.27.2.jar:0.27.2]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: io.debezium.text.ParsingException: DDL statement couldn't be parsed. Please open a Jira issue with the statement 'ALTER TABLE `order` ADD cancelled TINYINT(1) DEFAULT 0 NOT NULL, ADD delivered TINYINT(1) DEFAULT 0 NOT NULL, ADD returning TINYINT(1) DEFAULT 0 NOT NULL'
no viable alternative at input 'ALTER TABLE `order` ADD cancelled TINYINT(1) DEFAULT 0 NOT NULL, ADD delivered TINYINT(1) DEFAULT 0 NOT NULL, ADD returning'
	at io.debezium.antlr.ParsingErrorListener.syntaxError(ParsingErrorListener.java:43) ~[debezium-ddl-parser-2.2.0.Final.jar:2.2.0.Final]
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41) ~[antlr4-runtime-4.10.1.jar:4.10.1]
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:543) ~[antlr4-runtime-4.10.1.jar:4.10.1]
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:310) ~[antlr4-runtime-4.10.1.jar:4.10.1]
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:136) ~[antlr4-runtime-4.10.1.jar:4.10.1]
	at io.debezium.ddl.parser.mysql.generated.MySqlParser.sqlStatements(MySqlParser.java:1261) ~[debezium-ddl-parser-2.2.0.Final.jar:2.2.0.Final]
	at io.debezium.ddl.parser.mysql.generated.MySqlParser.root(MySqlParser.java:979) ~[debezium-ddl-parser-2.2.0.Final.jar:2.2.0.Final]
	at io.debezium.connector.mysql.antlr.MySqlAntlrDdlParser.parseTree(MySqlAntlrDdlParser.java:74) ~[debezium-connector-mysql-2.2.0.Final.jar:2.2.0.Final]
	at io.debezium.connector.mysql.antlr.MySqlAntlrDdlParser.parseTree(MySqlAntlrDdlParser.java:46) ~[debezium-connector-mysql-2.2.0.Final.jar:2.2.0.Final]
	at io.debezium.antlr.AntlrDdlParser.parse(AntlrDdlParser.java:78) ~[debezium-ddl-parser-2.2.0.Final.jar:2.2.0.Final]
	at io.debezium.connector.mysql.MySqlDatabaseSchema.parseDdl(MySqlDatabaseSchema.java:213) ~[debezium-connector-mysql-2.2.0.Final.jar:2.2.0.Final]
	at io.debezium.connector.mysql.MySqlDatabaseSchema.parseStreamingDdl(MySqlDatabaseSchema.java:199) ~[debezium-connector-mysql-2.2.0.Final.jar:2.2.0.Final]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleQueryEvent(MySqlStreamingChangeEventSource.java:590) ~[debezium-connector-mysql-2.2.0.Final.jar:2.2.0.Final]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.lambda$execute$15(MySqlStreamingChangeEventSource.java:894) ~[debezium-connector-mysql-2.2.0.Final.jar:2.2.0.Final]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleEvent(MySqlStreamingChangeEventSource.java:372) ~[debezium-connector-mysql-2.2.0.Final.jar:2.2.0.Final]
	... 6 more
Caused by: org.antlr.v4.runtime.NoViableAltException
	at org.antlr.v4.runtime.atn.ParserATNSimulator.noViableAlt(ParserATNSimulator.java:2028) ~[antlr4-runtime-4.10.1.jar:4.10.1]
	at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:467) ~[antlr4-runtime-4.10.1.jar:4.10.1]
	at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:393) ~[antlr4-runtime-4.10.1.jar:4.10.1]
	at io.debezium.ddl.parser.mysql.generated.MySqlParser.sqlStatements(MySqlParser.java:1055) ~[debezium-ddl-parser-2.2.0.Final.jar:2.2.0.Final]
	at io.debezium.ddl.parser.mysql.generated.MySqlParser.root(MySqlParser.java:979) ~[debezium-ddl-parser-2.2.0.Final.jar:2.2.0.Final]
	at io.debezium.connector.mysql.antlr.MySqlAntlrDdlParser.parseTree(MySqlAntlrDdlParser.java:74) ~[debezium-connector-mysql-2.2.0.Final.jar:2.2.0.Final]
	at io.debezium.connector.mysql.antlr.MySqlAntlrDdlParser.parseTree(MySqlAntlrDdlParser.java:46) ~[debezium-connector-mysql-2.2.0.Final.jar:2.2.0.Final]
	at io.debezium.antlr.AntlrDdlParser.parse(AntlrDdlParser.java:78) ~[debezium-ddl-parser-2.2.0.Final.jar:2.2.0.Final]
	at io.debezium.connector.mysql.MySqlDatabaseSchema.parseDdl(MySqlDatabaseSchema.java:213) ~[debezium-connector-mysql-2.2.0.Final.jar:2.2.0.Final]
	at io.debezium.connector.mysql.MySqlDatabaseSchema.parseStreamingDdl(MySqlDatabaseSchema.java:199) ~[debezium-connector-mysql-2.2.0.Final.jar:2.2.0.Final]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleQueryEvent(MySqlStreamingChangeEventSource.java:590) ~[debezium-connector-mysql-2.2.0.Final.jar:2.2.0.Final]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.lambda$execute$15(MySqlStreamingChangeEventSource.java:894) ~[debezium-connector-mysql-2.2.0.Final.jar:2.2.0.Final]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleEvent(MySqlStreamingChangeEventSource.java:372) ~[debezium-connector-mysql-2.2.0.Final.jar:2.2.0.Final]
	... 6 more

Stack Trace: io.debezium.DebeziumException: Error processing binlog event
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleEvent(MySqlStreamingChangeEventSource.java:392)
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.lambda$execute$27(MySqlStreamingChangeEventSource.java:923)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.notifyEventListeners(BinaryLogClient.java:1246)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:1072)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:631)
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:932)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.debezium.text.ParsingException: DDL statement couldn't be parsed. Please open a Jira issue with the statement 'ALTER TABLE `order` ADD cancelled TINYINT(1) DEFAULT 0 NOT NULL, ADD delivered TINYINT(1) DEFAULT 0 NOT NULL, ADD returning TINYINT(1) DEFAULT 0 NOT NULL'
no viable alternative at input 'ALTER TABLE `order` ADD cancelled TINYINT(1) DEFAULT 0 NOT NULL, ADD delivered TINYINT(1) DEFAULT 0 NOT NULL, ADD returning'
	at io.debezium.antlr.ParsingErrorListener.syntaxError(ParsingErrorListener.java:43)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:543)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:310)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:136)
	at io.debezium.ddl.parser.mysql.generated.MySqlParser.sqlStatements(MySqlParser.java:1261)
	at io.debezium.ddl.parser.mysql.generated.MySqlParser.root(MySqlParser.java:979)
	at io.debezium.connector.mysql.antlr.MySqlAntlrDdlParser.parseTree(MySqlAntlrDdlParser.java:74)
	at io.debezium.connector.mysql.antlr.MySqlAntlrDdlParser.parseTree(MySqlAntlrDdlParser.java:46)
	at io.debezium.antlr.AntlrDdlParser.parse(AntlrDdlParser.java:78)
	at io.debezium.connector.mysql.MySqlDatabaseSchema.parseDdl(MySqlDatabaseSchema.java:213)
	at io.debezium.connector.mysql.MySqlDatabaseSchema.parseStreamingDdl(MySqlDatabaseSchema.java:199)
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleQueryEvent(MySqlStreamingChangeEventSource.java:590)
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.lambda$execute$15(MySqlStreamingChangeEventSource.java:894)
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleEvent(MySqlStreamingChangeEventSource.java:372)
	... 6 more
Caused by: org.antlr.v4.runtime.NoViableAltException
	at org.antlr.v4.runtime.atn.ParserATNSimulator.noViableAlt(ParserATNSimulator.java:2028)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:467)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:393)
	at io.debezium.ddl.parser.mysql.generated.MySqlParser.sqlStatements(MySqlParser.java:1055)
	... 15 more

2023-12-04 08:45:35 source > INFO i.d.c.m.MySqlStreamingChangeEventSource(handleEvent):397 Error processing binlog event, and propagating to Kafka Connect so it stops this connector. Future binlog events read before connector is shutdown will be ignored.
2023-12-04 08:45:35 source > INFO i.d.e.EmbeddedEngine(run):944 Stopping the task and engine
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by theyueli** [comment]
please reopen if it happens again. Closing it for now.
