### ISSUE TITLE
[needs-investigation] environment is not stable after upgrade

### ISSUE THREAD

**Issue by sivankumar86** [airbytehq/airbyte#33279]
### Platform Version

0.50.34

### What step the error happened?

During the Sync

### Revelant information

lot of attempts during sync which creates many ops p2 alerts in production 

### Relevant log output

```shell
2023-12-09 03:40:04 INFO i.a.w.t.s.a.AppendToAttemptLogActivityImpl(log):56 - Retry State: RetryManager(completeFailureBackoffPolicy=BackoffPolicy(minInterval=PT10S, maxInterval=PT30M, base=3), partialFailureBackoffPolicy=null, successiveCompleteFailureLimit=5, totalCompleteFailureLimit=10, successivePartialFailureLimit=1000, totalPartialFailureLimit=10, successiveCompleteFailures=1, totalCompleteFailures=1, successivePartialFailures=0, totalPartialFailures=0)
 Backoff before next attempt: 10 seconds
2023-12-09 03:45:03 ERROR i.a.w.g.DefaultCheckConnectionWorker(run):133 - Unexpected error while checking connection: 
io.airbyte.workers.exception.WorkerException: Failed to create pod for check step
        at io.airbyte.workers.process.KubeProcessFactory.create(KubeProcessFactory.java:188) ~[io.airbyte-airbyte-commons-worker-0.50.34.jar:?]
        at io.airbyte.workers.process.AirbyteIntegrationLauncher.check(AirbyteIntegrationLauncher.java:143) ~[io.airbyte-airbyte-commons-worker-0.50.34.jar:?]
        at io.airbyte.workers.general.DefaultCheckConnectionWorker.run(DefaultCheckConnectionWorker.java:71) ~[io.airbyte-airbyte-commons-worker-0.50.34.jar:?]
        at io.airbyte.workers.general.DefaultCheckConnectionWorker.run(DefaultCheckConnectionWorker.java:44) ~[io.airbyte-airbyte-commons-worker-0.50.34.jar:?]
        at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:135) ~[io.airbyte-airbyte-workers-0.50.34.jar:?]
        at io.airbyte.workers.temporal.check.connection.CheckConnectionActivityImpl.lambda$runWithJobOutput$1(CheckConnectionActivityImpl.java:133) ~[io.airbyte-airbyte-workers-0.50.34.jar:?]
        at io.airbyte.commons.temporal.HeartbeatUtils.withBackgroundHeartbeat(HeartbeatUtils.java:57) ~[io.airbyte-airbyte-commons-temporal-core-0.50.34.jar:?]
        at io.airbyte.workers.temporal.check.connection.CheckConnectionActivityImpl.runWithJobOutput(CheckConnectionActivityImpl.java:118) ~[io.airbyte-airbyte-workers-0.50.34.jar:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
        at io.temporal.internal.activity.RootActivityInboundCallsInterceptor$POJOActivityInboundCallsInterceptor.executeActivity(RootActivityInboundCallsInterceptor.java:64) ~[temporal-sdk-1.17.0.jar:?]
        at io.temporal.internal.activity.RootActivityInboundCallsInterceptor.execute(RootActivityInboundCallsInterceptor.java:43) ~[temporal-sdk-1.17.0.jar:?]
        at io.temporal.internal.activity.ActivityTaskExecutors$BaseActivityTaskExecutor.execute(ActivityTaskExecutors.java:95) ~[temporal-sdk-1.17.0.jar:?]
        at io.temporal.internal.activity.ActivityTaskHandlerImpl.handle(ActivityTaskHandlerImpl.java:92) ~[temporal-sdk-1.17.0.jar:?]
        at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handleActivity(ActivityWorker.java:241) ~[temporal-sdk-1.17.0.jar:?]
        at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:206) ~[temporal-sdk-1.17.0.jar:?]
        at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:179) ~[temporal-sdk-1.17.0.jar:?]
        at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93) ~[temporal-sdk-1.17.0.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "io.airbyte.workers.process.KubePortManagerSingleton.take()" is null
        at io.airbyte.workers.process.KubeProcessFactory.create(KubeProcessFactory.java:131) ~[io.airbyte-airbyte-commons-worker-0.50.34.jar:?]
```

**Comment by Ageds** [comment]
+1

**Comment by marcosmarxm** [comment]
Can you give more information about from what version you upgraded? Are you running on docker?

**Comment by sivankumar86** [comment]
Upgraded from 0.50.3 to 0.50.34
Running on : k8s
option: control-plane

It seems, issue resolved after restarting pod but, it is not a good solution.Increased worker pod to 6 pods although, we need to only one pods as we have only 20 jobs at a time so that, we can reduce the restart time.

Attached. full log.

[c810ba10_3e93_4c4c_976f_8605746e4520_job_474936_attempt_2_txt.log](https://github.com/airbytehq/airbyte/files/13641577/c810ba10_3e93_4c4c_976f_8605746e4520_job_474936_attempt_2_txt.log)


<img width="1468" alt="Screenshot 2023-12-12 at 9 21 49 am" src="https://github.com/airbytehq/airbyte/assets/5317602/71188d84-5f38-4d0f-87f3-c2d5a63b28a2">

**Comment by sivankumar86** [comment]
Reduced the ports to 30 from 40 but, still this issue is  happening.

**Comment by marcosmarxm** [comment]
Can you share the helm value file and your cluster resource info?
From what version did you upgraded?

Please add as much information is possible to make the problem reproducible. At the moment it isn't...

**Comment by sivankumar86** [comment]
@marcosmarxm I am using custom helm chat and find the worker env values 

          env:
            - name: AIRBYTE_VERSION
              value: {{ .Values.image.tag | default .Chart.AppVersion }}
            - name: CONFIG_ROOT
              value: /config
            - name: DATABASE_HOST
              value: {{ .Values.airbyte.database.host }}
            - name: DATABASE_PORT
              value: "{{ .Values.airbyte.database.port }}"
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: airbyte
                  key: databaseUser
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airbyte
                  key: databasePassword
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: airbyte
                  key: databaseUrl
            - name: TRACKING_STRATEGY
              value: logging
            - name: WORKSPACE_DOCKER_MOUNT
              value: workspace
            - name: WORKSPACE_ROOT
              value: /workspace
            - name: WORKER_ENVIRONMENT
              value: kubernetes
            - name: LOCAL_ROOT
              value: /tmp/airbyte_local
            - name: WEBAPP_URL
              value: {{ .Values.airbyte.web.url }}
            - name: TEMPORAL_HOST
              value: "airbyte-ab-temporal:7233"
            - name: TEMPORAL_WORKER_PORTS
              value: "9001,9002,9003,9004,9005,9006,9007,9008,9009,9010,9011,9012,9013,9014,9015,9016,9017,9018,9019,9020,9021,9022,9023,9024,9025,9026,9027,9028,9029,9030"
            - name: LOG_LEVEL
              value: INFO
            - name: JOB_KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SUBMITTER_NUM_THREADS
              value: "30"
            - name: MAX_SPEC_WORKERS
              value: "6"
            - name: MAX_DISCOVER_WORKERS
              value: "6"
            - name: MAX_SYNC_WORKERS
              value: "6"
            - name: JOB_MAIN_CONTAINER_CPU_REQUEST
              value: "{{ .Values.airbyte.jobResources.requests.cpu }}"
            - name: JOB_KUBE_ANNOTATIONS
              value: "cluster-autoscaler.kubernetes.io/safe-to-evict=true"
            - name: JOB_MAIN_CONTAINER_CPU_LIMIT
              value: "{{ .Values.airbyte.jobResources.limits.cpu }}"
            - name: JOB_MAIN_CONTAINER_MEMORY_REQUEST
              value: "{{ .Values.airbyte.jobResources.requests.memory }}"
            - name: JOB_MAIN_CONTAINER_MEMORY_LIMIT
              value: "{{ .Values.airbyte.jobResources.limits.memory }}"
            - name: JOB_KUBE_MAIN_CONTAINER_IMAGE_PULL_SECRET
              value: artifactory-sec
            - name: JOB_KUBE_SOCAT_IMAGE
              value: "zipau-docker.jfrog.io/alpine/socat:1.7.4.3-r0"
            - name: JOB_KUBE_BUSYBOX_IMAGE
              value: "zipau-docker.jfrog.io/busybox:1.28"
            - name: JOB_KUBE_CURL_IMAGE
              value: "zipau-docker.jfrog.io/curlimages/curl:7.83.1"
            - name: S3_LOG_BUCKET
              value: {{ .Values.airbyte.log.bucket }}
            - name: S3_LOG_BUCKET_REGION
              value: {{ .Values.airbyte.log.region }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: airbyte
                  key: accessKeyId
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: airbyte
                  key: secretAccessKey
            - name: WORKER_LOGS_STORAGE_TYPE
              value: "s3"
            - name: WORKER_STATE_STORAGE_TYPE
              value: "s3"
            - name: S3_PATH_STYLE_ACCESS
              value: "true"
            - name: S3_MINIO_ENDPOINT
              value: ""
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: ""
            - name: GCS_LOG_BUCKET
              value: ""
            - name: STATE_STORAGE_MINIO_BUCKET_NAME
              value: ""
            - name: STATE_STORAGE_MINIO_ACCESS_KEY
              value: ""
            - name: STATE_STORAGE_MINIO_SECRET_ACCESS_KEY
              value: ""
            - name: STATE_STORAGE_MINIO_ENDPOINT
              value: ""
            - name: INTERNAL_API_HOST
              value: airbyte-ab-server:8001
            - name: JOB_KUBE_TOLERATIONS
              value: ""
            - name: JOB_KUBE_NODE_SELECTORS
              value: ""
            - name: AUTO_DETECT_SCHEMA
              value: "true"
            - name: JOB_KUBE_MAIN_CONTAINER_IMAGE_PULL_POLICY
              value: "IfNotPresent"
            - name: STATE_STORAGE_S3_BUCKET_REGION
              value: {{ .Values.airbyte.log.region }}
            - name: STATE_STORAGE_S3_BUCKET_NAME
              value: {{ .Values.airbyte.stateStorage.bucket }}
            - name: STATE_STORAGE_S3_REGION
              value: {{ .Values.airbyte.stateStorage.region }}
            - name: STATE_STORAGE_S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: airbyte
                  key: accessKeyId
            - name: STATE_STORAGE_S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: airbyte
                  key: secretAccessKey
            - name: ACTIVITY_INITIAL_DELAY_BETWEEN_ATTEMPTS_SECONDS
              value: "60"
            - name: CONFIGS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION
              value: "0.35.15.001"
            - name: JOBS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION
              value: "0.29.15.001"
            - name: METRIC_CLIENT
              value: ""
            - name: OTEL_COLLECTOR_ENDPOINT
              value: ""
            - name: MICRONAUT_ENVIRONMENTS
              value: control-plane
            - name: CONTAINER_ORCHESTRATOR_IMAGE
              value: "airbyte/container-orchestrator:{{ .Values.image.tag | default .Chart.AppVersion }}"
            - name: CONTAINER_ORCHESTRATOR_ENABLED
              value: "true"
            - name : USE_STREAM_CAPABLE_STATE
              value: "true"

          ports:
            - name: heartbeat
              containerPort: 9000
              protocol: TCP
            - containerPort: 9001
            - containerPort: 9002
            - containerPort: 9003
            - containerPort: 9004
            - containerPort: 9005
            - containerPort: 9006
            - containerPort: 9007
            - containerPort: 9008
            - containerPort: 9009
            - containerPort: 9010
            - containerPort: 9011
            - containerPort: 9012
            - containerPort: 9013
            - containerPort: 9014
            - containerPort: 9015
            - containerPort: 9016
            - containerPort: 9017
            - containerPort: 9018
            - containerPort: 9019
            - containerPort: 9020
            - containerPort: 9021
            - containerPort: 9022
            - containerPort: 9023
            - containerPort: 9024
            - containerPort: 9025
            - containerPort: 9026
            - containerPort: 9027
            - containerPort: 9028
            - containerPort: 9029
            - containerPort: 9030


resources:
  requests:
    cpu: 200m
    memory: 1024Mi
  limits:
    cpu: 500m
    memory: 2048Mi

From what version did you upgraded?

==>  Upgraded from 0.50.3 to 0.50.34

Reproduce steps:

I guess,  worker is not releasing port if any fail attempts eventually, all the ports are blocked and job failed . it gets fixed upon restart the worker .

1. keep one worker
2. Make sync fail for multiple time for 10 times (all the port would be blocked)
3. Eventually, you start getting above error instead of actual sync fail.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
