### ISSUE TITLE
[custom source] java.lang.NullPointerException - Something went wrong during replication

### ISSUE THREAD

**Issue by jhaynie** [airbytehq/airbyte#33284]
### Connector Name

source-custom

### Connector Version

0.0.0

### What step the error happened?

During the sync

### Relevant information

Build a custom connector which seems to work fine when I test it in the builder. I get back the appropriate records as an array of JSON. The schema is also detected correctly.

Attached are the logs from the job

[airbyte_error_logs.txt](https://github.com/airbytehq/airbyte/files/13630571/airbyte_error_logs.txt)

### Relevant log output

```shell
I get the following from the log when trying to perform the initial sync:

java.lang.RuntimeException: java.lang.NullPointerException
	at io.airbyte.workers.general.ReplicationWorkerHelper.startSource(ReplicationWorkerHelper.kt:184)
	at io.airbyte.workers.general.BufferedReplicationWorker.lambda$run$1(BufferedReplicationWorker.java:153)
	at io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsync$2(BufferedReplicationWorker.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Reader.java:168)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:124)
	at io.airbyte.commons.io.IOs.newBufferedReader(IOs.java:74)
	at io.airbyte.commons.io.LineGobbler.<init>(LineGobbler.java:134)
	at io.airbyte.commons.io.LineGobbler.gobble(LineGobbler.java:73)
	at io.airbyte.workers.internal.DefaultAirbyteSource.start(DefaultAirbyteSource.java:93)
	at io.airbyte.workers.general.ReplicationWorkerHelper.startSource(ReplicationWorkerHelper.kt:182)
	... 6 more
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by jhaynie** [comment]
I was able to mess around with the Record Selector value and now it sinks fine with no error.
