### ISSUE TITLE
Checking that the SQL Server Agent is running using the query

### ISSUE THREAD

**Issue by ssro92** [airbytehq/airbyte#33338]
### Connector Name

source-mssql

### Connector Version

3.1.0

### What step the error happened?

Configuring a new connector

### Relevant information

PLS Added support to Korean MSSQL Server Agent
KR Version Mssql Agent name but, now Only 'SQL Server Agent%' and 'SQL Server 代理%' are supported
- 'SQL Server %' OR 'SQL Server 에이전트%' 

### Relevant log output

```shell
2023-12-12 01:56:22 [46mplatform[0m > Docker volume job log path: /tmp/workspace/58a8f4a3-bb69-4b7c-991f-f1d02e5a098f/0/logs.log
2023-12-12 01:56:22 [46mplatform[0m > Executing worker wrapper. Airbyte version: 0.50.35
2023-12-12 01:56:22 [46mplatform[0m > Attempt 0 to save workflow id for cancellation
2023-12-12 01:56:22 [46mplatform[0m > 
2023-12-12 01:56:22 [46mplatform[0m > Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2023-12-12 01:56:22 [46mplatform[0m > ----- START CHECK -----
2023-12-12 01:56:22 [46mplatform[0m > Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2023-12-12 01:56:22 [46mplatform[0m > 
2023-12-12 01:56:22 [46mplatform[0m > Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2023-12-12 01:56:22 [46mplatform[0m > Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2023-12-12 01:56:22 [46mplatform[0m > Using default value for environment variable LAUNCHDARKLY_KEY: ''
2023-12-12 01:56:22 [46mplatform[0m > Checking if airbyte/source-mssql:3.1.0 exists...
2023-12-12 01:56:22 [46mplatform[0m > airbyte/source-mssql:3.1.0 was found locally.
2023-12-12 01:56:22 [46mplatform[0m > Creating docker container = source-mssql-check-58a8f4a3-bb69-4b7c-991f-f1d02e5a098f-0-fttbh with resources io.airbyte.config.ResourceRequirements@142efbb6[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts null
2023-12-12 01:56:22 [46mplatform[0m > Preparing command: docker run --rm --init -i -w /data/58a8f4a3-bb69-4b7c-991f-f1d02e5a098f/0 --log-driver none --name source-mssql-check-58a8f4a3-bb69-4b7c-991f-f1d02e5a098f-0-fttbh --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/source-mssql:3.1.0 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e FIELD_SELECTION_WORKSPACES= -e USE_STREAM_CAPABLE_STATE=true -e AIRBYTE_ROLE= -e WORKER_ENVIRONMENT=DOCKER -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=0 -e OTEL_COLLECTOR_ENDPOINT=http://host.docker.internal:4317 -e FEATURE_FLAG_CLIENT=config -e AIRBYTE_VERSION=0.50.35 -e WORKER_JOB_ID=58a8f4a3-bb69-4b7c-991f-f1d02e5a098f airbyte/source-mssql:3.1.0 check --config source_config.json
2023-12-12 01:56:22 [46mplatform[0m > Reading messages from protocol version 0.2.0
2023-12-12 01:56:23 [46mplatform[0m > WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
2023-12-12 01:56:23 [46mplatform[0m > WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
2023-12-12 01:56:23 [46mplatform[0m > WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
2023-12-12 01:56:23 [46mplatform[0m > WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
2023-12-12 01:56:23 [46mplatform[0m > 2023-12-12 01:56:23 [32mINFO[m i.a.i.s.m.MssqlSource(main):607 - starting source: class io.airbyte.integrations.source.mssql.MssqlSource
2023-12-12 01:56:23 [46mplatform[0m > 2023-12-12 01:56:23 [32mINFO[m i.a.c.i.b.IntegrationCliParser(parseOptions):126 - integration args: {check=null, config=source_config.json}
2023-12-12 01:56:23 [46mplatform[0m > 2023-12-12 01:56:23 [32mINFO[m i.a.c.i.b.IntegrationRunner(runInternal):132 - Running integration: io.airbyte.cdk.integrations.base.ssh.SshWrappedSource
2023-12-12 01:56:23 [46mplatform[0m > 2023-12-12 01:56:23 [32mINFO[m i.a.c.i.b.IntegrationRunner(runInternal):133 - Command: CHECK
2023-12-12 01:56:23 [46mplatform[0m > 2023-12-12 01:56:23 [32mINFO[m i.a.c.i.b.IntegrationRunner(runInternal):134 - Integration config: IntegrationConfig{command=CHECK, configPath='source_config.json', catalogPath='null', statePath='null'}
2023-12-12 01:56:23 [46mplatform[0m > 2023-12-12 01:56:23 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):278 - Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-12-12 01:56:23 [46mplatform[0m > 2023-12-12 01:56:23 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):278 - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-12-12 01:56:23 [46mplatform[0m > 2023-12-12 01:56:23 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):278 - Unknown keyword display_type - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-12-12 01:56:23 [46mplatform[0m > 2023-12-12 01:56:23 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):278 - Unknown keyword min - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-12-12 01:56:23 [46mplatform[0m > 2023-12-12 01:56:23 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):278 - Unknown keyword max - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-12-12 01:56:23 [46mplatform[0m > 2023-12-12 01:56:23 [32mINFO[m i.a.c.i.b.s.SshTunnel(getInstance):204 - Starting connection with method: NO_TUNNEL
2023-12-12 01:56:23 [46mplatform[0m > 2023-12-12 01:56:23 [32mINFO[m c.z.h.HikariDataSource(<init>):80 - HikariPool-1 - Starting...
2023-12-12 01:56:23 [46mplatform[0m > 2023-12-12 01:56:23 [32mINFO[m c.z.h.HikariDataSource(<init>):82 - HikariPool-1 - Start completed.
2023-12-12 01:56:24 [46mplatform[0m > 2023-12-12 01:56:24 [32mINFO[m i.a.c.i.s.j.AbstractJdbcSource(lambda$getCheckOperations$1):141 - Attempting to get metadata from the database to see if we can connect.
2023-12-12 01:56:24 [46mplatform[0m > 2023-12-12 01:56:24 [32mINFO[m i.a.i.s.m.MssqlSource(lambda$assertCdcEnabledInDb$16):372 - Checking that cdc is enabled on database 'JOB_DB30_GI' using the query: 'SELECT name, is_cdc_enabled FROM sys.databases WHERE name = ?'
2023-12-12 01:56:24 [46mplatform[0m > 2023-12-12 01:56:24 [32mINFO[m i.a.c.d.j.s.AdaptiveStreamingQueryConfig(initialize):31 - Set initial fetch size: 10 rows
2023-12-12 01:56:24 [46mplatform[0m > 2023-12-12 01:56:24 [32mINFO[m i.a.i.s.m.MssqlSource(lambda$assertCdcSchemaQueryable$17):404 - Checking user 'AWS_Glue_User' can query the cdc schema and that we have at least 1 cdc enabled table using the query: 'USE [JOB_DB30_GI]; SELECT * FROM cdc.change_tables'
2023-12-12 01:56:24 [46mplatform[0m > 2023-12-12 01:56:24 [32mINFO[m i.a.c.d.j.s.AdaptiveStreamingQueryConfig(initialize):31 - Set initial fetch size: 10 rows
2023-12-12 01:56:24 [46mplatform[0m > 2023-12-12 01:56:24 [32mINFO[m i.a.c.d.j.s.AdaptiveStreamingQueryConfig(accept):40 - Set new fetch size: 274784 rows
2023-12-12 01:56:24 [46mplatform[0m > 2023-12-12 01:56:24 [32mINFO[m i.a.c.d.j.s.TwoStageSizeEstimator(getTargetBufferByteSize):71 - Max memory limit: 37983617024, JDBC buffer size: 22790170214
2023-12-12 01:56:24 [46mplatform[0m > 2023-12-12 01:56:24 [32mINFO[m i.a.i.s.m.MssqlSource(lambda$assertSqlServerAgentRunning$18):424 - Checking that the SQL Server Agent is running using the query: 'SELECT status_desc FROM sys.dm_server_services WHERE [servicename] LIKE 'SQL Server Agent%' OR [servicename] LIKE 'SQL Server 代理%' '
2023-12-12 01:56:24 [46mplatform[0m > 2023-12-12 01:56:24 [32mINFO[m i.a.c.d.j.s.AdaptiveStreamingQueryConfig(initialize):31 - Set initial fetch size: 10 rows
2023-12-12 01:56:24 [46mplatform[0m > 2023-12-12 01:56:24 [32mINFO[m i.a.c.i.s.r.AbstractDbSource(check):108 - Exception while checking connection: 
2023-12-12 01:56:24 [46mplatform[0m > java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
2023-12-12 01:56:24 [46mplatform[0m > 	at java.base/java.util.ImmutableCollections$ListN.get(ImmutableCollections.java:680) ~[?:?]
2023-12-12 01:56:24 [46mplatform[0m > 	at io.airbyte.integrations.source.mssql.MssqlSource.assertSqlServerAgentRunning(MssqlSource.java:428) ~[io.airbyte.airbyte-integrations.connectors-source-mssql-0.50.34.jar:?]
2023-12-12 01:56:24 [46mplatform[0m > 	at io.airbyte.integrations.source.mssql.MssqlSource.lambda$getCheckOperations$14(MssqlSource.java:359) ~[io.airbyte.airbyte-integrations.connectors-source-mssql-0.50.34.jar:?]
2023-12-12 01:56:24 [46mplatform[0m > 	at io.airbyte.cdk.integrations.source.relationaldb.AbstractDbSource.check(AbstractDbSource.java:94) ~[airbyte-cdk-db-sources-0.6.2.jar:?]
2023-12-12 01:56:24 [46mplatform[0m > 	at io.airbyte.integrations.source.mssql.MssqlSource.check(MssqlSource.java:125) ~[io.airbyte.airbyte-integrations.connectors-source-mssql-0.50.34.jar:?]
2023-12-12 01:56:24 [46mplatform[0m > 	at io.airbyte.cdk.integrations.base.ssh.SshTunnel.sshWrap(SshTunnel.java:270) [airbyte-cdk-core-0.6.2.jar:?]
2023-12-12 01:56:24 [46mplatform[0m > 	at io.airbyte.cdk.integrations.base.ssh.SshWrappedSource.check(SshWrappedSource.java:54) [airbyte-cdk-core-0.6.2.jar:?]
2023-12-12 01:56:24 [46mplatform[0m > 	at io.airbyte.cdk.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:150) [airbyte-cdk-core-0.6.2.jar:?]
2023-12-12 01:56:24 [46mplatform[0m > 	at io.airbyte.cdk.integrations.base.IntegrationRunner.run(IntegrationRunner.java:125) [airbyte-cdk-core-0.6.2.jar:?]
2023-12-12 01:56:24 [46mplatform[0m > 	at io.airbyte.integrations.source.mssql.MssqlSource.main(MssqlSource.java:608) [io.airbyte.airbyte-integrations.connectors-source-mssql-0.50.34.jar:?]
2023-12-12 01:56:24 [46mplatform[0m > 2023-12-12 01:56:24 [32mINFO[m c.z.h.HikariDataSource(close):350 - HikariPool-1 - Shutdown initiated...
2023-12-12 01:56:24 [46mplatform[0m > 2023-12-12 01:56:24 [32mINFO[m c.z.h.HikariDataSource(close):352 - HikariPool-1 - Shutdown completed.
2023-12-12 01:56:24 [46mplatform[0m > 2023-12-12 01:56:24 [32mINFO[m i.a.c.i.b.IntegrationRunner(runInternal):228 - Completed integration: io.airbyte.cdk.integrations.base.ssh.SshWrappedSource
2023-12-12 01:56:24 [46mplatform[0m > 2023-12-12 01:56:24 [32mINFO[m i.a.i.s.m.MssqlSource(main):609 - completed source: class io.airbyte.integrations.source.mssql.MssqlSource
2023-12-12 01:56:24 [46mplatform[0m > Check connection job received output: io.airbyte.config.StandardCheckConnectionOutput@218fdee1[status=failed,message=Could not connect with provided configuration. Error: Index 0 out of bounds for length 0,additionalProperties={}]
2023-12-12 01:56:24 [46mplatform[0m > 
2023-12-12 01:56:24 [46mplatform[0m > ----- END CHECK -----
2023-12-12 01:56:24 [46mplatform[0m >
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 365 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.
