### ISSUE TITLE
[destination-s3-glue] `NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.isArray()`

### ISSUE THREAD

**Issue by AhmedSKBHL** [airbytehq/airbyte#33422]
### Connector Name

s3 glue

### Connector Version

0.1.7

### What step the error happened?

During the sync

### Relevant information

Hello, job fails between stripe (source) and s3 glue (destination)

### Relevant log output

```shell
2023-12-13 14:43:31 destination > ERROR i.a.i.d.b.BufferedStreamConsumer(close):285 Close failed. java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.isArray()" because "type" is null
	at io.airbyte.integrations.destination.s3_glue.GlueOperations.filterTypes(GlueOperations.java:171) ~[io.airbyte.airbyte-integrations.connectors-destination-s3-glue-0.44.3.jar:?]
	at io.airbyte.integrations.destination.s3_glue.GlueOperations.transformSchemaRecursive(GlueOperations.java:124) ~[io.airbyte.airbyte-integrations.connectors-destination-s3-glue-0.44.3.jar:?]
	at io.airbyte.integrations.destination.s3_glue.GlueOperations.lambda$transformSchema$0(GlueOperations.java:116) ~[io.airbyte.airbyte-integrations.connectors-destination-s3-glue-0.44.3.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at io.airbyte.integrations.destination.s3_glue.GlueOperations.transformSchema(GlueOperations.java:117) ~[io.airbyte.airbyte-integrations.connectors-destination-s3-glue-0.44.3.jar:?]
	at io.airbyte.integrations.destination.s3_glue.GlueOperations.upsertTable(GlueOperations.java:87) ~[io.airbyte.airbyte-integrations.connectors-destination-s3-glue-0.44.3.jar:?]
	at io.airbyte.integrations.destination.s3_glue.S3GlueConsumerFactory.lambda$onCloseFunction$3(S3GlueConsumerFactory.java:170) ~[io.airbyte.airbyte-integrations.connectors-destination-s3-glue-0.44.3.jar:?]
	at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.close(BufferedStreamConsumer.java:273) ~[io.airbyte.airbyte-integrations.bases-base-java-0.44.3.jar:?]
	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.close(FailureTrackingAirbyteMessageConsumer.java:82) ~[io.airbyte.airbyte-integrations.bases-base-java-0.44.3.jar:?]
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:152) ~[io.airbyte.airbyte-integrations.bases-base-java-0.44.3.jar:?]
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:101) ~[io.airbyte.airbyte-integrations.bases-base-java-0.44.3.jar:?]
	at io.airbyte.integrations.destination.s3_glue.S3GlueDestination.main(S3GlueDestination.java:36) ~[io.airbyte.airbyte-integrations.connectors-destination-s3-glue-0.44.3.jar:?]

Stack Trace: java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.isArray()" because "type" is null
	at io.airbyte.integrations.destination.s3_glue.GlueOperations.filterTypes(GlueOperations.java:171)
	at io.airbyte.integrations.destination.s3_glue.GlueOperations.transformSchemaRecursive(GlueOperations.java:124)
	at io.airbyte.integrations.destination.s3_glue.GlueOperations.lambda$transformSchema$0(GlueOperations.java:116)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.airbyte.integrations.destination.s3_glue.GlueOperations.transformSchema(GlueOperations.java:117)
	at io.airbyte.integrations.destination.s3_glue.GlueOperations.upsertTable(GlueOperations.java:87)
	at io.airbyte.integrations.destination.s3_glue.S3GlueConsumerFactory.lambda$onCloseFunction$3(S3GlueConsumerFactory.java:170)
	at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.close(BufferedStreamConsumer.java:273)
	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.close(FailureTrackingAirbyteMessageConsumer.java:82)
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:152)
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:101)
	at io.airbyte.integrations.destination.s3_glue.S3GlueDestination.main(S3GlueDestination.java:36)

2023-12-13 14:43:31 destination > ERROR i.a.i.b.AirbyteExceptionHandler(uncaughtException):26 Something went wrong in the connector. See the logs for more details. java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.isArray()" because "type" is null
	at io.airbyte.integrations.destination.s3_glue.GlueOperations.filterTypes(GlueOperations.java:171) ~[io.airbyte.airbyte-integrations.connectors-destination-s3-glue-0.44.3.jar:?]
	at io.airbyte.integrations.destination.s3_glue.GlueOperations.transformSchemaRecursive(GlueOperations.java:124) ~[io.airbyte.airbyte-integrations.connectors-destination-s3-glue-0.44.3.jar:?]
	at io.airbyte.integrations.destination.s3_glue.GlueOperations.lambda$transformSchema$0(GlueOperations.java:116) ~[io.airbyte.airbyte-integrations.connectors-destination-s3-glue-0.44.3.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at io.airbyte.integrations.destination.s3_glue.GlueOperations.transformSchema(GlueOperations.java:117) ~[io.airbyte.airbyte-integrations.connectors-destination-s3-glue-0.44.3.jar:?]
	at io.airbyte.integrations.destination.s3_glue.GlueOperations.upsertTable(GlueOperations.java:87) ~[io.airbyte.airbyte-integrations.connectors-destination-s3-glue-0.44.3.jar:?]
	at io.airbyte.integrations.destination.s3_glue.S3GlueConsumerFactory.lambda$onCloseFunction$3(S3GlueConsumerFactory.java:170) ~[io.airbyte.airbyte-integrations.connectors-destination-s3-glue-0.44.3.jar:?]
	at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.close(BufferedStreamConsumer.java:273) ~[io.airbyte.airbyte-integrations.bases-base-java-0.44.3.jar:?]
	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.close(FailureTrackingAirbyteMessageConsumer.java:82) ~[io.airbyte.airbyte-integrations.bases-base-java-0.44.3.jar:?]
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:152) ~[io.airbyte.airbyte-integrations.bases-base-java-0.44.3.jar:?]
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:101) ~[io.airbyte.airbyte-integrations.bases-base-java-0.44.3.jar:?]
	at io.airbyte.integrations.destination.s3_glue.S3GlueDestination.main(S3GlueDestination.java:36) ~[io.airbyte.airbyte-integrations.connectors-destination-s3-glue-0.44.3.jar:?]

Stack Trace: java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.isArray()" because "type" is null
	at io.airbyte.integrations.destination.s3_glue.GlueOperations.filterTypes(GlueOperations.java:171)
	at io.airbyte.integrations.destination.s3_glue.GlueOperations.transformSchemaRecursive(GlueOperations.java:124)
	at io.airbyte.integrations.destination.s3_glue.GlueOperations.lambda$transformSchema$0(GlueOperations.java:116)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.airbyte.integrations.destination.s3_glue.GlueOperations.transformSchema(GlueOperations.java:117)
	at io.airbyte.integrations.destination.s3_glue.GlueOperations.upsertTable(GlueOperations.java:87)
	at io.airbyte.integrations.destination.s3_glue.S3GlueConsumerFactory.lambda$onCloseFunction$3(S3GlueConsumerFactory.java:170)
	at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.close(BufferedStreamConsumer.java:273)
	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.close(FailureTrackingAirbyteMessageConsumer.java:82)
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:152)
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:101)
	at io.airbyte.integrations.destination.s3_glue.S3GlueDestination.main(S3GlueDestination.java:36)

2023-12-13 14:43:31 platform > readFromDestination: exception caught
io.airbyte.workers.internal.exception.DestinationException: Destination process exited with non-zero exit code 1
	at io.airbyte.workers.general.BufferedReplicationWorker.readFromDestination(BufferedReplicationWorker.java:477) ~[io.airbyte-airbyte-commons-worker-0.50.35.jar:?]
	at io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsync$2(BufferedReplicationWorker.java:228) ~[io.airbyte-airbyte-commons-worker-0.50.35.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
2023-12-13 14:43:31 platform > readFromDestination: done. (writeToDestFailed:false, dest.isFinished:true)
2023-12-13 14:43:31 platform > sync summary: {
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
