### ISSUE TITLE
"Normalization Failed" on Salesforce -> Snowflake sync process

### ISSUE THREAD

**Issue by royt-via** [airbytehq/airbyte#3364]
## Expected Behavior
Sync shouldn't fail :)

## Current Behavior
Sync fails with "Normalization Failed" exception

## Logs
[logs](https://drive.google.com/file/d/1TmGeoTJml7ghqHjquBT4mYXfhqdQWTxQ/view?usp=sharing)

## Steps to Reproduce
1. Sync Salesforce -> Snowflake 

## Severity of the bug for you
Critical
Can't sync Salesforce source

## Airbyte Version
0.22.2-alpha

## Connector Version (if applicable)
Salesforce - 0.2.1

## Additional context
t3a.xlarge ec2

**Comment by marcosmarxm** [comment]
Thanks @royt-via for reporting this!
```
2021-05-11 15:33:30 INFO (/tmp/workspace/15/1) LineGobbler(voidCall):69 -  [31mUnhandled error while executing model.airbyte_utils.RAW_DRIVER__C_AB3_0E2 [0m
2021-05-11 15:33:30 INFO (/tmp/workspace/15/1) LineGobbler(voidCall):69 - maximum recursion depth exceeded
2021-05-11 15:33:30 INFO (/tmp/workspace/15/1) LineGobbler(voidCall):69 - 15:33:30 | 1 of 1 SKIP relation AIRBYTE.RAW_DRIVER__C_1CB due to ephemeral model error.................................. [ [31mERROR SKIP [0m]
```

**Comment by royt-via** [comment]
@marcosmarxm is there a time line to when this issue (and maybe also [this](https://github.com/airbytehq/airbyte/issues/3251) one) will be fixed?
I'd really like to use Airbyte but these 2 issues are blocking me from doing so (can't sync PG nor Salesforce sources)

**Comment by marcosmarxm** [comment]
@royt-via I'll request to the team take a look at this normalization problem. About the other issue, it's on the current sprint possibly be solved this week or max next.

**Comment by ChristopheDuong** [comment]
Can you share more information?

The following commands are described as part of https://docs.airbyte.io/tutorials/browsing-output-logs

1. What is the catalog.json of the stream? That would allow us to run normalization generation on our side to reproduce
```
docker run -it --rm -v airbyte_workspace:/data busybox find /data/15/1/normalize/destination_catalog.json -type f -exec cat "{}" \;
```

2. Most importantly, what do the generated files by normalization look like?
```
docker run -it --rm -v airbyte_workspace:/data busybox find /data/15/1/normalize/models/generated/ -type f -exec cat "{}" \;
```

Maybe it's easier, if you export the whole workspace of the sync and select the appropriate files (so you can exclude credentials from source_config.json and destination_config.json) from, make a zip and share?
```
docker cp airbyte-server:/tmp/workspace/15/0/ <my_export_folder>
```

**Comment by royt-via** [comment]
Thanks you, @ChristopheDuong !
[Here's](https://drive.google.com/file/d/1rw3kTQIm0QKRcNFKSQW9viKK2D8zS-kq/view?usp=sharing) the exported workspace (option 3).
Please lmk if there's something else you need.

**Comment by ChristopheDuong** [comment]
Thanks for the additional files...

Here is more details from dbt's log files:
```
2021-05-11 15:33:30.251782 (Thread-5): Unhandled error while executing model.airbyte_utils.RAW_DRIVER__C_AB3_0E2
maximum recursion depth exceeded
2021-05-11 15:33:30.252006 (Thread-5): 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/dbt/task/base.py", line 333, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/usr/local/lib/python3.7/site-packages/dbt/task/base.py", line 270, in compile_and_execute
    ctx.node = self.compile(manifest)
  File "/usr/local/lib/python3.7/site-packages/dbt/task/compile.py", line 23, in compile
    return compiler.compile_node(self.node, manifest, {})
  File "/usr/local/lib/python3.7/site-packages/dbt/compilation.py", line 479, in compile_node
    node = self._compile_node(node, manifest, extra_context)
  File "/usr/local/lib/python3.7/site-packages/dbt/compilation.py", line 394, in _compile_node
    compiled_node, manifest, extra_context
  File "/usr/local/lib/python3.7/site-packages/dbt/compilation.py", line 356, in _insert_ctes
    compiled_node, manifest, extra_context
  File "/usr/local/lib/python3.7/site-packages/dbt/compilation.py", line 323, in _recursively_prepend_ctes
    model = self._model_prepend_ctes(model, prepended_ctes)
  File "/usr/local/lib/python3.7/site-packages/dbt/compilation.py", line 274, in _model_prepend_ctes
    prepended_ctes,
  File "/usr/local/lib/python3.7/site-packages/dbt/compilation.py", line 234, in _inject_ctes_into_sql
    parsed_stmts = sqlparse.parse(sql)
  File "/usr/local/lib/python3.7/site-packages/sqlparse/__init__.py", line 32, in parse
    return tuple(parsestream(sql, encoding))
  File "/usr/local/lib/python3.7/site-packages/sqlparse/engine/filter_stack.py", line 37, in run
    stmt = grouping.group(stmt)
  File "/usr/local/lib/python3.7/site-packages/sqlparse/engine/grouping.py", line 419, in group
    func(stmt)
  File "/usr/local/lib/python3.7/site-packages/sqlparse/engine/grouping.py", line 267, in group_operator
    valid_prev, valid_next, post, extend=False)
  File "/usr/local/lib/python3.7/site-packages/sqlparse/engine/grouping.py", line 441, in _group
    _group(token, cls, match, valid_prev, valid_next, post, extend)
  File "/usr/local/lib/python3.7/site-packages/sqlparse/engine/grouping.py", line 441, in _group
    _group(token, cls, match, valid_prev, valid_next, post, extend)
  File "/usr/local/lib/python3.7/site-packages/sqlparse/engine/grouping.py", line 441, in _group
    _group(token, cls, match, valid_prev, valid_next, post, extend)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.7/site-packages/sqlparse/engine/grouping.py", line 447, in _group
    grp = tlist.group_tokens(cls, from_idx, to_idx, extend=extend)
  File "/usr/local/lib/python3.7/site-packages/sqlparse/sql.py", line 334, in group_tokens
    grp = grp_cls(subtokens)
  File "/usr/local/lib/python3.7/site-packages/sqlparse/sql.py", line 166, in __init__
    super(TokenList, self).__init__(None, text_type(self))
  File "/usr/local/lib/python3.7/site-packages/sqlparse/sql.py", line 170, in __str__
    return u''.join(token.value for token in self.flatten())
  File "/usr/local/lib/python3.7/site-packages/sqlparse/sql.py", line 170, in <genexpr>
    return u''.join(token.value for token in self.flatten())
  File "/usr/local/lib/python3.7/site-packages/sqlparse/sql.py", line 219, in flatten
    for item in token.flatten():
  File "/usr/local/lib/python3.7/site-packages/sqlparse/sql.py", line 219, in flatten
    for item in token.flatten():
  File "/usr/local/lib/python3.7/site-packages/sqlparse/sql.py", line 219, in flatten
    for item in token.flatten():
  [Previous line repeated 962 more times]
RecursionError: maximum recursion depth exceeded
```
