### ISSUE TITLE
[Source Teradata] - Unable to connect to database due to JDBC Type 4 driver

### ISSUE THREAD

**Issue by philippeboyd** [airbytehq/airbyte#33655]
### Connector Name

source-teradata

### Connector Version

0.2.0

### What step the error happened?

Configuring a new connector

### Relevant information

I'm trying to implement SSH for Teradata but even so, it doesn't work without. I need to be able to specify an IP and Port. But there's a validation done on the IP and port and I get the error. It seems the port with [Teradata is to be set with `DBS_PORT`](https://teradata-docs.s3.amazonaws.com/doc/connectivity/jdbc/reference/current/jdbcug_chapter_2.html#BABJIHBJ)

```
java.net.UnknownHostException: <IPV4_REDACTED>:5050: invalid IPv6 address literal
```
The error message suggests with the port number it is being interpreted as a malformed IPv6 address.

### Relevant log output

```shell
2023-12-19 20:57:41 platform > 2023-12-19.20:57:41.169 TERAJDBC4 ERROR [HikariPool-1 connection adder] com.teradata.jdbc.jdbc_4.TDSession@26c32e74 Connection to <IPV4_REDACTED>:5050 Tue Dec 19 20:57:41 UTC 2023 socket orig=<IPV4_REDACTED>:5050 cid=194239a8 sess=0 java.net.UnknownHostException: <IPV4_REDACTED>:5050: invalid IPv6 address literal
  at java.base/java.net.InetAddress.invalidIPv6LiteralException(InetAddress.java:1390)
  at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1360)
  at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
  at com.teradata.jdbc.jdbc_4.io.TDNetworkIOIF$Lookup.doLookup(TDNetworkIOIF.java:241)
  at com.teradata.jdbc.jdbc_4.io.TDNetworkIOIF$Lookup.isLiteralIpAddress(TDNetworkIOIF.java:267)
  at com.teradata.jdbc.jdbc_4.io.TDNetworkIOIF.connectToHost(TDNetworkIOIF.java:413)
  at com.teradata.jdbc.jdbc_4.io.TDNetworkIOIF.createSocketConnection(TDNetworkIOIF.java:187)
  at com.teradata.jdbc.jdbc_4.io.TDNetworkIOIF.createIO(TDNetworkIOIF.java:178)
  at com.teradata.jdbc.jdbc.GenericTeradataConnection.<init>(GenericTeradataConnection.java:346)
  at com.teradata.jdbc.jdbc_4.TDSession.<init>(TDSession.java:180)
  at com.teradata.jdbc.jdbc.ConnectionFactory.createConnection(ConnectionFactory.java:63)
  at com.teradata.jdbc.jdbc.ConnectionFactory.createConnection(ConnectionFactory.java:53)
  at com.teradata.jdbc.TeraDriver.doConnect(TeraDriver.java:232)
  at com.teradata.jdbc.TeraDriver.connect(TeraDriver.java:165)
  at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
  at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
  at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
  at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
  at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:733)
  at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  at java.base/java.lang.Thread.run(Thread.java:833)
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by Fabrizib** [comment]
I am also having this issue
@philippeboyd Have you found any solution for this?

**Comment by philippeboyd** [comment]
@Fabrizib Unfortunately, no. And I'm not working on the new connector anymore.

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 180 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
