### ISSUE TITLE
[CONFLUNECE] How to support http sync data?

### ISSUE THREAD

**Issue by ScGPS** [airbytehq/airbyte#33773]
### Connector Name

source-confluence

### Connector Version

0.50.2

### What step the error happened?

During the sync

### Relevant information

Configure http(Confluence and Elasticsearch) web, there is an issue about sync data.
```
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by ScGPS** [comment]
I have fixed this issue.
```
source_confluence/source.py
Change
class ConfluenceStream(HttpStream, ABC):
    url_base = "https://{}/rest/api/"

To

class ConfluenceStream(HttpStream, ABC):
    url_base = "http://{}/rest/api/"
```
![image](https://github.com/airbytehq/airbyte/assets/10125111/a39104ae-1c96-4126-9c82-6b1b0409aeff)
