### ISSUE TITLE
HikariPool-1  Connection is not available, request timed out after 60001ms.

### ISSUE THREAD

**Issue by Thaksinna** [airbytehq/airbyte#33821]
### Connector Name.    Postgres -> clickhouse 

source-postgres

### Connector Version

0.2.63

### What step the error happened?

During the sync

### Relevant information

        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:532)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:637)
        at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:280)
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:385)
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:407)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1430)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1401)
        at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:226)
        at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:101)
        at com.clickhouse.client.AbstractClient.execute(AbstractClient.java:296)
        at com.clickhouse.client.ClickHouseClientBuilder$Agent.sendOnce(ClickHouseClientBuilder.java:191)
        at com.clickhouse.client.ClickHouseClientBuilder$Agent.send(ClickHouseClientBuilder.java:202)
        at com.clickhouse.client.ClickHouseClientBuilder$Agent.execute(ClickHouseClientBuilder.java:234)
        at com.clickhouse.client.ClickHouseRequest.execute(ClickHouseRequest.java:1748)
        at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.getServerInfo(ClickHouseConnectionImpl.java:79)
        ... 14 more
2023-12-28 04:08:26 platform > INFO c.z.h.HikariDataSource(close):350 HikariPool-1 - Shutdown initiated...
2023-12-28 04:08:26 platform > INFO c.z.h.HikariDataSource(close):352 HikariPool-1 - Shutdown completed.
2023-12-28 04:08:26 platform > INFO i.a.i.b.IntegrationRunner(runInternal):195 Completed integration: io.airbyte.integrations.base.ssh.SshWrappedDestination
2023-12-28 04:08:26 platform > INFO i.a.i.d.c.ClickhouseDestination(main):115 completed destination: class io.airbyte.integrations.destination.clickhouse.ClickhouseDestination
2023-12-28 04:08:26 platform > Check connection job received output: io.airbyte.config.StandardCheckConnectionOutput@11908bb9[status=failed,message=Could not connect with provided configuration. 
java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 60001ms.,additionalProperties={}]
2023-12-28 04:08:26 platform > 
2023-12-28 04:08:26 platform > ----- END CHECK -----
2023-12-28 04:08:26 platform > 
2023-12-28 04:08:26 platform > Retry State: RetryManager(completeFailureBackoffPolicy=BackoffPolicy(minInterval=PT10S, maxInterval=PT30M, base=3), partialFailureBackoffPolicy=null, successiveCompleteFailureLimit=5, totalCompleteFailureLimit=10, successivePartialFailureLimit=1000, totalPartialFailureLimit=10, successiveCompleteFailures=1, totalCompleteFailures=1, successivePartialFailures=0, totalPartialFailures=0)
 Backoff before next attempt: 10 seconds
2023-12-28 04:08:26 platform > Failing job: 1005, reason: Connection Check Failed d1dc06fa-e739-4ab2-928e-4a7283812d61

### Contribute

- [X] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
This means Airbyte wasn't able to connect to the database. Please make sure your istance have the proper configuration.
