### ISSUE TITLE
mysql normalization failed locally

### ISSUE THREAD

**Issue by himanshu046** [airbytehq/airbyte#33826]
platform :- airbyte
source :- mysql
destination :- mysql

I just built the "normalization-mysql," "destination-mysql:0.0.1," and "source-mysql:0.0.1" images locally using the same Airbyte code,  After a successful build, when I sync the connector (MySQL to MySQL), an error occurs.

I know that using the "airbyte/normalization-mysql" image works fine, but the error occurs when I build the MySQL normalization image locally. Can you help me identify the issue?

some debuge information
work fine with basic sync (without normalization)

logs ....

2023-12-25 13:12:16 normalization >     from normalization.transform_config.transform import main
2023-12-25 13:12:16 INFO i.a.w.t.TemporalAttemptExecution(lambda$getWorkerThread$2):162 - Completing future exceptionally...
io.airbyte.workers.exception.WorkerException: Normalization Failed.
	at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:92) ~[io.airbyte-airbyte-workers-0.40.6.jar:?]
	at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:27) ~[io.airbyte-airbyte-workers-0.40.6.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:159) ~[io.airbyte-airbyte-workers-0.40.6.jar:?]
	at java.lang.Thread.run(Thread.java:1589) [?:?]
 2023-12-25 13:12:16 normalization >   File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/connector.py", line 14, in <module>
 2023-12-25 13:12:16 WARN i.t.i.a.POJOActivityTaskHandler(activityFailureToResult):307 - Activity failure. ActivityId=1817b4e2-ed0c-3c57-95aa-e95875ac9509, activityType=Normalize, attempt=1
 java.lang.RuntimeException: io.temporal.serviceclient.CheckedExceptionWrapper: java.util.concurrent.ExecutionException: io.airbyte.workers.exception.WorkerException: Normalization Failed.
 	at io.airbyte.workers.temporal.TemporalUtils.withBackgroundHeartbeat(TemporalUtils.java:310) ~[io.airbyte-airbyte-workers-0.40.6.jar:?]
 	at io.airbyte.workers.temporal.sync.NormalizationActivityImpl.normalize(NormalizationActivityImpl.java:80) ~[io.airbyte-airbyte-workers-0.40.6.jar:?]
 	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
 	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
....
2023-12-25 13:12:16 normalization >   File "pydantic/__init__.py", line 2, in init pydantic.__init__
 2023-12-25 13:12:16 normalization >   File "pydantic/dataclasses.py", line 41, in init pydantic.dataclasses
 2023-12-25 13:12:16 normalization >     # | <blank> | No action: no method is added.          |
 2023-12-25 13:12:16 normalization > ImportError: cannot import name dataclass_transform
 2023-12-25 13:12:16 ERROR i.t.i.s.WorkflowExecuteRunnable(logWorkflowExecutionException):125 - Workflow execution failure WorkflowId=sync_944, RunId=9e19d2f8-4087-40f3-af4b-ee2e0fbc62ce, WorkflowType=SyncWorkflow
 io.temporal.failure.ActivityFailure: scheduledEventId=24, startedEventId=25, activityType='Normalize', activityId='1817b4e2-ed0c-3c57-95aa-e95875ac9509', identity='1@19936f29535b', retryState=RETRY_STATE_MAXIMUM_ATTEMPTS_REACHED
 	at java.lang.Thread.getStackTrace(Thread.java:2550) ~[?:?]
 	at io.temporal.internal.sync.ActivityStubBase.execute(ActivityStubBase.java:48) ~[temporal-sdk-1.8.1.jar:?]
 	at io.temporal.internal.sync.ActivityInvocationHandler.lambda$getActivityFunc$0(ActivityInvocationHandler.java:77) ~[temporal-sdk-1.8.1.jar:?]
 	at io.temporal.internal.sync.ActivityInvocationHandlerBase.invoke(ActivityInvocationHandlerBase.java:70) ~[temporal-sdk-1.8.1.jar:?]
 	at jdk.proxy2.$Proxy69.normalize(Unknown Source) ~[?:?]
 	
 	
 	for the more information and details please let me know

_Originally posted by @himanshu046 in https://github.com/airbytehq/airbyte/discussions/33774_

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
