### ISSUE TITLE
Redshift NullPointerException in hasUnprocessedRecords

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#33945]
A Bug from our beta test users ([slack](https://airbytehq-team.slack.com/archives/C0690DFUDGS/p1704388357215549?thread_ts=1704317572.946759&cid=C0690DFUDGS))

```
2024-01-04 13:16:59 destination > 	Caused by: java.lang.NullPointerException: Cannot invoke "io.airbyte.integrations.base.destination.typing_deduping.DestinationHandler$InitialRawTableState.hasUnprocessedRecords()" because the return value of "java.util.Map.get(Object)" is null
2024-01-04 13:16:59 destination > 		at io.airbyte.integrations.base.destination.typing_deduping.DefaultTyperDeduper.lambda$typeAndDedupe$6(DefaultTyperDeduper.java:273) ~[airbyte-cdk-typing-deduping-0.10.2.jar:?]
2024-01-04 13:16:59 destination > 		at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
2024-01-04 13:16:59 destination > 		at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
2024-01-04 13:17:00 destination > 		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
2024-01-04 13:17:00 destination > 		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
2024-01-04 13:17:00 destination > 		at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
2024-01-04 13:17:00 destination > 		at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
2024-01-04 13:17:00 destination > 		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
2024-01-04 13:17:00 destination > 		at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
2024-01-04 13:17:00 destination > 		at io.airbyte.integrations.base.destination.typing_deduping.DefaultTyperDeduper.typeAndDedupe(DefaultTyperDeduper.java:285) ~[airbyte-cdk-typing-deduping-0.10.2.jar:?]
2024-01-04 13:17:00 destination > 		at io.airbyte.cdk.integrations.destination.staging.GeneralStagingFunctions.lambda$onCloseFunction$1(GeneralStagingFunctions.java:123) ~[airbyte-cdk-db-destinations-0.10.2.jar:?]
2024-01-04 13:17:00 destination > 		at io.airbyte.cdk.integrations.destination.staging.StagingConsumerFactory.lambda$createAsync$0(StagingConsumerFactory.java:118) ~[airbyte-cdk-s3-destinations-0.10.2.jar:?]
```

Full sync log here: 
[f05d2773_e10a_48b4_82c2_8b3f88d23f98_job_8612_attempt_13_txt.txt](https://github.com/airbytehq/airbyte/files/13833578/f05d2773_e10a_48b4_82c2_8b3f88d23f98_job_8612_attempt_13_txt.txt)

**Comment by gisripa** [comment]
This error surfaced due to connection issue. and trying to do Type&Dedupe when setup fails leads to NPE.
