### ISSUE TITLE
[source-mongodb] error 'not authorized on admin to execute command'

### ISSUE THREAD

**Issue by smhmh** [airbytehq/airbyte#33990]
### Connector Name

source-mongodb-v2

### Connector Version

1.2.1

### What step the error happened?

During the sync

### Relevant information

I configured a connection from Mongodb to Postgres. The source test and destination test individually got OK and also data has been moved! But sync failed (it shows that was failed!)
I guess the problem is setting replica set on my self hosted Mongodb instance.
finally problem solved with granting 'readAnyDatabase' on admin db instead of granting 'read' to target db (based on docs https://docs.airbyte.com/integrations/sources/mongodb-v2#self-hosted)

### Relevant log output

```shell
2024-01-07 05:49:27 source > 2024-01-07 05:49:27 ERROR i.a.c.i.b.AirbyteExceptionHandler(uncaughtException):64 - Something went wrong in the connector. See the logs for more details.
2024-01-07 05:49:27 source > com.mongodb.MongoCommandException: Command failed with error 13 (Unauthorized): 'not authorized on admin to execute command { aggregate: 1, pipeline: [ { $changeStream: { allChangesForCluster: true } } ], cursor: {}, $db: "admin", $clusterTime: { clusterTime: Timestamp(1704606567, 1), signature: { hash: BinData(0, 2AA73EA78E2A87896675A19EACE2A6910E5B75FB), keyId: 7267061639512326145 } }, lsid: { id: UUID("a9b35be5-1f1d-46c8-9314-09b7fba1e320") }, $readPreference: { mode: "secondaryPreferred" } }' on server [remote-host]:7170. The full response is {"ok": 0.0, "errmsg": "not authorized on admin to execute command { aggregate: 1, pipeline: [ { $changeStream: { allChangesForCluster: true } } ], cursor: {}, $db: \"admin\", $clusterTime: { clusterTime: Timestamp(1704606567, 1), signature: { hash: BinData(0, 2AA73EA78E2A87896675A19EACE2A6910E5B75FB), keyId: 7267061639512326145 } }, lsid: { id: UUID(\"a9b35be5-1f1d-46c8-9314-09b7fba1e320\") }, $readPreference: { mode: \"secondaryPreferred\" } }", "code": 13, "codeName": "Unauthorized", "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1704606567, "i": 1}}, "signature": {"hash": {"$binary": {"base64": "Kqc+p44qh4lmdaGerOKmkQ5bdfs=", "subType": "00"}}, "keyId": 7267061639512326145}}, "operationTime": {"$timestamp": {"t": 1704606567, "i": 1}}}
2024-01-07 05:49:27 source >         at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:205) ~[mongodb-driver-core-4.10.2.jar:?]
2024-01-07 05:49:27 source >         at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:448) ~[mongodb-driver-core-4.10.2.jar:?]
2024-01-07 05:49:27 source >         at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:370) ~[mongodb-driver-core-4.10.2.jar:?]
2024-01-07 05:49:27 source >         at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:114) ~[mongodb-driver-core-4.10.2.jar:?]
2024-01-07 05:49:27 source >         at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:719) ~[mongodb-driver-core-4.10.2.jar:?]
2024-01-07 05:49:27 source >         at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:76) ~[mongodb-driver-core-4.10.2.jar:?]
2024-01-07 05:49:27 source >         at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:203) ~[mongodb-driver-core-4.10.2.jar:?]
2024-01-07 05:49:27 source >         at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:115) ~[mongodb-driver-core-4.10.2.jar:?]
2024-01-07 05:49:27 source >         at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:83) ~[mongodb-driver-core-4.10.2.jar:?]
2024-01-07 05:49:27 source >         at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:74) ~[mongodb-driver-core-4.10.2.jar:?]
2024-01-07 05:49:27 source >         at com.mongodb.internal.connection.DefaultServer$OperationCountTrackingConnection.command(DefaultServer.java:287) ~[mongodb-driver-core-4.10.2.jar:?]
2024-01-07 05:49:27 source >         at com.mongodb.internal.operation.CommandOperationHelper.createReadCommandAndExecute(CommandOperationHelper.java:245) ~[mongodb-driver-core-4.10.2.jar:?]
2024-01-07 05:49:27 source >         at com.mongodb.internal.operation.CommandOperationHelper.lambda$executeRetryableRead$6(CommandOperationHelper.java:227) ~[mongodb-driver-core-4.10.2.jar:?]
2024-01-07 05:49:27 source >         at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$0(OperationHelper.java:345) ~[mongodb-driver-core-4.10.2.jar:?]
2024-01-07 05:49:27 source >         at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:370) ~[mongodb-driver-core-4.10.2.jar:?]
2024-01-07 05:49:27 source >         at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$1(OperationHelper.java:344) ~[mongodb-driver-core-4.10.2.jar:?]
2024-01-07 05:49:27 source >         at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:370) ~[mongodb-driver-core-4.10.2.jar:?]
2024-01-07 05:49:27 source >         at com.mongodb.internal.operation.OperationHelper.withSourceAndConnection(OperationHelper.java:343) ~[mongodb-driver-core-4.10.2.jar:?]
2024-01-07 05:49:27 source >         at com.mongodb.internal.operation.CommandOperationHelper.lambda$executeRetryableRead$7(CommandOperationHelper.java:225) ~[mongodb-driver-core-4.10.2.jar:?]
2024-01-07 05:49:27 source >         at com.mongodb.internal.operation.CommandOperationHelper.lambda$decorateReadWithRetries$3(CommandOperationHelper.java:192) ~[mongodb-driver-core-4.10.2.jar:?]
2024-01-07 05:49:27 source >         at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:67) ~[mongodb-driver-core-4.10.2.jar:?]
2024-01-07 05:49:27 source >         at com.mongodb.internal.operation.CommandOperationHelper.executeRetryableRead(CommandOperationHelper.java:230) ~[mongodb-driver-core-4.10.2.jar:?]
2024-01-07 05:49:27 source >         at com.mongodb.internal.operation.CommandOperationHelper.executeRetryableRead(CommandOperationHelper.java:212) ~[mongodb-driver-core-4.10.2.jar:?]
2024-01-07 05:49:27 source >         at com.mongodb.internal.operation.AggregateOperationImpl.execute(AggregateOperationImpl.java:191) ~[mongodb-driver-core-4.10.2.jar:?]
2024-01-07 05:49:27 source >         at com.mongodb.internal.operation.ChangeStreamOperation.lambda$execute$0(ChangeStreamOperation.java:187) ~[mongodb-driver-core-4.10.2.jar:?]
2024-01-07 05:49:27 source >         at com.mongodb.internal.operation.OperationHelper.withReadConnectionSource(OperationHelper.java:308) ~[mongodb-driver-core-4.10.2.jar:?]
2024-01-07 05:49:27 source >         at com.mongodb.internal.operation.ChangeStreamOperation.execute(ChangeStreamOperation.java:185) ~[mongodb-driver-core-4.10.2.jar:?]
2024-01-07 05:49:27 source >         at com.mongodb.internal.operation.ChangeStreamOperation.execute(ChangeStreamOperation.java:55) ~[mongodb-driver-core-4.10.2.jar:?]
2024-01-07 05:49:27 source >         at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:153) ~[mongodb-driver-sync-4.10.2.jar:?]
2024-01-07 05:49:27 source >         at com.mongodb.client.internal.ChangeStreamIterableImpl.execute(ChangeStreamIterableImpl.java:212) ~[mongodb-driver-sync-4.10.2.jar:?]
2024-01-07 05:49:27 source >         at com.mongodb.client.internal.ChangeStreamIterableImpl.cursor(ChangeStreamIterableImpl.java:187) ~[mongodb-driver-sync-4.10.2.jar:?]
2024-01-07 05:49:27 source >         at io.airbyte.cdk.integrations.debezium.internals.mongodb.MongoDbResumeTokenHelper.getMostRecentResumeToken(MongoDbResumeTokenHelper.java:34) ~[airbyte-cdk-db-sources-0.7.9.jar:?]
2024-01-07 05:49:27 source >         at io.airbyte.integrations.source.mongodb.cdc.MongoDbCdcInitializer.createCdcIterators(MongoDbCdcInitializer.java:95) ~[io.airbyte.airbyte-integrations.connectors-source-mongodb-v2-0.50.38.jar:?]
2024-01-07 05:49:27 source >         at io.airbyte.integrations.source.mongodb.MongoDbSource.read(MongoDbSource.java:135) ~[io.airbyte.airbyte-integrations.connectors-source-mongodb-v2-0.50.38.jar:?]
2024-01-07 05:49:27 source >         at io.airbyte.cdk.integrations.base.IntegrationRunner.readSerial(IntegrationRunner.java:275) ~[airbyte-cdk-core-0.7.9.jar:?]
2024-01-07 05:49:27 source >         at io.airbyte.cdk.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:173) ~[airbyte-cdk-core-0.7.9.jar:?]
2024-01-07 05:49:27 source >         at io.airbyte.cdk.integrations.base.IntegrationRunner.run(IntegrationRunner.java:125) ~[airbyte-cdk-core-0.7.9.jar:?]
2024-01-07 05:49:27 source >         at io.airbyte.integrations.source.mongodb.MongoDbSource.main(MongoDbSource.java:45) ~[io.airbyte.airbyte-integrations.connectors-source-mongodb-v2-0.50.38.jar:?]
```

### Contribute

- [X] Yes, I want to contribute
```[tasklist]
### Tasks
- [ ] edit doc about mongodb source
```

**Comment by evantahler** [comment]
Closing as issue was solved by OP
