### ISSUE TITLE
source-gcs: The signature token in file URL will expires if sync running longer than 3600 seconds.

### ISSUE THREAD

**Issue by kggx** [airbytehq/airbyte#34004]
### Connector Name

source-gcs

### Connector Version

0.3.3

### What step the error happened?

During the sync

### Relevant information

By default access tokens of GCS are good for 3600 seconds. If the a stream is running for more than 3600 seconds it will fail the remaining files as the signed URL is generated at "get_matching_files". In addition this will not fail the sync.

**Proposed fixes:**
- Check for "400 Status Code" and refresh signed URL
- Alternative: Move signature token generation to "open_file" function.

### Relevant log output

```shell
2024-01-08 16:09:54 source > We don't have access to https://storage.googleapis.com/path/to/file.csv?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=service-account%40gcp-project.iam.gserviceaccount.com%2F20240108%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20240108T150831Z&X-Goog-Expires=3600&X-Goog-SignedHeaders=host&X-Goog-Signature=TOKEN. The file appears to have become unreachable during sync.Check whether key https://storage.googleapis.com/path/to/file.csv?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=service-account%40gcp-project.iam.gserviceaccount.com%2F20240108%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20240108T150831Z&X-Goog-Expires=3600&X-Goog-SignedHeaders=host&X-Goog-Signature=TOKEN exists in `fmg-logistik-dwh-landing-dev` bucket and/or has proper ACL permissions
2024-01-08 16:09:54 source > 400 Client Error: Bad Request for url: https://storage.googleapis.com/path/to/file.csv?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=service-account%40gcp-project.iam.gserviceaccount.com%2F20240108%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20240108T150831Z&X-Goog-Expires=3600&X-Goog-SignedHeaders=host&X-Goog-Signature=TOKEN
Traceback (most recent call last):
  File "/airbyte/integration_code/source_gcs/stream_reader.py", line 104, in open_file
    result = smart_open.open(file.uri, mode=mode.value, encoding=encoding)
  File "/usr/local/lib/python3.9/site-packages/smart_open/smart_open_lib.py", line 235, in open
    binary = _open_binary_stream(uri, binary_mode, transport_params)
  File "/usr/local/lib/python3.9/site-packages/smart_open/smart_open_lib.py", line 398, in _open_binary_stream
    fobj = submodule.open_uri(uri, mode, transport_params)
  File "/usr/local/lib/python3.9/site-packages/smart_open/http.py", line 49, in open_uri
    return open(uri, mode, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/smart_open/http.py", line 81, in open
    fobj = SeekableBufferedInputBase(
  File "/usr/local/lib/python3.9/site-packages/smart_open/http.py", line 240, in __init__
    self.response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://storage.googleapis.com/path/to/file.csv?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=service-account%40gcp-project.iam.gserviceaccount.com%2F20240108%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20240108T150831Z&X-Goog-Expires=3600&X-Goog-SignedHeaders=host&X-Goog-Signature=TOKEN
2024-01-08 16:09:54 source > Error parsing record. This could be due to a mismatch between the config's file type and the actual file type, or because the file or record is not parseable. stream=adhoc_hcm_lohnarten_test file=https://storage.googleapis.com/path/to/file.csv?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=service-account%40gcp-project.iam.gserviceaccount.com%2F20240108%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20240108T150831Z&X-Goog-Expires=3600&X-Goog-SignedHeaders=host&X-Goog-Signature=TOKEN line_no=0 n_skipped=0
Stack Trace: Traceback (most recent call last):
  File "/airbyte/integration_code/source_gcs/stream_reader.py", line 109, in open_file
    yield result
UnboundLocalError: local variable 'result' referenced before assignment
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/file_based/stream/default_file_based_stream.py", line 90, in read_records_from_slice
    for record in parser.parse_records(self.config, file, self.stream_reader, self.logger, schema):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/file_based/file_types/csv_parser.py", line 183, in parse_records
    for row in data_generator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/file_based/file_types/csv_parser.py", line 51, in read_data
    with stream_reader.open_file(file, file_read_mode, config_format.encoding, logger) as fp:
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/airbyte/integration_code/source_gcs/stream_reader.py", line 111, in open_file
    result.close()
UnboundLocalError: local variable 'result' referenced before assignment
```

### Contribute

- [X] Yes, I want to contribute

**Comment by mehulkasliwal** [comment]
I'm also facing the same issue. This is a big blocker for us to integrate with GCS sources. Is there any workaround for this? Can we please prioritize the fix?

**Comment by mehulkasliwal** [comment]
https://github.com/airbytehq/airbyte/blob/34a9ff195f32031f970f70da622c0d6f1f17430c/airbyte-integrations/connectors/source-gcs/source_gcs/stream_reader.py#L81

`uri = blob.generate_signed_url(expiration=timedelta(hours=1), version="v4")`

This seems to be the root-cause of the issue

**Comment by marcosmarxm** [comment]
@mehulkasliwal, could you propose a change to this parameter? Perhaps make it configurable?

**Comment by szemek** [comment]
It is possible to do something different without signed urls

```python
uri = f"gs://{bucket.name}/{blob.name}"
```
then in smart.open

```python
smart_open.open(file.uri, mode=mode.value, encoding=encoding, transport_params={"client": self.gcs_client})
```

In that way list of uris won't expire and smart_open handles it.

The biggest drawback is that it requires migrating state.
