### ISSUE TITLE
Worker won't start due to missing property that doesn't exist in application.yaml

### ISSUE THREAD

**Issue by henryjarend** [airbytehq/airbyte#34060]
### Helm Chart Version

0.50.21

### What step the error happened?

On deploy

### Revelant information

I'm trying to use S3 for logging and I keep running into an issue when trying to deploy the airbyte helm chart. It seems like the worker is trying to find an endpoint URI even though everything is set to S3 as far as I can tell. 
I was able to get all of the services started when I was using minio but as soon as I swapped to S3 I started getting the error. If any other info is missing I'll be happy to provide it
The values that I changed are as follows
```
global:
  state:
    storage:
      type: "S3"
  logs:
    storage:
      type: "S3"
    s3:
      enabled: true
      bucket: <bucket-name-hidden>
      bucketRegion: us-east-1
serviceAccount:
  create: true
  annotations:
    "eks.amazonaws.com/role-arn": "<role-arn>"
  name: *service-account-name
minio:
  enabled: false
```

### Relevant log output

```shell
INFO StatusConsoleListener Loading mask data from '/seed/specs_secrets_mask.yaml

    ___    _      __          __
   /   |  (_)____/ /_  __  __/ /____
  / /| | / / ___/ __ \/ / / / __/ _ \
 / ___ |/ / /  / /_/ / /_/ / /_/  __/
/_/  |_/_/_/  /_.___/\__, /\__/\___/
                    /____/
        : airbyte-workers :

  Micronaut (v3.10.1)

2024-01-09 18:26:09 INFO i.m.c.e.DefaultEnvironment(<init>):167 - Established active environments: [k8s, cloud, ec2, control-plane]
2024-01-09 18:26:10 INFO i.m.l.PropertiesLoggingLevelsConfigurer(configureLogLevelForPrefix):111 - Setting log level 'DEBUG' for logger: 'io.airbyte.bootloader'
2024-01-09 18:26:10 INFO i.a.f.ConfigFileClient(<init>):105 - path /flags does not exist, will return default flag values
2024-01-09 18:26:11 ERROR i.m.r.Micronaut(handleStartupException):338 - Error starting Micronaut server: Error instantiating bean of type  [io.airbyte.config.helpers.LogConfigs]

Message: Missing property airbyte.cloud.storage.logs.s3.endpoint
Path Taken: new ApplicationInitializer() --> ApplicationInitializer.checkConnectionActivities --> List.checkConnectionActivities([CheckConnectionActivity checkConnectionActivity]) --> new CheckConnectionActivityImpl(WorkerConfigsProvider workerConfigsProvider,ProcessFactory processFactory,SecretsRepositoryReader secretsRepositoryReader,Path workspaceRoot,WorkerEnvironment workerEnvironment,[LogConfigs logConfigs],AirbyteApiClient airbyteApiClient,String airbyteVersion,AirbyteMessageSerDeProvider serDeProvider,AirbyteProtocolVersionedMigratorFactory migratorFactory,FeatureFlags featureFlags,FeatureFlagClient featureFlagClient,GsonPksExtractor gsonPksExtractor,WorkloadApi workloadApi,WorkloadIdGenerator workloadIdGenerator,JobOutputDocStore jobOutputDocStore) --> new LogConfigs([Optional storageConfigs])
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.airbyte.config.helpers.LogConfigs]

Message: Missing property airbyte.cloud.storage.logs.s3.endpoint
Path Taken: new ApplicationInitializer() --> ApplicationInitializer.checkConnectionActivities --> List.checkConnectionActivities([CheckConnectionActivity checkConnectionActivity]) --> new CheckConnectionActivityImpl(WorkerConfigsProvider workerConfigsProvider,ProcessFactory processFactory,SecretsRepositoryReader secretsRepositoryReader,Path workspaceRoot,WorkerEnvironment workerEnvironment,[LogConfigs logConfigs],AirbyteApiClient airbyteApiClient,String airbyteVersion,AirbyteMessageSerDeProvider serDeProvider,AirbyteProtocolVersionedMigratorFactory migratorFactory,FeatureFlags featureFlags,FeatureFlagClient featureFlagClient,GsonPksExtractor gsonPksExtractor,WorkloadApi workloadApi,WorkloadIdGenerator workloadIdGenerator,JobOutputDocStore jobOutputDocStore) --> new LogConfigs([Optional storageConfigs])
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2367) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1680) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.AbstractBeanResolutionContext.findBean(AbstractBeanResolutionContext.java:84) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.AbstractInitializableBeanDefinition.resolveOptionalBean(AbstractInitializableBeanDefinition.java:2178) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.AbstractInitializableBeanDefinition.findBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1581) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.airbyte.config.helpers.$LogConfigs$Definition.build(Unknown Source) ~[io.airbyte.airbyte-config-config-models-0.50.41.jar:?]
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.airbyte.workers.temporal.check.connection.$CheckConnectionActivityImpl$Definition.build(Unknown Source) ~[io.airbyte-airbyte-workers-0.50.41.jar:?]
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1297) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.airbyte.workers.config.$ActivityBeanFactory$CheckConnectionActivities0$Definition.build(Unknown Source) ~[io.airbyte-airbyte-workers-0.50.41.jar:?]
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1680) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.AbstractBeanResolutionContext.findBean(AbstractBeanResolutionContext.java:84) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.AbstractInitializableBeanDefinition.resolveOptionalBean(AbstractInitializableBeanDefinition.java:2178) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.AbstractInitializableBeanDefinition.findBeanForField(AbstractInitializableBeanDefinition.java:1843) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.airbyte.workers.$ApplicationInitializer$Definition.injectBean(Unknown Source) ~[io.airbyte-airbyte-workers-0.50.41.jar:?]
        at io.airbyte.workers.$ApplicationInitializer$Definition.build(Unknown Source) ~[io.airbyte-airbyte-workers-0.50.41.jar:?]
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2853) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:3511) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistrations(DefaultBeanContext.java:3457) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:3427) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:1381) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:903) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:893) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.context.event.ApplicationEventPublisherFactory$2.lambda$$0(ApplicationEventPublisherFactory.java:217) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.core.util.SupplierUtil$2.initialize(SupplierUtil.java:77) ~[micronaut-core-3.10.1.jar:3.10.1]
        at io.micronaut.core.util.SupplierUtil$2.get(SupplierUtil.java:72) ~[micronaut-core-3.10.1.jar:3.10.1]
        at io.micronaut.context.event.ApplicationEventPublisherFactory$2.publishEvent(ApplicationEventPublisherFactory.java:229) ~[micronaut-inject-3.10.1.jar:3.10.1]
        at io.micronaut.http.server.netty.NettyHttpServer.lambda$fireStartupEvents$15(NettyHttpServer.java:600) ~[micronaut-http-server-netty-3.10.1.jar:3.10.1]
        at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at io.micronaut.http.server.netty.NettyHttpServer.fireStartupEvents(NettyHttpServer.java:594) ~[micronaut-http-server-netty-3.10.1.jar:3.10.1]
        at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:298) ~[micronaut-http-server-netty-3.10.1.jar:3.10.1]
        at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:104) ~[micronaut-http-server-netty-3.10.1.jar:3.10.1]
        at io.micronaut.runtime.Micronaut.lambda$start$2(Micronaut.java:81) ~[micronaut-context-3.10.1.jar:3.10.1]
        at java.base/java.util.Optional.ifPresent(Optional.java:178) [?:?]
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:79) [micronaut-context-3.10.1.jar:3.10.1]        at io.micronaut.runtime.Micronaut.run(Micronaut.java:323) [micronaut-context-3.10.1.jar:3.10.1]
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:309) [micronaut-context-3.10.1.jar:3.10.1]
        at io.airbyte.workers.Application.main(Application.java:15) [io.airbyte-airbyte-workers-0.50.41.jar:?]
Caused by: java.lang.IllegalArgumentException: Missing property airbyte.cloud.storage.logs.s3.endpoint
        at io.airbyte.workers.config.DocumentStoreConfigFactory$getProperty$1.get(DocumentStoreFactory.kt:97) ~[io.airbyte-airbyte-commons-worker-0.50.41.jar:?]
        at io.airbyte.workers.config.DocumentStoreConfigFactory$getProperty$1.get(DocumentStoreFactory.kt:97) ~[io.airbyte-airbyte-commons-worker-0.50.41.jar:?]
        at java.base/java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at io.airbyte.workers.config.DocumentStoreConfigFactory.getProperty(DocumentStoreFactory.kt:97) ~[io.airbyte-airbyte-commons-worker-0.50.41.jar:?]
        at io.airbyte.workers.config.DocumentStoreConfigFactory.get(DocumentStoreFactory.kt:90) ~[io.airbyte-airbyte-commons-worker-0.50.41.jar:?]
        at io.airbyte.workers.config.CloudStorageBeanFactory.logStorageConfigs(CloudStorageBeanFactory.java:25) ~[io.airbyte-airbyte-workers-0.50.41.jar:?]
        at io.airbyte.workers.config.$CloudStorageBeanFactory$LogStorageConfigs0$Definition.build(Unknown Source) ~[io.airbyte-airbyte-workers-0.50.41.jar:?]
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.10.1.jar:3.10.1]
        ... 81 more
```

**Comment by colesnodgrass** [comment]
This should be fixed in `v0.50.43`
