### ISSUE TITLE
[worker] High CPU consumption when idle

### ISSUE THREAD

**Issue by sukolenvo** [airbytehq/airbyte#34081]
### Platform Version

0.50.30, 0.50.33

### What step the error happened?

During the Sync

### Use-case and problem
We use MSSQL CDC source and various destinations (Postgres, custom). Its important for us to get changes synced quickly, hence we setup jobs to run frequently. Thats where we noticed a problem - where there was no new messages aribyte-worker container would start consuming 2 cores CPU per connection. When we have multiple such busy no-op connections it affects web server responsiveness and performance of other sync jobs that are actually have data to copy.
### What we tried
* We did several thread dumps to identify hot points, high CPU was noticed in `BufferedReplicationWorker.writeToDestination()` and `BufferedReplicationWorker.processMessage()` which is unexpected given there is no messages to process or write:
  ```
  "pool-38154-thread-5" #79218 [175498] prio=5 os_prio=0 cpu=3569.94ms elapsed=19.40s tid=0x00007f2dec2021d0 nid=175498 runnable  [0x00007f2dbf89a000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.ThreadLocal$ThreadLocalMap.cleanSomeSlots(java.base@19.0.2/ThreadLocal.java:748)
	at java.lang.ThreadLocal$ThreadLocalMap.set(java.base@19.0.2/ThreadLocal.java:572)
	at java.lang.ThreadLocal.set(java.base@19.0.2/ThreadLocal.java:269)
	at java.lang.ThreadLocal.set(java.base@19.0.2/ThreadLocal.java:255)
	at java.util.concurrent.locks.ReentrantReadWriteLock$Sync.tryAcquireShared(java.base@19.0.2/ReentrantReadWriteLock.java:489)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(java.base@19.0.2/AbstractQueuedSynchronizer.java:1026)
	at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(java.base@19.0.2/ReentrantReadWriteLock.java:738)
	at io.airbyte.commons.concurrency.BoundedConcurrentLinkedQueue.isClosed(BoundedConcurrentLinkedQueue.java:118)
	at io.airbyte.workers.general.BufferedReplicationWorker.processMessage(BufferedReplicationWorker.java:409)
	at io.airbyte.workers.general.BufferedReplicationWorker$$Lambda$1199/0x0000000801d80880.run(Unknown Source)
	at io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsync$3(BufferedReplicationWorker.java:253)
	at io.airbyte.workers.general.BufferedReplicationWorker$$Lambda$1184/0x0000000801d7d948.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(java.base@19.0.2/CompletableFuture.java:1804)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@19.0.2/ThreadPoolExecutor.java:1144)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@19.0.2/ThreadPoolExecutor.java:642)
	at java.lang.Thread.run(java.base@19.0.2/Thread.java:1589)

  "pool-38154-thread-6" #79220 [175499] prio=5 os_prio=0 cpu=3645.18ms elapsed=19.40s tid=0x00007f2dec201bf0 nid=175499 runnable  [0x00007f2dbd476000]
     java.lang.Thread.State: RUNNABLE
	  at io.airbyte.commons.concurrency.BoundedConcurrentLinkedQueue.isDone(BoundedConcurrentLinkedQueue.java:96)
	  at io.airbyte.workers.general.BufferedReplicationWorker.writeToDestination(BufferedReplicationWorker.java:450)
	  at io.airbyte.workers.general.BufferedReplicationWorker$$Lambda$1200/0x0000000801d80a90.run(Unknown Source)
	  at io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsync$3(BufferedReplicationWorker.java:253)
	  at io.airbyte.workers.general.BufferedReplicationWorker$$Lambda$1184/0x0000000801d7d948.run(Unknown Source)
	  at java.util.concurrent.CompletableFuture$AsyncRun.run(java.base@19.0.2/CompletableFuture.java:1804)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@19.0.2/ThreadPoolExecutor.java:1144)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@19.0.2/ThreadPoolExecutor.java:642)
	  at java.lang.Thread.run(java.base@19.0.2/Thread.java:1589)
  ```
 * Looking in source code I noticed pattern of busy loop in both places. Eg https://github.com/airbytehq/airbyte-platform/blob/main/airbyte-commons-worker/src/main/java/io/airbyte/workers/general/BufferedReplicationWorker.java#L390 (modified for readability):
    ```java
          while (!messagesForDestinationQueue.isDone() && isReadFromDestRunning) {
            final AirbyteMessage message;
            message = messagesForDestinationQueue.poll();
            if (message == null) {
              continue;
            }
           // process message
         }
    ```
    Code is checking queue without delays again and  again taking all cpu it gets.
  * We've build and tested airbite/worker:dev image with modified BoundedConcurrentLinkedQueue.poll() method (pseudocode for readability purposes):
  ```patch
  public T poll() {
  - final T e = queue.poll();
  + final T e = queue.poll(1, TimeUnit.SECONDS);
    if (e != null) {
      size.decrementAndGet();
    }
    return e;
  }
  ```
  As a result we noticed dramatic drop of CPU consumption (near 0) and data was still synced without delays.
### Questions
* Given you run Airbyte Cloud you must have experience same problem - sync jobs at the end of their work consuming a lot of CPU, how you managed to isolate this so it don't affect other sync jobs and other clients? Or resource over provisioning is need?
* Is it possible to optimise this wait period of idle connections? I am not well familiar with project and all different connectors, so can't tell what would be a good solution (probably not our quick fix), but there should be a solution for this while maintaining high throughput of BoundedConcurrentLinkedQueue.

### Relevant log output

```shell
300s of high CPU noticed here:

2024-01-10 02:10:05 source > INFO i.a.i.d.i.DebeziumRecordIterator(requestClose):208 No records were returned by Debezium in the timeout seconds 300, closing the engine and iterator
2024-01-10 02:10:05 source > INFO i.d.e.EmbeddedEngine(stop):1146 Stopping the embedded engine
2024-01-10 02:10:05 source > INFO i.d.e.EmbeddedEngine(stop):1153 Waiting for PT5M for connector to stop
2024-01-10 02:10:05 source > INFO i.d.e.EmbeddedEngine(run):944 Stopping the task and engine
2024-01-10 02:10:05 source > INFO i.d.c.c.BaseSourceTask(stop):278 Stopping down connector
2024-01-10 02:10:05 source > INFO i.d.c.s.SqlServerChangeEventSourceCoordinator(executeChangeEventSources):120 Finished streaming
2024-01-10 02:10:05 source > INFO i.d.p.ChangeEventSourceCoordinator(streamingConnected):240 Connected metrics set to 'false'
2024-01-10 02:10:05 source > INFO i.d.j.JdbcConnection(lambda$doClose$4):947 Connection gracefully closed
2024-01-10 02:10:05 source > INFO i.d.j.JdbcConnection(lambda$doClose$4):947 Connection gracefully closed
2024-01-10 02:10:05 source > INFO o.a.k.c.s.FileOffsetBackingStore(stop):66 Stopped FileOffsetBackingStore
2024-01-10 02:10:05 source > INFO i.a.i.d.i.DebeziumRecordPublisher(lambda$start$1):87 Debezium engine shutdown.
2024-01-10 02:10:05 source > INFO i.a.i.d.i.DebeziumRecordPublisher(lambda$start$1):88 Connector 'io.debezium.connector.sqlserver.SqlServerConnector' completed normally.
```

**Comment by gosusnp** [comment]
@sukolenvo, thank you for this detailed issue. Your observations are spot on, this has been under our radar for some time now.
We initially had two implementations with blocking (`LinkedBlockingQueue`) and non-blocking (`ConcurrentLinkedQueue`) operations. From the early testing, the non-blocking one performed better but I believe the dataset was skewed towards very high throughput.

I hope this should be addressed by https://github.com/airbytehq/airbyte/issues/34416.

To your questions
* CPU hasn't been the biggest concern but also we are running on kubernetes. Syncs run on different nodes which limit the noisy neighbor effects.
* Can you define idle connections?

**Comment by sukolenvo** [comment]
Kubernetes makes sense, probably you also have configured container cpu request/limit and once its reached container is just throttled which protects nearby pods. Thank you, I will check in this direction if we can configure more conservative container cpu limits with docker-compose setup.

Sorry for confusing terms, by idle connections I meant worker runs that have completed cdc sync and don't have any new messages in queue to process, but wait up to 5 minutes till debezium engine is stopped and run is completed.
