### ISSUE TITLE
[Helm] Missing property airbyte.cloud.storage.logs.s3.endpoint

### ISSUE THREAD

**Issue by SEAC-Tam** [airbytehq/airbyte#34086]
### Helm Chart Version

0.50.21

### What step the error happened?

Upgrading the Platform or Helm Chart

### Revelant information

Error on worker pods after upgrading from 0.50.20 to 0.50.21

my current values.yaml
```yaml
minio:
  enabled: false
global:
  logs:
    minio:
      enabled: false
    storage:
      type: "S3"
    s3:
      enabled: true
      bucket: "MY_BUCKET"
      bucketRegion: "MY_REGION"
    accessKey:
      existingSecret: "my-aws-secret"
      existingSecretKey: "AWS_ACCESS_KEY_ID"
    secretKey:
      existingSecret: "my-aws-secret"
      existingSecretKey: "AWS_SECRET_ACCESS_KEY"
  state:
    storage:
      type: "S3"
worker:
  extraEnv:
    - name: STATE_STORAGE_S3_BUCKET_NAME
      value: "MY_BUCKET"
    - name: STATE_STORAGE_S3_REGION
      value: "MY_REGION"
```

### Relevant log output

```shell
Message: Missing property airbyte.cloud.storage.logs.s3.endpoint
2024-01-10T09:50:49.527207865Z Path Taken: new ApplicationInitializer() --> ApplicationInitializer.checkConnectionActivities --> List.checkConnectionActivities([CheckConnectionActivity checkConnectionActivity]) --> new CheckConnectionActivityImpl(WorkerConfigsProvider workerConfigsProvider,ProcessFactory processFactory,SecretsRepositoryReader secretsRepositoryReader,Path workspaceRoot,WorkerEnvironment workerEnvironment,[LogConfigs logConfigs],AirbyteApiClient airbyteApiClient,String airbyteVersion,AirbyteMessageSerDeProvider serDeProvider,AirbyteProtocolVersionedMigratorFactory migratorFactory,FeatureFlags featureFlags,FeatureFlagClient featureFlagClient,GsonPksExtractor gsonPksExtractor,WorkloadApi workloadApi,WorkloadIdGenerator workloadIdGenerator,JobOutputDocStore jobOutputDocStore) --> new LogConfigs([Optional storageConfigs])
2024-01-10T09:50:49.527216887Z io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.airbyte.config.helpers.LogConfigs]

Message: Missing property airbyte.cloud.storage.logs.s3.endpoint
Path Taken: new ApplicationInitializer() --> ApplicationInitializer.checkConnectionActivities --> List.checkConnectionActivities([CheckConnectionActivity checkConnectionActivity]) --> new CheckConnectionActivityImpl(WorkerConfigsProvider workerConfigsProvider,ProcessFactory processFactory,SecretsRepositoryReader secretsRepositoryReader,Path workspaceRoot,WorkerEnvironment workerEnvironment,[LogConfigs logConfigs],AirbyteApiClient airbyteApiClient,String airbyteVersion,AirbyteMessageSerDeProvider serDeProvider,AirbyteProtocolVersionedMigratorFactory migratorFactory,FeatureFlags featureFlags,FeatureFlagClient featureFlagClient,GsonPksExtractor gsonPksExtractor,WorkloadApi workloadApi,WorkloadIdGenerator workloadIdGenerator,JobOutputDocStore jobOutputDocStore) --> new LogConfigs([Optional storageConfigs])
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2367) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918) ~[micronaut-inject-3.10.1.jar:3.10.1]
```

**Comment by AronsonDan** [comment]
Just wanted to open that issue as I was trying to upgrade today.
Thanks for that and I wish you guys can find a solution for that :-)

**Comment by SEAC-Tam** [comment]
@AronsonDan
Yesterday, I again attempted to upgrade the chart from version 0.50.20 to 0.50.21 using the latest image tag (0.50.43), and the issue seems to have been resolved.
