### ISSUE TITLE
source-netsuite raise error  "INVALID_HEADER" when sync 

### ISSUE THREAD

**Issue by ojhtyy** [airbytehq/airbyte#34137]
### Connector Name

source-netsuite

### Connector Version

0.1.3

### What step the error happened?

None

### Relevant information

I encountered an error while synchronizing the stream in connection (tried inventoryItem , vendor) when retrieving the source data. ：2024-01-11 01:55:36 source > {"type":"https://www.rfc-editor.org/rfc/rfc9110.html#section-15.5.1","title":"Bad Request","status":400,"o:errorDetails":[{"detail":"Invalid language. REST web services currently only support the default company language, and do not support the language specified in your user preferences. Provide the Accept-Language header with your default company language value 'zh'.","o:errorHeader":"Accept-Language","o:errorCode":"INVALID_HEADER"}]}

Am I misconfiguring something, or is this a bug?

here is source config:
![image](https://github.com/airbytehq/airbyte/assets/28341047/edcce878-f82d-4cd1-8820-79ae7f6d1ca1)

here is full log file:

[default_workspace_job_201_attempt_1_txt.txt](https://github.com/airbytehq/airbyte/files/13896611/default_workspace_job_201_attempt_1_txt.txt)

### Relevant log output

```shell
File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 131, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 122, in run
    for message in generator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 129, in read
    raise e
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 115, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 184, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 294, in _read_full_refresh
    for record_data_or_message in record_data_or_messages:
  File "/airbyte/integration_code/source_netsuite/streams.py", line 202, in read_records
    yield from super().read_records(stream_slice=stream_slice, stream_state=stream_state, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 413, in read_records
    yield from self._read_pages(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 430, in _read_pages
    yield from records_generator_fn(request, response, stream_state, stream_slice)
  File "/airbyte/integration_code/source_netsuite/streams.py", line 246, in parse_response
    yield from self.filter_records_newer_than_state(stream_state, records)
  File "/airbyte/integration_code/source_netsuite/streams.py", line 223, in filter_records_newer_than_state
    yield from records
  File "/airbyte/integration_code/source_netsuite/streams.py", line 168, in parse_response
    yield from self.fetch_record(record, request_kwargs)
  File "/airbyte/integration_code/source_netsuite/streams.py", line 147, in fetch_record
    response = self._send_request(prep_req, request_kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 354, in _send_request
    return backoff_handler(user_backoff_handler)(request, request_kwargs)
  File "/usr/local/lib/python3.9/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 321, in _send
    raise exc
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 318, in _send
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://8192875-sb1.suitetalk.api.netsuite.com/services/rest/record/v1/inventoryitem/54592?expandSubResources=True
2024-01-11 01:55:36 platform > readFromSource: source exception
io.airbyte.workers.internal.exception.SourceException: Source process exited with non-zero exit code 1
        at io.airbyte.workers.general.BufferedReplicationWorker.readFromSource(BufferedReplicationWorker.java:365) ~[io.airbyte-airbyte-commons-worker-0.50.35.jar:?]
        at io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsyncWithHeartbeatCheck$3(BufferedReplicationWorker.java:235) ~[io.airbyte-airbyte-commons-worker-0.50.35.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
2024-01-11 01:55:36 platform > readFromSource: done. (source.isFinished:true, fromSource.isClosed:false)
2024-01-11 01:55:36 platform > processMessage: done. (fromSource.isDone:true, forDest.isClosed:false)
2024-01-11 01:55:36 platform > writeToDestination: done. (forDest.isDone:true, isDestRunning:true)
```

### Contribute

- [X] Yes, I want to contribute

**Comment by ojhtyy** [comment]
This issue has been resolved. We need to change the date format to yyyy-mm-dd in NetSuite.
