### ISSUE TITLE
[platform] Cannot change version of connectors in setting page.

### ISSUE THREAD

**Issue by luna3-k** [airbytehq/airbyte#34198]
### Platform Version

0.50.39

### What step the error happened?

Other

### Revelant information

When I click "change" button to change version of connectors in setting>Sources page, below error message below occurs.

Error upgrading MySQL to version 3.3.2: Internal Server Error: Failed to fetch connector registry entry for airbyte/source-mysql:3.3.2

![image](https://github.com/airbytehq/airbyte/assets/149746337/b5fcf2c1-94f8-477b-870d-d392a3281243)

Source image is in machine.

$ docker images | grep airbyte/source
airbyte/source-mysql                  3.3.2     ab7a42db529d   2 days ago     657MB

### Relevant log output

```shell
airbyte-server                    | 2024-01-12 07:59:38 ERROR i.a.s.a.ApiHelper(execute):49 - Unexpected Exception
airbyte-server                    | java.lang.RuntimeException: Failed to fetch connector registry entry for airbyte/source-mysql:3.3.2
airbyte-server                    |     at io.airbyte.config.specs.RemoteDefinitionsProvider.getConnectorRegistryEntryJson(RemoteDefinitionsProvider.java:223) ~[io.airbyte.airbyte-config-specs-0.50.39.jar:?]
airbyte-server                    |     at io.airbyte.config.specs.RemoteDefinitionsProvider.getSourceDefinitionByVersion(RemoteDefinitionsProvider.java:113) ~[io.airbyte.airbyte-config-specs-0.50.39.jar:?]
airbyte-server                    |     at io.airbyte.config.persistence.ActorDefinitionVersionResolver.fetchRemoteActorDefinitionVersion(ActorDefinitionVersionResolver.java:79) ~[io.airbyte.airbyte-config-config-persistence-0.50.39.jar:?]
airbyte-server                    |     at io.airbyte.config.persistence.ActorDefinitionVersionResolver.resolveVersionForTag(ActorDefinitionVersionResolver.java:59) ~[io.airbyte.airbyte-config-config-persistence-0.50.39.jar:?]
airbyte-server                    |     at io.airbyte.commons.server.handlers.helpers.ActorDefinitionHandlerHelper.defaultDefinitionVersionFromUpdate(ActorDefinitionHandlerHelper.java:106) ~[io.airbyte-airbyte-commons-server-0.50.39.jar:?]
airbyte-server                    |     at io.airbyte.commons.server.handlers.SourceDefinitionsHandler.updateSourceDefinition(SourceDefinitionsHandler.java:285) ~[io.airbyte-airbyte-commons-server-0.50.39.jar:?]
airbyte-server                    |     at io.airbyte.server.apis.SourceDefinitionApiController.lambda$updateSourceDefinition$9(SourceDefinitionApiController.java:172) ~[io.airbyte-airbyte-server-0.50.39.jar:?]
airbyte-server                    |     at io.airbyte.server.apis.ApiHelper.execute(ApiHelper.java:28) ~[io.airbyte-airbyte-server-0.50.39.jar:?]
airbyte-server                    |     at io.airbyte.server.apis.SourceDefinitionApiController.updateSourceDefinition(SourceDefinitionApiController.java:172) ~[io.airbyte-airbyte-server-0.50.39.jar:?]
airbyte-server                    |     at io.airbyte.server.apis.$SourceDefinitionApiController$Definition$Exec.dispatch(Unknown Source) ~[io.airbyte-airbyte-server-0.50.39.jar:?]
airbyte-server                    |     at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371) ~[micronaut-inject-3.10.1.jar:3.10.1]
airbyte-server                    |     at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594) ~[micronaut-inject-3.10.1.jar:3.10.1]
airbyte-server                    |     at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303) ~[micronaut-router-3.10.1.jar:3.10.1]
airbyte-server                    |     at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111) ~[micronaut-router-3.10.1.jar:3.10.1]
airbyte-server                    |     at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103) ~[micronaut-http-3.10.1.jar:3.10.1]
airbyte-server                    |     at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659) ~[micronaut-http-server-3.10.1.jar:3.10.1]
airbyte-server                    |     at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49) ~[reactor-core-3.5.5.jar:3.5.5]
airbyte-server                    |     at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62) ~[reactor-core-3.5.5.jar:3.5.5]
airbyte-server                    |     at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194) ~[reactor-core-3.5.5.jar:3.5.5]
airbyte-server                    |     at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62) ~[micronaut-runtime-3.10.1.jar:3.10.1]
airbyte-server                    |     at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.5.5.jar:3.5.5]
airbyte-server                    |     at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.5.5.jar:3.5.5]
airbyte-server                    |     at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53) ~[micronaut-context-3.10.1.jar:3.10.1]
airbyte-server                    |     at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
airbyte-server                    |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
airbyte-server                    |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
airbyte-server                    |     at java.lang.Thread.run(Thread.java:1583) ~[?:?]
airbyte-server                    | Caused by: java.net.SocketException: Connection reset
airbyte-server                    |     at sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:318) ~[?:?]
airbyte-server                    |     at sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346) ~[?:?]
airbyte-server                    |     at sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796) ~[?:?]
airbyte-server                    |     at java.net.Socket$SocketInputStream.read(Socket.java:1099) ~[?:?]
airbyte-server                    |     at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:489) ~[?:?]
airbyte-server                    |     at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:483) ~[?:?]
airbyte-server                    |     at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160) ~[?:?]
airbyte-server                    |     at sun.security.ssl.SSLTransport.decode(SSLTransport.java:111) ~[?:?]
airbyte-server                    |     at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506) ~[?:?]
airbyte-server                    |     at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421) ~[?:?]
airbyte-server                    |     at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455) ~[?:?]
airbyte-server                    |     at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426) ~[?:?]
airbyte-server                    |     at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at io.airbyte.config.specs.RemoteDefinitionsProvider.getConnectorRegistryEntryJson(RemoteDefinitionsProvider.java:213) ~[io.airbyte.airbyte-config-specs-0.50.39.jar:?]
airbyte-server                    |     ... 26 more
airbyte-server                    | 2024-01-12 07:59:38 ERROR i.a.s.e.UncaughtExceptionHandler(handle):31 - Uncaught exception
airbyte-server                    | java.lang.RuntimeException: Failed to fetch connector registry entry for airbyte/source-mysql:3.3.2
airbyte-server                    |     at io.airbyte.config.specs.RemoteDefinitionsProvider.getConnectorRegistryEntryJson(RemoteDefinitionsProvider.java:223) ~[io.airbyte.airbyte-config-specs-0.50.39.jar:?]
airbyte-server                    |     at io.airbyte.config.specs.RemoteDefinitionsProvider.getSourceDefinitionByVersion(RemoteDefinitionsProvider.java:113) ~[io.airbyte.airbyte-config-specs-0.50.39.jar:?]
airbyte-server                    |     at io.airbyte.config.persistence.ActorDefinitionVersionResolver.fetchRemoteActorDefinitionVersion(ActorDefinitionVersionResolver.java:79) ~[io.airbyte.airbyte-config-config-persistence-0.50.39.jar:?]
airbyte-server                    |     at io.airbyte.config.persistence.ActorDefinitionVersionResolver.resolveVersionForTag(ActorDefinitionVersionResolver.java:59) ~[io.airbyte.airbyte-config-config-persistence-0.50.39.jar:?]
airbyte-server                    |     at io.airbyte.commons.server.handlers.helpers.ActorDefinitionHandlerHelper.defaultDefinitionVersionFromUpdate(ActorDefinitionHandlerHelper.java:106) ~[io.airbyte-airbyte-commons-server-0.50.39.jar:?]
airbyte-server                    |     at io.airbyte.commons.server.handlers.SourceDefinitionsHandler.updateSourceDefinition(SourceDefinitionsHandler.java:285) ~[io.airbyte-airbyte-commons-server-0.50.39.jar:?]
airbyte-server                    |     at io.airbyte.server.apis.SourceDefinitionApiController.lambda$updateSourceDefinition$9(SourceDefinitionApiController.java:172) ~[io.airbyte-airbyte-server-0.50.39.jar:?]
airbyte-server                    |     at io.airbyte.server.apis.ApiHelper.execute(ApiHelper.java:28) ~[io.airbyte-airbyte-server-0.50.39.jar:?]
airbyte-server                    |     at io.airbyte.server.apis.SourceDefinitionApiController.updateSourceDefinition(SourceDefinitionApiController.java:172) ~[io.airbyte-airbyte-server-0.50.39.jar:?]
airbyte-server                    |     at io.airbyte.server.apis.$SourceDefinitionApiController$Definition$Exec.dispatch(Unknown Source) ~[io.airbyte-airbyte-server-0.50.39.jar:?]
airbyte-server                    |     at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371) ~[micronaut-inject-3.10.1.jar:3.10.1]
airbyte-server                    |     at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594) ~[micronaut-inject-3.10.1.jar:3.10.1]
airbyte-server                    |     at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303) ~[micronaut-router-3.10.1.jar:3.10.1]
airbyte-server                    |     at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111) ~[micronaut-router-3.10.1.jar:3.10.1]
airbyte-server                    |     at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103) ~[micronaut-http-3.10.1.jar:3.10.1]
airbyte-server                    |     at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659) ~[micronaut-http-server-3.10.1.jar:3.10.1]
airbyte-server                    |     at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49) ~[reactor-core-3.5.5.jar:3.5.5]
airbyte-server                    |     at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62) ~[reactor-core-3.5.5.jar:3.5.5]
airbyte-server                    |     at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194) ~[reactor-core-3.5.5.jar:3.5.5]
airbyte-server                    |     at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62) ~[micronaut-runtime-3.10.1.jar:3.10.1]
airbyte-server                    |     at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.5.5.jar:3.5.5]
airbyte-server                    |     at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.5.5.jar:3.5.5]
airbyte-server                    |     at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53) ~[micronaut-context-3.10.1.jar:3.10.1]
airbyte-server                    |     at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
airbyte-server                    |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
airbyte-server                    |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
airbyte-server                    |     at java.lang.Thread.run(Thread.java:1583) ~[?:?]
airbyte-server                    | Caused by: java.net.SocketException: Connection reset
airbyte-server                    |     at sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:318) ~[?:?]
airbyte-server                    |     at sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346) ~[?:?]
airbyte-server                    |     at sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796) ~[?:?]
airbyte-server                    |     at java.net.Socket$SocketInputStream.read(Socket.java:1099) ~[?:?]
airbyte-server                    |     at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:489) ~[?:?]
airbyte-server                    |     at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:483) ~[?:?]
airbyte-server                    |     at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160) ~[?:?]
airbyte-server                    |     at sun.security.ssl.SSLTransport.decode(SSLTransport.java:111) ~[?:?]
airbyte-server                    |     at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506) ~[?:?]
airbyte-server                    |     at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421) ~[?:?]
airbyte-server                    |     at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455) ~[?:?]
airbyte-server                    |     at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426) ~[?:?]
airbyte-server                    |     at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154) ~[okhttp-4.12.0.jar:?]
airbyte-server                    |     at io.airbyte.config.specs.RemoteDefinitionsProvider.getConnectorRegistryEntryJson(RemoteDefinitionsProvider.java:213) ~[io.airbyte.airbyte-config-specs-0.50.39.jar:?]
airbyte-server                    |     ... 26 more
airbyte-proxy                     | 172.18.0.1 - airbyte [12/Jan/2024:07:59:38 +0000] "POST /api/v1/source_definitions/update HTTP/1.1" 500 1442 "http://localhost:8000/workspaces/e1a6f47d-a070-4c5e-b219-06098afb813c/settings/source" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
airbyte-webapp                    | 172.18.0.10 - airbyte [12/Jan/2024:07:59:38 +0000] "POST /api/v1/source_definitions/update HTTP/1.0" 500 1442 "http://localhost:8000/workspaces/e1a6f47d-a070-4c5e-b219-06098afb813c/settings/source" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" "172.18.0.1"
```

**Comment by marcosmarxm** [comment]
@luna3-k I was able to upgrade and downgrade an existing connector. Maybe this is a problem with your network? Are you still experiencing the issue?

**Comment by luna3-k** [comment]
Hi, @marcosmarxm 
The response to other api like /api/v1/destination_definitions/list_for_workspace is OK. 
But the response to /api/v1/source_definitions/update is an error. 
Which part of the network should I check?
Thank you

**Comment by marcosmarxm** [comment]
This is solve in latest version. 
Please follow instructions to load custom connectors to the kind cluster [here](https://docs.airbyte.com/operator-guides/using-custom-connectors/#loading-connector-docker-containers-into-kind) and you're going to be able to use the connector in your abctl setup.

See example:
<img width="1183" alt="Image" src="https://github.com/user-attachments/assets/8f08fce0-5649-47b6-97f6-8178ceae543c" />
