### ISSUE TITLE
[source-intercom] Problem with Check Connection step when building connector (but works in current published connector)

### ISSUE THREAD

**Issue by shayan-nathan** [airbytehq/airbyte#34193]
### Connector Name

source-intercom

### Connector Version

0.50.2

### What step the error happened?

Configuring a new connector

### Relevant information

We have cloned and checked out the latest main branch of airbyte, have run airbyte locally, and built the latest version of the Intercom connector with the latest version of the airbyte-ci. When we try to set up a new source with the Intercom credentials and start date, it fails to perform a connection check call. The exact error we see is:

`"Unable to connect to stream tags - 'str' object has no attribute 'value'"`

Digging into the code, the `tags` stream is what is configured in the connector's manifest file for the connection check call. Furthermore, the call stack drills down to the `http_retriever.py` file in the airbyte-cdk. It looks like the exact error occurs on this line https://github.com/airbytehq/airbyte/blob/9a3666058eb5c827932c7057615c7a68d6e080ce/airbyte-cdk/python/airbyte_cdk/sources/declarative/requesters/http_requester.py#L422

Additional Info:
- We have observed the error on multiple machines and multiple versions of airbyte but only within the last week or so

### Relevant log output

```shell
2024-01-11 19:49:59 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(create):186 - Reading messages from protocol version 0.2.0
2024-01-11 19:49:59 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):149 - WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
2024-01-11 19:50:00 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):313 - Encountered an error trying to connect to stream segments. Error: 
 Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/checks/check_stream.py", line 42, in check_connection
    stream_is_available, reason = availability_strategy.check_availability(stream, logger, source)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/availability_strategy.py", line 50, in check_availability
    get_first_record_for_slice(stream, stream_slice)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/utils/stream_helper.py", line 40, in get_first_record_for_slice
    return next(records_for_slice)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py", line 104, in read_records
    yield from self.retriever.read_records(self.get_json_schema(), stream_slice)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 323, in read_records
    for stream_data in self._read_pages(record_generator, self.state, stream_slice):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 287, in _read_pages
    response = self._fetch_next_page(stream_state, stream_slice, next_page_token)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 262, in _fetch_next_page
    return self.requester.send_request(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 449, in send_request
    request = self._create_prepared_request(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 422, in _create_prepared_request
    http_method = str(self.http_method.value)
AttributeError: 'str' object has no attribute 'value'

2024-01-11 19:50:00 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):313 - Check failed
2024-01-11 19:50:00 [32mINFO[m i.a.w.g.DefaultCheckConnectionWorker(run):117 - Check connection job received output: io.airbyte.config.StandardCheckConnectionOutput@7fbc1a15[status=failed,message="Unable to connect to stream tags - 'str' object has no attribute 'value'",additionalProperties={}]
2024-01-11 19:50:00 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2024-01-11 19:50:00 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - ----- END CHECK -----
2024-01-11 19:50:00 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 -
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by shayan-nathan** [comment]
Closing issue. Was resolved internally after fixing discrepancies in Airbyte versions used for connected builds.
