### ISSUE TITLE
Platform should attribute errors properly when suppression occurs

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#34192]
Consider https://github.com/airbytehq/oncall/issues/3682#issuecomment-1864904039

At the top we fault the destination: `io.airbyte.workers.internal.exception.DestinationException`, but all the way at the bottom, the source is to blame: `Suppressed: io.airbyte.workers.exception.WorkerException: Source process exit with code 137. This warning is normal if the job was cancelled.`. <-- It's not normal!

```
java.util.concurrent.ExecutionException: io.airbyte.workers.internal.exception.DestinationException: Destination process message delivery failed
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
        at io.airbyte.workers.general.DefaultReplicationWorker.replicate(DefaultReplicationWorker.java:227) ~[io.airbyte-airbyte-commons-worker-dev-abaf76a2a2.jar:?]
        at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:160) ~[io.airbyte-airbyte-commons-worker-dev-abaf76a2a2.jar:?]
        at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:70) ~[io.airbyte-airbyte-commons-worker-dev-abaf76a2a2.jar:?]
        at io.airbyte.container_orchestrator.orchestrator.ReplicationJobOrchestrator.runJob(ReplicationJobOrchestrator.java:91) ~[io.airbyte-airbyte-container-orchestrator-dev-abaf76a2a2.jar:?]
        at io.airbyte.container_orchestrator.Application.run(Application.java:78) ~[io.airbyte-airbyte-container-orchestrator-dev-abaf76a2a2.jar:?]
        at io.airbyte.container_orchestrator.Application.main(Application.java:38) ~[io.airbyte-airbyte-container-orchestrator-dev-abaf76a2a2.jar:?]
        Suppressed: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.net.SocketException: Broken pipe
                at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
                at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
                at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807) ~[?:?]
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
                at java.lang.Thread.run(Thread.java:1589) ~[?:?]
        Caused by: java.lang.RuntimeException: java.net.SocketException: Broken pipe
                at io.airbyte.workers.general.DefaultReplicationWorker$CloseableWithTimeout.lambda$close$0(DefaultReplicationWorker.java:480) ~[io.airbyte-airbyte-commons-worker-dev-abaf76a2a2.jar:?]
                at io.airbyte.workers.general.DefaultReplicationWorker.lambda$runAsyncWithTimeout$6(DefaultReplicationWorker.java:292) ~[io.airbyte-airbyte-commons-worker-dev-abaf76a2a2.jar:?]
                at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
                ... 3 more
        Caused by: java.net.SocketException: Broken pipe
                at sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:413) ~[?:?]
                at sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:433) ~[?:?]
                at sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:812) ~[?:?]
                at java.net.Socket$SocketOutputStream.write(Socket.java:1120) ~[?:?]
                at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:313) ~[?:?]
                at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:409) ~[?:?]
                at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:414) ~[?:?]
                at sun.nio.cs.StreamEncoder.lockedFlush(StreamEncoder.java:218) ~[?:?]
                at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:205) ~[?:?]
                at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:263) ~[?:?]
                at java.io.BufferedWriter.implFlush(BufferedWriter.java:372) ~[?:?]
                at java.io.BufferedWriter.flush(BufferedWriter.java:359) ~[?:?]
                at io.airbyte.workers.internal.DefaultAirbyteMessageBufferedWriter.flush(DefaultAirbyteMessageBufferedWriter.java:31) ~[io.airbyte-airbyte-commons-worker-dev-abaf76a2a2.jar:?]
                at io.airbyte.workers.internal.DefaultAirbyteDestination.notifyEndOfInputWithNoTimeoutMonitor(DefaultAirbyteDestination.java:133) ~[io.airbyte-airbyte-commons-worker-dev-abaf76a2a2.jar:?]
                at io.airbyte.workers.internal.DefaultAirbyteDestination.notifyEndOfInput(DefaultAirbyteDestination.java:126) ~[io.airbyte-airbyte-commons-worker-dev-abaf76a2a2.jar:?]
                at io.airbyte.workers.internal.DefaultAirbyteDestination.close(DefaultAirbyteDestination.java:146) ~[io.airbyte-airbyte-commons-worker-dev-abaf76a2a2.jar:?]
                at io.airbyte.workers.general.DefaultReplicationWorker$CloseableWithTimeout.lambda$close$0(DefaultReplicationWorker.java:478) ~[io.airbyte-airbyte-commons-worker-dev-abaf76a2a2.jar:?]
                at io.airbyte.workers.general.DefaultReplicationWorker.lambda$runAsyncWithTimeout$6(DefaultReplicationWorker.java:292) ~[io.airbyte-airbyte-commons-worker-dev-abaf76a2a2.jar:?]
                at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
                ... 3 more
        Suppressed: io.airbyte.workers.exception.WorkerException: Source process exit with code 137. This warning is normal if the job was cancelled.
                at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:157) ~[io.airbyte-airbyte-commons-worker-dev-abaf76a2a2.jar:?]
                at io.airbyte.workers.general.DefaultReplicationWorker.replicate(DefaultReplicationWorker.java:179) ~[io.airbyte-airbyte-commons-worker-dev-abaf76a2a2.jar:?]
                at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:160) ~[io.airbyte-airbyte-commons-worker-dev-abaf76a2a2.jar:?]
                at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:70) ~[io.airbyte-airbyte-commons-worker-dev-abaf76a2a2.jar:?]
                at io.airbyte.container_orchestrator.orchestrator.ReplicationJobOrchestrator.runJob(ReplicationJobOrchestrator.java:91) ~[io.airbyte-airbyte-container-orchestrator-dev-abaf76a2a2.jar:?]
                at io.airbyte.container_orchestrator.Application.run(Application.java:78) ~[io.airbyte-airbyte-container-orchestrator-dev-abaf76a2a2.jar:?]
                at io.airbyte.container_orchestrator.Application.main(Application.java:38) ~[io.airbyte-airbyte-container-orchestrator-dev-abaf76a2a2.jar:?]
```

This error was attributed to the destination, but it was actually due to the source exiting first.  Assigning errors properly helps OC triage, and effects connector metrics

**Comment by benmoriceau** [comment]
@evantahler I believe that https://github.com/airbytehq/airbyte-platform-internal/pull/10757 will fix the issue. I don't know how to reproduce this though.
