### ISSUE TITLE
destination-typesense: Configuration check failed -> check() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by jenssogaard** [airbytehq/airbyte#34331]
### Connector Name

destination-typesense

### Connector Version

0.1.2

### What step the error happened?

Configuring a new connector

### Relevant information

Using local docker instance of Airbyte. When adding Typesense as a destination I keep getting an error.

### Relevant log output

```shell
2024-01-17 19:23:56 platform > Using default value for environment variable LAUNCHDARKLY_KEY: ''
2024-01-17 19:23:56 platform > Checking if airbyte/destination-typesense:0.1.2 exists...
2024-01-17 19:23:57 platform > airbyte/destination-typesense:0.1.2 was found locally.
2024-01-17 19:23:57 platform > Creating docker container = destination-typesense-check-7469c96c-b2af-4b10-a9d6-85a1e1cda09c-0-gvopy with resources io.airbyte.config.ResourceRequirements@67d8e5bb[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts null
2024-01-17 19:23:57 platform > Preparing command: docker run --rm --init -i -w /data/7469c96c-b2af-4b10-a9d6-85a1e1cda09c/0 --log-driver none --name destination-typesense-check-7469c96c-b2af-4b10-a9d6-85a1e1cda09c-0-gvopy --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/destination-typesense:0.1.2 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e FIELD_SELECTION_WORKSPACES= -e USE_STREAM_CAPABLE_STATE=true -e WORKER_ENVIRONMENT=DOCKER -e AIRBYTE_ROLE= -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=0 -e OTEL_COLLECTOR_ENDPOINT=http://host.docker.internal:4317 -e FEATURE_FLAG_CLIENT=config -e AIRBYTE_VERSION=0.50.43 -e WORKER_JOB_ID=7469c96c-b2af-4b10-a9d6-85a1e1cda09c airbyte/destination-typesense:0.1.2 check --config source_config.json
2024-01-17 19:23:57 platform > Reading messages from protocol version 0.2.0
2024-01-17 19:23:59 platform > check() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 11, in <module>
    DestinationTypesense().run(sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/destinations/destination.py", line 119, in run
    for message in output_messages:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/destinations/destination.py", line 109, in run_cmd
    yield self._run_check(config=config)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/destinations/destination.py", line 32, in _run_check
    check_result = self.check(logger, config)
TypeError: check() takes 2 positional arguments but 3 were given
2024-01-17 19:23:59 platform > Check connection job subprocess finished with exit code 1
2024-01-17 19:23:59 platform > 
2024-01-17 19:23:59 platform > ----- END CHECK -----
2024-01-17 19:23:59 platform >
```

### Contribute

- [X] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Thanks for contributing the solution @jenssogaard the team will take a look in the next sprint to get your code merged.
