### ISSUE TITLE
[source-facebook-marketing] sync fails with "The source is unresponsive"

### ISSUE THREAD

**Issue by henriquemeloo** [airbytehq/airbyte#34334]
### Connector Name

source-facebook-marketing

### Connector Version

1.2.3

### What step the error happened?

During the sync

### Relevant information

Attempting to sync data from Facebook Marketing to S3, sync fails with message "The source is unresponsive", apparently after a "java.io.IOException: Stream closed", as shown in logs. For this connection, this always happens after about 1h10min.

Airbyte v0.50.34
Running Airbyte in Docker on EC2 r6a.2xlarge
source-facebook-marketing v1.2.3
destination-s3 v0.5.1

### Relevant log output

```shell
2024-01-17 21:11:00 destination > INFO i.a.i.b.a.AdaptiveDestinationRunner$Runner(run):88 Completed destination: io.airbyte.integrations.destination.s3.S3Destination
2024-01-17 21:11:00 INFO i.a.w.g.BufferedReplicationWorker(readFromDestination):490 - readFromDestination: done. (writeToDestFailed:false, dest.isFinished:true)
2024-01-17 21:11:22 source > InsightAsyncJob(id=274424835670669, <AdAccount> {
    "account_id":"**********",
    "id": "act_***"
}, time_range=<Period [2023-05-16 -> 2023-05-16]>, breakdowns=['platform_position', 'publisher_platform']): created AdReportRun
2024-01-17 21:11:23 source > InsightAsyncJob(id=7257477810983484, <AdAccount> {
    "account_id":"**********",
    "id": "act_***"
}, time_range=<Period [2023-05-17 -> 2023-05-17]>, breakdowns=['platform_position', 'publisher_platform']): created AdReportRun
2024-01-17 21:11:23 source > InsightAsyncJob(id=1144766140025167, <AdAccount> {
    "account_id":"**********",
    "id": "act_***"
}, time_range=<Period [2023-05-18 -> 2023-05-18]>, breakdowns=['platform_position', 'publisher_platform']): created AdReportRun
2024-01-17 21:11:24 source > InsightAsyncJob(id=309370605402587, <AdAccount> {
    "account_id":"**********",
    "id": "act_***"
}, time_range=<Period [2023-05-19 -> 2023-05-19]>, breakdowns=['platform_position', 'publisher_platform']): created AdReportRun
2024-01-17 21:11:24 source > InsightAsyncJob(id=3784582775109179, <AdAccount> {
    "account_id":"**********",
    "id": "act_***"
}, time_range=<Period [2023-05-20 -> 2023-05-20]>, breakdowns=['platform_position', 'publisher_platform']): created AdReportRun
2024-01-17 21:11:25 source > InsightAsyncJob(id=1293901691276561, <AdAccount> {
    "account_id":"**********",
    "id": "act_***"
}, time_range=<Period [2023-05-21 -> 2023-05-21]>, breakdowns=['platform_position', 'publisher_platform']): created AdReportRun
2024-01-17 21:11:25 source > InsightAsyncJob(id=886752249592048, <AdAccount> {
    "account_id":"**********",
    "id": "act_***"
}, time_range=<Period [2023-05-22 -> 2023-05-22]>, breakdowns=['platform_position', 'publisher_platform']): created AdReportRun
2024-01-17 21:11:26 source > InsightAsyncJob(id=1037211680671347, <AdAccount> {
    "account_id":"**********",
    "id": "act_***"
}, time_range=<Period [2023-05-23 -> 2023-05-23]>, breakdowns=['platform_position', 'publisher_platform']): created AdReportRun
2024-01-17 21:11:26 source > InsightAsyncJob(id=925162028964818, <AdAccount> {
    "account_id":"**********",
    "id": "act_***"
}, time_range=<Period [2023-05-24 -> 2023-05-24]>, breakdowns=['platform_position', 'publisher_platform']): created AdReportRun
2024-01-17 21:11:26 source > InsightAsyncJob(id=371084352280048, <AdAccount> {
    "account_id":"**********",
    "id": "act_***"
}, time_range=<Period [2023-05-25 -> 2023-05-25]>, breakdowns=['platform_position', 'publisher_platform']): created AdReportRun
2024-01-17 21:11:27 source > InsightAsyncJob(id=1130937851399937, <AdAccount> {
    "account_id":"**********",
    "id": "act_***"
}, time_range=<Period [2023-05-26 -> 2023-05-26]>, breakdowns=['platform_position', 'publisher_platform']): created AdReportRun
2024-01-17 21:11:27 source > InsightAsyncJob(id=1276651349961770, <AdAccount> {
    "account_id":"**********",
    "id": "act_***"
}, time_range=<Period [2023-05-27 -> 2023-05-27]>, breakdowns=['platform_position', 'publisher_platform']): created AdReportRun
2024-01-17 21:11:28 source > InsightAsyncJob(id=695930342704747, <AdAccount> {
    "account_id":"**********",
    "id": "act_***"
}, time_range=<Period [2023-05-28 -> 2023-05-28]>, breakdowns=['platform_position', 'publisher_platform']): created AdReportRun
2024-01-17 21:11:28 source > InsightAsyncJob(id=1035153160893063, <AdAccount> {
    "account_id":"**********",
    "id": "act_***"
}, time_range=<Period [2023-05-29 -> 2023-05-29]>, breakdowns=['platform_position', 'publisher_platform']): created AdReportRun
2024-01-17 21:11:29 source > InsightAsyncJob(id=399958729149786, <AdAccount> {
    "account_id":"**********",
    "id": "act_***"
}, time_range=<Period [2023-05-30 -> 2023-05-30]>, breakdowns=['platform_position', 'publisher_platform']): created AdReportRun
2024-01-17 21:11:29 source > Utilization is too high (85)%, pausing for 2 minutes
2024-01-17 21:12:00 INFO i.a.w.g.BufferedReplicationWorker(readFromSource):379 - readFromSource: exception caught
java.io.UncheckedIOException: java.io.IOException: Stream closed
	at java.io.BufferedReader$1.hasNext(BufferedReader.java:685) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1931) ~[?:?]
	at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:292) ~[?:?]
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206) ~[?:?]
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:169) ~[?:?]
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:298) ~[?:?]
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681) ~[?:?]
	at io.airbyte.workers.internal.DefaultAirbyteSource.isFinished(DefaultAirbyteSource.java:120) ~[io.airbyte-airbyte-commons-worker-0.50.34.jar:?]
	at io.airbyte.workers.general.BufferedReplicationWorker.sourceIsFinished(BufferedReplicationWorker.java:345) ~[io.airbyte-airbyte-commons-worker-0.50.34.jar:?]
	at io.airbyte.workers.general.BufferedReplicationWorker.readFromSource(BufferedReplicationWorker.java:356) ~[io.airbyte-airbyte-commons-worker-0.50.34.jar:?]
	at io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsyncWithHeartbeatCheck$3(BufferedReplicationWorker.java:243) ~[io.airbyte-airbyte-commons-worker-0.50.34.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:172) ~[?:?]
	at java.io.BufferedInputStream.implRead(BufferedInputStream.java:373) ~[?:?]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:367) ~[?:?]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:333) ~[?:?]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:376) ~[?:?]
	at sun.nio.cs.StreamDecoder.lockedRead(StreamDecoder.java:219) ~[?:?]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:173) ~[?:?]
	at java.io.InputStreamReader.read(InputStreamReader.java:189) ~[?:?]
	at java.io.BufferedReader.fill(BufferedReader.java:161) ~[?:?]
	at java.io.BufferedReader.implReadLine(BufferedReader.java:371) ~[?:?]
	at java.io.BufferedReader.readLine(BufferedReader.java:348) ~[?:?]
	at java.io.BufferedReader.readLine(BufferedReader.java:437) ~[?:?]
	at java.io.BufferedReader$1.hasNext(BufferedReader.java:682) ~[?:?]
	... 14 more
2024-01-17 21:12:00 INFO i.a.w.g.BufferedReplicationWorker(readFromSource):382 - readFromSource: done. (source.isFinished:false, fromSource.isClosed:true)
2024-01-17 21:12:00 INFO i.a.w.g.ReplicationWorkerHelper(getReplicationOutput):244 - sync summary: {
  "status" : "failed",
  "startTime" : 1705522260690,
  "endTime" : 1705525920893,
  "totalStats" : {
    "bytesEmitted" : 0,
    "destinationStateMessagesEmitted" : 0,
    "destinationWriteEndTime" : 1705525860815,
    "destinationWriteStartTime" : 1705522260690,
    "meanSecondsBeforeSourceStateMessageEmitted" : 0,
    "maxSecondsBeforeSourceStateMessageEmitted" : 0,
    "meanSecondsBetweenStateMessageEmittedandCommitted" : 0,
    "recordsEmitted" : 0,
    "replicationEndTime" : 1705525920893,
    "replicationStartTime" : 1705522260690,
    "sourceReadEndTime" : 0,
    "sourceReadStartTime" : 1705522260690,
    "sourceStateMessagesEmitted" : 0
  },
  "streamStats" : [ ],
  "performanceMetrics" : {
    "processFromSource" : {
      "elapsedTimeInNanos" : 7621335,
      "executionCount" : 1,
      "avgExecTimeInNanos" : 7621335.0
    },
    "readFromSource" : {
      "elapsedTimeInNanos" : 3660171161676,
      "executionCount" : 2,
      "avgExecTimeInNanos" : 1.830085580838E12
    },
    "processFromDest" : {
      "elapsedTimeInNanos" : 0,
      "executionCount" : 0,
      "avgExecTimeInNanos" : "NaN"
    },
    "writeToDest" : {
      "elapsedTimeInNanos" : 0,
      "executionCount" : 0,
      "avgExecTimeInNanos" : "NaN"
    },
    "readFromDest" : {
      "elapsedTimeInNanos" : 3600093994835,
      "executionCount" : 971,
      "avgExecTimeInNanos" : 3.707614824752832E9
    }
  }
}
2024-01-17 21:12:00 INFO i.a.w.g.ReplicationWorkerHelper(getReplicationOutput):245 - failures: [ {
  "failureOrigin" : "source",
  "failureType" : "heartbeat_timeout",
  "internalMessage" : "Heartbeat has stopped. Heartbeat freshness threshold: 3600 secs Actual heartbeat age: 3600 secs",
  "externalMessage" : "The source is unresponsive",
  "metadata" : {
    "attemptNumber" : 0,
    "jobId" : 52619,
    "connector_command" : "read"
  },
  "stacktrace" : "io.airbyte.workers.internal.HeartbeatTimeoutChaperone$HeartbeatTimeoutException: Heartbeat has stopped. Heartbeat freshness threshold: 3600 secs Actual heartbeat age: 3600 secs\n\tat io.airbyte.workers.internal.HeartbeatTimeoutChaperone.runWithHeartbeatThread(HeartbeatTimeoutChaperone.java:122)\n\tat io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsyncWithHeartbeatCheck$4(BufferedReplicationWorker.java:248)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1589)\n",
  "timestamp" : 1705525860731
} ]
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by henriquemeloo** [comment]
After setting `heartbeat.failSync` to `false`, the sync completes without exceptions, but this does not seem ideal.

**Comment by henriquemeloo** [comment]
> After setting `heartbeat.failSync` to `false`, the sync completes without exceptions, but this does not seem ideal.

This seems not to be a bug, but rather a configuration issue. The source was probably too slow to respond so it was missing the heartbeat threshold.
