### ISSUE TITLE
[source-gcs] support for blobs without prefix

### ISSUE THREAD

**Issue by diogoosorio** [airbytehq/airbyte#34459]
### Connector Name

source-gcs

### Connector Version

0.3.4

### What step the error happened?

Configuring a new connector

### Relevant information

I believe this is quite easy to reproduce:

1. Create a GCS bucket
2. Create a couple of objects with the following keys within the bucket (from the "root" of the bucket) `a/a.csv`, `b/b.csv`
3. Configure the connector with a stream with `*/*.csv` as the glob

<img width="772" alt="image" src="https://github.com/airbytehq/airbyte/assets/1484824/d53cb098-f07a-47eb-8573-dc73db470761">

I'd expect both objects to be picked up on the stream instead, I get an error configuring the connector due to the stream being empty.

Using Google's SDK directly, I get the results I'm expecting:

```py
from google.cloud import storage
next(storage.Client().get_bucket("<my_bucket>").list_blobs(prefix=None, match_glob="*/*.csv"))
```

I'm a bit out of my depth, but I took a look at the connector's source code and I suspect that this cartesian product might be the culprit: https://github.com/airbytehq/airbyte/blob/3b2dbe05ec22d3a88f434db85bfaa36dc7067db6/airbyte-integrations/connectors/source-gcs/source_gcs/stream_reader.py#L73

```py
>>> from source_gcs import SourceGCSStreamReader
>>> from itertools import product
>>> reader.get_prefixes_from_globs(["*/*.csv"])
set()
>>> list(product(set(), ["*/*.csv"]))
[]
```

As the `get_prefixes_from_globs` method returns an empty set, I suspect that the for loop immediately below is being skipped. In my head, in this situation defaulting the prefix to `None` would be a sensible option.

I can try to confirm what I said above (and eventually open a PR to patch it), but I'd appreciate confirmation that the behavior I describe is desirable (i.e. there isn't a strong reason for a prefix to be necessary).

### Relevant log output

```shell
2024-01-23 22:06:31 platform > Docker volume job log path: /tmp/workspace/92bfe205-21e2-41c4-b9d2-b09577f4f202/0/logs.log
2024-01-23 22:06:31 platform > Executing worker wrapper. Airbyte version: 0.50.44
2024-01-23 22:06:31 platform > Attempt 0 to save workflow id for cancellation
2024-01-23 22:06:31 platform > Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2024-01-23 22:06:31 platform > Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2024-01-23 22:06:31 platform > Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2024-01-23 22:06:31 platform > 
2024-01-23 22:06:31 platform > Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2024-01-23 22:06:31 platform > ----- START CHECK -----
2024-01-23 22:06:31 platform > Using default value for environment variable LAUNCHDARKLY_KEY: ''
2024-01-23 22:06:31 platform > 
2024-01-23 22:06:31 platform > Checking if airbyte/source-gcs:0.3.4 exists...
2024-01-23 22:06:31 platform > airbyte/source-gcs:0.3.4 was found locally.
2024-01-23 22:06:31 platform > Creating docker container = source-gcs-check-92bfe205-21e2-41c4-b9d2-b09577f4f202-0-asqbn with resources io.airbyte.config.ResourceRequirements@220250d3[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts null
2024-01-23 22:06:31 platform > Preparing command: docker run --rm --init -i -w /data/92bfe205-21e2-41c4-b9d2-b09577f4f202/0 --log-driver none --name source-gcs-check-92bfe205-21e2-41c4-b9d2-b09577f4f202-0-asqbn --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/source-gcs:0.3.4 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e FIELD_SELECTION_WORKSPACES= -e USE_STREAM_CAPABLE_STATE=true -e WORKER_ENVIRONMENT=DOCKER -e AIRBYTE_ROLE=dev -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=0 -e OTEL_COLLECTOR_ENDPOINT=http://host.docker.internal:4317 -e FEATURE_FLAG_CLIENT=config -e AIRBYTE_VERSION=0.50.44 -e WORKER_JOB_ID=92bfe205-21e2-41c4-b9d2-b09577f4f202 airbyte/source-gcs:0.3.4 check --config source_config.json
2024-01-23 22:06:31 platform > Reading messages from protocol version 0.2.0
2024-01-23 22:06:33 platform > Check failed
2024-01-23 22:06:34 platform > Check connection job received output: io.airbyte.config.StandardCheckConnectionOutput@25d4a4f0[status=failed,message=['Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/file_based/availability_strategy/default_file_based_availability_strategy.py", line 81, in _check_list_files\n    file = next(iter(stream.get_files()))\nStopIteration\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/file_based/availability_strategy/default_file_based_availability_strategy.py", line 62, in check_availability_and_parsability\n    file = self._check_list_files(stream)\n  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/file_based/availability_strategy/default_file_based_availability_strategy.py", line 83, in _check_list_files\n    raise CheckAvailabilityError(FileBasedSourceError.EMPTY_STREAM, stream=stream.name)\nairbyte_cdk.sources.file_based.exceptions.CheckAvailabilityError: No files were identified in the stream. This may be because there are no files in the specified container, or because your glob patterns did not match any files. Please verify that your source contains files last modified after the start_date and that your glob patterns are not overly strict. Contact Support if you need assistance.\nstream=Revenue Reports\n'],additionalProperties={}]
2024-01-23 22:06:34 platform > 
2024-01-23 22:06:34 platform > ----- END CHECK -----
2024-01-23 22:06:34 platform >
```

### Contribute

- [X] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Thanks for reporting the issue @diogoosorio I added it to the connector backlog. GCS is still a community supported connector and can take a while until the team can spend some time to submit a fix. If you want to contribute please send me a msg on Slack so I can help you how to submit the contribution
