### ISSUE TITLE
Cannot resume initial snapshot when _id type is different than ObjectID

### ISSUE THREAD

**Issue by rodireich** [airbytehq/airbyte#34640]
### Connector Name

source-mongodb-v2

### Connector Version

1.2.4

### What step the error happened?

During the sync

### Relevant information

While we allow syncing collection with `_id` type other than the default Object ID, 
Attempting to resume an initial snapshot from a checkpoint when id type is String, Long or Int fails with an exception.

We need to allow resuming from all acceptable id types

### Relevant log output

```shell
2024-01-29 22:48:42 source > 2024-01-29 22:48:42 ERROR i.a.i.s.m.MongoDbSource(read):143 - Unable to perform sync read operation.
2024-01-29 22:48:42 source > java.lang.IllegalArgumentException: state should be: hexString has 24 characters
2024-01-29 22:48:42 source >         at org.bson.assertions.Assertions.isTrueArgument(Assertions.java:64) ~[bson-4.10.2.jar:?]
2024-01-29 22:48:42 source >         at org.bson.types.ObjectId.parseHexString(ObjectId.java:419) ~[bson-4.10.2.jar:?]
2024-01-29 22:48:42 source >         at org.bson.types.ObjectId.<init>(ObjectId.java:205) ~[bson-4.10.2.jar:?]
2024-01-29 22:48:42 source >         at io.airbyte.integrations.source.mongodb.InitialSnapshotHandler.lambda$getIterators$3(InitialSnapshotHandler.java:90) ~[io.airbyte.airbyte-integrations.connectors-source-mongodb-v2-0.50.45.jar:?]
2024-01-29 22:48:42 source >         at java.base/java.util.Optional.map(Optional.java:260) ~[?:?]
2024-01-29 22:48:42 source >         at io.airbyte.integrations.source.mongodb.InitialSnapshotHandler.lambda$getIterators$4(InitialSnapshotHandler.java:90) ~[io.airbyte.airbyte-integrations.connectors-source-mongodb-v2-0.50.45.jar:?]
2024-01-29 22:48:42 source >         at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
2024-01-29 22:48:42 source >         at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
2024-01-29 22:48:42 source >         at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541) ~[?:?]
2024-01-29 22:48:42 source >         at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
2024-01-29 22:48:42 source >         at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
2024-01-29 22:48:42 source >         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
2024-01-29 22:48:42 source >         at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
2024-01-29 22:48:42 source >         at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
2024-01-29 22:48:42 source >         at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
2024-01-29 22:48:42 source >         at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
2024-01-29 22:48:42 source >         at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
2024-01-29 22:48:42 source >         at io.airbyte.integrations.source.mongodb.InitialSnapshotHandler.getIterators(InitialSnapshotHandler.java:113) ~[io.airbyte.airbyte-integrations.connectors-source-mongodb-v2-0.50.45.jar:?]
2024-01-29 22:48:42 source >         at io.airbyte.integrations.source.mongodb.cdc.MongoDbCdcInitializer.createCdcIterators(MongoDbCdcInitializer.java:131) ~[io.airbyte.airbyte-integrations.connectors-source-mongodb-v2-0.50.45.jar:?]
2024-01-29 22:48:42 source >         at io.airbyte.integrations.source.mongodb.MongoDbSource.read(MongoDbSource.java:135) [io.airbyte.airbyte-integrations.connectors-source-mongodb-v2-0.50.45.jar:?]
2024-01-29 22:48:42 source >         at io.airbyte.cdk.integrations.base.IntegrationRunner.readSerial(IntegrationRunner.java:275) [airbyte-cdk-core-0.16.0.jar:?]
2024-01-29 22:48:42 source >         at io.airbyte.cdk.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:173) [airbyte-cdk-core-0.16.0.jar:?]
2024-01-29 22:48:42 source >         at io.airbyte.cdk.integrations.base.IntegrationRunner.run(IntegrationRunner.java:125) [airbyte-cdk-core-0.16.0.jar:?]
2024-01-29 22:48:42 source >         at io.airbyte.integrations.source.mongodb.MongoDbSource.main(MongoDbSource.java:45) [io.airbyte.airbyte-integrations.connectors-source-mongodb-v2-0.50.45.jar:?]
2024-01-29 22:48:42 source > 2024-01-29 22:48:42 ERROR i.a.c.i.b.AirbyteExceptionHandler(uncaughtException):64 - Something went wrong in the connector. See the logs for more details.
2024-01-29 22:48:42 source > java.lang.IllegalArgumentException: state should be: hexString has 24 characters
2024-01-29 22:48:42 source >         at org.bson.assertions.Assertions.isTrueArgument(Assertions.java:64) ~[bson-4.10.2.jar:?]
2024-01-29 22:48:42 source >         at org.bson.types.ObjectId.parseHexString(ObjectId.java:419) ~[bson-4.10.2.jar:?]
2024-01-29 22:48:42 source >         at org.bson.types.ObjectId.<init>(ObjectId.java:205) ~[bson-4.10.2.jar:?]
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by rodireich** [comment]
@danaronson
