### ISSUE TITLE
Configuration check failed while setting up GCS source

### ISSUE THREAD

**Issue by deepapt** [airbytehq/airbyte#34695]
### Connector Name

source-gcs

### Connector Version

0.3.4

### What step the error happened?

Configuring a new connector

### Relevant information

I am trying to set up a Google Cloud Storage (GCS) source to access a file in the bucket named "pubsite_prod_rev_XXXXXXXXXXXXXXXXXXXX." Specifically, this is for a compressed .CSV file located in a subfolder named "sales," with the filename "salesreport_202401.zip" (i.e., "sales/salesreport_202401.zip").

The setup information is as follows:

Added Service Account Information.
Added the bucket: "pubsite_prod_rev_XXXXXXXXXXXXXXXXXXXX."
Name of the stream: "salesreport."
Glob pattern: "sales/salesreport_*.zip."

I used only Service Account JSON and Bucket inputs. However, it doesn't work and returns "Configuration check failed"

I have tried with sample Python code and have successfully downloaded the report from the bucket

### Relevant log output

```shell
Configuration check failed
['Traceback (most recent call last):\n File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/file_based/availability_strategy/default_file_based_availability_strategy.py", line 81, in _check_list_files\n file = next(iter(stream.get_files()))\nStopIteration\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/file_based/availability_strategy/default_file_based_availability_strategy.py", line 62, in check_availability_and_parsability\n file = self._check_list_files(stream)\n File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/file_based/availability_strategy/default_file_based_availability_strategy.py", line 83, in _check_list_files\n raise CheckAvailabilityError(FileBasedSourceError.EMPTY_STREAM, stream=stream.name)\nairbyte_cdk.sources.file_based.exceptions.CheckAvailabilityError: No files were identified in the stream. This may be because there are no files in the specified container, or because your glob patterns did not match any files. Please verify that your source contains files last modified after the start_date and that your glob patterns are not overly strict. Contact Support if you need assistance.\nstream=salesreport\n']
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by szemek** [comment]
@deepapt @marcosmarxm 
https://docs.airbyte.com/integrations/sources/gcs
> This connector supports loading multiple CSV files (non compressed) from a GCS directory.
For the time being, handling CSV files inside ZIP archives is not implemented yet.

https://github.com/airbytehq/airbyte/blob/01b6f4bedeb55a705d465279a030cbbef93ff1d3/airbyte-integrations/connectors/source-gcs/source_gcs/stream_reader.py#L79
As `"csv"` (`FILE_FORMAT = "csv"`) is not even a part of blob name, GCS connector doesn't "find" any matching blobs.
