### ISSUE TITLE
[source-mongodb] self hosted replica set connection error

### ISSUE THREAD

**Issue by chathushka1996** [airbytehq/airbyte#34896]
### Connector Name

source-mongodb

### Connector Version

1.2.6

### What step the error happened?

Configuring a new connector

### Relevant information

<img width="616" alt="Screenshot 2024-02-06 at 11 00 02" src="https://github.com/airbytehq/airbyte/assets/89377148/c0429514-2a56-458b-935b-0f0413c170d5">

I tried to connect mongodb self hosted replica set. but it give error

I can connect to replica set using connection string but that connection string doesn't work with airbyte and give this error

### Relevant log output

```shell
2024-02-06 05:27:22 platform > 	at com.mongodb.internal.operation.CommandOperationHelper.executeRetryableRead(CommandOperationHelper.java:230) ~[mongodb-driver-core-4.10.2.jar:?]
2024-02-06 05:27:22 platform > 	at com.mongodb.internal.operation.CommandOperationHelper.executeRetryableRead(CommandOperationHelper.java:212) ~[mongodb-driver-core-4.10.2.jar:?]
2024-02-06 05:27:22 platform > 	at com.mongodb.internal.operation.ListDatabasesOperation.execute(ListDatabasesOperation.java:124) ~[mongodb-driver-core-4.10.2.jar:?]
2024-02-06 05:27:22 platform > 	at com.mongodb.internal.operation.ListDatabasesOperation.execute(ListDatabasesOperation.java:51) ~[mongodb-driver-core-4.10.2.jar:?]
2024-02-06 05:27:22 platform > 	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:153) ~[mongodb-driver-sync-4.10.2.jar:?]
2024-02-06 05:27:22 platform > 	at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:130) ~[mongodb-driver-sync-4.10.2.jar:?]
2024-02-06 05:27:22 platform > 	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:90) ~[mongodb-driver-sync-4.10.2.jar:?]
2024-02-06 05:27:22 platform > 	at com.mongodb.client.internal.MappingIterable.iterator(MappingIterable.java:42) ~[mongodb-driver-sync-4.10.2.jar:?]
2024-02-06 05:27:22 platform > 	at com.mongodb.client.internal.MappingIterable.iterator(MappingIterable.java:30) ~[mongodb-driver-sync-4.10.2.jar:?]
2024-02-06 05:27:22 platform > 	at java.base/java.lang.Iterable.spliterator(Iterable.java:101) ~[?:?]
2024-02-06 05:27:22 platform > 	at io.airbyte.integrations.source.mongodb.MongoUtil.checkDatabaseExists(MongoUtil.java:84) ~[io.airbyte.airbyte-integrations.connectors-source-mongodb-v2-0.50.38.jar:?]
2024-02-06 05:27:22 platform > 	at io.airbyte.integrations.source.mongodb.MongoDbSource.check(MongoDbSource.java:56) [io.airbyte.airbyte-integrations.connectors-source-mongodb-v2-0.50.38.jar:?]
2024-02-06 05:27:22 platform > 	at io.airbyte.cdk.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:153) [airbyte-cdk-core-0.7.9.jar:?]
2024-02-06 05:27:22 platform > 	at io.airbyte.cdk.integrations.base.IntegrationRunner.run(IntegrationRunner.java:125) [airbyte-cdk-core-0.7.9.jar:?]
2024-02-06 05:27:22 platform > 	at io.airbyte.integrations.source.mongodb.MongoDbSource.main(MongoDbSource.java:45) [io.airbyte.airbyte-integrations.connectors-source-mongodb-v2-0.50.38.jar:?]
2024-02-06 05:27:22 platform > 2024-02-06 05:27:22 INFO i.a.c.i.b.IntegrationRunner(runInternal):231 - Completed integration: io.airbyte.integrations.source.mongodb.MongoDbSource
2024-02-06 05:27:22 platform > 2024-02-06 05:27:22 INFO i.a.i.s.m.MongoDbSource(main):46 - completed source: class io.airbyte.integrations.source.mongodb.MongoDbSource
2024-02-06 05:27:22 platform > Check connection job received output: io.airbyte.config.StandardCheckConnectionOutput@5f794ec2[status=failed,message=Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=44.205.154.107:27049, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketWriteException: Exception sending message}, caused by {javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake}, caused by {java.io.EOFException: SSL peer shut down incorrectly}}, {address=44.205.154.107:27048, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketWriteException: Exception sending message}, caused by {javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake}, caused by {java.io.EOFException: SSL peer shut down incorrectly}}, {address=44.205.154.107:27047, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketWriteException: Exception sending message}, caused by {javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake}, caused by {java.io.EOFException: SSL peer shut down incorrectly}}],additionalProperties={}]
2024-02-06 05:27:22 platform > 
2024-02-06 05:27:22 platform > ----- END check-orchestrator -----
2024-02-06 05:27:22 platform >
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
