### ISSUE TITLE
Unable to create a schema with Snowflake connector when source schema name contains the character `-`

### ISSUE THREAD

**Issue by augustingombault** [airbytehq/airbyte#3489]
## Expected Behavior
The schema should be created on Snowflake replacing the `-` character with the `_` character on the name.

## Current Behavior
Synchronization failed with MySQL source connector and Snowflake destination connector when schema name contains `-`.

## Logs
```
2021-05-19 13:52:10 INFO (/tmp/workspace/1/0) WorkerRun(call):62 - Executing worker wrapper. Airbyte version: 0.23.0-alpha
2021-05-19 13:52:10 INFO (/tmp/workspace/1/0) TemporalAttemptExecution(get):111 - Executing worker wrapper. Airbyte version: 0.23.0-alpha
2021-05-19 13:52:10 INFO (/tmp/workspace/1/0) DefaultReplicationWorker(run):77 - start sync worker. job id: 1 attempt id: 0
2021-05-19 13:52:10 INFO (/tmp/workspace/1/0) DefaultReplicationWorker(run):86 - configured sync modes: {staging-2.tags=full_refresh - append}
2021-05-19 13:52:10 INFO (/tmp/workspace/1/0) DefaultAirbyteDestination(start):67 - Running destination...
2021-05-19 13:52:10 INFO (/tmp/workspace/1/0) LineGobbler(voidCall):69 - Checking if airbyte/destination-snowflake:0.3.6 exists...
2021-05-19 13:52:10 INFO (/tmp/workspace/1/0) LineGobbler(voidCall):69 - airbyte/destination-snowflake:0.3.6 was found locally.
2021-05-19 13:52:10 INFO (/tmp/workspace/1/0) LineGobbler(voidCall):69 - Checking if airbyte/source-mysql:0.3.0 exists...
2021-05-19 13:52:10 INFO (/tmp/workspace/1/0) LineGobbler(voidCall):69 - airbyte/source-mysql:0.3.0 was found locally.
2021-05-19 13:52:12 INFO (/tmp/workspace/1/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-05-19 13:52:12 [32mINFO[m i.a.i.s.m.MySqlSource(main):80 - {} - starting source: class io.airbyte.integrations.source.mysql.MySqlSource
2021-05-19 13:52:12 INFO (/tmp/workspace/1/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-05-19 13:52:12 [32mINFO[m i.a.i.b.IntegrationRunner(run):78 - {} - Running integration: io.airbyte.integrations.source.mysql.MySqlSource
2021-05-19 13:52:12 INFO (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 2021-05-19 13:52:12 [32mINFO[m i.a.i.d.s.SnowflakeDestination(main):81 - {} - starting destination: class io.airbyte.integrations.destination.snowflake.SnowflakeDestination
2021-05-19 13:52:12 INFO (/tmp/workspace/1/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-05-19 13:52:12 [32mINFO[m i.a.i.b.IntegrationCliParser(parseOptions):135 - {} - integration args: {read=null, catalog=source_catalog.json, config=source_config.json}
2021-05-19 13:52:12 INFO (/tmp/workspace/1/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-05-19 13:52:12 [32mINFO[m i.a.i.b.IntegrationRunner(run):82 - {} - Command: READ
2021-05-19 13:52:12 INFO (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 2021-05-19 13:52:12 [32mINFO[m i.a.i.b.IntegrationRunner(run):78 - {} - Running integration: io.airbyte.integrations.destination.snowflake.SnowflakeDestination
2021-05-19 13:52:12 INFO (/tmp/workspace/1/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-05-19 13:52:12 [32mINFO[m i.a.i.b.IntegrationRunner(run):83 - {} - Integration config: IntegrationConfig{command=READ, configPath='source_config.json', catalogPath='source_catalog.json', statePath='null'}
2021-05-19 13:52:12 INFO (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 2021-05-19 13:52:12 [32mINFO[m i.a.i.b.IntegrationCliParser(parseOptions):135 - {} - integration args: {catalog=destination_catalog.json, write=null, config=destination_config.json}
2021-05-19 13:52:12 INFO (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 2021-05-19 13:52:12 [32mINFO[m i.a.i.b.IntegrationRunner(run):82 - {} - Command: WRITE
2021-05-19 13:52:12 INFO (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 2021-05-19 13:52:12 [32mINFO[m i.a.i.b.IntegrationRunner(run):83 - {} - Integration config: IntegrationConfig{command=WRITE, configPath='destination_config.json', catalogPath='destination_catalog.json', statePath='null'}
2021-05-19 13:52:12 INFO (/tmp/workspace/1/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-05-19 13:52:12 [32mINFO[m i.a.i.s.j.JdbcCdcStateManager(<init>):46 - {} - Initialized CDC state with: null
2021-05-19 13:52:12 INFO (/tmp/workspace/1/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-05-19 13:52:12 [32mINFO[m i.a.i.s.j.JdbcStateManager(createCursorInfoForStream):138 - {} - No cursor field set in catalog but not present in state. Stream: AirbyteStreamNameNamespacePair{name='tags', namespace='staging-2'}, New Cursor Field: null. Resetting cursor value
2021-05-19 13:52:12 INFO (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 2021-05-19 13:52:12 [32mINFO[m i.a.i.d.j.c.SwitchingDestination(getConsumer):83 - {} - Using destination type: INSERT
2021-05-19 13:52:12 INFO (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 2021-05-19 13:52:12 [32mINFO[m i.a.i.d.b.BufferedStreamConsumer(startTracked):119 - {} - class io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer started.
2021-05-19 13:52:12 INFO (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 2021-05-19 13:52:12 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp tables in destination started for 1 streams
2021-05-19 13:52:12 INFO (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 2021-05-19 13:52:12 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):147 - {} - Preparing tmp table in destination started for stream testtags. schema: staging-2, tmp table name: _airbyte_1621432332653__airbyte_raw_testtags
2021-05-19 13:52:15 INFO (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 2021-05-19 13:52:15 [32mINFO[m i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):77 - {} - hasFailed: true.
2021-05-19 13:52:15 INFO (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 2021-05-19 13:52:15 [1;31mERROR[m i.a.i.d.b.BufferedStreamConsumer(close):187 - {} - executing on failed close procedure.
2021-05-19 13:52:15 INFO (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 2021-05-19 13:52:15 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):203 - {} - Cleaning tmp tables in destination started for 1 streams
2021-05-19 13:52:15 INFO (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 2021-05-19 13:52:15 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):207 - {} - Cleaning tmp table in destination started for stream testtags. schema staging-2, tmp table name: _airbyte_1621432332653__airbyte_raw_testtags
2021-05-19 13:52:16 INFO (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 2021-05-19 13:52:16 [1;31mERROR[m i.a.i.d.b.BufferedStreamConsumer(close):202 - {} - on close failed.
2021-05-19 13:52:16 ERROR (/tmp/workspace/1/0) LineGobbler(voidCall):69 - Exception in thread "main" net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
2021-05-19 13:52:16 ERROR (/tmp/workspace/1/0) LineGobbler(voidCall):69 - syntax error line 1 at position 35 unexpected '-'.
2021-05-19 13:52:16 ERROR (/tmp/workspace/1/0) LineGobbler(voidCall):69 - syntax error line 1 at position 35 unexpected '-'.
2021-05-19 13:52:16 ERROR (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:124)
2021-05-19 13:52:16 ERROR (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:64)
2021-05-19 13:52:16 ERROR (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 	at net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:434)
2021-05-19 13:52:16 ERROR (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 	at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:338)
2021-05-19 13:52:16 ERROR (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 	at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:501)
2021-05-19 13:52:16 ERROR (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:229)
2021-05-19 13:52:16 ERROR (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:167)
2021-05-19 13:52:16 ERROR (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:749)
2021-05-19 13:52:16 ERROR (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeInternal(SnowflakeStatementV1.java:292)
2021-05-19 13:52:16 ERROR (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 	at net.snowflake.client.jdbc.SnowflakeStatementV1.execute(SnowflakeStatementV1.java:342)
2021-05-19 13:52:16 ERROR (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 	at io.airbyte.db.jdbc.JdbcDatabase.lambda$execute$0(JdbcDatabase.java:50)
2021-05-19 13:52:16 ERROR (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 	at io.airbyte.db.jdbc.DefaultJdbcDatabase.execute(DefaultJdbcDatabase.java:61)
2021-05-19 13:52:16 ERROR (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 	at io.airbyte.db.jdbc.JdbcDatabase.execute(JdbcDatabase.java:50)
2021-05-19 13:52:16 ERROR (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 	at io.airbyte.integrations.destination.jdbc.DefaultSqlOperations.createSchemaIfNotExists(DefaultSqlOperations.java:56)
2021-05-19 13:52:16 ERROR (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 	at io.airbyte.integrations.destination.jdbc.JdbcBufferedConsumerFactory.lambda$onStartFunction$1(JdbcBufferedConsumerFactory.java:150)
2021-05-19 13:52:16 ERROR (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:35)
2021-05-19 13:52:16 ERROR (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 	at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.startTracked(BufferedStreamConsumer.java:121)
2021-05-19 13:52:16 ERROR (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.start(FailureTrackingAirbyteMessageConsumer.java:54)
2021-05-19 13:52:16 ERROR (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 	at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:127)
2021-05-19 13:52:16 ERROR (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:113)
2021-05-19 13:52:16 ERROR (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 	at io.airbyte.integrations.destination.snowflake.SnowflakeDestination.main(SnowflakeDestination.java:82)
2021-05-19 13:52:20 INFO (/tmp/workspace/1/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-05-19 13:52:20 [32mINFO[m i.a.i.s.j.AbstractJdbcSource(queryTableFullRefresh):518 - {} - Queueing query for table: tags
2021-05-19 13:52:21 INFO (/tmp/workspace/1/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-05-19 13:52:21 [32mINFO[m i.a.i.s.j.AbstractJdbcSource(lambda$queryTableFullRefresh$29):523 - {} - Preparing query for table: tags
2021-05-19 13:52:21 INFO (/tmp/workspace/1/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-05-19 13:52:21 [32mINFO[m i.a.i.s.j.AbstractJdbcSource(lambda$queryTableFullRefresh$29):528 - {} - Executing query for table: tags
2021-05-19 13:52:21 INFO (/tmp/workspace/1/0) TemporalAttemptExecution(lambda$getWorkerThread$2):150 - Completing future exceptionally...
io.airbyte.workers.WorkerException: Sync failed
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:130) ~[io.airbyte-airbyte-workers-0.23.0-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:46) ~[io.airbyte-airbyte-workers-0.23.0-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:147) [io.airbyte-airbyte-workers-0.23.0-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.io.IOException: Stream closed
	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:442) ~[?:?]
	at java.io.OutputStream.write(OutputStream.java:162) ~[?:?]
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:123) ~[?:?]
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:242) ~[?:?]
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:312) ~[?:?]
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:290) ~[?:?]
	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:131) ~[?:?]
	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:208) ~[?:?]
	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:120) ~[?:?]
	at java.io.BufferedWriter.write(BufferedWriter.java:233) ~[?:?]
	at java.io.Writer.write(Writer.java:249) ~[?:?]
	at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.accept(DefaultAirbyteDestination.java:82) ~[io.airbyte-airbyte-workers-0.23.0-alpha.jar:?]
	at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.accept(DefaultAirbyteDestination.java:46) ~[io.airbyte-airbyte-workers-0.23.0-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:104) ~[io.airbyte-airbyte-workers-0.23.0-alpha.jar:?]
	... 3 more
	Suppressed: java.io.IOException: Stream closed
		at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:442) ~[?:?]
		at java.io.OutputStream.write(OutputStream.java:162) ~[?:?]
		at java.io.BufferedOutputStream.write(BufferedOutputStream.java:123) ~[?:?]
		at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:242) ~[?:?]
		at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:312) ~[?:?]
		at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:290) ~[?:?]
		at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:131) ~[?:?]
		at java.io.OutputStreamWriter.write(OutputStreamWriter.java:208) ~[?:?]
		at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:120) ~[?:?]
		at java.io.BufferedWriter.flush(BufferedWriter.java:256) ~[?:?]
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.notifyEndOfStream(DefaultAirbyteDestination.java:90) ~[io.airbyte-airbyte-workers-0.23.0-alpha.jar:?]
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.close(DefaultAirbyteDestination.java:102) ~[io.airbyte-airbyte-workers-0.23.0-alpha.jar:?]
		at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:94) ~[io.airbyte-airbyte-workers-0.23.0-alpha.jar:?]
		at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:46) ~[io.airbyte-airbyte-workers-0.23.0-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:147) [io.airbyte-airbyte-workers-0.23.0-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:832) [?:?]
2021-05-19 13:52:21 INFO (/tmp/workspace/1/0) TemporalAttemptExecution(get):134 - Stopping cancellation check scheduling...
2021-05-19 13:52:21 WARN (/tmp/workspace/1/0) POJOActivityTaskHandler$POJOActivityImplementation(execute):243 - Activity failure. ActivityId=9cef8d39-10cb-3cd3-a2f0-5b9d967f4b7d, activityType=Replicate, attempt=1
java.util.concurrent.ExecutionException: io.airbyte.workers.WorkerException: Sync failed
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2063) ~[?:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:132) ~[io.airbyte-airbyte-workers-0.23.0-alpha.jar:?]
	at io.airbyte.workers.temporal.SyncWorkflow$ReplicationActivityImpl.replicate(SyncWorkflow.java:183) ~[io.airbyte-airbyte-workers-0.23.0-alpha.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityInboundCallsInterceptor.execute(POJOActivityTaskHandler.java:277) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityImplementation.execute(POJOActivityTaskHandler.java:216) [temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.POJOActivityTaskHandler.handle(POJOActivityTaskHandler.java:181) [temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:192) [temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:154) [temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73) [temporal-sdk-1.0.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: io.airbyte.workers.WorkerException: Sync failed
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:130) ~[io.airbyte-airbyte-workers-0.23.0-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:46) ~[io.airbyte-airbyte-workers-0.23.0-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:147) ~[io.airbyte-airbyte-workers-0.23.0-alpha.jar:?]
	... 1 more
Caused by: java.io.IOException: Stream closed
	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:442) ~[?:?]
	at java.io.OutputStream.write(OutputStream.java:162) ~[?:?]
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:123) ~[?:?]
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:242) ~[?:?]
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:312) ~[?:?]
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:290) ~[?:?]
	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:131) ~[?:?]
	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:208) ~[?:?]
	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:120) ~[?:?]
	at java.io.BufferedWriter.write(BufferedWriter.java:233) ~[?:?]
	at java.io.Writer.write(Writer.java:249) ~[?:?]
	at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.accept(DefaultAirbyteDestination.java:82) ~[io.airbyte-airbyte-workers-0.23.0-alpha.jar:?]
	at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.accept(DefaultAirbyteDestination.java:46) ~[io.airbyte-airbyte-workers-0.23.0-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:104) ~[io.airbyte-airbyte-workers-0.23.0-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:46) ~[io.airbyte-airbyte-workers-0.23.0-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:147) ~[io.airbyte-airbyte-workers-0.23.0-alpha.jar:?]
	... 1 more
	Suppressed: java.io.IOException: Stream closed
		at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:442) ~[?:?]
		at java.io.OutputStream.write(OutputStream.java:162) ~[?:?]
		at java.io.BufferedOutputStream.write(BufferedOutputStream.java:123) ~[?:?]
		at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:242) ~[?:?]
		at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:312) ~[?:?]
		at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:290) ~[?:?]
		at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:131) ~[?:?]
		at java.io.OutputStreamWriter.write(OutputStreamWriter.java:208) ~[?:?]
		at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:120) ~[?:?]
		at java.io.BufferedWriter.flush(BufferedWriter.java:256) ~[?:?]
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.notifyEndOfStream(DefaultAirbyteDestination.java:90) ~[io.airbyte-airbyte-workers-0.23.0-alpha.jar:?]
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.close(DefaultAirbyteDestination.java:102) ~[io.airbyte-airbyte-workers-0.23.0-alpha.jar:?]
		at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:94) ~[io.airbyte-airbyte-workers-0.23.0-alpha.jar:?]
		at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:46) ~[io.airbyte-airbyte-workers-0.23.0-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:147) ~[io.airbyte-airbyte-workers-0.23.0-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:832) [?:?]
```

## Steps to Reproduce
1. Add Mysql source with a database name containing `-` character
1. Add Snowflake destination
1. Start a synchronization 

## Severity of the bug for you
Low

## Airbyte Version
0.23.0-alpha

## Connector Version (if applicable)
* airbyte/source-mysql:0.3.0
* airbyte/destination-snowflake:0.3.6

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368196071523) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
@augustingombault thanks for the report! we'll take a look and fix soon.
