### ISSUE TITLE
Source GitHub: Unhandled exception `AttributeError: 'NoneType' object has no attribute 'get'`

### ISSUE THREAD

**Issue by aaronsteers** [airbytehq/airbyte#35429]
### Connector Name

source-github

### Connector Version

latest

### What step the error happened?

None

### Relevant information

This occurs with the following config:

```
        {
            "owner": "airbytehq",
            "repositories": REPOS,
            "start_date": "2024-01-01T00:00:00Z",
            "credentials": {
                "personal_access_token": str(
                    ab.get_secret(ENV_GITHUB_PERSONAL_ACCESS_TOKEN)
                )
            },
        }
```

I suspect the issue is an expired or invalid personal access token - but the error does not imply this. We should try to improve handling and raise a more informative error message.

### Relevant log output

```shell
Traceback (most recent call last):
      File "/Users/ajsteers/Source/aj-dataops-personal/.venv-source-github/bin/source-github", line 8, in <module>
        sys.exit(run())
      File "/Users/ajsteers/Source/aj-dataops-personal/.venv-source-github/lib/python3.10/site-packages/source_github/run.py", line 17, in run
        launch(source, sys.argv[1:])
      File "/Users/ajsteers/Source/aj-dataops-personal/.venv-source-github/lib/python3.10/site-packages/airbyte_cdk/entrypoint.py", line 214, in launch
        for message in source_entrypoint.run(parsed_args):
      File "/Users/ajsteers/Source/aj-dataops-personal/.venv-source-github/lib/python3.10/site-packages/airbyte_cdk/entrypoint.py", line 116, in run
        yield from map(AirbyteEntrypoint.airbyte_message_to_string, self.discover(source_spec, config))
      File "/Users/ajsteers/Source/aj-dataops-personal/.venv-source-github/lib/python3.10/site-packages/airbyte_cdk/entrypoint.py", line 151, in discover
        catalog = self.source.discover(self.logger, config)
      File "/Users/ajsteers/Source/aj-dataops-personal/.venv-source-github/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py", line 77, in discover
        streams = [stream.as_airbyte_stream() for stream in self.streams(config=config)]
      File "/Users/ajsteers/Source/aj-dataops-personal/.venv-source-github/lib/python3.10/site-packages/source_github/source.py", line 246, in streams
        authenticator = self._get_authenticator(config)
      File "/Users/ajsteers/Source/aj-dataops-personal/.venv-source-github/lib/python3.10/site-packages/source_github/source.py", line 129, in _get_authenticator
        return MultipleTokenAuthenticatorWithRateLimiter(tokens=tokens)
      File "/Users/ajsteers/Source/aj-dataops-personal/.venv-source-github/lib/python3.10/site-packages/source_github/utils.py", line 63, in __init__
        self.check_all_tokens()
      File "/Users/ajsteers/Source/aj-dataops-personal/.venv-source-github/lib/python3.10/site-packages/source_github/utils.py", line 137, in check_all_tokens
        self._check_token_limits(token)
      File "/Users/ajsteers/Source/aj-dataops-personal/.venv-source-github/lib/python3.10/site-packages/source_github/utils.py", line 125, in _check_token_limits
        remaining_info_core = rate_limit_info.get("core")
```
```


### Contribute

- [X] Yes, I want to contribute

**Comment by aaronsteers** [comment]
Confirmed: When I replaced the access token with a new one, the error resolved.
