### ISSUE TITLE
[Helm] 500 NullPointerException in API Server on listing elements

### ISSUE THREAD

**Issue by LouisAuneau** [airbytehq/airbyte#35430]
### Helm Chart Version

0.53.250

### What step the error happened?

Upgrading the Platform or Helm Chart

### Revelant information

We have a Helm (`0.53.250` / `0.50.51`) install on **GKE**, with private database hosted in **CloudSQL**, and logs & state hosted in **Google Cloud Storage** buckets. Our cluster is healthy. `GET http://localhost:8006/health` returns a 200 response or `GET http://localhost:8006/v1/sources/<source_id>` returns a 200 response. But any call to `http://localhost:8006/v1/sources` or `http://localhost:8006/v1/workspaces` returns a 500 with body:
```
{
    "type": "about:blank",
    "status": 500
}
```

I tried with a completely empty install (empty database, empty buckets, full re-install of the helm chart) and got the same error.

### Relevant log output

```shell
The API Server logs shows the following error:

java.lang.NullPointerException: null
	at io.airbyte.api.server.services.SourceServiceImpl.listSourcesForWorkspaces(SourceService.kt:296) ~[io.airbyte-airbyte-api-server-0.50.51.jar:?]
	at io.airbyte.api.server.controllers.SourcesController.listSources$lambda$4(SourcesController.kt:180) ~[io.airbyte-airbyte-api-server-0.50.51.jar:?]
	at io.airbyte.api.server.apiTracking.TrackingHelper.callWithTracker(TrackingHelper.kt:107) ~[io.airbyte-airbyte-api-server-0.50.51.jar:?]
	at io.airbyte.api.server.controllers.SourcesController.listSources(SourcesController.kt:179) ~[io.airbyte-airbyte-api-server-0.50.51.jar:?]
	at io.airbyte.api.server.controllers.$SourcesController$Definition$Exec.dispatch(Unknown Source) ~[io.airbyte-airbyte-api-server-0.50.51.jar:?]
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594) ~[micronaut-inject-3.10.1.jar:3.10.1]
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303) ~[micronaut-router-3.10.1.jar:3.10.1]
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111) ~[micronaut-router-3.10.1.jar:3.10.1]
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103) ~[micronaut-http-3.10.1.jar:3.10.1]
	at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659) ~[micronaut-http-server-3.10.1.jar:3.10.1]
	at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49) ~[reactor-core-3.5.5.jar:3.5.5]
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62) ~[reactor-core-3.5.5.jar:3.5.5]
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194) ~[reactor-core-3.5.5.jar:3.5.5]
	at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62) ~[micronaut-runtime-3.10.1.jar:3.10.1]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.5.5.jar:3.5.5]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.5.5.jar:3.5.5]
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53) ~[micronaut-context-3.10.1.jar:3.10.1]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by marcosmarxm** [comment]
Closed as duplicated of https://github.com/airbytehq/airbyte/discussions/35116#discussioncomment-8569228
