### ISSUE TITLE
[destination-mongodb] Cannot connect MongoDB Standalone

### ISSUE THREAD

**Issue by telmocrp1** [airbytehq/airbyte#35621]
### Connector Name

destination-mongodb

### Connector Version

0.2.0

### What step the error happened?

Configuring a new connector

### Relevant information

When connecting my MongoDB Community instance, I get this error message `Configuration check failed
Format specifier '%s'`
Impossible to connect, I've modified the port, credentials, rights... 

I put all the logs directly into the issue.

### Relevant log output

```shell
2024-02-25 18:52:53 [46mplatform[0m > Docker volume job log path: /tmp/workspace/39ea67c7-8951-45b8-96e1-f4caf7480516/0/logs.log
2024-02-25 18:52:53 [46mplatform[0m > Executing worker wrapper. Airbyte version: 0.50.53
2024-02-25 18:52:53 [46mplatform[0m > Attempt 0 to save workflow id for cancellation
2024-02-25 18:52:53 [46mplatform[0m > 
2024-02-25 18:52:53 [46mplatform[0m > ----- START CHECK -----
2024-02-25 18:52:53 [46mplatform[0m > 
2024-02-25 18:52:53 [46mplatform[0m > Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2024-02-25 18:52:53 [46mplatform[0m > Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2024-02-25 18:52:53 [46mplatform[0m > Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2024-02-25 18:52:53 [46mplatform[0m > Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2024-02-25 18:52:53 [46mplatform[0m > Using default value for environment variable LAUNCHDARKLY_KEY: ''
2024-02-25 18:52:53 [46mplatform[0m > Checking if airbyte/destination-mongodb:0.2.0 exists...
2024-02-25 18:52:53 [46mplatform[0m > airbyte/destination-mongodb:0.2.0 not found locally. Attempting to pull the image...
2024-02-25 18:53:04 [46mplatform[0m > Pulled airbyte/destination-mongodb:0.2.0 from remote.
2024-02-25 18:53:04 [46mplatform[0m > Creating docker container = destination-mongodb-check-39ea67c7-8951-45b8-96e1-f4caf7480516-0-zzyxa with resources io.airbyte.config.ResourceRequirements@5473c82c[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts null
2024-02-25 18:53:04 [46mplatform[0m > Preparing command: docker run --rm --init -i -w /data/39ea67c7-8951-45b8-96e1-f4caf7480516/0 --log-driver none --name destination-mongodb-check-39ea67c7-8951-45b8-96e1-f4caf7480516-0-zzyxa --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/destination-mongodb:0.2.0 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e FIELD_SELECTION_WORKSPACES= -e USE_STREAM_CAPABLE_STATE=true -e AIRBYTE_ROLE=dev -e WORKER_ENVIRONMENT=DOCKER -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=0 -e OTEL_COLLECTOR_ENDPOINT=http://host.docker.internal:4317 -e FEATURE_FLAG_CLIENT=config -e AIRBYTE_VERSION=0.50.53 -e WORKER_JOB_ID=39ea67c7-8951-45b8-96e1-f4caf7480516 airbyte/destination-mongodb:0.2.0 check --config source_config.json
2024-02-25 18:53:04 [46mplatform[0m > Reading messages from protocol version 0.2.0
2024-02-25 18:53:05 [46mplatform[0m > INFO i.a.i.d.m.MongodbDestination(main):63 starting destination: class io.airbyte.integrations.destination.mongodb.MongodbDestination
2024-02-25 18:53:05 [46mplatform[0m > INFO i.a.i.b.IntegrationCliParser(parseOptions):126 integration args: {check=null, config=source_config.json}
2024-02-25 18:53:05 [46mplatform[0m > INFO i.a.i.b.IntegrationRunner(runInternal):106 Running integration: io.airbyte.integrations.base.ssh.SshWrappedDestination
2024-02-25 18:53:05 [46mplatform[0m > INFO i.a.i.b.IntegrationRunner(runInternal):107 Command: CHECK
2024-02-25 18:53:05 [46mplatform[0m > INFO i.a.i.b.IntegrationRunner(runInternal):108 Integration config: IntegrationConfig{command=CHECK, configPath='source_config.json', catalogPath='null', statePath='null'}
2024-02-25 18:53:05 [46mplatform[0m > WARN c.n.s.JsonMetaSchema(newValidator):278 Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2024-02-25 18:53:05 [46mplatform[0m > WARN c.n.s.JsonMetaSchema(newValidator):278 Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2024-02-25 18:53:05 [46mplatform[0m > INFO i.a.i.b.s.SshTunnel(getInstance):204 Starting connection with method: NO_TUNNEL
2024-02-25 18:53:05 [46mplatform[0m > ERROR i.a.i.d.m.MongodbDestination(check):85 Check failed. java.util.MissingFormatArgumentException: Format specifier '%s'
	at java.util.Formatter.format(Formatter.java:2688) ~[?:?]
	at java.util.Formatter.format(Formatter.java:2625) ~[?:?]
	at java.lang.String.format(String.java:4143) ~[?:?]
	at io.airbyte.integrations.destination.mongodb.MongodbDestination.buildConnectionString(MongodbDestination.java:168) ~[io.airbyte.airbyte-integrations.connectors-destination-mongodb-24.0.2.jar:?]
	at io.airbyte.integrations.destination.mongodb.MongodbDestination.getConnectionString(MongodbDestination.java:150) ~[io.airbyte.airbyte-integrations.connectors-destination-mongodb-24.0.2.jar:?]
	at io.airbyte.integrations.destination.mongodb.MongodbDestination.getDatabase(MongodbDestination.java:136) ~[io.airbyte.airbyte-integrations.connectors-destination-mongodb-24.0.2.jar:?]
	at io.airbyte.integrations.destination.mongodb.MongodbDestination.check(MongodbDestination.java:71) ~[io.airbyte.airbyte-integrations.connectors-destination-mongodb-24.0.2.jar:?]
	at io.airbyte.integrations.base.ssh.SshTunnel.sshWrap(SshTunnel.java:270) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
	at io.airbyte.integrations.base.ssh.SshWrappedDestination.check(SshWrappedDestination.java:67) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:124) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:99) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
	at io.airbyte.integrations.destination.mongodb.MongodbDestination.main(MongodbDestination.java:64) ~[io.airbyte.airbyte-integrations.connectors-destination-mongodb-24.0.2.jar:?]

Stack Trace: java.util.MissingFormatArgumentException: Format specifier '%s'
	at java.base/java.util.Formatter.format(Formatter.java:2688)
	at java.base/java.util.Formatter.format(Formatter.java:2625)
	at java.base/java.lang.String.format(String.java:4143)
	at io.airbyte.integrations.destination.mongodb.MongodbDestination.buildConnectionString(MongodbDestination.java:168)
	at io.airbyte.integrations.destination.mongodb.MongodbDestination.getConnectionString(MongodbDestination.java:150)
	at io.airbyte.integrations.destination.mongodb.MongodbDestination.getDatabase(MongodbDestination.java:136)
	at io.airbyte.integrations.destination.mongodb.MongodbDestination.check(MongodbDestination.java:71)
	at io.airbyte.integrations.base.ssh.SshTunnel.sshWrap(SshTunnel.java:270)
	at io.airbyte.integrations.base.ssh.SshWrappedDestination.check(SshWrappedDestination.java:67)
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:124)
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:99)
	at io.airbyte.integrations.destination.mongodb.MongodbDestination.main(MongodbDestination.java:64)

2024-02-25 18:53:05 [46mplatform[0m > INFO i.a.i.b.IntegrationRunner(runInternal):197 Completed integration: io.airbyte.integrations.base.ssh.SshWrappedDestination
2024-02-25 18:53:05 [46mplatform[0m > INFO i.a.i.d.m.MongodbDestination(main):65 completed destination: class io.airbyte.integrations.destination.mongodb.MongodbDestination
2024-02-25 18:53:05 [46mplatform[0m > Check connection job received output: io.airbyte.config.StandardCheckConnectionOutput@7828d34b[status=failed,message=Format specifier '%s',additionalProperties={}]
2024-02-25 18:53:05 [46mplatform[0m > 
2024-02-25 18:53:05 [46mplatform[0m > ----- END CHECK -----
2024-02-25 18:53:05 [46mplatform[0m >
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Hello @telmocrp1 Mongo Database Destination is a vital part of our community, but it's not currently on our roadmap for updates. This means it might take some time before it gets prioritized by the Airbyte Team. However, we encourage community involvement to improve it, and your contributions are welcome! If you're interested, please reach out to me on Slack so we can discuss how you can help 🎖️ .

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
