### ISSUE TITLE
[source-shopify] TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by vivekdk** [airbytehq/airbyte#35778]
### Connector Name

source-shopify

### Connector Version

2.0.0

### What step the error happened?

During the sync

### Relevant information

Get this error during shopify to clickhouse sync

```
2024-03-03 19:03:07 source > Marking stream customer_address as STARTED
2024-03-03 19:03:07 replication-orchestrator > Attempt 0 to stream status started null:customer_address
2024-03-03 19:03:07 source > Syncing stream: customer_address 
2024-03-03 19:03:07 source > Encountered an exception while reading stream customer_address
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 126, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 203, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 263, in _read_full_refresh
    for record_data_or_message in stream_instance.read_full_refresh(configured_stream.cursor_field, logger, self._slice_logger):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/core.py", line 118, in read_full_refresh
    for _slice in slices:
  File "/airbyte/integration_code/source_shopify/streams/base_streams.py", line 690, in stream_slices
    start = pdm.parse(state)
  File "/usr/local/lib/python3.9/site-packages/pendulum/parser.py", line 29, in parse
    return _parse(text, **options)
  File "/usr/local/lib/python3.9/site-packages/pendulum/parser.py", line 45, in _parse
    parsed = base_parse(text, **options)
  File "/usr/local/lib/python3.9/site-packages/pendulum/parsing/__init__.py", line 74, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/usr/local/lib/python3.9/site-packages/pendulum/parsing/__init__.py", line 115, in _parse
    return _parse_iso8601_interval(text)
  File "/usr/local/lib/python3.9/site-packages/pendulum/parsing/__init__.py", line 215, in _parse_iso8601_interval
    if "/" not in text:
TypeError: argument of type 'NoneType' is not iterable
2024-03-03 19:03:07 source > Marking stream customer_address as STOPPED
2024-03-03 19:03:07 replication-orchestrator > Attempt 0 to update stream status incomplete null:customer_address
2024-03-03 19:03:07 replication-orchestrator > Attempt 0 to update stream status incomplete null:customer_address error: io.airbyte.api.client.invoker.generated.ApiException: updateStreamStatus call failed with: 400 - {"message":"Incomplete run cause must be set for runs that stopped in an incomplete state.","exceptionClassName":"io.airbyte.server.apis.StreamStatusesApiController$Validations$2","exceptionStack":["io.airbyte.server.apis.StreamStatusesApiController$Validations$2: Incomplete run cause must be set for runs that stopped in an incomplete state.","\tat io.airbyte.server.apis.StreamStatusesApiController$Validations.validate(StreamStatusesApiController.java:93)","\tat io.airbyte.server.apis.StreamStatusesApiController.updateStreamStatus(StreamStatusesApiController.java:56)","\tat io.airbyte.server.apis.$StreamStatusesApiController$Definition$Exec.dispatch(Unknown Source)","\tat io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371)","\tat io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594)","\tat io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)","\tat io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)","\tat io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)","\tat io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659)","\tat reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)","\tat reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)","\tat reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)","\tat io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62)","\tat reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)","\tat reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)","\tat io.micrometer.core.instrument.composite.CompositeTimer.recordCallable(CompositeTimer.java:129)","\tat io.micrometer.core.instrument.Timer.lambda$wrap$1(Timer.java:206)","\tat io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)","\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)","\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)","\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)","\tat java.base/java.lang.Thread.run(Thread.java:1583)"]}
```

This happens for all these streams for which Graphql bulk operations are enabled
```metafield_collections
metafield_customers 
metafield_draft_orders
metafield_locations
metafield_orders
metafield_product_images
metafield_product_variants
collections
discount_codes
fulfillment_orders
inventory_items
inventory_levels
customer_address
```

I tried with all three sync modes (incremental append, Full refresh overwite and fill refresh append), but the result is the same.

### Contribute

- [ ] Yes, I want to contribute

**Comment by bazarnov** [comment]
Please try the latest version `2.0.4`, the issue should be fixed there.
