### ISSUE TITLE
[destination-redshift] sync crashes because of soft reset

### ISSUE THREAD

**Issue by RogerSehn** [airbytehq/airbyte#35807]
### Connector Name

destination-redshift

### Connector Version

2.1.7

### What step the error happened?

During the sync

### Relevant information

Because of some reason, the connector starts a soft reset, then the query consumes a lot of storage and broke when the disk is full. At the beginning, the cluster has 100gb free, approximately, and all of that are consuming by the job. 

Full log:
[1521ff03_2dc8_4fc2_abb7_2dbafc259f94_job_5889_attempt_1_txt.txt](https://github.com/airbytehq/airbyte/files/14489330/1521ff03_2dc8_4fc2_abb7_2dbafc259f94_job_5889_attempt_1_txt.txt)

### Relevant log output

```shell
2024-03-05 01:36:00 destination > 2024-03-05 01:36:00 INFO i.a.c.i.d.FlushWorkers(printWorkerInfo):146 - [ASYNC WORKER INFO] Pool queue size: 0, Active threads: 0
2024-03-05 01:37:00 destination > 2024-03-05 01:37:00 INFO i.a.c.i.d.b.BufferManager(printQueueInfo):118 - [ASYNC QUEUE INFO] Global: max: 519.71 MB, allocated: 10 MB (10.0 MB), % used: 0.01924163893484099 | State Manager memory usage: Allocated: 10 MB, Used: 0 bytes, percentage Used 0.000000
2024-03-05 01:37:00 destination > 2024-03-05 01:37:00 INFO i.a.c.i.d.FlushWorkers(printWorkerInfo):146 - [ASYNC WORKER INFO] Pool queue size: 0, Active threads: 0
2024-03-05 01:37:37 destination > 2024-03-05 01:37:37 ERROR i.a.i.d.r.t.RedshiftDestinationHandler(execute):44 - Sql b9a03d02-06d5-475b-beb7-f81c79ff58c3-af37cd1a-37df-4241-b2dc-ae6b50db75fd failed
2024-03-05 01:37:37 destination > com.amazon.redshift.util.RedshiftException: ERROR: Insufficient system resources to support data size: consider increasing compute size. (Disk Full)
2024-03-05 01:37:37 destination >   Detail: 
2024-03-05 01:37:37 destination >   -----------------------------------------------
2024-03-05 01:37:37 destination >   error:  Insufficient system resources to support data size: consider increasing compute size. (Disk Full)
2024-03-05 01:37:37 destination >   code:      1016
2024-03-05 01:37:37 destination >   context:   node: 0
2024-03-05 01:37:37 destination >   query:     52501344
2024-03-05 01:37:37 destination >   location:  fdisk_api.cpp:436
2024-03-05 01:37:37 destination >   process:   query0_113_52501344 [pid=10893]
2024-03-05 01:37:37 destination >   -----------------------------------------------
2024-03-05 01:37:37 destination > 
2024-03-05 01:37:37 destination > 	at com.amazon.redshift.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2613) ~[redshift-jdbc42-2.1.0.23.jar:?]
2024-03-05 01:37:37 destination > 	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResultsOnThread(QueryExecutorImpl.java:2281) ~[redshift-jdbc42-2.1.0.23.jar:?]
2024-03-05 01:37:37 destination > 	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1886) ~[redshift-jdbc42-2.1.0.23.jar:?]
2024-03-05 01:37:37 destination > 	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1878) ~[redshift-jdbc42-2.1.0.23.jar:?]
2024-03-05 01:37:37 destination > 	at com.amazon.redshift.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:375) ~[redshift-jdbc42-2.1.0.23.jar:?]
2024-03-05 01:37:37 destination > 	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeInternal(RedshiftStatementImpl.java:515) ~[redshift-jdbc42-2.1.0.23.jar:?]
2024-03-05 01:37:37 destination > 	at com.amazon.redshift.jdbc.RedshiftStatementImpl.execute(RedshiftStatementImpl.java:436) ~[redshift-jdbc42-2.1.0.23.jar:?]
2024-03-05 01:37:37 destination > 	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeWithFlags(RedshiftStatementImpl.java:377) ~[redshift-jdbc42-2.1.0.23.jar:?]
2024-03-05 01:37:37 destination > 	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeCachedSql(RedshiftStatementImpl.java:363) ~[redshift-jdbc42-2.1.0.23.jar:?]
2024-03-05 01:37:37 destination > 	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeWithFlags(RedshiftStatementImpl.java:340) ~[redshift-jdbc42-2.1.0.23.jar:?]
2024-03-05 01:37:37 destination > 	at com.amazon.redshift.jdbc.RedshiftStatementImpl.execute(RedshiftStatementImpl.java:330) ~[redshift-jdbc42-2.1.0.23.jar:?]
2024-03-05 01:37:37 destination > 	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94) ~[HikariCP-5.1.0.jar:?]
2024-03-05 01:37:37 destination > 	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-5.1.0.jar:?]
2024-03-05 01:37:37 destination > 	at io.airbyte.cdk.db.jdbc.JdbcDatabase.lambda$executeWithinTransaction$1(JdbcDatabase.java:57) ~[airbyte-cdk-core-0.20.0.jar:?]
2024-03-05 01:37:37 destination > 	at io.airbyte.cdk.db.jdbc.DefaultJdbcDatabase.execute(DefaultJdbcDatabase.java:47) ~[airbyte-cdk-core-0.20.0.jar:?]
2024-03-05 01:37:37 destination > 	at io.airbyte.cdk.db.jdbc.JdbcDatabase.executeWithinTransaction(JdbcDatabase.java:54) ~[airbyte-cdk-core-0.20.0.jar:?]
2024-03-05 01:37:37 destination > 	at io.airbyte.integrations.destination.redshift.typing_deduping.RedshiftDestinationHandler.execute(RedshiftDestinationHandler.java:42) ~[io.airbyte.airbyte-integrations.connectors-destination-redshift-0.50.48.jar:?]
2024-03-05 01:37:37 destination > 	at io.airbyte.integrations.base.destination.typing_deduping.TypeAndDedupeTransaction.executeTypeAndDedupe(TypeAndDedupeTransaction.java:39) ~[airbyte-cdk-typing-deduping-0.20.0.jar:?]
2024-03-05 01:37:37 destination > 	at io.airbyte.integrations.base.destination.typing_deduping.TypeAndDedupeTransaction.executeSoftReset(TypeAndDedupeTransaction.java:69) ~[airbyte-cdk-typing-deduping-0.20.0.jar:?]
2024-03-05 01:37:37 destination > 	at io.airbyte.integrations.base.destination.typing_deduping.DefaultTyperDeduper.lambda$prepareTablesFuture$3(DefaultTyperDeduper.java:163) ~[airbyte-cdk-typing-deduping-0.20.0.jar:?]
2024-03-05 01:37:37 destination > 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
2024-03-05 01:37:37 destination > 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
2024-03-05 01:37:37 destination > 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
2024-03-05 01:37:37 destination > 	at java.base/java.lang.Thread.run(Thread.java:833) [?:?]
2024-03-05 01:37:37 destination > 2024-03-05 01:37:37 ERROR i.a.i.b.d.t.TypeAndDedupeTransaction(executeTypeAndDedupe):48 - Encountered Exception on unsafe SQL for stream stg_data_operators_tim_engineering_charging charging_received with suffix _ab_soft_reset, Retry is skipped
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by gisripa** [comment]
Can you share the DB instance size & size of the data you are syncing

**Comment by evantahler** [comment]
closing due to lack of comment from OP
