### ISSUE TITLE
[source-shopify] 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by rainers24** [airbytehq/airbyte#35972]
### Connector Name

source-shopify

### Connector Version

2.0.0

### What step the error happened?

During the sync

### Relevant information

Hi, 

looks like there a new erorr while pulling Order and Transaction from shopify source.

### Relevant log output

```shell
2024-03-11 19:45:21 source > Encountered an exception while reading stream transactions
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 126, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 203, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 239, in _read_incremental
    for record_data_or_message in stream_instance.read_incremental(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/core.py", line 156, in read_incremental
    for record_data_or_message in records:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 482, in read_records
    yield from self._read_pages(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 499, in _read_pages
    yield from records_generator_fn(request, response, stream_state, stream_slice)
  File "/airbyte/integration_code/source_shopify/streams/base_streams.py", line 722, in parse_response
    yield from self.process_bulk_results(response, stream_state)
  File "/airbyte/integration_code/source_shopify/streams/base_streams.py", line 709, in process_bulk_results
    filename = self.job_manager.job_check(response)
  File "/airbyte/integration_code/source_shopify/utils.py", line 221, in wrapper_balance_rate_limit
    return func(*args, **kwargs)
  File "/airbyte/integration_code/source_shopify/shopify_graphql/bulk/job.py", line 246, in job_check
    job_response = self.job_healthcheck(created_job_response)
  File "/airbyte/integration_code/source_shopify/shopify_graphql/bulk/job.py", line 233, in job_healthcheck
    if not self.has_running_concurrent_job(errors):
  File "/airbyte/integration_code/source_shopify/shopify_graphql/bulk/job.py", line 187, in has_running_concurrent_job
    message = error.get("message", "")
AttributeError: 'str' object has no attribute 'get'
2024-03-11 19:45:21 source > Marking stream transactions as STOPPED
2024-03-11 19:45:21 source > Finished syncing transactions
2024-03-11 19:45:21 source > SourceShopify runtimes:
Syncing stream orders 0:00:01.640385
Syncing stream transactions 0:00:02.326003
2024-03-11 19:45:21 source > 'str' object has no attribute 'get'
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by bazarnov** [comment]
Closing in favor of: https://github.com/airbytehq/oncall/issues/4824
