### ISSUE TITLE
[destination-redshift] Redshift V2: cannot save to raw tables if the row has a column with a value bigger than 65K chars and sync crashes

### ISSUE THREAD

**Issue by CataldoTractable** [airbytehq/airbyte#35985]
### Connector Name

destination-redshift

### Connector Version

2.1.8

### What step the error happened?

During the sync

### Relevant information

I have updated the Redshift connector to V2. Despite saying in the [documentation](https://docs.airbyte.com/integrations/destinations/redshift#data-size-limitations) that rows too big will be ignored, the sync still fails when one row has got keys with values over 65K chars. The sync takes place with the `S3 staging` strategy, so it's the COPY command that fails. The error from the `stl_load_errors` table is as follows:

### Relevant log output

```shell
2024-03-12 12:12:49 destination > INFO pool-4-thread-1 i.a.i.d.r.o.RedshiftS3StagingSqlOperations(copyIntoTableFromStage):110 Starting copy to target table from stage: schema_name_raw__stream_table_name in destination from stage: staging/schema_name_raw__stream_table_name/2024_03_12_12_db33e281-8fc3-4ae3-bff7-13a99567b08d/, schema: airbyte_internal, .
2024-03-12 12:12:50 destination > ERROR pool-4-thread-1 i.a.c.i.d.s.AsyncFlush(flush):119 Failed to flush and commit buffer data into destination's raw table java.lang.RuntimeException: Failed to upload data from stage staging/schema_name_raw__stream_table_name/2024_03_12_12_db33e281-8fc3-4ae3-bff7-13a99567b08d/
        at io.airbyte.cdk.integrations.destination.staging.GeneralStagingFunctions.copyIntoTableFromStage(GeneralStagingFunctions.java:110) ~[airbyte-cdk-db-destinations-0.23.2.jar:?]
        at io.airbyte.cdk.integrations.destination.staging.AsyncFlush.flush(AsyncFlush.java:106) ~[airbyte-cdk-s3-destinations-0.23.2.jar:?]
        at io.airbyte.cdk.integrations.destination_async.FlushWorkers.lambda$flush$1(FlushWorkers.java:169) ~[airbyte-cdk-core-0.23.2.jar:?]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.RuntimeException: com.amazon.redshift.util.RedshiftException: ERROR: Load into table 'schema_name_raw__stream_table_name' failed.  Check 'stl_load_errors' system table for details.
        at io.airbyte.commons.lang.Exceptions.castCheckedToRuntime(Exceptions.java:49) ~[airbyte-cdk-dependencies-0.23.2.jar:?]
        at io.airbyte.commons.lang.Exceptions.toRuntime(Exceptions.java:40) ~[airbyte-cdk-dependencies-0.23.2.jar:?]
        at io.airbyte.integrations.destination.redshift.operations.RedshiftS3StagingSqlOperations.executeCopy(RedshiftS3StagingSqlOperations.java:148) ~[io.airbyte.airbyte-integrations.connectors-destination-redshift.jar:?]
        at io.airbyte.integrations.destination.redshift.operations.RedshiftS3StagingSqlOperations.lambda$copyIntoTableFromStage$1(RedshiftS3StagingSqlOperations.java:115) ~[io.airbyte.airbyte-integrations.connectors-destination-redshift.jar:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at io.airbyte.integrations.destination.redshift.operations.RedshiftS3StagingSqlOperations.lambda$copyIntoTableFromStage$2(RedshiftS3StagingSqlOperations.java:115) ~[io.airbyte.airbyte-integrations.connectors-destination-redshift.jar:?]
        at io.airbyte.commons.lang.Exceptions.castCheckedToRuntime(Exceptions.java:45) ~[airbyte-cdk-dependencies-0.23.2.jar:?]
        at io.airbyte.commons.lang.Exceptions.toRuntime(Exceptions.java:40) ~[airbyte-cdk-dependencies-0.23.2.jar:?]
        at io.airbyte.integrations.destination.redshift.operations.RedshiftS3StagingSqlOperations.copyIntoTableFromStage(RedshiftS3StagingSqlOperations.java:113) ~[io.airbyte.airbyte-integrations.connectors-destination-redshift.jar:?]
        at io.airbyte.cdk.integrations.destination.staging.GeneralStagingFunctions.copyIntoTableFromStage(GeneralStagingFunctions.java:97) ~[airbyte-cdk-db-destinations-0.23.2.jar:?]
        ... 7 more



And in the stl_load_errors table:
43416	_airbyte_data                                                                                                                  	super     	16384000  	1506 1224	String value exceeds the max size of 65535 bytes
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by jbfbell** [comment]
@CataldoTractable please update to the latest version of redshift, we very recently fixed this!
