### ISSUE TITLE
[helm] AWS SDK version mismatch error in 0.53.0

### ISSUE THREAD

**Issue by nicolasgpvoodoo** [airbytehq/airbyte#36184]
### Helm Chart Version

0.55.40

### What step the error happened?

During the Sync

### Revelant information

# Context:

Airbyte helm deployment configured with S3 bucket for logging. Version is 0.53.0, according to helm chart 0.55.40.

# Behavior

When starting a sync, the server immediately refuses and throws an error (caught by the UI) referring to an invalid class definition:
`java.lang.NoClassDefFoundError: software/amazon/awssdk/protocols/query/interceptor/QueryParametersToBodyInterceptor`

Unless I'm mistaken, it is likely due to a miss-match of build configuration for the AWS SDK.

According to the logs, last call is performed by `sts-2.20.162.jar`, while `aws-core` is using version `2.23.17.` Might want to look into this further first.

# Expected behavior

Startup of the sync without any error being triggered.

### Relevant log output

```shell
2024-03-15 13:25:31 ERROR i.a.s.e.UncaughtExceptionHandler(handle):31 - Uncaught exception
java.lang.NoClassDefFoundError: software/amazon/awssdk/protocols/query/interceptor/QueryParametersToBodyInterceptor
	at software.amazon.awssdk.services.sts.DefaultStsBaseClientBuilder.finalizeServiceConfiguration(DefaultStsBaseClientBuilder.java:73) ~[sts-2.20.162.jar:?]
	at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.finalizeChildConfiguration(AwsDefaultClientBuilder.java:160) ~[aws-core-2.23.17.jar:?]
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.syncClientConfiguration(SdkDefaultClientBuilder.java:188) ~[sdk-core-2.23.17.jar:?]
	at software.amazon.awssdk.services.sts.DefaultStsClientBuilder.buildClient(DefaultStsClientBuilder.java:39) ~[sts-2.20.162.jar:?]
	at software.amazon.awssdk.services.sts.DefaultStsClientBuilder.buildClient(DefaultStsClientBuilder.java:28) ~[sts-2.20.162.jar:?]
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:155) ~[sdk-core-2.23.17.jar:?]
	at software.amazon.awssdk.services.sts.internal.StsWebIdentityCredentialsProviderFactory$StsWebIdentityCredentialsProvider.<init>(StsWebIdentityCredentialsProviderFactory.java:74) ~[sts-2.20.162.jar:?]
	at software.amazon.awssdk.services.sts.internal.StsWebIdentityCredentialsProviderFactory$StsWebIdentityCredentialsProvider.<init>(StsWebIdentityCredentialsProviderFactory.java:56) ~[sts-2.20.162.jar:?]
	at software.amazon.awssdk.services.sts.internal.StsWebIdentityCredentialsProviderFactory.create(StsWebIdentityCredentialsProviderFactory.java:48) ~[sts-2.20.162.jar:?]
	at software.amazon.awssdk.auth.credentials.WebIdentityTokenFileCredentialsProvider.<init>(WebIdentityTokenFileCredentialsProvider.java:115) ~[auth-2.23.17.jar:?]
	at software.amazon.awssdk.auth.credentials.WebIdentityTokenFileCredentialsProvider.<init>(WebIdentityTokenFileCredentialsProvider.java:51) ~[auth-2.23.17.jar:?]
	at software.amazon.awssdk.auth.credentials.WebIdentityTokenFileCredentialsProvider$BuilderImpl.build(WebIdentityTokenFileCredentialsProvider.java:315) ~[auth-2.23.17.jar:?]
	at software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider.lambda$createChain$0(DefaultCredentialsProvider.java:97) ~[auth-2.23.17.jar:?]
	at software.amazon.awssdk.utils.Lazy.getValue(Lazy.java:50) ~[utils-2.23.17.jar:?]
	at software.amazon.awssdk.auth.credentials.internal.LazyAwsCredentialsProvider.resolveCredentials(LazyAwsCredentialsProvider.java:45) ~[auth-2.23.17.jar:?]
	at software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider.resolveCredentials(DefaultCredentialsProvider.java:128) ~[auth-2.23.17.jar:?]
	at software.amazon.awssdk.auth.credentials.AwsCredentialsProvider.resolveIdentity(AwsCredentialsProvider.java:54) ~[auth-2.23.17.jar:?]
	at software.amazon.awssdk.identity.spi.IdentityProvider.resolveIdentity(IdentityProvider.java:60) ~[identity-spi-2.23.17.jar:?]
	at software.amazon.awssdk.awscore.internal.authcontext.AwsCredentialsAuthorizationStrategy.lambda$resolveCredentials$2(AwsCredentialsAuthorizationStrategy.java:112) ~[aws-core-2.23.17.jar:?]
	at software.amazon.awssdk.core.internal.util.MetricUtils.measureDuration(MetricUtils.java:60) ~[sdk-core-2.23.17.jar:?]
	at software.amazon.awssdk.awscore.internal.authcontext.AwsCredentialsAuthorizationStrategy.resolveCredentials(AwsCredentialsAuthorizationStrategy.java:112) ~[aws-core-2.23.17.jar:?]
	at software.amazon.awssdk.awscore.internal.authcontext.AwsCredentialsAuthorizationStrategy.addCredentialsToExecutionAttributes(AwsCredentialsAuthorizationStrategy.java:85) ~[aws-core-2.23.17.jar:?]
	at software.amazon.awssdk.awscore.internal.AwsExecutionContextBuilder.invokeInterceptorsAndCreateExecutionContext(AwsExecutionContextBuilder.java:138) ~[aws-core-2.23.17.jar:?]
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.invokeInterceptorsAndCreateExecutionContext(AwsSyncClientHandler.java:67) ~[aws-core-2.23.17.jar:?]
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:76) ~[sdk-core-2.23.17.jar:?]
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:182) ~[sdk-core-2.23.17.jar:?]
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:74) ~[sdk-core-2.23.17.jar:?]
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45) ~[sdk-core-2.23.17.jar:?]
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:53) ~[aws-core-2.23.17.jar:?]
	at software.amazon.awssdk.services.s3.DefaultS3Client.listObjectsV2(DefaultS3Client.java:6032) ~[s3-2.16.84.jar:?]
	at software.amazon.awssdk.services.s3.paginators.ListObjectsV2Iterable$ListObjectsV2ResponseFetcher.nextPage(ListObjectsV2Iterable.java:153) ~[s3-2.16.84.jar:?]
	at software.amazon.awssdk.services.s3.paginators.ListObjectsV2Iterable$ListObjectsV2ResponseFetcher.nextPage(ListObjectsV2Iterable.java:144) ~[s3-2.16.84.jar:?]
	at software.amazon.awssdk.core.pagination.sync.PaginatedResponsesIterator.next(PaginatedResponsesIterator.java:58) ~[sdk-core-2.23.17.jar:?]
	at io.airbyte.config.helpers.S3Logs.getAscendingObjectKeys(S3Logs.java:148) ~[io.airbyte.airbyte-config-config-models-0.53.0.jar:?]
	at io.airbyte.config.helpers.S3Logs.tailCloudLog(S3Logs.java:92) ~[io.airbyte.airbyte-config-config-models-0.53.0.jar:?]
	at io.airbyte.config.helpers.LogClientSingleton.getJobLogFile(LogClientSingleton.java:86) ~[io.airbyte.airbyte-config-config-models-0.53.0.jar:?]
	at io.airbyte.commons.server.converters.JobConverter.getLogRead(JobConverter.java:235) ~[io.airbyte-airbyte-commons-server-0.53.0.jar:?]
	at io.airbyte.commons.server.converters.JobConverter.getSynchronousJobRead(JobConverter.java:270) ~[io.airbyte-airbyte-commons-server-0.53.0.jar:?]
	at io.airbyte.commons.server.converters.JobConverter.getSynchronousJobRead(JobConverter.java:256) ~[io.airbyte-airbyte-commons-server-0.53.0.jar:?]
	at io.airbyte.commons.server.handlers.SchedulerHandler.retrieveDiscoveredSchema(SchedulerHandler.java:553) ~[io.airbyte-airbyte-commons-server-0.53.0.jar:?]
	at io.airbyte.commons.server.handlers.SchedulerHandler.discoverSchemaForSourceFromSourceId(SchedulerHandler.java:373) ~[io.airbyte-airbyte-commons-server-0.53.0.jar:?]
	at io.airbyte.server.apis.SourceApiController.lambda$discoverSchemaForSource$6(SourceApiController.java:114) ~[io.airbyte-airbyte-server-0.53.0.jar:?]
	at io.airbyte.server.apis.ApiHelper.execute(ApiHelper.java:28) ~[io.airbyte-airbyte-server-0.53.0.jar:?]
	at io.airbyte.server.apis.SourceApiController.discoverSchemaForSource(SourceApiController.java:114) ~[io.airbyte-airbyte-server-0.53.0.jar:?]
	at io.airbyte.server.apis.$SourceApiController$Definition$Exec.dispatch(Unknown Source) ~[io.airbyte-airbyte-server-0.53.0.jar:?]
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invokeUnsafe(AbstractExecutableMethodsDefinition.java:461) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext$BeanContextUnsafeExecutionHandle.invokeUnsafe(DefaultBeanContext.java:4276) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:271) ~[micronaut-router-4.3.10.jar:4.3.10]
	at io.micronaut.http.server.RouteExecutor.executeRouteAndConvertBody(RouteExecutor.java:488) ~[micronaut-http-server-4.3.10.jar:4.3.10]
	at io.micronaut.http.server.RouteExecutor.lambda$callRoute$6(RouteExecutor.java:465) ~[micronaut-http-server-4.3.10.jar:4.3.10]
	at io.micronaut.core.execution.ExecutionFlow.lambda$async$1(ExecutionFlow.java:87) ~[micronaut-core-4.3.10.jar:4.3.10]
	at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211) ~[micronaut-core-4.3.10.jar:4.3.10]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassNotFoundException: software.amazon.awssdk.protocols.query.interceptor.QueryParametersToBodyInterceptor
	... 55 more
```

**Comment by cobed95** [comment]
I've run into this issue as well on v0.52.0. I suspect that you were trying to do external logging to S3 via EKS IRSA. My workaround was to use an access key based logging as per the [docs](https://docs.airbyte.com/deploying-airbyte/on-kubernetes-via-helm#external-logs-with-s3). Although I'm not a big fan of creating an IAM user just for this purpose, this works (at least for v0.52.0).

It seems that airbyte currently uses an outdated SDK for external logging only. The S3 source and destination work fine with EKS IRSA since they are built completely isolated from the airbyte server.

**Comment by bgroff** [comment]
This should be fixed in the latest releases.
