### ISSUE TITLE
Freshdesk skill sync is giving 404

### ISSUE THREAD

**Issue by HarishPetavue** [airbytehq/airbyte#36226]
### Connector Name

source-freshdesk

### Connector Version

3.0.7

### What step the error happened?

During the sync

### Relevant information

Hello,

When i try to sync skills object from freshdesk to postgres, im getting 404 error.

### Relevant log output

```shell
File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://*.freshdesk.com/api/v2/skills?per_page=100
,retryable=<null>,timestamp=1710747486672,additionalProperties={}], io.airbyte.config.FailureReason@4b5a9f2e[failureOrigin=source,failureType=<null>,internalMessage=Source didn't exit properly - check the logs!,externalMessage=Something went wrong within the source connector,metadata=io.airbyte.config.Metadata@16bd7d8[additionalProperties={attemptNumber=2, jobId=9458678, connector_command=read}],stacktrace=io.airbyte.workers.internal.exception.SourceException: Source didn't exit properly - check the logs!
        at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:367)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
        at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:173)
        at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:365)
        ... 4 more
,retryable=<null>,timestamp=1710747487762,additionalProperties={}]],additionalProperties={}]
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
@HarishPetavue are you able to run this request manually? Freshdesk doesn't have an error page to explain possible causes.

**Comment by HarishPetavue** [comment]
@marcosmarxm Seems the issue with freshdesk api itself, i think its better till freshdesk fix the issue the skill object should not be synced, it stopping the entire sync.

**Comment by marcosmarxm** [comment]
Thanks, please disable the `skills` stream. I'm going to share this to the team.

**Comment by agarwalgazal** [comment]
Freshdesk skills api is still not functional. As per Freshdesk, the new endpoint is: get  /api/v2/admin/skills/
Ref: https://developers.freshdesk.com/api/#skills

**Comment by marcosmarxm** [comment]
@airbytehq/community-contractors can someone take this task? 😉

**Comment by pabloescoder** [comment]
@marcosmarxm I can pick this up

**Comment by natikgadzhi** [comment]
@pabloescoder since you're not actively working on this, I am movinng this away from in progres so we have a clear picture for @brianjlai — it's important that you keep "in nprogress" actually in progress.

**Comment by pabloescoder** [comment]
@natikgadzhi Got it, I'll keep that in mind for any future bugs/features.
