### ISSUE TITLE
Helm Chart Not Working For External Database

### ISSUE THREAD

**Issue by travishillmeq** [airbytehq/airbyte#36238]
### Helm Chart Version

0.56.16

### What step the error happened?

On deploy

### Revelant information

Using airbyte helm chart version 0.56.16 and the following values.yaml:
```
global:
  database:
    secretName: "secrets-airbyte-airbyte-webapp-svc-prod"
    secretValue:  "airbyte-db-password"

postgresql:
  enabled: false

externalDatabase:
  host: "my-custom-host.com"
  user: "postgres"
  database: "airbyte"
  password: ""
  existingSecret: "secrets-airbyte-airbyte-webapp-svc-prod"
  existingSecretPasswordKey: "airbyte-db-password"
  port: 5432
  jdbcUrl: ""
  ```
  and using the following Chart.yaml:
  ```
 apiVersion: v2
name: airbyte
description: A Helm chart for installing Airbyte
type: application

# The chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# Version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: "1.0"

dependencies:
- name: airbyte
  version: 0.56.16
  repository: https://airbytehq.github.io/helm-charts
```
  I cannot successfully deploy airbyte whilst using an external database.
  
The `DATABASE_HOST` and `DATABASE_PORT` are pulled from the generated config map `airbyte-airbyte-env` where these values are set:
 
 ```
  DATABASE_DB: db-airbyte
  DATABASE_HOST: airbyte-db-svc # todo: database information into secrets
  DATABASE_PORT: "5432"
  DATABASE_URL: "jdbc:postgresql://airbyte-db-svc:5432/db-airbyte"
  ```
  
 It looks like the database user is pulled from the generated secret `airbyte-airbyte-secrets`. Where the default is set to `airbyte`.
 
 The only thing i can get to work and get updated in the generated config is if you set `externalDatabase.existingSecret` and `externalDatabase.existingSecretPasswordKey`
 
 As far as I can tell and no matter what I set and where, I cannot set the `DATABASE_HOST`, `DATABASE_PORT` and `DATABASE_USER` via the chart. No matter what I try, its pulled from the configmap and secret. Nothing I set in the chart updates the generated configmap or secret.
 
Using `env_var` or `extraEnv` it does add it to the config, but I am getting a collision because theres two env vars within the generated yaml file with the same env var name.

Can someone please provide some direction on how to properly set the values.yaml and/or Chart.yaml so I can set airbyte to use an external database with an existing kubernetes secret?

### Relevant log output

```shell
2024-03-18 14:25:12 ERROR i.m.m.h.i.HealthResult$Builder(exception):119 - Health indicator [airbyte-db-svc:5432/db-airbyte] reported exception: java.sql.SQLTransientConnectionException: HikariPool-2 - Connection is not available, request timed out after 30000ms.
java.sql.SQLTransientConnectionException: HikariPool-2 - Connection is not available, request timed out after 30000ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:181) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[HikariCP-5.0.1.jar:?]
	at io.micronaut.management.health.indicator.jdbc.JdbcIndicator.lambda$getResult$0(JdbcIndicator.java:92) ~[micronaut-management-3.10.1.jar:3.10.1]
	at io.micronaut.core.async.publisher.AsyncSingleResultPublisher$ExecutorServiceSubscription.lambda$request$1(AsyncSingleResultPublisher.java:100) ~[micronaut-core-reactive-3.10.1.jar:3.10.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "airbyte"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:693) ~[postgresql-42.5.4.jar:42.5.4]
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:203) ~[postgresql-42.5.4.jar:42.5.4]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258) ~[postgresql-42.5.4.jar:42.5.4]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54) ~[postgresql-42.5.4.jar:42.5.4]
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:253) ~[postgresql-42.5.4.jar:42.5.4]
	at org.postgresql.Driver.makeConnection(Driver.java:434) ~[postgresql-42.5.4.jar:42.5.4]
	at org.postgresql.Driver.connect(Driver.java:291) ~[postgresql-42.5.4.jar:42.5.4]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:733) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712) ~[HikariCP-5.0.1.jar:?]
	... 4 more
```
```

**Comment by travishillmeq** [comment]
Issue was not using `airbyte` in values.yaml:
``` 
airbyte:
  global:
    database:
      secretName: "secrets-airbyte-airbyte-webapp-svc-prod"
      secretValue:  "airbyte-db-password"
  
  postgresql:
    enabled: false
  
  externalDatabase:
    host: "my-custom-host.com"
    user: "postgres"
    database: "airbyte"
    password: ""
    existingSecret: "secrets-airbyte-airbyte-webapp-svc-prod"
    existingSecretPasswordKey: "airbyte-db-password"
    port: 5432
    jdbcUrl: ""
```

**Comment by anitsche-bt** [comment]
Seems to be still valid, i tried to install via `abctl local install` and external database, but got the same error with v1.1.1, after adding airbyte: as root, the install completed successfully:

`Installed Helm Chart airbyte/airbyte:
            Name: airbyte-abctl
            Namespace: airbyte-abctl
            Version: 1.1.1
            AppVersion: 1.1.0
            Release: 1`

Error before:
'  ERROR   airbyte-bootloader: i.a.d.c.DatabaseAvailabilityCheck(lambda$isDatabaseConnected$1):78 - Failed to verify database connection.
  ERROR   airbyte-bootloader: org.jooq.exception.DataAccessException: Error getting connection from data source HikariDataSource (HikariPool-1)
  ERROR   airbyte-bootloader: Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30003ms (total=0, active=0, idle=0, waiting=0)
  ERROR   airbyte-bootloader: Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "airbyte"
  ERROR   airbyte-bootloader: i.a.d.c.DatabaseAvailabilityCheck(lambda$isDatabaseConnected$1):78 - Failed to verify database connection.'
