### ISSUE TITLE
Netsuite ODBC - Error in SQL statement

### ISSUE THREAD

**Issue by Jgerardopine** [airbytehq/airbyte#36283]

**Comment by Jgerardopine** [comment]
When running a sync, there are some streams that return this error:

```
Error in the SQL statement.[10104] (10104) (SQLExecDirectW)')"), DeletedRecordInConnect: AirbyteTracedException("('42000', '[42000] [NetSuite][ODBC 64 bit driver][OpenAccess SDK SQL Engine]Syntax Error in the SQL statement.[10104] (10104) (SQLExecDirectW)')"), transaction: AirbyteTracedException("('HY000', '[HY000] [NetSuite][ODBC 64 bit driver][OpenAccess SDK SQL Engine]Failed to retrieve data. Error ticket# lt3g0s99wyb56kuqss91[400] (400) (SQLFetch)')")
2024-02-26 22:00:14 [44msource[0m > None
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 214, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 121, in run
    yield from map(AirbyteEntrypoint.airbyte_message_to_string, self.read(source_spec, config, config_catalog, state))
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 163, in read
    yield from self.source.read(self.logger, config, catalog, state)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 177, in read
    raise AirbyteTracedException(message=error_message, failure_type=FailureType.config_error)
airbyte_cdk.utils.traced_exception.AirbyteTracedException: None
2024-02-26 22:00:16 [46mplatform[0m > readFromSource: source exception
io.airbyte.workers.internal.exception.SourceException: Source process exited with non-zero exit code 1
	at io.airbyte.workers.general.BufferedReplicationWorker.readFromSource(BufferedReplicationWorker.java:366) ~[io.airbyte-airbyte-commons-worker-0.50.44.jar:?]
	at io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsyncWithHeartbeatCheck$3(BufferedReplicationWorker.java:235) ~[io.airbyte-airbyte-commons-worker-0.50.44.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

It is not able to retrieve data, but it is not clear why the this specific table is not taking data. We are trying to figure out if there is because the source data (customer) does not have data inn this specific table.
