### ISSUE TITLE
[destination-bigquery] Executing maximum query length of 1024k characters

### ISSUE THREAD

**Issue by benorourke** [airbytehq/airbyte#36303]
### Connector Name

destination-bigquery

### Connector Version

2.4.12

### What step the error happened?

None

### Relevant information

Key Details:
- Loading method: GCS Staging
- Transformation query run type: interactive
- Client chunk size: 15

When attempting to load some tables, a [POST request on the BQ jobs API](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/insert) is causing the connector to fail:
> The query is too large. The maximum standard SQL query length is 1024.00K characters, including comments and white space characters.

### Relevant log output

```shell
2024-03-20 01:39:51 destination > ERROR main i.a.c.i.b.AirbyteExceptionHandler(uncaughtException):64 Something went wrong in the connector. See the logs for more details. java.util.concurrent.CompletionException: java.lang.RuntimeException: com.google.cloud.bigquery.BigQueryException: The query is too large. The maximum standard SQL query length is 1024.00K characters, including comments and white space characters.
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.RuntimeException: com.google.cloud.bigquery.BigQueryException: The query is too large. The maximum standard SQL query length is 1024.00K characters, including comments and white space characters.
        at io.airbyte.integrations.base.destination.typing_deduping.DefaultTyperDeduper.lambda$prepareTablesFuture$3(DefaultTyperDeduper.java:215) ~[airbyte-cdk-typing-deduping-0.23.11.jar:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more
Caused by: com.google.cloud.bigquery.BigQueryException: The query is too large. The maximum standard SQL query length is 1024.00K characters, including comments and white space characters.
        at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:114) ~[google-cloud-bigquery-2.37.0.jar:2.37.0]
        at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.create(HttpBigQueryRpc.java:231) ~[google-cloud-bigquery-2.37.0.jar:2.37.0]
        at com.google.cloud.bigquery.BigQueryImpl$5.call(BigQueryImpl.java:414) ~[google-cloud-bigquery-2.37.0.jar:2.37.0]
        at com.google.cloud.bigquery.BigQueryImpl$5.call(BigQueryImpl.java:399) ~[google-cloud-bigquery-2.37.0.jar:2.37.0]
        at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103) ~[gax-2.41.0.jar:2.41.0]
        at com.google.cloud.bigquery.BigQueryRetryHelper.run(BigQueryRetryHelper.java:86) ~[google-cloud-bigquery-2.37.0.jar:2.37.0]
        at com.google.cloud.bigquery.BigQueryRetryHelper.runWithRetries(BigQueryRetryHelper.java:49) ~[google-cloud-bigquery-2.37.0.jar:2.37.0]
        at com.google.cloud.bigquery.BigQueryImpl.create(BigQueryImpl.java:398) ~[google-cloud-bigquery-2.37.0.jar:2.37.0]
        at com.google.cloud.bigquery.BigQueryImpl.create(BigQueryImpl.java:363) ~[google-cloud-bigquery-2.37.0.jar:2.37.0]
        at io.airbyte.integrations.destination.bigquery.typing_deduping.BigQueryDestinationHandler.execute(BigQueryDestinationHandler.java:141) ~[io.airbyte.airbyte-integrations.connectors-destination-bigquery.jar:?]
        at io.airbyte.integrations.base.destination.typing_deduping.TypeAndDedupeTransaction.executeTypeAndDedupe(TypeAndDedupeTransaction.java:46) ~[airbyte-cdk-typing-deduping-0.23.11.jar:?]
        at io.airbyte.integrations.base.destination.typing_deduping.TypeAndDedupeTransaction.executeSoftReset(TypeAndDedupeTransaction.java:71) ~[airbyte-cdk-typing-deduping-0.23.11.jar:?]
        at io.airbyte.integrations.base.destination.typing_deduping.DefaultTyperDeduper.lambda$prepareTablesFuture$3(DefaultTyperDeduper.java:191) ~[airbyte-cdk-typing-deduping-0.23.11.jar:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
POST https://bigquery.googleapis.com/bigquery/v2/projects/seedlegals/jobs?prettyPrint=false
{
  "code": 400,
  "errors": [
    {
      "domain": "global",
      "message": "The query is too large. The maximum standard SQL query length is 1024.00K characters, including comments and white space characters.",
      "reason": "invalid"
    }
  ],
  "message": "The query is too large. The maximum standard SQL query length is 1024.00K characters, including comments and white space characters.",
  "status": "INVALID_ARGUMENT"
}
        at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146) ~[google-api-client-2.2.0.jar:2.2.0]
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118) ~[google-api-client-2.2.0.jar:2.2.0]
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37) ~[google-api-client-2.2.0.jar:2.2.0]
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$3.interceptResponse(AbstractGoogleClientRequest.java:466) ~[google-api-client-2.2.0.jar:2.2.0]
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1111) ~[google-http-client-1.43.3.jar:1.43.3]
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:552) ~[google-api-client-2.2.0.jar:2.2.0]
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:493) ~[google-api-client-2.2.0.jar:2.2.0]
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:603) ~[google-api-client-2.2.0.jar:2.2.0]
        at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.create(HttpBigQueryRpc.java:229) ~[google-cloud-bigquery-2.37.0.jar:2.37.0]
        at com.google.cloud.bigquery.BigQueryImpl$5.call(BigQueryImpl.java:414) ~[google-cloud-bigquery-2.37.0.jar:2.37.0]
        at com.google.cloud.bigquery.BigQueryImpl$5.call(BigQueryImpl.java:399) ~[google-cloud-bigquery-2.37.0.jar:2.37.0]
        at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103) ~[gax-2.41.0.jar:2.41.0]
        at com.google.cloud.bigquery.BigQueryRetryHelper.run(BigQueryRetryHelper.java:86) ~[google-cloud-bigquery-2.37.0.jar:2.37.0]
        at com.google.cloud.bigquery.BigQueryRetryHelper.runWithRetries(BigQueryRetryHelper.java:49) ~[google-cloud-bigquery-2.37.0.jar:2.37.0]
        at com.google.cloud.bigquery.BigQueryImpl.create(BigQueryImpl.java:398) ~[google-cloud-bigquery-2.37.0.jar:2.37.0]
        at com.google.cloud.bigquery.BigQueryImpl.create(BigQueryImpl.java:363) ~[google-cloud-bigquery-2.37.0.jar:2.37.0]
        at io.airbyte.integrations.destination.bigquery.typing_deduping.BigQueryDestinationHandler.execute(BigQueryDestinationHandler.java:141) ~[io.airbyte.airbyte-integrations.connectors-destination-bigquery.jar:?]
        at io.airbyte.integrations.base.destination.typing_deduping.TypeAndDedupeTransaction.executeTypeAndDedupe(TypeAndDedupeTransaction.java:46) ~[airbyte-cdk-typing-deduping-0.23.11.jar:?]
        at io.airbyte.integrations.base.destination.typing_deduping.TypeAndDedupeTransaction.executeSoftReset(TypeAndDedupeTransaction.java:71) ~[airbyte-cdk-typing-deduping-0.23.11.jar:?]
        at io.airbyte.integrations.base.destination.typing_deduping.DefaultTyperDeduper.lambda$prepareTablesFuture$3(DefaultTyperDeduper.java:191) ~[airbyte-cdk-typing-deduping-0.23.11.jar:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Hello @benorourke I added the issue to the destination backlog for grooming and further investigation. Do you mind sharing what source are you using or any more information could help us reproduce the issue?

**Comment by benorourke** [comment]
Hi @marcosmarxm, thanks for your reply.

I'm using the Hubspot source (4.0.0). In particular, the deals/deal_property_history table is the issue. I suspect it may be due to a large property value.

**Comment by jbfbell** [comment]
Hey @benorourke sorry you're experiencing this issue, we've seen this issue occur usually when there are a lot of columns. Values typically don't cause this since we're selecting from the raw table. But it's possible some combination of syncing into hundreds of columns, or if the column names are particularly long. You may be able to use Airbyte's column selection feature to only sync the columns you're interested in which would reduce the query size. You can also set up multiple connections and split the columns across two distinct tables in the bigquery but that is a little trickier.

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 365 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.
