### ISSUE TITLE
[docker] Deploy Bug when not using postgres user

### ISSUE THREAD

**Issue by renasm** [airbytehq/airbyte#36311]
### Platform Version

0.53.1

### What step the error happened?

On deploy

### Revelant information

When using another DB user that not 'postgre' it will fail on airbyte-temporal. And airbyte will not start.

Looking on docker-compose.yaml I do see hardcoded:

DB=postgresql

  airbyte-temporal:
    image: airbyte/temporal:${VERSION}
    logging: *default-logging
    container_name: airbyte-temporal
    restart: unless-stopped
    environment:
      - DB=postgresql
      - DB_PORT=${DATABASE_PORT}
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
      - LOG_LEVEL=${LOG_LEVEL}
      - POSTGRES_PWD=${DATABASE_PASSWORD}
      - POSTGRES_SEEDS=${DATABASE_HOST}
      - POSTGRES_USER=${DATABASE_USER}
    volumes:
      - ./temporal/dynamicconfig:/etc/temporal/config/dynamicconfig
    networks:
      - airbyte_internal

I do think this is the reason why It fails.

### Relevant log output

```shell
airbyte-server                    | Mar 20, 2024 10:53:44 AM io.grpc.internal.ManagedChannelImpl$NameResolverListener handleErrorInSyncContext
airbyte-server                    | WARNING: [Channel<45>: (airbyte-temporal:7233)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Unable to resolve host airbyte-temporal, cause=java.lang.RuntimeException: java.net.UnknownHostException: airbyte-temporal
airbyte-server                    |     at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223)
airbyte-server                    |     at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)
airbyte-server                    |     at io.grpc.grpclb.GrpclbNameResolver.doResolve(GrpclbNameResolver.java:63)
airbyte-server                    |     at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)
airbyte-server                    |     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
airbyte-server                    |     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
airbyte-server                    |     at java.base/java.lang.Thread.run(Thread.java:1583)
airbyte-server                    | Caused by: java.net.UnknownHostException: airbyte-temporal
airbyte-server                    |     at java.base/java.net.InetAddress$CachedLookup.get(InetAddress.java:988)
airbyte-server                    |     at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1818)
airbyte-server                    |     at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1688)
airbyte-server                    |     at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:632)
airbyte-server                    |     at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
```

**Comment by marcosmarxm** [comment]
Can you share the temporal logs?

**Comment by renasm** [comment]
Yes, how can i access the temporal logs(Linux on EC2)

**Comment by marcosmarxm** [comment]
`docker logs airbyte-temporal > temporal.logs`

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.
