### ISSUE TITLE
[source-zoom] Report streams fail on 404

### ISSUE THREAD

**Issue by Rock-it-science** [airbytehq/airbyte#36341]
### Connector Name

source-zoom

### Connector Version

1.1.0

### What step the error happened?

During the sync

### Relevant information

Syncing `report_webinar_participants` causes jobs to fail due to a 404 from Zoom. Other streams such as webinars and webinar_registrants are able to complete successfully.

I have also tested `report_webinars` and confirmed it also fails with the same error.

(Note the actual webinar ID in the log output below is replaced with `***` for privacy)

### Relevant log output

```shell
2024-03-19 17:13:55 source > Encountered an exception while reading stream report_webinar_participants
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 129, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 224, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 284, in _read_full_refresh
    for record_data_or_message in stream_instance.read_full_refresh(configured_stream.cursor_field, logger, self._slice_logger):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/core.py", line 121, in read_full_refresh
    yield from self.read_records(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py", line 104, in read_records
    yield from self.retriever.read_records(self.get_json_schema(), stream_slice)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 324, in read_records
    for stream_data in self._read_pages(record_generator, self.state, stream_slice):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 288, in _read_pages
    response = self._fetch_next_page(stream_state, stream_slice, next_page_token)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 263, in _fetch_next_page
    return self.requester.send_request(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 461, in send_request
    return self._validate_response(response)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 566, in _validate_response
    raise ReadException(error_message)
airbyte_cdk.sources.declarative.exceptions.ReadException: Request to https://api.zoom.us/v2/report/webinars/***/participants?page_size=30 failed with status code 404 and error message Meeting does not exist: ***.
2024-03-19 17:13:55 source > Marking stream report_webinar_participants as STOPPED
```

### Contribute

- [X] Yes, I want to contribute

**Comment by Rock-it-science** [comment]
Issue may be related to this: https://devforum.zoom.us/t/meeting-does-not-exist-error-when-meeting-exists/19128

Would be nice to have the ability to allow the sync to attempt to continue despite the 404 in case some requests are successful - i.e. change to a warning instead of a stopping the stream.

**Comment by marcosmarxm** [comment]
Agree @Rock-it-science it's possible to add a IGNORE the error and continue the sync. (Read more about it [here](https://docs.airbyte.com/connector-development/config-based/understanding-the-yaml-file/error-handling#from-status-code)). Please let me know or send a msg to me on Slack if you want to make the contribution 🚀

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.
