### ISSUE TITLE
[server] GCP secret manager cannot store secrets

### ISSUE THREAD

**Issue by ism-k** [airbytehq/airbyte#36442]
### Platform Version

v0.52.0 ~ v0.55.1

### What step the error happened?

Other

### Revelant information

I saw this change (https://github.com/airbytehq/airbyte-platform/commit/fdc62493e94cdadaf8352b725e1d731bb682beda Update user interface for configuring secret manager and storage (#11509)) and enabled gcp secret manager, but since then mysql source and bigquery destination registration has failed.

While using a gcp secret manager, set up a connector with confidential information for both source and destination and press the [Set up source/destination] button from the management screen.

When I did so, I found the following messages in the airbyte server logs:
```
2024-03-25 13:46:06 WARN i.a.c.s.p.GoogleSecretManagerPersistence(read):55 - Unable to locate secret for coordinate airbyte_workspace_00000000-0000-0000-0000-000000000000_secret_b24af7c6-a4fd-4f1d-9bc9-c219617c3d45_v1.
com.google.api.gax.rpc.NotFoundException: io.grpc.StatusRuntimeException: NOT_FOUND: Secret [projects/75442930950/secrets/airbyte_workspace_00000000-0000-0000-0000-000000000000_secret_b24af7c6-a4fd-4f1d-9bc9-c219617c3d45_v1] not found or has no versions.
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:90) ~[gax-2.39.0.jar:2.39.0]
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:41) ~[gax-2.39.0.jar:2.39.0]
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:86) ~[gax-grpc-2.39.0.jar:2.39.0]
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:66) ~[gax-grpc-2.39.0.jar:2.39.0]
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97) ~[gax-grpc-2.39.0.jar:2.39.0]
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:84) ~[api-common-2.22.0.jar:2.22.0]
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1127) ~[guava-32.1.3-jre.jar:?]
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31) ~[guava-32.1.3-jre.jar:?]
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1286) ~[guava-32.1.3-jre.jar:?]
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1055) ~[guava-32.1.3-jre.jar:?]
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:807) ~[guava-32.1.3-jre.jar:?]
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:568) ~[grpc-stub-1.61.0.jar:1.61.0]
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:538) ~[grpc-stub-1.61.0.jar:1.61.0]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[grpc-api-1.61.0.jar:1.61.0]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[grpc-api-1.61.0.jar:1.61.0]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[grpc-api-1.61.0.jar:1.61.0]
	at com.google.api.gax.grpc.ChannelPool$ReleasingClientCall$1.onClose(ChannelPool.java:570) ~[gax-grpc-2.39.0.jar:2.39.0]
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:489) ~[grpc-core-1.61.0.jar:1.61.0]
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:453) ~[grpc-core-1.61.0.jar:1.61.0]
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:486) ~[grpc-core-1.61.0.jar:1.61.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574) ~[grpc-core-1.61.0.jar:1.61.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72) ~[grpc-core-1.61.0.jar:1.61.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742) ~[grpc-core-1.61.0.jar:1.61.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723) ~[grpc-core-1.61.0.jar:1.61.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.61.0.jar:1.61.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[grpc-core-1.61.0.jar:1.61.0]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57) ~[gax-2.39.0.jar:2.39.0]
		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112) ~[gax-2.39.0.jar:2.39.0]
		at com.google.cloud.secretmanager.v1.SecretManagerServiceClient.accessSecretVersion(SecretManagerServiceClient.java:1668) ~[google-cloud-secretmanager-2.33.0.jar:2.33.0]
		at com.google.cloud.secretmanager.v1.SecretManagerServiceClient.accessSecretVersion(SecretManagerServiceClient.java:1598) ~[google-cloud-secretmanager-2.33.0.jar:2.33.0]
		at io.airbyte.config.secrets.persistence.GoogleSecretManagerPersistence.read(GoogleSecretManagerPersistence.kt:51) ~[io.airbyte.airbyte-config-config-secrets-0.55.1.jar:?]
		at io.airbyte.config.secrets.persistence.GoogleSecretManagerPersistence.write(GoogleSecretManagerPersistence.kt:68) ~[io.airbyte.airbyte-config-config-secrets-0.55.1.jar:?]
````

And if waiting for a while, I got a 502 error on the admin page because the server is not responding.
<img width="658" alt="image" src="https://github.com/airbytehq/airbyte/assets/22790224/e47e56e1-de18-4e37-9d97-bd29ef9e8518">

What I don't understand is that the workspace id associated with the secret I am trying to register is not unique, but `00000000-0000-0000-0000-0000-0000000000000000` . This does not seem to be normal behaviour, are there other configuration items that need to be done?

For some reason, the Salesforce source connector works fine, even though it contains sensitive information such as client secrets and refresh tokens. I have no idea what difference the different connector implementations are making.

### Relevant log output

```shell
2024-03-25 13:44:48 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.128.214 - - [25/Mar/2024:13:44:48 +0000] "GET /api/v1/health HTTP/1.0" 200 18
2024-03-25 13:44:51 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.129.65 - - [25/Mar/2024:13:44:51 +0000] "GET /api/v1/health HTTP/1.1" 200 18
2024-03-25 13:44:51 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.129.65 - - [25/Mar/2024:13:44:51 +0000] "GET /api/v1/health HTTP/1.1" 200 18
2024-03-25 13:44:59 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.128.214 - - [25/Mar/2024:13:44:59 +0000] "GET /api/v1/instance_configuration HTTP/1.0" 200 217
2024-03-25 13:44:59 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.128.214 - - [25/Mar/2024:13:44:59 +0000] "POST /api/v1/users/get HTTP/1.0" 200 204
2024-03-25 13:44:59 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.128.214 - - [25/Mar/2024:13:44:59 +0000] "POST /api/v1/workspaces/get HTTP/1.0" 200 445
2024-03-25 13:45:00 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.128.214 - - [25/Mar/2024:13:44:59 +0000] "POST /api/v1/permissions/list_by_user HTTP/1.0" 200 353
2024-03-25 13:45:00 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.128.214 - - [25/Mar/2024:13:45:00 +0000] "POST /api/v1/sources/list HTTP/1.0" 200 44757
2024-03-25 13:45:00 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.128.214 - - [25/Mar/2024:13:45:00 +0000] "POST /api/v1/sources/list HTTP/1.0" 200 44757
2024-03-25 13:45:00 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.128.214 - - [25/Mar/2024:13:45:00 +0000] "POST /api/v1/web_backend/check_updates HTTP/1.0" 200 50
2024-03-25 13:45:00 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.128.214 - - [25/Mar/2024:13:45:00 +0000] "POST /api/v1/web_backend/connections/list HTTP/1.0" 200 71980
2024-03-25 13:45:01 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.128.214 - - [25/Mar/2024:13:45:01 +0000] "POST /api/v1/workspaces/get HTTP/1.0" 200 445
2024-03-25 13:45:01 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.129.65 - - [25/Mar/2024:13:45:01 +0000] "GET /api/v1/health HTTP/1.1" 200 18
2024-03-25 13:45:01 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.129.65 - - [25/Mar/2024:13:45:01 +0000] "GET /api/v1/health HTTP/1.1" 200 18
2024-03-25 13:45:08 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.128.214 - - [25/Mar/2024:13:45:08 +0000] "GET /api/v1/health HTTP/1.0" 200 18
2024-03-25 13:45:09 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.128.214 - - [25/Mar/2024:13:45:08 +0000] "POST /api/v1/source_definitions/list_for_workspace HTTP/1.0" 200 2071216
2024-03-25 13:45:09 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.128.214 - - [25/Mar/2024:13:45:09 +0000] "POST /api/v1/destination_definitions/list_for_workspace HTTP/1.0" 200 360150
2024-03-25 13:45:11 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.129.65 - - [25/Mar/2024:13:45:11 +0000] "GET /api/v1/health HTTP/1.1" 200 18
2024-03-25 13:45:11 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.129.65 - - [25/Mar/2024:13:45:11 +0000] "GET /api/v1/health HTTP/1.1" 200 18
2024-03-25 13:45:14 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.128.214 - - [25/Mar/2024:13:45:14 +0000] "POST /api/v1/permissions/list_by_user HTTP/1.0" 200 353
2024-03-25 13:45:14 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.128.214 - - [25/Mar/2024:13:45:14 +0000] "POST /api/v1/workspaces/get HTTP/1.0" 200 445
2024-03-25 13:45:14 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.128.214 - - [25/Mar/2024:13:45:14 +0000] "POST /api/v1/source_definition_specifications/get HTTP/1.0" 200 9611
2024-03-25 13:45:14 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.128.214 - - [25/Mar/2024:13:45:14 +0000] "POST /api/v1/connector_documentation/get HTTP/1.0" 200 53956
2024-03-25 13:45:20 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.128.214 - - [25/Mar/2024:13:45:20 +0000] "GET /api/v1/health HTTP/1.0" 200 18
2024-03-25 13:45:21 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.128.214 - - [25/Mar/2024:13:45:21 +0000] "GET /api/v1/health HTTP/1.0" 200 18
2024-03-25 13:45:21 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.129.65 - - [25/Mar/2024:13:45:21 +0000] "GET /api/v1/health HTTP/1.1" 200 18
2024-03-25 13:45:21 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.129.65 - - [25/Mar/2024:13:45:21 +0000] "GET /api/v1/health HTTP/1.1" 200 18
2024-03-25 13:45:25 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.128.214 - - [25/Mar/2024:13:45:25 +0000] "POST /api/v1/web_backend/connections/list HTTP/1.0" 200 7549
2024-03-25 13:45:28 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.128.214 - - [25/Mar/2024:13:45:28 +0000] "GET /api/v1/health HTTP/1.0" 200 18
2024-03-25 13:45:31 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.129.65 - - [25/Mar/2024:13:45:31 +0000] "GET /api/v1/health HTTP/1.1" 200 18
2024-03-25 13:45:31 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.129.65 - - [25/Mar/2024:13:45:31 +0000] "GET /api/v1/health HTTP/1.1" 200 18
2024-03-25 13:45:40 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.128.214 - - [25/Mar/2024:13:45:40 +0000] "GET /api/v1/health HTTP/1.0" 200 18
2024-03-25 13:45:41 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.129.65 - - [25/Mar/2024:13:45:41 +0000] "GET /api/v1/health HTTP/1.1" 200 18
2024-03-25 13:45:41 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.129.65 - - [25/Mar/2024:13:45:41 +0000] "GET /api/v1/health HTTP/1.1" 200 18
2024-03-25 13:45:48 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.128.214 - - [25/Mar/2024:13:45:48 +0000] "GET /api/v1/health HTTP/1.0" 200 18
2024-03-25 13:45:51 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.129.65 - - [25/Mar/2024:13:45:51 +0000] "GET /api/v1/health HTTP/1.1" 200 18
2024-03-25 13:45:51 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.129.65 - - [25/Mar/2024:13:45:51 +0000] "GET /api/v1/health HTTP/1.1" 200 18
2024-03-25 13:46:00 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.128.214 - - [25/Mar/2024:13:46:00 +0000] "GET /api/v1/health HTTP/1.0" 200 18
2024-03-25 13:46:01 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.129.65 - - [25/Mar/2024:13:46:01 +0000] "GET /api/v1/health HTTP/1.1" 200 18
2024-03-25 13:46:01 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.129.65 - - [25/Mar/2024:13:46:01 +0000] "GET /api/v1/health HTTP/1.1" 200 18
2024-03-25 13:46:06 [33mWARN[m i.a.c.s.p.GoogleSecretManagerPersistence(read):55 - Unable to locate secret for coordinate airbyte_workspace_00000000-0000-0000-0000-000000000000_secret_b24af7c6-a4fd-4f1d-9bc9-c219617c3d45_v1.
com.google.api.gax.rpc.NotFoundException: io.grpc.StatusRuntimeException: NOT_FOUND: Secret [projects/75442930950/secrets/airbyte_workspace_00000000-0000-0000-0000-000000000000_secret_b24af7c6-a4fd-4f1d-9bc9-c219617c3d45_v1] not found or has no versions.
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:90) ~[gax-2.39.0.jar:2.39.0]
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:41) ~[gax-2.39.0.jar:2.39.0]
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:86) ~[gax-grpc-2.39.0.jar:2.39.0]
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:66) ~[gax-grpc-2.39.0.jar:2.39.0]
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97) ~[gax-grpc-2.39.0.jar:2.39.0]
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:84) ~[api-common-2.22.0.jar:2.22.0]
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1127) ~[guava-32.1.3-jre.jar:?]
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31) ~[guava-32.1.3-jre.jar:?]
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1286) ~[guava-32.1.3-jre.jar:?]
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1055) ~[guava-32.1.3-jre.jar:?]
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:807) ~[guava-32.1.3-jre.jar:?]
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:568) ~[grpc-stub-1.61.0.jar:1.61.0]
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:538) ~[grpc-stub-1.61.0.jar:1.61.0]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[grpc-api-1.61.0.jar:1.61.0]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[grpc-api-1.61.0.jar:1.61.0]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[grpc-api-1.61.0.jar:1.61.0]
	at com.google.api.gax.grpc.ChannelPool$ReleasingClientCall$1.onClose(ChannelPool.java:570) ~[gax-grpc-2.39.0.jar:2.39.0]
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:489) ~[grpc-core-1.61.0.jar:1.61.0]
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:453) ~[grpc-core-1.61.0.jar:1.61.0]
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:486) ~[grpc-core-1.61.0.jar:1.61.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574) ~[grpc-core-1.61.0.jar:1.61.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72) ~[grpc-core-1.61.0.jar:1.61.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742) ~[grpc-core-1.61.0.jar:1.61.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723) ~[grpc-core-1.61.0.jar:1.61.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.61.0.jar:1.61.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[grpc-core-1.61.0.jar:1.61.0]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57) ~[gax-2.39.0.jar:2.39.0]
		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112) ~[gax-2.39.0.jar:2.39.0]
		at com.google.cloud.secretmanager.v1.SecretManagerServiceClient.accessSecretVersion(SecretManagerServiceClient.java:1668) ~[google-cloud-secretmanager-2.33.0.jar:2.33.0]
		at com.google.cloud.secretmanager.v1.SecretManagerServiceClient.accessSecretVersion(SecretManagerServiceClient.java:1598) ~[google-cloud-secretmanager-2.33.0.jar:2.33.0]
		at io.airbyte.config.secrets.persistence.GoogleSecretManagerPersistence.read(GoogleSecretManagerPersistence.kt:51) ~[io.airbyte.airbyte-config-config-secrets-0.55.1.jar:?]
		at io.airbyte.config.secrets.persistence.GoogleSecretManagerPersistence.write(GoogleSecretManagerPersistence.kt:68) ~[io.airbyte.airbyte-config-config-secrets-0.55.1.jar:?]
		at io.airbyte.config.secrets.SecretsRepositoryWriter.splitSecretConfig(SecretsRepositoryWriter.kt:223) ~[io.airbyte.airbyte-config-config-secrets-0.55.1.jar:?]
		at io.airbyte.config.secrets.SecretsRepositoryWriter.statefulSplitSecretsToDefaultSecretPersistence(SecretsRepositoryWriter.kt:189) ~[io.airbyte.airbyte-config-config-secrets-0.55.1.jar:?]
		at io.airbyte.commons.server.handlers.SchedulerHandler.sanitizePartialConfig(SchedulerHandler.java:846) ~[io.airbyte-airbyte-commons-server-0.55.1.jar:?]
		at io.airbyte.commons.server.handlers.SchedulerHandler.checkSourceConnectionFromSourceCreate(SchedulerHandler.java:238) ~[io.airbyte-airbyte-commons-server-0.55.1.jar:?]
		at io.airbyte.server.apis.SchedulerApiController.lambda$executeSourceCheckConnection$1(SchedulerApiController.java:47) ~[io.airbyte-airbyte-server-0.55.1.jar:?]
		at io.airbyte.server.apis.ApiHelper.execute(ApiHelper.java:28) ~[io.airbyte-airbyte-server-0.55.1.jar:?]
		at io.airbyte.server.apis.SchedulerApiController.executeSourceCheckConnection(SchedulerApiController.java:47) ~[io.airbyte-airbyte-server-0.55.1.jar:?]
		at io.airbyte.server.apis.$SchedulerApiController$Definition$Exec.dispatch(Unknown Source) ~[io.airbyte-airbyte-server-0.55.1.jar:?]
		at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invokeUnsafe(AbstractExecutableMethodsDefinition.java:461) ~[micronaut-inject-4.3.11.jar:4.3.11]
		at io.micronaut.context.DefaultBeanContext$BeanContextUnsafeExecutionHandle.invokeUnsafe(DefaultBeanContext.java:4276) ~[micronaut-inject-4.3.11.jar:4.3.11]
		at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:271) ~[micronaut-router-4.3.11.jar:4.3.11]
		at io.micronaut.http.server.RouteExecutor.executeRouteAndConvertBody(RouteExecutor.java:488) ~[micronaut-http-server-4.3.11.jar:4.3.11]
		at io.micronaut.http.server.RouteExecutor.lambda$callRoute$6(RouteExecutor.java:465) ~[micronaut-http-server-4.3.11.jar:4.3.11]
		at io.micronaut.core.execution.ExecutionFlow.lambda$async$1(ExecutionFlow.java:87) ~[micronaut-core-4.3.11.jar:4.3.11]
		at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211) ~[micronaut-core-4.3.11.jar:4.3.11]
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
		at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: io.grpc.StatusRuntimeException: NOT_FOUND: Secret [projects/75442930950/secrets/airbyte_workspace_00000000-0000-0000-0000-000000000000_secret_b24af7c6-a4fd-4f1d-9bc9-c219617c3d45_v1] not found or has no versions.
	at io.grpc.Status.asRuntimeException(Status.java:533) ~[grpc-api-1.61.0.jar:1.61.0]
	... 17 more
2024-03-25 13:46:08 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.128.214 - - [25/Mar/2024:13:46:08 +0000] "GET /api/v1/health HTTP/1.0" 200 18
2024-03-25 13:46:11 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.129.65 - - [25/Mar/2024:13:46:11 +0000] "GET /api/v1/health HTTP/1.1" 200 18
2024-03-25 13:46:11 [32mINFO[m i.m.h.s.n.h.a.e.AccessLog(log):125 - 10.169.129.65 - - [25/Mar/2024:13:46:11 +0000] "GET /api/v1/health HTTP/1.1" 200 18
```

**Comment by marcosmarxm** [comment]
Thanks for reporting the issue @ism-k I added it to the deployment team further investigate in the next grooming session.

**Comment by marcosmarxm** [comment]
Can you share the Helm value part where you'r configuring the Secret Manager?

**Comment by ism-k** [comment]
> Can you share the Helm value part where you'r configuring the Secret Manager?

This is the helm value I set:
```
global:
  secretsManager:
    type: GOOGLE_SECRET_MANAGER
    secretsManagerSecretName: airbyte-gcs-log-creds # The json key secret is also used for storage
    googleSecretManager:
      authenticationType: credentials
      projectId: project1 # dummy
      credentialsSecretKey: "gcp.json"
```

**Comment by ism-k** [comment]
And, the Google ServiceAccount referred to in this helm value has been assigned the following four IAM roles.

```
- roles/bigquery.dataEditor
- roles/bigquery.user
- roles/secretmanager.admin
- roles/storage.admin
```

**Comment by ism-k** [comment]
As a result of another aspect of my research, I share the error behaviour when I press the [Reset saved destination] button in the "Test the destination" section of an existing bigquery destination.

This is the error returned on the connector page.
<img width="841" alt="image" src="https://github.com/airbytehq/airbyte/assets/22790224/186ce224-a6f3-4bf7-99c2-8ce8bd55e68a">

Although hidden on display, the stack trace is the following wording: `io.temporal.failure.ActivityFailure: Activity with activityType='RunWithJobOutput' failed: 'Activity task failed'. scheduledEventId=12, startedEventId=13, activityId=c00584d6-61a4-3e3d-8248-fc35f14b1579, identity='1@airbyte-worker-69bcb966c5-n9lgc', retryState=RETRY_STATE_MAXIMUM_ATTEMPTS_REACHED`

And the following error logs are then logged on the server:
```
2024-03-26 02:20:57 ERROR i.a.c.l.Exceptions(swallow):65 - Swallowed error.
java.lang.NullPointerException: Cannot invoke "io.airbyte.config.Metadata.getAdditionalProperties()" because the return value of "io.airbyte.config.FailureReason.getMetadata()" is null
	at io.airbyte.persistence.job.errorreporter.JobErrorReporter.getFailureReasonMetadata(JobErrorReporter.java:286) ~[io.airbyte.airbyte-persistence-job-persistence-0.55.1.jar:?]
	at io.airbyte.persistence.job.errorreporter.JobErrorReporter.reportJobFailureReason(JobErrorReporter.java:332) ~[io.airbyte.airbyte-persistence-job-persistence-0.55.1.jar:?]
	at io.airbyte.persistence.job.errorreporter.JobErrorReporter.reportDestinationCheckJobFailure(JobErrorReporter.java:198) ~[io.airbyte.airbyte-persistence-job-persistence-0.55.1.jar:?]
	at io.airbyte.commons.server.scheduler.DefaultSynchronousSchedulerClient.lambda$reportError$4(DefaultSynchronousSchedulerClient.java:306) ~[io.airbyte-airbyte-commons-server-0.55.1.jar:?]
	at io.airbyte.commons.lang.Exceptions.swallow(Exceptions.java:63) ~[io.airbyte-airbyte-commons-0.55.1.jar:?]
	at io.airbyte.commons.server.scheduler.DefaultSynchronousSchedulerClient.reportError(DefaultSynchronousSchedulerClient.java:299) ~[io.airbyte-airbyte-commons-server-0.55.1.jar:?]
	at io.airbyte.commons.server.scheduler.DefaultSynchronousSchedulerClient.execute(DefaultSynchronousSchedulerClient.java:241) ~[io.airbyte-airbyte-commons-server-0.55.1.jar:?]
	at io.airbyte.commons.server.scheduler.DefaultSynchronousSchedulerClient.createDestinationCheckConnectionJob(DefaultSynchronousSchedulerClient.java:153) ~[io.airbyte-airbyte-commons-server-0.55.1.jar:?]
	at io.airbyte.commons.server.handlers.SchedulerHandler.checkDestinationConnectionFromDestinationId(SchedulerHandler.java:294) ~[io.airbyte-airbyte-commons-server-0.55.1.jar:?]
	at io.airbyte.server.apis.DestinationApiController.lambda$checkConnectionToDestination$0(DestinationApiController.java:53) ~[io.airbyte-airbyte-server-0.55.1.jar:?]
	at io.airbyte.server.apis.ApiHelper.execute(ApiHelper.java:28) ~[io.airbyte-airbyte-server-0.55.1.jar:?]
	at io.airbyte.server.apis.DestinationApiController.checkConnectionToDestination(DestinationApiController.java:53) ~[io.airbyte-airbyte-server-0.55.1.jar:?]
	at io.airbyte.server.apis.$DestinationApiController$Definition$Exec.dispatch(Unknown Source) ~[io.airbyte-airbyte-server-0.55.1.jar:?]
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invokeUnsafe(AbstractExecutableMethodsDefinition.java:461) ~[micronaut-inject-4.3.11.jar:4.3.11]
	at io.micronaut.context.DefaultBeanContext$BeanContextUnsafeExecutionHandle.invokeUnsafe(DefaultBeanContext.java:4276) ~[micronaut-inject-4.3.11.jar:4.3.11]
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:271) ~[micronaut-router-4.3.11.jar:4.3.11]
	at io.micronaut.http.server.RouteExecutor.executeRouteAndConvertBody(RouteExecutor.java:488) ~[micronaut-http-server-4.3.11.jar:4.3.11]
	at io.micronaut.http.server.RouteExecutor.lambda$callRoute$6(RouteExecutor.java:465) ~[micronaut-http-server-4.3.11.jar:4.3.11]
	at io.micronaut.core.execution.ExecutionFlow.lambda$async$1(ExecutionFlow.java:87) ~[micronaut-core-4.3.11.jar:4.3.11]
	at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211) ~[micronaut-core-4.3.11.jar:4.3.11]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

Hopefully this will be of some help.

**Comment by ism-k** [comment]
We avoided using this feature in the production environment, so we missed the timing to fix/investigate the problem.
I hope it has been resolved successfully. Thank you very much!
