### ISSUE TITLE
io.airbyte.workers.exception.WorkerException: Could not find image: airbyte/source-sftp:0.2.2

### ISSUE THREAD

**Issue by kavyapothula14** [airbytehq/airbyte#36732]
### Connector Name

SFTP

### Connector Version

0.55.2

### What step the error happened?

Configuring a new connector

### Relevant information

I've deployed Airbyte locally on EC2 using Docker. While trying to create a connection using SFTP connector, I am getting the following error: Unexpected error while checking connection:
io.airbyte.workers.exception.WorkerException: Could not find image: airbyte/source-sftp:0.2.2

I have tried the same connector in cloud version and it was working fine over there .
I have attached the logs as well for more information.

### Relevant log output

```shell
2024-03-29 15:44:29 [46mplatform[0m > Docker volume job log path: /tmp/workspace/9ddd310e-e522-42dc-8bea-49812d677172/0/logs.log
2024-03-29 15:44:29 [46mplatform[0m > Executing worker wrapper. Airbyte version: 0.55.2
2024-03-29 15:44:29 [46mplatform[0m > Attempt 0 to save workflow id for cancellation
2024-03-29 15:44:29 [46mplatform[0m > Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2024-03-29 15:44:29 [46mplatform[0m > Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2024-03-29 15:44:29 [46mplatform[0m > Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2024-03-29 15:44:29 [46mplatform[0m > Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2024-03-29 15:44:29 [46mplatform[0m > 
2024-03-29 15:44:29 [46mplatform[0m > ----- START CHECK -----
2024-03-29 15:44:29 [46mplatform[0m > 
2024-03-29 15:44:29 [46mplatform[0m > Checking if airbyte/source-sftp:0.2.2 exists...
2024-03-29 15:44:29 [46mplatform[0m > airbyte/source-sftp:0.2.2 not found locally. Attempting to pull the image...
2024-03-29 15:44:33 [46mplatform[0m > Image does not exist.
2024-03-29 15:44:33 [46mplatform[0m > Unexpected error while checking connection: 
io.airbyte.workers.exception.WorkerException: Could not find image: airbyte/source-sftp:0.2.2
	at io.airbyte.workers.process.DockerProcessFactory.create(DockerProcessFactory.java:117) ~[io.airbyte-airbyte-commons-worker-0.55.2.jar:?]
	at io.airbyte.workers.process.AirbyteIntegrationLauncher.check(AirbyteIntegrationLauncher.java:149) ~[io.airbyte-airbyte-commons-worker-0.55.2.jar:?]
	at io.airbyte.workers.general.DefaultCheckConnectionWorker.run(DefaultCheckConnectionWorker.java:71) ~[io.airbyte-airbyte-commons-worker-0.55.2.jar:?]
	at io.airbyte.workers.general.DefaultCheckConnectionWorker.run(DefaultCheckConnectionWorker.java:44) ~[io.airbyte-airbyte-commons-worker-0.55.2.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:142) ~[io.airbyte-airbyte-workers-0.55.2.jar:?]
	at io.airbyte.workers.temporal.check.connection.CheckConnectionActivityImpl.lambda$runWithJobOutput$1(CheckConnectionActivityImpl.java:226) ~[io.airbyte-airbyte-workers-0.55.2.jar:?]
	at io.airbyte.commons.temporal.HeartbeatUtils.withBackgroundHeartbeat(HeartbeatUtils.java:57) ~[io.airbyte-airbyte-commons-temporal-core-0.55.2.jar:?]
	at io.airbyte.workers.temporal.check.connection.CheckConnectionActivityImpl.runWithJobOutput(CheckConnectionActivityImpl.java:211) ~[io.airbyte-airbyte-workers-0.55.2.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at io.temporal.internal.activity.RootActivityInboundCallsInterceptor$POJOActivityInboundCallsInterceptor.executeActivity(RootActivityInboundCallsInterceptor.java:64) ~[temporal-sdk-1.22.3.jar:?]
	at io.temporal.internal.activity.RootActivityInboundCallsInterceptor.execute(RootActivityInboundCallsInterceptor.java:43) ~[temporal-sdk-1.22.3.jar:?]
	at io.temporal.internal.activity.ActivityTaskExecutors$BaseActivityTaskExecutor.execute(ActivityTaskExecutors.java:107) ~[temporal-sdk-1.22.3.jar:?]
	at io.temporal.internal.activity.ActivityTaskHandlerImpl.handle(ActivityTaskHandlerImpl.java:124) ~[temporal-sdk-1.22.3.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handleActivity(ActivityWorker.java:278) ~[temporal-sdk-1.22.3.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:243) ~[temporal-sdk-1.22.3.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:216) ~[temporal-sdk-1.22.3.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:105) ~[temporal-sdk-1.22.3.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
2024-03-29 15:44:33 [46mplatform[0m > 
2024-03-29 15:44:33 [46mplatform[0m > ----- END CHECK -----
2024-03-29 15:44:33 [46mplatform[0m >
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Please check your disk space problably it is full and you can't download the image.
I'll close as the image exists. PLease report a new issue if it persists.
