### ISSUE TITLE
Discover/refresh schema issue

### ISSUE THREAD

**Issue by alexgreen496** [airbytehq/airbyte#36745]
### Platform Version

0.57.0

### What step the error happened?

Other

### Revelant information

In creating a new connection, I experience a "Discovering schema failed, Failed to run schema discovery." error.

In refreshing the source schema in an existing connection, I experience a "Internal Server Error: Cannot invoke "io.airbyte.api.model.generated.AirbyteCatalog.getStreams()" because "discovered" is null" error.

These errors are occurring with all sources I've tested:
BigQuery connector 0.4.2
Chargebee connector 0.4.1
Intercom connector 0.6.0
S3 connector 4.5.10

**Comment by alexgreen496** [comment]
In trying to run a sync, I experience a "The check connection failed because of an internal error in the scheduler used by airbyte." error.

![image](https://github.com/airbytehq/airbyte/assets/95924027/14426eb0-922f-48c4-b836-05fc10f50e1d)

**Comment by ThomasGoodvest** [comment]
Same issue here. I'm on Docker.
Migrated from 0.50.50 to 0.57.0, now all connections fail with the same message:
`The check connection failed because of an internal error in the scheduler used by airbyte.`

Is it related to the changes in 0.51.0? I couldn't find any migration documentation, and used the run-ab-platform.sh script as usual.

> **v0.51.0**
> **⚠️ 🚨 Deployment Configuration Breaking Change Alert 🚨 ⚠️**
> This update has a breaking change to Docker and Helm deployments.
> We've revamped how external logs are configured, making it much simpler.
> Be sure to watch out for upcoming migration documentation if you're considering upgrading to this version.
> Remember to verify that your deployment uses the correct variables.

https://github.com/airbytehq/airbyte/releases/tag/v0.51.0

**Comment by alexgreen496** [comment]
Yeah I suspect these are the breaking changes. I'm also looking out for the migration docs, will be sure to post a link if I find them

**Comment by ThomasGoodvest** [comment]
I just rollbacked to 0.50.50 (downloaded .env, docker-compose.yaml and flags.yml from [source](https://raw.githubusercontent.com/airbytehq/airbyte-platform/v0.50.50/.env)), everything works now again.

I'll follow this thread and look for any documentation about upgrading to v51.

**Comment by marcosmarxm** [comment]
@davinchia can the team take a look in next sprint?

**Comment by marcosmarxm** [comment]
@ThomasGoodvest @alexgreen496 I'll try to reproduce the issue locally upgrading from the same version as yours. Any more additional information you can. share please add here.

**Comment by kissifrot** [comment]
@marcosmarxm It seems we are getting permission denied errors in the worker container:
```
airbyte-worker                    | ERROR StatusConsoleListener RollingFileManager (/app/airbyte/workspace/scheduler/logs/logs.log) java.io.FileNotFoundException: /app/airbyte/workspace/scheduler/logs/logs.log (Permission denied)
airbyte-worker                    |  java.io.FileNotFoundException: /app/airbyte/workspace/scheduler/logs/logs.log (Permission denied)
airbyte-worker                    |     at java.base/java.io.FileOutputStream.open0(Native Method)
airbyte-worker                    |     at java.base/java.io.FileOutputStream.open(FileOutputStream.java:289)
airbyte-worker                    |     at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:230)
airbyte-worker                    |     at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:150)
airbyte-worker                    |     at org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory.createManager(RollingFileManager.java:878)
airbyte-worker                    |     at org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory.createManager(RollingFileManager.java:844)
airbyte-worker                    |     at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:146)
airbyte-worker                    |     at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:112)
airbyte-worker                    |     at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.getFileManager(RollingFileManager.java:307)
airbyte-worker                    |     at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:144)
airbyte-worker                    |     at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:65)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:124)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1162)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1083)
airbyte-worker                    |     at org.apache.logging.log4j.core.appender.routing.RoutingAppender.createAppender(RoutingAppender.java:323)
airbyte-worker                    |     at org.apache.logging.log4j.core.appender.routing.RoutingAppender.getControl(RoutingAppender.java:295)
airbyte-worker                    |     at org.apache.logging.log4j.core.appender.routing.RoutingAppender.append(RoutingAppender.java:253)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:160)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:133)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:124)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:88)
airbyte-worker                    |     at org.apache.logging.log4j.core.appender.rewrite.RewriteAppender.append(RewriteAppender.java:89)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:160)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:133)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:124)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:88)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:705)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:663)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:639)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:575)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:92)
airbyte-worker                    |     at org.apache.logging.log4j.core.Logger.log(Logger.java:169)
airbyte-worker                    |     at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2933)
airbyte-worker                    |     at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2886)
airbyte-worker                    |     at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2868)
airbyte-worker                    |     at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2652)
airbyte-worker                    |     at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:2400)
airbyte-worker                    |     at org.apache.logging.slf4j.Log4jLogger.info(Log4jLogger.java:179)
airbyte-worker                    |     at io.airbyte.commons.temporal.TemporalUtils.configureTemporalNamespace(TemporalUtils.java:122)
airbyte-worker                    |     at io.airbyte.workers.ApplicationInitializer.configureTemporal(ApplicationInitializer.java:326)
airbyte-worker                    |     at io.airbyte.workers.ApplicationInitializer.initializeCommonDependencies(ApplicationInitializer.java:179)
airbyte-worker                    |     at io.airbyte.workers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:145)
airbyte-worker                    |     at io.airbyte.workers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:57)
airbyte-worker                    |     at io.micronaut.context.event.ApplicationEventPublisherFactory.notifyEventListeners(ApplicationEventPublisherFactory.java:266)
airbyte-worker                    |     at io.micronaut.context.event.ApplicationEventPublisherFactory$2.publishEvent(ApplicationEventPublisherFactory.java:226)
airbyte-worker                    |     at io.micronaut.http.server.netty.discovery.NettyServiceDiscovery.onStart(NettyServiceDiscovery.java:54)
airbyte-worker                    |     at io.micronaut.http.server.netty.discovery.$NettyServiceDiscovery$Definition$Exec.dispatch(Unknown Source)
airbyte-worker                    |     at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:456)
airbyte-worker                    |     at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:3903)
airbyte-worker                    |     at io.micronaut.aop.chain.AdapterIntroduction.intercept(AdapterIntroduction.java:84)
airbyte-worker                    |     at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:138)
airbyte-worker                    |     at io.micronaut.http.server.netty.discovery.NettyServiceDiscovery$ApplicationEventListener$onStart1$Intercepted.onApplicationEvent(Unknown Source)
airbyte-worker                    |     at io.micronaut.context.event.ApplicationEventPublisherFactory.notifyEventListeners(ApplicationEventPublisherFactory.java:266)
airbyte-worker                    |     at io.micronaut.context.event.ApplicationEventPublisherFactory$2.publishEvent(ApplicationEventPublisherFactory.java:226)
airbyte-worker                    |     at io.micronaut.http.server.netty.NettyHttpServer.fireStartupEvents(NettyHttpServer.java:638)
airbyte-worker                    |     at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:309)
airbyte-worker                    |     at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:109)
airbyte-worker                    |     at io.micronaut.runtime.Micronaut.start(Micronaut.java:80)
airbyte-worker                    |     at io.micronaut.runtime.Micronaut.run(Micronaut.java:328)
airbyte-worker                    |     at io.micronaut.runtime.Micronaut.run(Micronaut.java:314)
airbyte-worker                    |     at io.airbyte.workers.Application.main(Application.java:15)
airbyte-worker                    | ERROR StatusConsoleListener Could not create plugin of type class org.apache.logging.log4j.core.appender.RollingFileAppender for element RollingFile: java.lang.IllegalStateException: ManagerFactory [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory@4136b193] unable to create manager for [/app/airbyte/workspace/scheduler/logs/logs.log] with data [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$FactoryData@1adf387e[pattern=/app/airbyte/workspace/scheduler/logs/logs.%i.log.gz, append=true, bufferedIO=true, bufferSize=8192, policy=CompositeTriggeringPolicy(policies=[SizeBasedTriggeringPolicy(size=104857600)]), strategy=DefaultRolloverStrategy(min=1, max=3, useMax=true), advertiseURI=null, layout=%d{yyyy-MM-dd HH:mm:ss}{GMT+0} %highlight{%p} %C{1.}(%M):%L - %replace{%m}{apikey=[\w\-]*}{apikey=*****}%n, filePermissions=null, fileOwner=null]]
airbyte-worker                    |  java.lang.IllegalStateException: ManagerFactory [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory@4136b193] unable to create manager for [/app/airbyte/workspace/scheduler/logs/logs.log] with data [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$FactoryData@1adf387e[pattern=/app/airbyte/workspace/scheduler/logs/logs.%i.log.gz, append=true, bufferedIO=true, bufferSize=8192, policy=CompositeTriggeringPolicy(policies=[SizeBasedTriggeringPolicy(size=104857600)]), strategy=DefaultRolloverStrategy(min=1, max=3, useMax=true), advertiseURI=null, layout=%d{yyyy-MM-dd HH:mm:ss}{GMT+0} %highlight{%p} %C{1.}(%M):%L - %replace{%m}{apikey=[\w\-]*}{apikey=*****}%n, filePermissions=null, fileOwner=null]]
airbyte-worker                    |     at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:148)
airbyte-worker                    |     at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:112)
airbyte-worker                    |     at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.getFileManager(RollingFileManager.java:307)
airbyte-worker                    |     at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:144)
airbyte-worker                    |     at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:65)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:124)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1162)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1083)
airbyte-worker                    |     at org.apache.logging.log4j.core.appender.routing.RoutingAppender.createAppender(RoutingAppender.java:323)
airbyte-worker                    |     at org.apache.logging.log4j.core.appender.routing.RoutingAppender.getControl(RoutingAppender.java:295)
airbyte-worker                    |     at org.apache.logging.log4j.core.appender.routing.RoutingAppender.append(RoutingAppender.java:253)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:160)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:133)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:124)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:88)
airbyte-worker                    |     at org.apache.logging.log4j.core.appender.rewrite.RewriteAppender.append(RewriteAppender.java:89)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:160)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:133)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:124)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:88)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:705)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:663)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:639)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:575)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:92)
airbyte-worker                    |     at org.apache.logging.log4j.core.Logger.log(Logger.java:169)
airbyte-worker                    |     at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2933)
airbyte-worker                    |     at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2886)
airbyte-worker                    |     at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2868)
airbyte-worker                    |     at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2652)
airbyte-worker                    |     at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:2400)
airbyte-worker                    |     at org.apache.logging.slf4j.Log4jLogger.info(Log4jLogger.java:179)
airbyte-worker                    |     at io.airbyte.commons.temporal.TemporalUtils.configureTemporalNamespace(TemporalUtils.java:122)
airbyte-worker                    |     at io.airbyte.workers.ApplicationInitializer.configureTemporal(ApplicationInitializer.java:326)
airbyte-worker                    |     at io.airbyte.workers.ApplicationInitializer.initializeCommonDependencies(ApplicationInitializer.java:179)
airbyte-worker                    |     at io.airbyte.workers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:145)
airbyte-worker                    |     at io.airbyte.workers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:57)
airbyte-worker                    |     at io.micronaut.context.event.ApplicationEventPublisherFactory.notifyEventListeners(ApplicationEventPublisherFactory.java:266)
airbyte-worker                    |     at io.micronaut.context.event.ApplicationEventPublisherFactory$2.publishEvent(ApplicationEventPublisherFactory.java:226)
airbyte-worker                    |     at io.micronaut.http.server.netty.discovery.NettyServiceDiscovery.onStart(NettyServiceDiscovery.java:54)
airbyte-worker                    |     at io.micronaut.http.server.netty.discovery.$NettyServiceDiscovery$Definition$Exec.dispatch(Unknown Source)
airbyte-worker                    |     at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:456)
airbyte-worker                    |     at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:3903)
airbyte-worker                    |     at io.micronaut.aop.chain.AdapterIntroduction.intercept(AdapterIntroduction.java:84)
airbyte-worker                    |     at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:138)
airbyte-worker                    |     at io.micronaut.http.server.netty.discovery.NettyServiceDiscovery$ApplicationEventListener$onStart1$Intercepted.onApplicationEvent(Unknown Source)
airbyte-worker                    |     at io.micronaut.context.event.ApplicationEventPublisherFactory.notifyEventListeners(ApplicationEventPublisherFactory.java:266)
airbyte-worker                    |     at io.micronaut.context.event.ApplicationEventPublisherFactory$2.publishEvent(ApplicationEventPublisherFactory.java:226)
airbyte-worker                    |     at io.micronaut.http.server.netty.NettyHttpServer.fireStartupEvents(NettyHttpServer.java:638)
airbyte-worker                    |     at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:309)
airbyte-worker                    |     at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:109)
airbyte-worker                    |     at io.micronaut.runtime.Micronaut.start(Micronaut.java:80)
airbyte-worker                    |     at io.micronaut.runtime.Micronaut.run(Micronaut.java:328)
airbyte-worker                    |     at io.micronaut.runtime.Micronaut.run(Micronaut.java:314)
airbyte-worker                    |     at io.airbyte.workers.Application.main(Application.java:15)
airbyte-worker                    | ERROR StatusConsoleListener Unable to invoke factory method in class org.apache.logging.log4j.core.appender.RollingFileAppender for element RollingFile: java.lang.IllegalStateException: No factory method found for class org.apache.logging.log4j.core.appender.RollingFileAppender
airbyte-worker                    |  java.lang.IllegalStateException: No factory method found for class org.apache.logging.log4j.core.appender.RollingFileAppender
airbyte-worker                    |     at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.findFactoryMethod(PluginBuilder.java:268)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:140)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1162)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1083)
airbyte-worker                    |     at org.apache.logging.log4j.core.appender.routing.RoutingAppender.createAppender(RoutingAppender.java:323)
airbyte-worker                    |     at org.apache.logging.log4j.core.appender.routing.RoutingAppender.getControl(RoutingAppender.java:295)
airbyte-worker                    |     at org.apache.logging.log4j.core.appender.routing.RoutingAppender.append(RoutingAppender.java:253)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:160)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:133)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:124)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:88)
airbyte-worker                    |     at org.apache.logging.log4j.core.appender.rewrite.RewriteAppender.append(RewriteAppender.java:89)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:160)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:133)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:124)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:88)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:705)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:663)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:639)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:575)
airbyte-worker                    |     at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:92)
airbyte-worker                    |     at org.apache.logging.log4j.core.Logger.log(Logger.java:169)
airbyte-worker                    |     at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2933)
airbyte-worker                    |     at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2886)
airbyte-worker                    |     at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2868)
airbyte-worker                    |     at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2652)
airbyte-worker                    |     at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:2400)
airbyte-worker                    |     at org.apache.logging.slf4j.Log4jLogger.info(Log4jLogger.java:179)
airbyte-worker                    |     at io.airbyte.commons.temporal.TemporalUtils.configureTemporalNamespace(TemporalUtils.java:122)
airbyte-worker                    |     at io.airbyte.workers.ApplicationInitializer.configureTemporal(ApplicationInitializer.java:326)
airbyte-worker                    |     at io.airbyte.workers.ApplicationInitializer.initializeCommonDependencies(ApplicationInitializer.java:179)
airbyte-worker                    |     at io.airbyte.workers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:145)
airbyte-worker                    |     at io.airbyte.workers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:57)
airbyte-worker                    |     at io.micronaut.context.event.ApplicationEventPublisherFactory.notifyEventListeners(ApplicationEventPublisherFactory.java:266)
airbyte-worker                    |     at io.micronaut.context.event.ApplicationEventPublisherFactory$2.publishEvent(ApplicationEventPublisherFactory.java:226)
airbyte-worker                    |     at io.micronaut.http.server.netty.discovery.NettyServiceDiscovery.onStart(NettyServiceDiscovery.java:54)
airbyte-worker                    |     at io.micronaut.http.server.netty.discovery.$NettyServiceDiscovery$Definition$Exec.dispatch(Unknown Source)
airbyte-worker                    |     at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:456)
airbyte-worker                    |     at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:3903)
airbyte-worker                    |     at io.micronaut.aop.chain.AdapterIntroduction.intercept(AdapterIntroduction.java:84)
airbyte-worker                    |     at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:138)
airbyte-worker                    |     at io.micronaut.http.server.netty.discovery.NettyServiceDiscovery$ApplicationEventListener$onStart1$Intercepted.onApplicationEvent(Unknown Source)
airbyte-worker                    |     at io.micronaut.context.event.ApplicationEventPublisherFactory.notifyEventListeners(ApplicationEventPublisherFactory.java:266)
airbyte-worker                    |     at io.micronaut.context.event.ApplicationEventPublisherFactory$2.publishEvent(ApplicationEventPublisherFactory.java:226)
airbyte-worker                    |     at io.micronaut.http.server.netty.NettyHttpServer.fireStartupEvents(NettyHttpServer.java:638)
airbyte-worker                    |     at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:309)
airbyte-worker                    |     at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:109)
airbyte-worker                    |     at io.micronaut.runtime.Micronaut.start(Micronaut.java:80)
airbyte-worker                    |     at io.micronaut.runtime.Micronaut.run(Micronaut.java:328)
airbyte-worker                    |     at io.micronaut.runtime.Micronaut.run(Micronaut.java:314)
airbyte-worker                    |     at io.airbyte.workers.Application.main(Application.java:15)
airbyte-worker                    | ERROR StatusConsoleListener Unable to create Appender of type RollingFile
```

**Comment by perangel** [comment]
Hey @alexgreen496 there was a recent breaking change that is the cause of this, the resolution is described in the March release notes. 

https://docs.airbyte.com/release_notes/march_2024

```
A breaking change to Docker deployments. Containers no longer run as the root user. If you are upgrading from an older version, the `airbyte_workspace` docker volume must be recreated to fix the ownership of staging directories under /tmp (in the container). Alternatively, you can manually update the ownership (airbyte:airbyte) of the directory mount point /tmp/workspace in all containers where airbyte_workspace is mounted (see: docker-compose.yaml)
```

**Comment by kissifrot** [comment]
Removing old `airbyte_workspace` volume did the trick, thanks @perangel for pointing this :+1:
