### ISSUE TITLE
[source-monday] All syncing failing with `KeyError: 'data'`

### ISSUE THREAD

**Issue by deanmorin** [airbytehq/airbyte#36741]
### Connector Name

source-monday

### Connector Version

2.0.4

### What step the error happened?

During the sync

### Relevant information

This was syncing as expected on March 26. However, on March 30 (the next time it ran), the sync started failing with:

KeyError: 'data'

There were some pending schema changes, which I applied and did a full re-sync, but the issue persists.

### Relevant log output

```shell
2024-04-01 22:48:57 source > Encountered an exception while reading stream items
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 126, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 203, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 263, in _read_full_refresh
    for record_data_or_message in stream_instance.read_full_refresh(configured_stream.cursor_field, logger, self._slice_logger):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/core.py", line 121, in read_full_refresh
    yield from self.read_records(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py", line 104, in read_records
    yield from self.retriever.read_records(self.get_json_schema(), stream_slice)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 323, in read_records
    for stream_data in self._read_pages(record_generator, self.state, stream_slice):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 293, in _read_pages
    next_page_token = self._next_page_token(response)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 257, in _next_page_token
    return self._paginator.next_page_token(response, self._records_from_last_response)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/requesters/paginators/default_paginator.py", line 105, in next_page_token
    self._token = self.pagination_strategy.next_page_token(response, last_records)
  File "/airbyte/integration_code/source_monday/item_pagination_strategy.py", line 84, in next_page_token
    data = response.json()["data"]
KeyError: 'data'
2024-04-01 22:48:57 source > Marking stream items as STOPPED
2024-04-01 22:48:57 source > Finished syncing items
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
@deanmorin this was solved by #36717 please try the latest version of Monday connector.
