### ISSUE TITLE
sync not working 

### ISSUE THREAD

**Issue by xpert-chat** [airbytehq/airbyte#36786]
### Platform Version

.57.0

### What step the error happened?

During the Sync

### Revelant information

Unable to sync against shopify, says connector missing - but dont know why

![image](https://github.com/airbytehq/airbyte/assets/59007177/346c1d85-935d-4bc9-9665-d76b827a6a10)

### Relevant log output

```shell
2024-04-03 13:40:44 platform > Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2024-04-03 13:40:44 platform > Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2024-04-03 13:40:44 platform > 
2024-04-03 13:40:44 platform > ----- START CHECK -----
2024-04-03 13:40:44 platform > 
2024-04-03 13:40:44 platform > Checking if airbyte/source-shopify:2.0.1 exists...
2024-04-03 13:40:44 platform > airbyte/source-shopify:2.0.1 not found locally. Attempting to pull the image...
2024-04-03 13:40:44 platform > Image does not exist.
2024-04-03 13:40:44 platform > Unexpected error while checking connection: 
io.airbyte.workers.exception.WorkerException: Could not find image: airbyte/source-shopify:2.0.1
        at io.airbyte.workers.process.DockerProcessFactory.create(DockerProcessFactory.java:117) ~[io.airbyte-airbyte-commons-worker-0.57.0.jar:?]
        at io.airbyte.workers.process.AirbyteIntegrationLauncher.check(AirbyteIntegrationLauncher.java:149) ~[io.airbyte-airbyte-commons-worker-0.57.0.jar:?]
        at io.airbyte.workers.general.DefaultCheckConnectionWorker.run(DefaultCheckConnectionWorker.java:71) ~[io.airbyte-airbyte-commons-worker-0.57.0.jar:?]
        at io.airbyte.workers.general.DefaultCheckConnectionWorker.run(DefaultCheckConnectionWorker.java:44) ~[io.airbyte-airbyte-commons-worker-0.57.0.jar:?]
        at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:142) ~[io.airbyte-airbyte-workers-0.57.0.jar:?]
        at io.airbyte.workers.temporal.check.connection.CheckConnectionActivityImpl.lambda$runWithJobOutput$1(CheckConnectionActivityImpl.java:226) ~[io.airbyte-airbyte-workers-0.57.0.jar:?]
        at io.airbyte.commons.temporal.HeartbeatUtils.withBackgroundHeartbeat(HeartbeatUtils.java:57) ~[io.airbyte-airbyte-commons-temporal-core-0.57.0.jar:?]
        at io.airbyte.workers.temporal.check.connection.CheckConnectionActivityImpl.runWithJobOutput(CheckConnectionActivityImpl.java:211) ~[io.airbyte-airbyte-workers-0.57.0.jar:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at io.temporal.internal.activity.RootActivityInboundCallsInterceptor$POJOActivityInboundCallsInterceptor.executeActivity(RootActivityInboundCallsInterceptor.java:64) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.activity.RootActivityInboundCallsInterceptor.execute(RootActivityInboundCallsInterceptor.java:43) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.activity.ActivityTaskExecutors$BaseActivityTaskExecutor.execute(ActivityTaskExecutors.java:107) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.activity.ActivityTaskHandlerImpl.handle(ActivityTaskHandlerImpl.java:124) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handleActivity(ActivityWorker.java:278) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:243) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:216) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:105) ~[temporal-sdk-1.22.3.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
2024-04-03 13:40:44 platform > 
2024-04-03 13:40:44 platform > ----- END CHECK -----
2024-04-03 13:40:44 platform > 
2024-04-03 13:40:45 platform > Retry State: RetryManager(completeFailureBackoffPolicy=BackoffPolicy(minInterval=PT10S, maxInterval=PT30M, base=3), partialFailureBackoffPolicy=null, successiveCompleteFailureLimit=5, totalCompleteFailureLimit=10, successivePartialFailureLimit=1000, totalPartialFailureLimit=10, successiveCompleteFailures=5, totalCompleteFailures=5, successivePartialFailures=0, totalPartialFailures=0)
 Backoff before next attempt: 13 minutes 30 seconds
2024-04-03 13:40:45 platform > Failing job: 7, reason: Job failed after too many retries for connection 70bd3d92-b134-4d82-be14-94b5332826a7
```

**Comment by natikgadzhi** [comment]
Hey there. The source image [is there on Dockerhub](https://hub.docker.com/layers/airbyte/source-shopify/2.0.4/images/sha256-2b96df08070c9dcfb79727979a3662d75f3a14b3f3802883a3a9c2abf0d67723?context=explore).

I'd assume you're running Airbyte OSS? Slack might be better help with this, tbh.

**Comment by marcosmarxm** [comment]
@xpert-chat can you check if your disk isn't full? I saw this problem happening before and it was because the server could download the image.

**Comment by xpert-chat** [comment]
disk isnt full. this error starts showing up after i clicked on upgrade all for my connectors in the settings.
Even the space is available :

![image](https://github.com/airbytehq/airbyte/assets/59007177/b393ddd4-100c-41b1-9dfe-6a2a72cccdee)

**Comment by xpert-chat** [comment]
this is the log error now when runing a job :
[default_workspace_job_17_attempt_2_txt.txt](https://github.com/airbytehq/airbyte/files/14965531/default_workspace_job_17_attempt_2_txt.txt)

this is the earlier log for the same connection when running normally - before the ;upgrade all connectors was pressed.


[default_workspace_logs_16_txt.txt](https://github.com/airbytehq/airbyte/files/14965534/default_workspace_logs_16_txt.txt)

**Comment by xpert-chat** [comment]
i followed the upgrade insttructions - to reinstall airbyte and now its up and running - but am certain this error would be recreated on clicking on upgrading all in the source connectors

**Comment by natikgadzhi** [comment]
It _really_ shouldn't, and it doesn't seem to be common. Ping us if it does.
