### ISSUE TITLE
[API] patch custom source fails with NullPointerException

### ISSUE THREAD

**Issue by dmvianna** [airbytehq/airbyte#36916]
### Platform Version

0.57.2

### What step the error happened?

Other

### Revelant information

I have a source that was created via the no-code builder. It works seamlessly. However when I try to `PATCH` the connection to change a parameter, i.e.,
```sh
curl -X PATCH "http://localhost:8007/v1/sources/56293d69-38ec-48fc-9ac0-034653751ebe" -H "Accept: application/json"  -H "Content-Type: application/json" -d '{"job_id": "changed"}'
```
I get an unhelpful response in return
```json
{"type":"about:blank","status":500}
```

I also noticed that naked `GET`s, which are supposed to return the full list of items available at an endpoint, also return  `500`
```sh
curl -X GET "http://localhost:8007/v1/connections" -H "Accept: application/json"  -H "Content-Type: application/json"  
```
response:
```json
{"type":"about:blank","status":500}
```
A request with a key, though, returns just fine
```sh
curl -X GET "http://localhost:8007/v1/connections/82aadca5-354b-40d9-8b93-61c3cfc16516" -H "Accept: application/json"  -H "Content-Type: application/json"  
```
response
```json
{"connectionId":"82aadca5-354b-40d9-8b93-61c3cfc16516","name":"test → test","sourceId":"56293d69-38ec-48fc-9ac0-034653751ebe","destinationId":"b94de289-5518-4b61-ade7-87ac9c0de178","workspaceId":"8d7dd39a-f792-44be-b53d-2de143dca5f6","status":"active","schedule":{"scheduleType":"manual"},"dataResidency":"auto","nonBreakingSchemaUpdatesBehavior":"propagate_fully","namespaceDefinition":"custom_format","namespaceFormat":"test","prefix":"test_","configurations":{"streams":[{"name":"tests","syncMode":"full_refresh_overwrite"},{"name":"tests-by-location","syncMode":"full_refresh_overwrite"}]}}
```

### Relevant log output

```shell
Apr 09 01:41:10 ingestion airbyte-start.sh[78263]: airbyte-api-server                | 2024-04-09 01:41:10 INFO i.a.a.s.n.LoggingNettyChannelHandler(channelRead):38 - [PATCH] /v1/sources/56293d69-38ec-48fc-9ac0-034653751ebe
Apr 09 01:41:10 ingestion airbyte-start.sh[78263]: airbyte-api-server                | 2024-04-09 01:41:10 ERROR i.m.h.s.RouteExecutor(logException):282 - Unexpected error occurred: null cannot be cast to non-null type com.fasterxml.jackson.databind.node.ObjectNode
Apr 09 01:41:10 ingestion airbyte-start.sh[78263]: airbyte-api-server                | java.lang.NullPointerException: null cannot be cast to non-null type com.fasterxml.jackson.databind.node.ObjectNode
Apr 09 01:41:10 ingestion airbyte-start.sh[78263]: airbyte-api-server                |         at io.airbyte.api.server.helpers.ActorConfigurationHelperKt.removeConfigurationNode(ActorConfigurationHelper.kt:26) ~[io.airbyte-airbyte-api-server-0.57.2.jar:?]
Apr 09 01:41:10 ingestion airbyte-start.sh[78263]: airbyte-api-server                |         at io.airbyte.api.server.helpers.ActorConfigurationHelperKt.removeSourceTypeNode(ActorConfigurationHelper.kt:19) ~[io.airbyte-airbyte-api-server-0.57.2.jar:?]
Apr 09 01:41:10 ingestion airbyte-start.sh[78263]: airbyte-api-server                |         at io.airbyte.api.server.controllers.SourcesController.patchSource(SourcesController.kt:210) ~[io.airbyte-airbyte-api-server-0.57.2.jar:?]
Apr 09 01:41:10 ingestion airbyte-start.sh[78263]: airbyte-api-server                |         at io.airbyte.api.server.controllers.$SourcesController$Definition$Exec.dispatch(Unknown Source) ~[io.airbyte-airbyte-api-server-0.57.2.jar:?]
Apr 09 01:41:10 ingestion airbyte-start.sh[78263]: airbyte-api-server                |         at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invokeUnsafe(AbstractExecutableMethodsDefinition.java:461) ~[micronaut-inject-4.3.12.jar:4.3.12]
Apr 09 01:41:10 ingestion airbyte-start.sh[78263]: airbyte-api-server                |         at io.micronaut.context.DefaultBeanContext$BeanContextUnsafeExecutionHandle.invokeUnsafe(DefaultBeanContext.java:4276) ~[micronaut-inject-4.3.12.jar:4.3.12]
Apr 09 01:41:10 ingestion airbyte-start.sh[78263]: airbyte-api-server                |         at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:271) ~[micronaut-router-4.3.12.jar:4.3.12]
Apr 09 01:41:10 ingestion airbyte-start.sh[78263]: airbyte-api-server                |         at io.micronaut.http.server.RouteExecutor.executeRouteAndConvertBody(RouteExecutor.java:488) ~[micronaut-http-server-4.3.12.jar:4.3.12]
Apr 09 01:41:10 ingestion airbyte-start.sh[78263]: airbyte-api-server                |         at io.micronaut.http.server.RouteExecutor.lambda$callRoute$6(RouteExecutor.java:465) ~[micronaut-http-server-4.3.12.jar:4.3.12]
Apr 09 01:41:10 ingestion airbyte-start.sh[78263]: airbyte-api-server                |         at io.micronaut.core.execution.ExecutionFlow.lambda$async$1(ExecutionFlow.java:87) ~[micronaut-core-4.3.12.jar:4.3.12]
Apr 09 01:41:10 ingestion airbyte-start.sh[78263]: airbyte-api-server                |         at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211) ~[micronaut-core-4.3.12.jar:4.3.12]
Apr 09 01:41:10 ingestion airbyte-start.sh[78263]: airbyte-api-server                |         at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211) ~[micronaut-core-4.3.12.jar:4.3.12]
Apr 09 01:41:10 ingestion airbyte-start.sh[78263]: airbyte-api-server                |         at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314) ~[?:?]
Apr 09 01:41:10 ingestion airbyte-start.sh[78263]: airbyte-api-server                |         at java.base/java.lang.VirtualThread.run(VirtualThread.java:309) ~[?:?]
Apr 09 01:41:10 ingestion airbyte-start.sh[78263]: airbyte-api-server                | 2024-04-09 01:41:10 INFO i.a.a.s.n.LoggingNettyChannelHandler(capture):88 - Request: [fee0ee0e-76b3-4b99-903d-a5c32b85ce3f] -- {"headers":{"host":["localhost"],"x-real-ip":["172.18.0.1"],"x-forwarded-for":["172.18.0.1"],"connection":["close"],"content-length":["24"],"mime-version":["1.0"],"accept-encoding":["gzip"],"accept":["application\/json"],"content-type":["application\/json"],"x-airbyte-request-id":["fee0ee0e-76b3-4b99-903d-a5c32b85ce3f"]},"requestURI":"\/v1\/sources\/56293d69-38ec-48fc-9ac0-034653751ebe","bodyText":"{ \"job_id\": \"changed\" }\n","queryString":"","method":"PATCH"}
Apr 09 01:41:10 ingestion airbyte-start.sh[78263]: airbyte-api-server                | 2024-04-09 01:41:10 INFO i.a.a.s.n.LoggingNettyChannelHandler(capture):89 - Response: [fee0ee0e-76b3-4b99-903d-a5c32b85ce3f] -- {"headers":{"content-type":["application\/problem+json"],"date":["Tue, 9 Apr 2024 01:41:10 GMT"],"content-length":["35"]},"status":500,"bodyText":"{\"type\":\"about:blank\",\"status\":500}"}
Apr 09 01:41:10 ingestion airbyte-start.sh[78263]: airbyte-proxy                     | 172.18.0.1 - - [09/Apr/2024:01:41:10 +0000] "PATCH /v1/sources/56293d69-38ec-48fc-9ac0-034653751ebe HTTP/1.1" 500 35 "-" "-"
Apr 09 01:41:10 ingestion airbyte-start.sh[78263]: airbyte-api-server                | 2024-04-09 01:41:10 INFO i.m.h.s.n.h.a.e.AccessLog(log):125 - airbyte-proxy.airbyte_airbyte_internal - - [09/Apr/2024:01:41:10 +0000] "PATCH /v1/sources/56293d69-38ec-48fc-9ac0-034653751ebe HTTP/1.0" 500 35
```

**Comment by marcosmarxm** [comment]
Thanks @dmvianna to confirm you're using https://reference.airbyte.com/reference/patchsource endpoint, correct?

**Comment by dmvianna** [comment]
Correct.

**Comment by dermasmid** [comment]
solution here: https://github.com/airbytehq/airbyte/discussions/35116#discussioncomment-8569228

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by kev-datams** [comment]
@dmvianna did you check for proposed solution by @dermasmid ? 🙏

**Comment by dmvianna** [comment]
No, sorry. I got shuffled into other tasks. Will probably come back to this sometime in 2025, no estimate when though.

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 180 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by kev-datams** [comment]
@dmvianna did you check for proposed solution by @dermasmid ? 🙏

**Comment by pasunboneleve** [comment]
No, and won't check. We now use the **helm**-packaged **Airbyte** release and it suits our needs.
