### ISSUE TITLE
[helm/kubernetes] No bean of type [org.jooq.DSLContext] exists for the given qualifier: @Named('local-secrets')

### ISSUE THREAD

**Issue by rohitvarma01** [airbytehq/airbyte#37316]
### Helm Chart Version

0.56.50

### What step the error happened?

Upgrading the Platform or Helm Chart

### Revelant information

**Older Airbyte version: 50.7
New Airbyte Version : 0.53.1
Deployement using Helm on EKS**

I am getting below error in WebApp  pod while upgrading airbyte

Logs:
Unsetting empty environment variable 'VERSION'
INFO StatusConsoleListener Loading mask data from '/seed/specs_secrets_mask.yaml

    ___    _      __          __
   /   |  (_)____/ /_  __  __/ /____
  / /| | / / ___/ __ \/ / / / __/ _ \
 / ___ |/ / /  / /_/ / /_/ / /_/  __/
/_/  |_/_/_/  /_.___/\__, /\__/\___/
                    /____/
        : airbyte-workers :

2024-04-15 08:42:23 [32mINFO[m i.m.c.e.DefaultEnvironment(<init>):168 - Established active environments: [k8s, cloud]
2024-04-15 08:42:23 [32mINFO[m i.m.l.PropertiesLoggingLevelsConfigurer(configureLogLevelForPrefix):113 - Setting log level 'DEBUG' for logger: 'io.airbyte.bootloader'
2024-04-15 08:42:24 [32mINFO[m i.a.f.ConfigFileClient(<init>):105 - path /flags does not exist, will return default flag values
2024-04-15 08:42:24 [1;31mERROR[m i.m.r.Micronaut(handleStartupException):343 - Error starting Micronaut server: Failed to inject value for parameter [dslContext] of class: io.airbyte.config.secrets.persistence.$LocalTestingSecretPersistence$Definition$Intercepted

Message: No bean of type [org.jooq.DSLContext] exists for the given qualifier: @Named('local-secrets').
* [DSLContext] requires the presence of a bean of type [org.jooq.Configuration] with qualifier [@Named('local-secrets')].
 * [Configuration] requires the presence of a bean of type [io.r2dbc.spi.ConnectionFactory] with qualifier [@Named('local-secrets')].
 * [Configuration] requires the presence of a bean of type [javax.sql.DataSource] with qualifier [@Named('local-secrets')].
  * [DataSource] requires the presence of a bean of type [io.micronaut.configuration.jdbc.hikari.DatasourceConfiguration] with qualifier [@Named('local-secrets')].
   * [DatasourceConfiguration] is disabled because:
    - Configuration requires entries under the prefix: [datasources.local-secrets]
Path Taken: new ApplicationInitializer() --> ApplicationInitializer.checkConnectionActivities --> ActivityBeanFactory.checkConnectionActivities([CheckConnectionActivity checkConnectionActivity]) --> new CheckConnectionActivityImpl(WorkerConfigsProvider workerConfigsProvider,ProcessFactory processFactory,[SecretsRepositoryReader secretsRepositoryReader],Path workspaceRoot,WorkerEnvironment workerEnvironment,LogConfigs logConfigs,AirbyteApiClient airbyteApiClient,String airbyteVersion,AirbyteMessageSerDeProvider serDeProvider,AirbyteProtocolVersionedMigratorFactory migratorFactory,FeatureFlags featureFlags,FeatureFlagClient featureFlagClient,GsonPksExtractor gsonPksExtractor,WorkloadApi workloadApi,WorkloadIdGenerator workloadIdGenerator,JobOutputDocStore jobOutputDocStore,MetricClient metricClient) --> new SecretsRepositoryReader([SecretsHydrator secretsHydrator]) --> new RealSecretsHydrator([SecretPersistence secretPersistence]) --> new $LocalTestingSecretPersistence$Definition$Intercepted([DSLContext dslContext],BeanResolutionContext $beanResolutionContext,BeanContext $beanContext,Qualifier $qualifier,List $interceptors,InterceptorRegistry $interceptorRegistry)
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [dslContext] of class: io.airbyte.config.secrets.persistence.$LocalTestingSecretPersistence$Definition$Intercepted

Message: No bean of type [org.jooq.DSLContext] exists for the given qualifier: @Named('local-secrets').
* [DSLContext] requires the presence of a bean of type [org.jooq.Configuration] with qualifier [@Named('local-secrets')].
 * [Configuration] requires the presence of a bean of type [io.r2dbc.spi.ConnectionFactory] with qualifier [@Named('local-secrets')].
 * [Configuration] requires the presence of a bean of type [javax.sql.DataSource] with qualifier [@Named('local-secrets')].
  * [DataSource] requires the presence of a bean of type [io.micronaut.configuration.jdbc.hikari.DatasourceConfiguration] with qualifier [@Named('local-secrets')].
   * [DatasourceConfiguration] is disabled because:
    - Configuration requires entries under the prefix: [datasources.local-secrets]
Path Taken: new ApplicationInitializer() --> ApplicationInitializer.checkConnectionActivities --> ActivityBeanFactory.checkConnectionActivities([CheckConnectionActivity checkConnectionActivity]) --> new CheckConnectionActivityImpl(WorkerConfigsProvider workerConfigsProvider,ProcessFactory processFactory,[SecretsRepositoryReader secretsRepositoryReader],Path workspaceRoot,WorkerEnvironment workerEnvironment,LogConfigs logConfigs,AirbyteApiClient airbyteApiClient,String airbyteVersion,AirbyteMessageSerDeProvider serDeProvider,AirbyteProtocolVersionedMigratorFactory migratorFactory,FeatureFlags featureFlags,FeatureFlagClient featureFlagClient,GsonPksExtractor gsonPksExtractor,WorkloadApi workloadApi,WorkloadIdGenerator workloadIdGenerator,JobOutputDocStore jobOutputDocStore,MetricClient metricClient) --> new SecretsRepositoryReader([SecretsHydrator secretsHydrator]) --> new RealSecretsHydrator([SecretPersistence secretPersistence]) --> new $LocalTestingSecretPersistence$Definition$Intercepted([DSLContext dslContext],BeanResolutionContext $beanResolutionContext,BeanContext $beanContext,Qualifier $qualifier,List $interceptors,InterceptorRegistry $interceptorRegistry)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2181) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1328) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.airbyte.config.secrets.persistence.$LocalTestingSecretPersistence$Definition$Intercepted$Definition.instantiate(Unknown Source) ~[io.airbyte.airbyte-config-config-secrets-0.53.1.jar:?]
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2332) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2302) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2314) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3116) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3018) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2979) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2753) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1752) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:89) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2165) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1328) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.airbyte.config.secrets.hydration.$RealSecretsHydrator$Definition.instantiate(Unknown Source) ~[io.airbyte.airbyte-config-config-secrets-0.53.1.jar:?]
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2332) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2302) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2314) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3116) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3018) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2979) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2753) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1752) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:89) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2165) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1328) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.airbyte.config.secrets.$SecretsRepositoryReader$Definition.instantiate(Unknown Source) ~[io.airbyte.airbyte-config-config-secrets-0.53.1.jar:?]
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2332) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2302) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2314) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3116) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3018) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2979) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2753) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1752) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:89) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2165) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1328) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.airbyte.workers.temporal.check.connection.$CheckConnectionActivityImpl$Definition.instantiate(Unknown Source) ~[io.airbyte-airbyte-workers-0.53.1.jar:?]
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2332) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2302) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2314) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3116) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3018) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2979) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2753) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1752) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:89) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2165) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1328) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.airbyte.workers.config.$ActivityBeanFactory$CheckConnectionActivities0$Definition.instantiate(Unknown Source) ~[io.airbyte-airbyte-workers-0.53.1.jar:?]
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2332) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2302) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2314) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3116) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3018) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2979) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2753) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1815) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.AbstractBeanResolutionContext.findBean(AbstractBeanResolutionContext.java:112) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveOptionalBean(AbstractInitializableBeanDefinition.java:2309) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.AbstractInitializableBeanDefinition.findBeanForField(AbstractInitializableBeanDefinition.java:1908) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.airbyte.workers.$ApplicationInitializer$Definition.inject(Unknown Source) ~[io.airbyte-airbyte-workers-0.53.1.jar:?]
	at io.airbyte.workers.$ApplicationInitializer$Definition.instantiate(Unknown Source) ~[io.airbyte-airbyte-workers-0.53.1.jar:?]
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2332) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2302) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2314) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3116) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3018) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2979) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2953) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:3568) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistrations(DefaultBeanContext.java:3516) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:3486) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:1453) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:899) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:889) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.event.ApplicationEventPublisherFactory$2.lambda$$1(ApplicationEventPublisherFactory.java:215) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.core.util.SupplierUtil$1.get(SupplierUtil.java:47) ~[micronaut-core-4.3.10.jar:4.3.10]
	at io.micronaut.context.event.ApplicationEventPublisherFactory$2.publishEvent(ApplicationEventPublisherFactory.java:226) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.http.server.netty.discovery.NettyServiceDiscovery.onStart(NettyServiceDiscovery.java:54) ~[micronaut-http-server-netty-4.3.10.jar:4.3.10]
	at io.micronaut.http.server.netty.discovery.$NettyServiceDiscovery$Definition$Exec.dispatch(Unknown Source) ~[micronaut-http-server-netty-4.3.10.jar:4.3.10]
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:456) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:3903) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.aop.chain.AdapterIntroduction.intercept(AdapterIntroduction.java:84) ~[micronaut-aop-4.3.10.jar:4.3.10]
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:138) ~[micronaut-aop-4.3.10.jar:4.3.10]
	at io.micronaut.http.server.netty.discovery.NettyServiceDiscovery$ApplicationEventListener$onStart1$Intercepted.onApplicationEvent(Unknown Source) ~[micronaut-http-server-netty-4.3.10.jar:4.3.10]
	at io.micronaut.context.event.ApplicationEventPublisherFactory.notifyEventListeners(ApplicationEventPublisherFactory.java:266) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.event.ApplicationEventPublisherFactory$2.publishEvent(ApplicationEventPublisherFactory.java:226) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.http.server.netty.NettyHttpServer.fireStartupEvents(NettyHttpServer.java:638) ~[micronaut-http-server-netty-4.3.10.jar:4.3.10]
	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:309) ~[micronaut-http-server-netty-4.3.10.jar:4.3.10]
	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:109) ~[micronaut-http-server-netty-4.3.10.jar:4.3.10]
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:80) [micronaut-context-4.3.10.jar:4.3.10]
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:328) [micronaut-context-4.3.10.jar:4.3.10]
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:314) [micronaut-context-4.3.10.jar:4.3.10]
	at io.airbyte.workers.Application.main(Application.java:15) [io.airbyte-airbyte-workers-0.53.1.jar:?]
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [org.jooq.DSLContext] exists for the given qualifier: @Named('local-secrets').
* [DSLContext] requires the presence of a bean of type [org.jooq.Configuration] with qualifier [@Named('local-secrets')].
 * [Configuration] requires the presence of a bean of type [io.r2dbc.spi.ConnectionFactory] with qualifier [@Named('local-secrets')].
 * [Configuration] requires the presence of a bean of type [javax.sql.DataSource] with qualifier [@Named('local-secrets')].
  * [DataSource] requires the presence of a bean of type [io.micronaut.configuration.jdbc.hikari.DatasourceConfiguration] with qualifier [@Named('local-secrets')].
   * [DatasourceConfiguration] is disabled because:
    - Configuration requires entries under the prefix: [datasources.local-secrets]
	at io.micronaut.context.DefaultBeanContext.newNoSuchBeanException(DefaultBeanContext.java:2789) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultApplicationContext.newNoSuchBeanException(DefaultApplicationContext.java:309) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2758) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1752) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:89) ~[micronaut-inject-4.3.10.jar:4.3.10]
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2165) ~[micronaut-inject-4.3.10.jar:4.3.10]
	... 101 more
	
	
Please help me to resolve the issue.

**Comment by marcosmarxm** [comment]
@rohitvarma01 are you upgrading to the latest version of Airbyte or to a specific one? It wasn't sure in the issue.

**Comment by marcosmarxm** [comment]
Closed as unanswered.
