### ISSUE TITLE
[source-salesforce] process exited with non-zero exit code 137

### ISSUE THREAD

**Issue by jiangjef** [airbytehq/airbyte#37368]
### Connector Name

source-salesforce

### Connector Version

2.5.2

### What step the error happened?

None

### Relevant information

We hit the error ` Source process exited with non-zero exit code 137` when pulling a particular schema out of Salesforce. There is no error for other schemas.

```
2024-04-17 02:30:33 platform > Workload 16ec58e2-4d17-409a-aa1c-5e8e72d24a5e_10587463_2_sync is running
2024-04-17 02:31:03 platform > Workload 16ec58e2-4d17-409a-aa1c-5e8e72d24a5e_10587463_2_sync has returned a terminal status of failure.  Fetching output...
2024-04-17 02:31:03 platform > Replication output for workload 16ec58e2-4d17-409a-aa1c-5e8e72d24a5e_10587463_2_sync : io.airbyte.config.ReplicationOutput@641bcc06[replicationAttemptSummary=io.airbyte.config.ReplicationAttemptSummary@4f7a292d[status=failed,recordsSynced=0,bytesSynced=0,startTime=1713320943793,endTime=1713321041009,totalStats=io.airbyte.config.SyncStats@445f0030[bytesCommitted=0,bytesEmitted=29476885,destinationStateMessagesEmitted=0,destinationWriteEndTime=1713321040995,destinationWriteStartTime=1713320943812,estimatedBytes=<null>,estimatedRecords=<null>,meanSecondsBeforeSourceStateMessageEmitted=0,maxSecondsBeforeSourceStateMessageEmitted=0,maxSecondsBetweenStateMessageEmittedandCommitted=0,meanSecondsBetweenStateMessageEmittedandCommitted=0,recordsEmitted=999,recordsCommitted=0,replicationEndTime=1713321041002,replicationStartTime=1713320943793,sourceReadEndTime=0,sourceReadStartTime=1713320943813,sourceStateMessagesEmitted=0,additionalProperties={}],streamStats=[io.airbyte.config.StreamSyncStats@2dfd9da8[streamName=EmailMessage,streamNamespace=<null>,stats=io.airbyte.config.SyncStats@173c1fed[bytesCommitted=0,bytesEmitted=29476885,destinationStateMessagesEmitted=<null>,destinationWriteEndTime=<null>,destinationWriteStartTime=<null>,estimatedBytes=<null>,estimatedRecords=<null>,meanSecondsBeforeSourceStateMessageEmitted=<null>,maxSecondsBeforeSourceStateMessageEmitted=<null>,maxSecondsBetweenStateMessageEmittedandCommitted=<null>,meanSecondsBetweenStateMessageEmittedandCommitted=<null>,recordsEmitted=999,recordsCommitted=0,replicationEndTime=<null>,replicationStartTime=<null>,sourceReadEndTime=<null>,sourceReadStartTime=<null>,sourceStateMessagesEmitted=<null>,additionalProperties={}],wasBackfilled=<null>,additionalProperties={}]],performanceMetrics=io.airbyte.config.PerformanceMetrics@9917f66[additionalProperties={processFromSource={elapsedTimeInNanos=1567380299, executionCount=1001, avgExecTimeInNanos=1565814.4845154844}, readFromSource={elapsedTimeInNanos=80493177350, executionCount=46848, avgExecTimeInNanos=1718177.4536799863}, processFromDest={elapsedTimeInNanos=0, executionCount=0, avgExecTimeInNanos=NaN}, writeToDest={elapsedTimeInNanos=2070542515, executionCount=999, avgExecTimeInNanos=2072615.13013013}, readFromDest={elapsedTimeInNanos=91285899386, executionCount=120675, avgExecTimeInNanos=756460.7365734411}}],additionalProperties={}],state=<null>,outputCatalog=io.airbyte.protocol.models.ConfiguredAirbyteCatalog@35f3a0e4[streams=[io.airbyte.protocol.models.ConfiguredAirbyteStream@74226b2f[stream=io.airbyte.protocol.models.AirbyteStream@396c131[name=EmailMessage,jsonSchema={"type":"object","$schema":"http://json-schema.org/draft-07/schema#","properties":{"Id":{"type":["string","null"]},"Name":{"type":["string","null"]},"Status":{"type":["string","null"]},"Headers":{"type":["string","null"]},"Subject":{"type":["string","null"]},"FromName":{"type":["string","null"]},"HtmlBody":{"type":["string","null"]},"Incoming":{"type":["boolean","null"]},"IsOpened":{"type":["boolean","null"]},"ParentId":{"type":["string","null"]},"TextBody":{"type":["string","null"]},"CcAddress":{"type":["string","null"]},"IsBounced":{"type":["boolean","null"]},"IsDeleted":{"type":["boolean","null"]},"IsTracked":{"type":["boolean","null"]},"ToAddress":{"type":["string","null"]},"ActivityId":{"type":["string","null"]},"BccAddress":{"type":["string","null"]},"CreatedById":{"type":["string","null"]},"CreatedDate":{"type":["string","null"],"format":"date-time"},"FromAddress":{"type":["string","null"]},"MessageDate":{"type":["string","null"],"format":"date-time"},"RelatedToId":{"type":["string","null"]},"HasAttachment":{"type":["boolean","null"]},"IsPrivateDraft":{"type":["boolean","null"]},"LastOpenedDate":{"type":["string","null"],"format":"date-time"},"SystemModstamp":{"type":["string","null"],"format":"date-time"},"EmailTemplateId":{"type":["string","null"]},"FirstOpenedDate":{"type":["string","null"],"format":"date-time"},"IsClientManaged":{"type":["boolean","null"]},"LastModifiedById":{"type":["string","null"]},"LastModifiedDate":{"type":["string","null"],"format":"date-time"},"ThreadIdentifier":{"type":["string","null"]},"MessageIdentifier":{"type":["string","null"]},"IsExternallyVisible":{"type":["boolean","null"]},"ValidatedFromAddress":{"type":["string","null"]},"ReplyToEmailMessageId":{"type":["string","null"]},"ClientThreadIdentifier":{"type":["string","null"]}},"additionalProperties":true},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[SystemModstamp],sourceDefinedPrimaryKey=[[Id]],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[SystemModstamp],destinationSyncMode=overwrite,primaryKey=[[Id]],generationId=<null>,minimumGenerationId=<null>,syncId=<null>,additionalProperties={}]],additionalProperties={}],failures=[io.airbyte.config.FailureReason@17ef46a[failureOrigin=source,failureType=<null>,internalMessage=Source process exited with non-zero exit code 137,externalMessage=Something went wrong within the source connector,metadata=io.airbyte.config.Metadata@29228021[additionalProperties={attemptNumber=2, jobId=10587463, connector_command=read}],stacktrace=io.airbyte.workers.internal.exception.SourceException: Source process exited with non-zero exit code 137
        at io.airbyte.workers.general.BufferedReplicationWorker.readFromSource(BufferedReplicationWorker.java:378)
        at io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsyncWithHeartbeatCheck$3(BufferedReplicationWorker.java:242)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Is this happening to all syncs or some of them?
Anything in particular change or it is a new sync?

**Comment by jiangjef** [comment]
@marcosmarxm  it is one particular schema of a new sync. It fails every time for that schema. other schemas work fine.

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 180 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
