### ISSUE TITLE
Case Issue for MS SQL by Normalized tabular data

### ISSUE THREAD

**Issue by xiaoxiao11200** [airbytehq/airbyte#37567]
### Platform Version

0.51.0

### What step the error happened?

During the Sync

### Relevant information

error log: ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name '[DBname].information_schema.tables'. (208) (SQLExecDirectW)")

 Destination Database: SQL SERVER
Database Collation: SQL_Latin1_General_CP1_CS_AS

I believe that the database's collation is case sensitive, and table should be 'INFOMATION_SCHEMA'.
But I don't know how to fix it, because the migration SQL is generated automatically.

could you fix it?

### Relevant log output

```shell
2024-04-25 05:57:21 normalization > Found 4 models, 0 tests, 0 snapshots, 0 analyses, 621 macros, 0 operations, 0 seed files, 1 source, 0 exposures, 0 metrics
2024-04-25 05:57:22 platform > Terminating normalization process...
2024-04-25 05:57:22 platform > Normalization failed for job 72.
io.airbyte.workers.exception.WorkerException: Normalization process did not terminate normally (exit code: 2)
	at io.airbyte.workers.normalization.DefaultNormalizationRunner.close(DefaultNormalizationRunner.java:186) ~[io.airbyte-airbyte-commons-worker-0.51.0.jar:?]
	at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:89) ~[io.airbyte-airbyte-commons-worker-0.51.0.jar:?]
	at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:38) ~[io.airbyte-airbyte-commons-worker-0.51.0.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:142) ~[io.airbyte-airbyte-workers-0.51.0.jar:?]
	at io.airbyte.workers.temporal.sync.NormalizationActivityImpl.lambda$normalize$2(NormalizationActivityImpl.java:194) ~[io.airbyte-airbyte-workers-0.51.0.jar:?]
	at io.airbyte.commons.temporal.HeartbeatUtils.withBackgroundHeartbeat(HeartbeatUtils.java:57) ~[io.airbyte-airbyte-commons-temporal-core-0.51.0.jar:?]
	at io.airbyte.workers.temporal.sync.NormalizationActivityImpl.normalize(NormalizationActivityImpl.java:144) ~[io.airbyte-airbyte-workers-0.51.0.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at io.temporal.internal.activity.RootActivityInboundCallsInterceptor$POJOActivityInboundCallsInterceptor.executeActivity(RootActivityInboundCallsInterceptor.java:64) ~[temporal-sdk-1.22.3.jar:?]
	at io.temporal.internal.activity.RootActivityInboundCallsInterceptor.execute(RootActivityInboundCallsInterceptor.java:43) ~[temporal-sdk-1.22.3.jar:?]
	at io.temporal.internal.activity.ActivityTaskExecutors$BaseActivityTaskExecutor.execute(ActivityTaskExecutors.java:107) ~[temporal-sdk-1.22.3.jar:?]
	at io.temporal.internal.activity.ActivityTaskHandlerImpl.handle(ActivityTaskHandlerImpl.java:124) ~[temporal-sdk-1.22.3.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handleActivity(ActivityWorker.java:278) ~[temporal-sdk-1.22.3.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:243) ~[temporal-sdk-1.22.3.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:216) ~[temporal-sdk-1.22.3.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:105) ~[temporal-sdk-1.22.3.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
2024-04-25 05:57:22 platform > Normalization executed in 26 seconds for job 72.
2024-04-25 05:57:22 platform > Normalization summary: io.airbyte.config.NormalizationSummary@52f39fee[startTime=1714024615371,endTime=1714024642062,failures=[io.airbyte.config.FailureReason@2209464f[failureOrigin=normalization,failureType=system_error,internalMessage=('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'mip1.information_schema.tables'. (208) (SQLExecDirectW)"),externalMessage=Normalization failed during the dbt run. This may indicate a problem with the data itself.,metadata=io.airbyte.config.Metadata@2ae9cfe8[additionalProperties={attemptNumber=2, jobId=72, from_trace_message=true}],stacktrace=AirbyteDbtError: 
Encountered an error:
Database Error
  ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'mip1.information_schema.tables'. (208) (SQLExecDirectW)"),retryable=<null>,timestamp=1714024642054,additionalProperties={}], io.airbyte.config.FailureReason@3499fadb[failureOrigin=normalization,failureType=system_error,internalMessage=('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'mip1.information_schema.tables'. (208) (SQLExecDirectW)"),externalMessage=Normalization failed during the dbt run. This may indicate a problem with the data itself.,metadata=io.airbyte.config.Metadata@7a5b0f49[additionalProperties={attemptNumber=2, jobId=72, from_trace_message=true}],stacktrace=AirbyteDbtError: 
Encountered an error:
Database Error
  ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'mip1.information_schema.tables'. (208) (SQLExecDirectW)"),retryable=<null>,timestamp=1714024642054,additionalProperties={}]],additionalProperties={}]
2024-04-25 05:57:22 platform > 
2024-04-25 05:57:22 platform > ----- END DEFAULT NORMALIZATION -----
2024-04-25 05:57:22 platform > 
2024-04-25 05:57:22 platform > Retry State: RetryManager(completeFailureBackoffPolicy=BackoffPolicy(minInterval=PT10S, maxInterval=PT30M, base=3), partialFailureBackoffPolicy=null, successiveCompleteFailureLimit=5, totalCompleteFailureLimit=10, successivePartialFailureLimit=1000, totalPartialFailureLimit=10, successiveCompleteFailures=2, totalCompleteFailures=2, successivePartialFailures=0, totalPartialFailures=1)
 Backoff before next attempt: 30 seconds
```

**Comment by marcosmarxm** [comment]
This is a connector issue. Please report using the correct template.
