### ISSUE TITLE
Consistently support UTF8 encoding in Postgres Source

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#376]
## Expected Behavior
I expect the Postgresql Source to be able to read UTF8 encoded strings without exception. 

## Current Behavior
Currently, the PostgresQL Source supports whatever the default `client_encodign` is for the database being read from. This means that if the `client_encoding` is set to something other than UTF8 but the db contains UTF8 data being replicated an exception will be thrown. An example stacktrace that occurs when reading from : 

```
CRITICAL 'ascii' codec can't decode byte 0xe2 in position 17: ordinal not in range(128)
Traceback (most recent call last):
  File "./bin/tap-postgres", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/singer/tap-postgres/lib/python3.7/site-packages/tap_postgres/__init__.py", line 711, in main
    raise exc
  File "/usr/local/lib/singer/tap-postgres/lib/python3.7/site-packages/tap_postgres/__init__.py", line 708, in main
    main_impl()
  File "/usr/local/lib/singer/tap-postgres/lib/python3.7/site-packages/tap_postgres/__init__.py", line 702, in main_impl
    do_sync(conn_config, args.properties, args.config.get('default_replication_method'), state)
  File "/usr/local/lib/singer/tap-postgres/lib/python3.7/site-packages/tap_postgres/__init__.py", line 669, in do_sync
    state = sync_traditional_stream(conn_config, stream, state, sync_method_lookup[stream['tap_stream_id']], end_lsn)
  File "/usr/local/lib/singer/tap-postgres/lib/python3.7/site-packages/tap_postgres/__init__.py", line 555, in sync_traditional_stream
    state = do_sync_full_table(conn_config, stream, state, desired_columns, md_map)
  File "/usr/local/lib/singer/tap-postgres/lib/python3.7/site-packages/tap_postgres/__init__.py", line 452, in do_sync_full_table
    state = full_table.sync_table(conn_config, stream, state, desired_columns, md_map)
  File "/usr/local/lib/singer/tap-postgres/lib/python3.7/site-packages/tap_postgres/sync_strategies/full_table.py", line 142, in sync_table
    for rec in cur:
  File "/usr/local/lib/singer/tap-postgres/lib/python3.7/site-packages/psycopg2/extras.py", line 121, in __iter__
    yield next(res)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 17: ordinal not in range(128)
```

## Steps to Reproduce
1. Run Airbyte via docker-compose etc... 
2. Run the following: create a file called `initdb.sql` with the following contents: 
```
mkdir /tmp/configs
echo "CREATE TABLE id_and_name( id INTEGER, name VARCHAR(200) ); INSERT INTO id_and_name(id,name)VALUES(1,'\u2013');" > /tmp/configs/initdb.sql
docker pull postgres
 docker run -i --rm postgres cat /usr/share/postgresql/postgresql.conf.sample | sed -E 's/#client_encoding = sql_ascii/client_encoding = sql_ascii/g' > /tmp/configs/postgresql.conf
docker run -v /tmp/configs:/docker-entrypoint-initdb.d -v "/tmp/configs/postgresql.conf":/etc/postgresql/postgresql.conf -e POSTGRES_PASSWORD=pg -p 5432:5432 postgres -c 'config_file=/etc/postgresql/postgresql.conf'
```
to start a postgres DB with some unicode chars

Then in the Airbyte UI setup this DB as a source with the following creds: 
```
host: localhost
port:5432
password:pg
username:postgres
database:postgres
```

3. Choose any destination, then run a sync. You'll notice the sync has failed. 

4. Look in the server logs to find the stacktrace above. 

## Severity of the bug for you
Low - if a database has UTF8 data it's likely that it's already configured to default clients to UTF8 encodings. 

## Additional Context
This happens because the Postgres Singer tap defaults to whatever the encoding specified by the DB is. See the source [code snippet](https://github.com/singer-io/tap-postgres/blob/master/tap_postgres/sync_strategies/full_table.py#L101).

**Comment by sherifnada** [comment]
Steps to reproduce are not quite correct yet, fixing them
