### ISSUE TITLE
AWS Aurora MySQL CDC failed on normalization

### ISSUE THREAD

**Issue by tuanchris** [airbytehq/airbyte#3804]
## Expected Behavior
Cdc should run normally using `Incremental - Append` strategy

## Current Behavior
Pipeline failed with error Bad bool value: 1. The same table runs successfully using `Full refresh - overwrite`. 

## Logs
```
2021-06-02 07:55:51 INFO (/tmp/workspace/2/0) TemporalAttemptExecution(get):111 - Executing worker wrapper. Airbyte version: 0.24.4-alpha
2021-06-02 07:55:51 INFO (/tmp/workspace/2/0) DefaultNormalizationWorker(run):61 - Running normalization.
2021-06-02 07:55:51 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 - Checking if airbyte/normalization:0.1.30 exists...
2021-06-02 07:55:51 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 - airbyte/normalization:0.1.30 was found locally.
2021-06-02 07:55:51 INFO (/tmp/workspace/2/0) DockerProcessFactory(create):111 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/2/0/normalize --network host airbyte/normalization:0.1.30 run --integration-type bigquery --config destination_config.json --catalog destination_catalog.json
2021-06-02 07:55:51 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 - Running: transform-config --config destination_config.json --integration-type bigquery --out /data/2/0/normalize
2021-06-02 07:55:51 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 - Namespace(config='destination_config.json', integration_type=<DestinationType.bigquery: 'bigquery'>, out='/data/2/0/normalize')
2021-06-02 07:55:51 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 - transform_bigquery
2021-06-02 07:55:51 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 - Running: transform-catalog --integration-type bigquery --profile-config-dir /data/2/0/normalize --catalog destination_catalog.json --out /data/2/0/normalize/models/generated/ --json-column _airbyte_data
2021-06-02 07:55:52 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 - Processing destination_catalog.json...
2021-06-02 07:55:52 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 - Generating airbyte_ctes/***/Profile_ab1_6fe.sql from Profile
2021-06-02 07:55:52 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 - Generating airbyte_ctes/***/Profile_ab2_6fe.sql from Profile
2021-06-02 07:55:52 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 - Generating airbyte_ctes/***/Profile_ab3_6fe.sql from Profile
2021-06-02 07:55:52 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 - Generating airbyte_tables/***/Profile_64b.sql from Profile
2021-06-02 07:55:54 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 - Running with dbt=0.19.1
2021-06-02 07:55:55 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 - [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
2021-06-02 07:55:55 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 - There are 1 unused configuration paths:
2021-06-02 07:55:55 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 - - models.airbyte_utils.generated.airbyte_views
2021-06-02 07:55:55 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 -
2021-06-02 07:55:55 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 - Found 4 models, 0 tests, 0 snapshots, 0 analyses, 382 macros, 0 operations, 0 seed files, 1 source, 0 exposures
2021-06-02 07:55:55 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 -
2021-06-02 07:55:56 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 - 07:55:56 | Concurrency: 32 threads (target='prod')
2021-06-02 07:55:56 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 - 07:55:56 |
2021-06-02 07:55:56 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 - 07:55:56 | 1 of 1 START table model ***.Profile........................................................ [RUN]
2021-06-02 07:55:59 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 - 07:55:59 | 1 of 1 ERROR creating table model * **.Profile............................................... [[31mERROR[0m in 3.14s]
2021-06-02 07:55:59 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 - 07:55:59 |
2021-06-02 07:55:59 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 - 07:55:59 | Finished running 1 table model in 4.12s.
2021-06-02 07:55:59 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 -
2021-06-02 07:55:59 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 - [31mCompleted with 1 error and 0 warnings:[0m
2021-06-02 07:55:59 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 -
2021-06-02 07:55:59 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 - [33mDatabase Error in model Profile_64b (models/generated/airbyte_tables/***/Profile_64b.sql)[0m
2021-06-02 07:55:59 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 - Bad bool value: 1
2021-06-02 07:55:59 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 - compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/***/Profile_64b.sql
2021-06-02 07:55:59 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 -
2021-06-02 07:55:59 INFO (/tmp/workspace/2/0) LineGobbler(voidCall):69 - Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
2021-06-02 07:56:00 INFO (/tmp/workspace/2/0) TemporalAttemptExecution(lambda$getWorkerThread$2):150 - Completing future exceptionally...
io.airbyte.workers.WorkerException: Normalization Failed.
at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:68) ~[io.airbyte-airbyte-workers-0.24.4-alpha.jar:?]
at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:36) ~[io.airbyte-airbyte-workers-0.24.4-alpha.jar:?]
at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:147) [io.airbyte-airbyte-workers-0.24.4-alpha.jar:?]
at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: io.airbyte.workers.WorkerException: Normalization Failed.
at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:65) ~[io.airbyte-airbyte-workers-0.24.4-alpha.jar:?]
... 3 more
Suppressed: io.airbyte.workers.WorkerException: Normalization process wasn't successful
at io.airbyte.workers.normalization.DefaultNormalizationRunner.close(DefaultNormalizationRunner.java:115) ~[io.airbyte-airbyte-workers-0.24.4-alpha.jar:?]
at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:60) ~[io.airbyte-airbyte-workers-0.24.4-alpha.jar:?]
at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:36) ~[io.airbyte-airbyte-workers-0.24.4-alpha.jar:?]
at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:147) [io.airbyte-airbyte-workers-0.24.4-alpha.jar:?]
at java.lang.Thread.run(Thread.java:832) [?:?]
2021-06-02 07:56:00 INFO (/tmp/workspace/2/0) TemporalAttemptExecution(get):134 - Stopping cancellation check scheduling...
2021-06-02 07:56:00 WARN (/tmp/workspace/2/0) POJOActivityTaskHandler$POJOActivityImplementation(execute):243 - Activity failure. ActivityId=82768206-b78f-31a2-8068-c5e4e470a4df, activityType=Normalize, attempt=1
java.util.concurrent.ExecutionException: io.airbyte.workers.WorkerException: Normalization Failed.
at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[?:?]
at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2063) ~[?:?]
at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:132) ~[io.airbyte-airbyte-workers-0.24.4-alpha.jar:?]
at io.airbyte.workers.temporal.SyncWorkflow$NormalizationActivityImpl.normalize(SyncWorkflow.java:326) ~[io.airbyte-airbyte-workers-0.24.4-alpha.jar:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityInboundCallsInterceptor.execute(POJOActivityTaskHandler.java:277) ~[temporal-sdk-1.0.4.jar:?]
at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityImplementation.execute(POJOActivityTaskHandler.java:216) [temporal-sdk-1.0.4.jar:?]
at io.temporal.internal.sync.POJOActivityTaskHandler.handle(POJOActivityTaskHandler.java:181) [temporal-sdk-1.0.4.jar:?]
at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:192) [temporal-sdk-1.0.4.jar:?]
at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:154) [temporal-sdk-1.0.4.jar:?]
at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73) [temporal-sdk-1.0.4.jar:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: io.airbyte.workers.WorkerException: Normalization Failed.
at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:68) ~[io.airbyte-airbyte-workers-0.24.4-alpha.jar:?]
at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:36) ~[io.airbyte-airbyte-workers-0.24.4-alpha.jar:?]
at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:147) ~[io.airbyte-airbyte-workers-0.24.4-alpha.jar:?]
... 1 more
Caused by: io.airbyte.workers.WorkerException: Normalization Failed.
at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:65) ~[io.airbyte-airbyte-workers-0.24.4-alpha.jar:?]
at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:36) ~[io.airbyte-airbyte-workers-0.24.4-alpha.jar:?]
at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:147) ~[io.airbyte-airbyte-workers-0.24.4-alpha.jar:?]
... 1 more
Suppressed: io.airbyte.workers.WorkerException: Normalization process wasn't successful
at io.airbyte.workers.normalization.DefaultNormalizationRunner.close(DefaultNormalizationRunner.java:115) ~[io.airbyte-airbyte-workers-0.24.4-alpha.jar:?]
at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:60) ~[io.airbyte-airbyte-workers-0.24.4-alpha.jar:?]
at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:36) ~[io.airbyte-airbyte-workers-0.24.4-alpha.jar:?]
at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:147) ~[io.airbyte-airbyte-workers-0.24.4-alpha.jar:?]
at java.lang.Thread.run(Thread.java:832) [?:?]
```

## Steps to Reproduce
1. 
1. 
1. 

## Severity of the bug for you
High

## Airbyte Version
0.24.4-alpha

## Connector Version (if applicable)
0.3.3

## Additional context
_Environment, version, integration..._

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200414508065897) by [Unito](https://www.unito.io)

**Comment by ChristopheDuong** [comment]
@subodh1810, do you think we could change how CDC outputs the boolean values? 
We should not rely on implicit conversions of `1` to `true` as this may not behave consistently on the destinations?

**Comment by subodh1810** [comment]
@ChristopheDuong I think this is a known problem with MySQL debezium https://debezium.io/documentation/reference/connectors/mysql.html#mysql-boolean-values

We can instruct debezium to handle TINYINT as boolean

**Comment by subodh1810** [comment]
Another report 
```
2021-06-02 16:42:18 INFO (/tmp/workspace/34/1) LineGobbler(voidCall):69 -   100037 (22018): Boolean value '5' is not recognized
```

[logs-34-1.txt](https://github.com/airbytehq/airbyte/files/6586321/logs-34-1.txt)

**Comment by subodh1810** [comment]
@tuanchris can you share the schema of the table from mysql?

**Comment by tuanchris** [comment]
@subodh1810 This is the column at fault here: 
![image](https://user-images.githubusercontent.com/52090179/120770954-e7128580-c548-11eb-9988-5589e4b4bedc.png)

**Comment by subodh1810** [comment]
Thought so! Just wanted to confirm that a TinyINT(1) is at fault
