### ISSUE TITLE
Source Zendesk: “ERROR …. Sync worker failed.Error while Syncing [Failure Origin: Unknown, Message: Unknown]

### ISSUE THREAD

**Issue by nsateesh135** [airbytehq/airbyte#38112]
### Connector Name

source-zendesk_support

### Connector Version

0.1.11

### What step the error happened?

During the sync

### Relevant information

[source-name] : Zendesk Support
[destination-name] : BigQuery
[Sync Mode] : Incremental |Append
[Stream Name]: tickets
[Cursor Filed] : generated_timestamp

The Zendesk Support connector is working fine for other streams except tickets. 

There seems to be a Python module error which is prevalent post May2nd,2024 (Logs would indicate this)
 

### Relevant log output

```shell
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 116, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 107, in run
    for message in generator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 112, in read
    raise e
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 108, in read
    internal_config=internal_config,
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 141, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 185, in _read_incremental
    for record_counter, record_data in enumerate(records, start=1):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 352, in read_records
    response = self._send_request(request, request_kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 319, in _send_request
    return backoff_handler(user_backoff_handler)(request, request_kwargs)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 282, in _send
    raise DefaultBackoffException(request=request, response=response)
airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException
```

### Contribute

- [X] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
The issue reports a problem using an old version of the connector. The latest version now is (2.6.3) and this can be already be fixed. Please update to the latest version (2.6.3). If the issue continues, report a new issue.
