### ISSUE TITLE
Sources all failing after docker upgrade to v0.59.1

### ISSUE THREAD

**Issue by dtiesling** [airbytehq/airbyte#38133]
### Platform Version

v0.59.1

### What step the error happened?

Upgrading the Platform or Helm Chart

### Relevant information

Seems to be having trouble creating tmp directories after the upgrade.

### Relevant log output

```shell
Caused by: io.temporal.failure.ApplicationFailure: message='/tmp/workspace/76ebf7cd-02d9-4447-b29f-c882953546ec/0', type='io.airbyte.workers.exception.WorkerException', nonRetryable=false
	at io.airbyte.workers.process.DockerProcessFactory.create(DockerProcessFactory.java:191)
	at io.airbyte.workers.process.AirbyteIntegrationLauncher.check(AirbyteIntegrationLauncher.java:149)
	at io.airbyte.workers.general.DefaultCheckConnectionWorker.run(DefaultCheckConnectionWorker.java:71)
	... 18 more
Caused by: io.temporal.failure.ApplicationFailure: message='/tmp/workspace/76ebf7cd-02d9-4447-b29f-c882953546ec/0', type='java.nio.file.NoSuchFileException', nonRetryable=false
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:438)
	at java.base/java.nio.file.Files.createDirectory(Files.java:699)
	at io.airbyte.workers.process.DockerProcessFactory.create(DockerProcessFactory.java:121)
	... 20 more
```

**Comment by dtiesling** [comment]
At least temporarily resolved it by shelling into the worker container and chown the /tmp/workspace directory.

To get a shell: `docker compose exec -u root worker bash`
Chown command that fixed the error: `chown airbyte:airbyte /tmp/workspace`

Going to bring the docker compose up and down to make sure the ownership doesn't get reset and then I'll close.
