### ISSUE TITLE
[destination-bigquery] java.lang.RuntimeException: Unable to deserialize PartialAirbyteMessage.

### ISSUE THREAD

**Issue by kevogabaa** [airbytehq/airbyte#38641]
### Connector Name

destination-bigquery

### Connector Version

2.4.20

### What step the error happened?

During the sync

### Relevant information

Airbyte version is `0.60.0`, deployed via helm charts version `0.81.0`

source is postgres version `3.4.5`

In my database I have postgis enabled hence presence of Geo-Spatial data. And multiple JSON files in my postgres.

This is a flaky error, such that it might fail but pass after several attempts.

Additionally, my successful jobs took at average of less than 2 minutes, however, now for the jobs that pass on first attempt take between 16 and 20 minutes, and the data is very small.

When attempting to load all fields, the process fails with the following error:

[log_file.txt](https://github.com/airbytehq/airbyte/files/15428710/default_workspace_job_24927_attempt_3_txt.txt)

![image](https://github.com/airbytehq/airbyte/assets/108656708/69e05d1a-8446-499a-bee6-ed4012042c2b)

### Relevant log output

```shell
2024-05-24 04:00:25 destination > ERROR main i.a.c.i.b.AirbyteExceptionHandler(uncaughtException):30 Something went wrong in the connector. See the logs for more details. java.lang.RuntimeException: Unable to deserialize PartialAirbyteMessage.
        at io.airbyte.cdk.integrations.destination.async.deser.AirbyteMessageDeserializer.deserializeAirbyteMessage$lambda$0(AirbyteMessageDeserializer.kt:33) ~[airbyte-cdk-core-0.35.0.jar:?]
        at java.base/java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at io.airbyte.cdk.integrations.destination.async.deser.AirbyteMessageDeserializer.deserializeAirbyteMessage(AirbyteMessageDeserializer.kt:32) ~[airbyte-cdk-core-0.35.0.jar:?]
        at io.airbyte.cdk.integrations.destination.async.AsyncStreamConsumer.accept(AsyncStreamConsumer.kt:129) ~[airbyte-cdk-core-0.35.0.jar:?]
        at io.airbyte.cdk.integrations.base.IntegrationRunner$Companion$consumeWriteStream$1$1.invoke(IntegrationRunner.kt:429) ~[airbyte-cdk-core-0.35.0.jar:?]
        at io.airbyte.cdk.integrations.base.IntegrationRunner$Companion$consumeWriteStream$1$1.invoke(IntegrationRunner.kt:427) ~[airbyte-cdk-core-0.35.0.jar:?]
        at io.airbyte.cdk.integrations.base.IntegrationRunner$Companion.consumeWriteStream$lambda$1$lambda$0(IntegrationRunner.kt:427) ~[airbyte-cdk-core-0.35.0.jar:?]
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at io.airbyte.cdk.integrations.base.IntegrationRunner$Companion.consumeWriteStream$io_airbyte_airbyte_cdk_java_airbyte_cdk_airbyte_cdk_core(IntegrationRunner.kt:427) ~[airbyte-cdk-core-0.35.0.jar:?]
        at io.airbyte.cdk.integrations.base.IntegrationRunner$Companion.consumeWriteStream$io_airbyte_airbyte_cdk_java_airbyte_cdk_airbyte_cdk_core$default(IntegrationRunner.kt:419) ~[airbyte-cdk-core-0.35.0.jar:?]
        at io.airbyte.cdk.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.kt:209) ~[airbyte-cdk-core-0.35.0.jar:?]
        at io.airbyte.cdk.integrations.base.IntegrationRunner.run(IntegrationRunner.kt:116) ~[airbyte-cdk-core-0.35.0.jar:?]
        at io.airbyte.integrations.destination.bigquery.BigQueryDestination.main(BigQueryDestination.java:470) ~[io.airbyte.airbyte-integrations.connectors-destination-bigquery.jar:?]
Stack Trace: java.lang.RuntimeException: Unable to deserialize PartialAirbyteMessage.
        at io.airbyte.cdk.integrations.destination.async.deser.AirbyteMessageDeserializer.deserializeAirbyteMessage$lambda$0(AirbyteMessageDeserializer.kt:33)
        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
        at io.airbyte.cdk.integrations.destination.async.deser.AirbyteMessageDeserializer.deserializeAirbyteMessage(AirbyteMessageDeserializer.kt:32)
        at io.airbyte.cdk.integrations.destination.async.AsyncStreamConsumer.accept(AsyncStreamConsumer.kt:129)
        at io.airbyte.cdk.integrations.base.IntegrationRunner$Companion$consumeWriteStream$1$1.invoke(IntegrationRunner.kt:429)
        at io.airbyte.cdk.integrations.base.IntegrationRunner$Companion$consumeWriteStream$1$1.invoke(IntegrationRunner.kt:427)
        at io.airbyte.cdk.integrations.base.IntegrationRunner$Companion.consumeWriteStream$lambda$1$lambda$0(IntegrationRunner.kt:427)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at io.airbyte.cdk.integrations.base.IntegrationRunner$Companion.consumeWriteStream$io_airbyte_airbyte_cdk_java_airbyte_cdk_airbyte_cdk_core(IntegrationRunner.kt:427)
        at io.airbyte.cdk.integrations.base.IntegrationRunner$Companion.consumeWriteStream$io_airbyte_airbyte_cdk_java_airbyte_cdk_airbyte_cdk_core$default(IntegrationRunner.kt:419)
        at io.airbyte.cdk.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.kt:209)
        at io.airbyte.cdk.integrations.base.IntegrationRunner.run(IntegrationRunner.kt:116)
        at io.airbyte.integrations.destination.bigquery.BigQueryDestination.main(BigQueryDestination.java:470)
2024-05-24 04:00:26 replication-orchestrator > (pod: data-pipeline-airbyte / destination-bigquery-write-24923-4-cwbwi) - Closed all resources for pod
2024-05-24 04:00:26 replication-orchestrator > readFromDestination: exception caught
io.airbyte.workers.internal.exception.DestinationException: Destination process exited with non-zero exit code 1
        at io.airbyte.workers.general.BufferedReplicationWorker.readFromDestination(BufferedReplicationWorker.java:493) ~[io.airbyte-airbyte-commons-worker-0.60.0.jar:?]
        at io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsync$2(BufferedReplicationWorker.java:235) ~[io.airbyte-airbyte-commons-worker-0.60.0.jar:?]
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by kevogabaa** [comment]
This issue looks related to #37621

**Comment by marcosmarxm** [comment]
Hello @kevogabaa I reported this to the destination team take a look.

**Comment by evantahler** [comment]
This should be fixed for BigQuery!

**Comment by killthekitten** [comment]
@evantahler could you please refer to the PR that addressed the issue? While I see that the `PartialAirbyteMessage` error is gone on 2.8.0, the sync now fails with an `java.lang.OutOfMemoryError`, and I'd like to make sure it's not exactly the same issue: 

```
2024-07-02 07:51:20 source > Terminating due to java.lang.OutOfMemoryError: Java heap space
2024-07-02 07:51:20 platform > readFromSource: source exception
io.airbyte.workers.internal.exception.SourceException: Source process exited with non-zero exit code 3
        at io.airbyte.workers.general.BufferedReplicationWorker.readFromSource(BufferedReplicationWorker.java:378) ~[io.airbyte-airbyte-commons-worker-0.63.4.jar:?]
        at io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsyncWithHeartbeatCheck$3(BufferedReplicationWorker.java:242) ~[io.airbyte-airbyte-commons-worker-0.63.4.jar:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

...

Warning from destination: Some streams were unsuccessful due to a source error: [io.airbyte.protocol.models.v0.StreamDescriptor@47248a48[name=execution_data,namespace=<null>,additionalProperties={}], io.airbyte.protocol.models.v0.StreamDescriptor@2349f14d[name=role,namespace=<null>,additionalProperties={}], io.airbyte.protocol.models.v0.StreamDescriptor@17e0933c[name=workflow_history,namespace=<null>,additionalProperties={}], io.airbyte.protocol.models.v0.StreamDescriptor@7edb6fca[name=workflow_statistics,namespace=<null>,additionalProperties={}], io.airbyte.protocol.models.v0.StreamDescriptor@1dcedc93[name=execution_metadata,namespace=<null>,additionalProperties={}], io.airbyte.protocol.models.v0.StreamDescriptor@716185fe[name=webhook_entity,namespace=<null>,additionalProperties={}], io.airbyte.protocol.models.v0.StreamDescriptor@628b819d[name=workflows_tags,namespace=<null>,additionalProperties={}], io.airbyte.protocol.models.v0.StreamDescriptor@478b0739[name=execution_entity,namespace=<null>,additionalProperties={}], io.airbyte.protocol.models.v0.StreamDescriptor@2cca611f[name=workflow_entity,namespace=<null>,additionalProperties={}], io.airbyte.protocol.models.v0.StreamDescriptor@51f95f0d[name=tag_entity,namespace=<null>,additionalProperties={}]]
```

If I disable one suspect stream on both 2.8.0 and older versions, the error goes away.

**Comment by evantahler** [comment]
Good!  In the latest version of the connector, you should be able to increase the memory you give to the destination to eventually process a record this large (before we would give up and throw that deserilization error).  We should be able to parse records up to 50mb now.

That said, Bigquery won't be able to hold a row of that size, so you'll Linley need to exclude that suspect stream, or at least skip some columns.
