### ISSUE TITLE
[source-mongodb-v2] MongoDb source connector stops working / not stable (non-zero exit code 2)

### ISSUE THREAD

**Issue by phammer** [airbytehq/airbyte#38705]
### Connector Name

source-mongodb-v2

### Connector Version

1.3.13

### What step the error happened?

During the sync

### Relevant information

The MongoDB Source Connector is not stable. 

After a few successful runs, the connector stops working. We have tried with different configurations, e.g., to reduce the amount of data being synced or change sync frequency, but the issue persists. 

Remark: it is a Airbyte Docker deployed on EC2. The same Airbyte instance is syncing successfully and in a stable manner from Slack and Confluence. However, MongoDB would be the most relevant one. The EC2 has been already upgraded to make sure it has enough power.

<img width="951" alt="image" src="https://github.com/airbytehq/airbyte/assets/2461650/097133ca-c2e8-4e9a-8721-a7754e142c81">

<img width="1143" alt="image" src="https://github.com/airbytehq/airbyte/assets/2461650/31e32252-a865-41cf-84f6-69a75dc848d0">

[default_workspace_job_191_attempt_5_txt.txt](https://github.com/airbytehq/airbyte/files/15470145/default_workspace_job_191_attempt_5_txt.txt)

### Relevant log output

```shell
2024-05-28 05:21:17 source > INFO pool-2-thread-1 i.d.p.s.SignalProcessor(stop):127 SignalProcessor stopped
2024-05-28 05:21:17 source > INFO pool-2-thread-1 i.d.s.DefaultServiceRegistry(close):105 Debezium ServiceRegistry stopped.
2024-05-28 05:21:17 source > INFO pool-2-thread-1 i.a.c.i.d.i.DebeziumRecordPublisher$start$3(taskStopped):92 DebeziumEngine notify: task stopped
2024-05-28 05:21:17 source > INFO pool-2-thread-1 o.a.k.c.s.FileOffsetBackingStore(stop):71 Stopped FileOffsetBackingStore
2024-05-28 05:21:17 source > INFO pool-2-thread-1 i.d.c.m.MongoDbConnector(stop):183 Stopping MongoDB connector
2024-05-28 05:21:17 source > INFO pool-2-thread-1 i.d.c.m.MongoDbConnector(stop):190 Stopped MongoDB connector
2024-05-28 05:21:17 source > INFO pool-2-thread-1 i.a.c.i.d.i.DebeziumRecordPublisher$start$3(connectorStopped):84 DebeziumEngine notify: connector stopped
2024-05-28 05:21:17 source > INFO pool-2-thread-1 i.a.c.i.d.i.DebeziumRecordPublisher(start$lambda$1):60 Debezium engine shutdown. Engine terminated successfully : true
2024-05-28 05:21:17 source > INFO pool-2-thread-1 i.a.c.i.d.i.DebeziumRecordPublisher(start$lambda$1):64 Connector 'io.debezium.connector.mongodb.MongoDbConnector' completed normally.
2024-05-28 05:21:17 source > INFO main i.a.c.i.d.i.DebeziumRecordIterator(computeNext):88 no record found. polling again.
2024-05-28 05:21:17 source > INFO main i.a.i.s.m.c.MongoDbCdcStateHandler(saveState):36 Saving Debezium state MongoDbCdcState[state={"[\"nezasa-prod\",{\"rs\":\"atlas-1004ip-shard-0\",\"server_id\":\"nezasa-prod\"}]":"{\"sec\":1716869068,\"ord\":2,\"transaction_id\":null,\"resume_token\":\"82665557CC000000022B042C0100296E5A100465D878232F204CF2BDEDC5C62E8ED7CB463C6F7065726174696F6E54797065003C696E736572740046646F63756D656E744B65790046645F69640064665557CCACD22DD9F51C7888000004\"}"}, schema_enforced=false]...
2024-05-28 05:21:17 source > WARN main i.a.c.i.b.IntegrationRunner$Companion(stopOrphanedThreads):434 The main thread is exiting while children non-daemon threads from a connector are still active.
Ideally, this situation should not happen...
Please check with maintainers if the connector or library code should safely clean up its threads before quitting instead.
The main thread is: main (RUNNABLE)
 Thread stacktrace: java.base/java.lang.Thread.getStackTrace(Thread.java:2450)
        at io.airbyte.cdk.integrations.base.IntegrationRunner$Companion.dumpThread(IntegrationRunner.kt:489)
        at io.airbyte.cdk.integrations.base.IntegrationRunner$Companion.stopOrphanedThreads(IntegrationRunner.kt:441)
        at io.airbyte.cdk.integrations.base.IntegrationRunner$Companion.stopOrphanedThreads$default(IntegrationRunner.kt:419)
        at io.airbyte.cdk.integrations.base.IntegrationRunner.readSerial(IntegrationRunner.kt:317)
        at io.airbyte.cdk.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.kt:183)
        at io.airbyte.cdk.integrations.base.IntegrationRunner.run(IntegrationRunner.kt:115)
        at io.airbyte.integrations.source.mongodb.MongoDbSource.main(MongoDbSource.java:52)
2024-05-28 05:21:17 source > WARN main i.a.c.i.b.IntegrationRunner$Companion(stopOrphanedThreads):454 Active non-daemon thread: debezium-mongodbconnector-nezasa-prod-replicator-buffer-0 (RUNNABLE)
 Thread stacktrace: java.base/sun.nio.ch.Net.poll(Native Method)
        at java.base/sun.nio.ch.NioSocketImpl.park(NioSocketImpl.java:191)
        at java.base/sun.nio.ch.NioSocketImpl.park(NioSocketImpl.java:201)
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099)
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:489)
        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:483)
        at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
        at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1461)
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1066)
        at com.mongodb.internal.connection.SocketStream.read(SocketStream.java:175)
        at com.mongodb.internal.connection.SocketStream.read(SocketStream.java:200)
        at com.mongodb.internal.connection.InternalStreamConnection.receiveResponseBuffers(InternalStreamConnection.java:739)
        at com.mongodb.internal.connection.InternalStreamConnection.receiveMessageWithAdditionalTimeout(InternalStreamConnection.java:603)
        at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:451)
        at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:372)
        at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:114)
        at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:765)
        at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:76)
        at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:209)
        at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:115)
        at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:83)
        at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:74)
        at com.mongodb.internal.connection.DefaultServer$OperationCountTrackingConnection.command(DefaultServer.java:299)
        at com.mongodb.internal.operation.SyncOperationHelper.createReadCommandAndExecute(SyncOperationHelper.java:273)
        at com.mongodb.internal.operation.SyncOperationHelper.lambda$executeRetryableRead$3(SyncOperationHelper.java:191)
        at com.mongodb.internal.operation.SyncOperationHelper.lambda$withSourceAndConnection$0(SyncOperationHelper.java:127)
        at com.mongodb.internal.operation.SyncOperationHelper.withSuppliedResource(SyncOperationHelper.java:152)
        at com.mongodb.internal.operation.SyncOperationHelper.lambda$withSourceAndConnection$1(SyncOperationHelper.java:126)
        at com.mongodb.internal.operation.SyncOperationHelper.withSuppliedResource(SyncOperationHelper.java:152)
        at com.mongodb.internal.operation.SyncOperationHelper.withSourceAndConnection(SyncOperationHelper.java:125)
        at com.mongodb.internal.operation.SyncOperationHelper.lambda$executeRetryableRead$4(SyncOperationHelper.java:189)
        at com.mongodb.internal.operation.SyncOperationHelper.lambda$decorateReadWithRetries$12(SyncOperationHelper.java:292)
        at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:67)
        at com.mongodb.internal.operation.SyncOperationHelper.executeRetryableRead(SyncOperationHelper.java:194)
        at com.mongodb.internal.operation.SyncOperationHelper.executeRetryableRead(SyncOperationHelper.java:176)
        at com.mongodb.internal.operation.AggregateOperationImpl.execute(AggregateOperationImpl.java:193)
        at com.mongodb.internal.operation.ChangeStreamOperation.lambda$execute$0(ChangeStreamOperation.java:187)
        at com.mongodb.internal.operation.SyncOperationHelper.withReadConnectionSource(SyncOperationHelper.java:99)
        at com.mongodb.internal.operation.ChangeStreamOperation.execute(ChangeStreamOperation.java:185)
        at com.mongodb.internal.operation.ChangeStreamOperation.execute(ChangeStreamOperation.java:54)
        at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:153)
        at com.mongodb.client.internal.ChangeStreamIterableImpl.execute(ChangeStreamIterableImpl.java:212)
        at com.mongodb.client.internal.ChangeStreamIterableImpl.cursor(ChangeStreamIterableImpl.java:187)
        at io.debezium.connector.mongodb.events.BufferingChangeStreamCursor$EventFetcher.run(BufferingChangeStreamCursor.java:195)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
2024-05-28 05:21:17 source > INFO main i.a.c.i.b.IntegrationRunner(runInternal):247 Completed integration: io.airbyte.integrations.source.mongodb.MongoDbSource
2024-05-28 05:21:17 source > INFO main i.a.i.s.m.MongoDbSource(main):53 completed source: class io.airbyte.integrations.source.mongodb.MongoDbSource
2024-05-28 05:23:17 source > ERROR pool-3-thread-1 i.a.c.i.b.IntegrationRunner$Companion(stopOrphanedThreads$lambda$4):472 Failed to interrupt children non-daemon threads, forcefully exiting NOW...

---
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Hello @phammer what Airbyte Platform are you using?

I got from logs:
```
2024-05-28 05:14:01 source > WARN main i.a.i.s.m.c.MongoDbCdcInitializer(logOplogInfo):181 Unable to query for op log stats, exception: {}Command failed with error 13 (Unauthorized): 'not authorized on local to execute command { collStats: "oplog.rs", $db: "local", lsid: { id: UUID("5024784c-7fc1-4482-974d-96cb29692dd1") } }' on server domain.mongodb.net:27017. The full response is {"ok": 0.0, "errmsg": "not authorized on local to execute command { collStats: \"oplog.rs\", $db: \"local\", lsid: { id: UUID(\"5024784c-7fc1-4482-974d-96cb29692dd1\") } }", "code": 13, "codeName": "Unauthorized", "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1716873241, "i": 371}}, "signature": {"hash": {"$binary": {"base64": "Ox52jJ2/+/PxYLy/GMhuL60xdNo=", "subType": "00"}}, "keyId": 7313970237232119812}}, "operationTime": {"$timestamp": {"t": 1716873241, "i": 371}}}
```

If you reset and sync again it works?

**Comment by phammer** [comment]
Hi @marcosmarxm , 

Thank you for checking the issue. 

- yes, with a reset I can get it running again. But after a while (not a too long while), we are back in the same situation. 

- Platform is AWS EC2 t3.large

**Comment by teslahenry** [comment]
There is the same issue with the source MSSQL CDC.

**Comment by luatnc87** [comment]
I encountered a similar issue with the source MSSQL CDC. It seems the issue is related to the unsuccessful stopping of the Debezium.

**Comment by theyueli** [comment]
hi all, if you see the error regarding "not authorized on local to execute command { collStats: "oplog.rs"...", please make sure the user you created for airbyte has read access to the `oplog.rs` collection (which is the op/wal log of MongoDB used for our CDC reads) under `local` database. 

You can check by running the following in mongosh:

```
> use local
> already on db local
> try {
  db.runCommand({ collStats: "oplog.rs" });
  print("User has permission to execute collStats command.");
} catch (e) {
  print("User does not have permission to execute collStats command.");
};
> User does not have permission to execute collStats command.
```

If you see the output above, it means you need to have the MongoDB admin grant read access to that collection under `local` database.

**Comment by phammer** [comment]
@gauth-qobra : no, I manage. I haven't had time recently to try again, however.

**Comment by usbogie** [comment]
Hey all I have this same problem did you ever solve it @gauth-qobra @phammer ?
