### ISSUE TITLE
[desitnation-duckdb] Airbyte throwing error`Cannot invoke "io.airbyte.protocol.models.AirbyteGlobalState.getStreamStates()"` for CDC sync

### ISSUE THREAD

**Issue by g-diwakar** [airbytehq/airbyte#38749]
### Connector Name

destination-duckdb

### Connector Version

0.3.5

### What step the error happened?

During the sync

### Relevant information

Use the latest version of open source airbyte. Use mysql or postgres as source connector for cdc incremental load. Run the sync and after some minutes (depends on your data) the replication will stop throwing following error. 

![image](https://github.com/airbytehq/airbyte/assets/89558623/826ee3dc-3685-4d69-91b1-7189621395db)

I have attached log file here.

[default_workspace_job_9_attempt_5_txt.txt](https://github.com/airbytehq/airbyte/files/15480674/default_workspace_job_9_attempt_5_txt.txt)

### Relevant log output

```shell
2024-05-29 04:14:18 platform > readFromDestination: exception caught
java.lang.NullPointerException: Cannot invoke "io.airbyte.protocol.models.AirbyteGlobalState.getStreamStates()" because the return value of "io.airbyte.protocol.models.AirbyteStateMessage.getGlobal()" is null
        at io.airbyte.workers.internal.bookkeeping.ParallelStreamStatsTracker.updateDestinationStateStats(ParallelStreamStatsTracker.kt:144) ~[io.airbyte-airbyte-commons-worker-0.61.0.jar:?]
        at io.airbyte.workers.internal.syncpersistence.SyncPersistenceImpl.updateDestinationStateStats(SyncPersistence.kt:356) ~[io.airbyte-airbyte-commons-worker-0.61.0.jar:?]
        at io.airbyte.workers.internal.bookkeeping.AirbyteMessageTracker.acceptFromDestination(AirbyteMessageTracker.kt:66) ~[io.airbyte-airbyte-commons-worker-0.61.0.jar:?]
        at io.airbyte.workers.general.ReplicationWorkerHelper.internalProcessMessageFromDestination(ReplicationWorkerHelper.kt:415) ~[io.airbyte-airbyte-commons-worker-0.61.0.jar:?]
        at io.airbyte.workers.general.ReplicationWorkerHelper.processMessageFromDestination(ReplicationWorkerHelper.kt:303) ~[io.airbyte-airbyte-commons-worker-0.61.0.jar:?]
        at io.airbyte.workers.general.BufferedReplicationWorker.readFromDestination(BufferedReplicationWorker.java:488) ~[io.airbyte-airbyte-commons-worker-0.61.0.jar:?]
        at io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsync$2(BufferedReplicationWorker.java:235) ~[io.airbyte-airbyte-commons-worker-0.61.0.jar:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
2024-05-29 04:14:18 platform > readFromDestination: done. (writeToDestFailed:false, dest.isFinished:false)
2024-05-29 04:14:18 platform > thread status... timeout thread: false , replication thread: true
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Hello @g-diwakar could you try another destination? If you disable CDC it works?

**Comment by g-diwakar** [comment]
Sorry I didn't update here. It works with other destinations. Perhaps the issue is within the duckdb connector.

**Comment by N-liraj-khanna** [comment]
This is still not fixed, even for weaviate not working

**Comment by teetangh** [comment]
Even I am getting this error while migrating to google sheets

**Comment by MurilloMaia** [comment]
Try to add override the destination.run method adding `by_alias=True` 



```python
    def run(self, args: List[str]) -> None:
        init_uncaught_exception_handler(logger)
        parsed_args = self.parse_args(args)
        output_messages = self.run_cmd(parsed_args)
        for message in output_messages:
            print(message.model_dump_json(exclude_unset=True, by_alias=True))
```

**Comment by Omers-Frontegg** [comment]
@MurilloMaia @ykuc Could you please elaborate more how you fixed it?
I'm using the RabbitMQ destination and getting the same error :(

Thanks!

**Comment by TheOnlyWayUp** [comment]
I'm syncing postgres to typesense, same error

`Cannot invoke "io.airbyte.protocol.models.AirbyteGlobalState.getStreamStates()" because the return value of "io.airbyte.protocol.models.AirbyteStateMessage.getGlobal()" is null`

[default_workspace_job_4_attempt_1_txt.txt](https://github.com/user-attachments/files/17804911/default_workspace_job_4_attempt_1_txt.txt)

**Comment by marcosmarxm** [comment]
Hello all 👋 sorry the missing updates. This issue need further investigation as impacting different destinations. It can be the case those destination weren't updated and are using an outdated version of the Airbyte Protocol. I'll try to get an update during the week and return here

**Comment by TheOnlyWayUp** [comment]
Thanks @marcosmarxm! I can test your fixes when you're ready

**Comment by dewrich** [comment]
Getting this exact issue using CDC with Source MSSQL->DuckDB (latest versions of Source and Destinations as of this date).

**Comment by sssynk** [comment]
Also having this issue with Typesense as a destination.

**Comment by ptiurin** [comment]
Same issue with CDC pipeline of Mysql (latest) -> Firebolt. However, setting mysql source to version `3.4.7` works.

**Comment by turulix** [comment]
I'm facing the same issue with Postgres to Qdrant :)

**Comment by davidhu2000** [comment]
Facing the same error syncing planetscale (v1.38.0) to bigquery (v2.12.4). I was on airbyte 1.5.1 and it worked fine. The error started happening on 1.7.0, tried to downgrade to 1.6.0 and still faced the same issue. I thought it was maybe the upgrade that caused this, so on our staging environment, i redid the entire setup for airbyte using 1.7.0 (deleted all the db and all relevant resources), and still had the same exact error.

**Comment by davidhu2000** [comment]
i ended up forking the planetscale source https://github.com/planetscale/airbyte-source, and figured out the issue (maybe it'll help others).

Planetscale was emitted state in the legacy format, and I'd guess that something updated in how bigquery destination handles state that triggers the error. I had to update the state to use stream instead. Here is a sample final connection state

```json
[
  {
    "streamDescriptor": {
      "name": "Table",
      "namespace": "DB"
    },
    "streamState": {
      "shards": {
        "-": {
          "cursor": "cursor"
        }
      }
    }
  },
]
```

I ran the stripe source locally and pulled an output of the state messages 

two issues i had to fix

```diff
{
  "type": "TRACE",
  "trace": {
-   "type": "STREAM",
+   "type": "STREAM_STATUS",
    "emitted_at": 1752778740025.7312,
    "stream_status": {
      "stream_descriptor": { "name": "refunds" },
      "status": "STARTED"
    }
  }
}
```

```diff
{
  "type": "STATE",
- "state_type": {
+ "state": {
    "type": "STREAM",
    "stream": {
      "stream_descriptor": { "name": "refunds" },
      "stream_state": { "updated": "1737831351" }
    },
    "sourceStats": { "recordCount": 0.0 }
  }
}
```

here is the debug output I used from stripe https://github.com/davidhu2000/airbyte-source/blob/main/DEBUG.md

Based on my testing, if the messages matches the stripe one, it should work as expected.
