### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'edition')

### ISSUE THREAD

**Issue by flowerkzj** [airbytehq/airbyte#38843]
### Platform Version

0.61.0

### What step the error happened?

On deploy

### Relevant information

I can deploy airbyte by docker-compose and start successfully when the internet can be access. As I need to deploy in private network, I tried to block the internet and visit the same address http://127.0.0.1:8000 but failed with the error below. Is it possible to deploy the project without internet?

### Relevant log output

```shell
TypeError: Cannot read properties of undefined (reading 'edition')
    at Fs (App-wDQOZnNU.js:1:12593)
    at JP (core-B2qoHgR6.js:38:19552)
    at aG (core-B2qoHgR6.js:40:44104)
    at nG (core-B2qoHgR6.js:40:39822)
    at nfe (core-B2qoHgR6.js:40:39748)
    at k2 (core-B2qoHgR6.js:40:39598)
    at O4 (core-B2qoHgR6.js:40:35960)
    at eG (core-B2qoHgR6.js:40:34907)
    at C (core-B2qoHgR6.js:25:1578)
    at MessagePort.M (core-B2qoHgR6.js:25:1947)
```

**Comment by marcosmarxm** [comment]
As far I know it is possible but you'll need to update the catalog manually. I'll keep the issue open to further investigation

**Comment by flowerkzj** [comment]
> As far I know it is possible but you'll need to update the catalog manually. I'll keep the issue open to further investigation

Thanks. As I need to deploy in private network, it is acceptable to update the catalog manually. Hope for a release to support the deployment in private network.

**Comment by zoloogg** [comment]
happening on freshly installed helm chart with default config

**Comment by bmills22** [comment]
Occurring with internet access on a fresh install with low-resource and insecure-mode checked.

**Comment by marcosmarxm** [comment]
For folks having this trouble, can you try another browser? 
@bmills22 I think you noticed that using Firefox and Safari it worked but not on Chrome, right?

**Comment by fredrikkadolfsson** [comment]
> For folks having this trouble, can you try another browser? @bmills22 I think you noticed that using Firefox and Safari it worked but not on Chrome, right?

I'm seeing this issue in Chrome and I can confirm that Firefox and Safari works as expected.

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 180 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
