### ISSUE TITLE
sync tasks failed after jira connector update KeyError: 'states'

### ISSUE THREAD

**Issue by emnaamor8** [airbytehq/airbyte#38929]
### Connector Name

jira

### Connector Version

2.0.1

### What step the error happened?

Updating the connector

### Relevant information

updated to connector to 2.0.1 then all synchronization tasks failed with a KeyError: 'states'

### Relevant log output

```shell
2024-06-04 10:30:50 source > Starting syncing SourceJira
2024-06-04 10:30:50 source > Marking stream issues as STARTED
2024-06-04 10:30:50 source > Encountered an exception while reading stream issues
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 136, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 222, in _read_stream
    stream_instance.state = stream_state  # type: ignore # we check that state in the dir(stream_instance)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py", line 85, in state
    self.retriever.state = state
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 385, in state
    self.cursor.set_initial_state(value)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/incremental/per_partition_cursor.py", line 86, in set_initial_state
    for state in stream_state["states"]:
KeyError: 'states'
```
```


### Contribute

- [X] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
@emnaamor8 can you confirm you follow instructions to migrate from previous version https://docs.airbyte.com/integrations/sources/jira-migrations#upgrading-to-200? As the error looks you're using a old version of the state.

**Comment by emnaamor8** [comment]
hey! 
thank you for your feedback. Yes i followed these steps but still having this keyerror for states 
```
2024-06-04 14:33:00 source > Marking stream issues as STARTED
2024-06-04 14:33:00 source > Encountered an exception while reading stream issues
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 136, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 222, in _read_stream
    stream_instance.state = stream_state  # type: ignore # we check that state in the dir(stream_instance)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py", line 85, in state
    self.retriever.state = state
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 385, in state
    self.cursor.set_initial_state(value)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/incremental/per_partition_cursor.py", line 86, in set_initial_state
    for state in stream_state["states"]:
KeyError: 'states'
2024-06-04 14:33:00 source > Marking stream issues as STOPPED
```

full logs : `workspace/12878199/0/logs.log`
