### ISSUE TITLE
VM restart fails the subsequent syncs with error - Could not find image: airbyte/source-mongodb-v2:1.3.4

### ISSUE THREAD

**Issue by shubhshah01** [airbytehq/airbyte#38925]
### Platform Version

0.57.2

### What step the error happened?

During the Sync

### Relevant information

I have an airbyte instance running in a VM with all syncs working fine.
Now if the VM restarts, subsequent syncs fails with connector not found error and requires to re-run the `run-ab-platform.sh` script.
Any solution for this so we don't have to run the script again on every VM restart ?

### Relevant log output

```shell
2024-06-04 05:41:21 platform > Checking if airbyte/source-mongodb-v2:1.3.4 exists...
2024-06-04 05:41:21 platform > airbyte/source-mongodb-v2:1.3.4 not found locally. Attempting to pull the image...
2024-06-04 05:41:21 platform > Image does not exist.
2024-06-04 05:41:21 platform > Unexpected error while checking connection: 
io.airbyte.workers.exception.WorkerException: Could not find image: airbyte/source-mongodb-v2:1.3.4
```

**Comment by marcosmarxm** [comment]
Can you check the disk space in your instance? This sometimes happen when you don't have enough disk in yoru server.

**Comment by shubhshah01** [comment]
Yes there seems to be enough space available.

```
df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        29G   19G   11G  63% /
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           1.6G  2.4M  1.6G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
efivarfs        128M  9.7K  128M   1% /sys/firmware/efi/efivars
/dev/sda15      105M  6.1M   99M   6% /boot/efi
/dev/sdb1        16G   28K   15G   1% /mnt
tmpfs           793M  4.0K  793M   1% /run/user/1000
```

**Comment by marcosmarxm** [comment]
What happen if you try to pull the image manually? Does the instance hs access to the internet?

**Comment by shubhshah01** [comment]
Restarted the VM
```bash
uptime -p

up 18 minutes
```
Tried docker pull... Image already exists
```
docker pull airbyte/source-mongodb-v2:1.3.4

1.3.4: Pulling from airbyte/source-mongodb-v2
Digest: sha256:105307cb26ea73416686d2846a151168a79bc4278a77b9f40f1a903da760d99d
Status: Image is up to date for airbyte/source-mongodb-v2:1.3.4
docker.io/airbyte/source-mongodb-v2:1.3.4
```

Still getting the same error...
below log is when i retest the source connector connection
```
2024-06-06 05:12:23 platform > Docker volume job log path: /tmp/workspace/5baf5f52-5708-4bde-949d-a7b036a6bb13/0/logs.log
2024-06-06 05:12:23 platform > Executing worker wrapper. Airbyte version: 0.57.2
2024-06-06 05:12:23 platform > Attempt 0 to save workflow id for cancellation
2024-06-06 05:12:23 platform > 
2024-06-06 05:12:23 platform > ----- START CHECK -----
2024-06-06 05:12:23 platform > 
2024-06-06 05:12:23 platform > Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2024-06-06 05:12:23 platform > Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2024-06-06 05:12:23 platform > Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2024-06-06 05:12:23 platform > Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2024-06-06 05:12:23 platform > Checking if airbyte/source-mongodb-v2:1.3.4 exists...
2024-06-06 05:12:23 platform > airbyte/source-mongodb-v2:1.3.4 not found locally. Attempting to pull the image...
2024-06-06 05:12:23 platform > Image does not exist.
2024-06-06 05:12:23 platform > Unexpected error while checking connection: 
io.airbyte.workers.exception.WorkerException: Could not find image: airbyte/source-mongodb-v2:1.3.4
	at io.airbyte.workers.process.DockerProcessFactory.create(DockerProcessFactory.java:117) ~[io.airbyte-airbyte-commons-worker-0.57.2.jar:?]
	at io.airbyte.workers.process.AirbyteIntegrationLauncher.check(AirbyteIntegrationLauncher.java:149) ~[io.airbyte-airbyte-commons-worker-0.57.2.jar:?]
	at io.airbyte.workers.general.DefaultCheckConnectionWorker.run(DefaultCheckConnectionWorker.java:71) ~[io.airbyte-airbyte-commons-worker-0.57.2.jar:?]
	at io.airbyte.workers.general.DefaultCheckConnectionWorker.run(DefaultCheckConnectionWorker.java:44) ~[io.airbyte-airbyte-commons-worker-0.57.2.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:142) ~[io.airbyte-airbyte-workers-0.57.2.jar:?]
	at io.airbyte.workers.temporal.check.connection.CheckConnectionActivityImpl.lambda$runWithJobOutput$1(CheckConnectionActivityImpl.java:238) ~[io.airbyte-airbyte-workers-0.57.2.jar:?]
	at io.airbyte.commons.temporal.HeartbeatUtils.withBackgroundHeartbeat(HeartbeatUtils.java:57) ~[io.airbyte-airbyte-commons-temporal-core-0.57.2.jar:?]
        at io.airbyte.workers.temporal.check.connection.CheckConnectionActivityImpl.runWithJobOutput(CheckConnectionActivityImpl.java:223) ~[io.airbyte-airbyte-workers-0.57.2.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at io.temporal.internal.activity.RootActivityInboundCallsInterceptor$POJOActivityInboundCallsInterceptor.executeActivity(RootActivityInboundCallsInterceptor.java:64) ~[temporal-sdk-1.22.3.jar:?]
	at io.temporal.internal.activity.RootActivityInboundCallsInterceptor.execute(RootActivityInboundCallsInterceptor.java:43) ~[temporal-sdk-1.22.3.jar:?]
	at io.temporal.internal.activity.ActivityTaskExecutors$BaseActivityTaskExecutor.execute(ActivityTaskExecutors.java:107) ~[temporal-sdk-1.22.3.jar:?]
	at io.temporal.internal.activity.ActivityTaskHandlerImpl.handle(ActivityTaskHandlerImpl.java:124) ~[temporal-sdk-1.22.3.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handleActivity(ActivityWorker.java:278) ~[temporal-sdk-1.22.3.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:243) ~[temporal-sdk-1.22.3.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:216) ~[temporal-sdk-1.22.3.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:105) ~[temporal-sdk-1.22.3.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
2024-06-06 05:12:23 platform > 
2024-06-06 05:12:23 platform > ----- END CHECK -----
2024-06-06 05:12:23 platform >
```

**Comment by marcosmarxm** [comment]
Do your VM has access to the internet? It is really strange error as you pulled the image manually.

**Comment by marcosmarxm** [comment]
@davinchia any thoughts here?

**Comment by shubhshah01** [comment]
> Do your VM has access to the internet? It is really strange error as you pulled the image manually.

@marcosmarxm Yes the VM does have access to internet.
Need some solution for this. I would be glad to share any other details required to resolve this issue.

**Comment by hwildwood** [comment]
Related issues?

https://github.com/airbytehq/airbyte/issues/39337
https://github.com/airbytehq/airbyte/issues/39424

**Comment by davinchia** [comment]
Yeap. Docker errors usually indicate local instance issues, which is not something Airbyte controls. Usually restarting them is sufficient.
