### ISSUE TITLE
Discovery schema failed

### ISSUE THREAD

**Issue by timorkal** [airbytehq/airbyte#38927]
### Connector Name

source-postgres

### Connector Version

3.4.10

### What step the error happened?

Configuring a new connector

### Relevant information

After configuring and validating the source and destination settings (I am trying to sync from Postgresql to BigQuery).
I am trying to create a connection and getting the following error in the UI:
![image](https://github.com/airbytehq/airbyte/assets/52398089/5d7a0ba4-d87d-4c26-a193-c0338519c5b6)
and these error logs in the worker

### Relevant log output

```shell
2024-06-04 11:48:46 WARN i.t.i.s.WorkflowExecutionHandler(throwAndFailWorkflowExecution):171 - Workflow execution failure WorkflowId='9dba102c-85c2-4aa9-9490-05d1b791b214', RunId=bed03898-690f-4a43-af8b-e67a4371940b, WorkflowType='DiscoverCatalogWorkflow'
io.temporal.failure.ActivityFailure: Activity with activityType='Run' failed: 'Activity task failed'. scheduledEventId=12, startedEventId=13, activityId=f6cbc6aa-2586-329b-aae1-c99857a2c118, identity='1@988656e0d4a6', retryState=RETRY_STATE_MAXIMUM_ATTEMPTS_REACHED
        at java.base/java.lang.Thread.getStackTrace(Thread.java:2450) [?:?]
        at io.temporal.internal.sync.ActivityStubBase.execute(ActivityStubBase.java:49) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.sync.ActivityInvocationHandler.lambda$getActivityFunc$0(ActivityInvocationHandler.java:83) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.sync.ActivityInvocationHandlerBase.invoke(ActivityInvocationHandlerBase.java:60) ~[temporal-sdk-1.22.3.jar:?]
        at jdk.proxy2/jdk.proxy2.$Proxy89.run(Unknown Source) ~[?:?]
        at io.airbyte.workers.temporal.discover.catalog.DiscoverCatalogWorkflowImpl.run(DiscoverCatalogWorkflowImpl.java:55) ~[io.airbyte-airbyte-workers-0.61.0.jar:?]    
        at DiscoverCatalogWorkflowImplProxy.run$accessor$R3HUU8Pl(Unknown Source) ~[?:?]
        at DiscoverCatalogWorkflowImplProxy$auxiliary$eJG1xP28.call(Unknown Source) ~[?:?]
        at io.airbyte.micronaut.temporal.TemporalActivityStubInterceptor.execute(TemporalActivityStubInterceptor.java:79) ~[io.airbyte-airbyte-micronaut-temporal-0.61.0.jar:?]
        at DiscoverCatalogWorkflowImplProxy.run(Unknown Source) ~[?:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation$RootWorkflowInboundCallsInterceptor.execute(POJOWorkflowImplementationFactory.java:339) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation.execute(POJOWorkflowImplementationFactory.java:314) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.sync.WorkflowExecutionHandler.runWorkflowMethod(WorkflowExecutionHandler.java:70) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.sync.SyncWorkflow.lambda$start$0(SyncWorkflow.java:135) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.sync.CancellationScopeImpl.run(CancellationScopeImpl.java:102) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.sync.WorkflowThreadImpl$RunnableWrapper.run(WorkflowThreadImpl.java:107) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.worker.ActiveThreadReportingExecutor.lambda$submit$0(ActiveThreadReportingExecutor.java:53) ~[temporal-sdk-1.22.3.jar:?]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: io.temporal.failure.ApplicationFailure: message='io.temporal.serviceclient.CheckedExceptionWrapper: io.airbyte.workers.exception.WorkerException: Error while discovering schema', type='java.lang.RuntimeException', nonRetryable=false
        at io.airbyte.commons.temporal.HeartbeatUtils.withBackgroundHeartbeat(HeartbeatUtils.java:62) ~[io.airbyte-airbyte-commons-temporal-core-0.61.0.jar:?]
        at io.airbyte.workers.temporal.discover.catalog.DiscoverCatalogActivityImpl.run(DiscoverCatalogActivityImpl.java:182) ~[io.airbyte-airbyte-workers-0.61.0.jar:?]   
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at io.temporal.internal.activity.RootActivityInboundCallsInterceptor$POJOActivityInboundCallsInterceptor.executeActivity(RootActivityInboundCallsInterceptor.java:64) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.activity.RootActivityInboundCallsInterceptor.execute(RootActivityInboundCallsInterceptor.java:43) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.activity.ActivityTaskExecutors$BaseActivityTaskExecutor.execute(ActivityTaskExecutors.java:107) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.activity.ActivityTaskHandlerImpl.handle(ActivityTaskHandlerImpl.java:124) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handleActivity(ActivityWorker.java:278) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:243) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:216) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:105) ~[temporal-sdk-1.22.3.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: io.temporal.failure.ApplicationFailure: message='Error while discovering schema', type='io.airbyte.workers.exception.WorkerException', nonRetryable=false       
        at io.airbyte.workers.general.DefaultDiscoverCatalogWorker.run(DefaultDiscoverCatalogWorker.java:136) ~[io.airbyte-airbyte-commons-worker-0.61.0.jar:?]
        at io.airbyte.workers.general.DefaultDiscoverCatalogWorker.run(DefaultDiscoverCatalogWorker.java:52) ~[io.airbyte-airbyte-commons-worker-0.61.0.jar:?]
        at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:138) ~[io.airbyte-airbyte-workers-0.61.0.jar:?]
        at io.airbyte.workers.temporal.discover.catalog.DiscoverCatalogActivityImpl.lambda$run$1(DiscoverCatalogActivityImpl.java:197) ~[io.airbyte-airbyte-workers-0.61.0.jar:?]
        at io.airbyte.commons.temporal.HeartbeatUtils.withBackgroundHeartbeat(HeartbeatUtils.java:57) ~[io.airbyte-airbyte-commons-temporal-core-0.61.0.jar:?]
        at io.airbyte.workers.temporal.discover.catalog.DiscoverCatalogActivityImpl.run(DiscoverCatalogActivityImpl.java:182) ~[io.airbyte-airbyte-workers-0.61.0.jar:?]   
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at io.temporal.internal.activity.RootActivityInboundCallsInterceptor$POJOActivityInboundCallsInterceptor.executeActivity(RootActivityInboundCallsInterceptor.java:64) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.activity.RootActivityInboundCallsInterceptor.execute(RootActivityInboundCallsInterceptor.java:43) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.activity.ActivityTaskExecutors$BaseActivityTaskExecutor.execute(ActivityTaskExecutors.java:107) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.activity.ActivityTaskHandlerImpl.handle(ActivityTaskHandlerImpl.java:124) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handleActivity(ActivityWorker.java:278) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:243) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:216) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:105) ~[temporal-sdk-1.22.3.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: io.temporal.failure.ApplicationFailure: message='baseUrl is invalid.', type='java.lang.IllegalStateException', nonRetryable=false
        at io.airbyte.api.client.generated.SourceApi.writeDiscoverCatalogResultWithHttpInfo(SourceApi.kt:5853) ~[io.airbyte-airbyte-api-0.61.0.jar:?]
        at io.airbyte.api.client.generated.SourceApi.writeDiscoverCatalogResult(SourceApi.kt:1155) ~[io.airbyte-airbyte-api-0.61.0.jar:?]
        at io.airbyte.workers.general.DefaultDiscoverCatalogWorker.run(DefaultDiscoverCatalogWorker.java:125) ~[io.airbyte-airbyte-commons-worker-0.61.0.jar:?]
        at io.airbyte.workers.general.DefaultDiscoverCatalogWorker.run(DefaultDiscoverCatalogWorker.java:52) ~[io.airbyte-airbyte-commons-worker-0.61.0.jar:?]
        at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:138) ~[io.airbyte-airbyte-workers-0.61.0.jar:?]
        at io.airbyte.workers.temporal.discover.catalog.DiscoverCatalogActivityImpl.lambda$run$1(DiscoverCatalogActivityImpl.java:197) ~[io.airbyte-airbyte-workers-0.61.0.jar:?]
        at io.airbyte.commons.temporal.HeartbeatUtils.withBackgroundHeartbeat(HeartbeatUtils.java:57) ~[io.airbyte-airbyte-commons-temporal-core-0.61.0.jar:?]
        at io.airbyte.workers.temporal.discover.catalog.DiscoverCatalogActivityImpl.run(DiscoverCatalogActivityImpl.java:182) ~[io.airbyte-airbyte-workers-0.61.0.jar:?]   
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at io.temporal.internal.activity.RootActivityInboundCallsInterceptor$POJOActivityInboundCallsInterceptor.executeActivity(RootActivityInboundCallsInterceptor.java:64) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.activity.RootActivityInboundCallsInterceptor.execute(RootActivityInboundCallsInterceptor.java:43) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.activity.ActivityTaskExecutors$BaseActivityTaskExecutor.execute(ActivityTaskExecutors.java:107) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.activity.ActivityTaskHandlerImpl.handle(ActivityTaskHandlerImpl.java:124) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handleActivity(ActivityWorker.java:278) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:243) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:216) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:105) ~[temporal-sdk-1.22.3.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by timorkal** [comment]
Airbyte version: 0.61.0
Running as on-prem (docker-compose)

**Comment by armetiz** [comment]
Related to : https://github.com/airbytehq/airbyte/issues/38854 ?

**Comment by aiman-al-masoud** [comment]
I had a similar problem with a different source and destination. In my case, I didn't even see any error stacktrace in the logs. Moreover: when I tried manually running the docker command that retrieves the schema (copy-pasted from the logs) it worked fine (printed the schema  as a json in the shell).

Downgrading to 0.60.1 seemed to do the trick. I had to manually pull the older docker images (eg: docker pull airbyte/webapp:0.60.1) and then start airbyte with docker compose. I wonder if there's an easier way to downgrade.

**Comment by yzislin** [comment]
There is an easy way to downgrade (unless DB requires changes). Just go to .env file and change the version. On docker compose up, it will automatically pull and use that version

**Comment by timorkal** [comment]
yes thank you, downgrading helped.
Version 0.61.0 is defected and should be obsolete.
To downgrade I just pulled this file and run it:
https://raw.githubusercontent.com/airbytehq/airbyte/v0.60.1/run-ab-platform.sh

**Comment by timorkal** [comment]
yes thank you, downgrading helped.
Version 0.61.0 is defected and should be obsolete.
To downgrade I just pulled this file and run it:
https://raw.githubusercontent.com/airbytehq/airbyte/v0.60.1/run-ab-platform.sh

**Comment by cconnect-tmcfadden** [comment]
Starting to see this baseUrl failure with 0.63.8 schema Discovery this morning, connectors were able to discoverSchema ok yesterday.

**Comment by mujibishola** [comment]
This is failing for me as well.I Will attempt a downgrade.

**Comment by mujibishola** [comment]
> This is failing for me as well.I Will attempt a downgrade.

Downgrading to 0.60.1 works! I'm hoping this will get sorted soon.
