### ISSUE TITLE
Kube cancel can produce noisy worker exception.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#3923]
## Tell us about the problem you're trying to solve
On rare occasions, an additional worker exception is thrown when a job is cancelled. This is in addition to the two temporal exceptions being emitted that we don't have good control over. This tends to happen if the job is cancelled early, before the sync even begins.

E.g.
```
2021-06-07 09:24:23 INFO i.a.w.p.a.DefaultAirbyteSource(cancel):137 - {job_id=14, job_log_filename=logs.log, job_root=/workspace/14/0} - Source process no longer exists, cancellation is a no-op.
2021-06-07 09:24:23 INFO i.a.w.t.TemporalAttemptExecution(lambda$getCancellationChecker$3):185 - {job_id=14, job_log_filename=logs.log, job_root=/workspace/14/0} - Interrupting worker thread...
2021-06-07 09:24:23 INFO i.a.w.t.TemporalAttemptExecution(lambda$getCancellationChecker$3):188 - {job_id=14, job_log_filename=logs.log, job_root=/workspace/14/0} - Cancelling completable future...
2021-06-07 09:24:23 INFO i.a.w.t.TemporalAttemptExecution(get):134 - {ActivityId=c836e3e2-1d17-33cc-9ca1-ae450b11f515, ActivityType=Replicate, Namespace=default, RunId=59806a18-cc4a-45e6-9ebd-e5c7b2beebe0, TaskQueue=SYNC, WorkflowId=fe074c64-7c84-4491-9dd5-0cfc2e1bf9bc, job_id=14, job_log_filename=logs.log, job_root=/workspace/14/0} - Stopping cancellation check scheduling...
2021-06-07 09:24:23 WARN i.t.i.s.POJOActivityTaskHandler$POJOActivityImplementation(execute):243 - {ActivityId=c836e3e2-1d17-33cc-9ca1-ae450b11f515, ActivityType=Replicate, Namespace=default, RunId=59806a18-cc4a-45e6-9ebd-e5c7b2beebe0, TaskQueue=SYNC, WorkflowId=fe074c64-7c84-4491-9dd5-0cfc2e1bf9bc, job_id=14, job_log_filename=logs.log, job_root=/workspace/14/0} - Activity failure. ActivityId=c836e3e2-1d17-33cc-9ca1-ae450b11f515, activityType=Replicate, attempt=1
java.util.concurrent.CancellationException: null
	at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2468) ~[?:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getCancellationChecker$3(TemporalAttemptExecution.java:191) ~[io.airbyte-airbyte-workers-0.24.7-alpha.jar:?]
	at io.airbyte.workers.temporal.CancellationHandler$TemporalCancellationHandler.checkAndHandleCancellation(CancellationHandler.java:70) ~[io.airbyte-airbyte-workers-0.24.7-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getCancellationChecker$4(TemporalAttemptExecution.java:195) ~[io.airbyte-airbyte-workers-0.24.7-alpha.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
2021-06-07 09:24:23 WARN i.a.w.t.CancellationHandler$TemporalCancellationHandler(checkAndHandleCancellation):71 - {job_id=14, job_log_filename=logs.log, job_root=/workspace/14/0} - Job either timeout-ed or was cancelled.
2021-06-07 09:24:23 ERROR i.a.w.DefaultReplicationWorker(run):148 - {job_id=14, job_log_filename=logs.log, job_root=/workspace/14/0} - Sync worker failed.
io.airbyte.workers.WorkerException: null
	at io.airbyte.workers.process.KubeProcessFactory.create(KubeProcessFactory.java:88) ~[io.airbyte-airbyte-workers-0.24.7-alpha.jar:?]
	at io.airbyte.workers.process.ProcessFactory.create(ProcessFactory.java:68) ~[io.airbyte-airbyte-workers-0.24.7-alpha.jar:?]
	at io.airbyte.workers.process.AirbyteIntegrationLauncher.read(AirbyteIntegrationLauncher.java:126) ~[io.airbyte-airbyte-workers-0.24.7-alpha.jar:?]
	at io.airbyte.workers.protocols.airbyte.DefaultAirbyteSource.start(DefaultAirbyteSource.java:81) ~[io.airbyte-airbyte-workers-0.24.7-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:123) [io.airbyte-airbyte-workers-0.24.7-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:52) [io.airbyte-airbyte-workers-0.24.7-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:147) [io.airbyte-airbyte-workers-0.24.7-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
2021-06-07 09:24:23 INFO i.a.w.DefaultReplicationWorker(run):169 - {job_id=14, job_log_filename=logs.log, job_root=/workspace/14/0} - sync summary: io.airbyte.config.ReplicationAttemptSummary@10da1bdd[status=cancelled,recordsSynced=0,bytesSynced=0,startTime=1623057838887,endTime=1623057863463]
2021-06-07 09:24:23 INFO i.a.w.DefaultReplicationWorker(run):178 - {job_id=14, job_log_filename=logs.log, job_root=/workspace/14/0} - Source did not output any state messages
2021-06-07 09:24:23 WARN i.a.w.DefaultReplicationWorker(run):189 - {job_id=14, job_log_filename=logs.log, job_root=/workspace/14/0} - State capture: No state retained.
2021-06-07 09:24:23 ERROR i.t.i.s.POJOWorkflowImplementationFactory$POJOWorkflowImplementation$RootWorkflowInboundCallsInterceptor(logWorkflowExecutionException):323 - {Namespace=default, RunId=59806a18-cc4a-45e6-9ebd-e5c7b2beebe0, TaskQueue=SYNC, WorkflowId=fe074c64-7c84-4491-9dd5-0cfc2e1bf9bc, WorkflowType=SyncWorkflow} - Workflow execution failure WorkflowId=fe074c64-7c84-4491-9dd5-0cfc2e1bf9bc, RunId=59806a18-cc4a-45e6-9ebd-e5c7b2beebe0, WorkflowType=SyncWorkflow
io.temporal.failure.ActivityFailure: scheduledEventId=5, startedEventId=11, activityType='Replicate', activityId='c836e3e2-1d17-33cc-9ca1-ae450b11f515', identity='1@airbyte-scheduler-d8f488cf6-tt92c', retryState=RETRY_STATE_CANCEL_REQUESTED
	at java.lang.Thread.getStackTrace(Thread.java:1598) ~[?:?]
	at io.temporal.internal.sync.ActivityStubBase.execute(ActivityStubBase.java:48) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.ActivityInvocationHandler.lambda$getActivityFunc$0(ActivityInvocationHandler.java:59) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.ActivityInvocationHandlerBase.invoke(ActivityInvocationHandlerBase.java:65) ~[temporal-sdk-1.0.4.jar:?]
	at com.sun.proxy.$Proxy45.replicate(Unknown Source) ~[?:?]
	at io.airbyte.workers.temporal.SyncWorkflow$WorkflowImpl.run(SyncWorkflow.java:105) ~[io.airbyte-airbyte-workers-0.24.7-alpha.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation$RootWorkflowInboundCallsInterceptor.execute(POJOWorkflowImplementationFactory.java:289) [temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation.execute(POJOWorkflowImplementationFactory.java:253) [temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.WorkflowExecuteRunnable.run(WorkflowExecuteRunnable.java:52) [temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.SyncWorkflow.lambda$start$0(SyncWorkflow.java:126) [temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.CancellationScopeImpl.run(CancellationScopeImpl.java:101) [temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.WorkflowThreadImpl$RunnableWrapper.run(WorkflowThreadImpl.java:107) [temporal-sdk-1.0.4.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: io.temporal.failure.ApplicationFailure: type='java.util.concurrent.CancellationException', nonRetryable=false
	at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2468) ~[?:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getCancellationChecker$3(TemporalAttemptExecution.java:191) ~[io.airbyte-airbyte-workers-0.24.7-alpha.jar:?]
	at io.airbyte.workers.temporal.CancellationHandler$TemporalCancellationHandler.checkAndHandleCancellation(CancellationHandler.java:70) ~[io.airbyte-airbyte-workers-0.24.7-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getCancellationChecker$4(TemporalAttemptExecution.java:195) ~[io.airbyte-airbyte-workers-0.24.7-alpha.jar:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[?:?]
```

## Describe the solution you’d like
We should investigate and silence this.

**Comment by jrhizor** [comment]
@davinchia is there anything else you wanted to add for this?

**Comment by davinchia** [comment]
This is something I noticed while testing and was not able to reliably reproduce. I'm not sure if this is really fixed with the latest changes - let's leave this open for now.
