### ISSUE TITLE
Source MySQL: Connector fails if source contains "tricky" date values

### ISSUE THREAD

**Issue by DoNotPanicUA** [airbytehq/airbyte#3931]
Found by comprehensive tests #3810 

## Expected Behavior
A connector should finish its work no matter what data source contains. 
 
## Current Behavior
- If a source contains a zero date value like `2021-00-00` or even `0000-00-00`, the connector will fail with an error "Zero date value prohibited". Relevant for types `date` and `DATETIME`
- MySQL source can contain a time value larger than can handle the corresponding Java type. The connector fails with the error "The value '-794:59:59' is an invalid TIME value. JDBC Time objects represent a wall-clock time and not a duration as MySQL treats them. If you are treating this type as a duration, consider retrieving this value as a string and dealing with it according to your requirements."

## Steps to Reproduce
Short way:
1. Checkout master branch
2. Go to `MySqlSourceComprehensiveTest.java` and uncomment test values at lines: `208`, `218`, `236`

Long way:
1. Create a table with columns date, DATETIME, and time types. 
2. Insert zero date values(`2000-00-00`) into DATE and DATETIME columns and `-838:59:59.000000` into TIME column.
3. Setup and run connector
4. :bomb: 

## Severity of the bug for you
High

## Airbyte Version
0.24.7-alpha

## Connector Version
0.3.4

**Comment by vsayer** [comment]
Confirmed in:

- airbyte `0.27.3-alpha`
- source mysql `0.1.1`

```
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - Exception in thread "main" java.lang.RuntimeException: java.sql.SQLException: Zero date value prohibited
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.db.jdbc.JdbcUtils$1.tryAdvance(JdbcUtils.java:76)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:58)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.commons.util.LazyAutoCloseableIterator.computeNext(LazyAutoCloseableIterator.java:62)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:58)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:58)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.commons.util.CompositeIterator.computeNext(CompositeIterator.java:83)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:58)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:109)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.source.mysql.MySqlSource.main(MySqlSource.java:250)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - Caused by: java.sql.SQLException: Zero date value prohibited
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:99)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at com.mysql.cj.jdbc.result.ResultSetImpl.getTimestamp(ResultSetImpl.java:914)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1254)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at org.apache.commons.dbcp2.DelegatingResultSet.getObject(DelegatingResultSet.java:733)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at org.apache.commons.dbcp2.DelegatingResultSet.getObject(DelegatingResultSet.java:733)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.db.jdbc.JdbcUtils.rowToJson(JdbcUtils.java:103)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.db.jdbc.JdbcUtils$1.tryAdvance(JdbcUtils.java:73)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	... 24 more
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - Caused by: com.mysql.cj.exceptions.DataReadException: Zero date value prohibited
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at com.mysql.cj.result.SqlTimestampValueFactory.localCreateFromTimestamp(SqlTimestampValueFactory.java:101)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at com.mysql.cj.result.SqlTimestampValueFactory.localCreateFromTimestamp(SqlTimestampValueFactory.java:50)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at com.mysql.cj.result.AbstractDateTimeValueFactory.createFromTimestamp(AbstractDateTimeValueFactory.java:87)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at com.mysql.cj.protocol.a.MysqlBinaryValueDecoder.decodeTimestamp(MysqlBinaryValueDecoder.java:52)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at com.mysql.cj.protocol.result.AbstractResultsetRow.decodeAndCreateReturnValue(AbstractResultsetRow.java:87)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at com.mysql.cj.protocol.result.AbstractResultsetRow.getValueFromBytes(AbstractResultsetRow.java:241)
2021-07-15 21:35:29 ERROR () LineGobbler(voidCall):85 - 	at com.mysql.cj.protocol.a.result.BinaryBufferRow.getValue(BinaryBufferRow.java:244)
```

**Comment by ChristopheDuong** [comment]
Is this solvable by adding jdbc_params?

see this comment and linked question: 
https://github.com/airbytehq/airbyte/issues/2601#issuecomment-806581028

**Comment by yinondn** [comment]
I'm still getting this error for invalid TIME values:
```Message: The value '25:00:00' is an invalid TIME value. JDBC Time objects represent a wall-clock time and not a duration as MySQL treats them. If you are treating this type as a duration, consider retrieving this value as a string and dealing with it according to your requirements.```

Connector: MySQL 2.0.13
Airbyte v0.41.0

Can someone please check or explain a workaround?
