### ISSUE TITLE
Bootloader not starting. Issue with postgres actor collection

### ISSUE THREAD

**Issue by capture-namang** [airbytehq/airbyte#39355]
### Platform Version

0.59.0

### What step the error happened?

On deploy

### Relevant information

Hi team, I am using docker-compose to build my airbyte application. I integrated the same with dagster and was able to use it comfortably. I tried to upgrade my airbyte to 0.62.0 version, but since then I am facing the below error.

My dagster version is 1.7.8 and airbyte-dagster version is 0.23.8

### Relevant log output

```shell
2024-06-09 19:34:07 Caused by: org.postgresql.util.PSQLException: ERROR: column actor.default_version_id does not exist
2024-06-09 19:34:07   Position: 58
2024-06-09 19:34:07     at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725) ~[postgresql-42.7.3.jar:42.7.3]
2024-06-09 19:34:07     at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412) ~[postgresql-42.7.3.jar:42.7.3]
2024-06-09 19:34:07     at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371) ~[postgresql-42.7.3.jar:42.7.3]
2024-06-09 19:34:07     at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502) ~[postgresql-42.7.3.jar:42.7.3]
2024-06-09 19:34:07     at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419) ~[postgresql-42.7.3.jar:42.7.3]
2024-06-09 19:34:07     at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:194) ~[postgresql-42.7.3.jar:42.7.3]
2024-06-09 19:34:07     at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:180) ~[postgresql-42.7.3.jar:42.7.3]
2024-06-09 19:34:07     at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[HikariCP-5.1.0.jar:?]
2024-06-09 19:34:07     at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[HikariCP-5.1.0.jar:?]
2024-06-09 19:34:07     at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219) ~[jooq-3.19.1.jar:?]
2024-06-09 19:34:07     at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4848) ~[jooq-3.19.1.jar:?]
2024-06-09 19:34:07     at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:236) ~[jooq-3.19.1.jar:?]
2024-06-09 19:34:07     at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:348) ~[jooq-3.19.1.jar:?]
2024-06-09 19:34:07     ... 20 more
2024-06-09 19:34:07 2024-06-09 14:04:07 INFO i.m.r.Micronaut(lambda$start$0):117 - Embedded Application shutting down
2024-06-09 19:34:07 INFO StatusConsoleListener Loading mask data from '/seed/specs_secrets_mask.yaml
2024-06-09 19:34:07 WARN StatusConsoleListener Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger
```

**Comment by capture-namang** [comment]
I updated the version to 0.62.3 and it got resolved. Seems like the error was with the release of 0.62.0

**Comment by capture-namang** [comment]
I updated the version to 0.62.3 and it got resolved. Seems like the error was with the release of 0.62.0
