### ISSUE TITLE
Unable to configure the source connector Google Analytics GA4 on Airbyte running on Azure Kubernetes Cluster.

### ISSUE THREAD

**Issue by saurabh111222** [airbytehq/airbyte#39423]
### Connector Name

source-Google Analytics 4 (GA4)

### Connector Version

2.4.2

### What step the error happened?

Configuring a new connector

### Relevant information

Airbyte is running on AKS cluster which is in private network and we want to load the data from Google Analytics GA4 to some destination. But while configuring the source connection only we are getting the Permission denied and seems like airbyte is trying to write a source_config.json.

### Relevant log output

```shell
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 8, in <module>
    run()
  File "/airbyte/integration_code/source_google_analytics_data_api/run.py", line 17, in run
    MigrateCustomReportsCohortSpec.migrate(sys.argv[1:], source)
  File "/airbyte/integration_code/source_google_analytics_data_api/config_migrations.py", line 235, in migrate
    cls._modify_and_save(config_path, source, config),
  File "/airbyte/integration_code/source_google_analytics_data_api/config_migrations.py", line 208, in _modify_and_save
    source.write_config(migrated_config, config_path)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/connector.py", line 71, in write_config
    with open(config_path, "w") as fh:
PermissionError: [Errno 13] Permission denied: 'source_config.json'
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Are you using a different service account when deploying Airbyte using Helm? I think the problem is related to the permissions the service account or Airbyte has to access the pods.

**Comment by saurabh111222** [comment]
I the same by tried setting up the Airbyte on my local machine(mac) and I am still getting the same error while connecting to Google Analytics GA4 connector.

![image](https://github.com/airbytehq/airbyte/assets/37499007/ea7177c2-c528-498f-a156-57a04b9f8066)

**Comment by saurabh111222** [comment]
> Are you using a different service account when deploying Airbyte using Helm? I think the problem is related to the permissions the service account or Airbyte has to access the pods.


I am able to connect by downgrading the version of connector Google Analytics GA4 to version (2.0.3).

<img width="897" alt="Screenshot 2024-06-13 at 12 09 12 PM" src="https://github.com/airbytehq/airbyte/assets/37499007/f58c6813-8478-46b1-9835-b729a9117e8e">

**Comment by tanderson-hp** [comment]
I have the same issue, and downgrading to 2.0.3 worked.

**Comment by marcosmarxm** [comment]
I included the issue in connector team backlog for further investigation.

**Comment by Aasma-Aas** [comment]
I encountered the same issue while creating a GA4 source in Airbyte, but I resolved it by downgrading the version to GA4 2.0.3.

![2024-09-25_13h28_48](https://github.com/user-attachments/assets/1ec63242-f507-423d-b1a5-13df72443875)

To RESOLVE this, in Airbyte simply navigate to the Settings tab, click on Sources, and you can change the version from there.

![2024-09-25_13h32_37](https://github.com/user-attachments/assets/418f8847-010b-4fb1-8a21-672882a5902d)

**Comment by tristaningenius** [comment]
I encountered the same issue while creating a GA4 source in Airbyte, but I resolved it by downgrading the version to GA4 2.0.3.

**Comment by Sebastien73** [comment]
I encountered the same issue when I used GA4 v2.4.2 (or latest 2.5.12). I had to downgrade the version GA4 2.0.3 to resolved it.

**Comment by icychocolate98** [comment]
Good afternoon team ! 

We have encountered an error after migrating our ecosystem to v1.1.0, specifically related to the source-google-analytics-data-api source, the difference is that we are not using Azure, just deploying with abctl and kind in an own Linux server.

We had several workspaces using this source that migrated successfully (in UI logs, they are working with source > 2.0.3 but internally I think they are using < 2.0.3) but, when attempting to create a new one we receive an error, what appears to be the setup process:

```python
PermissionError: [Errno 13] Permission denied: '/config/connectionConfiguration.json'
```

This creates significant uncertainty for us, as we cannot create a new stream and must be cautious with the potential migration of existing streams prior to the update.

I believe the problem lies in the fact that when it tries to configure the source with the new data, either the config/ directory or the connectionConfiguration.json file have incorrect permissions and are created with a higher-level user, or conversely, the source is attempting to access them with a user that doesn't have the necessary permissions.

Another interesting aspect of this error is that if we have a source created with, for example, `v2.0.3`, migrate the source to `v2.6.1`, and execute a sync (without resetting), it synchronizes perfectly. However, if we migrate the source, reset, and then synchronize, we observe that it attempts to use the new version. This behavior seems somewhat unusual.

Is there any news about this issue ?

@marcosmarxm
