### ISSUE TITLE
[platform] v0.63.0 Unexpected error occurred: No enum constant io.airbyte.api.client.model.generated.JobStatus.running

### ISSUE THREAD

**Issue by descampsk** [airbytehq/airbyte#39482]
### Platform Version

v0.63.0

### What step the error happened?

Other

### Relevant information

Deployed via https://raw.githubusercontent.com/airbytehq/airbyte/v0.63.0/run-ab-platform.sh with my own database.

Occured after an upgrade from the version 0.61.0

When calling http://airbyte.dev.gcp.internal:8006/v1/jobs?connectionId=e3c6eec3-7240-490a-95be-eb58ea635fb1&status=running

But I have also a 400 error on http://airbyte.dev.gcp.internal:8006/v1/jobs?connectionId=e3c6eec3-7240-490a-95be-eb58ea635fb1 which is maybe related

### Relevant log output

```shell
Error 500

2024-06-14 09:21:09 ERROR i.m.h.s.RouteExecutor(logException):282 - Unexpected error occurred: No enum constant io.airbyte.api.client.model.generated.JobStatus.running
java.lang.IllegalArgumentException: No enum constant io.airbyte.api.client.model.generated.JobStatus.running
        at java.base/java.lang.Enum.valueOf(Enum.java:293) ~[?:?]
        at io.airbyte.api.client.model.generated.JobStatus.valueOf(JobStatus.kt) ~[io.airbyte-airbyte-api-0.63.0.jar:?]
        at io.airbyte.api.server.filters.JobsFilter.getConfigApiStatus(JobsFilter.kt:43) ~[io.airbyte-airbyte-api-server-0.63.0.jar:?]
        at io.airbyte.api.server.services.JobServiceImpl.getJobList(JobService.kt:263) ~[io.airbyte-airbyte-api-server-0.63.0.jar:?]
        at io.airbyte.api.server.controllers.JobsController.listJobs$lambda$6(JobsController.kt:248) ~[io.airbyte-airbyte-api-server-0.63.0.jar:?]
        at io.airbyte.api.server.apiTracking.TrackingHelper.callWithTracker(TrackingHelper.kt:107) ~[io.airbyte-airbyte-api-server-0.63.0.jar:?]
        at io.airbyte.api.server.controllers.JobsController.listJobs(JobsController.kt:246) ~[io.airbyte-airbyte-api-server-0.63.0.jar:?]
        at io.airbyte.api.server.controllers.$JobsController$Definition$Exec.dispatch(Unknown Source) ~[io.airbyte-airbyte-api-server-0.63.0.jar:?]
        at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invokeUnsafe(AbstractExecutableMethodsDefinition.java:461) ~[micronaut-inject-4.4.10.jar:4.4.10]
        at io.micronaut.context.DefaultBeanContext$BeanContextUnsafeExecutionHandle.invokeUnsafe(DefaultBeanContext.java:4232) ~[micronaut-inject-4.4.10.jar:4.4.10]
        at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:271) ~[micronaut-router-4.4.10.jar:4.4.10]
        at io.micronaut.http.server.RouteExecutor.executeRouteAndConvertBody(RouteExecutor.java:488) ~[micronaut-http-server-4.4.10.jar:4.4.10]
        at io.micronaut.http.server.RouteExecutor.lambda$callRoute$6(RouteExecutor.java:465) ~[micronaut-http-server-4.4.10.jar:4.4.10]
        at io.micronaut.core.execution.ExecutionFlow.lambda$async$1(ExecutionFlow.java:87) ~[micronaut-core-4.4.10.jar:4.4.10]
        at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211) ~[micronaut-core-4.4.10.jar:4.4.10]
        at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211) ~[micronaut-core-4.4.10.jar:4.4.10]
        at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314) ~[?:?]

Error 400 : 

2024-06-14 09:21:18 ERROR i.a.a.s.s.JobServiceImpl(getJobList):224 - Config api response error for getJobList: 
io.micronaut.http.client.exceptions.HttpClientResponseException: Bad Request
        at io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.makeErrorFromRequestBody(DefaultHttpClient.java:2259) ~[micronaut-http-client-4.4.10.jar:4.4.10]
        at io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.forwardResponseToPromise(DefaultHttpClient.java:2210) ~[micronaut-http-client-4.4.10.jar:4.4.10]
        at io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.channelReadInstrumented(DefaultHttpClient.java:2179) ~[micronaut-http-client-4.4.10.jar:4.4.10]
        at io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.channelReadInstrumented(DefaultHttpClient.java:2147) ~[micronaut-http-client-4.4.10.jar:4.4.10]
        at io.micronaut.http.client.netty.SimpleChannelInboundHandlerInstrumented.channelRead0(SimpleChannelInboundHandlerInstrumented.java:46) ~[micronaut-http-client-4.4.10.jar:4.4.10]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.micronaut.http.client.netty.ResettableReadTimeoutHandler$NextInterceptor.channelRead(ResettableReadTimeoutHandler.java:92) ~[micronaut-http-client-4.4.10.jar:4.4.10]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289) ~[netty-handler-4.1.110.Final.jar:4.1.110.Final]
        at io.micronaut.http.client.netty.ResettableReadTimeoutHandler.channelRead(ResettableReadTimeoutHandler.java:64) ~[micronaut-http-client-4.4.10.jar:4.4.10]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994) ~[netty-common-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.110.Final.jar:4.1.110.Final]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:104) ~[reactor-core-3.6.5.jar:3.6.5]
                at reactor.core.publisher.Flux.blockFirst(Flux.java:2766) ~[reactor-core-3.6.5.jar:3.6.5]
                at io.micronaut.http.client.netty.DefaultHttpClient$1.exchange(DefaultHttpClient.java:571) ~[micronaut-http-client-4.4.10.jar:4.4.10]
                at io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice.lambda$handleSynchronous$1(HttpClientIntroductionAdvice.java:233) ~[micronaut-http-client-core-4.4.10.jar:4.4.10]
                at io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice.handleBlockingCall(HttpClientIntroductionAdvice.java:620) ~[micronaut-http-client-core-4.4.10.jar:4.4.10]
                at io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice.handleSynchronous(HttpClientIntroductionAdvice.java:232) ~[micronaut-http-client-core-4.4.10.jar:4.4.10]
                at io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice.intercept(HttpClientIntroductionAdvice.java:195) ~[micronaut-http-client-core-4.4.10.jar:4.4.10]
                at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:138) ~[micronaut-aop-4.4.10.jar:4.4.10]
                at io.airbyte.api.server.forwardingClient.ConfigApiClient$Intercepted.getJobList(Unknown Source) ~[io.airbyte-airbyte-api-server-0.63.0.jar:?]
                at io.airbyte.api.server.services.JobServiceImpl.getJobList(JobService.kt:222) ~[io.airbyte-airbyte-api-server-0.63.0.jar:?]
                at io.airbyte.api.server.controllers.JobsController.listJobs$lambda$5(JobsController.kt:232) ~[io.airbyte-airbyte-api-server-0.63.0.jar:?]
                at io.airbyte.api.server.apiTracking.TrackingHelper.callWithTracker(TrackingHelper.kt:107) ~[io.airbyte-airbyte-api-server-0.63.0.jar:?]
                at io.airbyte.api.server.controllers.JobsController.listJobs(JobsController.kt:230) ~[io.airbyte-airbyte-api-server-0.63.0.jar:?]
                at io.airbyte.api.server.controllers.$JobsController$Definition$Exec.dispatch(Unknown Source) ~[io.airbyte-airbyte-api-server-0.63.0.jar:?]
                at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invokeUnsafe(AbstractExecutableMethodsDefinition.java:461) ~[micronaut-inject-4.4.10.jar:4.4.10]
                at io.micronaut.context.DefaultBeanContext$BeanContextUnsafeExecutionHandle.invokeUnsafe(DefaultBeanContext.java:4232) ~[micronaut-inject-4.4.10.jar:4.4.10]
                at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:271) ~[micronaut-router-4.4.10.jar:4.4.10]
                at io.micronaut.http.server.RouteExecutor.executeRouteAndConvertBody(RouteExecutor.java:488) ~[micronaut-http-server-4.4.10.jar:4.4.10]
                at io.micronaut.http.server.RouteExecutor.lambda$callRoute$6(RouteExecutor.java:465) ~[micronaut-http-server-4.4.10.jar:4.4.10]
                at io.micronaut.core.execution.ExecutionFlow.lambda$async$1(ExecutionFlow.java:87) ~[micronaut-core-4.4.10.jar:4.4.10]
                at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211) ~[micronaut-core-4.4.10.jar:4.4.10]
                at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211) ~[micronaut-core-4.4.10.jar:4.4.10]
                at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314) ~[?:?]
```

**Comment by descampsk** [comment]
This error is reproductible with the launcher script : 

```bash
# clone Airbyte from GitHub
git clone --depth=1 https://github.com/airbytehq/airbyte.git

# switch into Airbyte directory
cd airbyte

# start Airbyte
./run-ab-platform.sh

# GET jobs
curl http://airbyte:password@localhost:8006/v1/jobs?workspaceIds=688993b4-a749-4360-b372-1289600851e9&status=running

{"type":"about:blank","status":500}
```

**Comment by descampsk** [comment]
Still in v0.63.2

**Comment by benbauer-draeger** [comment]
any change someone could investigate the issue?

**Comment by descampsk** [comment]
I tried to investigate but without success to find the root cause :(

**Comment by marcosmarxm** [comment]
@descampsk @benbauer-draeger the team is working on a fix and will release it soon. Sorry for the lack of updates about the problem.

**Comment by tryangul** [comment]
I am able to reproduce an error (400 with a similar stack trace) in the 63.1 release using the curl @descampsk provided, but unable to do so with 63.2. Can anyone provide a fresh stack trace from  >= 63.2? 

There was an enum serialization fix that went out with 63.2, so I'm wondering if there's another issue / complication going here.

**Comment by JonsSpaghetti** [comment]
Can the folks on this thread try updating their URL from `localhost:8006` -> `localhost:8001/api/public` and let us know if that resolves the issue? We just tested on 63.2 and were able to confirm that the issue doesn't happen when making a call to the new URL but does happen with the old URL.

This means your URL will go from looking something like this: `localhost:8006/v1/connections` -> `localhost:8001/api/public/v1/connections`.

[Here's a page detailing what's going on](https://reference.airbyte.com/reference/standalone-server-deprecation-and-migration-to-airbyte-server), but the summary is that we have two versions of the Airbyte API right now and are planning to deprecate the one that you're referencing here. It seems as though some fixes that have gone into the new version have not made it into the old version that's being deprecated.

**Comment by daniel-ro** [comment]
@JonsSpaghetti changing the url for accessing the server instead of the deprecated api-server solves the issue for me, thanks!

**Comment by benbauer-draeger** [comment]
@JonsSpaghetti thanks for your solution. I could validate that it works for 63.5 as well.
Does anybody know whether this will be reflected in the Airflow provider package as the url now has the api/public part in it?

**Comment by JonsSpaghetti** [comment]
@benbauer-draeger I believe the Airflow operator uses the API that lives at `/api`, not the public API that lives at `/api/public` so for now that should not be affected as far as I'm aware.

**Comment by benbauer-draeger** [comment]
Yes, that's correct and with the change it's working. I just wanted to point out, that the default should probably be updated with one of the next updates :)

**Comment by JonsSpaghetti** [comment]
Our aim is to create a new version of the Airflow operator and submit it back to the project using the SDKs so that we use the Airbyte API and have supported auth mechanisms built in. I'm not sure that we have a public-facing ticket for that work, but it is represented on our board.

**Comment by descampsk** [comment]
@JonsSpaghetti I think we can close this issue.
Ok for everyone if I close it, localhost:8000/api/public/v1/connection seems to work fine ?
In the last version, :8006 does not exist anymore, so this issue seems not relevant anymore

**Comment by pmossman** [comment]
@descampsk thanks for confirming - closing as using the `/api/public/v1` endpoints on newer versions of Airbyte going forward should eliminate the problem reported in this issue
