### ISSUE TITLE
[source-amazon-seller-partner] GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE schema validation errors

### ISSUE THREAD

**Issue by zerobearing2** [airbytehq/airbyte#39502]
### Connector Name

source-amazon-seller-partner

### Connector Version

4.3.1

### What step the error happened?

During the sync

### Relevant information

Trying to extract return report into Bigquery, data is dropped due to schema validation errors during sync. Here is the destination metadata example:
```json
{
  "changes": [
    {
      "change": "NULLED",
      "field": "Order date",
      "reason": "DESTINATION_TYPECAST_ERROR"
    },
    {
      "change": "NULLED",
      "field": "Return request date",
      "reason": "DESTINATION_TYPECAST_ERROR"
    },
    {
      "change": "NULLED",
      "field": "Return delivery date",
      "reason": "DESTINATION_TYPECAST_ERROR"
    },
    {
      "change": "NULLED",
      "field": "SafeT claim creation time",
      "reason": "DESTINATION_TYPECAST_ERROR"
    }
  ],
  "sync_id": 0
}
```

### Relevant log output

```shell
2024-06-14 15:51:37 platform > Schema validation errors found for stream _GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE. Error messages: [$.Order date: 16-Mar-2024 is an invalid date-time, $.Order date: 17-Mar-2024 is an invalid date-time, $.Order date: 01-May-2024 is an invalid date-time, $.Return request date: 11-Jun-2024 is an invalid date-time, $.Return request date: 13-Jun-2024 is an invalid date-time, $.Order date: 16-Apr-2024 is an invalid date-time, $.Return request date: 12-Jun-2024 is an invalid date-time, $.Order date: 02-May-2024 is an invalid date-time, $.Order date: 06-May-2024 is an invalid date-time, $.Order date: 18-Apr-2024 is an invalid date-time, $.Order date: 21-May-2024 is an invalid date-time, $.Order date: 30-Apr-2024 is an invalid date-time, $.Order date: 31-May-2024 is an invalid date-time, $.Return request date: 14-Jun-2024 is an invalid date-time, $.Order date: 11-Mar-2024 is an invalid date-time, $.Order date: 12-Mar-2024 is an invalid date-time, $.Order date: 18-May-2024 is an invalid date-time, $.Order date: 15-May-2024 is an invalid date-time, $.Order date: 09-Jun-2024 is an invalid date-time, $.Order date: 08-Jun-2024 is an invalid date-time, $.Order date: 07-Jun-2024 is an invalid date-time, $.Order date: 19-May-2024 is an invalid date-time, $.Order date: 21-Apr-2024 is an invalid date-time, $.Order date: 06-Jun-2024 is an invalid date-time, $.Order date: 04-Jun-2024 is an invalid date-time, $.Order date: 05-Jun-2024 is an invalid date-time, $.Order date: 02-Jun-2024 is an invalid date-time, $.Order date: 03-Jun-2024 is an invalid date-time, $.Order date: 24-Apr-2024 is an invalid date-time, $.Order date: 01-Jun-2024 is an invalid date-time, $.Order date: 27-Apr-2024 is an invalid date-time, $.Order date: 13-Jun-2024 is an invalid date-time, $.Order date: 10-Jun-2024 is an invalid date-time, $.Order date: 22-Mar-2024 is an invalid date-time, $.Order date: 24-May-2024 is an invalid date-time, $.Order date: 12-Jun-2024 is an invalid date-time, $.Order date: 11-Jun-2024 is an invalid date-time, $.Order date: 25-May-2024 is an invalid date-time, $.Order date: 26-May-2024 is an invalid date-time, $.SafeT claim creation time:   is an invalid date-time, $.Order date: 29-May-2024 is an invalid date-time, $.Return delivery date:   is an invalid date-time, $.Order date: 28-May-2024 is an invalid date-time]
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Thanks for reporting the issue @zerobearing2 probably it will need to implement a transformer operation to this report update the datetime format for that field. Something similar to:
https://github.com/airbytehq/airbyte/blob/c7ecc41317cc93dc697821a54154ffad0676e2c1/airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py#L717-L727

**Comment by zerobearing2** [comment]
Still an issue on latest source v4.4.3, the `Return request date` fields ends up NULL in BigQuery.
```
Stack Trace: com.google.cloud.bigquery.BigQueryException: Query error: Invalid timestamp: '26-Jun-2024' at [2:1]
        at com.google.cloud.bigquery.Job.reload(Job.java:471)
        at io.airbyte.integrations.destination.bigquery.typing_deduping.BigQueryDestinationHandler.execute(BigQueryDestinationHandler.kt:147)
        at io.airbyte.integrations.base.destination.typing_deduping.TyperDeduperUtil.executeTypeAndDedupe(TyperDeduperUtil.kt:219)
        at io.airbyte.integrations.destination.bigquery.operation.BigQueryStorageOperation.typeAndDedupe(BigQueryStorageOperation.kt:164)
        at io.airbyte.integrations.base.destination.operation.AbstractStreamOperation.finalizeTable(AbstractStreamOperation.kt:406)
        at io.airbyte.integrations.base.destination.operation.DefaultSyncOperation.finalizeStreams$lambda$9$lambda$8(DefaultSyncOperation.kt:138)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```
