### ISSUE TITLE
Weaviate destination with 'Default Vectorizer' none failure

### ISSUE THREAD

**Issue by vade** [airbytehq/airbyte#39596]
### Connector Name

destination-weaviate

### Connector Version

0.2.19

### What step the error happened?

Configuring a new connector

### Relevant information

We are using a 'bring your own embeddings' to Weaviate - our setup has embeddings stored in Postgres via PGVector. We are looking to sync to Weaviate, and choose the Embedding -> `No External embedding` option  and `default vecotirzer` to None

`Can't instantiate abstract class NoEmbedder with abstract method embed_document`

Attempting to set 'Do not store raw text' also throws the same error. 

### Relevant log output

```shell
2024-06-19 16:01:55 [46mplatform[0m > Docker volume job log path: /tmp/workspace/87104844-0524-4d1e-aa2c-90a216cb2cd9/0/logs.log
2024-06-19 16:01:55 [46mplatform[0m > Executing worker wrapper. Airbyte version: 0.63.1
2024-06-19 16:01:55 [46mplatform[0m > 
2024-06-19 16:01:55 [46mplatform[0m > Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2024-06-19 16:01:55 [46mplatform[0m > Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2024-06-19 16:01:55 [46mplatform[0m > ----- START CHECK -----
2024-06-19 16:01:55 [46mplatform[0m > Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2024-06-19 16:01:55 [46mplatform[0m > 
2024-06-19 16:01:55 [46mplatform[0m > Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2024-06-19 16:01:55 [46mplatform[0m > Checking if airbyte/destination-weaviate:0.2.19 exists...
2024-06-19 16:01:55 [46mplatform[0m > airbyte/destination-weaviate:0.2.19 was found locally.
2024-06-19 16:01:55 [46mplatform[0m > Creating docker container = destination-weaviate-check-87104844-0524-4d1e-aa2c-90a216cb2cd9-0-rzefn with resources io.airbyte.config.ResourceRequirements@1ef466d4[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts null
2024-06-19 16:01:55 [46mplatform[0m > Preparing command: docker run --rm --init -i -w /data/87104844-0524-4d1e-aa2c-90a216cb2cd9/0 --log-driver none --name destination-weaviate-check-87104844-0524-4d1e-aa2c-90a216cb2cd9-0-rzefn --network host -v airbyte_workspace:/data -v oss_local_root:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/destination-weaviate:0.2.19 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e FIELD_SELECTION_WORKSPACES= -e USE_STREAM_CAPABLE_STATE=true -e WORKER_ENVIRONMENT=DOCKER -e AIRBYTE_ROLE=dev -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=0 -e OTEL_COLLECTOR_ENDPOINT=http://host.docker.internal:4317 -e FEATURE_FLAG_CLIENT=config -e AIRBYTE_VERSION=0.63.1 -e WORKER_JOB_ID=87104844-0524-4d1e-aa2c-90a216cb2cd9 airbyte/destination-weaviate:0.2.19 check --config source_config.json
2024-06-19 16:01:55 [46mplatform[0m > Reading messages from protocol version 0.2.0
2024-06-19 16:01:56 [46mplatform[0m > Can't instantiate abstract class NoEmbedder with abstract method embed_documents
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 11, in <module>
    DestinationWeaviate().run(sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/destinations/destination.py", line 119, in run
    for message in output_messages:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/destinations/destination.py", line 109, in run_cmd
    yield self._run_check(config=config)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/destinations/destination.py", line 32, in _run_check
    check_result = self.check(logger, config)
  File "/airbyte/integration_code/destination_weaviate/destination.py", line 49, in check
    self._init_indexer(parsed_config)
  File "/airbyte/integration_code/destination_weaviate/destination.py", line 29, in _init_indexer
    else NoEmbedder(config.embedding)
TypeError: Can't instantiate abstract class NoEmbedder with abstract method embed_documents
2024-06-19 16:01:56 [46mplatform[0m > Check connection job subprocess finished with exit code 1
2024-06-19 16:01:56 [46mplatform[0m > 
2024-06-19 16:01:56 [46mplatform[0m > ----- END CHECK -----
2024-06-19 16:01:56 [46mplatform[0m > 
```
```


### Contribute

- [X] Yes, I want to contribute

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.
