### ISSUE TITLE
[source-file] Error reading zipped CSV file with latin-1 encoding

### ISSUE THREAD

**Issue by chenriquealvarenga** [airbytehq/airbyte#39606]
### Connector Name

source-file

### Connector Version

0.5.2

### What step the error happened?

During the sync

### Relevant information

I encountered an error when trying to read a zipped CSV file using Latin-1 encoding. Below is the configuration I used (the data is open, so feel free to try):
```json
{
    "url": "https://dados.rfb.gov.br/CNPJ/Cnaes.zip",
    "format": "csv",
    "provider": {
        "storage": "HTTPS",
        "user_agent": false
    },
    "dataset_name": "cnaes",
    "reader_options": "{\"sep\": \";\", \"names\": [\"codigo\", \"descricao\"], \"encoding\": \"latin-1\"}"
}
```
The process fails during the check and discovery phases inside the `_cache_stream` method with the error: `TypeError: a bytes-like object is required, not 'str'`.
I think the problem is that when smart_open.open is called with mode="rb" **and** an encoding, the file is actually opened in "r" mode. This means it is trying to decode the zip file before it is extracted.
We could include a new condition in URLFile's self.args to only define encoding if the file is not zip/binary, something like this:
```python
self.args = {
    "mode": "rb" if binary else "r",
    "encoding": None if binary else encoding, #modified
}
```
That way, zip/binary files would always be opened in "rb" mode, and the encoding parameter, if defined in reader_options, would be used only by pandas when reading the extracted data.
Following this suggestion, we would also need to modify the `_unzip` method to open the extracted file in "rb" mode, so it can work for all sorts of files. If we have a zipped binary file, like an excel, it currently tries to open it in "r" mode after extracting, leading to a decoding error. Change from:
```python
fp_tmp = open(final_file, "r")
```
To:
```python
fp_tmp = open(final_file, "rb")
```
If the extracted file is not binary, like the csv I'm trying to read, it will still work fine because pandas will handle the decoding later on.

### Relevant log output

```shell
2024-06-20 01:52:13 INFO i.a.w.i.VersionedAirbyteStreamFactory(create):107 - Reading messages from protocol version 0.2.0
2024-06-20 01:52:18 INFO i.a.w.i.DefaultAirbyteStreamFactory(internalLog):167 - TransportParams: None
2024-06-20 01:52:18 ERROR i.a.w.i.DefaultAirbyteStreamFactory(internalLog):163 - Failed to load https://dados.rfb.gov.br/CNPJ/Cnaes.zip. Please check File Format and Reader Options are set correctly.
TypeError("a bytes-like object is required, not 'str'")
2024-06-20 01:52:18 ERROR i.a.w.i.DefaultAirbyteStreamFactory(internalLog):163 - Failed to load https://dados.rfb.gov.br/CNPJ/Cnaes.zip. Please check File Format and Reader Options are set correctly.
Traceback (most recent call last):
  File "/airbyte/integration_code/source_file/source.py", line 134, in check
    list(client.streams(empty_schema=True))
  File "/airbyte/integration_code/source_file/client.py", line 503, in streams
    "properties": self._stream_properties(fp, empty_schema=empty_schema, read_sample_chunk=True),
  File "/airbyte/integration_code/source_file/client.py", line 475, in _stream_properties
    fp = self._cache_stream(fp)
  File "/airbyte/integration_code/source_file/client.py", line 461, in _cache_stream
    fp_tmp.write(fp.read())
  File "/usr/local/lib/python3.9/tempfile.py", line 494, in func_wrapper
    return func(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 8, in <module>
    run()
  File "/airbyte/integration_code/source_file/run.py", line 14, in run
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 235, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 115, in run
    yield from map(AirbyteEntrypoint.airbyte_message_to_string, self.check(source_spec, config))
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 139, in check
    check_result = self.source.check(self.logger, config)
  File "/airbyte/integration_code/source_file/source.py", line 139, in check
    raise AirbyteTracedException(message=reason, internal_message=reason, failure_type=FailureType.config_error)
airbyte_cdk.utils.traced_exception.AirbyteTracedException: Failed to load https://dados.rfb.gov.br/CNPJ/Cnaes.zip. Please check File Format and Reader Options are set correctly.
2024-06-20 01:52:19 WARN i.a.w.g.DefaultCheckConnectionWorker(run):107 - Check connection job subprocess finished with exit code 1
2024-06-20 01:52:19 INFO i.a.w.t.TemporalAttemptExecution(get):163 - Stopping cancellation check scheduling...
2024-06-20 01:52:19 INFO i.a.c.i.LineGobbler(voidCall):114 - 
2024-06-20 01:52:19 INFO i.a.c.i.LineGobbler(voidCall):114 - ----- END CHECK -----
2024-06-20 01:52:19 INFO i.a.c.i.LineGobbler(voidCall):114 -
```

### Contribute

- [X] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
@chenriquealvarenga, please contact me on Slack if you need help contributing.
