### ISSUE TITLE
[GCS Destination] State code: SignatureDoesNotMatch; Message: Access denied

### ISSUE THREAD

**Issue by prashant6592** [airbytehq/airbyte#40209]
### Connector Name

destination-gcs

### Connector Version

0.4.6

### What step the error happened?

Configuring a new connector

### Relevant information

Trying to test GCS as destination. 
Added a service account, gave Storage Admin and Storage Object Admin role both, created keys and then added the client_email and private_key in airbyte correctly. 

Bucket path has a trailing `/`. 

My bucket is Multi-region, supports google managed encryption key. 

Heres the error I am getting all the time 

```
Configuration check failed
State code: SignatureDoesNotMatch; Message: Access denied. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: null; S3 Extended Request ID: null; Proxy: null)
``` 

### Relevant log output

```shell
2024-06-22 08:14:45 [32mINFO[m i.a.w.l.p.s.m.Stage(apply):39 - APPLY Stage: CLAIM — (workloadId = ca8f6566-e555-4b40-943a-545bf123117a_7b35acaa-6d0d-479c-a20e-32a5c5fa2c55_0_check) — (dataplaneId = gcp-us-expanded-queue-1)
2024-06-22 08:14:54 [32mINFO[m i.a.c.i.LineGobbler(voidCall):165 - 
2024-06-22 08:14:54 [32mINFO[m i.a.c.i.LineGobbler(voidCall):165 - ----- START CHECK -----
2024-06-22 08:14:54 [32mINFO[m i.a.c.i.LineGobbler(voidCall):165 - 
2024-06-22 08:15:03 [32mINFO[m i.a.c.ConnectorWatcher(run):82 - Connector exited, processing output
2024-06-22 08:15:03 [32mINFO[m i.a.c.ConnectorWatcher(run):85 - Output file jobOutput.json found
2024-06-22 08:15:03 [32mINFO[m i.a.c.ConnectorWatcher(run):91 - Connector exited with 0
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(create):189 - Reading messages from protocol version 0.2.0
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(logMalformedLogMessage):390 - 2024-06-22T08:15:00,920`[32mINFO[m`i.a.c.i.b.IntegrationCliParser(parseOptions):126 - integration args: {check=null, config=/config/connectionConfiguration.json}
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(logMalformedLogMessage):390 - 2024-06-22T08:15:00,926`[32mINFO[m`i.a.c.i.b.IntegrationRunner(runInternal):132 - Running integration: io.airbyte.integrations.destination.gcs.GcsDestination
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(logMalformedLogMessage):390 - 2024-06-22T08:15:00,926`[32mINFO[m`i.a.c.i.b.IntegrationRunner(runInternal):133 - Command: CHECK
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(logMalformedLogMessage):390 - 2024-06-22T08:15:00,927`[32mINFO[m`i.a.c.i.b.IntegrationRunner(runInternal):134 - Integration config: IntegrationConfig{command=CHECK, configPath='/config/connectionConfiguration.json', catalogPath='null', statePath='null'}
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(logMalformedLogMessage):390 - 2024-06-22T08:15:01,096`[33mWARN[m`c.n.s.JsonMetaSchema(newValidator):278 - Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(logMalformedLogMessage):390 - 2024-06-22T08:15:01,099`[33mWARN[m`c.n.s.JsonMetaSchema(newValidator):278 - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(logMalformedLogMessage):390 - 2024-06-22T08:15:01,102`[33mWARN[m`c.n.s.JsonMetaSchema(newValidator):278 - Unknown keyword requires - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(logMalformedLogMessage):390 - 2024-06-22T08:15:01,117`[32mINFO[m`i.a.c.i.d.s.S3FormatConfigs(getS3FormatConfig):22 - S3 format config: {"format_type":"CSV","flattening":"No flattening","compression":{"compression_type":"No Compression"}}
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(logMalformedLogMessage):390 - 2024-06-22T08:15:01,641`[32mINFO[m`i.a.c.i.d.s.S3BaseChecks(testSingleUpload):40 - Started testing if all required credentials assigned to user for single file uploading
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(logMalformedLogMessage):390 - 2024-06-22T08:15:02,925`[1;31mERROR[m`i.a.c.i.d.g.BaseGcsDestination(check):55 - Exception attempting to access the Gcs bucket
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(logMalformedLogMessage):390 - com.amazonaws.services.s3.model.AmazonS3Exception: Access denied. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: null; S3 Extended Request ID: null; Proxy: null)
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(logMalformedLogMessage):390 - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879) ~[aws-java-sdk-core-1.12.647.jar:?]
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(logMalformedLogMessage):390 - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418) ~[aws-java-sdk-core-1.12.647.jar:?]
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(logMalformedLogMessage):390 - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387) ~[aws-java-sdk-core-1.12.647.jar:?]
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(logMalformedLogMessage):390 - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157) ~[aws-java-sdk-core-1.12.647.jar:?]
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(logMalformedLogMessage):390 - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814) ~[aws-java-sdk-core-1.12.647.jar:?]
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(logMalformedLogMessage):390 - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781) ~[aws-java-sdk-core-1.12.647.jar:?]
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(logMalformedLogMessage):390 - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755) ~[aws-java-sdk-core-1.12.647.jar:?]
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(logMalformedLogMessage):390 - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715) ~[aws-java-sdk-core-1.12.647.jar:?]
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(logMalformedLogMessage):390 - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697) ~[aws-java-sdk-core-1.12.647.jar:?]
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(logMalformedLogMessage):390 - 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561) ~[aws-java-sdk-core-1.12.647.jar:?]
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(logMalformedLogMessage):390 - 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541) ~[aws-java-sdk-core-1.12.647.jar:?]
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(logMalformedLogMessage):390 - 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5520) ~[aws-java-sdk-s3-1.12.647.jar:?]
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(logMalformedLogMessage):390 - 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5467) ~[aws-java-sdk-s3-1.12.647.jar:?]
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(logMalformedLogMessage):390 - 	at com.amazonaws.services.s3.AmazonS3Client.deleteObject(AmazonS3Client.java:2332) ~[aws-java-sdk-s3-1.12.647.jar:?]
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(logMalformedLogMessage):390 - 	at com.amazonaws.services.s3.AmazonS3Client.deleteObject(AmazonS3Client.java:2316) ~[aws-java-sdk-s3-1.12.647.jar:?]
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(logMalformedLogMessage):390 - 	at io.airbyte.cdk.integrations.destination.s3.S3BaseChecks.testSingleUpload(S3BaseChecks.java:46) ~[airbyte-cdk-s3-destinations-0.20.8.jar:?]
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(logMalformedLogMessage):390 - 	at io.airbyte.cdk.integrations.destination.gcs.BaseGcsDestination.check(BaseGcsDestination.java:48) [airbyte-cdk-gcs-destinations-0.20.8.jar:?]
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(logMalformedLogMessage):390 - 	at io.airbyte.cdk.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:153) [airbyte-cdk-core-0.20.8.jar:?]
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(logMalformedLogMessage):390 - 	at io.airbyte.cdk.integrations.base.IntegrationRunner.run(IntegrationRunner.java:125) [airbyte-cdk-core-0.20.8.jar:?]
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(logMalformedLogMessage):390 - 	at io.airbyte.integrations.destination.gcs.GcsDestination.main(GcsDestination.java:16) [io.airbyte.airbyte-integrations.connectors-destination-gcs-0.50.50.jar:?]
2024-06-22 08:15:03 [33mWARN[m i.a.m.l.MetricClientFactory(getMetricClient):43 - MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-06-22 08:15:03 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(logMalformedLogMessage):390 - 2024-06-22T08:15:02,979`[32mINFO[m`i.a.c.i.b.IntegrationRunner(runInternal):231 - Completed integration: io.airbyte.integrations.destination.gcs.GcsDestination
2024-06-22 08:15:03 [32mINFO[m i.a.c.ConnectorMessageProcessor(updateConfigFromControlMessage):231 - Checking for optional control message...
2024-06-22 08:15:03 [32mINFO[m i.a.c.ConnectorMessageProcessor(updateConfigFromControlMessage):253 - Optional control message not found. Skipping...
2024-06-22 08:15:03 [32mINFO[m i.a.c.ConnectorWatcher(run):129 - Writing output of ca8f6566-e555-4b40-943a-545bf123117a_7b35acaa-6d0d-479c-a20e-32a5c5fa2c55_0_check to the doc store
2024-06-22 08:15:03 [32mINFO[m i.a.c.ConnectorWatcher(run):131 - Marking workload as successful
2024-06-22 08:15:03 [32mINFO[m i.a.c.i.LineGobbler(voidCall):165 - 
2024-06-22 08:15:03 [32mINFO[m i.a.c.ConnectorWatcher(exitProperly):181 - Deliberately exiting process with code 0.
2024-06-22 08:15:03 [32mINFO[m i.a.c.i.LineGobbler(voidCall):165 - ----- END CHECK -----
2024-06-22 08:15:03 [32mINFO[m i.a.c.i.LineGobbler(voidCall):165 -
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Thanks for reporting the issue @prashant6592 Destination GCS is a community connector and it isn’t in the current roadmap for improvements. If you want to contribute fixing the issue please reach me out in Slack so I can provide you instructions to make the contribution.

**Comment by kev-datams** [comment]
Hi @marcosmarxm, is there any ETA regarding the prioritization of the destination GCS ? 🙏

**Comment by marv90** [comment]
I had the same error with bigQuery destination and GCS Staging loading method.

The problem was the slash at the beginning of the GCS Bucket Path.
So I think it currently impossible to write in the root folder of the bucket.

Just type a folder name without a slash at the beginning.
The error message is awful though and the input field is required.

**Comment by kathywang** [comment]
Hi @marv90, I have tried the GCS Bucket Path without a slash at the beginning, I am still getting below error:
Configuration check failed
State code: SignatureDoesNotMatch; Message: Access denied. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: null; S3 Extended Request ID: null; Proxy: null)

**Comment by kev-datams** [comment]
Hi @prashant6592, please could you indicate which PR solved this issue ? 🙏
