### ISSUE TITLE
[GCS] Could not find image: airbyte/source-gcs:0.4.X

### ISSUE THREAD

**Issue by rcourivaud** [airbytehq/airbyte#40219]
### Connector Name

GCS

### Connector Version

0.4.2

### What step the error happened?

Configuring a new connector

### Relevant information

Could not find image: airbyte/source-gcs:0.4.3

### Relevant log output

```shell
io.temporal.failure.ActivityFailure: Activity with activityType='RunWithJobOutput' failed: 'Activity task failed'. scheduledEventId=12, startedEventId=13, activityId=e06afa68-4c22-33f8-84d4-ffa984f25f76, identity='1@e9feece09fce', retryState=RETRY_STATE_MAXIMUM_ATTEMPTS_REACHED
	at java.base/java.lang.Thread.getStackTrace(Thread.java:2450)
	at io.temporal.internal.sync.ActivityStubBase.execute(ActivityStubBase.java:49)
	at io.temporal.internal.sync.ActivityInvocationHandler.lambda$getActivityFunc$0(ActivityInvocationHandler.java:83)
	at io.temporal.internal.sync.ActivityInvocationHandlerBase.invoke(ActivityInvocationHandlerBase.java:60)
	at jdk.proxy2/jdk.proxy2.$Proxy87.runWithJobOutput(Unknown Source)
	at io.airbyte.workers.temporal.check.connection.CheckConnectionWorkflowImpl.run(CheckConnectionWorkflowImpl.java:55)
	at CheckConnectionWorkflowImplProxy.run$accessor$FD88Fcmn(Unknown Source)
	at CheckConnectionWorkflowImplProxy$auxiliary$dqpOP2GJ.call(Unknown Source)
	at io.airbyte.micronaut.temporal.TemporalActivityStubInterceptor.execute(TemporalActivityStubInterceptor.java:79)
	at CheckConnectionWorkflowImplProxy.run(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation$RootWorkflowInboundCallsInterceptor.execute(POJOWorkflowImplementationFactory.java:339)
	at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation.execute(POJOWorkflowImplementationFactory.java:314)
	at io.temporal.internal.sync.WorkflowExecutionHandler.runWorkflowMethod(WorkflowExecutionHandler.java:70)
	at io.temporal.internal.sync.SyncWorkflow.lambda$start$0(SyncWorkflow.java:135)
	at io.temporal.internal.sync.CancellationScopeImpl.run(CancellationScopeImpl.java:102)
	at io.temporal.internal.sync.WorkflowThreadImpl$RunnableWrapper.run(WorkflowThreadImpl.java:107)
	at io.temporal.worker.ActiveThreadReportingExecutor.lambda$submit$0(ActiveThreadReportingExecutor.java:53)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
This error is not a connector problem. Please open a new issue reporting a platform issue.
