### ISSUE TITLE
[source-gitlab] Schema validator failed

### ISSUE THREAD

**Issue by hugovandernotte** [airbytehq/airbyte#40620]
### Connector Name

source-gitlab

### Connector Version

4.04

### What step the error happened?

During the sync

### Relevant information

Since the 27th June, we are not able to run the Gitlab sync. It seems there is an issue with the schema validation.
The sync fails with any streams having an id column

### Relevant log output

```shell
com.networknt.schema.JsonSchemaException: java.lang.UnsupportedOperationException: No suitable validator for id
        at com.networknt.schema.JsonMetaSchema.newValidator(JsonMetaSchema.java:508) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.ValidationContext.newValidator(ValidationContext.java:62) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.read(JsonSchema.java:467) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.getValidators(JsonSchema.java:1085) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.<init>(JsonSchema.java:150) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.from(JsonSchema.java:66) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchemaFactory.doCreate(JsonSchemaFactory.java:313) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchemaFactory.create(JsonSchemaFactory.java:309) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.ValidationContext.newSchema(ValidationContext.java:57) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.PropertiesValidator.<init>(PropertiesValidator.java:52) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.ValidatorTypeCode.newValidator(ValidatorTypeCode.java:163) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonMetaSchema.newValidator(JsonMetaSchema.java:496) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.ValidationContext.newValidator(ValidationContext.java:62) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.read(JsonSchema.java:467) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.getValidators(JsonSchema.java:1085) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.<init>(JsonSchema.java:150) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.from(JsonSchema.java:66) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchemaFactory.doCreate(JsonSchemaFactory.java:313) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchemaFactory.create(JsonSchemaFactory.java:309) ~[json-schema-validator-1.4.0.jar:?]
        at io.airbyte.validation.json.JsonSchemaValidator.getSchemaValidator(JsonSchemaValidator.java:220) ~[io.airbyte-airbyte-json-validation-dev.jar:?]
        at io.airbyte.validation.json.JsonSchemaValidator.initializeSchemaValidator(JsonSchemaValidator.java:81) ~[io.airbyte-airbyte-json-validation-dev.jar:?]
        at io.airbyte.workers.RecordSchemaValidator.<init>(RecordSchemaValidator.java:64) ~[io.airbyte-airbyte-commons-worker-dev.jar:?]
        at io.airbyte.workers.RecordSchemaValidator.<init>(RecordSchemaValidator.java:46) ~[io.airbyte-airbyte-commons-worker-dev.jar:?]
        at io.airbyte.workers.RecordSchemaValidator.<init>(RecordSchemaValidator.java:41) ~[io.airbyte-airbyte-commons-worker-dev.jar:?]
        at io.airbyte.workers.general.ReplicationWorkerFactory.createRecordSchemaValidator(ReplicationWorkerFactory.java:288) ~[io.airbyte-airbyte-commons-worker-dev.jar:?]
        at io.airbyte.workers.general.ReplicationWorkerFactory.create(ReplicationWorkerFactory.java:150) ~[io.airbyte-airbyte-commons-worker-dev.jar:?]
        at io.airbyte.container_orchestrator.orchestrator.ReplicationJobOrchestrator.runJob(ReplicationJobOrchestrator.java:118) ~[io.airbyte-airbyte-container-orchestrator-dev.jar:?]
        at io.airbyte.container_orchestrator.Application.run(Application.java:78) [io.airbyte-airbyte-container-orchestrator-dev.jar:?]
        at io.airbyte.container_orchestrator.Application.main(Application.java:38) [io.airbyte-airbyte-container-orchestrator-dev.jar:?]
Caused by: java.lang.UnsupportedOperationException: No suitable validator for id
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by hugovandernotte** [comment]
It seems to have been fixed :)
