### ISSUE TITLE
[source-MongoDB] connector is getting BufferedReplicationWorker(readFromSource) exception

### ISSUE THREAD

**Issue by AronsonDan** [airbytehq/airbyte#41018]
### Connector Name

source-mongodb

### Connector Version

1.4.2

### What step the error happened?

During the sync

### Relevant information

Mongo source is constantly throwing errors on `readFromSource`

### Relevant log output

```shell
2024-07-07 14:25:23 replication-orchestrator > readFromSource: source exception
io.airbyte.workers.internal.exception.SourceException: Source process exited with non-zero exit code 2
        at io.airbyte.workers.general.BufferedReplicationWorker.readFromSource(BufferedReplicationWorker.java:365) ~[io.airbyte-airbyte-commons-worker-0.50.38.jar:?]
        at io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsyncWithHeartbeatCheck$3(BufferedReplicationWorker.java:235) ~[io.airbyte-airbyte-commons-worker-0.50.38.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
```


### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
@AronsonDan can you share the complete sync log file?

**Comment by AronsonDan** [comment]
@marcosmarxm Just added :-)
[68c1d0e2_4cc2_43bc_b5db_99b9f5cea75d_job_71651_attempt_5_txt.txt](https://github.com/user-attachments/files/16139208/68c1d0e2_4cc2_43bc_b5db_99b9f5cea75d_job_71651_attempt_5_txt.txt)

**Comment by AronsonDan** [comment]
@marcosmarxm We have been seeing the following behavior:

- The sync is running smoothly
- at a certain point of time it starts to show `101 records extracted`
- looking at the logs of the sync, I can see silent error that dosent fail the sync

[68c1d0e2_4cc2_43bc_b5db_99b9f5cea75d_job_71501_attempt_1_txt.txt](https://github.com/user-attachments/files/16139367/68c1d0e2_4cc2_43bc_b5db_99b9f5cea75d_job_71501_attempt_1_txt.txt)

Attaching the log 
![image](https://github.com/airbytehq/airbyte/assets/22011236/7dc55d09-3f92-4c06-9cdb-b0149f93edea)

**Comment by akashkulk** [comment]
Interesting. This seems to be an issue with debezium. 

During shutdown, we are seeing that debezium shuts down correctly but still has a orphaned thread running which does not shut down correctly because it's waiting on some internal lock. 

@AronsonDan can you try increasing the timeout here and trying again?

**Comment by AronsonDan** [comment]
@akashkulk How do I do that?

**Comment by akashkulk** [comment]
It's the Initial Waiting Time in Seconds (Advanced) section : 
<img width="1195" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzRTQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7495e278a03226321a95212fa505d7f95caec71f/image.png" alt="image.png" />

**Comment by AronsonDan** [comment]
It certainly made that much better :-)

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 180 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
