### ISSUE TITLE
[helm] Timeout when working with Karpenter (Spot Instances)

### ISSUE THREAD

**Issue by dorsegal** [airbytehq/airbyte#41059]
### Helm Chart Version

0.263.0

### What step the error happened?

Other

### Relevant information

I have karpenter in my EKS cluster for better node management. The issue is wherever new job is triggered, orchestrator container can get time out before source-read/destination-write spinning up duo to node provisioning times. 
I could not find a way to tune this setting in Airbyte.

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 180 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.

**Comment by GideonStowell** [comment]
It's helpful context to know that this is resolved when using airbyte 1.0+, btw.

**Comment by luizfelmach** [comment]
I'm also encountering the same error here when working with Karpenter AWS Spot Instances. When I launch the Karpenter nodes in ON_DEMAND mode, it works. It also works when I use an AWS-managed Spot instance. This suggests that the issue may not be with Airbyte itself. However, it's strange, because Airbyte should work regardless of whether it’s running on a Spot instance or not.

The specific log that appears in the bootloader is the following:

```
ERROR	i.a.b.ApplicationKt(main):28 - Unable to bootstrap Airbyte environment.
io.fabric8.kubernetes.client.KubernetesClientException: The timeout period of 10000ms has been exceeded while executing PUT /api/v1/namespaces/airbyte-test/secrets/airbyte-auth-secrets for server null
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:509)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:524)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleUpdate(OperationSupport.java:358)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleUpdate(BaseOperation.java:759)
	at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.update(HasMetadataOperation.java:138)
	at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.update(HasMetadataOperation.java:121)
	at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.update(HasMetadataOperation.java:44)
	at io.fabric8.kubernetes.client.extension.ResourceAdapter.update(ResourceAdapter.java:345)
	at io.airbyte.bootloader.K8sSecretHelper.createOrUpdateSecret(K8sSecretHelper.kt:52)
	at io.airbyte.bootloader.AuthKubernetesSecretInitializer.initializeSecrets(AuthKubernetesSecretInitializer.kt:34)
	at io.airbyte.bootloader.Bootloader.load(Bootloader.kt:76)
	at io.airbyte.bootloader.ApplicationKt.main(Application.kt:25)
Caused by: io.vertx.core.impl.NoStackTraceTimeoutException: The timeout period of 10000ms has been exceeded while executing PUT /api/v1/namespaces/airbyte-test/secrets/airbyte-auth-secrets for server null
```
