### ISSUE TITLE
[source-adjust] time date format is wrong after migration to lowcode

### ISSUE THREAD

**Issue by tim-werner** [airbytehq/airbyte#41054]
### Connector Name

source-adjust

### Connector Version

0.1.4, 0.1.5,0.1.6

### What step the error happened?

Configuring a new connector

### Relevant information

The time date format that is passed to the adjust API is wrong. The adjust connector passes a date '%Y-%m-%d' to the API but the API expects the format like '%Y-%m-%dT%H:%M:%SZ'.

The fix would be possible to change the manifest.yaml for the DatetimeBasedCursor from datetime_format: "%Y-%m-%d" to datetime_format: "%Y-%m-%dT%H:%M:%SZ".

### Relevant log output

```shell
Encountered an error trying to connect to stream AdjustReport. Error:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/checks/check_stream.py", line 42, in check_connection
stream_is_available, reason = availability_strategy.check_availability(stream, logger, source)
File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/availability_strategy.py", line 36, in check_availability
stream_slice = get_first_stream_slice(stream)
File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/utils/stream_helper.py", line 21, in get_first_stream_slice
stream.stream_slices(
File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py", line 148, in stream_slices
return self.retriever.stream_slices()
File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 378, in stream_slices
return self.stream_slicer.stream_slices()
File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py", line 168, in stream_slices
start_datetime = self._calculate_earliest_possible_value(self._select_best_end_datetime())
File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py", line 173, in _calculate_earliest_possible_value
earliest_possible_start_datetime = min(self._start_datetime.get_datetime(self.config), end_datetime)
File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/datetime/min_max_datetime.py", line 58, in get_datetime
time = self._parser.parse(str(self.datetime.eval(config, **additional_parameters)), datetime_format) # type: ignore # datetime is always cast to an interpolated string
File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/datetime/datetime_parser.py", line 33, in parse
parsed_datetime = datetime.datetime.strptime(str(date), format)
File "/usr/local/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
tt, fraction, gmtoff_fraction = _strptime(data_string, format)
File "/usr/local/lib/python3.9/_strptime.py", line 349, in _strptime
raise ValueError("time data %r does not match format %r" %
ValueError: time data '2024-07-01' does not match format '%Y-%m-%dT%H:%M:%SZ'
```

### Contribute

- [X] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Thanks for the quick fix @tim-werner

**Comment by yb-yu** [comment]
This fix still doesn't make the Adjust source work.

The format of the Adjust still expects **date**. Please refer to the following [API documentation.](https://dev.adjust.com/en/api/rs-api/reports)

The actual issue triggerd by the date format expected by airbyte .

I just opened a [additional PR](https://github.com/airbytehq/airbyte/pull/45226) to modify the test cases and the manifest.yaml.

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 180 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.

**Comment by pridemon** [comment]
Connector is still not work

**Comment by hasanozciftcii** [comment]
I am getting the error; anybody has an update?

```
2025-08-22 15:59:43  ERROR 2025-08-22 15:59:43 error Encountered an error trying to connect to stream AdjustReport. Error: 
 Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/checks/check_stream.py", line 42, in check_connection
    stream_is_available, reason = availability_strategy.check_availability(stream, logger, source)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/streams/http/availability_strategy.py", line 36, in check_availability
    stream_slice = get_first_stream_slice(stream)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/streams/utils/stream_helper.py", line 21, in get_first_stream_slice
    stream.stream_slices(
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py", line 148, in stream_slices
    return self.retriever.stream_slices()
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 378, in stream_slices
    return self.stream_slicer.stream_slices()
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py", line 167, in stream_slices
    end_datetime = self._select_best_end_datetime()
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py", line 181, in _select_best_end_datetime
    return min(self._end_datetime.get_datetime(self.config), now)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/datetime/min_max_datetime.py", line 58, in get_datetime
    time = self._parser.parse(str(self.datetime.eval(config, **additional_parameters)), datetime_format)  # type: ignore # datetime is always cast to an interpolated string
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/interpolation/interpolated_string.py", line 40, in eval
    return self._interpolation.eval(self.string, config, self.default, parameters=self._parameters, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/interpolation/jinja.py", line 91, in eval
    return self._literal_eval(self._eval(default, context), valid_types)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/interpolation/jinja.py", line 109, in _eval
    return self._environment.from_string(s).render(context)  # type: ignore # from_string is able to handle None
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.10/site-packages/jinja2/utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'strftime'
```
