### ISSUE TITLE
[source-outreach] HTTP 404 during pagination

### ISSUE THREAD

**Issue by dwisdom-tk** [airbytehq/airbyte#41107]
### Connector Name

source-outreach

### Connector Version

1.0.4

### What step the error happened?

During the sync

### Relevant information

Any stream that doesn't require pagination works perfectly. When a stream does require pagination, it gets the first 1000 records fine. When it goes to get the next 1000 records, the connector gets an HTTP 404 error.

It looks like the paginator is sending requests to `api.outreach.io/<stream>` instead of sending them to `api.outreach.io/api/v2/<stream>`. It also looks like it's using Python 3.9. That's a little surprising but I don't know whether it matters. Those are the only things I noticed in the logs.

Here are Outreach's docs about how their pagination works:
https://developers.outreach.io/api/making-requests/#cursor-based-pagination

airbyte version: 0.63.5
source-outreach version: 1.0.4

Airbyte is self-hosted on K8s and deployed using Airbyte's Helm chart.

### Relevant log output

```shell
2024-07-09 18:14:05 platform > Executing worker wrapper. Airbyte version: 0.63.5

[...]

2024-07-09 18:14:05 platform > Attempting to start pod = source-outreach-check-10552-0-vsmqm for airbyte/source-outreach:1.0.4

[...]

2024-07-09 18:15:47 source > Encountered an exception while reading stream accounts
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 135, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 230, in _read_stream
    for record_data_or_message in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/core.py", line 169, in read
    for record_data_or_message in records:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py", line 126, in read_records
    yield from self.retriever.read_records(self.get_json_schema(), stream_slice)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 327, in read_records
    for stream_data in self._read_pages(record_generator, self.state, _slice):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 291, in _read_pages
    response = self._fetch_next_page(stream_state, stream_slice, next_page_token)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 266, in _fetch_next_page
    return self.requester.send_request(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 461, in send_request
    return self._validate_response(response)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 566, in _validate_response
    raise ReadException(error_message)
airbyte_cdk.sources.declarative.exceptions.ReadException: Request to https://api.outreach.io/accounts?count=false&page%5Bafter%5D=eyJjbiI6IkFwaVYyOjpBY2NvdW50c0NvbnRyb2xsZXIiLCJzcCI6InVwZGF0ZWRBdCIsInN2IjpbIjIwMjQtMDUtMjBUMTk6NDM6MDUuMDAwWiJdLCJpZCI6OTUxOCwidiI6MX0%3D&page%5Bsize%5D=1000&sort=updatedAt failed with status code 404 and error message None

[...]

2024-07-09 18:15:47 source > During the sync, the following streams did not sync successfully: accounts: AirbyteTracedException('Request to https://api.outreach.io/accounts?count=false&page%5Bafter%5D=eyJjbiI6IkFwaVYyOjpBY2NvdW50c0NvbnRyb2xsZXIiLCJzcCI6InVwZGF0ZWRBdCIsInN2IjpbIjIwMjQtMDUtMjBUMTk6NDM6MDUuMDAwWiJdLCJpZCI6OTUxOCwidiI6MX0%3D&page%5Bsize%5D=1000&sort=updatedAt failed with status code 404 and error message None')
2024-07-09 18:15:47 source > None
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 8, in <module>
    run()
  File "/airbyte/integration_code/source_outreach/run.py", line 14, in run
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 235, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 122, in run
    yield from map(AirbyteEntrypoint.airbyte_message_to_string, self.read(source_spec, config, config_catalog, state))
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 166, in read
    for message in self.source.read(self.logger, config, catalog, state):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/manifest_declarative_source.py", line 167, in read
    yield from super().read(logger, config, catalog, state)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 184, in read
    raise AirbyteTracedException(message=error_message, failure_type=FailureType.config_error)
airbyte_cdk.utils.traced_exception.AirbyteTracedException: None
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by natikgadzhi** [comment]
@ChristoGrab can you take a look when you have a minute? @girarda I'm not certain but I think that should be marketplace, and the label wasn't applied correctly?

**Comment by ChristoGrab** [comment]
Sure thing, I'll take a look tomorrow morning!

**Comment by natikgadzhi** [comment]
@btkcodedev want another bugfix to work on?

**Comment by btkcodedev** [comment]
Yes sure! @natikgadzhi
Looking into this

**Comment by btkcodedev** [comment]
A little suspicious with the outreach response, According to the documentation the links[next] should be providing the full URL and we are injecting directly to the path itself
![image](https://github.com/user-attachments/assets/4a41afea-ba46-49a4-aa79-03035f45d967)


But according to this user log, the server is returning without `/api/v2`
![image](https://github.com/user-attachments/assets/e1ac9103-9c83-4c44-a20b-520e1c36dba9)

We can fix it using custom component by parsing the text, Curently the GSM creds are expired, waiting to get new

**Comment by btkcodedev** [comment]
Update: Got the creds, working on it
