### ISSUE TITLE
Intermittent test failures on webapp

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#4147]
## Expected Behavior
* I'm on master. I expect the build to pass. commit: 02c49c15cdae714d0f17ca2d1c0450abf2bf25e0

## Current Behavior
When building on my local machine.
```
> Task :airbyte-webapp:test FAILED
FAIL src/components/ServiceForm/ServiceForm.test.tsx (22.7 s)
  ● Service Form › filling service form › should fill all fields by right values

    thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      206 |     });
      207 |
    > 208 |     test("should fill all fields by right values", async () => {
          |     ^
      209 |       const name = container.querySelector("input[name='name']");
      210 |       const host = container.querySelector(
      211 |         "input[name='connectionConfiguration.host']"

      at src/components/ServiceForm/ServiceForm.test.tsx:208:5
      at src/components/ServiceForm/ServiceForm.test.tsx:192:3
      at Object.<anonymous> (src/components/ServiceForm/ServiceForm.test.tsx:91:1)

  ● Service Form › filling service form › should fill right values in array of simple entity field

    TypeError: Cannot read property 'connectionConfiguration' of undefined

      290 |       await waitFor(() => userEvent.click(submit!));
      291 |
    > 292 |       expect(result.connectionConfiguration.emails).toEqual([
          |                     ^
      293 |         "test1@test.com",
      294 |         "test2@test.com",
      295 |         "test3@test.com",

      at Object.<anonymous> (src/components/ServiceForm/ServiceForm.test.tsx:292:21)

  ● Service Form › filling service form › should fill right values in array with items list field

    expect(received).toEqual(expected) // deep equality

    Expected: ["day", "night"]
    Received: undefined

      309 |       await waitFor(() => userEvent.click(submit!));
      310 |
    > 311 |       expect(result.connectionConfiguration.workTime).toEqual(["day", "night"]);
          |                                                       ^
      312 |     });
      313 |
      314 |     test("change oneOf field value", async () => {

      at Object.<anonymous> (src/components/ServiceForm/ServiceForm.test.tsx:311:55)

  ● Service Form › filling service form › change oneOf field value

    expect(received).toBeInTheDocument()

    received value must be an HTMLElement or an SVGElement.
    Received has value: null

      320 |
      321 |       const oauth = container.querySelector("div[data-id='oauth']");
    > 322 |       expect(oauth).toBeInTheDocument();
          |                     ^
      323 |       await waitFor(() => oauth && userEvent.click(oauth));
      324 |
      325 |       const credentialsValue = credentials?.querySelector(

      at __EXTERNAL_MATCHER_TRAP__ (node_modules/expect/build/index.js:342:30)
      at Object.toBeInTheDocument (node_modules/expect/build/index.js:343:15)
      at Object.<anonymous> (src/components/ServiceForm/ServiceForm.test.tsx:322:21)
```

**Comment by davinchia** [comment]
@timroes I think this is out of date and we can close this. Thoughts?
