### ISSUE TITLE
Flaky test: image exists

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#419]
```
> Task :airbyte-workers:test

DockerProcessBuilderFactoryTest > testImageExists() FAILED
    java.lang.IllegalThreadStateException: process hasn't exited
        at java.base/java.lang.ProcessImpl.exitValue(ProcessImpl.java:500)
        at io.airbyte.workers.process.DockerProcessBuilderFactory.checkImageExists(DockerProcessBuilderFactory.java:122)
        at io.airbyte.workers.process.DockerProcessBuilderFactoryTest.testImageExists(DockerProcessBuilderFactoryTest.java:43)

44 tests completed, 1 failed, 1 skipped
```
the process that gobbles the logs sometimes doesn't close in time. we should make it not flake.

workaround: this happens relatively rarely and re-running the test will get you passed it.

**Comment by cgardens** [comment]
i haven't seen this in awhile and this code has been rewritten.

**Comment by cgardens** [comment]
I just saw this bug again for the first time in awhile when doing clean build.

**Comment by cgardens** [comment]
haven't seen this again in ages. going to close.
