### ISSUE TITLE
[source-strava] unconverted data remains: Z

### ISSUE THREAD

**Issue by sql-chris-albert** [airbytehq/airbyte#41960]
### Connector Name

source-strava

### Connector Version

0.2.10

### What step the error happened?

During the sync

### Relevant information

Connector tests successfully and I see API calls in my Strava profile. 

### Relevant log output

```shell
source


destination


platform


other

2024-07-15 14:00:57 source > Starting syncing SourceStrava
2024-07-15 14:00:57 source > Marking stream activities as STARTED
2024-07-15 14:00:57 source > Syncing stream: activities 
2024-07-15 14:00:57 source > Encountered an exception while reading stream activities
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py", line 136, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py", line 236, in _read_stream
    for record_data_or_message in record_iterator:
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/streams/core.py", line 126, in read
    slices = self.stream_slices(
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py", line 142, in stream_slices
    return self.retriever.stream_slices()
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 375, in stream_slices
    return self.stream_slicer.stream_slices()
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py", line 168, in stream_slices
    start_datetime = self._calculate_earliest_possible_value(self._select_best_end_datetime())
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py", line 173, in _calculate_earliest_possible_value
    earliest_possible_start_datetime = min(self._start_datetime.get_datetime(self.config), end_datetime)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/datetime/min_max_datetime.py", line 58, in get_datetime
    time = self._parser.parse(str(self.datetime.eval(config, **additional_parameters)), datetime_format)  # type: ignore # datetime is always cast to an interpolated string
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/datetime/datetime_parser.py", line 33, in parse
    parsed_datetime = datetime.datetime.strptime(str(date), format)
  File "/usr/local/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.10/_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: Z
2024-07-15 14:00:57 source > Marking stream activities as STOPPED
2024-07-15 14:00:57 source > Finished syncing activities
2024-07-15 14:00:57 source > SourceStrava runtimes:
Syncing stream activities 0:00:00.010146
2024-07-15 14:00:57 source > During the sync, the following streams did not sync successfully: activities: AirbyteTracedException('unconverted data remains: Z')
2024-07-15 14:00:57 source > None
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 8, in <module>
    run()
  File "/airbyte/integration_code/source_strava/run.py", line 14, in run
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/entrypoint.py", line 235, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/entrypoint.py", line 122, in run
    yield from map(AirbyteEntrypoint.airbyte_message_to_string, self.read(source_spec, config, config_catalog, state))
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/entrypoint.py", line 166, in read
    for message in self.source.read(self.logger, config, catalog, state):
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/manifest_declarative_source.py", line 167, in read
    yield from super().read(logger, config, catalog, state)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py", line 184, in read
    raise AirbyteTracedException(message=error_message, failure_type=FailureType.config_error)
airbyte_cdk.utils.traced_exception.AirbyteTracedException: None
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Thanks for reporting the issue @sql-chris-albert Strava is a community connector and it isn’t in the current roadmap for improvements. If you want to contribute fixing the issue please reach me out in Slack so I can provide you instructions to make the contribution.
