### ISSUE TITLE
[destination-google-sheets] This action would increase the number of cells in the workbook above the limit of 10000000 cells

### ISSUE THREAD

**Issue by alexnikitchuk** [airbytehq/airbyte#41977]
### Connector Name

destination-google-sheets

### Connector Version

0.2.9

### What step the error happened?

During the sync

### Relevant information

The connector appends empty rows during each sync and at some point (depending on the source data size) it starts to error out with the error:
```
<HttpError 400 when requesting https://sheets.googleapis.com/v4/spreadsheets/xxx/values/xxxx%21A2%3AY25648:append?valueInputOption=USER_ENTERED&insertDataOption=INSERT_ROWS&alt=json returned "This action would increase the number of cells in the workbook above the limit of 10000000 cells.". Details: "This action would increase the number of cells in the workbook above the limit of 10000000 cells.">
```

Workaround is to remove empty rows or the sheets. 

### Relevant log output

```shell
2024-07-16 05:14:00 destination > <httperror>
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 11, in <module>
    DestinationGoogleSheets().run(sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/destinations/destination.py", line 119, in run
    for message in output_messages:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/destinations/destination.py", line 113, in run_cmd
    yield from self._run_write(config=config, configured_catalog_path=parsed_args.catalog, input_stream=wrapped_stdin)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/destinations/destination.py", line 49, in _run_write
    yield from self.write(config=config, configured_catalog=catalog, input_messages=input_messages)
  File "/airbyte/integration_code/destination_google_sheets/destination.py", line 69, in write
    writer.queue_write_operation(record.stream)
  File "/airbyte/integration_code/destination_google_sheets/writer.py", line 45, in queue_write_operation
    self.write_from_queue(stream_name)
  File "/airbyte/integration_code/destination_google_sheets/writer.py", line 63, in write_from_queue
    stream.append_table(values, start="A2", dimension="ROWS")
  File "/usr/local/lib/python3.9/site-packages/pygsheets/utils.py", line 163, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pygsheets/worksheet.py", line 1094, in append_table
    self.client.sheet.values_append(self.spreadsheet.id, values, dimension, range=self._get_range(start, end),
  File "/usr/local/lib/python3.9/site-packages/pygsheets/sheet.py", line 267, in values_append
    return self._execute_requests(request)
  File "/usr/local/lib/python3.9/site-packages/pygsheets/sheet.py", line 495, in _execute_requests
    response = request.execute(num_retries=self.retries)
  File "/usr/local/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 131, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/googleapiclient/http.py", line 937, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <httperror>
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by jessica-bauer** [comment]
I'm experiencing this issue as well and it would be great if there was a fix/workaround for it. 

I've set up several connections in our self-hosted Airbyte instance (MySQL as the source and Google Sheets as the destination) to send data from a database table or view directly to a Google Sheet. This is helpful for us in displaying data to staff that don't have direct access to the database while still needing the option to filter data. 

Some of our tables have thousands of rows so every time a refresh/overwrite sync happens, the overwriting data seem to get inserted as new rows while leaving the old rows in the sheet. Since majority of my connections run daily, the row numbers add up pretty quickly and cause the `limit of 10000000 cells` error to occur. When this happens, the Google Sheet becomes blank and I need to manually go in and delete thousands of rows.

**Comment by louise-tt** [comment]
Hello, I am also experiencing the same issue. 
Any idea if this issue would lead to a fix ? 
thank you !

**Comment by aidanlister** [comment]
This is how we do this in our durable writer:

```
        for batch in itertools.batched(data, n=self.WRITE_BATCH_SIZE):
            if self.logger:
                self.logger.info(f"... Writing {len(batch)} rows")

            # Add more rows to the sheet if needed
            required_row = sheet_row_cursor + len(batch) - 1
            current_row_count = worksheet.row_count
            if required_row > current_row_count:
                worksheet.add_rows(required_row - current_row_count)

            # Write the rows
            worksheet.update(
                self._stringify_all_values(batch),
                f"A{sheet_row_cursor}",
                value_input_option=ValueInputOption.user_entered,
            )

            sheet_row_cursor += len(batch)
```

e.g. we're checking the number of rows that exist before we add more ... I think we need to do the same here.

**Comment by pablomc87** [comment]
I added a different PR because the first one had some tests that were failing, maybe my approach fixes the issue
