### ISSUE TITLE
[source-mssql] 

### ISSUE THREAD

**Issue by mkrawc** [airbytehq/airbyte#42491]
### Connector Name

source-mssql

### Connector Version

4.1.3

### What step the error happened?

Configuring a new connector

### Relevant information

When creating the new MS SQL connector to Azure Synapse the schema discovery fails with an error `Some part of your SQL statement is nested too deeply. Rewrite the query or break it up into smaller queries.`. 

I thought this could be caused by the number of tables in the database but even when I limited it to a small schema in the source configuration the error persists.

### Relevant log output

```shell
Stack Trace: com.microsoft.sqlserver.jdbc.SQLServerException: Some part of your SQL statement is nested too deeply. Rewrite the query or break it up into smaller queries.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:261)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1752)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:675)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:594)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7739)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:4384)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:293)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:263)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:509)
        at com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.getColumns(SQLServerDatabaseMetaData.java:759)
        at com.zaxxer.hikari.pool.ProxyDatabaseMetaData.getColumns(ProxyDatabaseMetaData.java:107)
        at com.zaxxer.hikari.pool.HikariProxyDatabaseMetaData.getColumns(HikariProxyDatabaseMetaData.java)
        at io.airbyte.cdk.integrations.source.jdbc.AbstractJdbcSource.discoverInternal$lambda$8(AbstractJdbcSource.kt:375)
        at io.airbyte.cdk.db.jdbc.DefaultJdbcDatabase.bufferedResultSetQuery(DefaultJdbcDatabase.kt:39)
        at io.airbyte.cdk.integrations.source.jdbc.AbstractJdbcSource.discoverInternal(AbstractJdbcSource.kt:373)
        at io.airbyte.cdk.integrations.source.jdbc.AbstractJdbcSource.discoverInternal(AbstractJdbcSource.kt:487)
        at io.airbyte.integrations.source.mssql.MssqlSource.discoverInternal(MssqlSource.java:235)
        at io.airbyte.integrations.source.mssql.MssqlSource.discoverInternal(MssqlSource.java:77)
        at io.airbyte.cdk.integrations.source.relationaldb.AbstractDbSource.discoverWithoutSystemTables(AbstractDbSource.kt:302)
        at io.airbyte.cdk.integrations.source.relationaldb.AbstractDbSource.discover(AbstractDbSource.kt:93)
        at io.airbyte.cdk.integrations.source.jdbc.AbstractJdbcSource.discover(AbstractJdbcSource.kt:118)
        at io.airbyte.integrations.source.mssql.MssqlSource.discover(MssqlSource.java:216)
        at io.airbyte.cdk.integrations.base.ssh.SshWrappedSource.discover$lambda$1(SshWrappedSource.kt:58)
        at io.airbyte.cdk.integrations.base.ssh.SshTunnel$Companion.sshWrap(SshTunnel.kt:545)
        at io.airbyte.cdk.integrations.base.ssh.SshWrappedSource.discover(SshWrappedSource.kt:58)
        at io.airbyte.cdk.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.kt:175)
        at io.airbyte.cdk.integrations.base.IntegrationRunner.run(IntegrationRunner.kt:119)
        at io.airbyte.cdk.integrations.base.IntegrationRunner.run$default(IntegrationRunner.kt:113)
        at io.airbyte.cdk.integrations.base.IntegrationRunner.run(IntegrationRunner.kt)
        at io.airbyte.integrations.source.mssql.MssqlSource.main(MssqlSource.java:583)
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by mkrawc** [comment]
So I investigated slightly deeper and possibly this is related to mssql-jdbc issue: https://github.com/microsoft/mssql-jdbc/issues/1246. Indeed the call to `database.getMetaData().getColumns(database, null, null, null)` fails with the error above.

From what I see in the source code MssqlSource class gets all columns and then filters out the schemas we need. I tried to execute `getColumns` with database and schema names but I just replaced one error to another.

I was trying to use this code in MssqlSource:
```
  @Override
  public List<TableInfo<CommonField<JDBCType>>> discoverInternal(final JdbcDatabase database) throws Exception {
    if (schemas != null && !schemas.isEmpty()) {
      return schemas.stream().flatMap(schema -> {
        LOGGER.info("Get columns for schema: {}", schema);
        try {
          return super.discoverInternal(database, schema).stream();
        } catch (Exception e) {
          LOGGER.error("Error getting columns for schema: {}", schema, e);
          return Stream.empty();
        }
      }).collect(toList());
    } else {
      LOGGER.info("No schemas explicitly set on UI to process, so will process all of existing schemas in DB");
      return super.discoverInternal(database);
    }
  }
```

But it fails with error below:
```
ERROR main i.a.c.i.b.AirbyteExceptionHandler(uncaughtException):31 Something went wrong in the connector. See the logs for more details. com.microsoft.sqlserver.jdbc.SQLServerException: The query processor ran out of internal resources and could not produce a query plan. This is a rare event and only expected for extremely complex queries or queries that reference a very large number of tables or partitions. Please simplify the query. If you believe you have received this message in error, contact Customer Support Services for more information.
```

While the `getColumns` call fails I was still able to get columns information from sys tables using the query below. So perhaps we could use that instead of ODBC metadata?
```
SELECT SCHEMA_NAME(tables.schema_id) AS schema_name, tables.name as table_name, columns.name AS column_name, types.name as column_type
FROM sys.columns 
JOIN sys.tables ON columns.object_id = tables.object_id
JOIN sys.types ON types.system_type_id = columns.system_type_id; 
```

If anyone could take a look that would be appreciated.

**Comment by marcosmarxm** [comment]
Thanks for the investigation @mkrawc. @airbytehq/dbsources can someone help here?

**Comment by evantahler** [comment]
Grooming:
* we should keep the MS/driver version of discover as the deftault.  It is more compatible with multiple versions of the DB
* However, if that fails, we can try the custom query that @mkrawc provided above.  It's less compatibile with old MSQSL versions, but... if the main query already failed... we might as well try it
