### ISSUE TITLE
Error Multiple successfull attempts (multiple job id in database)

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#4279]
## Expected Behavior
*Tell us what should happen.*

## Current Behavior
There are some cases where the job is written two times in job table.
```
2021-06-21 10:43:40 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/workspaces/get
2021-06-21 10:43:40 INFO  REQ 172.18.0.1 POST 200 /api/v1/workspaces/get - {"workspaceId":"5ae6b09b-fdec-41af-aaf7-7d94cfc33ef6"}
2021-06-21 10:43:40 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/source_definitions/list
2021-06-21 10:43:40 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/sources/list
2021-06-21 10:43:40 INFO  REQ 172.18.0.1 POST 200 /api/v1/source_definitions/list - {"workspaceId":"5ae6b09b-fdec-41af-aaf7-7d94cfc33ef6"}
2021-06-21 10:43:40 INFO  REQ 172.18.0.1 POST 200 /api/v1/sources/list - {"workspaceId":"5ae6b09b-fdec-41af-aaf7-7d94cfc33ef6"}
2021-06-21 10:43:41 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/source_definitions/list_latest
2021-06-21 10:43:41 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/web_backend/connections/list
2021-06-21 10:43:41 INFO  REQ 172.18.0.1 POST 200 /api/v1/source_definitions/list_latest - {"workspaceId":"5ae6b09b-fdec-41af-aaf7-7d94cfc33ef6"}
2021-06-21 10:43:43 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/destination_definitions/list
2021-06-21 10:43:43 INFO  REQ 172.18.0.1 POST 200 /api/v1/destination_definitions/list - {"workspaceId":"5ae6b09b-fdec-41af-aaf7-7d94cfc33ef6"}
2021-06-21 10:43:43 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/destination_definitions/list_latest
2021-06-21 10:43:44 INFO  REQ 172.18.0.1 POST 200 /api/v1/destination_definitions/list_latest - {"workspaceId":"5ae6b09b-fdec-41af-aaf7-7d94cfc33ef6"}
2021-06-21 10:43:47 INFO  REQ 172.18.0.1 POST 200 /api/v1/web_backend/connections/list - {"workspaceId":"5ae6b09b-fdec-41af-aaf7-7d94cfc33ef6"}
2021-06-21 10:43:55 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/jobs/list
2021-06-21 10:43:55 WARN  HV000254: Missing parameter metadata for JobConfigType(String, int, String), which declares implicit or synthetic parameters. Automatic resolution of generic type information for method parameters may yield incorrect results if multiple parameters have the same erasure. To solve this, compile your code with the '-parameters' flag.
2021-06-21 10:43:56 INFO  REQ 172.18.0.1 POST 200 /api/v1/jobs/list - {"configId":"a7d56e49-8298-407b-b7cb-b49eed63b3c9","configTypes":["sync","reset_connection"]}
2021-06-21 10:44:05 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/jobs/list
2021-06-21 10:44:06 INFO  REQ 172.18.0.1 POST 200 /api/v1/jobs/list - {"configId":"a7d56e49-8298-407b-b7cb-b49eed63b3c9","configTypes":["sync","reset_connection"]}
2021-06-21 10:44:08 INFO  REQ 172.18.0.1 POST 200 /api/v1/jobs/list - {"configId":"a7d56e49-8298-407b-b7cb-b49eed63b3c9","configTypes":["sync","reset_connection"]}
2021-06-21 10:44:11 INFO  REQ 172.18.0.1 POST 200 /api/v1/jobs/list - {"configId":"a7d56e49-8298-407b-b7cb-b49eed63b3c9","configTypes":["sync","reset_connection"]}
2021-06-21 10:44:12 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/jobs/list
2021-06-21 10:44:13 INFO  REQ 172.18.0.1 POST 200 /api/v1/jobs/list - {"configId":"a7d56e49-8298-407b-b7cb-b49eed63b3c9","configTypes":["sync","reset_connection"]}
2021-06-21 10:44:16 INFO  REQ 172.18.0.1 POST 200 /api/v1/jobs/list - {"configId":"a7d56e49-8298-407b-b7cb-b49eed63b3c9","configTypes":["sync","reset_connection"]}
2021-06-21 10:44:16 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/destination_definition_specifications/get
2021-06-21 10:44:16 INFO  REQ 172.18.0.1 POST 200 /api/v1/destination_definition_specifications/get - {"destinationDefinitionId":"22f6c74f-5699-40ff-833c-4a879ea40133"}
2021-06-21 10:44:19 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/jobs/list
2021-06-21 10:44:20 INFO  REQ 172.18.0.1 POST 200 /api/v1/jobs/list - {"configId":"a7d56e49-8298-407b-b7cb-b49eed63b3c9","configTypes":["sync","reset_connection"]}
2021-06-21 10:44:23 INFO  REQ 172.18.0.1 POST 200 /api/v1/jobs/list - {"configId":"a7d56e49-8298-407b-b7cb-b49eed63b3c9","configTypes":["sync","reset_connection"]}
2021-06-21 10:44:26 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/source_definitions/update
2021-06-21 10:44:39 INFO  REQ 172.18.0.1 POST 200 /api/v1/source_definitions/update - {"sourceDefinitionId":"435bb9a5-7887-4809-aa58-28c27df0d7ad","dockerImageTag":"0.3.7"}
2021-06-21 10:44:42 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/destinations/list
2021-06-21 10:44:43 INFO  REQ 172.18.0.1 POST 200 /api/v1/destinations/list - {"workspaceId":"5ae6b09b-fdec-41af-aaf7-7d94cfc33ef6"}
2021-06-21 10:44:44 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/source_definitions/list
2021-06-21 10:44:44 INFO  REQ 172.18.0.1 POST 200 /api/v1/source_definitions/list - {"workspaceId":"5ae6b09b-fdec-41af-aaf7-7d94cfc33ef6"}
2021-06-21 10:44:45 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/source_definitions/list_latest
2021-06-21 10:44:47 INFO  REQ 172.18.0.1 POST 200 /api/v1/source_definitions/list_latest - {"workspaceId":"5ae6b09b-fdec-41af-aaf7-7d94cfc33ef6"}
2021-06-21 10:44:47 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/destination_definitions/update
2021-06-21 10:44:57 INFO  REQ 172.18.0.1 POST 200 /api/v1/destination_definitions/update - {"destinationDefinitionId":"22f6c74f-5699-40ff-833c-4a879ea40133","dockerImageTag":"0.3.6"}
2021-06-21 10:44:59 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/web_backend/connections/list
2021-06-21 10:44:59 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/workspaces/get
2021-06-21 10:44:59 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/destination_definitions/list
2021-06-21 10:44:59 INFO  REQ 172.18.0.1 POST 200 /api/v1/workspaces/get - {"workspaceId":"5ae6b09b-fdec-41af-aaf7-7d94cfc33ef6"}
2021-06-21 10:44:59 INFO  REQ 172.18.0.1 POST 200 /api/v1/destination_definitions/list - {"workspaceId":"5ae6b09b-fdec-41af-aaf7-7d94cfc33ef6"}
2021-06-21 10:45:00 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/destination_definitions/list_latest
2021-06-21 10:45:00 INFO  REQ 172.18.0.1 POST 200 /api/v1/destination_definitions/list_latest - {"workspaceId":"5ae6b09b-fdec-41af-aaf7-7d94cfc33ef6"}
2021-06-21 10:45:02 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/jobs/list
2021-06-21 10:45:02 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/web_backend/connections/get
2021-06-21 10:45:02 INFO  REQ 172.18.0.1 POST 200 /api/v1/jobs/list - {"connectionId":"3882bab8-c34a-4f17-a2af-30f8fd4730f9"}
2021-06-21 10:45:05 INFO  REQ 172.18.0.1 POST 200 /api/v1/jobs/list - {"configId":"3882bab8-c34a-4f17-a2af-30f8fd4730f9","configTypes":["sync","reset_connection"]}
2021-06-21 10:45:06 INFO  REQ 172.18.0.1 POST 200 /api/v1/web_backend/connections/get - {"configId":"3882bab8-c34a-4f17-a2af-30f8fd4730f9","configTypes":["sync","reset_connection"]}
2021-06-21 10:45:06 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/jobs/get
2021-06-21 10:45:06 INFO  REQ 172.18.0.1 POST 200 /api/v1/jobs/get - {"id":5966}
2021-06-21 10:45:07 INFO  REQ 172.18.0.1 POST 200 /api/v1/jobs/get - {"id":5966}
2021-06-21 10:45:07 INFO  REQ 172.18.0.1 POST 200 /api/v1/jobs/list - {"id":5966}
2021-06-21 10:45:10 INFO  REQ 172.18.0.1 POST 200 /api/v1/jobs/get - {"id":5966}
2021-06-21 10:45:10 INFO  REQ 172.18.0.1 POST 200 /api/v1/web_backend/connections/list - {"id":5966}
2021-06-21 10:45:12 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/jobs/list
2021-06-21 10:45:12 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/jobs/get
2021-06-21 10:45:12 INFO  REQ 172.18.0.1 POST 200 /api/v1/jobs/get - {"id":5966}
2021-06-21 10:45:12 INFO  REQ 172.18.0.1 POST 200 /api/v1/jobs/list - {"id":5966}
2021-06-21 10:45:14 INFO  REQ 172.18.0.1 POST 200 /api/v1/jobs/list - {"configId":"3882bab8-c34a-4f17-a2af-30f8fd4730f9","configTypes":["sync","reset_connection"]}
2021-06-21 10:45:15 INFO  REQ 172.18.0.1 POST 200 /api/v1/jobs/get - {"id":5966}
2021-06-21 10:45:21 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/jobs/list
2021-06-21 10:45:21 INFO  REQ 172.18.0.1 POST 200 /api/v1/jobs/list - {"configId":"3882bab8-c34a-4f17-a2af-30f8fd4730f9","configTypes":["sync","reset_connection"]}
2021-06-21 10:45:23 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/connections/sync
2021-06-21 10:45:27 ERROR Uncaught exception
java.lang.IllegalStateException: Job 5966 has multiple successful attempts.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508) ~[guava-30.1-jre.jar:?]
	at io.airbyte.scheduler.models.Job.getSuccessfulAttempt(Job.java:119) ~[io.airbyte.airbyte-scheduler-models-0.23.0-alpha.jar:?]
	at io.airbyte.scheduler.models.Job.getSuccessOutput(Job.java:128) ~[io.airbyte.airbyte-scheduler-models-0.23.0-alpha.jar:?]
	at java.util.Optional.flatMap(Optional.java:287) ~[?:?]
	at io.airbyte.scheduler.persistence.DefaultJobPersistence.lambda$getCurrentState$18(DefaultJobPersistence.java:357) ~[io.airbyte.airbyte-scheduler-persistence-0.23.0-alpha.jar:?]
	at io.airbyte.db.Database.query(Database.java:51) ~[io.airbyte-airbyte-db-0.23.0-alpha.jar:?]
	at io.airbyte.db.ExceptionWrappingDatabase.query(ExceptionWrappingDatabase.java:43) ~[io.airbyte-airbyte-db-0.23.0-alpha.jar:?]
	at io.airbyte.scheduler.persistence.DefaultJobPersistence.getCurrentState(DefaultJobPersistence.java:346) ~[io.airbyte.airbyte-scheduler-persistence-0.23.0-alpha.jar:?]
	at io.airbyte.scheduler.persistence.DefaultJobCreator.createSyncJob(DefaultJobCreator.java:123) ~[io.airbyte.airbyte-scheduler-persistence-0.23.0-alpha.jar:?]
	at io.airbyte.scheduler.client.DefaultSchedulerJobClient.createOrGetActiveSyncJob(DefaultSchedulerJobClient.java:62) ~[io.airbyte.airbyte-scheduler-client-0.23.0-alpha.jar:?]
	at io.airbyte.server.handlers.SchedulerHandler.syncConnection(SchedulerHandler.java:296) ~[io.airbyte-airbyte-server-0.23.0-alpha.jar:?]
	at io.airbyte.server.apis.ConfigurationApi.lambda$syncConnection$34(ConfigurationApi.java:404) ~[io.airbyte-airbyte-server-0.23.0-alpha.jar:?]
	at io.airbyte.server.apis.ConfigurationApi.execute(ConfigurationApi.java:533) ~[io.airbyte-airbyte-server-0.23.0-alpha.jar:?]
	at io.airbyte.server.apis.ConfigurationApi.syncConnection(ConfigurationApi.java:404) ~[io.airbyte-airbyte-server-0.23.0-alpha.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253) [jersey-server-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [jersey-common-2.31.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [jersey-common-2.31.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232) [jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680) [jersey-server-2.31.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394) [jersey-container-servlet-core-2.31.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) [jersey-container-servlet-core-2.31.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366) [jersey-container-servlet-core-2.31.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319) [jersey-container-servlet-core-2.31.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) [jersey-container-servlet-core-2.31.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763) [jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:569) [jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1377) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:507) [jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.Server.handle(Server.java:501) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at java.lang.Thread.run(Thread.java:832) [?:?]
2021-06-21 10:45:27 ERROR REQ 172.18.0.1 POST 500 /api/v1/connections/sync - {"connectionId":"3882bab8-c34a-4f17-a2af-30f8fd4730f9"}
2021-06-21 10:45:29 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/jobs/list
2021-06-21 10:45:30 INFO  REQ 172.18.0.1 POST 200 /api/v1/jobs/list - {"configId":"3882bab8-c34a-4f17-a2af-30f8fd4730f9","configTypes":["sync","reset_connection"]}
2021-06-21 10:45:31 INFO  REQ 172.18.0.1 POST 200 /api/v1/jobs/list - {"configId":"3882bab8-c34a-4f17-a2af-30f8fd4730f9","configTypes":["sync","reset_connection"]}
2021-06-21 10:45:34 INFO  REQ 172.18.0.1 POST 200 /api/v1/jobs/list - {"configId":"3882bab8-c34a-4f17-a2af-30f8fd4730f9","configTypes":["sync","reset_connection"]}
2021-06-21 10:45:37 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/jobs/list
2021-06-21 10:45:37 INFO  REQ 172.18.0.1 POST 200 /api/v1/jobs/list - {"configId":"3882bab8-c34a-4f17-a2af-30f8fd4730f9","configTypes":["sync","reset_connection"]}
2021-06-21 10:45:47 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/jobs/list
2021-06-21 10:45:48 INFO  REQ 172.18.0.1 POST 200 /api/v1/jobs/list - {"configId":"3882bab8-c34a-4f17-a2af-30f8fd4730f9","configTypes":["sync","reset_connection"]}
2021-06-21 10:45:51 INFO  REQ 172.18.0.1 POST 200 /api/v1/jobs/list - {"configId":"3882bab8-c34a-4f17-a2af-30f8fd4730f9","configTypes":["sync","reset_connection"]}
2021-06-21 10:46:01 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/sources/list
2021-06-21 10:46:01 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/destination_definitions/list
2021-06-21 10:46:01 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/source_definitions/list
2021-06-21 10:46:01 INFO  REQ 172.18.0.1 POST 200 /api/v1/source_definitions/list - {"workspaceId":"5ae6b09b-fdec-41af-aaf7-7d94cfc33ef6"}
2021-06-21 10:46:01 INFO  REQ 172.18.0.1 POST 200 /api/v1/destination_definitions/list - {"workspaceId":"5ae6b09b-fdec-41af-aaf7-7d94cfc33ef6"}
2021-06-21 10:46:01 INFO  REQ 172.18.0.1 POST 200 /api/v1/sources/list - {"workspaceId":"5ae6b09b-fdec-41af-aaf7-7d94cfc33ef6"}
2021-06-21 10:46:02 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/destination_definitions/list_latest
2021-06-21 10:46:02 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/source_definitions/list_latest
2021-06-21 10:46:02 INFO  REQ 172.18.0.1 POST 200 /api/v1/destination_definitions/list_latest - {"workspaceId":"5ae6b09b-fdec-41af-aaf7-7d94cfc33ef6"}
2021-06-21 10:46:02 INFO  REQ 172.18.0.1 POST 200 /api/v1/source_definitions/list_latest - {"workspaceId":"5ae6b09b-fdec-41af-aaf7-7d94cfc33ef6"}
2021-06-21 10:46:07 INFO  REQ 172.18.0.1 OPTIONS 200 /api/v1/logs/get
2021-06-21 10:46:07 WARN  HV000254: Missing parameter metadata for LogType(String, int, String), which declares implicit or synthetic parameters. Automatic resolution of generic type information for method parameters may yield incorrect results if multiple parameters have the same erasure. To solve this, compile your code with the '-parameters' flag.
2021-06-21 10:46:07 INFO  REQ 172.18.0.1 POST 200 /api/v1/logs/get - {"logType":"server"}
```

## Logs
*If applicable, please upload the logs from the failing operation. For sync jobs, you can download the full logs from the UI by going to the sync attempt page and clicking the download logs button at the top right of the logs display window.*

## Steps to Reproduce
1.
1.
1.

## Severity of the bug for you
Very low / Low / Medium / High / Critical

## Airbyte Version
Found in the .env file in the root of the project.

## Connector Version (if applicable)
Found in the admin page in the UI in the respective Source or Destination tab.

## Additional context
*Environment, version, integration...*

**Comment by marcosmarxm** [comment]
Closes as duplicated #4378
