### ISSUE TITLE
When attempting to start Airbyte, the bootloader is failing to connect to the PostgreSQL database. The logs show repeated connection timeout errors.

### ISSUE THREAD

**Issue by ivorpad** [airbytehq/airbyte#42876]
### Platform Version

0.63.11

### What step the error happened?

Deploying in a fresh EC2 instance with `./run-ab-platform.sh -b`

## Environment
- Airbyte version: 0.63.11
- Previous working version: 0.63.4
- Deployment: EC2
- Database: PostgreSQL (default airbyte-db configuration)

## Steps to Reproduce
1. Deploy Airbyte 0.63.11 on EC2
2. Use default .env configuration (airbyte-db)
3. Start Airbyte services
4. Monitor bootloader logs

### Relevant log output

```shell
Attaching to airbyte-bootloader, airbyte-connector-builder-server, airbyte-cron, airbyte-db, airbyte-proxy, airbyte-server, airbyte-temporal, airbyte-webapp, airbyte-worker, ec2-user-docker-proxy-1, init
init                              | MOUNT: /local_parent
init                              | ROOT_PARENT: /tmp
init                              | ROOT: /tmp/airbyte_local
init                              | MOUNT_ROOT: /local_parent//airbyte_local
airbyte-temporal                  | Start init
airbyte-temporal                  | Done init
init exited with code 0
airbyte-db                        | The files belonging to this database system will be owned by user "postgres".
airbyte-db                        | This user must also own the server process.
airbyte-db                        |
airbyte-db                        | The database cluster will be initialized with locale "en_US.utf8".
airbyte-db                        | The default database encoding has accordingly been set to "UTF8".
airbyte-db                        | The default text search configuration will be set to "english".
airbyte-db                        |
airbyte-db                        | Data page checksums are disabled.
airbyte-db                        |
airbyte-db                        | fixing permissions on existing directory /var/lib/postgresql/data ... ok
airbyte-db                        | creating subdirectories ... ok
airbyte-db                        | selecting dynamic shared memory implementation ... posix
airbyte-db                        | selecting default max_connections ... 100
airbyte-db                        | selecting default shared_buffers ... 128MB
airbyte-db                        | selecting default time zone ... UTC
airbyte-db                        | creating configuration files ... ok
airbyte-db                        | running bootstrap script ... ok
airbyte-bootloader                | Unsetting empty environment variable 'DD_AGENT_HOST'
airbyte-bootloader                | Unsetting empty environment variable 'JAVA_OPTS'
airbyte-bootloader                | Unsetting empty environment variable 'DD_TRACE_AGENT_PORT'
airbyte-bootloader                | Unsetting empty environment variable 'CONTAINER_ORCHESTRATOR_JAVA_OPTS'
airbyte-bootloader                | Unsetting empty environment variable 'LOCAL_CONNECTOR_CATALOG_PATH'
airbyte-bootloader                | Unsetting empty environment variable 'CONNECTOR_REGISTRY_SEED_PROVIDER'
airbyte-bootloader                | Unsetting empty environment variable 'CONNECTOR_REGISTRY_BASE_URL'
airbyte-bootloader                | Unsetting empty environment variable 'DD_LOGS_INJECTION'
airbyte-bootloader                | Unsetting empty environment variable 'DD_DOGSTATSD_PORT'
airbyte-db                        | performing post-bootstrap initialization ... sh: locale: not found
airbyte-db                        | 2024-07-30 11:10:59.872 UTC [35] WARNING:  no usable system locales were found
airbyte-db                        | ok
airbyte-db                        | syncing data to disk ... ok
airbyte-db                        |
airbyte-db                        |
airbyte-db                        | Success. You can now start the database server using:
airbyte-db                        |
airbyte-db                        |     pg_ctl -D /var/lib/postgresql/data -l logfile start
airbyte-db                        |
airbyte-db                        | initdb: warning: enabling "trust" authentication for local connections
airbyte-db                        | You can change this by editing pg_hba.conf or using the option -A, or
airbyte-db                        | --auth-local and --auth-host, the next time you run initdb.
airbyte-db                        | waiting for server to start....2024-07-30 11:11:00.664 UTC [41] LOG:  starting PostgreSQL 13.15 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, 64-bit
airbyte-db                        | 2024-07-30 11:11:00.667 UTC [41] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
airbyte-db                        | 2024-07-30 11:11:00.675 UTC [42] LOG:  database system was shut down at 2024-07-30 11:11:00 UTC
airbyte-db                        | 2024-07-30 11:11:00.680 UTC [41] LOG:  database system is ready to accept connections
airbyte-db                        |  done
airbyte-db                        | server started
airbyte-db                        | CREATE DATABASE
airbyte-db                        |
airbyte-db                        |
airbyte-db                        | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/000_init.sql
airbyte-db                        | ALTER SYSTEM
airbyte-db                        | CREATE DATABASE
airbyte-db                        | You are now connected to database "airbyte" as user "docker".
airbyte-db                        | GRANT
airbyte-db                        |
airbyte-db                        |
airbyte-db                        | 2024-07-30 11:11:00.988 UTC [41] LOG:  received fast shutdown request
airbyte-db                        | waiting for server to shut down....2024-07-30 11:11:00.992 UTC [41] LOG:  aborting any active transactions
airbyte-db                        | 2024-07-30 11:11:00.994 UTC [41] LOG:  background worker "logical replication launcher" (PID 48) exited with exit code 1
airbyte-db                        | 2024-07-30 11:11:00.998 UTC [43] LOG:  shutting down
airbyte-db                        | 2024-07-30 11:11:01.027 UTC [41] LOG:  database system is shut down
airbyte-db                        |  done
airbyte-db                        | server stopped
airbyte-db                        |
airbyte-db                        | PostgreSQL init process complete; ready for start up.
airbyte-db                        |
airbyte-db                        | 2024-07-30 11:11:01.124 UTC [1] LOG:  starting PostgreSQL 13.15 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, 64-bit
airbyte-db                        | 2024-07-30 11:11:01.126 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
airbyte-db                        | 2024-07-30 11:11:01.127 UTC [1] LOG:  listening on IPv6 address "::", port 5432
airbyte-bootloader                | 2024-07-30T11:11:01.131720516Z main INFO Loading mask data from '/seed/specs_secrets_mask.yaml
airbyte-db                        | 2024-07-30 11:11:01.135 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
airbyte-db                        | 2024-07-30 11:11:01.142 UTC [59] LOG:  database system was shut down at 2024-07-30 11:11:01 UTC
airbyte-db                        | 2024-07-30 11:11:01.160 UTC [1] LOG:  database system is ready to accept connections
airbyte-bootloader                |
airbyte-bootloader                |     ___    _      __          __
airbyte-bootloader                |    /   |  (_)____/ /_  __  __/ /____
airbyte-bootloader                |   / /| | / / ___/ __ \/ / / / __/ _ \
airbyte-bootloader                |  / ___ |/ / /  / /_/ / /_/ / /_/  __/
airbyte-bootloader                | /_/  |_/_/_/  /_.___/\__, /\__/\___/
airbyte-bootloader                |                     /____/
airbyte-bootloader                |         : airbyte-bootloader :
airbyte-bootloader                |
airbyte-bootloader                | 2024-07-30 11:11:05 INFO i.m.r.Micronaut(start):101 - Startup completed in 3863ms. Server Running: http://469873b83eb3:9002
airbyte-bootloader                | 2024-07-30 11:11:05 INFO i.a.f.ConfigFileClient(<init>):105 - path /flags does not exist, will return default flag values
airbyte-bootloader                | 2024-07-30 11:11:05 WARN i.a.m.l.MetricClientFactory(initialize):72 - MetricClient was not recognized or not provided. Accepted values are `datadog` or `otel`.
airbyte-bootloader                | 2024-07-30 11:11:06 INFO i.a.c.s.RemoteDefinitionsProvider(<init>):75 - Creating remote definitions provider for URL 'https://connectors.airbyte.com/files/' and registry 'OSS'...
airbyte-bootloader                | 2024-07-30 11:11:06 INFO i.a.c.i.c.SeedBeanFactory(seedDefinitionsProvider):39 - Using local definitions provider for seeding
airbyte-bootloader                | 2024-07-30 11:11:06 INFO i.a.b.Bootloader(load):107 - Initializing databases...
airbyte-bootloader                | 2024-07-30 11:11:06 INFO i.a.b.Bootloader(initializeDatabases):232 - Initializing databases...
airbyte-bootloader                | 2024-07-30 11:11:06 WARN i.a.d.c.DatabaseAvailabilityCheck(check):38 - Waiting for database to become available...
airbyte-bootloader                | 2024-07-30 11:11:06 INFO i.a.d.c.DatabaseAvailabilityCheck(lambda$isDatabaseConnected$1):75 - Testing airbyte configs database connection...
airbyte-bootloader                | 2024-07-30 11:11:14 WARN i.m.s.r.u.Loggers$Slf4JLogger(warn):299 - [2e8c98af, L:/127.0.0.1:36780 - R:localhost/127.0.0.1:8125] An exception has been observed post termination, use DEBUG level to see the full stack: java.net.PortUnreachableException: recvAddress(..) failed: Connection refused
airbyte-bootloader                | 2024-07-30 11:11:24 WARN i.m.s.r.u.Loggers$Slf4JLogger(warn):299 - [2e8c98af, L:/127.0.0.1:36780 - R:localhost/127.0.0.1:8125] An exception has been observed post termination, use DEBUG level to see the full stack: java.net.PortUnreachableException: recvAddress(..) failed: Connection refused
airbyte-bootloader                | 2024-07-30 11:11:24 WARN i.m.s.r.u.Loggers$Slf4JLogger(warn):299 - [2e8c98af, L:/127.0.0.1:36780 - R:localhost/127.0.0.1:8125] An exception has been observed post termination, use DEBUG level to see the full stack: java.net.PortUnreachableException: recvAddress(..) failed: Connection refused
airbyte-bootloader                | 2024-07-30 11:11:24 WARN i.m.s.r.u.Loggers$Slf4JLogger(warn):299 - [2e8c98af, L:/127.0.0.1:36780 - R:localhost/127.0.0.1:8125] An exception has been observed post termination, use DEBUG level to see the full stack: java.net.PortUnreachableException: recvAddress(..) failed: Connection refused
airbyte-bootloader                | 2024-07-30 11:11:34 WARN i.m.s.r.u.Loggers$Slf4JLogger(warn):299 - [2e8c98af, L:/127.0.0.1:36780 - R:localhost/127.0.0.1:8125] An exception has been observed post termination, use DEBUG level to see the full stack: java.net.PortUnreachableException: recvAddress(..) failed: Connection refused
airbyte-bootloader                | 2024-07-30 11:11:34 WARN i.m.s.r.u.Loggers$Slf4JLogger(warn):299 - [2e8c98af, L:/127.0.0.1:36780 - R:localhost/127.0.0.1:8125] An exception has been observed post termination, use DEBUG level to see the full stack: java.net.PortUnreachableException: recvAddress(..) failed: Connection refused
airbyte-bootloader                | 2024-07-30 11:11:34 WARN i.m.s.r.u.Loggers$Slf4JLogger(warn):299 - [2e8c98af, L:/127.0.0.1:36780 - R:localhost/127.0.0.1:8125] An exception has been observed post termination, use DEBUG level to see the full stack: java.net.PortUnreachableException: recvAddress(..) failed: Connection refused
airbyte-bootloader                | 2024-07-30 11:11:34 WARN i.m.s.r.u.Loggers$Slf4JLogger(warn):299 - [2e8c98af, L:/127.0.0.1:36780 - R:localhost/127.0.0.1:8125] An exception has been observed post termination, use DEBUG level to see the full stack: java.net.PortUnreachableException: recvAddress(..) failed: Connection refused
airbyte-bootloader                | 2024-07-30 11:11:36 ERROR i.a.d.c.DatabaseAvailabilityCheck(lambda$isDatabaseConnected$1):78 - Failed to verify database connection.
airbyte-bootloader                | org.jooq.exception.DataAccessException: Error getting connection from data source HikariDataSource (HikariPool-2)
airbyte-bootloader                | 	at org.jooq_3.19.7.POSTGRES.debug(Unknown Source) ~[?:?]
airbyte-bootloader                | 	at org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:90) ~[jooq-3.19.7.jar:?]
airbyte-bootloader                | 	at org.jooq.impl.DefaultExecuteContext.connection(DefaultExecuteContext.java:651) ~[jooq-3.19.7.jar:?]
airbyte-bootloader                | 	at org.jooq.impl.AbstractQuery.connection(AbstractQuery.java:388) ~[jooq-3.19.7.jar:?]
airbyte-bootloader                | 	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:308) ~[jooq-3.19.7.jar:?]
airbyte-bootloader                | 	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:301) ~[jooq-3.19.7.jar:?]
airbyte-bootloader                | 	at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:322) ~[jooq-3.19.7.jar:?]
airbyte-bootloader                | 	at org.jooq.impl.SelectImpl.fetchLazyNonAutoClosing(SelectImpl.java:3256) ~[jooq-3.19.7.jar:?]
airbyte-bootloader                | 	at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:509) ~[jooq-3.19.7.jar:?]
airbyte-bootloader                | 	at org.jooq.impl.Tools.attach(Tools.java:1652) ~[jooq-3.19.7.jar:?]
airbyte-bootloader                | 	at org.jooq.impl.DefaultDSLContext.fetchOne(DefaultDSLContext.java:5019) ~[jooq-3.19.7.jar:?]
airbyte-bootloader                | 	at org.jooq.impl.DefaultDSLContext.lambda$fetchValue$55(DefaultDSLContext.java:5039) ~[jooq-3.19.7.jar:?]
airbyte-bootloader                | 	at org.jooq.impl.Tools.attach(Tools.java:1652) ~[jooq-3.19.7.jar:?]
airbyte-bootloader                | 	at org.jooq.impl.DefaultDSLContext.fetchValue(DefaultDSLContext.java:5039) ~[jooq-3.19.7.jar:?]
airbyte-bootloader                | 	at org.jooq.impl.DefaultDSLContext.fetchValue(DefaultDSLContext.java:5058) ~[jooq-3.19.7.jar:?]
airbyte-bootloader                | 	at org.jooq.impl.DefaultDSLContext.fetchExists(DefaultDSLContext.java:5150) ~[jooq-3.19.7.jar:?]
airbyte-bootloader                | 	at io.airbyte.db.check.DatabaseAvailabilityCheck.lambda$isDatabaseConnected$0(DatabaseAvailabilityCheck.java:76) ~[io.airbyte.airbyte-db-db-lib-0.63.11.jar:?]
airbyte-bootloader                | 	at io.airbyte.db.Database.query(Database.java:23) ~[io.airbyte.airbyte-db-db-lib-0.63.11.jar:?]
airbyte-bootloader                | 	at io.airbyte.db.check.DatabaseAvailabilityCheck.lambda$isDatabaseConnected$1(DatabaseAvailabilityCheck.java:76) ~[io.airbyte.airbyte-db-db-lib-0.63.11.jar:?]
airbyte-bootloader                | 	at io.airbyte.db.check.DatabaseAvailabilityCheck.check(DatabaseAvailabilityCheck.java:47) [io.airbyte.airbyte-db-db-lib-0.63.11.jar:?]
airbyte-bootloader                | 	at io.airbyte.db.init.DatabaseInitializer.initialize(DatabaseInitializer.java:45) [io.airbyte.airbyte-db-db-lib-0.63.11.jar:?]
airbyte-bootloader                | 	at io.airbyte.bootloader.Bootloader.initializeDatabases(Bootloader.java:233) [io.airbyte-airbyte-bootloader-0.63.11.jar:?]
airbyte-bootloader                | 	at io.airbyte.bootloader.Bootloader.load(Bootloader.java:108) [io.airbyte-airbyte-bootloader-0.63.11.jar:?]
airbyte-bootloader                | 	at io.airbyte.bootloader.Application.main(Application.java:22) [io.airbyte-airbyte-bootloader-0.63.11.jar:?]
airbyte-bootloader                | Caused by: java.sql.SQLTransientConnectionException: HikariPool-2 - Connection is not available, request timed out after 30001ms (total=0, active=0, idle=0, waiting=0)
airbyte-bootloader                | 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:686) ~[HikariCP-5.1.0.jar:?]
airbyte-bootloader                | 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:179) ~[HikariCP-5.1.0.jar:?]
airbyte-bootloader                | 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:144) ~[HikariCP-5.1.0.jar:?]
airbyte-bootloader                | 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:99) ~[HikariCP-5.1.0.jar:?]
airbyte-bootloader                | 	at org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:87) ~[jooq-3.19.7.jar:?]
airbyte-bootloader                | 	... 22 more
airbyte-bootloader                | Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
airbyte-bootloader                | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:358) ~[postgresql-42.7.3.jar:42.7.3]
airbyte-bootloader                | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54) ~[postgresql-42.7.3.jar:42.7.3]
airbyte-bootloader                | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:273) ~[postgresql-42.7.3.jar:42.7.3]
airbyte-bootloader                | 	at org.postgresql.Driver.makeConnection(Driver.java:446) ~[postgresql-42.7.3.jar:42.7.3]
airbyte-bootloader                | 	at org.postgresql.Driver.connect(Driver.java:298) ~[postgresql-42.7.3.jar:42.7.3]
airbyte-bootloader                | 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137) ~[HikariCP-5.1.0.jar:?]
airbyte-bootloader                | 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360) ~[HikariCP-5.1.0.jar:?]
airbyte-bootloader                | 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202) ~[HikariCP-5.1.0.jar:?]
airbyte-bootloader                | 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461) ~[HikariCP-5.1.0.jar:?]
airbyte-bootloader                | 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724) ~[HikariCP-5.1.0.jar:?]
airbyte-bootloader                | 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703) ~[HikariCP-5.1.0.jar:?]
airbyte-bootloader                | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
airbyte-bootloader                | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
airbyte-bootloader                | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
airbyte-bootloader                | 	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
airbyte-bootloader                | Caused by: java.net.SocketTimeoutException: Connect timed out
airbyte-bootloader                | 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546) ~[?:?]
airbyte-bootloader                | 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592) ~[?:?]
airbyte-bootloader                | 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
airbyte-bootloader                | 	at java.base/java.net.Socket.connect(Socket.java:751) ~[?:?]
airbyte-bootloader                | 	at org.postgresql.core.PGStream.createSocket(PGStream.java:243) ~[postgresql-42.7.3.jar:42.7.3]
airbyte-bootloader                | 	at org.postgresql.core.PGStream.<init>(PGStream.java:98) ~[postgresql-42.7.3.jar:42.7.3]
airbyte-bootloader                | 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:136) ~[postgresql-42.7.3.jar:42.7.3]
airbyte-bootloader                | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:262) ~[postgresql-42.7.3.jar:42.7.3]
airbyte-bootloader                | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54) ~[postgresql-42.7.3.jar:42.7.3]
airbyte-bootloader                | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:273) ~[postgresql-42.7.3.jar:42.7.3]
airbyte-bootloader                | 	at org.postgresql.Driver.makeConnection(Driver.java:446) ~[postgresql-42.7.3.jar:42.7.3]
airbyte-bootloader                | 	at org.postgresql.Driver.connect(Driver.java:298) ~[postgresql-42.7.3.jar:42.7.3]
airbyte-bootloader                | 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137) ~[HikariCP-5.1.0.jar:?]
airbyte-bootloader                | 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360) ~[HikariCP-5.1.0.jar:?]
airbyte-bootloader                | 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202) ~[HikariCP-5.1.0.jar:?]
airbyte-bootloader                | 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461) ~[HikariCP-5.1.0.jar:?]
airbyte-bootloader                | 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724) ~[HikariCP-5.1.0.jar:?]
airbyte-bootloader                | 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703) ~[HikariCP-5.1.0.jar:?]
airbyte-bootloader                | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
airbyte-bootloader                | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
airbyte-bootloader                | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
airbyte-bootloader                | 	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
airbyte-bootloader                | 2024-07-30 11:11:36 INFO i.a.d.c.DatabaseAvailabilityCheck(check):49 - Database is not ready yet. Please wait a moment, it might still be initializing...
airbyte-bootloader                | 2024-07-30 11:11:42 WARN i.a.d.c.DatabaseAvailabilityCheck(check):38 - Waiting for database to become available...
airbyte-bootloader                | 2024-07-30 11:11:42 INFO i.a.d.c.DatabaseAvailabilityCheck(lambda$isDatabaseConnected$1):75 - Testing airbyte configs database connection...
airbyte-bootloader                | 2024-07-30 11:11:44 WARN i.m.s.r.u.Loggers$Slf4JLogger(warn):299 - [2e8c98af, L:/127.0.0.1:36780 - R:localhost/127.0.0.1:8125] An exception has been observed post termination, use DEBUG level to see the full stack: java.net.PortUnreachableException: recvAddress(..) failed: Connection refused
airbyte-bootloader                | 2024-07-30 11:11:44 WARN i.m.s.r.u.Loggers$Slf4JLogger(warn):299 - [2e8c98af, L:/127.0.0.1:36780 - R:localhost/127.0.0.1:8125] An exception has been observed post termination, use DEBUG level to see the full stack: java.net.PortUnreachableException: recvAddress(..) failed: Connection refused
airbyte-bootloader                | 2024-07-30 11:11:44 WARN i.m.s.r.u.Loggers$Slf4JLogger(warn):299 - [2e8c98af, L:/127.0.0.1:36780 - R:localhost/127.0.0.1:8125] An exception has been observed post termination, use DEBUG level to see the full stack: java.net.PortUnreachableException: recvAddress(..) failed: Connection refused
airbyte-bootloader                | 2024-07-30 11:11:44 WARN i.m.s.r.u.Loggers$Slf4JLogger(warn):299 - [2e8c98af, L:/127.0.0.1:36780 - R:localhost/127.0.0.1:8125] An exception has been observed post termination, use DEBUG level to see the full stack: java.net.PortUnreachableException: recvAddress(..) failed: Connection refused
airbyte-bootloader                | 2024-07-30 11:11:54 WARN i.m.s.r.u.Loggers$Slf4JLogger(warn):299 - [2e8c98af, L:/127.0.0.1:36780 - R:localhost/127.0.0.1:8125] An exception has been observed post termination, use DEBUG level to see the full stack: java.net.PortUnreachableException: recvAddress(..) failed: Connection refused
airbyte-bootloader                | 2024-07-30 11:11:54 WARN i.m.s.r.u.Loggers$Slf4JLogger(warn):299 - [2e8c98af, L:/127.0.0.1:36780 - R:localhost/127.0.0.1:8125] An exception has been observed post termination, use DEBUG level to see the full stack: java.net.PortUnreachableException: recvAddress(..) failed: Connection refused
airbyte-bootloader                | 2024-07-30 11:11:54 WARN i.m.s.r.u.Loggers$Slf4JLogger(warn):299 - [2e8c98af, L:/127.0.0.1:36780 - R:localhost/127.0.0.1:8125] An exception has been observed post termination, use DEBUG level to see the full stack: java.net.PortUnreachableException: recvAddress(..) failed: Connection refused
airbyte-bootloader                | 2024-07-30 11:11:54 WARN i.m.s.r.u.Loggers$Slf4JLogger(warn):299 - [2e8c98af, L:/127.0.0.1:36780 - R:localhost/127.0.0.1:8125] An exception has been observed post termination, use DEBUG level to see the full stack: java.net.PortUnreachableException: recvAddress(..) failed: Connection refused
airbyte-bootloader                | 2024-07-30 11:12:04 WARN i.m.s.r.u.Loggers$Slf4JLogger(warn):299 - [2e8c98af, L:/127.0.0.1:36780 - R:localhost/127.0.0.1:8125] An exception has been observed post termination, use DEBUG level to see the full stack: java.net.PortUnreachableException: recvAddress(..) failed: Connection refused
airbyte-bootloader                | 2024-07-30 11:12:04 WARN i.m.s.r.u.Loggers$Slf4JLogger(warn):299 - [2e8c98af, L:/127.0.0.1:36780 - R:localhost/127.0.0.1:8125] An exception has been observed post termination, use DEBUG level to see the full stack: java.net.PortUnreachableException: recvAddress(..) failed: Connection refused
airbyte-bootloader                | 2024-07-30 11:12:12 ERROR i.a.d.c.DatabaseAvailabilityCheck(lambda$isDatabaseConnected$1):78 - Failed to verify database connection.
```

**Comment by marcosmarxm** [comment]
The `run-ab-platform.sh` is a deprecated method to deploy Airbyte and won't receive updates. Please consider migrating your deployment to use abctl or Helm deployment.

**Comment by ivorpad** [comment]
@marcosmarxm Docs need a little love then 😅

Thanks for pointing it out.
