### ISSUE TITLE
[source-salesloft] incremental stream date format issue, error code 500

### ISSUE THREAD

**Issue by apd-kredsecker** [airbytehq/airbyte#42883]
### Connector Name

source-salesloft

### Connector Version

1.2.11

### What step the error happened?

During the sync

### Relevant information

The jobs are lasting >120 hours, only "partially" succeeding, and I keep getting this error message:
`
Request URL: https://api.salesloft.com/v2/accounts?created_at%5Bgt%5D=2023-06-01T00%3A00%3A00Z&updated_at%5Bgt%5D=%7B%7B+%0A+++format_datetime%28%0A+++%28config%5B%27start_date%27%5D+if+stream_state%5B%27updated_at%27%5D+is+not+defined+else%0A+++%28stream_state.updated_at+if+stream_state.updated_at+%3C+now_utc%28%29+else+now_utc%28%29%29%29%2C+%0A+++%27%25Y-%25m-%25dT%25H%3A%25M%3A%25S.%25fZ%27%0A+++%29+%0A+%7D%7D&per_page=100, Response Code: 500, Response Text: {"status":500,"error":"Internal Server Error"}
`
reformatted:
`
https://api.salesloft.com/v2/accounts?created_at[gt]=2023-06-01T00:00:00Z&updated_at[gt]={{+
+++format_datetime(
+++(config['start_date']+if+stream_state['updated_at']+is+not+defined+else
+++(stream_state.updated_at+if+stream_state.updated_at+<+now_utc()+else+now_utc())),+
+++'%Y-%m-%dT%H:%M:%S.%fZ'
+++)+
+}}&per_page=100,ResponseCode:500,ResponseText:{"status":500,"error":"InternalServerError"}
`

Reached out to Salesloft Support who said "I suspect that the issue is due to how the date variable is being referenced in the API call. Can you verify that the variable set in this API call is being changed to a date/time value before being sent to Salesloft?"

<img width="715" alt="image" src="https://github.com/user-attachments/assets/7e305320-9b1f-4c63-9bf0-7e5e9832a2dc">

### Relevant log output

```shell
2024-07-20 02:20:08 source > Giving up _send(...) after 5 tries (airbyte_cdk.sources.streams.http.exceptions.UserDefinedBackoffException: Request URL: https://api.salesloft.com/v2/accounts?created_at%5Bgt%5D=2023-06-01T00%3A00%3A00Z&updated_at%5Bgt%5D=%7B%7B+%0A+++format_datetime%28%0A+++%28config%5B%27start_date%27%5D+if+stream_state%5B%27updated_at%27%5D+is+not+defined+else%0A+++%28stream_state.updated_at+if+stream_state.updated_at+%3C+now_utc%28%29+else+now_utc%28%29%29%29%2C+%0A+++%27%25Y-%25m-%25dT%25H%3A%25M%3A%25S.%25fZ%27%0A+++%29+%0A+%7D%7D&per_page=100, Response Code: 500, Response Text: {"status":500,"error":"Internal Server Error"})
2024-07-20 02:20:08 source > Max retry limit reached. Request: <PreparedRequest [GET]>, Response: <Response [500]>
2024-07-20 02:20:08 source > Encountered an exception while reading stream accounts
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py", line 136, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py", line 237, in _read_stream
    for record_data_or_message in record_iterator:
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/streams/core.py", line 145, in read
    for record_data_or_message in records:
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py", line 120, in read_records
    yield from self.retriever.read_records(self.get_json_schema(), stream_slice)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 324, in read_records
    for stream_data in self._read_pages(record_generator, self.state, _slice):
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 288, in _read_pages
    response = self._fetch_next_page(stream_state, stream_slice, next_page_token)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 263, in _fetch_next_page
    return self.requester.send_request(
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 460, in send_request
    response = self._send_with_retry(request, log_formatter=log_formatter)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 506, in _send_with_retry
    return backoff_handler(user_backoff_handler)(request, log_formatter=log_formatter)  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 545, in _send
    raise UserDefinedBackoffException(backoff=custom_backoff_time, request=request, response=response)
airbyte_cdk.sources.streams.http.exceptions.UserDefinedBackoffException: Request URL: https://api.salesloft.com/v2/accounts?created_at%5Bgt%5D=2023-06-01T00%3A00%3A00Z&updated_at%5Bgt%5D=%7B%7B+%0A+++format_datetime%28%0A+++%28config%5B%27start_date%27%5D+if+stream_state%5B%27updated_at%27%5D+is+not+defined+else%0A+++%28stream_state.updated_at+if+stream_state.updated_at+%3C+now_utc%28%29+else+now_utc%28%29%29%29%2C+%0A+++%27%25Y-%25m-%25dT%25H%3A%25M%3A%25S.%25fZ%27%0A+++%29+%0A+%7D%7D&per_page=100, Response Code: 500, Response Text: {"status":500,"error":"Internal Server Error"}
2024-07-20 02:20:08 source > Marking stream accounts as STOPPED
2024-07-20 02:20:08 replication-orchestrator > Stream status TRACE received of status: INCOMPLETE for stream accounts
2024-07-20 02:20:08 replication-orchestrator > Sending update for accounts - RUNNING -> INCOMPLETE
2024-07-20 02:20:08 replication-orchestrator > Stream Status Update Received: accounts - INCOMPLETE
2024-07-20 02:20:08 source > Finished syncing accounts
2024-07-20 02:20:08 replication-orchestrator > Updating status: accounts - INCOMPLETE
2024-07-20 02:20:08 source > SourceSalesloft runtimes:
Syncing stream accounts 0:28:26.059568
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by natikgadzhi** [comment]
Thank you for filing this! I'll figure out how to prioritize this and hopefully take a look this week

**Comment by apd-kredsecker** [comment]
@natikgadzhi just checking in on any progress here as I'm still getting the same errors. thanks!
![image](https://github.com/user-attachments/assets/6baba84f-119b-4517-9e3f-17242d6a6543)

**Comment by natikgadzhi** [comment]
@pabloescoder want to take this one too?

**Comment by pabloescoder** [comment]
@natikgadzhi Starting to work on this

**Comment by natikgadzhi** [comment]
@pabloescoder how's it looking? Need help?

**Comment by pabloescoder** [comment]
@natikgadzhi Apologies for the long delay, I've raised a PR for fixing this issue. https://github.com/airbytehq/airbyte/pull/48770
Note: There was a lot of duplication in the manifest so the diff is huge
