### ISSUE TITLE
Airyte worker fails to create job pods with `metadata.labels: Invalid value: "<port>/<connector_image>:x.y.z": must be no more than 63 characters`

### ISSUE THREAD

**Issue by ogusak** [airbytehq/airbyte#43376]
### Helm Chart Version

0.63.14

### What step the error happened?

During the Sync

### Relevant information

When airbyte worker pod is trying to create a connector job (e.g., launching source spec pod) it fails with the error (truncated to relevant lines only, image name is obfuscated):

```
Caused by: io.airbyte.workers.exception.WorkerException: Failed to create pod for spec step
	at io.airbyte.workers.process.KubeProcessFactory.create(KubeProcessFactory.java:197) ~[io.airbyte-airbyte-commons-worker-0.63.7.jar:?]
	at io.airbyte.workers.process.AirbyteIntegrationLauncher.spec(AirbyteIntegrationLauncher.java:121) ~[io.airbyte-airbyte-commons-worker-0.63.7.jar:?]
	at io.airbyte.workers.general.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:55) ~[io.airbyte-airbyte-commons-worker-0.63.7.jar:?]
	at io.airbyte.workers.general.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:36) ~[io.airbyte-airbyte-commons-worker-0.63.7.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:138) ~[io.airbyte-airbyte-workers-0.63.7.jar:?]
	at io.airbyte.workers.temporal.spec.SpecActivityImpl.lambda$run$2(SpecActivityImpl.java:168) ~[io.airbyte-airbyte-workers-0.63.7.jar:?]
	at io.airbyte.commons.temporal.HeartbeatUtils.withBackgroundHeartbeat(HeartbeatUtils.java:57) ~[io.airbyte-airbyte-commons-temporal-core-0.63.7.jar:?]
	... 14 more
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://127.1.1.1:443/api/v1/namespaces/aname/pods. Message: Pod "xyz-spec-829b8976-cd2a-4bc6-97e8-750073dd77a8-0-oiwlb" is invalid: [metadata.labels: Invalid value: "1234/repository/docker/mypath/airbyte-bitbucket-server-source:0.9.88": must be no more than 63 characters, metadata.labels: Invalid value: "1234/repository/docker/mypath/airbyte-bitbucket-server-source:0.9.88": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.labels, message=Invalid value: "1234/repository/docker/mypath/airbyte-bitbucket-server-source:0.9.88": must be no more than 63 characters, reason=FieldValueInvalid, additionalProperties={}), StatusCause(field=metadata.labels, message=Invalid value: "1234/repository/docker/mypath/airbyte-bitbucket-server-source:0.9.88": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'), reason=FieldValueInvalid, additionalProperties={})], group=null, kind=Pod, name=xyz-spec-829b8976-cd2a-4bc6-97e8-750073dd77a8-0-oiwlb, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Pod "xyz-spec-829b8976-cd2a-4bc6-97e8-750073dd77a8-0-oiwlb" is invalid: [metadata.labels: Invalid value: "1234/repository/docker/mypath/airbyte-bitbucket-server-source:0.9.88": must be no more than 63 characters, metadata.labels: Invalid value: "1234/repository/docker/mypath/airbyte-bitbucket-server-source:0.9.88": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')], metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
``` 

I suspect the error is due to incorrect image tag label generated by worker. Each connection pod is labeled with short [image name and image tag](https://github.com/airbytehq/airbyte-platform/blob/main/airbyte-commons-worker/src/main/java/io/airbyte/workers/process/KubeProcessFactory.java#L246-L247). The image tag value is [parsed from full image name](https://github.com/airbytehq/airbyte-platform/blob/main/airbyte-commons-worker/src/main/java/io/airbyte/workers/process/ProcessFactory.java#L121-L130) . However, the parsing assumes the the full image name is of format:
```
<image_registry>/<image_repo>/<image_name>:<image_tag>
```
That is it assumes there is only single separator `:` in the string and hence the code relies on finding first occurrence of `:` separator (ProcessFactory.java#L121-L130):
``` 
    int colonIndex = fullImagePath.indexOf(":");
    if (colonIndex != -1 && fullImagePath.length() > colonIndex + 1) {
      return fullImagePath.substring(colonIndex + 1);
    }
    return null;
```
However, in a more general case, and usually the case with private registries, the full image name may contain one more separator `:` - which is the delimiter for registry port, that is the full image name has format:
```
<image_registry>:<port>/<image_repo>/<image_name>:<image_tag>
```
and hence parsing of image tag with the code above results in string `<port>/<image_repo>/<image_name>:<image_tag>` and which is in our case much longer than 63 characters. 

The error can be fixed by replacing `fullImagePath.indexOf(":");` in the code above with `fullImagePath.lastIndexOf(":");`

Please note that there are few other places in Airbyte's code which assume only single delimiter `:` in the full image name and which may lead to incorrect tag being extracted. See
https://github.com/airbytehq/airbyte-platform/blob/main/airbyte-commons-worker/src/main/java/io/airbyte/workers/helper/ConnectorApmSupportHelper.java#L90
and 
https://github.com/airbytehq/airbyte-platform/blob/main/airbyte-commons-with-dependencies/src/main/java/io/airbyte/commons/helper/DockerImageNameHelper.java#L80

### Relevant log output

```shell
2024-08-06 16:35:47 [46mplatform[0m > Creating pod ixyz-spec-829b8976-cd2a-4bc6-97e8-750073dd77a8-0-oiwlb...
  java.net.SocketException: Socket closed
      at java.base/sun.nio.ch.NioSocketImpl.endAccept(NioSocketImpl.java:682)
      at java.base/sun.nio.ch.NioSocketImpl.accept(NioSocketImpl.java:755)
      at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:698)
      at java.base/java.net.ServerSocket.platformImplAccept(ServerSocket.java:663)
      at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:639)
      at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:585)
      at java.base/java.net.ServerSocket.accept(ServerSocket.java:543)
      at io.airbyte.workers.process.KubePodProcess.lambda$setupStdOutAndStdErrListeners$11(KubePodProcess.java:734)
      at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
      at java.base/java.lang.Thread.run(Thread.java:1583)
  java.net.SocketException: Socket closed
      at java.base/sun.nio.ch.NioSocketImpl.endAccept(NioSocketImpl.java:682)
      at java.base/sun.nio.ch.NioSocketImpl.accept(NioSocketImpl.java:755)
      at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:698)
      at java.base/java.net.ServerSocket.platformImplAccept(ServerSocket.java:663)
      at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:639)
      at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:585)
      at java.base/java.net.ServerSocket.accept(ServerSocket.java:543)
      at io.airbyte.workers.process.KubePodProcess.lambda$setupStdOutAndStdErrListeners$10(KubePodProcess.java:716)
      at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
      at java.base/java.lang.Thread.run(Thread.java:1583)
  2024-08-06 16:35:48 [46mplatform[0m > Unexpected: PodDefinition is null when closing in KubePodProcess. Log an error to help debugging but not blocking the process.
  2024-08-06 16:35:48 [32mINFO[m i.a.c.t.HeartbeatUtils(withBackgroundHeartbeat):64 - Stopping temporal heartbeating...
  2024-08-06 16:35:48 [32mINFO[m i.a.c.t.HeartbeatUtils(withBackgroundHeartbeat):73 - Temporal heartbeating stopped.
  2024-08-06 16:35:48 [33mWARN[m i.t.i.a.ActivityTaskExecutors$BaseActivityTaskExecutor(execute):126 - Activity failure. ActivityId=9633dc36-8ffd-363d-a9d7-26422562c54e, activityType=Run, attempt=1
  java.lang.RuntimeException: io.temporal.serviceclient.CheckedExceptionWrapper: io.airbyte.workers.exception.WorkerException: Error while getting spec from image registry:1234/repository/docker/abcd/efgh/airbyte-bitbucket-server-source:0.9.88
      at io.airbyte.commons.temporal.HeartbeatUtils.withBackgroundHeartbeat(HeartbeatUtils.java:62) ~[io.airbyte-airbyte-commons-temporal-core-0.63.7.jar:?]
      at io.airbyte.workers.temporal.spec.SpecActivityImpl.run(SpecActivityImpl.java:152) ~[io.airbyte-airbyte-workers-0.63.7.jar:?]
      at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
      at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
      at io.temporal.internal.activity.RootActivityInboundCallsInterceptor$POJOActivityInboundCallsInterceptor.executeActivity(RootActivityInboundCallsInterceptor.java:64) ~[temporal-sdk-1.22.3.jar:?]
      at io.temporal.internal.activity.RootActivityInboundCallsInterceptor.execute(RootActivityInboundCallsInterceptor.java:43) ~[temporal-sdk-1.22.3.jar:?]
      at io.temporal.internal.activity.ActivityTaskExecutors$BaseActivityTaskExecutor.execute(ActivityTaskExecutors.java:107) ~[temporal-sdk-1.22.3.jar:?]
      at io.temporal.internal.activity.ActivityTaskHandlerImpl.handle(ActivityTaskHandlerImpl.java:124) ~[temporal-sdk-1.22.3.jar:?]
      at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handleActivity(ActivityWorker.java:278) ~[temporal-sdk-1.22.3.jar:?]
      at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:243) ~[temporal-sdk-1.22.3.jar:?]
      at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:216) ~[temporal-sdk-1.22.3.jar:?]
      at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:105) ~[temporal-sdk-1.22.3.jar:?]
      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
      at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
  Caused by: io.temporal.serviceclient.CheckedExceptionWrapper: io.airbyte.workers.exception.WorkerException: Error while getting spec from image registry:1234/repository/docker/abcd/efgh/airbyte-bitbucket-server-source:0.9.88
      at io.temporal.serviceclient.CheckedExceptionWrapper.wrap(CheckedExceptionWrapper.java:57) ~[temporal-serviceclient-1.22.3.jar:?]
      at io.temporal.internal.sync.WorkflowInternal.wrap(WorkflowInternal.java:539) ~[temporal-sdk-1.22.3.jar:?]
      at io.temporal.activity.Activity.wrap(Activity.java:52) ~[temporal-sdk-1.22.3.jar:?]
      at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:143) ~[io.airbyte-airbyte-workers-0.63.7.jar:?]
      at io.airbyte.workers.temporal.spec.SpecActivityImpl.lambda$run$2(SpecActivityImpl.java:168) ~[io.airbyte-airbyte-workers-0.63.7.jar:?]
      at io.airbyte.commons.temporal.HeartbeatUtils.withBackgroundHeartbeat(HeartbeatUtils.java:57) ~[io.airbyte-airbyte-commons-temporal-core-0.63.7.jar:?]
      ... 14 more
  Caused by: io.airbyte.workers.exception.WorkerException: Error while getting spec from image registry:1234/repository/docker/abcd/efgh/airbyte-bitbucket-server-source:0.9.88
      at io.airbyte.workers.general.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:83) ~[io.airbyte-airbyte-commons-worker-0.63.7.jar:?]
      at io.airbyte.workers.general.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:36) ~[io.airbyte-airbyte-commons-worker-0.63.7.jar:?]
      at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:138) ~[io.airbyte-airbyte-workers-0.63.7.jar:?]
      at io.airbyte.workers.temporal.spec.SpecActivityImpl.lambda$run$2(SpecActivityImpl.java:168) ~[io.airbyte-airbyte-workers-0.63.7.jar:?]
      at io.airbyte.commons.temporal.HeartbeatUtils.withBackgroundHeartbeat(HeartbeatUtils.java:57) ~[io.airbyte-airbyte-commons-temporal-core-0.63.7.jar:?]
      ... 14 more
  Caused by: io.airbyte.workers.exception.WorkerException: Failed to create pod for spec step
      at io.airbyte.workers.process.KubeProcessFactory.create(KubeProcessFactory.java:197) ~[io.airbyte-airbyte-commons-worker-0.63.7.jar:?]
      at io.airbyte.workers.process.AirbyteIntegrationLauncher.spec(AirbyteIntegrationLauncher.java:121) ~[io.airbyte-airbyte-commons-worker-0.63.7.jar:?]
      at io.airbyte.workers.general.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:55) ~[io.airbyte-airbyte-commons-worker-0.63.7.jar:?]
      at io.airbyte.workers.general.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:36) ~[io.airbyte-airbyte-commons-worker-0.63.7.jar:?]
      at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:138) ~[io.airbyte-airbyte-workers-0.63.7.jar:?]
      at io.airbyte.workers.temporal.spec.SpecActivityImpl.lambda$run$2(SpecActivityImpl.java:168) ~[io.airbyte-airbyte-workers-0.63.7.jar:?]
      at io.airbyte.commons.temporal.HeartbeatUtils.withBackgroundHeartbeat(HeartbeatUtils.java:57) ~[io.airbyte-airbyte-commons-temporal-core-0.63.7.jar:?]
      ... 14 more
  Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://127.1.1.1:443/api/v1/namespaces/aspace/pods. Message: Pod "ixyz-spec-829b8976-cd2a-4bc6-97e8-750073dd77a8-0-oiwlb" is invalid: [metadata.labels: Invalid value: "1234/repository/docker/abcd/efgh/airbyte-bitbucket-server-source:0.9.88": must be no more than 63 characters, metadata.labels: Invalid value: "1234/repository/docker/abcd/efgh/airbyte-bitbucket-server-source:0.9.88": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.labels, message=Invalid value: "1234/repository/docker/abcd/efgh/airbyte-bitbucket-server-source:0.9.88": must be no more than 63 characters, reason=FieldValueInvalid, additionalProperties={}), StatusCause(field=metadata.labels, message=Invalid value: "1234/repository/docker/abcd/efgh/airbyte-bitbucket-server-source:0.9.88": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'), reason=FieldValueInvalid, additionalProperties={})], group=null, kind=Pod, name=ixyz-spec-829b8976-cd2a-4bc6-97e8-750073dd77a8-0-oiwlb, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Pod "ixyz-spec-829b8976-cd2a-4bc6-97e8-750073dd77a8-0-oiwlb" is invalid: [metadata.labels: Invalid value: "1234/repository/docker/abcd/efgh/airbyte-bitbucket-server-source:0.9.88": must be no more than 63 characters, metadata.labels: Invalid value: "1234/repository/docker/abcd/efgh/airbyte-bitbucket-server-source:0.9.88": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')], metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
      at io.fabric8.kubernetes.client.KubernetesClientException.copyAsCause(KubernetesClientException.java:238) ~[kubernetes-client-api-6.12.1.jar:?]
      at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:507) ~[kubernetes-client-6.12.1.jar:?]
      at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:524) ~[kubernetes-client-6.12.1.jar:?]
      at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleCreate(OperationSupport.java:340) ~[kubernetes-client-6.12.1.jar:?]
      at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleCreate(BaseOperation.java:754) ~[kubernetes-client-6.12.1.jar:?]
      at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleCreate(BaseOperation.java:98) ~[kubernetes-client-6.12.1.jar:?]
      at io.fabric8.kubernetes.client.dsl.internal.CreateOnlyResourceOperation.create(CreateOnlyResourceOperation.java:42) ~[kubernetes-client-6.12.1.jar:?]
      at io.fabric8.kubernetes.client.utils.internal.CreateOrReplaceHelper.createOrReplace(CreateOrReplaceHelper.java:53) ~[kubernetes-client-6.12.1.jar:?]
      at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.createOrReplace(BaseOperation.java:314) ~[kubernetes-client-6.12.1.jar:?]
      at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.createOrReplace(BaseOperation.java:98) ~[kubernetes-client-6.12.1.jar:?]
      at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.createOrReplace(BaseOperation.java:1120) ~[kubernetes-client-6.12.1.jar:?]
      at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.createOrReplace(BaseOperation.java:98) ~[kubernetes-client-6.12.1.jar:?]
      at io.airbyte.workers.process.KubePodProcess.<init>(KubePodProcess.java:643) ~[io.airbyte-airbyte-commons-worker-0.63.7.jar:?]
      at io.airbyte.workers.process.KubeProcessFactory.create(KubeProcessFactory.java:193) ~[io.airbyte-airbyte-commons-worker-0.63.7.jar:?]
      at io.airbyte.workers.process.AirbyteIntegrationLauncher.spec(AirbyteIntegrationLauncher.java:121) ~[io.airbyte-airbyte-commons-worker-0.63.7.jar:?]
      at io.airbyte.workers.general.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:55) ~[io.airbyte-airbyte-commons-worker-0.63.7.jar:?]
      at io.airbyte.workers.general.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:36) ~[io.airbyte-airbyte-commons-worker-0.63.7.jar:?]
      at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:138) ~[io.airbyte-airbyte-workers-0.63.7.jar:?]
      at io.airbyte.workers.temporal.spec.SpecActivityImpl.lambda$run$2(SpecActivityImpl.java:168) ~[io.airbyte-airbyte-workers-0.63.7.jar:?]
      at io.airbyte.commons.temporal.HeartbeatUtils.withBackgroundHeartbeat(HeartbeatUtils.java:57) ~[io.airbyte-airbyte-commons-temporal-core-0.63.7.jar:?]
      ... 14 more
  Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://127.1.1.1:443/api/v1/namespaces/aspace/pods. Message: Pod "ixyz-spec-829b8976-cd2a-4bc6-97e8-750073dd77a8-0-oiwlb" is invalid: [metadata.labels: Invalid value: "1234/repository/docker/abcd/efgh/airbyte-bitbucket-server-source:0.9.88": must be no more than 63 characters, metadata.labels: Invalid value: "1234/repository/docker/abcd/efgh/airbyte-bitbucket-server-source:0.9.88": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.labels, message=Invalid value: "1234/repository/docker/abcd/efgh/airbyte-bitbucket-server-source:0.9.88": must be no more than 63 characters, reason=FieldValueInvalid, additionalProperties={}), StatusCause(field=metadata.labels, message=Invalid value: "1234/repository/docker/abcd/efgh/airbyte-bitbucket-server-source:0.9.88": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'), reason=FieldValueInvalid, additionalProperties={})], group=null, kind=Pod, name=ixyz-spec-829b8976-cd2a-4bc6-97e8-750073dd77a8-0-oiwlb, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Pod "ixyz-spec-829b8976-cd2a-4bc6-97e8-750073dd77a8-0-oiwlb" is invalid: [metadata.labels: Invalid value: "1234/repository/docker/abcd/efgh/airbyte-bitbucket-server-source:0.9.88": must be no more than 63 characters, metadata.labels: Invalid value: "1234/repository/docker/abcd/efgh/airbyte-bitbucket-server-source:0.9.88": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')], metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
      at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:660) ~[kubernetes-client-6.12.1.jar:?]
      at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:640) ~[kubernetes-client-6.12.1.jar:?]
      at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.assertResponseCode(OperationSupport.java:589) ~[kubernetes-client-6.12.1.jar:?]
      at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.lambda$handleResponse$0(OperationSupport.java:549) ~[kubernetes-client-6.12.1.jar:?]
      at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
      at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
      at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179) ~[?:?]
      at io.fabric8.kubernetes.client.http.StandardHttpClient.lambda$completeOrCancel$10(StandardHttpClient.java:142) ~[kubernetes-client-api-6.12.1.jar:?]
      at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
      at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
      at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
      at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179) ~[?:?]
      at io.fabric8.kubernetes.client.http.ByteArrayBodyHandler.onBodyDone(ByteArrayBodyHandler.java:51) ~[kubernetes-client-api-6.12.1.jar:?]
      at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
      at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
      at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
      at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179) ~[?:?]
      at io.fabric8.kubernetes.client.okhttp.OkHttpClientImpl$OkHttpAsyncBody.doConsume(OkHttpClientImpl.java:136) ~[kubernetes-httpclient-okhttp-6.12.1.jar:?]
      ... 3 more
```

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 180 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by ogusak** [comment]
it is already fixed by https://github.com/airbytehq/airbyte-platform/pull/349
