### ISSUE TITLE
[source-stripe] Stripe sync charges always failed around 9.5 hours running

### ISSUE THREAD

**Issue by yin-ym** [airbytehq/airbyte#43428]
### Connector Name

source-stripe

### Connector Version

5.4.9

### What step the error happened?

During the sync

### Relevant information

Recently, we found our stripe sync always failed with following error:

platform > readFromSource: exception caught
io.airbyte.workers.exception.WorkerException: A stream status (null.charges) has been detected for a stream not present in the catalog

Not sure what happened, but since first happen this issue, we have accumulated nearly 14 days of out-of-sync data, and it is more and more difficult to get these data synced. Today, we found the sync job will reach to this issue near 9.5 hours run, and start over again. This is really frustrating. Please help to check and advise.

### Relevant log output

```shell
2024-08-09 12:28:11 source > Read 4270470 records from charges stream
2024-08-09 12:28:11 source > Marking stream charges as STOPPED
2024-08-09 12:28:11 platform > readFromSource: exception caught
io.airbyte.workers.exception.WorkerException: A stream status (null.charges) has been detected for a stream not present in the catalog
        at io.airbyte.workers.helper.StreamStatusCompletionTracker.track(StreamStatusCompletionTracker.kt:36) ~[io.airbyte-airbyte-commons-worker-0.63.7.jar:?]
        at io.airbyte.workers.general.BufferedReplicationWorker.readFromSource(BufferedReplicationWorker.java:361) ~[io.airbyte-airbyte-commons-worker-0.63.7.jar:?]
        at io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsyncWithHeartbeatCheck$3(BufferedReplicationWorker.java:242) ~[io.airbyte-airbyte-commons-worker-0.63.7.jar:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
2024-08-09 12:28:11 platform > readFromSource: done. (source.isFinished:false, fromSource.isClosed:false)
2024-08-09 12:28:11 platform > processMessage: done. (fromSource.isDone:true, forDest.isClosed:false)
2024-08-09 12:28:11 platform > writeToDestination: exception caught
java.lang.IllegalStateException: Source process is still alive, cannot retrieve exit value.
        at com.google.common.base.Preconditions.checkState(Preconditions.java:515) ~[guava-33.2.0-jre.jar:?]
        at io.airbyte.workers.internal.DefaultAirbyteSource.getExitValue(DefaultAirbyteSource.java:136) ~[io.airbyte-airbyte-commons-worker-0.63.7.jar:?]
        at io.airbyte.workers.general.BufferedReplicationWorker.writeToDestination(BufferedReplicationWorker.java:454) ~[io.airbyte-airbyte-commons-worker-0.63.7.jar:?]
        at io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsyncWithTimeout$5(BufferedReplicationWorker.java:263) ~[io.airbyte-airbyte-commons-worker-0.63.7.jar:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
2024-08-09 12:28:11 platform > writeToDestination: done. (forDest.isDone:true, isDestRunning:true)
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by jdpgrailsdev** [comment]
@yin-ym We have committed a fix that should address the issue with the "missing stream".  This fix is in release [v0.64.5](https://github.com/airbytehq/airbyte-platform/releases/tag/v0.64.5).  Please update to that release or any later version to see if it addresses the issue for you.  Thank you for your patience!

**Comment by yin-ym** [comment]
@jdpgrailsdev thank you so much, we will check that version (or newer) and go back to you soon.
