### ISSUE TITLE
Source Facebook Marketing: cannot sync 1 year of data sync failed

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#4375]
## Expected Behavior
Connector should work properly.

## Current Behavior
From [slack convo](https://airbytehq.slack.com/archives/C01MFR03D5W/p1624623845008300):

We are trying to pull facebook data for 1 year (have upgraded to latest version). It's failing at some point and never got completed.
```
2021-06-25 11:38:45 INFO (/tmp/workspace/1281/2) DefaultAirbyteStreamFactory(internalLog):110 - Setting state of ads_insights stream to {'updated_time': '2021-06-25T00:00:00+00:00', 'include_deleted': False}
2021-06-25 11:38:45 INFO (/tmp/workspace/1281/2) DefaultAirbyteStreamFactory(internalLog):110 - Created AdReportRun: 1222416931528134 to sync insights {'since': '2021-04-05', 'until': '2021-04-11'} with breakdown []
2021-06-25 11:38:45 INFO (/tmp/workspace/1281/2) DefaultAirbyteStreamFactory(internalLog):110 - ReportRunId 332991678455243 is 100% complete
2021-06-25 11:39:24 ERROR (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - Traceback (most recent call last):
2021-06-25 11:39:24 ERROR (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - File "/airbyte/integration_code/main.py", line 33, in <module>
2021-06-25 11:39:24 ERROR (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - launch(source, sys.argv[1:])
2021-06-25 11:39:24 ERROR (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 117, in launch
2021-06-25 11:39:24 ERROR (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - for message in source_entrypoint.run(parsed_args):
2021-06-25 11:39:24 ERROR (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 108, in run
2021-06-25 11:39:24 ERROR (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - for message in generator:
2021-06-25 11:39:24 ERROR (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 114, in read
2021-06-25 11:39:24 ERROR (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - raise e
2021-06-25 11:39:24 ERROR (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 110, in read
2021-06-25 11:39:24 ERROR (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - logger=logger, stream_instance=stream_instance, configured_stream=configured_stream, connector_state=connector_state
2021-06-25 11:39:24 INFO (/tmp/workspace/1281/2) DefaultAirbyteStreamFactory(internalLog):110 - Setting state of ads_insights stream to {'updated_time': '2021-06-25T00:00:00+00:00', 'include_deleted': False}
2021-06-25 11:39:24 ERROR (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 135, in _read_stream
2021-06-25 11:39:24 ERROR (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - for record in record_iterator:
2021-06-25 11:39:24 ERROR (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 166, in _read_incremental
2021-06-25 11:39:24 ERROR (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - for record_data in records:
2021-06-25 11:39:24 ERROR (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - File "/airbyte/integration_code/source_facebook_marketing/streams.py", line 298, in read_records
2021-06-25 11:39:24 ERROR (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - result = self.wait_for_job(stream_slice["job"])
2021-06-25 11:39:24 ERROR (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
2021-06-25 11:39:24 ERROR (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - ret = target(*args, **kwargs)
2021-06-25 11:39:24 ERROR (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - File "/airbyte/integration_code/source_facebook_marketing/streams.py", line 344, in wait_for_job
2021-06-25 11:39:24 ERROR (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - raise JobTimeoutException(f"AdReportRun {job} failed after {runtime.in_seconds()} seconds.")
2021-06-25 11:39:24 ERROR (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - source_facebook_marketing.common.JobTimeoutException: AdReportRun <AdReportRun> {
2021-06-25 11:39:24 ERROR (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - "account_id": "4674005327524",
2021-06-25 11:39:24 ERROR (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - "async_percent_completion": 66,
2021-06-25 11:39:24 ERROR (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - "async_status": "Job Failed",
2021-06-25 11:39:24 ERROR (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - "date_start": "2021-03-29",
2021-06-25 11:39:24 ERROR (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - "date_stop": "2021-04-04",
2021-06-25 11:39:24 ERROR (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - "id": "502737140784384",
2021-06-25 11:39:24 ERROR (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - "report_run_id": "502737140784384",
2021-06-25 11:39:24 ERROR (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - "time_ref": 1624621077
2021-06-25 11:39:24 ERROR (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - } failed after 0 seconds.
2021-06-25 11:39:24 INFO (/tmp/workspace/1281/2) DefaultAirbyteStreamFactory(internalLog):110 - Created AdReportRun: 341397384181755 to sync insights {'since': '2021-04-12', 'until': '2021-04-18'} with breakdown []
2021-06-25 11:39:24 INFO (/tmp/workspace/1281/2) DefaultAirbyteStreamFactory(internalLog):110 - ReportRunId 502737140784384 is 66% complete
2021-06-25 11:39:24 ERROR (/tmp/workspace/1281/2) DefaultAirbyteStreamFactory(internalLog):108 - Encountered an exception while reading stream SourceFacebookMarketing
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 110, in read
logger=logger, stream_instance=stream_instance, configured_stream=configured_stream, connector_state=connector_state
File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 135, in _read_stream
for record in record_iterator:
File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 166, in _read_incremental
for record_data in records:
File "/airbyte/integration_code/source_facebook_marketing/streams.py", line 298, in read_records
result = self.wait_for_job(stream_slice["job"])
File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
ret = target(*args, **kwargs)
File "/airbyte/integration_code/source_facebook_marketing/streams.py", line 344, in wait_for_job
raise JobTimeoutException(f"AdReportRun {job} failed after {runtime.in_seconds()} seconds.")
source_facebook_marketing.common.JobTimeoutException: AdReportRun <AdReportRun> {
"account_id": "4674005327524",
"async_percent_completion": 66,
"async_status": "Job Failed",
"date_start": "2021-03-29",
"date_stop": "2021-04-04",
"id": "502737140784384",
"report_run_id": "502737140784384",
"time_ref": 1624621077
} failed after 0 seconds.
2021-06-25 11:39:24 INFO (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - 2021-06-25 11:39:24 [32mINFO[m i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):77 - {} - hasFailed: false.
2021-06-25 11:39:29 INFO (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - 2021-06-25 11:39:29 [1;31mERROR[m i.a.i.d.b.BigQueryDestination$RecordConsumer(close):349 - {} - executing on success close procedure.
2021-06-25 11:39:31 INFO (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - 2021-06-25 11:39:31 [32mINFO[m i.a.i.b.IntegrationRunner(run):120 - {} - Completed integration: io.airbyte.integrations.destination.bigquery.BigQueryDestination
2021-06-25 11:39:31 INFO (/tmp/workspace/1281/2) LineGobbler(voidCall):69 - 2021-06-25 11:39:31 [32mINFO[m i.a.i.d.b.BigQueryDestination(main):397 - {} - completed destination: class io.airbyte.integrations.destination.bigquery.BigQueryDestination
2021-06-25 11:39:31 INFO (/tmp/workspace/1281/2) TemporalAttemptExecution(lambda$getWorkerThread$2):150 - Completing future exceptionally...
```

## Logs
*If applicable, please upload the logs from the failing operation. For sync jobs, you can download the full logs from the UI by going to the sync attempt page and clicking the download logs button at the top right of the logs display window.*

## Steps to Reproduce
1.
1.
1.

## Severity of the bug for you
Very low / Low / Medium / High / Critical

## Airbyte Version
Not informed

## Connector Version (if applicable)
0.2.12

## Additional context
From slack convo:
- I am not sure but moved back to older version and things are working

**Comment by marcosmarxm** [comment]
> Hey it's true we did face issues when we pulled data for one year. I have missed one very beautiful line from the  source settings (I agree since we only update version it's quite possible that we miss this) Number of days to sync in one job. The more data you have - the smaller you want this parameter to be. it's a parameter called Insights Days Per Job which we can configure to 1 and it works. We did approx 30 pulls all 1 year and it never failed.
