### ISSUE TITLE
workload-launcher pod fails with operation not permitted on temporal

### ISSUE THREAD

**Issue by hanslemm** [airbytehq/airbyte#44024]
### Helm Chart Version

0.390.0

### What step the error happened?

On deploy

### Relevant information

The `workload-launcher` pod fails when deploying with operation not permitted. Even when `temporal` is healthy, the `workload-launcher` does not recover on its own. Killing the pod usually fix the issue (but it is highly incovenient).

### Relevant log output

```shell
2024-08-13 17:36:25.140	
Unsetting empty environment variable 'ACTIVITY_MAX_DELAY_BETWEEN_ATTEMPTS_SECONDS'
2024-08-13 17:36:25.140	
Unsetting empty environment variable 'PUB_SUB_TOPIC_NAME'
2024-08-13 17:36:25.140	
Unsetting empty environment variable 'OTEL_COLLECTOR_ENDPOINT'
2024-08-13 17:36:25.140	
Unsetting empty environment variable 'ACTIVITY_MAX_ATTEMPT'
2024-08-13 17:36:25.140	
Unsetting empty environment variable 'JOB_MAIN_CONTAINER_CPU_LIMIT'
2024-08-13 17:36:25.140	
Unsetting empty environment variable 'VERSION'
2024-08-13 17:36:25.140	
Unsetting empty environment variable 'WORKFLOW_FAILURE_RESTART_DELAY_SECONDS'
2024-08-13 17:36:25.140	
Unsetting empty environment variable 'SECRET_PERSISTENCE'
2024-08-13 17:36:25.140	
Unsetting empty environment variable 'METRIC_CLIENT'
2024-08-13 17:36:25.140	
Unsetting empty environment variable 'KUBERNETES_CLIENT_MAX_IDLE_CONNECTIONS'
2024-08-13 17:36:25.140	
Unsetting empty environment variable 'S3_PATH_STYLE_ACCESS'
2024-08-13 17:36:25.140	
Unsetting empty environment variable 'JOB_MAIN_CONTAINER_MEMORY_LIMIT'
2024-08-13 17:36:25.140	
Unsetting empty environment variable 'ACTIVITY_INITIAL_DELAY_BETWEEN_ATTEMPTS_SECONDS'
2024-08-13 17:36:26.595	
2024-08-13T15:36:26.588462434Z main INFO Loading mask data from '/seed/specs_secrets_mask.yaml
2024-08-13 17:36:27.260	

2024-08-13 17:36:27.260	
    ___    _      __          __
2024-08-13 17:36:27.260	
   /   |  (_)____/ /_  __  __/ /____
2024-08-13 17:36:27.260	
  / /| | / / ___/ __ \/ / / / __/ _ \
2024-08-13 17:36:27.260	
 / ___ |/ / /  / /_/ / /_/ / /_/  __/
2024-08-13 17:36:27.260	
/_/  |_/_/_/  /_.___/\__, /\__/\___/
2024-08-13 17:36:27.260	
                    /____/
2024-08-13 17:36:27.260	
        : airbyte-workload-launcher :
2024-08-13 17:36:27.260	

2024-08-13 17:36:28.893	
2024-08-13 15:36:28 INFO i.m.c.e.DefaultEnvironment(<init>):168 - Established active environments: [k8s, cloud, control-plane, oss]
2024-08-13 17:36:29.521	
2024-08-13 15:36:29 INFO i.a.f.ConfigFileClient(<init>):105 - path /flags does not exist, will return default flag values
2024-08-13 17:36:29.608	
2024-08-13 15:36:29 INFO i.a.c.t.TemporalUtils(getTemporalClientWhenConnected):147 - Waiting for temporal server...
2024-08-13 17:36:29.612	
2024-08-13 15:36:29 WARN i.a.c.t.TemporalUtils(getTemporalClientWhenConnected):158 - Waiting for namespace default to be initialized in temporal...
2024-08-13 17:36:32.208	
2024-08-13 15:36:32 WARN i.a.m.l.MetricClientFactory(initialize):72 - MetricClient was not recognized or not provided. Accepted values are `datadog` or `otel`. 
2024-08-13 17:36:32.279	
2024-08-13 15:36:32 INFO i.t.s.WorkflowServiceStubsImpl(<init>):86 - Created WorkflowServiceStubs for channel: ManagedChannelOrphanWrapper{delegate=ManagedChannelImpl{logId=1, target=airbyte-temporal:7233}}
2024-08-13 17:36:32.682	
2024-08-13 15:36:32 WARN i.a.c.t.TemporalUtils(getTemporalClientWhenConnected):168 - Ignoring exception while trying to request Temporal namespace:
2024-08-13 17:36:32.682	
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
2024-08-13 17:36:32.682	
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:268) ~[grpc-stub-1.64.0.jar:1.64.0]
2024-08-13 17:36:32.682	
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:249) ~[grpc-stub-1.64.0.jar:1.64.0]
2024-08-13 17:36:32.682	
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:167) ~[grpc-stub-1.64.0.jar:1.64.0]
2024-08-13 17:36:32.682	
	at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.getSystemInfo(WorkflowServiceGrpc.java:4299) ~[temporal-serviceclient-1.22.3.jar:?]
2024-08-13 17:36:32.682	
	at io.temporal.serviceclient.SystemInfoInterceptor.getServerCapabilitiesOrThrow(SystemInfoInterceptor.java:95) ~[temporal-serviceclient-1.22.3.jar:?]
2024-08-13 17:36:32.682	
	at io.temporal.serviceclient.SystemInfoInterceptor$1.start(SystemInfoInterceptor.java:81) ~[temporal-serviceclient-1.22.3.jar:?]
2024-08-13 17:36:32.682	
	at io.grpc.stub.ClientCalls.startCall(ClientCalls.java:335) ~[grpc-stub-1.64.0.jar:1.64.0]
2024-08-13 17:36:32.682	
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:311) ~[grpc-stub-1.64.0.jar:1.64.0]
2024-08-13 17:36:32.682	
	at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:224) ~[grpc-stub-1.64.0.jar:1.64.0]
2024-08-13 17:36:32.682	
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156) ~[grpc-stub-1.64.0.jar:1.64.0]
2024-08-13 17:36:32.682	
	at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.describeNamespace(WorkflowServiceGrpc.java:3822) ~[temporal-serviceclient-1.22.3.jar:?]
2024-08-13 17:36:32.682	
	at io.airbyte.commons.temporal.TemporalUtils.getNamespaceInfo(TemporalUtils.java:182) ~[io.airbyte-airbyte-commons-temporal-0.63.14.jar:?]
2024-08-13 17:36:32.682	
	at io.airbyte.commons.temporal.TemporalUtils.getTemporalClientWhenConnected(TemporalUtils.java:164) ~[io.airbyte-airbyte-commons-temporal-0.63.14.jar:?]
2024-08-13 17:36:32.682	
	at io.airbyte.commons.temporal.TemporalUtils.createTemporalService(TemporalUtils.java:75) ~[io.airbyte-airbyte-commons-temporal-0.63.14.jar:?]
2024-08-13 17:36:32.682	
	at io.airbyte.commons.temporal.TemporalUtils.createTemporalService(TemporalUtils.java:96) ~[io.airbyte-airbyte-commons-temporal-0.63.14.jar:?]
2024-08-13 17:36:32.682	
	at io.airbyte.commons.temporal.config.TemporalBeanFactory.temporalService(TemporalBeanFactory.java:32) ~[io.airbyte-airbyte-commons-temporal-0.63.14.jar:?]
2024-08-13 17:36:32.682	
	at io.airbyte.commons.temporal.config.$TemporalBeanFactory$TemporalService0$Definition.instantiate(Unknown Source) ~[io.airbyte-airbyte-commons-temporal-0.63.14.jar:?]
2024-08-13 17:36:32.682	
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2328) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.682	
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2298) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.682	
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2310) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.682	
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3120) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.684	
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.684	
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3022) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.684	
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2983) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.684	
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2749) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.684	
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1748) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.684	
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:89) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.684	
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2188) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.684	
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1350) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.airbyte.commons.temporal.config.$TemporalBeanFactory$WorkflowClient2$Definition.instantiate(Unknown Source) ~[io.airbyte-airbyte-commons-temporal-0.63.14.jar:?]
2024-08-13 17:36:32.685	
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2328) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2298) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2310) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3120) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3022) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2983) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2749) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1748) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:89) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2188) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1350) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.airbyte.workload.launcher.config.$TemporalBeanFactory$WorkloadStarterWorkerFactory2$Definition.instantiate(Unknown Source) ~[io.airbyte-airbyte-workload-launcher-0.63.14.jar:?]
2024-08-13 17:36:32.685	
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2328) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2298) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2310) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3120) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3022) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2983) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2749) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1748) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:89) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2188) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1350) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.airbyte.workload.launcher.temporal.$TemporalWorkerController$Definition.instantiate(Unknown Source) ~[io.airbyte-airbyte-workload-launcher-0.63.14.jar:?]
2024-08-13 17:36:32.685	
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2328) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2298) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2310) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3120) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3022) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2983) ~[micronaut-inject-4.5.4.jar:4.5.4]



2024-08-13 17:36:32.685	
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2749) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1748) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:842) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at io.micronaut.scheduling.processor.ScheduledMethodProcessor.lambda$scheduleTask$2(ScheduledMethodProcessor.java:152) ~[micronaut-context-4.5.4.jar:4.5.4]
2024-08-13 17:36:32.685	
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
2024-08-13 17:36:32.685	
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
2024-08-13 17:36:32.685	
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
2024-08-13 17:36:32.685	
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
2024-08-13 17:36:32.685	
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
2024-08-13 17:36:32.685	
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
2024-08-13 17:36:32.685	
Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: airbyte-temporal/{redacted}:7233
2024-08-13 17:36:32.685	
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
2024-08-13 17:36:32.685	
	at io.grpc.netty.shaded.io.netty.channel.unix.Errors.newConnectException0(Errors.java:166) ~[grpc-netty-shaded-1.64.0.jar:1.64.0]
2024-08-13 17:36:32.685	
	at io.grpc.netty.shaded.io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:131) ~[grpc-netty-shaded-1.64.0.jar:1.64.0]
2024-08-13 17:36:32.685	
	at io.grpc.netty.shaded.io.netty.channel.unix.Socket.finishConnect(Socket.java:359) ~[grpc-netty-shaded-1.64.0.jar:1.64.0]
2024-08-13 17:36:32.685	
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710) ~[grpc-netty-shaded-1.64.0.jar:1.64.0]
2024-08-13 17:36:32.685	
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687) ~[grpc-netty-shaded-1.64.0.jar:1.64.0]
2024-08-13 17:36:32.685	
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567) ~[grpc-netty-shaded-1.64.0.jar:1.64.0]
2024-08-13 17:36:32.685	
	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[grpc-netty-shaded-1.64.0.jar:1.64.0]
2024-08-13 17:36:32.685	
	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[grpc-netty-shaded-1.64.0.jar:1.64.0]
2024-08-13 17:36:32.685	
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[grpc-netty-shaded-1.64.0.jar:1.64.0]
2024-08-13 17:36:32.685	
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[grpc-netty-shaded-1.64.0.jar:1.64.0]
2024-08-13 17:36:32.685	
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[grpc-netty-shaded-1.64.0.jar:1.64.0]
2024-08-13 17:36:32.685	
	... 1 more
```

**Comment by marcosmarxm** [comment]
Thanks for the contribution @hanslemm lets wait for the review and resolution of your pull request.

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 180 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.
