### ISSUE TITLE
[source GCS] can't setup streams with header

### ISSUE THREAD

**Issue by m-ronchi** [airbytehq/airbyte#44031]
### Connector Name

source-gcs

### Connector Version

0.4.15

### What step the error happened?

Configuring a new connector

### Relevant information

when I try to add a stream to GCS, if `CSV Header Definition` is anything else than "User Provided", the configuration check fails with an error

### Relevant log output

```shell
['Traceback (most recent call last):\n File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/file_based/availability_strategy/default_file_based_availability_strategy.py", line 95, in _check_parse_record\n record = next(iter(parser.parse_records(stream.config, file, self.stream_reader, logger, discovered_schema=None)))\n File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/file_based/file_types/csv_parser.py", line 206, in parse_records\n for row in data_generator:\n File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/file_based/file_types/csv_parser.py", line 55, in read_data\n headers = self._get_headers(fp, config_format, dialect_name)\n File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/file_based/file_types/csv_parser.py", line 110, in _get_headers\n fp.seek(0)\nio.UnsupportedOperation: underlying stream is not seekable\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/file_based/availability_strategy/default_file_based_availability_strategy.py", line 64, in check_availability_and_parsability\n self._check_parse_record(stream, file, logger)\n File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/file_based/availability_strategy/default_file_based_availability_strategy.py", line 102, in _check_parse_record\n raise CheckAvailabilityError(FileBasedSourceError.ERROR_READING_FILE, stream=stream.name, file=file.uri) from exc\nairbyte_cdk.sources.file_based.exceptions.CheckAvailabilityError: Error opening file. Please check the credentials provided in the config and verify that they provide permission to read files. Contact Support if you need assistance.\nstream=REDACTED file=https://storage.googleapis.com/REDACTED\n']
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by darynaishchenko** [comment]
@m-ronchi, Hi, I'm currently working on this issue. I was trying to reproduce it, on my side everything works as expected when stream has headers.
Could you please share a link to your connection, if you're using airbyte cloud? So I could investigate it more. Thanks!

**Comment by m-ronchi** [comment]
Hi,
unfortunately I am using the self-hosted version.
I tried using a local install (0.63.19 with abctl) and both versions 0.6.1 and 0.6.5 of the connectors, and the result is the same.

the streams I am syncing are ratings and reviews from the google play store (google owns the bucket and we have read permissions):
settings are the default ones, except:
- format: csv
- encoding: utf16
- glob: "stats/ratings/*_country.csv"

**Comment by darynaishchenko** [comment]
@m-ronchi thanks for the response.
Is it possible to share an example of csv file you want to sync? You can delete sensitive info, I just want to see a structure of the file.
Is error message the same as above or something was changed?

**Comment by m-ronchi** [comment]
Hi,
here a couple of samples: (I gzipped the ratings locally, both streams are uncompressed on drive)
[ratings_com.redacted_202408_country.csv.gz](https://github.com/user-attachments/files/16850378/ratings_com.redacted_202408_country.csv.gz)
[reviews_com.Redacted.Multiplayer_202409.csv](https://github.com/user-attachments/files/16850382/reviews_com.Redacted.Multiplayer_202409.csv)

there are 2 streams I setup: 
- ratings: contains daily aggregate reports of star ratings, one file per game, per month (since 2015, multiple games, 25k files total) in a flat folder `stats/ratings/`
- reviews: contains the raw reviews of users, also one file per game-month, in a flat folder `reviews`

the ratings folder contains multipe types of aggregations, identified by the suffix (i.e. _app_version.csv, _carrier.csv, _country.csv, _device.csv, _language.csv, _os_version.csv, _overview.csv) we are only interested in the _country one so we filter it with the glob
reviews are raw and we only filter per game (e.g. glob is `reviews/reviews_com.xxx.yyy_*`)

**Comment by darynaishchenko** [comment]
@m-ronchi My investigation results:

- I have tried to read from [ratings_com.redacted_202408_country.csv.gz](https://github.com/user-attachments/files/16850378/ratings_com.redacted_202408_country.csv.gz) and was able to set up and read data.
- Initial error from your log message `UnsupportedOperation: underlying stream is not seekable`: the source tries to get headers(this step is successful) and then calls `file.seek()` -> this action returns an error above. It could be 2 reasons why file is not seekable: response header value for `Content-Length` < 0 or this header does not exist or `Accept-Ranges` header value is not `bytes`.

It works with "User Provided" because for this headers type the source doesn't do actions above.

I see 2 way how we can investigate the behavior further here:
1. You can create a trial account in airbyte cloud and set up the same connection as you have on a self-hosted version. Then I will continue working on it with your connection on cloud.
2. You can validate files in your glob and find with file causes the error by manually reviewing file or setting up streams per each file to see what files are can be set up and which are not.

I think that some files in your folder are broken somehow, but it's hard to identify an actual reason.

**Comment by m-ronchi** [comment]
Hi,
I tried (2) locally with a bunch of different files (by setting the glob to the exact file), and all of them failed.
I also downloaded one of them with my browser, and I see `Content-Length` but not `Accept-Ranges` in the dev tools

for (1) I need permission from above, as I don't know if and which of the data is considered sensitive (both internally and by GDPR)

meanwhile, if you own any android app on google play store, what I am trying to sync are the "Download Reports > Reviews" and the "Download Reports > Statistics > Ratings" available in the google play console (e.g. https://play.google.com/console/u/0/developers/<REDACTED>/download-reports/statistics?appId=<REDACTED>)
