### ISSUE TITLE
[destination-weaviate] "No External Embedding"

### ISSUE THREAD

**Issue by hvuddagi** [airbytehq/airbyte#44167]
### Connector Name

destination-weaviate

### Connector Version

0.2.31

### What step the error happened?

Configuring a new connector

### Relevant information

I am trying an connection between Mongo as Source and Destination as Weaviate.
When configuring Weaviate as destination and selecting "No External Embedding" under "Embedding" section, the test is not passing with below error.
I dont want to go through any embedding as I created the collection with a inhouse vectorizer in the weaviate itself.

### Relevant log output

```shell
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 11, in <module>
    DestinationWeaviate().run(sys.argv[1:])
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/destinations/destination.py", line 119, in run
    for message in output_messages:
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/destinations/destination.py", line 109, in run_cmd
    yield self._run_check(config=config)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/destinations/destination.py", line 32, in _run_check
    check_result = self.check(logger, config)
  File "/airbyte/integration_code/destination_weaviate/destination.py", line 49, in check
    self._init_indexer(parsed_config)
  File "/airbyte/integration_code/destination_weaviate/destination.py", line 29, in _init_indexer
    else NoEmbedder(config.embedding)
TypeError: Can't instantiate abstract class NoEmbedder with abstract method embed_documents
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 180 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
