### ISSUE TITLE
PG Source Check Connection does not complete

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#444]
## Expected Behavior
* When given invalid credentials the check connection endpoint should complete and say that the creds are invalid.

## Current Behavior
* The check connection call times out.

## Error message
```
airbyte-server | 2020-09-24 05:12:29 ERROR i.a.s.h.WebBackendSourceImplementationHandler(webBackendCreateSourceImplementationAndCheck):71 - {} - Error while checking connection
airbyte-server | java.lang.RuntimeException: Check connection job did not complete.
airbyte-server | 	at io.airbyte.server.handlers.SchedulerHandler.waitUntilJobIsTerminalOrTimeout(SchedulerHandler.java:180) ~[airbyte-server-0.1.0-alpha.jar:?]
...
airbyte-server | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server | 	at java.lang.Thread.run(Thread.java:832) [?:?]
airbyte-server | 2020-09-24 05:12:29 DEBUG i.a.s.e.KnownExceptionMapper(toResponse):42 - {} - Known exception
airbyte-server | io.airbyte.server.errors.KnownException: Unable to connect to destination
airbyte-server | 	at io.airbyte.server.handlers.WebBackendSourceImplementationHandler.webBackendCreateSourceImplementationAndCheck(WebBackendSourceImplementationHandler.java:75) ~[airbyte-server-0.1.0-alpha.jar:?]
airbyte-server | 	at io.airbyte.server.apis.ConfigurationApi.lambda$webBackendCreateSourceImplementation$4(ConfigurationApi.java:145) ~[airbyte-server-0.1.0-alpha.jar:?]
```

**Comment by cgardens** [comment]
@jrhizor mentioned to me that this problem does _not_ exist for postgres containers he runs locally.

**Comment by cgardens** [comment]
haven't seen this in ages. seems to have been resolved.
