### ISSUE TITLE
Error will upgrading Airbyte version with existing connection in an air gap environment

### ISSUE THREAD

**Issue by tamilselvan-stratforge** [airbytehq/airbyte#44441]
### Platform Version

0.63.15

### What step the error happened?

Upgrading the Platform or Helm Chart

### Relevant information

I have initially deployed Airbyte version 0.58.0  in an **air gap environment** with an source image mounted on the path airbyte/source-postgres:3.3.29.
and similarly for the destination clickhouse on the respective path.

I have created a connection between the postgres and clickhouse and everything is fine.

Later I tried upgrading the Airbyte version from V0.58.0 to V0.63.15. But the bootloader existed with code 255 with the below errors

1. Failed to fetch remote platform compatibility file.
2. Caused by: java.net.UnknownHostException: connectors.airbyte.com - Trying to connect to airbyte
3. Failed to fetch connector registry entry for airbyte/source-postgres:3.3.29

Expected Result: Airbyte should upgrade to the newer version seamlessly without internet connection.
What else need to be included in the volume for upgrading to the latest version, tried to include [oss_registry.json](https://connectors.airbyte.com/files/registries/v0/oss_registry.json) to the volume src/main/resources/seed/local_oss_registry.json
It upgrading but still found issue with the above errors~!

Is there a way to do upgrade Airbyte in an airgap environment!

### Relevant log output

```shell
2024-08-19 08:10:04 ERROR i.a.c.i.AirbyteCompatibleConnectorVersionsProvider(getCompatibleConnectorsMatrix):60 - Failed to fetch remote platform compatibility file.
2024-08-19 13:40:04 dev.failsafe.FailsafeException: java.net.UnknownHostException: connectors.airbyte.com
2024-08-19 13:40:04     at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:196) ~[failsafe-3.3.2.jar:3.3.2]
2024-08-19 13:40:04     at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376) ~[failsafe-3.3.2.jar:3.3.2]
2024-08-19 13:40:04     at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112) ~[failsafe-3.3.2.jar:3.3.2]
2024-08-19 13:40:04     at io.airbyte.config.init.AirbyteCompatibleConnectorVersionsProvider.getCompatibleConnectorsMatrix(AirbyteCompatibleConnectorVersionsProvider.kt:47) ~[io.airbyte.airbyte-config-init-0.63.15.jar:?]
2024-08-19 13:40:04     at io.airbyte.config.init.$AirbyteCompatibleConnectorVersionsProvider$Definition$Intercepted.$$access$$getCompatibleConnectorsMatrix(Unknown Source) ~[io.airbyte.airbyte-config-init-0.63.15.jar:?]
2024-08-19 13:40:04     at io.airbyte.config.init.$AirbyteCompatibleConnectorVersionsProvider$Definition$Exec.dispatch(Unknown Source) ~[io.airbyte.airbyte-config-init-0.63.15.jar:?]
2024-08-19 13:40:04     at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:456) ~[micronaut-inject-4.5.4.jar:4.5.4]
2024-08-19 13:40:04     at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:129) ~[micronaut-aop-4.5.4.jar:4.5.4]
2024-08-19 13:40:04     at io.micronaut.cache.interceptor.CacheInterceptor.doContextProceed(CacheInterceptor.java:753) ~[micronaut-cache-core-4.3.0.jar:4.3.0]
2024-08-19 13:40:04     at io.micronaut.cache.interceptor.CacheInterceptor.doProceed(CacheInterceptor.java:757) ~[micronaut-cache-core-4.3.0.jar:4.3.0]
2024-08-19 13:40:04     at io.micronaut.cache.interceptor.CacheInterceptor.interceptSync(CacheInterceptor.java:435) ~[micronaut-cache-core-4.3.0.jar:4.3.0]
2024-08-19 13:40:04     at io.micronaut.cache.interceptor.CacheInterceptor.intercept(CacheInterceptor.java:161) ~[micronaut-cache-core-4.3.0.jar:4.3.0]
2024-08-19 13:40:04     at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:138) ~[micronaut-aop-4.5.4.jar:4.5.4]
2024-08-19 13:40:04     at io.airbyte.config.init.$AirbyteCompatibleConnectorVersionsProvider$Definition$Intercepted.getCompatibleConnectorsMatrix(Unknown Source) ~[io.airbyte.airbyte-config-init-0.63.15.jar:?]
2024-08-19 13:40:04     at io.airbyte.config.init.RealAirbyteCompatibleConnectorsValidator.validate(AirbyteCompatibleConnectorsValidator.kt:59) ~[io.airbyte.airbyte-config-init-0.63.15.jar:?]
2024-08-19 13:40:04     at io.airbyte.config.init.ApplyDefinitionsHelper$filterOutIncompatibleSourceDefsWithCurrentAirbyteVersion$1.invoke(ApplyDefinitionsHelper.kt:333) ~[io.airbyte.airbyte-config-init-0.63.15.jar:?]
2024-08-19 13:40:04     at io.airbyte.config.init.ApplyDefinitionsHelper$filterOutIncompatibleSourceDefsWithCurrentAirbyteVersion$1.invoke(ApplyDefinitionsHelper.kt:332) ~[io.airbyte.airbyte-config-init-0.63.15.jar:?]
2024-08-19 13:40:04     at io.airbyte.config.init.ApplyDefinitionsHelper.filterOutIncompatibleSourceDefsWithCurrentAirbyteVersion$lambda$4(ApplyDefinitionsHelper.kt:332) ~[io.airbyte.airbyte-config-init-0.63.15.jar:?]
2024-08-19 13:40:04     at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) [?:?]
2024-08-19 13:40:04     at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722) [?:?]
2024-08-19 13:40:04     at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) [?:?]
2024-08-19 13:40:04     at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) [?:?]
2024-08-19 13:40:04     at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) [?:?]
2024-08-19 13:40:04     at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) [?:?]
2024-08-19 13:40:04     at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) [?:?]
2024-08-19 13:40:04     at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) [?:?]
2024-08-19 13:40:04     at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) [?:?]
2024-08-19 13:40:04     at io.airbyte.config.init.ApplyDefinitionsHelper.filterOutIncompatibleSourceDefsWithCurrentAirbyteVersion(ApplyDefinitionsHelper.kt:339) [io.airbyte.airbyte-config-init-0.63.15.jar:?]
2024-08-19 13:40:04     at io.airbyte.config.init.ApplyDefinitionsHelper.apply(ApplyDefinitionsHelper.kt:89) [io.airbyte.airbyte-config-init-0.63.15.jar:?]
2024-08-19 13:40:04     at io.airbyte.bootloader.DefaultPostLoadExecutor.execute(DefaultPostLoadExecutor.java:45) [io.airbyte-airbyte-bootloader-0.63.15.jar:?]
2024-08-19 13:40:04     at io.airbyte.bootloader.Bootloader.load(Bootloader.java:134) [io.airbyte-airbyte-bootloader-0.63.15.jar:?]
2024-08-19 13:40:04     at io.airbyte.bootloader.Application.main(Application.java:22) [io.airbyte-airbyte-bootloader-0.63.15.jar:?]
2024-08-19 13:40:04 Caused by: java.net.UnknownHostException: connectors.airbyte.com
2024-08-19 13:40:04     at java.base/java.net.InetAddress$CachedLookup.get(InetAddress.java:988) ~[?:?]
2024-08-19 13:40:04     at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1818) ~[?:?]
2024-08-19 13:40:04     at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1688) ~[?:?]
2024-08-19 13:40:04     at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:169) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:131) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:73) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154) ~[okhttp-4.12.0.jar:?]
2024-08-19 13:40:04     at io.airbyte.config.init.AirbyteCompatibleConnectorVersionsProvider$getCompatibleConnectorsMatrix$responseSupplier$1.invoke(AirbyteCompatibleConnectorVersionsProvider.kt:46) ~[io.airbyte.airbyte-config-init-0.63.15.jar:?]
2024-08-19 13:40:04     at io.airbyte.config.init.AirbyteCompatibleConnectorVersionsProvider$getCompatibleConnectorsMatrix$responseSupplier$1.invoke(AirbyteCompatibleConnectorVersionsProvider.kt:46) ~[io.airbyte.airbyte-config-init-0.63.15.jar:?]
2024-08-19 13:40:04     at io.airbyte.config.init.AirbyteCompatibleConnectorVersionsProvider.getCompatibleConnectorsMatrix$lambda$0(AirbyteCompatibleConnectorVersionsProvider.kt:47) ~[io.airbyte.airbyte-config-init-0.63.15.jar:?]
2024-08-19 13:40:04     at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243) ~[failsafe-3.3.2.jar:3.3.2]
2024-08-19 13:40:04     at dev.failsafe.Functions.lambda$get$0(Functions.java:46) ~[failsafe-3.3.2.jar:3.3.2]
2024-08-19 13:40:04     at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74) ~[failsafe-3.3.2.jar:3.3.2]
2024-08-19 13:40:04     at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187) ~[failsafe-3.3.2.jar:3.3.2]
2024-08-19 13:40:04     ... 31 more
2024-08-19 13:40:05 2024-08-19 08:10:05 WARN i.m.s.r.u.Loggers$Slf4JLogger(warn):299 - [8a8a5904, L:/127.0.0.1:38285 - R:localhost/127.0.0.1:8125] An exception has been observed post termination, use DEBUG level to see the full stack: java.net.PortUnreachableException: recvAddress(..) failed: Connection refused
2024-08-19 13:40:05 2024-08-19 08:10:05 WARN i.m.s.r.u.Loggers$Slf4JLogger(warn):299 - [8a8a5904, L:/127.0.0.1:38285 - R:localhost/127.0.0.1:8125] An exception has been observed post termination, use DEBUG level to see the full stack: java.net.PortUnreachableException: recvAddress(..) failed: Connection refused
2024-08-19 13:40:05 2024-08-19 08:10:05 WARN i.m.s.r.u.Loggers$Slf4JLogger(warn):299 - [8a8a5904, L:/127.0.0.1:38285 - R:localhost/127.0.0.1:8125] An exception has been observed post termination, use DEBUG level to see the full stack: java.net.PortUnreachableException: recvAddress(..) failed: Connection refused
2024-08-19 13:40:05 2024-08-19 08:10:05 WARN i.m.s.r.u.Loggers$Slf4JLogger(warn):299 - [8a8a5904, L:/127.0.0.1:38285 - R:localhost/127.0.0.1:8125] An exception has been observed post termination, use DEBUG level to see the full stack: java.net.PortUnreachableException: recvAddress(..) failed: Connection refused
2024-08-19 13:40:05 2024-08-19 08:10:05 WARN i.m.s.r.u.Loggers$Slf4JLogger(warn):299 - [8a8a5904, L:/127.0.0.1:38285 - R:localhost/127.0.0.1:8125] An exception has been observed post termination, use DEBUG level to see the full stack: java.net.PortUnreachableException: recvAddress(..) failed: Connection refused
2024-08-19 13:40:05 2024-08-19 08:10:05 INFO i.a.c.i.ApplyDefinitionsHelper(applySourceDefinition):165 - Refreshing default version metadata for connector airbyte/source-postgres:3.3.29
2024-08-19 13:40:05 2024-08-19 08:10:05 WARN i.m.s.r.u.Loggers$Slf4JLogger(warn):299 - [8a8a5904, L:/127.0.0.1:38285 - R:localhost/127.0.0.1:8125] An exception has been observed post termination, use DEBUG level to see the full stack: java.net.PortUnreachableException: recvAddress(..) failed: Connection refused
2024-08-19 13:40:05 2024-08-19 08:10:05 ERROR i.a.b.Application(main):25 - Unable to bootstrap Airbyte environment.
2024-08-19 13:40:05 java.lang.RuntimeException: Failed to fetch connector registry entry for airbyte/source-postgres:3.3.29
2024-08-19 13:40:05     at io.airbyte.config.specs.RemoteDefinitionsProvider.getConnectorRegistryEntryJson(RemoteDefinitionsProvider.java:224) ~[io.airbyte.airbyte-config-specs-0.63.15.jar:?]
2024-08-19 13:40:05     at io.airbyte.config.specs.RemoteDefinitionsProvider.getSourceDefinitionByVersion(RemoteDefinitionsProvider.java:114) ~[io.airbyte.airbyte-config-specs-0.63.15.jar:?]
2024-08-19 13:40:05     at io.airbyte.config.persistence.ActorDefinitionVersionResolver.fetchRemoteActorDefinitionVersion(ActorDefinitionVersionResolver.java:79) ~[io.airbyte.airbyte-config-config-persistence-0.63.15.jar:?]
2024-08-19 13:40:05     at io.airbyte.config.init.ApplyDefinitionsHelper.applySourceDefinition(ApplyDefinitionsHelper.kt:168) ~[io.airbyte.airbyte-config-init-0.63.15.jar:?]
2024-08-19 13:40:05     at io.airbyte.config.init.ApplyDefinitionsHelper.apply(ApplyDefinitionsHelper.kt:99) ~[io.airbyte.airbyte-config-init-0.63.15.jar:?]
2024-08-19 13:40:05     at io.airbyte.bootloader.DefaultPostLoadExecutor.execute(DefaultPostLoadExecutor.java:45) ~[io.airbyte-airbyte-bootloader-0.63.15.jar:?]
2024-08-19 13:40:05     at io.airbyte.bootloader.Bootloader.load(Bootloader.java:134) ~[io.airbyte-airbyte-bootloader-0.63.15.jar:?]
2024-08-19 13:40:05     at io.airbyte.bootloader.Application.main(Application.java:22) [io.airbyte-airbyte-bootloader-0.63.15.jar:?]
```

**Comment by jdpgrailsdev** [comment]
@tamilselvan-stratforge  This error does not actually cause any issues.  If the platform fails to retrieve the compatibility file, it allows everything to run without doing any check.  The log message was erroneously logged as an error, hence the stack trace.  It has since been lowered in priority and should no longer produce a loud message in more recent releases ([v0.64.4](https://github.com/airbytehq/airbyte-platform/releases/tag/v0.64.4) and beyond).

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
