### ISSUE TITLE
[platform/0.63.15] - connection hangs on node maintenance or swap

### ISSUE THREAD

**Issue by LucasSegersFabro** [airbytehq/airbyte#44474]
### Helm Chart Version

0.429.0

### What step the error happened?

During the Sync

## Context/infra
* Have 3 similar connections that need to be kept in sync most of the time (running every minute)
* source: salesforce
* destination: bigquery
* running on GKE (with GCS logging)
* platform version: 0.63.15
* all pods that connect to the DB use the sidecar pattern (with cloud-sql-proxy). It also happened when I connected through a single pod
* Salesforce connector version: 2.5.25
* Bigquery destination version: 2.8.6

--- 

## The issue
When a GKE node in the pool is recycled (due to maintenance or failure) and a sync is running, it causes the sync job to hang indefinitely until manually canceled

On all occurrences (5 times since the upgrade to the worker model), the last log it prints before hanging forever is:
```sh
2024-08-20 19:12:23 platform > Creating workload badd9a5e-26ce-4fd3-b3b3-5a7476583d86_410807_0_sync
```

1. doesn't seem to be resource starvation issue, since I can't see any evictions/failed scheduling
2. the cluster resources seem fine
3. it **always** coincides with a node restart (can see through the node's age)

--- 

## Volume
* during the day each sync takes at most 2 minutes to keep up
* 200-500 records per sync
* can happen when there are only those 3 connections running, or a bit more (sometimes up to 5-6 connections run at the same time)

doesn't seem much

--- 

## Expected result
the job/workload should be able to "heal" or "auto-cancel"

--- 

## Observations
* the only way I know a job is "stuck" is when it takes much more time to run and, when I open the logs, I see it just doesn't log anything for a log time (always the same log entry: creating workload)
* would help to mitigate if I knew a job is running late (maybe marking the job as "late" based on the average time of the last N syncs) via some webhook
* or if I could maybe specify "time windows + expected time" to have a "auto restart" policy

Will paste some logs that I already sent on slack on the "Relevant log output", but the key here seems to be this last log line it always logs before hanging

Feel free to ask for more info. Maybe set logging level to debug if it isn't enough

### Relevant log output

```shell
2024-08-17 05:49:09 replication-orchestrator > Error while trying to heartbeat, re-trying
java.net.SocketTimeoutException: Connect timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546) ~[?:?]
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592) ~[?:?]
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
        at java.base/java.net.Socket.connect(Socket.java:751) ~[?:?]
        at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128) ~[okhttp-4.12.0.jar:?]
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295) ~[okhttp-4.12.0.jar:?]
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207) ~[okhttp-4.12.0.jar:?]
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226) ~[okhttp-4.12.0.jar:?]
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106) ~[okhttp-4.12.0.jar:?]
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74) ~[okhttp-4.12.0.jar:?]
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255) ~[okhttp-4.12.0.jar:?]
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) ~[okhttp-4.12.0.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[okhttp-4.12.0.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.12.0.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.12.0.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
        at io.airbyte.api.client.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:34) ~[io.airbyte.airbyte-api-commons-0.63.15.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
        at io.airbyte.api.client.auth.AirbyteAuthHeaderInterceptor.intercept(AirbyteAuthHeaderInterceptor.kt:28) ~[io.airbyte.airbyte-api-commons-0.63.15.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
        at io.airbyte.workload.api.client.auth.WorkloadApiAuthenticationInterceptor.intercept(WorkloadApiAuthenticationInterceptor.kt:36) ~[io.airbyte.airbyte-api-workload-api-0.63.15.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[okhttp-4.12.0.jar:?]
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154) ~[okhttp-4.12.0.jar:?]
        at io.airbyte.workload.api.client.generated.WorkloadApi.workloadHeartbeatWithHttpInfo(WorkloadApi.kt:2748) ~[io.airbyte.airbyte-api-workload-api-0.63.15.jar:?]
        at io.airbyte.workload.api.client.generated.WorkloadApi.workloadHeartbeat(WorkloadApi.kt:429) ~[io.airbyte.airbyte-api-workload-api-0.63.15.jar:?]
        at io.airbyte.workers.general.ReplicationWorkerHelper.getWorkloadStatusHeartbeat$lambda$1(ReplicationWorkerHelper.kt:153) ~[io.airbyte-airbyte-commons-worker-0.63.15.jar:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
        Suppressed: java.io.IOException: unexpected end of stream on http://airbyte-workload-api-server-svc:8007/...
                at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:210) ~[okhttp-4.12.0.jar:?]
                at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:110) ~[okhttp-4.12.0.jar:?]
                at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:93) ~[okhttp-4.12.0.jar:?]
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
                at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34) ~[okhttp-4.12.0.jar:?]
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
                at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[okhttp-4.12.0.jar:?]
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
                at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.12.0.jar:?]
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
                at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.12.0.jar:?]
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
                at io.airbyte.api.client.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:34) ~[io.airbyte.airbyte-api-commons-0.63.15.jar:?]
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
                at io.airbyte.api.client.auth.AirbyteAuthHeaderInterceptor.intercept(AirbyteAuthHeaderInterceptor.kt:28) ~[io.airbyte.airbyte-api-commons-0.63.15.jar:?]
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
                at io.airbyte.workload.api.client.auth.WorkloadApiAuthenticationInterceptor.intercept(WorkloadApiAuthenticationInterceptor.kt:36) ~[io.airbyte.airbyte-api-workload-api-0.63.15.jar:?]
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
                at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[okhttp-4.12.0.jar:?]
                at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154) ~[okhttp-4.12.0.jar:?]
                at io.airbyte.workload.api.client.generated.WorkloadApi.workloadHeartbeatWithHttpInfo(WorkloadApi.kt:2748) ~[io.airbyte.airbyte-api-workload-api-0.63.15.jar:?]
                at io.airbyte.workload.api.client.generated.WorkloadApi.workloadHeartbeat(WorkloadApi.kt:429) ~[io.airbyte.airbyte-api-workload-api-0.63.15.jar:?]
                at io.airbyte.workers.general.ReplicationWorkerHelper.getWorkloadStatusHeartbeat$lambda$1(ReplicationWorkerHelper.kt:153) ~[io.airbyte-airbyte-commons-worker-0.63.15.jar:?]
                at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
                at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
        Caused by: java.io.EOFException: \n not found: limit=0 content=…
                at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:335) ~[okio-jvm-3.6.0.jar:?]
                at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29) ~[okhttp-4.12.0.jar:?]
                at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:180) ~[okhttp-4.12.0.jar:?]

<job sync summary is printed>

2024-08-17 05:49:09 replication-orchestrator > failures: [ ]
2024-08-17 05:49:09 replication-orchestrator > 
2024-08-17 05:49:09 replication-orchestrator > ----- END REPLICATION -----
2024-08-17 05:49:09 replication-orchestrator > 
2024-08-17 05:49:40 ERROR i.a.c.Application(run):82 - Killing orchestrator because of an Exception
java.net.SocketTimeoutException: Connect timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546) ~[?:?]
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592) ~[?:?]
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
        at java.base/java.net.Socket.connect(Socket.java:751) ~[?:?]
        at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128) ~[okhttp-4.12.0.jar:?]
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295) ~[okhttp-4.12.0.jar:?]
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207) ~[okhttp-4.12.0.jar:?]
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226) ~[okhttp-4.12.0.jar:?]
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106) ~[okhttp-4.12.0.jar:?]
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74) ~[okhttp-4.12.0.jar:?]
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255) ~[okhttp-4.12.0.jar:?]
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) ~[okhttp-4.12.0.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[okhttp-4.12.0.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.12.0.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.12.0.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
        at io.airbyte.api.client.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:34) ~[io.airbyte.airbyte-api-commons-0.63.15.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
        at io.airbyte.api.client.auth.AirbyteAuthHeaderInterceptor.intercept(AirbyteAuthHeaderInterceptor.kt:28) ~[io.airbyte.airbyte-api-commons-0.63.15.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
        at io.airbyte.workload.api.client.auth.WorkloadApiAuthenticationInterceptor.intercept(WorkloadApiAuthenticationInterceptor.kt:36) ~[io.airbyte.airbyte-api-workload-api-0.63.15.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar:?]
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[okhttp-4.12.0.jar:?]
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154) ~[okhttp-4.12.0.jar:?]
        at io.airbyte.workload.api.client.generated.WorkloadApi.workloadSuccessWithHttpInfo(WorkloadApi.kt:4869) ~[io.airbyte.airbyte-api-workload-api-0.63.15.jar:?]
        at io.airbyte.workload.api.client.generated.WorkloadApi.workloadSuccess(WorkloadApi.kt:927) ~[io.airbyte.airbyte-api-workload-api-0.63.15.jar:?]
        at io.airbyte.container_orchestrator.orchestrator.ReplicationJobOrchestrator.succeedWorkload(ReplicationJobOrchestrator.java:174) ~[io.airbyte-airbyte-container-orchestrator-0.63.15.jar:?]
        at io.airbyte.container_orchestrator.orchestrator.ReplicationJobOrchestrator.updateStatusInWorkloadApi(ReplicationJobOrchestrator.java:154) ~[io.airbyte-airbyte-container-orchestrator-0.63.15.jar:?]
        at io.airbyte.container_orchestrator.orchestrator.ReplicationJobOrchestrator.runJob(ReplicationJobOrchestrator.java:113) ~[io.airbyte-airbyte-container-orchestrator-0.63.15.jar:?]
        at io.airbyte.container_orchestrator.Application.run(Application.java:79) [io.airbyte-airbyte-container-orchestrator-0.63.15.jar:?]
        at io.airbyte.container_orchestrator.Application.main(Application.java:39) [io.airbyte-airbyte-container-orchestrator-0.63.15.jar:?]
2024-08-17 05:49:40 INFO i.a.a.SegmentAnalyticsClient(close):233 - Closing Segment analytics client...
2024-08-17 05:49:40 INFO i.a.a.BlockingShutdownAnalyticsPlugin(waitForFlush):289 - Waiting for Segment analytic client to flush enqueued messages...
2024-08-17 05:49:40 INFO i.a.a.BlockingShutdownAnalyticsPlugin(waitForFlush):301 - Segment analytic client flush complete.
2024-08-17 05:49:40 INFO i.a.a.SegmentAnalyticsClient(close):237 - Segment analytics client closed.  No new events will be accepted.
2024-08-17 05:50:19 platform > Cloud storage job log path: /workspace/401366/0/logs.log
2024-08-17 05:50:19 platform > Executing worker wrapper. Airbyte version: 0.63.15
2024-08-17 05:50:19 platform > Creating workload badd9a5e-26ce-4fd3-b3b3-5a7476583d86_401366_0_sync
```

**Comment by LucasSegersFabro** [comment]
Can confirm that the problem is an AUTO_REPAIR gke operation.  
Will try to mitigate the issue by specifying limits and resources better to prevent node repairing

But it would still be nice if syncs could "recover" from node failures

<img width="1136" alt="image" src="https://github.com/user-attachments/assets/63943b3b-0ff5-4b9e-a0da-bfc383f22c0a">

**Comment by davinchia** [comment]
How long are you waiting to intervene? 

Our jobs heartbeat and kill themselves after some time. I'm wondering if you are seeing this because the termination periods are too long for your frequency.

To give context, we run in GKE as well, and don't notice this happening.

**Comment by LucasSegersFabro** [comment]
We usually intervene when we notice it's stuck

<img width="827" alt="image" src="https://github.com/user-attachments/assets/e5eca51d-5977-494a-9deb-d681414f377c">

* 2024-08-20T19:12:23Z -> intervened after ~45minutes
* 2024-08-20T03:54:08Z -> intervened after ~8:45 hours
* 2024-08-17T05:49:00Z -> intervened after ~9:00 hours

**Comment by LucasSegersFabro** [comment]
So, it happened again on 2024-08-23

This time:
* no GKE events
* no node repairing

Sync just got stuck until canceled  
Now I'm puzzled

```sh
2024-08-23 19:45:21 destination > INFO main i.a.c.i.d.a.AsyncStreamConsumer(close):195 class io.airbyte.cdk.integrations.destination.async.AsyncStreamConsumer closed
2024-08-23 19:45:21 destination > INFO main i.a.c.i.b.IntegrationRunner(runInternal):269 Completed integration: io.airbyte.integrations.destination.bigquery.BigQueryDestination
2024-08-23 19:45:21 destination > INFO main i.a.i.d.b.BigQueryDestinationKt(main):565 Completed Destination : class io.airbyte.integrations.destination.bigquery.BigQueryDestination
2024-08-23 19:45:22 replication-orchestrator > (pod: integration / destination-bigquery-write-417085-0-glbdg) - Closed all resources for pod
2024-08-23 19:45:22 replication-orchestrator > readFromDestination: done. (writeToDestFailed:false, dest.isFinished:true)
2024-08-23 19:45:22 replication-orchestrator > thread status... timeout thread: false , replication thread: true
2024-08-23 19:45:22 replication-orchestrator > Closing StateCheckSumCountEventHandler
2024-08-23 19:45:22 replication-orchestrator > No checksum errors were reported in the entire sync.
2024-08-23 19:45:22 replication-orchestrator > sync summary: {
  "status" : "completed",
  "recordsSynced" : 212,
  "bytesSynced" : 2981100,
  "startTime" : 1724442257753,
  "endTime" : 1724442322719,
  "totalStats" : {
    "bytesCommitted" : 2981100,
    "bytesEmitted" : 2981100,
    "destinationStateMessagesEmitted" : 2,
    "destinationWriteEndTime" : 1724442322451,
    "destinationWriteStartTime" : 1724442257919,
    "meanSecondsBeforeSourceStateMessageEmitted" : 0,
    "maxSecondsBeforeSourceStateMessageEmitted" : 2,
    "maxSecondsBetweenStateMessageEmittedandCommitted" : 8,
    "meanSecondsBetweenStateMessageEmittedandCommitted" : 8,
    "recordsEmitted" : 212,
    "recordsCommitted" : 212,
    "replicationEndTime" : 1724442322457,
    "replicationStartTime" : 1724442257753,
    "sourceReadEndTime" : 1724442271138,
    "sourceReadStartTime" : 1724442257920,
    "sourceStateMessagesEmitted" : 2
  },
  "streamStats" : [ {
    "streamName" : "Account",
    "stats" : {
      "bytesCommitted" : 2981100,
      "bytesEmitted" : 2981100,
      "recordsEmitted" : 212,
      "recordsCommitted" : 212
    }
  } ],
  "performanceMetrics" : {
    "processFromSource" : {
      "elapsedTimeInNanos" : 586654693,
      "executionCount" : 217,
      "avgExecTimeInNanos" : 2703477.8479262674
    },
    "readFromSource" : {
      "elapsedTimeInNanos" : 6769759527,
      "executionCount" : 20025,
      "avgExecTimeInNanos" : 338065.39460674155
    },
    "processFromDest" : {
      "elapsedTimeInNanos" : 17918296,
      "executionCount" : 2,
      "avgExecTimeInNanos" : 8959148.0
    },
    "writeToDest" : {
      "elapsedTimeInNanos" : 5190005536,
      "executionCount" : 214,
      "avgExecTimeInNanos" : 2.425236231775701E7
    },
    "readFromDest" : {
      "elapsedTimeInNanos" : 58199900226,
      "executionCount" : 155145,
      "avgExecTimeInNanos" : 375132.2970511457
    }
  }
}
2024-08-23 19:45:22 replication-orchestrator > failures: [ ]
2024-08-23 19:45:22 replication-orchestrator > 
2024-08-23 19:45:22 replication-orchestrator > ----- END REPLICATION -----
2024-08-23 19:45:22 replication-orchestrator > 
2024-08-24 14:33:38 platform > Workload ea680f0f-e55c-4e9f-9e32-bee7cfe60098_417085_0_sync has returned a terminal status of cancelled.  Fetching output...
```

**Comment by LucasSegersFabro** [comment]
Searching for logs on other applications, I found out this seems to be happening regularly, even when syncs are working as intended:

```sh
io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: namespace rate limit exceeded
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:268) ~[grpc-stub-1.64.0.jar:1.64.0]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:249) ~[grpc-stub-1.64.0.jar:1.64.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:167) ~[grpc-stub-1.64.0.jar:1.64.0]
	at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.listClosedWorkflowExecutions(WorkflowServiceGrpc.java:4171) ~[temporal-serviceclient-1.22.3.jar:?]
	at io.airbyte.commons.temporal.WorkflowServiceStubsWrapped.lambda$blockingStubListClosedWorkflowExecutions$0(WorkflowServiceStubsWrapped.java:47) ~[io.airbyte-airbyte-commons-temporal-core-0.63.15.jar:?]
	at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243) ~[failsafe-3.3.2.jar:3.3.2]
	at dev.failsafe.Functions.lambda$get$0(Functions.java:46) ~[failsafe-3.3.2.jar:3.3.2]
	at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74) ~[failsafe-3.3.2.jar:3.3.2]
	at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187) ~[failsafe-3.3.2.jar:3.3.2]
	at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376) ~[failsafe-3.3.2.jar:3.3.2]
	at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112) ~[failsafe-3.3.2.jar:3.3.2]
	at io.airbyte.commons.temporal.RetryHelper.withRetries(RetryHelper.java:60) ~[io.airbyte-airbyte-commons-temporal-core-0.63.15.jar:?]
	at io.airbyte.commons.temporal.WorkflowServiceStubsWrapped.withRetries(WorkflowServiceStubsWrapped.java:67) ~[io.airbyte-airbyte-commons-temporal-core-0.63.15.jar:?]
	at io.airbyte.commons.temporal.WorkflowServiceStubsWrapped.blockingStubListClosedWorkflowExecutions(WorkflowServiceStubsWrapped.java:47) ~[io.airbyte-airbyte-commons-temporal-core-0.63.15.jar:?]
	at io.airbyte.commons.temporal.TemporalClient.fetchClosedWorkflowsByStatus(TemporalClient.java:138) ~[io.airbyte-airbyte-commons-temporal-0.63.15.jar:?]
	at io.airbyte.commons.temporal.TemporalClient.restartClosedWorkflowByStatus(TemporalClient.java:116) ~[io.airbyte-airbyte-commons-temporal-0.63.15.jar:?]
	at io.airbyte.cron.jobs.SelfHealTemporalWorkflows.cleanTemporal(SelfHealTemporalWorkflows.java:42) ~[io.airbyte-airbyte-cron-0.63.15.jar:?]
	at io.airbyte.cron.jobs.$SelfHealTemporalWorkflows$Definition$Exec.dispatch(Unknown Source) ~[io.airbyte-airbyte-cron-0.63.15.jar:?]
	at io.micronaut.context.AbstractExecutableMethod… 
```

Also [found this issue](https://github.com/airbytehq/airbyte/issues/30691) but don't know if related. Maybe try to scale temporal up?

<img width="1526" alt="image" src="https://github.com/user-attachments/assets/c9f51b48-dcab-40b1-a2a5-8d5bc3e2dfcb">

**Comment by davinchia** [comment]
Please see the last post there on the fix. This is a Temporal configuration.

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 180 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
