### ISSUE TITLE
Hubspot -> S3: `java.lang.RuntimeException: java.lang.IllegalArgumentException: Unspecified schema type`

### ISSUE THREAD

**Issue by jjuleslasarte** [airbytehq/airbyte#44507]
### Connector Name

destination-s3

### Connector Version

1.0.2

### What step the error happened?

None

### Relevant information

Repeatedly getting this error. On any of my Hubspot->S3 syncs. Started happening after 1.0.2 upgrade (was having other, different issues with 1.0). It is not a source problem, since it happens with several differnt hubspot instances connected through diff sources, anything going into S3, configured with parquet compression is getting this error.

Configuration:
![Screenshot 2024-08-21 at 8 13 28 AM](https://github.com/user-attachments/assets/292ef6f8-aa09-47b5-9087-b0772fd5ae86)

### Relevant log output

```shell
2024-08-20 20:56:56 INFO i.a.a.SegmentAnalyticsClient(close):237 - Segment analytics client closed.  No new events will be accepted.
2024-08-20 20:57:14 platform > Workload ab3f6478-ad4a-4b26-bddb-394abfa46f5b_16554017_19_sync has returned a terminal status of failure.  Fetching output...
2024-08-20 20:57:14 platform > Replication output for workload ab3f6478-ad4a-4b26-bddb-394abfa46f5b_16554017_19_sync : io.airbyte.config.ReplicationOutput@a452a3c[replicationAttemptSummary=io.airbyte.config.ReplicationAttemptSummary@5768aea1[status=failed,recordsSynced=1,bytesSynced=3278,startTime=1724187335337,endTime=1724187416129,totalStats=io.airbyte.config.SyncStats@72242a65[bytesCommitted=3278,bytesEmitted=129211295,destinationStateMessagesEmitted=3,destinationWriteEndTime=0,destinationWriteStartTime=1724187335534,estimatedBytes=<null>,estimatedRecords=<null>,meanSecondsBeforeSourceStateMessageEmitted=4,maxSecondsBeforeSourceStateMessageEmitted=1,maxSecondsBetweenStateMessageEmittedandCommitted=63,meanSecondsBetweenStateMessageEmittedandCommitted=29,recordsEmitted=2919,recordsCommitted=1,replicationEndTime=1724187413953,replicationStartTime=1724187335337,sourceReadEndTime=1724187399245,sourceReadStartTime=1724187335545,sourceStateMessagesEmitted=9,discoverSchemaEndTime=<null>,discoverSchemaStartTime=<null>,additionalProperties={}],streamStats=[io.airbyte.config.StreamSyncStats@39b14e50[streamName=companies,streamNamespace=<null>,stats=io.airbyte.config.SyncStats@1a869790[bytesCommitted=0,bytesEmitted=0,destinationStateMessagesEmitted=<null>,destinationWriteEndTime=<null>,destinationWriteStartTime=<null>,estimatedBytes=<null>,estimatedRecords=<null>,meanSecondsBeforeSourceStateMessageEmitted=<null>,maxSecondsBeforeSourceStateMessageEmitted=<null>,maxSecondsBetweenStateMessageEmittedandCommitted=<null>,meanSecondsBetweenStateMessageEmittedandCommitted=<null>,recordsEmitted=0,recordsCommitted=0,replicationEndTime=<null>,replicationStartTime=<null>,sourceReadEndTime=<null>,sourceReadStartTime=<null>,sourceStateMessagesEmitted=<null>,discoverSchemaEndTime=<null>,discoverSchemaStartTime=<null>,additionalProperties={}],wasBackfilled=<null>,wasResumed=<null>,additionalProperties={}], io.airbyte.config.StreamSyncStats@8092fc7[streamName=engagements,streamNamespace=<null>,stats=io.airbyte.config.SyncStats@5b2d4ba1[bytesCommitted=0,bytesEmitted=129208017,destinationStateMessagesEmitted=<null>,destinationWriteEndTime=<null>,destinationWriteStartTime=<null>,estimatedBytes=<null>,estimatedRecords=<null>,meanSecondsBeforeSourceStateMessageEmitted=<null>,maxSecondsBeforeSourceStateMessageEmitted=<null>,maxSecondsBetweenStateMessageEmittedandCommitted=<null>,meanSecondsBetweenStateMessageEmittedandCommitted=<null>,recordsEmitted=2918,recordsCommitted=0,replicationEndTime=<null>,replicationStartTime=<null>,sourceReadEndTime=<null>,sourceReadStartTime=<null>,sourceStateMessagesEmitted=<null>,discoverSchemaEndTime=<null>,discoverSchemaStartTime=<null>,additionalProperties={}],wasBackfilled=<null>,wasResumed=<null>,additionalProperties={}], io.airbyte.config.StreamSyncStats@685d5d5a[streamName=deals,streamNamespace=<null>,stats=io.airbyte.config.SyncStats@46497dd6[bytesCommitted=0,bytesEmitted=0,destinationStateMessagesEmitted=<null>,destinationWriteEndTime=<null>,destinationWriteStartTime=<null>,estimatedBytes=<null>,estimatedRecords=<null>,meanSecondsBeforeSourceStateMessageEmitted=<null>,maxSecondsBeforeSourceStateMessageEmitted=<null>,maxSecondsBetweenStateMessageEmittedandCommitted=<null>,meanSecondsBetweenStateMessageEmittedandCommitted=<null>,recordsEmitted=0,recordsCommitted=0,replicationEndTime=<null>,replicationStartTime=<null>,sourceReadEndTime=<null>,sourceReadStartTime=<null>,sourceStateMessagesEmitted=<null>,discoverSchemaEndTime=<null>,discoverSchemaStartTime=<null>,additionalProperties={}],wasBackfilled=<null>,wasResumed=<null>,additionalProperties={}], io.airbyte.config.StreamSyncStats@7ff15cf[streamName=deal_pipelines,streamNamespace=<null>,stats=io.airbyte.config.SyncStats@363e36d2[bytesCommitted=3278,bytesEmitted=3278,destinationStateMessagesEmitted=<null>,destinationWriteEndTime=<null>,destinationWriteStartTime=<null>,estimatedBytes=<null>,estimatedRecords=<null>,meanSecondsBeforeSourceStateMessageEmitted=<null>,maxSecondsBeforeSourceStateMessageEmitted=<null>,maxSecondsBetweenStateMessageEmittedandCommitted=<null>,meanSecondsBetweenStateMessageEmittedandCommitted=<null>,recordsEmitted=1,recordsCommitted=1,replicationEndTime=<null>,replicationStartTime=<null>,sourceReadEndTime=<null>,sourceReadStartTime=<null>,sourceStateMessagesEmitted=<null>,discoverSchemaEndTime=<null>,discoverSchemaStartTime=<null>,additionalProperties={}],wasBackfilled=<null>,wasResumed=<null>,additionalProperties={}]],performanceMetrics=io.airbyte.config.PerformanceMetrics@340b0ac2[additionalProperties={processFromSource={elapsedTimeInNanos=3121024274, executionCount=2938, avgExecTimeInNanos=1062295.5323349216}, readFromSource={elapsedTimeInNanos=55428659282, executionCount=19538, avgExecTimeInNanos=2836966.8994779405}, processFromDest={elapsedTimeInNanos=80494559, executionCount=4, avgExecTimeInNanos=2.012363975E7}, writeToDest={elapsedTimeInNanos=4096751614, executionCount=2928, avgExecTimeInNanos=1399163.8025956284}, readFromDest={elapsedTimeInNanos=70012529805, executionCount=49799, avgExecTimeInNanos=1405902.3234402298}}],additionalProperties={}],state=<null>,outputCatalog=ConfiguredAirbyteCatalog(streams=[ConfiguredAirbyteStream(stream=AirbyteStream(name=companies, jsonSchema={"type":["null","object"],"$schema":"http://json-schema.org/draft-07/schema#","properties":{"id":{"type":["null","string"],"description":"Unique identifier for the company"},"archived":{"type":["null","boolean"],"description":"Indicates whether the company is archived or active"},"contacts":{"type":["null","array"],"items":{"type":"string","description":"Details of 
[....complete schema omitted to met github content limit]
, supportedSyncModes=[full_refresh, incremental], sourceDefinedCursor=true, defaultCursorField=[updatedAt], sourceDefinedPrimaryKey=[[id]], namespace=null, isResumable=true), syncMode=full_refresh, destinationSyncMode=overwrite, cursorField=[updatedAt], primaryKey=[[id]], generationId=2, minimumGenerationId=2, syncId=16554017), ConfiguredAirbyteStream(stream=AirbyteStream(name=deal_pipelines, jsonSchema={"type":["null","object"],"$schema":"http://json-schema.org/draft-07/schema#","properties":{"label":{"type":["null","string"],"description":"The label or name of the deal pipeline."},"active":{"type":["null","boolean"],"description":"Indicates if the deal pipeline is currently active or not."},"stages":{"type":["null","array"],"items":{"type":["null","object"],"properties":{"label":{"type":["null","string"],"description":"The label or name of the deal stage."},"active":{"type":["null","boolean"],"description":"Indicates if the deal stage is currently active or not."},"stageId":{"type":["null","string"],"description":"The unique identifier of the deal stage."},"metadata":{"type":["null","object"],"properties":{"isClosed":{"type":["null","string"],"description":"Indicates if the deal stage is considered closed or not."},"probability":{"type":["null","string"],"description":"The probability of closing a deal at this stage."}},"description":"Additional information related to the deal stage."},"createdAt":{"type":["null","integer"],"description":"Timestamp for the creation date of the deal stage."},"updatedAt":{"type":["null","integer"],"description":"Timestamp for the last update to the deal stage."},"displayOrder":{"type":["null","integer"],"description":"The ordering of the deal stage for display within the pipeline."}}},"description":"List of deal stages within the pipeline."},"default":{"type":["null","boolean"],"description":"Indicates if this pipeline is the default one in the system."},"createdAt":{"type":["null","integer"],"description":"Timestamp for the creation date of the deal pipeline."},"updatedAt":{"type":["null","integer"],"description":"Timestamp for the last update to the deal pipeline."},"objectType":{"type":["null","string"],"description":"The type of object this deal pipeline is associated with."},"pipelineId":{"type":["null","string"],"description":"The unique identifier of the deal pipeline."},"displayOrder":{"type":["null","integer"],"description":"The ordering of the deal pipeline for display."},"objectTypeId":{"type":["null","string"],"description":"The ID of the object type this deal pipeline is associated with."}}}, supportedSyncModes=[full_refresh, incremental], sourceDefinedCursor=true, defaultCursorField=[updatedAt], sourceDefinedPrimaryKey=[[pipelineId]], namespace=null, isResumable=true), syncMode=full_refresh, destinationSyncMode=overwrite, cursorField=[updatedAt], primaryKey=[[pipelineId]], generationId=2, minimumGenerationId=2, syncId=16554017)]),failures=[io.airbyte.config.FailureReason@39a17658[failureOrigin=destination,failureType=system_error,internalMessage=java.lang.RuntimeException: java.lang.IllegalArgumentException: Unspecified schema type,externalMessage=Something went wrong in the connector. See the logs for more details.,metadata=io.airbyte.config.Metadata@468f5dce[additionalProperties={attemptNumber=19, jobId=16554017, from_trace_message=true, connector_command=write}],stacktrace=java.lang.RuntimeException: java.lang.IllegalArgumentException: Unspecified schema type
        at io.airbyte.cdk.integrations.destination.record_buffer.SerializedBufferingStrategy$getOrCreateBuffer$1.invoke(SerializedBufferingStrategy.kt:103)
        at io.airbyte.cdk.integrations.destination.record_buffer.SerializedBufferingStrategy$getOrCreateBuffer$1.invoke(SerializedBufferingStrategy.kt:95)
        at io.airbyte.cdk.integrations.destination.record_buffer.SerializedBufferingStrategy.getOrCreateBuffer$lambda$0(SerializedBufferingStrategy.kt:95)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1228)
        at io.airbyte.cdk.integrations.destination.record_buffer.SerializedBufferingStrategy.getOrCreateBuffer(SerializedBufferingStrategy.kt:95)
        at io.airbyte.cdk.integrations.destination.record_buffer.SerializedBufferingStrategy.addRecord(SerializedBufferingStrategy.kt:55)
        at io.airbyte.cdk.integrations.destination.s3.S3DestinationFlushFunction.flush(S3DestinationFlushFunction.kt:51)
        at io.airbyte.cdk.integrations.destination.async.FlushWorkers.flush$lambda$6(FlushWorkers.kt:167)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IllegalArgumentException: Unspecified schema type
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by jjuleslasarte** [comment]
[dev_logs_16554017_txt.txt](https://github.com/user-attachments/files/16694367/dev_logs_16554017_txt.txt)
Here;s the complete logs.

**Comment by marcosmarxm** [comment]
@airbytehq/platform-move can someone help me check if this issue is something in your domain?
