### ISSUE TITLE
[destination-bigquery] internal server error "Error executing PERSIST"

### ISSUE THREAD

**Issue by arctica** [airbytehq/airbyte#44797]
### Connector Name

destination-bigquery

### Connector Version

2.8.8

### What step the error happened?

During the sync

### Relevant information

After a recent upgrade of Airbyte and its Bigquery connector we are seeing internal server errors, these even happen when doing the connection test in the destination configuration page.

`Internal Server Error: Error executing PERSIST: ERROR: could not read block 8 in file \"base/16385/17447\": read only 0 of 8192 bytes`

Airbyte version is 0.63.19

### Relevant log output

```shell
io.temporal.failure.ActivityFailure: Activity with activityType='RunWithWorkload' failed: 'Activity task failed'. scheduledEventId=12, startedEventId=13, activityId=058b4886-4cb3-3aba-9de7-499179c64d3f, identity='1@airbyte-abctl-worker-676874f448-p7fvz', retryState=RETRY_STATE_MAXIMUM_ATTEMPTS_REACHED
	at java.base/java.lang.Thread.getStackTrace(Thread.java:2450)
	at io.temporal.internal.sync.ActivityStubBase.execute(ActivityStubBase.java:49)
	at io.temporal.internal.sync.ActivityInvocationHandler.lambda$getActivityFunc$0(ActivityInvocationHandler.java:83)
	at io.temporal.internal.sync.ActivityInvocationHandlerBase.invoke(ActivityInvocationHandlerBase.java:60)
	at jdk.proxy2/jdk.proxy2.$Proxy91.runWithWorkload(Unknown Source)
	at io.airbyte.workers.temporal.check.connection.CheckConnectionWorkflowImpl.run(CheckConnectionWorkflowImpl.java:53)
	at CheckConnectionWorkflowImplProxy.run$accessor$rBNdDbso(Unknown Source)
	at CheckConnectionWorkflowImplProxy$auxiliary$8MPentQF.call(Unknown Source)
	at io.airbyte.micronaut.temporal.TemporalActivityStubInterceptor.execute(TemporalActivityStubInterceptor.java:79)
	at CheckConnectionWorkflowImplProxy.run(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation$RootWorkflowInboundCallsInterceptor.execute(POJOWorkflowImplementationFactory.java:339)
	at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation.execute(POJOWorkflowImplementationFactory.java:314)
	at io.temporal.internal.sync.WorkflowExecutionHandler.runWorkflowMethod(WorkflowExecutionHandler.java:70)
	at io.temporal.internal.sync.SyncWorkflow.lambda$start$0(SyncWorkflow.java:135)
	at io.temporal.internal.sync.CancellationScopeImpl.run(CancellationScopeImpl.java:102)
	at io.temporal.internal.sync.WorkflowThreadImpl$RunnableWrapper.run(WorkflowThreadImpl.java:107)
	at io.temporal.worker.ActiveThreadReportingExecutor.lambda$submit$0(ActiveThreadReportingExecutor.java:53)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 180 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
