### ISSUE TITLE
[source-mongodb] MongoDB cursor not found error during sync

### ISSUE THREAD

**Issue by ivan-sukhomlyn** [airbytehq/airbyte#45103]
### Connector Name

source-mongodb

### Connector Version

1.5.2

### What step the error happened?

During the sync

### Relevant information

MongoDB source fails while syncing data to Google BigQuery in the `Full Refresh | Overwrite` mode due to the `cursor not found` error.
The same error happens during the initial data sync in the `Incremental` mode.

**Airbyte** platform version - `0.60.1`
**MongoDB** Atlas cluster version - `7.3`
**source-mongodb-v2** version - `1.5.2`
**destination-bigquery** version - `2.6.3`

For example, the job log
```
2024-09-03 13:46:54 replication-orchestrator > failures: [ {
  "failureOrigin" : "source",
  "failureType" : "system_error",
  "internalMessage" : "Command failed with error 43 (CursorNotFound): 'cursor ? 1228054012842582349 not found' on server pl-{ host }:1029. The full response is {\"ok\": 0.0, \"errmsg\": \"cursor ? 1228054012842582349 not found\", \"code\": 43, \"codeName\": \"CursorNotFound\", \"$clusterTime\": {\"clusterTime\": {\"$timestamp\": {\"t\": 1725371108, \"i\": 209}}, \"signature\": {\"hash\": {\"$binary\": {\"base64\": \"4G4fw28Rs2wwtdakTpAqlTy8ndk=\", \"subType\": \"00\"}}, \"keyId\": 7374888786343231759}}, \"operationTime\": {\"$timestamp\": {\"t\": 1725371108, \"i\": 209}}}",
  "externalMessage" : "com.mongodb.MongoCursorNotFoundException: Command failed with error 43 (CursorNotFound): 'cursor id 1228054012842582349 not found' on server pl-{ host }:1029. The full response is {\"ok\": 0.0, \"errmsg\": \"cursor id 1228054012842582349 not found\", \"code\": 43, \"codeName\": \"CursorNotFound\", \"$clusterTime\": {\"clusterTime\": {\"$timestamp\": {\"t\": 1725371108, \"i\": 209}}, \"signature\": {\"hash\": {\"$binary\": {\"base64\": \"4G4fw28Rs2wwtdakTpAqlTy8ndk=\", \"subType\": \"00\"}}, \"keyId\": 7374888786343231759}}, \"operationTime\": {\"$timestamp\": {\"t\": 1725371108, \"i\": 209}}}",
  "metadata" : {
    "attemptNumber" : 0,
    "jobId" : 2364,
    "from_trace_message" : true,
    "connector_command" : "read"
  },
```

### Relevant log output

```shell
2024-09-03 13:45:08 source > ERROR main i.a.c.i.u.ConnectorExceptionHandler(handleException):80 caught exception! io.airbyte.cdk.integrations.source.relationaldb.state.FailedRecordIteratorException: com.mongodb.MongoCursorNotFoundException: Command failed with error 43 (CursorNotFound): 'cursor id 1228054012842582349 not found' on server pl-{ host }:1029. The full response is {"ok": 0.0, "errmsg": "cursor id 1228054012842582349 not found", "code": 43, "codeName": "CursorNotFound", "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1725371108, "i": 209}}, "signature": {"hash": {"$binary": {"base64": "4G4fw28Rs2wwtdakTpAqlTy8ndk=", "subType": "00"}}, "keyId": 7374888786343231759}}, "operationTime": {"$timestamp": {"t": 1725371108, "i": 209}}}
        at io.airbyte.cdk.integrations.source.relationaldb.state.SourceStateIterator.computeNext(SourceStateIterator.kt:38) ~[airbyte-cdk-db-sources-0.44.2.jar:?]
        at io.airbyte.cdk.integrations.source.relationaldb.state.SourceStateIterator.computeNext(SourceStateIterator.kt:18) ~[airbyte-cdk-db-sources-0.44.2.jar:?]
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145) ~[guava-33.0.0-jre.jar:?]
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140) ~[guava-33.0.0-jre.jar:?]
        at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.kt:42) ~[airbyte-cdk-dependencies-0.44.2.jar:?]
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145) ~[guava-33.0.0-jre.jar:?]
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140) ~[guava-33.0.0-jre.jar:?]
        at io.airbyte.commons.util.CompositeIterator.computeNext(CompositeIterator.kt:67) ~[airbyte-cdk-dependencies-0.44.2.jar:?]
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145) ~[guava-33.0.0-jre.jar:?]
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140) ~[guava-33.0.0-jre.jar:?]
        at io.airbyte.commons.util.CompositeIterator.computeNext(CompositeIterator.kt:67) ~[airbyte-cdk-dependencies-0.44.2.jar:?]
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145) ~[guava-33.0.0-jre.jar:?]
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140) ~[guava-33.0.0-jre.jar:?]
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132) ~[?:?]
        at io.airbyte.cdk.integrations.base.IntegrationRunner.produceMessages(IntegrationRunner.kt:234) ~[airbyte-cdk-core-0.44.2.jar:?]
        at io.airbyte.cdk.integrations.base.IntegrationRunner.readSerial(IntegrationRunner.kt:291) ~[airbyte-cdk-core-0.44.2.jar:?]
        at io.airbyte.cdk.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.kt:190) [airbyte-cdk-core-0.44.2.jar:?]
        at io.airbyte.cdk.integrations.base.IntegrationRunner.run(IntegrationRunner.kt:119) [airbyte-cdk-core-0.44.2.jar:?]
        at io.airbyte.cdk.integrations.base.IntegrationRunner.run$default(IntegrationRunner.kt:113) [airbyte-cdk-core-0.44.2.jar:?]
        at io.airbyte.cdk.integrations.base.IntegrationRunner.run(IntegrationRunner.kt) [airbyte-cdk-core-0.44.2.jar:?]
        at io.airbyte.integrations.source.mongodb.MongoDbSource.main(MongoDbSource.java:53) [io.airbyte.airbyte-integrations.connectors-source-mongodb-v2.jar:?]
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by ivan-sukhomlyn** [comment]
Fixed with https://github.com/airbytehq/airbyte/pull/45883
