### ISSUE TITLE
[destination-mongodb] OOM when copying data from tmp tables to permanent

### ISSUE THREAD

**Issue by afillatre** [airbytehq/airbyte#45118]
### Connector Name

destination-mongodb

### Connector Version

0.2.0

### What step the error happened?

During the sync

### Relevant information

I'm synchronizing data from BigQuery to MongoDB.
MongoDB is an Atlas cluster.
Airbyte is hosted on our private Kubernetes cluster.

The problem occurs during the initial sync (never got to the incremental updates) after all data have been read from the source (BigQuery), and being copying over to the destination (MongoDB).

The `destination-mongo-write` pod has 2Gi available memory, but uses only 380Mi at its peak, before crashing.
The amount of transferred data is about 1M rows, for about 150Mo (which does not seem pretty high).

I added the logs since the last batch data from the source, to show where the connection actually fails.

### Relevant log output

```shell
2024-09-04 07:09:18 source > INFO i.a.c.i.s.r.AbstractDbSource(lambda$createReadIterator$5):432 Reading stream view_agg_users_lvl1_favourite_categories. Records read: 1030000
2024-09-04 07:09:18 replication-orchestrator > Records read: 1030000 (133 MB)
2024-09-04 07:09:18 source > INFO i.a.c.i.s.r.AbstractDbSource(lambda$read$1):184 Closing database connection pool.
2024-09-04 07:09:18 source > INFO i.a.c.i.s.r.AbstractDbSource(lambda$read$1):186 Closed database connection pool.
2024-09-04 07:09:18 source > INFO i.a.c.i.b.IntegrationRunner(runInternal):231 Completed integration: io.airbyte.integrations.source.bigquery.BigQuerySource
2024-09-04 07:09:18 source > INFO i.a.i.s.b.BigQuerySource(main):221 completed source: class io.airbyte.integrations.source.bigquery.BigQuerySource
2024-09-04 07:09:18 replication-orchestrator > (pod: data-platform / source-bigquery-read-9301-4-ihoiv) - Closed all resources for pod
2024-09-04 07:09:18 replication-orchestrator > Total records read: 1031449 (133 MB)
2024-09-04 07:09:18 replication-orchestrator > Schema validation was performed to a max of 10 records with errors per stream.
2024-09-04 07:09:18 replication-orchestrator > readFromSource: done. (source.isFinished:true, fromSource.isClosed:false)
2024-09-04 07:09:18 replication-orchestrator > thread status... heartbeat thread: false , replication thread: true
2024-09-04 07:09:25 replication-orchestrator > Stream status TRACE received of status: COMPLETE for stream data_platform_gold:view_agg_users_lvl1_favourite_categories
2024-09-04 07:09:25 replication-orchestrator > processMessage: done. (fromSource.isDone:true, forDest.isClosed:false)
2024-09-04 07:09:25 replication-orchestrator > writeToDestination: done. (forDest.isDone:true, isDestRunning:true)
2024-09-04 07:09:25 replication-orchestrator > thread status... timeout thread: false , replication thread: true
2024-09-04 07:10:36 destination > INFO i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):80 Airbyte message consumer: succeeded.
2024-09-04 07:10:36 destination > INFO i.a.i.d.m.MongodbRecordConsumer(close):90 Migration finished with no explicit errors. Copying data from tmp tables to permanent
2024-09-04 07:10:56 INFO i.a.a.SegmentAnalyticsClient(close):233 - Closing Segment analytics client...
2024-09-04 07:10:56 INFO i.a.a.BlockingShutdownAnalyticsPlugin(waitForFlush):289 - Waiting for Segment analytic client to flush enqueued messages...
2024-09-04 07:10:56 INFO i.a.a.BlockingShutdownAnalyticsPlugin(waitForFlush):301 - Segment analytic client flush complete.
2024-09-04 07:10:56 INFO i.a.a.SegmentAnalyticsClient(close):237 - Segment analytics client closed.  No new events will be accepted.
2024-09-04 07:10:55 destination > Terminating due to java.lang.OutOfMemoryError: Java heap space
2024-09-04 07:10:56 replication-orchestrator > (pod: data-platform / destination-mongodb-write-9301-4-jorlm) - Closed all resources for pod
2024-09-04 07:10:56 replication-orchestrator > readFromDestination: exception caught
io.airbyte.workers.internal.exception.DestinationException: Destination process exited with non-zero exit code 3
	at io.airbyte.workers.general.BufferedReplicationWorker.readFromDestination(BufferedReplicationWorker.java:490) ~[io.airbyte-airbyte-commons-worker-0.64.1.jar:?]
	at io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsync$2(BufferedReplicationWorker.java:219) ~[io.airbyte-airbyte-commons-worker-0.64.1.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
2024-09-04 07:10:56 replication-orchestrator > readFromDestination: done. (writeToDestFailed:false, dest.isFinished:true)
2024-09-04 07:10:56 replication-orchestrator > Closing StateCheckSumCountEventHandler
2024-09-04 07:10:56 replication-orchestrator > sync summary: {
  "status" : "failed",
  "recordsSynced" : 0,
  "bytesSynced" : 0,
  "startTime" : 1725431257204,
  "endTime" : 1725433856096,
  "totalStats" : {
    "bytesCommitted" : 0,
    "bytesEmitted" : 139985069,
    "destinationStateMessagesEmitted" : 0,
    "destinationWriteEndTime" : 0,
    "destinationWriteStartTime" : 1725431257247,
    "meanSecondsBeforeSourceStateMessageEmitted" : 0,
    "maxSecondsBeforeSourceStateMessageEmitted" : 0,
    "maxSecondsBetweenStateMessageEmittedandCommitted" : 0,
    "meanSecondsBetweenStateMessageEmittedandCommitted" : 0,
    "recordsEmitted" : 1031871,
    "recordsCommitted" : 0,
    "replicationEndTime" : 1725433856089,
    "replicationStartTime" : 1725431257204,
    "sourceReadEndTime" : 1725433758099,
    "sourceReadStartTime" : 1725431257248,
    "sourceStateMessagesEmitted" : 0
  },
  "streamStats" : [ {
    "streamName" : "view_agg_users_lvl1_favourite_categories",
    "streamNamespace" : "data_platform_gold",
    "stats" : {
      "bytesCommitted" : 0,
      "bytesEmitted" : 139985069,
      "recordsEmitted" : 1031871,
      "recordsCommitted" : 0
    }
  } ],
  "performanceMetrics" : {
    "processFromSource" : {
      "elapsedTimeInNanos" : 5981281394,
      "executionCount" : 1031874,
      "avgExecTimeInNanos" : 5796.523019283362
    },
    "readFromSource" : {
      "elapsedTimeInNanos" : 44060284532,
      "executionCount" : 1031875,
      "avgExecTimeInNanos" : 42699.24606371896
    },
    "processFromDest" : {
      "elapsedTimeInNanos" : 0,
      "executionCount" : 0,
      "avgExecTimeInNanos" : "NaN"
    },
    "writeToDest" : {
      "elapsedTimeInNanos" : 2465821495924,
      "executionCount" : 1031871,
      "avgExecTimeInNanos" : 2389660.622232818
    },
    "readFromDest" : {
      "elapsedTimeInNanos" : 2593414236319,
      "executionCount" : 218055,
      "avgExecTimeInNanos" : 1.1893394952278094E7
    }
  }
}
2024-09-04 07:10:56 replication-orchestrator > failures: [ {
  "failureOrigin" : "destination",
  "internalMessage" : "Destination process exited with non-zero exit code 3",
  "externalMessage" : "Something went wrong within the destination connector",
  "metadata" : {
    "attemptNumber" : 4,
    "jobId" : 9301,
    "connector_command" : "write"
  },
  "stacktrace" : "io.airbyte.workers.internal.exception.DestinationException: Destination process exited with non-zero exit code 3\n\tat io.airbyte.workers.general.BufferedReplicationWorker.readFromDestination(BufferedReplicationWorker.java:490)\n\tat io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsync$2(BufferedReplicationWorker.java:219)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\n",
  "timestamp" : 1725433856053
}, {
  "failureOrigin" : "replication",
  "internalMessage" : "io.airbyte.workers.exception.WorkerException: Destination process exit with code 3. This warning is normal if the job was cancelled.",
  "externalMessage" : "Something went wrong during replication",
  "metadata" : {
    "attemptNumber" : 4,
    "jobId" : 9301
  },
  "stacktrace" : "java.lang.RuntimeException: io.airbyte.workers.exception.WorkerException: Destination process exit with code 3. This warning is normal if the job was cancelled.\n\tat io.airbyte.workers.general.BufferedReplicationWorker$CloseableWithTimeout.lambda$close$0(BufferedReplicationWorker.java:535)\n\tat io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsyncWithTimeout$5(BufferedReplicationWorker.java:247)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\nCaused by: io.airbyte.workers.exception.WorkerException: Destination process exit with code 3. This warning is normal if the job was cancelled.\n\tat io.airbyte.workers.internal.DefaultAirbyteDestination.close(DefaultAirbyteDestination.java:186)\n\tat io.airbyte.workers.general.BufferedReplicationWorker$CloseableWithTimeout.lambda$close$0(BufferedReplicationWorker.java:533)\n\t... 5 more\n",
  "timestamp" : 1725433856056
} ]
2024-09-04 07:10:56 replication-orchestrator > 
2024-09-04 07:10:56 replication-orchestrator > ----- END REPLICATION -----
2024-09-04 07:10:56 replication-orchestrator > 
2024-09-04 07:10:56 replication-orchestrator > Returning output...
2024-09-04 07:11:25 platform > Workload ef06557a-92d3-41a9-b7da-843a7e984712_9301_4_sync has returned a terminal status of failure.  Fetching output...
2024-09-04 07:11:25 platform > Replication output for workload ef06557a-92d3-41a9-b7da-843a7e984712_9301_4_sync : io.airbyte.config.ReplicationOutput@387055b[replicationAttemptSummary=io.airbyte.config.ReplicationAttemptSummary@79db9266[status=failed,recordsSynced=0,bytesSynced=0,startTime=1725431257204,endTime=1725433856096,totalStats=io.airbyte.config.SyncStats@541b109[bytesCommitted=0,bytesEmitted=139985069,destinationStateMessagesEmitted=0,destinationWriteEndTime=0,destinationWriteStartTime=1725431257247,estimatedBytes=<null>,estimatedRecords=<null>,meanSecondsBeforeSourceStateMessageEmitted=0,maxSecondsBeforeSourceStateMessageEmitted=0,maxSecondsBetweenStateMessageEmittedandCommitted=0,meanSecondsBetweenStateMessageEmittedandCommitted=0,recordsEmitted=1031871,recordsCommitted=0,replicationEndTime=1725433856089,replicationStartTime=1725431257204,sourceReadEndTime=1725433758099,sourceReadStartTime=1725431257248,sourceStateMessagesEmitted=0,discoverSchemaEndTime=<null>,discoverSchemaStartTime=<null>,additionalProperties={}],streamStats=[io.airbyte.config.StreamSyncStats@4866762e[streamName=view_agg_users_lvl1_favourite_categories,streamNamespace=data_platform_gold,stats=io.airbyte.config.SyncStats@73f01fa4[bytesCommitted=0,bytesEmitted=139985069,destinationStateMessagesEmitted=<null>,destinationWriteEndTime=<null>,destinationWriteStartTime=<null>,estimatedBytes=<null>,estimatedRecords=<null>,meanSecondsBeforeSourceStateMessageEmitted=<null>,maxSecondsBeforeSourceStateMessageEmitted=<null>,maxSecondsBetweenStateMessageEmittedandCommitted=<null>,meanSecondsBetweenStateMessageEmittedandCommitted=<null>,recordsEmitted=1031871,recordsCommitted=0,replicationEndTime=<null>,replicationStartTime=<null>,sourceReadEndTime=<null>,sourceReadStartTime=<null>,sourceStateMessagesEmitted=<null>,discoverSchemaEndTime=<null>,discoverSchemaStartTime=<null>,additionalProperties={}],wasBackfilled=<null>,wasResumed=<null>,additionalProperties={}]],performanceMetrics=io.airbyte.config.PerformanceMetrics@569deb1e[additionalProperties={processFromSource={elapsedTimeInNanos=5981281394, executionCount=1031874, avgExecTimeInNanos=5796.523019283362}, readFromSource={elapsedTimeInNanos=44060284532, executionCount=1031875, avgExecTimeInNanos=42699.24606371896}, processFromDest={elapsedTimeInNanos=0, executionCount=0, avgExecTimeInNanos=NaN}, writeToDest={elapsedTimeInNanos=2465821495924, executionCount=1031871, avgExecTimeInNanos=2389660.622232818}, readFromDest={elapsedTimeInNanos=2593414236319, executionCount=218055, avgExecTimeInNanos=1.1893394952278094E7}}],additionalProperties={}],state=<null>,outputCatalog=ConfiguredAirbyteCatalog(streams=[ConfiguredAirbyteStream(stream=AirbyteStream(name=bq_view_agg_users_lvl1_favourite_categories, jsonSchema={"type":"object","properties":{"rank":{"type":"number","airbyte_type":"integer"},"score":{"type":"number","airbyte_type":"integer"},"user_id":{"type":"string"},"favouriteAt":{"type":"string"},"item_parent_category_name":{"type":"string"}},"$schema":"http://json-schema.org/draft-07/schema#"}, supportedSyncModes=[full_refresh, incremental], sourceDefinedCursor=false, defaultCursorField=[], sourceDefinedPrimaryKey=[], namespace=null, isResumable=null), syncMode=full_refresh, destinationSyncMode=overwrite, cursorField=[], primaryKey=[], generationId=null, minimumGenerationId=null, syncId=null, fields=null, mappers=[])]),failures=[io.airbyte.config.FailureReason@5e5cc13d[failureOrigin=destination,failureType=<null>,internalMessage=Destination process exited with non-zero exit code 3,externalMessage=Something went wrong within the destination connector,metadata=io.airbyte.config.Metadata@25700bde[additionalProperties={attemptNumber=4, jobId=9301, connector_command=write}],stacktrace=io.airbyte.workers.internal.exception.DestinationException: Destination process exited with non-zero exit code 3
	at io.airbyte.workers.general.BufferedReplicationWorker.readFromDestination(BufferedReplicationWorker.java:490)
	at io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsync$2(BufferedReplicationWorker.java:219)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
,retryable=<null>,timestamp=1725433856053,streamDescriptor=<null>,additionalProperties={}], io.airbyte.config.FailureReason@560e3deb[failureOrigin=replication,failureType=<null>,internalMessage=io.airbyte.workers.exception.WorkerException: Destination process exit with code 3. This warning is normal if the job was cancelled.,externalMessage=Something went wrong during replication,metadata=io.airbyte.config.Metadata@6ff2e92f[additionalProperties={attemptNumber=4, jobId=9301}],stacktrace=java.lang.RuntimeException: io.airbyte.workers.exception.WorkerException: Destination process exit with code 3. This warning is normal if the job was cancelled.
	at io.airbyte.workers.general.BufferedReplicationWorker$CloseableWithTimeout.lambda$close$0(BufferedReplicationWorker.java:535)
	at io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsyncWithTimeout$5(BufferedReplicationWorker.java:247)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: io.airbyte.workers.exception.WorkerException: Destination process exit with code 3. This warning is normal if the job was cancelled.
	at io.airbyte.workers.internal.DefaultAirbyteDestination.close(DefaultAirbyteDestination.java:186)
	at io.airbyte.workers.general.BufferedReplicationWorker$CloseableWithTimeout.lambda$close$0(BufferedReplicationWorker.java:533)
	... 5 more
,retryable=<null>,timestamp=1725433856056,streamDescriptor=<null>,additionalProperties={}]],additionalProperties={}]
2024-09-04 07:11:26 platform > 
2024-09-04 07:11:26 platform > No post-replication operation(s) to perform.
2024-09-04 07:11:26 platform > ----- START POST REPLICATION OPERATIONS -----
2024-09-04 07:11:26 platform > 
2024-09-04 07:11:26 platform > 
2024-09-04 07:11:26 platform > ----- END POST REPLICATION OPERATIONS -----
2024-09-04 07:11:26 platform > 
2024-09-04 07:11:26 platform > Retry State: RetryManager(completeFailureBackoffPolicy=BackoffPolicy(minInterval=PT10S, maxInterval=PT30M, base=3), partialFailureBackoffPolicy=null, successiveCompleteFailureLimit=5, totalCompleteFailureLimit=10, successivePartialFailureLimit=1000, totalPartialFailureLimit=20, successiveCompleteFailures=5, totalCompleteFailures=5, successivePartialFailures=0, totalPartialFailures=0)
 Backoff before next attempt: 13 minutes 30 seconds
2024-09-04 07:11:26 platform > Failing job: 9301, reason: Job failed after too many retries for connection ef06557a-92d3-41a9-b7da-843a7e984712
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by afillatre** [comment]
Any idea would be welcomed, because I'm completely stuck for now. Thanks.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
