### ISSUE TITLE
Airbyte platform - Failing activity "RunWithJobOutput"

### ISSUE THREAD

**Issue by dmalheiro84** [airbytehq/airbyte#45185]
### Platform Version

0.63.15

### What step the error happened?

None

### Relevant information

I used to integrate Airbyte with Monday.com as a source and PostgresSQL as a destination. Apparently this was working all fine.

Recently we made an update of the platform and unfortunately now I cannot set any of this connections...

### Relevant log output

```shell
Error while trying to create connection with Monday.Com:

Learn more
Internal message: Check failed because of an internal error
Failure origin: airbyte_platform

Stacktrace
io.temporal.failure.ActivityFailure: Activity with activityType='RunWithJobOutput' failed: 'Activity task failed'. scheduledEventId=12, startedEventId=13, activityId=834780a7-4e77-3c1c-8943-25795b7e7786, identity='1@391af1dfa34f', retryState=RETRY_STATE_MAXIMUM_ATTEMPTS_REACHED
	at java.base/java.lang.Thread.getStackTrace(Thread.java:2450)
	at io.temporal.internal.sync.ActivityStubBase.execute(ActivityStubBase.java:49)
	at io.temporal.internal.sync.ActivityInvocationHandler.lambda$getActivityFunc$0(ActivityInvocationHandler.java:83)
	at io.temporal.internal.sync.ActivityInvocationHandlerBase.invoke(ActivityInvocationHandlerBase.java:60)
	at jdk.proxy2/jdk.proxy2.$Proxy88.runWithJobOutput(Unknown Source)
	at io.airbyte.workers.temporal.check.connection.CheckConnectionWorkflowImpl.run(CheckConnectionWorkflowImpl.java:55)
	at CheckConnectionWorkflowImplProxy.run$accessor$I0Wy8491(Unknown Source)
	at CheckConnectionWorkflowImplProxy$auxiliary$0YlsUJzm.call(Unknown Source)
	at io.airbyte.micronaut.temporal.TemporalActivityStubInterceptor.execute(TemporalActivityStubInterceptor.java:79)
	at CheckConnectionWorkflowImplProxy.run(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation$RootWorkflowInboundCallsInterceptor.execute(POJOWorkflowImplementationFactory.java:339)
	at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation.execute(POJOWorkflowImplementationFactory.java:314)
	at io.temporal.internal.sync.WorkflowExecutionHandler.runWorkflowMethod(WorkflowExecutionHandler.java:70)
	at io.temporal.internal.sync.SyncWorkflow.lambda$start$0(SyncWorkflow.java:135)
	at io.temporal.internal.sync.CancellationScopeImpl.run(CancellationScopeImpl.java:102)
	at io.temporal.internal.sync.WorkflowThreadImpl$RunnableWrapper.run(WorkflowThreadImpl.java:107)
	at io.temporal.worker.ActiveThreadReportingExecutor.lambda$submit$0(ActiveThreadReportingExecutor.java:53)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)



Error while trying to connect with Postgres:

Configuration check failed
Check failed because of an internal error


Learn more
Internal message: Check failed because of an internal error
Failure origin: airbyte_platform

Stacktrace
io.temporal.failure.ActivityFailure: Activity with activityType='RunWithJobOutput' failed: 'Activity task failed'. scheduledEventId=12, startedEventId=13, activityId=8e692497-a642-3fd7-909a-0acd3fa1eb21, identity='1@391af1dfa34f', retryState=RETRY_STATE_MAXIMUM_ATTEMPTS_REACHED
	at java.base/java.lang.Thread.getStackTrace(Thread.java:2450)
	at io.temporal.internal.sync.ActivityStubBase.execute(ActivityStubBase.java:49)
	at io.temporal.internal.sync.ActivityInvocationHandler.lambda$getActivityFunc$0(ActivityInvocationHandler.java:83)
	at io.temporal.internal.sync.ActivityInvocationHandlerBase.invoke(ActivityInvocationHandlerBase.java:60)
	at jdk.proxy2/jdk.proxy2.$Proxy88.runWithJobOutput(Unknown Source)
	at io.airbyte.workers.temporal.check.connection.CheckConnectionWorkflowImpl.run(CheckConnectionWorkflowImpl.java:55)
	at CheckConnectionWorkflowImplProxy.run$accessor$I0Wy8491(Unknown Source)
	at CheckConnectionWorkflowImplProxy$auxiliary$0YlsUJzm.call(Unknown Source)
	at io.airbyte.micronaut.temporal.TemporalActivityStubInterceptor.execute(TemporalActivityStubInterceptor.java:79)
	at CheckConnectionWorkflowImplProxy.run(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation$RootWorkflowInboundCallsInterceptor.execute(POJOWorkflowImplementationFactory.java:339)
	at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation.execute(POJOWorkflowImplementationFactory.java:314)
	at io.temporal.internal.sync.WorkflowExecutionHandler.runWorkflowMethod(WorkflowExecutionHandler.java:70)
	at io.temporal.internal.sync.SyncWorkflow.lambda$start$0(SyncWorkflow.java:135)
	at io.temporal.internal.sync.CancellationScopeImpl.run(CancellationScopeImpl.java:102)
	at io.temporal.internal.sync.WorkflowThreadImpl$RunnableWrapper.run(WorkflowThreadImpl.java:107)
	at io.temporal.worker.ActiveThreadReportingExecutor.lambda$submit$0(ActiveThreadReportingExecutor.java:53)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
```

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 180 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
