### ISSUE TITLE
[source-braintree] HTTP error 422, exceeding search or paging limit

### ISSUE THREAD

**Issue by hellmund** [airbytehq/airbyte#45364]
### Connector Name

source-braintree

### Connector Version

0.3.14

### What step the error happened?

During the sync

### Relevant information

`Request to https://api.braintreegateway.com:443/merchants/REDACTED/transactions/advanced_search?page=1001 failed with status code 422 and error message None`

When synchronizing the transaction stream, I'm encountering the following issue. From the log output it appears that, by passing `page=1001` the connector is running into a limitation of the Braintree APIs, also see https://developer.paypal.com/braintree/docs/reference/general/searching/search-results/node#search-limit

### Relevant log output

```shell
2024-09-09 19:53:43 source > Encountered an exception while reading stream transaction_stream
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py", line 122, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py", line 197, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py", line 328, in _read_full_refresh
    for record_data_or_message in record_data_or_messages:
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py", line 104, in read_records
    yield from self.retriever.read_records(stream_slice)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 304, in read_records
    for stream_data in self._read_pages(self._parse_records, self.state, stream_slice):
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 282, in _read_pages
    response = self._fetch_next_page(stream_state, stream_slice, next_page_token)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 256, in _fetch_next_page
    return self.requester.send_request(
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 399, in send_request
    return self._validate_response(response)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 496, in _validate_response
    raise ReadException(error_message)
airbyte_cdk.sources.declarative.exceptions.ReadException: Request to https://api.braintreegateway.com:443/merchants/REDACTED/transactions/advanced_search?page=1001 failed with status code 422 and error message None
2024-09-09 19:53:43 source > Marking stream transaction_stream as STOPPED
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by natikgadzhi** [comment]
Yep, I see what's going on here. 

To fix this, we'd need to check if we're trying to fetch more than 10k records, and if we are, stop. We'd need to partition syncs in a way that a particular set of search filters never needs more than 10k results (or 50k for transactions). 

Alternatively, we could add error handling for 422 and:
- Stop gracefully without erroring out
- Give user a message that they should use a start date closer to today. 

@hellmund, try a different start date — it's likely going to work.

**Comment by patricktrainer** [comment]
Hey @natikgadzhi - my team is also experiencing this issue. Failing at page 1001 as well. 

![Image](https://github.com/user-attachments/assets/a02ebe7a-f43c-456e-b1ed-2afc1a587bbc)

**Comment by outerim** [comment]
@natikgadzhi regarding trying a different start date. If we're trying to load all the data from Braintree is that even possible? We've been with them for years and likely have millions of transactions...

**Comment by jingyen** [comment]
Could there be an end date parameter exposed so that users could manually backfill their data with various start - end dates until they reach a point where the 50k limit isn't an issue? This is a show stopper for users who have large amounts of data.

**Comment by jingyen** [comment]
@natikgadzhi I'd like to take a stab at adding an optional end date to facilitate a manual backfill.  I see that this is not a no/low-code integration.  Where should I start with CDK documentation to do this for braintree?
