### ISSUE TITLE
[source-postgresql] CDC replication Postgresql to Clickhouse Failed to correctly convert data value for ‘public.table.created_at’ of type timestamp

### ISSUE THREAD

**Issue by VenusKanami** [airbytehq/airbyte#45451]
### Connector Name

source-Postgresql, destination-Clickhouse

### Connector Version

Clickhouse 0.2.5, Postgresql 3.6.18	

### What step the error happened?

During the sync

### Relevant information

CDC Replication PostgreSQL to Clickhouse
Sync mode: Incremental | Append + Deduped 

### Relevant log output

```shell
2024-09-13 07:44:22 ERROR i.a.w.i.VersionedAirbyteStreamFactory(internalLog):313 - ERROR debezium-postgresconnector-api_crm-change-event-source-coordinator i.d.u.Loggings(logErrorAndTraceRecord):58 Failed to properly convert data value for 'public.table.created_at' of type timestamp org.apache.kafka.connect.errors.DataException: Invalid Java object for schema with type STRING: class java.lang.Long for field: "created_at"
        at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:242) ~[connect-api-3.7.0.jar:?]
        at org.apache.kafka.connect.data.Struct.put(Struct.java:216) ~[connect-api-3.7.0.jar:?]
        at io.debezium.relational.TableSchemaBuilder.lambda$createValueGenerator$5(TableSchemaBuilder.java:298) ~[debezium-core-2.6.2.Final.jar:2.6.2.Final]
        at io.debezium.relational.TableSchema.valueFromColumnData(TableSchema.java:141) ~[debezium-core-2.6.2.Final.jar:2.6.2.Final]
        at io.debezium.relational.RelationalChangeRecordEmitter.emitDeleteRecord(RelationalChangeRecordEmitter.java:136) ~[debezium-core-2.6.2.Final.jar:2.6.2.Final]
        at io.debezium.relational.RelationalChangeRecordEmitter.emitChangeRecords(RelationalChangeRecordEmitter.java:56) ~[debezium-core-2.6.2.Final.jar:2.6.2.Final]
        at io.debezium.connector.postgresql.PostgresChangeRecordEmitter.emitChangeRecords(PostgresChangeRecordEmitter.java:94) ~[debezium-connector-postgres-2.6.2.Final.jar:2.6.2.Final]
        at io.debezium.pipeline.EventDispatcher.dispatchDataChangeEvent(EventDispatcher.java:271) ~[debezium-core-2.6.2.Final.jar:2.6.2.Final]
        at io.debezium.connector.postgresql.PostgresStreamingChangeEventSource.processReplicationMessages(PostgresStreamingChangeEventSource.java:315) ~[debezium-connector-postgres-2.6.2.Final.jar:2.6.2.Final]
        at io.debezium.connector.postgresql.PostgresStreamingChangeEventSource.lambda$processMessages$0(PostgresStreamingChangeEventSource.java:217) ~[debezium-connector-postgres-2.6.2.Final.jar:2.6.2.Final]
        at io.debezium.connector.postgresql.connection.pgoutput.PgOutputMessageDecoder.decodeDelete(PgOutputMessageDecoder.java:512) ~[debezium-connector-postgres-2.6.2.Final.jar:2.6.2.Final]
        at io.debezium.connector.postgresql.connection.pgoutput.PgOutputMessageDecoder.processNotEmptyMessage(PgOutputMessageDecoder.java:214) ~[debezium-connector-postgres-2.6.2.Final.jar:2.6.2.Final]
        at io.debezium.connector.postgresql.connection.AbstractMessageDecoder.processMessage(AbstractMessageDecoder.java:41) ~[debezium-connector-postgres-2.6.2.Final.jar:2.6.2.Final]
        at io.debezium.connector.postgresql.connection.PostgresReplicationConnection$1.deserializeMessages(PostgresReplicationConnection.java:642) ~[debezium-connector-postgres-2.6.2.Final.jar:2.6.2.Final]
        at io.debezium.connector.postgresql.connection.PostgresReplicationConnection$1.readPending(PostgresReplicationConnection.java:634) ~[debezium-connector-postgres-2.6.2.Final.jar:2.6.2.Final]
        at io.debezium.connector.postgresql.PostgresStreamingChangeEventSource.processMessages(PostgresStreamingChangeEventSource.java:217) ~[debezium-connector-postgres-2.6.2.Final.jar:2.6.2.Final]
        at io.debezium.connector.postgresql.PostgresStreamingChangeEventSource.execute(PostgresStreamingChangeEventSource.java:179) ~[debezium-connector-postgres-2.6.2.Final.jar:2.6.2.Final]
        at io.debezium.connector.postgresql.PostgresStreamingChangeEventSource.execute(PostgresStreamingChangeEventSource.java:42) ~[debezium-connector-postgres-2.6.2.Final.jar:2.6.2.Final]
        at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:280) ~[debezium-core-2.6.2.Final.jar:2.6.2.Final]        at io.debezium.pipeline.ChangeEventSourceCoordinator.executeChangeEventSources(ChangeEventSourceCoordinator.java:197) ~[debezium-core-2.6.2.Final.jar:2.6.2.Final]
        at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:140) ~[debezium-core-2.6.2.Final.jar:2.6.2.Final]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

Stack Trace: org.apache.kafka.connect.errors.DataException: Invalid Java object for schema with type STRING: class java.lang.Long for field: "created_at"
        at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:242)
        at org.apache.kafka.connect.data.Struct.put(Struct.java:216)
        at io.debezium.relational.TableSchemaBuilder.lambda$createValueGenerator$5(TableSchemaBuilder.java:298)
        at io.debezium.relational.TableSchema.valueFromColumnData(TableSchema.java:141)
        at io.debezium.relational.RelationalChangeRecordEmitter.emitDeleteRecord(RelationalChangeRecordEmitter.java:136)
        at io.debezium.relational.RelationalChangeRecordEmitter.emitChangeRecords(RelationalChangeRecordEmitter.java:56)
        at io.debezium.connector.postgresql.PostgresChangeRecordEmitter.emitChangeRecords(PostgresChangeRecordEmitter.java:94)
        at io.debezium.pipeline.EventDispatcher.dispatchDataChangeEvent(EventDispatcher.java:271)
        at io.debezium.connector.postgresql.PostgresStreamingChangeEventSource.processReplicationMessages(PostgresStreamingChangeEventSource.java:315)
        at io.debezium.connector.postgresql.PostgresStreamingChangeEventSource.lambda$processMessages$0(PostgresStreamingChangeEventSource.java:217)
        at io.debezium.connector.postgresql.connection.pgoutput.PgOutputMessageDecoder.decodeDelete(PgOutputMessageDecoder.java:512)
        at io.debezium.connector.postgresql.connection.pgoutput.PgOutputMessageDecoder.processNotEmptyMessage(PgOutputMessageDecoder.java:214)
        at io.debezium.connector.postgresql.connection.AbstractMessageDecoder.processMessage(AbstractMessageDecoder.java:41)
        at io.debezium.connector.postgresql.connection.PostgresReplicationConnection$1.deserializeMessages(PostgresReplicationConnection.java:642)
        at io.debezium.connector.postgresql.connection.PostgresReplicationConnection$1.readPending(PostgresReplicationConnection.java:634)
        at io.debezium.connector.postgresql.PostgresStreamingChangeEventSource.processMessages(PostgresStreamingChangeEventSource.java:217)
        at io.debezium.connector.postgresql.PostgresStreamingChangeEventSource.execute(PostgresStreamingChangeEventSource.java:179)
        at io.debezium.connector.postgresql.PostgresStreamingChangeEventSource.execute(PostgresStreamingChangeEventSource.java:42)
        at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:280)
        at io.debezium.pipeline.ChangeEventSourceCoordinator.executeChangeEventSources(ChangeEventSourceCoordinator.java:197)
        at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:140)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 180 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.
