### ISSUE TITLE
Kubernetes: Problem syncing Hubspot to Postgres

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#4548]
## Enviroment
- **Airbyte version**:  ~
- **OS Version / Instance**: ~
- **Deployment**: Kubernetes 
- **Source Connector and version**: Hubspot
- **Destination Connector and version**: Postgres
- **Severity**: Very Low / Low / **Medium** / High / Critical
- **Step where error happened**: Sync job

## Current Behavior
From [slack convo](https://airbytehq.slack.com/archives/C01MFR03D5W/p1624880967083000)
Opening this to try the connection using the Kubernetes deployment and validated.

## Expected Behavior
*Tell us what should happen.*

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

2021-06-28 11:26:57 INFO () LineGobbler(voidCall):85 - Generating airbyte_tables/public/sync_table_60d56e729__rliest_value_4757fe10.sql from sync_table_60d56e729938f241d424d5ff_contacts/associated-company/properties/hs_analytics_first_touch_converting_campaign_timestamp_earliest_value_4757fe10
2021-06-28 11:26:57 INFO () LineGobbler(voidCall):85 - Generating airbyte_ctes/public/sync_table_60d56e729__groups_fields_options_ab1.sql from sync_table_60d56e729938f241d424d5ff_forms/formFieldGroups/fields/options
2021-06-28 11:26:57 INFO () LineGobbler(voidCall):85 - Generating airbyte_ctes/public/sync_table_60d56e729__groups_fields_options_ab2.sql from sync_table_60d56e729938f241d424d5ff_forms/formFieldGroups/fields/options
2021-06-28 11:26:57 INFO () LineGobbler(voidCall):85 - Generating airbyte_ctes/public/sync_table_60d56e729__groups_fields_options_ab3.sql from sync_table_60d56e729938f241d424d5ff_forms/formFieldGroups/fields/options
2021-06-28 11:26:57 INFO () LineGobbler(voidCall):85 - Generating airbyte_tables/public/sync_table_60d56e729__groups_fields_options.sql from sync_table_60d56e729938f241d424d5ff_forms/formFieldGroups/fields/options
2021-06-28 11:26:57 INFO () LineGobbler(voidCall):85 - Generating airbyte_ctes/public/sync_table_60d56e729__ups_fields_validation_ab1.sql from sync_table_60d56e729938f241d424d5ff_forms/formFieldGroups/fields/validation
2021-06-28 11:26:57 INFO () LineGobbler(voidCall):85 - Generating airbyte_ctes/public/sync_table_60d56e729__ups_fields_validation_ab2.sql from sync_table_60d56e729938f241d424d5ff_forms/formFieldGroups/fields/validation
2021-06-28 11:26:57 INFO () LineGobbler(voidCall):85 - Generating airbyte_ctes/public/sync_table_60d56e729__ups_fields_validation_ab3.sql from sync_table_60d56e729938f241d424d5ff_forms/formFieldGroups/fields/validation
2021-06-28 11:26:57 INFO () LineGobbler(voidCall):85 - Generating airbyte_tables/public/sync_table_60d56e729__ups_fields_validation.sql from sync_table_60d56e729938f241d424d5ff_forms/formFieldGroups/fields/validation
2021-06-28 11:26:57 INFO () LineGobbler(voidCall):85 - Ignoring stream 'selectedOptions' from sync_table_60d56e729938f241d424d5ff_forms/formFieldGroups/fields/selectedOptions because properties list is empty
2021-06-28 11:26:57 INFO () LineGobbler(voidCall):85 - Ignoring stream 'blockedEmailAddresses' from sync_table_60d56e729938f241d424d5ff_forms/formFieldGroups/fields/validation/blockedEmailAddresses because properties list is empty
2021-06-28 11:27:00 INFO () LineGobbler(voidCall):85 - Running with dbt=0.19.1
2021-06-28 11:27:14 INFO () LineGobbler(voidCall):85 - [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
2021-06-28 11:27:14 INFO () LineGobbler(voidCall):85 - There are 1 unused configuration paths:
2021-06-28 11:27:14 INFO () LineGobbler(voidCall):85 - - models.airbyte_utils.generated.airbyte_views
2021-06-28 11:27:14 INFO () LineGobbler(voidCall):85 -
2021-06-28 11:27:14 INFO () LineGobbler(voidCall):85 - Found 700 models, 0 tests, 0 snapshots, 0 analyses, 364 macros, 0 operations, 0 seed files, 16 sources, 0 exposures
2021-06-28 11:27:14 INFO () LineGobbler(voidCall):85 -
2021-06-28 11:27:14 INFO () LineGobbler(voidCall):85 - Encountered an error:
2021-06-28 11:27:14 INFO () LineGobbler(voidCall):85 - Database Error
2021-06-28 11:27:14 INFO () LineGobbler(voidCall):85 - there is already a transaction in progress
2021-06-28 11:27:16 INFO () KubePodProcess(getReturnCode):574 - Exit code for pod airbyte-worker-1-2-ypmag is 2
2021-06-28 11:27:16 INFO () KubeProcessFactory(lambda$create$0):92 - Port consumer releasing: 9028
2021-06-28 11:27:16 INFO () KubeProcessFactory(lambda$create$0):92 - Port consumer releasing: 9029
2021-06-28 11:27:16 INFO () KubeProcessFactory(lambda$create$0):94 - Port consumer skipping releasing: 9028
2021-06-28 11:27:16 INFO () KubeProcessFactory(lambda$create$0):94 - Port consumer skipping releasing: 9029
2021-06-28 11:27:16 INFO () TemporalAttemptExecution(lambda$getWorkerThread$2):149 - Completing future exceptionally...
io.airbyte.workers.WorkerException: Normalization Failed.
at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:68) ~[io.airbyte-airbyte-workers-0.26.4-alpha.jar:?]
at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:36) ~[io.airbyte-airbyte-workers-0.26.4-alpha.jar:?]
at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:146) ~[io.airbyte-airbyte-workers-0.26.4-alpha.jar:?]
at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: io.airbyte.workers.WorkerException: Normalization Failed.
at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:65) ~[io.airbyte-airbyte-workers-0.26.4-alpha.jar:?]
... 3 more
Suppressed: io.airbyte.workers.WorkerException: Normalization process wasn't successful
at io.airbyte.workers.normalization.DefaultNormalizationRunner.close(DefaultNormalizationRunner.java:131) ~[io.airbyte-airbyte-workers-0.26.4-alpha.jar:?]
at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:60) ~[io.airbyte-airbyte-workers-0.26.4-alpha.jar:?]
at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:36) ~[io.airbyte-airbyte-workers-0.26.4-alpha.jar:?]
at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:146) ~[io.airbyte-airbyte-workers-0.26.4-alpha.jar:?]
at java.lang.Thread.run(Thread.java:832) [?:?]
2021-06-28 11:27:16 INFO () TemporalAttemptExecution(get):133 - Stopping cancellation check scheduling...
2021-06-28 11:27:16 WARN () POJOActivityTaskHandler$POJOActivityImplementation(execute):243 - Activity failure. ActivityId=c30caa1a-4e7f-30a0-9c14-92f703823895, activityType=Normalize, attempt=1
java.util.concurrent.ExecutionException: io.airbyte.workers.WorkerException: Normalization Failed.
at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[?:?]
at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2063) ~[?:?]
at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:131) ~[io.airbyte-airbyte-workers-0.26.4-alpha.jar:?]
at io.airbyte.workers.temporal.SyncWorkflow$NormalizationActivityImpl.normalize(SyncWorkflow.java:317) ~[io.airbyte-airbyte-workers-0.26.4-alpha.jar:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityInboundCallsInterceptor.execute(POJOActivityTaskHandler.java:277) ~[temporal-sdk-1.0.4.jar:?]
at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityImplementation.execute(POJOActivityTaskHandler.java:216) ~[temporal-sdk-1.0.4.jar:?]
at io.temporal.internal.sync.POJOActivityTaskHandler.handle(POJOActivityTaskHandler.java:181) ~[temporal-sdk-1.0.4.jar:?]
at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:192) ~[temporal-sdk-1.0.4.jar:?]
at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:154) ~[temporal-sdk-1.0.4.jar:?]
at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73) ~[temporal-sdk-1.0.4.jar:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: io.airbyte.workers.WorkerException: Normalization Failed.
at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:68) ~[io.airbyte-airbyte-workers-0.26.4-alpha.jar:?]
at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:36) ~[io.airbyte-airbyte-workers-0.26.4-alpha.jar:?]
at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:146) ~[io.airbyte-airbyte-workers-0.26.4-alpha.jar:?]
... 1 more
Caused by: io.airbyte.workers.WorkerException: Normalization Failed.
at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:65) ~[io.airbyte-airbyte-workers-0.26.4-alpha.jar:?]
at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:36) ~[io.airbyte-airbyte-workers-0.26.4-alpha.jar:?]
at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:146) ~[io.airbyte-airbyte-workers-0.26.4-alpha.jar:?]
... 1 more
Suppressed: io.airbyte.workers.WorkerException: Normalization process wasn't successful
at io.airbyte.workers.normalization.DefaultNormalizationRunner.close(DefaultNormalizationRunner.java:131) ~[io.airbyte-airbyte-workers-0.26.4-alpha.jar:?]
at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:60) ~[io.airbyte-airbyte-workers-0.26.4-alpha.jar:?]
at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:36) ~[io.airbyte-airbyte-workers-0.26.4-alpha.jar:?]
at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:146) ~[io.airbyte-airbyte-workers-0.26.4-alpha.jar:?]
at java.lang.Thread.run(Thread.java:832) [?:?]

```

</details>

## Steps to Reproduce
1.
2.
3.

**Comment by grishick** [comment]
Hubspot to Postgres connections have been working with normalization successfully
