### ISSUE TITLE
Source Salesforce: Schema fetching failure

### ISSUE THREAD

**Issue by po3na4skld** [airbytehq/airbyte#4564]
## Enviroment
- **Airbyte version**:  0.26.4-alpha
- **OS Version / Instance**: macOS 11.2.3
- **Deployment**: Docker
- **Source Connector and version**: Salesforce 0.2.3
- **Destination Connector and version**: Local CSV 0.2.7, BigQuery 0.3.7
- **Severity**: High
- **Step where error happened**: Setup new connection

## Current Behavior
When fetching the schema from the source, it fails with the next error I found in doker-compose up logs output:

org.glassfish.jersey.server.ServerRuntime$Responder writeResponse
SEVERE: An I/O error has occurred while writing a response message entity to the container output stream.

It runs unlit the end of the daily request quota. Then schema fetching fails due to limits.
 
## Expected Behavior
Schema should be fetched normally without any errors.

## Logs
[error_log.txt](https://github.com/airbytehq/airbyte/files/6768958/error_log.txt)

## Steps to Reproduce
1. docker compose up airbyte project
2. create source Salesforce
3. create local CSV or BigQuery destination
4. set up a connection
5. see the error in docker compose up command output

## Are you willing to submit a PR?
Yes

**Comment by keu** [comment]
@sherifnada @po3na4skld my initial guess seem right that this is the same issue we have in https://github.com/airbytehq/airbyte/pull/4175/files
I think the fix can be the same

**Comment by po3na4skld** [comment]
@sherifnada updated the title and the description

**Comment by grishick** [comment]
Related oncall issues:

- https://github.com/airbytehq/oncall/issues/212
- https://github.com/airbytehq/oncall/issues/308

**Comment by evantahler** [comment]
Is this still an issue?

**Comment by grishick** [comment]
> Is this still an issue?

Yes, unless someone explicitly fixed it recently. I haven't seen any related changes or tests.

**Comment by evantahler** [comment]
There's some good additional information (Temporal message size for one) in https://github.com/airbytehq/airbyte/issues/3943, which has been closed as a duplicate

**Comment by keu** [comment]
@evantahler you could also add support for `$ref` and optimize the payload

**Comment by evantahler** [comment]
Linking https://github.com/airbytehq/airbyte/pull/15888 which is part of the way we solve this problem

**Comment by namur007** [comment]
Any update on this or is the process still to create a seperate user with limited scope?

**Comment by arthurbarros** [comment]
> Any update on this or is the process still to create a seperate user with limited scope?

+1 on this. Also having the same issue trying to fetch 1200+ tables on Oracle DB.

**Comment by surajmaurya14** [comment]
+1 Even I am having issue for MYSQL DB when it is trying discover_schema: 502 Bad Gateway. I had 1000+ tables in DB.

**Comment by surajmaurya14** [comment]
@

> +1 Even I am having issue for MYSQL DB when it is trying discover_schema: 502 Bad Gateway. I had 1000+ tables in DB.

@evantahler Any update for this?

**Comment by philippeboyd** [comment]
Same boat as @arthurbarros 

Any news on this? I tried everything and no environment variables is changing the fact that **Discovery fails after 5 minutes.**

![image](https://github.com/airbytehq/airbyte/assets/3239656/21319958-e5b5-48ff-a445-965438bc6268)

I also tried setting the worker's missing environment variables in `.env` and linking them in docker-compose.yaml for the worker
```
# Worker
ACTIVITY_CHECK_TIMEOUT=15
ACTIVITY_DISCOVERY_TIMEOUT=30
```

![image](https://github.com/airbytehq/airbyte/assets/3239656/824a629e-c9ec-446b-9231-d0d898977dbc)

There's also the `BASIC_AUTH_PROXY_TIMEOUT` environment variable (seen in linked issue #19201) for nginx timeouts, but that's set to `900` so 15 minutes.

![image](https://github.com/airbytehq/airbyte/assets/3239656/de40a3c6-997a-4adb-a515-83e4434e169a)

This issue is over 2 years old...

**Comment by arthurbarros** [comment]
> Same boat as @arthurbarros
> 
> Any news on this? I tried everything and no environment variables is changing the fact that **Discovery fails after 5 minutes.**
> 
> ![image](https://private-user-images.githubusercontent.com/3239656/284409642-21319958-e5b5-48ff-a445-965438bc6268.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MDA0MjQsIm5iZiI6MTcwMjQwMDEyNCwicGF0aCI6Ii8zMjM5NjU2LzI4NDQwOTY0Mi0yMTMxOTk1OC1lNWI1LTQ4ZmYtYTQ0NS05NjU0MzhiYzYyNjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTJUMTY1NTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWM2ODEyYjUyNDdlZTU3NDhjNzdkNTc5NmEwYjM0ZmJjM2E3M2M1NzlkZDM1MGNiZWU2NWJjZjUxZjVmZWY3ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1h-MUM5e_7nXj0X1JsrIBIFP3Zeex-as9OFNNYGaXF0)
> 
> I also tried setting the worker's missing environment variables in `.env` and linking them in docker-compose.yaml for the worker
> 
> ```
> # Worker
> ACTIVITY_CHECK_TIMEOUT=15
> ACTIVITY_DISCOVERY_TIMEOUT=30
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/3239656/284410039-824a629e-c9ec-446b-9231-d0d898977dbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MDA0MjQsIm5iZiI6MTcwMjQwMDEyNCwicGF0aCI6Ii8zMjM5NjU2LzI4NDQxMDAzOS04MjRhNjI5ZS1jOWVjLTQ0NmItOTIzMS1kMGQ4OTg5NzdkYmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTJUMTY1NTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWY0MjM5ODg0ZTRjOWJkM2E1M2MyOGIwOWViNjlhODEyOTViN2JjNzFhZWJiNzg4MmFjNGFhMjhmNTM4NDc4YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EvUZxM9mptQLP4De0Pfy3468_OcCtctygGsNNs5huIw)
> 
> There's also the `BASIC_AUTH_PROXY_TIMEOUT` environment variable (seen in linked issue #19201) for nginx timeouts, but that's set to `900` so 15 minutes.
> 
> ![image](https://private-user-images.githubusercontent.com/3239656/284410256-de40a3c6-997a-4adb-a515-83e4434e169a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MDA0MjQsIm5iZiI6MTcwMjQwMDEyNCwicGF0aCI6Ii8zMjM5NjU2LzI4NDQxMDI1Ni1kZTQwYTNjNi05OTdhLTRhZGItYTUxNS04M2U0NDM0ZTE2OWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTJUMTY1NTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjQ1NGUwOGNhZDQyMTViZGJiMWQ2YjA0NzBhNTk1NGEzMTRiZDMzZGFhNjQ0YjEyY2MzMjExODM2NzdhODQ1NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ByKpKd45CEh8OKTRETlSoLvLwXCIlvN1-obBwL7qYu0)
> 
> I also tried setting `WORKLOAD_API_READ_TIMEOUT_SECONDS=1200` with no success;
> 
> Using Airbyte `v0.50.34`

The only workaround I found working, is to create multiple users on Oracle DB and give permission to work in a subset of tables. With that have multiple Oracle DB connections for each of those users.

It's ugly but works.

**Comment by philippeboyd** [comment]
@evantahler Such as?
I'm looking at the [release changelogs](https://github.com/airbytehq/airbyte/releases), what kind of improvements are we looking for?

**Comment by surajmaurya14** [comment]
> Part of the problem here was that until recently, the Airbyte platform could not handle discovered catalogs over ~4mb, due to a limitation in Temporal. We've changed up how we pass information between jobs recently which might help alleviate this.

Any dates when this changes would arrive in stable...

**Comment by surajmaurya14** [comment]
Currently, for me on cloud, discover_schema api gave below response (final line):
Discover primary keys for tables: [.....]

We had 2500+ tables on MYSQL.

But after that screen is freezed:
![image](https://github.com/airbytehq/airbyte/assets/49981798/d353d9bd-a02f-4e59-94dd-f4cc2634f72a)

For now, only solution which works is create multiple users on DB with limited access as @arthurbarros said.

Any dates when will changes be released to stable @evantahler

**Comment by pmossman** [comment]
@surajmaurya14 the change to how we pass Temporal data is live on Cloud, but there may be another bottleneck somewhere in our system when handling such a large catalog. 

Could you share your Cloud workspace ID and source name where you see the frozen screen so we can investigate where the bottleneck is? (Feel free to email it to me at `parker@airbyte.io` or message it to me on the [Airbyte Slack](https://airbytehq.slack.com/join/shared_invite/zt-28ls9a3oy-AsPJQ~Uo2MuTLrE34UPbdw#/shared-invite/email))

**Comment by surajmaurya14** [comment]
> @surajmaurya14 the change to how we pass Temporal data is live on Cloud, but there may be another bottleneck somewhere in our system when handling such a large catalog.
> 
> Could you share your Cloud workspace ID and source name where you see the frozen screen so we can investigate where the bottleneck is? (Feel free to email it to me at `parker@airbyte.io` or message it to me on the [Airbyte Slack](https://airbytehq.slack.com/join/shared_invite/zt-28ls9a3oy-AsPJQ~Uo2MuTLrE34UPbdw#/shared-invite/email), I'm `@Parker Mossman` there)

Mailed you @pmossman

**Comment by pmossman** [comment]
Thanks @surajmaurya14, I was able to reproduce the issue and investigate our Temporal cluster while the discovery job was running to see where the failure originated from. 

In this case, we have a hard cap of 9 minute execution time for Discover jobs. I think this catalog is so large that it is taking longer than 9 minutes to generate, so Temporal terminates the job at the 9 minute mark before it finishes. I can follow up with a few folks internally to see if we can either:
(a): increase the 9 minute threshold to give cases like this more time
(b): investigate this particular source to see if there's an optimization we can make for large table counts (since 9+ minutes is obviously a poor user experience!)

**Comment by pmossman** [comment]
@surajmaurya14 I passed along this feedback to our database sources team, and they recommended we try increasing the 9 minute timeout to 30 minutes to see if your use case eventually succeeds.

I made this change today, so our Temporal workers in Airbyte Cloud will now keep Discover jobs running up to 30 minutes before terminating. 

Obviously this is just a stop gap and it'd be ideal to optimize this source for cases where we have thousands of tables, but I'm hoping this unblocks you and gives us some more insight into where the bottleneck may be.

Can you give things another try and let me know how it goes? If the job still freezes/times out after 30 minutes, we'll likely need to do more investigation into the particular source connector to see where things are getting stuck.

**Comment by surajmaurya14** [comment]
@pmossman Server temporarily unavailable error.
Wrote a reply on same email to you.

**Comment by pmossman** [comment]
Thanks @surajmaurya14, I did some more digging and here's what I found:

Your discover catalog jobs are now able to finish in Temporal, so the increase to 30 minutes on the Temporal side helped.
However, our Load Balancer is configured with a maximum request time of 10 minutes, which means that even if the Discover job eventually succeeds, the server issues a 502 before it can finish processing the network request.

I also observed 502 errors before the 10 minute mark is reached, which seems to correspond with new code deploys that cause server pods to restart. So even if we could raise the maximum request time from 10 minutes to 30 minutes, we deploy code so often that there's a high likelihood the server would drop the request before it could complete.

We have an ongoing project to convert the Discover API to an async model, so that our server no longer needs to keep an active thread open for the entire duration of the Discover job. This project should address the fundamental issue at hand here, I'll make a note to tag you when it lands so we can make sure your use case is finally unblocked.

Thanks for the back and forth here, I know it must be frustrating that the app isn't working for you now but this iteration is extremely helpful for improving the platform and I really appreciate your involvement!

**Comment by necsord** [comment]
We seem to be having the same or similar issue, maybe someone can confirm.

We're trying to create a connection between Netsuite and Snowflake but the discover schema is throwing a Bad Gateway after few minutes. Our Airbyte instance is self hosted on Kubernetes and looking at the pods, the whole process for discovering schema still runs for a total of 11 minutes, so I'm guessing it's some kind of problem with keeping track of the progress. 

```
Request URL: https://{DOMAIN}/api/v1/sources/discover_schema
Request Method: POST
Status Code: 502 Bad Gateway
Remote Address: {IP}:443
Referrer Policy: strict-origin-when-cross-origin
Content-Length: 497
Content-Type: text/html
Date: Tue, 19 Mar 2024 16:53:52 GMT
Etag: "6537f572-1f1"
Server: nginx/1.25.3
```

I tried finding corresponding log but all I could find was one from webapp


>[error] 37#37: *1336519 upstream prematurely closed connection while reading response header from upstream, client: {IP}, server: localhost, request: "POST /api/v1/sources/discover_schema HTTP/1.1", upstream: "http://{IP}:8001/

**Comment by pedrohsroque** [comment]
Same issue here,
Trying to sync MySql to Snowflake

**Comment by shmf** [comment]
Same here with an Oracle Database

**Comment by evantahler** [comment]
This will be solved by https://github.com/airbytehq/airbyte-platform-internal/pull/12109

**Comment by plenti-jacob-roe** [comment]
Same here, we have tried increasing temporal message limit and http timeouts to no effect.

Trying to sync MSSQL to Databricks.

Though we have an old version of Airbyte(0.44.2) running and don't have this issue on that version with the same MSSQL Database and Databricks. Both are running on K8s

**Comment by jonodutch** [comment]
Also experiencing this issue with large Oracle db

**Comment by shmf** [comment]
Hey @evantahler is there any ETA? :) thanks

**Comment by evantahler** [comment]
cc @davinchia 
There's no ETA as of yet, but dealing with large catalogs is on our near-term roadmap.

**Comment by marcosmarxm** [comment]
2 problems here:
1. size problem of the catalog: this one is almost fixed. Updating to the latest version you shouldn't have this problem anymore.
2. time problem (how long it take to discover your schema): today there is a timeout of 10 min to discover the catalog. A possible is planned to be released in near future.

**Comment by shmf** [comment]
@marcosmarxm not sure what latest version you mean - i just tested airbyte 0.60.1 and oracle conenctor and i still get this error message:
`2024-05-24 16:06:21 platform > Attempt 0 to call to write discover schema result error: io.airbyte.api.client.invoker.generated.ApiException: writeDiscoverCatalogResult call failed with: 413 - {"message":"Request Entity Too Large","_links":{"self":{"href":"/api/v1/sources/write_discover_catalog_result","templated":false}},"_embedded":{"errors":[{"message":"The content length [10546869] exceeds the maximum allowed content length [10485760]","_links":{},"_embedded":{}}]}}`

**Comment by myu65** [comment]
I am currently facing this issue as well. I just tested Airbyte 0.63.2 (OSS version on WSL) with the Postgres connector, and I am still encountering the same 413 error. It seems that the size problem with the catalog has not been resolved in this version.


```
airbyte-worker                    | 2024-06-24 01:58:28 INFO i.a.c.t.HeartbeatUtils(withBackgroundHeartbeat):64 - Stopping temporal heartbeating...
airbyte-worker                    | 2024-06-24 01:58:28 INFO i.a.c.t.HeartbeatUtils(withBackgroundHeartbeat):73 - Temporal heartbeating stopped.
airbyte-worker                    | 2024-06-24 01:58:28 WARN i.t.i.a.ActivityTaskExecutors$BaseActivityTaskExecutor(execute):126 - Activity failure. ActivityId=cfcf798c-1ca9-35a3-af14-e14852c013fd, activityType=Run, attempt=1
airbyte-worker                    | java.lang.RuntimeException: io.temporal.serviceclient.CheckedExceptionWrapper: io.airbyte.workers.exception.WorkerException: Error while discovering schema
airbyte-worker                    |     at io.airbyte.commons.temporal.HeartbeatUtils.withBackgroundHeartbeat(HeartbeatUtils.java:62) ~[io.airbyte-airbyte-commons-temporal-core-0.63.2.jar:?]
airbyte-worker                    |     at io.airbyte.workers.temporal.discover.catalog.DiscoverCatalogActivityImpl.run(DiscoverCatalogActivityImpl.java:183) ~[io.airbyte-airbyte-workers-0.63.2.jar:?]
airbyte-worker                    |     at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
airbyte-worker                    |     at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
airbyte-worker                    |     at io.temporal.internal.activity.RootActivityInboundCallsInterceptor$POJOActivityInboundCallsInterceptor.executeActivity(RootActivityInboundCallsInterceptor.java:64) ~[temporal-sdk-1.22.3.jar:?]
airbyte-worker                    |     at io.temporal.internal.activity.RootActivityInboundCallsInterceptor.execute(RootActivityInboundCallsInterceptor.java:43) ~[temporal-sdk-1.22.3.jar:?]
airbyte-worker                    |     at io.temporal.internal.activity.ActivityTaskExecutors$BaseActivityTaskExecutor.execute(ActivityTaskExecutors.java:107) ~[temporal-sdk-1.22.3.jar:?]
airbyte-worker                    |     at io.temporal.internal.activity.ActivityTaskHandlerImpl.handle(ActivityTaskHandlerImpl.java:124) ~[temporal-sdk-1.22.3.jar:?]
airbyte-worker                    |     at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handleActivity(ActivityWorker.java:278) ~[temporal-sdk-1.22.3.jar:?]
airbyte-worker                    |     at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:243) ~[temporal-sdk-1.22.3.jar:?]
airbyte-worker                    |     at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:216) ~[temporal-sdk-1.22.3.jar:?]
airbyte-worker                    |     at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:105) ~[temporal-sdk-1.22.3.jar:?]
airbyte-worker                    |     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
airbyte-worker                    |     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
airbyte-worker                    |     at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
airbyte-worker                    | Caused by: io.temporal.serviceclient.CheckedExceptionWrapper: io.airbyte.workers.exception.WorkerException: Error while discovering schema
airbyte-worker                    |     at io.temporal.serviceclient.CheckedExceptionWrapper.wrap(CheckedExceptionWrapper.java:57) ~[temporal-serviceclient-1.22.3.jar:?]
airbyte-worker                    |     at io.temporal.internal.sync.WorkflowInternal.wrap(WorkflowInternal.java:539) ~[temporal-sdk-1.22.3.jar:?]
airbyte-worker                    |     at io.temporal.activity.Activity.wrap(Activity.java:52) ~[temporal-sdk-1.22.3.jar:?]
airbyte-worker                    |     at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:143) ~[io.airbyte-airbyte-workers-0.63.2.jar:?]
airbyte-worker                    |     at io.airbyte.workers.temporal.discover.catalog.DiscoverCatalogActivityImpl.lambda$run$1(DiscoverCatalogActivityImpl.java:198) ~[io.airbyte-airbyte-workers-0.63.2.jar:?]
airbyte-worker                    |     at io.airbyte.commons.temporal.HeartbeatUtils.withBackgroundHeartbeat(HeartbeatUtils.java:57) ~[io.airbyte-airbyte-commons-temporal-core-0.63.2.jar:?]
airbyte-worker                    |     ... 14 more
airbyte-worker                    | Caused by: io.airbyte.workers.exception.WorkerException: Error while discovering schema
airbyte-worker                    |     at io.airbyte.workers.general.DefaultDiscoverCatalogWorker.run(DefaultDiscoverCatalogWorker.java:136) ~[io.airbyte-airbyte-commons-worker-0.63.2.jar:?]
airbyte-worker                    |     at io.airbyte.workers.general.DefaultDiscoverCatalogWorker.run(DefaultDiscoverCatalogWorker.java:52) ~[io.airbyte-airbyte-commons-worker-0.63.2.jar:?]
airbyte-worker                    |     at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:138) ~[io.airbyte-airbyte-workers-0.63.2.jar:?]
airbyte-worker                    |     at io.airbyte.workers.temporal.discover.catalog.DiscoverCatalogActivityImpl.lambda$run$1(DiscoverCatalogActivityImpl.java:198) ~[io.airbyte-airbyte-workers-0.63.2.jar:?]
airbyte-worker                    |     at io.airbyte.commons.temporal.HeartbeatUtils.withBackgroundHeartbeat(HeartbeatUtils.java:57) ~[io.airbyte-airbyte-commons-temporal-core-0.63.2.jar:?]
airbyte-worker                    |     ... 14 more
airbyte-worker                    | Caused by: org.openapitools.client.infrastructure.ClientException: Client error : 413 Request Entity Too Large
airbyte-worker                    |     at io.airbyte.api.client.generated.SourceApi.writeDiscoverCatalogResult(SourceApi.kt:1163) ~[io.airbyte-airbyte-api-0.63.2.jar:?]
airbyte-worker                    |     at io.airbyte.workers.general.DefaultDiscoverCatalogWorker.run(DefaultDiscoverCatalogWorker.java:125) ~[io.airbyte-airbyte-commons-worker-0.63.2.jar:?]
airbyte-worker                    |     at io.airbyte.workers.general.DefaultDiscoverCatalogWorker.run(DefaultDiscoverCatalogWorker.java:52) ~[io.airbyte-airbyte-commons-worker-0.63.2.jar:?]
airbyte-worker                    |     at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:138) ~[io.airbyte-airbyte-workers-0.63.2.jar:?]
airbyte-worker                    |     at io.airbyte.workers.temporal.discover.catalog.DiscoverCatalogActivityImpl.lambda$run$1(DiscoverCatalogActivityImpl.java:198) ~[io.airbyte-airbyte-workers-0.63.2.jar:?]
airbyte-worker                    |     at io.airbyte.commons.temporal.HeartbeatUtils.withBackgroundHeartbeat(HeartbeatUtils.java:57) ~[io.airbyte-airbyte-commons-temporal-core-0.63.2.jar:?]
airbyte-worker                    |     ... 14 more
```

**Comment by shmf** [comment]
@myu65 i managed to overcome a similar error thanks to this suggestion https://github.com/airbytehq/airbyte/issues/37463#issuecomment-2073396085

**Comment by myu65** [comment]
> @myu65 i managed to overcome a similar error thanks to this suggestion [#37463 (comment)](https://github.com/airbytehq/airbyte/issues/37463#issuecomment-2073396085)

Thank you for your reply.  
I managed to resolve my error by following your suggestion.

I added the following values to the `.env` file and the `docker-compose` file, which resolved the error in fetching the schema when making connection:
 
**.env**
```
MICRONAUT_SERVER_MAX_REQUEST_SIZE=52428800
```

**docker-compose.yaml**
```yaml
    environment:
      # ADD THIS ENVIRONMENT VARIABLE TO THE APPROPRIATE CONTAINER
      # I AM UNSURE WHICH CONTAINER REQUIRES THIS SETTING
      - MICRONAUT_SERVER_MAX_REQUEST_SIZE=${MICRONAUT_SERVER_MAX_REQUEST_SIZE}
```



To reduce the number of similar issues being raised, I suggest updating the following files:

https://github.com/airbytehq/airbyte-platform/blob/main/.env  
https://github.com/airbytehq/airbyte-platform/blob/main/docker-compose.yaml

**Comment by myu65** [comment]
I am experiencing this issue in Airbyte 1.0 (OSS) and am exploring solutions using the abctl startup method.

**values.yaml**
```yaml
global:
  env_vars:
    MICRONAUT_SERVER_MAX_REQUEST_SIZE: "104857600"
```

I ran the command `abctl local install --values ./values.yaml`.

Afterward, I confirmed that all pods have the environment variable `MICRONAUT_SERVER_MAX_REQUEST_SIZE=104857600`.

```bash
root@airbyte-abctl-control-plane:/# kubectl exec -it airbyte-abctl-worker-5bd88d996-2gqqx -n airbyte-abctl -- env | grep MICRONAUT
MICRONAUT_SERVER_MAX_REQUEST_SIZE=104857600
MICRONAUT_ENVIRONMENTS=control-plane
```

However, discovering the schema failed with a 413 Request Entity Too Large error.

```
2024-10-01 10:11:35 INFO i.a.c.ConnectorMessageProcessor(updateConfigFromControlMessage):231 - Checking for optional control message...
2024-10-01 10:11:35 INFO i.a.c.ConnectorMessageProcessor(setOutput):176 - Writing catalog result to API...
2024-10-01 10:11:37 ERROR i.a.c.ConnectorWatcher(run):139 - Error performing operation: io.airbyte.workers.exception.WorkerException
io.airbyte.workers.exception.WorkerException: Unexpected error performing DISCOVER. The exit of the connector was: 0
	at io.airbyte.connectorSidecar.ConnectorMessageProcessor.run(ConnectorMessageProcessor.kt:90) ~[io.airbyte-airbyte-connector-sidecar-1.0.0.jar:?]
	at io.airbyte.connectorSidecar.ConnectorWatcher.run(ConnectorWatcher.kt:113) [io.airbyte-airbyte-connector-sidecar-1.0.0.jar:?]
	at io.airbyte.connectorSidecar.ApplicationKt.main(Application.kt:32) [io.airbyte-airbyte-connector-sidecar-1.0.0.jar:?]
	at io.airbyte.connectorSidecar.ApplicationKt.main(Application.kt) [io.airbyte-airbyte-connector-sidecar-1.0.0.jar:?]
Caused by: org.openapitools.client.infrastructure.ClientException: Client error : 413 Request Entity Too Large
	at io.airbyte.api.client.generated.SourceApi.writeDiscoverCatalogResult(SourceApi.kt:1163) ~[io.airbyte-airbyte-api-server-api-1.0.0.jar:?]
	at io.airbyte.connectorSidecar.ConnectorMessageProcessor.setOutput(ConnectorMessageProcessor.kt:179) ~[io.airbyte-airbyte-connector-sidecar-1.0.0.jar:?]
	at io.airbyte.connectorSidecar.ConnectorMessageProcessor.run(ConnectorMessageProcessor.kt:84) ~[io.airbyte-airbyte-connector-sidecar-1.0.0.jar:?]
	... 3 more
```

I also manually changed the ingress-nginx configuration to `proxy-body-size:100m`, but this did not resolve the error.

I'm stuck and would appreciate any guidance or suggestions on how to resolve this issue. Thank you!

**Comment by ambyte** [comment]
@myu65 did you manage to find a solution to the problem?

**Comment by rab4u** [comment]
@myu65 , did you manage to find a solution ?

**Comment by myu65** [comment]
i couldn’t resolve this problem yet.
