### ISSUE TITLE
[destination-bigquery] Encounter Duplicate column name _airbyte_meta when using Bigquery destination connector

### ISSUE THREAD

**Issue by PuChenTW** [airbytehq/airbyte#45666]
### Connector Name

BigQuery

### Connector Version

2.9.0

### What step the error happened?

None

### Relevant information

I’m using Airbyte Cloud to sync data from S3 to BigQuery and have encountered the following error:

`Warning from destination: com.google.cloud.bigquery.BigQueryException: Duplicate column name _airbyte_meta in CREATE TABLE at [7:1]`

I checked the BigQuery history and found that the query has duplicate columns with different data types.

```
CREATE  TABLE `playground-project`.`poc_0919`.`mongodb_from_airbyte_test` (
  _airbyte_raw_id STRING NOT NULL,
  _airbyte_extracted_at TIMESTAMP NOT NULL,
  _airbyte_meta JSON NOT NULL,
  _airbyte_generation_id INTEGER,
`_airbyte_data` JSON,
`_airbyte_meta` JSON,
`_airbyte_raw_id` STRING,
`_ab_source_file_url` STRING,
`_airbyte_extracted_at` INT64,
`_airbyte_generation_id` INT64,
`_ab_source_file_last_modified` STRING
)
PARTITION BY (DATE_TRUNC(_airbyte_extracted_at, DAY))
CLUSTER BY `_airbyte_extracted_at`;
```

### Relevant log output

```shell
2024-09-19 08:01:32 replication-orchestrator > ----- START REPLICATION -----
2024-09-19 08:01:32 replication-orchestrator > 
2024-09-19 08:01:33 replication-orchestrator > Number of Resumed Full Refresh Streams: {0}
2024-09-19 08:01:33 replication-orchestrator > Running destination...
2024-09-19 08:01:33 replication-orchestrator > Writing messages to protocol version 0.2.0
2024-09-19 08:01:33 replication-orchestrator > Reading messages from protocol version 0.2.0
2024-09-19 08:01:33 replication-orchestrator > Reading messages from protocol version 0.2.0
2024-09-19 08:01:33 replication-orchestrator > readFromSource: start
2024-09-19 08:01:33 replication-orchestrator > Starting workload heartbeat
2024-09-19 08:01:33 replication-orchestrator > Starting source heartbeat check. Will check threshold of 5400 seconds, every 1 minutes.
2024-09-19 08:01:33 replication-orchestrator > processMessage: start
2024-09-19 08:01:33 replication-orchestrator > writeToDestination: start
2024-09-19 08:01:33 replication-orchestrator > readFromDestination: start
2024-09-19 08:01:35 destination > INFO main i.a.i.d.b.BigQueryDestinationKt(main):565 Starting Destination : class io.airbyte.integrations.destination.bigquery.BigQueryDestination
2024-09-19 08:01:35 destination > INFO main i.a.c.i.b.IntegrationCliParser$Companion(parseOptions):144 integration args: {catalog=/dest/catalog.json, write=null, config=/dest/connectorConfig.json}
2024-09-19 08:01:35 destination > INFO main i.a.c.i.b.IntegrationRunner(runInternal):130 Running integration: io.airbyte.integrations.destination.bigquery.BigQueryDestination
2024-09-19 08:01:35 destination > INFO main i.a.c.i.b.IntegrationRunner(runInternal):131 Command: WRITE
2024-09-19 08:01:35 destination > INFO main i.a.c.i.b.IntegrationRunner(runInternal):132 Integration config: IntegrationConfig{command=WRITE, configPath='/dest/connectorConfig.json', catalogPath='/dest/catalog.json', statePath='null'}
2024-09-19 08:01:35 destination > WARN main c.n.s.UnknownKeywordFactory(lambda$getKeyword$0):37 Unknown keyword group - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword or if it should generate annotations AnnotationKeyword
2024-09-19 08:01:35 destination > WARN main c.n.s.UnknownKeywordFactory(lambda$getKeyword$0):37 Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword or if it should generate annotations AnnotationKeyword
2024-09-19 08:01:35 destination > WARN main c.n.s.UnknownKeywordFactory(lambda$getKeyword$0):37 Unknown keyword display_type - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword or if it should generate annotations AnnotationKeyword
2024-09-19 08:01:35 destination > WARN main c.n.s.UnknownKeywordFactory(lambda$getKeyword$0):37 Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword or if it should generate annotations AnnotationKeyword
2024-09-19 08:01:35 destination > WARN main c.n.s.UnknownKeywordFactory(lambda$getKeyword$0):37 Unknown keyword always_show - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword or if it should generate annotations AnnotationKeyword
2024-09-19 08:01:35 destination > WARN main c.n.s.UnknownKeywordFactory(lambda$getKeyword$0):37 Unknown keyword groups - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword or if it should generate annotations AnnotationKeyword
2024-09-19 08:01:35 destination > INFO main i.a.i.d.b.BigQueryUtils(getLoadingMethod):233 Selected loading method is set to: STANDARD
2024-09-19 08:01:36 destination > INFO main i.a.i.b.d.t.CatalogParser(parseCatalog):132 Running sync with stream configs: [StreamConfig(id=StreamId(finalNamespace=poc_one_data_raw, finalName=mongodb_from_airbyte_cdc_sit_6083_cloud, rawNamespace=airbyte_internal, rawName=poc_one_data_raw_raw__stream_mongodb_from_airbyte_cdc_sit_6083_cloud, originalNamespace=poc_one_data_raw, originalName=mongodb_from_airbyte_cdc_sit_6083_cloud), postImportAction=APPEND, primaryKey=[], cursor=Optional[ColumnId(name=_ab_source_file_last_modified, originalName=_ab_source_file_last_modified, canonicalName=_ab_source_file_last_modified)], columns={ColumnId(name=_airbyte_data, originalName=_airbyte_data, canonicalName=_airbyte_data)=Struct(properties={}), ColumnId(name=_airbyte_meta, originalName=_airbyte_meta, canonicalName=_airbyte_meta)=Struct(properties={}), ColumnId(name=_airbyte_raw_id, originalName=_airbyte_raw_id, canonicalName=_airbyte_raw_id)=STRING, ColumnId(name=_ab_source_file_url, originalName=_ab_source_file_url, canonicalName=_ab_source_file_url)=STRING, ColumnId(name=_airbyte_extracted_at, originalName=_airbyte_extracted_at, canonicalName=_airbyte_extracted_at)=INTEGER, ColumnId(name=_airbyte_generation_id, originalName=_airbyte_generation_id, canonicalName=_airbyte_generation_id)=INTEGER, ColumnId(name=_ab_source_file_last_modified, originalName=_ab_source_file_last_modified, canonicalName=_ab_source_file_last_modified)=STRING}, generationId=0, minimumGenerationId=0, syncId=18286011)]
2024-09-19 08:01:36 destination > INFO main i.a.i.b.d.o.DefaultSyncOperation(createPerStreamOpClients):52 Preparing required schemas and tables for all streams
2024-09-19 08:01:38 source > Starting syncing SourceS3
2024-09-19 08:01:38 source > Marking stream mongodb_from_airbyte_cdc_sit_6083_cloud as STARTED
2024-09-19 08:01:38 source > Setting state of SourceS3 stream to {}
2024-09-19 08:01:38 source > Syncing stream: mongodb_from_airbyte_cdc_sit_6083_cloud 
2024-09-19 08:01:38 replication-orchestrator > Stream status TRACE received of status: STARTED for stream mongodb_from_airbyte_cdc_sit_6083_cloud
2024-09-19 08:01:38 replication-orchestrator > Sending update for mongodb_from_airbyte_cdc_sit_6083_cloud - null -> RUNNING
2024-09-19 08:01:38 replication-orchestrator > Stream Status Update Received: mongodb_from_airbyte_cdc_sit_6083_cloud - RUNNING
2024-09-19 08:01:38 replication-orchestrator > Creating status: mongodb_from_airbyte_cdc_sit_6083_cloud - RUNNING
2024-09-19 08:01:39 source > Received 3 objects from S3 for prefix 'mongodb_from_airbyte_cdc_sit_6083_cloud/'.
2024-09-19 08:01:39 source > Finished listing objects from S3 for prefix=mongodb_from_airbyte_cdc_sit_6083_cloud/. Found 3 objects.
2024-09-19 08:01:39 source > Finished listing objects from S3. Found 3 objects total (3 unique objects).
2024-09-19 08:01:39 destination > INFO sync-operations-1 i.a.i.b.d.t.TyperDeduperUtil(runMigrationsAsync$lambda$12):165 Maybe executing BigQueryDV2Migration migration for stream poc_one_data_raw.mongodb_from_airbyte_cdc_sit_6083_cloud.
2024-09-19 08:01:39 destination > INFO sync-operations-1 i.a.i.d.b.m.BigQueryDV2Migration(migrateIfNecessary):27 Initializing DV2 Migration check
2024-09-19 08:01:39 destination > INFO sync-operations-1 i.a.i.b.d.t.BaseDestinationV1V2Migrator(migrateIfNecessary):19 Assessing whether migration is necessary for stream mongodb_from_airbyte_cdc_sit_6083_cloud
2024-09-19 08:01:39 destination > INFO sync-operations-1 i.a.i.b.d.t.BaseDestinationV1V2Migrator(shouldMigrate):43 Checking whether v1 raw table _airbyte_raw_mongodb_from_airbyte_cdc_sit_6083_cloud in dataset poc_one_data_raw exists
2024-09-19 08:01:40 destination > INFO sync-operations-1 i.a.i.b.d.t.BaseDestinationV1V2Migrator(shouldMigrate):50 Migration Info: Required for Sync mode: true, No existing v2 raw tables: false, A v1 raw table exists: false
2024-09-19 08:01:40 destination > INFO sync-operations-1 i.a.i.b.d.t.BaseDestinationV1V2Migrator(migrateIfNecessary):30 No Migration Required for stream: mongodb_from_airbyte_cdc_sit_6083_cloud
2024-09-19 08:01:40 destination > INFO main i.a.i.b.d.t.TyperDeduperUtil(executeRawTableMigrations):66 Refetching initial state for streams: [StreamId(finalNamespace=poc_one_data_raw, finalName=mongodb_from_airbyte_cdc_sit_6083_cloud, rawNamespace=airbyte_internal, rawName=poc_one_data_raw_raw__stream_mongodb_from_airbyte_cdc_sit_6083_cloud, originalNamespace=poc_one_data_raw, originalName=mongodb_from_airbyte_cdc_sit_6083_cloud)]
2024-09-19 08:01:42 destination > INFO main i.a.i.b.d.t.TyperDeduperUtil(executeRawTableMigrations):73 Updated states: [DestinationInitialStatus(streamConfig=StreamConfig(id=StreamId(finalNamespace=poc_one_data_raw, finalName=mongodb_from_airbyte_cdc_sit_6083_cloud, rawNamespace=airbyte_internal, rawName=poc_one_data_raw_raw__stream_mongodb_from_airbyte_cdc_sit_6083_cloud, originalNamespace=poc_one_data_raw, originalName=mongodb_from_airbyte_cdc_sit_6083_cloud), postImportAction=APPEND, primaryKey=[], cursor=Optional[ColumnId(name=_ab_source_file_last_modified, originalName=_ab_source_file_last_modified, canonicalName=_ab_source_file_last_modified)], columns={ColumnId(name=_airbyte_data, originalName=_airbyte_data, canonicalName=_airbyte_data)=Struct(properties={}), ColumnId(name=_airbyte_meta, originalName=_airbyte_meta, canonicalName=_airbyte_meta)=Struct(properties={}), ColumnId(name=_airbyte_raw_id, originalName=_airbyte_raw_id, canonicalName=_airbyte_raw_id)=STRING, ColumnId(name=_ab_source_file_url, originalName=_ab_source_file_url, canonicalName=_ab_source_file_url)=STRING, ColumnId(name=_airbyte_extracted_at, originalName=_airbyte_extracted_at, canonicalName=_airbyte_extracted_at)=INTEGER, ColumnId(name=_airbyte_generation_id, originalName=_airbyte_generation_id, canonicalName=_airbyte_generation_id)=INTEGER, ColumnId(name=_ab_source_file_last_modified, originalName=_ab_source_file_last_modified, canonicalName=_ab_source_file_last_modified)=STRING}, generationId=0, minimumGenerationId=0, syncId=18286011), isFinalTablePresent=false, initialRawTableStatus=InitialRawTableStatus(rawTableExists=true, hasUnprocessedRecords=false, maxProcessedTimestamp=Optional.empty), initialTempRawTableStatus=InitialRawTableStatus(rawTableExists=false, hasUnprocessedRecords=false, maxProcessedTimestamp=Optional.empty), isSchemaMismatch=false, isFinalTableEmpty=true, destinationState=BigQueryDestinationState(needsSoftReset=false), finalTableGenerationId=0, finalTempTableGenerationId=null)]
2024-09-19 08:01:42 destination > INFO sync-operations-2 i.a.i.b.d.t.TyperDeduperUtil(runMigrationsAsync$lambda$12):165 Maybe executing BigqueryAirbyteMetaAndGenerationIdMigration migration for stream poc_one_data_raw.mongodb_from_airbyte_cdc_sit_6083_cloud.
2024-09-19 08:01:42 destination > INFO sync-operations-2 i.a.i.d.b.m.BigqueryAirbyteMetaAndGenerationIdMigration(migrateIfNecessary):43 Skipping airbyte_meta/generation_id migration for poc_one_data_raw.mongodb_from_airbyte_cdc_sit_6083_cloud because the table already has the columns
2024-09-19 08:01:42 destination > INFO main i.a.i.d.b.t.BigQueryDestinationHandler(createDataset):367 Creating dataset if not present airbyte_internal
2024-09-19 08:01:42 destination > INFO main i.a.i.d.b.t.BigQueryDestinationHandler(createDataset):367 Creating dataset if not present poc_one_data_raw
2024-09-19 08:01:43 destination > INFO sync-operations-3 i.a.i.b.d.o.AbstractStreamOperation(prepareStageForNormalSync):79 poc_one_data_raw.mongodb_from_airbyte_cdc_sit_6083_cloud: non-truncate sync. Creating raw table if not exists.
2024-09-19 08:01:44 destination > INFO sync-operations-3 i.a.i.d.b.BigQueryUtils(createPartitionedTableIfNotExists):131 Partitioned table ALREADY EXISTS: GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=airbyte_internal, tableId=poc_one_data_raw_raw__stream_mongodb_from_airbyte_cdc_sit_6083_cloud}}
2024-09-19 08:01:44 destination > INFO sync-operations-3 i.a.i.b.d.o.AbstractStreamOperation(prepareStageForNormalSync):125 poc_one_data_raw.mongodb_from_airbyte_cdc_sit_6083_cloud: non-truncate sync and no temp raw table. Initial raw table status is null.
2024-09-19 08:01:44 destination > INFO sync-operations-3 i.a.i.b.d.o.AbstractStreamOperation(prepareFinalTable):240 Final table does not exist for stream mongodb_from_airbyte_cdc_sit_6083_cloud, creating.
2024-09-19 08:01:45 source > Exceeded the maximum number of bytes per file for schema inference (1000000). Inferring schema from an incomplete set of records.
2024-09-19 08:01:45 destination > ERROR main i.a.c.i.u.ConnectorExceptionUtil(logAllAndThrowFirst):37 Following exceptions occurred during sync initializationjava.util.concurrent.CompletionException: com.google.cloud.bigquery.BigQueryException: Duplicate column name _airbyte_meta in CREATE TABLE at [7:1]
	at io.airbyte.commons.concurrency.CompletableFutures$allOf$1.invoke(CompletableFutures.kt:46)
	at io.airbyte.commons.concurrency.CompletableFutures$allOf$1.invoke(CompletableFutures.kt:31)
	at io.airbyte.commons.concurrency.CompletableFutures.allOf$lambda$1(CompletableFutures.kt:31)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.google.cloud.bigquery.BigQueryException: Duplicate column name _airbyte_meta in CREATE TABLE at [7:1]
	at com.google.cloud.bigquery.Job.reload(Job.java:471)
	at io.airbyte.integrations.destination.bigquery.typing_deduping.BigQueryDestinationHandler.execute(BigQueryDestinationHandler.kt:147)
	at io.airbyte.integrations.destination.bigquery.operation.BigQueryStorageOperation.createFinalTable(BigQueryStorageOperation.kt:131)
	at io.airbyte.integrations.base.destination.operation.AbstractStreamOperation.prepareFinalTable(AbstractStreamOperation.kt:243)
	at io.airbyte.integrations.base.destination.operation.AbstractStreamOperation.<init>(AbstractStreamOperation.kt:67)
	at io.airbyte.integrations.base.destination.operation.StandardStreamOperation.<init>(StandardStreamOperation.kt:22)
	at io.airbyte.integrations.destination.bigquery.BigQueryDestination.getSerializedMessageConsumer$lambda$1(BigQueryDestination.kt:430)
	at io.airbyte.integrations.base.destination.operation.DefaultSyncOperation.createPerStreamOpClients$lambda$4$lambda$3(DefaultSyncOperation.kt:81)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 3 more
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by spm33** [comment]
Leaving this here because this burned me for a while and the only thing that comes up in Google: this is related to chaining syncs.

I just had this happen when I was trying to do a two step sync with a Snowflake destination.

Flow looks something like:
* Connection 1: Source A (Postgres) -> Destination B (Redshift)
* Connection 2: Destination B (as a source) -> Destination C (Snowflake)

When connection 2 ran, it was attempting to sync the _airbyte_* fields that were already added to the tables as part of the Connection 1 sync tracking.

I'm not sure if this type of chaining is a supported use-case or topology, but this is just a temporary requirement for me, so I worked around it for now by just unchecking the _airbyte_* fields from Connection 2's schemas.
