### ISSUE TITLE
[api]  Issue with Source Creation via API vs. UI Testing

### ISSUE THREAD

**Issue by karolur** [airbytehq/airbyte#45940]
### Connector Name

source-shopify

### Connector Version

2.5.2

### What step the error happened?

Configuring a new connector

### Relevant information

Hi Airbyte Support Team,

I'm encountering an issue when testing a newly created source. I am creating the source via the API using the correct parameters. However, when I test this source in the UI, it fails.

Interestingly, when I manually create the source using the exact same parameters directly in the UI, the test is successful. I’ve also tried creating other connectors via the API, and I don’t experience this issue with those connectors.

This issue prevents me from creating any connection with that source. Could you please help me troubleshoot this inconsistency? I would appreciate any insights you can provide.

Edit: This morning when testing the connection i just get this error without any context or logs "An unexpected error occurred. Please report this if the issue persists. (HTTP 500)"

Thanks for your support!

### Relevant log output

```shell
Configuration check failed

Check failed because of an internal error
Internal message: Check failed because of an internal error
Failure origin: airbyte_platform
		at io.airbyte.config.secrets.SecretsHelpers$combineConfig$1.invoke(SecretsHelpers.kt:177)
	at io.airbyte.config.secrets.SecretsHelpers.combineConfig$lambda$2(SecretsHelpers.kt:177)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at io.airbyte.config.secrets.SecretsHelpers.combineConfig(SecretsHelpers.kt:177)
	at io.airbyte.config.secrets.hydration.RealSecretsHydrator.hydrateFromDefaultSecretPersistence(RealSecretsHydrator.kt:21)
	at io.airbyte.config.secrets.SecretsRepositoryReader.hydrateConfigFromDefaultSecretPersistence(SecretsRepositoryReader.kt:60)
	at io.airbyte.workers.ConnectorSecretsHydrator.hydrateConfig(ConnectorSecretsHydrator.kt:33)
	at io.airbyte.workers.CheckConnectionInputHydrator.getHydratedStandardCheckInput(CheckConnectionInputHydrator.kt:13)
	at io.airbyte.workers.temporal.check.connection.CheckConnectionActivityImpl.runWithJobOutput(CheckConnectionActivityImpl.java:207)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.temporal.internal.activity.RootActivityInboundCallsInterceptor$POJOActivityInboundCallsInterceptor.executeActivity(RootActivityInboundCallsInterceptor.java:64)
	at io.temporal.internal.activity.RootActivityInboundCallsInterceptor.execute(RootActivityInboundCallsInterceptor.java:43)
	at io.temporal.internal.activity.ActivityTaskExecutors$BaseActivityTaskExecutor.execute(ActivityTaskExecutors.java:107)
	at io.temporal.internal.activity.ActivityTaskHandlerImpl.handle(ActivityTaskHandlerImpl.java:124)
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handleActivity(ActivityWorker.java:278)
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:243)
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:216)
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:105)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Can you share the payload you're using to create the source using the API?
Also, you can maybe take a look in the Network tabs in the UI and check if you're using the same payload :)

**Comment by karolur** [comment]
Thank you for replying. I was able to solve the issue with your suggestion to check for network tab. I found the difference in the payloads .

Thank you very much
