### ISSUE TITLE
Salesforce connector missing data when using incremental append

### ISSUE THREAD

**Issue by anton-epsagon** [airbytehq/airbyte#4620]
## Enviroment
- **Airbyte version**:  0.26.4-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: docker-compose
- **Source Connector and version**: salesforce 0.2.3
- **Destination Connector and version**: redshift 0.3.9
- **Severity**: High / Critical
- **Step where error happened**: Data exploration

## Current Behavior
I've set up the connector about 2 weeks ago and was pulling data into my redshift. However when starting to build reports upon it we found that there's data missing in our tables when compared to SF, or even another tool's ingestion process.

## Expected Behavior
I'd expect to have all the data that was in SF

## Logs
The only failure I could find was during my Cluster resize, however the missing data is from before that period, so I'd imagine it's not related, I'll paste it and a successful log regardless.
[logs-605-0.log](https://github.com/airbytehq/airbyte/files/6781922/logs-605-0.log)
[logs-155-2.log](https://github.com/airbytehq/airbyte/files/6781923/logs-155-2.log)

## Steps to Reproduce
1. I'm not quite sure since once i ran a full refresh (well, created a new one) the missing data was loaded

## Are you willing to submit a PR?
If time permits and i actually have an idea what to do, sure.

**Comment by marcosmarxm** [comment]
@anton-epsagon in the second log there is a Error probably from Redshift. 
```
2021-06-30 16:17:12 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-06-30 16:17:12 [1;31mERROR[m i.a.i.d.b.BufferedStreamConsumer(close):203 - {} - on close failed.
2021-06-30 16:17:12 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - java.sql.SQLException: [Amazon](500310) Invalid operation: Cannot execute write query because system is in resize mode 
2021-06-30 16:17:12 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - Details: System is in resize mode, and ONLY read-only queries are allowed to execute.;
2021-06-30 16:17:12 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at com.amazon.redshift.client.messages.inbound.ErrorResponse.toErrorException(Unknown Source) ~[redshift-jdbc42-no-awssdk-1.2.51.1078.jar:RedshiftJDBC_1.2.51.1078]
2021-06-30 16:17:12 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at com.amazon.redshift.client.PGMessagingContext.handleErrorResponse(Unknown Source) ~[redshift-jdbc42-no-awssdk-1.2.51.1078.jar:RedshiftJDBC_1.2.51.1078]
2021-06-30 16:17:12 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at com.amazon.redshift.client.PGMessagingContext.handleMessage(Unknown Source) ~[redshift-jdbc42-no-awssdk-1.2.51.1078.jar:RedshiftJDBC_1.2.51.1078]
2021-06-30 16:17:12 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at com.amazon.jdbc.communications.InboundMessagesPipeline.getNextMessageOfClass(Unknown Source) ~[redshift-jdbc42-no-awssdk-1.2.51.1078.jar:RedshiftJDBC_1.2.51.1078]
```

**Comment by anton-epsagon** [comment]
Yes, this was during the cluster resize, but I don't think it's related to the issue since I've had multiple successful runs after that.
![image](https://user-images.githubusercontent.com/80029864/125022146-b2807500-e084-11eb-8626-11ed2029522b.png)

**Comment by sherifnada** [comment]
@anton-epsagon can you give us an idea of what the missing data was? was it custom objects or standard objects? We're trying to recreate this on our end

**Comment by anton-epsagon** [comment]
@sherifnada, mostly missing opportunities and opportunity history rows. At least that's what I was able to notice.

Wasn't able to really differentiate what's missing aside from a few specific rows that tipped me off. The dataset was abit too large to investigate this given the deliverables required of me >_>

**Comment by yevhenii-ldv** [comment]
Hello, @anton-epsagon .
I investigated your request very carefully, and I really managed to miss a certain number of records if I used `Incremental` sync vs `Full Refresh`.
However, this can only work if you specified `start_date` later than some of the entries.
The situation is such that the `Full Refresh` synchronization does not use `start_date` and pulls out all the data on the stream that exists, while the `Incremental` is repelled from `start_date` and further from the `state` values.
Could you make sure that your `start_date` is set correctly for your purposes and run `Incremental` again to make sure everything works correctly?

Please let us know if you have any further questions.

**Comment by sherifnada** [comment]
closing since resolution seems to have been found
