### ISSUE TITLE
[source-planhat] Unable to create a source

### ISSUE THREAD

**Issue by descampsk** [airbytehq/airbyte#46270]
### Connector Name

source-planhat

### Connector Version

0.0.1	

### What step the error happened?

Configuring a new connector

### Relevant information

Just create a new source with Planhat.

Airbyte Helm release 1.0.0.

@natikgadzhi 
For my company, I also created a Planhat connector with the builder which supports incremental sync. Maybe we can put our efforts together to maintain this connector.

### Relevant log output

```shell
TypeError: s.startsWith is not a function
    at ee (http://airbyte/assets/DocumentationPanel-nc1lze43su.js:2:320)
    at oR (http://airbyte/assets/core-klzzp8kfpr.js:38:19551)
    at SB (http://airbyte/assets/core-klzzp8kfpr.js:40:44099)
    at bB (http://airbyte/assets/core-klzzp8kfpr.js:40:39820)
    at Gee (http://airbyte/assets/core-klzzp8kfpr.js:40:39747)
    at ob (http://airbyte/assets/core-klzzp8kfpr.js:40:39597)
    at u8 (http://airbyte/assets/core-klzzp8kfpr.js:40:36709)
    at Gu (http://airbyte/assets/core-klzzp8kfpr.js:38:3287)
    at http://airbyte/assets/core-klzzp8kfpr.js:40:34285
```

### Contribute

- [X] Yes, I want to contribute

**Comment by natikgadzhi** [comment]
Yeah, I can reproduce this on Cloud. Sorry about that! I think this is a docs page problem, let me look into it right away.

**Comment by natikgadzhi** [comment]
Also re: work on the connector together: here's a loom of how you can edit this connector in Connector Builder, and make pull requests agaist it, straight from Builder! https://www.loom.com/share/f3491fef810a4d1d8828dd4bfc60ba62

**Comment by descampsk** [comment]
I will try that thanks :)
