### ISSUE TITLE
[source-google-sheet] ConnectorStateManager initialization failing

### ISSUE THREAD

**Issue by Udit107710** [airbytehq/airbyte#46283]
### Connector Name

source-google-sheet

### Connector Version

0.7.3

### What step the error happened?

During the sync

### Relevant information

Stacktrace attached below

### Relevant log output

```shell
2024-10-01 13:14:45 - INFO - Check succeeded
2024-10-01 13:14:48 - INFO - Running discovery on sheet 1AVwf-as4zq0q21RZe7a-rpnBPFZrlooSZEVb-iEp8Zs
2024-10-01 13:14:56 - INFO - Finished syncing spreadsheet 1AVwf-as4zq0q21RZe7a-rpnBPFZrlooSZEVb-iEp8Zs
2024-10-01 13:14:56 - INFO - ConnectorStateManager.__init__() got an unexpected keyword argument 'stream_instance_map'
Traceback (most recent call last):
  File "/Users/uditchaudhary/Pixis/jarvis/prefect_jobs/google_sheet_sync/.venv-source-google-sheets/bin/source-google-sheets", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/Users/uditchaudhary/Pixis/jarvis/prefect_jobs/google_sheet_sync/.venv-source-google-sheets/lib/python3.11/site-packages/source_google_sheets/run.py", line 15, in run
    launch(source, sys.argv[1:])
  File "/Users/uditchaudhary/Pixis/jarvis/prefect_jobs/google_sheet_sync/.venv-source-google-sheets/lib/python3.11/site-packages/airbyte_cdk/entrypoint.py", line 234, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/Users/uditchaudhary/Pixis/jarvis/prefect_jobs/google_sheet_sync/.venv-source-google-sheets/lib/python3.11/site-packages/airbyte_cdk/entrypoint.py", line 122, in run
    yield from map(AirbyteEntrypoint.airbyte_message_to_string, self.read(source_spec, config, config_catalog, state))
  File "/Users/uditchaudhary/Pixis/jarvis/prefect_jobs/google_sheet_sync/.venv-source-google-sheets/lib/python3.11/site-packages/airbyte_cdk/entrypoint.py", line 164, in read
    for message in self.source.read(self.logger, config, catalog, state):
  File "/Users/uditchaudhary/Pixis/jarvis/prefect_jobs/google_sheet_sync/.venv-source-google-sheets/lib/python3.11/site-packages/source_google_sheets/source.py", line 244, in read
    yield from self._read(logger, config, catalog, state)
  File "/Users/uditchaudhary/Pixis/jarvis/prefect_jobs/google_sheet_sync/.venv-source-google-sheets/lib/python3.11/site-packages/source_google_sheets/source.py", line 166, in _read
    state_manager = ConnectorStateManager(stream_instance_map=stream_instances, state=state or {})
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ConnectorStateManager.__init__() got an unexpected keyword argument 'stream_instance_map'
2024-10-01 13:14:56 - ERROR - Something went wrong in the connector. See the logs for more details.
```

### Contribute

- [X] Yes, I want to contribute

**Comment by natikgadzhi** [comment]
We've made a bunch of updates to google-sheets, tell us if this is still a problem please
