### ISSUE TITLE
[destination-s3] Endpoint not utilized correctly when setting up the destination

### ISSUE THREAD

**Issue by rtyler** [airbytehq/airbyte#46531]
### Connector Name

destination-s3

### Connector Version

 1.2.1

### What step the error happened?

Configuring a new connector

### Relevant information

I cannot figure out when this regression might have happened or if it's only in the validation of the destination, but the Endpoint configuration simply isn't used . Either way, there is no value that can be added to the Endpoint field that is used in the testing of the destination it seems.

This has prevented my test setup (helm install 1.1.0) from connecting to a separate Minio instance.

![image](https://github.com/user-attachments/assets/58fa6a73-80ad-48bf-8f14-5b6d007c8469)

### Relevant log output

```shell
Failed to read the output
Internal message: Failed to read the output of a successful workload 4816b78f-1489-44c1-9060-4b19d5fa9362_f03a7918-de4e-4bb2-af43-497cb0bd2269_0_check
Failure origin: airbyte_platform
Failure type: system_error
```

```
io.airbyte.workers.workload.exception.DocStoreAccessException: Unable to read output for 4816b78f-1489-44c1-9060-4b19d5fa9362_f03a7918-de4e-4bb2-af43-497cb0bd2269_0_check
	at io.airbyte.workers.workload.JobOutputDocStore.read(JobOutputDocStore.kt:27)
	at io.airbyte.workers.sync.WorkloadClient.getConnectorJobOutput(WorkloadClient.kt:77)
	at io.airbyte.workers.temporal.check.connection.CheckConnectionActivityImpl.runWithWorkload(CheckConnectionActivityImpl.java:128)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.temporal.internal.activity.RootActivityInboundCallsInterceptor$POJOActivityInboundCallsInterceptor.executeActivity(RootActivityInboundCallsInterceptor.java:64)
	at io.temporal.internal.activity.RootActivityInboundCallsInterceptor.execute(RootActivityInboundCallsInterceptor.java:43)
	at io.temporal.internal.activity.ActivityTaskExecutors$BaseActivityTaskExecutor.execute(ActivityTaskExecutors.java:107)
	at io.temporal.internal.activity.ActivityTaskHandlerImpl.handle(ActivityTaskHandlerImpl.java:124)
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handleActivity(ActivityWorker.java:278)
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:243)
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:216)
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:105)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: software.amazon.awssdk.services.s3.model.S3Exception: Access Denied. (Service: S3, Status Code: 403, Request ID: 17FBF4B86B737D89, Extended Request ID: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:82)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41)
```
```


### Contribute

- [ ] Yes, I want to contribute

**Comment by rtyler** [comment]
Digging deeper into other destinations, I think this might actually be a helm chart issue in that the logs are not being read from the internal minio, but rather it _seems_ like perhaps it is trying to load logs from S3
