### ISSUE TITLE
[source-datadog] raise ValueError("time data %r does not match format %r" %..)

### ISSUE THREAD

**Issue by VolubleRain1** [airbytehq/airbyte#46549]
[default_workspace_job_319_attempt_1_txt.txt](https://github.com/user-attachments/files/17282316/default_workspace_job_319_attempt_1_txt.txt)
### Connector Name

Datadog

### Connector Version

1.0.6

### What step the error happened?

None

### Relevant information

I'm trying to run the initial sync for the Datadog connector into BigQuery. I'm not able to successfully sync the "logs" schema as it returns the error _time data '' does not match format '%Y-%m-%dT%H:%M:%SZ'_

### Relevant log output

```shell
2024-10-07 16:33:39 destination > ERROR main i.a.c.i.u.ConnectorExceptionHandler(handleException):68 caught exception! io.airbyte.commons.exceptions.TransientErrorException: Some streams were unsuccessful due to a source error. See logs for details.
        at io.airbyte.cdk.integrations.destination.async.AsyncStreamConsumer.close(AsyncStreamConsumer.kt:215) ~[airbyte-cdk-core-0.46.0.jar:?]
        at kotlin.jdk7.AutoCloseableKt.closeFinally(AutoCloseableJVM.kt:48) ~[kotlin-stdlib-2.0.0.jar:2.0.0-release-341]
        at io.airbyte.cdk.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.kt:215) [airbyte-cdk-core-0.46.0.jar:?]
        at io.airbyte.cdk.integrations.base.IntegrationRunner.run(IntegrationRunner.kt:119) [airbyte-cdk-core-0.46.0.jar:?]
        at io.airbyte.cdk.integrations.base.IntegrationRunner.run$default(IntegrationRunner.kt:113) [airbyte-cdk-core-0.46.0.jar:?]
        at io.airbyte.integrations.destination.bigquery.BigQueryDestinationKt.main(BigQueryDestination.kt:566) [io.airbyte.airbyte-integrations.connectors-destination-bigquery.jar:?]
Stack Trace: io.airbyte.commons.exceptions.TransientErrorException: Some streams were unsuccessful due to a source error. See logs for details.
        at io.airbyte.cdk.integrations.destination.async.AsyncStreamConsumer.close(AsyncStreamConsumer.kt:215)
        at kotlin.jdk7.AutoCloseableKt.closeFinally(AutoCloseableJVM.kt:48)
        at io.airbyte.cdk.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.kt:215)
        at io.airbyte.cdk.integrations.base.IntegrationRunner.run(IntegrationRunner.kt:119)
        at io.airbyte.cdk.integrations.base.IntegrationRunner.run$default(IntegrationRunner.kt:113)
        at io.airbyte.integrations.destination.bigquery.BigQueryDestinationKt.main(BigQueryDestination.kt:566)
2024-10-07 16:33:39 replication-orchestrator > Destination finished successfully — exiting read dest...
2024-10-07 16:33:39 replication-orchestrator > readFromDestination: exception caught
io.airbyte.workers.internal.exception.DestinationException: Destination process exited with non-zero exit code 1
        at io.airbyte.workers.general.BufferedReplicationWorker.readFromDestination(BufferedReplicationWorker.java:500) ~[io.airbyte-airbyte-commons-worker-1.1.0.jar:?]
        at io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsync$2(BufferedReplicationWorker.java:215) ~[io.airbyte-airbyte-commons-worker-1.1.0.jar:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
2024-10-07 16:33:39 replication-orchestrator > readFromDestination: done. (writeToDestFailed:false, dest.isFinished:true)
2024-10-07 16:33:39 replication-orchestrator > Closing StateCheckSumCountEventHandler
2024-10-07 16:33:39 replication-orchestrator > sync summary: {
  "status" : "failed",
  "recordsSynced" : 76,
  "bytesSynced" : 11720,
  "startTime" : 1728318759918,
  "endTime" : 1728318819680,
  "totalStats" : {
    "bytesCommitted" : 11720,
    "bytesEmitted" : 11720,
    "destinationStateMessagesEmitted" : 10,
    "destinationWriteEndTime" : 0,
    "destinationWriteStartTime" : 1728318760041,
    "meanSecondsBeforeSourceStateMessageEmitted" : 0,
    "maxSecondsBeforeSourceStateMessageEmitted" : 1,
    "maxSecondsBetweenStateMessageEmittedandCommitted" : 56,
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by btkcodedev** [comment]
Taking this a look
