### ISSUE TITLE
Airbyte not responding via UI or API

### ISSUE THREAD

**Issue by henriquemeloo** [airbytehq/airbyte#46554]
### What happened?

Related issue: https://github.com/airbytehq/airbyte/issues/44833

Airbyte does not respond via UI or via the API.

Temporal logs show errors and warnings like:
```
{"level":"info","ts":"2024-10-07T13:29:15.145Z","msg":"matching client encountered error","service":"frontend","error":"service rate limit exceeded","service-error-type":"serviceerror.ResourceExhausted","logging-call-at":"metric_client.go:219"}
{"level":"info","ts":"2024-10-07T13:29:15.153Z","msg":"history client encountered error","service":"frontend","error":"service rate limit exceeded","service-error-type":"serviceerror.ResourceExhausted","logging-call-at":"metric_client.go:104"}
{"level":"warn","ts":"2024-10-07T13:30:49.145Z","msg":"Per shard per namespace RPS warn limit exceeded","service":"history","shard-id":2,"wf-namespace":"default","rps":65,"logging-call-at":"health_signal_aggregator.go:171"}
{"level":"warn","ts":"2024-10-07T13:30:49.145Z","msg":"Per shard RPS warn limit exceeded","service":"history","shard-id":2,"rps":65,"logging-call-at":"health_signal_aggregator.go:178"}
{"level":"warn","ts":"2024-10-07T13:30:49.146Z","msg":"Per shard per namespace RPS warn limit exceeded","service":"history","shard-id":3,"wf-namespace":"default","rps":115,"logging-call-at":"health_signal_aggregator.go:171"}
{"level":"warn","ts":"2024-10-07T13:31:06.245Z","msg":"Unspecified task queue kind","service":"frontend","wf-task-queue-name":"GET_SPEC","wf-namespace":"default","logging-call-at":"workflow_handler.go:3772"}
```

We had this problem on a Docker deployment  with Airbyte v0.54.0, and after upgrading to Airbyte v1.1.0 with `abctl` this still happens.

### What did you expect to happen?

Airbyte to be functional in this version, with this deployment.

### Abctl Version

<details>

```console
$ abctl version
version: v0.18.0
```

</details>

### Docker Version

<details>

```console
$ docker version
Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:41:00 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:41:00 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.22
  GitCommit:        7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc:
  Version:          1.1.14
  GitCommit:        v1.1.14-0-g2c9f560
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

</details>

### OS Version

<details>

```console
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

</details>

**Comment by henriquemeloo** [comment]
Should I have deleted Temporal databases before the migration? They have grown a bit large.

**Comment by bgroff** [comment]
Possibly, what size instance are you using?

**Comment by henriquemeloo** [comment]
@bgroff Airbyte is running with abctl on a c5a.4xlarge EC2 instance, with external database on a db.t4g.micro RDS instance. The database instance CPU utilization doesn't seem to have peaked above 35% though.

**Comment by bgroff** [comment]
That should be plenty :). I don't think the Temporal db should be breaking the API or UI. Can you try and load the web page with the network tab opened in the developer tools? I am curious if all requests are blocked or if a specific request is getting hung up.

**Comment by henriquemeloo** [comment]
@bgroff the pending request seems to be `/api/v1/workspaces/get`
I'm not sure it has to do with the Temporal database. I mentioned it because deleting them [seems to be a workaround](https://github.com/airbytehq/airbyte/issues/30691#issuecomment-1745305229) to the "service rate limit exceeded" error...

**Comment by henriquemeloo** [comment]
Does increasing the number of Temporal replicas help with this? If not, is there an easy way to fine tune the values in Temporal's `dynamicconfig/development.yaml` file? Do we have to customize Airbyte's Helm chart?

**Comment by bgroff** [comment]
Were you able to resolve this issue?

**Comment by henriquemeloo** [comment]
@bgroff not really. Deploying on EKS with 2 Temporal replicas seems to have helped, and Airbyte is not stuck anymore and is accessible, but I am still getting these logs in the cron deployment:
```
2024-12-10 13:31:52,128 [scheduled-executor-thread-4]	ERROR	i.m.s.DefaultTaskExceptionHandler(handle):47 - Error invoking scheduled task for bean [io.airbyte.cron.jobs.SelfHealTemporalWorkflows@757950e4] RESOURCE_EXHAUSTED: namespace rate limit exceeded
io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: namespace rate limit exceeded
    at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:268)
    at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:249)
    at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:167)
    at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.listClosedWorkflowExecutions(WorkflowServiceGrpc.java:4620)
    at io.airbyte.commons.temporal.WorkflowServiceStubsWrapped.lambda$blockingStubListClosedWorkflowExecutions$0(WorkflowServiceStubsWrapped.java:47)
    at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
    at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
    at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
    at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
    at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
    at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112)
    at io.airbyte.commons.temporal.RetryHelper.withRetries(RetryHelper.java:60)
    at io.airbyte.commons.temporal.WorkflowServiceStubsWrapped.withRetries(WorkflowServiceStubsWrapped.java:67)
    at io.airbyte.commons.temporal.WorkflowServiceStubsWrapped.blockingStubListClosedWorkflowExecutions(WorkflowServiceStubsWrapped.java:47)
    at io.airbyte.commons.temporal.TemporalClient.fetchClosedWorkflowsByStatus(TemporalClient.java:139)
    at io.airbyte.commons.temporal.TemporalClient.restartClosedWorkflowByStatus(TemporalClient.java:117)
    at io.airbyte.cron.jobs.SelfHealTemporalWorkflows.cleanTemporal(SelfHealTemporalWorkflows.java:42)
    at io.airbyte.cron.jobs.$SelfHealTemporalWorkflows$Definition$Exec.dispatch(Unknown Source)
    at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:456)
    at io.micronaut.inject.DelegatingExecutableMethod.invoke(DelegatingExecutableMethod.java:86)
    at io.micronaut.context.bind.DefaultExecutableBeanContextBinder$ContextBoundExecutable.invoke(DefaultExecutableBeanContextBinder.java:152)
    at io.micronaut.scheduling.processor.ScheduledMethodProcessor.lambda$scheduleTask$2(ScheduledMethodProcessor.java:160)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
    at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
    at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.base/java.lang.Thread.run(Thread.java:1583)
```
and Temporal configurations are not easily accessible without creating a custom Helm chart.

**Comment by bgroff** [comment]
Are there lots of pods that are not cleaned up? `namespace rate limit exceeded` is a very strange error.

**Comment by henriquemeloo** [comment]
@bgroff I think this is about Temporal namespace, not Kubernetes (see https://github.com/airbytehq/airbyte/issues/30691). That fix will not exactly work for me though since we cannot change Temporal configuration values in the Airbyte Helm chart.

**Comment by northonheld** [comment]
Hello @henriquemeloo.

I had the same problem and the Temporal helm chart doesn't really give you the option of setting values. However, in the latest version (1.4.0) add more generous limits have been added.

https://github.com/airbytehq/airbyte-platform/commit/68480528a7e7931338b48f2fd03b5393d8279076

After the update we no longer had this problem with the airbyte-cron. Now everything works like a Swiss clock
