### ISSUE TITLE
Error 500 on /streams api endpoints

### ISSUE THREAD

**Issue by alenoir** [airbytehq/airbyte#46667]
### What happened?

Environnement : Self hosted

I have a 500 error when I try to get streams from API.
`{baseurl}/api/public/v1/streams?sourceId={sourceId}&destinationId={destinationId}`

Response : 
```json
{
    "status": 500,
    "type": "https://reference.airbyte.com/reference/errors",
    "title": "unexpected-problem",
    "detail": "An unexpected problem has occurred. If this is an error that needs to be addressed, please submit a pull request or github issue.",
    "documentationUrl": null,
    "data": {
        "message": "Something went wrong in the connector. logs:Something went wrong in the connector. See the logs for more details."
    }
}
```

Server logs
```
 ERROR i.a.c.s.e.p.AbstractThrowableProblemHandler(handle):30 - Throwable Problem Handler caught exception: 
io.airbyte.api.problems.throwable.generated.UnexpectedProblem: An unexpected problem has occurred. If this is an error that needs to be addressed, please submit a pull request or github issue.
        at io.airbyte.server.apis.publicapi.services.SourceServiceImpl.getSourceSchema(SourceService.kt:215) ~[io.airbyte-airbyte-server-1.1.0.jar:?]
        at io.airbyte.server.apis.publicapi.controllers.StreamsController.getStreamProperties$lambda$1(StreamsController.kt:76) ~[io.airbyte-airbyte-server-1.1.0.jar:?]
        at io.airbyte.server.apis.publicapi.apiTracking.TrackingHelper.callWithTracker(TrackingHelper.kt:107) ~[io.airbyte-airbyte-server-1.1.0.jar:?]
        at io.airbyte.server.apis.publicapi.controllers.StreamsController.getStreamProperties(StreamsController.kt:74) ~[io.airbyte-airbyte-server-1.1.0.jar:?]
        at io.airbyte.server.apis.publicapi.controllers.$StreamsController$Definition$Exec.dispatch(Unknown Source) ~[io.airbyte-airbyte-server-1.1.0.jar:?]
        at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invokeUnsafe(AbstractExecutableMethodsDefinition.java:461) ~[micronaut-inject-4.6.5.jar:4.6.5]
        at io.micronaut.context.DefaultBeanContext$BeanContextUnsafeExecutionHandle.invokeUnsafe(DefaultBeanContext.java:4350) ~[micronaut-inject-4.6.5.jar:4.6.5]
        at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:237) ~[micronaut-router-4.6.5.jar:4.6.5]
        at io.micronaut.web.router.DefaultUriRouteMatch.execute(DefaultUriRouteMatch.java:38) ~[micronaut-router-4.6.5.jar:4.6.5]
        at io.micronaut.http.server.RouteExecutor.executeRouteAndConvertBody(RouteExecutor.java:498) ~[micronaut-http-server-4.6.5.jar:4.6.5]
        at io.micronaut.http.server.RouteExecutor.lambda$callRoute$5(RouteExecutor.java:475) ~[micronaut-http-server-4.6.5.jar:4.6.5]
        at io.micronaut.core.execution.ExecutionFlow.lambda$async$1(ExecutionFlow.java:87) ~[micronaut-core-4.6.5.jar:4.6.5]
        at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211) ~[micronaut-core-4.6.5.jar:4.6.5]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```console

### What did you expect to happen?

List of streams

### Abctl Version

<details>

```console
$ abctl version
version: v0.18.1
```

</details>

### Docker Version

<details>

```console
$ docker version
Client: Docker Engine - Community
 Version:           26.1.4
 API version:       1.45
 Go version:        go1.21.11
 Git commit:        5650f9b
 Built:             Wed Jun  5 11:29:15 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.1.4
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       de5c9cf
  Built:            Wed Jun  5 11:29:15 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.33
  GitCommit:        d2d58213f83a351ca8f528a95fbd145f5654e957
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0```

</details>


### OS Version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

</details>

**Comment by alenoir** [comment]
I found the origin of my bug.
Before getting any streams, I updated with PUT the associated source without the `custom_queries_array` field.
This modification causes the Source to error and other calls to this source to fail.

When I add this field or make a patch, everything is fine. 
I think there's been a change to this because I didn't have this problem before. 
To improve things, can we put a 400 on the source PUT if the payload isn't right?
