### ISSUE TITLE
Error Syncing between Hubspot to BigQuery

### ISSUE THREAD

**Issue by wallies** [airbytehq/airbyte#4779]
## Enviroment
- **Airbyte version**:  v0.27.2-alpha
- **OS Version / Instance**: GCP
- **Deployment**: GKE
- **Source Connector and version**: Hubspot 0.1.5
- **Destination Connector and version**: BigQuery 0.3.7
- **Severity**: Medium
- **Step where error happened**: Sync Job

## Current Behavior
Airbyte syncs the source, but then fails to parse some values for bigquery gets a lot of these errors
Bad double value: true
Looks very similiar to this https://github.com/airbytehq/airbyte/issues/1904

## Expected Behavior
Sync should work fine, as it works fine with bigquery denormalised destination, so issue must be in the sql

**Comment by cgardens** [comment]
slack convo: https://airbytehq.slack.com/archives/C019WEENQRM/p1626647144151000

**Comment by cgardens** [comment]
logs.
[logs-181-2.txt](https://github.com/airbytehq/airbyte/files/6842577/logs-181-2.txt)

**Comment by gaart** [comment]
@wallies

We just merged this bug fix into master and released a new version of the connector. 

Upgrade your connector to version 0.1.7 and get started. To upgrade your connector version, go to the admin panel in the left hand side of the UI, find this connector in the list, and input the latest connector version. 

Please let us know if you have any further questions. 

Enjoy!

**Comment by wallies** [comment]
@gaart thanks. upgraded only got a single error 

```

2021-08-03 21:50:28 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Starting syncing SourceHubspot
2021-08-03 21:50:28 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Syncing campaigns stream
2021-08-03 21:50:48 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Syncing companies stream
2021-08-03 21:50:48 WARN () DefaultAirbyteStreamFactory(internalLog):109 - Could not cast  to <class 'float'>
2021-08-03 21:50:48 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - Encountered an exception while reading stream SourceHubspot
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/source_hubspot/api.py", line 281, in _cast_value
    casted_value = target_type(field_value)
ValueError: could not convert string to float: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/base_python/source.py", line 88, in read
    yield from self._read_stream(logger=logger, client=client, configured_stream=configured_stream, state=total_state)
  File "/usr/local/lib/python3.7/site-packages/base_python/source.py", line 107, in _read_stream
    for record in client.read_stream(configured_stream.stream):
  File "/usr/local/lib/python3.7/site-packages/base_python/client.py", line 166, in read_stream
    for message in method(fields=fields):
  File "/usr/local/lib/python3.7/site-packages/source_hubspot/api.py", line 506, in list
    yield from self._flat_associations(generator)
  File "/usr/local/lib/python3.7/site-packages/source_hubspot/api.py", line 521, in _flat_associations
    for record in records:
  File "/usr/local/lib/python3.7/site-packages/source_hubspot/api.py", line 369, in read
    yield from self._filter_dynamic_fields(self._filter_old_records(self._transform(self._read(getter, params))))
  File "/usr/local/lib/python3.7/site-packages/source_hubspot/api.py", line 254, in _filter_dynamic_fields
    for record in records:
  File "/usr/local/lib/python3.7/site-packages/source_hubspot/api.py", line 327, in _filter_old_records
    for record in records:
  File "/usr/local/lib/python3.7/site-packages/source_hubspot/api.py", line 310, in _transform
    record = self._cast_record_fields_if_needed(record)
  File "/usr/local/lib/python3.7/site-packages/source_hubspot/api.py", line 303, in _cast_record_fields_if_needed
    record["properties"][field_name] = self._cast_value(declared_field_types, field_name, field_value)
  File "/usr/local/lib/python3.7/site-packages/source_hubspot/api.py", line 284, in _cast_value
    logger.warn(e)
  File "/usr/local/lib/python3.7/site-packages/base_python/logger.py", line 61, in warn
    self.log("WARN", message)
  File "/usr/local/lib/python3.7/site-packages/base_python/logger.py", line 46, in log
    log_record = AirbyteLogMessage(level=level, message=message)
  File "pydantic/main.py", line 346, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AirbyteLogMessage
message
  str type expected (type=type_error.str)

2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 - Traceback (most recent call last):
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/source_hubspot/api.py", line 281, in _cast_value
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -     casted_value = target_type(field_value)
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 - ValueError: could not convert string to float: 
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 - 
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 - During handling of the above exception, another exception occurred:
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 - 
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 - Traceback (most recent call last):
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/bin/base-python", line 8, in <module>
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -     sys.exit(main())
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/base_python/entrypoint.py", line 135, in main
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -     launch(source, sys.argv[1:])
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/base_python/entrypoint.py", line 120, in launch
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -     AirbyteEntrypoint(source).start(args)
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/base_python/entrypoint.py", line 111, in start
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -     for message in generator:
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/base_python/source.py", line 88, in read
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -     yield from self._read_stream(logger=logger, client=client, configured_stream=configured_stream, state=total_state)
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/base_python/source.py", line 107, in _read_stream
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -     for record in client.read_stream(configured_stream.stream):
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/base_python/client.py", line 166, in read_stream
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -     for message in method(fields=fields):
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/source_hubspot/api.py", line 506, in list
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -     yield from self._flat_associations(generator)
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/source_hubspot/api.py", line 521, in _flat_associations
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -     for record in records:
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/source_hubspot/api.py", line 369, in read
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -     yield from self._filter_dynamic_fields(self._filter_old_records(self._transform(self._read(getter, params))))
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/source_hubspot/api.py", line 254, in _filter_dynamic_fields
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -     for record in records:
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/source_hubspot/api.py", line 327, in _filter_old_records
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -     for record in records:
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/source_hubspot/api.py", line 310, in _transform
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -     record = self._cast_record_fields_if_needed(record)
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/source_hubspot/api.py", line 303, in _cast_record_fields_if_needed
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -     record["properties"][field_name] = self._cast_value(declared_field_types, field_name, field_value)
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/source_hubspot/api.py", line 284, in _cast_value
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -     logger.warn(e)
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/base_python/logger.py", line 61, in warn
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -     self.log("WARN", message)
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/base_python/logger.py", line 46, in log
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -     log_record = AirbyteLogMessage(level=level, message=message)
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -   File "pydantic/main.py", line 346, in pydantic.main.BaseModel.__init__
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 - pydantic.error_wrappers.ValidationError: 1 validation error for AirbyteLogMessage
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 - message
2021-08-03 21:50:48 ERROR () LineGobbler(voidCall):85 -   str type expected (type=type_error.str)
2021-08-03 21:51:19 INFO () KubePodProcess(getReturnCode):616 - Exit code for pod source-hubspot-worker-17-0-bympc is 1
2021-08-03 21:51:19 INFO () KubePodProcess(exitValue):631 - Closed all resources for pod source-hubspot-worker-17-0-bympc
2021-08-03 21:51:19 INFO () DefaultReplicationWorker(run):141 - Source thread complete.
```

**Comment by wallies** [comment]
@cgardens @gaart Ive since tested this with 0.1.8 version of hubspot and it fails like the original error did with Bad double values
