### ISSUE TITLE
JIRA connect calling deprecated endpoint /field/{field name}/context

### ISSUE THREAD

**Issue by bajolly** [airbytehq/airbyte#4793]
## Enviroment
- **Airbyte version**:  0.27.3-alpha
- **OS Version / Instance**: Ubuntu 20.04.2 LTS
- **Deployment**:  Docker local machine
- **Source Connector and version**: 
```
{
    "baseUrl": "https://jollyworks.atlassian.net",
    "version": "1001.0.0-SNAPSHOT",
    "versionNumbers": [
        1001,
        0,
        0
    ],
    "deploymentType": "Cloud",
    "buildNumber": 100168,
    "buildDate": "2021-07-15T08:27:45.000-0500",
    "scmInfo": "7af8a0b78232236c8497240c18a3e70dd9fe80e4",
    "serverTitle": "Jira",
    "defaultLocale": {
        "locale": "en_US"
    }
}
```
- **Destination Connector and version**: NA
- **Severity**: Low
- **Step where error happened**: Sync job

## Current Behavior
When syncing from the Jira Cloud Rest Api  the context endpoint  called witch cannot be found.  This appears to only happen for `customfield_10029`

`GET /rest/api/3/field/{fieldId}/context`

## Expected Behavior
the api call returns with 200 OK or skip if the url doesn't exist and continue processing (?)

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```
2021-07-15 14:22:46 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - Encountered an exception while reading stream SourceJira
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 110, in read
    logger=logger, stream_instance=stream_instance, configured_stream=configured_stream, connector_state=connector_state
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 135, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 181, in _read_full_refresh
    for record in records:
  File "/airbyte/integration_code/source_jira/streams.py", line 230, in read_records
    yield from super().read_records(stream_slice={"field_id": field["id"]}, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 228, in read_records
    response = self._send_request(request)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 204, in _send_request
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://jollyworks.atlassian.net/rest/api/3/field/customfield_10029/context

2021-07-15 14:22:46 ERROR () LineGobbler(voidCall):85 - Traceback (most recent call last):
2021-07-15 14:22:46 ERROR () LineGobbler(voidCall):85 -   File "/airbyte/integration_code/main.py", line 33, in <module>
2021-07-15 14:22:46 ERROR () LineGobbler(voidCall):85 -     launch(source, sys.argv[1:])
2021-07-15 14:22:46 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 117, in launch
2021-07-15 14:22:46 ERROR () LineGobbler(voidCall):85 -     for message in source_entrypoint.run(parsed_args):
2021-07-15 14:22:46 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 108, in run
2021-07-15 14:22:46 ERROR () LineGobbler(voidCall):85 -     for message in generator:
2021-07-15 14:22:46 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 114, in read
2021-07-15 14:22:46 ERROR () LineGobbler(voidCall):85 -     raise e
2021-07-15 14:22:46 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 110, in read
2021-07-15 14:22:46 ERROR () LineGobbler(voidCall):85 -     logger=logger, stream_instance=stream_instance, configured_stream=configured_stream, connector_state=connector_state
2021-07-15 14:22:46 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 135, in _read_stream
2021-07-15 14:22:46 ERROR () LineGobbler(voidCall):85 -     for record in record_iterator:
2021-07-15 14:22:46 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 181, in _read_full_refresh
2021-07-15 14:22:46 ERROR () LineGobbler(voidCall):85 -     for record in records:
2021-07-15 14:22:46 ERROR () LineGobbler(voidCall):85 -   File "/airbyte/integration_code/source_jira/streams.py", line 230, in read_records
2021-07-15 14:22:46 ERROR () LineGobbler(voidCall):85 -     yield from super().read_records(stream_slice={"field_id": field["id"]}, **kwargs)
2021-07-15 14:22:46 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 228, in read_records
2021-07-15 14:22:46 ERROR () LineGobbler(voidCall):85 -     response = self._send_request(request)
2021-07-15 14:22:46 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
2021-07-15 14:22:46 ERROR () LineGobbler(voidCall):85 -     ret = target(*args, **kwargs)
2021-07-15 14:22:46 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
2021-07-15 14:22:46 ERROR () LineGobbler(voidCall):85 -     ret = target(*args, **kwargs)
2021-07-15 14:22:46 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 204, in _send_request
2021-07-15 14:22:46 ERROR () LineGobbler(voidCall):85 -     response.raise_for_status()
2021-07-15 14:22:46 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
2021-07-15 14:22:46 ERROR () LineGobbler(voidCall):85 -     raise HTTPError(http_error_msg, response=self)
2021-07-15 14:22:46 ERROR () LineGobbler(voidCall):85 - requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://jollyworks.atlassian.net/rest/api/3/field/customfield_10029/context

```

</details>

## Steps to Reproduce
1. Create a Jira Cloud NextGen project 

This may not be reproducible and only apply to "next gen" projects that were created during the period when you could choose between "next gen" and "classic" templates.  It does not appear that you have that choice anymore.

I have in my jira integration "classic", "next gen" and ""current for lack of a better word" templates all three use different custom fields to define Story Points.

field/customfield_10028/context  returns 200 response code with expected data
field/customfield_10029/context  returns 404 response code
field/customfield_10016/context returns 200 response with expected data

```
    {
        "id": "customfield_10028",
        "key": "customfield_10028",
        "name": "Story Points",
        "untranslatedName": "Story Points",
        "custom": true,
        "orderable": true,
        "navigable": true,
        "searchable": true,
        "clauseNames": [
            "cf[10028]",
            "Story Points",
            "Story Points[Number]"
        ],
        "schema": {
            "type": "number",
            "custom": "com.atlassian.jira.plugin.system.customfieldtypes:float",
            "customId": 10028
        }
    },
    {
        "id": "customfield_10029",
        "key": "customfield_10029",
        "name": "Story Point",
        "untranslatedName": "Story Point",
        "custom": true,
        "orderable": true,
        "navigable": true,
        "searchable": true,
        "clauseNames": [
            "cf[10029]",
            "Story Point",
            "Story Point[Number]"
        ],
        "scope": {
            "type": "PROJECT",
            "project": {
                "id": "10002"
            }
        },
        "schema": {
            "type": "number",
            "custom": "com.atlassian.jira.plugin.system.customfieldtypes:float",
            "customId": 10029
        }
    },
    {
        "id": "customfield_10016",
        "key": "customfield_10016",
        "name": "Story point estimate",
        "untranslatedName": "Story point estimate",
        "custom": true,
        "orderable": true,
        "navigable": true,
        "searchable": true,
        "clauseNames": [
            "cf[10016]",
            "Story point estimate"
        ],
        "schema": {
            "type": "number",
            "custom": "com.pyxis.greenhopper.jira:jsw-story-points",
            "customId": 10016
        }
    },
```

## Are you willing to submit a PR?

Yes I will need to do some more testing of the different currently available templates to see if any contain "customfield_10029" "Story Point" field.  Then propose a solution.

**Comment by bajolly** [comment]
update to include stack trace in log.

**Comment by quorak** [comment]
Hey there, 
I ran into the same problem. After Some [googeling](https://community.developer.atlassian.com/t/get-custom-field-contexts-not-found-returned/48408/2) it turns out that the endpoint only works for classic projects. Confirmed by atlassian staff. Maybe this helps for the resolution. I had to deactivate this table.
