### ISSUE TITLE
Pipedrive Source Normalization Error

### ISSUE THREAD

**Issue by cnpatric** [airbytehq/airbyte#4828]
## Enviroment
- **Airbyte version**: 0.27.3-alpha
- **OS Version / Instance**: Ubuntu 18.04
- **Deployment**: Docker
- **Source Connector and version**: Pipedrive 0.1.0
- **Destination Connector and version**: BigQuery 0.3.7
- **Severity**:  High
- **Step where error happened**: Setup Connection with Pipedrive and BigQuery and have a deal with a float in pipedrive
## Current Behavior

Syncjob fails with 

2021-07-19 14:37:11 INFO () LineGobbler(voidCall):85 - Database Error in model deals (models/generated/airbyte_tables/airbyte_pipedrive/deals.sql)
2021-07-19 14:37:11 INFO () LineGobbler(voidCall):85 -   Bad int64 value: 179.98
2021-07-19 14:37:11 INFO () LineGobbler(voidCall):85 -   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/airbyte_pipedrive/deals.sql

## Expected Behavior

Normalize floats too.

## Logs
<details>
<summary>LOG</summary> 

```

	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:154) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73) ~[temporal-sdk-1.0.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: io.airbyte.workers.WorkerException: Normalization Failed.
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:69) ~[io.airbyte-airbyte-workers-0.27.3-alpha.jar:?]
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:36) ~[io.airbyte-airbyte-workers-0.27.3-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:146) ~[io.airbyte-airbyte-workers-0.27.3-alpha.jar:?]
	... 1 more
Caused by: io.airbyte.workers.WorkerException: Normalization Failed.
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:66) ~[io.airbyte-airbyte-workers-0.27.3-alpha.jar:?]
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:36) ~[io.airbyte-airbyte-workers-0.27.3-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:146) ~[io.airbyte-airbyte-workers-0.27.3-alpha.jar:?]
	... 1 more
	Suppressed: io.airbyte.workers.WorkerException: Normalization process wasn't successful
		at io.airbyte.workers.normalization.DefaultNormalizationRunner.close(DefaultNormalizationRunner.java:151) ~[io.airbyte-airbyte-workers-0.27.3-alpha.jar:?]
		at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:60) ~[io.airbyte-airbyte-workers-0.27.3-alpha.jar:?]
		at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:36) ~[io.airbyte-airbyte-workers-0.27.3-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:146) ~[io.airbyte-airbyte-workers-0.27.3-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:832) [?:?]

```

</details>

**Comment by cnpatric** [comment]
I don't really know which field is causing this unfortunately.

**Comment by gaart** [comment]
@cnpatric 

We just merged this fix into master and released a new version of the connector. 

Upgrade your connector to version 0.1.2 and get started. To upgrade your connector version, go to the admin panel in the left hand side of the UI, find this connector in the list, and input the latest connector version. 

Please let us know if you have any further questions. 

Enjoy!
