### ISSUE TITLE
[source-mysql] Sync fails upon encountering `ALTER USER DISCARD OLD PASSWORD` statement in binlog

### ISSUE THREAD

**Issue by biased-badger** [airbytehq/airbyte#48497]
### Connector Name

source-mysql

### Connector Version

3.7.3

### What step the error happened?

During the sync

### Relevant information

The sync from MySQL to BigQuery is failing when `ALTER USER 'user'@'%' DISCARD OLD PASSWORD` is encountered in the binlog. I got this error several times and although it can be solved with full refresh, it is not convenient.
Maybe this statement should be just ignored as it doesn't affect the synced database/tables?

### Relevant log output

```shell
Caused by: io.debezium.DebeziumException: Error processing binlog event
        ... 7 more
Caused by: io.debezium.text.ParsingException: DDL statement couldn't be parsed. Please open a Jira issue with the statement 'ALTER USER 'user'@'%' DISCARD OLD PASSWORD'
mismatched input 'DISCARD' expecting {<eof>, '-'}
        at io.debezium.antlr.ParsingErrorListener.syntaxError(ParsingErrorListener.java:43)
        at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
        at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:543)
        at org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMismatch(DefaultErrorStrategy.java:327)
        at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:139)
        at io.debezium.ddl.parser.mysql.generated.MySqlParser.root(MySqlParser.java:1018)
        at io.debezium.connector.mysql.antlr.MySqlAntlrDdlParser.parseTree(MySqlAntlrDdlParser.java:82)
        at io.debezium.connector.mysql.antlr.MySqlAntlrDdlParser.parseTree(MySqlAntlrDdlParser.java:49)
        at io.debezium.antlr.AntlrDdlParser.parse(AntlrDdlParser.java:76)
        at io.debezium.connector.binlog.BinlogDatabaseSchema.parseDdl(BinlogDatabaseSchema.java:311)
        at io.debezium.connector.binlog.BinlogDatabaseSchema.parseStreamingDdl(BinlogDatabaseSchema.java:258)
        at io.debezium.connector.binlog.BinlogStreamingChangeEventSource.handleQueryEvent(BinlogStreamingChangeEventSource.java:726)
        at io.debezium.connector.binlog.BinlogStreamingChangeEventSource.lambda$execute$5(BinlogStreamingChangeEventSource.java:179)
        at io.debezium.connector.binlog.BinlogStreamingChangeEventSource.handleEvent(BinlogStreamingChangeEventSource.java:559)
        ... 6 more
Caused by: org.antlr.v4.runtime.InputMismatchException
        at org.antlr.v4.runtime.DefaultErrorStrategy.sync(DefaultErrorStrategy.java:270)
        at io.debezium.ddl.parser.mysql.generated.MySqlParser.root(MySqlParser.java:1001)
        ... 14 more
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by biased-badger** [comment]
@marcosmarxm Yep, everything happens exactly as you wrote

**Comment by theyueli** [comment]
The error message suggests a possible Debezium bug, will raise this issue with their community.

**Comment by theyueli** [comment]
another approach would be for us to skip such unsupported DDL by setting our Debezium property:

```
schema.history.internal.skip.unparseable.ddl: true
```

**Comment by theyueli** [comment]
hi @biased-badger, thanks for reporting the issue. 

Currently we are in progress of rolling out a new source-mysql connector using the latest bulk extract CDK. The PR by @burakku above fixes this issue in the new CDK, which will be brought only to the new source-mysql. 

Since we haven't released it yet, if you would like to have a try, we could send you a tag for our release candidate. Please let us know. Thank you!

**Comment by biased-badger** [comment]
Hi @theyueli 👋 

Sure, I'd be happy to help and test the new connector! That said, I'm a bit busy at the moment, so it could take a week or two.
