### ISSUE TITLE
[source - bing ads] Getting error testing bing ads created by Terraform: Workload failed, source: workload-launcher

### ISSUE THREAD

**Issue by cbuckle1** [airbytehq/airbyte#48739]
### Connector Name

source - bing ads

### Connector Version

2.8.3

### What step the error happened?

Configuring a new connector

### Relevant information

Error happens when I test the source from the GUI, but all the values have been tested in Bing Ads and are correct. No issue when creating from Terraform, just when testing.

Configuration check failed
Workload failed, source: workload-launcher

### Relevant log output

```shell
Internal message: io.airbyte.workload.launcher.pipeline.stages.model.StageError: java.lang.RuntimeException: That secret was not found in the store! Coordinate: airbyte_workspace_30f58c2f-8f66-4976-8bde-a53ae6303e9a_secret_1851eeb6-0cb1-4072-82d2-40e5f166f880_v1 at io.airbyte.workload.launcher.pipeline.stages.model.Stage.apply(Stage.kt:46) at io.airbyte.workload.launcher.pipeline.stages.BuildInputStage.apply(BuildInputStage.kt:58) at io.airbyte.workload.launcher.pipeline.stages.$BuildInputStage$Definition$Intercepted.$$access$$apply(Unknown Source) at io.airbyte.workload.launcher.pipeline.stages.$BuildInputStage$Definition$Exec.dispatch(Unknown Source) at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:456) at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:134) at io.airbyte.metrics.interceptors.InstrumentInterceptorBase.doIntercept(InstrumentInterceptorBase.kt:61) at io.airbyte.metrics.interceptors.InstrumentInterceptorBase.intercept(InstrumentInterceptorBase.kt:44) at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:143) at io.airbyte.workload.launcher.pipeline.stages.$BuildInputStage$Definition$Intercepted.apply(Unknown Source) at io.airbyte.workload.launcher.pipeline.stages.BuildInputStage.apply(BuildInputStage.kt:39) at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132) at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158) at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2571) at reactor.core.publisher.MonoFlatMap$FlatMapMain.request(MonoFlatMap.java:194) at reactor.core.publisher.MonoFlatMap$FlatMapMain.request(MonoFlatMap.java:194) at reactor.core.publisher.MonoFlatMap$FlatMapMain.request(MonoFlatMap.java:194) at reactor.core.publisher.MonoFlatMap$FlatMapMain.request(MonoFlatMap.java:194) at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2367) at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onSubscribe(FluxOnErrorResume.java:74) at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:117) at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:117) at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:117) at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:117) at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:193) at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53) at reactor.core.publisher.Mono.subscribe(Mono.java:4560) at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126) at reactor.core.scheduler.ImmediateScheduler$ImmediateSchedulerWorker.schedule(ImmediateScheduler.java:84) at reactor.core.publisher.MonoSubscribeOn.subscribeOrReturn(MonoSubscribeOn.java:55) at reactor.core.publisher.Mono.subscribe(Mono.java:4560) at reactor.core.publisher.Mono.subscribeWith(Mono.java:4642) at reactor.core.publisher.Mono.subscribe(Mono.java:4403) at io.airbyte.workload.launcher.pipeline.LaunchPipeline.accept(LaunchPipeline.kt:50) at io.airbyte.workload.launcher.pipeline.consumer.LauncherMessageConsumer.consume(LauncherMessageConsumer.kt:28) at io.airbyte.workload.launcher.pipeline.consumer.LauncherMessageConsumer.consume(LauncherMessageConsumer.kt:12) at io.airbyte.commons.temporal.queue.QueueActivityImpl.consume(Internal.kt:87) at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) at java.base/java.lang.reflect.Method.invoke(Method.java:580) at io.temporal.internal.activity.RootActivityInboundCallsInterceptor$POJOActivityInboundCallsInterceptor.executeActivity(RootActivityInboundCallsInterceptor.java:64) at io.temporal.internal.activity.RootActivityInboundCallsInterceptor.execute(RootActivityInboundCallsInterceptor.java:43) at io.temporal.common.interceptors.ActivityInboundCallsInterceptorBase.execute(ActivityInboundCallsInterceptorBase.java:39) at io.temporal.opentracing.internal.OpenTracingActivityInboundCallsInterceptor.execute(OpenTracingActivityInboundCallsInterceptor.java:78) at io.temporal.internal.activity.ActivityTaskExecutors$BaseActivityTaskExecutor.execute(ActivityTaskExecutors.java:107) at io.temporal.internal.activity.ActivityTaskHandlerImpl.handle(ActivityTaskHandlerImpl.java:124) at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handleActivity(ActivityWorker.java:278) at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:243) at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:216) at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:105) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) at java.base/java.lang.Thread.run(Thread.java:1583) Caused by: java.lang.RuntimeException: That secret was not found in the store! Coordinate: airbyte_workspace_30f58c2f-8f66-4976-8bde-a53ae6303e9a_secret_1851eeb6-0cb1-4072-82d2-40e5f166f880_v1 at io.airbyte.config.secrets.SecretsHelpers.getOrThrowSecretValue(SecretsHelpers.kt:288) at io.airbyte.config.secrets.SecretsHelpers.combineConfig(SecretsHelpers.kt:173) at io.airbyte.config.secrets.SecretsHelpers$combineConfig$1.invoke(SecretsHelpers.kt:183) at io.airbyte.config.secrets.SecretsHelpers$combineConfig$1.invoke(SecretsHelpers.kt:177) at io.airbyte.config.secrets.SecretsHelpers.combineConfig$lambda$2(SecretsHelpers.kt:177) at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) at io.airbyte.config.secrets.SecretsHelpers.combineConfig(SecretsHelpers.kt:177) at io.airbyte.config.secrets.hydration.RealSecretsHydrator.hydrateFromDefaultSecretPersistence(RealSecretsHydrator.kt:21) at io.airbyte.config.secrets.SecretsRepositoryReader.hydrateConfigFromDefaultSecretPersistence(SecretsRepositoryReader.kt:60) at io.airbyte.workers.ConnectorSecretsHydrator.hydrateConfig(ConnectorSecretsHydrator.kt:33) at io.airbyte.workers.CheckConnectionInputHydrator.getHydratedStandardCheckInput(CheckConnectionInputHydrator.kt:13) at io.airbyte.workload.launcher.pipeline.stages.BuildInputStage.buildPayload(BuildInputStage.kt:90) at io.airbyte.workload.launcher.pipeline.stages.BuildInputStage.applyStage(BuildInputStage.kt:62) at io.airbyte.workload.launcher.pipeline.stages.BuildInputStage.applyStage(BuildInputStage.kt:39) at io.airbyte.workload.launcher.pipeline.stages.model.Stage.apply(Stage.kt:42) ... 51 more
Failure origin: airbyte_platform
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
It looks a platform issue related to secrets. Can you share what platform/helm version are you using? Also if you can upload the complete sync log file can help.

**Comment by cbuckle1** [comment]
Airbyte version 1.1.0; no sync logs, the error occurs when testing the source, fails adding the connection from Terrabyte.

**Comment by cbuckle1** [comment]
Tested again after upgrading to Airbyte v1.2.0

Configuration check failed
Workload failed, source: airbyte_platform


Learn more
Internal message: Init container error encountered while processing workload for id: 47f20000-dd5e-4636-8c39-e7cea2453331_e0a12341-f71f-4ab7-ae1a-2e1234dc41c3e_0_check. Encountered exception of type: class java.lang.NullPointerException. Exception message: Cannot invoke "java.util.UUID.toString()" because the return value of "io.airbyte.persistence.job.models.IntegrationLauncherConfig.getConnectionId()" is null.
Failure origin: airbyte_platform

**Comment by nevo-elementor** [comment]
I'm facing a similar issue. (Airbyte v0.63.9)
When creating a Bing source (v2.8.3) using Terraform, the source is being created successfully, but an error occurred when attempting to test it. 
The stack trace indicates an issue with the secret values, and the suspect was 'Client Secret' that was not passed by me from TF but seemed to have a value, judging by the '*******' in the UI. 
A quick and nasty fix was to manually edit the value in Airbyte DB, which solve the problem.
