### ISSUE TITLE
[destination-bigquery] syncs fail when GCP project-Ids contain special characters, starting with 2.9.0

### ISSUE THREAD

**Issue by andnig** [airbytehq/airbyte#48732]
### Connector Name

destination-bigquery

### Connector Version

2.9.0

### What step the error happened?

During the sync

### Relevant information

Airbyte platform version: 1.2.0

My GCP project id has a hyphen ("-") in the project id (it's 'vol-at').
This was not an issue up until version 2.8.9, so 2.8.9 of destination-bigquery works fine.

However, with 2.9.0, any sync fails with the appended logs.
From the BigQuery job logs I can see that the following query fails:

```sql
DROP TABLE IF EXISTS vol-at.airbyte_integrations_raw_v2.airbyte_integrations_v2_raw__stream__airbyte_bigquery_connection_test_70d5677ee1f048e09370b4dc0eccc5a6;
```

The issue is, I guess, that vol-at is not escaped and therefore leads to a database error.

### Relevant log output

```shell
2024-11-27 20:32:08 platform > Using job log path: /workspace/137388/0/logs.log
2024-11-27 20:32:42 destination > INFO main i.a.i.d.b.BigQueryDestinationKt(main):565 Starting Destination : class io.airbyte.integrations.destination.bigquery.BigQueryDestination
2024-11-27 20:32:43 destination > INFO main i.a.c.i.b.IntegrationCliParser$Companion(parseOptions):144 integration args: {catalog=/dest/catalog.json, write=null, config=/dest/connectorConfig.json}
2024-11-27 20:32:43 destination > INFO main i.a.c.i.b.IntegrationRunner(runInternal):130 Running integration: io.airbyte.integrations.destination.bigquery.BigQueryDestination
2024-11-27 20:32:43 destination > INFO main i.a.c.i.b.IntegrationRunner(runInternal):131 Command: WRITE
2024-11-27 20:32:43 destination > INFO main i.a.c.i.b.IntegrationRunner(runInternal):132 Integration config: IntegrationConfig{command=WRITE, configPath='/dest/connectorConfig.json', catalogPath='/dest/catalog.json', statePath='null'}
2024-11-27 20:32:43 destination > WARN main c.n.s.UnknownKeywordFactory(lambda$getKeyword$0):37 Unknown keyword group - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword or if it should generate annotations AnnotationKeyword
2024-11-27 20:32:43 destination > WARN main c.n.s.UnknownKeywordFactory(lambda$getKeyword$0):37 Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword or if it should generate annotations AnnotationKeyword
2024-11-27 20:32:43 destination > WARN main c.n.s.UnknownKeywordFactory(lambda$getKeyword$0):37 Unknown keyword display_type - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword or if it should generate annotations AnnotationKeyword
2024-11-27 20:32:43 destination > WARN main c.n.s.UnknownKeywordFactory(lambda$getKeyword$0):37 Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword or if it should generate annotations AnnotationKeyword
2024-11-27 20:32:43 destination > WARN main c.n.s.UnknownKeywordFactory(lambda$getKeyword$0):37 Unknown keyword always_show - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword or if it should generate annotations AnnotationKeyword
2024-11-27 20:32:43 destination > WARN main c.n.s.UnknownKeywordFactory(lambda$getKeyword$0):37 Unknown keyword groups - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword or if it should generate annotations AnnotationKeyword
2024-11-27 20:32:43 destination > INFO main i.a.i.d.b.BigQueryUtils(getLoadingMethod):230 Selected loading method is set to: GCS
2024-11-27 20:32:43 destination > ERROR main i.a.c.i.u.ConnectorExceptionHandler(handleException):68 caught exception! io.airbyte.commons.exceptions.ConfigErrorException: You must upgrade your platform version to use this connector version. Either downgrade your connector or upgrade platform to 0.63.7
        at io.airbyte.integrations.base.destination.typing_deduping.CatalogParser.toStreamConfig(CatalogParser.kt:139) ~[airbyte-cdk-typing-deduping-0.46.0.jar:?]
        at io.airbyte.integrations.base.destination.typing_deduping.CatalogParser.parseCatalog(CatalogParser.kt:56) ~[airbyte-cdk-typing-deduping-0.46.0.jar:?]
        at io.airbyte.integrations.destination.bigquery.BigQueryDestination.parseCatalog(BigQueryDestination.kt:501) ~[io.airbyte.airbyte-integrations.connectors-destination-bigquery.jar:?]
        at io.airbyte.integrations.destination.bigquery.BigQueryDestination.getSerializedMessageConsumer(BigQueryDestination.kt:398) ~[io.airbyte.airbyte-integrations.connectors-destination-bigquery.jar:?]
        at io.airbyte.cdk.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.kt:214) [airbyte-cdk-core-0.46.0.jar:?]
        at io.airbyte.cdk.integrations.base.IntegrationRunner.run(IntegrationRunner.kt:119) [airbyte-cdk-core-0.46.0.jar:?]
        at io.airbyte.cdk.integrations.base.IntegrationRunner.run$default(IntegrationRunner.kt:113) [airbyte-cdk-core-0.46.0.jar:?]
        at io.airbyte.integrations.destination.bigquery.BigQueryDestinationKt.main(BigQueryDestination.kt:566) [io.airbyte.airbyte-integrations.connectors-destination-bigquery.jar:?]
Stack Trace: io.airbyte.commons.exceptions.ConfigErrorException: You must upgrade your platform version to use this connector version. Either downgrade your connector or upgrade platform to 0.63.7
        at io.airbyte.integrations.base.destination.typing_deduping.CatalogParser.toStreamConfig(CatalogParser.kt:139)
        at io.airbyte.integrations.base.destination.typing_deduping.CatalogParser.parseCatalog(CatalogParser.kt:56)
        at io.airbyte.integrations.destination.bigquery.BigQueryDestination.parseCatalog(BigQueryDestination.kt:501)
        at io.airbyte.integrations.destination.bigquery.BigQueryDestination.getSerializedMessageConsumer(BigQueryDestination.kt:398)
        at io.airbyte.cdk.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.kt:214)
        at io.airbyte.cdk.integrations.base.IntegrationRunner.run(IntegrationRunner.kt:119)
        at io.airbyte.cdk.integrations.base.IntegrationRunner.run$default(IntegrationRunner.kt:113)
        at io.airbyte.integrations.destination.bigquery.BigQueryDestinationKt.main(BigQueryDestination.kt:566)
2024-11-27 20:32:08 platform > Executing worker wrapper. Airbyte version: 1.1.0
2024-11-27 20:32:08 platform > Creating workload 0f357951-fcfe-4e31-95ac-2456b49098bf_137388_0_sync
2024-11-27 20:32:08 platform > Workload 0f357951-fcfe-4e31-95ac-2456b49098bf_137388_0_sync is pending
2024-11-27 20:33:08 platform > Workload 0f357951-fcfe-4e31-95ac-2456b49098bf_137388_0_sync has returned a terminal status of failure.  Fetching output...
2024-11-27 20:33:08 platform > Replication output for workload 0f357951-fcfe-4e31-95ac-2456b49098bf_137388_0_sync : io.airbyte.config.ReplicationOutput@430d48f3[replicationAttemptSummary=io.airbyte.config.ReplicationAttemptSummary@48543c67[status=failed,recordsSynced=0,bytesSynced=0,startTime=1732739561036,endTime=1732739568637,totalStats=io.airbyte.config.SyncStats@7173a08c[bytesCommitted=0,bytesEmitted=63728,destinationStateMessagesEmitted=0,destinationWriteEndTime=0,destinationWriteStartTime=1732739561253,estimatedBytes=<null>,estimatedRecords=<null>,meanSecondsBeforeSourceStateMessageEmitted=0,maxSecondsBeforeSourceStateMessageEmitted=0,maxSecondsBetweenStateMessageEmittedandCommitted=0,meanSecondsBetweenStateMessageEmittedandCommitted=0,recordsEmitted=81,recordsCommitted=0,replicationEndTime=1732739568633,replicationStartTime=1732739561036,sourceReadEndTime=1732739563465,sourceReadStartTime=1732739561254,sourceStateMessagesEmitted=1,discoverSchemaEndTime=<null>,discoverSchemaStartTime=<null>,additionalProperties={}],streamStats=[io.airbyte.config.StreamSyncStats@30c3aa26[streamName=customers,streamNamespace=<null>,stats=io.airbyte.config.SyncStats@1920361d[bytesCommitted=0,bytesEmitted=63728,destinationStateMessagesEmitted=<null>,destinationWriteEndTime=<null>,destinationWriteStartTime=<null>,estimatedBytes=<null>,estimatedRecords=<null>,meanSecondsBeforeSourceStateMessageEmitted=<null>,maxSecondsBeforeSourceStateMessageEmitted=<null>,maxSecondsBetweenStateMessageEmittedandCommitted=<null>,meanSecondsBetweenStateMessageEmittedandCommitted=<null>,recordsEmitted=81,recordsCommitted=0,replicationEndTime=<null>,replicationStartTime=<null>,sourceReadEndTime=<null>,sourceReadStartTime=<null>,sourceStateMessagesEmitted=<null>,discoverSchemaEndTime=<null>,discoverSchemaStartTime=<null>,additionalProperties={}],wasBackfilled=<null>,wasResumed=<null>,additionalProperties={}]],performanceMetrics=io.airbyte.config.PerformanceMetrics@707e965a[additionalProperties={processFromSource={elapsedTimeInNanos=247422293, executionCount=85, avgExecTimeInNanos=2910850.505882353}, readFromSource={elapsedTimeInNanos=2040704357, executionCount=89, avgExecTimeInNanos=2.2929262438202247E7}, processFromDest={elapsedTimeInNanos=538660, executionCount=1, avgExecTimeInNanos=538660.0}, writeToDest={elapsedTimeInNanos=493711748, executionCount=82, avgExecTimeInNanos=6020874.975609756}, readFromDest={elapsedTimeInNanos=2733367001, executionCount=435, avgExecTimeInNanos=6283602.301149425}}],additionalProperties={}],state=<null>,outputCatalog=ConfiguredAirbyteCatalog(streams=[ConfiguredAirbyteStream(stream=AirbyteStream(name=article_sharings__customers, jsonSchema={"type":"object","$schema":"http://json-schema.org/draft-07/schema#","properties":{"id":{"type":"number"},"link":{"type":"object","properties":{"self":{"type":"string"}}},"meta":{"type":"object","properties":{"email":{"type":"string"},"login":{"type":"string"}}},"domain":{"type":"string"},"created_at":{"type":"string"},"updated_at":{"type":"string"},"external_id":{"type":"string"},"share_items":{"type":"array","items":{"type":"object","properties":{"id":{"type":"number"},"type":{"type":"string"},"scope":{"type":"string"},"token":{"type":"string"},"client":{"type":"string"},"created_at":{"type":"string"},"identifier":{"type":"string"},"updated_at":{"type":"string"},"customer_id":{"type":"number"},"current_pageviews":{"type":"number"},"remaining_pageviews":{"type":"number"}}}}}}, supportedSyncModes=[full_refresh], sourceDefinedCursor=false, defaultCursorField=[], sourceDefinedPrimaryKey=[[id]], namespace=null, isResumable=null), syncMode=full_refresh, destinationSyncMode=append, cursorField=[], primaryKey=[[id]], generationId=null, minimumGenerationId=null, syncId=null, fields=[Field(name=id, type=NUMBER), Field(name=link, type=OBJECT), Field(name=meta, type=OBJECT), Field(name=domain, type=STRING), Field(name=created_at, type=STRING), Field(name=updated_at, type=STRING), Field(name=external_id, type=STRING), Field(name=share_items, type=ARRAY)], mappers=[])]),failures=[io.airbyte.config.FailureReason@1c652f19[failureOrigin=destination,failureType=config_error,internalMessage=io.airbyte.commons.exceptions.ConfigErrorException: You must upgrade your platform version to use this connector version. Either downgrade your connector or upgrade platform to 0.63.7,externalMessage=You must upgrade your platform version to use this connector version. Either downgrade your connector or upgrade platform to 0.63.7,metadata=io.airbyte.config.Metadata@31da2429[additionalProperties={attemptNumber=0, jobId=137388, from_trace_message=true, connector_command=write}],stacktrace=io.airbyte.commons.exceptions.ConfigErrorException: You must upgrade your platform version to use this connector version. Either downgrade your connector or upgrade platform to 0.63.7
        at io.airbyte.integrations.base.destination.typing_deduping.CatalogParser.toStreamConfig(CatalogParser.kt:139)
        at io.airbyte.integrations.base.destination.typing_deduping.CatalogParser.parseCatalog(CatalogParser.kt:56)
        at io.airbyte.integrations.destination.bigquery.BigQueryDestination.parseCatalog(BigQueryDestination.kt:501)
        at io.airbyte.integrations.destination.bigquery.BigQueryDestination.getSerializedMessageConsumer(BigQueryDestination.kt:398)
        at io.airbyte.cdk.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.kt:214)
        at io.airbyte.cdk.integrations.base.IntegrationRunner.run(IntegrationRunner.kt:119)
        at io.airbyte.cdk.integrations.base.IntegrationRunner.run$default(IntegrationRunner.kt:113)
        at io.airbyte.integrations.destination.bigquery.BigQueryDestinationKt.main(BigQueryDestination.kt:566)
,retryable=<null>,timestamp=1732739563963,streamDescriptor=<null>,additionalProperties={}], io.airbyte.config.FailureReason@29d26cd1[failureOrigin=destination,failureType=<null>,internalMessage=Destination process exited with non-zero exit code 1,externalMessage=Something went wrong within the destination connector,metadata=io.airbyte.config.Metadata@2d9af3f7[additionalProperties={attemptNumber=0, jobId=137388, connector_command=write}],stacktrace=io.airbyte.workers.internal.exception.DestinationException: Destination process exited with non-zero exit code 1
        at io.airbyte.workers.general.BufferedReplicationWorker.readFromDestination(BufferedReplicationWorker.java:500)
        at io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsync$2(BufferedReplicationWorker.java:215)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
,retryable=<null>,timestamp=1732739564105,streamDescriptor=<null>,additionalProperties={}], io.airbyte.config.FailureReason@18b20cba[failureOrigin=replication,failureType=<null>,internalMessage=io.airbyte.workers.exception.WorkerException: Destination process exit with code 1. This warning is normal if the job was cancelled.,externalMessage=Something went wrong during replication,metadata=io.airbyte.config.Metadata@78a998e9[additionalProperties={attemptNumber=0, jobId=137388}],stacktrace=java.lang.RuntimeException: io.airbyte.workers.exception.WorkerException: Destination process exit with code 1. This warning is normal if the job was cancelled.
        at io.airbyte.workers.general.BufferedReplicationWorker$CloseableWithTimeout.lambda$close$0(BufferedReplicationWorker.java:545)
        at io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsyncWithTimeout$5(BufferedReplicationWorker.java:243)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: io.airbyte.workers.exception.WorkerException: Destination process exit with code 1. This warning is normal if the job was cancelled.
        at io.airbyte.workers.internal.LocalContainerAirbyteDestination.close(LocalContainerAirbyteDestination.kt:62)
        at io.airbyte.workers.general.BufferedReplicationWorker$CloseableWithTimeout.lambda$close$0(BufferedReplicationWorker.java:543)
        ... 5 more
,retryable=<null>,timestamp=1732739568562,streamDescriptor=<null>,additionalProperties={}]],additionalProperties={}]
2024-11-27 20:33:08 platform > 
2024-11-27 20:33:08 platform > No post-replication operation(s) to perform.
2024-11-27 20:33:08 platform > ----- START POST REPLICATION OPERATIONS -----
2024-11-27 20:33:08 platform > 
2024-11-27 20:33:08 platform > 
2024-11-27 20:33:08 platform > ----- END POST REPLICATION OPERATIONS -----
2024-11-27 20:33:08 platform > 
2024-11-27 20:33:09 platform > Retry State: RetryManager(completeFailureBackoffPolicy=BackoffPolicy(minInterval=PT10S, maxInterval=PT30M, base=3), partialFailureBackoffPolicy=null, successiveCompleteFailureLimit=5, totalCompleteFailureLimit=10, successivePartialFailureLimit=1000, totalPartialFailureLimit=20, successiveCompleteFailures=1, totalCompleteFailures=1, successivePartialFailures=0, totalPartialFailures=0)
 Backoff before next attempt: 10 seconds
2024-11-27 20:33:09 platform > Failing job: 137388, reason: Connection Check Failed 0f357951-fcfe-4e31-95ac-2456b49098bf
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by FloDevelops** [comment]
@andnig having the same issue from 2.9.0, I would even argue that hyphens ('-') are recommended characters in project ids according to [GCP documentation](https://cloud.google.com/resource-manager/docs/creating-managing-projects#before_you_begin).

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 180 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by andnig** [comment]
@octavia-squidington-iii This is important as Airbyte should allow all valid characters in BigQuery project names. Furthermore its a regression from previous version, meaning existing projects don't work anymore!
