### ISSUE TITLE
Cannot use airbyte on kubernetes

### ISSUE THREAD

**Issue by jomach** [airbytehq/airbyte#48797]
### Connector Name

all-connectors

### Connector Version

latest

### What step the error happened?

None

### Relevant information

Hello, 

I just deployed the newest helm version of airbyte (1.2.0). When I try to setup a source or destination I get: 

```
2024-12-04 14:57:36,670 [scheduler-executor-thread-15]	WARN	i.a.c.s.c.JobConverter(getWorkspaceId):403 - Unable to retrieve workspace ID for job null.
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:904)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4016)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4040)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4989)
	at io.airbyte.persistence.job.WorkspaceHelper.lambda$getWorkspaceForJobId$4(WorkspaceHelper.java:162)
	at io.airbyte.persistence.job.WorkspaceHelper.handleCacheExceptions(WorkspaceHelper.java:231)
	at io.airbyte.persistence.job.WorkspaceHelper.getWorkspaceForJobId(WorkspaceHelper.java:162)
	at io.airbyte.commons.server.converters.JobConverter.getWorkspaceId(JobConverter.java:401)
	at io.airbyte.commons.server.converters.JobConverter.getAttemptLogs(JobConverter.java:320)
	at io.airbyte.commons.server.converters.JobConverter.getSynchronousJobRead(JobConverter.java:349)
	at io.airbyte.commons.server.converters.JobConverter.getSynchronousJobRead(JobConverter.java:344)
	at io.airbyte.commons.server.handlers.SchedulerHandler.reportConnectionStatus(SchedulerHandler.java:690)
	at io.airbyte.commons.server.handlers.SchedulerHandler.checkSourceConnectionFromSourceCreate(SchedulerHandler.java:270)
	at io.airbyte.server.apis.SchedulerApiController.lambda$executeSourceCheckConnection$1(SchedulerApiController.java:47)
	at io.airbyte.server.apis.ApiHelper.execute(ApiHelper.kt:29)
	at io.airbyte.server.apis.SchedulerApiController.executeSourceCheckConnection(SchedulerApiController.java:47)
	at io.airbyte.server.apis.$SchedulerApiController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invokeUnsafe(AbstractExecutableMethodsDefinition.java:461)
	at io.micronaut.context.DefaultBeanContext$BeanContextUnsafeExecutionHandle.invokeUnsafe(DefaultBeanContext.java:4350)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:272)
	at io.micronaut.web.router.DefaultUriRouteMatch.execute(DefaultUriRouteMatch.java:38)
	at io.micronaut.http.server.RouteExecutor.executeRouteAndConvertBody(RouteExecutor.java:498)
	at io.micronaut.http.server.RouteExecutor.lambda$callRoute$5(RouteExecutor.java:475)
	at io.micronaut.core.execution.ExecutionFlow.lambda$async$1(ExecutionFlow.java:87)
	at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

````

Any idea ? 

### Relevant log output

```shell

```

### Contribute

- [ ] Yes, I want to contribute

**Comment by natikgadzhi** [comment]
Huh. Not my area, but that seems way off. Tried community slack yet?

**Comment by jomach** [comment]
@natikgadzhi  I just found out why. OOM and airybte is ignoring the envs : JOB_MAIN_CONTAINER_MEMORY_REQUEST again :(

**Comment by jomach** [comment]
This was such a good project...

**Comment by jomach** [comment]
Will close this as it is not really the issue
