### ISSUE TITLE
[source-google-analytics-data-api] Google Analytics 4 source check fails with "Permission denied: '/config/connectionConfiguration.json'"

### ISSUE THREAD

**Issue by henriquemeloo** [airbytehq/airbyte#48796]
### Connector Name

source-google-analytics-data-api

### Connector Version

2.6.1

### What step the error happened?

During the sync

### Relevant information

The connector fails with this error during source check, when running on Airbyte helm chart v1.2.0 deployed on AWS EKS.

### Relevant log output

```shell
2024-12-03 21:55:06 platform > Retry State: RetryManager(completeFailureBackoffPolicy=BackoffPolicy(minInterval=PT10S, maxInterval=PT30M, base=3), partialFailureBackoffPolicy=null, successiveCompleteFailureLimit=5, totalCompleteFailureLimit=10, successivePartialFailureLimit=1000, totalPartialFailureLimit=20, successiveCompleteFailures=4, totalCompleteFailures=4, successivePartialFailures=0, totalPartialFailures=0)
2024-12-03 21:55:07 platform > Backing off for: 4 minutes 30 seconds.
2024-12-03 22:00:53 platform > APPLY Stage: CLAIM — (workloadId = 3cc2eafd-84aa-4dca-93af-322d9dfeec1a_46909_4_check) — (dataplaneId = local)
2024-12-03 22:00:53 platform > Claimed: true for 3cc2eafd-84aa-4dca-93af-322d9dfeec1a_46909_4_check via API for local
2024-12-03 22:00:53 platform > APPLY Stage: CHECK_STATUS — (workloadId = 3cc2eafd-84aa-4dca-93af-322d9dfeec1a_46909_4_check) — (dataplaneId = local)
2024-12-03 22:00:53 platform > No pod found running for workload 3cc2eafd-84aa-4dca-93af-322d9dfeec1a_46909_4_check
2024-12-03 22:00:53 platform > APPLY Stage: BUILD — (workloadId = 3cc2eafd-84aa-4dca-93af-322d9dfeec1a_46909_4_check) — (dataplaneId = local)
2024-12-03 22:00:53 platform > APPLY Stage: MUTEX — (workloadId = 3cc2eafd-84aa-4dca-93af-322d9dfeec1a_46909_4_check) — (dataplaneId = local)
2024-12-03 22:00:53 platform > No mutex key specified for workload: 3cc2eafd-84aa-4dca-93af-322d9dfeec1a_46909_4_check. Continuing...
2024-12-03 22:00:53 platform > APPLY Stage: LAUNCH — (workloadId = 3cc2eafd-84aa-4dca-93af-322d9dfeec1a_46909_4_check) — (dataplaneId = local)
2024-12-03 22:00:53 platform > [initContainer] image: airbyte/workload-init-container:1.2.0 resources: ResourceRequirements(claims=[], limits={}, requests={}, additionalProperties={})
2024-12-03 22:00:57 platform > Attempting to update workload: 3cc2eafd-84aa-4dca-93af-322d9dfeec1a_46909_4_check to LAUNCHED.
2024-12-03 22:00:57 platform > Pipeline completed for workload: 3cc2eafd-84aa-4dca-93af-322d9dfeec1a_46909_4_check.
2024-12-03 22:00:59 platform > 
2024-12-03 22:00:59 platform > Connector exited, processing output
2024-12-03 22:00:59 platform > ----- START CHECK -----
2024-12-03 22:00:59 platform > 
2024-12-03 22:00:59 platform > Output file jobOutput.json found
2024-12-03 22:00:59 platform > Connector exited with exit code 1
2024-12-03 22:00:59 platform > Reading messages from protocol version 0.2.0
2024-12-03 22:00:59 platform > MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-12-03 22:00:59 platform > [Errno 13] Permission denied: '/config/connectionConfiguration.json'
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 8, in <module>
    run()
  File "/airbyte/integration_code/source_google_analytics_data_api/run.py", line 17, in run
    MigrateCustomReportsCohortSpec.migrate(sys.argv[1:], source)
  File "/airbyte/integration_code/source_google_analytics_data_api/config_migrations.py", line 237, in migrate
    cls._modify_and_save(config_path, source, config),
  File "/airbyte/integration_code/source_google_analytics_data_api/config_migrations.py", line 210, in _modify_and_save
    source.write_config(migrated_config, config_path)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/connector.py", line 60, in write_config
    with open(config_path, "w") as fh:
PermissionError: [Errno 13] Permission denied: '/config/connectionConfiguration.json'
2024-12-03 22:00:59 platform > Checking for optional control message...
2024-12-03 22:00:59 platform > Writing output of 3cc2eafd-84aa-4dca-93af-322d9dfeec1a_46909_4_check to the doc store
2024-12-03 22:00:59 platform > Marking workload 3cc2eafd-84aa-4dca-93af-322d9dfeec1a_46909_4_check as successful
2024-12-03 22:00:59 platform > 
2024-12-03 22:00:59 platform > Deliberately exiting process with code 0.
2024-12-03 22:00:59 platform > ----- END CHECK -----
2024-12-03 22:00:59 platform > 
2024-12-03 22:01:01 platform > Retry State: RetryManager(completeFailureBackoffPolicy=BackoffPolicy(minInterval=PT10S, maxInterval=PT30M, base=3), partialFailureBackoffPolicy=null, successiveCompleteFailureLimit=5, totalCompleteFailureLimit=10, successivePartialFailureLimit=1000, totalPartialFailureLimit=20, successiveCompleteFailures=5, totalCompleteFailures=5, successivePartialFailures=0, totalPartialFailures=0)
 Backoff before next attempt: 13 minutes 30 seconds
2024-12-03 22:01:01 platform > Failing job: 46909, reason: Job failed after too many retries for connection 590faf5d-55a1-4c31-a254-56f76b26030a
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by henriquemeloo** [comment]
This is a follow up of discussion https://github.com/airbytehq/airbyte/discussions/43356

**Comment by henriquemeloo** [comment]
Version 2.0.3 seems to be working.
