### ISSUE TITLE
Redshift Source connector consistently fails with "null value in entry: isNullable=null"

### ISSUE THREAD

**Issue by olegflo** [airbytehq/airbyte#48856]
### Connector Name

source-redshift

### Connector Version

0.5.2

### What step the error happened?

None

### Relevant information

Hi dear community,

Airbyte Redshift source connector fails with the "Internal message: java.lang.NullPointerException: null value in entry: isNullable=null"

It worked once on Nov 7th and broke later and doesn't work since then.

It's a reproducible issue that appears for each new source connector for Redshift. I tested with a few different SQL users with different  Redshift permissions.

On the screenshot you see that during source creation all tests are passed but later I can't proceed with the full connection creation.

It tries first "discover" and then falls back to "discoverWithoutSystemTables" - presumably it lacks access to system tables? If yes to which ones? The docu page https://docs.airbyte.com/integrations/sources/redshift doesn't mention anything about any special requirements of having access to system tables 🤷 

Has anyone faced a similar issue or could suggest direction of further debugging? The error content is limited so it's not really clear what's going in.

![Image](https://github.com/user-attachments/assets/96500f84-7b60-4e05-a072-0d10274f2a38)

### Relevant log output

```shell
java.lang.NullPointerException: null value in entry: isNullable=null
	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:33)
	at com.google.common.collect.ImmutableMapEntry.<init>(ImmutableMapEntry.java:54)
	at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:345)
	at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:454)
	at io.airbyte.cdk.integrations.source.jdbc.AbstractJdbcSource.getColumnMetadata(AbstractJdbcSource.java:248)
	at io.airbyte.cdk.db.jdbc.JdbcDatabase$1.tryAdvance(JdbcDatabase.java:84)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.airbyte.cdk.db.jdbc.DefaultJdbcDatabase.bufferedResultSetQuery(DefaultJdbcDatabase.java:57)
	at io.airbyte.cdk.integrations.source.jdbc.AbstractJdbcSource.discoverInternal(AbstractJdbcSource.java:171)
	at io.airbyte.integrations.source.redshift.RedshiftSource.discoverInternal(RedshiftSource.java:94)
	at io.airbyte.integrations.source.redshift.RedshiftSource.discoverInternal(RedshiftSource.java:30)
	at io.airbyte.cdk.integrations.source.relationaldb.AbstractDbSource.discoverWithoutSystemTables(AbstractDbSource.java:268)
	at io.airbyte.cdk.integrations.source.relationaldb.AbstractDbSource.discover(AbstractDbSource.java:126)
	at io.airbyte.cdk.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:159)
	at io.airbyte.cdk.integrations.base.IntegrationRunner.run(IntegrationRunner.java:125)
	at io.airbyte.integrations.source.redshift.RedshiftSource.main(RedshiftSource.java:141)
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by olegflo** [comment]
Found a more narrowly mentioned failure reason which I tested and could confirm so I am closing my request in favour of https://github.com/airbytehq/airbyte/issues/48832
