### ISSUE TITLE
Sync attempt with killed pod hangs eternally

### ISSUE THREAD

**Issue by henriquemeloo** [airbytehq/airbyte#48879]
### Helm Chart Version

1.2.0

### What step the error happened?

During the Sync

### Relevant information

When the pod for a sync gets killed externally (e.g. by cluster downsizing or running nodes on EC2 spot instances), the sync just hangs there without starting a new attempt or failing. I would expect the heartbeat mechanism (which I did not intentionally configure either on or off) to flag this attempt as failed, but the sync's logs just freeze and the sync is still tagged as running in the webapp. I couldn't find any logs in the other pods relative to this specific job ID. What I did find were these (possibly unrelated) logs from the server deployment:

### Relevant log output

```shell
2024-12-10 13:53:15,461 [io-executor-thread-2]	WARN	i.a.c.s.c.JobConverter(getWorkspaceId):403 - Unable to retrieve workspace ID for job null.
java.lang.NullPointerException: null
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:904)
    at com.google.common.cache.LocalCache.get(LocalCache.java:4016)
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4040)
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4989)
    at io.airbyte.persistence.job.WorkspaceHelper.lambda$getWorkspaceForJobId$4(WorkspaceHelper.java:162)
    at io.airbyte.persistence.job.WorkspaceHelper.handleCacheExceptions(WorkspaceHelper.java:231)
    at io.airbyte.persistence.job.WorkspaceHelper.getWorkspaceForJobId(WorkspaceHelper.java:162)
    at io.airbyte.commons.server.converters.JobConverter.getWorkspaceId(JobConverter.java:401)
    at io.airbyte.commons.server.converters.JobConverter.getAttemptLogs(JobConverter.java:320)
    at io.airbyte.commons.server.converters.JobConverter.getSynchronousJobRead(JobConverter.java:349)
    at io.airbyte.commons.server.converters.JobConverter.getSynchronousJobRead(JobConverter.java:344)
    at io.airbyte.commons.server.handlers.SchedulerHandler.retrieveDiscoveredSchema(SchedulerHandler.java:567)
    at io.airbyte.commons.server.handlers.SchedulerHandler.discoverAndGloballyDisable(SchedulerHandler.java:400)
    at io.airbyte.commons.server.handlers.SchedulerHandler.discoverSchemaForSourceFromSourceId(SchedulerHandler.java:365)
    at io.airbyte.commons.server.handlers.WebBackendConnectionsHandler.getRefreshedSchema(WebBackendConnectionsHandler.java:488)
    at io.airbyte.commons.server.handlers.WebBackendConnectionsHandler.webBackendGetConnection(WebBackendConnectionsHandler.java:432)
    at io.airbyte.server.apis.WebBackendApiController.lambda$webBackendGetConnection$2(WebBackendApiController.java:113)
    at io.airbyte.server.apis.ApiHelper.execute(ApiHelper.kt:29)
    at io.airbyte.server.apis.WebBackendApiController.webBackendGetConnection(WebBackendApiController.java:103)
    at io.airbyte.server.apis.$WebBackendApiController$Definition$Exec.dispatch(Unknown Source)
    at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invokeUnsafe(AbstractExecutableMethodsDefinition.java:461)
    at io.micronaut.context.DefaultBeanContext$BeanContextUnsafeExecutionHandle.invokeUnsafe(DefaultBeanContext.java:4350)
    at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:272)
    at io.micronaut.web.router.DefaultUriRouteMatch.execute(DefaultUriRouteMatch.java:38)
    at io.micronaut.http.server.RouteExecutor.executeRouteAndConvertBody(RouteExecutor.java:498)
    at io.micronaut.http.server.RouteExecutor.lambda$callRoute$5(RouteExecutor.java:475)
    at io.micronaut.core.execution.ExecutionFlow.lambda$async$1(ExecutionFlow.java:87)
    at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by henriquemeloo** [comment]
The cron service might be dead though:
```
2024-12-10 13:31:52,128 [scheduled-executor-thread-4]	ERROR	i.m.s.DefaultTaskExceptionHandler(handle):47 - Error invoking scheduled task for bean [io.airbyte.cron.jobs.SelfHealTemporalWorkflows@757950e4] RESOURCE_EXHAUSTED: namespace rate limit exceeded
io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: namespace rate limit exceeded
    at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:268)
    at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:249)
    at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:167)
    at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.listClosedWorkflowExecutions(WorkflowServiceGrpc.java:4620)
    at io.airbyte.commons.temporal.WorkflowServiceStubsWrapped.lambda$blockingStubListClosedWorkflowExecutions$0(WorkflowServiceStubsWrapped.java:47)
    at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
    at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
    at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
    at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
    at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
    at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112)
    at io.airbyte.commons.temporal.RetryHelper.withRetries(RetryHelper.java:60)
    at io.airbyte.commons.temporal.WorkflowServiceStubsWrapped.withRetries(WorkflowServiceStubsWrapped.java:67)
    at io.airbyte.commons.temporal.WorkflowServiceStubsWrapped.blockingStubListClosedWorkflowExecutions(WorkflowServiceStubsWrapped.java:47)
    at io.airbyte.commons.temporal.TemporalClient.fetchClosedWorkflowsByStatus(TemporalClient.java:139)
    at io.airbyte.commons.temporal.TemporalClient.restartClosedWorkflowByStatus(TemporalClient.java:117)
    at io.airbyte.cron.jobs.SelfHealTemporalWorkflows.cleanTemporal(SelfHealTemporalWorkflows.java:42)
    at io.airbyte.cron.jobs.$SelfHealTemporalWorkflows$Definition$Exec.dispatch(Unknown Source)
    at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:456)
    at io.micronaut.inject.DelegatingExecutableMethod.invoke(DelegatingExecutableMethod.java:86)
    at io.micronaut.context.bind.DefaultExecutableBeanContextBinder$ContextBoundExecutable.invoke(DefaultExecutableBeanContextBinder.java:152)
    at io.micronaut.scheduling.processor.ScheduledMethodProcessor.lambda$scheduleTask$2(ScheduledMethodProcessor.java:160)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
    at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
    at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by marcosmarxm** [comment]
@airbytehq/move-platform can someone take a look into this issue?

**Comment by hvignolo87** [comment]
I'm facing the same situation. Is there any news related to this issue?

**Comment by gosusnp** [comment]
@henriquemeloo, you assessment seems right. In the event where a job pod disappears, hard failure or node getting taken away, there's a timeout related to the heartbeat that should catch it.
The `cron` is the application enforcing this. One way to confirm this from the logs would be to look for `Checking for non heartbeating workload`.

@hvignolo87 , same answer, can you confirm if the `cron` is running?

**Comment by hvignolo87** [comment]
> [@henriquemeloo](https://github.com/henriquemeloo), you assessment seems right. In the event where a job pod disappears, hard failure or node getting taken away, there's a timeout related to the heartbeat that should catch it. The `cron` is the application enforcing this. One way to confirm this from the logs would be to look for `Checking for non heartbeating workload`.
> 
> [@hvignolo87](https://github.com/hvignolo87) , same answer, can you confirm if the `cron` is running?

Hi @gosusnp! Thanks for your reply!

The `cron` is up and running, and there's no match for `Checking for non heartbeating workload` in its logs.

**Comment by gosusnp** [comment]
@hvignolo87 , are you running `1.2.0` as well? if not, which version are you running?

Also, do you observe this sync hanging issue frequently? I have seen some activity around the cron recently, there should a few fixes in the next version.

**Comment by hvignolo87** [comment]
> [@hvignolo87](https://github.com/hvignolo87) , are you running `1.2.0` as well? if not, which version are you running?

Yes, I'm running `1.2.0` in EKS, and it's the same behavior described in this issue. Furthermore, I'm using `karpenter` 1.0 with 2 `NodePools` configured: one for the airbyte's components, and the other for the jobs (sync, check, discover, and spec).

> Also, do you observe this sync hanging issue frequently? I have seen some activity around the cron recently, there should a few fixes in the next version.

Yes, this was an everyday issue until I figured out how to define the resources for the non-sync jobs through the environment variables (unfortunately, not documented). After that, and although this issue continued to happen, the frequency was significantly reduced. Let's say it's happening 1-2 times per week, depending on karpenter's actions regarding disruption.

**Comment by gosusnp** [comment]
@hvignolo87, I have been over our recent commit history, I believe the [fix](https://github.com/airbytehq/airbyte-platform-internal/pull/14918) to enable the missing component has been merged in Jan and is part of version 1.4.
I'd recommend updating to the latest.

**Comment by gosusnp** [comment]
Correct link is https://github.com/airbytehq/airbyte-platform/commit/6b61cf10c6077e0c3cce7f18ce7e94d417181f17

**Comment by hvignolo87** [comment]
> Correct link is [airbytehq/airbyte-platform@6b61cf1](https://github.com/airbytehq/airbyte-platform/commit/6b61cf10c6077e0c3cce7f18ce7e94d417181f17)

I'm not sure I understand why that change fixes this problem 🤔

**Comment by gosusnp** [comment]
The component in the `airbyte-cron` that is enforcing timeout wasn't enabled properly. The PR I linked is addressing the main issue here.

Heads up, I don't the configuration overrides you uncovered are meant to stay in the `workload-launcher`.
I am also not sure how the temporal configuration override relates to this issue.

**Comment by hvignolo87** [comment]
The `RESOURCE_EXHAUSTED` error is because of Temporal. See [this issue](https://community.temporal.io/t/resource-exhausted-namespace-rate-limit-exceeded/6244) for example, or [the other](https://github.com/airbytehq/airbyte/issues/46554#issuecomment-2634226702) I linked before.

**Comment by davinchia** [comment]
Closing as the original issue is resolved. Please reopen if needed. Thanks.
