### ISSUE TITLE
[source-google-analytics-data-api] Connector failed with permission error Internal message: [Errno 13] Permission denied: '/config/connectionConfiguration.json'

### ISSUE THREAD

**Issue by jingpang25** [airbytehq/airbyte#49468]
### What happened?

The google-analytics-data connector failed with permission error 
```
Internal message: [Errno 13] Permission denied: '/config/connectionConfiguration.json'
```
Full error message
```
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 8, in <module>
    run()
  File "/airbyte/integration_code/source_google_analytics_data_api/run.py", line 17, in run
    MigrateCustomReportsCohortSpec.migrate(sys.argv[1:], source)
  File "/airbyte/integration_code/source_google_analytics_data_api/config_migrations.py", line 237, in migrate
    cls._modify_and_save(config_path, source, config),
  File "/airbyte/integration_code/source_google_analytics_data_api/config_migrations.py", line 210, in _modify_and_save
    source.write_config(migrated_config, config_path)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/connector.py", line 60, in write_config
    with open(config_path, "w") as fh:
PermissionError: [Errno 13] Permission denied: '/config/connectionConfiguration.json'
```

## Running versions 
We are running airbyte v1.3 using the latest abctl v0.24 on an EC2 instance. 
The connector we used is google-analytics-data connector with v2.6.1. 

## Hypothesis
The error message suggests the installation step is not properly granting the airbyte with necessary permission on config files. 

Ps, Confirmed if we downgrade to v2.0.3, the connector is working. 

### Abctl Version

<details>

```console
abctl version
version: v0.24.0
```

</details>

### Docker Version

<details>

```console
Client:
 Version:           25.0.5
 API version:       1.44
 Go version:        go1.22.5
 Git commit:        5dc9bcc
 Built:             Wed Aug 21 00:00:00 2024
 OS/Arch:           linux/arm64
 Context:           default

Server:
 Engine:
  Version:          25.0.6
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.22.5
  Git commit:       b08a51f
  Built:            Wed Aug 21 00:00:00 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.7.22
  GitCommit:        7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc:
  Version:          1.1.14
  GitCommit:        2c9f5602f0ba3d9da1c2596322dfc4e156844890
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

</details>

### OS Version

<details>

```console
NAME="Amazon Linux"
VERSION="2023"
ID="amzn"
ID_LIKE="fedora"
VERSION_ID="2023"
PLATFORM_ID="platform:al2023"
PRETTY_NAME="Amazon Linux 2023.6.20241010"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2023"
HOME_URL="https://aws.amazon.com/linux/amazon-linux-2023/"
DOCUMENTATION_URL="https://docs.aws.amazon.com/linux/"
SUPPORT_URL="https://aws.amazon.com/premiumsupport/"
BUG_REPORT_URL="https://github.com/amazonlinux/amazon-linux-2023"
VENDOR_NAME="AWS"
VENDOR_URL="https://aws.amazon.com/"
SUPPORT_END="2028-03-15"
```

</details>

**Comment by AshvinBambhaniya2003** [comment]
@jingpang25 any update on this ?

**Comment by alafanechere** [comment]
@jingpang25 @AshvinBambhaniya2003 we updated the connector again. I think this will solve your issue. Can you try `airbyte/source-google-analytics-data-api:2.6.2` ?

**Comment by jingpang25** [comment]
issue resolved by using version `airbyte/source-google-analytics-data-api:2.6.2`
