### ISSUE TITLE
NPE when reporting syncCPU resource

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#4954]
A user reported a NPE:

```
2021-07-23 17:08:06 INFO () EnvConfigs(getEnvOrDefault):302 - WORKER_ENVIRONMENT not found or empty, defaulting to DOCKER
2021-07-23 17:08:06 INFO () DefaultNormalizationWorker(run):77 - Normalization executed in 0.
2021-07-23 17:08:06 INFO () TemporalAttemptExecution(get):133 - Stopping cancellation check scheduling...
2021-07-23 17:08:06 ERROR () Exceptions(swallow):84 - Swallowed error.
java.lang.NullPointerException: null value in entry: sync_cpu_request=null
	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:32) ~[guava-30.1.1-jre.jar:?]
	at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:171) ~[guava-30.1.1-jre.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:281) ~[guava-30.1.1-jre.jar:?]
	at io.airbyte.scheduler.persistence.job_tracker.TrackingMetadata.generateSyncMetadata(TrackingMetadata.java:62) ~[io.airbyte.airbyte-scheduler-persistence-0.27.5-alpha.jar:?]
	at io.airbyte.scheduler.persistence.job_tracker.JobTracker.generateSyncMetadata(JobTracker.java:211) ~[io.airbyte.airbyte-scheduler-persistence-0.27.5-alpha.jar:?]
	at io.airbyte.scheduler.persistence.job_tracker.JobTracker.lambda$trackSync$3(JobTracker.java:134) ~[io.airbyte.airbyte-scheduler-persistence-0.27.5-alpha.jar:?]
```

**Comment by sbakiu** [comment]
I am also receiving the following error while saving custom `dbt` transformations. 
Version: `0.28.0-alpha`

**Comment by jrhizor** [comment]
I just put up a PR https://github.com/airbytehq/airbyte/pull/4988 to address the logging of this error.

However, the stacktrace @ChristopheDuong is sharing above is a caught exception that is only being logged for debugging purposes. It shouldn't actually impact sync completion.

@sbakiu there is likely another exception causing the error you're seeing. Please create a ticket or post on Slack with the rest of the logs and someone can help debug.
