### ISSUE TITLE
[destination-postgres] Name collision with index causes table creation to fail

### ISSUE THREAD

**Issue by mcornejo** [airbytehq/airbyte#49582]
### Connector Name

destination-postgres

### Connector Version

2.4.0

### What step the error happened?

During the sync

### Relevant information

If a stream has the "wrong" number of characters, it will fail when syncing due to a collision with an index.
If the length of Stream prefix + Table Name = 43 then it will fail the sync.

For example:
public_raw__stream_  = 19 characters
Stream prefix + Table Name = 43 = characters

These two add up to 62 characters + `_` makes the 63 limit character of postgres.

So in this example, if the stream prefix is `abc_compt1_v2` and the table is called `ubkypumjzgxjboycjilsqvhbiurne` then an index is created under the name  `public_raw__stream_abc_compt1_v2_ubkypumjzgxjboycjilsqvhbiurne_` for the tmp folder. When the real table is created, it cannot be created because there is an index with the same name yielding to `ERROR: "public_raw__stream_abc_compt1_v2_ubkypumjzgxjboycjilsqvhbiurne_" is an index`.

### Relevant log output

```shell
Stack Trace: org.postgresql.util.PSQLException: ERROR: "public_raw__stream_abc_compt1_v2_ubkypumjzgxjboycjilsqvhbiurne_" is an index
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2733)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2420)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:372)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:517)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:434)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:356)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:341)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:317)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:312)
        at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94)
        at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
        at io.airbyte.cdk.db.jdbc.JdbcDatabase.execute$lambda$0(JdbcDatabase.kt:52)
        at io.airbyte.cdk.db.jdbc.DefaultJdbcDatabase.execute(DefaultJdbcDatabase.kt:30)
        at io.airbyte.cdk.db.jdbc.JdbcDatabase.execute(JdbcDatabase.kt:48)
        at io.airbyte.cdk.db.jdbc.JdbcDatabase.execute(JdbcDatabase.kt:43)
        at io.airbyte.cdk.integrations.destination.jdbc.JdbcSqlOperations.createTableIfNotExists(JdbcSqlOperations.kt:63)
```

### Contribute

- [x] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Duplicated of https://github.com/airbytehq/airbyte/issues/45345

@davinchia + @airbytehq/move-destinations fyi as this becoming more frequent issue.
