### ISSUE TITLE
Hubspot connector fails by querying API with wrong API key

### ISSUE THREAD

**Issue by JianhaoZhang** [airbytehq/airbyte#4964]
## Enviroment
- **Airbyte version**:  0.27.3-alpha
- **OS Version / Instance**: Ubuntu 18.04 / GCP n.2
- **Deployment**: Docker
- **Source Connector and version**: Hubspot 0.1.5
- **Destination Connector and version**: BigQuery 0.3.8
- **Severity**: Medium
- **Step where error happened**: Sync job / Setup new connection

## Current Behavior
The Hubspot connector uses an API key under a specific account to access data. 
However, when it calls GET /automation/v3/workflows, the permission is denied because this API is from a different scope.
It requires a developer portal API key instead of a specific account API key.
Documentation on this: [https://legacydocs.hubspot.com/docs/faq/developer-api-keys](url)

> Note: Developer API keys can only be used for managing those settings. Developer API keys cannot be used for accessing the data APIs, such as the Contacts API. You must use the API key from a specific account to access the data for that account. If you are looking to test the data APIs, you can create a test account, and get the API key from that test account.

The Hubspot connector will fail three times in a row and go through at last with a "failed" status. The unaffected data are successfully transferred, so it is not as bad as unusable. However, the three retries hurt the performance and the empty workflow tables confuses people.

## Expected Behavior
Solution 1: remove Workflow from hubspot schema
Solution 2: require multiple hapikeys from different scopes
Solution 3: split Hubspot into multiple connectors (such as Hubspot-developer or something)

## Logs
Relevant logs folded below
<details>
<summary>LOG</summary> 

```

2021-07-23 21:09:47 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Syncing workflows stream
2021-07-23 21:09:47 ERROR () LineGobbler(voidCall):85 - Traceback (most recent call last):
2021-07-23 21:09:47 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - Encountered an exception while reading stream SourceHubspot
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/base_python/source.py", line 88, in read
    yield from self._read_stream(logger=logger, client=client, configured_stream=configured_stream, state=total_state)
  File "/usr/local/lib/python3.7/site-packages/base_python/source.py", line 107, in _read_stream
    for record in client.read_stream(configured_stream.stream):
  File "/usr/local/lib/python3.7/site-packages/base_python/client.py", line 166, in read_stream
    for message in method(fields=fields):
  File "/usr/local/lib/python3.7/site-packages/source_hubspot/api.py", line 220, in list
    yield from self.read(partial(self._api.get, url=self.url))
  File "/usr/local/lib/python3.7/site-packages/source_hubspot/api.py", line 294, in read
    yield from self._filter_dynamic_fields(self._filter_old_records(self._transform(self._read(getter, params))))
  File "/usr/local/lib/python3.7/site-packages/source_hubspot/api.py", line 226, in _filter_dynamic_fields
    for record in records:
  File "/usr/local/lib/python3.7/site-packages/source_hubspot/api.py", line 252, in _filter_old_records
    for record in records:
  File "/usr/local/lib/python3.7/site-packages/source_hubspot/api.py", line 235, in _transform
    for record in records:
  File "/usr/local/lib/python3.7/site-packages/source_hubspot/api.py", line 262, in _read
    response = getter(params=params)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/source_hubspot/api.py", line 181, in get
    return self._parse_and_handle_errors(response)
  File "/usr/local/lib/python3.7/site-packages/source_hubspot/api.py", line 160, in _parse_and_handle_errors
    raise HubspotAccessDenied(message, response=response)
source_hubspot.errors.HubspotAccessDenied: This hapikey (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx) does not have proper permissions! (requires any of [automation-access])

```

</details>

## Steps to Reproduce
1. Connect Hubspot to BigQuery (or somewhere else)
2. Trigger a sync
3. Happens

## Are you willing to submit a PR?

No

**Comment by bazarnov** [comment]
The right way for this, is to check the permissions before we show the list of streams available for the user and start fetching the data, however `Hubspot` does not seem to have any handy functionality to retrieve the list of endpoints available for the fetch, so the alternative here could also be: 
- leave the `workflows` stream in place, but instead of failing with permissions error we print the warning that `Stream <name>: API key requires some additional permissions....` and simply skip this stream,  as it cannot be processed using small permissions scope.
- add note into documentation about this behaviour 

This solution keeps the existing functionality of the connector and will process all available streams for particular API Key, the downside here are empty tables, they would be created

**Comment by sherifnada** [comment]
@bazarnov 

I like solution 4 since it is very predictable and maintains a single connector/interface for Hubspot.
