### ISSUE TITLE
Sentry connector fails on normalization step for some projects

### ISSUE THREAD

**Issue by arnoo** [airbytehq/airbyte#49808]
### Connector Name

sentry

### Connector Version

0.5.3

### What step the error happened?

During the sync

### Relevant information

I get an error in the normalization process. I have tried to remove the table, but it did not help.

### Relevant log output

```shell
723
2024-12-16 10:11:56 normalization > Finished running 31 table models in 14.67s.
724
2024-12-16 10:11:56 normalization > Completed with 1 error and 0 warnings:
725
2024-12-16 10:11:56 normalization > Database Error in model backend_project_detail_options (models/generated/airbyte_tables/sentry_data/backend_project_detail_options.sql)
726
2024-12-16 10:11:56 normalization >   1292 (22007): Truncated incorrect INTEGER value: 'true'
727
2024-12-16 10:11:56 normalization >   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/sentry_data/backend_project_detail_options.sql
728
2024-12-16 10:11:56 normalization > Done. PASS=30 WARN=0 ERROR=1 SKIP=0 TOTAL=31
729
2024-12-16 10:11:56 normalization > closed ssh tunnel
730
2024-12-16 10:11:56 platform > Terminating normalization process...
731
2024-12-16 10:11:56 normalization > Warning: Permanently added 'data.hozana.org,141.94.165.241' (ECDSA) to the list of known hosts.
732
2024-12-16 10:11:56 normalization > Exit request sent.
733
2024-12-16 10:11:56 platform > Normalization failed for job 9724.
734
io.airbyte.workers.exception.WorkerException: Normalization process did not terminate normally (exit code: 1)
735
        at io.airbyte.workers.normalization.DefaultNormalizationRunner.close(DefaultNormalizationRunner.java:186) ~[io.airbyte-airbyte-commons-worker-0.51.0.jar:?]
736
        at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:89) ~[io.airbyte-airbyte-commons-worker-0.51.0.jar:?]
737
        at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:38) ~[io.airbyte-airbyte-commons-worker-0.51.0.jar:?]
738
        at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:142) ~[io.airbyte-airbyte-workers-0.51.0.jar:?]
739
        at io.airbyte.workers.temporal.sync.NormalizationActivityImpl.lambda$normalize$2(NormalizationActivityImpl.java:194) ~[io.airbyte-airbyte-workers-0.51.0.jar:?]
740
        at io.airbyte.commons.temporal.HeartbeatUtils.withBackgroundHeartbeat(HeartbeatUtils.java:57) ~[io.airbyte-airbyte-commons-temporal-core-0.51.0.jar:?]
741
        at io.airbyte.workers.temporal.sync.NormalizationActivityImpl.normalize(NormalizationActivityImpl.java:144) ~[io.airbyte-airbyte-workers-0.51.0.jar:?]
742
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
743
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
744
        at io.temporal.internal.activity.RootActivityInboundCallsInterceptor$POJOActivityInboundCallsInterceptor.executeActivity(RootActivityInboundCallsInterceptor.java:64) ~[temporal-sdk-1.22.3.jar:?]
745
        at io.temporal.internal.activity.RootActivityInboundCallsInterceptor.execute(RootActivityInboundCallsInterceptor.java:43) ~[temporal-sdk-1.22.3.jar:?]
746
        at io.temporal.internal.activity.ActivityTaskExecutors$BaseActivityTaskExecutor.execute(ActivityTaskExecutors.java:107) ~[temporal-sdk-1.22.3.jar:?]
747
        at io.temporal.internal.activity.ActivityTaskHandlerImpl.handle(ActivityTaskHandlerImpl.java:124) ~[temporal-sdk-1.22.3.jar:?]
748
        at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handleActivity(ActivityWorker.java:278) ~[temporal-sdk-1.22.3.jar:?]
749
        at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:243) ~[temporal-sdk-1.22.3.jar:?]
750
        at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:216) ~[temporal-sdk-1.22.3.jar:?]
751
        at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:105) ~[temporal-sdk-1.22.3.jar:?]
752
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
753
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
754
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
755
2024-12-16 10:11:56 platform > Normalization executed in 37 seconds for job 9724.
756
2024-12-16 10:11:56 platform > Normalization summary: io.airbyte.config.NormalizationSummary@42987aa3[startTime=1734343879331,endTime=1734343916600,failures=[io.airbyte.config.FailureReason@5e7b3b6a[failureOrigin=normalization,failureType=system_error,internalMessage=1292 (22007): Truncated incorrect INTEGER value: 'true',externalMessage=Normalization failed during the dbt run. This may indicate a problem with the data itself.,metadata=io.airbyte.config.Metadata@7544a83b[additionalProperties={attemptNumber=9, jobId=9724, from_trace_message=true}],stacktrace=AirbyteDbtError: 
757
11 of 31 ERROR creating table model sentry_data.backend_project_detail_options.......................................... [ERROR in 0.13s]
758
Database Error in model backend_project_detail_options (models/generated/airbyte_tables/sentry_data/backend_project_detail_options.sql)
759
  1292 (22007): Truncated incorrect INTEGER value: 'true'
760
  compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/sentry_data/backend_project_detail_options.sql
761
11 of 31 ERROR creating table model sentry_data.backend_project_detail_options.......................................... [ERROR in 0.13s]
762
Database Error in model backend_project_detail_options (models/generated/airbyte_tables/sentry_data/backend_project_detail_options.sql)
763
  1292 (22007): Truncated incorrect INTEGER value: 'true'
764
  compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/sentry_data/backend_project_detail_options.sql,retryable=<null>,timestamp=1734343916598,additionalProperties={}], io.airbyte.config.FailureReason@5d1dcf7e[failureOrigin=normalization,failureType=system_error,internalMessage=1292 (22007): Truncated incorrect INTEGER value: 'true',externalMessage=Normalization failed during the dbt run. This may indicate a problem with the data itself.,metadata=io.airbyte.config.Metadata@5c51fb1c[additionalProperties={attemptNumber=9, jobId=9724, from_trace_message=true}],stacktrace=AirbyteDbtError: 
765
11 of 31 ERROR creating table model sentry_data.backend_project_detail_options.......................................... [ERROR in 0.13s]
766
Database Error in model backend_project_detail_options (models/generated/airbyte_tables/sentry_data/backend_project_detail_options.sql)
767
  1292 (22007): Truncated incorrect INTEGER value: 'true'
768
  compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/sentry_data/backend_project_detail_options.sql
769
11 of 31 ERROR creating table model sentry_data.backend_project_detail_options.......................................... [ERROR in 0.13s]
770
Database Error in model backend_project_detail_options (models/generated/airbyte_tables/sentry_data/backend_project_detail_options.sql)
771
  1292 (22007): Truncated incorrect INTEGER value: 'true'
772
compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/sentry_data/backend_project_detail_options.sql,retryable=<null>,timestamp=1734343916598,additionalProperties={}]],additionalProperties={}]
773
2024-12-16 10:11:56 platform > 
774
2024-12-16 10:11:56 platform > ----- END DEFAULT NORMALIZATION -----
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Normalization is a deprecated feature please upgrade your destination to v2 (typing and deduping).
