### ISSUE TITLE
[source-dynamodb] Checksum Error during sync with no further explanation

### ISSUE THREAD

**Issue by groccaIM** [airbytehq/airbyte#49805]
### Connector Name

source-dynamodb

### Connector Version

0.3.6

### What step the error happened?

During the sync

### Relevant information

When readFromSource, i get an exception from BufferedReplicationWorker. Right after the tables in destination are prepared, I get the checksum error.
`2024-12-16 00:14:22 source > ERROR i.a.i.b.AirbyteExceptionHandler(uncaughtException):26 Something went wrong in the connector. See the logs for more details. software.amazon.awssdk.core.exception.Crc32MismatchException: Expected 3139043157 as the Crc32 checksum but the actual calculated checksum was 3260888086`

### Relevant log output

```shell
2024-12-16 00:14:22 source > ERROR i.a.i.b.AirbyteExceptionHandler(uncaughtException):26 Something went wrong in the connector. See the logs for more details. software.amazon.awssdk.core.exception.Crc32MismatchException: Expected 3139043157 as the Crc32 checksum but the actual calculated checksum was 3260888086
        at software.amazon.awssdk.core.exception.Crc32MismatchException$BuilderImpl.build(Crc32MismatchException.java:88) ~[sdk-core-2.18.1.jar:?]
        at software.amazon.awssdk.core.internal.util.Crc32ChecksumValidatingInputStream.validateChecksum(Crc32ChecksumValidatingInputStream.java:62) ~[sdk-core-2.18.1.jar:?]
        at software.amazon.awssdk.core.internal.util.Crc32ChecksumValidatingInputStream.close(Crc32ChecksumValidatingInputStream.java:50) ~[sdk-core-2.18.1.jar:?]
        at java.io.FilterInputStream.close(FilterInputStream.java:179) ~[?:?]
        at software.amazon.awssdk.utils.FunctionalUtils.lambda$safeRunnable$5(FunctionalUtils.java:124) ~[utils-2.18.1.jar:?]
        at software.amazon.awssdk.utils.FunctionalUtils.invokeSafely(FunctionalUtils.java:140) ~[utils-2.18.1.jar:?]
        at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonResponseHandler.lambda$handle$2(JsonResponseHandler.java:87) ~[aws-json-protocol-2.18.1.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonResponseHandler.handle(JsonResponseHandler.java:87) ~[aws-json-protocol-2.18.1.jar:?]
        at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonResponseHandler.handle(JsonResponseHandler.java:36) ~[aws-json-protocol-2.18.1.jar:?]
        at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonResponseHandler.handle(AwsJsonResponseHandler.java:43) ~[aws-json-protocol-2.18.1.jar:?]
        at software.amazon.awssdk.core.http.MetricCollectingHttpResponseHandler.lambda$handle$0(MetricCollectingHttpResponseHandler.java:52) ~[sdk-core-2.18.1.jar:?]
        at software.amazon.awssdk.core.internal.util.MetricUtils.measureDurationUnsafe(MetricUtils.java:63) ~[sdk-core-2.18.1.jar:?]
        at software.amazon.awssdk.core.http.MetricCollectingHttpResponseHandler.handle(MetricCollectingHttpResponseHandler.java:52) ~[sdk-core-2.18.1.jar:?]
        at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler$Crc32ValidationResponseHandler.handle(AwsSyncClientHandler.java:95) ~[aws-core-2.18.1.jar:?]
        at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$resultTransformationResponseHandler$8(BaseClientHandler.java:283) ~[sdk-core-2.18.1.jar:?]
        at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleSuccessResponse(CombinedResponseHandler.java:99) ~[sdk-core-2.18.1.jar:?]
        at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:75) ~[sdk-core-2.18.1.jar:?]
        at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60) ~[sdk-core-2.18.1.jar:?]
        at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41) ~[sdk-core-2.18.1.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40) ~[sdk-core-2.18.1.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30) ~[sdk-core-2.18.1.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[sdk-core-2.18.1.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73) ~[sdk-core-2.18.1.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42) ~[sdk-core-2.18.1.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78) ~[sdk-core-2.18.1.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40) ~[sdk-core-2.18.1.jar:?]
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
I added the issue to the team backlog, but currently, Dynamo isn't scheduled for improvements in the roadmap. @groccaIM, feel free to reach out to me on Slack if you'd like to help with the fix.

**Comment by nourbenhassen** [comment]
@marcosmarxm @groccaIM what's the update on this issue ? I'd like to contribute as well if possible

**Comment by groccaIM** [comment]
If you're looking for a temporary fix, we export our data from dynamodb to s3 on a daily basis, and then use the certified s3 connector with airbyte.
