### ISSUE TITLE
[destination-mongodb] Format specifier exception when connecting to MongoDB destination

### ISSUE THREAD

**Issue by shybovycha** [airbytehq/airbyte#49829]
### Connector Name

destination-mongodb

### Connector Version

0.2.0

### What step the error happened?

Configuring a new connector

### Relevant information

When setting up the source connector for MongoDB and pointing it to my local instance running on Docker, I get an error "Configuration check failed"

I have tried various combinations of credentials, auth methods and replica set addresses but it all seems to fall into the same code path.

### Relevant log output

```shell
2024-12-17 05:01:27,017 [main]  ERROR   i.a.w.i.VersionedAirbyteStreamFactory(internalLog):310 - ERROR i.a.i.d.m.MongodbDestination(check):85 Check failed. java.util.MissingFormatArgumentException: Format specifier '%s'
        at java.util.Formatter.format(Formatter.java:2688) ~[?:?]
        at java.util.Formatter.format(Formatter.java:2625) ~[?:?]
        at java.lang.String.format(String.java:4143) ~[?:?]
        at io.airbyte.integrations.destination.mongodb.MongodbDestination.buildConnectionString(MongodbDestination.java:174) ~[io.airbyte.airbyte-integrations.connectors-destination-mongodb-24.0.2.jar:?]
        at io.airbyte.integrations.destination.mongodb.MongodbDestination.getConnectionString(MongodbDestination.java:150) ~[io.airbyte.airbyte-integrations.connectors-destination-mongodb-24.0.2.jar:?]
        at io.airbyte.integrations.destination.mongodb.MongodbDestination.getDatabase(MongodbDestination.java:136) ~[io.airbyte.airbyte-integrations.connectors-destination-mongodb-24.0.2.jar:?]
        at io.airbyte.integrations.destination.mongodb.MongodbDestination.check(MongodbDestination.java:71) ~[io.airbyte.airbyte-integrations.connectors-destination-mongodb-24.0.2.jar:?]
        at io.airbyte.integrations.base.ssh.SshTunnel.sshWrap(SshTunnel.java:270) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
        at io.airbyte.integrations.base.ssh.SshWrappedDestination.check(SshWrappedDestination.java:67) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
        at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:124) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
        at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:99) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
        at io.airbyte.integrations.destination.mongodb.MongodbDestination.main(MongodbDestination.java:64) ~[io.airbyte.airbyte-integrations.connectors-destination-mongodb-24.0.2.jar:?]
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Hello @shybovycha can you share the format of host and configs you're using to access the local Mongo instance?

**Comment by shybovycha** [comment]
The format of host - as in the type of deployment? It is a local 2-node replica set, spinning in Docker. Pretty much just following the tutorial https://blog.devops.dev/setting-up-mongodb-replica-set-with-docker-compose-006f578dcdad

**Comment by saadqc** [comment]
@shybovycha did it work? facing same issue with 0.2.0

**Comment by shybovycha** [comment]
@saadqc did what work? this is a bug report with no workaround suggestions 🤷

**Comment by Renanrmx** [comment]
@davinchia Can you tell me if this bug is on the 'Destinations-to-certify' list like Clickhouse?
I had tried using Clickhouse but had issue #36199 , so I tried an alternative with MongoDB and it also has a bug 😩
