### ISSUE TITLE
[source-linkedin-pages] Linkedin pages source config test fails with "Permission denied: '/tmp/config.json'"

### ISSUE THREAD

**Issue by AshvinBambhaniya2003** [airbytehq/airbyte#49860]
### Connector Name

source-linkedin-pages

### Connector Version

1.1.6

### What step the error happened?

During test the config 

### Relevant information

when i run command `meltano config tap-linkedin-pages test` i got this error

### Relevant log output

```shell
Plugin configuration is invalid
Catalog discovery failed: command ['/home/ashvin.bambhaniya/workspace/meltano/my-meltano-project/.meltano/extractors/tap-linkedin-pages/venv/bin/tap-airbyte', '--config', '/home/ashvin.bambhaniya/workspace/meltano/my-meltano-project/.meltano/run/tap-linkedin-pages/tap.62146e16-9d7a-4829-877f-e36fb878ae26.config.json', '--discover'] returned 1 with stderr:
 2024-12-18 18:09:42,769 | INFO     | tap-airbyte          | Checking for docker on PATH.
2024-12-18 18:09:42,778 | INFO     | tap-airbyte          | Found docker on PATH.
2024-12-18 18:09:42,778 | INFO     | tap-airbyte          | Checking docker version.
2024-12-18 18:09:42,823 | INFO     | tap-airbyte          | Successfully executed docker version.
2024-12-18 18:09:45,252 | CRITICAL | tap-airbyte          | Error starting the sync. This could be due to an invalid configuration or catalog. Please contact Support for assistance. Error: [Errno 13] Permission denied: '/tmp/config.json'
tap_airbyte.tap.AirbyteException: Traceback (most recent call last):
  File "/airbyte/integration_code/source_declarative_manifest/run.py", line 94, in _get_local_yaml_source
    config, catalog, state = _parse_inputs_into_config_catalog_state(args)
  File "/airbyte/integration_code/source_declarative_manifest/run.py", line 210, in _parse_inputs_into_config_catalog_state
    ConcurrentDeclarativeSource.read_config(parsed_args.config)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/connector.py", line 45, in read_config
    config = BaseConnector._read_json_file(config_path)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/connector.py", line 55, in _read_json_file
    with open(file_path, "r") as file:
PermissionError: [Errno 13] Permission denied: '/tmp/config.json'

Traceback (most recent call last):
  File "/home/ashvin.bambhaniya/workspace/meltano/my-meltano-project/.meltano/extractors/tap-linkedin-pages/venv/bin/tap-airbyte", line 8, in <module>
    sys.exit(TapAirbyte.cli())
  File "/home/ashvin.bambhaniya/workspace/meltano/my-meltano-project/.meltano/extractors/tap-linkedin-pages/venv/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ashvin.bambhaniya/workspace/meltano/my-meltano-project/.meltano/extractors/tap-linkedin-pages/venv/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ashvin.bambhaniya/workspace/meltano/my-meltano-project/.meltano/extractors/tap-linkedin-pages/venv/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ashvin.bambhaniya/workspace/meltano/my-meltano-project/.meltano/extractors/tap-linkedin-pages/venv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ashvin.bambhaniya/workspace/meltano/my-meltano-project/.meltano/extractors/tap-linkedin-pages/venv/lib/python3.9/site-packages/tap_airbyte/tap.py", line 286, in cli
    tap: TapAirbyte = cls(  # type: ignore
  File "/home/ashvin.bambhaniya/workspace/meltano/my-meltano-project/.meltano/extractors/tap-linkedin-pages/venv/lib/python3.9/site-packages/singer_sdk/tap_base.py", line 109, in __init__
    self.setup_mapper()
  File "/home/ashvin.bambhaniya/workspace/meltano/my-meltano-project/.meltano/extractors/tap-linkedin-pages/venv/lib/python3.9/site-packages/singer_sdk/tap_base.py", line 179, in setup_mapper
    self.mapper.register_raw_streams_from_catalog(self.catalog)
  File "/home/ashvin.bambhaniya/workspace/meltano/my-meltano-project/.meltano/extractors/tap-linkedin-pages/venv/lib/python3.9/site-packages/singer_sdk/tap_base.py", line 172, in catalog
    self._catalog = self.input_catalog or self._singer_catalog
  File "/home/ashvin.bambhaniya/workspace/meltano/my-meltano-project/.meltano/extractors/tap-linkedin-pages/venv/lib/python3.9/site-packages/singer_sdk/tap_base.py", line 325, in _singer_catalog
    for stream in self.streams.values()
  File "/home/ashvin.bambhaniya/workspace/meltano/my-meltano-project/.meltano/extractors/tap-linkedin-pages/venv/lib/python3.9/site-packages/singer_sdk/tap_base.py", line 134, in streams
    for stream in self.load_streams():
  File "/home/ashvin.bambhaniya/workspace/meltano/my-meltano-project/.meltano/extractors/tap-linkedin-pages/venv/lib/python3.9/site-packages/singer_sdk/tap_base.py", line 358, in load_streams
    for stream in self.discover_streams():
  File "/home/ashvin.bambhaniya/workspace/meltano/my-meltano-project/.meltano/extractors/tap-linkedin-pages/venv/lib/python3.9/site-packages/tap_airbyte/tap.py", line 886, in discover_streams
    for stream in self.airbyte_catalog["streams"]:
  File "/home/ashvin.bambhaniya/workspace/meltano/my-meltano-project/.meltano/extractors/tap-linkedin-pages/venv/lib/python3.9/site-packages/tap_airbyte/tap.py", line 715, in airbyte_catalog
    self._process_log_message(message)
  File "/home/ashvin.bambhaniya/workspace/meltano/my-meltano-project/.meltano/extractors/tap-linkedin-pages/venv/lib/python3.9/site-packages/tap_airbyte/tap.py", line 637, in _process_log_message
    raise exc
tap_airbyte.tap.AirbyteException: Traceback (most recent call last):
  File "/airbyte/integration_code/source_declarative_manifest/run.py", line 94, in _get_local_yaml_source
    config, catalog, state = _parse_inputs_into_config_catalog_state(args)
  File "/airbyte/integration_code/source_declarative_manifest/run.py", line 210, in _parse_inputs_into_config_catalog_state
    ConcurrentDeclarativeSource.read_config(parsed_args.config)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/connector.py", line 45, in read_config
    config = BaseConnector._read_json_file(config_path)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/connector.py", line 55, in _read_json_file
    with open(file_path, "r") as file:
PermissionError: [Errno 13] Permission denied: '/tmp/config.json'
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by AshvinBambhaniya2003** [comment]
@alafanechere any update on this?

**Comment by AshvinBambhaniya2003** [comment]
@alafanechere this issue is similar like #49468
