### ISSUE TITLE
airbyte-ci failure when building a connector

### ISSUE THREAD

**Issue by pai911** [airbytehq/airbyte#50408]
### Topic

airbyte-ci

### Relevant information

I suspect it's related to dagger veriosn, but I am not sure.

Could anyone shade some light on this issue?

Tried tag version: `v1.3.0`

Thank you

```
╰─ airbyte-ci connectors --name=source-coresignal-company build

[10:12:14] INFO     root: Setting working directory to /Users/paijung-shuo/workspace/repos/github/airbyte                                       ensure_repo_root.py:58
[10:12:16] INFO     pipelines: airbyte-ci is up to date. Installed version: 4.44.1. Latest version: 4.44.1                                           auto_update.py:88
           INFO     pipelines: Called with dagger run: False                                                                                         airbyte_ci.py:126
[10:12:20] INFO     pipelines.cli.dagger_run: Running command: ['/usr/local/bin/dagger', '--silent', 'run',                                          dagger_run.py:119
                    '/Users/paijung-shuo/Library/Caches/pypoetry/virtualenvs/pipelines-LYfKkJ6r-py3.10/bin/airbyte-ci', 'connectors',
                    '--name=source-coresignal-company', 'build']
[10:12:23] INFO     root: Setting working directory to /Users/paijung-shuo/workspace/repos/github/airbyte                                       ensure_repo_root.py:58
[10:12:25] INFO     pipelines: airbyte-ci is up to date. Installed version: 4.44.1. Latest version: 4.44.1                                           auto_update.py:88
           INFO     pipelines: Called with dagger run: True                                                                                          airbyte_ci.py:126
[10:12:32] INFO     pipelines: Will run on the following 1 connectors: source-coresignal-company.                                                       commands.py:30
           INFO     pipelines: Running Dagger Command build...                                                                           dagger_pipeline_command.py:30
           INFO     pipelines: If you're running this command for the first time the Dagger engine image will be pulled, it can take a   dagger_pipeline_command.py:31
                    short minute...
           INFO     pipelines: Saving dagger logs to:                                                                                    dagger_pipeline_command.py:41
                    /Users/paijung-shuo/workspace/repos/github/airbyte/airbyte-ci/connectors/pipelines/pipeline_reports/airbyte-ci/conne
                    ctors/build/manual/release-130/1734977545/542655d046dc62d2ca51789ad3544745156ce70b/dagger.log
           INFO     pipelines: Building connectors for ['linux/amd64'], use --architecture to change this.                                              commands.py:45
           INFO     Build connector source-coresignal-company: Should send status check: False                                                 pipeline_context.py:222
           INFO     pipelines: Dagger logs saved to                                                                                      dagger_pipeline_command.py:56
                    /Users/paijung-shuo/workspace/repos/github/airbyte/airbyte-ci/connectors/pipelines/pipeline_reports/airbyte-ci/conne
                    ctors/build/manual/release-130/1734977545/542655d046dc62d2ca51789ad3544745156ce70b/dagger.log
Traceback (most recent call last):
  File "/Users/paijung-shuo/Library/Caches/pypoetry/virtualenvs/pipelines-LYfKkJ6r-py3.10/bin/airbyte-ci", line 6, in <module>
    sys.exit(airbyte_ci())
  File "/Users/paijung-shuo/Library/Caches/pypoetry/virtualenvs/pipelines-LYfKkJ6r-py3.10/lib/python3.10/site-packages/asyncclick/core.py", line 1205, in __call__
    return anyio.run(self._main, main, args, kwargs, **opts)
  File "/Users/paijung-shuo/Library/Caches/pypoetry/virtualenvs/pipelines-LYfKkJ6r-py3.10/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 68, in run
    return asynclib.run(func, *args, **backend_options)
  File "/Users/paijung-shuo/Library/Caches/pypoetry/virtualenvs/pipelines-LYfKkJ6r-py3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 204, in run
    return native_run(wrapper(), debug=debug)
  File "/opt/anaconda3/envs/airbyte-connector-310/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/anaconda3/envs/airbyte-connector-310/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Users/paijung-shuo/Library/Caches/pypoetry/virtualenvs/pipelines-LYfKkJ6r-py3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 199, in wrapper
    return await func(*args)
  File "/Users/paijung-shuo/Library/Caches/pypoetry/virtualenvs/pipelines-LYfKkJ6r-py3.10/lib/python3.10/site-packages/asyncclick/core.py", line 1208, in _main
    return await main(*args, **kwargs)
  File "/Users/paijung-shuo/Library/Caches/pypoetry/virtualenvs/pipelines-LYfKkJ6r-py3.10/lib/python3.10/site-packages/asyncclick/core.py", line 1120, in main
    rv = await self.invoke(ctx)
  File "/Users/paijung-shuo/Library/Caches/pypoetry/virtualenvs/pipelines-LYfKkJ6r-py3.10/lib/python3.10/site-packages/asyncclick/core.py", line 1739, in invoke
    return await _process_result(await sub_ctx.command.invoke(sub_ctx))
  File "/Users/paijung-shuo/Library/Caches/pypoetry/virtualenvs/pipelines-LYfKkJ6r-py3.10/lib/python3.10/site-packages/asyncclick/core.py", line 1739, in invoke
    return await _process_result(await sub_ctx.command.invoke(sub_ctx))
  File "/Users/paijung-shuo/workspace/repos/github/airbyte/airbyte-ci/connectors/pipelines/pipelines/cli/dagger_pipeline_command.py", line 48, in invoke
    pipeline_success = await super().invoke(ctx)
  File "/Users/paijung-shuo/Library/Caches/pypoetry/virtualenvs/pipelines-LYfKkJ6r-py3.10/lib/python3.10/site-packages/asyncclick/core.py", line 1485, in invoke
    return await ctx.invoke(self.callback, **ctx.params)
  File "/Users/paijung-shuo/Library/Caches/pypoetry/virtualenvs/pipelines-LYfKkJ6r-py3.10/lib/python3.10/site-packages/asyncclick/core.py", line 824, in invoke
    rv = await rv
  File "/Users/paijung-shuo/workspace/repos/github/airbyte/airbyte-ci/connectors/pipelines/pipelines/airbyte_ci/connectors/build_image/commands.py", line 74, in build
    await run_connectors_pipelines(
  File "/Users/paijung-shuo/workspace/repos/github/airbyte/airbyte-ci/connectors/pipelines/pipelines/airbyte_ci/connectors/pipeline.py", line 98, in run_connectors_pipelines
    async with dagger.Connection(Config(log_output=dagger_logs_output, execute_timeout=execute_timeout)) as dagger_client:
  File "/Users/paijung-shuo/Library/Caches/pypoetry/virtualenvs/pipelines-LYfKkJ6r-py3.10/lib/python3.10/site-packages/dagger/_connection.py", line 65, in __aenter__
    return await engine.setup_client(conn)
  File "/Users/paijung-shuo/Library/Caches/pypoetry/virtualenvs/pipelines-LYfKkJ6r-py3.10/lib/python3.10/site-packages/dagger/_engine/conn.py", line 87, in setup_client
    await self.progress.update("Establishing connection to the API server")
  File "/Users/paijung-shuo/Library/Caches/pypoetry/virtualenvs/pipelines-LYfKkJ6r-py3.10/lib/python3.10/site-packages/dagger/_engine/progress.py", line 33, in update
    if self.status:
AttributeError: 'Progress' object has no attribute 'status'
```

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 180 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.
