### ISSUE TITLE
[MySQL Destination] Normalization fails with MySQL destination - error in SQL syntax

### ISSUE THREAD

**Issue by philippeboyd** [airbytehq/airbyte#5117]
## Environment
- **Airbyte version**:  0.29.1-alpha
- **OS Version / Instance**: GCP COS
- **Deployment**: Docker
- **Source Connector and version**: Snowflake 0.1.0
- **Destination Connector and version**: MySQL 0.1.10
- **Severity**: High
- **Step where error happened**: Sync

**Server version: 5.7.33-log Source distribution**

Datasource is pretty simple
![image](https://user-images.githubusercontent.com/3239656/127678474-c6ebb8c8-59a2-484c-a050-5eaebe3216a4.png)

## Current Behavior
Normalization fails when syncing Snowflake to MySQL with
```
1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '__dbt__CTE__ltv_data_campaign_all_ab1 as (
```

Here's the first part of the generated SQL file located in `build/run/airbyte_utils/models/generated/airbyte_tables/result_db/ltv_data_campaign_all.sql`

```sql
  create  table
    result_db.`ltv_data_campaign_all__dbt_tmp`
  as (

-- ERROR COMES FROM THE FOLLOWING LINE
with __dbt__CTE__ltv_data_campaign_all_ab1 as (

-- SQL model to parse JSON blob stored in a single column and extract into separated field columns as described by the JSON Schema
select
    json_value(_airbyte_data,
    '$."T"') as t,
    json_value(_airbyte_data,
    '$."CUMSUM"') as cumsum,
    json_value(_airbyte_data,
    '$."CAMPAIGN_ID"') as campaign_id,
    json_value(_airbyte_data,
    '$."TOTAL_USERS"') as total_users,
    _airbyte_emitted_at
from result_db._airbyte_raw_ltv_data_campaign_all
-- ltv_data_campaign_all
),  __dbt__CTE__ltv_data_campaign_all_ab2 as (

-- SQL model to cast each column to its adequate SQL type converted from the JSON schema type
select
    cast(t as
    float
) as t,
    cast(cumsum as
    float
) as cumsum,
    cast(campaign_id as
    float

...
```

## Expected Behavior
Normalization should not fail.

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```
2021-07-30 15:26:58 INFO () LineGobbler(voidCall):85 - Processing destination_catalog.json...
2021-07-30 15:26:58 INFO () LineGobbler(voidCall):85 -   Generating airbyte_ctes/result_db/ltv_data_campaign_all_ab1.sql from LTV_DATA_CAMPAIGN_ALL
2021-07-30 15:26:58 INFO () LineGobbler(voidCall):85 -   Generating airbyte_ctes/result_db/ltv_data_campaign_all_ab2.sql from LTV_DATA_CAMPAIGN_ALL
2021-07-30 15:26:58 INFO () LineGobbler(voidCall):85 -   Generating airbyte_ctes/result_db/ltv_data_campaign_all_ab3.sql from LTV_DATA_CAMPAIGN_ALL
2021-07-30 15:26:58 INFO () LineGobbler(voidCall):85 -   Generating airbyte_tables/result_db/ltv_data_campaign_all.sql from LTV_DATA_CAMPAIGN_ALL
2021-07-30 15:26:59 INFO () LineGobbler(voidCall):85 - Running with dbt=0.19.0
2021-07-30 15:27:01 INFO () LineGobbler(voidCall):85 - [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
2021-07-30 15:27:01 INFO () LineGobbler(voidCall):85 - There are 1 unused configuration paths:
2021-07-30 15:27:01 INFO () LineGobbler(voidCall):85 - - models.airbyte_utils.generated.airbyte_views
2021-07-30 15:27:01 INFO () LineGobbler(voidCall):85 - 
2021-07-30 15:27:01 INFO () LineGobbler(voidCall):85 - Found 4 models, 0 tests, 0 snapshots, 0 analyses, 383 macros, 0 operations, 0 seed files, 1 source, 0 exposures
2021-07-30 15:27:01 INFO () LineGobbler(voidCall):85 - 
2021-07-30 15:27:02 INFO () LineGobbler(voidCall):85 - 15:27:02 | Concurrency: 1 threads (target='prod')
2021-07-30 15:27:02 INFO () LineGobbler(voidCall):85 - 15:27:02 | 
2021-07-30 15:27:02 INFO () LineGobbler(voidCall):85 - 15:27:02 | 1 of 1 START table model result_db.ltv_data_campaign_all............................................... [RUN]
2021-07-30 15:27:02 INFO () LineGobbler(voidCall):85 - 15:27:02 | 1 of 1 ERROR creating table model result_db.ltv_data_campaign_all...................................... [[31mERROR[0m in 0.43s]
2021-07-30 15:27:02 INFO () LineGobbler(voidCall):85 - 15:27:02 | 
2021-07-30 15:27:02 INFO () LineGobbler(voidCall):85 - 15:27:02 | Finished running 1 table model in 1.54s.
2021-07-30 15:27:02 INFO () LineGobbler(voidCall):85 - 
2021-07-30 15:27:02 INFO () LineGobbler(voidCall):85 - [31mCompleted with 1 error and 0 warnings:[0m
2021-07-30 15:27:02 INFO () LineGobbler(voidCall):85 - 
2021-07-30 15:27:02 INFO () LineGobbler(voidCall):85 - [33mDatabase Error in model ltv_data_campaign_all (models/generated/airbyte_tables/result_db/ltv_data_campaign_all.sql)[0m
2021-07-30 15:27:02 INFO () LineGobbler(voidCall):85 -   1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '__dbt__CTE__ltv_data_campaign_all_ab1 as (
2021-07-30 15:27:02 INFO () LineGobbler(voidCall):85 -   
2021-07-30 15:27:02 INFO () LineGobbler(voidCall):85 -   -- SQL model to parse JSON blob stor' at line 8
2021-07-30 15:27:02 INFO () LineGobbler(voidCall):85 -   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/result_db/ltv_data_campaign_all.sql
2021-07-30 15:27:02 INFO () LineGobbler(voidCall):85 - 
2021-07-30 15:27:02 INFO () LineGobbler(voidCall):85 - Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
2021-07-30 15:27:03 INFO () TemporalAttemptExecution(lambda$getWorkerThread$2):149 - Completing future exceptionally...
io.airbyte.workers.WorkerException: Normalization Failed.
    at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:69) ~[io.airbyte-airbyte-workers-0.29.1-alpha.jar:?]
    at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:36) ~[io.airbyte-airbyte-workers-0.29.1-alpha.jar:?]
    at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:146) ~[io.airbyte-airbyte-workers-0.29.1-alpha.jar:?]
    at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: io.airbyte.workers.WorkerException: Normalization Failed.
    at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:66) ~[io.airbyte-airbyte-workers-0.29.1-alpha.jar:?]
    ... 3 more
    Suppressed: io.airbyte.workers.WorkerException: Normalization process wasn't successful
        at io.airbyte.workers.normalization.DefaultNormalizationRunner.close(DefaultNormalizationRunner.java:151) ~[io.airbyte-airbyte-workers-0.29.1-alpha.jar:?]
        at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:60) ~[io.airbyte-airbyte-workers-0.29.1-alpha.jar:?]
        at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:36) ~[io.airbyte-airbyte-workers-0.29.1-alpha.jar:?]
        at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:146) ~[io.airbyte-airbyte-workers-0.29.1-alpha.jar:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
2021-07-30 15:27:03 INFO () TemporalAttemptExecution(get):133 - Stopping cancellation check scheduling...
2021-07-30 15:27:03 WARN () POJOActivityTaskHandler$POJOActivityImplementation(execute):243 - Activity failure. ActivityId=0c035610-3956-3157-9bd4-c69a3b064d9c, activityType=Normalize, attempt=1
java.util.concurrent.ExecutionException: io.airbyte.workers.WorkerException: Normalization Failed.
    at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[?:?]
    at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2063) ~[?:?]
    at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:131) ~[io.airbyte-airbyte-workers-0.29.1-alpha.jar:?]
    at io.airbyte.workers.temporal.SyncWorkflow$NormalizationActivityImpl.normalize(SyncWorkflow.java:321) ~[io.airbyte-airbyte-workers-0.29.1-alpha.jar:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
    at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
    at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityInboundCallsInterceptor.execute(POJOActivityTaskHandler.java:277) ~[temporal-sdk-1.0.4.jar:?]
    at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityImplementation.execute(POJOActivityTaskHandler.java:216) ~[temporal-sdk-1.0.4.jar:?]
    at io.temporal.internal.sync.POJOActivityTaskHandler.handle(POJOActivityTaskHandler.java:181) ~[temporal-sdk-1.0.4.jar:?]
    at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:192) ~[temporal-sdk-1.0.4.jar:?]
    at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:154) ~[temporal-sdk-1.0.4.jar:?]
    at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73) ~[temporal-sdk-1.0.4.jar:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
    at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: io.airbyte.workers.WorkerException: Normalization Failed.
    at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:69) ~[io.airbyte-airbyte-workers-0.29.1-alpha.jar:?]
    at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:36) ~[io.airbyte-airbyte-workers-0.29.1-alpha.jar:?]
    at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:146) ~[io.airbyte-airbyte-workers-0.29.1-alpha.jar:?]
    ... 1 more
Caused by: io.airbyte.workers.WorkerException: Normalization Failed.
    at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:66) ~[io.airbyte-airbyte-workers-0.29.1-alpha.jar:?]
    at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:36) ~[io.airbyte-airbyte-workers-0.29.1-alpha.jar:?]
    at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:146) ~[io.airbyte-airbyte-workers-0.29.1-alpha.jar:?]
    ... 1 more
    Suppressed: io.airbyte.workers.WorkerException: Normalization process wasn't successful
        at io.airbyte.workers.normalization.DefaultNormalizationRunner.close(DefaultNormalizationRunner.java:151) ~[io.airbyte-airbyte-workers-0.29.1-alpha.jar:?]
        at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:60) ~[io.airbyte-airbyte-workers-0.29.1-alpha.jar:?]
        at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:36) ~[io.airbyte-airbyte-workers-0.29.1-alpha.jar:?]
        at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:146) ~[io.airbyte-airbyte-workers-0.29.1-alpha.jar:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```

</details>

## Steps to Reproduce
1. Have to simple table in snowflake
2. Setup Snowflake Source
3. Setup MySQL destination

**Comment by marcosmarxm** [comment]
@philippeboyd normalization doesn't work in mysql version 5.x. it's your case right? Take a look https://github.com/airbytehq/airbyte/issues/4989

**Comment by philippeboyd** [comment]
@marcosmarxm indeed that's the problem: the `with` keyword. I was under the assumption that Airbyte (with normalization) would be compatible with both 5.7.8+ and 8.0 [as per the doc](https://docs.airbyte.io/integrations/destinations/mysql#requirements)

![image](https://user-images.githubusercontent.com/3239656/129617830-f4c86d21-7bf4-4d21-927c-d6e8a3364f55.png)
