### ISSUE TITLE
Basic normalization fails on Google Ads data

### ISSUE THREAD

**Issue by zestyping** [airbytehq/airbyte#5162]
- **Airbyte version**:  0.28.1-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Google Ads 0.1.5
- **Destination Connector and version**: BigQuery 0.3.12
- **Severity**: High (sync fails)
- **Step where error happened**: Sync job

Looks like it was using `airbyte/normalization:0.1.37` as well for this run.

## Current Behavior
This error appears in the logs:

```
2021-08-03 17:20:18 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.8/site-packages/normalization/transform_catalog/stream_processor.py", line 535, in <listcomp>
2021-08-03 17:20:18 ERROR () LineGobbler(voidCall):85 -     return ", ".join([self.get_primary_key_from_path(column_names, path) for path in self.primary_key])
2021-08-03 17:20:18 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.8/site-packages/normalization/transform_catalog/stream_processor.py", line 557, in get_primary_key_from_path
2021-08-03 17:20:18 ERROR () LineGobbler(voidCall):85 -     raise ValueError(f"Unsupported nested path {'.'.join(path)} for stream {self.stream_name}")
2021-08-03 17:20:18 ERROR () LineGobbler(voidCall):85 - ValueError: Unsupported nested path customer.id for stream account_performance_report
```

followed by:

```
Caused by: io.airbyte.workers.WorkerException: Normalization Failed.
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:66) ~[io.airbyte-airbyte-workers-0.28.1-alpha.jar:?]
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:36) ~[io.airbyte-airbyte-workers-0.28.1-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:146) ~[io.airbyte-airbyte-workers-0.28.1-alpha.jar:?]
	... 1 more
	Suppressed: io.airbyte.workers.WorkerException: Normalization process wasn't successful
		at io.airbyte.workers.normalization.DefaultNormalizationRunner.close(DefaultNormalizationRunner.java:151) ~[io.airbyte-airbyte-workers-0.28.1-alpha.jar:?]
```

If I turn off normalization (by selecting "Raw data - no normalization"), the sync succeeds.

## Expected Behavior
Normalization should work.

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

[logs-75-0.txt](https://github.com/airbytehq/airbyte/files/6925972/logs-75-0.txt)

**Comment by zestyping** [comment]
Looks like this is a duplicate of #5088
