### ISSUE TITLE
Postgres connector creates a similar table for "Center", but tries to load data from another existing table "center"

### ISSUE THREAD

**Issue by cristiscu** [airbytehq/airbyte#5171]
## Enviroment
- **Airbyte version**:  0.28.2-alpha
- **OS Version / Instance**: Amazon Linux 2 on Amazon Workspaces
- **Deployment**: Docker
- **Source Connector and version**: Postgres 0.3.7 
- **Destination Connector and version**: Snowflake 0.3.11 
- **Severity**: Medium
- **Step where error happened**: Sync job

## Current Behavior
You have both a "Center" and a "center" table in Postgres (this is valid, because Postgres table names are case sensitive). When you transfer data from "Center" through Airbyte from Postgres to let's say Snowflake, with normalization, a similar table is properly created, but the Sync job tries to load data from "center" instead. Delete "center", and data will be properly loaded from "Center".

## Expected Behavior
When you transfer both metadata and data from "Center" with normalization, you expect a similar table created, and data loaded from the same "Center" table. Not from another existing "center" table.

## Logs
Look below for the following rows:
```
Message contained record from a stream that was not in the catalog.
 catalog: {"streams":[{"stream":{"name":"Center", ...
 message: {"type":"RECORD","record":{"stream":"center","data":{...

```
<details>
<summary>LOG</summary> 
2021-08-03 18:51:25 ERROR () LineGobbler(voidCall):85 - Exception in thread "main" java.lang.IllegalArgumentException: Message contained record from a stream that was not in the catalog. 
2021-08-03 18:51:25 ERROR () LineGobbler(voidCall):85 - catalog: {"streams":[{"stream":{"name":"Center","json_schema":{"type":"object","properties":{"id":{"type":"number"},"fax":{"type":"string"},"url":{"type":"string"},"city":{"type":"string"},"logo":{"type":"string"},"name":{"type":"string"},"address":{"type":"string"},"contact":{"type":"string"},"StatusId":{"type":"number"},"province":{"type":"string"},"timezone":{"type":"string"},"tollFree":{"type":"string"},"createdAt":{"type":"string"},"legalName":{"type":"string"},"updatedAt":{"type":"string"},"postalCode":{"type":"string"},"_ab_cdc_lsn":{"type":"number"},"phoneNumber":{"type":"string"},"sequenceName":{"type":"string"},"invoicePrefix":{"type":"string"},"AuthenticationId":{"type":"string"},"preauthorization":{"type":"boolean"},"_ab_cdc_deleted_at":{"type":"number"},"_ab_cdc_updated_at":{"type":"number"},"spaBookerLocationId":{"type":"number"},"userLocaleFieldValue":{"type":"string"}}},"supported_sync_modes":["full_refresh","incremental"],"source_defined_cursor":true,"default_cursor_field":[],"source_defined_primary_key":[["id"]],"namespace":"CDC"},"sync_mode":"incremental","cursor_field":[],"destination_sync_mode":"append_dedup","primary_key":[["id"]]}]} , 
2021-08-03 18:51:25 ERROR () LineGobbler(voidCall):85 - message: {"type":"RECORD","record":{"stream":"center","data":{"id":1,"name":"***","timezone":"America/Toronto","spaBookerLocationId":3510,"userLocaleFieldValue":"45997","createdAt":"2019-08-16T23:55:27.34661Z","updatedAt":"2019-08-16T23:55:27.34661Z","StatusId":3,"url":"https://***.com","_ab_cdc_updated_at":1628016683316,"_ab_cdc_lsn":16161089541632,"_ab_cdc_deleted_at":null},"emitted_at":1628016678681,"namespace":"CDC"}}
2021-08-03 18:51:25 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.throwUnrecognizedStream(BufferedStreamConsumer.java:197)
2021-08-03 18:51:25 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.acceptTracked(BufferedStreamConsumer.java:157)
2021-08-03 18:51:25 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.accept(FailureTrackingAirbyteMessageConsumer.java:66)
2021-08-03 18:51:25 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:167)
2021-08-03 18:51:25 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:148)
2021-08-03 18:51:25 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.snowflake.SnowflakeDestination.main(SnowflakeDestination.java:82)</details>

## Steps to Reproduce
1. Select table "Center" to transfer from Postgres to Snowflake
2. Reset works well, as empty tables are properly created
3. Sync fails with a logged error "Message contained record from a stream that was not in the catalog.", as described before.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by alexandr-shegeda** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Java-Connectors-625f0102b11304001e0f6c6e/issues/airbytehq/airbyte/5171?planning-poker) with ZenHub @DoNotPanicUA @VitaliiMaltsev @alexandertsukanov @etsybaev

**Comment by etsybaev** [comment]
Additionally checked for other connectors, the issue seems to be in destinations, probably some kind of "toUpperCase()\to LowerCase()" standardization is used. Here are examples for snowflake and MySQL destinations. Records from both tables appears to be migrated to a single table:

![Selection_207.png](https://images.zenhubusercontent.com/627269f99b780c901a3d24e2/13d05f37-82fc-4422-9303-2c45c2add740)
![Selection_210.png](https://images.zenhubusercontent.com/627269f99b780c901a3d24e2/fd74a049-e856-4fe4-a767-f54557a1dc58)

**Comment by cristiscu** [comment]
I would like to keep this open a bit longer. You came up with a lot of stuff and I had no time to review it.

**Comment by etsybaev** [comment]
@cristiscu I can confirm that basically issue exists, but it's on the destination side as we normalize names for destination connectors. The issue appears to be more comprehensive and reviewers some business solutions as the straightforward fix will break backward compatibility.  We're on it.
Thanks

**Comment by etsybaev** [comment]
RFC document
https://docs.google.com/document/d/1UqLrnISRd3yWv5wiE5Z5QhU3L1KMpq3YQvAi9HRbcwk/edit

**Comment by sherifnada** [comment]
relies on #5396

**Comment by cristiscu** [comment]
guys, you can go ahead and close it if you wish, as I really don't have time right now for this. :(

**Comment by etsybaev** [comment]
Could be also helpfuld https://app.zenhub.com/workspaces/java-connectors-625f0102b11304001e0f6c6e/issues/airbytehq/airbyte/13262

**Comment by grishick** [comment]
Proposals in RFC are blocked on https://github.com/airbytehq/airbyte/issues/13262

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 365 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.
