### ISSUE TITLE
MSSQL source: cann't connect instance with backslash name

### ISSUE THREAD

**Issue by PS-istarostenko** [airbytehq/airbyte#5327]
## Enviroment
- **Airbyte version**:  0.29.4-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: source-mssql:0.3.3
- **Severity**: Very low
- **Step where error happened**: Setup new connection

## Current Behavior
When setting up Microsoft SQL Server as a new source, while having an instance name in host (for example MSSQLSERVER.com\MYINSTANCE1), I get the following error:
```
Could not connect with provided configuration. Error: Cannot create PoolableConnectionFactory (The TCP/IP connection to the host MSSQLSERVER.com, port 1433 has failed. Error: "Connect timed out. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".)
```

Seems that the \MYINSTANCE part is not actually used to connect to the database. Probably because of the backslash character.

## Expected Behavior
Log the instance name next to the host name:
he TCP/IP connection to the host MSSQLSERVER.com\MYINSTANCE1, port 1433 has failed. Error: "Connect timed out.

## Logs
```
2021-08-11 04:48:17 INFO () TemporalAttemptExecution(get):110 - Executing worker wrapper. Airbyte version: 0.29.4-alpha
2021-08-11 04:48:17 INFO () LineGobbler(voidCall):85 - Checking if airbyte/source-mssql:0.3.3 exists...
2021-08-11 04:48:17 INFO () LineGobbler(voidCall):85 - airbyte/source-mssql:0.3.3 was found locally.
2021-08-11 04:48:17 INFO () DockerProcessFactory(create):146 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/6f293ad2-98c3-4bc7-a79b-e35a44ce79b1/0 --network host --log-driver none airbyte/source-mssql:0.3.3 check --config source_config.json
2021-08-11 04:48:19 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-11 04:48:19 INFO i.a.i.s.m.MssqlSource(main):327 - {} - starting source: class io.airbyte.integrations.source.mssql.MssqlSource
2021-08-11 04:48:19 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-11 04:48:19 INFO i.a.i.b.IntegrationRunner(run):81 - {} - Running integration: io.airbyte.integrations.source.mssql.MssqlSource
2021-08-11 04:48:19 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-11 04:48:19 INFO i.a.i.b.IntegrationCliParser(parseOptions):135 - {} - integration args: {check=null, config=source_config.json}
2021-08-11 04:48:19 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-11 04:48:19 INFO i.a.i.b.IntegrationRunner(run):85 - {} - Command: CHECK
2021-08-11 04:48:19 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-11 04:48:19 INFO i.a.i.b.IntegrationRunner(run):86 - {} - Integration config: IntegrationConfig{command=CHECK, configPath='source_config.json', catalogPath='null', statePath='null'}
2021-08-11 04:48:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-11 04:48:34 INFO i.a.i.s.r.AbstractRelationalDbSource(check):154 - {} - Exception while checking connection: 
2021-08-11 04:48:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - java.sql.SQLException: Cannot create PoolableConnectionFactory (The TCP/IP connection to the host MSSQLSERVER.com, port 1433 has failed. Error: "Connect timed out. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".)
2021-08-11 04:48:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:669) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2021-08-11 04:48:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:544) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2021-08-11 04:48:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:753) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2021-08-11 04:48:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.db.jdbc.DefaultJdbcDatabase$DataSourceConnectionSupplier.getConnection(DefaultJdbcDatabase.java:149) ~[io.airbyte-airbyte-db-0.27.2-alpha.jar:?]
2021-08-11 04:48:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.db.jdbc.DefaultJdbcDatabase.getMetaData(DefaultJdbcDatabase.java:92) ~[io.airbyte-airbyte-db-0.27.2-alpha.jar:?]
2021-08-11 04:48:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.db.jdbc.StreamingJdbcDatabase.getMetaData(StreamingJdbcDatabase.java:57) ~[io.airbyte-airbyte-db-0.27.2-alpha.jar:?]
2021-08-11 04:48:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.integrations.source.jdbc.AbstractJdbcSource.createDatabase(AbstractJdbcSource.java:260) ~[io.airbyte.airbyte-integrations.connectors-source-jdbc-0.27.2-alpha.jar:?]
2021-08-11 04:48:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.integrations.source.jdbc.AbstractJdbcSource.createDatabase(AbstractJdbcSource.java:61) ~[io.airbyte.airbyte-integrations.connectors-source-jdbc-0.27.2-alpha.jar:?]
2021-08-11 04:48:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.integrations.source.relationaldb.AbstractRelationalDbSource.createDatabaseInternal(AbstractRelationalDbSource.java:488) ~[io.airbyte.airbyte-integrations.connectors-source-relational-db-0.27.2-alpha.jar:?]
2021-08-11 04:48:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.integrations.source.relationaldb.AbstractRelationalDbSource.check(AbstractRelationalDbSource.java:147) [io.airbyte.airbyte-integrations.connectors-source-relational-db-0.27.2-alpha.jar:?]
```

**Comment by marcosmarxm** [comment]
@PS-istarostenko is possible to you use the direct IP instead?

**Comment by PS-istarostenko** [comment]
@marcosmarxm I can use the server IP, but it still requires to add the instance name in the end like: `12.34.56.789\MYINSTANCE`. Ideally I would want to use a hostname anyways.

**Comment by PS-istarostenko** [comment]
It appears that the connection works, just the logs are not printing the instance name next to the host. Updated the ticket

**Comment by marcosmarxm** [comment]
From [Slack Discussion (Isaac)](https://airbytehq.slack.com/archives/C01MFR03D5W/p1641961731252400?thread_ts=1641522910.052200&cid=C01MFR03D5W) suggestion: 
> Would using a different java driver work to correct the backslash string issue? https://github.com/airbytehq/airbyte/blob/8ddfd90c9cc04b02cf11a7d4399672760f35bf4e[…]main/java/io/airbyte/integrations/source/mssql/MssqlSource.java  line 73. , Say jtds like this? -> https://stackoverflow.com/questions/37766908/using-jdbc-when-server-name-contains-a-backslash-localhost-testdata

**Comment by tesla-avant** [comment]
Would using a different java driver (line 73) work to correct the backslash string issue? 
https://github.com/airbytehq/airbyte/blob/8ddfd90c9cc04b02cf11a7d4399672760f35bf4e/airbyte-integrations/connectors/source-mssql/src/main/java/io/airbyte/integrations/source/mssql/MssqlSource.java

Say jtds like this? 
-> https://stackoverflow.com/questions/37766908/using-jdbc-when-server-name-contains-a-backslash-localhost-testdata

**Comment by xiaohansong** [comment]
Validated that we can support backslash. In the latest version of mssql source connector we do not log hostname anymore. Closing this ticket.
