### ISSUE TITLE
All syncs started failing

### ISSUE THREAD

**Issue by m-ronchi** [airbytehq/airbyte#5337]
## Enviroment
- **Airbyte version**:  example is 0.29.2-alpha
- **OS Version / Instance**: AWS
- **Deployment**: Kubernetes
- **Source Connector and version**: all
- **Destination Connector and version**: all
- **Severity**: Medium
- **Step where error happened**: Sync job

## Current Behavior
starting a couple hours ago, all sync jobs failed with exception from scheduler

## Expected Behavior
sync jobs don't fail

## Logs
(trimmed to last stack trace)
```

2021-08-11 12:11:06 WARN i.t.i.s.POJOActivityTaskHandler$POJOActivityImplementation(execute):243 - {ActivityId=06fa3bae-ab3b-3360-adea-166834a8b744, ActivityType=Normalize, Namespace=default, RunId=a93267b6-7076-453a-96cd-d2760d58ffdc, TaskQueue=SYNC, WorkflowId=b780f6eb-8215-4198-a117-73777fe9e6eb, job_log_path=/workspace/115/2/logs.log} - Activity failure. ActivityId=06fa3bae-ab3b-3360-adea-166834a8b744, activityType=Normalize, attempt=1
java.util.concurrent.ExecutionException: io.airbyte.workers.WorkerException: Normalization Failed.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2063) ~[?:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:131) ~[io.airbyte-airbyte-workers-0.29.2-alpha.jar:?]
	at io.airbyte.workers.temporal.SyncWorkflow$NormalizationActivityImpl.normalize(SyncWorkflow.java:321) ~[io.airbyte-airbyte-workers-0.29.2-alpha.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor580.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityInboundCallsInterceptor.execute(POJOActivityTaskHandler.java:277) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityImplementation.execute(POJOActivityTaskHandler.java:216) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.POJOActivityTaskHandler.handle(POJOActivityTaskHandler.java:181) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:192) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:154) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73) ~[temporal-sdk-1.0.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: io.airbyte.workers.WorkerException: Normalization Failed.
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:69) ~[io.airbyte-airbyte-workers-0.29.2-alpha.jar:?]
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:36) ~[io.airbyte-airbyte-workers-0.29.2-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:146) ~[io.airbyte-airbyte-workers-0.29.2-alpha.jar:?]
	... 1 more
Caused by: io.airbyte.workers.WorkerException
	at io.airbyte.workers.process.KubeProcessFactory.create(KubeProcessFactory.java:102) ~[io.airbyte-airbyte-workers-0.29.2-alpha.jar:?]
	at io.airbyte.workers.normalization.DefaultNormalizationRunner.runProcess(DefaultNormalizationRunner.java:125) ~[io.airbyte-airbyte-workers-0.29.2-alpha.jar:?]
	at io.airbyte.workers.normalization.DefaultNormalizationRunner.normalize(DefaultNormalizationRunner.java:111) ~[io.airbyte-airbyte-workers-0.29.2-alpha.jar:?]
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:64) ~[io.airbyte-airbyte-workers-0.29.2-alpha.jar:?]
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:36) ~[io.airbyte-airbyte-workers-0.29.2-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:146) ~[io.airbyte-airbyte-workers-0.29.2-alpha.jar:?]
	... 1 more
Caused by: java.lang.NullPointerException
	at io.airbyte.workers.process.KubeProcessFactory.create(KubeProcessFactory.java:81) ~[io.airbyte-airbyte-workers-0.29.2-alpha.jar:?]
	at io.airbyte.workers.normalization.DefaultNormalizationRunner.runProcess(DefaultNormalizationRunner.java:125) ~[io.airbyte-airbyte-workers-0.29.2-alpha.jar:?]
	at io.airbyte.workers.normalization.DefaultNormalizationRunner.normalize(DefaultNormalizationRunner.java:111) ~[io.airbyte-airbyte-workers-0.29.2-alpha.jar:?]
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:64) ~[io.airbyte-airbyte-workers-0.29.2-alpha.jar:?]
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:36) ~[io.airbyte-airbyte-workers-0.29.2-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:146) ~[io.airbyte-airbyte-workers-0.29.2-alpha.jar:?]
	... 1 more
2021-08-11 12:11:06 ERROR i.t.i.s.POJOWorkflowImplementationFactory$POJOWorkflowImplementation$RootWorkflowInboundCallsInterceptor(logWorkflowExecutionException):323 - {Namespace=default, RunId=a93267b6-7076-453a-96cd-d2760d58ffdc, TaskQueue=SYNC, WorkflowId=b780f6eb-8215-4198-a117-73777fe9e6eb, WorkflowType=SyncWorkflow} - Workflow execution failure WorkflowId=b780f6eb-8215-4198-a117-73777fe9e6eb, RunId=a93267b6-7076-453a-96cd-d2760d58ffdc, WorkflowType=SyncWorkflow


```

## Extra notes

- restarting the scheduler pod fixed the issue.
- stack trace points to [this line](https://github.com/airbytehq/airbyte/blob/350bb5876e998a0d4e73c298b84faa7e62da38bc/airbyte-workers/src/main/java/io/airbyte/workers/process/KubeProcessFactory.java#L81). according to java docs, `BlockingQueue.poll(...)` returns null if timeout elapses, then it throws when it's converted to int.
the underlying problem may be (again) ports not released properly and leaking?

**Comment by jrhizor** [comment]
1. What is your `SUBMITTER_NUM_THREADS` set to in your .env file? 
2. Can you share how many `containerPort` are specified in the version of scheduler.yaml you are using?
3. Do you have an idea of how many simultaneous syncs were running?
4. Do you see the log output by https://github.com/airbytehq/airbyte/blob/master/airbyte-scheduler/app/src/main/java/io/airbyte/scheduler/app/SchedulerApp.java#L227 in your scheduler logs on startup?

**Comment by davinchia** [comment]
@m-ronchi have you seen this since? We support 10 concurrent jobs in theory.

I think it's also worth upgrading to the latest and monitoring. We've made some improvements in how the worker lifecycles.

**Comment by m-ronchi** [comment]
no, but I am upgrading (therefore rebooting) regularly (now on 0.29.7, uptime 7d4h)

**Comment by davinchia** [comment]
Cool - please update us if you see this.

**Comment by cgardens** [comment]
closed as stale.
