### ISSUE TITLE
GA source dimension selection fails

### ISSUE THREAD

**Issue by EdmonWales** [airbytehq/airbyte#5359]
## Enviroment
- **Airbyte version**:  0.29.4-alpha
- **OS Version / Instance**: Ubuntu 18.04
- **Deployment**: Docker
- **Source Connector and version**: Google Analytics 0.2.6
- **Destination Connector and version**: Postgres 0.3.8
- **Severity**: High
- **Step where error happened**: Sync job

## Current Behavior
I need to synchronize some dimensions for google analytics and not all default dimensions at once. However, after choosing one dimension in the connection (to start synchronization) the job simply freezes (even after a long time. it freezes without new logs). And the problem is that, for an unclear reason, the data is pulled from measurements that are not selected for synchronization. Job catches a mismatch error (Message contained record from a stream that was not in the catalog) and just freezes (it continues to be in the running status). The job never ends and the data is not synced (the destination is empty). However, if I include all measurements, then the data is synchronized as expected.

## Expected Behavior
Data (only) for selected in connection  measurements appears in the destination.

## Logs

<details>
<summary>LOG</summary> 

```

2021-08-11 21:25:11 INFO () WorkerRun(call):62 - Executing worker wrapper. Airbyte version: 0.29.4-alpha
2021-08-11 21:25:11 INFO () TemporalAttemptExecution(get):110 - Executing worker wrapper. Airbyte version: 0.29.4-alpha
2021-08-11 21:25:11 INFO () DefaultReplicationWorker(run):102 - start sync worker. job id: 87 attempt id: 0
2021-08-11 21:25:11 INFO () DefaultReplicationWorker(run):111 - configured sync modes: {null.weekly_active_users=incremental - append}
2021-08-11 21:25:11 INFO () DefaultAirbyteDestination(start):78 - Running destination...
2021-08-11 21:25:11 INFO () LineGobbler(voidCall):85 - Checking if airbyte/destination-postgres:0.3.8 exists...
2021-08-11 21:25:11 INFO () LineGobbler(voidCall):85 - airbyte/destination-postgres:0.3.8 was found locally.
2021-08-11 21:25:11 INFO () DockerProcessFactory(create):146 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/87/0 --network host --log-driver none airbyte/destination-postgres:0.3.8 write --config destination_config.json --catalog destination_catalog.json
2021-08-11 21:25:11 INFO () LineGobbler(voidCall):85 - Checking if airbyte/source-googleanalytics-singer:0.2.6 exists...
2021-08-11 21:25:11 INFO () LineGobbler(voidCall):85 - airbyte/source-googleanalytics-singer:0.2.6 was found locally.
2021-08-11 21:25:11 INFO () DockerProcessFactory(create):146 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/87/0 --network host --log-driver none airbyte/source-googleanalytics-singer:0.2.6 read --config source_config.json --catalog source_catalog.json
2021-08-11 21:25:11 INFO () DefaultReplicationWorker(lambda$getDestinationOutputRunnable$3):246 - Destination output thread started.
2021-08-11 21:25:11 INFO () DefaultReplicationWorker(run):139 - Waiting for source thread to join.
2021-08-11 21:25:11 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):210 - Replication thread started.
2021-08-11 21:25:14 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-11 21:25:14 [32mINFO[m i.a.i.d.p.PostgresDestination(main):83 - {} - starting destination: class io.airbyte.integrations.destination.postgres.PostgresDestination
2021-08-11 21:25:14 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-11 21:25:14 [32mINFO[m i.a.i.b.IntegrationRunner(run):96 - {} - Running integration: io.airbyte.integrations.destination.postgres.PostgresDestination
2021-08-11 21:25:14 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-11 21:25:14 [32mINFO[m i.a.i.b.IntegrationCliParser(parseOptions):135 - {} - integration args: {catalog=destination_catalog.json, write=null, config=destination_config.json}
2021-08-11 21:25:14 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-11 21:25:14 [32mINFO[m i.a.i.b.IntegrationRunner(run):100 - {} - Command: WRITE
2021-08-11 21:25:14 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-11 21:25:14 [32mINFO[m i.a.i.b.IntegrationRunner(run):101 - {} - Integration config: IntegrationConfig{command=WRITE, configPath='destination_config.json', catalogPath='destination_catalog.json', statePath='null'}
2021-08-11 21:25:14 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-11 21:25:14 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2021-08-11 21:25:14 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-11 21:25:14 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword examples - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2021-08-11 21:25:14 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-11 21:25:14 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2021-08-11 21:25:14 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-11 21:25:14 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=weekly_active_users, namespace=null, outputSchemaName=test, tmpTableName=_airbyte_tmp_ibb_weekly_active_users, outputTableName=_airbyte_raw_weekly_active_users, syncMode=append}
2021-08-11 21:25:14 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-11 21:25:14 [32mINFO[m i.a.i.d.b.BufferedStreamConsumer(startTracked):142 - {} - class io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer started.
2021-08-11 21:25:14 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-11 21:25:14 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):139 - {} - Preparing tmp tables in destination started for 1 streams
2021-08-11 21:25:14 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-11 21:25:14 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream weekly_active_users. schema: test, tmp table name: _airbyte_tmp_ibb_weekly_active_users
2021-08-11 21:25:15 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:12 name=googleapiclient.discovery level=INFO message=URL being requested: GET https://www.googleapis.com/discovery/v1/apis/analyticsreporting/v4/rest
2021-08-11 21:25:15 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:13 name=googleapiclient.discovery level=INFO message=URL being requested: GET https://www.googleapis.com/discovery/v1/apis/analytics/v3/rest
2021-08-11 21:25:15 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:13 name=googleapiclient.discovery level=INFO message=URL being requested: GET https://analytics.googleapis.com/analytics/v3/metadata/ga/columns?alt=json
2021-08-11 21:25:15 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:13 name=oauth2client.transport level=INFO message=Refreshing due to a 401 (attempt 1/2)
2021-08-11 21:25:15 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:13 name=oauth2client.client level=INFO message=Refreshing access_token
2021-08-11 21:25:15 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:13 name=googleapiclient.discovery level=INFO message=URL being requested: GET https://www.googleapis.com/discovery/v1/apis/analyticsreporting/v4/rest

2021-08-11 21:25:15 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:13 name=googleapiclient.discovery level=INFO message=URL being requested: GET https://www.googleapis.com/discovery/v1/apis/analytics/v3/rest

2021-08-11 21:25:15 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:13 name=googleapiclient.discovery level=INFO message=URL being requested: GET https://analytics.googleapis.com/analytics/v3/metadata/ga/columns?alt=json

2021-08-11 21:25:15 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:13 name=oauth2client.transport level=INFO message=Refreshing due to a 401 (attempt 1/2)

2021-08-11 21:25:15 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:13 name=oauth2client.client level=INFO message=Refreshing access_token

2021-08-11 21:25:15 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:14 name=tap_google_analytics level=INFO message=Syncing stream: website_overview

2021-08-11 21:25:15 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:14 name=tap_google_analytics level=INFO message=Sending request for 2021-08-05

2021-08-11 21:25:15 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:14 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json

2021-08-11 21:25:15 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:14 name=tap_google_analytics level=INFO message=Sending request for 2021-08-06

2021-08-11 21:25:15 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:14 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json

2021-08-11 21:25:15 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:14 name=tap_google_analytics level=INFO message=Sending request for 2021-08-07

2021-08-11 21:25:15 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:14 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json

2021-08-11 21:25:15 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:14 name=tap_google_analytics level=INFO message=Sending request for 2021-08-08

2021-08-11 21:25:15 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:14 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json

2021-08-11 21:25:15 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:14 name=tap_google_analytics level=INFO message=Sending request for 2021-08-09

2021-08-11 21:25:15 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:14 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json

2021-08-11 21:25:15 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:15 name=tap_google_analytics level=INFO message=Sending request for 2021-08-10

2021-08-11 21:25:15 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:15 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json

2021-08-11 21:25:15 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:15 name=tap_google_analytics level=INFO message=Syncing stream: traffic_sources

2021-08-11 21:25:15 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:15 name=tap_google_analytics level=INFO message=Sending request for 2021-08-05

2021-08-11 21:25:15 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:15 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json

2021-08-11 21:25:15 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-11 21:25:15 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):149 - {} - Preparing tables in destination completed.
2021-08-11 21:25:17 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:15 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json

2021-08-11 21:25:17 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:15 name=tap_google_analytics level=INFO message=Sending request for 2021-08-06

2021-08-11 21:25:17 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:15 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json

2021-08-11 21:25:17 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:15 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json

2021-08-11 21:25:17 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:15 name=tap_google_analytics level=INFO message=Sending request for 2021-08-07

2021-08-11 21:25:17 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:15 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json

2021-08-11 21:25:17 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:16 name=tap_google_analytics level=INFO message=Sending request for 2021-08-08

2021-08-11 21:25:17 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:16 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json

2021-08-11 21:25:17 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:16 name=tap_google_analytics level=INFO message=Sending request for 2021-08-09

2021-08-11 21:25:17 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:16 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json

2021-08-11 21:25:17 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:16 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json

2021-08-11 21:25:17 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:16 name=tap_google_analytics level=INFO message=Sending request for 2021-08-10

2021-08-11 21:25:17 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:16 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json

2021-08-11 21:25:17 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-08-11 21:25:16 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json

2021-08-11 21:25:17 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-11 21:25:17 [33mWARN[m i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):78 - {} - Airbyte message consumer: failed.
2021-08-11 21:25:17 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-11 21:25:17 [1;31mERROR[m i.a.i.d.b.BufferedStreamConsumer(close):210 - {} - executing on failed close procedure.
2021-08-11 21:25:17 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-11 21:25:17 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):199 - {} - Cleaning tmp tables in destination started for 1 streams
2021-08-11 21:25:17 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-11 21:25:17 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):203 - {} - Cleaning tmp table in destination started for stream weekly_active_users. schema test, tmp table name: _airbyte_tmp_ibb_weekly_active_users
2021-08-11 21:25:17 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-11 21:25:17 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):208 - {} - Cleaning tmp tables in destination completed.
2021-08-11 21:25:17 ERROR () LineGobbler(voidCall):85 - Exception in thread "main" java.lang.IllegalArgumentException: Message contained record from a stream that was not in the catalog. 
2021-08-11 21:25:17 ERROR () LineGobbler(voidCall):85 - catalog: {"streams":[{"stream":{"name":"weekly_active_users","json_schema":{"type":["null","object"],"properties":{"ga_date":{"type":["string"]},"ga_7dayUsers":{"type":["null","integer"]},"report_end_date":{"type":["string"]},"report_start_date":{"type":["string"]}},"additionalProperties":false},"supported_sync_modes":["incremental"],"source_defined_cursor":true,"default_cursor_field":[],"source_defined_primary_key":[]},"sync_mode":"incremental","cursor_field":[],"destination_sync_mode":"append","primary_key":[]}]} , 
2021-08-11 21:25:17 ERROR () LineGobbler(voidCall):85 - message: {"type":"RECORD","record":{"stream":"website_overview","data":{"ga_date":"20210805","ga_users":26794,"ga_newUsers":16707,"ga_sessions":32547,"ga_sessionsPerUser":1.2147122490109725,"ga_avgSessionDuration":158.96116385534765,"ga_pageviews":2,"ga_pageviewsPerSession":6.144959596890651E-5,"ga_avgTimeOnPage":2.0,"ga_bounceRate":0.0,"ga_exitRate":50.0,"report_start_date":"2021-08-05","report_end_date":"2021-08-05"},"emitted_at":1628717115000}}
2021-08-11 21:25:17 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.throwUnrecognizedStream(BufferedStreamConsumer.java:197)
2021-08-11 21:25:17 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.acceptTracked(BufferedStreamConsumer.java:157)
2021-08-11 21:25:17 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.accept(FailureTrackingAirbyteMessageConsumer.java:66)
2021-08-11 21:25:17 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:167)
2021-08-11 21:25:17 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:148)
2021-08-11 21:25:17 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.postgres.PostgresDestination.main(PostgresDestination.java:84)

```

</details>

## Steps to Reproduce
1. Create GA source and Postgres destination.
2. Make connection with default arguments but only one dimension selected.

**Comment by marcosmarxm** [comment]
Thanks for reporting this @EdmonWales I added this issue to the connector team take a look!

**Comment by sherifnada** [comment]
@EdmonWales please use the new GA v4 connector, it should not have this issue
