### ISSUE TITLE
error syncing intercom conversations and conversation parts

### ISSUE THREAD

**Issue by prasrvenkat** [airbytehq/airbyte#5474]
## Enviroment
- **Airbyte version**:  0.29.4-alpha
- **OS Version / Instance**:  PopOS 21.04
- **Deployment**: Docker
- **Source Connector and version**: Intercom Native 0.1.1 
- **Destination Connector and version**: Local JSON 0.2.8 
- **Severity**:  High
- **Step where error happened**: Sync Job

## Current Behavior
I think the cursor used for Conversation is wrong, which affects Conversation parts (messages) too
![image](https://user-images.githubusercontent.com/47996246/129783619-b6655f58-1307-4f2f-ac8f-26c06a5defd2.png)

```
2021-08-16 22:34:07 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - Encountered an exception while reading stream SourceIntercom
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 177, in _read_full_refresh
    for slice in slices:
  File "/airbyte/integration_code/source_intercom/source.py", line 160, in stream_slices
    sync_mode=sync_mode
  File "/airbyte/integration_code/source_intercom/source.py", line 81, in read_records
    yield from super().read_records(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 243, in read_records
    next_page_token = self.next_page_token(response)
  File "/airbyte/integration_code/source_intercom/source.py", line 66, in next_page_token
    return {"starting_after": next_page["starting_after"]}
TypeError: string indices must be integers
```
## Expected Behavior
Sync should succeed using the right cursor for the right stream

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```
2021-08-16 22:29:49 INFO () DefaultAirbyteStreamFactory(internhttps://docs.airbyte.io/alLog):110 - Syncing stream: conversation_parts 
2021-08-16 22:29:49 INFO () DefaultReplicationWorker(lambda$getDestinationOutputRunnable$3):251 - state in DefaultReplicationWorker from Destination: io.airbyte.protocol.models.AirbyteMessage@2dafc3d1[type=STATE,log=<null>,spec=<null>,connectionStatus=<null>,catalog=<null>,record=<null>,state=io.airbyte.protocol.models.AirbyteStateMessage@47e7bac3[data={"contacts":{"updated_at":"2021-08-16T22:18:26"},"companies":{"updated_at":"2021-08-16T22:17:49"},"company_segments":{"updated_at":"2021-07-20T23:10:50"}},additionalProperties={}],additionalProperties={}]
2021-08-16 22:29:56 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - Encountered an exception while reading stream SourceIntercom
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 110, in read
    logger=logger, stream_instance=stream_instance, configured_stream=configured_stream, connector_state=connector_state
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 135, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 177, in _read_full_refresh
    for slice in slices:
  File "/airbyte/integration_code/source_intercom/source.py", line 160, in stream_slices
    sync_mode=sync_mode
  File "/airbyte/integration_code/source_intercom/source.py", line 81, in read_records
    yield from super().read_records(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 243, in read_records
    next_page_token = self.next_page_token(response)
  File "/airbyte/integration_code/source_intercom/source.py", line 66, in next_page_token
    return {"starting_after": next_page["starting_after"]}
TypeError: string indices must be integers

2021-08-16 22:29:56 ERROR () LineGobbler(voidCall):85 - Traceback (most recent call last):
2021-08-16 22:29:56 ERROR () LineGobbler(voidCall):85 -   File "/airbyte/integration_code/main.py", line 33, in <module>
2021-08-16 22:29:56 ERROR () LineGobbler(voidCall):85 -     launch(source, sys.argv[1:])
2021-08-16 22:29:56 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 117, in launch
2021-08-16 22:29:56 ERROR () LineGobbler(voidCall):85 -     for message in source_entrypoint.run(parsed_args):
2021-08-16 22:29:56 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 108, in run
2021-08-16 22:29:56 ERROR () LineGobbler(voidCall):85 -     for message in generator:
2021-08-16 22:29:56 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 114, in read
2021-08-16 22:29:56 ERROR () LineGobbler(voidCall):85 -     raise e
2021-08-16 22:29:56 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 110, in read
2021-08-16 22:29:56 ERROR () LineGobbler(voidCall):85 -     logger=logger, stream_instance=stream_instance, configured_stream=configured_stream, connector_state=connector_state
2021-08-16 22:29:56 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 135, in _read_stream
2021-08-16 22:29:56 ERROR () LineGobbler(voidCall):85 -     for record in record_iterator:
2021-08-16 22:29:56 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 177, in _read_full_refresh
2021-08-16 22:29:56 ERROR () LineGobbler(voidCall):85 -     for slice in slices:
2021-08-16 22:29:56 ERROR () LineGobbler(voidCall):85 -   File "/airbyte/integration_code/source_intercom/source.py", line 160, in stream_slices
2021-08-16 22:29:56 ERROR () LineGobbler(voidCall):85 -     sync_mode=sync_mode
2021-08-16 22:29:56 ERROR () LineGobbler(voidCall):85 -   File "/airbyte/integration_code/source_intercom/source.py", line 81, in read_records
2021-08-16 22:29:56 ERROR () LineGobbler(voidCall):85 -     yield from super().read_records(*args, **kwargs)
2021-08-16 22:29:56 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 243, in read_records
2021-08-16 22:29:56 ERROR () LineGobbler(voidCall):85 -     next_page_token = self.next_page_token(response)
2021-08-16 22:29:56 ERROR () LineGobbler(voidCall):85 -   File "/airbyte/integration_code/source_intercom/source.py", line 66, in next_page_token
2021-08-16 22:29:56 ERROR () LineGobbler(voidCall):85 -     return {"starting_after": next_page["starting_after"]}
2021-08-16 22:29:56 ERROR () LineGobbler(voidCall):85 - TypeError: string indices must be integers
2021-08-16 22:29:56 INFO () DefaultReplicationWorker(run):141 - Source thread complete.
2021-08-16 22:29:56 INFO () DefaultReplicationWorker(run):142 - Waiting for destination thread to join.
2021-08-16 22:29:56 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-16 22:29:56 [32mINFO[m i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):80 - {} - Airbyte message consumer: succeeded.

```

</details>

## Steps to Reproduce
1. Add intercom source with at least some converstaions and conversation parts
2. Connect with any destination
3. Sync

## Are you willing to submit a PR?

Yes! Happy to!

I also like to discuss how to do paging/incremental sync properly here.
Intercom has a list API and Search API.
Ideal pulling would use List for full sync and Search for incremental syncs based on filters, updated_at or created_at.
Let me know if that would be useful too? (It will be for us! With current model we sync all conversations all the time which is a high volume data)

**Comment by sherifnada** [comment]
@prasrvenkat the improvement you suggested around search/list sounds great to have. It should probably go in a separate PR for easier review/housekeeping, since the immediate pain point is around the cursor. 

Is there anything we can do to help you get started with a PR?

**Comment by prasrvenkat** [comment]
> @prasrvenkat the improvement you suggested around search/list sounds great to have. It should probably go in a separate PR for easier review/housekeeping, since the immediate pain point is around the cursor.
> 
> Is there anything we can do to help you get started with a PR?

Ok I will work on that in a separate PR. Nothing as of now, just trying to wrap up [sync_success](https://github.com/airbytehq/airbyte/issues/4519) notification for review before I can get to this. Thanks @sherifnada

**Comment by prasrvenkat** [comment]
Apparently another bug and fixed here https://github.com/airbytehq/airbyte/issues/5527

**Comment by marcosmarxm** [comment]
@prasrvenkat closing this because #5531 solves it.
