### ISSUE TITLE
Connector: BigQuery Denormalized NPE when sync data from intercom

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#5525]
## Enviroment
- **Airbyte version**:  0.29.9-alpha
- **Destination connector version**: destination-bigquery-denormalized:0.1.2

## Current Behavior
*Tell us what happens.*
Trying to replicate data from source Intercom to destination bigquery denormalized fails on `admins` stream.
 
## Expected Behavior
*Tell us what should happen.*
Success sync

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```
2021-08-18 15:23:38 INFO  SyncMode: WRITE_APPEND, 
2021-08-18 15:23:38 INFO  TableName: GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=intercom, tableId=companies}}, 
2021-08-18 15:23:38 INFO  TmpTableName: GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=intercom, tableId=_airbyte_tmp_yhi_companies}}, 
2021-08-18 15:23:38 INFO  AirbyteMessage: io.airbyte.protocol.models.AirbyteMessage@523d6bdb[type=RECORD,log=<null>,spec=<null>,connectionStatus=<null>,catalog=<null>,record=io.airbyte.protocol.models.AirbyteRecordMessage@58496c97[stream=companies,data={"type":"company","company_id":"monitor","id":"5a9e90bcba1bb767b48db707","app_id":"sb3m6fs3","name":"Monitors","created_at":1520341180,"updated_at":"2021-08-03T20:48:47","last_request_at":1626090714,"monthly_spend":0,"session_count":0,"user_count":2334,"tags":{"type":"tag.list","tags":[]},"segments":{"type":"segment.list","segments":[]},"plan":{},"custom_attributes":{"creation_source":"api","company_survicate_last_response_date":1628023727}},emittedAt=1629300201000,namespace=intercom,additionalProperties={}],state=<null>,additionalProperties={}]
2021-08-18 15:23:38 INFO  2021-08-18 15:23:38 [32mINFO[m i.a.i.d.b.BigQueryRecordConsumer(printHeapMemoryConsumption):208 - {} - Initial Memory (xms) mb = 46
2021-08-18 15:23:38 INFO  2021-08-18 15:23:38 [32mINFO[m i.a.i.d.b.BigQueryRecordConsumer(printHeapMemoryConsumption):209 - {} - Max Memory (xmx) : mb + 705
2021-08-18 15:23:38 INFO  2021-08-18 15:23:38 [33mWARN[m i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):78 - {} - Airbyte message consumer: failed.
2021-08-18 15:23:38 INFO  2021-08-18 15:23:38 [32mINFO[m i.a.i.d.b.BigQueryRecordConsumer(close):133 - {} - Started closing all connections
2021-08-18 15:23:40 INFO  2021-08-18 15:23:40 [32mINFO[m i.a.i.d.b.BigQueryRecordConsumer(close):147 - {} - Waiting for jobs to be finished/closed
2021-08-18 15:23:41 INFO  2021-08-18 15:23:41 [1;31mERROR[m i.a.i.d.b.BigQueryRecordConsumer(lambda$close$2):153 - {} - Failed to process a message for job: Job{job=JobId{project=airbyte-test-323308, job=3d54dcc1-eea7-4c8a-878f-c70449a4cbf7, location=europe-west1}, status=JobStatus{state=RUNNING, error=null, executionErrors=null}, statistics=LoadStatistics{creationTime=1629300219827, endTime=null, startTime=1629300219993, numChildJobs=null, parentJobId=null, scriptStatistics=null, inputBytes=null, inputFiles=null, outputBytes=null, outputRows=null, badRecords=null}, userEmail=airbyte-test@airbyte-test-323308.iam.gserviceaccount.com, etag=5u+UHL7N2GB+BGiumYL9zA==, generatedId=airbyte-test-323308:europe-west1.3d54dcc1-eea7-4c8a-878f-c70449a4cbf7, selfLink=https://www.googleapis.com/bigquery/v2/projects/airbyte-test-323308/jobs/3d54dcc1-eea7-4c8a-878f-c70449a4cbf7?location=europe-west1, configuration=LoadJobConfiguration{type=LOAD, destinationTable=GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=intercom, projectId=airbyte-test-323308, tableId=_airbyte_tmp_vwy_admins}}, destinationEncryptionConfiguration=null, createDisposition=CREATE_IF_NEEDED, writeDisposition=null, formatOptions=FormatOptions{format=NEWLINE_DELIMITED_JSON}, nullMarker=null, maxBadRecords=null, schema=Schema{fields=[Field{name=id, type=STRING, mode=NULLABLE, description=null, policyTags=null}, Field{name=name, type=STRING, mode=NULLABLE, description=null, policyTags=null}, Field{name=type, type=STRING, mode=NULLABLE, description=null, policyTags=null}, Field{name=email, type=STRING, mode=NULLABLE, description=null, policyTags=null}, Field{name=avatar, type=RECORD, mode=NULLABLE, description=null, policyTags=null}, Field{name=team_ids, type=STRING, mode=null, description=null, policyTags=null}, Field{name=admin_ids, type=STRING, mode=null, description=null, policyTags=null}, Field{name=job_title, type=STRING, mode=NULLABLE, description=null, policyTags=null}, Field{name=has_inbox_seat, type=BOOLEAN, mode=NULLABLE, description=null, policyTags=null}, Field{name=away_mode_enabled, type=BOOLEAN, mode=NULLABLE, description=null, policyTags=null}, Field{name=away_mode_reassign, type=BOOLEAN, mode=NULLABLE, description=null, policyTags=null}, Field{name=_airbyte_ab_id, type=STRING, mode=null, description=null, policyTags=null}, Field{name=_airbyte_emitted_at, type=TIMESTAMP, mode=null, description=null, policyTags=null}]}, ignoreUnknownValue=null, sourceUris=[gs://bigquery-prod-upload-europe-west1/prod-scotty-1ab3444f-461e-4ed8-ac71-c04a12169657], schemaUpdateOptions=null, autodetect=null, timePartitioning=null, clustering=null, useAvroLogicalTypes=null, labels=null, jobTimeoutMs=null, rangePartitioning=null, hivePartitioningOptions=null}}, 
2021-08-18 15:23:41 INFO  Streams numbers: 11, 
2021-08-18 15:23:41 INFO  SyncMode: WRITE_APPEND, 
2021-08-18 15:23:41 INFO  TableName: GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=intercom, tableId=admins}}, 
2021-08-18 15:23:41 INFO  TmpTableName: GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=intercom, tableId=_airbyte_tmp_vwy_admins}}
2021-08-18 15:23:41 INFO  2021-08-18 15:23:41 [32mINFO[m i.a.i.d.b.BigQueryRecordConsumer(printHeapMemoryConsumption):208 - {} - Initial Memory (xms) mb = 46
2021-08-18 15:23:41 INFO  2021-08-18 15:23:41 [32mINFO[m i.a.i.d.b.BigQueryRecordConsumer(printHeapMemoryConsumption):209 - {} - Max Memory (xmx) : mb + 705
2021-08-18 15:23:41 INFO  2021-08-18 15:23:41 [32mINFO[m i.a.i.d.b.BigQueryRecordConsumer(close):176 - {} - Removing tmp tables...
2021-08-18 15:23:48 INFO  2021-08-18 15:23:48 [32mINFO[m i.a.i.d.b.BigQueryRecordConsumer(close):178 - {} - Finishing destination process...completed
2021-08-18 15:23:48 ERROR Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
2021-08-18 15:23:48 ERROR 	at io.airbyte.integrations.destination.bigquery.BigQueryRecordConsumer.acceptTracked(BigQueryRecordConsumer.java:112)
2021-08-18 15:23:48 ERROR 	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.accept(FailureTrackingAirbyteMessageConsumer.java:66)
2021-08-18 15:23:48 ERROR 	at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:167)
2021-08-18 15:23:48 ERROR 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:148)
2021-08-18 15:23:48 ERROR 	at io.airbyte.integrations.destination.bigquery.BigQueryDenormalizedDestination.main(BigQueryDenormalizedDestination.java:175)
2021-08-18 15:23:48 ERROR 	Suppressed: java.lang.RuntimeException: com.google.cloud.bigquery.BigQueryException: Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 1; errors: 1. Please look into the errors[] collection for more details.
2021-08-18 15:23:48 ERROR 		at io.airbyte.integrations.destination.bigquery.BigQueryRecordConsumer.lambda$close$2(BigQueryRecordConsumer.java:158)
2021-08-18 15:23:48 ERROR 		at io.airbyte.commons.lang.Exceptions.castCheckedToRuntime(Exceptions.java:72)
2021-08-18 15:23:48 ERROR 		at io.airbyte.commons.lang.Exceptions.toRuntime(Exceptions.java:59)
2021-08-18 15:23:48 ERROR 		at io.airbyte.integrations.destination.bigquery.BigQueryRecordConsumer.lambda$close$3(BigQueryRecordConsumer.java:148)
2021-08-18 15:23:48 ERROR 		at java.base/java.util.HashMap$Values.forEach(HashMap.java:1068)
2021-08-18 15:23:48 ERROR 		at io.airbyte.integrations.destination.bigquery.BigQueryRecordConsumer.close(BigQueryRecordConsumer.java:148)
2021-08-18 15:23:48 ERROR 		at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.close(FailureTrackingAirbyteMessageConsumer.java:82)
2021-08-18 15:23:48 ERROR 		at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:161)
2021-08-18 15:23:48 ERROR 		... 2 more
2021-08-18 15:23:48 ERROR 	Caused by: com.google.cloud.bigquery.BigQueryException: Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 1; errors: 1. Please look into the errors[] collection for more details.
2021-08-18 15:23:48 ERROR 		at com.google.cloud.bigquery.Job.reload(Job.java:411)
2021-08-18 15:23:48 ERROR 		at com.google.cloud.bigquery.Job.waitFor(Job.java:248)
2021-08-18 15:23:48 ERROR 		at io.airbyte.integrations.destination.bigquery.BigQueryRecordConsumer.lambda$close$2(BigQueryRecordConsumer.java:151)
2021-08-18 15:23:48 ERROR 		... 9 more
2021-08-18 15:23:48 ERROR Caused by: java.lang.NullPointerException
2021-08-18 15:23:48 ERROR 	at io.airbyte.integrations.destination.bigquery.BigQueryDenormalizedRecordConsumer.formatData(BigQueryDenormalizedRecordConsumer.java:87)
2021-08-18 15:23:48 ERROR 	at io.airbyte.integrations.destination.bigquery.BigQueryDenormalizedRecordConsumer.lambda$formatData$1(BigQueryDenormalizedRecordConsumer.java:98)
2021-08-18 15:23:48 ERROR 	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:178)
2021-08-18 15:23:48 ERROR 	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
2021-08-18 15:23:48 ERROR 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
2021-08-18 15:23:48 ERROR 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
2021-08-18 15:23:48 ERROR 	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
2021-08-18 15:23:48 ERROR 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
2021-08-18 15:23:48 ERROR 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
2021-08-18 15:23:48 ERROR 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
2021-08-18 15:23:48 ERROR 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2021-08-18 15:23:48 ERROR 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
2021-08-18 15:23:48 ERROR 	at io.airbyte.integrations.destination.bigquery.BigQueryDenormalizedRecordConsumer.formatData(BigQueryDenormalizedRecordConsumer.java:97)
2021-08-18 15:23:48 ERROR 	at io.airbyte.integrations.destination.bigquery.BigQueryDenormalizedRecordConsumer.formatRecord(BigQueryDenormalizedRecordConsumer.java:79)
2021-08-18 15:23:48 ERROR 	at io.airbyte.integrations.destination.bigquery.BigQueryRecordConsumer.acceptTracked(BigQueryRecordConsumer.java:105)
2021-08-18 15:23:48 ERROR 	... 4 more
2021-08-18 15:24:18 INFO  Exit code for pod destination-bigquery-denormalized-worker-113-0-ilyga is 2

```

</details>

## Steps to Reproduce
1. Setup intercom source
2. Setup Bigquery-denormalized destination
3. Create connection between above source/destination and run sync

**Comment by irynakruk** [comment]
I've created follow up [ticket](https://github.com/airbytehq/airbyte/issues/5882) for Intercom source due to schema and data inconsistency.
