### ISSUE TITLE
Connector: Hubspot.campaigns error java.lang.NullPointerException: Array field contacts misses the items property

### ISSUE THREAD

**Issue by 27Bslash6** [airbytehq/airbyte#5563]
## Enviroment
- **Airbyte version**:  0.29.11-alpha
- **OS Version / Instance**: GCE Debian GNU/Linux 10 (buster)
- **Deployment**: Docker CE 20.10.8
- **Source Connector and version**: Hubspot 0.1.10
- **Destination Connector and version**: Google Cloud Storage 0.1.0
- **Severity**: Critical
- **Step where error happened**: Sync job

## Current Behavior
Sync crashes with java.lang.NullPointerException: Array field contacts misses the items property when trying to fetch `campaigns`

## Expected Behavior
Successful sync

## Logs

<details>
<summary>
Exception in thread "main" java.lang.NullPointerException: Array field contacts misses the items property.
</summary> 

```2021-08-23 00:55:37 INFO () WorkerRun(call):62 - Executing worker wrapper. Airbyte version: 0.29.11-alpha
2021-08-23 00:55:37 INFO () TemporalAttemptExecution(get):110 - Executing worker wrapper. Airbyte version: 0.29.11-alpha
2021-08-23 00:55:37 INFO () DefaultReplicationWorker(run):102 - start sync worker. job id: 1 attempt id: 0
2021-08-23 00:55:37 INFO () DefaultReplicationWorker(run):111 - configured sync modes: {null.deal_pipelines=full_refresh - append, null.workflows=full_refresh - append, null.companies=full_refresh - append, null.deals=full_refresh - append, null.email_events=incremental - append, null.products=full_refresh - append, null.engagements=full_refresh - append, null.forms=full_refresh - append, null.line_items=full_refresh - append, null.tickets=full_refresh - append, null.quotes=full_refresh - append, null.contact_lists=full_refresh - append, null.contacts=full_refresh - append, null.campaigns=full_refresh - append, null.owners=full_refresh - append, null.subscription_changes=incremental - append}
2021-08-23 00:55:37 INFO () DefaultAirbyteDestination(start):78 - Running destination...
2021-08-23 00:55:37 INFO () LineGobbler(voidCall):85 - Checking if airbyte/destination-gcs:0.1.0 exists...
2021-08-23 00:55:37 INFO () LineGobbler(voidCall):85 - airbyte/destination-gcs:0.1.0 was found locally.
2021-08-23 00:55:37 INFO () DockerProcessFactory(create):146 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/1/0 --network host --log-driver none airbyte/destination-gcs:0.1.0 write --config destination_config.json --catalog destination_catalog.json
2021-08-23 00:55:37 INFO () LineGobbler(voidCall):85 - Checking if airbyte/source-hubspot:0.1.10 exists...
2021-08-23 00:55:37 INFO () LineGobbler(voidCall):85 - airbyte/source-hubspot:0.1.10 was found locally.
2021-08-23 00:55:37 INFO () DockerProcessFactory(create):146 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/1/0 --network host --log-driver none airbyte/source-hubspot:0.1.10 read --config source_config.json --catalog source_catalog.json
2021-08-23 00:55:37 INFO () DefaultReplicationWorker(lambda$getDestinationOutputRunnable$3):246 - Destination output thread started.
2021-08-23 00:55:37 INFO () DefaultReplicationWorker(run):139 - Waiting for source thread to join.
2021-08-23 00:55:37 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):210 - Replication thread started.
2021-08-23 00:55:40 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 00:55:40 [32mINFO[m i.a.i.b.IntegrationRunner(run):81 - {} - Running integration: io.airbyte.integrations.destination.gcs.GcsDestination
2021-08-23 00:55:40 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 00:55:40 [32mINFO[m i.a.i.b.IntegrationCliParser(parseOptions):135 - {} - integration args: {catalog=destination_catalog.json, write=null, config=destination_config.json}
2021-08-23 00:55:40 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 00:55:40 [32mINFO[m i.a.i.b.IntegrationRunner(run):85 - {} - Command: WRITE
2021-08-23 00:55:40 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 00:55:40 [32mINFO[m i.a.i.b.IntegrationRunner(run):86 - {} - Integration config: IntegrationConfig{command=WRITE, configPath='destination_config.json', catalogPath='destination_catalog.json', statePath='null'}
2021-08-23 00:55:40 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 00:55:40 [32mINFO[m i.a.i.d.s.S3FormatConfigs(getS3FormatConfig):42 - {} - S3 format config: {"format_type":"Avro","compression_codec":{"codec":"no compression"}}
2021-08-23 00:55:42 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 00:55:42 [32mINFO[m i.a.i.d.g.w.ProductionWriterFactory(create):63 - {} - Paquet schema for stream campaigns: {"type":"record","name":"campaigns","fields":[{"name":"_airbyte_ab_id","type":{"type":"string","logicalType":"uuid"}},{"name":"_airbyte_emitted_at","type":{"type":"long","logicalType":"timestamp-millis"}},{"name":"id","type":["null","int"],"default":null},{"name":"name","type":["null","string"],"default":null},{"name":"type","type":["null","string"],"default":null},{"name":"appId","type":["null","int"],"default":null},{"name":"appName","type":["null","string"],"default":null},{"name":"subType","type":["null","string"],"default":null},{"name":"subject","type":["null","string"],"default":null},{"name":"counters","type":["null",{"type":"record","name":"counters","fields":[{"name":"open","type":["null","int"],"default":null},{"name":"sent","type":["null","int"],"default":null},{"name":"click","type":["null","int"],"default":null},{"name":"print","type":["null","int"],"default":null},{"name":"reply","type":["null","int"],"default":null},{"name":"bounce","type":["null","int"],"default":null},{"name":"dropped","type":["null","int"],"default":null},{"name":"forward","type":["null","int"],"default":null},{"name":"deferred","type":["null","int"],"default":null},{"name":"delivered","type":["null","int"],"default":null},{"name":"processed","type":["null","int"],"default":null},{"name":"spamreport","type":["null","int"],"default":null},{"name":"suppressed","type":["null","int"],"default":null},{"name":"mta_dropped","type":["null","int"],"default":null},{"name":"statuschange","type":["null","int"],"default":null},{"name":"unsubscribed","type":["null","int"],"default":null}]}],"default":null},{"name":"contentId","type":["null","int"],"default":null},{"name":"numQueued","type":["null","int"],"default":null},{"name":"numIncluded","type":["null","int"],"default":null},{"name":"lastUpdatedTime","type":["null","int"],"default":null}]}
2021-08-23 00:55:42 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 00:55:42 [32mINFO[m i.a.i.d.g.a.GcsAvroWriter(<init>):72 - {} - Full GCS path for stream 'campaigns': test-airbyte-afr-avro/sync/campaigns/2021_08_23_1629680141928_0.avro
2021-08-23 00:55:42 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 00:55:42 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - {} - Initiated multipart upload to test-airbyte-afr-avro/sync/campaigns/2021_08_23_1629680141928_0.avro with full ID ABPnzm7LqwSoLMYSipBW1j38NKQS5kSy2zugXCDFTgLstxo9k8KOPOJhGN6vnUnlrK02IoMn
2021-08-23 00:55:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 00:55:43 [33mWARN[m i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):78 - {} - Airbyte message consumer: failed.
2021-08-23 00:55:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 00:55:43 [33mWARN[m i.a.i.d.g.w.BaseGcsWriter(close):125 - {} - Failure detected. Aborting upload of stream 'campaigns'...
2021-08-23 00:55:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 00:55:43 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
2021-08-23 00:55:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 00:55:43 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
2021-08-23 00:55:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 00:55:43 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
2021-08-23 00:55:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 00:55:43 [32mINFO[m a.m.s.StreamTransferManager(abort):470 - {} - [Manager uploading to test-airbyte-afr-avro/sync/campaigns/2021_08_23_1629680141928_0.avro with id ABPnzm7Lq...lrK02IoMn]: Aborted
2021-08-23 00:55:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 00:55:43 [33mWARN[m i.a.i.d.g.w.BaseGcsWriter(close):127 - {} - Upload of stream 'campaigns' aborted.
2021-08-23 00:55:43 ERROR () LineGobbler(voidCall):85 - Exception in thread "main" java.lang.NullPointerException: Array field contacts misses the items property.
2021-08-23 00:55:43 ERROR () LineGobbler(voidCall):85 - 	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:989)
2021-08-23 00:55:43 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.s3.avro.JsonToAvroSchemaConverter.getSingleFieldType(JsonToAvroSchemaConverter.java:183)
2021-08-23 00:55:43 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.s3.avro.JsonToAvroSchemaConverter.lambda$getNullableFieldTypes$4(JsonToAvroSchemaConverter.java:226)
2021-08-23 00:55:43 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
2021-08-23 00:55:43 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
2021-08-23 00:55:43 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
2021-08-23 00:55:43 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
2021-08-23 00:55:43 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
2021-08-23 00:55:43 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2021-08-23 00:55:43 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
2021-08-23 00:55:43 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.s3.avro.JsonToAvroSchemaConverter.getNullableFieldTypes(JsonToAvroSchemaConverter.java:234)
2021-08-23 00:55:43 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.s3.avro.JsonToAvroSchemaConverter.getAvroSchema(JsonToAvroSchemaConverter.java:162)
2021-08-23 00:55:43 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.gcs.writer.ProductionWriterFactory.create(ProductionWriterFactory.java:60)
2021-08-23 00:55:43 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.gcs.GcsConsumer.startTracked(GcsConsumer.java:74)
2021-08-23 00:55:43 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.start(FailureTrackingAirbyteMessageConsumer.java:54)
2021-08-23 00:55:43 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:131)
2021-08-23 00:55:43 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:117)
2021-08-23 00:55:43 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.gcs.GcsDestination.main(GcsDestination.java:48)
2021-08-23 00:55:43 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Starting syncing SourceHubspot
2021-08-23 00:55:43 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Syncing campaigns stream
```
</details>

## Steps to Reproduce
1. Install as per https://docs.airbyte.io/deploying-airbyte/on-gcp-compute-engine
2. Add Hubspot source connector
3. Add GCS destination
4. Sync

## Are you willing to submit a PR?

Sure, I'm happy to experiment to improve stability of the Hubspot connector or GCS destinations

**Comment by yaroslav-dudar** [comment]
<details><summary>new  Exception in thread "main" java.lang.NullPointerException error</summary>
<p>

```bash
2021-09-03 06:30:17 INFO () DockerProcessFactory(create):146 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/42/0 --network host --log-driver none airbyte/source-hubspot:dev read --config source_config.json --catalog source_catalog.json
2021-09-03 06:30:17 INFO () DefaultReplicationWorker(run):139 - Waiting for source thread to join.
2021-09-03 06:30:17 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):210 - Replication thread started.
2021-09-03 06:30:17 INFO () DefaultReplicationWorker(lambda$getDestinationOutputRunnable$3):246 - Destination output thread started.
2021-09-03 06:30:18 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-03 06:30:18 [32mINFO[m i.a.i.b.IntegrationRunner(run):81 - {} - Running integration: io.airbyte.integrations.destination.gcs.GcsDestination
2021-09-03 06:30:18 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-03 06:30:18 [32mINFO[m i.a.i.b.IntegrationCliParser(parseOptions):135 - {} - integration args: {catalog=destination_catalog.json, write=null, config=destination_config.json}
2021-09-03 06:30:18 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-03 06:30:18 [32mINFO[m i.a.i.b.IntegrationRunner(run):85 - {} - Command: WRITE
2021-09-03 06:30:18 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-03 06:30:18 [32mINFO[m i.a.i.b.IntegrationRunner(run):86 - {} - Integration config: IntegrationConfig{command=WRITE, configPath='destination_config.json', catalogPath='destination_catalog.json', statePath='null'}
2021-09-03 06:30:18 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-03 06:30:18 [32mINFO[m i.a.i.d.s.S3FormatConfigs(getS3FormatConfig):42 - {} - S3 format config: {"format_type":"Avro","compression_codec":{"codec":"no compression"}}
2021-09-03 06:30:19 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-03 06:30:19 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):126 - {} - Schema name contains illegal character(s) and is standardized: fix-campaigns -> fix_campaigns
2021-09-03 06:30:19 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-03 06:30:19 [32mINFO[m i.a.i.d.g.w.ProductionWriterFactory(create):63 - {} - Paquet schema for stream fix-campaigns: {"type":"record","name":"fix_campaigns","doc":"_airbyte_original_name:fix-campaigns","fields":[{"name":"_airbyte_ab_id","type":{"type":"string","logicalType":"uuid"}},{"name":"_airbyte_emitted_at","type":{"type":"long","logicalType":"timestamp-millis"}},{"name":"id","type":["null","int"],"default":null},{"name":"name","type":["null","string"],"default":null},{"name":"type","type":["null","string"],"default":null},{"name":"appId","type":["null","int"],"default":null},{"name":"appName","type":["null","string"],"default":null},{"name":"subType","type":["null","string"],"default":null},{"name":"subject","type":["null","string"],"default":null},{"name":"counters","type":["null",{"type":"record","name":"counters","fields":[{"name":"open","type":["null","int"],"default":null},{"name":"sent","type":["null","int"],"default":null},{"name":"click","type":["null","int"],"default":null},{"name":"print","type":["null","int"],"default":null},{"name":"reply","type":["null","int"],"default":null},{"name":"bounce","type":["null","int"],"default":null},{"name":"dropped","type":["null","int"],"default":null},{"name":"forward","type":["null","int"],"default":null},{"name":"deferred","type":["null","int"],"default":null},{"name":"delivered","type":["null","int"],"default":null},{"name":"processed","type":["null","int"],"default":null},{"name":"spamreport","type":["null","int"],"default":null},{"name":"suppressed","type":["null","int"],"default":null},{"name":"mta_dropped","type":["null","int"],"default":null},{"name":"statuschange","type":["null","int"],"default":null},{"name":"unsubscribed","type":["null","int"],"default":null}]}],"default":null},{"name":"contentId","type":["null","int"],"default":null},{"name":"numQueued","type":["null","int"],"default":null},{"name":"numIncluded","type":["null","int"],"default":null},{"name":"lastUpdatedTime","type":["null","int"],"default":null}]}
2021-09-03 06:30:19 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-03 06:30:19 [32mINFO[m i.a.i.d.g.w.ProductionWriterFactory(create):65 - {} - The following field names will be standardized: {fix-campaigns=fix_campaigns}
2021-09-03 06:30:19 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-03 06:30:19 [32mINFO[m i.a.i.d.g.a.GcsAvroWriter(<init>):72 - {} - Full GCS path for stream 'fix-campaigns': aurbyte-bucket/old/fix_campaigns/2021_09_03_1630650619002_0.avro
2021-09-03 06:30:19 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Starting syncing SourceHubspot
2021-09-03 06:30:19 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Syncing campaigns stream
2021-09-03 06:30:19 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Syncing companies stream
2021-09-03 06:30:19 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-03 06:30:19 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - {} - Initiated multipart upload to aurbyte-bucket/old/fix_campaigns/2021_09_03_1630650619002_0.avro with full ID ABPnzm4bkpiIHfm4ocPHPCWDYHLnyjvK9cA82Jpli0ROZ34zSH9s8ZXMiVnvj6rtjDtHPnw
2021-09-03 06:30:19 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-03 06:30:19 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):126 - {} - Schema name contains illegal character(s) and is standardized: fix-companies -> fix_companies
2021-09-03 06:30:19 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-03 06:30:19 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):126 - {} - Schema name contains illegal character(s) and is standardized: mergeAudits.items -> mergeAudits_items
2021-09-03 06:30:19 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-03 06:30:19 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):126 - {} - Schema name contains illegal character(s) and is standardized: movedProperties.items -> movedProperties_items
2021-09-03 06:30:19 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-03 06:30:19 [33mWARN[m i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):78 - {} - Airbyte message consumer: failed.
2021-09-03 06:30:19 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-03 06:30:19 [33mWARN[m i.a.i.d.g.w.BaseGcsWriter(close):125 - {} - Failure detected. Aborting upload of stream 'fix-campaigns'...
2021-09-03 06:30:19 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-03 06:30:19 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
2021-09-03 06:30:19 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-03 06:30:19 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
2021-09-03 06:30:19 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-03 06:30:19 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
2021-09-03 06:30:20 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-03 06:30:20 [32mINFO[m a.m.s.StreamTransferManager(abort):470 - {} - [Manager uploading to aurbyte-bucket/old/fix_campaigns/2021_09_03_1630650619002_0.avro with id ABPnzm4bk...rtjDtHPnw]: Aborted
2021-09-03 06:30:20 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-03 06:30:20 [33mWARN[m i.a.i.d.g.w.BaseGcsWriter(close):127 - {} - Upload of stream 'fix-campaigns' aborted.
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - Exception in thread "main" java.lang.NullPointerException
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.s3.avro.JsonToAvroSchemaConverter.getAvroSchema(JsonToAvroSchemaConverter.java:139)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.s3.avro.JsonToAvroSchemaConverter.getSingleFieldType(JsonToAvroSchemaConverter.java:196)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.s3.avro.JsonToAvroSchemaConverter.lambda$getNullableFieldTypes$4(JsonToAvroSchemaConverter.java:226)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.s3.avro.JsonToAvroSchemaConverter.getNullableFieldTypes(JsonToAvroSchemaConverter.java:234)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.s3.avro.JsonToAvroSchemaConverter.getSingleFieldType(JsonToAvroSchemaConverter.java:186)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.s3.avro.JsonToAvroSchemaConverter.lambda$getNullableFieldTypes$4(JsonToAvroSchemaConverter.java:226)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.s3.avro.JsonToAvroSchemaConverter.getNullableFieldTypes(JsonToAvroSchemaConverter.java:234)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.s3.avro.JsonToAvroSchemaConverter.getAvroSchema(JsonToAvroSchemaConverter.java:162)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.s3.avro.JsonToAvroSchemaConverter.getSingleFieldType(JsonToAvroSchemaConverter.java:196)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.s3.avro.JsonToAvroSchemaConverter.lambda$getNullableFieldTypes$4(JsonToAvroSchemaConverter.java:226)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.s3.avro.JsonToAvroSchemaConverter.getNullableFieldTypes(JsonToAvroSchemaConverter.java:234)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.s3.avro.JsonToAvroSchemaConverter.getSingleFieldType(JsonToAvroSchemaConverter.java:186)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.s3.avro.JsonToAvroSchemaConverter.lambda$getNullableFieldTypes$4(JsonToAvroSchemaConverter.java:226)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.s3.avro.JsonToAvroSchemaConverter.getNullableFieldTypes(JsonToAvroSchemaConverter.java:234)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.s3.avro.JsonToAvroSchemaConverter.getAvroSchema(JsonToAvroSchemaConverter.java:162)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.gcs.writer.ProductionWriterFactory.create(ProductionWriterFactory.java:60)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.gcs.GcsConsumer.startTracked(GcsConsumer.java:74)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.start(FailureTrackingAirbyteMessageConsumer.java:54)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:131)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:117)
2021-09-03 06:30:20 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.gcs.GcsDestination.main(GcsDestination.java:48)
2021-09-03 06:32:37 INFO () TemporalAttemptExecution(lambda$getCancellationChecker$3):180 - Running sync worker cancellation...
2021-09-03 06:32:37 INFO () DefaultReplicationWorker(cancel):270 - Cancelling replication worker...
2021-09-03 06:32:47 INFO () DefaultReplicationWorker(cancel):278 - Cancelling destination...
2021-09-03 06:32:47 INFO () DefaultAirbyteDestination(cancel):134 - Attempting to cancel destination process...
2021-09-03 06:32:47 INFO () DefaultAirbyteDestination(cancel):139 - Destination process exists, cancelling...
2021-09-03 06:32:47 INFO () DefaultAirbyteDestination(cancel):141 - Cancelled destination process!
2021-09-03 06:32:47 INFO () DefaultReplicationWorker(cancel):285 - Cancelling source...
2021-09-03 06:32:47 INFO () DefaultAirbyteSource(cancel):141 - Attempting to cancel source process...
2021-09-03 06:32:47 INFO () DefaultAirbyteSource(cancel):146 - Source process exists, cancelling...
2021-09-03 06:32:47 WARN () LineGobbler(voidCall):88 - airbyte-source gobbler IOException: Stream closed. Typically happens when cancelling a job.
2021-09-03 06:32:47 INFO () DefaultAirbyteSource(cancel):148 - Cancelled source process!
2021-09-03 06:32:47 INFO () TemporalAttemptExecution(lambda$getCancellationChecker$3):184 - Interrupting worker thread...
2021-09-03 06:32:47 INFO () TemporalAttemptExecution(lambda$getCancellationChecker$3):187 - Cancelling completable future...
2021-09-03 06:32:47 WARN () CancellationHandler$TemporalCancellationHandler(checkAndHandleCancellation):71 - Job either timeout-ed or was cancelled.
```

</p>
</details>
