### ISSUE TITLE
Connector: Hubspot.contact_lists Exception in thread "main" org.apache.avro.SchemaParseException: Can't redefine: properties

### ISSUE THREAD

**Issue by 27Bslash6** [airbytehq/airbyte#5564]
## Enviroment
- **Airbyte version**:  0.29.11-alpha
- **OS Version / Instance**: GCE Debian GNU/Linux 10 (buster)
- **Deployment**: Docker CE 20.10.8
- **Source Connector and version**: Hubspot 0.1.10
- **Destination Connector and version**: Google Cloud Storage 0.1.0
- **Severity**: Critical
- **Step where error happened**: Sync job

## Current Behavior
Sync crashes with Exception in thread "main" org.apache.avro.SchemaParseException: Can't redefine: properties

## Logs
<details>
<summary>
Exception in thread "main" org.apache.avro.SchemaParseException: Can't redefine: properties</summary> 

```
2021-08-23 01:19:29 INFO () WorkerRun(call):62 - Executing worker wrapper. Airbyte version: 0.29.11-alpha
2021-08-23 01:19:29 INFO () TemporalAttemptExecution(get):110 - Executing worker wrapper. Airbyte version: 0.29.11-alpha
2021-08-23 01:19:29 INFO () DefaultReplicationWorker(run):102 - start sync worker. job id: 5 attempt id: 0
2021-08-23 01:19:29 INFO () DefaultReplicationWorker(run):111 - configured sync modes: {null.deal_pipelines=full_refresh - append, null.workflows=full_refresh - append, null.deals=full_refresh - append, null.email_events=incremental - append, null.products=full_refresh - append, null.engagements=full_refresh - append, null.forms=full_refresh - append, null.line_items=full_refresh - append, null.tickets=full_refresh - append, null.quotes=full_refresh - append, null.contact_lists=full_refresh - append, null.contacts=full_refresh - append, null.owners=full_refresh - append, null.subscription_changes=incremental - append}
2021-08-23 01:19:29 INFO () DefaultAirbyteDestination(start):78 - Running destination...
2021-08-23 01:19:29 INFO () LineGobbler(voidCall):85 - Checking if airbyte/destination-gcs:0.1.0 exists...
2021-08-23 01:19:29 INFO () LineGobbler(voidCall):85 - airbyte/destination-gcs:0.1.0 was found locally.
2021-08-23 01:19:29 INFO () DockerProcessFactory(create):146 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/5/0 --network host --log-driver none airbyte/destination-gcs:0.1.0 write --config destination_config.json --catalog destination_catalog.json
2021-08-23 01:19:29 INFO () LineGobbler(voidCall):85 - Checking if airbyte/source-hubspot:0.1.10 exists...
2021-08-23 01:19:29 INFO () LineGobbler(voidCall):85 - airbyte/source-hubspot:0.1.10 was found locally.
2021-08-23 01:19:29 INFO () DockerProcessFactory(create):146 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/5/0 --network host --log-driver none airbyte/source-hubspot:0.1.10 read --config source_config.json --catalog source_catalog.json
2021-08-23 01:19:29 INFO () DefaultReplicationWorker(run):139 - Waiting for source thread to join.
2021-08-23 01:19:29 INFO () DefaultReplicationWorker(lambda$getDestinationOutputRunnable$3):246 - Destination output thread started.
2021-08-23 01:19:29 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):210 - Replication thread started.
2021-08-23 01:19:30 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Starting syncing SourceHubspot
2021-08-23 01:19:30 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Syncing contact_lists stream
2021-08-23 01:19:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:31 [32mINFO[m i.a.i.b.IntegrationRunner(run):81 - {} - Running integration: io.airbyte.integrations.destination.gcs.GcsDestination
2021-08-23 01:19:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:31 [32mINFO[m i.a.i.b.IntegrationCliParser(parseOptions):135 - {} - integration args: {catalog=destination_catalog.json, write=null, config=destination_config.json}
2021-08-23 01:19:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:31 [32mINFO[m i.a.i.b.IntegrationRunner(run):85 - {} - Command: WRITE
2021-08-23 01:19:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:31 [32mINFO[m i.a.i.b.IntegrationRunner(run):86 - {} - Integration config: IntegrationConfig{command=WRITE, configPath='destination_config.json', catalogPath='destination_catalog.json', statePath='null'}
2021-08-23 01:19:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:32 [32mINFO[m i.a.i.d.s.S3FormatConfigs(getS3FormatConfig):42 - {} - S3 format config: {"format_type":"Avro","compression_codec":{"codec":"no compression"}}
2021-08-23 01:19:33 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Syncing contacts stream
2021-08-23 01:19:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:33 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):126 - {} - Schema name contains illegal character(s) and is standardized: filters.items.items -> filters_items_items
2021-08-23 01:19:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:33 [32mINFO[m i.a.i.d.g.w.ProductionWriterFactory(create):63 - {} - Paquet schema for stream contact_lists: {"type":"record","name":"contact_lists","fields":[{"name":"_airbyte_ab_id","type":{"type":"string","logicalType":"uuid"}},{"name":"_airbyte_emitted_at","type":{"type":"long","logicalType":"timestamp-millis"}},{"name":"name","type":["null","string"],"default":null},{"name":"listId","type":["null","int"],"default":null},{"name":"dynamic","type":["null","boolean"],"default":null},{"name":"filters","type":["null",{"type":"array","items":["null",{"type":"array","items":["null",{"type":"record","name":"filters_items_items","doc":"_airbyte_original_name:filters.items.items","fields":[{"name":"type","type":["null","string"],"default":null},{"name":"value","type":["null","string"],"default":null},{"name":"operator","type":["null","string"],"default":null},{"name":"property","type":["null","string"],"default":null},{"name":"filterFamily","type":["null","string"],"default":null},{"name":"withinTimeMode","type":["null","string"],"default":null},{"name":"checkPastVersions","type":["null","boolean"],"default":null}]}]}]}],"default":null},{"name":"archived","type":["null","boolean"],"default":null},{"name":"listType","type":["null","string"],"default":null},{"name":"metaData","type":["null",{"type":"record","name":"metaData","fields":[{"name":"size","type":["null","int"],"default":null},{"name":"error","type":["null","string"],"default":null},{"name":"processing","type":["null","string"],"default":null},{"name":"lastSizeChangeAt","type":["null","int"],"default":null},{"name":"lastProcessingStateChangeAt","type":["null","int"],"default":null}]}],"default":null},{"name":"parentId","type":["null","int"],"default":null},{"name":"portalId","type":["null","int"],"default":null},{"name":"readOnly","type":["null","boolean"],"default":null},{"name":"createdAt","type":["null","int"],"default":null},{"name":"updatedAt","type":["null","int"],"default":null},{"name":"deleteable","type":["null","boolean"],"default":null},{"name":"internalListId","type":["null","int"],"default":null}]}
2021-08-23 01:19:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:33 [32mINFO[m i.a.i.d.g.w.ProductionWriterFactory(create):65 - {} - The following field names will be standardized: {filters.items.items=filters_items_items}
2021-08-23 01:19:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:33 [32mINFO[m i.a.i.d.g.a.GcsAvroWriter(<init>):72 - {} - Full GCS path for stream 'contact_lists': test-airbyte-afr-avro/sync/contact_lists/2021_08_23_1629681573173_0.avro
2021-08-23 01:19:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:34 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - {} - Initiated multipart upload to test-airbyte-afr-avro/sync/contact_lists/2021_08_23_1629681573173_0.avro with full ID ABPnzm4boKds749IAFZPeSQckjnl16mNOObFaQ7UWlcxs021sILx-gF8DrUqwPw9Glya-xtn
2021-08-23 01:19:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:34 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: portal-id -> portal_id
2021-08-23 01:19:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:34 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: is-contact -> is_contact
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: merged-vids -> merged_vids
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: profile-url -> profile_url
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: merge-audits -> merge_audits
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):126 - {} - Schema name contains illegal character(s) and is standardized: merge-audits.items -> merge_audits_items
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: user-id -> user_id
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: vid-to-merge -> vid_to_merge
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: canonical-vid -> canonical_vid
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: source-id -> source_id
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: source-type -> source_type
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: source-label -> source_label
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: source-id -> source_id
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: source-type -> source_type
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: source-vids -> source_vids
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: source-label -> source_label
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: num-properties-moved -> num_properties_moved
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: canonical-vid -> canonical_vid
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: profile-token -> profile_token
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: form-submissions -> form_submissions
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):126 - {} - Schema name contains illegal character(s) and is standardized: form-submissions.items -> form_submissions_items
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: form-id -> form_id
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: page-url -> page_url
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: portal-id -> portal_id
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: conversion-id -> conversion_id
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: list-memberships -> list_memberships
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):126 - {} - Schema name contains illegal character(s) and is standardized: list-memberships.items -> list_memberships_items
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: is-member -> is_member
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: static-list-id -> static_list_id
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: internal-list-id -> internal_list_id
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: identity-profiles -> identity_profiles
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):126 - {} - Schema name contains illegal character(s) and is standardized: identity-profiles.items -> identity_profiles_items
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):126 - {} - Schema name contains illegal character(s) and is standardized: identities.items -> identities_items
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: saved-at-timestamp -> saved_at_timestamp
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: deleted-changed-timestamp -> deleted_changed_timestamp
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: associated-company -> associated_company
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):126 - {} - Schema name contains illegal character(s) and is standardized: associated-company -> associated_company
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: portal-id -> portal_id
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):155 - {} - Field name contains illegal character(s) and is standardized: company-id -> company_id
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):78 - {} - Airbyte message consumer: failed.
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m i.a.i.d.g.w.BaseGcsWriter(close):125 - {} - Failure detected. Aborting upload of stream 'contact_lists'...
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
2021-08-23 01:19:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:35 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
2021-08-23 01:19:36 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:36 [32mINFO[m a.m.s.StreamTransferManager(abort):470 - {} - [Manager uploading to test-airbyte-afr-avro/sync/contact_lists/2021_08_23_1629681573173_0.avro with id ABPnzm4bo...9Glya-xtn]: Aborted
2021-08-23 01:19:36 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-23 01:19:36 [33mWARN[m i.a.i.d.g.w.BaseGcsWriter(close):127 - {} - Upload of stream 'contact_lists' aborted.
2021-08-23 01:19:36 ERROR () LineGobbler(voidCall):85 - Exception in thread "main" org.apache.avro.SchemaParseException: Can't redefine: properties
2021-08-23 01:19:36 ERROR () LineGobbler(voidCall):85 - 	at org.apache.avro.Schema$Names.put(Schema.java:1542)
2021-08-23 01:19:36 ERROR () LineGobbler(voidCall):85 - 	at org.apache.avro.Schema$NamedSchema.writeNameRef(Schema.java:805)
2021-08-23 01:19:36 ERROR () LineGobbler(voidCall):85 - 	at org.apache.avro.Schema$RecordSchema.toJson(Schema.java:967)
2021-08-23 01:19:36 ERROR () LineGobbler(voidCall):85 - 	at org.apache.avro.Schema$UnionSchema.toJson(Schema.java:1234)
2021-08-23 01:19:36 ERROR () LineGobbler(voidCall):85 - 	at org.apache.avro.Schema$RecordSchema.fieldsToJson(Schema.java:995)
2021-08-23 01:19:36 ERROR () LineGobbler(voidCall):85 - 	at org.apache.avro.Schema$RecordSchema.toJson(Schema.java:979)
2021-08-23 01:19:36 ERROR () LineGobbler(voidCall):85 - 	at org.apache.avro.Schema$UnionSchema.toJson(Schema.java:1234)
2021-08-23 01:19:36 ERROR () LineGobbler(voidCall):85 - 	at org.apache.avro.Schema$RecordSchema.fieldsToJson(Schema.java:995)
2021-08-23 01:19:36 ERROR () LineGobbler(voidCall):85 - 	at org.apache.avro.Schema$RecordSchema.toJson(Schema.java:979)
2021-08-23 01:19:36 ERROR () LineGobbler(voidCall):85 - 	at org.apache.avro.Schema.toString(Schema.java:419)
2021-08-23 01:19:36 ERROR () LineGobbler(voidCall):85 - 	at org.apache.avro.Schema.toString(Schema.java:391)
2021-08-23 01:19:36 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.gcs.writer.ProductionWriterFactory.create(ProductionWriterFactory.java:63)
2021-08-23 01:19:36 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.gcs.GcsConsumer.startTracked(GcsConsumer.java:74)
2021-08-23 01:19:36 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.start(FailureTrackingAirbyteMessageConsumer.java:54)
2021-08-23 01:19:36 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:131)
2021-08-23 01:19:36 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:117)
2021-08-23 01:19:36 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.gcs.GcsDestination.main(GcsDestination.java:48)

```

</details>

## Steps to Reproduce
1. Install as per https://docs.airbyte.io/deploying-airbyte/on-gcp-compute-engine
2. Add Hubspot source connector
3. Add GCS destination
4. Sync
## Are you willing to submit a PR?

Sure

**Comment by sherifnada** [comment]
nothing looks particularly off about the hubspot schema. There is probably an issue with how the schema is being parsed on the destination side. We should: 

1. identify the issue
2. add an acceptance test case to verify it's not breaking anything else


hubspot stream schema:

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "parentId": {
      "type": ["null", "integer"]
    },
    "metaData": {
      "type": ["null", "object"],
      "properties": {
        "processing": {
          "type": ["null", "string"]
        },
        "size": {
          "type": ["null", "integer"]
        },
        "error": {
          "type": ["null", "string"]
        },
        "lastProcessingStateChangeAt": {
          "type": ["null", "integer"]
        },
        "lastSizeChangeAt": {
          "type": ["null", "integer"]
        }
      }
    },
    "dynamic": {
      "type": ["null", "boolean"]
    },
    "name": {
      "type": ["null", "string"]
    },
    "filters": {
      "type": ["null", "array"],
      "items": {
        "type": ["null", "array"],
        "items": {
          "type": ["null", "object"],
          "properties": {
            "filterFamily": {
              "type": ["null", "string"]
            },
            "withinTimeMode": {
              "type": ["null", "string"]
            },
            "checkPastVersions": {
              "type": ["null", "boolean"]
            },
            "type": {
              "type": ["null", "string"]
            },
            "property": {
              "type": ["null", "string"]
            },
            "value": {
              "type": ["null", "string"]
            },
            "operator": {
              "type": ["null", "string"]
            }
          }
        }
      }
    },
    "portalId": {
      "type": ["null", "integer"]
    },
    "createdAt": {
      "type": ["null", "integer"]
    },
    "listId": {
      "type": ["null", "integer"]
    },
    "updatedAt": {
      "type": ["null", "integer"]
    },
    "internalListId": {
      "type": ["null", "integer"]
    },
    "readOnly": {
      "type": ["null", "boolean"]
    },
    "deleteable": {
      "type": ["null", "boolean"]
    },
    "listType": {
      "type": ["null", "string"]
    },
    "archived": {
      "type": ["null", "boolean"]
    }
  }
}

```

**Comment by tuliren** [comment]
Cannot reproduce this issue. The Json to Avro schema converter has multiple updates, and much more test coverage since this issue was opened. Also the schema is added as a test case in #9363, and there is no problem processing this schema.
