### ISSUE TITLE
Add configuration of securityContext for kube worker pods 

### ISSUE THREAD

**Issue by Dracyr** [airbytehq/airbyte#5736]
## Tell us about the problem you're trying to solve
I have been evaluating and experimenting with setting up Airbyte in our on-prem kubenetes cluster. While there were some issues I could solve by modifying the manifests and creating new dockerfiles (Configuring http clients to use a proxy, running the containers as non-root) there's one remaining blocker.

Our cluster and security profile requires all pods to define a [SecurityContext](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod), with `runAsNonRoot: true`. 
Since the [PodBuilder](https://github.com/airbytehq/airbyte/blob/f4ffe47ae04976abb40759b91dbe968fcddb8187/airbyte-workers/src/main/java/io/airbyte/workers/process/KubePodProcess.java#L374) does not allow for any configuration regarding the SecurityContext, on an attempt to sync the image spec in the creation of the pod the scheduler will throw an error, making it impossible to configure the source/destination and set up a new connection.

## Describe the solution you’d like
A simple way to define the `SecurityContext` of worker pods, for example via env vars like in https://github.com/airbytehq/airbyte/pull/4381
Although a more dynamic way of specifying the worker spec would also be nice.

Or running all worker containers and pods as a non root user by default, with a default `SecurityContext` set, removing the need for customization.

## Describe the alternative you’ve considered or used
We can wrap the docker images and create non-root users, but without being able to create the pods, they cannot be run.

## Additional context

<details>
  <summary>Stack trace for Scheduler failing to create a new pod for future searchability</summary>
  
  ```
  io.airbyte.workers.WorkerException: Error while getting spec from image airbyte/source-db2:0.1.1
        at io.airbyte.workers.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:94) ~[io.airbyte-airbyte-workers-0.29.13-alpha.jar:?]
        at io.airbyte.workers.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:43) ~[io.airbyte-airbyte-workers-0.29.13-alpha.jar:?]
        at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:146) ~[io.airbyte-airbyte-workers-0.29.13-alpha.jar:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: io.airbyte.workers.WorkerException: Operation: [create]  for kind: [Pod]  with name: [source-db2-worker-7148e69a-539a-4691-9d06-589c734ab3bc-0-lwgzo]  in namespace: [infrastructure]  failed.
        at io.airbyte.workers.process.KubeProcessFactory.create(KubeProcessFactory.java:126) ~[io.airbyte-airbyte-workers-0.29.13-alpha.jar:?]
        at io.airbyte.workers.process.AirbyteIntegrationLauncher.spec(AirbyteIntegrationLauncher.java:72) ~[io.airbyte-airbyte-workers-0.29.13-alpha.jar:?]
        at io.airbyte.workers.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:64) ~[io.airbyte-airbyte-workers-0.29.13-alpha.jar:?]
        ... 3 more
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [create]  for kind: [Pod]  with name: [source-db2-worker-7148e69a-539a-4691-9d06-589c734ab3bc-0-lwgzo]  in namespace: [infrastructure]  failed.
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64) ~[kubernetes-client-5.5.0.jar:?]
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:72) ~[kubernetes-client-5.5.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:359) ~[kubernetes-client-5.5.0.jar:?]
        at io.fabric8.kubernetes.client.utils.CreateOrReplaceHelper.createOrReplace(CreateOrReplaceHelper.java:55) ~[kubernetes-client-5.5.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:390) ~[kubernetes-client-5.5.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:90) ~[kubernetes-client-5.5.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:380) ~[kubernetes-client-5.5.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:90) ~[kubernetes-client-5.5.0.jar:?]
        at io.airbyte.workers.process.KubePodProcess.<init>(KubePodProcess.java:389) ~[io.airbyte-airbyte-workers-0.29.13-alpha.jar:?]
        at io.airbyte.workers.process.KubeProcessFactory.create(KubeProcessFactory.java:109) ~[io.airbyte-airbyte-workers-0.29.13-alpha.jar:?]
        at io.airbyte.workers.process.AirbyteIntegrationLauncher.spec(AirbyteIntegrationLauncher.java:72) ~[io.airbyte-airbyte-workers-0.29.13-alpha.jar:?]
        at io.airbyte.workers.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:64) ~[io.airbyte-airbyte-workers-0.29.13-alpha.jar:?]
        ... 3 more
Caused by: java.io.IOException: Unexpected response code for CONNECT: 403
        at okhttp3.internal.connection.RealConnection.createTunnel(RealConnection.java:427) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.java:236) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:177) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:?]
        at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:133) ~[kubernetes-client-5.5.0.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:?]
        at io.fabric8.kubernetes.client.utils.TokenRefreshInterceptor.intercept(TokenRefreshInterceptor.java:42) ~[kubernetes-client-5.5.0.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:?]
        at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68) ~[kubernetes-client-5.5.0.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:?]
        at io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createApplicableInterceptors$6(HttpClientUtils.java:290) ~[kubernetes-client-5.5.0.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:?]
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229) ~[okhttp-3.14.9.jar:?]
        at okhttp3.RealCall.execute(RealCall.java:81) ~[okhttp-3.14.9.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.retryWithExponentialBackoff(OperationSupport.java:585) ~[kubernetes-client-5.5.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:558) ~[kubernetes-client-5.5.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:521) ~[kubernetes-client-5.5.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:309) ~[kubernetes-client-5.5.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:776) ~[kubernetes-client-5.5.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:351) ~[kubernetes-client-5.5.0.jar:?]
        at io.fabric8.kubernetes.client.utils.CreateOrReplaceHelper.createOrReplace(CreateOrReplaceHelper.java:55) ~[kubernetes-client-5.5.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:390) ~[kubernetes-client-5.5.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:90) ~[kubernetes-client-5.5.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:380) ~[kubernetes-client-5.5.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:90) ~[kubernetes-client-5.5.0.jar:?]
        at io.airbyte.workers.process.KubePodProcess.<init>(KubePodProcess.java:389) ~[io.airbyte-airbyte-workers-0.29.13-alpha.jar:?]
        at io.airbyte.workers.process.KubeProcessFactory.create(KubeProcessFactory.java:109) ~[io.airbyte-airbyte-workers-0.29.13-alpha.jar:?]
        at io.airbyte.workers.process.AirbyteIntegrationLauncher.spec(AirbyteIntegrationLauncher.java:72) ~[io.airbyte-airbyte-workers-0.29.13-alpha.jar:?]
        at io.airbyte.workers.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:64) ~[io.airbyte-airbyte-workers-0.29.13-alpha.jar:?]
        ... 3 more

```

</details>

## Are you willing to submit a PR?
Maybe, since I'm not well versed in the codebase, I'd attempt to just re-use the approach found in https://github.com/airbytehq/airbyte/pull/4381

**Comment by davinchia** [comment]
@Dracyr to make sure I understand, this issue is about setting the security context of the worker to run as non root. It is okay for the scheduler to run as root? (It needs to do so to create the pods.)

**Comment by Dracyr** [comment]
Hey!

Both would need to run as non-root inside the cluster. But from my understanding, when the scheduler runs in k8s mode (`WORKER_ENVIRONMENT=kubernetes`) it's talking to the k8s API inside the cluster, using a service account set up with pod creation rights. This should not require the container to run as root AFAIK?

If the scheduler is running in docker mode and talking to the docker daemon, then it would still need it yes.
