### ISSUE TITLE
 Source Mysql Value '65535' is outside of valid range for type java.lang.Short

### ISSUE THREAD

**Issue by Abrar-ul-farhan-Mohammed** [airbytehq/airbyte#5842]
## Enviroment
- **Airbyte version**:  0.29.13-alpha
- **OS Version / Instance**: Windows 10
- **Deployment**: Docker
- **Source Connector and version**: MySQL
- **Destination Connector and version**: Snowflake 5.31.4
- **Severity**: High 
- **Step where error happened**: Sync job

## Current Behavior
Sync fails for some tables from the same database. It is loading data into the destination and for some tables, it is erroring out and is stopping there. Normalization also fails. Raw data load is working.

## Expected Behavior
Should sync without errors and load the data into the destination

## Logs
`
[logs-7-0.txt](https://github.com/airbytehq/airbyte/files/7106810/logs-7-0.txt)
`

**Comment by marcosmarxm** [comment]
Relevant logs 
```
2021-09-01 23:45:35 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):223 - Records read: 19919000
2021-09-01 23:45:36 ERROR () LineGobbler(voidCall):85 - Exception in thread "main" java.lang.RuntimeException: java.sql.SQLDataException: Value '65535' is outside of valid range for type java.lang.Short
2021-09-01 23:45:36 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.db.jdbc.JdbcUtils$1.tryAdvance(JdbcUtils.java:71)
2021-09-01 23:45:36 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
2021-09-01 23:45:36 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:58)
2021-09-01 23:45:36 ERROR () LineGobbler(voidCall):85 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
2021-09-01 23:45:36 ERROR () LineGobbler(voidCall):85 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
2021-09-01 23:45:36 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.commons.util.LazyAutoCloseableIterator.computeNext(LazyAutoCloseableIterator.java:62)
2021-09-01 23:45:36 ERROR () LineGobbler(voidCall):85 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
2021-09-01 23:45:36 ERROR () LineGobbler(voidCall):85 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
2021-09-01 23:45:36 ERROR () LineGobbler(voidCall):85 - 	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
2021-09-01 23:45:36 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:58)
2021-09-01 23:45:36 ERROR () LineGobbler(voidCall):85 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
2021-09-01 23:45:36 ERROR () LineGobbler(voidCall):85 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
2021-09-01 23:45:36 ERROR () LineGobbler(voidCall):85 - 	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
2021-09-01 23:45:36 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:58)
2021-09-01 23:45:36 ERROR () LineGobbler(voidCall):85 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
2021-09-01 23:45:36 ERROR () LineGobbler(voidCall):85 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
2021-09-01 23:45:36 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.commons.util.CompositeIterator.computeNext(CompositeIterator.java:83)
2021-09-01 23:45:36 ERROR () LineGobbler(voidCall):85 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
2021-09-01 23:45:36 ERROR () LineGobbler(voidCall):85 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
2021-09-01 23:45:36 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:58)
2021-09-01 23:45:36 ERROR () LineGobbler(voidCall):85 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
2021-09-01 23:45:36 ERROR () LineGobbler(voidCall):85 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
2021-09-01 23:45:36 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
2021-09-01 23:45:36 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:139)
2021-09-01 23:45:36 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.source.mysql.MySqlSource.main(MySqlSource.java:250)
2021-09-01 23:45:36 ERROR () LineGobbler(voidCall):85 - Caused by: java.sql.SQLDataException: Value '65535' is outside of valid range for type java.lang.Short
```

[Uploading logs-7-0 (9).txt…]()
