### ISSUE TITLE
Cant setup MySql as a source

### ISSUE THREAD

**Issue by Wajira** [airbytehq/airbyte#5858]
## Enviroment
- **Airbyte version**:   is 0.29.13-alpha
- **OS Version / Instance**: Windows 10
- **Deployment**: Docker 
- **Source Connector and version**:MySql 5.7
- **Destination Connector and version**: not applicable
- **Severity**:  Critical
- **Step where error happened**: Setup new connection 

## Current Behavior
when trying to setup MySQL as a source it returns error

## Expected Behavior
connection should be successful

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```
2021-09-06 04:02:30 INFO () TemporalAttemptExecution(get):110 - Executing worker wrapper. Airbyte version: 0.29.13-alpha
2021-09-06 04:02:30 INFO () LineGobbler(voidCall):85 - Checking if airbyte/source-mysql:0.4.3 exists...
2021-09-06 04:02:30 INFO () LineGobbler(voidCall):85 - airbyte/source-mysql:0.4.3 was found locally.
2021-09-06 04:02:30 INFO () DockerProcessFactory(create):146 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/fb51b5f8-edce-4857-8280-31f545db3b2d/0 --network host --log-driver none airbyte/source-mysql:0.4.3 check --config source_config.json
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 04:02:31 [32mINFO[m i.a.i.s.m.MySqlSource(main):249 - {} - starting source: class io.airbyte.integrations.source.mysql.MySqlSource
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 04:02:31 [32mINFO[m i.a.i.b.IntegrationRunner(run):96 - {} - Running integration: io.airbyte.integrations.source.mysql.MySqlSource
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 04:02:31 [32mINFO[m i.a.i.b.IntegrationCliParser(parseOptions):135 - {} - integration args: {check=null, config=source_config.json}
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 04:02:31 [32mINFO[m i.a.i.b.IntegrationRunner(run):100 - {} - Command: CHECK
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 04:02:31 [32mINFO[m i.a.i.b.IntegrationRunner(run):101 - {} - Integration config: IntegrationConfig{command=CHECK, configPath='source_config.json', catalogPath='null', statePath='null'}
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 04:02:31 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 04:02:31 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword examples - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 04:02:31 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 04:02:31 [32mINFO[m i.a.i.s.r.AbstractRelationalDbSource(check):154 - {} - Exception while checking connection: 
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - java.sql.SQLException: Cannot create PoolableConnectionFactory (Communications link failure
2021-09-06 04:02:31 INFO () JsonSchemaValidator(test):76 - JSON schema validation failed. 
errors: $: unknown found, object expected
2021-09-06 04:02:31 ERROR () DefaultAirbyteStreamFactory(lambda$create$1):83 - Validation failed: null
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.)
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:669) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:544) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:753) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.db.jdbc.DefaultJdbcDatabase$DataSourceConnectionSupplier.getConnection(DefaultJdbcDatabase.java:149) ~[io.airbyte-airbyte-db-0.29.7-alpha.jar:?]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.db.jdbc.DefaultJdbcDatabase.getMetaData(DefaultJdbcDatabase.java:92) ~[io.airbyte-airbyte-db-0.29.7-alpha.jar:?]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.db.jdbc.StreamingJdbcDatabase.getMetaData(StreamingJdbcDatabase.java:57) ~[io.airbyte-airbyte-db-0.29.7-alpha.jar:?]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.integrations.source.jdbc.AbstractJdbcSource.createDatabase(AbstractJdbcSource.java:260) ~[io.airbyte.airbyte-integrations.connectors-source-jdbc-0.29.7-alpha.jar:?]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.integrations.source.jdbc.AbstractJdbcSource.createDatabase(AbstractJdbcSource.java:61) ~[io.airbyte.airbyte-integrations.connectors-source-jdbc-0.29.7-alpha.jar:?]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.integrations.source.relationaldb.AbstractRelationalDbSource.createDatabaseInternal(AbstractRelationalDbSource.java:488) ~[io.airbyte.airbyte-integrations.connectors-source-relational-db-0.29.7-alpha.jar:?]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.integrations.source.relationaldb.AbstractRelationalDbSource.check(AbstractRelationalDbSource.java:147) [io.airbyte.airbyte-integrations.connectors-source-relational-db-0.29.7-alpha.jar:?]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:122) [io.airbyte.airbyte-integrations.bases-base-java-0.29.7-alpha.jar:?]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.integrations.source.mysql.MySqlSource.main(MySqlSource.java:250) [io.airbyte.airbyte-integrations.connectors-source-mysql-0.29.7-alpha.jar:?]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
2021-09-06 04:02:31 INFO () JsonSchemaValidator(test):76 - JSON schema validation failed. 
errors: $: unknown found, object expected
2021-09-06 04:02:31 ERROR () DefaultAirbyteStreamFactory(lambda$create$1):83 - Validation failed: null
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:55) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:355) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:115) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:665) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	... 11 more
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
2021-09-06 04:02:31 INFO () JsonSchemaValidator(test):76 - JSON schema validation failed. 
errors: $: unknown found, object expected
2021-09-06 04:02:31 ERROR () DefaultAirbyteStreamFactory(lambda$create$1):83 - Validation failed: null
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[?:?]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at com.mysql.cj.NativeSession.connect(NativeSession.java:144) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:956) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:55) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:355) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:115) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:665) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	... 11 more
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - Caused by: java.net.ConnectException: Connection refused
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at sun.nio.ch.Net.connect(Net.java:503) ~[?:?]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at sun.nio.ch.Net.connect(Net.java:492) ~[?:?]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588) ~[?:?]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333) ~[?:?]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at java.net.Socket.connect(Socket.java:648) ~[?:?]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at com.mysql.cj.NativeSession.connect(NativeSession.java:144) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:956) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.22.jar:8.0.22]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:55) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:355) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:115) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:665) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2021-09-06 04:02:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	... 11 more
2021-09-06 04:02:32 INFO () TemporalAttemptExecution(get):133 - Stopping cancellation check scheduling...
```

</details>

## Steps to Reproduce
1. give a name for source
2.select MySQL as a source type
3.fill the connection details and click set source button
[logs-1bdeca8e-2a4c-49f6-a6f9-af67221daf2d-.txt](https://github.com/airbytehq/airbyte/files/7113229/logs-1bdeca8e-2a4c-49f6-a6f9-af67221daf2d-.txt)

## Are you willing to submit a PR? No

Remove this with your answer.

**Comment by marcosmarxm** [comment]
@Wajira is this mysql database in the same machine (like running a container)? Are you able to connect to this database using other (IDE, command line)? The last could you access the airbyte-scheduler container and ping the database IP to ensure Airbyte can reach the network?

**Comment by sherifnada** [comment]
@Wajira does the issue exist on the latest airbyte and mysql connector versions?

**Comment by Wajira** [comment]
yes.
