### ISSUE TITLE
Oracle destination connection failed with  - Could not connect with provided configuration. ORA-00972: identifier is too long

### ISSUE THREAD

**Issue by nijatrzayev1** [airbytehq/airbyte#5862]
## Enviroment
- **Airbyte version**:  airbyte/server:0.29.15-alpha
- **OS Version / Instance**: Windows 11
- **Deployment**: Docker
- **Source Connector and version**: oracle 0.3.3
- **Destination Connector and version**:Oracle (Alpha) 0.1.7  (0.1.6 also) 
- **Severity**: High 
- **Step where error happened**: Setup new connection

## Current Behavior
Source connection created successfully.
During create destination connection failed with: Could not connect with provided configuration. ORA-00972: identifier is too long. I try different oracle connections. Same error.

## Expected Behavior
Fix Oracle connection for destination connection.

## Logs
[logs-031b4754-d555-41bb-929d-19083877c82c-.txt](https://github.com/airbytehq/airbyte/files/7116826/logs-031b4754-d555-41bb-929d-19083877c82c-.txt)

<details>
<summary>LOG</summary> 

2021-09-06 15:16:53 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1823) ~[ojdbc8-19.7.0.0.jar:19.7.0.0.0]
2021-09-06 15:16:53 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1778) ~[ojdbc8-19.7.0.0.jar:19.7.0.0.0]
2021-09-06 15:16:53 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:303) ~[ojdbc8-19.7.0.0.jar:19.7.0.0.0]
2021-09-06 15:16:53 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2021-09-06 15:16:53 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194) ~[commons-dbcp2-2.7.0.jar:2.7.0]
2021-09-06 15:16:53 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.db.jdbc.JdbcDatabase.lambda$execute$0(JdbcDatabase.java:54) ~[io.airbyte-airbyte-db-0.29.11-alpha.jar:?]
2021-09-06 15:16:53 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.db.jdbc.DefaultJdbcDatabase.execute(DefaultJdbcDatabase.java:62) ~[io.airbyte-airbyte-db-0.29.11-alpha.jar:?]
2021-09-06 15:16:53 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.db.jdbc.JdbcDatabase.execute(JdbcDatabase.java:54) ~[io.airbyte-airbyte-db-0.29.11-alpha.jar:?]
2021-09-06 15:16:53 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.integrations.destination.oracle.OracleOperations.createTableIfNotExists(OracleOperations.java:67) ~[io.airbyte.airbyte-integrations.connectors-destination-oracle-0.29.11-alpha.jar:?]
2021-09-06 15:16:53 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.integrations.destination.jdbc.AbstractJdbcDestination.attemptSQLCreateAndDropTableOperations(AbstractJdbcDestination.java:99) ~[io.airbyte.airbyte-integrations.connectors-destination-jdbc-0.29.11-alpha.jar:?]
2021-09-06 15:16:53 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.integrations.destination.jdbc.AbstractJdbcDestination.check(AbstractJdbcDestination.java:77) [io.airbyte.airbyte-integrations.connectors-destination-jdbc-0.29.11-alpha.jar:?]
2021-09-06 15:16:53 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:122) [io.airbyte.airbyte-integrations.bases-base-java-0.29.11-alpha.jar:?]
2021-09-06 15:16:53 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.integrations.destination.oracle.OracleDestination.main(OracleDestination.java:71) [io.airbyte.airbyte-integrations.connectors-destination-oracle-0.29.11-alpha.jar:?]
2021-09-06 15:16:53 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - Caused by: oracle.jdbc.OracleDatabaseException: ORA-00972: identifier is too long
2021-09-06 15:16:53 INFO () JsonSchemaValidator(test):76 - JSON schema validation failed. 
errors: $: unknown found, object expected
2021-09-06 15:16:53 ERROR () DefaultAirbyteStreamFactory(lambda$create$1):83 - Validation failed: null
2021-09-06 15:16:53 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:513) ~[ojdbc8-19.7.0.0.jar:19.7.0.0.0]
2021-09-06 15:16:53 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	... 22 more
2021-09-06 15:16:54 INFO () TemporalAttemptExecution(get):139 - Stopping cancellation check scheduling..
</details>

## Steps to Reproduce
1. Install Airbyte
2. Create source connection with oracle
3. Create destination connection with oracle (oracle alpha)

**Comment by marcosmarxm** [comment]
@nijatrzayev1 what version of Oracle database are you using in destination? After 0.1.6 we only support Oracle 18 where the table name length are 120 chars. If you're using 12 you need to enable your database to support this table name length.

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 365 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.
