### ISSUE TITLE
Connector Iterable failing in normalization process

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#5867]
## Enviroment
- **Airbyte version**:  0.29.15-alpha
- **OS Version / Instance**: ~
- **Deployment**: ~
- **Source Connector and version**: Iterable 0.1.6
- **Destination Connector and version**: Redshift 0.3.13
- **Severity**: Very Low / Low / Medium / **High** / Critical
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
Normalization is failing because of wrong data type.

## Expected Behavior
*Tell us what should happen.*

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

2021-09-06 18:41:49 INFO () WorkerRun(call):62 - Executing worker wrapper. Airbyte version: 0.29.15-alpha
2021-09-06 18:41:49 INFO () TemporalAttemptExecution(get):111 - Executing worker wrapper. Airbyte version: 0.29.15-alpha
2021-09-06 18:41:49 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 18:41:49 INFO () DefaultReplicationWorker(run):102 - start sync worker. job id: 4 attempt id: 1
2021-09-06 18:41:49 INFO () DefaultReplicationWorker(run):111 - configured sync modes: {null.email_subscribe=full_refresh - overwrite, null.email_send_skip=full_refresh - overwrite, null.email_unsubscribe=full_refresh - overwrite, null.message_types=full_refresh - overwrite, null.email_complaint=full_refresh - overwrite, null.list_users=full_refresh - overwrite, null.channels=full_refresh - overwrite, null.email_open=full_refresh - overwrite, null.campaigns=full_refresh - overwrite, null.lists=full_refresh - overwrite, null.email_click=full_refresh - overwrite, null.metadata=full_refresh - overwrite, null.users=full_refresh - overwrite, null.email_send=full_refresh - overwrite, null.templates=full_refresh - overwrite, null.email_bounce=full_refresh - overwrite}
2021-09-06 18:41:49 INFO () DefaultAirbyteDestination(start):78 - Running destination...
2021-09-06 18:41:49 INFO () LineGobbler(voidCall):85 - Checking if airbyte/destination-redshift:0.3.13 exists...
2021-09-06 18:41:49 INFO () LineGobbler(voidCall):85 - airbyte/destination-redshift:0.3.13 was found locally.
2021-09-06 18:41:49 INFO () DockerProcessFactory(create):146 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/4/1 --network host --log-driver none airbyte/destination-redshift:0.3.13 write --config destination_config.json --catalog destination_catalog.json
2021-09-06 18:41:49 INFO () LineGobbler(voidCall):85 - Checking if airbyte/source-iterable:0.1.6 exists...
2021-09-06 18:41:49 INFO () LineGobbler(voidCall):85 - airbyte/source-iterable:0.1.6 was found locally.
2021-09-06 18:41:49 INFO () DockerProcessFactory(create):146 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/4/1 --network host --log-driver none airbyte/source-iterable:0.1.6 read --config source_config.json --catalog source_catalog.json
2021-09-06 18:41:49 INFO () DefaultReplicationWorker(lambda$getDestinationOutputRunnable$3):246 - Destination output thread started.
2021-09-06 18:41:49 INFO () DefaultReplicationWorker(run):139 - Waiting for source thread to join.
2021-09-06 18:41:49 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):210 - Replication thread started.
2021-09-06 18:41:59 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:41:59 [32mINFO[m i.a.i.d.r.RedshiftDestination(main):97 - {} - starting destination: class io.airbyte.integrations.destination.redshift.RedshiftDestination
2021-09-06 18:41:59 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 18:41:59 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:41:59 [32mINFO[m i.a.i.b.IntegrationRunner(run):96 - {} - Running integration: io.airbyte.integrations.destination.redshift.RedshiftDestination
2021-09-06 18:41:59 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:41:59 [32mINFO[m i.a.i.b.IntegrationCliParser(parseOptions):135 - {} - integration args: {catalog=destination_catalog.json, write=null, config=destination_config.json}
2021-09-06 18:41:59 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:41:59 [32mINFO[m i.a.i.b.IntegrationRunner(run):100 - {} - Command: WRITE
2021-09-06 18:41:59 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:41:59 [32mINFO[m i.a.i.b.IntegrationRunner(run):101 - {} - Integration config: IntegrationConfig{command=WRITE, configPath='destination_config.json', catalogPath='destination_catalog.json', statePath='null'}
2021-09-06 18:41:59 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:41:59 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword examples - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2021-09-06 18:41:59 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:41:59 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2021-09-06 18:41:59 INFO () TemporalAttemptExecution(lambda$getCancellationChecker$3):186 - Running sync worker cancellation...
2021-09-06 18:41:59 INFO () DefaultReplicationWorker(cancel):270 - Cancelling replication worker...
2021-09-06 18:41:59 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:41:59 [32mINFO[m i.a.i.d.j.c.SwitchingDestination(getConsumer):83 - {} - Using destination type: INSERT
2021-09-06 18:42:00 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:42:00 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=campaigns, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_lkb_campaigns, outputTableName=_airbyte_raw_campaigns, syncMode=overwrite}
2021-09-06 18:42:00 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:42:00 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=channels, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_rsp_channels, outputTableName=_airbyte_raw_channels, syncMode=overwrite}
2021-09-06 18:42:00 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:42:00 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=email_bounce, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_pzc_email_bounce, outputTableName=_airbyte_raw_email_bounce, syncMode=overwrite}
2021-09-06 18:42:00 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:42:00 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=email_click, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_nop_email_click, outputTableName=_airbyte_raw_email_click, syncMode=overwrite}
2021-09-06 18:42:00 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:42:00 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=email_complaint, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_xji_email_complaint, outputTableName=_airbyte_raw_email_complaint, syncMode=overwrite}
2021-09-06 18:42:00 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:42:00 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=email_open, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_bvt_email_open, outputTableName=_airbyte_raw_email_open, syncMode=overwrite}
2021-09-06 18:42:00 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:42:00 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=email_send, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_ifv_email_send, outputTableName=_airbyte_raw_email_send, syncMode=overwrite}
2021-09-06 18:42:00 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:42:00 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=email_send_skip, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_zpg_email_send_skip, outputTableName=_airbyte_raw_email_send_skip, syncMode=overwrite}
2021-09-06 18:42:00 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:42:00 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=email_subscribe, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_uhq_email_subscribe, outputTableName=_airbyte_raw_email_subscribe, syncMode=overwrite}
2021-09-06 18:42:00 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:42:00 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=email_unsubscribe, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_eaf_email_unsubscribe, outputTableName=_airbyte_raw_email_unsubscribe, syncMode=overwrite}
2021-09-06 18:42:00 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:42:00 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=list_users, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_ihj_list_users, outputTableName=_airbyte_raw_list_users, syncMode=overwrite}
2021-09-06 18:42:00 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:42:00 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=lists, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_dzn_lists, outputTableName=_airbyte_raw_lists, syncMode=overwrite}
2021-09-06 18:42:00 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:42:00 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=message_types, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_rbr_message_types, outputTableName=_airbyte_raw_message_types, syncMode=overwrite}
2021-09-06 18:42:00 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:42:00 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=metadata, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_kur_metadata, outputTableName=_airbyte_raw_metadata, syncMode=overwrite}
2021-09-06 18:42:00 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:42:00 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=templates, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_pdp_templates, outputTableName=_airbyte_raw_templates, syncMode=overwrite}
2021-09-06 18:42:00 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:42:00 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=users, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_pbj_users, outputTableName=_airbyte_raw_users, syncMode=overwrite}
2021-09-06 18:42:00 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:42:00 [32mINFO[m i.a.i.d.b.BufferedStreamConsumer(startTracked):142 - {} - class io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer started.
2021-09-06 18:42:00 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:42:00 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):139 - {} - Preparing tmp tables in destination started for 16 streams
2021-09-06 18:42:00 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:42:00 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream campaigns. schema: public, tmp table name: _airbyte_tmp_lkb_campaigns
2021-09-06 18:42:03 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:42:03 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream channels. schema: public, tmp table name: _airbyte_tmp_rsp_channels
2021-09-06 18:42:03 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:42:03 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream email_bounce. schema: public, tmp table name: _airbyte_tmp_pzc_email_bounce
2021-09-06 18:42:04 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Starting syncing SourceIterable
2021-09-06 18:42:04 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Syncing stream: campaigns 
2021-09-06 18:42:04 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Read 2 records from campaigns stream
2021-09-06 18:42:04 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Syncing stream: channels 
2021-09-06 18:42:04 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Read 3 records from channels stream
2021-09-06 18:42:04 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Syncing stream: email_bounce 
2021-09-06 18:42:04 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Read 1 records from email_bounce stream
2021-09-06 18:42:04 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Syncing stream: email_click 
2021-09-06 18:42:04 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Read 6 records from email_click stream
2021-09-06 18:42:04 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Syncing stream: email_complaint 
2021-09-06 18:42:04 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Read 0 records from email_complaint stream
2021-09-06 18:42:04 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Syncing stream: email_open 
2021-09-06 18:42:04 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:42:04 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream email_click. schema: public, tmp table name: _airbyte_tmp_nop_email_click
2021-09-06 18:42:05 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:42:05 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream email_complaint. schema: public, tmp table name: _airbyte_tmp_xji_email_complaint
2021-09-06 18:42:05 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:42:05 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream email_open. schema: public, tmp table name: _airbyte_tmp_bvt_email_open
2021-09-06 18:42:06 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Read 10 records from email_open stream
2021-09-06 18:42:06 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Syncing stream: email_send 
2021-09-06 18:42:06 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Read 2 records from email_send stream
2021-09-06 18:42:06 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Syncing stream: email_send_skip 
2021-09-06 18:42:06 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Read 0 records from email_send_skip stream
2021-09-06 18:42:06 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Syncing stream: email_subscribe 
2021-09-06 18:42:06 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:42:06 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream email_send. schema: public, tmp table name: _airbyte_tmp_ifv_email_send
2021-09-06 18:42:06 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Read 62 records from email_subscribe stream
2021-09-06 18:42:06 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Syncing stream: email_unsubscribe 
2021-09-06 18:42:07 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:42:07 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream email_send_skip. schema: public, tmp table name: _airbyte_tmp_zpg_email_send_skip
2021-09-06 18:42:07 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:42:07 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream email_subscribe. schema: public, tmp table name: _airbyte_tmp_uhq_email_subscribe
2021-09-06 18:42:08 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:42:08 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream email_unsubscribe. schema: public, tmp table name: _airbyte_tmp_eaf_email_unsubscribe
2021-09-06 18:42:09 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:42:09 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream list_users. schema: public, tmp table name: _airbyte_tmp_ihj_list_users
2021-09-06 18:42:09 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 18:42:09 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream lists. schema: public, tmp table name: _airbyte_tmp_dzn_lists
2021-09-06 18:42:09 INFO () DefaultReplicationWorker(cancel):278 - Cancelling destination...
2021-09-06 18:42:09 INFO () DefaultAirbyteDestination(cancel):134 - Attempting to cancel destination process...
2021-09-06 18:42:09 INFO () DefaultAirbyteDestination(cancel):139 - Destination process exists, cancelling...
2021-09-06 18:42:12 INFO () DefaultAirbyteDestination(cancel):141 - Cancelled destination process!
2021-09-06 18:42:12 INFO () DefaultReplicationWorker(cancel):285 - Cancelling source...
2021-09-06 18:42:12 INFO () DefaultAirbyteSource(cancel):141 - Attempting to cancel source process...
2021-09-06 18:42:12 INFO () DefaultAirbyteSource(cancel):146 - Source process exists, cancelling...
2021-09-06 18:42:15 INFO () DefaultAirbyteSource(cancel):148 - Cancelled source process!
2021-09-06 18:42:15 INFO () TemporalAttemptExecution(lambda$getCancellationChecker$3):190 - Interrupting worker thread...
2021-09-06 18:42:15 INFO () DefaultReplicationWorker(run):141 - Source thread complete.
2021-09-06 18:42:15 INFO () TemporalAttemptExecution(lambda$getCancellationChecker$3):193 - Cancelling completable future...
2021-09-06 18:42:15 INFO () DefaultReplicationWorker(run):142 - Waiting for destination thread to join.
2021-09-06 18:42:15 INFO () DefaultReplicationWorker(run):144 - Destination thread complete.
2021-09-06 18:42:15 WARN () CancellationHandler$TemporalCancellationHandler(checkAndHandleCancellation):71 - Job either timeout-ed or was cancelled.
2021-09-06 18:42:15 INFO () TemporalAttemptExecution(get):139 - Stopping cancellation check scheduling...
2021-09-06 18:42:15 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 18:42:15 WARN () POJOActivityTaskHandler$POJOActivityImplementation(execute):243 - Activity failure. ActivityId=3a47dfbc-ed2c-348c-b5f8-2283a4d55342, activityType=Replicate, attempt=1
java.util.concurrent.CancellationException: null
	at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2468) ~[?:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getCancellationChecker$3(TemporalAttemptExecution.java:196) ~[io.airbyte-airbyte-workers-0.29.15-alpha.jar:?]
	at io.airbyte.workers.temporal.CancellationHandler$TemporalCancellationHandler.checkAndHandleCancellation(CancellationHandler.java:70) ~[io.airbyte-airbyte-workers-0.29.15-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getCancellationChecker$4(TemporalAttemptExecution.java:199) ~[io.airbyte-airbyte-workers-0.29.15-alpha.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
2021-09-06 18:42:15 ERROR () DefaultReplicationWorker(run):148 - Sync worker failed.
io.airbyte.workers.WorkerException: Source process exit with code 143. This warning is normal if the job was cancelled.
	at io.airbyte.workers.protocols.airbyte.DefaultAirbyteSource.close(DefaultAirbyteSource.java:135) ~[io.airbyte-airbyte-workers-0.29.15-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:146) ~[io.airbyte-airbyte-workers-0.29.15-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:52) ~[io.airbyte-airbyte-workers-0.29.15-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:152) ~[io.airbyte-airbyte-workers-0.29.15-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
	Suppressed: java.io.IOException: Stream closed
		at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:442) ~[?:?]
		at java.io.OutputStream.write(OutputStream.java:162) ~[?:?]
		at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81) ~[?:?]
		at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142) ~[?:?]
		at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:327) ~[?:?]
		at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:159) ~[?:?]
		at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:251) ~[?:?]
		at java.io.BufferedWriter.flush(BufferedWriter.java:257) ~[?:?]
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.notifyEndOfStream(DefaultAirbyteDestination.java:107) ~[io.airbyte-airbyte-workers-0.29.15-alpha.jar:?]
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.close(DefaultAirbyteDestination.java:120) ~[io.airbyte-airbyte-workers-0.29.15-alpha.jar:?]
		at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:121) ~[io.airbyte-airbyte-workers-0.29.15-alpha.jar:?]
		at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:52) ~[io.airbyte-airbyte-workers-0.29.15-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:152) ~[io.airbyte-airbyte-workers-0.29.15-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:832) [?:?]
2021-09-06 18:42:15 INFO () DefaultReplicationWorker(run):172 - sync summary: io.airbyte.config.ReplicationAttemptSummary@5fb7cf4d[status=cancelled,recordsSynced=118,bytesSynced=26682,startTime=1630953709707,endTime=1630953735289]
2021-09-06 18:42:15 INFO () DefaultReplicationWorker(run):181 - Source did not output any state messages
2021-09-06 18:42:15 WARN () DefaultReplicationWorker(run):192 - State capture: No state retained.
2021-09-06 18:42:15 WARN () CancellationHandler$TemporalCancellationHandler(checkAndHandleCancellation):71 - Job either timeout-ed or was cancelled.

```

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by sherifnada** [comment]
Logs: 
[logs-10-0 (2).txt](https://github.com/airbytehq/airbyte/files/7141730/logs-10-0.2.txt)

From the Slack conversation: https://airbytehq.slack.com/archives/C01MFR03D5W/p1630434713206800
