### ISSUE TITLE
source asana  - fix schema related failure

### ISSUE THREAD

**Issue by midavadim** [airbytehq/airbyte#5975]
the connector's build [is failing](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/builds.md). This issue tracks fixing it.

**Comment by yevhenii-ldv** [comment]
It looks like there is a problem with schema correctness for the following streams (issue with `format` for fields):
- sections
- stories
- tasks
- users
```
------------------------------ Captured log call -------------------------------
ERROR    root:test_core.py:158 The sections stream has the following schema errors:
'2021-06-29T09:42:21.036Z' is not of type 'null', 'array'

Failed validating 'type' in schema['properties'***['created_at'***:
    ***'format': 'date-time', 'type': ['null', 'array'***

On instance['created_at'***:
    '2021-06-29T09:42:21.036Z'
ERROR    root:test_core.py:158 The stories stream has the following schema errors:
'2021-06-29T09:45:51.926Z' is not of type 'null', 'array'

Failed validating 'type' in schema['properties'***['created_at'***:
    ***'format': 'date-time', 'type': ['null', 'array'***

On instance['created_at'***:
    '2021-06-29T09:45:51.926Z'
ERROR    root:test_core.py:158 The tasks stream has the following schema errors:
' https://github.com/airbytehq/airbyte/pull/4376' is not of type 'null', 'boolean'

Failed validating 'type' in schema['properties'***['custom_fields'***['items'***['properties'***['text_value'***:
    ***'type': ['null', 'boolean'***

On instance['custom_fields'***[12***['text_value'***:
    ' https://github.com/airbytehq/airbyte/pull/4376'
ERROR    root:test_core.py:158 The users stream has the following schema errors:
[***'gid': '1200272750255812'*** ***'gid': '1199152354181012'*** is not of type 'null', 'object'

Failed validating 'type' in schema['properties'***['workspaces'***:
    ***'properties': ***'gid': ***'type': ['null', 'string'***
                    'name': ***'type': ['null', 'string'***
                    'resource_type': ***'type': ['null', 'string'***
     'type': ['null', 'object'***

On instance['workspaces'***:
    [***'gid': '1200272750255812'*** ***'gid': '1199152354181012'***
```

Also, you need to fix the `invalid_config.json` file so that the keys match the `spec.json`.
```
E           docker.errors.ContainerError: Command 'check --config tap_config.json' in image 'sha256:a882940262858c1389406dc7c32d4da79e443647f4effa6778f3cdb6f16d7226' returned non-zero exit status 1: Traceback (most recent call last):
E             File "/airbyte/integration_code/main.py", line 33, in <module>
E               launch(source, sys.argv[1:***)
E             File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 125, in launch
E               for message in source_entrypoint.run(parsed_args):
E             File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 96, in run
E               check_config_against_spec_or_exit(config, source_spec, logger)
E             File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/utils/schema_helpers.py", line 141, in check_config_against_spec_or_exit
E               raise Exception("Config validation error: " + validation_error.message) from None
E           Exception: Config validation error: 'access_token' is a required property
```
