### ISSUE TITLE
Stream was allocated the part numbers from 1 (inclusive) to 10001 (exclusive)and it has gone beyond the end

### ISSUE THREAD

**Issue by chandininekkantti** [airbytehq/airbyte#6245]
## Enviroment
- **Airbyte version**: 0.29.19-alpha
- **OS Version / Instance**:  GCP c2-standard-16 (16 vCPUs, 64 GB memory)
- **Deployment**: Docker 
- **Source Connector and version**: airbyte/source-snowflake 0.1.1
- **Destination Connector and version**:  airbyte/destination-bigquery | 0.4.0 |  
- **Severity**:  Critical
- **Step where error happened**: Sync job 

## Current Behavior
Have GCS enabled to store the tmp files and set to 5M B chunk. However, I see following errors after 5 hours of Airbyte running

## Expected Behavior
The tmp files getting uploaded to GCS bucket.

## Logs
The following is just snapshot of error. I have same error for almost 30 tables.
<details>
<summary>LOG</summary> 

```
2021-09-18 11:03:37 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-18 11:03:37 [33mWARN[m i.a.i.d.g.w.BaseGcsWriter(close):127 - {} - Upload of stream 'SAT_SITE_TEST' aborted.
2021-09-18 11:03:37 ERROR () LineGobbler(voidCall):85 - Exception in thread "main" java.lang.IndexOutOfBoundsException: This stream was allocated the part numbers from 1 (inclusive) to 10001 (exclusive)and it has gone beyond the end.
2021-09-18 11:03:37 ERROR () LineGobbler(voidCall):85 - 	at alex.mojaki.s3upload.MultiPartOutputStream.putCurrentStream(MultiPartOutputStream.java:121)
2021-09-18 11:03:37 ERROR () LineGobbler(voidCall):85 - 	at alex.mojaki.s3upload.MultiPartOutputStream.checkSize(MultiPartOutputStream.java:110)
2021-09-18 11:03:37 ERROR () LineGobbler(voidCall):85 - 	at alex.mojaki.s3upload.MultiPartOutputStream.write(MultiPartOutputStream.java:143)
2021-09-18 11:03:37 ERROR () LineGobbler(voidCall):85 - 	at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:242)
2021-09-18 11:03:37 ERROR () LineGobbler(voidCall):85 - 	at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:312)
2021-09-18 11:03:37 ERROR () LineGobbler(voidCall):85 - 	at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:290)
2021-09-18 11:03:37 ERROR () LineGobbler(voidCall):85 - 	at java.base/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:131)
2021-09-18 11:03:37 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.io.OutputStreamWriter.write(OutputStreamWriter.java:208)
```
</details>

## Steps to Reproduce
1. Choose BiQuery as destination
2. Enable GCS staging with 5MB as chunk and transfer 1GB table from SnowFlake
3. Run job

## Are you willing to submit a PR?
No

**Comment by joshuataylor** [comment]
As a workaround, can we configure how big the chunk size is, that we we don't break the current implementation?

Otherwise can we flush to our destination every 10k parts?
