### ISSUE TITLE
UI unresponsive and Too many open files

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#6468]
## Enviroment
OS Version / Instance: Linux EC2 m5.xlarge
Deployment: Docker
Airbyte Version: 0.29.22-alpha

## Current Behavior
UI unresponsive (loading wheel), webapp container seems fine but running into Too many open files issue. Possibly a related issue?

## Expected Behavior
*Tell us what should happen.*

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by jrhizor** [comment]
Any more context on this @harshithmullapudi ? Is this happening on startup for the first time or an existing / long running instance? Why does it look like a too many open files issue?

**Comment by harshithmullapudi** [comment]
Hey @jrhizor i have requested @danieldiamond to add logs here will update it

**Comment by danieldiamond** [comment]
Hi @jrhizor the context is:
* several MySQL to Snowflake connectors (each source is a different MySQL RDS instance) using CDC
* Each connector syncs every 30minutes (the way airbyte scheduling or rather delayed jobs works these syncs end up converging to sync at the same time)
* One my sources is unable to sync all the tables using CDC, so i removed 2 of the tables and tried them as their own connector, this doesn't work either, the sync just hangs - it's an issue with CDC but probably not relevant for this issue
* Given the above point (the 2 tables not working in CDC), I created seperate connectors using STANDARD (non-CDC) syncing
* I wanted to see if the CDC issue was resolved and so I paused the two (STANDARD) connectors and made a new CDC connector with one of these tables. It appeared to get past the hanging state that I normally experience but then a new error appeared. 

Here are the logs of the new error
```
2021-09-26 02:45:03 WARN () GrpcRetryer(retryWithResult):152 - Retrying after failure
io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262) ~[grpc-stub-1.40.0.jar:1.40.0]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243) ~[grpc-stub-1.40.0.jar:1.40.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156) ~[grpc-stub-1.40.0.jar:1.40.0]
	at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.getWorkflowExecutionHistory(WorkflowServiceGrpc.java:2638) ~[temporal-serviceclient-1.0.4.jar:?]
	at io.temporal.internal.common.WorkflowExecutionUtils.lambda$getInstanceCloseEvent$1(WorkflowExecutionUtils.java:256) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.common.GrpcRetryer.retryWithResult(GrpcRetryer.java:127) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.common.WorkflowExecutionUtils.getInstanceCloseEvent(WorkflowExecutionUtils.java:244) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.common.WorkflowExecutionUtils.getWorkflowExecutionResult(WorkflowExecutionUtils.java:132) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.WorkflowStubImpl.getResult(WorkflowStubImpl.java:346) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.WorkflowStubImpl.getResult(WorkflowStubImpl.java:328) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.WorkflowInvocationHandler$SyncWorkflowInvocationHandler.startWorkflow(WorkflowInvocationHandler.java:315) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.WorkflowInvocationHandler$SyncWorkflowInvocationHandler.invoke(WorkflowInvocationHandler.java:270) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.WorkflowInvocationHandler.invoke(WorkflowInvocationHandler.java:178) ~[temporal-sdk-1.0.4.jar:?]
	at com.sun.proxy.$Proxy38.run(Unknown Source) ~[?:?]
	at io.airbyte.workers.temporal.TemporalClient.lambda$submitSync$3(TemporalClient.java:124) ~[io.airbyte-airbyte-workers-0.29.22-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalClient.execute(TemporalClient.java:144) ~[io.airbyte-airbyte-workers-0.29.22-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalClient.submitSync(TemporalClient.java:123) ~[io.airbyte-airbyte-workers-0.29.22-alpha.jar:?]
	at io.airbyte.scheduler.app.worker_run.TemporalWorkerRunFactory.lambda$createSupplier$0(TemporalWorkerRunFactory.java:67) ~[io.airbyte.airbyte-scheduler-app-0.29.22-alpha.jar:?]
	at io.airbyte.scheduler.app.worker_run.WorkerRun.call(WorkerRun.java:65) [io.airbyte.airbyte-scheduler-app-0.29.22-alpha.jar:?]
	at io.airbyte.scheduler.app.worker_run.WorkerRun.call(WorkerRun.java:43) [io.airbyte.airbyte-scheduler-app-0.29.22-alpha.jar:?]
	at io.airbyte.commons.concurrency.LifecycledCallable.execute(LifecycledCallable.java:114) [io.airbyte-airbyte-commons-0.29.22-alpha.jar:?]
	at io.airbyte.commons.concurrency.LifecycledCallable.call(LifecycledCallable.java:98) [io.airbyte-airbyte-commons-0.29.22-alpha.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

The logs for this error would continue again and again and the UI became unresponsive.

With all the context above I imagine that this bloated the airbyte instance as the instance still also has to process all the other connectors

**Comment by harshithmullapudi** [comment]
@manavkohli as we are looking into it. For to solve it immediately you can restart the docker. Can you also add some details on the version of airbyte you are using?

**Comment by manavkohli** [comment]
@harshithmullapudi thanks for taking a look - restarting docker works, though we have 100s of jobs running at a time and rely on the API for our onboarding flow. We're using `0.30.8-alpha`

@danieldiamond thanks also for that tip, unfortunately since we have so many jobs running somewhat difficult to guarantee that all are disabled each time the server starts throwing 500s :(

**Comment by manavkohli** [comment]
@danieldiamond @harshithmullapudi do either of you actively use the `/v1/web_backend/connections/search` API? This issue seemed to arise after starting to make use of the API more heavily

**Comment by hbd** [comment]
> @danieldiamond @olivermeyer can you give an idea how many connections/sources/destinations you're running? We are running around 50+ of each and are seeing this issue.

Additionally, how frequently are you using the UI? Our use of UI seems to correlate with the `server` service failing.

**Comment by danieldiamond** [comment]
~15 connectors. not using the API. mainly use the UI and quite heavily

**Comment by manavkohli** [comment]
We actually ended up modifying the compose file to restart the server container on failure and increase the open file limit as a stop gap

**Comment by timroes** [comment]
Closing this issue due to inactivity.

*We are trying to keep our issues to a manageable amount, which means we are trying to close issues we cannot reproduce or gather required information for some time. Please feel free to still provide the requested information in case the issue still persists. We will gladly reopen this issue again.*
