### ISSUE TITLE
Source: Google Search Console Bug - Not working with service account 

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#6697]
## Enviroment
OS Version / Instance: Linux EC2 m5.xlarge
Deployment: Docker
Airbyte Version: 0.29.20-alpha
Source name: GSC 0.1.2
destination: Redshift 0.3.14

## Current Behavior
Failed sync Bad Request for url: https://www.googleapis.com/webmasters/v3/sites/https%3A%2F%2Fmydomain.com/searchAnalytics/query
logs in thread

```
2021-09-23 08:09:48 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Syncing stream: search_analytics_by_page
2021-09-23 08:09:48 ERROR () LineGobbler(voidCall):85 - Traceback (most recent call last):
2021-09-23 08:09:48 ERROR () LineGobbler(voidCall):85 -   File "/airbyte/integration_code/main.py", line 33, in <module>
2021-09-23 08:09:48 ERROR () LineGobbler(voidCall):85 -     launch(source, sys.argv[1:])
2021-09-23 08:09:48 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 125, in launch
2021-09-23 08:09:48 ERROR () LineGobbler(voidCall):85 -     for message in source_entrypoint.run(parsed_args):
2021-09-23 08:09:48 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 116, in run
2021-09-23 08:09:48 ERROR () LineGobbler(voidCall):85 -     for message in generator:
2021-09-23 08:09:48 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 121, in read
2021-09-23 08:09:48 ERROR () LineGobbler(voidCall):85 -     raise e
2021-09-23 08:09:48 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 117, in read
2021-09-23 08:09:48 ERROR () LineGobbler(voidCall):85 -     internal_config=internal_config,
2021-09-23 08:09:48 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 147, in _read_stream
2021-09-23 08:09:48 ERROR () LineGobbler(voidCall):85 -     for record in record_iterator:
2021-09-23 08:09:48 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 192, in _read_incremental
2021-09-23 08:09:48 ERROR () LineGobbler(voidCall):85 -     for record_counter, record_data in enumerate(records, start=1):
2021-09-23 08:09:48 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 372, in read_records
2021-09-23 08:09:48 ERROR () LineGobbler(voidCall):85 -     response = self._send_request(request, request_kwargs)
2021-09-23 08:09:48 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 339, in _send_request
2021-09-23 08:09:48 ERROR () LineGobbler(voidCall):85 -     return backoff_handler(user_backoff_handler)(request, request_kwargs)
2021-09-23 08:09:48 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
2021-09-23 08:09:48 ERROR () LineGobbler(voidCall):85 -     ret = target(*args, **kwargs)
2021-09-23 08:09:48 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
2021-09-23 08:09:48 ERROR () LineGobbler(voidCall):85 -     ret = target(*args, **kwargs)
2021-09-23 08:09:48 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - Encountered an exception while reading stream SourceGoogleSearchConsole
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 117, in read
    internal_config=internal_config,
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 147, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 192, in _read_incremental
    for record_counter, record_data in enumerate(records, start=1):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 372, in read_records
    response = self._send_request(request, request_kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 339, in _send_request
    return backoff_handler(user_backoff_handler)(request, request_kwargs)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 305, in _send
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.googleapis.com/webmasters/v3/sites/https%3A%2F%2Fmydomain.com/searchAnalytics/query
```

## Expected Behavior
*Tell us what should happen.*

Here is the slack convo https://airbytehq.slack.com/archives/C01MFR03D5W/p1632386847225300

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by sherifnada** [comment]
@danieldiamond could you try the new connector version and let us know if the issue persists?

**Comment by danieldiamond** [comment]
hey @sherifnada thanks for reaching out. the issue related to this specific issue was that the connector required an `end_date`, i was able to get it working by manually putting in a future `end_date`. i believe a PR has been merged that defaults this to sometime in the future.

i was separately help up on a seperate issue regarding incremental streams: https://github.com/airbytehq/airbyte/issues/7479 (i'll refrain from discussing that issue here)
