### ISSUE TITLE
Facebook Marketing Source Sync Failing

### ISSUE THREAD

**Issue by jd-sanders** [airbytehq/airbyte#6726]
## Enviroment
- **Airbyte version**:  0.29.19-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Facebook Marketing 0.2.19 
- **Destination Connector and version**: Big Query 0.4.0 
- **Severity**: Critical
- **Step where error happened**: Sync job

## Current Behavior
The Facebook Marketing stream sync fails for every/any object requested.  Logs.  This appears to be systemic and failed every sync job we have.  Logs below.  

## Expected Behavior
The sync should successfully complete

## Logs
```
2021-10-04 16:02:57 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Starting syncing SourceFacebookMarketing
2021-10-04 16:02:57 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Syncing stream: ad_creatives 
2021-10-04 16:02:57 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - Encountered an exception while reading stream SourceFacebookMarketing
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 117, in read
    internal_config=internal_config,
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 147, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 219, in _read_full_refresh
    for record in records:
  File "/airbyte/integration_code/source_facebook_marketing/streams.py", line 281, in read_records
    records = self._read_records(params=self.request_params(stream_state=stream_state))
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/airbyte/integration_code/source_facebook_marketing/streams.py", line 297, in _read_records
    return self._api.account.get_ad_creatives(params=params)
  File "/usr/local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/airbyte/integration_code/source_facebook_marketing/api.py", line 127, in account
    return self._find_account(self._account_id)
  File "/airbyte/integration_code/source_facebook_marketing/api.py", line 133, in _find_account
    accounts = fb_user.User(fbid="me").get_ad_accounts()
  File "/usr/local/lib/python3.7/site-packages/facebook_business/adobjects/user.py", line 456, in get_ad_accounts
    return request.execute()
  File "/usr/local/lib/python3.7/site-packages/facebook_business/api.py", line 677, in execute
    cursor.load_next_page()
  File "/usr/local/lib/python3.7/site-packages/facebook_business/api.py", line 866, in load_next_page
    self._queue = self.build_objects_from_response(response)
  File "/usr/local/lib/python3.7/site-packages/facebook_business/api.py", line 875, in build_objects_from_response
    return self._object_parser.parse_multiple(response)
  File "/usr/local/lib/python3.7/site-packages/facebook_business/adobjects/objectparser.py", line 96, in parse_multiple
    self._target_class)]
  File "/usr/local/lib/python3.7/site-packages/facebook_business/adobjects/abstractobject.py", line 173, in create_object
    new_object._set_data(data)
  File "/usr/local/lib/python3.7/site-packages/facebook_business/adobjects/abstractcrudobject.py", line 192, in _set_data
    self[key] = data[key]
TypeError: string indices must be integers
```

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1.  Set up connection with Facebook Marketing Source (any stream)
2.  Try to run

## Are you willing to submit a PR?

Unfortunately, I can't at the moment.

**Comment by jd-sanders** [comment]
Oh,  I just realized FB is experiencing a global outage.  This may be... that.
