### ISSUE TITLE
improve UX when pulling images is slower than timeout

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#696]
## Expected Behavior
The UI should not hang without any indication to the user while trying to pull an image and failing. 

## Current Behavior
The UI just hangs if it fails to pull the image in the time limit.

Example log output:
```
[32mairbyte-scheduler |[0m 2020-10-23 03:59:24 [1;31mERROR[m i.a.w.DefaultGetSpecWorker(run):102 - {job_id=7, job_log_filename=logs.log, job_root=/tmp/workspace/7/0} - Error while getting spec from image airbyte/postgres-singer-source-abprotocol:0.1.0: java.lang.IllegalThreadStateException: process hasn't exited
[32mairbyte-scheduler |[0m 2020-10-23 03:59:24 [32mINFO[m i.a.s.p.DefaultSchedulerPersistence(updateStatus):200 - {job_id=7, job_log_filename=logs.log, job_root=/tmp/workspace/7/0} - Setting job status to FAILED for job 7
[32mairbyte-scheduler |[0m 2020-10-23 03:59:24 [32mINFO[m i.a.s.JobRetrier(run):53 - {} - Running job-retrier...
[32mairbyte-scheduler |[0m 2020-10-23 03:59:24 [32mINFO[m i.a.s.JobRetrier(run):67 - {} - Completed job-retrier...
[32mairbyte-scheduler |[0m 2020-10-23 03:59:24 [32mINFO[m i.a.s.JobScheduler(run):76 - {} - Running job-scheduler...
[32mairbyte-scheduler |[0m 2020-10-23 03:59:24 [32mINFO[m i.a.s.JobScheduler(run):80 - {} - Completed job-scheduler...
[32mairbyte-scheduler |[0m 2020-10-23 03:59:24 [32mINFO[m i.a.s.JobSubmitter(run):57 - {} - Running job-submitter...
[32mairbyte-scheduler |[0m 2020-10-23 03:59:24 [32mINFO[m i.a.s.JobSubmitter(run):63 - {} - Completed job-submitter...
[35mairbyte-server |[0m 2020-10-23 03:59:24 [36mDEBUG[m i.a.s.e.UncaughtExceptionMapper(toResponse):42 - {} - Uncaught exception
[35mairbyte-server |[0m java.util.NoSuchElementException: No value present
[35mairbyte-server |[0m 	at java.util.Optional.orElseThrow(Optional.java:375) ~[?:?]
[35mairbyte-server |[0m 	at io.airbyte.server.handlers.SchedulerHandler.getConnectorSpecification(SchedulerHandler.java:177) ~[io.airbyte-airbyte-server-0.2.0-alpha.jar:?]
[35mairbyte-server |[0m 	at io.airbyte.server.handlers.SchedulerHandler.getSourceSpecification(SchedulerHandler.java:157) ~[io.airbyte-airbyte-server-0.2.0-alpha.jar:?]
[35mairbyte-server |[0m 	at io.airbyte.server.apis.ConfigurationApi.lambda$getSourceSpecification$8(ConfigurationApi.java:180) ~[io.airbyte-airbyte-server-0.2.0-alpha.jar:?]
[35mairbyte-server |[0m 	at io.airbyte.server.apis.ConfigurationApi.execute(ConfigurationApi.java:349) ~[io.airbyte-airbyte-server-0.2.0-alpha.jar:?]
[35mairbyte-server |[0m 	at io.airbyte.server.apis.ConfigurationApi.getSourceSpecification(ConfigurationApi.java:180) ~[io.airbyte-airbyte-server-0.2.0-alpha.jar:?]
[35mairbyte-server |[0m 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
[35mairbyte-server |[0m 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
[35mairbyte-server |[0m 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
[35mairbyte-server |[0m 	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
[35mairbyte-server |[0m 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[jersey-server-2.31.jar:?]
[35mairbyte-server |[0m 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) ~[jersey-server-2.31.jar:?]
[35mairbyte-server |[0m 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) ~[jersey-server-2.31.jar:?]
[35mairbyte-server |[0m 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) ~[jersey-server-2.31.jar:?]
[35mairbyte-server |[0m 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[jersey-server-2.31.jar:?]
[35mairbyte-server |[0m 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469) ~[jersey-server-2.31.jar:?]
[35mairbyte-server |[0m 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391) ~[jersey-server-2.31.jar:?]
[35mairbyte-server |[0m 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80) ~[jersey-server-2.31.jar:?]
[35mairbyte-server |[0m 	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253) [jersey-server-2.31.jar:?]
[35mairbyte-server |[0m 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [jersey-common-2.31.jar:?]
[35mairbyte-server |[0m 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [jersey-common-2.31.jar:?]
[35mairbyte-server |[0m 	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [jersey-common-2.31.jar:?]
[35mairbyte-server |[0m 	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [jersey-common-2.31.jar:?]
[35mairbyte-server |[0m 	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [jersey-common-2.31.jar:?]
[35mairbyte-server |[0m 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [jersey-common-2.31.jar:?]
[35mairbyte-server |[0m 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232) [jersey-server-2.31.jar:?]
[35mairbyte-server |[0m 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680) [jersey-server-2.31.jar:?]
[35mairbyte-server |[0m 	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394) [jersey-container-servlet-core-2.31.jar:?]
[35mairbyte-server |[0m 	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) [jersey-container-servlet-core-2.31.jar:?]
[35mairbyte-server |[0m 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366) [jersey-container-servlet-core-2.31.jar:?]
[35mairbyte-server |[0m 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319) [jersey-container-servlet-core-2.31.jar:?]
[35mairbyte-server |[0m 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) [jersey-container-servlet-core-2.31.jar:?]
[35mairbyte-server |[0m 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763) [jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
[35mairbyte-server |[0m 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:569) [jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
[35mairbyte-server |[0m 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
[35mairbyte-server |[0m 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1377) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
[35mairbyte-server |[0m 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
[35mairbyte-server |[0m 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:507) [jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
[35mairbyte-server |[0m 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
[35mairbyte-server |[0m 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
[35mairbyte-server |[0m 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
[35mairbyte-server |[0m 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
[35mairbyte-server |[0m 	at org.eclipse.jetty.server.Server.handle(Server.java:501) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
[35mairbyte-server |[0m 	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
[35mairbyte-server |[0m 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
[35mairbyte-server |[0m 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
[35mairbyte-server |[0m 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
[35mairbyte-server |[0m 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
[35mairbyte-server |[0m 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
[35mairbyte-server |[0m 	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
[35mairbyte-server |[0m 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
[35mairbyte-server |[0m 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
[35mairbyte-server |[0m 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
[35mairbyte-server |[0m 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
[35mairbyte-server |[0m 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
[35mairbyte-server |[0m 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
[35mairbyte-server |[0m 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
[35mairbyte-server |[0m 	at java.lang.Thread.run(Thread.java:832) [?:?]
[35mairbyte-server |[0m Oct 23, 2020 3:59:24 AM org.glassfish.jersey.logging.LoggingInterceptor log
[35mairbyte-server |[0m INFO: 12 * Server responded with a response on thread qtp608817143-22
[35mairbyte-server |[0m 12 < 500
[35mairbyte-server |[0m 12 < Access-Control-Allow-Headers: Origin, Content-Type, Accept
[35mairbyte-server |[0m 12 < Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS, HEAD
[35mairbyte-server |[0m 12 < Access-Control-Allow-Origin: *
[35mairbyte-server |[0m 12 < Content-Type: application/json
[35mairbyte-server |[0m {"message":"internal server error"}
[35mairbyte-server |[0m 
```

## Steps to Reproduce
1. Remove your local python integration docker image
1. Throttle your internet connection or set the timeout in `DefaultGetSpecWorker`'s `gentleClose` to a very low value.
1. Try to configure Postgres.

## Severity of the bug for you
Medium

## Potential fixes (lowest to highest effort)
- Increase the timeout for first interactions with an image (getting the spec)
- We could download images at the first start of the app.
- We could show a descriptive error that asks someone to pull the image manually.
- Maybe long term we could keep track of the progress of downloading the image and have a progress bar (and no timeout because we know if it's progressing).

**Comment by cgardens** [comment]
this has been much less bad now that we cache.

**Comment by cgardens** [comment]
remaining issue is going to be handled in this issue https://github.com/airbytehq/airbyte/issues/1466
