### ISSUE TITLE
Consuming parquet data/files from s3 and writing it to Snowflake

### ISSUE THREAD

**Issue by nahta123** [airbytehq/airbyte#6987]
**Specifications:**
Deployment: Docker
Airbyte Version: v0.30.15-alpha
Source name: S3
Destination name: Snowflake
File format: parquet

**Problem:**
While consuming parquet data from s3 and writing it to Snowflake, it is facing some issue. It seems it is not able to read parquet data. While traversing the logs, it is found that some python library ('pytz') is missing.

**Solution Tried:**
However I tried to install the missing Python library('pytz'), but still it is showing the same issue. 

**Error Logs**:
_2021-10-12 03:33:52 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-12 03:33:52 [32mINFO[m i.a.i.b.IntegrationRunner(run):100 - {} - Command: WRITE
2021-10-12 03:33:52 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-12 03:33:52 [32mINFO[m i.a.i.b.IntegrationRunner(run):101 - {} - Integration config: IntegrationConfig{command=WRITE, configPath='destination_config.json', catalogPath='destination_catalog.json', statePath='null'}
2021-10-12 03:33:53 ERROR () LineGobbler(voidCall):65 - Traceback (most recent call last):
2021-10-12 03:33:53 ERROR () LineGobbler(voidCall):65 -   File "/airbyte/integration_code/main.py", line 33, in <module>
2021-10-12 03:33:53 ERROR () LineGobbler(voidCall):65 -     launch(source, sys.argv[1:])
2021-10-12 03:33:53 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 125, in launch
2021-10-12 03:33:53 ERROR () LineGobbler(voidCall):65 -     for message in source_entrypoint.run(parsed_args):
2021-10-12 03:33:53 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 116, in run
2021-10-12 03:33:53 ERROR () LineGobbler(voidCall):65 -     for message in generator:
2021-10-12 03:33:53 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 121, in read
2021-10-12 03:33:53 ERROR () LineGobbler(voidCall):65 -     raise e
2021-10-12 03:33:53 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 117, in read
2021-10-12 03:33:53 ERROR () LineGobbler(voidCall):65 -     internal_config=internal_config,
2021-10-12 03:33:53 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 147, in _read_stream
2021-10-12 03:33:53 ERROR () LineGobbler(voidCall):65 -     for record in record_iterator:
2021-10-12 03:33:53 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 181, in _read_incremental
2021-10-12 03:33:53 ERROR () LineGobbler(voidCall):65 -     for record_data in records:
2021-10-12 03:33:53 ERROR () LineGobbler(voidCall):65 -   File "/airbyte/integration_code/source_s3/source_files_abstract/stream.py", line 358, in read_records
2021-10-12 03:33:53 ERROR () LineGobbler(voidCall):65 -     for record in file_reader.stream_records(f):
2021-10-12 03:33:53 ERROR () LineGobbler(voidCall):65 -   File "/airbyte/integration_code/source_s3/source_files_abstract/formats/parquet_parser.py", line 113, in stream_records
2021-10-12 03:33:53 ERROR () LineGobbler(voidCall):65 -     batch_dict = batch.to_pydict()
2021-10-12 03:33:53 ERROR () LineGobbler(voidCall):65 -   File "pyarrow/table.pxi", line 938, in pyarrow.lib.RecordBatch.to_pydict
2021-10-12 03:33:53 ERROR () LineGobbler(voidCall):65 -   File "pyarrow/array.pxi", line 1193, in pyarrow.lib.Array.to_pylist
2021-10-12 03:33:53 ERROR () LineGobbler(voidCall):65 -   File "pyarrow/scalar.pxi", line 459, in pyarrow.lib.TimestampScalar.as_py
2021-10-12 03:33:53 ERROR () LineGobbler(voidCall):65 -   File "pyarrow/types.pxi", line 1893, in pyarrow.lib.string_to_tzinfo
2021-10-12 03:33:53 ERROR () LineGobbler(voidCall):65 -   File "pyarrow/error.pxi", line 141, in pyarrow.lib.pyarrow_internal_check_status
2021-10-12 03:33:53 ERROR () LineGobbler(voidCall):65 - **ModuleNotFoundError: No module named 'pytz'**
2021-10-12 03:33:53 INFO () DefaultAirbyteStreamFactory(internalLog):90 - initialised stream with format:
2021-10-12 03:33:53 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Starting syncing SourceS3
2021-10-12 03:33:53 INFO () DefaultAirbyteStreamFactory(internalLog):90 - **initialised stream with format: {'filetype': 'parquet', 'batch_size': 65536, 'buffer_size': 1000}**_

**Comment by marcosmarxm** [comment]
Duplicated of https://github.com/airbytehq/airbyte/issues/6594 please upgrade your source connector version to latest.

**Comment by nahta123** [comment]
I have upgraded but it's still showing me same error. Moreover George is saying that we will be fixing this issue by this week. It's in master branch but not deployed. 
Airbyte version: 0.30.15-alpha
S3 source connector version: 0.1.5
