### ISSUE TITLE
Able to control the log rotation

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#7033]
## Tell us about the problem you're trying to solve
We sync our data every 30 minutes. I believe this has led to accumulation of logs and Airbyte is choking.

## Describe the solution you’d like
Delete the old logs automatically or give option to user to configure it

## Describe the alternative you’ve considered or used
Delete logs manually

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by RKdev** [comment]
We had roughly 5000 log folders for jobs that have accumulated since officially switching to Airbyte from Stitch. One of our analysts pointed out that data from the previous day wasn't showing up in reporting.

When we logged into Airbyte the web interface was extremely slow and would just hang. We mounted the `airbyte_workspace:/data` volume to a BusyBox container and concluded that Airbyte must be trying to load the entire log history.

It wasn't clear which logs were safe to delete so we ended up doing `docker-compose down -v` and setting our connectors up again and doing a fully resync. 

This was fine for a one-off problem but isn't sustainable.

In the meantime, can you please indicate which logs are safe to delete on a regular basis?

Thanks so much everyone! We love this project!

**Comment by RKdev** [comment]
@jrhizor Just an update

In the data folder for the `airbyte_workspace` volume I can run `ls -A | wc -l` this returns 502. So currently we have 502 folders numbered `602` - `1092`. Is this within the expected limits if log rotation is happening normally?

**Comment by RKdev** [comment]
Used space has climbed to 24G in the last 5 days

```Filesystem      Size  Used Avail Use% Mounted on
udev            2.1G     0  2.1G   0% /dev
tmpfs           414M   43M  372M  11% /run
/dev/sda1       106G   24G   79G  23% /
tmpfs           2.1G     0  2.1G   0% /dev/shm
tmpfs           5.3M     0  5.3M   0% /run/lock
tmpfs           2.1G     0  2.1G   0% /sys/fs/cgroup
/dev/sda15      130M  6.0M  124M   5% /boot/efi
overlay         106G   24G   79G  23% /var/lib/docker/overlay2/3d11c127aa9bc9601710519bdab5facea7b1edcba4256f7b0f614d72829b741e/merged
overlay         106G   24G   79G  23% /var/lib/docker/overlay2/dce099b6de975b9d44539ad915a0a35c3c7d7eaca9ae3d7887d63da83e6dc611/merged
overlay         106G   24G   79G  23% /var/lib/docker/overlay2/37dfe451d185e6038dddd9b623fc5bcc74d27792a082fd3cfb05c87bf9a264b6/merged
overlay         106G   24G   79G  23% /var/lib/docker/overlay2/84c77f4ab7b5a94f689f489dc01e723fc74df5925c0369479d25ece3d579ed24/merged
overlay         106G   24G   79G  23% /var/lib/docker/overlay2/870eb515fcaaedaad8cf85ea93a5217745fd7fe06c6d9be38b1e0ea30b472d2d/merged
overlay         106G   24G   79G  23% /var/lib/docker/overlay2/0eb435ab6882b601ea944d3c377c8c376edd1f6ce1b8c90562d5dd6df1a4e95d/merged
shm              68M     0   68M   0% /var/lib/docker/containers/ff26f1e4a705de3bc111e581c9663c100df589d69a59fcc1bb878763715f1ea5/mounts/shm
shm              68M     0   68M   0% /var/lib/docker/containers/aa949c91fc748a9b56c186a447f3977f4f1cc7703cf703a7cc25ba84697287ee/mounts/shm
shm              68M     0   68M   0% /var/lib/docker/containers/e5dd16fff044e6da16a0b6757f1ce316a8d5ab5bcd0f72df69a871a755fbb3be/mounts/shm
shm              68M     0   68M   0% /var/lib/docker/containers/183e5d1e02e6c8f2108b373c0c58cb11df883f1bce74a278f55e8d88f6b625e8/mounts/shm
shm              68M     0   68M   0% /var/lib/docker/containers/43be3d7bd258991aa4f614acd5c7087cd64d3db23f317f82faaed77b6d57e8f2/mounts/shm
shm              68M   17k   68M   1% /var/lib/docker/containers/797e3d6ccb54fbf93ae1435733138b75fab2a1e1633424e8f6aa00fc5ed72673/mounts/shm
tmpfs           414M     0  414M   0% /run/user/1000```

**Comment by RKdev** [comment]
Update - folder count is still climbing. `ls -A | wc -l` currently returns 758 numbered 602 - 1348

**Comment by RKdev** [comment]
```df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            2.0G     0  2.0G   0% /dev
tmpfs           395M  5.8M  389M   2% /run
/dev/sda1        99G   23G   72G  25% /
tmpfs           2.0G     0  2.0G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/sda15      124M  5.7M  119M   5% /boot/efi
overlay          99G   23G   72G  25% /var/lib/docker/overlay2/37dfe451d185e6038dddd9b623fc5bcc74d27792a082fd3cfb05c87bf9a264b6/merged
overlay          99G   23G   72G  25% /var/lib/docker/overlay2/870eb515fcaaedaad8cf85ea93a5217745fd7fe06c6d9be38b1e0ea30b472d2d/merged
overlay          99G   23G   72G  25% /var/lib/docker/overlay2/dce099b6de975b9d44539ad915a0a35c3c7d7eaca9ae3d7887d63da83e6dc611/merged
overlay          99G   23G   72G  25% /var/lib/docker/overlay2/3d11c127aa9bc9601710519bdab5facea7b1edcba4256f7b0f614d72829b741e/merged
overlay          99G   23G   72G  25% /var/lib/docker/overlay2/0eb435ab6882b601ea944d3c377c8c376edd1f6ce1b8c90562d5dd6df1a4e95d/merged
overlay          99G   23G   72G  25% /var/lib/docker/overlay2/84c77f4ab7b5a94f689f489dc01e723fc74df5925c0369479d25ece3d579ed24/merged
shm              64M     0   64M   0% /var/lib/docker/containers/183e5d1e02e6c8f2108b373c0c58cb11df883f1bce74a278f55e8d88f6b625e8/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/aa949c91fc748a9b56c186a447f3977f4f1cc7703cf703a7cc25ba84697287ee/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/e5dd16fff044e6da16a0b6757f1ce316a8d5ab5bcd0f72df69a871a755fbb3be/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/ff26f1e4a705de3bc111e581c9663c100df589d69a59fcc1bb878763715f1ea5/mounts/shm
shm              64M   16K   64M   1% /var/lib/docker/containers/797e3d6ccb54fbf93ae1435733138b75fab2a1e1633424e8f6aa00fc5ed72673/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/43be3d7bd258991aa4f614acd5c7087cd64d3db23f317f82faaed77b6d57e8f2/mounts/shm
tmpfs           395M     0  395M   0% /run/user/1000
overlay          99G   23G   72G  25% /var/lib/docker/overlay2/2dcf0d3430b9f6b18e1fcb251eb69ef581f6e3d9755217664fef6da2b11f3a19/merged
overlay          99G   23G   72G  25% /var/lib/docker/overlay2/446f4d0ad46c004edc189880e8370e5e72c445a49196a4581c469f5ee88b8f81/merged
overlay          99G   23G   72G  25% /var/lib/docker/overlay2/ea32d48d28d4c88b9250ac728dc74d9366ceb5e3a52e49282556d14d0cec6f36/merged
overlay          99G   23G   72G  25% /var/lib/docker/overlay2/4395e36a8fd9fe09e4974e33564d89262703f289e01d98c087fb84b5eb5ba832/merged
overlay          99G   23G   72G  25% /var/lib/docker/overlay2/7cb7eee1f3a2ddaa0b005180a051653d48b4fe75623973e0cb567d604618f357/merged
overlay          99G   23G   72G  25% /var/lib/docker/overlay2/978685f7b84940bd0890057b81261853eaa80eb1611e86cad288d5776a19b7b8/merged```

**Comment by jrhizor** [comment]
Do you see "Deleting old file" or "Deleting: " in your logs? We have a cleaner that should remove old log files. I'm curious if that isn't showing up at all or if it's running but just deleting a subset of files.

**Comment by RKdev** [comment]
I downloaded the recent "Server Logs" from the webapp console.

Neither "Deleting old file" or "Deleting: " are present in the log.

There are a number of these though:

```2021-10-26 22:23:45 ERROR () HealthCheckHandler(health):49 - database health check failed.
2021-10-26 22:52:24 INFO () RequestLogger(filter):109 - REQ 172.18.0.2 GET 200 /api/v1/health
2021-10-26 23:36:22 WARN () HttpChannel(handleException):596 - handleException /api/v1/health java.io.IOException: Unable to delete file: /tmp/airbyte_staged_resources
2021-10-26 22:28:49 INFO () RequestLogger(filter):109 - REQ 172.18.0.2 GET 200 /api/v1/health
2021-10-26 22:28:49 INFO () RequestLogger(filter):109 - REQ 172.18.0.2 GET 200 /api/v1/health
2021-10-27 03:03:12 INFO () RequestLogger(filter):109 - REQ 172.18.0.2 GET 200 /api/v1/health
2021-10-27 03:03:12 WARN () HttpChannelState(onError):768 - unhandled due to prior sendError
javax.servlet.ServletException: A MultiException has 1 exceptions.  They are:
1. java.lang.RuntimeException: Failed to create staging resource folder

	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:410) ~[jersey-container-servlet-core-2.31.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) ~[jersey-container-servlet-core-2.31.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366) ~[jersey-container-servlet-core-2.31.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319) ~[jersey-container-servlet-core-2.31.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) ~[jersey-container-servlet-core-2.31.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:569) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1377) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:507) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.Server.handle(Server.java:501) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at java.lang.Thread.run(Thread.java:832) [?:?]```

and 

```
2021-10-27 08:02:18 WARN () HttpChannel(handleException):596 - handleException /api/v1/health java.io.IOException: Unable to delete file: /tmp/airbyte_staged_resources
2021-10-27 08:02:18 INFO () RequestLogger(filter):109 - REQ 172.18.0.2 GET 200 /api/v1/health

```

**Comment by RKdev** [comment]
@jrhizor What I haven't tried is upgrading to a more recent version of Airbyte in a while. We tend to follow the "if it ain't broke don't fix it" policy. I'll do an upgrade this week and let you know if things improve

**Comment by RKdev** [comment]
@davinchia Sorry for the delayed response. We got major funding and have been going through some major transitions. I ended up resetting all of our connectors for an unrelated reason and this problem seemed to go away. It's still a mystery what happened but everything has been working fine for a while now. Thank you!
