### ISSUE TITLE
SSH Tunnel: allow using OPENSSH key format

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#7198]
## Enviroment
- **Airbyte version**:  Cloud
- **Source Connector and version**: postgres
- **Severity**: Very Low / Low / **Medium** / High / Critical
- **Step where error happened**: Create a Source

## Current Behavior
Airbyte uses BouncyCastle to validate the SSH key. Some users want to use the OPENSSH format and its not supported.

## Expected Behavior
I want to use OPENSSH keys when trying to connect using SSH tunnels.

## Logs
```
2021-10-19 21:56:09 INFO  2021-10-19 21:56:09 [32mINFO[m i.a.i.b.s.SshTunnel(getInstance):170 - {} - Starting connection with method: SSH_KEY_AUTH
2021-10-19 21:56:17 ERROR Exception in thread "main" java.lang.RuntimeException: java.io.IOException: unrecognised object: OPENSSH PRIVATE KEY
2021-10-19 21:56:17 ERROR 	at io.airbyte.integrations.base.ssh.SshTunnel.openTunnel(SshTunnel.java:286)
2021-10-19 21:56:17 ERROR 	at io.airbyte.integrations.base.ssh.SshTunnel.<init>(SshTunnel.java:134)
2021-10-19 21:56:17 ERROR 	at io.airbyte.integrations.base.ssh.SshTunnel.getInstance(SshTunnel.java:185)
2021-10-19 21:56:17 ERROR 	at io.airbyte.integrations.base.ssh.SshTunnel.sshWrap(SshTunnel.java:204)
2021-10-19 21:56:17 ERROR 	at io.airbyte.integrations.base.ssh.SshWrappedSource.check(SshWrappedSource.java:37)
2021-10-19 21:56:17 ERROR 	at io.airbyte.integrations.base.spec_modification.SpecModifyingSource.check(SpecModifyingSource.java:38)
2021-10-19 21:56:17 ERROR 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:102)
2021-10-19 21:56:17 ERROR 	at io.airbyte.integrations.source.postgres.PostgresSourceStrictEncrypt.main(PostgresSourceStrictEncrypt.java:34)
2021-10-19 21:56:17 ERROR Caused by: java.io.IOException: unrecognised object: OPENSSH PRIVATE KEY
2021-10-19 21:56:17 ERROR 	at org.bouncycastle.openssl.PEMParser.readObject(Unknown Source)
2021-10-19 21:56:17 ERROR 	at io.airbyte.integrations.base.ssh.SshTunnel.getPrivateKeyPair(SshTunnel.java:234)
2021-10-19 21:56:17 ERROR 	at io.airbyte.integrations.base.ssh.SshTunnel.openTunnel(SshTunnel.java:267)
2021-10-19 21:56:17 ERROR 	... 7 more
```
## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by sherifnada** [comment]
@marcosmarxm Is there a practical blocker to using the PEM format?

**Comment by edgan** [comment]
Just ran into this with a key generated by openssh 8.8p1's ssh-keygen. It would be nice if this was fixed.

**Comment by danieldiamond** [comment]
yeah surprising this still has not been resolved. Would probably opt to remove rather than users having access to broken feature.

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-08-02 at 14:27:*

<blockquote><div class="zd-comment" dir="auto">Any updates on <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/pull/14876">https://github.com/airbytehq/airbyte/pull/14876</a> I'll return to you. You can use RSA keys and it will work but not with OPENSSH keys<br></div></blockquote>
