### ISSUE TITLE
LinkedIn Ads Source hangs after preparing tmp Tables

### ISSUE THREAD

**Issue by tinomerl** [airbytehq/airbyte#7206]
## Enviroment
- **Airbyte version**:  0.30.20-alpha
- **OS Version / Instance**: Ubuntu 20.04
- **Deployment**: Docker
- **Source Connector and version**: LinkedIn Ads 0.1.1
- **Destination Connector and version**: Postgres 0.3.11
- **Severity**: High
- **Step where error happened**: Sync job

## Current Behavior
When replicating data from LinkedIn Ads to Postgres the tmp tables will be prepared but afterwards nothing happens. The Sync Job hangs and won't call any data. After some time a retryable Error is caught.

## Expected Behavior
Data from LinkedIn should be replicated.

I tested different sources to exclude it's because of the deployment. I also tested with LinkedIn as a source and other destinations. No change in behaviour. Also tested in two different environments.

## Logs

<details>
<summary>LinkedIn Ads to Postgres</summary> 

```
2021-10-20 07:28:39 INFO () WorkerRun(call):47 - Executing worker wrapper. Airbyte version: 0.30.20-alpha
2021-10-20 07:28:41 INFO () TemporalAttemptExecution(get):94 - Executing worker wrapper. Airbyte version: 0.30.20-alpha
2021-10-20 07:28:41 WARN () Databases(createPostgresDatabaseWithRetry):38 - Waiting for database to become available...
2021-10-20 07:28:41 INFO () JobsDatabaseInstance(lambda$static$2):25 - Testing if jobs database is ready...
2021-10-20 07:28:41 INFO () Databases(createPostgresDatabaseWithRetry):55 - Database available!
2021-10-20 07:28:41 INFO () DefaultReplicationWorker(run):82 - start sync worker. job id: 35 attempt id: 1
2021-10-20 07:28:41 INFO () DefaultReplicationWorker(run):91 - configured sync modes: {null.ad_creative_analytics=full_refresh - append, null.ad_campaign_analytics=full_refresh - append}
2021-10-20 07:28:41 INFO () DefaultAirbyteDestination(start):58 - Running destination...
2021-10-20 07:28:42 INFO () LineGobbler(voidCall):65 - Checking if airbyte/destination-postgres:0.3.11 exists...
2021-10-20 07:28:42 INFO () LineGobbler(voidCall):65 - airbyte/destination-postgres:0.3.11 was found locally.
2021-10-20 07:28:42 INFO () DockerProcessFactory(create):127 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/35/1 --network host --log-driver none airbyte/destination-postgres:0.3.11 write --config destination_config.json --catalog destination_catalog.json
2021-10-20 07:28:42 INFO () LineGobbler(voidCall):65 - Checking if airbyte/source-linkedin-ads:0.1.1 exists...
2021-10-20 07:28:42 INFO () LineGobbler(voidCall):65 - airbyte/source-linkedin-ads:0.1.1 was found locally.
2021-10-20 07:28:42 INFO () DockerProcessFactory(create):127 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/35/1 --network host --log-driver none airbyte/source-linkedin-ads:0.1.1 read --config source_config.json --catalog source_catalog.json
2021-10-20 07:28:42 INFO () DefaultReplicationWorker(lambda$getDestinationOutputRunnable$3):226 - Destination output thread started.
2021-10-20 07:28:42 INFO () DefaultReplicationWorker(run):119 - Waiting for source thread to join.
2021-10-20 07:28:42 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):190 - Replication thread started.
2021-10-20 07:29:11 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:11 [32mINFO[m i.a.i.d.p.PostgresDestination(main):85 - {} - starting destination: class io.airbyte.integrations.destination.postgres.PostgresDestination
2021-10-20 07:29:12 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:12 [32mINFO[m i.a.i.b.IntegrationRunner(run):96 - {} - Running integration: io.airbyte.integrations.base.ssh.SshWrappedDestination
2021-10-20 07:29:13 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:12 [32mINFO[m i.a.i.b.IntegrationCliParser(parseOptions):135 - {} - integration args: {catalog=destination_catalog.json, write=null, config=destination_config.json}
2021-10-20 07:29:13 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:12 [32mINFO[m i.a.i.b.IntegrationRunner(run):100 - {} - Command: WRITE
2021-10-20 07:29:13 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:13 [32mINFO[m i.a.i.b.IntegrationRunner(run):101 - {} - Integration config: IntegrationConfig{command=WRITE, configPath='destination_config.json', catalogPath='destination_catalog.json', statePath='null'}
2021-10-20 07:29:13 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:13 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2021-10-20 07:29:13 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:13 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword examples - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2021-10-20 07:29:13 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:13 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2021-10-20 07:29:13 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:13 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword multiline - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2021-10-20 07:29:15 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:15 [32mINFO[m i.a.i.b.s.SshTunnel(getInstance):190 - {} - Starting connection with method: NO_TUNNEL
2021-10-20 07:29:15 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:15 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=item_de-linkedin-ad_campaign_analytics, namespace=null, outputSchemaName=staging, tmpTableName=_airbyte_tmp_ojl_item_de_linkedin_ad_campaign_analytics, outputTableName=_airbyte_raw_item_de_linkedin_ad_campaign_analytics, syncMode=append}
2021-10-20 07:29:15 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:15 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=item_de-linkedin-ad_creative_analytics, namespace=null, outputSchemaName=staging, tmpTableName=_airbyte_tmp_rcg_item_de_linkedin_ad_creative_analytics, outputTableName=_airbyte_raw_item_de_linkedin_ad_creative_analytics, syncMode=append}
2021-10-20 07:29:16 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:16 [32mINFO[m i.a.i.d.b.BufferedStreamConsumer(startTracked):143 - {} - class io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer started.
2021-10-20 07:29:16 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:16 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):139 - {} - Preparing tmp tables in destination started for 2 streams
2021-10-20 07:29:16 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:16 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream item_de-linkedin-ad_campaign_analytics. schema: staging, tmp table name: _airbyte_tmp_ojl_item_de_linkedin_ad_campaign_analytics
2021-10-20 07:29:17 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:17 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream item_de-linkedin-ad_creative_analytics. schema: staging, tmp table name: _airbyte_tmp_rcg_item_de_linkedin_ad_creative_analytics
2021-10-20 07:29:17 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:17 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):149 - {} - Preparing tables in destination completed.
2021-10-20 07:41:00 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Starting syncing SourceLinkedinAds
2021-10-20 07:41:00 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Syncing stream: ad_campaign_analytics 
2021-10-20 07:41:00 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2021-10-20 07:41:00 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2021-10-20 07:41:00 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2021-10-20 07:41:00 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2021-10-20 07:41:00 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2021-10-20 07:41:00 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2021-10-20 07:41:00 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2021-10-20 07:41:00 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2021-10-20 07:41:00 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2021-10-20 07:41:00 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2021-10-20 07:41:00 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2021-10-20 07:41:00 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2021-10-20 07:41:00 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2021-10-20 07:41:00 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2021-10-20 07:41:45 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
```

</details>

## Steps to Reproduce
1. Setup LinkedIn Ads Source
2. Setup Postgres Destination
3. Try to replicate data.

## Acceptance Criteria
1. Find root cause and publish a fix
2. Fix the log message `Caught retryable error ''` which doesn't tell us what the actual error was

## Are you willing to submit a PR?
Yes

**Comment by sherifnada** [comment]
@tinomerl apologies for the late response here! will look into this and understand the root cause soon. Are you open to sharing the full job logs with us by downloading it from the UI?

**Comment by tinomerl** [comment]
@sherifnada thanks for the reply! i added some logs specific for this source and destination in the issue when i opened it under `LinkedIn Ads to Postgres`. do you need more than that? if so i can export the whole scheduler log or are the server logs better?

**Comment by sherifnada** [comment]
@tinomerl would you be able to share the full logs? specifically i'm unable to tell how this job terminated -- was it cancelled manually or failed on its own?

**Comment by tinomerl** [comment]
@sherifnada i cancelled the job manually after the message `Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...`

Before that it ran for almost 20 Minutes without syncing any data. i attached the whole log. Is this sufficient?

<details>

<summary>Full Logs</summary>

```
2021-10-20 07:28:39 INFO () WorkerRun(call):47 - Executing worker wrapper. Airbyte version: 0.30.20-alpha
2021-10-20 07:28:41 INFO () TemporalAttemptExecution(get):94 - Executing worker wrapper. Airbyte version: 0.30.20-alpha
2021-10-20 07:28:41 WARN () Databases(createPostgresDatabaseWithRetry):38 - Waiting for database to become available...
2021-10-20 07:28:41 INFO () JobsDatabaseInstance(lambda$static$2):25 - Testing if jobs database is ready...
2021-10-20 07:28:41 INFO () Databases(createPostgresDatabaseWithRetry):55 - Database available!
2021-10-20 07:28:41 INFO () DefaultReplicationWorker(run):82 - start sync worker. job id: 35 attempt id: 1
2021-10-20 07:28:41 INFO () DefaultReplicationWorker(run):91 - configured sync modes: {null.ad_creative_analytics=full_refresh - append, null.ad_campaign_analytics=full_refresh - append}
2021-10-20 07:28:41 INFO () DefaultAirbyteDestination(start):58 - Running destination...
2021-10-20 07:28:42 INFO () LineGobbler(voidCall):65 - Checking if airbyte/destination-postgres:0.3.11 exists...
2021-10-20 07:28:42 INFO () LineGobbler(voidCall):65 - airbyte/destination-postgres:0.3.11 was found locally.
2021-10-20 07:28:42 INFO () DockerProcessFactory(create):127 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/35/1 --network host --log-driver none airbyte/destination-postgres:0.3.11 write --config destination_config.json --catalog destination_catalog.json
2021-10-20 07:28:42 INFO () LineGobbler(voidCall):65 - Checking if airbyte/source-linkedin-ads:0.1.1 exists...
2021-10-20 07:28:42 INFO () LineGobbler(voidCall):65 - airbyte/source-linkedin-ads:0.1.1 was found locally.
2021-10-20 07:28:42 INFO () DockerProcessFactory(create):127 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/35/1 --network host --log-driver none airbyte/source-linkedin-ads:0.1.1 read --config source_config.json --catalog source_catalog.json
2021-10-20 07:28:42 INFO () DefaultReplicationWorker(lambda$getDestinationOutputRunnable$3):226 - Destination output thread started.
2021-10-20 07:28:42 INFO () DefaultReplicationWorker(run):119 - Waiting for source thread to join.
2021-10-20 07:28:42 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):190 - Replication thread started.
2021-10-20 07:29:11 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:11 [32mINFO[m i.a.i.d.p.PostgresDestination(main):85 - {} - starting destination: class io.airbyte.integrations.destination.postgres.PostgresDestination
2021-10-20 07:29:12 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:12 [32mINFO[m i.a.i.b.IntegrationRunner(run):96 - {} - Running integration: io.airbyte.integrations.base.ssh.SshWrappedDestination
2021-10-20 07:29:13 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:12 [32mINFO[m i.a.i.b.IntegrationCliParser(parseOptions):135 - {} - integration args: {catalog=destination_catalog.json, write=null, config=destination_config.json}
2021-10-20 07:29:13 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:12 [32mINFO[m i.a.i.b.IntegrationRunner(run):100 - {} - Command: WRITE
2021-10-20 07:29:13 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:13 [32mINFO[m i.a.i.b.IntegrationRunner(run):101 - {} - Integration config: IntegrationConfig{command=WRITE, configPath='destination_config.json', catalogPath='destination_catalog.json', statePath='null'}
2021-10-20 07:29:13 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:13 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2021-10-20 07:29:13 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:13 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword examples - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2021-10-20 07:29:13 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:13 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2021-10-20 07:29:13 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:13 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword multiline - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2021-10-20 07:29:15 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:15 [32mINFO[m i.a.i.b.s.SshTunnel(getInstance):190 - {} - Starting connection with method: NO_TUNNEL
2021-10-20 07:29:15 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:15 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=item_de-linkedin-ad_campaign_analytics, namespace=null, outputSchemaName=staging, tmpTableName=_airbyte_tmp_ojl_item_de_linkedin_ad_campaign_analytics, outputTableName=_airbyte_raw_item_de_linkedin_ad_campaign_analytics, syncMode=append}
2021-10-20 07:29:15 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:15 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=item_de-linkedin-ad_creative_analytics, namespace=null, outputSchemaName=staging, tmpTableName=_airbyte_tmp_rcg_item_de_linkedin_ad_creative_analytics, outputTableName=_airbyte_raw_item_de_linkedin_ad_creative_analytics, syncMode=append}
2021-10-20 07:29:16 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:16 [32mINFO[m i.a.i.d.b.BufferedStreamConsumer(startTracked):143 - {} - class io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer started.
2021-10-20 07:29:16 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:16 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):139 - {} - Preparing tmp tables in destination started for 2 streams
2021-10-20 07:29:16 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:16 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream item_de-linkedin-ad_campaign_analytics. schema: staging, tmp table name: _airbyte_tmp_ojl_item_de_linkedin_ad_campaign_analytics
2021-10-20 07:29:17 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:17 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream item_de-linkedin-ad_creative_analytics. schema: staging, tmp table name: _airbyte_tmp_rcg_item_de_linkedin_ad_creative_analytics
2021-10-20 07:29:17 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-20 07:29:17 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):149 - {} - Preparing tables in destination completed.
2021-10-20 07:41:00 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Starting syncing SourceLinkedinAds
2021-10-20 07:41:00 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Syncing stream: ad_campaign_analytics 
2021-10-20 07:41:00 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2021-10-20 07:41:00 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2021-10-20 07:41:00 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2021-10-20 07:41:00 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2021-10-20 07:41:00 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2021-10-20 07:41:00 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2021-10-20 07:41:00 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2021-10-20 07:41:00 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2021-10-20 07:41:00 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2021-10-20 07:41:00 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2021-10-20 07:41:00 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2021-10-20 07:41:00 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2021-10-20 07:41:00 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2021-10-20 07:41:00 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2021-10-20 07:41:45 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2021-10-20 07:42:40 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2021-10-20 07:43:45 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Caught retryable error '' after 1 tries. Waiting 5 seconds then retrying...
2021-10-20 07:47:21 INFO () TemporalAttemptExecution(lambda$getCancellationChecker$2):179 - Running sync worker cancellation...
2021-10-20 07:47:21 INFO () DefaultReplicationWorker(cancel):250 - Cancelling replication worker...
2021-10-20 07:47:31 INFO () DefaultReplicationWorker(cancel):258 - Cancelling destination...
2021-10-20 07:47:31 INFO () DefaultAirbyteDestination(cancel):114 - Attempting to cancel destination process...
2021-10-20 07:47:31 INFO () DefaultAirbyteDestination(cancel):119 - Destination process exists, cancelling...
2021-10-20 07:47:40 INFO () DefaultAirbyteDestination(cancel):121 - Cancelled destination process!
2021-10-20 07:47:40 INFO () DefaultReplicationWorker(cancel):265 - Cancelling source...
2021-10-20 07:47:40 INFO () DefaultAirbyteSource(cancel):121 - Attempting to cancel source process...
2021-10-20 07:47:40 INFO () DefaultAirbyteSource(cancel):126 - Source process exists, cancelling...
2021-10-20 07:47:48 INFO () DefaultReplicationWorker(run):121 - Source thread complete.
2021-10-20 07:47:48 INFO () DefaultReplicationWorker(run):122 - Waiting for destination thread to join.
2021-10-20 07:47:48 INFO () DefaultReplicationWorker(run):124 - Destination thread complete.
2021-10-20 07:47:49 INFO () DefaultAirbyteSource(cancel):128 - Cancelled source process!
2021-10-20 07:47:49 INFO () TemporalAttemptExecution(lambda$getCancellationChecker$2):183 - Interrupting worker thread...
2021-10-20 07:47:49 INFO () TemporalAttemptExecution(lambda$getCancellationChecker$2):186 - Cancelling completable future...
2021-10-20 07:47:49 WARN () CancellationHandler$TemporalCancellationHandler(checkAndHandleCancellation):51 - Job either timeout-ed or was cancelled.
2021-10-20 07:47:49 INFO () TemporalAttemptExecution(get):115 - Stopping cancellation check scheduling...
2021-10-20 07:47:49 WARN () POJOActivityTaskHandler$POJOActivityImplementation(execute):243 - Activity failure. ActivityId=277b1525-ae1e-398d-8e78-e84a45b0a916, activityType=Replicate, attempt=1
java.util.concurrent.CancellationException: null
	at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2468) ~[?:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getCancellationChecker$2(TemporalAttemptExecution.java:189) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
	at io.airbyte.workers.temporal.CancellationHandler$TemporalCancellationHandler.checkAndHandleCancellation(CancellationHandler.java:50) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getCancellationChecker$3(TemporalAttemptExecution.java:192) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
2021-10-20 07:47:49 ERROR () DefaultReplicationWorker(run):128 - Sync worker failed.
io.airbyte.workers.WorkerException: Source process exit with code 143. This warning is normal if the job was cancelled.
	at io.airbyte.workers.protocols.airbyte.DefaultAirbyteSource.close(DefaultAirbyteSource.java:115) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:126) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:32) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$1(TemporalAttemptExecution.java:145) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
	Suppressed: java.io.IOException: Stream closed
		at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:442) ~[?:?]
		at java.io.OutputStream.write(OutputStream.java:162) ~[?:?]
		at java.io.BufferedOutputStream.write(BufferedOutputStream.java:123) ~[?:?]
		at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:242) ~[?:?]
		at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:321) ~[?:?]
		at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:325) ~[?:?]
		at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:159) ~[?:?]
		at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:251) ~[?:?]
		at java.io.BufferedWriter.flush(BufferedWriter.java:257) ~[?:?]
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.notifyEndOfStream(DefaultAirbyteDestination.java:87) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.close(DefaultAirbyteDestination.java:100) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
		at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:101) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
		at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:32) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$1(TemporalAttemptExecution.java:145) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:832) [?:?]
2021-10-20 07:47:49 INFO () DefaultReplicationWorker(run):152 - sync summary: io.airbyte.config.ReplicationAttemptSummary@1904db9e[status=cancelled,recordsSynced=340,bytesSynced=428636,startTime=1634714921908,endTime=1634716069189]
2021-10-20 07:47:49 INFO () DefaultReplicationWorker(run):161 - Source did not output any state messages
2021-10-20 07:47:49 WARN () DefaultReplicationWorker(run):172 - State capture: No state retained.
2021-10-20 07:47:50 WARN () CancellationHandler$TemporalCancellationHandler(checkAndHandleCancellation):51 - Job either timeout-ed or was cancelled.
```
</details>

**Comment by sherifnada** [comment]
thanks, this is helpful!

**Comment by annalvova05** [comment]
@tinomerl @sherifnada this error was caused due to rate limits. Each account has quota limits for requests. Rate limits specify the maximum number of API calls that can be made in a 24 hour period. These limits reset at midnight UTC every day. You can find more information [here](https://docs.airbyte.io/integrations/sources/linkedin-ads). Also quotas and usage are [here](https://www.linkedin.com/developers/apps).

Also, just published a new connector version with a more informative log message, when sync is stopped.

**Comment by tinomerl** [comment]
Hey @annalvova05 thanks for your comment. But the issue seems to be a different one. I upgraded to your connector version last week and tested it. It took about 2 Hours to replicate the data to postgres. This is the only source connector we have problems with. I also checked our quotas after you mentioned it. We don't run into any restrictions here either.

@sherifnada i attached the logs to the original comment and updated the connector version. Could the issue please be reopened?
