### ISSUE TITLE
[HELM Chart] Forbidden!Configured service account doesn't have access

### ISSUE THREAD

**Issue by quorak** [airbytehq/airbyte#7211]
## Enviroment
helm: v3
kubernetes: 1.20
chart: latest

_*Edit:*_ I just tried it with a kubernetes 1.19 cluster and this worked out of the box!

## Current Behavior
When making a clean install, with the current helm chart, everything works as expected, all pods are created.
I can even open the web interface. But it is not possible to add connectors. When looking at the logs of the worker or sweeper pod, I see the below error logs.

## Expected Behavior
RBAC would setup service account correctly and i can add connectors

## Logs
```
Caused by: io.temporal.failure.ApplicationFailure: message='Failure executing: POST at: https://10.3.0.1/api/v1/namespaces/airbyte/pods. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods is forbidden: User "system:serviceaccount:airbyte:airbyte-admin" cannot create resource "pods" in API group "" in the namespace "airbyte": RBAC: role.rbac.authorization.k8s.io "airbyte-admin-role" not found.', type='io.fabric8.kubernetes.client.KubernetesClientException', nonRetryable=false
```

## Steps to Reproduce
1. git clone https://github.com/airbytehq/airbyte.git
2. cd charts/airbyte
3. ./ci.sh install

## Are you willing to submit a PR?
sure. but dont know the problem

**Comment by superpan** [comment]
Using v1.9.16 didn't work .. any workarounds?

**Comment by cgardens** [comment]
closing due to inactivity and old version

**Comment by tfoldi** [comment]
We have the same issue as @jfouchard - I can confirm it is still exists in Helm v0.41. A worker pod restart helps

**Comment by ShaneGCareCru** [comment]
I have seen this issue as well.
EKS

**Comment by raulsh** [comment]
Is still an issue in EKS 1.21

**Comment by snahelou** [comment]
Still an issue in GKE 1.24

**Comment by olivermeyer** [comment]
@cgardens can you reopen this issue? We're also seeing it in our open source deployment running Airbyte `0.40.32`, and with various sources.

From the logs:
```
2023-02-13 10:56:12 ERROR i.a.w.g.DefaultCheckConnectionWorker(run):124 - Unexpected error while checking connection: 
io.airbyte.workers.exception.WorkerException: Failure executing: POST at: https://172.20.0.1/api/v1/namespaces/airbyte-prod/pods. Message: Unauthorized! Configured service account doesn't have access. Service account may have been revoked. Unauthorized.
	at io.airbyte.workers.process.KubeProcessFactory.create(KubeProcessFactory.java:143) ~[io.airbyte-airbyte-commons-worker-0.40.32.jar:?]
	at io.airbyte.workers.process.AirbyteIntegrationLauncher.check(AirbyteIntegrationLauncher.java:100) ~[io.airbyte-airbyte-commons-worker-0.40.32.jar:?]
	at io.airbyte.workers.general.DefaultCheckConnectionWorker.run(DefaultCheckConnectionWorker.java:71) ~[io.airbyte-airbyte-commons-worker-0.40.32.jar:?]
	at io.airbyte.workers.general.DefaultCheckConnectionWorker.run(DefaultCheckConnectionWorker.java:41) ~[io.airbyte-airbyte-commons-worker-0.40.32.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$5(TemporalAttemptExecution.java:195) ~[io.airbyte-airbyte-workers-0.40.32.jar:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://172.20.0.1/api/v1/namespaces/airbyte-prod/pods. Message: Unauthorized! Configured service account doesn't have access. Service account may have been revoked. Unauthorized.
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:682) ~[kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:661) ~[kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:610) ~[kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:555) ~[kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:518) ~[kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:305) ~[kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:644) ~[kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:83) ~[kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.CreateOnlyResourceOperation.create(CreateOnlyResourceOperation.java:61) ~[kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.utils.CreateOrReplaceHelper.createOrReplace(CreateOrReplaceHelper.java:48) ~[kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:318) ~[kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:83) ~[kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:308) ~[kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:83) ~[kubernetes-client-5.12.2.jar:?]
	at io.airbyte.workers.process.KubePodProcess.<init>(KubePodProcess.java:536) ~[io.airbyte-airbyte-commons-worker-0.40.32.jar:?]
	at io.airbyte.workers.process.KubeProcessFactory.create(KubeProcessFactory.java:139) ~[io.airbyte-airbyte-commons-worker-0.40.32.jar:?]
	... 5 more
```

**Comment by zifeo** [comment]
@olivermeyer Same here, rebooting the server did the job.

**Comment by froblesmartin** [comment]
Similar problem here, after adding the image pull secret configuration with the main `airbyte` Helm chart, the config got added to the ConfigMap, and the worker pod was restarted with the new environment variable. Then it was not working, failing with the same errors mentioned in this issue.

As suggested by @tfoldi (thanks!), a restart of the worker pod made it work.

**Comment by vrfn** [comment]
@cgardens running into this issue on 0.45.17 as well. 

Restarting the worker pods resolves the issue for a period of time (about an hour).

**Comment by zubairov** [comment]
Just saw this problem on 0.50.05, restarted the worker helped so far

**Comment by kevogaba** [comment]
Yet again in version 0.50.34 via Helm charts

**Comment by LouisAuneau** [comment]
Same here in 0.50.34 with Helm Chart 0.49.21.

**Comment by nhatsangvn** [comment]
Helm version: 0.49.23
As I check the RoleBinding here, there is a ServiceAccount name `airbyte-admin`, but if you
```
kubectl get sa -n airbyte
```
there is no such users.
![image](https://github.com/airbytehq/airbyte/assets/20770118/0831ed93-3cc9-4b65-804a-fb13a85020b5)

So the fix is about recreate that users:
```
$ cat /tmp/airbyte.sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: airbyte-admin
  namespace: airbyte

$ kubectl apply -f /tmp/airbyte.sa
```

**Comment by sidharrth2002** [comment]
Facing the same issue on Airbyte version `0.50.33`

**Comment by Kampe** [comment]
Seeing the same behavior in 0.55.0 - any update on this?

**Comment by zspsole** [comment]
btw you can workaround this problem by setting your service account name manually in the chart:
```
        global:
          serviceAccountName: airbyte-admin

        serviceAccount:
          create: true
          name: airbyte-admin
```

**Comment by hongbo-miao** [comment]
I think because I set instanceAdmin firstName and lastName, and Airbyte tries to create an admin using that first name and last but may have a bug, @zspsole solution works for me, thanks! ☺️
