### ISSUE TITLE
Quickbooks token expires after 24 hours 

### ISSUE THREAD

**Issue by JCastillo700** [airbytehq/airbyte#7296]
## Enviroment
OS Version / Instance: EC2 t3.medium
Memory / Disk: 4GB / 8GB
Deployment: Docker
Airbyte Version: 0.29.4-alpha
Source name/version: Quickbooks 0.1.3
Destination name/version: S3 0.1.10
Severity: High
Step: Source / On sync

## Current Behavior
Access token for quickbooks OAuth is not being refreshed

## Expected Behavior
Connection should generate a new token after 24 hours using the refresh token that has an expiration of 101 days

## Logs

[logs-901-2.txt](https://github.com/airbytehq/airbyte/files/7401927/logs-901-2.txt)

<details>
<summary>LOG</summary> 

```

2021-10-22 23:36:06 INFO () DefaultAirbyteStreamFactory(internalLog):110 - https://sandbox-quickbooks.api.intuit.com/v3/company/4620816365201690220/query - Making request to GET endpoint /v3/company/4620816365201690220/query, with params {'query': 'SELECT * FROM CompanyInfo'}
2021-10-22 23:36:06 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Error initializing QuickbooksClient during token refresh, please reauthenticate.
2021-10-22 23:36:06 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - CRITICAL (invalid_grant) 
2021-10-22 23:36:06 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - Traceback (most recent call last):
2021-10-22 23:36:06 ERROR () DefaultAirbyteStreamFactory(internalLog):108 -   File "/usr/local/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py", line 478, in request
2021-10-22 23:36:06 ERROR () DefaultAirbyteStreamFactory(internalLog):108 -     url, http_method=method, body=data, headers=headers
2021-10-22 23:36:06 ERROR () DefaultAirbyteStreamFactory(internalLog):108 -   File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 198, in add_token
2021-10-22 23:36:06 ERROR () DefaultAirbyteStreamFactory(internalLog):108 -     raise TokenExpiredError()

```

</details>

## Steps to Reproduce
1. Create a quickbooks connection 
2. wait 24 hours for the token to expire
3. get `invalid_grant` error

**Comment by JDSanto** [comment]
I've also been having problems with this.

[The refresh token of the Quickbooks API can change after 24 hours](https://help.developer.intuit.com/s/article/Validity-of-Refresh-Token), and since it is not updated in the Airbyte configuration, the following sync will fail with `invalid_grant`.

The singer tap already takes care of this by modifying [the JSON configuration with the new refresh token](https://github.com/singer-io/tap-quickbooks/blob/2aa2d166153103354c8b24a923ab400ea22900a0/tap_quickbooks/client.py#L59-L69), but I think it stays the same in the Airbyte configuration itself.

**Comment by RickRen7575** [comment]
I'm also having this issue. I would love to help with the solution/stay informed.

**Comment by victorolawale** [comment]
I am also having this issue. I would really like to see a solution as soon as possible.

**Comment by jscottpolevault** [comment]
I’m also having this issue. And I don’t see anywhere to input an Access token on source setup, only the refresh token and other creds. But obviously the Refresh token isn’t working like its intended =)
