### ISSUE TITLE
Source Recharge: API return mal-formated JSON need to implement retry

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#7469]
## Enviroment
- **Airbyte version**: 0.30.23-alpha
- **OS Version / Instance**: GCP
- **Deployment**: Docker
- **Source Connector and version**: Recharge 0.1.3
- **Destination Connector and version**: BigQuery 0.5.0
- **Severity**: Very Low / Low / Medium / **High** / Critical
- **Step where error happened**: Deploy / **Sync job** / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
I have 10+ connections using Recharge connector. For the account with fewer data points (10k) the sync runs without any problem, but for two large accounts (500k+) the connection keep failing
![image](https://user-images.githubusercontent.com/5154322/139351036-fbef9e6f-5fcd-4b7b-98c3-49beccec381b.png)

## Expected Behavior
I expected the connector works for any size of account.

## Logs

[logs-956-0.txt](https://github.com/airbytehq/airbyte/files/7437919/logs-956-0.txt)

From logs is not clear why is failing. The error is about a mal-formated JSON reponse from the API. Maybe is a Error or a return we dont expect from their side.
```
2021-11-02 21:31:16 ERROR () LineGobbler(voidCall):65 - Traceback (most recent call last):
2021-11-02 21:31:16 ERROR () LineGobbler(voidCall):65 -   File "/airbyte/integration_code/main.py", line 13, in <module>
2021-11-02 21:31:16 ERROR () LineGobbler(voidCall):65 -     launch(source, sys.argv[1:])
2021-11-02 21:31:16 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 108, in launch
2021-11-02 21:31:16 ERROR () LineGobbler(voidCall):65 -     for message in source_entrypoint.run(parsed_args):
2021-11-02 21:31:16 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 99, in run
2021-11-02 21:31:16 ERROR () LineGobbler(voidCall):65 -     for message in generator:
2021-11-02 21:31:16 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 110, in read
2021-11-02 21:31:16 ERROR () LineGobbler(voidCall):65 -     raise e
2021-11-02 21:31:16 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 106, in read
2021-11-02 21:31:16 ERROR () LineGobbler(voidCall):65 -     internal_config=internal_config,
2021-11-02 21:31:16 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 136, in _read_stream
2021-11-02 21:31:16 ERROR () LineGobbler(voidCall):65 -     for record in record_iterator:
2021-11-02 21:31:16 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 181, in _read_incremental
2021-11-02 21:31:16 ERROR () LineGobbler(voidCall):65 -     for record_counter, record_data in enumerate(records, start=1):
2021-11-02 21:31:16 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 353, in read_records

```

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by marcosmarxm** [comment]
I tried to change:

```python
    def parse_response(self, response: requests.Response, **kwargs) -> Iterable[Mapping]:
        try:
            response_data = response.json()
            stream_data = self.get_stream_data(response_data)
            yield from stream_data
        except Exception:
            yield []
```

and 

```python
    def get_updated_state(self, current_stream_state: MutableMapping[str, Any], latest_record: Mapping[str, Any]) -> Mapping[str, Any]:
        try:
            latest_benchmark = latest_record[self.cursor_field]
        except Exception:
            # In case the response is mal-formated
            latest_benchmark = current_stream_state[self.cursor_field]
        if current_stream_state.get(self.cursor_field):
            return {self.cursor_field: max(latest_benchmark, current_stream_state[self.cursor_field])}
        return {self.cursor_field: latest_benchmark}
```

but this didn't solve the problem, the connection keep failing.
[logs-27-2.txt](https://github.com/airbytehq/airbyte/files/7465240/logs-27-2.txt)

**Comment by rohansingh** [comment]
I've noticed that the Recharge API sometimes returns gzip'd JSON without providing appropriate headers. You can verify by piping to `gzcat`.
