### ISSUE TITLE
Salesforce source: 400 bad request error fails connector

### ISSUE THREAD

**Issue by denis-sokolov** [airbytehq/airbyte#7518]
## Enviroment
- **Airbyte version**: cloud.airbyte.io
- **Source Connector and version**: Salesforce 0.1.2
- **Destination Connector and version**: Redshift 0.3.18
- **Severity**: Medium
- **Step where error happened**: Sync job

## Current Behavior
The job logs end with “Completed successfully”. The sync job reports “Cancelled”.

![image](https://user-images.githubusercontent.com/113721/139666474-bbf86fe8-38f1-4743-8ad2-4515aea292f1.png)

## Expected Behavior
Either the job error/cancellation is detected and the job is fully cancelled or the sync job reports “Succeeded”.

I am unable to say whether the sync completed truly correctly. There is some data in the destination, I have not yet noticed data missing, but my review was not very thorough.

## Logs

<details>
<summary>LOG</summary> 

The logs have four mentions of cancellation, all included here.

```
[..skipped 3000 lines..]
2021-11-01 10:29:45 INFO  2021-11-01 10:29:45 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):192 - {} - Cleaning tmp tables in destination completed.
2021-11-01 10:29:45 INFO  2021-11-01 10:29:45 [32mINFO[m i.a.i.b.IntegrationRunner(run):133 - {} - Completed integration: io.airbyte.integrations.destination.redshift.RedshiftDestination
2021-11-01 10:29:45 INFO  2021-11-01 10:29:45 [32mINFO[m i.a.i.d.r.RedshiftDestination(main):79 - {} - completed destination: class io.airbyte.integrations.destination.redshift.RedshiftDestination
2021-11-01 10:29:45 INFO  Exit code for pod destination-redshift-worker-5466-0-yjxzs is 0
2021-11-01 10:29:45 WARN  airbyte-destination gobbler IOException: Socket closed. Typically happens when cancelling a job.
2021-11-01 10:29:45 INFO  Closed all resources for pod destination-redshift-worker-5466-0-yjxzs
2021-11-01 10:29:45 INFO  Destination thread complete.
2021-11-01 10:29:45 INFO  Closed all resources for pod source-salesforce-worker-5466-0-siwqa
2021-11-01 10:29:45 INFO  Closed all resources for pod source-salesforce-worker-5466-0-siwqa
[..skipped 9 lines..]
2021-11-01 10:29:45 INFO  Closed all resources for pod destination-redshift-worker-5466-0-yjxzs
2021-11-01 10:29:45 INFO  Closed all resources for pod destination-redshift-worker-5466-0-yjxzs
2021-11-01 10:29:45 ERROR Sync worker failed.
io.airbyte.workers.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
	at io.airbyte.workers.protocols.airbyte.DefaultAirbyteSource.close(DefaultAirbyteSource.java:115) ~[io.airbyte-airbyte-workers-0.30.22-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:126) ~[io.airbyte-airbyte-workers-0.30.22-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:32) ~[io.airbyte-airbyte-workers-0.30.22-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$1(TemporalAttemptExecution.java:145) ~[io.airbyte-airbyte-workers-0.30.22-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
2021-11-01 10:29:45 INFO  sync summary: io.airbyte.config.ReplicationAttemptSummary@687fac5[status=failed,recordsSynced=4800,bytesSynced=1265315,startTime=1635761267706,endTime=1635762585796]
2021-11-01 10:29:45 INFO  Source did not output any state messages
2021-11-01 10:29:45 WARN  State capture: No state retained.
2021-11-01 10:29:45 INFO  Stopping cancellation check scheduling...
2021-11-01 10:29:45 INFO  sync summary: io.airbyte.config.StandardSyn
[..skipped 3000 lines..]
2021-11-01 10:59:11 INFO  10:59:11 | Finished running 487 table models in 1576.85s.
2021-11-01 10:59:12 INFO  
2021-11-01 10:59:12 INFO  [32mCompleted successfully[0m
2021-11-01 10:59:12 INFO  
2021-11-01 10:59:12 INFO  Done. PASS=487 WARN=0 ERROR=0 SKIP=0 TOTAL=487
2021-11-01 10:59:15 INFO  Exit code for pod normalization-worker-5466-0-daaam is 0
2021-11-01 10:59:15 INFO  Closed all resources for pod normalization-worker-5466-0-daaam
2021-11-01 10:59:15 INFO  Closed all resources for pod normalization-worker-5466-0-daaam
2021-11-01 10:59:15 INFO  Closed all resources for pod normalization-worker-5466-0-daaam
2021-11-01 10:59:15 INFO  Closed all resources for pod normalization-worker-5466-0-daaam
2021-11-01 10:59:15 INFO  Closed all resources for pod normalization-worker-5466-0-daaam
2021-11-01 10:59:15 INFO  Closed all resources for pod normalization-worker-5466-0-daaam
2021-11-01 10:59:15 INFO  Normalization executed in 29 minutes 28 seconds.
2021-11-01 10:59:15 INFO  Stopping cancellation check scheduling...
```

</details>

## Steps to Reproduce
1. Open [the connection on cloud.airbyte.io](https://cloud.airbyte.io/connections/9c6cc9c6-5c01-445e-9b2b-065d3d32cb33)
2. Press Sync now
3. Wait for an hour

## Are you willing to submit a PR?
Sorry, no.

**Comment by harshithmullapudi** [comment]
Thanks for creating issue this helps us to track them. Team will look into it soon.

**Comment by sherifnada** [comment]
@denis-sokolov AFAICT the "success" in the log is referring specifically to normalization succeeding. This is expected as normalization can partially succeed (e.g: in the case that only a subset of the data from the source was successfully synced). So the fact that the overall sync was cancelled but normalization specifically succeeded is expected behavior. 

could you share the full log of your sync however so we can understand the reason behind the failure?

**Comment by denis-sokolov** [comment]
I see. Then I suppose the issue is a cosmetic one. Perhaps the normalization success message could be more explicit and less green. E.g. “Normalization step finished successfully.”

I’ve sent you the full log to your email at dataline.io, let me know if I chose a wrong address.

**Comment by sherifnada** [comment]
relevant part of the logs with the issue: 

```
2021-11-01 10:27:04 INFO  Syncing stream: In_App_Checklist_Settings__Share 
2021-11-01 10:27:04 INFO  Giving up for returned HTTP status: 400
2021-11-01 10:27:04 ERROR Encountered an exception while reading stream SourceSalesforce
Traceback (most recent call last):
  File "/airbyte/integration_code/source_salesforce/source.py", line 79, in read
    internal_config=internal_config,
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 134, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 206, in _read_full_refresh
    for record in records:
  File "/airbyte/integration_code/source_salesforce/streams.py", line 232, in read_records
    job_id = self.create_stream_job(query=params["q"], url=path)
  File "/airbyte/integration_code/source_salesforce/streams.py", line 130, in create_stream_job
    raise error
  File "/airbyte/integration_code/source_salesforce/streams.py", line 116, in create_stream_job
    response = self._send_http_request("POST", f"{self.url_base}/{url}", json=json)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/airbyte/integration_code/source_salesforce/streams.py", line 110, in _send_http_request
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://<REDACTED>.my.salesforce.com//services/data/v52.0/jobs/query

2021-11-01 10:27:04 ERROR Traceback (most recent call last):
2021-11-01 10:27:04 ERROR   File "/airbyte/integration_code/main.py", line 13, in <module>
2021-11-01 10:27:04 ERROR     launch(source, sys.argv[1:])
2021-11-01 10:27:04 ERROR   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 105, in launch
2021-11-01 10:27:04 ERROR     for message in source_entrypoint.run(parsed_args):
2021-11-01 10:27:04 ERROR   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 96, in run
2021-11-01 10:27:04 ERROR     for message in generator:
2021-11-01 10:27:04 ERROR   File "/airbyte/integration_code/source_salesforce/source.py", line 83, in read
2021-11-01 10:27:04 ERROR     raise e
2021-11-01 10:27:04 ERROR   File "/airbyte/integration_code/source_salesforce/source.py", line 79, in read
2021-11-01 10:27:04 ERROR     internal_config=internal_config,
2021-11-01 10:27:04 ERROR   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 134, in _read_stream
2021-11-01 10:27:04 ERROR     for record in record_iterator:
2021-11-01 10:27:04 ERROR   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 206, in _read_full_refresh
2021-11-01 10:27:04 ERROR     for record in records:
2021-11-01 10:27:04 ERROR   File "/airbyte/integration_code/source_salesforce/streams.py", line 232, in read_records
2021-11-01 10:27:04 ERROR     job_id = self.create_stream_job(query=params["q"], url=path)
2021-11-01 10:27:04 ERROR   File "/airbyte/integration_code/source_salesforce/streams.py", line 130, in create_stream_job
2021-11-01 10:27:04 ERROR     raise error
2021-11-01 10:27:04 ERROR   File "/airbyte/integration_code/source_salesforce/streams.py", line 116, in create_stream_job
2021-11-01 10:27:04 ERROR     response = self._send_http_request("POST", f"{self.url_base}/{url}", json=json)
2021-11-01 10:27:04 ERROR   File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
2021-11-01 10:27:04 ERROR     ret = target(*args, **kwargs)
2021-11-01 10:27:04 ERROR   File "/airbyte/integration_code/source_salesforce/streams.py", line 110, in _send_http_request
2021-11-01 10:27:04 ERROR     response.raise_for_status()
2021-11-01 10:27:04 ERROR   File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 953, in raise_for_status
2021-11-01 10:27:04 ERROR     raise HTTPError(http_error_msg, response=self)
2021-11-01 10:27:04 ERROR requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://<REDACTED>.my.salesforce.com//services/data/v52.0/jobs/query
2021-11-01 10:27:36 INFO  Exit code for pod source-salesforce-worker-5466-0-siwqa is 1
2021-11-01 10:27:36 INFO  Closed all resources for pod source-salesforce-worker-5466-0-siwqa
```

**Comment by yevhenii-ldv** [comment]
Hi @denis-sokolov!
I have investigated this issue and I have two questions for you:
1. As far as I understand, then you are using the configuration with BULK as API Type, is that so?
2. I have tried over 300 streams to reproduce this error, and it doesnэt reproduce for me (I tried both on the latest version and on the version that is indicated in the ticket `0.1.2`). After this issue was created, new versions for the Salesforce connector were released. Could you please update the Salesforce version to the latest (namely `0.1.6`) and restart the synchronization to make sure that this problem still exists. If the problem persists - could you please provide more detailed error logs that you will receive during the synchronization process?

Thank you for your active participation.

**Comment by denis-sokolov** [comment]
Correct, I am using BULK as API type.

Running the sync again on 0.1.6 failed after running for 14 minutes. The important bit seems to be “In_App_Checklist_Settings__Share: [{'errorCode': 'INVALIDENTITY', 'message': "Entity '01I4x000001fDs9.Share' is not supported by the Bulk API."}] ”

<details><summary>Log snippet</summary>

```
...
[34msource[0m - 2021-11-19 15:21:24 INFO DefaultAirbyteStreamFactory(internalLog):97 - Created Job: 7504x000009GGJWAA4 to sync In_App_Checklist_Settings__c
[34msource[0m - 2021-11-19 15:21:25 INFO DefaultAirbyteStreamFactory(internalLog):97 - Read 0 records from In_App_Checklist_Settings__c stream
[34msource[0m - 2021-11-19 15:21:25 INFO DefaultAirbyteStreamFactory(internalLog):97 - Syncing stream: In_App_Checklist_Settings__Share 
[34msource[0m - 2021-11-19 15:21:25 INFO DefaultAirbyteStreamFactory(internalLog):97 - Giving up for returned HTTP status: 400, body: [{'errorCode': 'INVALIDENTITY', 'message': "Entity '01I4x000001fDs9.Share' is not supported by the Bulk API."}]
[34msource[0m - 2021-11-19 15:21:25 ERROR DefaultAirbyteStreamFactory(internalLog):95 - Giving up _send_http_request(...) after 1 tries (requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://headsup4.my.salesforce.com/services/data/v52.0/jobs/query)
[34msource[0m - 2021-11-19 15:21:25 ERROR DefaultAirbyteStreamFactory(internalLog):95 - Encountered an exception while reading stream SourceSalesforce
Traceback (most recent call last):
  File "/airbyte/integration_code/source_salesforce/source.py", line 85, in read
    internal_config=internal_config,
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 136, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 208, in _read_full_refresh
    for record in records:
  File "/airbyte/integration_code/source_salesforce/streams.py", line 241, in read_records
    job_full_url = self.execute_job(query=params["q"], url=f"{self.url_base}{path}")
  File "/airbyte/integration_code/source_salesforce/streams.py", line 190, in execute_job
    job_id = self.create_stream_job(query=query, url=url)
  File "/airbyte/integration_code/source_salesforce/streams.py", line 154, in create_stream_job
    raise error
  File "/airbyte/integration_code/source_salesforce/streams.py", line 140, in create_stream_job
    response = self._send_http_request("POST", url, json=json)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/airbyte/integration_code/source_salesforce/streams.py", line 131, in _send_http_request
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://headsup4.my.salesforce.com/services/data/v52.0/jobs/query
...
```

</details>

**Comment by yevhenii-ldv** [comment]
@denis-sokolov Thank you very much, this greatly expands the understanding of this error.

**Comment by yevhenii-ldv** [comment]
Hello @denis-sokolov

We just merged this fix into master and released a new version of the connector (Salesforce version 0.1.7). 

Upgrade your connector to version 0.1.7 and get started. To upgrade your connector version, go to the admin panel in the left hand side of the UI, find this connector in the list, and input the latest connector version. 

Please let us know if you have any further questions. 

Enjoy!
