### ISSUE TITLE
Sync seems to time out after 72 hours, Can't finish large table sets.

### ISSUE THREAD

**Issue by qops1981** [airbytehq/airbyte#7525]
## Enviroment
- **Airbyte version**:  example is 0.30.20-alpha
- **OS Version / Instance**: AWS EC2, Amazon Linux
- **Deployment**: Docker Deploy, .env is unchanged except for pg_db creds and connection to External DB vs container db. 
- **Source Connector and version**: Postgres 0.3.11 
- **Destination Connector and version**: Snowflake 0.3.16 
- **Severity**: Medium
- **Step where error happened**: Sync job to very large tables, 100GB+

## Current Behavior
Sync will eventually timeout. after roughtly 72 hours

## Expected Behavior
It should run as long as it need to to complete the sync

## Logs
Log Tail included in fold out
<details>
<summary>LOG</summary> 

```

2021-10-30 19:25:55 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-30 19:25:55 [32mINFO[m i.a.i.s.r.AbstractRelationalDbSource(lambda$createReadIterator$6):323 - {} - Reading stream archived_messages. Records read: 145210000
2021-10-30 19:25:55 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):203 - Records read: 483026000
2021-10-30 19:25:55 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):203 - Records read: 483027000
2021-10-30 19:25:55 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):203 - Records read: 483028000
2021-10-30 19:25:55 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):203 - Records read: 483029000
2021-10-30 19:25:55 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):203 - Records read: 483030000
2021-10-30 19:25:55 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-30 19:25:55 [32mINFO[m i.a.i.d.s.SnowflakeSqlOperations(insertRecordsInternal):40 - {} - actual size of batch: 10000
2021-10-30 19:25:58 INFO () DefaultReplicationWorker(cancel):258 - Cancelling destination...
2021-10-30 19:25:58 INFO () DefaultAirbyteDestination(cancel):114 - Attempting to cancel destination process...
2021-10-30 19:25:58 INFO () DefaultAirbyteDestination(cancel):119 - Destination process exists, cancelling...
2021-10-30 19:25:59 INFO () DefaultReplicationWorker(run):121 - Source thread complete.
2021-10-30 19:25:59 INFO () DefaultAirbyteDestination(cancel):121 - Cancelled destination process!
2021-10-30 19:25:59 INFO () DefaultReplicationWorker(cancel):265 - Cancelling source...
2021-10-30 19:25:59 INFO () DefaultReplicationWorker(run):122 - Waiting for destination thread to join.
2021-10-30 19:25:59 INFO () DefaultReplicationWorker(run):124 - Destination thread complete.
2021-10-30 19:25:59 INFO () DefaultAirbyteSource(cancel):121 - Attempting to cancel source process...
2021-10-30 19:25:59 INFO () DefaultAirbyteSource(cancel):126 - Source process exists, cancelling...
2021-10-30 19:25:59 WARN () LineGobbler(voidCall):68 - airbyte-source gobbler IOException: Stream closed. Typically happens when cancelling a job.
2021-10-30 19:25:59 INFO () DefaultAirbyteSource(cancel):128 - Cancelled source process!
2021-10-30 19:25:59 INFO () TemporalAttemptExecution(lambda$getCancellationChecker$2):183 - Interrupting worker thread...
2021-10-30 19:25:59 INFO () TemporalAttemptExecution(lambda$getCancellationChecker$2):186 - Cancelling completable future...
2021-10-30 19:25:59 WARN () CancellationHandler$TemporalCancellationHandler(checkAndHandleCancellation):51 - Job either timeout-ed or was cancelled.
2021-10-30 19:25:59 INFO () TemporalAttemptExecution(get):115 - Stopping cancellation check scheduling...
2021-10-30 19:25:59 ERROR () DefaultReplicationWorker(run):128 - Sync worker failed.
io.airbyte.workers.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
  at io.airbyte.workers.protocols.airbyte.DefaultAirbyteSource.close(DefaultAirbyteSource.java:115) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
  at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:126) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
  at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:32) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
  at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$1(TemporalAttemptExecution.java:145) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
  at java.lang.Thread.run(Thread.java:832) [?:?]
  Suppressed: java.io.IOException: Stream closed
    at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:442) ~[?:?]
    at java.io.OutputStream.write(OutputStream.java:162) ~[?:?]
    at java.io.BufferedOutputStream.write(BufferedOutputStream.java:123) ~[?:?]
    at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:242) ~[?:?]
    at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:321) ~[?:?]
    at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:325) ~[?:?]
    at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:159) ~[?:?]
    at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:251) ~[?:?]
    at java.io.BufferedWriter.flush(BufferedWriter.java:257) ~[?:?]
    at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.notifyEndOfStream(DefaultAirbyteDestination.java:87) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
    at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.close(DefaultAirbyteDestination.java:100) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
    at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:101) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
    at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:32) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
    at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$1(TemporalAttemptExecution.java:145) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
    at java.lang.Thread.run(Thread.java:832) [?:?]
2021-10-30 19:25:59 WARN () POJOActivityTaskHandler$POJOActivityImplementation(execute):243 - Activity failure. ActivityId=e7bb92f0-c268-3d0c-8fe7-f621537bfb63, activityType=Replicate, attempt=1
java.util.concurrent.CancellationException: null
  at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2468) ~[?:?]
  at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getCancellationChecker$2(TemporalAttemptExecution.java:189) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
  at io.airbyte.workers.temporal.CancellationHandler$TemporalCancellationHandler.checkAndHandleCancellation(CancellationHandler.java:50) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
  at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getCancellationChecker$3(TemporalAttemptExecution.java:192) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
  at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
  at java.lang.Thread.run(Thread.java:832) [?:?]
2021-10-30 19:25:59 INFO () DefaultReplicationWorker(run):152 - sync summary: io.airbyte.config.ReplicationAttemptSummary@666390b8[status=cancelled,recordsSynced=483030495,bytesSynced=190128295585,startTime=1635408378899,endTime=1635621959150]
2021-10-30 19:25:59 INFO () DefaultReplicationWorker(run):161 - Source did not output any state messages
2021-10-30 19:25:59 WARN () DefaultReplicationWorker(run):172 - State capture: No state retained.
2021-10-30 19:25:59 WARN () CancellationHandler$TemporalCancellationHandler(checkAndHandleCancellation):51 - Job either timeout-ed or was cancelled.
2021-10-30 19:25:59 ERROR () PollerOptions$Builder(lambda$build$0):138 - uncaught exception
java.lang.RuntimeException: Failure processing activity response. WorkflowId=1378f044-2018-46bd-b22a-e33c561dc3c8, RunId=62de2784-44f3-4e18-9807-3218214f14bc, ActivityType=Replicate, ActivityId=e7bb92f0-c268-3d0c-8fe7-f621537bfb63
  at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.wrapFailure(ActivityWorker.java:256) ~[temporal-sdk-1.0.4.jar:?]
  at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.wrapFailure(ActivityWorker.java:154) ~[temporal-sdk-1.0.4.jar:?]
  at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:79) ~[temporal-sdk-1.0.4.jar:?]
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
  at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: io.grpc.StatusRuntimeException: NOT_FOUND: workflow execution already completed
  at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262) ~[grpc-stub-1.40.0.jar:1.40.0]
  at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243) ~[grpc-stub-1.40.0.jar:1.40.0]
  at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156) ~[grpc-stub-1.40.0.jar:1.40.0]
  at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.respondActivityTaskFailed(WorkflowServiceGrpc.java:2770) ~[temporal-serviceclient-1.0.4.jar:?]
  at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.lambda$sendReply$1(ActivityWorker.java:302) ~[temporal-sdk-1.0.4.jar:?]
  at io.temporal.internal.common.GrpcRetryer.lambda$retry$0(GrpcRetryer.java:109) ~[temporal-sdk-1.0.4.jar:?]
  at io.temporal.internal.common.GrpcRetryer.retryWithResult(GrpcRetryer.java:127) ~[temporal-sdk-1.0.4.jar:?]
  at io.temporal.internal.common.GrpcRetryer.retry(GrpcRetryer.java:106) ~[temporal-sdk-1.0.4.jar:?]
  at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.sendReply(ActivityWorker.java:296) ~[temporal-sdk-1.0.4.jar:?]
  at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:196) ~[temporal-sdk-1.0.4.jar:?]
  at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:154) ~[temporal-sdk-1.0.4.jar:?]
  at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73) ~[temporal-sdk-1.0.4.jar:?]
  ... 3 more

```

</details>

## Steps to Reproduce
1. Launch Airbyte from Docker Compose having an external Postgres server on AWS RDS and configure the `.env` with those credentials.
2. Create a Sync between another Postgres Database (ours is in Heroku) and Snowflake on a set of very large tables.
3. See if they can get past 72 hours

## Are you willing to submit a PR?

If it's something I can do, sure.

## Note
This maybe as something as easy as a config, I just haven't found anything yet that would indicate why it just stops after that time limit. I can confirm that we have not intentionally canceled the job, despite the logs.

**Comment by harshithmullapudi** [comment]
Thanks for creating issue this helps us to track them. Team will look into it soon.

**Comment by marcosmarxm** [comment]
@qops1981 there is a .env parameter you can configure this timeout. You can change it and restart Airbyte.
https://github.com/airbytehq/airbyte/blob/9a07136f2b7e78fd611a3ec12c8ec6db78dc4dd1/.env#L73-L77

**Comment by misteryeo** [comment]
@qops1981 can you confirm that following @marcosmarxm's guidance above you've managed to resolve this issue so we can close this?

**Comment by qops1981** [comment]
OMG, Yes, I am so sorry. Yes, this was super helpful and resolved out problem. Thank You!
