### ISSUE TITLE
Source Facebook Marketing 0.2.21: JobTimeout with 0 seconds and Job Failed message return

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#7533]
## Enviroment
- **Airbyte version**:  0.30.20-alpha
- **OS Version / Instance**: GCP
- **Deployment**: Docker
- **Source Connector and version**: Facebook Marketing 0.2.21
- **Destination Connector and version**: Snowflake
- **Severity**: Very Low / Low / Medium / **High** / Critical
- **Step where error happened**: Deploy / **Sync job** / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
Job fails in a random fashion.

The last sync: 
![image](https://user-images.githubusercontent.com/5154322/139725303-13128997-779d-4600-8699-c2763b30f72b.png)

The last week:
![image](https://user-images.githubusercontent.com/5154322/139726378-7bcf2c1f-d880-4326-acf8-fb800ccd3974.png)

## Expected Behavior
Connector should handle error messgae from API and give me a good feedback to understand the failure reason.

## Logs
```
2021-11-01 11:08:01 ERROR () LineGobbler(voidCall):65 - Traceback (most recent call last):
2021-11-01 11:08:01 ERROR () LineGobbler(voidCall):65 -   File "/airbyte/integration_code/main.py", line 13, in <module>
2021-11-01 11:08:01 ERROR () LineGobbler(voidCall):65 -     launch(source, sys.argv[1:])
2021-11-01 11:08:01 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 108, in launch
2021-11-01 11:08:01 ERROR () LineGobbler(voidCall):65 -     for message in source_entrypoint.run(parsed_args):
2021-11-01 11:08:01 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 99, in run
2021-11-01 11:08:01 ERROR () LineGobbler(voidCall):65 -     for message in generator:
2021-11-01 11:08:01 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 108, in read
2021-11-01 11:08:01 ERROR () LineGobbler(voidCall):65 -     raise e
2021-11-01 11:08:01 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 104, in read
2021-11-01 11:08:01 ERROR () LineGobbler(voidCall):65 -     internal_config=internal_config,
2021-11-01 11:08:01 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 134, in _read_stream
2021-11-01 11:08:01 ERROR () LineGobbler(voidCall):65 -     for record in record_iterator:
2021-11-01 11:08:01 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 206, in _read_full_refresh
2021-11-01 11:08:01 ERROR () LineGobbler(voidCall):65 -     for record in records:
2021-11-01 11:08:01 ERROR () LineGobbler(voidCall):65 -   File "/airbyte/integration_code/source_facebook_marketing/streams.py", line 330, in read_records
2021-11-01 11:08:01 ERROR () LineGobbler(voidCall):65 -     result = self.wait_for_job(stream_slice["job"])
2021-11-01 11:08:01 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
2021-11-01 11:08:01 ERROR () LineGobbler(voidCall):65 -     ret = target(*args, **kwargs)
2021-11-01 11:08:01 ERROR () LineGobbler(voidCall):65 -   File "/airbyte/integration_code/source_facebook_marketing/streams.py", line 371, in wait_for_job
2021-11-01 11:08:01 ERROR () LineGobbler(voidCall):65 -     raise JobTimeoutException(f"AdReportRun {job} failed after {runtime.in_seconds()} seconds.")
2021-11-01 11:08:01 ERROR () LineGobbler(voidCall):65 - source_facebook_marketing.common.JobTimeoutException: AdReportRun <AdReportRun> {
2021-11-01 11:08:01 ERROR () LineGobbler(voidCall):65 -     "account_id": "255091422171865",
2021-11-01 11:08:01 ERROR () LineGobbler(voidCall):65 -     "async_percent_completion": 0,
2021-11-01 11:08:01 ERROR () LineGobbler(voidCall):65 -     "async_status": "Job Failed",
2021-11-01 11:08:01 ERROR () LineGobbler(voidCall):65 -     "date_start": "2020-10-21",
2021-11-01 11:08:01 ERROR () LineGobbler(voidCall):65 -     "date_stop": "2020-10-27",
2021-11-01 11:08:01 ERROR () LineGobbler(voidCall):65 -     "id": "374882567717385",
2021-11-01 11:08:01 ERROR () LineGobbler(voidCall):65 -     "report_run_id": "374882567717385",
2021-11-01 11:08:01 ERROR () LineGobbler(voidCall):65 -     "time_ref": 1635764820
2021-11-01 11:08:01 ERROR () LineGobbler(voidCall):65 - } failed after 0 seconds.
```

[logs-5534-0.txt](https://github.com/airbytehq/airbyte/files/7455511/logs-5534-0.txt)

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by manavkohli** [comment]
+1 here

**Comment by htrueman** [comment]
It seems that it's an Facebook issue. The only possible solution they suggest is to restart the job after it fails.
For now, please try to reduce `insights_days_per_job` value (e.g. to 3), this should reduce the number of failures.

We are working on restarting job logics, going to push it later today.

**Comment by ayyoubmaulana** [comment]
I have the same issue, using Airbyte 0.32.2 and Facebook 0.2.20
