### ISSUE TITLE
Marketo connector seems to always fail

### ISSUE THREAD

**Issue by pacificsky** [airbytehq/airbyte#7598]
## Environment
- **Airbyte version**:  0.30.25-alpha
- **OS Version / Instance**: Ubuntu 20.04 on AWS EC2
- **Deployment**: Airbyte-provided docker image
- **Source Connector and version**: Marketo 0.1.0
- **Destination Connector and version**: Snowflake 0.3.16
- **Severity**: High
- **Step where error happened**: Sync job

## Current Behavior
Market sync job seems to always fail with no useful error message. Eventually it gives up after three attempts. 
Some data seems to be getting synced, but there's no way to tell if the data is complete or partial. 

I tried this across two different Marketo deployments. 

## Expected Behavior
Marketo sync should succeed. 

## Logs

<details>

```
2021-11-03 09:40:31 INFO () WorkerRun(call):49 - Executing worker wrapper. Airbyte version: 0.30.25-alpha
2021-11-03 09:40:31 INFO () TemporalAttemptExecution(get):94 - Executing worker wrapper. Airbyte version: 0.30.25-alpha
2021-11-03 09:40:31 WARN () Databases(createPostgresDatabaseWithRetry):38 - Waiting for database to become available...
2021-11-03 09:40:31 INFO () JobsDatabaseInstance(lambda$static$2):25 - Testing if jobs database is ready...
2021-11-03 09:40:31 INFO () Databases(createPostgresDatabaseWithRetry):55 - Database available!
2021-11-03 09:40:31 INFO () DefaultReplicationWorker(run):82 - start sync worker. job id: 3 attempt id: 2
2021-11-03 09:40:31 INFO () DefaultReplicationWorker(run):91 - configured sync modes: {null.activity_types=full_refresh - append, null.leads=full_refresh - append, null.campaigns=full_refresh - append, null.activities_fill_out_form=full_refresh - append, null.activities_visit_webpage=full_refresh - append}
2021-11-03 09:40:31 INFO () DefaultAirbyteDestination(start):65 - Running destination...
2021-11-03 09:40:31 INFO () LineGobbler(voidCall):82 - Checking if airbyte/destination-snowflake:0.3.16 exists...
2021-11-03 09:40:31 INFO () DockerProcessFactory(create):127 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/3/2 --network host --log-driver none airbyte/destination-snowflake:0.3.16 write --config destination_config.json --catalog destination_catalog.json
2021-11-03 09:40:31 INFO () LineGobbler(voidCall):82 - Checking if airbyte/source-marketo:0.1.0 exists...
2021-11-03 09:40:31 INFO () DockerProcessFactory(create):127 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/3/2 --network host --log-driver none airbyte/source-marketo:0.1.0 read --config source_config.json --catalog source_catalog.json
2021-11-03 09:40:31 INFO () DefaultReplicationWorker(lambda$getDestinationOutputRunnable$3):226 - Destination output thread started.
2021-11-03 09:40:31 INFO () DefaultReplicationWorker(run):119 - Waiting for source thread to join.
2021-11-03 09:40:31 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):190 - Replication thread started.
2021-11-03 09:40:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):62 - 2021-11-03 09:40:33 [32mINFO[m i.a.i.d.s.SnowflakeDestination(main):61 - {} - starting destination: class io.airbyte.integrations.destination.snowflake.SnowflakeDestination
2021-11-03 09:41:46 INFO () DefaultAirbyteStreamFactory(internalLog):98 - Starting syncing SourceMarketo
2021-11-03 11:36:02 ERROR () LineGobbler(voidCall):82 - Traceback (most recent call last):
2021-11-03 11:36:02 INFO () DefaultReplicationWorker(run):121 - Source thread complete.
2021-11-03 11:36:02 INFO () DefaultReplicationWorker(run):122 - Waiting for destination thread to join.
2021-11-03 11:36:14 INFO () DefaultReplicationWorker(run):124 - Destination thread complete.
2021-11-03 11:36:14 ERROR () DefaultReplicationWorker(run):128 - Sync worker failed.
io.airbyte.workers.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
	at io.airbyte.workers.protocols.airbyte.DefaultAirbyteSource.close(DefaultAirbyteSource.java:123) ~[io.airbyte-airbyte-workers-0.30.25-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:126) ~[io.airbyte-airbyte-workers-0.30.25-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:32) ~[io.airbyte-airbyte-workers-0.30.25-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$1(TemporalAttemptExecution.java:145) ~[io.airbyte-airbyte-workers-0.30.25-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
2021-11-03 11:36:14 INFO () DefaultReplicationWorker(run):152 - sync summary: io.airbyte.config.ReplicationAttemptSummary@48e2b10f[status=failed,recordsSynced=215389,bytesSynced=62398480,startTime=1635932431269,endTime=1635939374338]
2021-11-03 11:36:14 INFO () DefaultReplicationWorker(run):161 - Source did not output any state messages
2021-11-03 11:36:14 WARN () DefaultReplicationWorker(run):172 - State capture: No state retained.
2021-11-03 11:36:14 INFO () TemporalAttemptExecution(get):115 - Stopping cancellation check scheduling...
2021-11-03 11:36:14 INFO () SyncWorkflow$ReplicationActivityImpl(replicate):203 - sync summary: io.airbyte.config.StandardSyncOutput@57ab1271[standardSyncSummary=io.airbyte.config.StandardSyncSummary@63dd2a86[status=failed,recordsSynced=215389,bytesSynced=62398480,startTime=1635932431269,endTime=1635939374338],state=<null>,outputCatalog=io.airbyte.protocol.models.ConfiguredAirbyteCatalog@2ca1bc14[streams=[io.airbyte.protocol.models.ConfiguredAirbyteStream@5c521002[stream=io.airbyte.protocol.models.AirbyteStream@53e5a963[name=marketotest__activities_fill_out_form,jsonSchema={"type":["null","object"],"$schema":"http://json-schema.org/draft-07/schema#","properties":{"leadId":{"type":["null","integer"]},"attributes":{"type":["null","string"]},"campaignId":{"type":["null","integer"]},"user_agent":{"type":["string","null"]},"form_fields":{"type":["string","null"]},"marketoGUID":{"type":["null","string"]},"webpage_i_d":{"type":["integer","null"]},"activityDate":{"type":["null","string"],"format":"date-time"},"program_name":{"type":["string","null"]},"program_type":{"type":["string","null"]},"referrer_url":{"type":["string","null"]},"activityTypeId":{"type":["null","integer"]},"query_parameters":{"type":["string","null"]},"client_ip_address":{"type":["string","null"]},"primaryAttributeName":{"type":["null","string"]},"primaryAttributeValue":{"type":["null","string"]},"primaryAttributeValueId":{"type":["null","string"]}},"additionalProperties":false},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[activityDate],sourceDefinedPrimaryKey=[[marketoGUID]],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[activityDate],destinationSyncMode=append,primaryKey=[[marketoGUID]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@59663083[stream=io.airbyte.protocol.models.AirbyteStream@788666a7[name=marketotest__activities_visit_webpage,jsonSchema={"type":["null","object"],"$schema":"http://json-schema.org/draft-07/schema#","properties":{"leadId":{"type":["null","integer"]},"attributes":{"type":["null","string"]},"campaignId":{"type":["null","integer"]},"user_agent":{"type":["string","null"]},"marketoGUID":{"type":["null","string"]},"webpage_url":{"type":["string","null"]},"activityDate":{"type":["null","string"],"format":"date-time"},"program_name":{"type":["string","null"]},"program_type":{"type":["string","null"]},"referrer_url":{"type":["string","null"]},"search_query":{"type":["string","null"]},"search_engine":{"type":["string","null"]},"activityTypeId":{"type":["null","integer"]},"personalized_url":{"type":["boolean","null"]},"query_parameters":{"type":["string","null"]},"client_ip_address":{"type":["string","null"]},"primaryAttributeName":{"type":["null","string"]},"primaryAttributeValue":{"type":["null","string"]},"primaryAttributeValueId":{"type":["null","string"]}},"additionalProperties":false},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[activityDate],sourceDefinedPrimaryKey=[[marketoGUID]],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[activityDate],destinationSyncMode=append,primaryKey=[[marketoGUID]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@3418abb5[stream=io.airbyte.protocol.models.AirbyteStream@4ac8a2e4[name=marketotest__activity_types,jsonSchema={"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"name":{"type":["null","string"]},"attributes":{"type":["null","array"],"items":{"type":["null","object"],"properties":{"name":{"type":["null","string"]},"dataType":{"type":["null","string"]}}}},"description":{"type":["null","string"]},"primaryAttribute":{"type":["null","object"],"properties":{"name":{"type":["null","string"]},"dataType":{"type":["null","string"]}}}},"additionalProperties":false},supportedSyncModes=[full_refresh],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[[id]],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@22427116[stream=io.airbyte.protocol.models.AirbyteStream@693a88a7[name=marketotest__campaigns,jsonSchema={"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"name":{"type":["null","string"]},"type":{"type":["null","string"]},"active":{"type":["null","boolean"]},"createdAt":{"type":["null","string"],"format":"date-time"},"programId":{"type":["null","integer"]},"updatedAt":{"type":["null","string"],"format":"date-time"},"description":{"type":["null","string"]},"programName":{"type":["null","string"]},"workspaceName":{"type":["null","string"]}},"additionalProperties":false},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[createdAt],sourceDefinedPrimaryKey=[[id]],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[createdAt],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@180ec336[stream=io.airbyte.protocol.models.AirbyteStream@175e9d51[name=marketotest__leads,jsonSchema={"type":["object","null"],"properties":{"id":{"type":["integer","null"]},"fax":{"type":["string","null"]},"city":{"type":["string","null"]},"site":{"type":["string","null"]},"email":{"type":["string","null"]},"phone":{"type":["string","null"]},"state":{"type":["string","null"]},"title":{"type":["string","null"]},"isLead":{"type":["boolean","null"]},"rating":{"type":["string","null"]},"address":{"type":["string","null"]},"company":{"type":["string","null"]},"cookies":{"type":["string","null"]},"country":{"type":["string","null"]},"sicCode":{"type":["string","null"]},"urgency":{"type":["number","null"]},"website":{"type":["string","null"]},"industry":{"type":["string","null"]},"lastName":{"type":["string","null"]},"leadRole":{"type":["string","null"]},"mktoName":{"type":["string","null"]},"priority":{"type":["integer","null"]},"createdAt":{"type":["string","null"],"format":"date-time"},"doNotCall":{"type":["boolean","null"]},"firstName":{"type":["string","null"]},"leadScore":{"type":["integer","null"]},"mainPhone":{"type":["string","null"]},"updatedAt":{"type":["string","null"],"format":"date-time"},"department":{"type":["string","null"]},"leadPerson":{"type":["string","null"]},"leadSource":{"type":["string","null"]},"leadStatus":{"type":["string","null"]},"middleName":{"type":["string","null"]},"personType":{"type":["string","null"]},"postalCode":{"type":["string","null"]},"salutation":{"type":["string","null"]},"anonymousIP":{"type":["string","null"]},"billingCity":{"type":["string","null"]},"blackListed":{"type":["boolean","null"]},"dateOfBirth":{"type":["string","null"],"format":"date-time"},"isAnonymous":{"type":["boolean","null"]},"mobilePhone":{"type":["string","null"]},"billingState":{"type":["string","null"]},"emailInvalid":{"type":["boolean","null"]},"inferredCity":{"type":["string","null"]},"unsubscribed":{"type":["boolean","null"]},"annualRevenue":{"type":["number","null"]},"billingStreet":{"type":["string","null"]},"mktoIsPartner":{"type":["boolean","null"]},"relativeScore":{"type":["integer","null"]},"billingCountry":{"type":["string","null"]},"contactCompany":{"type":["string","null"]},"emailSuspended":{"type":["boolean","null"]},"mktoIsCustomer":{"type":["boolean","null"]},"personTimeZone":{"type":["string","null"]},"doNotCallReason":{"type":["string","null"]},"inferredCompany":{"type":["string","null"]},"inferredCountry":{"type":["string","null"]},"leadPartitionId":{"type":["string","null"]},"mktoPersonNotes":{"type":["string","null"]},"relativeUrgency":{"type":["integer","null"]},"blackListedCause":{"type":["string","null"]},"emailSuspendedAt":{"type":["string","null"],"format":"date-time"},"mktoCompanyNotes":{"type":["string","null"]},"originalReferrer":{"type":["string","null"]},"billingPostalCode":{"type":["string","null"]},"emailInvalidCause":{"type":["string","null"]},"externalCompanyId":{"type":["string","null"]},"numberOfEmployees":{"type":["integer","null"]},"inferredPostalCode":{"type":["string","null"]},"leadRevenueStageId":{"type":["string","null"]},"marketingSuspended":{"type":["boolean","null"]},"mktoDoNotCallCause":{"type":["string","null"]},"originalSourceInfo":{"type":["string","null"]},"originalSourceType":{"type":["string","null"]},"unsubscribedReason":{"type":["string","null"]},"emailSuspendedCause":{"type":["string","null"]},"inferredStateRegion":{"type":["string","null"]},"mktoAcquisitionDate":{"type":["string","null"],"format":"date-time"},"acquisitionProgramId":{"type":["string","null"]},"originalSearchEngine":{"type":["string","null"]},"originalSearchPhrase":{"type":["string","null"]},"externalSalesPersonId":{"type":["string","null"]},"inferredPhoneAreaCode":{"type":["string","null"]},"registrationSourceInfo":{"type":["string","null"]},"registrationSourceType":{"type":["string","null"]},"leadRevenueCycleModelId":{"type":["string","null"]},"marketingSuspendedCause":{"type":["string","null"]},"inferredMetropolitanArea":{"type":["string","null"]},"personPrimaryLeadInterest":{"type":["string","null"]}},"additionalProperties":false},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[updatedAt],sourceDefinedPrimaryKey=[[id]],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[updatedAt],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}]],additionalProperties={}]]
2021-11-03 11:36:14 INFO () TemporalAttemptExecution(get):94 - Executing worker wrapper. Airbyte version: 0.30.25-alpha
2021-11-03 11:36:14 WARN () Databases(createPostgresDatabaseWithRetry):38 - Waiting for database to become available...
2021-11-03 11:36:14 INFO () JobsDatabaseInstance(lambda$static$2):25 - Testing if jobs database is ready...
2021-11-03 11:36:14 INFO () Databases(createPostgresDatabaseWithRetry):55 - Database available!
2021-11-03 11:36:14 INFO () DefaultNormalizationWorker(run):46 - Running normalization.
2021-11-03 11:36:14 INFO () DefaultNormalizationRunner(runProcess):115 - Running with normalization version: airbyte/normalization:0.1.58
2021-11-03 11:36:14 INFO () LineGobbler(voidCall):82 - Checking if airbyte/normalization:0.1.58 exists...
2021-11-03 11:36:14 INFO () DockerProcessFactory(create):127 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/3/2/normalize --network host --log-driver none airbyte/normalization:0.1.58 run --integration-type snowflake --config destination_config.json --catalog destination_catalog.json
2021-11-03 11:36:14 INFO () LineGobbler(voidCall):82 - Running: transform-config --config destination_config.json --integration-type snowflake --out /data/3/2/normalize
2021-11-03 11:36:29 INFO () DefaultNormalizationWorker(run):69 - Normalization executed in 14 seconds.
2021-11-03 11:36:29 INFO () TemporalAttemptExecution(get):115 - Stopping cancellation check scheduling...
```
</details>

## Steps to Reproduce
1. Set up a marketo connector pointing at a destination of your choice (I used Snowflake)
2. Limit the selected streams to: activities_visit_webpage, activities_fill_out_form, leads, campaigns, activity_types
3. Run the sync

## Are you willing to submit a PR?
Unfortunately I don't have the bandwidth to do so.

**Comment by chriestensonb** [comment]
I filed a similar issue a few days ago here: https://github.com/airbytehq/airbyte/issues/7286

**Comment by pacificsky** [comment]
I noticed that! At least in your log there was a very specific issue it was bombing on. Here, there's nothing!

**Comment by sherifnada** [comment]
@pacificsky can you upgrade airbyte and run again to obtain logs? there was a bug in the platform which blackholed logs from connectors

**Comment by pdulapalli** [comment]
@sherifnada I was able to reproduce the error state on the Marketo sync, but this time successfully retrieved a stack trace. Given the error stack, this seems like a duplicate of: https://github.com/airbytehq/airbyte/issues/7286

### Environment

Same configuration as @pacificsky used above, but with Airbyte version: 0.32.4-alpha.

### Logs

Here is the relevant portion from the failed run:
```
[34msource[0m - 2021-11-19 19:41:16 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Starting syncing SourceMarketo
[34msource[0m - 2021-11-19 19:41:16 ERROR () LineGobbler(voidCall):82 - Traceback (most recent call last):
[34msource[0m - 2021-11-19 19:41:16 ERROR () LineGobbler(voidCall):82 -   File "/airbyte/integration_code/main.py", line 33, in <module>
[34msource[0m - 2021-11-19 19:41:16 ERROR () LineGobbler(voidCall):82 -     launch(source, sys.argv[1:])
[34msource[0m - 2021-11-19 19:41:16 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 125, in launch
[34msource[0m - 2021-11-19 19:41:16 ERROR () LineGobbler(voidCall):82 -     for message in source_entrypoint.run(parsed_args):
[34msource[0m - 2021-11-19 19:41:16 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 116, in run
[34msource[0m - 2021-11-19 19:41:16 ERROR () LineGobbler(voidCall):82 -     for message in generator:
[34msource[0m - 2021-11-19 19:41:16 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 121, in read
[34msource[0m - 2021-11-19 19:41:16 ERROR () LineGobbler(voidCall):82 -     raise e
[34msource[0m - 2021-11-19 19:41:16 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Syncing stream: leads 
[34msource[0m - 2021-11-19 19:41:16 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 117, in read
[34msource[0m - 2021-11-19 19:41:16 ERROR () LineGobbler(voidCall):82 -     internal_config=internal_config,
[34msource[0m - 2021-11-19 19:41:16 ERROR () DefaultAirbyteStreamFactory(internalLog):95 - Encountered an exception while reading stream SourceMarketo
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 117, in read
    internal_config=internal_config,
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 147, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 182, in _read_incremental
    cursor_field=configured_stream.cursor_field, sync_mode=SyncMode.incremental, stream_state=stream_state
  File "/airbyte/integration_code/source_marketo/source.py", line 193, in stream_slices
    date_slice["id"] = export["exportId"]
KeyError: 'exportId'

[34msource[0m - 2021-11-19 19:41:16 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 147, in _read_stream
[34msource[0m - 2021-11-19 19:41:16 ERROR () LineGobbler(voidCall):82 -     for record in record_iterator:
[34msource[0m - 2021-11-19 19:41:16 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 182, in _read_incremental
[34msource[0m - 2021-11-19 19:41:16 ERROR () LineGobbler(voidCall):82 -     cursor_field=configured_stream.cursor_field, sync_mode=SyncMode.incremental, stream_state=stream_state
[34msource[0m - 2021-11-19 19:41:16 ERROR () LineGobbler(voidCall):82 -   File "/airbyte/integration_code/source_marketo/source.py", line 193, in stream_slices
[34msource[0m - 2021-11-19 19:41:16 ERROR () LineGobbler(voidCall):82 -     date_slice["id"] = export["exportId"]
[34msource[0m - 2021-11-19 19:41:16 ERROR () LineGobbler(voidCall):82 - KeyError: 'exportId'
```

**Comment by pacificsky** [comment]
Looks like the lack of meaningful output in my stack trace was because my airbyte version was out of date. I'm closing this as a duplicate of https://github.com/airbytehq/airbyte/issues/7286
