### ISSUE TITLE
mysql source scan stuck

### ISSUE THREAD

**Issue by radiatorius** [airbytehq/airbyte#7716]
## Enviroment
- **Airbyte version**:  0.30.31-alpha
- **OS Version / Instance**: macOS 12.0.1
- **Deployment**: Docker
- **Source Connector and version**: airbyte/source-mysql:0.4.9 (Incremental | Append)
- **Destination Connector and version**: airbyte/destination-s3:0.1.13
- **Severity**: High
- **Step where error happened**: Sync job
- 
## Current Behavior
Stops after reading 40 - 60% of all records and task hangs forever.

## Expected Behavior
Successful scanning of all records

## Logs
*2021-11-05 14:01:38 WARN () ActivityExecutionContextImpl(doHeartBeat):153 - Heartbeat failed
io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 9.971567100s. [closed=[], open=[[remote_addr=airbyte-temporal/172.19.0.7:7233]]]
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262) ~[grpc-stub-1.40.0.jar:1.40.0]*

<details>
<summary>

```
2021-11-05 14:01:38 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):203 - Records read: 430000
2021-11-05 14:01:38 WARN () ActivityExecutionContextImpl(doHeartBeat):153 - Heartbeat failed
io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 9.971567100s. [closed=[], open=[[remote_addr=airbyte-temporal/172.19.0.7:7233]]]
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262) ~[grpc-stub-1.40.0.jar:1.40.0]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243) ~[grpc-stub-1.40.0.jar:1.40.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156) ~[grpc-stub-1.40.0.jar:1.40.0]
	at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.recordActivityTaskHeartbeat(WorkflowServiceGrpc.java:2710) ~[temporal-serviceclient-1.0.4.jar:?]
	at io.temporal.internal.sync.ActivityExecutionContextImpl.sendHeartbeatRequest(ActivityExecutionContextImpl.java:203) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.ActivityExecutionContextImpl.doHeartBeat(ActivityExecutionContextImpl.java:147) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.ActivityExecutionContextImpl.heartbeat(ActivityExecutionContextImpl.java:108) ~[temporal-sdk-1.0.4.jar:?]
	at io.airbyte.workers.temporal.CancellationHandler$TemporalCancellationHandler.checkAndHandleCancellation(CancellationHandler.java:46) ~[io.airbyte-airbyte-workers-0.30.31-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getCancellationChecker$4(TemporalAttemptExecution.java:216) ~[io.airbyte-airbyte-workers-0.30.31-alpha.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]

```

</details>

## Steps to Reproduce
1. Run table, with > 1M records, incremental reading.

**Comment by grishick** [comment]
this should be fixed now that we've introduced more frequent checkpointing and auto-sizing number of records to fetch

**Comment by danieliser** [comment]
I think I'm seeing similar in the docker stack. I ran it successfully once but later changed to syncing to an S3  Avro store vs the previous Postgres and now it stops here and hangs every time:

```
2023-02-19 11:41:32 source > State report for stream cfbxdymgpd_pmapi_pum_reviews - original: null = null (count 0) -> latest: id = 778815 (count 1)
2023-02-19 11:41:32 INFO i.a.w.g.DefaultReplicationWorker(lambda$readFromSrcAndWriteToDstRunnable$7):385 - Records read: 779000 (129 MB)
2023-02-19 11:41:32 source > State report for stream cfbxdymgpd_pmapi_pum_reviews - original: null = null (count 0) -> latest: id = 778915 (count 1)
```
