### ISSUE TITLE
Source Facebook Marketing: failed normalization No matching signature for function TIMESTAMP_TRUNC

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#7737]
## Enviroment
- **Airbyte version**: Cloud
- **Source Connector and version**: Facebook Marketing 0.2.21
- **Destination Connector and version**: Bigquery 0.5.0
- **Severity**: Very Low / Low / Medium / **High** / Critical
- **Step where error happened**: replication & normalization

## Current Behavior
Sync failed during normalization step with a problem trying to convert date types.
```
normalization - 2021-11-08 10:09:02 INFO LineGobbler(voidCall):82 - Database Error in model ad_sets (models/generated/airbyte_incremental/default_ads_data/ad_sets.sql)
normalization - 2021-11-08 10:09:02 INFO LineGobbler(voidCall):82 -   No matching signature for function TIMESTAMP_TRUNC for argument types: STRING, DATE_TIME_PART. Supported signatures: TIMESTAMP_TRUNC(TIMESTAMP, DATE_TIME_PART, [STRING]); TIMESTAMP_TRUNC(DATETIME, DATE_TIME_PART) at [5:16]
normalization - 2021-11-08 10:09:02 INFO LineGobbler(voidCall):82 -   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_incremental/default_ads_data/ad_sets.sql
normalization - 2021-11-08 10:09:02 INFO LineGobbler(voidCall):82 - 
normalization - 2021-11-08 10:09:02 INFO LineGobbler(voidCall):82 - Database Error in model campaigns (models/generated/airbyte_incremental/default_ads_data/campaigns.sql)
normalization - 2021-11-08 10:09:02 INFO LineGobbler(voidCall):82 -   No matching signature for function TIMESTAMP_TRUNC for argument types: STRING, DATE_TIME_PART. Supported signatures: TIMESTAMP_TRUNC(TIMESTAMP, DATE_TIME_PART, [STRING]); TIMESTAMP_TRUNC(DATETIME, DATE_TIME_PART) at [5:16]
normalization - 2021-11-08 10:09:02 INFO LineGobbler(voidCall):82 -   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_incremental/default_ads_data/campaigns.sql
normalization - 2021-11-08 10:09:02 INFO LineGobbler(voidCall):82 - 
normalization - 2021-11-08 10:09:02 INFO LineGobbler(voidCall):82 - Database Error in model ads (models/generated/airbyte_incremental/default_ads_data/ads.sql)
normalization - 2021-11-08 10:09:02 INFO LineGobbler(voidCall):82 -   No matching signature for function TIMESTAMP_TRUNC for argument types: STRING, DATE_TIME_PART. Supported signatures: TIMESTAMP_TRUNC(TIMESTAMP, DATE_TIME_PART, [STRING]); TIMESTAMP_TRUNC(DATETIME, DATE_TIME_PART) at [5:16]
normalization - 2021-11-08 10:09:02 INFO LineGobbler(voidCall):82 -   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_incremental/default_ads_data/ads.sql
normalization - 2021-11-08 10:09:02 INFO LineGobbler(voidCall):82 - 
```

## Logs
Complete logs from the sync: [logs-6988-2.txt](https://github.com/airbytehq/airbyte/files/7497844/logs-6988-2.txt)

## Steps to Reproduce
1. Run sync using destination-bigquery:0.4.0
2. Upgrade to destination-bigquery:0.5.0
3. Run the sync again

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by ChristopheDuong** [comment]
The real exception is:
```
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - Exception in thread "main" java.lang.RuntimeException: com.google.cloud.bigquery.BigQueryException: Column '_airbyte_emitted_at' has type TIMESTAMP which cannot be coerced from query output type STRING at [1:107]
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.bigquery.BigQueryUtils.waitForQuery(BigQueryUtils.java:62)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.bigquery.BigQueryUtils.executeQuery(BigQueryUtils.java:44)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.bigquery.BigQueryUtils.executeQuery(BigQueryUtils.java:40)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.bigquery.BigQueryRecordConsumer.lambda$partitionIfUnpartitioned$11(BigQueryRecordConsumer.java:395)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at com.google.common.collect.Iterables$5.lambda$forEach$0(Iterables.java:704)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:406)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at com.google.common.collect.Iterables$5.forEach(Iterables.java:704)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.bigquery.BigQueryRecordConsumer.partitionIfUnpartitioned(BigQueryRecordConsumer.java:379)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.bigquery.BigQueryRecordConsumer.lambda$closeNormalBigqueryStreams$8(BigQueryRecordConsumer.java:300)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1068)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.bigquery.BigQueryRecordConsumer.closeNormalBigqueryStreams(BigQueryRecordConsumer.java:297)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.bigquery.BigQueryRecordConsumer.close(BigQueryRecordConsumer.java:169)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.close(FailureTrackingAirbyteMessageConsumer.java:62)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:152)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:128)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.bigquery.BigQueryDestination.main(BigQueryDestination.java:335)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - Caused by: com.google.cloud.bigquery.BigQueryException: Column '_airbyte_emitted_at' has type TIMESTAMP which cannot be coerced from query output type STRING at [1:107]
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:115)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.getQueryResults(HttpBigQueryRpc.java:628)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at com.google.cloud.bigquery.BigQueryImpl$35.call(BigQueryImpl.java:1347)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at com.google.cloud.bigquery.BigQueryImpl$35.call(BigQueryImpl.java:1342)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at com.google.cloud.bigquery.BigQueryImpl.getQueryResults(BigQueryImpl.java:1341)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at com.google.cloud.bigquery.BigQueryImpl.getQueryResults(BigQueryImpl.java:1325)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at com.google.cloud.bigquery.Job$1.call(Job.java:334)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at com.google.cloud.bigquery.Job$1.call(Job.java:331)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at com.google.cloud.RetryHelper.poll(RetryHelper.java:64)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at com.google.cloud.bigquery.Job.waitForQueryResults(Job.java:330)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at com.google.cloud.bigquery.Job.waitFor(Job.java:240)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.bigquery.BigQueryUtils.waitForQuery(BigQueryUtils.java:59)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	... 15 more
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - GET https://www.googleapis.com/bigquery/v2/projects/airbyte-ads-data/queries/5d436133-b8de-45ff-b488-64fad77524b4?location=US&maxResults=0&prettyPrint=false
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - {
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 -   "code" : 400,
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 -   "errors" : [ {
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 -     "domain" : "global",
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 -     "location" : "q",
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 -     "locationType" : "parameter",
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 -     "message" : "Column '_airbyte_emitted_at' has type TIMESTAMP which cannot be coerced from query output type STRING at [1:107]",
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 -     "reason" : "invalidQuery"
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 -   } ],
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 -   "message" : "Column '_airbyte_emitted_at' has type TIMESTAMP which cannot be coerced from query output type STRING at [1:107]",
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 -   "status" : "INVALID_ARGUMENT"
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - }
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:428)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1111)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.getQueryResults(HttpBigQueryRpc.java:626)
[35mdestination[0m - 2021-11-08 10:08:09 ERROR LineGobbler(voidCall):82 - 	... 30 more
```

With the recommandations to solve here: 
https://airbytehq.slack.com/archives/C01MFR03D5W/p1636126917185700?thread_ts=1635938945.039900&cid=C01MFR03D5W

- Changing the type of   _airbyte_emitted_at in your BigQuery destination table to timestamp and re-run a sync.
- Rollback the connector version to a previous version while we release a fix in destination-bigquery 0.5.x
- Reset your connection, drop the destination table and re-run the sync.

**Comment by ChristopheDuong** [comment]
Note that https://github.com/airbytehq/airbyte/pull/7669 also introduced a safety cast to the airbyte emitted at column, so in the next release, this might not throw exceptions in normalization... 

But still, the core issue to solve is in the connector

**Comment by ChristopheDuong** [comment]
`Destination-bigquery` 0.4.0 to 0.5.0 triggers a migration from a non-partitioned table to a partitioned table
it’s made using a `create table (...) as select (...) from (...)`

but it doesn’t handle the datatype change of the column… 

this test case should be slightly modified to create a table with a string column: https://github.com/airbytehq/airbyte/blob/c6edf1358881fe80082503e98b8882ebb13b8cbf[…]/integrations/destination/bigquery/BigQueryDestinationTest.java
and maybe inject some preliminary data in the table too (that would need to be migrated)
