### ISSUE TITLE
Source Facebook: job sync with key error in dict `times_job_restarted[time_range]`

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#7788]
## Enviroment
- **Airbyte version**:  0.30.20-alpha
- **OS Version / Instance**: GCP
- **Deployment**: Docker
- **Source Connector and version**: Facebook Marketing 0.2.22
- **Destination Connector and version**: Snowflake 0.3.16
- **Severity**: Very Low / Low / Medium / High / **Critical**
- **Step where error happened**: Deploy / **Sync job** / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
Facebook sync doesn't work! The sync is only using `ads_insights` incremental dedup + history with PK: `ad_id, ad_name, adset_id, age_targeting, date_start` and the table `ads_insights_platform_and_device`.

## Expected Behavior
*Tell us what should happen.*

## Logs
```
2021-11-09 08:34:34 ERROR () LineGobbler(voidCall):65 - Traceback (most recent call last):
2021-11-09 08:34:34 ERROR () LineGobbler(voidCall):65 -   File "/airbyte/integration_code/main.py", line 13, in <module>
2021-11-09 08:34:34 ERROR () LineGobbler(voidCall):65 -     launch(source, sys.argv[1:])
2021-11-09 08:34:34 WARN () DefaultAirbyteStreamFactory(internalLog):89 - '0' is not of type 'null', 'number'
2021-11-09 08:34:34 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 108, in launch
2021-11-09 08:34:34 ERROR () LineGobbler(voidCall):65 -     for message in source_entrypoint.run(parsed_args):
2021-11-09 08:34:34 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 99, in run
2021-11-09 08:34:34 ERROR () LineGobbler(voidCall):65 -     for message in generator:
2021-11-09 08:34:34 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 110, in read
2021-11-09 08:34:34 ERROR () LineGobbler(voidCall):65 -     raise e
2021-11-09 08:34:34 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 106, in read
2021-11-09 08:34:34 ERROR () LineGobbler(voidCall):65 -     internal_config=internal_config,
2021-11-09 08:34:34 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 136, in _read_stream
2021-11-09 08:34:34 ERROR () LineGobbler(voidCall):65 -     for record in record_iterator:
2021-11-09 08:34:34 ERROR () DefaultAirbyteStreamFactory(internalLog):88 - Encountered an exception while reading stream SourceFacebookMarketing
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 106, in read
    internal_config=internal_config,
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 136, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 208, in _read_full_refresh
    for record in records:
  File "/airbyte/integration_code/source_facebook_marketing/streams.py", line 333, in read_records
    result = self.wait_for_job(stream_slice["job"], stream_state=stream_state)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/airbyte/integration_code/source_facebook_marketing/streams.py", line 381, in wait_for_job
    self.times_job_restarted[time_range] += 1
KeyError: ('2021-09-15', '2021-09-21')
2021-11-09 08:34:34 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 208, in _read_full_refresh
2021-11-09 08:34:34 ERROR () LineGobbler(voidCall):65 -     for record in records:
2021-11-09 08:34:34 ERROR () LineGobbler(voidCall):65 -   File "/airbyte/integration_code/source_facebook_marketing/streams.py", line 333, in read_records
2021-11-09 08:34:34 ERROR () LineGobbler(voidCall):65 -     result = self.wait_for_job(stream_slice["job"], stream_state=stream_state)
2021-11-09 08:34:34 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
2021-11-09 08:34:34 ERROR () LineGobbler(voidCall):65 -     ret = target(*args, **kwargs)
2021-11-09 08:34:34 ERROR () LineGobbler(voidCall):65 -   File "/airbyte/integration_code/source_facebook_marketing/streams.py", line 381, in wait_for_job
2021-11-09 08:34:34 ERROR () LineGobbler(voidCall):65 -     self.times_job_restarted[time_range] += 1
2021-11-09 08:34:34 ERROR () LineGobbler(voidCall):65 - KeyError: ('2021-09-15', '2021-09-21')
2021-11-09 08:34:34 INFO () DefaultReplicationWorker(run):121 - Source thread complete.
2021-11-09 08:34:34 INFO () DefaultReplicationWorker(run):122 - Waiting for destination thread to join.
```
Complete logs: [logs-6057-0 (3).txt.zip](https://github.com/airbytehq/airbyte/files/7506389/logs-6057-0.3.txt.zip)

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by tuliren** [comment]
This issue has been fixed. However, a new one shows up: https://github.com/airbytehq/airbyte/issues/7822

**Comment by marcosmarxm** [comment]
Solved by https://github.com/airbytehq/airbyte/pull/7744
