### ISSUE TITLE
Source MongoDB error during setup the connection

### ISSUE THREAD

**Issue by WarayutPeem** [airbytehq/airbyte#7897]
## Enviroment
- **Airbyte version**:  0.30.9-alpha
- **OS Version / Instance**: Ubuntu 18.04
- **Deployment**: Docker
- **Source Connector and version**: airbyte/source-mongodb-v2 0.1.3
- **Destination Connector and version**: airbyte/destination-gcs 0.1.3
- **Severity**: Medium
- **Step where error happened**: Add destination
## Current Behavior
I have a problem with MongoDB connection.
I linked source to Destinations, Fatch Table Error.

![12418a4s4145s66a6](https://user-images.githubusercontent.com/93768994/141395600-7571d0be-13e1-43e0-8e9e-5a12110f1f8b.PNG)

## Expected Behavior
I want to fix it to make it work normally. for example I can Fatch Table.

## Logs
Full Log
[logs-f8be86a9-890b-4d3a-bed4-16b947689c34-.txt](https://github.com/airbytehq/airbyte/files/7524347/logs-f8be86a9-890b-4d3a-bed4-16b947689c34-.txt)

<details>
<summary>LOG</summary> 

```

2021-11-12 01:56:18 ERROR () LineGobbler(voidCall):65 - 	at com.mongodb.internal.operation.FindOperation$1.call(FindOperation.java:663)
2021-11-12 01:56:18 ERROR () LineGobbler(voidCall):65 - 	at com.mongodb.internal.operation.FindOperation$1.call(FindOperation.java:653)
2021-11-12 01:56:18 ERROR () LineGobbler(voidCall):65 - 	at com.mongodb.internal.operation.OperationHelper.withReadConnectionSource(OperationHelper.java:583)
2021-11-12 01:56:18 ERROR () LineGobbler(voidCall):65 - 	at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:653)
2021-11-12 01:56:18 ERROR () LineGobbler(voidCall):65 - 	at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:81)
2021-11-12 01:56:18 ERROR () LineGobbler(voidCall):65 - 	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:184)
2021-11-12 01:56:18 ERROR () LineGobbler(voidCall):65 - 	at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:135)
2021-11-12 01:56:18 ERROR () LineGobbler(voidCall):65 - 	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:92)
2021-11-12 01:56:18 ERROR () LineGobbler(voidCall):65 - 	at io.airbyte.db.mongodb.MongoUtils.getUniqueFields(MongoUtils.java:178)
2021-11-12 01:56:18 ERROR () LineGobbler(voidCall):65 - 	at io.airbyte.integrations.source.mongodb.MongoDbSource.discoverInternal(MongoDbSource.java:119)
2021-11-12 01:56:18 ERROR () LineGobbler(voidCall):65 - 	at io.airbyte.integrations.source.mongodb.MongoDbSource.discoverInternal(MongoDbSource.java:41)
2021-11-12 01:56:18 ERROR () LineGobbler(voidCall):65 - 	at io.airbyte.integrations.source.relationaldb.AbstractDbSource.discoverWithoutSystemTables(AbstractDbSource.java:129)
2021-11-12 01:56:18 ERROR () LineGobbler(voidCall):65 - 	at io.airbyte.integrations.source.relationaldb.AbstractDbSource.getTables(AbstractDbSource.java:319)
2021-11-12 01:56:18 ERROR () LineGobbler(voidCall):65 - 	at io.airbyte.integrations.source.relationaldb.AbstractDbSource.discover(AbstractDbSource.java:80)
2021-11-12 01:56:18 ERROR () LineGobbler(voidCall):65 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:108)
2021-11-12 01:56:18 ERROR () LineGobbler(voidCall):65 - 	at io.airbyte.integrations.source.mongodb.MongoDbSource.main(MongoDbSource.java:65)

```

</details>

## Steps to Reproduce
1. Create Source Mongo DB
2. Create Destination GCS
3. Pick  Source MongoDB
4. Add Destination
5. Pick Destination GCS
6. Wait a moment
7. Error, Failed to fetch schema

**Comment by marcosmarxm** [comment]
[slack convo](https://airbytehq.slack.com/archives/C01MFR03D5W/p1636617320418000)

**Comment by WarayutPeem** [comment]
I'm still waiting for an answer.

**Comment by sherifnada** [comment]
@WarayutPeem we're looking into this issue this week and will have an update by EOW

**Comment by sherifnada** [comment]
assigning to @alexandr-shegeda for triage

**Comment by andriikorotkov** [comment]
@WarayutPeem, could you change the version of the mongodb source to the latest? 0.1.8 should work stably.

**Comment by WarayutPeem** [comment]
@andriikorotkov , I changed the version of the mongodb source to 0.1.8 and tested it still got the same error.
![image](https://user-images.githubusercontent.com/93768994/144538012-e9214ec1-a51b-4fa4-ad4a-b64f10809a29.png)
![image](https://user-images.githubusercontent.com/93768994/144538036-04b7743a-9567-46dd-a51f-638650bff32c.png)

**Comment by WarayutPeem** [comment]
@andriikorotkov,  log file
[logs-efdf7887-ea84-4db2-8392-0b0f49c6a6ac-.txt](https://github.com/airbytehq/airbyte/files/7646548/logs-efdf7887-ea84-4db2-8392-0b0f49c6a6ac-.txt)
e

**Comment by andriikorotkov** [comment]
@WarayutPeem, Can you please tell me how many collections you are trying to work with and what is the approximate size of each of them? And also, I want to ask you for the structure of the collection document (with data types) so that I can create a test and reproduce this bug.

**Comment by WarayutPeem** [comment]
@andriikorotkov, There are 18 collections in MongoDB. The minimum size is 2.0 KB and the maximum is 193.9 MB.



in the structure of the collection document, example in picture
![image](https://user-images.githubusercontent.com/93768994/144751886-e16c6219-4a75-49d4-a702-e847cf82a19e.png)
![image](https://user-images.githubusercontent.com/93768994/144751900-26cb017b-697d-475a-a263-f29c4c62da0d.png)
![image](https://user-images.githubusercontent.com/93768994/144751917-e01f425e-17a0-486b-86fa-4574239fe13e.png)
![image](https://user-images.githubusercontent.com/93768994/144751928-c4999da4-2835-4fbc-897f-13a18466ef90.png)



"MongoDb instance type" do you use?,   I don't know. I'll just ask the responsible team to bring the information to you.

**Comment by andriikorotkov** [comment]
@WarayutPeem, we have released a new version of mongo source connection - 0.1.19. I ran tests on collections with the structure and data types you provided above. The number of documents in the collection is from 100 to 200 thousand. All tests passed successfully. Could you try to connect again with the new version of the connector and report the results?
