### ISSUE TITLE
CockroachdB error with https://go.crdb.dev/issue-v/40195/v21.1 

### ISSUE THREAD

**Issue by carlallen** [airbytehq/airbyte#7933]
## Enviroment
- **Airbyte version**:  0.30.36-alpha
- **OS Version / Instance**: Ubuntu on EC2
- **Deployment**: Docker
- **Source Connector and version**: Cockroachdb 0.1.3 (connected to Cockroachdb v21.1.10)
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
- **Severity**: Very Low / Low / Medium / High / Critical
- **Step where error happened**: Sync job

## Current Behavior
*Tell us what happens.*

It throws an error

## Expected Behavior
It doesn't throw an error

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - Exception in thread "main" java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.db.jdbc.JdbcSourceOperations$1.tryAdvance(JdbcSourceOperations.java:55)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.commons.util.LazyAutoCloseableIterator.computeNext(LazyAutoCloseableIterator.java:42)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.source.relationaldb.StateDecoratingIterator.computeNext(StateDecoratingIterator.java:48)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.source.relationaldb.StateDecoratingIterator.computeNext(StateDecoratingIterator.java:18)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.commons.util.CompositeIterator.computeNext(CompositeIterator.java:63)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:119)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.source.cockroachdb.CockroachDbSource.main(CockroachDbSource.java:87)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2674)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2364)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:354)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:484)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:404)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:162)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.jdbc.TypeInfoCache.getPGType(TypeInfoCache.java:509)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.jdbc.PgResultSetMetaData.getPGType(PgResultSetMetaData.java:407)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.jdbc.PgResultSetMetaData.getColumnTypeName(PgResultSetMetaData.java:325)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.source.cockroachdb.CockroachJdbcSourceOperations.putCockroachSpecialDataType(CockroachJdbcSourceOperations.java:54)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.source.cockroachdb.CockroachJdbcSourceOperations.rowToJson(CockroachJdbcSourceOperations.java:47)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.db.jdbc.JdbcSourceOperations$1.tryAdvance(JdbcSourceOperations.java:52)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	... 31 more
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - Caused by: org.postgresql.util.PSQLException: ERROR: unimplemented: multiple active portals not supported
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 -   Hint: You have attempted to use a feature that is not yet implemented.
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - See: https://go.crdb.dev/issue-v/40195/v21.1
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2674)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2364)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:354)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:484)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:404)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:162)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.jdbc.TypeInfoCache.getPGType(TypeInfoCache.java:509)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.jdbc.PgResultSet.initSqlType(PgResultSet.java:2993)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.jdbc.PgResultSet.getSQLType(PgResultSet.java:2982)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.jdbc.PgResultSet.internalGetObject(PgResultSet.java:187)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.jdbc.PgResultSet.getObject(PgResultSet.java:2843)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.apache.commons.dbcp2.DelegatingResultSet.getObject(DelegatingResultSet.java:733)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.apache.commons.dbcp2.DelegatingResultSet.getObject(DelegatingResultSet.java:733)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.source.cockroachdb.CockroachJdbcSourceOperations.rowToJson(CockroachJdbcSourceOperations.java:42)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	... 32 more

```

</details>

## Steps to Reproduce
1. Create a CockroachDB (v21.1.10) source
2. Use incremental | Deduped
3. Failures occur

## Are you willing to submit a PR?

I'm not a huge java person, but I guess I could try.

**Comment by lshrinivas** [comment]
I encountered this same error with Source connector: Cockroachdb 0.1.5 (connected to Cockroachdb v21.1). This seems to only happen for tables that have more than ~1000 rows.

**Comment by lshrinivas** [comment]
@igrankova I have opened a PR for this issue: https://github.com/airbytehq/airbyte/pull/10235. This is my first time contributing to Airbyte, so would appreciate any pointers to things I've missed.

**Comment by igrankova** [comment]
@misteryeo, I've linked the pull request, can you help @lshrinivas with the next steps?
