### ISSUE TITLE
Error is swallowed for check_connector values

### ISSUE THREAD

**Issue by jamakase** [airbytehq/airbyte#7990]
When there is some error on the backend during `check_connection` during source or destination creation and it is not able to return a proper response, UI is swallowing the error instead of trying to handle it.

**Comment by sherifnada** [comment]
@lmossman @timroes do you know if this is still happening? if you're not sure, just close it and it'll come up again

**Comment by lmossman** [comment]
I'm not totally sure. I know that we properly surface responses from check_connection to the UI, but I'm not entirely sure what happens if the check_connection command actually fails to run successfully

**Comment by dmvianna** [comment]
```
Mar 07 23:35:07 ingestion-dev 3r3b77l06h412yhzks39i3ydqvnr1vr0-execStart[3467]: airbyte-server                    | 2024-03-07 23:35:07 ERROR i.a.c.l.Exceptions(swallow):65 - Swallowed error.
Mar 07 23:35:07 ingestion-dev 3r3b77l06h412yhzks39i3ydqvnr1vr0-execStart[3467]: airbyte-server                    | java.lang.NullPointerException: Cannot invoke "io.airbyte.config.Metadata.getAdditionalProperties()" because the return value of "io.airbyte.config.FailureReason.getMetadata()" is null

```
Does that mean it is still there?

**Comment by talha-naeem1** [comment]
Voting to reopen this issue, as we are also getting the same issue.
Airbyte server logs:
```
io.temporal.internal.activity.ActivityTaskExecutors$BaseActivityTaskExecutor.execute(ActivityTaskExecutors.java:95) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.activity.ActivityTaskHandlerImpl.handle(ActivityTaskHandlerImpl.java:92) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handleActivity(ActivityWorker.java:241) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:206) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:179) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93) ~[temporal-sdk-1.17.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: io.temporal.serviceclient.CheckedExceptionWrapper: io.airbyte.workers.exception.WorkerException: Unexpected error while getting checking connection.
	at io.temporal.serviceclient.CheckedExceptionWrapper.wrap(CheckedExceptionWrapper.java:57) ~[temporal-serviceclient-1.17.0.jar:?]
	at io.temporal.internal.sync.WorkflowInternal.wrap(WorkflowInternal.java:461) ~[temporal-sdk-1.17.0.jar:?]
	at io.temporal.activity.Activity.wrap(Activity.java:52) ~[temporal-sdk-1.17.0.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:139) ~[io.airbyte-airbyte-workers-0.50.33.jar:?]
	at io.airbyte.workers.temporal.check.connection.CheckConnectionActivityImpl.lambda$runWithJobOutput$1(CheckConnectionActivityImpl.java:136) ~[io.airbyte-airbyte-workers-0.50.33.jar:?]
	at io.airbyte.commons.temporal.TemporalUtils.withBackgroundHeartbeat(TemporalUtils.java:314) ~[io.airbyte-airbyte-commons-temporal-0.50.33.jar:?]
	... 14 more
```
