### ISSUE TITLE
source-paypal-transaction fails with 400 Client Error: Bad Request

### ISSUE THREAD

**Issue by Dock1100** [airbytehq/airbyte#8012]
Hi, got 400 errors when trying to import data from paypal. Any ideas on how to debug it?

## Enviroment
- **Airbyte version**:  0.32.0-alpha
- **OS Version / Instance**: GCP n2. (`uname -a` `Linux airbyte-test 4.19.0-18-cloud-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux`)
- **Deployment**: docker-compose
- **Source Connector and version**: source-paypal-transaction 0.1.2
- **Destination Connector and version**: destination-bigquery	0.5.0
- **Severity**: Medium
- **Step where error happened**: Sync job

## Current Behavior
Added new source, the test works without issues.
Once I set up connection, sync job fails with
```
2021-11-16 15:15:05 ERROR () DefaultAirbyteStreamFactory(internalLog):95 - Encountered an exception while reading stream SourcePaypalTransaction
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 106, in read
    internal_config=internal_config,
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 136, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 202, in _read_full_refresh
    slices = stream_instance.stream_slices(sync_mode=SyncMode.full_refresh, cursor_field=configured_stream.cursor_field)
  File "/airbyte/integration_code/source_paypal_transaction/source.py", line 204, in stream_slices
    self.last_refreshed_datetime = self.get_last_refreshed_datetime(sync_mode)
  File "/airbyte/integration_code/source_paypal_transaction/source.py", line 191, in get_last_refreshed_datetime
    list(paypal_stream.read_records(sync_mode=sync_mode, stream_slice=stream_slice))
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 351, in read_records
    response = self._send_request(request, request_kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 318, in _send_request
    return backoff_handler(user_backoff_handler)(request, request_kwargs)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 284, in _send
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api-m.sandbox.paypal.com/v1/reporting/balances?as_of_time=2021-01-01T00%3A00%3A00%2B00%3A00
```

## Expected Behavior
Initial sync imports data to destination without issues

## Logs
Full log
[logs-24-2.txt](https://github.com/airbytehq/airbyte/files/7547674/logs-24-2.txt)

## Steps to Reproduce
1. Setup source for sandbox paypal
2. Setup any destination
3. Setup connection

**Comment by bazarnov** [comment]
The sandbox of PayPal is continuously in development, therefore the bugs are possible. The issue was reproduced on our sandbox as well. But on prod (Live) this issue should not appear.

@Dock1100 have you tried to use the Live instead of Sandbox for your data?
