### ISSUE TITLE
🐛 Source Appstore:  Message contained record from a stream that was not in the catalog.

### ISSUE THREAD

**Issue by dbhagen** [airbytehq/airbyte#8165]
## Enviroment
- **Airbyte version**:  0.32.5-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker-Compose
- **Source Connector and version**: airbyte/source-appstore-singer 0.2.4
- **Destination Connector and version**: airbyte/destination-postgres 0.3.12
- **Severity**: Medium
- **Step where error happened**: Sync job

## Current Behavior
There is an error on the sync job and fails.

## Expected Behavior
The sync job completes

## Logs
<details>
<summary>LOG</summary> 

```

2021-11-22 02:24:21 INFO () WorkerRun(call):49 - Executing worker wrapper. Airbyte version: 0.32.5-alpha
2021-11-22 02:24:21 INFO () TemporalAttemptExecution(get):116 - Executing worker wrapper. Airbyte version: 0.32.5-alpha
2021-11-22 02:24:21 WARN () Databases(createPostgresDatabaseWithRetry):41 - Waiting for database to become available...
2021-11-22 02:24:21 INFO () JobsDatabaseInstance(lambda$static$2):25 - Testing if jobs database is ready...
2021-11-22 02:24:21 INFO () Databases(createPostgresDatabaseWithRetry):58 - Database available!
2021-11-22 02:24:21 INFO () DefaultReplicationWorker(run):99 - start sync worker. job id: 88 attempt id: 2
2021-11-22 02:24:21 INFO () DefaultReplicationWorker(run):108 - configured sync modes: {}
2021-11-22 02:24:21 INFO () DefaultAirbyteDestination(start):64 - Running destination...
2021-11-22 02:24:21 INFO () LineGobbler(voidCall):82 - Checking if airbyte/destination-postgres:0.3.12 exists...
2021-11-22 02:24:21 INFO () LineGobbler(voidCall):82 - airbyte/destination-postgres:0.3.12 was found locally.
2021-11-22 02:24:21 INFO () DockerProcessFactory(create):127 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/88/2 --network host --log-driver none airbyte/destination-postgres:0.3.12 write --config destination_config.json --catalog destination_catalog.json
2021-11-22 02:24:21 INFO () LineGobbler(voidCall):82 - Checking if airbyte/source-appstore-singer:0.2.4 exists...
2021-11-22 02:24:21 INFO () LineGobbler(voidCall):82 - airbyte/source-appstore-singer:0.2.4 was found locally.
2021-11-22 02:24:21 INFO () DockerProcessFactory(create):127 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/88/2 --network host --log-driver none airbyte/source-appstore-singer:0.2.4 read --config source_config.json --catalog source_catalog.json --state input_state.json
2021-11-22 02:24:21 INFO () DefaultReplicationWorker(lambda$getDestinationOutputRunnable$3):243 - Destination output thread started.
2021-11-22 02:24:21 INFO () DefaultReplicationWorker(run):136 - Waiting for source thread to join.
2021-11-22 02:24:21 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):207 - Replication thread started.
[35mdestination[0m - 2021-11-22 02:24:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-22 02:24:23 [32mINFO[m i.a.i.d.p.PostgresDestination(main):69 - {} - starting destination: class io.airbyte.integrations.destination.postgres.PostgresDestination
[35mdestination[0m - 2021-11-22 02:24:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-22 02:24:23 [32mINFO[m i.a.i.b.IntegrationRunner(run):76 - {} - Running integration: io.airbyte.integrations.base.ssh.SshWrappedDestination
[35mdestination[0m - 2021-11-22 02:24:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-22 02:24:23 [32mINFO[m i.a.i.b.IntegrationCliParser(parseOptions):118 - {} - integration args: {catalog=destination_catalog.json, write=null, config=destination_config.json}
[35mdestination[0m - 2021-11-22 02:24:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-22 02:24:23 [32mINFO[m i.a.i.b.IntegrationRunner(run):80 - {} - Command: WRITE
[35mdestination[0m - 2021-11-22 02:24:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-22 02:24:23 [32mINFO[m i.a.i.b.IntegrationRunner(run):81 - {} - Integration config: IntegrationConfig{command=WRITE, configPath='destination_config.json', catalogPath='destination_catalog.json', statePath='null'}
[35mdestination[0m - 2021-11-22 02:24:24 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-22 02:24:24 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
[35mdestination[0m - 2021-11-22 02:24:24 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-22 02:24:24 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword examples - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
[35mdestination[0m - 2021-11-22 02:24:24 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-22 02:24:24 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
[35mdestination[0m - 2021-11-22 02:24:24 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-22 02:24:24 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword multiline - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
[35mdestination[0m - 2021-11-22 02:24:24 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-22 02:24:24 [32mINFO[m i.a.i.b.s.SshTunnel(getInstance):170 - {} - Starting connection with method: NO_TUNNEL
[35mdestination[0m - 2021-11-22 02:24:24 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-22 02:24:24 [32mINFO[m i.a.i.d.b.BufferedStreamConsumer(startTracked):124 - {} - class io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer started.
[35mdestination[0m - 2021-11-22 02:24:24 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-22 02:24:24 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):121 - {} - Preparing tmp tables in destination started for 0 streams
[35mdestination[0m - 2021-11-22 02:24:24 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-22 02:24:24 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):131 - {} - Preparing tables in destination completed.
[34msource[0m - 2021-11-22 02:24:27 ERROR () DefaultAirbyteStreamFactory(internalLog):95 - Invalid vendor number specified. Try again.
[34msource[0m - 2021-11-22 02:24:27 ERROR () DefaultAirbyteStreamFactory(internalLog):95 - Invalid vendor number specified. Try again.
[34msource[0m - 2021-11-22 02:24:27 ERROR () DefaultAirbyteStreamFactory(internalLog):95 - Invalid vendor number specified. Try again.
[34msource[0m - 2021-11-22 02:24:27 ERROR () DefaultAirbyteStreamFactory(internalLog):95 - Invalid vendor number specified. Try again.
[34msource[0m - 2021-11-22 02:24:27 ERROR () DefaultAirbyteStreamFactory(internalLog):95 - Invalid vendor number specified. Try again.
[34msource[0m - 2021-11-22 02:24:27 ERROR () DefaultAirbyteStreamFactory(internalLog):95 - Invalid vendor number specified. Try again.
[34msource[0m - 2021-11-22 02:24:27 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Requesting Appstore data for: sales_report on 2020-12-01
[35mdestination[0m - 2021-11-22 02:24:27 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-22 02:24:27 [33mWARN[m i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):58 - {} - Airbyte message consumer: failed.
[35mdestination[0m - 2021-11-22 02:24:27 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-22 02:24:27 [1;31mERROR[m i.a.i.d.b.BufferedStreamConsumer(close):197 - {} - executing on failed close procedure.
[35mdestination[0m - 2021-11-22 02:24:27 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-22 02:24:27 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):183 - {} - Cleaning tmp tables in destination started for 0 streams
[35mdestination[0m - 2021-11-22 02:24:27 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-22 02:24:27 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):192 - {} - Cleaning tmp tables in destination completed.
[35mdestination[0m - 2021-11-22 02:24:27 ERROR () LineGobbler(voidCall):82 - Exception in thread "main" java.lang.IllegalArgumentException: Message contained record from a stream that was not in the catalog. 
[35mdestination[0m - 2021-11-22 02:24:27 ERROR () LineGobbler(voidCall):82 - catalog: {"streams":[]} , 
[35mdestination[0m - 2021-11-22 02:24:27 ERROR () LineGobbler(voidCall):82 - message: {"type":"RECORD","record":{"stream":"test-appstore-sales_report","data":{"provider":"APPLE","provider_country":"US","sku":"TEST_IOS","developer":"Test Dev","title":"Test Title","version":"1.2.0","product_type_identifier":"1F","units":15,"developer_proceeds":"0.00","begin_date":"12/01/2020","end_date":"12/01/2020","customer_currency":"EUR","country_code":"FR","currency_of_proceeds":"","apple_identifier":"123456","customer_price":"0.00","promo_code":"","parent_identifier":"","subscription":"","period":"","category":"Games","cmb":"","device":"iPad","supported_platforms":"iOS","proceeds_reason":"","preserved_pricing":"","client":"","order_type":"","_line_id":1,"_time_extracted":"2021-11-22T02:24:27.000000Z","_api_report_date":"2020-12-01"},"emitted_at":1637547867000}}
[35mdestination[0m - 2021-11-22 02:24:27 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.throwUnrecognizedStream(BufferedStreamConsumer.java:184)
[35mdestination[0m - 2021-11-22 02:24:27 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.acceptTracked(BufferedStreamConsumer.java:137)
[35mdestination[0m - 2021-11-22 02:24:27 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.accept(FailureTrackingAirbyteMessageConsumer.java:46)
[35mdestination[0m - 2021-11-22 02:24:27 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.base.AirbyteMessageConsumer$1.accept(AirbyteMessageConsumer.java:53)
[35mdestination[0m - 2021-11-22 02:24:27 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:147)
[35mdestination[0m - 2021-11-22 02:24:27 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:128)
[35mdestination[0m - 2021-11-22 02:24:27 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.postgres.PostgresDestination.main(PostgresDestination.java:70)
2021-11-22 02:25:27 WARN () LineGobbler(voidCall):86 - airbyte-source gobbler IOException: Stream closed. Typically happens when cancelling a job.
2021-11-22 02:25:27 ERROR () DefaultReplicationWorker(run):145 - Sync worker failed.
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.io.IOException: Stream closed
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:137) ~[io.airbyte-airbyte-workers-0.32.5-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:49) ~[io.airbyte-airbyte-workers-0.32.5-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:167) ~[io.airbyte-airbyte-workers-0.32.5-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
	Suppressed: io.airbyte.workers.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteSource.close(DefaultAirbyteSource.java:117) ~[io.airbyte-airbyte-workers-0.32.5-alpha.jar:?]
		at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:118) ~[io.airbyte-airbyte-workers-0.32.5-alpha.jar:?]
		at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:49) ~[io.airbyte-airbyte-workers-0.32.5-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:167) ~[io.airbyte-airbyte-workers-0.32.5-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:832) [?:?]
	Suppressed: java.io.IOException: Stream closed
		at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:442) ~[?:?]
		at java.io.OutputStream.write(OutputStream.java:162) ~[?:?]
		at java.io.BufferedOutputStream.write(BufferedOutputStream.java:123) ~[?:?]
		at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:242) ~[?:?]
		at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:312) ~[?:?]
		at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:290) ~[?:?]
		at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:131) ~[?:?]
		at java.io.OutputStreamWriter.write(OutputStreamWriter.java:208) ~[?:?]
		at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:120) ~[?:?]
		at java.io.BufferedWriter.flush(BufferedWriter.java:256) ~[?:?]
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.notifyEndOfStream(DefaultAirbyteDestination.java:93) ~[io.airbyte-airbyte-workers-0.32.5-alpha.jar:?]
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.close(DefaultAirbyteDestination.java:106) ~[io.airbyte-airbyte-workers-0.32.5-alpha.jar:?]
		at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:118) ~[io.airbyte-airbyte-workers-0.32.5-alpha.jar:?]
		at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:49) ~[io.airbyte-airbyte-workers-0.32.5-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:167) ~[io.airbyte-airbyte-workers-0.32.5-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.RuntimeException: java.io.IOException: Stream closed
	at io.airbyte.workers.DefaultReplicationWorker.lambda$getReplicationRunnable$2(DefaultReplicationWorker.java:231) ~[io.airbyte-airbyte-workers-0.32.5-alpha.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	... 1 more
Caused by: java.io.IOException: Stream closed
	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:442) ~[?:?]
	at java.io.OutputStream.write(OutputStream.java:162) ~[?:?]
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:123) ~[?:?]
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:242) ~[?:?]
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:312) ~[?:?]
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:290) ~[?:?]
	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:131) ~[?:?]
	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:208) ~[?:?]
	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:120) ~[?:?]
	at java.io.BufferedWriter.write(BufferedWriter.java:233) ~[?:?]
	at java.io.Writer.write(Writer.java:249) ~[?:?]
	at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.accept(DefaultAirbyteDestination.java:85) ~[io.airbyte-airbyte-workers-0.32.5-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.lambda$getReplicationRunnable$2(DefaultReplicationWorker.java:216) ~[io.airbyte-airbyte-workers-0.32.5-alpha.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	... 1 more
2021-11-22 02:25:27 INFO () DefaultReplicationWorker(run):169 - sync summary: io.airbyte.config.ReplicationAttemptSummary@189841d9[status=failed,recordsSynced=191,bytesSynced=136514,startTime=1637547861762,endTime=1637547927544]
2021-11-22 02:25:27 INFO () DefaultReplicationWorker(run):178 - Source did not output any state messages
2021-11-22 02:25:27 WARN () DefaultReplicationWorker(run):186 - State capture: No new state, falling back on input state: io.airbyte.config.State@308469e9[state={}]
2021-11-22 02:25:27 INFO () TemporalAttemptExecution(get):137 - Stopping cancellation check scheduling...
2021-11-22 02:25:27 INFO () ReplicationActivityImpl(replicate):121 - sync summary: io.airbyte.config.StandardSyncOutput@497e0d79[standardSyncSummary=io.airbyte.config.StandardSyncSummary@546da90b[status=failed,recordsSynced=191,bytesSynced=136514,startTime=1637547861762,endTime=1637547927544],state=io.airbyte.config.State@308469e9[state={}],outputCatalog=io.airbyte.protocol.models.ConfiguredAirbyteCatalog@5fb808e2[streams=[],additionalProperties={}]]
2021-11-22 02:25:27 INFO () ConfigRepository(updateConnectionState):518 - Updating connection 9a2ccf27-4a12-4bc7-b26b-0752332a24aa state: io.airbyte.config.State@742cfdea[state={}]
2021-11-22 02:25:27 INFO () DatabaseConfigPersistence(updateConfigRecord):273 - Updating STANDARD_SYNC_STATE record 9a2ccf27-4a12-4bc7-b26b-0752332a24aa
2021-11-22 02:25:27 INFO () TemporalAttemptExecution(get):116 - Executing worker wrapper. Airbyte version: 0.32.5-alpha
2021-11-22 02:25:27 WARN () Databases(createPostgresDatabaseWithRetry):41 - Waiting for database to become available...
2021-11-22 02:25:27 INFO () JobsDatabaseInstance(lambda$static$2):25 - Testing if jobs database is ready...
2021-11-22 02:25:27 INFO () Databases(createPostgresDatabaseWithRetry):58 - Database available!
2021-11-22 02:25:27 INFO () DefaultNormalizationWorker(run):46 - Running normalization.
2021-11-22 02:25:27 INFO () DefaultNormalizationRunner(runProcess):114 - Running with normalization version: airbyte/normalization:0.1.60
2021-11-22 02:25:27 INFO () LineGobbler(voidCall):82 - Checking if airbyte/normalization:0.1.60 exists...
2021-11-22 02:25:27 INFO () DockerProcessFactory(create):127 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/88/2/normalize --network host --log-driver none airbyte/normalization:0.1.60 run --integration-type postgres --config destination_config.json --catalog destination_catalog.json
2021-11-22 02:25:27 INFO () LineGobbler(voidCall):82 - airbyte/normalization:0.1.60 was found locally.
[32mnormalization[0m - 2021-11-22 02:25:28 INFO () LineGobbler(voidCall):82 - Running: transform-config --config destination_config.json --integration-type postgres --out /data/88/2/normalize
[32mnormalization[0m - 2021-11-22 02:25:28 INFO () LineGobbler(voidCall):82 - Namespace(config='destination_config.json', integration_type=<DestinationType.postgres: 'postgres'>, out='/data/88/2/normalize')
[32mnormalization[0m - 2021-11-22 02:25:28 INFO () LineGobbler(voidCall):82 - transform_postgres
[32mnormalization[0m - 2021-11-22 02:25:28 INFO () LineGobbler(voidCall):82 - Running: transform-catalog --integration-type postgres --profile-config-dir /data/88/2/normalize --catalog destination_catalog.json --out /data/88/2/normalize/models/generated/ --json-column _airbyte_data
[32mnormalization[0m - 2021-11-22 02:25:28 INFO () LineGobbler(voidCall):82 - Processing destination_catalog.json...
[32mnormalization[0m - 2021-11-22 02:25:28 INFO () LineGobbler(voidCall):82 - detected no config file for ssh, assuming ssh is off.
[32mnormalization[0m - 2021-11-22 02:25:31 INFO () LineGobbler(voidCall):82 - Running with dbt=0.21.0
[32mnormalization[0m - 2021-11-22 02:25:31 INFO () LineGobbler(voidCall):82 - Unable to do partial parsing because ../build/partial_parse.msgpack not found
[32mnormalization[0m - 2021-11-22 02:25:32 INFO () LineGobbler(voidCall):82 - [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[32mnormalization[0m - 2021-11-22 02:25:32 INFO () LineGobbler(voidCall):82 - There are 5 unused configuration paths:
[32mnormalization[0m - 2021-11-22 02:25:32 INFO () LineGobbler(voidCall):82 - - models.airbyte_utils.generated.airbyte_views
[32mnormalization[0m - 2021-11-22 02:25:32 INFO () LineGobbler(voidCall):82 - - models.airbyte_utils.generated.airbyte_tables
[32mnormalization[0m - 2021-11-22 02:25:32 INFO () LineGobbler(voidCall):82 - - models.airbyte_utils.generated.airbyte_ctes
[32mnormalization[0m - 2021-11-22 02:25:32 INFO () LineGobbler(voidCall):82 - - models.airbyte_utils
[32mnormalization[0m - 2021-11-22 02:25:32 INFO () LineGobbler(voidCall):82 - - models.airbyte_utils.generated.airbyte_incremental
[32mnormalization[0m - 2021-11-22 02:25:32 INFO () LineGobbler(voidCall):82 - 
[32mnormalization[0m - 2021-11-22 02:25:32 INFO () LineGobbler(voidCall):82 - Found 0 models, 0 tests, 0 snapshots, 0 analyses, 478 macros, 0 operations, 0 seed files, 0 sources, 0 exposures
[32mnormalization[0m - 2021-11-22 02:25:32 INFO () LineGobbler(voidCall):82 - 
[32mnormalization[0m - 2021-11-22 02:25:32 INFO () LineGobbler(voidCall):82 - WARNING: Nothing to do. Try checking your model configs and model specification args
2021-11-22 02:25:33 INFO () DefaultNormalizationWorker(run):69 - Normalization executed in 5 seconds.
2021-11-22 02:25:33 INFO () TemporalAttemptExecution(get):137 - Stopping cancellation check scheduling...
```

</details>

## Steps to Reproduce
1. Configure source connector as Appstore.
2. Configure destination connector as Postgres
3. Initialize sync.

## Are you willing to submit a PR?
I would love to help, if I can be pointed in the right direction.

**Comment by alafanechere** [comment]
The source indeed returns a message from a stream `test-appstore-sales_report` which is not part of the destination catalog. @dbhagen does your problem persists when re-creating your connection?

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by marcosmarxm** [comment]
The App Store connector has been [archived](https://docs.airbyte.com/integrations/sources/appstore#deprecation-notice) and won't get updates in the future. We're closing this issue to focus on features and connectors in our roadmap. Thanks for understanding! 🚀
