### ISSUE TITLE
Error in Kafka source when connecting using SASL_SSL protocol 

### ISSUE THREAD

**Issue by cereusperuv** [airbytehq/airbyte#8230]
## Enviroment
- **Airbyte version**:  0.32.5-alpha
- **OS Version / Instance**: -
- **Deployment**: Docker
- **Source Connector and version**: Kafka 0.1.0
- **Destination Connector and version**: - 
- **Severity**: Critical
- **Step where error happened**: Sync job / Setup new connection

## Current Behavior
Cannot connect to Kafka on Confluent with security protocol 'SASL_SSL'. I think the problem is line 89 (& 90) in `io.airbyte.integrations.source.kafka.KafkaSourceConfig.propertiesByProtocol()`, where `config.get()` should be `protocolConfig.get()`.

```
79  private Map<String, Object> propertiesByProtocol(final JsonNode config) {
80    final JsonNode protocolConfig = config.get("protocol");
81    LOGGER.info("Kafka protocol config: {}", protocolConfig.toString());
82    final KafkaProtocol protocol = KafkaProtocol.valueOf(protocolConfig.get("security_protocol").asText().toUpperCase());
83    final ImmutableMap.Builder<String, Object> builder = ImmutableMap.<String, Object>builder()
84        .put(CommonClientConfigs.SECURITY_PROTOCOL_CONFIG, protocol.toString());
85
86    switch (protocol) {
87      case PLAINTEXT -> {}
88      case SASL_SSL, SASL_PLAINTEXT -> {
89        builder.put(SaslConfigs.SASL_JAAS_CONFIG, config.get("sasl_jaas_config").asText());
90        builder.put(SaslConfigs.SASL_MECHANISM, config.get("sasl_mechanism").asText());
91      }
92      default -> throw new RuntimeException("Unexpected Kafka protocol: " + Jsons.serialize(protocol));
93    }
94
95    return builder.build();
96  }
```

## Expected Behavior

Should connect.

## Logs

```
2021-11-24 12:59:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 12:59:34 INFO i.a.i.s.k.KafkaSourceConfig(propertiesByProtocol):81 - {} - Kafka protocol config: {"sasl_mechanism":"GSSAPI","sasl_jaas_config":"org.apache.kafka.common.security.plain.PlainLoginModule required username=***** password=*****","security_protocol":"SASL_SSL"}
2021-11-24 12:59:34 ERROR () LineGobbler(voidCall):82 - Exception in thread "main" java.lang.NullPointerException
2021-11-24 12:59:34 ERROR () LineGobbler(voidCall):82 - at io.airbyte.integrations.source.kafka.KafkaSourceConfig.propertiesByProtocol(KafkaSourceConfig.java:89)
2021-11-24 12:59:34 ERROR () LineGobbler(voidCall):82 - at io.airbyte.integrations.source.kafka.KafkaSourceConfig.buildKafkaConsumer(KafkaSourceConfig.java:54)
2021-11-24 12:59:34 ERROR () LineGobbler(voidCall):82 - at io.airbyte.integrations.source.kafka.KafkaSourceConfig.getConsumer(KafkaSourceConfig.java:102)
2021-11-24 12:59:34 ERROR () LineGobbler(voidCall):82 - at io.airbyte.integrations.source.kafka.KafkaSourceConfig.getTopicsToSubscribe(KafkaSourceConfig.java:132)
2021-11-24 12:59:34 ERROR () LineGobbler(voidCall):82 - at io.airbyte.integrations.source.kafka.KafkaSource.discover(KafkaSource.java:58)
2021-11-24 12:59:34 ERROR () LineGobbler(voidCall):82 - at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:108)
2021-11-24 12:59:34 ERROR () LineGobbler(voidCall):82 - at io.airbyte.integrations.source.kafka.KafkaSource.main(KafkaSource.java:121)
```

## Steps to Reproduce
1. Connect airbyte to Kafka topic with secure connection protocol SASL_SSL

## Are you willing to submit a PR?

Not at this point.

**Comment by cereusperuv** [comment]
A further note: When the above code snippet is changed as decsribed, there are further issues when trying to connect using SASL_SSL. Related to #8220

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 365 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.
