### ISSUE TITLE
Import Config v0.29.21-alpha failed with ` AccessExclusiveLock on relation 16701 of database 16385; blocked by process 104.`

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#8471]
## Environment
- **Airbyte version**:  0.29.21-alpha
- **OS Version / Instance**: GCP => local 16Gb / 300Gb reserved to Docker.
- **Deployment**: Docker
- **Source Connector and version**: N/A
- **Destination Connector and version**: N/A
- **Severity**: Very Low / **Low** / Medium / High / Critical
- **Step where error happened**: Migrate Config

## Current Behavior
I'm trying to debug some problems related to migration to 0.32+ version using a production scenario config.
I downloaded the exported zip file from demo.airbyte.io and spin up a local instance using the same version (0.29.19-alpha), but the importing process failed with a deadlock in the database.
Looks issue #8276 had the same problem but wasn't reproducible.

## Expected Behavior
*Tell us what should happen.*

## Logs
```
2021-12-02 18:18:36 ERROR i.a.s.h.ArchiveHandler(importInternal):151 - {workspace_app_root=/tmp/workspace/server/logs} - Import failed
org.jooq.exception.DataAccessException: SQL [truncate table public.JOBS restart identity]; ERROR: deadlock detected
  Detail: Process 91 waits for AccessExclusiveLock on relation 16701 of database 16385; blocked by process 104.
Process 104 waits for AccessShareLock on relation 16711 of database 16385; blocked by process 91.
  Hint: See server log for query details.
        at org.jooq_3.13.4.POSTGRES.debug(Unknown Source) ~[?:?]
        at org.jooq.impl.Tools.translate(Tools.java:2753) ~[jooq-3.13.4.jar:?]
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:755) ~[jooq-3.13.4.jar:?]
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:385) ~[jooq-3.13.4.jar:?]
        at io.airbyte.scheduler.persistence.DefaultJobPersistence.truncateTable(DefaultJobPersistence.java:686) ~[io.airbyte.airbyte-scheduler-persistence-0.29.21-alpha.jar:?]
        at io.airbyte.scheduler.persistence.DefaultJobPersistence.lambda$importDatabase$45(DefaultJobPersistence.java:662) ~[io.airbyte.airbyte-scheduler-persistence-0.29.21-alpha.jar:?]
        at io.airbyte.db.Database.lambda$transaction$0(Database.java:51) ~[io.airbyte.airbyte-db-lib-0.29.21-alpha.jar:?]
        at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$0(DefaultDSLContext.java:564) ~[jooq-3.13.4.jar:?]
        at org.jooq.impl.Tools$12$1.block(Tools.java:4926) ~[jooq-3.13.4.jar:?]
        at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3137) ~[?:?]
        at org.jooq.impl.Tools$12.get(Tools.java:4923) ~[jooq-3.13.4.jar:?]
        at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:616) ~[jooq-3.13.4.jar:?]
        at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:533) ~[jooq-3.13.4.jar:?]
        at io.airbyte.db.Database.transaction(Database.java:51) ~[io.airbyte.airbyte-db-lib-0.29.21-alpha.jar:?]
        at io.airbyte.db.ExceptionWrappingDatabase.transaction(ExceptionWrappingDatabase.java:51) ~[io.airbyte.airbyte-db-lib-0.29.21-alpha.jar:?]
        at io.airbyte.scheduler.persistence.DefaultJobPersistence.importDatabase(DefaultJobPersistence.java:659) ~[io.airbyte.airbyte-scheduler-persistence-0.29.21-alpha.jar:?]
        at io.airbyte.scheduler.persistence.DefaultJobPersistence.importDatabase(DefaultJobPersistence.java:649) ~[io.airbyte.airbyte-scheduler-persistence-0.29.21-alpha.jar:?]
        at io.airbyte.server.ConfigDumpImporter.importDatabaseFromArchive(ConfigDumpImporter.java:255) ~[io.airbyte-airbyte-server-0.29.21-alpha.jar:?]
        at io.airbyte.server.ConfigDumpImporter.importDataWithSeed(ConfigDumpImporter.java:147) ~[io.airbyte-airbyte-server-0.29.21-alpha.jar:?]
        at io.airbyte.server.handlers.ArchiveHandler.lambda$importData$0(ArchiveHandler.java:117) ~[io.airbyte-airbyte-server-0.29.21-alpha.jar:?]
        at io.airbyte.server.handlers.ArchiveHandler.importInternal(ArchiveHandler.java:148) ~[io.airbyte-airbyte-server-0.29.21-alpha.jar:?]
        at io.airbyte.server.handlers.ArchiveHandler.importData(ArchiveHandler.java:117) ~[io.airbyte-airbyte-server-0.29.21-alpha.jar:?]
        at io.airbyte.server.apis.ConfigurationApi.lambda$importArchive$64(ConfigurationApi.java:622) ~[io.airbyte-airbyte-server-0.29.21-alpha.jar:?]
        at io.airbyte.server.apis.ConfigurationApi.execute(ConfigurationApi.java:642) ~[io.airbyte-airbyte-server-0.29.21-alpha.jar:?]
```

Complete logs: [server-logs (17).txt](https://github.com/airbytehq/airbyte/files/7644319/server-logs.17.txt)

## Steps to Reproduce
1. Download exported file from demo.airbyte.io
2. Spin up an Airbyte same version (0.29.21-alpha)
3. Use the import button and see the logs.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by marcosmarxm** [comment]
@lmossman tried to import the same config and was able to.
