### ISSUE TITLE
Source Jira: unnesting of issue.fields in normalization fails

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#8473]
## Environment
- **Airbyte version**:  0.32.11-alpha
- **OS Version / Instance**: macOs
- **Deployment**: Docker
- **Source Connector and version**: Jira 0.2.15
- **Destination Connector and version**: Postgres 0.3.16
- **Severity**: Very Low / Low / **Medium** / High / Critical
- **Step where error happened**: Deploy / **Sync job** / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
When trying to sync `board_issues` stream with Incremental + Dedup the sync failed during normalization. The reason is because the cursor field is configured to use a nested field `cursor_field = ["fields", "updated"]`

## Expected Behavior
The sync must work with incremental.

## Logs
Complete logs: [logs-1-0 (4).txt](https://github.com/airbytehq/airbyte/files/7644926/logs-1-0.4.txt)
```
oidCall):82 -   File "/usr/local/lib/python3.8/site-packages/normalization/transform_catalog/transform.py", line 35, in run
normalization - 2021-12-02 19:29:49 ERROR () LineGobbler(voidCall):82 -     self.process_catalog()
normalization - 2021-12-02 19:29:49 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.8/site-packages/normalization/transform_catalog/transform.py", line 62, in process_catalog
normalization - 2021-12-02 19:29:49 ERROR () LineGobbler(voidCall):82 -     processor.process(catalog_file=catalog_file, json_column_name=json_col, default_schema=schema)
normalization - 2021-12-02 19:29:49 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.8/site-packages/normalization/transform_catalog/catalog_processor.py", line 74, in process
normalization - 2021-12-02 19:29:49 ERROR () LineGobbler(voidCall):82 -     nested_processors = stream_processor.process()
normalization - 2021-12-02 19:29:49 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.8/site-packages/normalization/transform_catalog/stream_processor.py", line 282, in process
normalization - 2021-12-02 19:29:49 ERROR () LineGobbler(voidCall):82 -     self.generate_scd_type_2_model(from_table, column_names),
normalization - 2021-12-02 19:29:49 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.8/site-packages/normalization/transform_catalog/stream_processor.py", line 810, in generate_scd_type_2_model
normalization - 2021-12-02 19:29:49 ERROR () LineGobbler(voidCall):82 -     cursor_field=self.get_cursor_field(column_names),
normalization - 2021-12-02 19:29:49 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.8/site-packages/normalization/transform_catalog/stream_processor.py", line 833, in get_cursor_field
normalization - 2021-12-02 19:29:49 ERROR () LineGobbler(voidCall):82 -     raise ValueError(f"Unsupported nested cursor field {'.'.join(self.cursor_field)} for stream {self.stream_name}")
normalization - 2021-12-02 19:29:49 ERROR () LineGobbler(voidCall):82 - ValueError: Unsupported nested cursor field fields.updated for stream board_issues
```

## Steps to Reproduce
1. create source jira with integration account creds
2. create a postgres
3. run sync using the specific stream with incremental

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by marcosmarxm** [comment]
Workaround: change the sync method to `full_refresh`.

Probably the solution for this problem is transform the data to unnest the cursor field value.
@ChristopheDuong what do you think?

**Comment by cdermcarter** [comment]
Normalisation also fails for the other streams that support incremental sync: issues and epic_issues.

Tested on Airbyte 0.35.57-alpha and jira source, 0.2.18, currently the latest versions.

**Comment by toandm** [comment]
Did anyone fix this? I can see that in the latest update for Jira connector version 0.2.20, it has incremental sync mode for `issue` table. However this issue still happens.

**Comment by saifmahamood** [comment]
I want to point out that this issue also exists in `stream board_issues`

```
2022-07-05 21:30:23 normalization > {"type": "LOG", "log": {"level": "FATAL", "message": "Unsupported nested cursor field fields.updated for stream board_issues\nTraceback (most recent call last):\n  File \"/usr/local/bin/transform-catalog\", line 8, in <module>\n    sys.exit(main())\n  File \"/usr/local/lib/python3.9/site-packages/normalization/transform_catalog/transform.py\", line 104, in main\n    TransformCatalog().run(args)\n  File \"/usr/local/lib/python3.9/site-packages/normalization/transform_catalog/transform.py\", line 36, in run\n    self.process_catalog()\n  File \"/usr/local/lib/python3.9/site-packages/normalization/transform_catalog/transform.py\", line 64, in process_catalog\n    processor.process(catalog_file=catalog_file, json_column_name=json_col, default_schema=schema)\n  File \"/usr/local/lib/python3.9/site-packages/normalization/transform_catalog/catalog_processor.py\", line 76, in process\n    nested_processors = stream_processor.process()\n  File \"/usr/local/lib/python3.9/site-packages/normalization/transform_catalog/stream_processor.py\", line 295, in process\n    self.generate_scd_type_2_model(from_table, column_names),\n  File \"/usr/local/lib/python3.9/site-packages/normalization/transform_catalog/stream_processor.py\", line 709, in generate_scd_type_2_model\n    cursor_field = self.get_cursor_field(column_names)\n  File \"/usr/local/lib/python3.9/site-packages/normalization/transform_catalog/stream_processor.py\", line 995, in get_cursor_field\n    raise ValueError(f\"Unsupported nested cursor field {'.'.join(self.cursor_field)} for stream {self.stream_name}\")\nValueError: Unsupported nested cursor field fields.updated for stream board_issues"}}
2022-07-05 21:30:23 normalization > {"type": "TRACE", "trace": {"type": "ERROR", "emitted_at": 1657056623570.177, "error": {"message": "Something went wrong in the connector. See the logs for more details.", "internal_message": "Unsupported nested cursor field fields.updated for stream board_issues", "stack_trace": "Traceback (most recent call last):\n  File \"/usr/local/bin/transform-catalog\", line 8, in <module>\n    sys.exit(main())\n  File \"/usr/local/lib/python3.9/site-packages/normalization/transform_catalog/transform.py\", line 104, in main\n    TransformCatalog().run(args)\n  File \"/usr/local/lib/python3.9/site-packages/normalization/transform_catalog/transform.py\", line 36, in run\n    self.process_catalog()\n  File \"/usr/local/lib/python3.9/site-packages/normalization/transform_catalog/transform.py\", line 64, in process_catalog\n    processor.process(catalog_file=catalog_file, json_column_name=json_col, default_schema=schema)\n  File \"/usr/local/lib/python3.9/site-packages/normalization/transform_catalog/catalog_processor.py\", line 76, in process\n    nested_processors = stream_processor.process()\n  File \"/usr/local/lib/python3.9/site-packages/normalization/transform_catalog/stream_processor.py\", line 295, in process\n    self.generate_scd_type_2_model(from_table, column_names),\n  File \"/usr/local/lib/python3.9/site-packages/normalization/transform_catalog/stream_processor.py\", line 709, in generate_scd_type_2_model\n    cursor_field = self.get_cursor_field(column_names)\n  File \"/usr/local/lib/python3.9/site-packages/normalization/transform_catalog/stream_processor.py\", line 995, in get_cursor_field\n    raise ValueError(f\"Unsupported nested cursor field {'.'.join(self.cursor_field)} for stream {self.stream_name}\")\nValueError: Unsupported nested cursor field fields.updated for stream board_issues\n", "failure_type": "system_error"}}}
```

**Comment by luccafialho** [comment]
Hi everyone! I've experiencing the same problem on Source Connector V 2.20/2.22. You expect to fix it on next release or am I probably doing something wrong?

**Comment by marcosmarxm** [comment]
Zendesk ticket #[1985](https://airbyte7538.zendesk.com/agent/tickets/1985) has been linked to this issue.

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-08-29 at 14:20:*

<blockquote><div class="zd-comment" dir="auto">Hi @ndavies-om1 and @luccafialho, I've found a related issue on GitHub:<br><a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/8473">https://github.com/airbytehq/airbyte/issues/8473</a><br><br>Keep an eye on it, but also try the workaround mentioned and let me know if that helps!<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-08-31 at 14:29:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Thanks <a href="/u/natalyjazzviolin" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">@natalyjazzviolin</a>. I’ve already commented on this issue. I’ll keep looking at it!</p> 

 [<a href="https://discuss.airbyte.io/t/normalization-error-and-final-table-not-created-with-jira-to-redshift/2290/5" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-09-01 at 18:19:*

<blockquote><div class="zd-comment" dir="auto">Ah I see it now! I know the engineering team is prioritizing database connectors right now, so this might fall into Q4 or so. Would you be interested in submitting a PR yourself?<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-07 at 11:31:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">our work around is to export raw json and then flatten it and extract what we want in Snowflake</p> 

 [<a href="https://discuss.airbyte.io/t/normalization-error-and-final-table-not-created-with-jira-to-redshift/2290/7" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-09-07 at 17:15:*

<blockquote><div class="zd-comment" dir="auto">Thanks for bringing that work around to our attention, @ndavies-om1!<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-11-17 at 14:36:*

<blockquote><div class="zd-comment" dir="auto">Looks like the GitHub issue has been resolved - hope this fixes this error for you!<br></div></blockquote>
