### ISSUE TITLE
Exception on sync Salesforce with Portgres - Normalization Failed  

### ISSUE THREAD

**Issue by incoventures** [airbytehq/airbyte#8474]
## Environment
- **Airbyte version**:  0.32.10-alpha
- **OS Version / Instance**: Windows 10 WSL2 Docker
- **Deployment**: Docker
- **Source Connector and version**:Salesforce
- **Destination Connector and version**: PostgreSQL
- **Severity**: Critical
- **Step where error happened**: Sync job

## Current Behavior
Initial sync of Salesforce source with PostgreSQL fails on data normalization

## Logs

<details>
<summary>LOG</summary> 

[32mnormalization[0m - 2021-12-02 19:38:49 INFO () LineGobbler(voidCall):82 - Running with dbt=0.21.0
[32mnormalization[0m - 2021-12-02 19:38:49 INFO () LineGobbler(voidCall):82 - Unable to do partial parsing because ../build/partial_parse.msgpack not found
[32mnormalization[0m - 2021-12-02 19:40:24 INFO () LineGobbler(voidCall):82 - [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[32mnormalization[0m - 2021-12-02 19:40:24 INFO () LineGobbler(voidCall):82 - There are 2 unused configuration paths:
[32mnormalization[0m - 2021-12-02 19:40:24 INFO () LineGobbler(voidCall):82 - - models.airbyte_utils.generated.airbyte_tables
[32mnormalization[0m - 2021-12-02 19:40:24 INFO () LineGobbler(voidCall):82 - - models.airbyte_utils.generated.airbyte_views
[32mnormalization[0m - 2021-12-02 19:40:24 INFO () LineGobbler(voidCall):82 - 
[32mnormalization[0m - 2021-12-02 19:40:40 INFO () LineGobbler(voidCall):82 - Found 3376 models, 0 tests, 0 snapshots, 0 analyses, 478 macros, 0 operations, 0 seed files, 831 sources, 0 exposures
[32mnormalization[0m - 2021-12-02 19:40:41 INFO () LineGobbler(voidCall):82 - 
[32mnormalization[0m - 2021-12-02 19:40:52 INFO () LineGobbler(voidCall):82 - ERROR: Database Error
[32mnormalization[0m - 2021-12-02 19:40:52 INFO () LineGobbler(voidCall):82 -   timeout expired
[32mnormalization[0m - 2021-12-02 19:40:52 INFO () LineGobbler(voidCall):82 -   
2021-12-02 19:40:52 INFO () TemporalAttemptExecution(lambda$getWorkerThread$2):170 - Completing future exceptionally...
io.airbyte.workers.WorkerException: Normalization Failed.
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:60) ~[io.airbyte-airbyte-workers-0.32.10-alpha.jar:?]
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:18) ~[io.airbyte-airbyte-workers-0.32.10-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:167) ~[io.airbyte-airbyte-workers-0.32.10-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: io.airbyte.workers.WorkerException: Normalization Failed.
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:57) ~[io.airbyte-airbyte-workers-0.32.10-alpha.jar:?]
	... 3 more
	Suppressed: io.airbyte.workers.WorkerException: Normalization process wasn't successful
		at io.airbyte.workers.normalization.DefaultNormalizationRunner.close(DefaultNormalizationRunner.java:142) ~[io.airbyte-airbyte-workers-0.32.10-alpha.jar:?]
		at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:45) ~[io.airbyte-airbyte-workers-0.32.10-alpha.jar:?]
		at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:18) ~[io.airbyte-airbyte-workers-0.32.10-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:167) ~[io.airbyte-airbyte-workers-0.32.10-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:832) [?:?]
2021-12-02 19:40:52 INFO () TemporalAttemptExecution(get):137 - Stopping cancellation check scheduling...
2021-12-02 19:40:52 WARN () POJOActivityTaskHandler$POJOActivityImplementation(execute):243 - Activity failure. ActivityId=faa5deea-a8e4-3166-85a0-5c2e12ca8134, activityType=Normalize, attempt=1
java.util.concurrent.ExecutionException: io.airbyte.workers.WorkerException: Normalization Failed.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2063) ~[?:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:135) ~[io.airbyte-airbyte-workers-0.32.10-alpha.jar:?]
	at io.airbyte.workers.temporal.sync.NormalizationActivityImpl.normalize(NormalizationActivityImpl.java:100) ~[io.airbyte-airbyte-workers-0.32.10-alpha.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityInboundCallsInterceptor.execute(POJOActivityTaskHandler.java:277) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityImplementation.execute(POJOActivityTaskHandler.java:216) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.POJOActivityTaskHandler.handle(POJOActivityTaskHandler.java:181) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:192) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:154) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73) ~[temporal-sdk-1.0.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: io.airbyte.workers.WorkerException: Normalization Failed.
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:60) ~[io.airbyte-airbyte-workers-0.32.10-alpha.jar:?]
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:18) ~[io.airbyte-airbyte-workers-0.32.10-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:167) ~[io.airbyte-airbyte-workers-0.32.10-alpha.jar:?]
	... 1 more
Caused by: io.airbyte.workers.WorkerException: Normalization Failed.
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:57) ~[io.airbyte-airbyte-workers-0.32.10-alpha.jar:?]
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:18) ~[io.airbyte-airbyte-workers-0.32.10-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:167) ~[io.airbyte-airbyte-workers-0.32.10-alpha.jar:?]
	... 1 more
	Suppressed: io.airbyte.workers.WorkerException: Normalization process wasn't successful
		at io.airbyte.workers.normalization.DefaultNormalizationRunner.close(DefaultNormalizationRunner.java:142) ~[io.airbyte-airbyte-workers-0.32.10-alpha.jar:?]
		at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:45) ~[io.airbyte-airbyte-workers-0.32.10-alpha.jar:?]
		at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:18) ~[io.airbyte-airbyte-workers-0.32.10-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:167) ~[io.airbyte-airbyte-workers-0.32.10-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:832) [?:?]

</details>

**Comment by marcosmarxm** [comment]
@incoventures what version of connector are you using? Also can you share the complete logs? This is a local Postgres or a cloud instance?

**Comment by incoventures** [comment]
It's a local Postgres. How can I check the connector version?
[logs-3-0.txt](https://github.com/airbytehq/airbyte/files/7645022/logs-3-0.txt)

**Comment by incoventures** [comment]
it seems there was a problem with the db connection. closing the issue now. thanks
