### ISSUE TITLE
🐛 Source Postgres (CDC):  Sync fails when records in Postgres are deleted for tables with non null constraint on columns

### ISSUE THREAD

**Issue by malcolmtivelius** [airbytehq/airbyte#8557]
## Environment
- **Airbyte version**:  v.30.39 **(upgraded to v.0.32.6)**
- **OS Version / Instance**: debian / GCP e2-medium
- **Deployment**: Docker
- **Source Connector and version**: Postgres 0.3.13 **(upgraded to 0.3.17)**
- **Destination Connector and version**: Bigquery 0.5.0
- **Severity**: High
- **Step where error happened**: Sync job

## Current Behavior
Trying to setup CDC with postgres 12 (CloudSQL hosted)-> Bigquery, keep getting errors when data is deleted. Think it has something to do with that the postgres schema has non null constraints on certain columns. The deletes are picked up as row [id, null, null etc..] and since some of the columns have non null constraints it produces an error. Have tried with both wall2json and pgoutput

## Expected Behavior
Expected behavior is that the delete events should be picked up by debezium and not throw any errors, since the non null constraints are only relevant when writing to the Postgres table, not reading from it.

## Logs

<details>
<summary>LOG</summary> 

```

[34msource[0m - 2021-11-12 14:15:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-12 14:15:01 [1;31mERROR[m i.d.r.TableSchemaBuilder(lambda$createValueGenerator$5):269 - {} - Failed to properly convert data value for 'public.countries.code' of type varchar for row [090add40-0a14-11eb-b226-6f1fbcfccacc, null, null, null, null, null]:
[34msource[0m - 2021-11-12 14:15:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - org.apache.kafka.connect.errors.DataException: Invalid value: null used for required field: "code", schema type: STRING
[34msource[0m - 2021-11-12 14:15:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:220) ~[connect-api-2.6.1.jar:?]
[34msource[0m - 2021-11-12 14:15:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at org.apache.kafka.connect.data.Struct.put(Struct.java:216) ~[connect-api-2.6.1.jar:?]
[34msource[0m - 2021-11-12 14:15:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.debezium.relational.TableSchemaBuilder.lambda$createValueGenerator$5(TableSchemaBuilder.java:265) ~[debezium-core-1.4.2.Final.jar:1.4.2.Final]
[34msource[0m - 2021-11-12 14:15:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.debezium.relational.TableSchema.valueFromColumnData(TableSchema.java:141) ~[debezium-core-1.4.2.Final.jar:1.4.2.Final]
[34msource[0m - 2021-11-12 14:15:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.debezium.relational.RelationalChangeRecordEmitter.emitDeleteRecord(RelationalChangeRecordEmitter.java:130) ~[debezium-core-1.4.2.Final.jar:1.4.2.Final]
[34msource[0m - 2021-11-12 14:15:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.debezium.relational.RelationalChangeRecordEmitter.emitChangeRecords(RelationalChangeRecordEmitter.java:54) ~[debezium-core-1.4.2.Final.jar:1.4.2.Final]
[34msource[0m - 2021-11-12 14:15:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.debezium.connector.postgresql.PostgresChangeRecordEmitter.emitChangeRecords(PostgresChangeRecordEmitter.java:88) ~[debezium-connector-postgres-1.4.2.Final.jar:1.4.2.Final]
[34msource[0m - 2021-11-12 14:15:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.debezium.pipeline.EventDispatcher.dispatchDataChangeEvent(EventDispatcher.java:198) ~[debezium-core-1.4.2.Final.jar:1.4.2.Final]
[34msource[0m - 2021-11-12 14:15:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.debezium.connector.postgresql.PostgresStreamingChangeEventSource.lambda$processMessages$0(PostgresStreamingChangeEventSource.java:226) ~[debezium-connector-postgres-1.4.2.Final.jar:1.4.2.Final]
[34msource[0m - 2021-11-12 14:15:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.debezium.connector.postgresql.connection.wal2json.NonStreamingWal2JsonMessageDecoder.processNotEmptyMessage(NonStreamingWal2JsonMessageDecoder.java:78) ~[debezium-connector-postgres-1.4.2.Final.jar:1.4.2.Final]
[34msource[0m - 2021-11-12 14:15:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.debezium.connector.postgresql.connection.AbstractMessageDecoder.processMessage(AbstractMessageDecoder.java:42) ~[debezium-connector-postgres-1.4.2.Final.jar:1.4.2.Final]
[34msource[0m - 2021-11-12 14:15:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.debezium.connector.postgresql.connection.PostgresReplicationConnection$1.deserializeMessages(PostgresReplicationConnection.java:482) ~[debezium-connector-postgres-1.4.2.Final.jar:1.4.2.Final]
[34msource[0m - 2021-11-12 14:15:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.debezium.connector.postgresql.connection.PostgresReplicationConnection$1.readPending(PostgresReplicationConnection.java:474) ~[debezium-connector-postgres-1.4.2.Final.jar:1.4.2.Final]
[34msource[0m - 2021-11-12 14:15:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.debezium.connector.postgresql.PostgresStreamingChangeEventSource.processMessages(PostgresStreamingChangeEventSource.java:185) ~[debezium-connector-postgres-1.4.2.Final.jar:1.4.2.Final]
[34msource[0m - 2021-11-12 14:15:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.debezium.connector.postgresql.PostgresStreamingChangeEventSource.execute(PostgresStreamingChangeEventSource.java:147) ~[debezium-connector-postgres-1.4.2.Final.jar:1.4.2.Final]
[34msource[0m - 2021-11-12 14:15:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:140) ~[debezium-core-1.4.2.Final.jar:1.4.2.Final]
[34msource[0m - 2021-11-12 14:15:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:113) ~[debezium-core-1.4.2.Final.jar:1.4.2.Final]
[34msource[0m - 2021-11-12 14:15:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
[34msource[0m - 2021-11-12 14:15:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
[34msource[0m - 2021-11-12 14:15:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
[34msource[0m - 2021-11-12 14:15:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
[34msource[0m - 2021-11-12 14:15:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at java.lang.Thread.run(Thread.java:832) [?:?]

```

</details>

## Steps to Reproduce
1. Set up CDC replication sync from postgres 12 to bigquery
2. Run a sync
3. Delete a row from the postgres source table 
4. Run another sync

## Are you willing to submit a PR?
Do not know how to solve this, it seems like and issue with debezium

**Comment by alafanechere** [comment]
@malcolmtivelius could you upgrade your Postgres connector from 0.3.13 to 0.3.17 and tell us if the error persists?

**Comment by malcolmtivelius** [comment]
Hey I just upgraded Airbyte to v.0.32.6 and the Postgres connector to 0.3.17. Still running into the same issue when deleting a record! Let me know if you need anything else

**Comment by alafanechere** [comment]
@sherifnada I'll let you prioritize 😄

**Comment by shrodingers** [comment]
Hi ! Just stumbled upon the same issue, and it seems that this is because of the way data is meant to be formatted when going out of the source, and in case of deletes, if REPLICA IDENTITY is set on the tables with DEFAULT value, we do not have information about the original data. A workaround i've find is to use REPLICA IDENTITY FULL in order to keep the previous data in cases of update / delete, and avoiding having issues in cases of delete, even if the best would be not to make some schema validation on these source events

**Comment by malcolmtivelius** [comment]
Thanks for letting me know about this workaround! @shrodingers I just tried it out and my issue was resolved. But as you say, it would still be beneficial to only send the primary key (and not the entire row) if a record is deleted. Will follow this issue for further updates

**Comment by yurii-bidiuk** [comment]
Hello @malcolmtivelius
Could you please verify if this bug still is reproducible for you? 
I tried to repeat all the steps (run a sync, delete one row, run sync again) but my syncs are successful and no issues occurs
Thank you in advance

**Comment by yurii-bidiuk** [comment]
@lucienfregosibodyguard @shrodingers thank you, guys. Previously I used a table with 2 columns (id and testData), but after increasing the number of columns to 5 a bug start reproducing for me as well
