### ISSUE TITLE
🐛 Destination BigQuery denormalized (MongoDB source): JSON table encountered too many errors, giving up.

### ISSUE THREAD

**Issue by TSkrebe** [airbytehq/airbyte#8586]
## Environment
- **Airbyte version**:  0.33.5-alpha
- **OS Version / Instance**: Container-Optimized OS from Google 
- **Deployment**: Kubernetes
- **Source Connector and version**: mongo v2 0.1.8
- **Destination Connector and version**: BigQuery Denormalized 0.1.10
- **Severity**: High 
- **Step where error happened**: Sync job

## Current Behavior
Sync fails with the error:
```
[35mdestination[0m - 2021-12-07 14:23:12 INFO DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-07 14:23:12 [32mINFO[m i.a.i.d.b.BigQueryRecordConsumer(closeNormalBigqueryStreams):312 - {} - Removing tmp tables...
[35mdestination[0m - 2021-12-07 14:23:12 INFO DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-07 14:23:12 [32mINFO[m i.a.i.d.b.BigQueryRecordConsumer(closeNormalBigqueryStreams):314 - {} - Finishing destination process...completed
[35mdestination[0m - 2021-12-07 14:23:12 ERROR LineGobbler(voidCall):82 - Exception in thread "main" java.lang.RuntimeException: com.google.cloud.bigquery.BigQueryException: Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 1; errors: 1. Please look into the errors[] collection for more details.
[35mdestination[0m - 2021-12-07 14:23:12 ERROR LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.bigquery.BigQueryRecordConsumer.lambda$closeNormalBigqueryStreams$6(BigQueryRecordConsumer.java:289)
[35mdestination[0m - 2021-12-07 14:23:12 ERROR LineGobbler(voidCall):82 - 	at io.airbyte.commons.lang.Exceptions.castCheckedToRuntime(Exceptions.java:52)
[35mdestination[0m - 2021-12-07 14:23:12 ERROR LineGobbler(voidCall):82 - 	at io.airbyte.commons.lang.Exceptions.toRuntime(Exceptions.java:39)
[35mdestination[0m - 2021-12-07 14:23:12 ERROR LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.bigquery.BigQueryRecordConsumer.lambda$closeNormalBigqueryStreams$7(BigQueryRecordConsumer.java:279)
[35mdestination[0m - 2021-12-07 14:23:12 ERROR LineGobbler(voidCall):82 - 	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1068)
[35mdestination[0m - 2021-12-07 14:23:12 ERROR LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.bigquery.BigQueryRecordConsumer.closeNormalBigqueryStreams(BigQueryRecordConsumer.java:279)
[35mdestination[0m - 2021-12-07 14:23:12 ERROR LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.bigquery.BigQueryRecordConsumer.close(BigQueryRecordConsumer.java:169)
[35mdestination[0m - 2021-12-07 14:23:12 ERROR LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.bigquery.BigQueryDenormalizedRecordConsumer.close(BigQueryDenormalizedRecordConsumer.java:81)
[35mdestination[0m - 2021-12-07 14:23:12 ERROR LineGobbler(voidCall):82 - 	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.close(FailureTrackingAirbyteMessageConsumer.java:62)
[35mdestination[0m - 2021-12-07 14:23:12 ERROR LineGobbler(voidCall):82 - 	at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:152)
[35mdestination[0m - 2021-12-07 14:23:12 ERROR LineGobbler(voidCall):82 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:128)
[35mdestination[0m - 2021-12-07 14:23:12 ERROR LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.bigquery.BigQueryDenormalizedDestination.main(BigQueryDenormalizedDestination.java:209)
[35mdestination[0m - 2021-12-07 14:23:12 ERROR LineGobbler(voidCall):82 - Caused by: com.google.cloud.bigquery.BigQueryException: Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 1; errors: 1. Please look into the errors[] collection for more details.
[35mdestination[0m - 2021-12-07 14:23:12 ERROR LineGobbler(voidCall):82 - 	at com.google.cloud.bigquery.Job.reload(Job.java:411)
[35mdestination[0m - 2021-12-07 14:23:12 ERROR LineGobbler(voidCall):82 - 	at com.google.cloud.bigquery.Job.waitFor(Job.java:248)
[35mdestination[0m - 2021-12-07 14:23:12 ERROR LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.bigquery.BigQueryRecordConsumer.lambda$closeNormalBigqueryStreams$6(BigQueryRecordConsumer.java:282)
[35mdestination[0m - 2021-12-07 14:23:12 ERROR LineGobbler(voidCall):82 - 	... 11 more
2021-12-07 14:23:12 INFO KubePodProcess(getReturnCode):583 - Exit code for pod destination-bigquery-denormalized-sync-27-0-xpmjg is 0
2021-12-07 14:23:12 INFO KubePodProcess(exitValue):598 - Closed all resources for pod destination-bigquery-denormalized-sync-27-0-xpmjg
2021-12-07 14:23:12 INFO DefaultReplicationWorker(run):141 - Destination thread complete.

```

yet the sync is marked as _Succeeded_ with no data in destination.

## Expected Behavior
1. Sync is not marked as succeeded when it failed.
2. Bug is fixed or the error message would explain what is wrong with the source data.

## Steps to Reproduce
1. set-up connectors
2. run sync

## Are you willing to submit a PR?
no

**Comment by alafanechere** [comment]
Hi @TSkrebe could you share the full sync log + your source and destination catalogs so we can get a bit more insight on what's happening?

More information how to extract logs [here](https://docs.airbyte.io/operator-guides/browsing-output-logs#exploring-the-logs-folders)
```
docker run -it --rm --volume airbyte_workspace:/data busybox cat /data/<job_id>/<attempt_id>/source_catalog.json
docker run -it --rm --volume airbyte_workspace:/data busybox cat /data/<job_id>/<attempt_id>/destination_catalog.json
```

**Comment by TSkrebe** [comment]
attaching [logs.txt](https://github.com/airbytehq/airbyte/files/7676123/logs.txt)

**Comment by alafanechere** [comment]
@TSkrebe thanks! The source and destination catalogs would be helpful too.

**Comment by TSkrebe** [comment]
@alafanechere can you elaborate how to get those logs? i'm running kubernetes and commands provided in the documentation fail because, it's not possible to exec into completed pods.

**Comment by alafanechere** [comment]
I'd suggest you to attach to the any airbyte pod that shares the workspace volume and cat the catalog at the path suggested in my commands.

**Comment by TSkrebe** [comment]
so i checked three containers: scheduler, server and worker, but none of them seem to have access to the volume you're referring. 
```
➜ kubectl exec -it airbyte-server-577bc4464-t5fm7 -- sh
# cd /
# ls
app  bin  boot	configs  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  secrets  srv  sys	tmp  usr  var  workspace
# ls -la configs
total 8
drwxr-xr-x 2 root root 4096 Dec  6 10:56 .
drwxr-xr-x 1 root root 4096 Dec  7 23:33 ..
# ls -la workspace
total 8
drwxr-xr-x 2 root root 4096 Dec  6 10:56 .
drwxr-xr-x 1 root root 4096 Dec  7 23:33 ..
```

```
➜ kubectl exec -it  airbyte-worker-95cc88d6c-v6g7g -- sh
# cd /
# ls
app  bin  boot	dev  etc  home	lib  lib64  media  mnt	opt  proc  root  run  sbin  secrets  srv  sys  tmp  usr  var
```


```
➜   kubectl exec -it airbyte-scheduler-75fdb4d7b9-f6ffd -- sh
# cd /
# ls
app  bin  boot	dev  etc  home	lib  lib64  media  mnt	opt  proc  root  run  sbin  secrets  srv  sys  tmp  usr  var  workspace
$ cd /workspace/62/0
# ls -la
total 8
drwxr-xr-x 2 root root 4096 Dec  8 14:09 .
drwxr-xr-x 3 root root 4096 Dec  8 14:09 ..
```

i'm using default helm configuration. It would be great to be able to report such things without diving deep into underlying architecture.

**Comment by alafanechere** [comment]
When you're using  the helm chart the worspace root is set to `/workspace`. According to the output you shared above you indeed have a `/workspace` folder on the server. Could you share the output of an `ls` on this folder, I think you'll find what you're looking for here.

**Comment by TSkrebe** [comment]
it's empty
```
➜  kubectl exec -it airbyte-server-577bc4464-t5fm7 -- sh
# cd /workspace
# pwd
/workspace
# ls -la
total 8
drwxr-xr-x 2 root root 4096 Dec  6 10:56 .
drwxr-xr-x 1 root root 4096 Dec  7 23:33 ..
```

**Comment by alafanechere** [comment]
Hi @TSkrebe could you have a look to this [documentation](https://docs.airbyte.io/operator-guides/browsing-output-logs#browsing-on-kubernetes) about extracting catalogs in K8S  ? Please let me know if it's not working.

**Comment by TSkrebe** [comment]
@alafanechere k8s documentation is only relevant when pods are still up and running. In our case pods have already exited.

**Comment by alafanechere** [comment]
Ok @TSkrebe, could you try to run the kubectl commands in the doc while your job is running?

**Comment by TSkrebe** [comment]
I switched from helm to kustomize not sure if it changes anything. i still see no logs:
```
root@airbyte-scheduler-57d766b8fb-kwglj:/workspace/286/0# ls -la
total 8
drwxr-xr-x 2 root root 4096 Feb  4 13:04 .
drwxr-xr-x 3 root root 4096 Feb  4 13:04 ..
```

![Screenshot 2022-02-04 at 15 06 57](https://user-images.githubusercontent.com/4008242/152534202-8e6dfce2-c18f-4a44-bbfc-22adf206376a.png)
