### ISSUE TITLE
🐛 Destination Snowflake: DBT found an approximate match, Instead of guessing, Failure.

### ISSUE THREAD

**Issue by qops1981** [airbytehq/airbyte#8605]
## Environment
- **Airbyte version**:  example is 0.30.20-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Postgres 0.3.11 
- **Destination Connector and version**: Snowflake 0.3.16 
- **Severity**: Low
- **Step where error happened**: Sync job

## Current Behavior
Sync Job fails on `case` table.

## Expected Behavior
Sync job should sync the `case` table without issue.

## Logs

<details>
<summary>LOG</summary> 

```
2021-12-03 16:43:53 INFO () LineGobbler(voidCall):65 - detected no config file for ssh, assuming ssh is off.
2021-12-03 16:43:54 INFO () LineGobbler(voidCall):65 - Running with dbt=0.19.0
2021-12-03 16:44:00 INFO () LineGobbler(voidCall):65 - [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
2021-12-03 16:44:00 INFO () LineGobbler(voidCall):65 - There are 1 unused configuration paths:
2021-12-03 16:44:00 INFO () LineGobbler(voidCall):65 - - models.airbyte_utils.generated.airbyte_views
2021-12-03 16:44:00 INFO () LineGobbler(voidCall):65 - 
2021-12-03 16:44:01 INFO () LineGobbler(voidCall):65 - Found 84 models, 0 tests, 0 snapshots, 0 analyses, 427 macros, 0 operations, 0 seed files, 14 sources, 0 exposures
2021-12-03 16:44:01 INFO () LineGobbler(voidCall):65 - 
2021-12-03 16:44:05 INFO () LineGobbler(voidCall):65 - 16:44:05 | Concurrency: 32 threads (target='prod')
2021-12-03 16:44:05 INFO () LineGobbler(voidCall):65 - 16:44:05 | 
2021-12-03 16:44:08 INFO () LineGobbler(voidCall):65 - 16:44:08 | 1 of 28 START table model SALESFORCE.ACCOUNT_SCD............................................................. [RUN]
2021-12-03 16:44:08 INFO () LineGobbler(voidCall):65 - 16:44:08 | 3 of 28 START table model SALESFORCE.BRAND_REGISTRATION__C_SCD............................................... [RUN]
2021-12-03 16:44:08 INFO () LineGobbler(voidCall):65 - 16:44:08 | 4 of 28 START table model SALESFORCE.ZQU__PRODUCTRATEPLAN__C_SCD............................................. [RUN]
2021-12-03 16:44:08 INFO () LineGobbler(voidCall):65 - 16:44:08 | 2 of 28 START table model SALESFORCE.BRAND_USE_CASE__C_SCD................................................... [RUN]
2021-12-03 16:44:08 INFO () LineGobbler(voidCall):65 - 16:44:08 | 5 of 28 START table model SALESFORCE.ZQU__PRODUCTRATEPLANCHARGE__C_SCD....................................... [RUN]
2021-12-03 16:44:08 INFO () LineGobbler(voidCall):65 - 16:44:08 | 6 of 28 START table model SALESFORCE.ZQU__ZPRODUCT__C_SCD.................................................... [RUN]
2021-12-03 16:44:08 INFO () LineGobbler(voidCall):65 - 16:44:08 | 7 of 28 START table model SALESFORCE.ZUORA__SUBSCRIPTIONPRODUCTCHARGE__C_SCD................................. [RUN]
2021-12-03 16:44:08 INFO () LineGobbler(voidCall):65 - 16:44:08 | 8 of 28 START table model SALESFORCE.PARTNER_SUBSCRIPTION__C_SCD............................................. [RUN]
2021-12-03 16:44:08 INFO () LineGobbler(voidCall):65 - 16:44:08 | 9 of 28 START table model SALESFORCE.CASE_SCD................................................................ [RUN]
2021-12-03 16:44:08 INFO () LineGobbler(voidCall):65 - 16:44:08 | 10 of 28 START table model SALESFORCE.SUBSCRIPTION_PLAN__C_SCD............................................... [RUN]
2021-12-03 16:44:08 INFO () LineGobbler(voidCall):65 - 16:44:08 | 11 of 28 START table model SALESFORCE.ZUORA__CUSTOMERACCOUNT__C_SCD.......................................... [RUN]
2021-12-03 16:44:08 INFO () LineGobbler(voidCall):65 - 16:44:08 | 12 of 28 START table model SALESFORCE.ZUORA__SUBSCRIPTION__C_SCD............................................. [RUN]
2021-12-03 16:44:08 INFO () LineGobbler(voidCall):65 - 16:44:08 | 13 of 28 START table model SALESFORCE.ZUORA__SUBSCRIPTIONPRODUCTFEATURE__C_SCD............................... [RUN]
2021-12-03 16:44:08 INFO () LineGobbler(voidCall):65 - 16:44:08 | 14 of 28 START table model SALESFORCE.OPPORTUNITY_SCD........................................................ [RUN]
2021-12-03 16:44:15 INFO () LineGobbler(voidCall):65 - 16:44:15 | 4 of 28 OK created table model SALESFORCE.ZQU__PRODUCTRATEPLAN__C_SCD........................................ [[32mSUCCESS 1[0m in 7.26s]
2021-12-03 16:44:15 INFO () LineGobbler(voidCall):65 - 16:44:15 | 15 of 28 START table model SALESFORCE.ZQU__PRODUCTRATEPLAN__C................................................ [RUN]
2021-12-03 16:44:15 INFO () LineGobbler(voidCall):65 - 16:44:15 | 5 of 28 OK created table model SALESFORCE.ZQU__PRODUCTRATEPLANCHARGE__C_SCD.................................. [[32mSUCCESS 1[0m in 7.32s]
2021-12-03 16:44:15 INFO () LineGobbler(voidCall):65 - 16:44:15 | 16 of 28 START table model SALESFORCE.ZQU__PRODUCTRATEPLANCHARGE__C.......................................... [RUN]
2021-12-03 16:44:15 INFO () LineGobbler(voidCall):65 - 16:44:15 | 1 of 28 OK created table model SALESFORCE.ACCOUNT_SCD........................................................ [[32mSUCCESS 1[0m in 7.60s]
2021-12-03 16:44:15 INFO () LineGobbler(voidCall):65 - 16:44:15 | 17 of 28 START table model SALESFORCE.ACCOUNT................................................................ [RUN]
2021-12-03 16:44:16 INFO () LineGobbler(voidCall):65 - 16:44:16 | 3 of 28 OK created table model SALESFORCE.BRAND_REGISTRATION__C_SCD.......................................... [[32mSUCCESS 1[0m in 8.05s]
2021-12-03 16:44:16 INFO () LineGobbler(voidCall):65 - 16:44:16 | 18 of 28 START table model SALESFORCE.BRAND_REGISTRATION__C.................................................. [RUN]
2021-12-03 16:44:16 INFO () LineGobbler(voidCall):65 - 16:44:16 | 6 of 28 OK created table model SALESFORCE.ZQU__ZPRODUCT__C_SCD............................................... [[32mSUCCESS 1[0m in 8.59s]
2021-12-03 16:44:16 INFO () LineGobbler(voidCall):65 - 16:44:16 | 19 of 28 START table model SALESFORCE.ZQU__ZPRODUCT__C....................................................... [RUN]
2021-12-03 16:44:16 INFO () LineGobbler(voidCall):65 - 16:44:16 | 11 of 28 OK created table model SALESFORCE.ZUORA__CUSTOMERACCOUNT__C_SCD..................................... [[32mSUCCESS 1[0m in 8.53s]
2021-12-03 16:44:16 INFO () LineGobbler(voidCall):65 - 16:44:16 | 2 of 28 OK created table model SALESFORCE.BRAND_USE_CASE__C_SCD.............................................. [[32mSUCCESS 1[0m in 8.80s]
2021-12-03 16:44:16 INFO () LineGobbler(voidCall):65 - 16:44:16 | 8 of 28 OK created table model SALESFORCE.PARTNER_SUBSCRIPTION__C_SCD........................................ [[32mSUCCESS 1[0m in 8.73s]
2021-12-03 16:44:17 INFO () LineGobbler(voidCall):65 - 16:44:16 | 20 of 28 START table model SALESFORCE.ZUORA__CUSTOMERACCOUNT__C.............................................. [RUN]
2021-12-03 16:44:17 INFO () LineGobbler(voidCall):65 - 16:44:17 | 21 of 28 START table model SALESFORCE.BRAND_USE_CASE__C...................................................... [RUN]
2021-12-03 16:44:17 INFO () LineGobbler(voidCall):65 - 16:44:17 | 22 of 28 START table model SALESFORCE.PARTNER_SUBSCRIPTION__C................................................ [RUN]
2021-12-03 16:44:18 INFO () LineGobbler(voidCall):65 - 16:44:18 | 7 of 28 OK created table model SALESFORCE.ZUORA__SUBSCRIPTIONPRODUCTCHARGE__C_SCD............................ [[32mSUCCESS 1[0m in 9.84s]
2021-12-03 16:44:18 INFO () LineGobbler(voidCall):65 - 16:44:18 | 23 of 28 START table model SALESFORCE.ZUORA__SUBSCRIPTIONPRODUCTCHARGE__C.................................... [RUN]
2021-12-03 16:44:18 INFO () LineGobbler(voidCall):65 - 16:44:18 | 10 of 28 OK created table model SALESFORCE.SUBSCRIPTION_PLAN__C_SCD.......................................... [[32mSUCCESS 1[0m in 10.13s]
2021-12-03 16:44:18 INFO () LineGobbler(voidCall):65 - 16:44:18 | 24 of 28 START table model SALESFORCE.SUBSCRIPTION_PLAN__C................................................... [RUN]
2021-12-03 16:44:18 INFO () LineGobbler(voidCall):65 - 16:44:18 | 13 of 28 OK created table model SALESFORCE.ZUORA__SUBSCRIPTIONPRODUCTFEATURE__C_SCD.......................... [[32mSUCCESS 1[0m in 10.31s]
2021-12-03 16:44:18 INFO () LineGobbler(voidCall):65 - 16:44:18 | 25 of 28 START table model SALESFORCE.ZUORA__SUBSCRIPTIONPRODUCTFEATURE__C................................... [RUN]
2021-12-03 16:44:19 INFO () LineGobbler(voidCall):65 - 16:44:19 | 15 of 28 OK created table model SALESFORCE.ZQU__PRODUCTRATEPLAN__C........................................... [[32mSUCCESS 1[0m in 4.23s]
2021-12-03 16:44:19 INFO () LineGobbler(voidCall):65 - 16:44:19 | 12 of 28 OK created table model SALESFORCE.ZUORA__SUBSCRIPTION__C_SCD........................................ [[32mSUCCESS 1[0m in 11.14s]
2021-12-03 16:44:19 INFO () LineGobbler(voidCall):65 - 16:44:19 | 16 of 28 OK created table model SALESFORCE.ZQU__PRODUCTRATEPLANCHARGE__C..................................... [[32mSUCCESS 1[0m in 4.05s]
2021-12-03 16:44:19 INFO () LineGobbler(voidCall):65 - 16:44:19 | 26 of 28 START table model SALESFORCE.ZUORA__SUBSCRIPTION__C................................................. [RUN]
2021-12-03 16:44:21 INFO () LineGobbler(voidCall):65 - 16:44:21 | 20 of 28 OK created table model SALESFORCE.ZUORA__CUSTOMERACCOUNT__C......................................... [[32mSUCCESS 1[0m in 4.46s]
2021-12-03 16:44:21 INFO () LineGobbler(voidCall):65 - 16:44:21 | 17 of 28 OK created table model SALESFORCE.ACCOUNT........................................................... [[32mSUCCESS 1[0m in 6.00s]
2021-12-03 16:44:21 INFO () LineGobbler(voidCall):65 - 16:44:21 | 25 of 28 OK created table model SALESFORCE.ZUORA__SUBSCRIPTIONPRODUCTFEATURE__C.............................. [[32mSUCCESS 1[0m in 2.96s]
2021-12-03 16:44:21 INFO () LineGobbler(voidCall):65 - 16:44:21 | 19 of 28 OK created table model SALESFORCE.ZQU__ZPRODUCT__C.................................................. [[32mSUCCESS 1[0m in 5.09s]
2021-12-03 16:44:21 INFO () LineGobbler(voidCall):65 - 16:44:21 | 21 of 28 OK created table model SALESFORCE.BRAND_USE_CASE__C................................................. [[32mSUCCESS 1[0m in 4.83s]
2021-12-03 16:44:22 INFO () LineGobbler(voidCall):65 - 16:44:22 | 22 of 28 OK created table model SALESFORCE.PARTNER_SUBSCRIPTION__C........................................... [[32mSUCCESS 1[0m in 4.71s]
2021-12-03 16:44:22 INFO () LineGobbler(voidCall):65 - 16:44:22 | 18 of 28 OK created table model SALESFORCE.BRAND_REGISTRATION__C............................................. [[32mSUCCESS 1[0m in 5.92s]
2021-12-03 16:44:22 INFO () LineGobbler(voidCall):65 - 16:44:22 | 24 of 28 OK created table model SALESFORCE.SUBSCRIPTION_PLAN__C.............................................. [[32mSUCCESS 1[0m in 4.18s]
2021-12-03 16:44:22 INFO () LineGobbler(voidCall):65 - 16:44:22 | 26 of 28 OK created table model SALESFORCE.ZUORA__SUBSCRIPTION__C............................................ [[32mSUCCESS 1[0m in 2.89s]
2021-12-03 16:44:23 INFO () LineGobbler(voidCall):65 - 16:44:23 | 23 of 28 OK created table model SALESFORCE.ZUORA__SUBSCRIPTIONPRODUCTCHARGE__C............................... [[32mSUCCESS 1[0m in 5.22s]
2021-12-03 16:44:25 INFO () LineGobbler(voidCall):65 - 16:44:25 | 14 of 28 OK created table model SALESFORCE.OPPORTUNITY_SCD................................................... [[32mSUCCESS 1[0m in 16.67s]
2021-12-03 16:44:25 INFO () LineGobbler(voidCall):65 - 16:44:25 | 27 of 28 START table model SALESFORCE.OPPORTUNITY............................................................ [RUN]
2021-12-03 16:44:28 INFO () LineGobbler(voidCall):65 - 16:44:28 | 9 of 28 OK created table model SALESFORCE.CASE_SCD........................................................... [[32mSUCCESS 1[0m in 20.52s]
2021-12-03 16:44:28 INFO () LineGobbler(voidCall):65 - 16:44:28 | 28 of 28 START table model SALESFORCE.case................................................................... [RUN]
2021-12-03 16:44:28 INFO () LineGobbler(voidCall):65 - 16:44:28 | 28 of 28 ERROR creating table model SALESFORCE.case.......................................................... [[31mERROR[0m in 0.05s]
2021-12-03 16:44:29 INFO () LineGobbler(voidCall):65 - 16:44:29 | 27 of 28 OK created table model SALESFORCE.OPPORTUNITY....................................................... [[32mSUCCESS 1[0m in 3.55s]
2021-12-03 16:44:29 INFO () LineGobbler(voidCall):65 - 16:44:29 | 
2021-12-03 16:44:29 INFO () LineGobbler(voidCall):65 - 16:44:29 | Finished running 28 table models in 28.64s.
2021-12-03 16:44:30 INFO () LineGobbler(voidCall):65 - 
2021-12-03 16:44:30 INFO () LineGobbler(voidCall):65 - [31mCompleted with 1 error and 0 warnings:[0m
2021-12-03 16:44:30 INFO () LineGobbler(voidCall):65 - 
2021-12-03 16:44:30 INFO () LineGobbler(voidCall):65 - [33mCompilation Error in model case (models/generated/airbyte_tables/SALESFORCE/case.sql)[0m
2021-12-03 16:44:30 INFO () LineGobbler(voidCall):65 -   When searching for a relation, dbt found an approximate match. Instead of guessing 
2021-12-03 16:44:30 INFO () LineGobbler(voidCall):65 -   which relation to use, dbt will move on. Please delete "AIRBYTE_DB"."SALESFORCE"."CASE", or rename it to be less ambiguous.
2021-12-03 16:44:30 INFO () LineGobbler(voidCall):65 -   Searched for: AIRBYTE_DB.SALESFORCE.case
2021-12-03 16:44:30 INFO () LineGobbler(voidCall):65 -   Found: "AIRBYTE_DB"."SALESFORCE"."CASE"
2021-12-03 16:44:30 INFO () LineGobbler(voidCall):65 -   
2021-12-03 16:44:30 INFO () LineGobbler(voidCall):65 -   > in macro materialization_table_snowflake (macros/materializations/table.sql)
2021-12-03 16:44:30 INFO () LineGobbler(voidCall):65 -   > called by model case (models/generated/airbyte_tables/SALESFORCE/case.sql)
2021-12-03 16:44:30 INFO () LineGobbler(voidCall):65 - 
2021-12-03 16:44:30 INFO () LineGobbler(voidCall):65 - Done. PASS=27 WARN=0 ERROR=1 SKIP=0 TOTAL=28
2021-12-03 16:44:31 INFO () TemporalAttemptExecution(lambda$getWorkerThread$1):148 - Completing future exceptionally...
io.airbyte.workers.WorkerException: Normalization Failed.
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:60) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:18) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$1(TemporalAttemptExecution.java:145) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: io.airbyte.workers.WorkerException: Normalization Failed.
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:57) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
	... 3 more
	Suppressed: io.airbyte.workers.WorkerException: Normalization process wasn't successful
		at io.airbyte.workers.normalization.DefaultNormalizationRunner.close(DefaultNormalizationRunner.java:135) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
		at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:45) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
		at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:18) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$1(TemporalAttemptExecution.java:145) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:832) [?:?]
2021-12-03 16:44:31 INFO () TemporalAttemptExecution(get):115 - Stopping cancellation check scheduling...
2021-12-03 16:44:31 WARN () POJOActivityTaskHandler$POJOActivityImplementation(execute):243 - Activity failure. ActivityId=ee928b07-d34d-3b61-b6b2-7b0a659a3234, activityType=Normalize, attempt=1
java.util.concurrent.ExecutionException: io.airbyte.workers.WorkerException: Normalization Failed.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2063) ~[?:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:113) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
	at io.airbyte.workers.temporal.SyncWorkflow$NormalizationActivityImpl.normalize(SyncWorkflow.java:299) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor154.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityInboundCallsInterceptor.execute(POJOActivityTaskHandler.java:277) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityImplementation.execute(POJOActivityTaskHandler.java:216) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.sync.POJOActivityTaskHandler.handle(POJOActivityTaskHandler.java:181) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:192) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:154) ~[temporal-sdk-1.0.4.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73) ~[temporal-sdk-1.0.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: io.airbyte.workers.WorkerException: Normalization Failed.
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:60) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:18) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$1(TemporalAttemptExecution.java:145) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
	... 1 more
Caused by: io.airbyte.workers.WorkerException: Normalization Failed.
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:57) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:18) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$1(TemporalAttemptExecution.java:145) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
	... 1 more
	Suppressed: io.airbyte.workers.WorkerException: Normalization process wasn't successful
		at io.airbyte.workers.normalization.DefaultNormalizationRunner.close(DefaultNormalizationRunner.java:135) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
		at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:45) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
		at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:18) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$1(TemporalAttemptExecution.java:145) ~[io.airbyte-airbyte-workers-0.30.20-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:832) [?:?]
```

</details>

## Steps to Reproduce
1. Run Fresh sync - **Failure**
2. Drop Snowflake Tables and Reload - **Failure**
3. Try a data reload - **Failure**

## Theory
At the moment we think it's because CASE is a function keyword to Snowflake. But we wanted you all to see it, just in case. 

## Are you willing to submit a PR?

If I knew what I was doing, sure

**Comment by alafanechere** [comment]
Hi @qops1981 do you think the root cause could be that dbt is searching for a lower cased `case` relation while the one that exists is in uppercase: 
```
Searched for: AIRBYTE_DB.SALESFORCE.case
Found: "AIRBYTE_DB"."SALESFORCE"."CASE"
```

**Comment by qops1981** [comment]
@alafanechere so that's the weird thing. The source table is `case`, the table that Airbyte creates in Snowflake is `CASE`. Most (if not all) of the tables that Airbyte created are ALL CAPS versions of their origins. I have tried dropping the `CASE` table, but it just recreates it and fails again. To be clear I see no `case` table in Snowflake, just `CASE` which Airybyte created from the `case` table in Postgres.

**Comment by alafanechere** [comment]
@qops1981 I think that your first intuition is the right one. I think this is related to SQL compilation on the DBT side because the `case` keyword is a reserved one that their compiler might lowercase. I found great information in this [blog post](https://towardsdatascience.com/debugging-dbt-when-your-table-name-is-a-reserved-keyword-faf81ab6376b).
I'd see three solutions: 
1. Rename your source table 
2. Change your destination table name using a custom dbt  transformation. You can find an example on how to extract our basic normalization dbt code and edit it in [this guide](https://docs.airbyte.io/operator-guides/transformation-and-normalization/transformations-with-sql)
3. Same as the previous step but rather than renaming the column you could escape it as explained in the blog post above.

@ChristopheDuong do you confirm that's the way to go? I think its closely related to this issue https://github.com/airbytehq/airbyte/issues/8553 .

**Comment by ChristopheDuong** [comment]
sounds good

**Comment by qops1981** [comment]
Ok, we will look into that. Our Analytics person wanted me to make sure to call out that this is a "standard" Salesforce table, so you might see this with other users. Thank you both for following up on this.

**Comment by qops1981** [comment]
We found a quick work around. We just created a separate connection for just that table and added a "prefix" to the destination table. This got the data over successfully on the initial and following sync's.
