### ISSUE TITLE
🐛 Destination MeiliSearch: NullPointerException when getOrCreate index

### ISSUE THREAD

**Issue by longfellowone** [airbytehq/airbyte#8674]
## Environment
- **Airbyte version**:   0.33.5-alpha
- **OS Version / Instance**: Windows 10
- **Deployment**: Docker
- **Source Connector and version**:  Postgres 0.3.17
- **Destination Connector and version**: MeiliSearch 0.2.10
- **Step where error happened**:  Sync job

## Current Behavior
Both connectors setup/test ok. Initial sync/refresh fails

## Expected Behavior
Sync/refresh ok

## Logs

[logs1.txt](https://github.com/airbytehq/airbyte/files/7686901/logs1.txt)
[logs2.txt](https://github.com/airbytehq/airbyte/files/7686902/logs2.txt)

```

2021-12-08 19:35:30 INFO () WorkerRun(call):49 - Executing worker wrapper. Airbyte version: 0.33.5-alpha
2021-12-08 19:35:30 INFO () TemporalAttemptExecution(get):116 - Executing worker wrapper. Airbyte version: 0.33.5-alpha
2021-12-08 19:35:30 WARN () Databases(createPostgresDatabaseWithRetry):41 - Waiting for database to become available...
2021-12-08 19:35:30 INFO () JobsDatabaseInstance(lambda$static$2):25 - Testing if jobs database is ready...
2021-12-08 19:35:30 INFO () Databases(createPostgresDatabaseWithRetry):58 - Database available!
2021-12-08 19:35:30 INFO () DefaultReplicationWorker(run):99 - start sync worker. job id: 2 attempt id: 1
2021-12-08 19:35:30 INFO () DefaultReplicationWorker(run):108 - configured sync modes: {public.projects=full_refresh - overwrite}
2021-12-08 19:35:30 INFO () DefaultAirbyteDestination(start):64 - Running destination...
2021-12-08 19:35:30 INFO () LineGobbler(voidCall):82 - Checking if airbyte/destination-meilisearch:0.2.10 exists...
2021-12-08 19:35:30 INFO () LineGobbler(voidCall):82 - airbyte/destination-meilisearch:0.2.10 was found locally.
2021-12-08 19:35:30 INFO () DockerProcessFactory(create):127 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/2/1 --network host --log-driver none airbyte/destination-meilisearch:0.2.10 write --config destination_config.json --catalog destination_catalog.json
2021-12-08 19:35:30 INFO () DefaultReplicationWorker(run):136 - Waiting for source thread to join.
2021-12-08 19:35:30 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):207 - Replication thread started.
2021-12-08 19:35:30 INFO () DefaultReplicationWorker(lambda$getDestinationOutputRunnable$3):243 - Destination output thread started.
2021-12-08 19:35:30 INFO () DefaultReplicationWorker(run):138 - Source thread complete.
2021-12-08 19:35:30 INFO () DefaultReplicationWorker(run):139 - Waiting for destination thread to join.
[35mdestination[0m - 2021-12-08 19:35:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-08 19:35:31 [32mINFO[m i.a.i.d.m.MeiliSearchDestination(main):202 - {} - starting destination: class io.airbyte.integrations.destination.meilisearch.MeiliSearchDestination
[35mdestination[0m - 2021-12-08 19:35:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-08 19:35:31 [32mINFO[m i.a.i.b.IntegrationRunner(run):96 - {} - Running integration: io.airbyte.integrations.destination.meilisearch.MeiliSearchDestination
[35mdestination[0m - 2021-12-08 19:35:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-08 19:35:31 [32mINFO[m i.a.i.b.IntegrationCliParser(parseOptions):135 - {} - integration args: {catalog=destination_catalog.json, write=null, config=destination_config.json}
[35mdestination[0m - 2021-12-08 19:35:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-08 19:35:31 [32mINFO[m i.a.i.b.IntegrationRunner(run):100 - {} - Command: WRITE
[35mdestination[0m - 2021-12-08 19:35:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-08 19:35:31 [32mINFO[m i.a.i.b.IntegrationRunner(run):101 - {} - Integration config: IntegrationConfig{command=WRITE, configPath='destination_config.json', catalogPath='destination_catalog.json', statePath='null'}
[35mdestination[0m - 2021-12-08 19:35:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-08 19:35:31 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
[35mdestination[0m - 2021-12-08 19:35:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-08 19:35:31 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
[35mdestination[0m - 2021-12-08 19:35:31 ERROR () LineGobbler(voidCall):82 - WARNING: An illegal reflective access operation has occurred
[35mdestination[0m - 2021-12-08 19:35:31 ERROR () LineGobbler(voidCall):82 - WARNING: Illegal reflective access by com.google.gson.internal.reflect.UnsafeReflectionAccessor (file:/airbyte/lib/gson-2.8.7.jar) to field java.lang.ThreadLocal.threadLocalHashCode
[35mdestination[0m - 2021-12-08 19:35:31 ERROR () LineGobbler(voidCall):82 - WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.reflect.UnsafeReflectionAccessor
[35mdestination[0m - 2021-12-08 19:35:31 ERROR () LineGobbler(voidCall):82 - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[35mdestination[0m - 2021-12-08 19:35:31 ERROR () LineGobbler(voidCall):82 - WARNING: All illegal access operations will be denied in a future release
[35mdestination[0m - 2021-12-08 19:35:31 ERROR () LineGobbler(voidCall):82 - Exception in thread "main" java.lang.NullPointerException
[35mdestination[0m - 2021-12-08 19:35:31 ERROR () LineGobbler(voidCall):82 - 	at com.meilisearch.sdk.Client.getOrCreateIndex(Client.java:141)
[35mdestination[0m - 2021-12-08 19:35:31 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.meilisearch.MeiliSearchDestination.createIndices(MeiliSearchDestination.java:141)
[35mdestination[0m - 2021-12-08 19:35:31 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.meilisearch.MeiliSearchDestination.getConsumer(MeiliSearchDestination.java:117)
[35mdestination[0m - 2021-12-08 19:35:31 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:147)
[35mdestination[0m - 2021-12-08 19:35:31 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.meilisearch.MeiliSearchDestination.main(MeiliSearchDestination.java:203)
2021-12-08 19:35:31 INFO () DefaultReplicationWorker(run):141 - Destination thread complete.
2021-12-08 19:35:31 ERROR () DefaultReplicationWorker(run):145 - Sync worker failed.
io.airbyte.workers.WorkerException: Destination process exit with code 1. This warning is normal if the job was cancelled.
	at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.close(DefaultAirbyteDestination.java:114) ~[io.airbyte-airbyte-workers-0.33.5-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:143) ~[io.airbyte-airbyte-workers-0.33.5-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:49) ~[io.airbyte-airbyte-workers-0.33.5-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:167) ~[io.airbyte-airbyte-workers-0.33.5-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
2021-12-08 19:35:31 INFO () DefaultReplicationWorker(run):169 - sync summary: io.airbyte.config.ReplicationAttemptSummary@65352e49[status=failed,recordsSynced=0,bytesSynced=0,startTime=1638992130239,endTime=1638992131798]
2021-12-08 19:35:31 INFO () DefaultReplicationWorker(run):176 - Source output at least one state message
2021-12-08 19:35:31 WARN () DefaultReplicationWorker(run):189 - State capture: No state retained.
2021-12-08 19:35:31 INFO () TemporalAttemptExecution(get):137 - Stopping cancellation check scheduling...
2021-12-08 19:35:31 INFO () ReplicationActivityImpl(replicate):121 - sync summary: io.airbyte.config.StandardSyncOutput@36c460c1[standardSyncSummary=io.airbyte.config.StandardSyncSummary@ac8e54e[status=failed,recordsSynced=0,bytesSynced=0,startTime=1638992130239,endTime=1638992131798],state=<null>,outputCatalog=io.airbyte.protocol.models.ConfiguredAirbyteCatalog@570de96b[streams=[io.airbyte.protocol.models.ConfiguredAirbyteStream@27dd04e6[stream=io.airbyte.protocol.models.AirbyteStream@328abab4[name=projects,jsonSchema={"type":"object","properties":{"id":{"type":"string"},"name":{"type":"string"}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[[id]],namespace=public,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=overwrite,primaryKey=[[id]],additionalProperties={}]],additionalProperties={}]]

```

```

2021-12-09 04:07:23 INFO () WorkerRun(call):49 - Executing worker wrapper. Airbyte version: 0.33.5-alpha
2021-12-09 04:07:23 INFO () TemporalAttemptExecution(get):116 - Executing worker wrapper. Airbyte version: 0.33.5-alpha
2021-12-09 04:07:23 WARN () Databases(createPostgresDatabaseWithRetry):41 - Waiting for database to become available...
2021-12-09 04:07:23 INFO () JobsDatabaseInstance(lambda$static$2):25 - Testing if jobs database is ready...
2021-12-09 04:07:23 INFO () Databases(createPostgresDatabaseWithRetry):58 - Database available!
2021-12-09 04:07:23 WARN () JsonMetaSchema(newValidator):338 - Unknown keyword example - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2021-12-09 04:07:23 INFO () DefaultReplicationWorker(run):99 - start sync worker. job id: 1 attempt id: 0
2021-12-09 04:07:23 INFO () DefaultReplicationWorker(run):108 - configured sync modes: {public.projects=incremental - append}
2021-12-09 04:07:23 INFO () DefaultAirbyteDestination(start):64 - Running destination...
2021-12-09 04:07:23 INFO () LineGobbler(voidCall):82 - Checking if airbyte/destination-meilisearch:0.2.10 exists...
2021-12-09 04:07:23 INFO () LineGobbler(voidCall):82 - airbyte/destination-meilisearch:0.2.10 was found locally.
2021-12-09 04:07:23 INFO () DockerProcessFactory(create):127 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/1/0 --network host --log-driver none airbyte/destination-meilisearch:0.2.10 write --config destination_config.json --catalog destination_catalog.json
2021-12-09 04:07:23 INFO () LineGobbler(voidCall):82 - Checking if airbyte/source-postgres:0.3.17 exists...
2021-12-09 04:07:23 INFO () LineGobbler(voidCall):82 - airbyte/source-postgres:0.3.17 was found locally.
2021-12-09 04:07:23 INFO () DockerProcessFactory(create):127 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/1/0 --network host --log-driver none airbyte/source-postgres:0.3.17 read --config source_config.json --catalog source_catalog.json
2021-12-09 04:07:23 INFO () DefaultReplicationWorker(lambda$getDestinationOutputRunnable$3):243 - Destination output thread started.
2021-12-09 04:07:23 INFO () DefaultReplicationWorker(run):136 - Waiting for source thread to join.
2021-12-09 04:07:23 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):207 - Replication thread started.
[34msource[0m - 2021-12-09 04:07:28 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-09 04:07:28 [32mINFO[m i.a.i.s.p.PostgresSource(main):279 - {} - starting source: class io.airbyte.integrations.source.postgres.PostgresSource
[35mdestination[0m - 2021-12-09 04:07:28 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-09 04:07:28 [32mINFO[m i.a.i.d.m.MeiliSearchDestination(main):202 - {} - starting destination: class io.airbyte.integrations.destination.meilisearch.MeiliSearchDestination
[34msource[0m - 2021-12-09 04:07:28 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-09 04:07:28 [32mINFO[m i.a.i.b.IntegrationRunner(run):76 - {} - Running integration: io.airbyte.integrations.base.ssh.SshWrappedSource
[35mdestination[0m - 2021-12-09 04:07:28 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-09 04:07:28 [32mINFO[m i.a.i.b.IntegrationRunner(run):96 - {} - Running integration: io.airbyte.integrations.destination.meilisearch.MeiliSearchDestination
[34msource[0m - 2021-12-09 04:07:28 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-09 04:07:28 [32mINFO[m i.a.i.b.IntegrationCliParser(parseOptions):118 - {} - integration args: {read=null, catalog=source_catalog.json, config=source_config.json}
[35mdestination[0m - 2021-12-09 04:07:28 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-09 04:07:28 [32mINFO[m i.a.i.b.IntegrationCliParser(parseOptions):135 - {} - integration args: {catalog=destination_catalog.json, write=null, config=destination_config.json}
[35mdestination[0m - 2021-12-09 04:07:28 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-09 04:07:28 [32mINFO[m i.a.i.b.IntegrationRunner(run):100 - {} - Command: WRITE
[34msource[0m - 2021-12-09 04:07:28 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-09 04:07:28 [32mINFO[m i.a.i.b.IntegrationRunner(run):80 - {} - Command: READ
[34msource[0m - 2021-12-09 04:07:28 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-09 04:07:28 [32mINFO[m i.a.i.b.IntegrationRunner(run):81 - {} - Integration config: IntegrationConfig{command=READ, configPath='source_config.json', catalogPath='source_catalog.json', statePath='null'}
[35mdestination[0m - 2021-12-09 04:07:28 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-09 04:07:28 [32mINFO[m i.a.i.b.IntegrationRunner(run):101 - {} - Integration config: IntegrationConfig{command=WRITE, configPath='destination_config.json', catalogPath='destination_catalog.json', statePath='null'}
[35mdestination[0m - 2021-12-09 04:07:28 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-09 04:07:28 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
[35mdestination[0m - 2021-12-09 04:07:28 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-09 04:07:28 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
[34msource[0m - 2021-12-09 04:07:28 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-09 04:07:28 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
[34msource[0m - 2021-12-09 04:07:28 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-09 04:07:28 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword examples - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
[34msource[0m - 2021-12-09 04:07:28 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-09 04:07:28 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
[34msource[0m - 2021-12-09 04:07:28 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-09 04:07:28 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword multiline - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
[35mdestination[0m - 2021-12-09 04:07:28 ERROR () LineGobbler(voidCall):82 - Exception in thread "main" java.lang.NullPointerException
[35mdestination[0m - 2021-12-09 04:07:28 ERROR () LineGobbler(voidCall):82 - 	at com.meilisearch.sdk.Client.getOrCreateIndex(Client.java:141)
[35mdestination[0m - 2021-12-09 04:07:28 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.meilisearch.MeiliSearchDestination.createIndices(MeiliSearchDestination.java:141)
[35mdestination[0m - 2021-12-09 04:07:28 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.meilisearch.MeiliSearchDestination.getConsumer(MeiliSearchDestination.java:117)
[35mdestination[0m - 2021-12-09 04:07:28 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:147)
[35mdestination[0m - 2021-12-09 04:07:28 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.meilisearch.MeiliSearchDestination.main(MeiliSearchDestination.java:203)
[34msource[0m - 2021-12-09 04:07:28 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-09 04:07:28 [32mINFO[m i.a.i.b.s.SshTunnel(getInstance):170 - {} - Starting connection with method: NO_TUNNEL
[34msource[0m - 2021-12-09 04:07:28 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-09 04:07:28 [32mINFO[m i.a.i.s.p.PostgresSource(isCdc):210 - {} - using CDC: false
[34msource[0m - 2021-12-09 04:07:28 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-09 04:07:28 [32mINFO[m i.a.i.s.j.AbstractJdbcSource(lambda$getCheckOperations$1):93 - {} - Attempting to get metadata from the database to see if we can connect.
[34msource[0m - 2021-12-09 04:07:28 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-09 04:07:28 [32mINFO[m i.a.i.s.r.CdcStateManager(<init>):26 - {} - Initialized CDC state with: null
[34msource[0m - 2021-12-09 04:07:28 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-09 04:07:28 [32mINFO[m i.a.i.s.r.StateManager(createCursorInfoForStream):118 - {} - No cursor field set in catalog but not present in state. Stream: AirbyteStreamNameNamespacePair{name='projects', namespace='public'}, New Cursor Field: updated_at. Resetting cursor value
[34msource[0m - 2021-12-09 04:07:29 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-09 04:07:29 [32mINFO[m i.a.i.s.p.PostgresSource(isCdc):210 - {} - using CDC: false
[34msource[0m - 2021-12-09 04:07:29 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-09 04:07:29 [32mINFO[m i.a.i.s.r.AbstractRelationalDbSource(queryTableFullRefresh):35 - {} - Queueing query for table: projects
[34msource[0m - 2021-12-09 04:07:29 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-09 04:07:29 [32mINFO[m i.a.i.s.r.StateDecoratingIterator(computeNext):60 - {} - State Report: stream name: AirbyteStreamNameNamespacePair{name='projects', namespace='public'}, original cursor field: null, original cursor null, cursor field: updated_at, new cursor: 2021-12-08T22:01:59Z
[34msource[0m - 2021-12-09 04:07:29 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-09 04:07:29 [32mINFO[m i.a.i.s.r.AbstractDbSource(lambda$read$2):123 - {} - Closing database connection pool.
[34msource[0m - 2021-12-09 04:07:29 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-09 04:07:29 [32mINFO[m i.a.i.s.r.AbstractDbSource(lambda$read$2):125 - {} - Closed database connection pool.
[34msource[0m - 2021-12-09 04:07:29 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-09 04:07:29 [32mINFO[m i.a.i.b.IntegrationRunner(run):133 - {} - Completed integration: io.airbyte.integrations.base.ssh.SshWrappedSource
[34msource[0m - 2021-12-09 04:07:29 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-09 04:07:29 [32mINFO[m i.a.i.s.p.PostgresSource(main):281 - {} - completed source: class io.airbyte.integrations.source.postgres.PostgresSource
2021-12-09 04:07:29 ERROR () DefaultReplicationWorker(run):145 - Sync worker failed.
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.io.IOException: Stream closed
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:137) ~[io.airbyte-airbyte-workers-0.33.5-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:49) ~[io.airbyte-airbyte-workers-0.33.5-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:167) ~[io.airbyte-airbyte-workers-0.33.5-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
	Suppressed: java.io.IOException: Stream closed
		at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:442) ~[?:?]
		at java.io.OutputStream.write(OutputStream.java:162) ~[?:?]
		at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81) ~[?:?]
		at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142) ~[?:?]
		at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:327) ~[?:?]
		at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:159) ~[?:?]
		at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:251) ~[?:?]
		at java.io.BufferedWriter.flush(BufferedWriter.java:257) ~[?:?]
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.notifyEndOfStream(DefaultAirbyteDestination.java:93) ~[io.airbyte-airbyte-workers-0.33.5-alpha.jar:?]
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.close(DefaultAirbyteDestination.java:106) ~[io.airbyte-airbyte-workers-0.33.5-alpha.jar:?]
		at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:118) ~[io.airbyte-airbyte-workers-0.33.5-alpha.jar:?]
		at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:49) ~[io.airbyte-airbyte-workers-0.33.5-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:167) ~[io.airbyte-airbyte-workers-0.33.5-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.RuntimeException: java.io.IOException: Stream closed
	at io.airbyte.workers.DefaultReplicationWorker.lambda$getReplicationRunnable$2(DefaultReplicationWorker.java:231) ~[io.airbyte-airbyte-workers-0.33.5-alpha.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	... 1 more
Caused by: java.io.IOException: Stream closed
	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:442) ~[?:?]
	at java.io.OutputStream.write(OutputStream.java:162) ~[?:?]
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81) ~[?:?]
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142) ~[?:?]
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:327) ~[?:?]
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:159) ~[?:?]
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:251) ~[?:?]
	at java.io.BufferedWriter.flush(BufferedWriter.java:257) ~[?:?]
	at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.notifyEndOfStream(DefaultAirbyteDestination.java:93) ~[io.airbyte-airbyte-workers-0.33.5-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.lambda$getReplicationRunnable$2(DefaultReplicationWorker.java:224) ~[io.airbyte-airbyte-workers-0.33.5-alpha.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	... 1 more
2021-12-09 04:07:29 INFO () DefaultReplicationWorker(run):169 - sync summary: io.airbyte.config.ReplicationAttemptSummary@4be3286b[status=failed,recordsSynced=3,bytesSynced=300,startTime=1639022843567,endTime=1639022849268]
2021-12-09 04:07:29 INFO () DefaultReplicationWorker(run):176 - Source output at least one state message
2021-12-09 04:07:29 WARN () DefaultReplicationWorker(run):189 - State capture: No state retained.
2021-12-09 04:07:29 INFO () TemporalAttemptExecution(get):137 - Stopping cancellation check scheduling...
2021-12-09 04:07:29 INFO () ReplicationActivityImpl(replicate):121 - sync summary: io.airbyte.config.StandardSyncOutput@30763218[standardSyncSummary=io.airbyte.config.StandardSyncSummary@65d7fa57[status=failed,recordsSynced=3,bytesSynced=300,startTime=1639022843567,endTime=1639022849268],state=<null>,outputCatalog=io.airbyte.protocol.models.ConfiguredAirbyteCatalog@39c7fafc[streams=[io.airbyte.protocol.models.ConfiguredAirbyteStream@209db9d9[stream=io.airbyte.protocol.models.AirbyteStream@21fab920[name=projects,jsonSchema={"type":"object","properties":{"id":{"type":"string"},"name":{"type":"string"},"updated_at":{"type":"string"}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[[id]],namespace=public,additionalProperties={}],syncMode=incremental,cursorField=[updated_at],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}]],additionalProperties={}]]

```

## Steps to Reproduce
1. `git clone https://github.com/longfellowone/airbyteerr.git`
2. `docker-compose up`
3. Setup postgres connector - Host `localhost` User `postgres` Password `postgres` database `postgres`
4. Setup meilisearch connector - Host `http://localhost:7700/` Key `key`

MEILI_MASTER_KEY=key

**Comment by marcosmarxm** [comment]
thanks @longfellowone looks this a problem with the destination connector. I added your issue in the connector roadmap.

**Comment by cirdes** [comment]
@marcosmarxm, with the new [python version](https://github.com/airbytehq/airbyte/pull/18036) this issue is no longer applicable.
