### ISSUE TITLE
Env S3_LOG_BUCKET_REGION not working

### ISSUE THREAD

**Issue by granescb** [airbytehq/airbyte#8696]
## Environment
- **Airbyte version**:  0.33.5-alpha
- **OS Version / Instance**: Container-Optimized OS from Google
- **Deployment**: Kubernetes
- **Severity**: High
- **Step where error happened**: Deploy

## Current Behavior
When I deployed application I see exception:
Cannot create enum from 'us-east-1' value!
In documentation I didn't found any example values for this env

My envs:
S3_LOG_BUCKET=<my_bucket_name>
S3_LOG_BUCKET_REGION='us-east-1'
S3_MINIO_ENDPOINT=
S3_PATH_STYLE_ACCESS=
By this documentation: https://docs.airbyte.io/deploying-airbyte/on-kubernetes#custom-configuration
AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY in secrets

## Expected Behavior
Working without exception

## Logs
[aibyte-error-logs.txt](https://github.com/airbytehq/airbyte/files/7692588/aibyte-error-logs.txt)

<details>
<summary>LOG</summary> 

```

2021-12-10 12:02:50 INFO i.t.i.w.Poller(start):95 - {cloud_workspace_app_root=/workspace/scheduler/logs} - start(): Poller{options=PollerOptions{maximumPollRateIntervalMilliseconds=1000, maximumPollRatePerSecond=0.0, pollBackoffCoefficient=2.0, pollBackoffInitialInterval=PT0.1S, pollBackoffMaximumInterval=PT1M, pollThreadCount=5, pollThreadNamePrefix='Activity Poller taskQueue="SYNC", namespace="default"'}, identity=1@airbyte-worker-5948f8c8f4-gl8lc}
2021-12-10 12:02:50,265 main ERROR Could not create plugin of type class com.van.logging.log4j2.Log4j2Appender for element Log4j2Appender: java.lang.RuntimeException: Cannot build appender due to errors java.lang.RuntimeException: Cannot build appender due to errors
	at com.van.logging.log4j2.Log4j2AppenderBuilder.build(Log4j2AppenderBuilder.java:133)
	at com.van.logging.log4j2.Log4j2AppenderBuilder.build(Log4j2AppenderBuilder.java:25)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1000)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:940)
	at org.apache.logging.log4j.core.appender.routing.RoutingAppender.createAppender(RoutingAppender.java:299)
	at org.apache.logging.log4j.core.appender.routing.RoutingAppender.getControl(RoutingAppender.java:271)
	at org.apache.logging.log4j.core.appender.routing.RoutingAppender.append(RoutingAppender.java:229)
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:540)
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:498)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:481)
	at org.apache.logging.log4j.core.config.LoggerConfig.logParent(LoggerConfig.java:531)
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:481)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:456)
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
	at org.apache.logging.log4j.core.Logger.log(Logger.java:161)
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2022)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1875)
	at org.apache.logging.slf4j.Log4jLogger.info(Log4jLogger.java:179)
	at io.temporal.internal.worker.Poller.start(Poller.java:95)
	at io.temporal.internal.worker.ActivityWorker.start(ActivityWorker.java:104)
	at io.temporal.internal.sync.SyncActivityWorker.start(SyncActivityWorker.java:64)
	at io.temporal.worker.Worker.start(Worker.java:331)
	at io.temporal.worker.WorkerFactory.start(WorkerFactory.java:201)
	at io.airbyte.workers.WorkerApp.start(WorkerApp.java:146)
	at io.airbyte.workers.WorkerApp.main(WorkerApp.java:213)
Caused by: java.lang.IllegalArgumentException: Cannot create enum from 'us-east-1' value!
	at com.amazonaws.regions.Regions.fromName(Regions.java:99)
	at com.van.logging.aws.S3Configuration.resolveRegion(S3Configuration.java:181)
	at com.van.logging.aws.S3Configuration.setRegion(S3Configuration.java:121)
	at com.van.logging.log4j2.Log4j2AppenderBuilder.getS3ConfigIfEnabled(Log4j2AppenderBuilder.java:158)
	at com.van.logging.log4j2.Log4j2AppenderBuilder.createCachePublisher(Log4j2AppenderBuilder.java:251)
	at com.van.logging.log4j2.Log4j2AppenderBuilder.build(Log4j2AppenderBuilder.java:128)
	... 33 more

```

</details>

## Steps to Reproduce
1. Deploy application in k8s
2. Setup S3 logs bucket via env

## Are you willing to submit a PR?
No

**Comment by marcosmarxm** [comment]
Did you use `'` in the value? Could you try without it?

**Comment by marcosmarxm** [comment]
Closing due inactivity please open a new issue if it cotinues.
