### ISSUE TITLE
Source typeform not showing logs and CPU usage 100%

### ISSUE THREAD

**Issue by bruno-nirello** [airbytehq/airbyte#8817]
## Environment
Is this your first time deploying Airbyte: No
**OS Version** / Instance: Ubuntu 20.04
**Machine type** e2-standard-8 ( 8 CPU )
**Memory / Disk:** 32Gb / 100 GB ssd
**Deployment**: Docker
**Airbyte Version:** 0.33.9-alpha
**Source name/version:** airbyte/source-typeform:0.1.4
**Destination name/version:** airbyte/destination-bigquery:0.5.0
**Description:** Typeform does not return logs in UI, plus the machine cpu utilization increases to 100%, the airbyte/server:0.33.9-alpha is the resource hunger.
- **Severity**: High
- **Step where error happened**: Sync job 

## Current Behavior
Typeform does not return logs in UI, plus the machine cpu utilization increases to 100%, the airbyte/server:0.33.9-alpha is the resource hunger.

![Screenshot from 2021-12-14 14-27-55](https://user-images.githubusercontent.com/30416677/146239947-6336bb90-5f24-4ec2-8541-7c617cbbcf30.png)

![Screenshot from 2021-12-15 14-17-16](https://user-images.githubusercontent.com/30416677/146239999-b56e4084-1b06-4006-9e36-57c504b324a8.png)

## Expected Behavior
All other conectors behave normally, showing in the UI.

## Steps to Reproduce
1. First time is ok, close the front-end.
2. Open again and try to sync the typeform

## Are you willing to submit a PR?
Yes

**Comment by bruno-nirello** [comment]
i found more info about the problem, the logs are printing the content of reports. That also data privacy problem, it explain why it's not showing the logs in the UI
![image](https://user-images.githubusercontent.com/30416677/147132673-257756a4-6ee5-4376-86a3-c5339f9594b1.png)

**Comment by bruno-nirello** [comment]
hi, i'm still having problems trying to sync data from typeform, if someone wants to make a video call i can share my screen and show the problem.

**Comment by bruno-nirello** [comment]
![Screenshot from 2022-01-27 11-49-34](https://user-images.githubusercontent.com/30416677/151382912-13acfcc3-f5f2-4e48-b411-1cfb6835f283.png)
I'm trying to get reports from > '2021-01-01' **it fails**, and the fact that they print all content from files in the log, i cannot see what causes the issue because the log freezes.

When i tried to get just a few days I am successful

**Comment by bruno-nirello** [comment]
@marcosmarxm yes

Airbyte Version: 0.39.34-alpha
Source: Typeform (0.1.7)
Destination: BigQuery (1.1.11)

i can't share the logs because still printing response data

32mINFO[m i.a.w.g.DefaultReplicationWorker(run):272 - State capture: Updated state to: Optional[io.airbyte.config.State@52a15a19[state={"responses":{"gcv[PRIVATE_DATE]

**Comment by davydov-d** [comment]
moving to On hold since OAuth implementation is blocked and so is certification

**Comment by caiopedroso** [comment]
Having the ~ same ~ problem, but I'm think it's actually two different problems.
One is with the connector itself, the way airbyte is handling the data retrieved from typeform.
The other is it prints the whole response at least 2 times and when you try to open using the webserver the CPU tops 100% - but not sure if it's related to the connector crash.

```
2022-08-17 22:41:42 destination > 2022-08-17 22:41:42 INFO i.a.i.d.b.BigQueryStagingConsumerFactory(lambda$onCloseFunction$5):164 - Cleaning up destination completed.

----------------------------------- WHOLE RESPONSE PRINTED ----------------------------------- 

2022-08-17 22:41:43 destination > 2022-08-17 22:41:43 INFO i.a.i.b.IntegrationRunner(runInternal):152 - Completed integration: io.airbyte.integrations.destination.bigquery.BigQueryDestination
2022-08-17 22:41:43 INFO i.a.w.g.DefaultReplicationWorker(run):180 - Source and destination threads complete.
2022-08-17 22:41:43 INFO i.a.w.g.DefaultReplicationWorker(run):243 - sync summary: io.airbyte.config.ReplicationAttemptSummary@1c3c0a30[status=completed,recordsSynced=61183,bytesSynced=90436055,startTime=1660775684829,endTime=1660776103668,totalStats=io.airbyte.config.SyncStats@5d680aef[recordsEmitted=61183,bytesEmitted=90436055,stateMessagesEmitted=321,recordsCommitted=61183],streamStats=[io.airbyte.config.StreamSyncStats@1f40f8e1[streamName=typeform_workspaces,stats=io.airbyte.config.SyncStats@7f4ed58b[recordsEmitted=2,bytesEmitted=507,stateMessagesEmitted=<null>,recordsCommitted=2]], io.airbyte.config.StreamSyncStats@35f2dd8[streamName=typeform_forms,stats=io.airbyte.config.SyncStats@1e7d702e[recordsEmitted=17,bytesEmitted=120431,stateMessagesEmitted=<null>,recordsCommitted=17]], io.airbyte.config.StreamSyncStats@66214f0[streamName=typeform_responses,stats=io.airbyte.config.SyncStats@f097b3a[recordsEmitted=61164,bytesEmitted=90315117,stateMessagesEmitted=<null>,recordsCommitted=61164]]]]
2022-08-17 22:41:43 INFO i.a.w.g.DefaultReplicationWorker(run):270 - Source output at least one state message

----------------------------------- WHOLE RESPONSE PRINTED ----------------------------------- 

2022-08-17 22:41:44 INFO i.a.w.t.TemporalUtils(withBackgroundHeartbeat):312 - Stopping temporal heartbeating...
2022-08-17 22:41:44 WARN i.t.i.r.GrpcSyncRetryer(retry):56 - Retrying after failure
io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: grpc: received message larger than max (9752703 vs. 4194304)
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262) ~[grpc-stub-1.44.1.jar:1.44.1]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243) ~[grpc-stub-1.44.1.jar:1.44.1]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156) ~[grpc-stub-1.44.1.jar:1.44.1]
	at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.respondActivityTaskCompleted(WorkflowServiceGrpc.java:2746) ~[temporal-serviceclient-1.8.1.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.lambda$sendReply$0(ActivityWorker.java:278) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.retryer.GrpcRetryer.lambda$retry$0(GrpcRetryer.java:44) ~[temporal-serviceclient-1.8.1.jar:?]
	at io.temporal.internal.retryer.GrpcSyncRetryer.retry(GrpcSyncRetryer.java:61) ~[temporal-serviceclient-1.8.1.jar:?]
	at io.temporal.internal.retryer.GrpcRetryer.retryWithResult(GrpcRetryer.java:51) ~[temporal-serviceclient-1.8.1.jar:?]
	at io.temporal.internal.retryer.GrpcRetryer.retry(GrpcRetryer.java:41) ~[temporal-serviceclient-1.8.1.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.sendReply(ActivityWorker.java:272) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:208) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:164) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93) ~[temporal-sdk-1.8.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [?:?]
	at java.lang.Thread.run(Thread.java:1589) [?:?]
```

**Comment by marcosmarxm** [comment]
@bruno-nirello I'm closing due inactivity, please test latest version of Typeform and if the issue continue please open a new issue.
