### ISSUE TITLE
Normalization Fails on Google Sheets

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#904]
## Current Behavior
```
airbyte-scheduler | 2020-11-11 02:44:10 INFO i.a.c.i.LineGobbler(voidCall):69 - {job_id=36, job_log_filename=logs.log, job_root=/tmp/workspace/36/0} - 02:44:10 |
airbyte-scheduler | 2020-11-11 02:44:10 INFO i.a.c.i.LineGobbler(voidCall):69 - {job_id=36, job_log_filename=logs.log, job_root=/tmp/workspace/36/0} - 02:44:10 | 1 of 1 START table model CG_MANUAL_TEST.sheet1............................................................... [RUN]
airbyte-scheduler | 2020-11-11 02:44:12 INFO i.a.c.i.LineGobbler(voidCall):69 - {job_id=36, job_log_filename=logs.log, job_root=/tmp/workspace/36/0} - 02:44:12 | 1 of 1 ERROR creating table model CG_MANUAL_TEST.sheet1...................................................... [ERROR in 1.77s]
airbyte-scheduler | 2020-11-11 02:44:13 INFO i.a.c.i.LineGobbler(voidCall):69 - {job_id=36, job_log_filename=logs.log, job_root=/tmp/workspace/36/0} - 2020-11-11 02:44:13 INFO i.a.i.b.IntegrationRunner(run):120 - {} - Completed integration: io.airbyte.integrations.destination.snowflake.SnowflakeDestination
airbyte-scheduler | 2020-11-11 02:44:13 INFO i.a.c.i.LineGobbler(voidCall):69 - {job_id=36, job_log_filename=logs.log, job_root=/tmp/workspace/36/0} - 2020-11-11 02:44:13 INFO i.a.i.d.s.SnowflakeDestination(main):137 - {} - completed destination: class io.airbyte.integrations.destination.snowflake.SnowflakeDestination
airbyte-scheduler | 2020-11-11 02:44:14 INFO i.a.c.i.LineGobbler(voidCall):69 - {job_id=36, job_log_filename=logs.log, job_root=/tmp/workspace/36/0} - 02:44:14 |
airbyte-scheduler | 2020-11-11 02:44:14 INFO i.a.c.i.LineGobbler(voidCall):69 - {job_id=36, job_log_filename=logs.log, job_root=/tmp/workspace/36/0} - 02:44:14 | Finished running 1 table model in 7.82s.
airbyte-scheduler | 2020-11-11 02:44:14 INFO i.a.c.i.LineGobbler(voidCall):69 - {job_id=36, job_log_filename=logs.log, job_root=/tmp/workspace/36/0} -
airbyte-scheduler | 2020-11-11 02:44:14 INFO i.a.c.i.LineGobbler(voidCall):69 - {job_id=36, job_log_filename=logs.log, job_root=/tmp/workspace/36/0} - Completed with 1 error and 0 warnings:
airbyte-scheduler | 2020-11-11 02:44:14 INFO i.a.c.i.LineGobbler(voidCall):69 - {job_id=36, job_log_filename=logs.log, job_root=/tmp/workspace/36/0} -
airbyte-scheduler | 2020-11-11 02:44:14 INFO i.a.c.i.LineGobbler(voidCall):69 - {job_id=36, job_log_filename=logs.log, job_root=/tmp/workspace/36/0} - Database Error in model sheet1 (models/generated/sheet1.sql)
airbyte-scheduler | 2020-11-11 02:44:14 INFO i.a.c.i.LineGobbler(voidCall):69 - {job_id=36, job_log_filename=logs.log, job_root=/tmp/workspace/36/0} -   001851 (22023): Invalid extraction path 'basic working': invalid token at position 6.
airbyte-scheduler | 2020-11-11 02:44:14 INFO i.a.c.i.LineGobbler(voidCall):69 - {job_id=36, job_log_filename=logs.log, job_root=/tmp/workspace/36/0} -   compiled SQL at build/run/airbyte/models/generated/sheet1.sql
airbyte-scheduler | 2020-11-11 02:44:14 INFO i.a.c.i.LineGobbler(voidCall):69 - {job_id=36, job_log_filename=logs.log, job_root=/tmp/workspace/36/0} -
airbyte-scheduler | 2020-11-11 02:44:14 INFO i.a.c.i.LineGobbler(voidCall):69 - {job_id=36, job_log_filename=logs.log, job_root=/tmp/workspace/36/0} - Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
airbyte-scheduler | 2020-11-11 02:44:14 DEBUG i.a.w.n.DefaultNormalizationRunner(close):96 - {job_id=36, job_log_filename=logs.log, job_root=/tmp/workspace/36/0} - Closing tap process
airbyte-scheduler | 2020-11-11 02:44:14 DEBUG i.a.w.p.a.DefaultAirbyteSource(close):107 - {job_id=36, job_log_filename=logs.log, job_root=/tmp/workspace/36/0} - Closing tap process
airbyte-scheduler | 2020-11-11 02:44:14 DEBUG i.a.w.p.a.DefaultAirbyteDestination(close):102 - {job_id=36, job_log_filename=logs.log, job_root=/tmp/workspace/36/0} - Closing target process
airbyte-scheduler | 2020-11-11 02:44:14 INFO i.a.s.JobRetrier(run):53 - {} - Running job-retrier...
airbyte-scheduler | 2020-11-11 02:44:14 INFO i.a.s.JobRetrier(run):67 - {} - Completed job-retrier...
airbyte-scheduler | 2020-11-11 02:44:14 INFO i.a.s.JobScheduler(run):76 - {} - Running job-scheduler...
airbyte-scheduler | 2020-11-11 02:44:14 INFO i.a.s.JobScheduler(run):80 - {} - Completed job-scheduler...
airbyte-scheduler | 2020-11-11 02:44:14 INFO i.a.s.JobSubmitter(run):67 - {} - Running job-submitter...
airbyte-scheduler | 2020-11-11 02:44:14 INFO i.a.s.JobSubmitter(run):76 - {} - Completed job-submitter...
airbyte-scheduler | 2020-11-11 02:44:14 ERROR i.a.w.DefaultSyncWorker(run):99 - {job_id=36, job_log_filename=logs.log, job_root=/tmp/workspace/36/0} - Sync worker failed.
airbyte-scheduler | io.airbyte.workers.WorkerException: Normalization Failed.
airbyte-scheduler | 	at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:95) [io.airbyte-airbyte-workers-0.2.1-alpha.jar:?]
airbyte-scheduler | 	at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:44) [io.airbyte-airbyte-workers-0.2.1-alpha.jar:?]
airbyte-scheduler | 	at io.airbyte.workers.wrappers.OutputConvertingWorker.run(OutputConvertingWorker.java:44) [io.airbyte-airbyte-workers-0.2.1-alpha.jar:?]
airbyte-scheduler | 	at io.airbyte.workers.wrappers.JobOutputSyncWorker.run(JobOutputSyncWorker.java:32) [io.airbyte-airbyte-workers-0.2.1-alpha.jar:?]
airbyte-scheduler | 	at io.airbyte.scheduler.WorkerRun.lambda$new$0(WorkerRun.java:53) [io.airbyte-airbyte-scheduler-0.2.1-alpha.jar:?]
airbyte-scheduler | 	at io.airbyte.scheduler.WorkerRun.call(WorkerRun.java:61) [io.airbyte-airbyte-scheduler-0.2.1-alpha.jar:?]
airbyte-scheduler | 	at io.airbyte.scheduler.WorkerRun.call(WorkerRun.java:42) [io.airbyte-airbyte-scheduler-0.2.1-alpha.jar:?]
airbyte-scheduler | 	at io.airbyte.commons.concurrency.LifecycledCallable.execute(LifecycledCallable.java:114) [io.airbyte-airbyte-commons-0.2.1-alpha.jar:?]
airbyte-scheduler | 	at io.airbyte.commons.concurrency.LifecycledCallable.call(LifecycledCallable.java:98) [io.airbyte-airbyte-commons-0.2.1-alpha.jar:?]
airbyte-scheduler | 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
airbyte-scheduler | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
airbyte-scheduler | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
airbyte-scheduler | 	at java.lang.Thread.run(Thread.java:832) [?:?]
airbyte-scheduler | 	Suppressed: io.airbyte.workers.WorkerException: Tap process wasn't successful
airbyte-scheduler | 		at io.airbyte.workers.normalization.DefaultNormalizationRunner.close(DefaultNormalizationRunner.java:99) ~[io.airbyte-airbyte-workers-0.2.1-alpha.jar:?]
airbyte-scheduler | 		at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:90) [io.airbyte-airbyte-workers-0.2.1-alpha.jar:?]
airbyte-scheduler | 		at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:44) [io.airbyte-airbyte-workers-0.2.1-alpha.jar:?]
airbyte-scheduler | 		at io.airbyte.workers.wrappers.OutputConvertingWorker.run(OutputConvertingWorker.java:44) [io.airbyte-airbyte-workers-0.2.1-alpha.jar:?]
airbyte-scheduler | 		at io.airbyte.workers.wrappers.JobOutputSyncWorker.run(JobOutputSyncWorker.java:32) [io.airbyte-airbyte-workers-0.2.1-alpha.jar:?]
airbyte-scheduler | 		at io.airbyte.scheduler.WorkerRun.lambda$new$0(WorkerRun.java:53) [io.airbyte-airbyte-scheduler-0.2.1-alpha.jar:?]
airbyte-scheduler | 		at io.airbyte.scheduler.WorkerRun.call(WorkerRun.java:61) [io.airbyte-airbyte-scheduler-0.2.1-alpha.jar:?]
airbyte-scheduler | 		at io.airbyte.scheduler.WorkerRun.call(WorkerRun.java:42) [io.airbyte-airbyte-scheduler-0.2.1-alpha.jar:?]
airbyte-scheduler | 		at io.airbyte.commons.concurrency.LifecycledCallable.execute(LifecycledCallable.java:114) [io.airbyte-airbyte-commons-0.2.1-alpha.jar:?]
airbyte-scheduler | 		at io.airbyte.commons.concurrency.LifecycledCallable.call(LifecycledCallable.java:98) [io.airbyte-airbyte-commons-0.2.1-alpha.jar:?]
airbyte-scheduler | 		at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
airbyte-scheduler | 		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
airbyte-scheduler | 		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
airbyte-scheduler | 		at java.lang.Thread.run(Thread.java:832) [?:?]
airbyte-scheduler | 2020-11-11 02:44:14 INFO i.a.s.p.DefaultSchedulerPersistence(updateStatus):199 - {job_id=36, job_log_filename=logs.log, job_root=/tmp/workspace/36/0} - Setting job status to FAILED for job 36
```

## Steps to Reproduce
1. go through the setup steps. 
1. attempt to sync our testing spreadsheet: https://docs.google.com/spreadsheets/d/1wMKCQ_oQ-qOGduwvPodtDO_1dBhQ9v8_V3Le1EOQatg/edit#gid=0

raw version goes through. normalization doesn't. unfortunately the error is kinda opaque.

**Comment by cgardens** [comment]
zooming in on the part of the error message that it think shows the problem:

```
{job_id=36, job_log_filename=logs.log, job_root=/tmp/workspace/36/0} -
{job_id=36, job_log_filename=logs.log, job_root=/tmp/workspace/36/0} - Database Error in model sheet1 (models/generated/sheet1.sql)
{job_id=36, job_log_filename=logs.log, job_root=/tmp/workspace/36/0} -   001851 (22023): Invalid extraction path 'basic working': invalid token at position 6.
{job_id=36, job_log_filename=logs.log, job_root=/tmp/workspace/36/0} -   compiled SQL at build/run/airbyte/models/generated/sheet1.sql
{job_id=36, job_log_filename=logs.log, job_root=/tmp/workspace/36/0} -
```

**Comment by cgardens** [comment]
fixed with the casing fixes.
