### ISSUE TITLE
Posthog to Redshift Erroring (Airbyte - 0.34.4-alpha Redshift - 0.3.23 Posthog - 0.1.4)

### ISSUE THREAD

**Issue by nthbooth-feedr** [airbytehq/airbyte#9041]
## Environment
- **Airbyte version**:  0.34.4-alpha
- **OS Version / Instance**: AWS EC2 T3a XL $ uname -a
Linux eu-west-1.compute.internal 4.14.252-195.483.amzn2.x86_64 #1 SMP Mon Nov 1 20:58:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- **Deployment**: Docker 
- **Source Connector and version**:Posthog 0.1.4
- **Destination Connector and version**: Redshift 0.3.23
- **Severity**:  High
- **Step where error happened**:  Sync job 

PULL REQUEST CREATED BY POSTHOG For this issue:  https://github.com/airbytehq/airbyte/pull/9082
## Current Behavior
Sync fails with error

2021-12-22 10:46:02 [1;31mERROR[m i.a.w.DefaultReplicationWorker(run):141 - Sync worker failed.
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Source process exited with non-zero exit code 1
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:134) ~[io.airbyte-airbyte-workers-0.34.4-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:49) ~[io.airbyte-airbyte-workers-0.34.4-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:174) ~[io.airbyte-airbyte-workers-0.34.4-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
	Suppressed: io.airbyte.workers.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteSource.close(DefaultAirbyteSource.java:136) ~[io.airbyte-airbyte-workers-0.34.4-alpha.jar:?]
		at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:118) ~[io.airbyte-airbyte-workers-0.34.4-alpha.jar:?]
		at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:49) ~[io.airbyte-airbyte-workers-0.34.4-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:174) ~[io.airbyte-airbyte-workers-0.34.4-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:833) [?:?]
	Suppressed: io.airbyte.workers.WorkerException: Destination process exit with code 143. This warning is normal if the job was cancelled.
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.close(DefaultAirbyteDestination.java:119) ~[io.airbyte-airbyte-workers-0.34.4-alpha.jar:?]
		at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:118) ~[io.airbyte-airbyte-workers-0.34.4-alpha.jar:?]
		at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:49) ~[io.airbyte-airbyte-workers-0.34.4-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:174) ~[io.airbyte-airbyte-workers-0.34.4-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Source process exited with non-zero exit code 1
	at io.airbyte.workers.DefaultReplicationWorker.lambda$getReplicationRunnable$2(DefaultReplicationWorker.java:230) ~[io.airbyte-airbyte-workers-0.34.4-alpha.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
Caused by: java.lang.RuntimeException: Source process exited with non-zero exit code 1
	at io.airbyte.workers.DefaultReplicationWorker.lambda$getReplicationRunnable$2(DefaultReplicationWorker.java:222) ~[io.airbyte-airbyte-workers-0.34.4-alpha.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
2021-12-22 10:46:02 [32mINFO[m i.a.w.DefaultReplicationWorker(run):165 - sync summary: io.airbyte.config.ReplicationAttemptSummary@6fc9c92[status=failed,recordsSynced=5006702,bytesSynced=25486455595,startTime=1640110729635,endTime=1640169962072]
2021-12-22 10:46:02 [32mINFO[m i.a.w.DefaultReplicationWorker(run):174 - Source did not output any state messages
2021-12-22 10:46:02 [33mWARN[m i.a.w.DefaultReplicationWorker(run):182 - State capture: No new state, falling back on input state: io.airbyte.config.State@62d3f8d9[state={}]
2021-12-22 10:46:02 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):144 - Stopping cancellation check scheduling...
[logs-209-0 (1).txt](https://github.com/airbytehq/airbyte/files/7762578/logs-209-0.1.txt)

## Expected Behavior
sync to work

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

`

**Comment by nthbooth-feedr** [comment]
Posthog have created a pull request to fix this issue.

https://github.com/airbytehq/airbyte/pull/9082

Their description of the issue is as fllows:
Had a quick look, and it seems that airbyte is trying to scoop up more than we can offer. Namely it works well for all the events, but it gets stuck here, on EventsSessions. We recently removed this feature from PostHog, and the API endpoint errors. This endpoint was one very expensive calculation performed on top of the Events, so you're not losing any data with it being gone. You can now just use the session_id property of an event to split events into sessions yourself if you ever need to.

**Comment by nthbooth-feedr** [comment]
This has been addressed with the pull request from posthog.
