### ISSUE TITLE
🐛  Source Postgres: "Invalid value: null used for required field" with CDC syncs

### ISSUE THREAD

**Issue by smartpierre** [airbytehq/airbyte#9118]
## Environment
* **Airbyte version**:  0.35.1-alpha
* **OS Version / Instance**: Ubuntu 20.04 on AWS EC2
* **Deployment**: Docker
* **Source Connector and version**: Postgres 0.4.0
* **Destination Connector and version**: Snowflake 0.3.22
* **Severity**: Medium
* **Step where error happened**: Sync job

## Current Behavior
I've setup multiple connections to import several databases from a RDS PostgreSQL 13.3 to Snowflake.
On some database I have no problems, but on other when I try to do a sync I get this kind of errors :

```
2021-12-27 10:04:46 source > 2021-12-27 10:04:46 ERROR i.d.r.TableSchemaBuilder(lambda$createValueGenerator$5):269 - Failed to properly convert data value for 'public.record_record.region' of type varchar for row [268cc2f4-e36b-4196-8939-d0efeb9b613a, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null]:
2021-12-27 10:04:46 source > org.apache.kafka.connect.errors.DataException: Invalid value: null used for required field: "region", schema type: STRING
```

Whereas, when I lookup the row in my database, all fields with the PostgreSQL `NOT NULL` constraints are actually filled.

I tried to change the `REPLICATE IDENTITY` of the databases to `FULL` instead of letting Airbyte set it to `DEFAULT` as someone said in this issue https://github.com/airbytehq/airbyte/issues/8557 but it didn't fixed anything. And I believe it is not exactly the same issue, because they mention deleted records, when my error is occuring on records that are still in my tables.

## Logs
Here is the complete stack trace for this error.

<details>
<summary>LOG</summary> 

```
2021-12-27 10:04:46 source > 2021-12-27 10:04:46 ERROR i.d.r.TableSchemaBuilder(lambda$createValueGenerator$5):269 - Failed to properly convert data value for 'public.record_record.region' of type varchar for row [268cc2f4-e36b-4196-8939-d0efeb9b613a, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null]:
2021-12-27 10:04:46 source > org.apache.kafka.connect.errors.DataException: Invalid value: null used for required field: "region", schema type: STRING
2021-12-27 10:04:46 source > 	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:220) ~[connect-api-2.6.1.jar:?]
2021-12-27 10:04:46 source > 	at org.apache.kafka.connect.data.Struct.put(Struct.java:216) ~[connect-api-2.6.1.jar:?]
2021-12-27 10:04:46 source > 	at io.debezium.relational.TableSchemaBuilder.lambda$createValueGenerator$5(TableSchemaBuilder.java:265) ~[debezium-core-1.4.2.Final.jar:1.4.2.Final]
2021-12-27 10:04:46 source > 	at io.debezium.relational.TableSchema.valueFromColumnData(TableSchema.java:141) ~[debezium-core-1.4.2.Final.jar:1.4.2.Final]
2021-12-27 10:04:46 source > 	at io.debezium.relational.RelationalChangeRecordEmitter.emitUpdateRecord(RelationalChangeRecordEmitter.java:98) ~[debezium-core-1.4.2.Final.jar:1.4.2.Final]
2021-12-27 10:04:46 source > 	at io.debezium.relational.RelationalChangeRecordEmitter.emitChangeRecords(RelationalChangeRecordEmitter.java:51) ~[debezium-core-1.4.2.Final.jar:1.4.2.Final]
2021-12-27 10:04:46 source > 	at io.debezium.connector.postgresql.PostgresChangeRecordEmitter.emitChangeRecords(PostgresChangeRecordEmitter.java:88) ~[debezium-connector-postgres-1.4.2.Final.jar:1.4.2.Final]
2021-12-27 10:04:46 source > 	at io.debezium.pipeline.EventDispatcher.dispatchDataChangeEvent(EventDispatcher.java:198) ~[debezium-core-1.4.2.Final.jar:1.4.2.Final]
2021-12-27 10:04:46 source > 	at io.debezium.connector.postgresql.PostgresStreamingChangeEventSource.lambda$processMessages$0(PostgresStreamingChangeEventSource.java:226) ~[debezium-connector-postgres-1.4.2.Final.jar:1.4.2.Final]
2021-12-27 10:04:46 source > 	at io.debezium.connector.postgresql.connection.wal2json.NonStreamingWal2JsonMessageDecoder.processNotEmptyMessage(NonStreamingWal2JsonMessageDecoder.java:78) ~[debezium-connector-postgres-1.4.2.Final.jar:1.4.2.Final]
2021-12-27 10:04:46 source > 	at io.debezium.connector.postgresql.connection.AbstractMessageDecoder.processMessage(AbstractMessageDecoder.java:42) ~[debezium-connector-postgres-1.4.2.Final.jar:1.4.2.Final]
2021-12-27 10:04:46 source > 	at io.debezium.connector.postgresql.connection.PostgresReplicationConnection$1.deserializeMessages(PostgresReplicationConnection.java:482) ~[debezium-connector-postgres-1.4.2.Final.jar:1.4.2.Final]
2021-12-27 10:04:46 source > 	at io.debezium.connector.postgresql.connection.PostgresReplicationConnection$1.readPending(PostgresReplicationConnection.java:474) ~[debezium-connector-postgres-1.4.2.Final.jar:1.4.2.Final]
2021-12-27 10:04:46 source > 	at io.debezium.connector.postgresql.PostgresStreamingChangeEventSource.processMessages(PostgresStreamingChangeEventSource.java:185) ~[debezium-connector-postgres-1.4.2.Final.jar:1.4.2.Final]
2021-12-27 10:04:46 source > 	at io.debezium.connector.postgresql.PostgresStreamingChangeEventSource.execute(PostgresStreamingChangeEventSource.java:147) ~[debezium-connector-postgres-1.4.2.Final.jar:1.4.2.Final]
2021-12-27 10:04:46 source > 	at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:140) ~[debezium-core-1.4.2.Final.jar:1.4.2.Final]
2021-12-27 10:04:46 source > 	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:113) ~[debezium-core-1.4.2.Final.jar:1.4.2.Final]
2021-12-27 10:04:46 source > 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
2021-12-27 10:04:46 source > 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
2021-12-27 10:04:46 source > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
2021-12-27 10:04:46 source > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
2021-12-27 10:04:46 source > 	at java.lang.Thread.run(Thread.java:833) [?:?]

```

</details>

## Steps to Reproduce
1. Set up CDC replication from pg13 to snowflake on tables with `NOT NULL` constraints
1. Run sync

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202102171868563/1202126687154504) by [Unito](https://www.unito.io)

**Comment by smartpierre** [comment]
Update:

**I have no error on the first sync of the database.** But if I add records to a table with `NOT NULL` constraints, I get the error from Airbyte on the following sync.

**Comment by smartpierre** [comment]
Update:

We saw this error occuring on database **where we selected only some tables in the sync configuration**. When we select all tables, there are no errors and everything runs fine.

**Comment by alexchouraki** [comment]
Update:
With a CDC configuration. Incremental sync fails for several databases, always with the same type of error log:
2022-01-04 09:30:32 source > 2022-01-04 09:30:32 ERROR i.d.r.TableSchemaBuilder(lambda$createValueGenerator$5):269 - Failed to properly convert data value for 'public.content_pagerpage.content' of type varchar for row [86318, null, null, null, null, null]:
even though, when looking at the table, the row actually has values...

Pierre's message is about what happens when encountering this issue during first sync, and my message is just to add that this issue is also encountered during incremental syncs, even when the first sync was successful.

**Comment by smartpierre** [comment]
Hi again, we managed to go through this issue by setting the replica identity manually to `FULL` on tables that were causing issues. It's quite annoying since we don't have a way to anticipate thoses errors, here's our method to fix :

- Setup a PostgreSQL source with CDC using wal2json (we're on AWS RDS)
- Do the first sync on your connection (let Airbyte set the replica identity to default)
- Do some changes on your table (must have a NOT NULL constraint on a field)
- Incremental-Append sync should fail
- In pgsql run `ALTER TABLE my_table REPLICA IDENTITY FULL;`
- In pgsql, drop the replication slot and recreate it
- In Airbyte, reset the destination linked to the connection
- In Airbyte re-do the initial sync
- Incremental-Append sync should success

I hope this helps to reproduce, let me know if I can provide you with more data.

**Comment by sitepodmatt** [comment]
We're also seeing this. NOT NULL fields, it works for a few hours (varies after each reset), then we get error. I'll try smartpierre's suggestion

**Comment by alexandr-shegeda** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Java-Connectors-625f0102b11304001e0f6c6e/issues/airbytehq/airbyte/9118?planning-poker) with ZenHub @sashaNeshcheret @yurii-bidiuk @alexandertsukanov

**Comment by alexchouraki** [comment]
Hello,
@smartpierre's workaround works quite well, but it would be really nice to avoid having to deal with this issue 3 to 4 times a week... Any visibility on when this will be dealt with?

**Comment by yurii-bidiuk** [comment]
Hello @smartpierre
Could you please try to reproduce it with the latest version of the connector (now it's 0.4.18)
It could be fixed by #13016

**Comment by smartpierre** [comment]
Hello @yurii-bidiuk 
Sorry for the late answer, we didn't have this issue for the past weeks, so I would say it is fixed. 
It's quite complicated to test this for use without taking the chance of breaking something on production.
I think it's best to close this issue for now and if someone encounter it again, we will re-open.
Thank you for taking the time to work on it :)
Have a great day, Pierre.

**Comment by rohaldb** [comment]
I am experiencing this issue with latest version of PG connector. I get it for an array field on a table that is non nullable. Any suggestions?
