### ISSUE TITLE
🐛 Source Jira: Sync fails when custom field syncing is enabled 

### ISSUE THREAD

**Issue by nthbooth-feedr** [airbytehq/airbyte#9237]
## Environment
- **Airbyte version**: 0.35.2-alpha
- **OS Version / Instance**: AWS EC2 
- **Deployment**: Docker 
- **Source Connector and version**JIRA 0.2.18
- **Destination Connector and version**: Redshift 0.3.23
- **Severity**:  Medium 
- **Step where error happened**: Sync job 

## Current Behavior
Sync fails due to the custom fields api giving a 404
## Expected Behavior
it should work or maybe this api end point no longer exists.

## Logs
2021-12-31 10:45:59 [44msource[0m > Syncing stream: issue_custom_field_contexts 
2021-12-31 10:46:00 [44msource[0m > Encountered an exception while reading stream SourceJira
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 108, in read
    internal_config=internal_config,
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 141, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 213, in _read_full_refresh
    for record in records:
  File "/airbyte/integration_code/source_jira/streams.py", line 466, in read_records
    yield from super().read_records(stream_slice={"field_id": field["id"]}, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 352, in read_records
    response = self._send_request(request, request_kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 319, in _send_request
    return backoff_handler(user_backoff_handler)(request, request_kwargs)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 285, in _send
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://teamfeedr.atlassian.net/rest/api/3/field/customfield_10074/context
2021-12-31 10:46:00 [44msource[0m > Finished syncing SourceJira
2021-12-31 10:46:00 [44msource[0m > SourceJira runtimes:

2021-12-31 10:46:00 [44msource[0m > 404 Client Error: Not Found for url: https://teamfeedr.atlassian.net/rest/api/3/field/customfield_10074/context
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 116, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 107, in run
    for message in generator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 112, in read
    raise e
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 108, in read
    internal_config=internal_config,
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 141, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 213, in _read_full_refresh
    for record in records:
  File "/airbyte/integration_code/source_jira/streams.py", line 466, in read_records
    yield from super().read_records(stream_slice={"field_id": field["id"]}, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 352, in read_records
    response = self._send_request(request, request_kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 319, in _send_request
    return backoff_handler(user_backoff_handler)(request, request_kwargs)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 285, in _send
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://teamfeedr.atlassian.net/rest/api/3/field/customfield_10074/contex
[logs-286-1.txt](https://github.com/airbytehq/airbyte/files/7796304/logs-286-1.txt)
[logs-286-1.txt](https://github.com/airbytehq/airbyte/files/7796310/logs-286-1.txt)
t

**Comment by alafanechere** [comment]
HI @nthbooth-feedr, a similar issue was opened here: https://github.com/airbytehq/airbyte/issues/9218 
Feel free to subscribe to it to receive updates.
