### ISSUE TITLE
🐛 Source Slack: more specific typing required for `pending_shared` field

### ISSUE THREAD

**Issue by octavia-squidington-iii** [airbytehq/airbyte#9252]
Is this your first time deploying Airbyte: Yes
OS Version / Instance: EC2 t2.large
Memory / Disk: 8Gb / 40 gb
Deployment: Docker
Airbyte Version: 0.34.4-alpha
Source name/version: source-slack:0.1.13
Destination name/version: destination-s3:0.2.0
Step: On sync
Description: Conversion of `channel_messages` to Parquet, Avro or JSON fails because the items of the field `pending_shared` have no type:

````
2021-12-29 05:56:47 [43mdestination[0m > Exception in thread "main" java.lang.IllegalStateException: Field pending_shared.items has no type
2021-12-29 05:56:47 [43mdestination[0m > 	at io.airbyte.integrations.destination.s3.avro.JsonToAvroSchemaConverter.getTypes(JsonToAvroSchemaConverter.java:63)
2021-12-29 05:56:47 [43mdestination[0m > 	at io.airbyte.integrations.destination.s3.avro.JsonToAvroSchemaConverter.getNonNullTypes(JsonToAvroSchemaConverter.java:51)
2021-12-29 05:56:47 [43mdestination[0m > 	at io.airbyte.integrations.destination.s3.avro.JsonToAvroSchemaConverter.getNullableFieldTypes(JsonToAvroSchemaConverter.java:237)
2021-12-29 05:56:47 [43mdestination[0m > 	at io.airbyte.integrations.destination.s3.avro.JsonToAvroSchemaConverter.getSingleFieldType(JsonToAvroSchemaConverter.java:200)
2021-12-29 05:56:47 [43mdestination[0m > 	at io.airbyte.integrations.destination.s3.avro.JsonToAvroSchemaConverter.lambda$getNullableFieldTypes$4(JsonToAvroSchemaConverter.java:240)
2021-12-29 05:56:47 [43mdestination[0m > 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
2021-12-29 05:56:47 [43mdestination[0m > 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
2021-12-29 05:56:47 [43mdestination[0m > 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
2021-12-29 05:56:47 [43mdestination[0m > 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
2021-12-29 05:56:47 [43mdestination[0m > 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
2021-12-29 05:56:47 [43mdestination[0m > 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2021-12-29 05:56:47 [43mdestination[0m > 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
2021-12-29 05:56:47 [43mdestination[0m > 	at io.airbyte.integrations.destination.s3.avro.JsonToAvroSchemaConverter.getNullableFieldTypes(JsonToAvroSchemaConverter.java:248)
2021-12-29 05:56:47 [43mdestination[0m > 	at io.airbyte.integrations.destination.s3.avro.JsonToAvroSchemaConverter.getAvroSchema(JsonToAvroSchemaConverter.java:153)
2021-12-29 05:56:47 [43mdestination[0m > 	at io.airbyte.integrations.destination.s3.writer.ProductionWriterFactory.create(ProductionWriterFactory.java:40)
2021-12-29 05:56:47 [43mdestination[0m > 	at io.airbyte.integrations.destination.s3.S3Consumer.startTracked(S3Consumer.java:53)
2021-12-29 05:56:47 [43mdestination[0m > 	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.start(FailureTrackingAirbyteMessageConsumer.java:34)
2021-12-29 05:56:47 [43mdestination[0m > 	at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:142)
2021-12-29 05:56:47 [43mdestination[0m > 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:128)
2021-12-29 05:56:47 [43mdestination[0m > 	at io.airbyte.integrations.destination.s3.S3Destination.main(S3Destination.java:30)
````

The sync works with CSV (though there is a warning on schema validation). Parquet, Avro, JSON are failing.

[Related slack conversation
]( https://airbytehq.slack.com/archives/C01MFR03D5W/p1640758132458900?thread_ts=1640758132.458900&cid=C01MFR03D5W)

### Logs:
[logs-507-0.txt](https://github.com/airbytehq/airbyte/files/7803031/logs-507-0.txt)

**Comment by tuliren** [comment]
The root cause is that the `pending_shared` field is an arry of unknown types:

```json
"pending_shared": {
  "type": "array",
  "items": {}
}
```

I will update the Json to Avro schema converter to default the array element type to `string`.

The better way to fix it is to update the `items` with the correct `type`. However, Slack API doc does not specify what type is array should be:

https://api.slack.com/methods/conversations.list
```json
"pending_shared": [],
```
