### ISSUE TITLE
Investigate source database benchmark sync failures

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#9325]
The benchmark syncs run in [this workspace](https://cloud.airbyte.io/workspaces/a3554b53-fcc3-4236-8b83-d0e367489b21/connections). They're meant to run regularly so that we can track performance over time, but have been failing for a while. We should figure out why they're failing and then fix them.

Potentially related issue: https://github.com/airbytehq/airbyte/issues/8284

**Comment by grishick** [comment]
I tried running a job with postgres source and it ran out of memory: https://cloud.airbyte.io/workspaces/a3554b53-fcc3-4236-8b83-d0e367489b21/connections/79d99d5d-a407-405f-9b6c-45166169c4f3/status

**Comment by noahkawasaki-airbyte** [comment]
Doing some initial troubleshooting:

MSSQL: seems like we just need to reset a password or something, might just be an expired username/password:

```
2022-04-19 21:04:19 source > Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Cannot open database "newsmall1000tableswith10000rows" requested by the login. The login failed. ClientConnectionId:94b81f8d-2134-412f-803e-fff26cadcd71
2022-04-19 21:04:19 source > 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
2022-04-19 21:04:19 source > 	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:283)
2022-04-19 21:04:19 source > 	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:129)
```

MySQL: Seems like we've renamed/deleted an expected database

```
2022-04-19 21:05:16 source > Exception in thread "main" java.sql.SQLException: Cannot create PoolableConnectionFactory (Unknown database 'newsmall1000tableswith10000rows')
2022-04-19 21:05:16 source > 	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:669)
2022-04-19 21:05:16 source > 	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:544)
```

Postgres: Same deal, memory issues

```
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: org.postgresql.util.PSQLException: Ran out of memory retrieving query results.
2022-04-19 21:07:37 source > 	at io.airbyte.integrations.source.relationaldb.AbstractRelationalDbSource.lambda$queryTable$0(AbstractRelationalDbSource.java:64)
2022-04-19 21:07:37 source > 	at io.airbyte.commons.util.LazyAutoCloseableIterator.computeNext(LazyAutoCloseableIterator.java:37)
```

**Comment by noahkawasaki-airbyte** [comment]
Found the updated benchmark database information from https://github.com/airbytehq/airbyte/pull/9597/files

**Comment by noahkawasaki-airbyte** [comment]
Most connections are set up again with green status: https://cloud.airbyte.io/workspaces/a3554b53-fcc3-4236-8b83-d0e367489b21/connections

<img width="1409" alt="Screen Shot 2022-04-20 at 11 47 50 AM" src="https://user-images.githubusercontent.com/103465980/164301498-7d2ad0c4-a9ef-4e4d-bc5b-5a5772732739.png">

The Sources connections for each (postgres, mssql, mysql) cannot handle the database `t1000_c240_r200` and fail with "Failed to fetch schema" errors. Seems we need to improve how we handle schemas/databases with many columns
