### ISSUE TITLE
File Source Manual Testing issues.

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#935]
In general we need to add how to use each of the different file sources in the documentation. Right now I had to guess and had trouble figuring out the right configuration to make them work.

HTTPS:
* Why is the file name needed in two places?

![Screen Shot 2020-11-11 at 9 43 31 PM](https://user-images.githubusercontent.com/9092207/98900645-1061ac00-2467-11eb-84e9-615eeee3633b.png)

Local:
* Not sure how to make this works. Maybe it's just not compatible with mac. The error:
```
airbyte-scheduler | 2020-11-12 05:45:54 ERROR i.a.w.p.a.DefaultAirbyteStreamFactory(internalLog):108 - {job_id=166, job_log_filename=logs.log, job_root=/tmp/workspace/166/0} - Failed to load file:///tmp/airbyte_local/edge_case_messages.txt: FileNotFoundError(2, 'No such file or directory')
```

AWS:
* Failing with a dependency issues:
```
airbyte-scheduler | 2020-11-12 05:48:01 INFO i.a.w.p.a.DefaultAirbyteStreamFactory(internalLog):110 - {job_id=170, job_log_filename=logs.log, job_root=/tmp/workspace/170/0} - Checking access to s3://airbyte.public.test/edge_case_messages.txt...
airbyte-scheduler | 2020-11-12 05:48:01 ERROR i.a.w.p.a.DefaultAirbyteStreamFactory(internalLog):108 - {job_id=170, job_log_filename=logs.log, job_root=/tmp/workspace/170/0} - Failed to load s3://airbyte.public.test/edge_case_messages.txt: ImportError('You are trying to use the s3 functionality of smart_open\nbut you do not have the correct s3 dependencies installed. Try:\n\n    pip install smart_open[s3]\n\n')
airbyte-scheduler | Traceback (most recent call last):
airbyte-scheduler |   File "/usr/local/lib/python3.7/site-packages/source_file/source.py", line 101, in check
airbyte-scheduler |     SourceFile.open_file_url(config, logger)
airbyte-scheduler |   File "/usr/local/lib/python3.7/site-packages/source_file/source.py", line 237, in open_file_url
airbyte-scheduler |     result = open(f"{storage}{url}")
airbyte-scheduler |   File "/usr/local/lib/python3.7/site-packages/smart_open/smart_open_lib.py", line 222, in open
airbyte-scheduler |     binary = _open_binary_stream(uri, binary_mode, transport_params)
airbyte-scheduler |   File "/usr/local/lib/python3.7/site-packages/smart_open/smart_open_lib.py", line 323, in _open_binary_stream
airbyte-scheduler |     submodule = transport.get_transport(scheme)
airbyte-scheduler |   File "/usr/local/lib/python3.7/site-packages/smart_open/transport.py", line 90, in get_transport
airbyte-scheduler |     raise ImportError(_MISSING_DEPS_ERROR % dict(module=_ERRORS[scheme]))
airbyte-scheduler | ImportError: You are trying to use the s3 functionality of smart_open
airbyte-scheduler | but you do not have the correct s3 dependencies installed. Try:
airbyte-scheduler |
airbyte-scheduler |     pip install smart_open[s3]
airbyte-scheduler |
airbyte-scheduler |
airbyte-scheduler |
airbyte-scheduler | 2020-11-12 05:48:01 ERROR i.a.w.p.a.DefaultAirbyteStreamFactory(internalLog):108 - {job_id=170, job_log_filename=logs.log, job_root=/tmp/workspace/170/0} - Check failed
airbyte-scheduler | 2020-11-12 05:48:02 DEBUG i.a.w.DefaultCheckConnectionWorker(run):96 - {job_id=170, job_log_filename=logs.log, job_root=/tmp/workspace/170/0} - Check connection job subprocess finished with exit code 0
airbyte-scheduler | 2020-11-12 05:48:02 DEBUG i.a.w.DefaultCheckConnectionWorker(run):97 - {job_id=170, job_log_filename=logs.log, job_root=/tmp/workspace/170/0} - Check connection job received output: io.airbyte.config.StandardCheckConnectionOutput@178602e8[status=failed,message=Failed to load s3://airbyte.public.test/edge_case_messages.txt: ImportError('You are trying to use the s3 functionality of smart_open\nbut you do not have the correct s3 dependencies installed. Try:\n\n    pip install smart_open[s3]\n\n')
airbyte-scheduler | Traceback (most recent call last):
airbyte-scheduler |   File "/usr/local/lib/python3.7/site-packages/source_file/source.py", line 101, in check
airbyte-scheduler |     SourceFile.open_file_url(config, logger)
airbyte-scheduler |   File "/usr/local/lib/python3.7/site-packages/source_file/source.py", line 237, in open_file_url
airbyte-scheduler |     result = open(f"{storage}{url}")
airbyte-scheduler |   File "/usr/local/lib/python3.7/site-packages/smart_open/smart_open_lib.py", line 222, in open
airbyte-scheduler |     binary = _open_binary_stream(uri, binary_mode, transport_params)
airbyte-scheduler |   File "/usr/local/lib/python3.7/site-packages/smart_open/smart_open_lib.py", line 323, in _open_binary_stream
airbyte-scheduler |     submodule = transport.get_transport(scheme)
airbyte-scheduler |   File "/usr/local/lib/python3.7/site-packages/smart_open/transport.py", line 90, in get_transport
airbyte-scheduler |     raise ImportError(_MISSING_DEPS_ERROR % dict(module=_ERRORS[scheme]))
airbyte-scheduler | ImportError: You are trying to use the s3 functionality of smart_open
airbyte-scheduler | but you do not have the correct s3 dependencies installed. Try:
airbyte-scheduler |
airbyte-scheduler |     pip install smart_open[s3]
airbyte-scheduler |
airbyte-scheduler |
airbyte-scheduler | ]
```

GCS
* was not able to pull a public data set without credentials.

**Comment by jrhizor** [comment]
Local file also needs the URL and filename.

**Comment by ChristopheDuong** [comment]
The filename  is the stream name that will dictate how the final table will be called and should follow the standard naming without special characters whereas URL can be quite complicated...

And yes, all providers need both URL and filename

**Comment by cgardens** [comment]
@ChristopheDuong - I think adding docs will help with this. You mind doing that and then we can see if the doc resolve all of the blocker I ran into?

**Comment by ChristopheDuong** [comment]
> Local: Not sure how to make this works. Maybe it's just not compatible with mac. The error:

What URL did you put in your tests?
 
1. `file:///tmp/airbyte_local/edge_case_messages.txt`
1. `/local/edge_case_messages.txt`

I've tried both and only the second one works (inside docker)
