### ISSUE TITLE
UnknownHostException for other docker container name

### ISSUE THREAD

**Issue by raphaelauv** [airbytehq/airbyte#9468]
## Environment
- **Airbyte version**: 0.35.4-alpha
- **OS Version / Instance**: Linux  5.11.0-46-generic 20.04.1-Ubuntu 
- **Docker version** : 20.10.12
- **Docker-compose version** : 1.29.1 build c34c88b2
- **Deployment**: local with docker-compose
- **Destination Connector and version**:  S3 - > 0.2.3
- **Severity**: High 
- **Step where error happened**: creation of a S3 destination connector to a dockerize minio
- 
## Current Behavior
If I give the name of a container ( that is part of the docker-compose network of airbyte)

![Screenshot from 2022-01-13 12-10-44](https://user-images.githubusercontent.com/10202690/149319784-57d9e07e-5c30-4e2a-8ccf-1de706c677ca.png)

 it fail to resolve the HostName

![Screenshot from 2022-01-13 10-26-02](https://user-images.githubusercontent.com/10202690/149302636-5563d31c-08d0-4af7-aed5-c609db90107c.png)

but if I try to curl it directly from a terminal inside the airbyte container if work

```shell
root@753893a38bc7:/app# curl http://minio:9000
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Resource>/</Resource><Region>eu-west-3</Region><RequestId>16C9C96B80C1D06C</RequestId><HostId>2bcb1593-7ee0-41fd-82dc-5609236160fb</HostId></Error>root@753893a38bc7:/app# 
```

## Expected Behavior
the creation of the destination should work without setting manually the ip of the container

![Screenshot from 2022-01-13 10-24-46](https://user-images.githubusercontent.com/10202690/149302466-952759fc-1791-43f6-9c42-97d4dee87c5b.png)

## Logs

```
2022-01-13 09:11:01 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):118 - Docker volume job log path: /tmp/workspace/825b9bb6-cf1e-494c-a497-f66be3b3c08b/0/logs.log
2022-01-13 09:11:01 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):123 - Executing worker wrapper. Airbyte version: version not set
2022-01-13 09:11:01 [32mINFO[m i.a.c.i.LineGobbler(voidCall):82 - Checking if airbyte/destination-s3:0.2.2 exists...
2022-01-13 09:11:01 [32mINFO[m i.a.c.i.LineGobbler(voidCall):82 - airbyte/destination-s3:0.2.2 was found locally.
2022-01-13 09:11:01 [32mINFO[m i.a.w.p.DockerProcessFactory(create):171 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/825b9bb6-cf1e-494c-a497-f66be3b3c08b/0 --network host --log-driver none airbyte/destination-s3:0.2.2 check --config source_config.json
2022-01-13 09:11:01 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):82 - SLF4J: Class path contains multiple SLF4J bindings.
2022-01-13 09:11:01 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):82 - SLF4J: Found binding in [jar:file:/airbyte/lib/log4j-slf4j-impl-2.16.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2022-01-13 09:11:01 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):82 - SLF4J: Found binding in [jar:file:/airbyte/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2022-01-13 09:11:01 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):82 - SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
2022-01-13 09:11:01 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):82 - SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
2022-01-13 09:11:01 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-01-13 09:11:01 [32mINFO[m i.a.i.b.IntegrationRunner(run):76 - Running integration: io.airbyte.integrations.destination.s3.S3Destination
2022-01-13 09:11:01 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-01-13 09:11:01 [32mINFO[m i.a.i.b.IntegrationCliParser(parseOptions):118 - integration args: {check=null, config=source_config.json}
2022-01-13 09:11:01 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-01-13 09:11:01 [32mINFO[m i.a.i.b.IntegrationRunner(run):80 - Command: CHECK
2022-01-13 09:11:01 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-01-13 09:11:01 [32mINFO[m i.a.i.b.IntegrationRunner(run):81 - Integration config: IntegrationConfig{command=CHECK, configPath='source_config.json', catalogPath='null', statePath='null'}
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-01-13 09:11:02 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword examples - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-01-13 09:11:02 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-01-13 09:11:02 [32mINFO[m i.a.i.d.s.S3FormatConfigs(getS3FormatConfig):22 - S3 format config: {"part_size_mb":5,"format_type":"JSONL"}
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-01-13 09:11:02 [1;31mERROR[m i.a.i.d.s.S3Destination(check):39 - Exception attempting to access the S3 bucket: 
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - com.amazonaws.SdkClientException: Unable to execute HTTP request: minio
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1207) ~[aws-java-sdk-core-1.12.6.jar:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1153) ~[aws-java-sdk-core-1.12.6.jar:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802) ~[aws-java-sdk-core-1.12.6.jar:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770) ~[aws-java-sdk-core-1.12.6.jar:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744) ~[aws-java-sdk-core-1.12.6.jar:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704) ~[aws-java-sdk-core-1.12.6.jar:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686) ~[aws-java-sdk-core-1.12.6.jar:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550) ~[aws-java-sdk-core-1.12.6.jar:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530) ~[aws-java-sdk-core-1.12.6.jar:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5437) ~[aws-java-sdk-s3-1.12.6.jar:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5384) ~[aws-java-sdk-s3-1.12.6.jar:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at com.amazonaws.services.s3.AmazonS3Client.access$300(AmazonS3Client.java:421) ~[aws-java-sdk-s3-1.12.6.jar:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at com.amazonaws.services.s3.AmazonS3Client$PutObjectStrategy.invokeServiceCall(AmazonS3Client.java:6508) ~[aws-java-sdk-s3-1.12.6.jar:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1856) ~[aws-java-sdk-s3-1.12.6.jar:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1816) ~[aws-java-sdk-s3-1.12.6.jar:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:3982) ~[aws-java-sdk-s3-1.12.6.jar:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.destination.s3.S3Destination.attemptWriteAndDeleteS3Object(S3Destination.java:73) ~[io.airbyte.airbyte-integrations.connectors-destination-s3-0.34.4-alpha.jar:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.destination.s3.S3Destination.attemptS3WriteAndDelete(S3Destination.java:67) ~[io.airbyte.airbyte-integrations.connectors-destination-s3-0.34.4-alpha.jar:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.destination.s3.S3Destination.attemptS3WriteAndDelete(S3Destination.java:60) ~[io.airbyte.airbyte-integrations.connectors-destination-s3-0.34.4-alpha.jar:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.destination.s3.S3Destination.check(S3Destination.java:36) [io.airbyte.airbyte-integrations.connectors-destination-s3-0.34.4-alpha.jar:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:102) [io.airbyte.airbyte-integrations.bases-base-java-0.34.4-alpha.jar:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.destination.s3.S3Destination.main(S3Destination.java:30) [io.airbyte.airbyte-integrations.connectors-destination-s3-0.34.4-alpha.jar:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - Caused by: java.net.UnknownHostException: minio
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at java.net.InetAddress$CachedAddresses.get(InetAddress.java:801) ~[?:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at java.net.InetAddress.getAllByName0(InetAddress.java:1509) ~[?:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at java.net.InetAddress.getAllByName(InetAddress.java:1367) ~[?:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at java.net.InetAddress.getAllByName(InetAddress.java:1301) ~[?:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at com.amazonaws.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:27) ~[aws-java-sdk-core-1.12.6.jar:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at com.amazonaws.http.DelegatingDnsResolver.resolve(DelegatingDnsResolver.java:38) ~[aws-java-sdk-core-1.12.6.jar:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112) ~[httpclient-4.5.13.jar:4.5.13]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient-4.5.13.jar:4.5.13]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76) ~[aws-java-sdk-core-1.12.6.jar:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at com.amazonaws.http.conn.$Proxy31.connect(Unknown Source) ~[?:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.13.jar:4.5.13]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.13.jar:4.5.13]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.13.jar:4.5.13]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.13.jar:4.5.13]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.13.jar:4.5.13]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.13.jar:4.5.13]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72) ~[aws-java-sdk-core-1.12.6.jar:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1331) ~[aws-java-sdk-core-1.12.6.jar:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145) ~[aws-java-sdk-core-1.12.6.jar:?]
2022-01-13 09:11:02 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 	... 20 more
2022-01-13 09:11:02 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):144 - Stopping cancellation check scheduling...

```

</details>

## Are you willing to submit a PR?
no

**Comment by jrhizor** [comment]
The launched sync jobs use the host network by default. You can change that by specifying `DOCKER_NETWORK` in your `.env` file. 

So you can either change the Docker network to access only containers running within the airbyte network or you can run your minio container on the host network so you can access both it and any other container that you may want to run on the host networking.

**Comment by raphaelauv** [comment]
Thank you for your help, it work.

Some details for the future 

so I add to the .env file this line

```env
DOCKER_NETWOR=toto_network
```

because I add to the docker-compose.yam file of airbyte , these lines : 

```yaml
networks:
  default:
    external: true
    name: toto_network
```
