### ISSUE TITLE
🐛 Source Snowflake: Expiring token on Snowflake connector

### ISSUE THREAD

**Issue by AM-I-Human** [airbytehq/airbyte#9469]
## Environment
- **Airbyte version**:  0.33.9-alpha
- **OS Version / Instance**: Doker on swarm (don't know on which machine is but are all linux based)
- **Deployment**: Custom Doker Swarm
- **Source Connector and version**: Snowflake 0.1.2
- **Destination Connector and version**: Mongodb 0.1.0
- **Severity**: Very Low / Low / Medium / High / Critical: High
- **Step where error happened**:  Sync job 

## Current Behavior
When the job is long the token expires.
After the error the job hang on sync status

## Expected Behavior
The connection will be reestablish on 400 errors
IF an error happen the job is marked as broken/on error status

## Logs
<details>
<summary>LOG</summary> 

```
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - Jan 12, 2022 5:43:25 PM net.snowflake.client.jdbc.RestRequest execute
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - SEVERE: Error response: HTTP Response code: 403, request: GET https://sfc-ie-ds1-9-customer-stage.s3.eu-west-1.amazonaws.com/uvih-s-iest5312/results/01a19073-3201-2922-0000-d6f9000eb6ea_0/main/data_0_2_38?x-amz-server-side-encryption-customer-algorithm=AES256&response-content-encoding=gzip&AWSAccessKeyId=****&Expires=1642008824&Signature=**** HTTP/1.1
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - Jan 12, 2022 5:43:25 PM net.snowflake.client.jdbc.SnowflakeChunkDownloader$2 getInputStream
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - SEVERE: Error fetching chunk from: https://sfc-ie-ds1-9-customer-stage.s3.eu-west-1.amazonaws.com/uvih-s-iest5312/results/01a19073-3201-2922-0000-d6f9000eb6ea_0/main/data_0_2_38?x-amz-server-side-encryption-customer-algorithm=AES256&response-content-encoding=gzip&AWSAccessKeyId=****&Expires=1642008824&Signature=****
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - Jan 12, 2022 5:43:25 PM net.snowflake.client.jdbc.SnowflakeUtil logResponseDetails
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - SEVERE: Response status line reason: Forbidden
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - Jan 12, 2022 5:43:25 PM net.snowflake.client.jdbc.SnowflakeUtil logResponseDetails
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - SEVERE: Response content: <?xml version="1.0" encoding="UTF-8"?>
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - <Error><Code>AccessDenied</Code><Message>Request has expired</Message><Expires>2022-01-12T17:33:44Z</Expires><ServerTime>2022-01-12T17:43:26Z</ServerTime><RequestId>3HGV34DVZTZTES6R</RequestId><HostId>O4y/ptUvGJYF3U5y25yHNQmMBlarrfCAaKxB5f2AozUp+0czi3ZzuH4GhUpPMBofbBeWKoqpio8=</HostId></Error>
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - Exception in thread "main" java.lang.RuntimeException: net.snowflake.client.jdbc.SnowflakeSQLLoggedException: JDBC driver internal error: Max retry reached for the download of #chunk78 (Total chunks: 160) retry=10, error=net.snowflake.client.jdbc.SnowflakeSQLException: JDBC driver encountered communication error. Message: Error encountered when downloading a result chunk: HTTP status=403.
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at net.snowflake.client.jdbc.SnowflakeChunkDownloader$2.getInputStream(SnowflakeChunkDownloader.java:803)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at net.snowflake.client.jdbc.SnowflakeChunkDownloader$2.call(SnowflakeChunkDownloader.java:947)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at net.snowflake.client.jdbc.SnowflakeChunkDownloader$2.call(SnowflakeChunkDownloader.java:766)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at java.base/java.lang.Thread.run(Thread.java:832)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - .
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.db.jdbc.JdbcSourceOperations$1.tryAdvance(JdbcSourceOperations.java:55)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.commons.util.LazyAutoCloseableIterator.computeNext(LazyAutoCloseableIterator.java:42)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.commons.util.CompositeIterator.computeNext(CompositeIterator.java:63)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:119)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.source.snowflake.SnowflakeSource.main(SnowflakeSource.java:30)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	Suppressed: java.lang.RuntimeException: net.snowflake.client.jdbc.SnowflakeReauthenticationRequest: Authentication token has expired.  The user must authenticate again.
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 		at io.airbyte.db.jdbc.StreamingJdbcDatabase.lambda$query$0(StreamingJdbcDatabase.java:100)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 		at java.base/java.util.stream.AbstractPipeline.close(AbstractPipeline.java:323)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 		at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 		at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:49)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 		at io.airbyte.commons.util.LazyAutoCloseableIterator.close(LazyAutoCloseableIterator.java:52)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 		at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 		at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:49)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 		at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 		at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:49)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 		at io.airbyte.commons.util.CompositeIterator.close(CompositeIterator.java:91)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 		at io.airbyte.commons.util.AutoCloseableIterators.lambda$appendOnClose$0(AutoCloseableIterators.java:88)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 		at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 		at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:49)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 		at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:118)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 		... 1 more
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	Caused by: net.snowflake.client.jdbc.SnowflakeReauthenticationRequest: Authentication token has expired.  The user must authenticate again.
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 		at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:121)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 		at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionIncludingReauth(SnowflakeUtil.java:60)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 		at net.snowflake.client.core.SessionUtil.tokenRequest(SessionUtil.java:819)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 		at net.snowflake.client.core.SessionUtil.renewSession(SessionUtil.java:738)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 		at net.snowflake.client.core.SFSession.renewSession(SFSession.java:816)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 		at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:507)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 		at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:229)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 		at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:167)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 		at net.snowflake.client.core.SFStatement.execute(SFStatement.java:749)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 		at net.snowflake.client.jdbc.SnowflakeStatementV1.executeInternal(SnowflakeStatementV1.java:292)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 		at net.snowflake.client.jdbc.SnowflakeStatementV1.execute(SnowflakeStatementV1.java:342)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 		at net.snowflake.client.jdbc.SnowflakeConnectionV1.executeImmediate(SnowflakeConnectionV1.java:225)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 		at net.snowflake.client.jdbc.SnowflakeConnectionV1.setAutoCommit(SnowflakeConnectionV1.java:384)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 		at org.apache.commons.dbcp2.DelegatingConnection.setAutoCommit(DelegatingConnection.java:537)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 		at org.apache.commons.dbcp2.DelegatingConnection.setAutoCommit(DelegatingConnection.java:537)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 		at io.airbyte.db.jdbc.StreamingJdbcDatabase.lambda$query$0(StreamingJdbcDatabase.java:97)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 		... 14 more
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - Caused by: net.snowflake.client.jdbc.SnowflakeSQLLoggedException: JDBC driver internal error: Max retry reached for the download of #chunk78 (Total chunks: 160) retry=10, error=net.snowflake.client.jdbc.SnowflakeSQLException: JDBC driver encountered communication error. Message: Error encountered when downloading a result chunk: HTTP status=403.
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at net.snowflake.client.jdbc.SnowflakeChunkDownloader$2.getInputStream(SnowflakeChunkDownloader.java:803)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at net.snowflake.client.jdbc.SnowflakeChunkDownloader$2.call(SnowflakeChunkDownloader.java:947)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at net.snowflake.client.jdbc.SnowflakeChunkDownloader$2.call(SnowflakeChunkDownloader.java:766)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at java.base/java.lang.Thread.run(Thread.java:832)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - .
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at net.snowflake.client.jdbc.SnowflakeChunkDownloader.getNextChunkToConsume(SnowflakeChunkDownloader.java:518)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at net.snowflake.client.core.SFArrowResultSet.fetchNextRowUnsorted(SFArrowResultSet.java:227)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at net.snowflake.client.core.SFArrowResultSet.fetchNextRow(SFArrowResultSet.java:204)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at net.snowflake.client.core.SFArrowResultSet.next(SFArrowResultSet.java:340)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at net.snowflake.client.jdbc.SnowflakeResultSetV1.next(SnowflakeResultSetV1.java:97)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at org.apache.commons.dbcp2.DelegatingResultSet.next(DelegatingResultSet.java:1160)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at org.apache.commons.dbcp2.DelegatingResultSet.next(DelegatingResultSet.java:1160)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.db.jdbc.JdbcSourceOperations$1.tryAdvance(JdbcSourceOperations.java:49)
[34msource[0m - 2022-01-12 17:43:26 ERROR () LineGobbler(voidCall):82 - 	... 24 more
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-01-12 17:43:25 [1;31mERROR[m i.a.c.u.CompositeIterator(close):93 - {} - exception while closing
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - java.lang.RuntimeException: net.snowflake.client.jdbc.SnowflakeReauthenticationRequest: Authentication token has expired.  The user must authenticate again.
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.db.jdbc.StreamingJdbcDatabase.lambda$query$0(StreamingJdbcDatabase.java:100) ~[io.airbyte.airbyte-db-lib-0.30.21-alpha.jar:?]
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at java.util.stream.AbstractPipeline.close(AbstractPipeline.java:323) ~[?:?]
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15) ~[io.airbyte-airbyte-commons-0.30.21-alpha.jar:?]
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:49) ~[io.airbyte-airbyte-commons-0.30.21-alpha.jar:?]
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.commons.util.LazyAutoCloseableIterator.close(LazyAutoCloseableIterator.java:52) ~[io.airbyte-airbyte-commons-0.30.21-alpha.jar:?]
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15) ~[io.airbyte-airbyte-commons-0.30.21-alpha.jar:?]
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:49) ~[io.airbyte-airbyte-commons-0.30.21-alpha.jar:?]
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15) ~[io.airbyte-airbyte-commons-0.30.21-alpha.jar:?]
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:49) ~[io.airbyte-airbyte-commons-0.30.21-alpha.jar:?]
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.commons.util.CompositeIterator.close(CompositeIterator.java:91) ~[io.airbyte-airbyte-commons-0.30.21-alpha.jar:?]
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.commons.util.AutoCloseableIterators.lambda$appendOnClose$0(AutoCloseableIterators.java:88) ~[io.airbyte-airbyte-commons-0.30.21-alpha.jar:?]
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15) [io.airbyte-airbyte-commons-0.30.21-alpha.jar:?]
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:49) [io.airbyte-airbyte-commons-0.30.21-alpha.jar:?]
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:118) [io.airbyte.airbyte-integrations.bases-base-java-0.30.21-alpha.jar:?]
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.source.snowflake.SnowflakeSource.main(SnowflakeSource.java:30) [io.airbyte.airbyte-integrations.connectors-source-snowflake-0.30.21-alpha.jar:?]
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - Caused by: net.snowflake.client.jdbc.SnowflakeReauthenticationRequest: Authentication token has expired.  The user must authenticate again.
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:121) ~[snowflake-jdbc-3.12.14.jar:3.12.14]
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionIncludingReauth(SnowflakeUtil.java:60) ~[snowflake-jdbc-3.12.14.jar:3.12.14]
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at net.snowflake.client.core.SessionUtil.tokenRequest(SessionUtil.java:819) ~[snowflake-jdbc-3.12.14.jar:3.12.14]
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at net.snowflake.client.core.SessionUtil.renewSession(SessionUtil.java:738) ~[snowflake-jdbc-3.12.14.jar:3.12.14]
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at net.snowflake.client.core.SFSession.renewSession(SFSession.java:816) ~[snowflake-jdbc-3.12.14.jar:3.12.14]
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:507) ~[snowflake-jdbc-3.12.14.jar:3.12.14]
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:229) ~[snowflake-jdbc-3.12.14.jar:3.12.14]
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:167) ~[snowflake-jdbc-3.12.14.jar:3.12.14]
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:749) ~[snowflake-jdbc-3.12.14.jar:3.12.14]
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeInternal(SnowflakeStatementV1.java:292) ~[snowflake-jdbc-3.12.14.jar:3.12.14]
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at net.snowflake.client.jdbc.SnowflakeStatementV1.execute(SnowflakeStatementV1.java:342) ~[snowflake-jdbc-3.12.14.jar:3.12.14]
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at net.snowflake.client.jdbc.SnowflakeConnectionV1.executeImmediate(SnowflakeConnectionV1.java:225) ~[snowflake-jdbc-3.12.14.jar:3.12.14]
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at net.snowflake.client.jdbc.SnowflakeConnectionV1.setAutoCommit(SnowflakeConnectionV1.java:384) ~[snowflake-jdbc-3.12.14.jar:3.12.14]
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at org.apache.commons.dbcp2.DelegatingConnection.setAutoCommit(DelegatingConnection.java:537) ~[commons-dbcp2-2.7.0.jar:2.7.0]
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at org.apache.commons.dbcp2.DelegatingConnection.setAutoCommit(DelegatingConnection.java:537) ~[commons-dbcp2-2.7.0.jar:2.7.0]
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.db.jdbc.StreamingJdbcDatabase.lambda$query$0(StreamingJdbcDatabase.java:97) ~[io.airbyte.airbyte-db-lib-0.30.21-alpha.jar:?]
[34msource[0m - 2022-01-12 17:43:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	... 14 more
```

</details>

## Steps to Reproduce
1. launch a more than 8 hour job

## Are you willing to submit a PR?
Yes, but I don't think my job agree to let me do that

**Comment by AM-I-Human** [comment]
Closed by an update 
resolved by https://github.com/airbytehq/airbyte/pull/9567
