### ISSUE TITLE
Evaluate Options for fixing flakiness in K8s acceptance tests

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#9650]
## Tell us about the problem you're trying to solve
Remove K8s integration test flakiness

## Backlog Grooming Notes
- EC2 runners necessary for resource-intensive builds
- AMI cloning makes iteration very slow for debugging this
- Perhaps should be using an actual GKE cluster for testing

- Option: debug AWS runners, AMI reproducibility
- Option: set up a GKE cluster for running acceptance tests

### Acceptance Criteria: 
- Evaluate options for improving this
- Select an option and create an implementation issue

**Comment by davinchia** [comment]
*   transient build error:
    *   [https://github.com/airbytehq/airbyte/runs/5393279792?check\_suite\_focus=true#step:10:34744](https://github.com/airbytehq/airbyte/runs/5393279792?check_suite_focus=true#step:10:34744)
    *   [https://github.com/airbytehq/airbyte/runs/5405902024?check\_suite\_focus=true#step:12:9805](https://github.com/airbytehq/airbyte/runs/5405902024?check_suite_focus=true#step:12:9805)
    *   [https://github.com/airbytehq/airbyte/runs/5406999551?check\_suite\_focus=true#step:12:1438](https://github.com/airbytehq/airbyte/runs/5406999551?check_suite_focus=true#step:12:1438)
    *   [https://github.com/airbytehq/airbyte/runs/5407406217?check\_suite\_focus=true#step:9:2145](https://github.com/airbytehq/airbyte/runs/5407406217?check_suite_focus=true#step:9:2145)

**Comment by davinchia** [comment]
I just came across this while running the tests locally. I was mimicking the kube acceptance tests script. First I ran `SUB_BUILD=PLATFORM  ./gradlew :airbyte-workers:integrationTest` then I ran `KUBE=true SUB_BUILD=PLATFORM USE_EXTERNAL_DEPLOYMENT=true ./gradlew :airbyte-tests:acceptanceTests`.

This resulted in:
```
Unable to receive command from client socket connection from /127.0.0.1:55080 to /127.0.0.1:59585. Discarding connection.
org.gradle.internal.remote.internal.MessageIOException: Could not read message from '/127.0.0.1:59585'.
        at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:94)
        at org.gradle.launcher.daemon.server.SynchronizedDispatchConnection.receive(SynchronizedDispatchConnection.java:70)
        at org.gradle.launcher.daemon.server.DefaultDaemonConnection$1.run(DefaultDaemonConnection.java:73)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Unexpected type tag 108 found.
        at org.gradle.internal.serialize.DefaultSerializerRegistry$TaggedTypeSerializer.read(DefaultSerializerRegistry.java:145)
        at org.gradle.internal.serialize.Serializers$StatefulSerializerAdapter$1.read(Serializers.java:36)
        at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:81)
        ... 7 more
Unable to receive command from client socket connection from /127.0.0.1:55080 to /127.0.0.1:59589. Discarding connection.
org.gradle.internal.remote.internal.MessageIOException: Could not read message from '/127.0.0.1:59589'.
        at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:94)
        at org.gradle.launcher.daemon.server.SynchronizedDispatchConnection.receive(SynchronizedDispatchConnection.java:70)
        at org.gradle.launcher.daemon.server.DefaultDaemonConnection$1.run(DefaultDaemonConnection.java:73)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Unexpected type tag 108 found.
        at org.gradle.internal.serialize.DefaultSerializerRegistry$TaggedTypeSerializer.read(DefaultSerializerRegistry.java:145)
        at org.gradle.internal.serialize.Serializers$StatefulSerializerAdapter$1.read(Serializers.java:36)
        at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:81)
        ... 7 more

> Task :airbyte-tests:acceptanceTests

AcceptanceTests > initializationError FAILED
    java.lang.IllegalStateException: Could not connect to Ryuk at localhost:55080
        at org.testcontainers.utility.ResourceReaper.start(ResourceReaper.java:201)
        at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:205)
        at org.testcontainers.LazyDockerClient.getDockerClient(LazyDockerClient.java:14)
        at org.testcontainers.LazyDockerClient.authConfig(LazyDockerClient.java:12)
        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:310)
        at io.airbyte.test.acceptance.AcceptanceTests.init(AcceptanceTests.java:198)

1 test completed, 1 failed
```
which is an error message I commonly see on the build runners.

However, running `KUBE=true SUB_BUILD=PLATFORM USE_EXTERNAL_DEPLOYMENT=true ./gradlew :airbyte-tests:acceptanceTests` a second time was ok.

My hypothesis here is ports are still being freed up from the previous test command.

**Comment by davinchia** [comment]
Another flaky test I've seen while running `KUBE=true SUB_BUILD=PLATFORM USE_EXTERNAL_DEPLOYMENT=true ./gradlew :airbyte-tests:acceptanceTests` locally

```
AcceptanceTests > testBackpressure() FAILED
    io.airbyte.api.client.invoker.ApiException: java.io.IOException: HTTP/1.1 header parser received no bytes
        at app//io.airbyte.api.client.DestinationApi.deleteDestinationWithHttpInfo(DestinationApi.java:414)
        at app//io.airbyte.api.client.DestinationApi.deleteDestination(DestinationApi.java:386)
        at app//io.airbyte.test.acceptance.AcceptanceTests.deleteDestination(AcceptanceTests.java:1482)
        at app//io.airbyte.test.acceptance.AcceptanceTests.tearDown(AcceptanceTests.java:304)

        Caused by:
        java.io.IOException: HTTP/1.1 header parser received no bytes
            at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:586)
            at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)
            at io.airbyte.api.client.DestinationApi.deleteDestinationWithHttpInfo(DestinationApi.java:399)
            ... 3 more

            Caused by:
            java.io.IOException: HTTP/1.1 header parser received no bytes
                at java.net.http/jdk.internal.net.http.common.Utils.wrapWithExtraDetail(Utils.java:348)
                at java.net.http/jdk.internal.net.http.Http1Response$HeadersReader.onReadError(Http1Response.java:675)
                at java.net.http/jdk.internal.net.http.Http1AsyncReceiver.checkForErrors(Http1AsyncReceiver.java:302)
                at java.net.http/jdk.internal.net.http.Http1AsyncReceiver.flush(Http1AsyncReceiver.java:268)
                at java.net.http/jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:205)
                at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
                at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:230)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
                at java.base/java.lang.Thread.run(Thread.java:833)

                Caused by:
                java.io.EOFException: EOF reached while reading
                    at java.net.http/jdk.internal.net.http.Http1AsyncReceiver$Http1TubeSubscriber.onComplete(Http1AsyncReceiver.java:596)
                    at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadSubscription.signalCompletion(SocketTube.java:640)
                    at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(SocketTube.java:845)
                    at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowTask.run(SocketTube.java:181)
                    at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:230)
                    at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:303)
                    at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:256)
                    at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.signalReadable(SocketTube.java:774)
                    at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent.signalEvent(SocketTube.java:957)
                    at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowEvent.handle(SocketTube.java:253)
                    at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(HttpClientImpl.java:979)
                    at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(HttpClientImpl.java:934)
                    at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
                    at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:934)

24 tests completed, 1 failed, 17 skipped
```

**Comment by davinchia** [comment]
The test `testPortsReintroducedIntoPoolOnlyOnce` failed for me the first two times I ran it. I had to run it 3 times for it to pass. This might explain the port issues we've been seeing.

**Comment by davinchia** [comment]
fyi @jrhizor ^

**Comment by jrhizor** [comment]
fixed in https://github.com/airbytehq/airbyte/pull/11735 @davinchia
