### ISSUE TITLE
Source PostgreSQL to S3 - Failed to convert JSON to Avro

### ISSUE THREAD

**Issue by israel-caylent** [airbytehq/airbyte#9698]
## Environment
- **Airbyte version**:  0.35.0-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: airbyte/source-postgres 0.4.2
- **Destination Connector and version**: airbyte/destination-s3 0.2.5
- **Severity**: High
- **Step where error happened**: Upgrade Airbyte / Run Connection

## Current Behavior
After upgrading the version of Airbyte from `0.34.0` to `0.35.0`, the connection from PostgreSQL to S3 is sending an error like `Failed to convert JSON to Avro`.

## Expected Behavior
After upgrading the version of Airbyte from `0.34.0` to `0.35.0`, the connection from PostgreSQL to S3 should work normally, like the previous versions.

## Logs

<details>
<summary>LOG</summary> 

```

2022-01-20 14:09:55 [44msource[0m > 2022-01-20 14:09:54 [32mINFO[m i.a.i.s.r.AbstractDbSource(lambda$createReadIterator$7):249 - Reading stream order_vendors. Records read: 230000
2022-01-20 14:09:56 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 1219000
2022-01-20 14:09:57 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 1220000
2022-01-20 14:09:57 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 1221000
2022-01-20 14:09:58 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 1222000
2022-01-20 14:09:59 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 1223000
2022-01-20 14:10:00 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 1224000
2022-01-20 14:10:01 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 1225000
2022-01-20 14:10:02 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 1226000
2022-01-20 14:10:03 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 1227000
2022-01-20 14:10:04 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 1228000
2022-01-20 14:10:04 [44msource[0m > 2022-01-20 14:10:03 [32mINFO[m i.a.i.s.r.AbstractDbSource(lambda$createReadIterator$7):249 - Reading stream order_vendors. Records read: 240000
2022-01-20 14:10:04 [44msource[0m > 2022-01-20 14:10:03 [32mINFO[m i.a.i.s.r.StateDecoratingIterator(computeNext):60 - State Report: stream name: AirbyteStreamNameNamespacePair{name='order_vendors', namespace='public'}, original cursor field: null, original cursor null, cursor field: updated_at, new cursor: 2022-01-20T13:19:42Z
2022-01-20 14:10:04 [43mdestination[0m > 2022-01-20 14:10:04 [33mWARN[m i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):58 - Airbyte message consumer: failed.
2022-01-20 14:10:04 [43mdestination[0m > 2022-01-20 14:10:04 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):103 - Failure detected. Aborting upload of stream 'monolith_payments'...
2022-01-20 14:10:05 [43mdestination[0m > 2022-01-20 14:10:05 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):105 - Upload of stream 'monolith_payments' aborted.
2022-01-20 14:10:05 [43mdestination[0m > 2022-01-20 14:10:05 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):103 - Failure detected. Aborting upload of stream 'monolith_price_points'...
2022-01-20 14:10:05 [43mdestination[0m > 2022-01-20 14:10:05 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):105 - Upload of stream 'monolith_price_points' aborted.
2022-01-20 14:10:05 [43mdestination[0m > 2022-01-20 14:10:05 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):103 - Failure detected. Aborting upload of stream 'monolith_product_categories'...
2022-01-20 14:10:06 [43mdestination[0m > 2022-01-20 14:10:06 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):105 - Upload of stream 'monolith_product_categories' aborted.
2022-01-20 14:10:06 [43mdestination[0m > 2022-01-20 14:10:06 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):103 - Failure detected. Aborting upload of stream 'monolith_orders'...
2022-01-20 14:10:06 [43mdestination[0m > 2022-01-20 14:10:06 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):105 - Upload of stream 'monolith_orders' aborted.
2022-01-20 14:10:06 [43mdestination[0m > 2022-01-20 14:10:06 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):103 - Failure detected. Aborting upload of stream 'monolith_price_set_events'...
2022-01-20 14:10:06 [43mdestination[0m > 2022-01-20 14:10:06 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):105 - Upload of stream 'monolith_price_set_events' aborted.
2022-01-20 14:10:06 [43mdestination[0m > 2022-01-20 14:10:06 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):103 - Failure detected. Aborting upload of stream 'monolith_canonical_product_subcategories'...
2022-01-20 14:10:06 [43mdestination[0m > 2022-01-20 14:10:06 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):105 - Upload of stream 'monolith_canonical_product_subcategories' aborted.
2022-01-20 14:10:06 [43mdestination[0m > 2022-01-20 14:10:06 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):103 - Failure detected. Aborting upload of stream 'monolith_canonical_product_types'...
2022-01-20 14:10:07 [43mdestination[0m > 2022-01-20 14:10:07 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):105 - Upload of stream 'monolith_canonical_product_types' aborted.
2022-01-20 14:10:07 [43mdestination[0m > 2022-01-20 14:10:07 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):103 - Failure detected. Aborting upload of stream 'monolith_accountships'...
2022-01-20 14:10:07 [43mdestination[0m > 2022-01-20 14:10:07 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):105 - Upload of stream 'monolith_accountships' aborted.
2022-01-20 14:10:07 [43mdestination[0m > 2022-01-20 14:10:07 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):103 - Failure detected. Aborting upload of stream 'monolith_users'...
2022-01-20 14:10:08 [43mdestination[0m > 2022-01-20 14:10:08 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):105 - Upload of stream 'monolith_users' aborted.
2022-01-20 14:10:08 [43mdestination[0m > 2022-01-20 14:10:08 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):103 - Failure detected. Aborting upload of stream 'monolith_returns'...
2022-01-20 14:10:08 [43mdestination[0m > 2022-01-20 14:10:08 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):105 - Upload of stream 'monolith_returns' aborted.
2022-01-20 14:10:08 [43mdestination[0m > 2022-01-20 14:10:08 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):103 - Failure detected. Aborting upload of stream 'monolith_organizations_products'...
2022-01-20 14:10:08 [43mdestination[0m > 2022-01-20 14:10:08 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):105 - Upload of stream 'monolith_organizations_products' aborted.
2022-01-20 14:10:08 [43mdestination[0m > 2022-01-20 14:10:08 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):103 - Failure detected. Aborting upload of stream 'monolith_vendors'...
2022-01-20 14:10:08 [43mdestination[0m > 2022-01-20 14:10:08 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):105 - Upload of stream 'monolith_vendors' aborted.
2022-01-20 14:10:08 [43mdestination[0m > 2022-01-20 14:10:08 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):103 - Failure detected. Aborting upload of stream 'monolith_organizations'...
2022-01-20 14:10:09 [43mdestination[0m > 2022-01-20 14:10:09 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):105 - Upload of stream 'monolith_organizations' aborted.
2022-01-20 14:10:09 [43mdestination[0m > 2022-01-20 14:10:09 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):103 - Failure detected. Aborting upload of stream 'monolith_products'...
2022-01-20 14:10:09 [43mdestination[0m > 2022-01-20 14:10:09 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):105 - Upload of stream 'monolith_products' aborted.
2022-01-20 14:10:09 [43mdestination[0m > 2022-01-20 14:10:09 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):103 - Failure detected. Aborting upload of stream 'monolith_statuses'...
2022-01-20 14:10:09 [43mdestination[0m > 2022-01-20 14:10:09 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):105 - Upload of stream 'monolith_statuses' aborted.
2022-01-20 14:10:09 [43mdestination[0m > 2022-01-20 14:10:09 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):103 - Failure detected. Aborting upload of stream 'monolith_supplier_invoices'...
2022-01-20 14:10:09 [43mdestination[0m > 2022-01-20 14:10:09 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):105 - Upload of stream 'monolith_supplier_invoices' aborted.
2022-01-20 14:10:09 [43mdestination[0m > 2022-01-20 14:10:09 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):103 - Failure detected. Aborting upload of stream 'monolith_locations'...
2022-01-20 14:10:10 [43mdestination[0m > 2022-01-20 14:10:10 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):105 - Upload of stream 'monolith_locations' aborted.
2022-01-20 14:10:10 [43mdestination[0m > 2022-01-20 14:10:10 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):103 - Failure detected. Aborting upload of stream 'monolith_order_vendors'...
2022-01-20 14:10:11 [43mdestination[0m > 2022-01-20 14:10:11 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):105 - Upload of stream 'monolith_order_vendors' aborted.
2022-01-20 14:10:11 [43mdestination[0m > 2022-01-20 14:10:11 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):103 - Failure detected. Aborting upload of stream 'monolith_order_product_links'...
2022-01-20 14:10:13 [43mdestination[0m > 2022-01-20 14:10:13 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):105 - Upload of stream 'monolith_order_product_links' aborted.
2022-01-20 14:10:13 [43mdestination[0m > 2022-01-20 14:10:13 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):103 - Failure detected. Aborting upload of stream 'monolith_canonical_product_categories'...
2022-01-20 14:10:14 [43mdestination[0m > 2022-01-20 14:10:14 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):105 - Upload of stream 'monolith_canonical_product_categories' aborted.
2022-01-20 14:10:14 [43mdestination[0m > 2022-01-20 14:10:14 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):103 - Failure detected. Aborting upload of stream 'monolith_payment_rules'...
2022-01-20 14:10:14 [43mdestination[0m > 2022-01-20 14:10:14 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):105 - Upload of stream 'monolith_payment_rules' aborted.
2022-01-20 14:10:14 [43mdestination[0m > 2022-01-20 14:10:14 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):103 - Failure detected. Aborting upload of stream 'monolith_addresses'...
2022-01-20 14:10:15 [43mdestination[0m > 2022-01-20 14:10:15 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):105 - Upload of stream 'monolith_addresses' aborted.
2022-01-20 14:10:15 [43mdestination[0m > 2022-01-20 14:10:15 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):103 - Failure detected. Aborting upload of stream 'monolith_linked_accounts'...
2022-01-20 14:10:15 [43mdestination[0m > 2022-01-20 14:10:15 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):105 - Upload of stream 'monolith_linked_accounts' aborted.
2022-01-20 14:10:15 [43mdestination[0m > 2022-01-20 14:10:15 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):103 - Failure detected. Aborting upload of stream 'monolith_original_vendors'...
2022-01-20 14:10:15 [43mdestination[0m > 2022-01-20 14:10:15 [33mWARN[m i.a.i.d.s.w.BaseS3Writer(close):105 - Upload of stream 'monolith_original_vendors' aborted.
2022-01-20 14:10:15 [43mdestination[0m > Exception in thread "main" tech.allegro.schema.json2avro.converter.AvroConversionException: Failed to convert JSON to Avro: Could not evaluate union, field idempotency_key_failures is expected to be one of these: NULL, STRING. If this is a complex type, check if offending field: idempotency_key_failures adheres to schema.
2022-01-20 14:10:15 [43mdestination[0m > 	at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.read(JsonGenericRecordReader.java:129)
2022-01-20 14:10:15 [43mdestination[0m > 	at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.read(JsonGenericRecordReader.java:118)
2022-01-20 14:10:15 [43mdestination[0m > 	at tech.allegro.schema.json2avro.converter.JsonAvroConverter.convertToGenericDataRecord(JsonAvroConverter.java:95)
2022-01-20 14:10:15 [43mdestination[0m > 	at io.airbyte.integrations.destination.s3.avro.AvroRecordFactory.getAvroRecord(AvroRecordFactory.java:39)
2022-01-20 14:10:15 [43mdestination[0m > 	at io.airbyte.integrations.destination.s3.parquet.S3ParquetWriter.write(S3ParquetWriter.java:108)
2022-01-20 14:10:15 [43mdestination[0m > 	at io.airbyte.integrations.destination.s3.S3Consumer.acceptTracked(S3Consumer.java:83)
2022-01-20 14:10:15 [43mdestination[0m > 	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.accept(FailureTrackingAirbyteMessageConsumer.java:46)
2022-01-20 14:10:15 [43mdestination[0m > 	at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:147)
2022-01-20 14:10:15 [43mdestination[0m > 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:128)
2022-01-20 14:10:15 [43mdestination[0m > 	at io.airbyte.integrations.destination.s3.S3Destination.main(S3Destination.java:30)
2022-01-20 14:10:15 [43mdestination[0m > Caused by: org.apache.avro.AvroTypeException: Could not evaluate union, field idempotency_key_failures is expected to be one of these: NULL, STRING. If this is a complex type, check if offending field: idempotency_key_failures adheres to schema.
2022-01-20 14:10:15 [43mdestination[0m > 	at tech.allegro.schema.json2avro.converter.AvroTypeExceptions.unionException(AvroTypeExceptions.java:28)
2022-01-20 14:10:15 [43mdestination[0m > 	at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.readUnion(JsonGenericRecordReader.java:289)
2022-01-20 14:10:15 [43mdestination[0m > 	at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.read(JsonGenericRecordReader.java:196)
2022-01-20 14:10:15 [43mdestination[0m > 	at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.read(JsonGenericRecordReader.java:170)
2022-01-20 14:10:15 [43mdestination[0m > 	at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.lambda$readRecord$0(JsonGenericRecordReader.java:152)
2022-01-20 14:10:15 [43mdestination[0m > 	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
2022-01-20 14:10:15 [43mdestination[0m > 	at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.readRecord(JsonGenericRecordReader.java:141)
2022-01-20 14:10:15 [43mdestination[0m > 	at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.read(JsonGenericRecordReader.java:127)
2022-01-20 14:10:15 [43mdestination[0m > 	... 9 more
2022-01-20 14:11:16 [33mWARN[m i.a.c.i.LineGobbler(voidCall):86 - airbyte-source gobbler IOException: Stream closed. Typically happens when cancelling a job.
2022-01-20 14:11:16 [1;31mERROR[m i.a.w.DefaultReplicationWorker(run):141 - Sync worker failed.
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.io.IOException: Broken pipe
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:134) ~[io.airbyte-airbyte-workers-0.35.6-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:52) ~[io.airbyte-airbyte-workers-0.35.6-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:174) ~[io.airbyte-airbyte-workers-0.35.6-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
	Suppressed: io.airbyte.workers.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteSource.close(DefaultAirbyteSource.java:136) ~[io.airbyte-airbyte-workers-0.35.6-alpha.jar:?]
		at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:118) ~[io.airbyte-airbyte-workers-0.35.6-alpha.jar:?]
		at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:52) ~[io.airbyte-airbyte-workers-0.35.6-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:174) ~[io.airbyte-airbyte-workers-0.35.6-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:833) [?:?]
	Suppressed: java.io.IOException: Stream closed
		at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:445) ~[?:?]
		at java.io.OutputStream.write(OutputStream.java:162) ~[?:?]
		at java.io.BufferedOutputStream.write(BufferedOutputStream.java:123) ~[?:?]
		at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234) ~[?:?]
		at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:313) ~[?:?]
		at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:318) ~[?:?]
		at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:160) ~[?:?]
		at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:248) ~[?:?]
		at java.io.BufferedWriter.flush(BufferedWriter.java:257) ~[?:?]
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.notifyEndOfStream(DefaultAirbyteDestination.java:98) ~[io.airbyte-airbyte-workers-0.35.6-alpha.jar:?]
		at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.close(DefaultAirbyteDestination.java:111) ~[io.airbyte-airbyte-workers-0.35.6-alpha.jar:?]
		at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:118) ~[io.airbyte-airbyte-workers-0.35.6-alpha.jar:?]
		at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:52) ~[io.airbyte-airbyte-workers-0.35.6-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:174) ~[io.airbyte-airbyte-workers-0.35.6-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: java.io.IOException: Broken pipe
	at io.airbyte.workers.DefaultReplicationWorker.lambda$getReplicationRunnable$3(DefaultReplicationWorker.java:265) ~[io.airbyte-airbyte-workers-0.35.6-alpha.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
Caused by: java.io.IOException: Broken pipe
	at java.io.FileOutputStream.writeBytes(Native Method) ~[?:?]
	at java.io.FileOutputStream.write(FileOutputStream.java:349) ~[?:?]
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:123) ~[?:?]
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234) ~[?:?]
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:304) ~[?:?]
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282) ~[?:?]
	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:132) ~[?:?]
	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:205) ~[?:?]
	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:120) ~[?:?]
	at java.io.BufferedWriter.write(BufferedWriter.java:233) ~[?:?]
	at java.io.Writer.write(Writer.java:249) ~[?:?]
	at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.accept(DefaultAirbyteDestination.java:90) ~[io.airbyte-airbyte-workers-0.35.6-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.lambda$getReplicationRunnable$3(DefaultReplicationWorker.java:247) ~[io.airbyte-airbyte-workers-0.35.6-alpha.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
2022-01-20 14:11:16 [32mINFO[m i.a.w.DefaultReplicationWorker(run):200 - sync summary: io.airbyte.config.ReplicationAttemptSummary@5bf8946[status=failed,recordsSynced=1228939,bytesSynced=1195126101,startTime=1642687088573,endTime=1642687876157,totalStats=io.airbyte.config.SyncStats@27b1324f[recordsEmitted=1228939,bytesEmitted=1195126101,stateMessagesEmitted=9,recordsCommitted=0],streamStats=[io.airbyte.config.StreamSyncStats@629cc5b1[streamName=monolith_orders,stats=io.airbyte.config.SyncStats@396de2f1[recordsEmitted=256,bytesEmitted=537996,stateMessagesEmitted=<null>,recordsCommitted=<null>]], io.airbyte.config.StreamSyncStats@4061b923[streamName=monolith_canonical_product_subcategories,stats=io.airbyte.config.SyncStats@6e6cd82a[recordsEmitted=1,bytesEmitted=103,stateMessagesEmitted=<null>,recordsCommitted=<null>]], io.airbyte.config.StreamSyncStats@6a59291b[streamName=monolith_locations,stats=io.airbyte.config.SyncStats@3cf524cb[recordsEmitted=31278,bytesEmitted=6915251,stateMessagesEmitted=<null>,recordsCommitted=<null>]], io.airbyte.config.StreamSyncStats@71102ad7[streamName=monolith_canonical_product_categories,stats=io.airbyte.config.SyncStats@79b50157[recordsEmitted=1,bytesEmitted=103,stateMessagesEmitted=<null>,recordsCommitted=<null>]], io.airbyte.config.StreamSyncStats@5a87ee8b[streamName=monolith_order_product_links,stats=io.airbyte.config.SyncStats@4fc14a6c[recordsEmitted=782983,bytesEmitted=787916260,stateMessagesEmitted=<null>,recordsCommitted=<null>]], io.airbyte.config.StreamSyncStats@3f7787d1[streamName=monolith_order_vendors,stats=io.airbyte.config.SyncStats@6e1986d1[recordsEmitted=240431,bytesEmitted=334787117,stateMessagesEmitted=<null>,recordsCommitted=<null>]], io.airbyte.config.StreamSyncStats@b8fde2f[streamName=monolith_canonical_product_types,stats=io.airbyte.config.SyncStats@4ed87718[recordsEmitted=1,bytesEmitted=103,stateMessagesEmitted=<null>,recordsCommitted=<null>]], io.airbyte.config.StreamSyncStats@4d12381d[streamName=monolith_addresses,stats=io.airbyte.config.SyncStats@6f1f0060[recordsEmitted=140296,bytesEmitted=49832246,stateMessagesEmitted=<null>,recordsCommitted=<null>]], io.airbyte.config.StreamSyncStats@1a94c50a[streamName=monolith_linked_accounts,stats=io.airbyte.config.SyncStats@177911f7[recordsEmitted=29553,bytesEmitted=14332033,stateMessagesEmitted=<null>,recordsCommitted=<null>]], io.airbyte.config.StreamSyncStats@4bf701d5[streamName=monolith_accountships,stats=io.airbyte.config.SyncStats@5cfc04cb[recordsEmitted=4139,bytesEmitted=804889,stateMessagesEmitted=<null>,recordsCommitted=<null>]]]]
2022-01-20 14:11:16 [32mINFO[m i.a.w.DefaultReplicationWorker(run):207 - Source output at least one state message
2022-01-20 14:11:16 [33mWARN[m i.a.w.DefaultReplicationWorker(run):217 - State capture: No new state, falling back on input state: io.airbyte.config.State@60fc36cb[state={}]
2022-01-20 14:11:16 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):144 - Stopping cancellation check scheduling...


```

</details>

## Steps to Reproduce
1. Upgrade Airbyte to `v0.35.0` or later.
2. Set a connection between PostgreSQL and S3, parquet file format.
3. Define a table in the connection with a column as an `array`.

## Are you willing to submit a PR?
No.

## Additional comments
- I had sent a message into the slack channel `#troubleshooting`, but I have not received a useful response to solve the problem.
- The problem that I'm having is similar to this issue here (#5609), but for the PostgreSQL DB.
- This error is only happening with one table, the specific column from the logs that are presenting the error is a `text` type with `arrays`.

**Comment by tuliren** [comment]
> This error is only happening with one table, the specific column from the logs that are presenting the error is a `text` type with `arrays`.

@israel-caylent, just to clarify this, by `a text type with arrays`, you mean the offending column is typed as `text[]`, right?

Could you paste the full log? Specifically near the beginning of the sync, there should be some logs about: 1) the original type and Airbyte internal type of each column (e.g. `Table users column name (CHAR[50]) -> Json type string`), and 2) the Avro schema to be used by the destination. Those logs will be very helpful in debugging this issue.

Thank you.

**Comment by klaussilveira** [comment]
Same thing happens on PostgreSQL to Snowflake on 0.35.32-alpha.

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 365 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.
