### ISSUE TITLE
🐛 Source MSSQL: IllegalArgumentException: nanos > 999999999 or < 0

### ISSUE THREAD

**Issue by PS-istarostenko** [airbytehq/airbyte#9890]
Trying to sync quite a large table from SQLServer to Snowflake with S3 stage.
After fetching the records for about an hour and a half I keep getting the same error:
`Exception in thread "main" java.lang.IllegalArgumentException: nanos > 999999999 or < 0`.
It's the first error in the logs. It's followed by:
`ERROR i.a.w.DefaultReplicationWorker(run):158 - Sync worker failed.
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Source process exited with non-zero exit code 1` and followed by `Caused by: java.io.IOException: Stream closed`.

## Environment
- **Airbyte version**:  0.35.12-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: docker-compose
- **Source Connector and version**: MSSQL 0.3.14
- **Destination Connector and version**: Snowflake 0.1.6
- **Severity**: High
- **Step where error happened**: Sync job

## Current Behavior
Getting the error

## Expected Behavior
Being able to sync the data

## Logs
Full logs attached
[logs-9312.txt](https://github.com/airbytehq/airbyte/files/7962743/logs-9312.txt)

```

2022-01-28 22:48:27 [44msource[0m > Exception in thread "main" java.lang.IllegalArgumentException: nanos > 999999999 or < 0
2022-01-28 22:48:27 [44msource[0m > 	at java.sql/java.sql.Timestamp.setNanos(Timestamp.java:336)
2022-01-28 22:48:27 [44msource[0m > 	at com.microsoft.sqlserver.jdbc.DDC.convertTemporalToObject(DDC.java:1298)
2022-01-28 22:48:27 [44msource[0m > 	at com.microsoft.sqlserver.jdbc.DDC.convertTemporalToObject(DDC.java:897)
2022-01-28 22:48:27 [44msource[0m > 	at com.microsoft.sqlserver.jdbc.TDSReader.readDateTime(IOBuffer.java:6965)
2022-01-28 22:48:27 [44msource[0m > 	at com.microsoft.sqlserver.jdbc.ServerDTVImpl.getValue(dtv.java:3843)
2022-01-28 22:48:27 [44msource[0m > 	at com.microsoft.sqlserver.jdbc.DTV.getValue(dtv.java:247)
2022-01-28 22:48:27 [44msource[0m > 	at com.microsoft.sqlserver.jdbc.Column.getValue(Column.java:190)
2022-01-28 22:48:27 [44msource[0m > 	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.getValue(SQLServerResultSet.java:2054)
2022-01-28 22:48:27 [44msource[0m > 	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.getValue(SQLServerResultSet.java:2040)
2022-01-28 22:48:27 [44msource[0m > 	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.getObject(SQLServerResultSet.java:2372)
2022-01-28 22:48:27 [44msource[0m > 	at org.apache.commons.dbcp2.DelegatingResultSet.getObject(DelegatingResultSet.java:733)
2022-01-28 22:48:27 [44msource[0m > 	at org.apache.commons.dbcp2.DelegatingResultSet.getObject(DelegatingResultSet.java:733)
2022-01-28 22:48:27 [44msource[0m > 	at io.airbyte.db.jdbc.AbstractJdbcCompatibleSourceOperations.rowToJson(AbstractJdbcCompatibleSourceOperations.java:42)
2022-01-28 22:48:27 [44msource[0m > 	at io.airbyte.db.jdbc.AbstractJdbcCompatibleSourceOperations.rowToJson(AbstractJdbcCompatibleSourceOperations.java:30)
2022-01-28 22:48:27 [44msource[0m > 	at io.airbyte.db.jdbc.JdbcDatabase$1.tryAdvance(JdbcDatabase.java:77)
2022-01-28 22:48:27 [44msource[0m > 	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
2022-01-28 22:48:27 [44msource[0m > 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
2022-01-28 22:48:27 [44msource[0m > 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
2022-01-28 22:48:27 [44msource[0m > 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
2022-01-28 22:48:27 [44msource[0m > 	at io.airbyte.commons.util.LazyAutoCloseableIterator.computeNext(LazyAutoCloseableIterator.java:42)
2022-01-28 22:48:27 [44msource[0m > 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
2022-01-28 22:48:27 [44msource[0m > 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
2022-01-28 22:48:27 [44msource[0m > 	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:46)
2022-01-28 22:48:27 [44msource[0m > 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
2022-01-28 22:48:27 [44msource[0m > 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
2022-01-28 22:48:27 [44msource[0m > 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
2022-01-28 22:48:27 [44msource[0m > 	at io.airbyte.integrations.source.relationaldb.StateDecoratingIterator.computeNext(StateDecoratingIterator.java:48)
2022-01-28 22:48:27 [44msource[0m > 	at io.airbyte.integrations.source.relationaldb.StateDecoratingIterator.computeNext(StateDecoratingIterator.java:18)
2022-01-28 22:48:27 [44msource[0m > 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
2022-01-28 22:48:27 [44msource[0m > 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
2022-01-28 22:48:27 [44msource[0m > 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
2022-01-28 22:48:27 [44msource[0m > 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
2022-01-28 22:48:27 [44msource[0m > 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
2022-01-28 22:48:27 [44msource[0m > 	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:46)
2022-01-28 22:48:27 [44msource[0m > 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
2022-01-28 22:48:27 [44msource[0m > 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
2022-01-28 22:48:27 [44msource[0m > 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
2022-01-28 22:48:27 [44msource[0m > 	at io.airbyte.commons.util.CompositeIterator.computeNext(CompositeIterator.java:63)
2022-01-28 22:48:27 [44msource[0m > 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
2022-01-28 22:48:27 [44msource[0m > 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
2022-01-28 22:48:27 [44msource[0m > 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
2022-01-28 22:48:27 [44msource[0m > 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
2022-01-28 22:48:27 [44msource[0m > 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
2022-01-28 22:48:27 [44msource[0m > 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
2022-01-28 22:48:27 [44msource[0m > 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
2022-01-28 22:48:27 [44msource[0m > 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
2022-01-28 22:48:27 [44msource[0m > 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
2022-01-28 22:48:27 [44msource[0m > 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:119)
2022-01-28 22:48:27 [44msource[0m > 	at io.airbyte.integrations.source.mssql.MssqlSource.main(MssqlSource.java:443)
2022-01-28 22:48:27 [43mdestination[0m > 2022-01-28 22:48:27 [32mINFO[m i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):60 - Airbyte message consumer: succeeded.
2022-01-28 22:48:27 [43mdestination[0m > 2022-01-28 22:48:27 [32mINFO[m i.a.i.d.b.BufferedStreamConsumer(close):201 - executing on success close procedure.

```

</details>

## Are you willing to submit a PR?
No

**Comment by alafanechere** [comment]
Hi @PS-istarostenko, could you please share the schema of your table `MyTable`? It looks like the JDBC driver fails at deserializing a timestamp value.

**Comment by PS-istarostenko** [comment]
Hi @alafanechere 
The table has 50 columns. Including 6 columns with `smalldatetime(4)` type and 2 with `datetime(8)` type.
Sync method is "Incremental | Deduped + History" with the cursor field also of the `smalldatetime(4)` type.

**Comment by xiaohansong** [comment]
I do not think there's any issue on airbyte side. It looks like JDBC cannot parse out a given datetime column correctly; but without the culprit data I cannot reproduce this. 

I would recommend to upgrade our dependency on mssql (currently we are using 10.2, but the latest is 12.4) if the problem persists or we see other similar tickets coming up.

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
