### ISSUE TITLE
Destination Rockset: failed acceptance tests

### ISSUE THREAD

**Issue by yurii-bidiuk** [airbytehq/airbyte#9961]
## Current Behavior
Tests failed with an exception
```
RocksetDestinationAcceptanceTest > testEntrypointEnvVar() FAILED
    java.lang.RuntimeException: java.nio.file.NoSuchFileException: secrets/config.json
        at io.airbyte.commons.io.IOs.readFile(IOs.java:74)
        at io.airbyte.integrations.destination.rockset.RocksetDestinationAcceptanceTest.getConfig(RocksetDestinationAcceptanceTest.java:54)
        at io.airbyte.integrations.destination.rockset.RocksetDestinationAcceptanceTest.tearDown(RocksetDestinationAcceptanceTest.java:135)

        Caused by:
        java.nio.file.NoSuchFileException: secrets/config.json
            at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
            at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
            at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
            at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
            at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
            at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
            at java.base/java.nio.file.Files.readAllBytes(Files.java:3288)
            at java.base/java.nio.file.Files.readString(Files.java:3366)
            at io.airbyte.commons.io.IOs.readFile(IOs.java:72)
            ... 2 more
```

## Expected Behavior
*Tell us what should happen.*

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

RocksetDestinationAcceptanceTest > testEntrypointEnvVar() FAILED
    java.lang.RuntimeException: java.nio.file.NoSuchFileException: secrets/config.json
        at io.airbyte.commons.io.IOs.readFile(IOs.java:74)
        at io.airbyte.integrations.destination.rockset.RocksetDestinationAcceptanceTest.getConfig(RocksetDestinationAcceptanceTest.java:54)
        at io.airbyte.integrations.destination.rockset.RocksetDestinationAcceptanceTest.tearDown(RocksetDestinationAcceptanceTest.java:135)

        Caused by:
        java.nio.file.NoSuchFileException: secrets/config.json
            at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
            at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
            at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
            at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
            at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
            at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
            at java.base/java.nio.file.Files.readAllBytes(Files.java:3288)
            at java.base/java.nio.file.Files.readString(Files.java:3366)
            at io.airbyte.commons.io.IOs.readFile(IOs.java:72)
            ... 2 more

```

</details>

## Steps to Reproduce
1. Run tests

**Comment by yurii-bidiuk** [comment]
Added config.json to Google Secret manager
