### ISSUE TITLE
Destination Mongodb strict encrypt: failed acceptance tests

### ISSUE THREAD

**Issue by yurii-bidiuk** [airbytehq/airbyte#9962]
## Current Behavior
Tests are failed with error:
```
MongodbDestinationStrictEncryptAcceptanceTest > testEntrypointEnvVar() FAILED
    com.mongodb.MongoNotPrimaryException: Command failed with error 10107 (NotWritablePrimary): 'not primary' on server cluster0-shard-00-02.iqgf8.mongodb.net:27017. The full response is ***"topologyVersion": ***"processId": ***"$oid": "61f3f7b99f1f748cd857024a"***, "counter": 3***, "operationTime": ***"$timestamp": ***"t": 1643668475, "i": 1***, "ok": 0.0, "errmsg": "not primary", "code": 10107, "codeName": "NotWritablePrimary", "$clusterTime": ***"clusterTime": ***"$timestamp": ***"t": 1643668475, "i": 1***, "signature": ***"hash": ***"$binary": ***"base64": "XqMo8RQOxVzqcM/riuHfGZqs8aU=", "subType": "00"***, "keyId": 7025217558697476099***
        at app//com.mongodb.internal.connection.ProtocolHelper.createSpecialException(ProtocolHelper.java:265)
        at app//com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:191)
        at app//com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:398)
        at app//com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:319)
        at app//com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:114)
        at app//com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:601)
        at app//com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:81)
        at app//com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:249)
        at app//com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:214)
        at app//com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:123)
        at app//com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:113)
        at app//com.mongodb.internal.operation.CommandOperationHelper.executeWriteCommand(CommandOperationHelper.java:357)
        at app//com.mongodb.internal.operation.CommandOperationHelper.executeWriteCommand(CommandOperationHelper.java:347)
        at app//com.mongodb.internal.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:269)
        at app//com.mongodb.internal.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:262)
        at app//com.mongodb.internal.operation.DropCollectionOperation$1.call(DropCollectionOperation.java:94)
        at app//com.mongodb.internal.operation.DropCollectionOperation$1.call(DropCollectionOperation.java:90)
        at app//com.mongodb.internal.operation.OperationHelper.withConnectionSource(OperationHelper.java:650)
        at app//com.mongodb.internal.operation.OperationHelper.withConnection(OperationHelper.java:612)
        at app//com.mongodb.internal.operation.DropCollectionOperation.execute(DropCollectionOperation.java:90)
        at app//com.mongodb.internal.operation.DropCollectionOperation.execute(DropCollectionOperation.java:53)
        at app//com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:205)
        at app//com.mongodb.client.internal.MongoCollectionImpl.executeDrop(MongoCollectionImpl.java:797)
        at app//com.mongodb.client.internal.MongoCollectionImpl.drop(MongoCollectionImpl.java:787)
        at app//io.airbyte.integrations.destination.mongodb.MongodbDestinationStrictEncryptAcceptanceTest.tearDown(MongodbDestinationStrictEncryptAcceptanceTest.java:118)
```

## Expected Behavior
*Tell us what should happen.*

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1.Run tests

**Comment by pcsoni89** [comment]
There was probably an overload of the main cluster - cluster0-shard-00-02, it rebooted or something like that, and the first cluster instead of cluster0-shard-00-02 was cluster0-shard-00-01. After updating credentials in secret Json file the tests is works well.
