### ISSUE TITLE
🐛 Source MongoDB: source incremental sync not working

### ISSUE THREAD

**Issue by zackliston** [airbytehq/airbyte#9986]
## Environment
- **Airbyte version**:  0.35.15-alpha
- **OS Version / Instance**: Kubernetes via Kustomize
- **Deployment**: Kubernetes
- **Source Connector and version**: airbyte/source-mongodb-v2 0.1.11
- **Destination Connector and version**: 0.3.24 airbyte/destination-redshift
- **Severity**: High
- **Step where error happened**: Sync job

## Current Behavior
When syncing from MongoDB to Redshift a full sync works as expected. However, a incremental sync throws this error:

```
2022-02-02 00:12:13 source > Exception in thread "main" java.util.NoSuchElementException: No value present
2022-02-02 00:12:13 source > 	at java.base/java.util.Optional.orElseThrow(Optional.java:377)
2022-02-02 00:12:13 source > 	at io.airbyte.integrations.source.relationaldb.AbstractDbSource.getIncrementalStream(AbstractDbSource.java:268)
2022-02-02 00:12:13 source > 	at io.airbyte.integrations.source.relationaldb.AbstractDbSource.createReadIterator(AbstractDbSource.java:220)
2022-02-02 00:12:13 source > 	at io.airbyte.integrations.source.relationaldb.AbstractDbSource.getSelectedIterators(AbstractDbSource.java:185)
2022-02-02 00:12:13 source > 	at io.airbyte.integrations.source.relationaldb.AbstractDbSource.getIncrementalIterators(AbstractDbSource.java:156)
2022-02-02 00:12:13 source > 	at io.airbyte.integrations.source.relationaldb.AbstractDbSource.read(AbstractDbSource.java:113)
2022-02-02 00:12:13 source > 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:117)
2022-02-02 00:12:13 source > 	at io.airbyte.integrations.source.mongodb.MongoDbSource.main(MongoDbSource.java:65)
```
Which results in the job not finishing

## Expected Behavior
Incremental sync should complete with no errors.

## Logs
[logs-206.txt](https://github.com/airbytehq/airbyte/files/7982726/logs-206.txt)

## Steps to Reproduce
1. Setup connection from mongoDB to Redshift with Incremental Sync + de-duped history
2. Set the cursor to be a field that is a number (epoch)
3. Set the primary key to be an string ObjectId
4. Perform a full sync - this should succeed
5. Perform a incremental sync. This will fail

## Are you willing to submit a PR?
Happy to provide more detail, unable to submit PR.

**Comment by alafanechere** [comment]
Hi @zackliston could you please try to set a different cursor field, I'm wondering if it could be related to it's type.

**Comment by zackliston** [comment]
@alafanechere I reset and resync-ed all collections with the most recent version and this appears to no longer be an issue. I do however see this line (the original name was `t`) so I imagine this must have been fixed in a recent version. This field does not have a consistent type.

 Thanks for looking into it, I'll go ahead and close.

<img width="1186" alt="Screen Shot 2022-02-02 at 11 18 06 PM" src="https://user-images.githubusercontent.com/2746752/152280650-865c9cee-5b3c-4797-b715-897faee5c4fd.png">
